### ISSUE TITLE
Incorrect steps for AD FS preauthentication flow 

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/windowsserverdocs#1001]
"Web Application Proxy redirects the HTTPS request to the AD FS server with URL encoded parameters, including the resource URL and the appRealm (a relying party identifier). " 

This is not how it works.  The WAP proxies the request to the ADFS server.  Hence the "proxy" in the name.  If it redirected the client, the client would have to be able to connect to the ADFS servers, which are not exposed to the internet in about 100% of the cases I've deployed or seen.

"If the edge token is valid, Web Application Proxy forwards the HTTPS request to the published web application using either HTTP or HTTPS. "

Again, incorrect.  It proxies the request.  Half the point of having WAPs is so the STS and target application are not exposed directly to the internet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1228501-446f-0b3a-0963-b15c375e50b8
* Version Independent ID: 6b068962-48e8-45a8-94ab-d3d29a780aaa
* Content: [Publishing Applications using AD FS Preauthentication](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/web-application-proxy/publishing-applications-using-ad-fs-preauthentication)
* Content Source: [WindowsServerDocs/remote/remote-access/web-application-proxy/Publishing-Applications-using-AD-FS-Preauthentication.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/web-application-proxy/Publishing-Applications-using-AD-FS-Preauthentication.md)
* Product: **windows-server-threshold**
* GitHub Login: @kgremban

**Comment by illfated** [comment]
I assume this is a semantics issue. Would you be so kind as to suggest the specific sentences in a rephrased form?

(I admit that I am not overly keen on using the noun "proxy" transformed to a verb, as it is described as non-standard English most places.)

**Comment by IngridAtMicrosoft** [comment]
#please-close
