### ISSUE TITLE
Additional Options?

### ISSUE THREAD

**Issue by tgmoorhead** [MicrosoftDocs/windowsserverdocs#1004]
Additional options were referenced as "see below," but were not mentioned below.  Looking for more on local drive redirection and local resources.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e13574b-1a5b-f6d9-2cd5-c3e298324ebc
* Version Independent ID: 8824e1fa-8ac3-a68f-202e-2366c1ecbdd7
* Content: [Get started with Remote Desktop on Windows](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windows)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windows.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windows.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by lizap** [comment]
Thanks. We've created a work item to track adding this information.

**Comment by mismamente** [comment]
Cannot connect to another port. 
My company's VPN redirects my work computer to 127.0.0.2:3390 but with the UWP I can't connect. With the legacy remote desktop app I can connect without any problem.
It's a must to be able to connect to other ports.

**Comment by aiwaxxx** [comment]
How to set color depth to 15-bit ?

**Comment by narsi424** [comment]
How to launch the remote desktop app using Windows+Run command? (similar to 'mstsc' run command)
