### ISSUE TITLE
Is the entry point configuration example for the script option correct?

### ISSUE THREAD

**Issue by leeprtc** [MicrosoftDocs/windowsserverdocs#1007]
The example for the script option has all 3 option specified in a configuration - localhost, inventory, and script. Is this correct? Should it just only have the script option in a configuration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9473ecb6-7d1d-7b0f-44d3-58690fc21020
* Version Independent ID: 1b922f56-101e-e217-0e4e-8bb8c386f7e5
* Content: [Control your tool's visibility in a solution](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/extend/guides/dynamic-tool-display)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/extend/guides/dynamic-tool-display.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/extend/guides/dynamic-tool-display.md)
* Product: **windows-server-threshold**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by jwwool** [comment]
Adding the owner of this content, @nwashburn-ms
