### ISSUE TITLE
No support for DHCP Option 118

### ISSUE THREAD

**Issue by tdimli** [MicrosoftDocs/windowsserverdocs#1012]
This document contains inaccurate information re DHCP Option 118: There is currently no support for DHCP Option 118.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d187c10-06ed-8821-fa27-4018404dd200
* Version Independent ID: 2bcbca3c-17f3-7115-2c77-6e17af63eeb7
* Content: [DHCP Subnet Selection Options](https://docs.microsoft.com/en-us/windows-server/networking/technologies/dhcp/dhcp-subnet-options#feedback)
* Content Source: [WindowsServerDocs/networking/technologies/dhcp/dhcp-subnet-options.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/dhcp/dhcp-subnet-options.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@tdimli, Thank you for pointing out the inaccuracies.  I will get the document updated.

**Comment by shortpatti** [comment]
DHCP Option 118 was not part of WS 2016 release.

**Comment by wasytb** [comment]
Review the spanish version of the content and the URL https://docs.microsoft.com/en-us/windows-server/networking/technologies/dhcp/what-s-new-in-dhcp. They are still mentioning option 118 as available
