### ISSUE TITLE
OpenID Connect id_token claims tracing through fiddler

### ISSUE THREAD

**Issue by sbsharma35** [MicrosoftDocs/windowsserverdocs#1013]
This document is very informative and very well created. Also, if you could please share any documentation for tracing the https requests and response using Fiddler along with id_token claims during openID Connect based SSO configurations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bbfe936-5ada-6a20-bba0-6b7f910dd8a1
* Version Independent ID: 7bd39af2-e6c3-8096-1995-c05422bf9582
* Content: [AD FS Troubleshooting - Fiddler - WS-Federation](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-fiddler-ws-fed#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-fiddler-ws-fed.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-fiddler-ws-fed.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by lizap** [comment]
Thanks for the feedback! I'll share your request with the AD writers and see what they have/what they can get. Thanks!
