### ISSUE TITLE
where are pictures?

### ISSUE THREAD

**Issue by VitasLoWang** [MicrosoftDocs/windowsserverdocs#1017]
why don't you includes pictures of DNS console so it's clear how it looks in the GUI??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7d51b04-ef68-c5dc-edc9-30d7242c74fa
* Version Independent ID: ad25fe01-0042-11dc-837c-8beb66c2d7f8
* Content: [Use DNS Policy for Split-Brain DNS in Active Directory](https://docs.microsoft.com/en-us/windows-server/networking/dns/deploy/dns-sb-with-ad)
* Content Source: [WindowsServerDocs/networking/dns/deploy/dns-sb-with-ad.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/dns/deploy/dns-sb-with-ad.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by doctordns** [comment]
In which document?

**Comment by shortpatti** [comment]
@VitasLoWang, thank you for your comment.  Can I ask what you're trying to do?  In other words, what is the scenario?  Are you trying to set up split-brain DNS in AD?

**Comment by VitasLoWang** [comment]
I was learning for an exam

**Comment by shortpatti** [comment]
@VitasLoWang, I'll work on adding the necessary console images for the scenarios.
