### ISSUE TITLE
windowsserverdocs/WindowsServerDocs/manage/windows-admin-center/plan/installation-options.md needs improving

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/windowsserverdocs#1018]
This document does not explain that the default _installation_ of WAC (version 1806)fails on a just-installed server 2019 as the default it to use IE. IE does not work with WAC.

This document should include the browsers that work and are supported.

I also think the installation program should be a tad smarter and tell the user at installation time that his/her installation is borked until they load Chrome, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29295bfb-4d36-07cc-4e47-29835aa835ec
* Version Independent ID: 618170e7-cc5c-2ff8-af3b-701c1b26ed11
* Content: [What type of installation is right for you](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/plan/installation-options#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/plan/installation-options.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/plan/installation-options.md)
* Product: **windows-server-threshold**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by lizap** [comment]
Spurred by both this comment and your proposed change, the team updated the article to make this point clear. Thanks!
