### ISSUE TITLE
Created module never used

### ISSUE THREAD

**Issue by leeprtc** [MicrosoftDocs/windowsserverdocs#1022]
The steps on this page walks one through to creating a new module. However, because app-routing.module.ts was never updated, the newly created module cannot be access.

Add the instructions to either update app-routing.module.ts or remove the steps for creating new module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 229f7b83-a501-f0b9-6b3b-bffc84b04554
* Version Independent ID: 7d5f608f-bc6d-6ab6-c186-83dda2ae922d
* Content: [Prepare your development environment](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/extend/prepare-development-environment)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/extend/prepare-development-environment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/extend/prepare-development-environment.md)
* Product: **windows-server-threshold**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by nwashburn-ms** [comment]
Hi @leeptrc, we're planning some updates to this page soon, I'll make sure your comment is addressed in the updates!  Thanks!
