### ISSUE TITLE
Wrong statement

### ISSUE THREAD

**Issue by SebastienAime** [MicrosoftDocs/windowsserverdocs#1024]
This statement: "The Alternate login ID feature is only available for federated environments with AD FS deployed" is not correct.
At this time, PTA also fully support AlternateID.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02d8b61-29e8-c0a7-b3b2-79be7212a91c
* Version Independent ID: b4346d87-0727-c7fe-7896-7fd79098825c
* Content: [Configuring Alternate Login ID](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configuring-alternate-login-id#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configuring-Alternate-Login-ID.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configuring-Alternate-Login-ID.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by dorenack** [comment]
What about PHS?

**Comment by illfated** [comment]
Resolved in PR #1939 , commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/d0a0ddc47d2b28608d866261ef303ba5af079193 .

#please-close
