### ISSUE TITLE
Inaccurate Exchange prerequisites.

### ISSUE THREAD

**Issue by SebastienAime** [MicrosoftDocs/windowsserverdocs#1026]
You mention in a big blue box "For the best end-user experience, Microsoft recommends using Hybrid Modern Authentication."
Few lines later you mention this prerequisite for Exchange OnPrem "Exchange on-premises should have Modern Authentication turned ON."

From my understanding it should be "Exchange on-premises should have -HYBRID- Modern Authentication turned ON."

This is kind of different because it implies to understand the concept of Hybrid Modern Auth explained a bit here:
 https://support.office.com/en-us/article/Hybrid-Modern-Authentication-overview-and-prerequisites-for-using-it-with-on-premises-Skype-for-Business-and-Exchange-servers-ef753b32-7251-4c9e-b442-1a5aec14e58d

And furthermore to apply this configuration:
https://support.office.com/en-us/article/how-to-configure-exchange-server-on-premises-to-use-hybrid-modern-authentication-cef3044d-d4cb-4586-8e82-ee97bd3b14ad?ui=en-US&rs=en-US&ad=US

What is the final reco here ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02d8b61-29e8-c0a7-b3b2-79be7212a91c
* Version Independent ID: b4346d87-0727-c7fe-7896-7fd79098825c
* Content: [Configuring Alternate Login ID](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configuring-alternate-login-id#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configuring-Alternate-Login-ID.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configuring-Alternate-Login-ID.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 976 -b #assign:IngridAtMicrosoft
