### ISSUE TITLE
How to tell whether or not a machine is already domain-joined

### ISSUE THREAD

**Issue by olofh-msft** [MicrosoftDocs/windowsserverdocs#1029]
Before giving instructions on how to join a domain, it would help to give instructions on how to tell whether or not a machine is already domain-joined.  That would also make a last step pretty easy:  i.e. How to verify that the process of joining a domain was successful.
Also, is it possible to have a machine joined to more than one domain?  Is it possible to join a different domain if the machine is already domain joined?  
Why would want a machine to join a domain, anyway?  Are there any disadvantages to consider? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f091cf6-cc59-5ac2-69e7-bff6b674dc01
* Version Independent ID: 7e6209b4-2547-f5b9-1730-5ca2aea7243f
* Content: [Join a Computer to a Domain](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/join-a-computer-to-a-domain)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Join-a-Computer-to-a-Domain.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Join-a-Computer-to-a-Domain.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by MicrosoftGuyJFlo** [comment]
@olofh-msft Let us know if you want to write something for this. The article does what is intended today but if you think more should be added we welcome your contribution as a fellow Microsoft employee.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
