### ISSUE TITLE
Wildcard Certs

### ISSUE THREAD

**Issue by jaypatrick** [MicrosoftDocs/windowsserverdocs#1030]
Why don’t wildcard certs work for the AlternateTlsBinding commands? This has become a huge hassle for our organization with managing all of the various SAN values needed. A Wildcard cert should cover *all* of this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5d65aa8-3f9c-3d49-091d-6be4e41b6b05
* Version Independent ID: 25b734c6-d31b-8ae9-83c9-c7f267c1e030
* Content: [AD FS support for alternate hostname binding for certificate authentication](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/ad-fs-support-for-alternate-hostname-binding-for-certificate-authentication)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/AD-FS-support-for-alternate-hostname-binding-for-certificate-authentication.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/AD-FS-support-for-alternate-hostname-binding-for-certificate-authentication.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 1028 -b #assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
