### ISSUE TITLE
LDAP on Ububtu and ADFS

### ISSUE THREAD

**Issue by sumanbikram** [MicrosoftDocs/windowsserverdocs#1032]
Hi There,
I'm trying to configure ADFS with LDAP on Ubuntu but it asks below-mentioned information. Can you help? 
Supply values for the following parameters:
LdapServerConnection[0]: 
UserObjectClass: 
UserContainer: 
AnchorClaimLdapAttribute: 
AnchorClaimType:

Its Windows Server 2016 based ADFS and below information

LDAP server IP : 10.0.014
Hostname Ubuntu-LdapServer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce6494d8-d525-8961-8dff-c5ee55a18849
* Version Independent ID: a3608a5f-26ed-1a93-2cd2-2fe2e5238248
* Content: [Configure AD FS to authenticate users stored in LDAP directories](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-to-authenticate-users-stored-in-ldap-directories)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-to-authenticate-users-stored-in-LDAP-directories.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-to-authenticate-users-stored-in-LDAP-directories.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#please-close
