### ISSUE TITLE
Missing PowerShell documentation for this process

### ISSUE THREAD

**Issue by nromyn** [MicrosoftDocs/windowsserverdocs#1036]
Documentation for enabling the roles is present but the configuration of the CA with PowerShell is not. The use of PowerShell may be preferred by some customers. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e75c5bf-aefe-154e-de20-a01ab982adf6
* Version Independent ID: 92189653-36bb-7e01-aa84-20fbad5808c8
* Content: [Install the Certification Authority](https://docs.microsoft.com/en-us/windows-server/networking/core-network-guide/cncg/server-certs/install-the-certification-authority)
* Content Source: [WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Install-the-Certification-Authority.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Install-the-Certification-Authority.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@nromyn, Thank you for letting us know about the missing content.  We will work to get it incorporated.

**Comment by shortpatti** [comment]
Added a TIP pointing users to the PS cmdlets and optional parameters.
