### ISSUE TITLE
Windows Server, version 1803 Datacenter Key

### ISSUE THREAD

**Issue by Gaz2600** [MicrosoftDocs/windowsserverdocs#1037]
I think you are missing a character in the first quintet of your "Windows Server, version 1803" Datacenter Key

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc9df0c0-db17-3226-b734-59ebd27fa212
* Version Independent ID: 5b7ddecc-b700-9726-30af-bda0989146e2
* Content: [KMS client setup keys](https://docs.microsoft.com/en-us/windows-server/get-started/kmsclientkeys#feedback)
* Content Source: [WindowsServerDocs/get-started/KMSclientkeys.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/KMSclientkeys.md)
* Product: **windows-server-threshold**
* GitHub Login: @jaimeo

**Comment by lizap** [comment]
You are 100% correct - we missed the first character. We also had the datacenter key as the standard and vice versa. Just pushed a correction. Thanks for raising the issue!
