### ISSUE TITLE
AuthorizationContext.AcquireToken not found

### ISSUE THREAD

**Issue by robv8r** [MicrosoftDocs/windowsserverdocs#1039]
The AuthenticationContext.AcquireToken method does not exist in recent versions of the Microsoft.IdentityModel.Clients.ActiveDirectory NuGet package.  Instead, use AuthenticationContext.AcquireTokenAsync.  In the example, that would be:

    result = await authContext.AcquireTokenAsync(...);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e13f162-0b92-091e-f811-8645f786185f
* Version Independent ID: 68332cf9-44a5-8f19-d149-d294c8c4db5c
* Content: [Build a multi-tiered application using On-Behalf-Of (OBO) using OAuth with AD FS 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/ad-fs-on-behalf-of-authentication-in-windows-server)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/ad-fs-on-behalf-of-authentication-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/ad-fs-on-behalf-of-authentication-in-windows-server.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by MicrosoftGuyJFlo** [comment]
@CelesteDG can you take a look at this

**Comment by CelesteDG** [comment]
@MicrosoftGuyJFlo @billmath - Confirmed. There is no AuthenticationContext.AcquireToken method anymore. See https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.authenticationcontext?view=azure-dotnet#methods for the latest.

**Comment by MicrosoftGuyJFlo** [comment]
Updating in a PR in our private repo. Will publish today.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
