### ISSUE TITLE
Does the HTML5 client work on Chromebooks??

### ISSUE THREAD

**Issue by tommls** [MicrosoftDocs/windowsserverdocs#1040]
Does this HTML5 client work correctly and properly without errors within the Chrome browser running on the Chrome OS within a Chromebook device?? If so, how should it be configured to do so?? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Product: **windows-server-threshold**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by lizap** [comment]
As long as your admin has configured the web client in their Remote Desktop deployment (using the steps in this article), then yes, you can access the web client in Chrome. The instructions for that are [here](https://docs.microsoft.com/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client).
