### ISSUE TITLE
Installation sequence??

### ISSUE THREAD

**Issue by tommls** [MicrosoftDocs/windowsserverdocs#1041]
Must the HTML5 client be installed at the same time one creates and installs a Win2k16 RDSH farm (is this a requirement)?? 
OR
Can the HTML5 client be installed into an existing Win2k16 RDSH farm after the farm has been created and deployed??
The above instructions are not clear on this topic.
Thank you, Tom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Product: **windows-server-threshold**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by davidbel** [comment]
Hi @tommls, the web client can be installed on any RDS 2016 or 2019 that has a RD Gateway and RDWeb installed. It can be added to an existing deployment and does not need a new deployment to be setup.

**Comment by tommls** [comment]
Thank you...only other thing I can think of is to suggest removing the dependency on user CALs and not eating up the device CALs. :) My company uses device CALs because many users work from multiple computers and the CALs were deployed several months ago...I'll assume the web client can be downloaded when we're ready, I don't recall if that information where to download it is included. 
Thank you, Tom

**Comment by davidbel** [comment]
Hi @tommls, appreciate the feedback.

Licensing was definitely a challenge with this web client and since we can't properly track devices, we only recommend using this in a per-user CAL environment. As you said, it will otherwise just eat up device CALs. We will see if we can make improvements around this in the future.

Yes, the web client can be installed and updated at any time since it is a separate component that can be added to an RDS 2016 or 2019 environment. The client is downloaded and deployed using PowerShell scripts as described at: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)

**Comment by tommls** [comment]
Thank you for elucidating -- maybe set up something such that one assigns a changeable 'fixed' quantity of device licenses to the web client. Also provide more information -- how much must one use the web client to use all the device licenses?? e.g. 10 users will use them all up or 100 users will....or you must make it much easier to switch around types of CALs instead of the excessively restrictive one-time only change of CAL type, or create a tool to help users figure out which kind of CAL works for them, or allow using a mixture of user and device CALs, I'm not even knowledgeable about CALs and look at all I thought of, put some technical geniuses to work on this and user/device CAL magic will appear. :)

**Comment by tommls** [comment]
One other idea -- please include UN-installation instructions for the web client for people who might want to do so.

**Comment by davidbel** [comment]
Thanks @tommls, I added a task on my side to document the removal process for the web client.

**Comment by lizap** [comment]
@davidbel added the uninstall instructions here: https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin#how-to-uninstall-the-remote-desktop-web-client
