### ISSUE TITLE
Remove requirement to save id/pass with remote resource feed

### ISSUE THREAD

**Issue by tommls** [MicrosoftDocs/windowsserverdocs#1043]
The Desktop function makes it optional to not save id/password, please do the same for remote resource feed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45d9f311-2994-948d-ad91-f5c7370d73ec
* Version Independent ID: 5f978676-6f53-3f2d-fabb-3554027edbcc
* Content: [Get started with Remote Desktop on Android](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-android)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-android.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-android.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by lizap** [comment]
This is great feedback. Can you submit it to the [Remote Desktop user voice forum](https://remotedesktop.uservoice.com/forums/266795-remote-desktop-services-for-enterprises)? That's where we collect suggestions/requests/enhancements. Thanks!

**Comment by tommls** [comment]
I did this.
