### ISSUE TITLE
Very slow scroll bar in Firefox

### ISSUE THREAD

**Issue by davemail** [MicrosoftDocs/windowsserverdocs#1045]
We encounter a very slow scroll behavior in Firefox (ESR and most recent versions). IE or Edge seem to work out of the box.
Does anyone know how to fix this issue?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Product: **windows-server-threshold**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by davidbel** [comment]
@davemail, if possible, please send mail to the address on the About page of the web client so we can investigate further.
