### ISSUE TITLE
Image not resized

### ISSUE THREAD

**Issue by ioamnesia** [MicrosoftDocs/windowsserverdocs#1048]
Screenshot under Managing Fine-Grained Password Policies that shows each area of the UI with callouts is not sized properly and cannot be read

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c2da2ea-03a9-8710-007f-33a44b17bbab
* Version Independent ID: ea3919b1-4762-1bcc-17e3-c8cbf319b751
* Content: [Advanced AD DS Management Using Active Directory Administrative Center (Level 200)](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/get-started/adac/advanced-ad-ds-management-using-active-directory-administrative-center--level-200-#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/get-started/adac/Advanced-AD-DS-Management-Using-Active-Directory-Administrative-Center--Level-200-.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/get-started/adac/Advanced-AD-DS-Management-Using-Active-Directory-Administrative-Center--Level-200-.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by MicrosoftGuyJFlo** [comment]
Resolving in private repo branch GitHubIssues072018

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
