### ISSUE TITLE
Deduplication with Storage Replica

### ISSUE THREAD

**Issue by dapsandhu** [MicrosoftDocs/windowsserverdocs#1052]
Please provide info on how Deduplication can work with server-to-server storage replica.
Going by what is said in on deduplication page (https://docs.microsoft.com/en-us/windows-server/storage/data-deduplication/interop) "Storage Replica is fully supported. Data Deduplication should be configured to not run on the secondary copy", does that mean Server A (Site A, primary) should only have dedup enabled and not Server B (Site B, Replica)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f58b836-4eb3-562a-9ca1-92202c267db0
* Version Independent ID: f8674fad-5571-57e1-8afd-cf21cb044525
* Content: [Server-to-server storage replication](https://docs.microsoft.com/en-us/windows-server/storage/storage-replica/server-to-server-storage-replication)
* Content Source: [WindowsServerDocs/storage/storage-replica/server-to-server-storage-replication.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-replica/server-to-server-storage-replication.md)
* Product: **windows-server-threshold**
* GitHub Login: @nedpyle
* Microsoft Alias: **nedpyle**

**Comment by nedpyle** [comment]
It means that while the deduplication feature can be installed on the destination server, enabling it will do nothing: the destination volume is always dismounted with Storage Replica. After you failover to the destination and make it primary or remove replication, you can then enable dedup.

**Comment by dapsandhu** [comment]
Thanks for your response @nedpyle. 
In that case, if my primary deduped volume is lost and I bring the destination server online by breaking the replica group, the data could be missing as the non-dedup data will be more than the actual volume?
This means dedup is unsupported in replica?
