### ISSUE TITLE
Self-Signed Certificate Question

### ISSUE THREAD

**Issue by wychong82** [MicrosoftDocs/windowsserverdocs#1054]
Refer to the document warning, the automatically generated certificate will expire 60 days after installation.  Does we generate the self-signed certificate which can use more than 60 days?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe84fb4b-3420-bc1e-6a1d-b64ecc56fc5e
* Version Independent ID: f089767e-4613-d595-a0ee-0dab012724a1
* Content: [Install Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/install)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/deploy/install.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/deploy/install.md)
* Product: **windows-server-threshold**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by jwwool** [comment]
**Please note:** The self-signed certificate is for testing purposes only and not recommended for production use. 

To generate a new certificate, re-run the installer. The previously generated certificate thumbprint will be automatically populated, but toggling back to the generate option will create new self-signed certificate with a new expiration date.

Another option would be to create and install your own self-signed certificate using the [New-SelfSignedCertificate](https://docs.microsoft.com/en-us/powershell/module/pkiclient/new-selfsignedcertificate?view=win10-ps) PowerShell Cmdlet.
