### ISSUE TITLE
Debian Stretch

### ISSUE THREAD

**Issue by lastuptodate** [MicrosoftDocs/windowsserverdocs#1055]
Can you please update this page for Debian Stretch 9 ?
Best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef7e57c1-a0f5-126a-775c-7e99a607197b
* Version Independent ID: 22a9dc7b-18c2-6f73-d224-886757a65a7c
* Content: [Supported Debian virtual machines on Hyper-V](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-debian-virtual-machines-on-hyper-v#feedback)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Supported-Debian-virtual-machines-on-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/Supported-Debian-virtual-machines-on-Hyper-V.md)
* Service: **na**
* Product: **windows-server-threshold**
* GitHub Login: @shirgall
* Microsoft Alias: **kathydav**

**Comment by dawnwood** [comment]
@lastuptodate We added the column for Debian 9 (stretch).
