### ISSUE TITLE
Ctrl - Alt - End

### ISSUE THREAD

**Issue by SimonWaters** [MicrosoftDocs/windowsserverdocs#1056]
PC says send Ctrl-Alt-End - feels like special key sequences should be in the FAQ for the Mac client. I have Ctrl Alt but no End on this keyboard.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5581a04a-e204-4a19-3eba-0852d2eb5d8e
* Version Independent ID: 820c77b6-2182-7e92-bbe6-0819f727d207
* Content: [Remote Desktop clients FAQ](https://docs.microsoft.com/en-gb/windows-server/remote/remote-desktop-services/clients/remote-desktop-client-faq#mac-client---hardware-questions)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by Heidilohr** [comment]
The Get started with Remote Desktop on Mac article has a list of the Mac's keyboard special keys, which you can find [here.](https://docs.microsoft.com/en-gb/windows-server/remote/remote-desktop-services/clients/remote-desktop-mac#use-a-keyboard-in-a-remote-session)

**Comment by SimonWaters** [comment]
But doesn’t cover “End” as far as I can find.

Loved into Windows Box, first thing it said was password is expiring press “ctrl alt End”. Most other clients I’ve used had options to send special sequences, but was left guessing... and failed to guess.

Simon Waters
phone  +448454681066
email  simon.waters@surevine.com
skype  simon.waters.surevine


Participate | Collaborate | Innovate

Surevine Limited, registered in England and Wales with number 06726289. Mailing Address : PO Box 1136, Guildford GU1 9ND
If you think you have received this message in error, please notify us.

**Comment by Heidilohr** [comment]
It sounds like your issue involves the text used in the notification. I'm going to get in touch with the development team and see if I can get an answer for you.

**Comment by ljf0021** [comment]
Did anybody solve the answer to Control Alt End?

**Comment by Heidilohr** [comment]
For Mac, you should use Ctrl+Fn+Option+Delete. Thank you for your patience!
