### ISSUE TITLE
Redundant Acronym Phrases 

### ISSUE THREAD

**Issue by gredinger** [MicrosoftDocs/windowsserverdocs#1057]
NPS = Network Policy Server
"Network Policy Server Server" doesn't really make sense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b885e67-eece-8a90-144a-e3c570310feb
* Version Independent ID: 319d623a-fe0b-fce9-f069-2d950b1796eb
* Content: [Export an NPS Server Configuration for Import on Another Server](https://docs.microsoft.com/en-us/windows-server/networking/technologies/nps/nps-manage-export)
* Content Source: [WindowsServerDocs/networking/technologies/nps/nps-manage-export.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/nps/nps-manage-export.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
Fixed.
