### ISSUE TITLE
Stretch Cluster IP Addressing considerations

### ISSUE THREAD

**Issue by linusjody** [MicrosoftDocs/windowsserverdocs#1060]
What is the recommendation for IP addressing the cluster nodes and the CNO in differing sites?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e81b5767-e7e7-749f-2656-246a34882f5d
* Version Independent ID: 3a1235a0-3006-7855-0dce-5dcdf8160f91
* Content: [Stretch Cluster Replication Using Shared Storage](https://docs.microsoft.com/en-us/windows-server/storage/storage-replica/stretch-cluster-replication-using-shared-storage)
* Content Source: [WindowsServerDocs/storage/storage-replica/Stretch-Cluster-Replication-Using-Shared-Storage.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-replica/Stretch-Cluster-Replication-Using-Shared-Storage.md)
* Product: **windows-server-threshold**
* GitHub Login: @nedpyle
* Microsoft Alias: **nedpyle**

**Comment by dawnwood** [comment]
Thank you for your question. It should now be answered [here](https://docs.microsoft.com/en-us/windows-server/storage/storage-replica/stretch-cluster-replication-using-shared-storage), please let us know if it is not.

**Comment by linusjody** [comment]
I’ve read this article and it doesn’t address the differing subnets in the respective sites and with that, what address the CNO could potentially take in that situation. In 2012 R2 on a traditional cluster the CNO would be in the same subnet as the nodes, so what do you do when the nodes are in different subnets?

**Comment by dawnwood** [comment]
That comment really isn’t going to be explained from this article.  Failover Clustering nodes do not have to be in the same subnet.  All that is required is that they can be contacted by all nodes.  Cluster will set up the various networks automatically.  So let’s take for example, you have the two sites with Site1 on 1.0.0.x network and another Site2 on 192.168.0.x network and there are two nodes in each site.  Your nodes would have these IP Addresses:

Site1 Node1 = 1.0.0.50
Site1 Node2 = 1.0.0.51
Site2 Node3 = 192.168.0.50
Site2 Node4 = 192.168.0.51

In Failover Cluster Manager, you would have a “Cluster Network 1” that has the 1.0.0.x network and “Cluster Network 2” that has the 192.168.0.x network with the respective nodes listed in the appropriate network.  When you created the Cluster, it could have selected “Cluster Network 1” for the Cluster IP Address so it could have the IP of 1.0.0.52.  The Cluster Group will successfully come online on Node1/Node2 as it has that network and matches the IP Address scheme.  So for it to be able to move to Site2, you will need to create an additional IP Address that the Cluster Name has a dependency on that is in Cluster Network 2.  So following the blog, you would create a second IP Address in the Cluster Group (say 192.168.0.52) and assign it to “Cluster Network 2”.  Then under the dependencies for the Cluster Network Name, add the second IP Address specifying it as OR.  That way, when the Cluster Group is in Site1, the 1.0.0.52 IP Address will be online and the 192.168.0.52 address offline.  When the Cluster Group is in Site2, it is reversed where 1.0.0.52 address is offline and 192.168.0.52 address is online.
