### ISSUE TITLE
Powershell script must be run as SYSTEM to create device tunnel

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/windowsserverdocs#1062]
Running the provided powershell script as a user (even running as admin) will not create a device tunnel.  The script must be run in the context of the SYSTEM account on the computer.  For more info, see Richard Hicks's blog post here:
https://directaccess.richardhicks.com/2017/12/11/always-on-vpn-windows-10-device-tunnel-step-by-step-configuration-using-powershell/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06629f78-c4b1-4345-578c-596e92dff977
* Version Independent ID: e3686eef-c2c6-5a21-ac76-6bac575e7cfc
* Content: [Configure the VPN device tunnel in Windows 10](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/vpn-device-tunnel-config)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/vpn-device-tunnel-config.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/vpn-device-tunnel-config.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@NeighborGeek, thank you for the information.  I'll incorporate the necessary information :)

**Comment by NeighborGeek** [comment]
Thanks.  Of course, while Richard is an expert on windows remote access, please run it by the appropriate engineering team first to verify the accuracy of the information.  It's possible that there's a better way to go about it...

**Comment by shortpatti** [comment]
Thank you, I always do run it by engineering.

**Comment by shortpatti** [comment]
The content has been updated and will be reviewed with other requested changes.  

Thank you again for pointing that caveat out.
