### ISSUE TITLE
Is this document is a draft version?

### ISSUE THREAD

**Issue by sbsharma35** [MicrosoftDocs/windowsserverdocs#1064]
Token response, Authentication, Claim rule processing is not elaborated. Also, if you could elaborate/provide more info on web debugger tool which can be leveraged to see the claims in id_tokens

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 107d67e0-b40d-96cc-448c-2da3c482482a
* Version Independent ID: e81ca4eb-174d-f5f3-275c-5292de9499ad
* Content: [AD FS Troubleshooting - Claims Issuance](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-claims-issuance#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-claims-issuance.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-claims-issuance.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
