### ISSUE TITLE
Scale Out File Server Role Creation Failure

### ISSUE THREAD

**Issue by aahmad81** [MicrosoftDocs/windowsserverdocs#1069]
If the SOFS command fails and you find the Role offline, make sure to go to the Container in AD where the Cluster were is and give the Cluster Role rights to Create Computer Objects. Then you will be able to restart the SOFS role and it should suceed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 706b2e1a-e90e-d70e-431f-5476b0ca52c1
* Version Independent ID: 70721d4c-642c-61f8-6c61-84b1dd1ae96c
* Content: [Deploy a two-node Storage Spaces Direct SOFS for UPD storage in Azure](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-storage-spaces-direct-deployment)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-storage-spaces-direct-deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-storage-spaces-direct-deployment.md)
* Product: **windows-server-threshold**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by IngridAtMicrosoft** [comment]
#please-close
