### ISSUE TITLE
Thank 

### ISSUE THREAD

**Issue by Suil3File** [MicrosoftDocs/windowsserverdocs#1070]
How to use ios

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b400e326-face-ddc7-d9ac-ab08488bb75a
* Version Independent ID: 1da91dfc-2a76-5be4-1376-959e6c3635a9
* Content: [Windows Server](https://docs.microsoft.com/en-us/windows-server/windows-server)
* Content Source: [WindowsServerDocs/Windows-Server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/Windows-Server.md)
* Product: **windows-server-threshold**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by lizap** [comment]
Hi, is there specific information that you're looking for? Thanks!

**Comment by phototrimbd** [comment]
This is not much information for windows server 
 http://www.educationbangla.com/
