### ISSUE TITLE
Domain vs Workgroup

### ISSUE THREAD

**Issue by simphiwemkhize** [MicrosoftDocs/windowsserverdocs#1080]
Hi There
Just need to know which one is recommended over the other (domain or workgroup) when deploying Windows Admin Center?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 136cbcd9-a631-587d-3b48-dded76d9e6c9
* Version Independent ID: d1ac1f79-89de-97d8-aec7-1c6a78212910
* Content: [Windows Admin Center Frequently Asked Questions](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/understand/faq)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/understand/faq.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/understand/faq.md)
* Product: **windows-server-threshold**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by jwwool** [comment]
Both are supported. In a workgroup, there are [additional considerations](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/troubleshooting#workgroup), and single sign-on is not available.
