### ISSUE TITLE
robocopy logging

### ISSUE THREAD

**Issue by pjaj** [MicrosoftDocs/windowsserverdocs#1081]
Would it be possible to have a switch(s) that logged only the files and directories that were new / updated and omitted the ones that were not copied? Or maybe there is a combination that does that. It would make the log file considerably smaller when robocopy is used for backup. The user can assume that if the file / directory is not listed as either copied or failed then the target was up to date and can concentrate on the important information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af94ad3b-6603-2b26-1010-073fb2c07c2a
* Version Independent ID: 09fd75d0-8624-5cfd-5122-b40ba50055f9
* Content: [robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by WurstCommander** [comment]
I think it's the default behavior, because with /v you get all the not copied files?

**Comment by ChristianKurz** [comment]
The files not copied will be logged as `EXTRA` files. You can disable this behaviour with the `/xx` command: exclude Extra files.
