### ISSUE TITLE
netsh deprecation - need pointers to Powershell equivalents

### ISSUE THREAD

**Issue by rangercej** [MicrosoftDocs/windowsserverdocs#1085]
This page indicates that netsh is deprecated in favour of powershell ("It is recommended that you use Windows PowerShell to manage networking technologies in Windows Server 2016 and Windows 10 rather than Network Shell [...]"), however there appear to be no (at least obvious) replacements for "netsh http" (URL reservations, SSL certificate binding, etc). 

Can you provide pointers to the equivalent PS documentation for "netsh http"? If this doesn't exist, can this page indicate what features of netsh are not supported by powershell so we're not spending time pointlessly searching the internet.

More generally, it would be useful to list all the features of netsh together with their powershell equivalents to people porting scripts have a one-place easy reference to this information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104c0791-b5a1-6502-401a-d472ff6144bb
* Version Independent ID: 5a8faa14-9cef-6a9b-26af-9782a799b23a
* Content: [Network Shell (Netsh)](https://docs.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh)
* Content Source: [WindowsServerDocs/networking/technologies/netsh/netsh.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/netsh/netsh.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by Djfe** [comment]
just stumbled across this:
https://stackoverflow.com/questions/6851161/net-or-win32-equivalent-of-netsh-http-add-urlacl-command

Maybe it helps :)

**Comment by shortpatti** [comment]
@Djfe, thank you for providing the extra information. I'll get it incorporated :)

**Comment by shortpatti** [comment]
Thank you for your patience.  I've updated the [content](https://docs.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh-http).

**Comment by Djfe** [comment]
cool, thx
The link is unavailable though (404)

**Comment by shortpatti** [comment]
Ah, it must not have been published yet.  Give it until this afternoon.  

It's essentially [this](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc725882%28v%3dws.10%29).
