### ISSUE TITLE
Tool visibility not working when powershell script is written in conditions block.

### ISSUE THREAD

**Issue by SainiBhavna** [MicrosoftDocs/windowsserverdocs#1092]
Written a powershell script which checks the availability of a particular folder and it returns status as 'NotConfigured' if the folder does not exits or else it returns status to be 'Available', but the script seems to have no effect on the tools visibility. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9473ecb6-7d1d-7b0f-44d3-58690fc21020
* Version Independent ID: 1b922f56-101e-e217-0e4e-8bb8c386f7e5
* Content: [Control your tool's visibility in a solution](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/extend/guides/dynamic-tool-display)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/extend/guides/dynamic-tool-display.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/extend/guides/dynamic-tool-display.md)
* Product: **windows-server-threshold**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by IngridAtMicrosoft** [comment]
#please-close
