### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by aszego** [MicrosoftDocs/windowsserverdocs#1095]
Based on my experience, '==' is case-sensitive. This doc states that: "The rules must be encoded in UTF-16, and the string comparisons must be treated as case insensitive."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 209d4f95-36d3-9235-9475-3962dab3fd76
* Version Independent ID: 321bebc7-3737-ec35-3a2c-ffb4ef1544c3
* Content: [Claims Transformation Rules Language](https://docs.microsoft.com/en-us/windows-server/identity/solution-guides/claims-transformation-rules-language)
* Content Source: [WindowsServerDocs/identity/solution-guides/Claims-Transformation-Rules-Language.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/solution-guides/Claims-Transformation-Rules-Language.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by PRMerger4** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: ingridatmicrosoft 
gh issue comment 1064 -b ingridatmicrosoft
