### ISSUE TITLE
Keyboard layout is different than the keyboard in the phone

### ISSUE THREAD

**Issue by deliad2** [MicrosoftDocs/windowsserverdocs#1099]
Hi,

It happens only with the Microsoft RDP Client for android, and its latest version

It happens on hebrew keyboard enabled machines (or machines with any other different layout language than english i guess)

The key i press in phone is another key on the controlled station

Example: 
If i press .
I get \

You need to do something that sends the actual char to the machine like teamviewer does and anydesk and Remote RDP Enterprise does

Please fix, this is very disturbing.

**Comment by IngridAtMicrosoft** [comment]
#please-close
