### ISSUE TITLE
:,v

### ISSUE THREAD

**Issue by PabloJoaquin** [MicrosoftDocs/windowsserverdocs#1100]
escribo graftabl /status y me dice que ese comando no existe :,v

**Comment by illfated** [comment]
Ticket originated from the following page:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bcda751-29e6-5541-0bcd-7b3f7a5e9d94
* Version Independent ID: 24314f2c-5492-10da-deac-fc97f88dc671
* Content: [graftabl](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/graftabl)
* Content Source: [WindowsServerDocs/administration/windows-commands/graftabl.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/graftabl.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
We need to do something about the `graftabl` page, because it has not been needed for GUI versions of Windows since Windows XP.
(Not even sure if this Windows command-line command is even available anymore, even on non-GUI versions of Windows.)
