### ISSUE TITLE
escribes help | more y te muestra información pantalla a pantalla :v (por cierto el sigo | es el que está al lado del uno ;v

### ISSUE THREAD

**Issue by PabloJoaquin** [MicrosoftDocs/windowsserverdocs#1101]
:v solo eso pe 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 586a9dcb-68a3-3fff-f99c-3d6b6700aaca
* Version Independent ID: 0c41fe94-6281-fabc-4372-3b34b37dfbb8
* Content: [help](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/help)
* Content Source: [WindowsServerDocs/administration/windows-commands/help.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/help.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
The `more` command has already got usage examples. IT Pro admins should know this from their early education steps.

**Comment by illfated** [comment]
#please-close
