### ISSUE TITLE
interesante :v

### ISSUE THREAD

**Issue by PabloJoaquin** [MicrosoftDocs/windowsserverdocs#1103]
;v prro

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e13348f3-3c91-ca88-b1bf-bf275243294e
* Version Independent ID: 7ba9aafa-ec9e-dd97-1445-091866053d97
* Content: [if](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/if)
* Content Source: [WindowsServerDocs/administration/windows-commands/if.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/if.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
@PabloJoaquin : Thank you for your nice comment. I am going to close this issue ticket now, since it does not seem to contain any documentation improvement suggestions or request for new updates. Feel free to create a new issue ticket if you find something in need of correction or updating.

**Comment by illfated** [comment]
#please-close
