### ISSUE TITLE
saben dónde está ese tal archivo CONFIG.SYS :v?

### ISSUE THREAD

**Issue by PabloJoaquin** [MicrosoftDocs/windowsserverdocs#1106]
io no se :,v

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 397b03ea-324c-1ebd-2c19-94b6eda68dcc
* Version Independent ID: 62c547dc-92e8-00f9-1cb9-02aefa2a42aa
* Content: [rem](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/rem)
* Content Source: [WindowsServerDocs/administration/windows-commands/rem.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/rem.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
#please-close
