### ISSUE TITLE
mirad mi pequeño "buscador".

### ISSUE THREAD

**Issue by PabloJoaquin** [MicrosoftDocs/windowsserverdocs#1107]
@echo off
title Buscador archivos :D!!!
color f0
:one
cls
echo 						____________________
echo  						 B U S C A D O R 7w7              escribe salir para salir :3
echo 						 ___________________
echo.
set /p archivo=Escribe el nombre de archivo con su extension :3 y nombre EXACTO :d : 
echo.
if exist "%archivo%" (
    echo Correcto existe "%archivo%" :D!.
) else (
    echo.
    echo :( No existe.
)
if "%archivo%" == "salir" exit
echo.
echo presiona una tecla para buscar otro archivo/directorio :D.
pause&gt;nul
goto one
pause&gt;nul

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e13348f3-3c91-ca88-b1bf-bf275243294e
* Version Independent ID: 7ba9aafa-ec9e-dd97-1445-091866053d97
* Content: [if](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/if)
* Content Source: [WindowsServerDocs/administration/windows-commands/if.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/if.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
#please-close
