### ISSUE TITLE
pathping output is mangled

### ISSUE THREAD

**Issue by weq** [MicrosoftDocs/windowsserverdocs#1108]
the codeblock with the pathping results is unreable in it's current state.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eee40cd-e852-11e7-7713-0e8c8033dc53
* Version Independent ID: 147206f0-5fb6-edf3-70ee-02bc9b6a2c09
* Content: [pathping](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/pathping)
* Content Source: [WindowsServerDocs/administration/windows-commands/pathping.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/pathping.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by weq** [comment]
I can add that the markdown looks just fine when viewing it at github but completely broken on https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/pathping

**Comment by lizap** [comment]
Yep, the markdown just needed some carriage returns to break up the sections. I'm working on it now. Thanks!

**Comment by lizap** [comment]
I fixed the formatting so you can view the actual example syntax now. Thanks for raising this issue.
