### ISSUE TITLE
Section is missing Windows 2016 details and is redundant to another article under "Identity and Access -> Getting Started

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/windowsserverdocs#1110]
https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/active-directory-functional-levels

The above linked article covers all of the same information plus the information for Windows 2016.  Just an FYI.  I might be missing the logic for why the same info is located in two separate pages within the same overarching section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 740cea70-5958-4560-617f-d9f55e7dc78d
* Version Independent ID: cb9cdd27-779d-2dda-9753-574588d616f3
* Content: [Understanding Active Directory Domain Services (AD DS) Functional Levels](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/understanding-active-directory-domain-services--ad-ds--functional-levels)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Understanding-Active-Directory-Domain-Services--AD-DS--Functional-Levels.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Understanding-Active-Directory-Domain-Services--AD-DS--Functional-Levels.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by MicrosoftGuyJFlo** [comment]
Thanks for calling that out. Need to delete the older topic.

**Comment by MicrosoftGuyJFlo** [comment]
Created Product Backlog Item 497654 to remove the duplicate article

**Comment by MicrosoftGuyJFlo** [comment]
#in-progress

**Comment by JeremyTBradshaw** [comment]
Thanks, and to confirm I'm not trying to be critical, I just use a lot of these pages for work to make sure I'm using the latest info and since this avenue is available am reporting stuff when I find oddities. I'm definitely thankful that the info is here, and so well looked after!

**Comment by MicrosoftGuyJFlo** [comment]
Article is being deleted today and redirected to the new content.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
