### ISSUE TITLE
Windows Admin Center server's grouping

### ISSUE THREAD

**Issue by jagdishsaini7** [MicrosoftDocs/windowsserverdocs#1114]
Hello, I am currently using Windows Admin Center and loving it, I would like to group my servers based on Sites, region, roles. I wanted to check if in future if this functionality will be added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc4cb072-7157-55b4-dbe1-c5723d2873b3
* Version Independent ID: 70a3605d-6d21-5719-b661-6023bad96627
* Content: [Windows Admin Center Overview](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/overview)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/overview.md)
* Product: **windows-server-threshold**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by sergiomartinezconde** [comment]
Hi @jagdishsaini7

This is one of the most requested new features for WAC.

https://windowsserver.uservoice.com/forums/295071-management-tools/suggestions/31481722--connections-list-ability-to-group-connections

And seems that is planned to include it in a new release.

Regards

**Comment by sergiomartinezconde** [comment]
Nowadays the only way to organize or group servers by some specific criteria is using tags.
