### ISSUE TITLE
URL with escape character \ cause an error with pkiview in the next section (windows 2016dc)

### ISSUE THREAD

**Issue by oncledad** [MicrosoftDocs/windowsserverdocs#1115]
Urls didn't work for me with escape character \. It worked fine without escaping special characters (server 2016 dc). For instance I had to use http://pki.corp.contoso.com/pki/<ServerDNSName\>\_\<CaName\>\<CertificateName\>.crt
 instead of 
http:\\/\\/pki.corp.contoso.com\\/pki\\/<ServerDNSName\>\\_\<CaName\>\<CertificateName\>.crt 
in order to get the expected pkiview result in the next section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2929b93e-fe36-d3e4-ee28-2a4aaf977da6
* Version Independent ID: 689f7606-45b0-3444-65dc-85c2ba217e9b
* Content: [Configure the CDP and AIA Extensions on CA1](https://docs.microsoft.com/en-us/windows-server/networking/core-network-guide/cncg/server-certs/configure-the-cdp-and-aia-extensions-on-ca1)
* Content Source: [WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Configure-the-CDP-and-AIA-Extensions-on-CA1.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Configure-the-CDP-and-AIA-Extensions-on-CA1.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
I removed the unnecessary escape characters and it will be published later today :)  Thank you for bringing that to my attention.
