### ISSUE TITLE
Why the recommendation of 32 CSVs per cluster?

### ISSUE THREAD

**Issue by thethird1978** [MicrosoftDocs/windowsserverdocs#1116]
Why the recommendation of 32 CSVs per cluster?  Is there some performance gain or is there a risk to the data?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5fc5666-93ee-1dde-2342-a171a22620f7
* Version Independent ID: f252b465-87fc-e0ed-7676-a60f2cd627de
* Content: [Planning volumes in Storage Spaces Direct](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/plan-volumes)
* Content Source: [WindowsServerDocs/storage/storage-spaces/plan-volumes.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/plan-volumes.md)
* Product: **windows-server-threshold**
* GitHub Login: @cosmosdarwin
* Microsoft Alias: **cosdar**

**Comment by IngridAtMicrosoft** [comment]
#please-close
