### ISSUE TITLE
Missing bits and additional spaces

### ISSUE THREAD

**Issue by elmatkos** [MicrosoftDocs/windowsserverdocs#1123]
Hi, could you fix the commands in this article, for example:
PS C:&gt;\$a= Get- TpmEndorsementKeyInfo
Should be:
PS C:&gt;\$a=Get-TpmEndorsementKeyInfo
So whoever copy paste them will see just errors.
Another one:
PS C:&gt;\$a.manufacturerCertificates|Export-Certificate c:\myEkcert.cer
Should be:
PS C:&gt;\$a.manufacturerCertificates|Export-Certificate -filepath c:\myEkcert.cer

I think I saw some more spaces somewhere, so pls check the article, thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5236dc2c-c366-9c2c-85b7-45434341eaa8
* Version Independent ID: 838950d1-f187-1f7a-aff6-ca09fc111f18
* Content: [TPM Key Attestation](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/component-updates/tpm-key-attestation)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/component-updates/TPM-Key-Attestation.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/manage/component-updates/TPM-Key-Attestation.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by MicrosoftGuyJFlo** [comment]
Sending note to PG for feedback

**Comment by MicrosoftGuyJFlo** [comment]
#in-progress

**Comment by MicrosoftGuyJFlo** [comment]
Updating in our private repo will publish later today.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
