### ISSUE TITLE
Need to add Okta now

### ISSUE THREAD

**Issue by powershellshock** [MicrosoftDocs/windowsserverdocs#1128]
Per the following article, Okta should now be added to this list.  https://help.okta.com/en/prod/Content/Topics/integrations/adfs-okta-int.htm  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8348816f-fc89-4d25-d077-24cd86cdd38c
* Version Independent ID: 5f49fb4b-72da-f818-e87d-8fe002fc8ddc
* Content: [Configure Additional Authentication Methods for AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-additional-authentication-methods-for-ad-fs#microsoft-and-third-party-additional-authentication-methods)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-Additional-Authentication-Methods-for-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-Additional-Authentication-Methods-for-AD-FS.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by belac9615** [comment]
I believe this was done by @piaudonn in the current live docs page. Okta was added by PR #2393.

**Comment by powershellshock** [comment]
It does look like this is already completed to me.  The public docs page has the link to Okta's page.  https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-additional-authentication-methods-for-ad-fs

**Comment by illfated** [comment]
#please-close
