### ISSUE TITLE
Incomplete details on step 10

### ISSUE THREAD

**Issue by belangerx** [MicrosoftDocs/windowsserverdocs#1129]
"... or use numbers to specify the roles. The numbers. For more information ..."
The 'numbers' phrase doesn't really make sense, something is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e32288e6-1a81-01da-51bf-d1564049a28a
* Version Independent ID: 7388c199-ee35-63fa-deda-e3f6399de3ee
* Content: [Upgrade Domain Controllers to Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/upgrade-domain-controllers)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/upgrade-domain-controllers.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/upgrade-domain-controllers.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by MicrosoftGuyJFlo** [comment]
Information about Move-ADDirectoryServerOperationMasterRole can be found in the document below... 

https://docs.microsoft.com/powershell/module/addsadministration/move-addirectoryserveroperationmasterrole?view=win10-ps#required-parameters

-OperationMasterRole 
Specifies one or more operation master roles to move to the specified directory server in Active Directory Domain Services. The acceptable values for this parameter are:
PDCEmulator or 0
RIDMaster or 1
InfrastructureMaster or 2
SchemaMaster or 3
DomainNamingMaster or 4

**Comment by MicrosoftGuyJFlo** [comment]
#please-close

**Comment by belangerx** [comment]
I'm not sure if there was a confusion with another request, but this one is not solved. The incomplete sentence is still incomplete:

Step 10: 
"You can type the name of each -OperationMasterRole or use numbers to specify the roles. **The numbers.** For more information see Move-ADDirectoryServerOperationMasterRole"

Could you please have a second look at this? Thanks.

**Comment by MicrosoftGuyJFlo** [comment]
I submitted a PR against our private repo to resolve this. It will be fixed later today.
