### ISSUE TITLE
Windows 10?

### ISSUE THREAD

**Issue by rosskoes05** [MicrosoftDocs/windowsserverdocs#1133]
Where are the recommended audit policy recommendations for Windows 10?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd6aec18-46fe-37f4-995f-a98a65678e1f
* Version Independent ID: 519ae984-bcff-ec57-f855-c926b09ccdf2
* Content: [Audit Policy Recommendations](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/audit-policy-recommendations)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Audit-Policy-Recommendations.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Audit-Policy-Recommendations.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
