### ISSUE TITLE
through the AD we can't able to connect connection broker 

### ISSUE THREAD

**Issue by biren1234** [MicrosoftDocs/windowsserverdocs#1134]
[we create connection broker with 2016 datacenter but there are an issue with that through the AD we can' t connect connection broker.  whereas Active directory with 2012  ## ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7242a6c0-8f40-bb91-c23e-0081a4d4a94a
* Version Independent ID: 9a1213ac-baf5-c1f3-e735-33a0b818fb6f
* Content: [Supported configurations for Remote Desktop Services](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-supported-config)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-supported-config.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-supported-config.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by lizap** [comment]
Sorry to hear that you've run into trouble. Unfortunately we don't have the resources to offer troubleshooting through the docs. Instead, your best option is to start a new thread on the [Remote Desktop forum](https://social.technet.microsoft.com/Forums/windowsserver/en-US/home?forum=winserverTS). Thanks!
