### ISSUE TITLE
Missing Datacenter features.

### ISSUE THREAD

**Issue by carlosmayol** [MicrosoftDocs/windowsserverdocs#1138]
Please create a new column for Standard and Datacenter versions and fill them up appropriately. 
Get-WindowsFeature exposes: Standard version: 198 items in Datacenter: 263 items 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db13df44-6cc0-9af2-8cea-60a16b724959
* Version Independent ID: 54b777c3-e1b4-2748-a458-f99dcc44ee7b
* Content: [Roles, Role Services, and Features included in Windows Server - Server Core](https://docs.microsoft.com/en-us/windows-server/administration/server-core/server-core-roles-and-services)
* Content Source: [WindowsServerDocs/administration/server-core/server-core-roles-and-services.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/server-core/server-core-roles-and-services.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap

**Comment by Karl-WE** [comment]
This would be very helpful
here is a docs to start with

unfortunately each of them have a different level detail
docs content:
https://docs.microsoft.com/en-us/windows-server/get-started-19/editions-comparison-19

original content:
https://blogs.technet.microsoft.com/ausoemteam/2017/03/03/comparison-of-standard-and-datacenter-editions-of-windows-server-2016/

**Comment by carlosmayol** [comment]
Awesome, thanks!

**Comment by Karl-WE** [comment]
What is still open on this PR?

**Comment by eross-msft** [comment]
@Karl-WE I believe it was re-opened by mistake. We're running code to try to auto tag/assign our issues so we can look at groupings and see if there's anything we can do with our tiny team. I'll re-close it.
