### ISSUE TITLE
"Oops, could not connect" Error from Web UI

### ISSUE THREAD

**Issue by Geogboe** [MicrosoftDocs/windowsserverdocs#1140]
I think this content could benefit from a few additional troubleshooting pieces:

Logging: 
- I sent an email to the support link in the app and they provided some good info, one of which was to open developer tools in your web browser ( F12 ) and watch the console logs to help troubleshoot. 

NPS Registration in Active Directory
- This definitely needs to be added to the troubleshooting section of the docs. I worked on this issue for days before finally realizing that gateway wasn't registered in Active Directory.  The reason was, when I set up my base RDWeb configuration I only tested it with local connections which didn't utilize the gateway. So I missed the fact that the gateway wasn't working due to NPS registration. Well, the RDWebclient seems to always use the gateway, even if you're running locally, so I kept getting that "Oops" error. 
- Some people may not have this issue if, when they set up all the roles, they're running as a Domain Admin, because I think it takes care of NPS registration for them. I can't imagine must people configuring apps as a domain admins though so it might be useful to point people towards this document: 
https://docs.microsoft.com/en-us/windows-server/networking/technologies/nps/nps-manage-register about registering NPS if they get that "Oops" error when trying to utilize the gateway. 

Trying a previous version of of webclient
- I didn't put this together from the docs but support told me that if you just install an older version of the RDSWebClient module you can then run an older version of the webclient which could be useful for testing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Product: **windows-server-threshold**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by strange-walker** [comment]
Is there an error log? 
my test setup tells:
Oops, we couldn't connect to "Calculator"
The connection to the remote PC was lost. This might be because of a network connection problem. If this keeps happening, ask your admin or tech support for help.

which is not very informative. "Classic" remote calculator app works just fine. Event do not contain any errors

**Comment by Geogboe** [comment]
@strange-walker, what I was getting at about logging is that, in your local web browser, press F12 to open up developer tools and then look at the console logs while trying to make a connection. I'll admit though that the logs are very very verbose and technical! Especially for me, a non-developer.

**Comment by Flodu31** [comment]
Hello,
Same problem on my new deployment. It works fine with the old portal... Any idea?
Thanks.
Florent

**Comment by Heidilohr** [comment]
Hi @Geogboe. We added a section about how to access the console log. The other two items you brought up are currently under consideration.

**Comment by Neckross** [comment]
We received an error accessing the resource from RDWeb/webclient error: Oops, we couldn't connec to remote desktop resource".
We can access the resource from the RdWeb just fine.
The RDWeb/webclient its being published via WAP using Pass-through auth.

Are there any workarounds to access a resource from RDWeb/webclient published by WAP using Pass-through for auth?

**Comment by Mitchperry** [comment]
My NPS is registered, certificates are in place and no luck yet with the HTML5 web client. I have reconfigured, reinstalled, republished etc and still no cigar.
Could I please have some form of assistance?

**Comment by superandroiduser** [comment]
I don't know why this thread is closed. This problem is still not fixed.
