### ISSUE TITLE
Does Mirror-accelerated parity also supported in storage space (Not S2D)?

### ISSUE THREAD

**Issue by sparkf1** [MicrosoftDocs/windowsserverdocs#1145]
According to below article that tiered storage is supported on parity (SSD Mirror and HDD parity) in win2016, I think this should be updated to this official document here.

https://social.technet.microsoft.com/Forums/windowsserver/en-US/9a7715c5-fb79-4c62-b414-ef5ffb73d0c1/storage-spaces-tiers-in-windows-server-2016-configuration-question?prof=required

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 621d449f-4675-d504-e266-5933283b61e7
* Version Independent ID: c2bd816f-d617-0ac2-7f9f-0f17c06b84bf
* Content: [Mirror-accelerated parity](https://docs.microsoft.com/en-us/windows-server/storage/refs/mirror-accelerated-parity)
* Content Source: [WindowsServerDocs/storage/refs/mirror-accelerated-parity.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/refs/mirror-accelerated-parity.md)
* Product: **windows-server-threshold**
* GitHub Login: @gawatu
* Microsoft Alias: **gawatu**

**Comment by dawnwood** [comment]
@sparkf1 Yes, ReFS dynamic tiering is supported on any tiered space. S2D is the term used for space (tiered or non-tiered) in a cluster. Does that answer your question?

**Comment by Krautmaster** [comment]
sry to question again:

Ive a single server with Datacenter 2019 on it, lets say 6 Disks, 2 SSDs.  I can create 1 Pool, 2+6 drives in it. Create a Parity Tier with the 6x HDDs in it, a second Tier "Mirror" with the 2 SSDs, and then ill distribute a tiered ReFS Storage on it.

Is that the understanding of "Mirror-accelerated parity" on a single server then? Fully Supported?
