### ISSUE TITLE
What firewall rule are required to manage a Hyper-V host? 

### ISSUE THREAD

**Issue by Geogboe** [MicrosoftDocs/windowsserverdocs#1148]
Maybe I missed this but I don't see where it's listed what firewall rules are required to be opened for managing hyper-v hosts? I think this would be useful for organization using group policy and DSC to deploy firewall rules. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c4bb2d4-9b81-b153-6936-3ca0f95bf631
* Version Independent ID: 968f574d-3be8-2af6-7470-d4e1f65b4a48
* Content: [Remotely manage Hyper-V hosts](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/remotely-manage-hyper-v-hosts)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/Remotely-manage-Hyper-V-hosts.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/Remotely-manage-Hyper-V-hosts.md)
* Service: **na**
* Product: **windows-server-threshold**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by database64128** [comment]
In Windows Firewall, the following rule:
Windows Remote Management (HTTP-In)
opens port 5985/TCP.
