### ISSUE TITLE
Do clients have to be domain-joined?

### ISSUE THREAD

**Issue by DrDave242** [MicrosoftDocs/windowsserverdocs#1152]
The Prerequisites section of this page states "Remote client computers must be joined to the Active Directory domain and running the Windows 10 Anniversary Update (version 1607) or later operating system."

However, the Feature Comparison page states "Always On VPN does not require devices to be domain joined, so there are no dedicated Group Policy settings to configure it."

So which is it? Do clients have to be domain-joined or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87a4f55-2139-c9b1-c5fc-e280659f58c1
* Version Independent ID: 0cf47e38-99f1-6745-e0d8-4efe5521cdb7
* Content: [Always On VPN Deployment for Windows Server and Windows 10](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
Always On VPN in Windows 10 supports domain-joined and nondomain-joined clients.  I've updated the Prerequisites section to make it clearer.

**Comment by edwinpantony1** [comment]
Can I deploy always on VPN solution without On-Prem AD. My Customer does not have on-prem AD they have only Azure AD (Cloud Only Identity Model). please advise.
