### ISSUE TITLE
Can you clarify the contrained delegation section?

### ISSUE THREAD

**Issue by Geogboe** [MicrosoftDocs/windowsserverdocs#1153]
&gt;When you install Windows Admin Center on Windows 10, it's ready to use single sign-on. If you're going to use Windows Admin Center on Windows Server, however, you need to set up some form of Kerberos delegation in your environment before you can use single sign-on. The delegation configures the gateway computer as trusted to delegate to the target node.

Does this mean I'd need to run this cmdlet for *every* host that I want to manage with Windows Admin Center? So if I have 500 hosts, I have to set this property on each one of their AD computer objects?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6273f49-fe06-5a18-80e3-863bd3a0cf4e
* Version Independent ID: 4ed5bf3d-0c2a-a80e-5bd9-0e858dd8749b
* Content: [Configuring user access control and permissions](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/configure/user-access-control)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/configure/user-access-control.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/configure/user-access-control.md)
* Product: **windows-server-threshold**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by jwwool** [comment]
Yes, if you choose to use this form of delegation, you would need to run that for every host. You could use an array of computer names and a loop like this:

```powershell
$gatewayObject = Get-ADComputer -Identity "<hostname of gateway here>"
foreach ($node in $nodeList) {
    $nodeObject = Get-ADComputer -Identity $node
    Set-ADComputer -Identity $nodeObject -PrincipalsAllowedToDelegateToAccount $gatewayObject
}
```

I include the instructions Resource-based constrained delegation because it's the easiest to set up with a few lines of PowerShell. There are other forms of Kerberos delegation that may be more suitable for scale.
