### ISSUE TITLE
"Third-party VPN plug-in" list update

### ISSUE THREAD

**Issue by sasanmcp** [MicrosoftDocs/windowsserverdocs#1157]
how can we keep this list updated? Palo Alto for example does have a WUP-based plug-in for VPN; but is not mentioned there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 149b80ed-bd71-4082-4ebd-3d39e9fd5cd0
* Version Independent ID: a2558520-580d-c669-db43-f673c1985b6a
* Content: [Always On VPN enhancements](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/always-on-vpn-enhancements)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/always-on-vpn-enhancements.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/always-on-vpn-enhancements.md)
* Product: **windows-server**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
Hi @sasanmcp, what is the name of the Palo Alto VPN plug-in?

**Comment by sasanmcp** [comment]
there it is:
https://www.microsoft.com/en-us/p/globalprotect/9nblggh6bzl3

Get GlobalProtect - Microsoft Store<https://www.microsoft.com/en-us/p/globalprotect/9nblggh6bzl3>
www.microsoft.com
Download this app from Microsoft Store for Windows 10, Windows 10 Mobile, Windows 10 Team (Surface Hub), HoloLens. See screenshots, read the latest customer reviews, and compare ratings for GlobalProtect.





________________________________

**Comment by shortpatti** [comment]
Awesome!  Thank you. I will get the third-party vpn plug-in list updated and it will be published tomorrow.

**Comment by sasanmcp** [comment]
but we need to make this flow running. is there a team at Microsoft working with Partners on this so that they can keep this list updated anytime somebody released a plug-in?


________________________________

**Comment by shortpatti** [comment]
I've updated the third-party vpn plug-in list and I'm starting to work on a process for keeping the list updated. 

Closing.  The update will reflect later today.
