### ISSUE TITLE
ctsTraffic has moved to GitHub

### ISSUE THREAD

**Issue by kehorton** [MicrosoftDocs/windowsserverdocs#1158]
As CodePlex.com has effectively shutdown, ctsTraffic has moved to GitHub: https://github.com/Microsoft/ctsTraffic 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3df5212a-ee78-28aa-876f-9b36ff9f4188
* Version Independent ID: a90fe541-c8f6-939e-3af4-b5b8fe9d89fa
* Content: [Performance Tools for Network Workloads](https://docs.microsoft.com/en-us/windows-server/networking/technologies/network-subsystem/net-sub-performance-tools#bkmk_size)
* Content Source: [WindowsServerDocs/networking/technologies/network-subsystem/net-sub-performance-tools.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/network-subsystem/net-sub-performance-tools.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@kehorton, Thanks for letting me know.  I'll make sure that all links are updated.
