### ISSUE TITLE
which command is it after all?

### ISSUE THREAD

**Issue by sasanmcp** [MicrosoftDocs/windowsserverdocs#1167]
on Step 3, is it Grant-ClusterAccess or Grant-SRAccess? description says one and the code snippet says the other.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f70b91f-1cbc-3ea4-3760-d8945f9ff1fb
* Version Independent ID: 5372fa26-d2b9-8fa9-c4ec-7ce34f062b57
* Content: [Cluster to cluster Storage Replication](https://docs.microsoft.com/en-us/windows-server/storage/storage-replica/cluster-to-cluster-storage-replication#step-3-set-up-cluster-to-cluster-replication-using-windows-powershell)
* Content Source: [WindowsServerDocs/storage/storage-replica/cluster-to-cluster-storage-replication.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-replica/cluster-to-cluster-storage-replication.md)
* Product: **windows-server-threshold**
* GitHub Login: @nedpyle
* Microsoft Alias: **nedpyle**

**Comment by dawnwood** [comment]
Thank you for your question. The answer is **Grant-SRAccess. I'll update the topic.

**Comment by dawnwood** [comment]
@sasanmcp This has been fixed.
