### ISSUE TITLE
Minimum and Maximum Values

### ISSUE THREAD

**Issue by ilio78** [MicrosoftDocs/windowsserverdocs#1170]
Hello,

can you please specify the minimum and maximum value of the property : –SsoLifetime ?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95839036-86aa-c988-1d6b-4ac2ef399fbc
* Version Independent ID: 126ca9cf-5d45-e5e5-88d9-b83d3b7987b8
* Content: [AD FS 2016 Single Sign On Settings](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/ad-fs-single-sign-on-settings)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/ad-fs-single-sign-on-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/ad-fs-single-sign-on-settings.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
