### ISSUE TITLE
Key combinations

### ISSUE THREAD

**Issue by ferronsw** [MicrosoftDocs/windowsserverdocs#1171]
Some of my apps have key combinations to use the application. How can I use them within the new client?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d3b53c9-06c8-883c-6197-3fa09fa2e737
* Version Independent ID: e679b983-6e34-75a8-8e4d-f56a5067bf85
* Content: [Access the Remote Desktop web client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client.md)
* Product: **windows-server-threshold**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by ferronsw** [comment]
The combination is CTRL + TAB.

**Comment by IngridAtMicrosoft** [comment]
#please-close
