### ISSUE TITLE
error code 0x204

### ISSUE THREAD

**Issue by mavrik64** [MicrosoftDocs/windowsserverdocs#1172]
this was working on my MacBook Pro (High Sierra) fine up until recently. I loved the app and it's simplicity. All of a sudden last week I couldn't log in. I find the app has an update so I download the new app. import config settings for my Remote Desktop (win10Pro) and still can't connect. I see loads of comments on forums about this, but none of the solutions work. 
I can login to the win10Pro machine if I use my iPhone (iOS 11.4.1). Works great from there. I can access the machines folders and files directly from the MacBook Pro using Finder.
Why can't I use full desktop with Microsoft Remote Desktop app any more?
any help would be nice, thanks 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 526c6220-c5f5-7dce-3239-66e5134cd40e
* Version Independent ID: 598ceeef-0f46-fff1-8528-45c12e112612
* Content: [Get started with Remote Desktop on Mac](https://docs.microsoft.com/en-gb/windows-server/remote/remote-desktop-services/clients/remote-desktop-mac#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by dawnwood** [comment]
Thanks for reaching out to the Windows content team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use this information. I see you found the [Windows Server Forum](https://social.technet.microsoft.com/Forums/windowsserver/en-US/home). Did you try posting your question there? The community there is quite responsive. Again, thanks for reaching out. Best of luck with this issue.
