### ISSUE TITLE
Windows Admin Center: FQDN vs AD DNSHostName

### ISSUE THREAD

**Issue by clavrus** [MicrosoftDocs/windowsserverdocs#1174]
I'm unable to add a computer via it's DNS FQDN as it autocorrects to the DNSHostName entry in Active Directory which is not the desired behavior. 

Ex.
Domain = domain.contoso.com
Computer FQDN: compname.bldgname.contoso.com

Actions:

1. Select 'Add' from All Connections
2. Type in compname.bldgname.contoso.com
3. Prompt for credentials and enter
4. Completes and is added as compname.domain.contoso.com (which is not resolvable)

Various workarounds are possible such as adding IP to trusted hosts and connecting that way but is not feasible for us to roll out to our technical community as of yet.

Desired behavior is to take the FQDN input without resolving through AD/autocorrecting.

**Comment by clavrus** [comment]
Correction, adding by IP will also resolve to compname.domain.contoso.com instead of compname.bldgname.contoso.com (most of the time) It will add just the IP sometimes.

**Comment by clavrus** [comment]
Also, adding it via 'Import from TXT' works just fine. It's just the add manual button.

**Comment by jwwool** [comment]
In Windows Admin Center 1809, we've added an option labeled "Don't attempt to resolve the server name." Selecting this option will resolve your issue.
