### ISSUE TITLE
Make it clear that mklink requires admin rights for most operations

### ISSUE THREAD

**Issue by mungojam** [MicrosoftDocs/windowsserverdocs#1177]
I think the only one that doesn't require admin rights is creating a directory junction `/j`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe72a6d-c0c6-8cc1-fc16-9912594fbe3e
* Version Independent ID: b6ce16a6-8f41-5551-d55f-244238814459
* Content: [mklink](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink)
* Content Source: [WindowsServerDocs/administration/windows-commands/mklink.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/mklink.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by jantari** [comment]
Hey, just found this issue.

I realize it was closed without a reason given, but just wanted to add that you are also incorrect. One does NOT need admin rights to create a symbolic link for example, you just need `SeCreateSymbolicLinkPrivilege` which can be granted to anyone - including non-admins
