### ISSUE TITLE
WAC Installation problem and URL

### ISSUE THREAD

**Issue by FranzSchenk** [MicrosoftDocs/windowsserverdocs#1178]
Install WAC on Server 2016 with GUI and an existing Web Server certificate. Can't make it work at all.
What is strange that the URL according the documentation should be https://srv.domain.com. On our server, the URL that the admin center installation creates is https://domain.com/

Also, can't manage anything or add a system, not even the local host where Admin Center is installed. Get SMEGateway Events "401 - PSRemotingTransportException: Connecting to remote server sa failed with the following error message : Access is denied. "

**Comment by jwwool** [comment]
It looks like you used a wildcard certificate, this is not supported. you can add your vote to the request here: https://windowsserver.uservoice.com/forums/295071-management-tools/suggestions/33990187--security-certificate-wildcard-certificate
