### ISSUE TITLE
Conflicting advice around disabling the built-in "Administrator" account.

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/windowsserverdocs#1182]
FYI, this section:
> # Configuring GPOs to Restrict Domains' Administrator Accounts on Domain-Joined Systems
> Although disabling the Administrator account in a domain makes the account effectively unusable, you should implement additional restrictions on the account in case the account is inadvertently or maliciously enabled. Although these controls can ultimately be reversed by the Administrator account, the goal is to create controls that slow an attacker's progress and limit the damage the account can inflict.

... conflicts with the updated advice from [Appendix D: Securing Built-In Administrator Accounts in Active Directory](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/appendix-d--securing-built-in-administrator-accounts-in-active-directory), where the note at the top of the page advises it is no longer recommended to disable the Administrator account.

It's not necessarily saying in this article to go and disable the Administrator account, but it does refer to it as a working solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19620533-3f60-a1cb-a679-ff6ff5dde2bc
* Version Independent ID: 54583dac-de23-b64c-3396-fac964724595
* Content: [Implementing Least-Privilege Administrative Models](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/implementing-least-privilege-administrative-models)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Implementing-Least-Privilege-Administrative-Models.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Implementing-Least-Privilege-Administrative-Models.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by MicrosoftGuyJFlo** [comment]
Resolved in private repo PR 10491

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
