### ISSUE TITLE
InputProvider documentation seems incorrect

### ISSUE THREAD

**Issue by FallenGameR** [MicrosoftDocs/windowsserverdocs#1183]
Right now it is the same as for the Enabled. But according to https://docs.microsoft.com/en-us/windows/desktop/sysinfo/registering-a-time-provider InputProvider just specifies if provider is input or output.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc978a2-5a8b-c6af-0c56-f762ea9edf16
* Version Independent ID: 33693e91-d1a2-10c0-0dd7-43167114868a
* Content: [Windows Time Service Tools and Settings](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings)
* Content Source: [WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
Hi @FallenGameR, let me pass this onto the engineer working on Windows Time Service for clarification.

**Comment by shortpatti** [comment]
Talked to the engineer and technically the content is correct; however, it does need to be rewritten for clarity.  I am working with them to correct the confusion.
