### ISSUE TITLE
Changing default ports

### ISSUE THREAD

**Issue by gigarun** [MicrosoftDocs/windowsserverdocs#1185]
hi, using webserver and remote desktop services on différents ports (also published collections on used ports by powershell), but no way to get remoteapp launcher working...only rdp access et https access is ok.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Product: **windows-server-threshold**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Heidilohr** [comment]
I’m sorry to hear you’re having problems with the web client. If you’re not able to fix it using the information here, please reach out using the email address found on the About page of the client.
