### ISSUE TITLE
Wrong Command in Prerequisites

### ISSUE THREAD

**Issue by huzzeytech** [MicrosoftDocs/windowsserverdocs#1188]
https://docs.microsoft.com/en-us/windows-server/networking/core-network-guide/cncg/server-certs/prepare-the-capolicy-inf-file#create-the-capolicyinf-file

Step 1 should be correct to the following:
1. On the computer where you are planning to install AD CS, open Windows PowerShell, type notepad c:\CAPolicy.inf and press ENTER.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8ffdaef-7179-7cfc-ceb3-7443fe3e9476
* Version Independent ID: e5c1e3a8-9b73-d314-df06-c6da3a3adf67
* Content: [Prepare the CAPolicy.inf File](https://docs.microsoft.com/en-us/windows-server/networking/core-network-guide/cncg/server-certs/prepare-the-capolicy-inf-file#create-the-capolicyinf-file)
* Content Source: [WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Prepare-the-CAPolicy-inf-File.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Prepare-the-CAPolicy-inf-File.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@huzzeytech, Thank you :) I'll get the information updated.
