### ISSUE TITLE
Missing Image

### ISSUE THREAD

**Issue by huzzeytech** [MicrosoftDocs/windowsserverdocs#1189]
The following illustration depicts the pkiview results pane with a status of OK for all items.

![adcs_pkiviewmedia/adcs_pkiview.png) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ebaa641-a80b-3555-30c3-b047c9acdf3c
* Version Independent ID: d6b6fee7-4468-bfea-c231-4c6c40028c50
* Content: [Copy the CA Certificate and CRL to the Virtual Directory](https://docs.microsoft.com/en-us/windows-server/networking/core-network-guide/cncg/server-certs/copy-the-ca-certificate-and-crl-to-the-virtual-directory)
* Content Source: [WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Copy-the-CA-Certificate-and-CRL-to-the-Virtual-Directory.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Copy-the-CA-Certificate-and-CRL-to-the-Virtual-Directory.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
Removed the image; added some detail to the step referencing the image so that it's clear.
