### ISSUE TITLE
"Avoid Write-Host" needs elaboration

### ISSUE THREAD

**Issue by aydeisen** [MicrosoftDocs/windowsserverdocs#119]
[Avoid Write-Host](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/performance-tuning/powershell/script-authoring-considerations.md#avoid-write-host) should mention that the primary purpose of Write-Host is to format the console, and clarify whether [Console]::WriteLine() is the .NET alternative to it.

There should also be mention of other ways to provide output, such as Write-Output.  Taking some of the information from [Jeffrey Snover's blog](http://www.jsnover.com/blog/2013/12/07/write-host-considered-harmful/) may be beneficial for this section

**Comment by lzybkr** [comment]
This document is not meant to teach PowerShell - just to raise awareness for common aspects of PowerShell that do not perform well, but it is worth clarifying that `[Console]::WriteLine()` is only a suitable alternative for specific hosts like `powershell.exe` or `powershell_ise.exe` - not guaranteed to work in all hosts.

**Comment by aydeisen** [comment]
I understand.  The older TechNet blogs talking about avoiding Write-Host always mention Write-Output the alternative.  So, not seeing it in that section seemed to me to be a glaring omission.

**Comment by lizap** [comment]
I've edited the section in question as follows. "Write-Output" is a link, but that's not rendering here. This change should go live later today; as such, I'm closing this issue.

> It is generally considered poor practice to write output directly to the console, but when it makes sense, many scripts use Write-Host.
> 
> If you must write many messages to the console, Write-Host can be an order of magnitude slower than [Console]::WriteLine(). However, be aware that [Console]::WriteLine() is only a suitable alternative for specific hosts like powershell.exe or powershell_ise.exe - it's not guaranteed to work in all hosts.
> 
> Instead of using Write-Host, consider using Write-Output.
