### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by onekz** [MicrosoftDocs/windowsserverdocs#1194]
Typo in "dosplayed" word: "Once the virtual machine has been created, it will be dosplayed in Hyper-V manager"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 414a9139-0144-64c3-63d4-ad713cd66d5b
* Version Independent ID: 7c91e247-4a93-8f5b-c55b-0f38ef23a3eb
* Content: [Cluster Sets](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/Cluster-Sets)
* Content Source: [WindowsServerDocs/storage/storage-spaces/Cluster-Sets.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/Cluster-Sets.md)
* Product: **windows-server-threshold**
* GitHub Login: @JohnMarlin-MSFT

**Comment by dawnwood** [comment]
Thank you for the note. The spelling error is fixed.
