### ISSUE TITLE
Architecture Guidance is wrong for RDWEB

### ISSUE THREAD

**Issue by bskeg** [MicrosoftDocs/windowsserverdocs#1195]
The current guidance to install RDWeb is extremely misleading, to initially configure the RDweb role it must be done using domain credentials, not ideal if your expecting to store this VM in a DMZ which is also the recommended practice. This has caused me issues on a current project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 428e9e07-ca35-27d2-e63a-92930cec0118
* Version Independent ID: 9a452a85-9afa-42d5-f319-bf1c4c50d01d
* Content: [Remote Desktop Services architecture](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/desktop-hosting-logical-architecture)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/Desktop-hosting-logical-architecture.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/Desktop-hosting-logical-architecture.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
#please-close
