### ISSUE TITLE
Applies to 2012r2 also?

### ISSUE THREAD

**Issue by PlateSpinner** [MicrosoftDocs/windowsserverdocs#1197]
I can't figure out why should this content not apply to AD FS 2012r2 also. The content of the page seems to match this one which is labeled for server 2012 technical preview: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn823754(v=ws.11)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce6494d8-d525-8961-8dff-c5ee55a18849
* Version Independent ID: a3608a5f-26ed-1a93-2cd2-2fe2e5238248
* Content: [Configure AD FS to authenticate users stored in LDAP directories](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-to-authenticate-users-stored-in-ldap-directories)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-to-authenticate-users-stored-in-LDAP-directories.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-to-authenticate-users-stored-in-LDAP-directories.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by iisahre** [comment]
Configure AD FS to authenticate users stored in LDAP directories

I executed  the cmdlet '$vendorDirectory = New-AdfsLdapServerConnection –HostName adserver.contoso.com –Port 389 –SslMode None –AuthenticationMethod Basic –Credential $DirectoryCred' met error, error info is : 
New-AdfsLdapServerConnection : The term 'New-AdfsLdapServerConnection' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:20
+ $vendorDirectory = New-AdfsLdapServerConnection -HostName adserver.contoso.com -P ...
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-AdfsLdapServerConnection:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundExceptionpelease help me

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by bradsen** [comment]
Hi, may I know the solution to this? Why is it that we cannot apply this command (New-AdfsLdapServerConnection) in windows server 2012. Is there a workaround for this?
