### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by hannahfowler1217** [MicrosoftDocs/windowsserverdocs#1199]
The link for "Microsoft Support article 947226" leads to a page that no longer exists

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e0cba7a-810b-91ff-c475-c3fe4cea7138
* Version Independent ID: 5b0708d3-f400-2f9a-0ec3-f4f2e5e8b487
* Content: [Appendix L - Events to Monitor](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/appendix-l--events-to-monitor)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/Appendix-L--Events-to-Monitor.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/Appendix-L--Events-to-Monitor.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
This should be assigned to @MicrosoftGuyJFlo
