### ISSUE TITLE
Is defining SchUseStrongCrypto still necessary for Server 2016 ADFS?

### ISSUE THREAD

**Issue by RamblingPSTech** [MicrosoftDocs/windowsserverdocs#1200]
The microsoft document dotnet framework network-programming tls states that "If your app targets .NET Framework 4.6 or later versions, this key defaults to a value of 1". Since Server 2016 is shipped with donet 4.6.2 one would like to assume that the ADFS service development target framework would have also been updated to dotnet 4.6. Is ADFS on Server 2016 still targeting dotnet 4.5 which requires SchUseStrongCrypto  to be manually set or is setting SchUseStrongCrypto  for ADFS on Server 2016 pointless? This document does seem to indicate SchUseStrongCrypto  is still required but is that really accurate?
Ref: https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ae56e74-1346-a822-2800-70db6d365376
* Version Independent ID: ccf848e1-5276-1f3f-73e8-036dba9c66a7
* Content: [Managing SSL/TLS Protocols and Cipher Suites for AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/manage-ssl-protocols-in-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Manage-SSL-Protocols-in-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Manage-SSL-Protocols-in-AD-FS.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by use-theforce** [comment]
Yes, it is still necessary. This has been verified in our ADFS environment [ADFS 4] where relying party's have disabled TLS1 and no longer able to monitor their federation metadata. After applying this registry, it fixed our issue.
