### ISSUE TITLE
Like si te dice " La aplicación C:\windows\system32\autoconv.exe no se puede ejecutar en modo Win32." :v

### ISSUE THREAD

**Issue by PabloJoaquin** [MicrosoftDocs/windowsserverdocs#1205]
Sólo eso...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a9bb4bd-cb9a-790c-1681-17e3fa99b19b
* Version Independent ID: 104b2911-8d97-7a51-4921-5fadedd93dab
* Content: [autoconv](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/autoconv)
* Content Source: [WindowsServerDocs/administration/windows-commands/autoconv.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/autoconv.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
#please-close
