### ISSUE TITLE
Unable to initialize disk for SSD

### ISSUE THREAD

**Issue by killerpenguin12** [MicrosoftDocs/windowsserverdocs#1208]
Here is the screen shot:
![ssdproblem](https://user-images.githubusercontent.com/35267092/43088349-2d78eed4-8e5f-11e8-8cf6-64e745e8b1ff.PNG)
The drive also shows the incorrect capacity. It is only a 250GB. When I refresh the disk management this is the look of the screen:
![ssdproblem1](https://user-images.githubusercontent.com/35267092/43088438-626a4f70-8e5f-11e8-8cb6-44b45bb9dd77.PNG)

**Comment by dawnwood** [comment]
Thanks for reaching out to the Windows content team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use this information. You may have success posting your question in the [Windows Server forum](https://social.technet.microsoft.com/Forums/windowsserver/en-US/home), where other users and Microsoft engineers can be found. The community there is quite responsive. Again, thanks for reaching out. Best of luck with this issue.
