### ISSUE TITLE
RDS Webclient - Labels are not showing correctly and wont connect to resources

### ISSUE THREAD

**Issue by PaulStirling** [MicrosoftDocs/windowsserverdocs#1212]
![resourceslabel](https://user-images.githubusercontent.com/39282583/43117343-6cfe478c-8f60-11e8-92b8-128aa5047a10.JPG)
![logginglabel](https://user-images.githubusercontent.com/39282583/43117344-6d2dea50-8f60-11e8-876c-5fbad08f221e.JPG)
![menulabel](https://user-images.githubusercontent.com/39282583/43117345-6d591e0a-8f60-11e8-8b22-4974c54011a3.JPG)

All through the preview we have had the labels displaying as code entries. And the remoteapps/desktops never launch.
I thought this was a preview thing, however it continues with the full release.
For example

when logging in instead of 'username' + 'password' labels, you see 'USER_NAME_LABEL' and 'PASSWORD_LABEL' and to continue you click the button with 'BUTTON_SIGNIN'.

Once logged in you, see the remoteapps/desktops but continue to have the labels incorrect and they don't launch with no error.

Accessed in and out of our network, chrome, edge, ie and firefox all the same thing.

See screenshots.

**Comment by IngridAtMicrosoft** [comment]
#please-close
