### ISSUE TITLE
Firewall rules break trust betweeen domain and workstation

### ISSUE THREAD

**Issue by CoMMyCZ** [MicrosoftDocs/windowsserverdocs#1215]
Should be noted that if you use the firewall rules included in the package for GPO "PAW Configuration - Computer" you will most likely end up with a broken trust relationship between PAW and Domain because of missing TCP 53 outbound rule for DNS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd5878a8-a83e-e75d-ddae-59edc04e7138
* Version Independent ID: 0f0cbbe4-20da-3abe-1a7c-effc608d8cca
* Content: [Privileged Access Workstations](https://docs.microsoft.com/en-us/windows-server/identity/securing-privileged-access/privileged-access-workstations)
* Content Source: [WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by SteveUnderScoreN** [comment]
Please refer to https://github.com/SteveUnderScoreN/WindowsFirewall for the scripts and policies that will create group policies containing the firewall rules required for the PAW.

**Comment by IngridAtMicrosoft** [comment]
#please-close
