### ISSUE TITLE
Windows update broke my share resources (file system).

### ISSUE THREAD

**Issue by laurentcau** [MicrosoftDocs/windowsserverdocs#1217]
That was working well until a recent windows update.
All settings seem to be ok. I don't see how to access the "Connect to ..." dialog to check the configuration.
Any idea ?
Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d05b53f-c597-cd63-e8e6-9c6ec2b707aa
* Version Independent ID: 3f90196e-fb81-2906-55d0-9dac0a6a7367
* Content: [Use local resources on Hyper-V virtual machine with VMConnect](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/learn-more/use-local-resources-on-hyper-v-virtual-machine-with-vmconnect)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/learn-more/Use-local-resources-on-Hyper-V-virtual-machine-with-VMConnect.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/learn-more/Use-local-resources-on-Hyper-V-virtual-machine-with-VMConnect.md)
* Service: **na**
* Product: **windows-server-threshold**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathyDav**

**Comment by lizap** [comment]
Thanks for reaching out to the Windows content team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use this information. You may have success posting your question in the [Hyper-V forum](https://social.technet.microsoft.com/forums/windowsserver/en-us/home?forum=winserverhyperv), where other users and Microsoft engineers can be found. The community there is quite responsive. Again, thanks for reaching out. Best of luck with this issue.
