### ISSUE TITLE
ReFS and Deduplication

### ISSUE THREAD

**Issue by drdmohssine** [MicrosoftDocs/windowsserverdocs#1219]
As i know data Deduplicaton Supports ReFS on Windows Server 2016-1709 Build
But that isn't mentioned on this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5fc5666-93ee-1dde-2342-a171a22620f7
* Version Independent ID: f252b465-87fc-e0ed-7676-a60f2cd627de
* Content: [Planning volumes in Storage Spaces Direct](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/plan-volumes)
* Content Source: [WindowsServerDocs/storage/storage-spaces/plan-volumes.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/plan-volumes.md)
* Product: **windows-server-threshold**
* GitHub Login: @cosmosdarwin
* Microsoft Alias: **cosdar**

**Comment by dawnwood** [comment]
Hi @drdmohssine , apologies for the late reply. I am following up with the subject matter expert. I will keep this issue open until we have an update.
Best,
Dawn

**Comment by illfated** [comment]
(ref. #5211, #1219, #2482, #3809)

**Comment by IngridAtMicrosoft** [comment]
#please-close
