### ISSUE TITLE
Windows Insider Program Feature

### ISSUE THREAD

**Issue by ang216** [MicrosoftDocs/windowsserverdocs#1220]
Hi, can you please indicate more clearly that this is a Windows Server Insider Program feature? Currently this is only mentioned as an afterthought at the end of the first paragraph and again at the bottom of the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65558184-a52d-7b81-c2ed-874fe85078a4
* Version Independent ID: fe830182-032f-8bd4-bd8f-3dd1afd8bb11
* Content: [Use performance counters to diagnose application responsiveness problems on Remote Desktop Session Hosts](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-rdsh-performance-counters#download-windows-server-insider-software)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-rdsh-performance-counters.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-rdsh-performance-counters.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by lizap** [comment]
That's a great point - we'll get this updated to be more clear and to include info at the top of the article that specifies the OS versions that include these counters. Thanks.

**Comment by mcheve01** [comment]
Is there a way you can use these performance counters in a VDI setup?  This only talks about session host servers.  I have many RDVH servers setup and would like something like this for my setup.  Maybe you already know of a way to performance troubleshoot them in my situation?
