### ISSUE TITLE
OneNote Clipper doesn't capture the table

### ISSUE THREAD

**Issue by icdeadppl4u** [MicrosoftDocs/windowsserverdocs#1224]
When using Edge Beta and the OneNote Clipper in article mode, the table is missing in the clipped article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588d12d1-fdd1-892a-eb5e-9e2d86302368
* Version Independent ID: 5eceac91-1d90-a663-2856-19e13da59351
* Content: [Remote Desktop clients](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-clients)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by icdeadppl4u** [comment]
The table is still not being captured by the OneNote Clipper v3.8.0 using Edge Beta v43.18204.1001.0 on Windows 10 Pro Insider Preview v19H1 build 18204.1001.

**Comment by icdeadppl4u** [comment]
The table is still not being captured by the OneNote Clipper extension v3.8.0 using the Article clipping mode within Edge Beta v43.18204.1001.0 on Windows 10 Pro Insider Preview v19H1 build 18204.1001.

Thanks,
Al

Al Grosser
Icdeadppl4u@live.com<mailto:Icdeadppl4u@live.com>
+1 (480) 435-3008

________________________________

**Comment by dawnwood** [comment]
Thanks for reaching out to the Windows content team. Unfortunately, the content team is are not able to triage or fix issues with products. The feedback link is meant to allow you to provide feedback on the content you've read. 
I would suggest that you use the Windows Feedback Hub, which you can reach by typing Feedback in the search box.  
Again, thanks for reaching out. Best of luck with this issue.
