### ISSUE TITLE
What are the different link types?

### ISSUE THREAD

**Issue by timtribers** [MicrosoftDocs/windowsserverdocs#1230]
Please provide an explanation of the different sorts of links.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe72a6d-c0c6-8cc1-fc16-9912594fbe3e
* Version Independent ID: b6ce16a6-8f41-5551-d55f-244238814459
* Content: [mklink](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink)
* Content Source: [WindowsServerDocs/administration/windows-commands/mklink.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/mklink.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by coreyp-at-msft** [comment]
Hi @timtribers ,

There are **symbolic links**, **hard links** and **junctions** (aka soft links). We have documentation on the link types here:

[https://docs.microsoft.com/en-us/windows/desktop/FileIO/symbolic-links](https://docs.microsoft.com/en-us/windows/desktop/FileIO/symbolic-links)
[https://docs.microsoft.com/en-us/windows/desktop/FileIO/hard-links-and-junctions](https://docs.microsoft.com/en-us/windows/desktop/FileIO/hard-links-and-junctions)

We will add these links to this page ASAP, or you are welcome to submit a PR of your own to do the same in the meantime.

Thanks,
Corey

**Comment by timtribers** [comment]
You folks at Microsoft are so impressive these days - everything
(documentation in this case) is being put on to such a sensible basis,
opened up, and well supported.  You are winning back a hardened old dev
like me.  Thanks.


*  REVOLUTIOИARYsystems*

*​m:  *
+44 (0)7760 654640

*w:  *www.revolutionarysystems.co.uk
*a:  *Penvose House, Broad Lane, Upper Bucklebury, Reading, Berkshire, RG7
6QH

**Comment by thisIsMikeKane** [comment]
I'm not sure why this issue is closed, when the links still need to be added to this page. 

In addition to the descriptions from the links above, a summary table of the impact of each type of link would be helpful ([example](https://www.computerhope.com/mklink.htm)).

**Comment by thisIsMikeKane** [comment]
Sorry, linked to the wrong page in my previous comment. Here is a great summary table example 
https://ss64.com/nt/mklink.html
