### ISSUE TITLE
AIA needs _ to match default settings.

### ISSUE THREAD

**Issue by schnitz76** [MicrosoftDocs/windowsserverdocs#1231]
Steps 12 and 14 need an _ between `<ServerDNSName><CaName>` to match out of the box settings.
Example (step 12):
`http://pki.corp.contoso.com/pki/<ServerDNSName><CaName><CertificateName>.crt`
should be:
`http://pki.corp.contoso.com/pki/<ServerDNSName>_<CaName><CertificateName>.crt`

**Comment by shortpatti** [comment]
@schnitz76, thank you for catching the error. I've fixed it.
