### ISSUE TITLE
Additional references error

### ISSUE THREAD

**Issue by sttelv** [MicrosoftDocs/windowsserverdocs#1236]
Hi,

The hyperlink under additional references links to the URL

assetid:53582ab0-24a0-411c-9c7a-7b2466741699

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f03e2a9-c986-b6f4-2eda-6368e367544e
* Version Independent ID: 91d8322a-f47b-1067-7b31-313cc66a61e9
* Content: [perfmon](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/perfmon)
* Content Source: [WindowsServerDocs/administration/windows-commands/perfmon.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/perfmon.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by coreyp-at-msft** [comment]
Hi @sttelv ,

Thanks for bringing this to our attention. I've redirected the link here:

[https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc749154(v%3dws.11)](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc749154(v%3dws.11))

Thanks,
Corey
