### ISSUE TITLE
Text cursor visible in figure

### ISSUE THREAD

**Issue by Dottn** [MicrosoftDocs/windowsserverdocs#1238]
The last figure of the document has a clearly visible text cursor between the on-premise web browser and the web server (|HTTPS).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfc1fd4d-4e12-880f-20ab-85bc1436059a
* Version Independent ID: 25d6854b-8a38-eec1-b638-b150b1fbf8fa
* Content: [Windows Server Software-Defined Datacenter](https://docs.microsoft.com/en-us/windows-server/sddc)
* Content Source: [WindowsServerDocs/sddc.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/sddc.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Resolved in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/881e73bbdc5c15237526c24bb07068a18a138731

#please-close
