### ISSUE TITLE
Connection lists

### ISSUE THREAD

**Issue by Dottn** [MicrosoftDocs/windowsserverdocs#1239]
Are connection lists personal? How to share the connection list with a co-worker? 

I've just installed wac as a gateway, and after creating and tagging a connection list, I pointed a co-worker towards the solution. They only found the gateway server in the list. Is this working as intended?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99fcece9-57ba-c2cb-a4a4-4d9188490bd5
* Version Independent ID: 63fd5c3b-76c7-a45f-1700-6fdb81706aee
* Content: [Manage Servers with Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/manage-servers)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/use/manage-servers.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/use/manage-servers.md)
* Product: **windows-server-threshold**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by jwwool** [comment]
Yes connection lists are personal.
