### ISSUE TITLE
No error message possible with SP initiated sign-in

### ISSUE THREAD

**Issue by JGSPIERS** [MicrosoftDocs/windowsserverdocs#1242]
The documentation should be updated to state that when using ADFS 2016 with Azure MFA as an IdP, if you perform SP initiated sign-in and the authenticating user is not registered with Azure MFA, it is not possible to present an error message to the user telling them to register with Azure MFA. Instead an assertion is send from ADFS to SP and an error message is displayed to the user.

It seems from my findings and from speaking with Microsoft support that displaying this error message via onload.js is only possible for IdP initiated sign-ins. I find this bizarre and it leads ultimately to a poor user experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae96cfcf-0a50-7e13-30c8-43e3730e184f
* Version Independent ID: 9d8ed7b7-eec6-1b95-40b8-24a13361f66d
* Content: [Configure AD FS 2016 and Azure MFA](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md)
* Product: **windows-server-threshold**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by thibaultchatiron** [comment]
Yes, you're right ! 
The message is only displayed for IdP-init sign-ins. In case of the use of the SAML protocol, the assertion is sent to the app with a bad status when SP-init sign-ins.

The message should be displayed for SP-init in case of WS-Fed protocol

For the SAML app, you can try to access to the app via the IDP-init way via the URL : 
https://_<ADFS FQDN>_/adfs/ls/idpinitiatedsigon.aspx?LogintoRP=_<identifier>_

**Comment by MicrosoftGuyJFlo** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
