### ISSUE TITLE
Promote this entire chapter/section

### ISSUE THREAD

**Issue by fielcabral** [MicrosoftDocs/windowsserverdocs#1247]
"TLS - SSL (Channel SSP)" is very important so it should be promoted or highlighted in some top level page about securing Windows systems. Cheers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38fcd9dd-91c8-e79b-5f4d-28a435a8ada8
* Version Independent ID: 0d79a0c8-0b73-c783-4d5c-b107d24acf55
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server-threshold**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@fielcabral thanks for the suggestion. I added an entry for TLS at the top page here: https://docs.microsoft.com/en-us/windows-server/security/security-and-assurance

**Comment by fielcabral** [comment]
Thank you Justin.
