### ISSUE TITLE
Custom ADFS Proofup with script error from Skype

### ISSUE THREAD

**Issue by clanwoverine** [MicrosoftDocs/windowsserverdocs#1261]
To implement ADFS Azure MFA. We added the following in onload.js for user to proof up. But users are getting script error when logging on from Skype for business. The error is "Unable to get property 'innerHTML' of undefined or null reference".

if (document.getElementById('errorMessage').innerHTML.search("The selected authentication method is not available") ) { 
errorMessage.innerHTML = 'You must first set up your Multi-Factor Authentication profile. Please go to &lt;a href="https://aka.ms/mfasetup"&gt;https://aka.ms/mfasetup&lt;/a&gt;, and then try again.'; 
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae96cfcf-0a50-7e13-30c8-43e3730e184f
* Version Independent ID: 9d8ed7b7-eec6-1b95-40b8-24a13361f66d
* Content: [Configure AD FS 2016 and Azure MFA](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md)
* Product: **windows-server-threshold**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by solarfusionuk** [comment]
Microsoft example code needs to be updated to include an extra "if" under "var errorMessage" e.g.
var errorMessage = document.getElementById("errorMessage");
if (errorMessage) {

**Comment by cwanized** [comment]
is this issue fixed? I still get the Script error in multiple environments
