### ISSUE TITLE
/inheritance flag?

### ISSUE THREAD

**Issue by bendodge-xwis** [MicrosoftDocs/windowsserverdocs#1264]
I see that the /inheritance option exists, but I don't see any documentation for it in this article, or else I'm misreading it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a990d09-b5b1-3aba-de57-0aec79c12784
* Version Independent ID: 36d90c17-ba95-4ed6-de9d-f379dcad6c4d
* Content: [icacls](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/icacls#BKMK_examples)
* Content Source: [WindowsServerDocs/administration/windows-commands/icacls.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/icacls.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by lizap** [comment]
Thanks for the feedback - I've updated the article.
