### ISSUE TITLE
Unclear How SmartCard Authentication Works

### ISSUE THREAD

**Issue by thesmall** [MicrosoftDocs/windowsserverdocs#1269]
After reading and re-reading the section on SmartCard Authentication, I've come to the conclusion that this functionality only works in scenarios where Azure is involved, but its not at all clear by the documentation whether or not that's true. I am relatively confident that there is no such thing as a "smartcard-based security group" feature available in an on-premises install of Active Directory Domain Services, even when the Forest and Domain functional levels are raised to 2016, and subsequently, adding a normal security group to the Gateway - defined as a SmartCardGroup -  when Azure is not part of the implementation does not result in any multifactor features being enabled for those accounts that are a member of the group.. 

If this is indeed the case, the documentation should be updated to reflect and clarify that SmartCardGroup functionality is only available when Azure is acting as authentication mechanism to access the gateway.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6273f49-fe06-5a18-80e3-863bd3a0cf4e
* Version Independent ID: 4ed5bf3d-0c2a-a80e-5bd9-0e858dd8749b
* Content: [Configuring user access control and permissions](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/configure/user-access-control)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/configure/user-access-control.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/configure/user-access-control.md)
* Product: **windows-server-threshold**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by jwwool** [comment]
This functionality is only for on-premises Active Directory. An example of a "smartcard-based security group" feature is Authentication Mechanism Assurance ([AMA](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd378897(v=ws.10))), however any group membership based just-in-time administration service will work.
