### ISSUE TITLE
This page is not accessible from the left side "Contents" pane

### ISSUE THREAD

**Issue by Kevin-He-DVHS** [MicrosoftDocs/windowsserverdocs#1270]
[This page](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/set_1) is not accessible from the left side pane. You can test this by inputting `set` into the "Filter by Title" box on the left. It is only accessible from the [S Index](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands#BKMK_s) on [Windows Commands](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands) page.
### Expected Behavior
This page should be shown in the results from a "Filter by title" search on the left side contents pane. This page should be highlighted in the "Contents" pane.

A demonstration of what is meant by "highlighted":
![cmd](https://user-images.githubusercontent.com/32375681/43531131-252f6a58-957d-11e8-8a72-e76dea126691.png)

### Actual Behavior
This page has a weird title: `set_1` rather than `set` and is not accessible except going through the alphabetical index. This page is not highlighted on the left side "Contents" pane:
![set_1](https://user-images.githubusercontent.com/32375681/43531184-48c3fc40-957d-11e8-9a0f-3d1e231e7c06.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa28d438-585b-ba81-ef47-922d2048adb1
* Version Independent ID: 5f8af166-49b8-dd96-1630-a38c723bdb6a
* Content: [set_1](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/set_1)
* Content Source: [WindowsServerDocs/administration/windows-commands/set_1.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/set_1.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by lizap** [comment]
Thanks for the feedback - I've updated the article.
