### ISSUE TITLE
Step 14 is invalid

### ISSUE THREAD

**Issue by thepkiguy** [MicrosoftDocs/windowsserverdocs#1272]
ADCS is unable to publish the AIA certificate to any path other than the default c:\windows\system32\certsrv\certenroll and (if applicable) Active Directory. Step 14 will not work as ADCS will not honor the request to publish the certificate in the remote location. This does however work for CRL files via the CDP extension. Step 14 should be removed. The Certificate will need to be manually copied to the desired location.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2929b93e-fe36-d3e4-ee28-2a4aaf977da6
* Version Independent ID: 689f7606-45b0-3444-65dc-85c2ba217e9b
* Content: [Configure the CDP and AIA Extensions on CA1](https://docs.microsoft.com/en-us/windows-server/networking/core-network-guide/cncg/server-certs/configure-the-cdp-and-aia-extensions-on-ca1)
* Content Source: [WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Configure-the-CDP-and-AIA-Extensions-on-CA1.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Configure-the-CDP-and-AIA-Extensions-on-CA1.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@thepkiguy, so that I'm clear, the transition from step 13 to the next step is to "Manually copy the certificate to the desired location."?

**Comment by thepkiguy** [comment]
Technically 14 isn't needed at all. The very next doc https://docs.microsoft.com/en-us/windows-server/networking/core-network-guide/cncg/server-certs/copy-the-ca-certificate-and-crl-to-the-virtual-directory has the user copying the files. There are issues in that doc so I will post separately on that doc.

**Comment by shortpatti** [comment]
You are awesome!!  Thank you.  I'll take a look at your comments for the other doc and then figure a way to transition it better :)

**Comment by thepkiguy** [comment]
Excellent!

**Comment by shortpatti** [comment]
@thepkiguy, I've made the change.

**Comment by shortpatti** [comment]
@thepkiguy, if you're interested in contributing to the content, such as making changes, correcting spelling mistakes, and so on, I can send you the instructions for making your own contributions.  Let me know and I'd be happy to work with you on it :)

**Comment by thepkiguy** [comment]
That would be great. Are you guys planning to bring all of the TechNet ADCS related content over? What's the plan for updating for new OSes?

**Comment by shortpatti** [comment]
I am tasked with bringing the networking topics over from the TechNet Gallery but I'm not aware of the whole plan for the TechNet site in general.  Let me find out about this and the new OSes for you and then I'll send you the contributor information.

**Comment by thepkiguy** [comment]
I would LOVE to nominate some of the critical ADCS docs on TechNet for migration over for updates/tweaks. So whatever you feel like inviting me to participate in as it relates to ADCS I'm game.
