### ISSUE TITLE
Something went wrong while loading your resources.  Trying again...

### ISSUE THREAD

**Issue by blicalzi** [MicrosoftDocs/windowsserverdocs#1273]
Login/auth seemingly works fine, but after that I continuously get "Something went wrong while loading your resources. Trying agian..."
If Duo 2FA for RDWeb is already in place, will this cause and issue accessing the web client setup?

**Comment by Heidilohr** [comment]
@blicalzi I recommend emailing the web client help team at rdwbclnt@microsoft.com. They can help you with any questions the article doesn't answer.
