### ISSUE TITLE
The connection generated an internal exception with disconnect code=GenericByServer(15)

### ISSUE THREAD

**Issue by comptest86** [MicrosoftDocs/windowsserverdocs#1277]
Hi,
I am trying to use webclient configured on w2016 with latest updates. earlier it was failing with certificate length mismatch error.
now after putting certificate, it is failing with error in the webconsole.

The connection generated an internal exception with disconnect code=GenericByServer(15) extended code=1032, reason=DisconnectProviderUltimatum received from server Thrown in thread 0 at: rdplifecyclestate.cpp(75)

No luck in getting it work after trying 3-4 days on this. please suggest is there any way can get glimpse of html5 webclient.

**Comment by lizap** [comment]
Hi - I'm assuming you're trying to use the RD web client - true? (Sorry, we usually get information about the specific article you are on when you came to comment - I don't see that here.) If that's the case, your best bet is going to be emailing the web client support team at rdwbclnt@microsoft.com. Thanks, and good luck.
