### ISSUE TITLE
CRL copy isn't needed

### ISSUE THREAD

**Issue by thepkiguy** [MicrosoftDocs/windowsserverdocs#1278]
In the previous document, the CA was configured to publish the CRL to the website via the file: extension. But in this document you have the user manually copy the CRL. The copy "C:\Windows\system32\certsrv\certenroll\*.crl \\WEB1\pki" isn't needed as the CA will do this automatically. In addition, step 2 isn't needed after copying the file manually.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ebaa641-a80b-3555-30c3-b047c9acdf3c
* Version Independent ID: d6b6fee7-4468-bfea-c231-4c6c40028c50
* Content: [Copy the CA Certificate and CRL to the Virtual Directory](https://docs.microsoft.com/en-us/windows-server/networking/core-network-guide/cncg/server-certs/copy-the-ca-certificate-and-crl-to-the-virtual-directory)
* Content Source: [WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Copy-the-CA-Certificate-and-CRL-to-the-Virtual-Directory.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Copy-the-CA-Certificate-and-CRL-to-the-Virtual-Directory.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
I'm on it :)  Thank you for your help in addressing these inaccuracies.
