### ISSUE TITLE
HTTPS port 443 is listed as HTTP 443 

### ISSUE THREAD

**Issue by gretchunkim** [MicrosoftDocs/windowsserverdocs#1282]
You can replicate over HTTP or encrypted HTTPS. Select Use Kerberos (HTTP) or Use certificate-based Authentication (HTTPS). By default HTTP 80 and HTTP 443  

Above, it should be HTTPS 443 and not HTTP. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02a070e0-13ae-2ec0-fb59-f53e76c447a5
* Version Independent ID: 6689fc76-46a7-5091-0e3b-ddec78385326
* Content: [Set up Hyper-V Replica](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/set-up-hyper-v-replica)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/Set-up-Hyper-V-Replica.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/Set-up-Hyper-V-Replica.md)
* Service: **na**
* Product: **windows-server-threshold**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by shortpatti** [comment]
@gretchunkim, Thank you for pointing this out.  I've made the change.
