### ISSUE TITLE
Cannot connect from RDP web client to Remote App or Full Desktop collection

### ISSUE THREAD

**Issue by alexey-zhel** [MicrosoftDocs/windowsserverdocs#1294]
I'm facing problem in lab environment. All firewalls disabled, certificates installed, RDS farm in per user licensing mode. Traditional Webaccess portal accessible and allowing to launch Remote App, but Web client giving error message: "We couldn't connect to the gateway because of an error. If this keeps happening, ask your admin or tech support for help."
 
ModuleType Version    Name
---------- -------    ----
Script     1.0.1      Microsoft.PowerShell.Operation.V...
Script     1.1.7.2    PackageManagement
Binary     1.0.0.1    PackageManagement
Script     3.4.0      Pester
Script     1.6.6      PowerShellGet
Script     1.0.0.1    PowerShellGet
Script     1.2        PSReadline
Script     1.0.0      RDWebClientManagement

OS Build 14393.2396
NET:  4.7.3081.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Product: **windows-server-threshold**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Heidilohr** [comment]
@alexey-zhel I recommend emailing the web client support team at rdwbclnt@microsoft.com. They can help you with any issues that can't be solved by the troubleshooting recommendations.

**Comment by alexey-zhel** [comment]
Web client does not work in environment with NTLM protocol disabled. Everything start working once I have enabled NTLM.

**Comment by ErLWinner** [comment]
@alexey-zhel . I run into the same issue. Can you be more precise on what you did? Where did you enable the NTLM Protocol settings.
Thanks!

**Comment by alexey-zhel** [comment]
Check if you have set value of following parameter: Computer Configuration -> Policies -> Windows Settings -> Security Settings -> Local Policies -> Security Options -> Network Security: Restrict NTLM: NTLM Authentication in this domain.

It should be set to "Disable" to allow NTLM authentication for all machines.

**Comment by ErLWinner** [comment]
Thank you. I will look in to that.

2018-08-13 20:37 GMT+02:00 alexey-zhel <notifications@github.com>:

**Comment by dennisbaker** [comment]
I ran into a similar issue the solution was registering the NPS in Active Directory. To do this, on the gateway server, launch the Network Policy Server MMC from Admin Tools, right-click the NPS (Local) node, and choose Register Server in Active Directory. I cannot find this step documented anywhere, but they gateway won't function if you don't complete it. It needs to be completed on all gateway servers in a farm if you have one.
