### ISSUE TITLE
Disabling /adfs/services/trust/2005/windowstransport/ proxy endpoint

### ISSUE THREAD

**Issue by JozoSlejko** [MicrosoftDocs/windowsserverdocs#1300]
Disabling the proxy endpoint for /adfs/services/trust/2005/windowstransport/ in the production environment raised an alert from the Azure AD Connect health agent saying that this endpoint is not enabled and should be enabled.
Please investigate if this is an error in this documentation not including this endpoint in the minimum set of proxy enabled endpoints for the AAD/O365 scenarios, or if the Azure AD Connect health agent has wrong parameters to check.
In the ADFS logs we see that there are in fact requests for MicrosoftOnline relying party coming to this endpoint via WAP proxies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a834de4-c696-4599-6ab2-94ae03d31471
* Version Independent ID: 78658bfd-8bcc-0d71-5139-77733f1a795e
* Content: [Best Practices for securing AD FS and Web Application Proxy](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/best-practices-securing-ad-fs#optional-min-set-of-endpoints-proxy-enabled-for-azure-ad--office-365)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Best-Practices-Securing-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Best-Practices-Securing-AD-FS.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
