### ISSUE TITLE
Access Control Policy MFA Loop on Office 365

### ISSUE THREAD

**Issue by kemper451** [MicrosoftDocs/windowsserverdocs#1301]
If I apply an ACP on Office 365 Trust that requires MFA for a particular scenario, the brand new user (that does not have MFA configured yet) gets prompted to setup MFA at aka.ms/mfasetup (via the custom error).  The issue is that access to that MS site is blocked with the very same Office 365 ACP, which results in a big loop.  The first Note at the top indicates that this is adjusted to allow this scenario but my testing does not show any success.  I would love to create an exception in the ACP for users that have not yet configured MFA to only be able to access the mfasetup pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae96cfcf-0a50-7e13-30c8-43e3730e184f
* Version Independent ID: 9d8ed7b7-eec6-1b95-40b8-24a13361f66d
* Content: [Configure AD FS 2016 and Azure MFA](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md)
* Product: **windows-server-threshold**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by DawnRaj** [comment]
Has this issue been solved ? I am facing the same issue with an unregistered user. Is there a work around ?

**Comment by IngridAtMicrosoft** [comment]
#please-close
