### ISSUE TITLE
Why am I getting mirrored content?

### ISSUE THREAD

**Issue by bypfung** [MicrosoftDocs/windowsserverdocs#1304]
I am trying to use ‘mklink’ to backup my iPhone to an external drive (E:) rather than to the default Apple backup folder on the C: drive since the C: drive doesn’t have enough memory storage.  While I am able to create the link, my problem is that I am getting a copy of everything in both the link folder (on the E: drive) as well as in the target folder (on the C: drive).  Since I don’t have enough memory on C: drive, the operation is canceled when I run a backup, despite the link.

The syntax I am using is:
Mklink  /D  “E:\iphone-backup”  “C:\Users\My Name\AppData\Roaming\Apple Computer\MobileSync\Backup”

where ‘iphone_backup’ is the new folder for the backups that is created on E: drive when mklink is run.  What am I doing wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe72a6d-c0c6-8cc1-fc16-9912594fbe3e
* Version Independent ID: b6ce16a6-8f41-5551-d55f-244238814459
* Content: [mklink](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink)
* Content Source: [WindowsServerDocs/administration/windows-commands/mklink.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/mklink.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by rdegrove** [comment]
Be nice to have an example of creating a link that is not in the root folder. That seems to have some gotchas.
