### ISSUE TITLE
Standardize Debian/Ubuntu operations

### ISSUE THREAD

**Issue by bureado** [MicrosoftDocs/windowsserverdocs#1306]
I was wondering whether we should standardize Debian/Ubuntu APT repo and signing key operations using standard tooling. For example, as tested in `xenial`:

    curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
    sudo apt-add-repository https://packages.microsoft.com/ubuntu/16.04/prod
    
Or an even more aggressive:

    sudo apt-add-repository https://packages.microsoft.com/`lsb_release -is`/`lsb_release -rs`/prod

Thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e7ed059-d77f-6ce0-8501-fc3afd1c8048
* Version Independent ID: f2d249ee-50e4-52b4-4187-954a84a48ec1
* Content: [Linux Software Repository for Microsoft Products](https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software)
* Content Source: [WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md)
* Service: **na**
* Product: **windows-server-threshold**
* GitHub Login: @szarkos
* Microsoft Alias: **szark**

**Comment by szarkos** [comment]
That's certainly fine with me.  I think the two-step approach is more clear for the reader.  Did you want to make a PR? :)

**Comment by bureado** [comment]
For clarity, I'm looking to standardize usage across docs.ms to ensure we use default tools for APT users (Debian and Ubuntu) and that service teams that are providing their own instructions don't deviate from a standard approach.

Here are some usages of:

* [apt-key](https://docs.microsoft.com/en-us/search/index?search=%22apt-key%22)
* [apt-add-repository](https://docs.microsoft.com/en-us/search/index?search=%22apt-add-repository%22)
* [/etc/apt/sources.list](https://docs.microsoft.com/en-us/search/index?search=%22%2Fetc%2Fapt%2Fsources.list%22)

Once I get some guidance here I can file individual PRs with those pages, other things we should standardize on is the usage of sudo, here's:

* [sudo su](https://docs.microsoft.com/en-us/search/index?search=%22sudo+su%22) (less of...)
* [sudo tee](https://docs.microsoft.com/en-us/search/index?search=%22sudo+tee%22) (more of...)

And pinging @listonb for input.

**Comment by szarkos** [comment]
Makes sense.  I'm fine with either approach here.

The repo setup is probably not the worst thing we need to fix in the docs.  Even the Debian and Ubuntu docs are inconsistent here.
