### ISSUE TITLE
images are missing

### ISSUE THREAD

**Issue by sc211166** [MicrosoftDocs/windowsserverdocs#131]
images are missing like this 
https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/media/hyper-v-network-virtualization-technical-details-in-windows-server/VNetF6.gif

**Comment by lizap** [comment]
Hi - I'm seeing that specific graphic rendering in the article: https://docs.microsoft.com/en-us/windows-server/networking/sdn/technologies/hyper-v-network-virtualization/hyperv-network-virtualization-technical-details-windows-server

If you're still seeing this issue, please reopen the issue. Thanks!
