### ISSUE TITLE
BLG to Editable format and back to BLG is that possible?

### ISSUE THREAD

**Issue by agvardha** [MicrosoftDocs/windowsserverdocs#1312]
I want to convert a *.blg file to a editable format, edit the file, convert it back to .blg file. Is that possible? Please advice. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88c7179b-7544-073e-c4d9-0f88db2a4ef3
* Version Independent ID: 7c71336f-7074-dceb-448d-f3d4d7aa377d
* Content: [relog](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/relog)
* Content Source: [WindowsServerDocs/administration/windows-commands/relog.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/relog.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by jasongroce** [comment]
Hi @agvardha , check out the relog command help on the command line or [the online command help](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/relog). This will allow you to convert back and forth between .blg and .csv, which you could then edit.

**Comment by agvardha** [comment]
@jasongroce Thanks and sorry for the late response. I will close this.
