### ISSUE TITLE
Link Missing

### ISSUE THREAD

**Issue by montereyharris** [MicrosoftDocs/windowsserverdocs#1313]
This article appears to be missing the link 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0881a79b-ca1a-79b6-3644-32f8785f5251
* Version Independent ID: da021a5f-eaa0-e9c9-21a6-43d2e89282e5
* Content: [Schannel Security Support Provider Technical Reference](https://docs.microsoft.com/en-us/windows-server/security/tls/schannel-security-support-provider-technical-reference)
* Content Source: [WindowsServerDocs/security/tls/schannel-security-support-provider-technical-reference.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/schannel-security-support-provider-technical-reference.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Justinha** [comment]
@montereyharris Thanks for reporting this. The links are fixed.
