### ISSUE TITLE
Support for Server 2008R2

### ISSUE THREAD

**Issue by KonTheCat** [MicrosoftDocs/windowsserverdocs#1320]
Hello! Could you please include in this doc (or provide in another doc) an outline of what is supported as far as Server 2008R2? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7242a6c0-8f40-bb91-c23e-0081a4d4a94a
* Version Independent ID: 9a1213ac-baf5-c1f3-e735-33a0b818fb6f
* Content: [Supported configurations for Remote Desktop Services](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-supported-config)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-supported-config.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-supported-config.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
#please-close
