### ISSUE TITLE
need an installed updates detail with installed date

### ISSUE THREAD

**Issue by dpugazhendhi** [MicrosoftDocs/windowsserverdocs#1322]
need an installed updates detail with installed date in wsus wid or sql db

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e2a5a31-29b9-5599-2f14-bc244c5da034
* Version Independent ID: 393db29c-0866-46f4-9ee6-7ae82e8cb29f
* Content: [Migrating the WSUS Database from (Windows Internal Database) WID to SQL](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/manage/wid-to-sql-migration)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/manage/wid-to-sql-migration.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/manage/wid-to-sql-migration.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by aydeisen** [comment]
@dpugazhendhi
@dawnwood 

I'm confused to what the request is here, and what Update details and installed date have to do with migrating the WSUS DB from WID to SQL.

Update Details and History can be retrieved from the Windows Update Agent on a specific machine using the [IUpdateSearcher interface](https://docs.microsoft.com/en-us/windows/desktop/api/wuapi/nn-wuapi-iupdatesearcher).  From WSUS, the update details can be retrieved in the [IUpdate interface](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ms752700(v%3dvs.85)) and the install date can be retrieved using the [GetUpdateEventHistory()](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ms747165%28v%3dvs.85%29) method.  I would caution that, [by default, those events are only kept in the WSUS server for 15 days](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ms751937%28v%3dvs.85%29#property-value).

Would you please clarify what the question relates to the article in question?

**Comment by dpugazhendhi** [comment]
Hi

My requirement simple one but I couldn’t find that detail in wsus MMC
console.

Requirement: patch installed date view in wsus server itself.




Regards,
Pugazhendhi D

**Comment by aydeisen** [comment]
@dpugazhendhi The requirement might be simple, but the forum makes no sense.  The issue opened is linked to the specific document pertaining to migrating the database SUSDB from WID to SQL, which has nothing to do with the WSUS MMC console.  It sounds like you're either asking for help or asking for a feature, which would either be posted [ServerFault](https://serverfault.com/questions) or [UserVoice](https://windowsserver.uservoice.com) respectively.

@dawnwood and @coreyp-at-msft would be within their rights as owners and managers of the linked document to close this issue as irrelevant to the document that it's being linked to.

**Comment by IngridAtMicrosoft** [comment]
#please-close
