### ISSUE TITLE
Display details in this article are vague/inadequate/confusing...

### ISSUE THREAD

**Issue by deejerydoo** [MicrosoftDocs/windowsserverdocs#1327]
"Customize your display resolution"
This section should be titled "Customising your Display Options and be broken down into:
1. Resolution
2. Using multiple monitors

"Displays have separate spaces If you are running Mac OS X 10.9 and disabled Displays have separate spaces in Mavericks (System Preferences &gt; Mission Control), you need to configure this setting in the remote desktop client using the same option."

This part doesn't actually say what it's about. It is kind of out of context and confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 526c6220-c5f5-7dce-3239-66e5134cd40e
* Version Independent ID: 598ceeef-0f46-fff1-8528-45c12e112612
* Content: [Get started with Remote Desktop on Mac](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-mac)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by dawnwood** [comment]
Thank you for the feedback @deejerydoo I'll look into your suggestion. 
Best,
Dawn
