### ISSUE TITLE
CTRL+ALT+UP arrow also releases the mouse and keyboard

### ISSUE THREAD

**Issue by marvhen** [MicrosoftDocs/windowsserverdocs#1328]
This appears to be a bug because CTRL+ALT+UP is not one of the configurable key combinations in Hyper-V settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c67eb5e-7fb1-0840-dfe0-40955b3f9489
* Version Independent ID: f30efc81-d336-2ff2-3fe5-5eb3f9432d82
* Content: [Hyper-V Virtual Machine Connection](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/learn-more/hyper-v-virtual-machine-connect#keyboard-shortcuts)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/learn-more/hyper-v-virtual-machine-connect.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/learn-more/hyper-v-virtual-machine-connect.md)
* Product: **windows-server-threshold**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by samrueby** [comment]
Missing the keyboard shortcut for saving the machine state. I know this because I accidentally press it all the time when trying to use the machine and I don't know what I'm pressing to cause it.
