### ISSUE TITLE
Gen 2 Support for openSUSE Leap 15

### ISSUE THREAD

**Issue by ryansun96** [MicrosoftDocs/windowsserverdocs#1329]
Generation 2 VM supports openSUSE Leap15, as has been tested on Windows 10 Pro 1803.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f754d56c-0290-d582-ba2c-b3f0dcc13866
* Version Independent ID: f3062eb0-c4d0-a637-675e-f867ea934877
* Content: [Should I create a generation 1 or 2 virtual machine in Hyper-V?](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/plan/should-i-create-a-generation-1-or-2-virtual-machine-in-hyper-v)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/plan/Should-I-create-a-generation-1-or-2-virtual-machine-in-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/plan/Should-I-create-a-generation-1-or-2-virtual-machine-in-Hyper-V.md)
* Service: **na**
* Product: **windows-server-threshold**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by IngridAtMicrosoft** [comment]
#please-close
