### ISSUE TITLE
ReFS will not record all corruptions.

### ISSUE THREAD

**Issue by mjohnsonn** [MicrosoftDocs/windowsserverdocs#1332]
I suggest you remove the text stating that ReFS will report all corruptions in the Event Log.  I have a dozen checksum errors that ReFS has reported to my display during file copying, yet only one showed up in the Event Log.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ca609fd-a4a8-c238-1f90-9e7223ca338d
* Version Independent ID: ed26c24f-a7bd-5041-c372-146527d6a600
* Content: [ReFS integrity streams](https://docs.microsoft.com/en-us/windows-server/storage/refs/integrity-streams)
* Content Source: [WindowsServerDocs/storage/refs/integrity-streams.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/refs/integrity-streams.md)
* Product: **windows-server-threshold**
* GitHub Login: @gawatu
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#please-close
