### ISSUE TITLE
List of Events ID

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/windowsserverdocs#1333]
Regarding Types of Events, is their is single document that enlisting entire Events?

As example, I can find the partial list but not entire stuff.

https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-logging#types-of-events

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8396683-4498-71bd-60a1-345277e1433e
* Version Independent ID: 36ed02b0-555a-4714-32f8-f4e0434adf51
* Content: [AD FS 2016 FAQ](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-faq)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/AD-FS-FAQ.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/AD-FS-FAQ.md)
* Product: **windows-server-threshold**
* GitHub Login: @jenfieldmsft
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#please-close
