### ISSUE TITLE
The Japanese version of this document is dead-link

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/windowsserverdocs#1334]
The link toward to the [AD FS のエクストラネット ロックアウト保護を構成します] which is Japanese Title of this document is in dead link.
Please change the language to Japanese and Check the link of [AD FS のエクストラネット ロックアウト保護を構成します。]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f51716ad-72e5-c96a-9178-76b7b39ffa3f
* Version Independent ID: 4c3434ad-f50a-22ed-8b05-1aeb14f00706
* Content: [Configure AD FS Extranet Lockout Protection](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-extranet-soft-lockout-protection)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Soft-Lockout-Protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Soft-Lockout-Protection.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Partially resolved in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/7f71d35d985520cc4517109469903a9ff61d67ca (direct file link https://github.com/MicrosoftDocs/windowsserverdocs/commit/7f71d35d985520cc4517109469903a9ff61d67ca#diff-9fc6614388de52dd73c920a67e627fa6a65dff5d4d3d958f58bb15444eb7b6b0) and later fully resolved in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/60b7e505e0580ba8eeff6ee96c9172e8c42ed630 (direct file link https://github.com/MicrosoftDocs/windowsserverdocs/commit/60b7e505e0580ba8eeff6ee96c9172e8c42ed630#diff-9fc6614388de52dd73c920a67e627fa6a65dff5d4d3d958f58bb15444eb7b6b0).

Please note: The document has also changed after this ticket was created, so the Japanese kanji sentence

[**AD FS のエクストラネット ロックアウト保護を構成します。**]

is no longer to be found in the page. Only the fragments [**AD FS のエクストラネット**] and [**ロックアウト保護を構成**] can be found separately. (Sorry, I do not speak Japanese or read Kanji, so I am unable to see how much of the Automatic Machine Translation has changed, in addition to any related changes in the /enus/ version of the document.

Also note: The only English linked sentences or lines containing **AD FS** are in the **Additional references** section at the bottom of the page, none of the lines in the main document or title contain URL/link code at this time (2020-11-21).

**Comment by illfated** [comment]
#please-close
