### ISSUE TITLE
network adapater

### ISSUE THREAD

**Issue by stephc-msft** [MicrosoftDocs/windowsserverdocs#1335]
"A network adapter is not required for this scenario" should actually say "A specialized network adapter is not required for this scenario"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b56960f1-2dc0-b617-a0f9-f04802da541b
* Version Independent ID: 89bf1694-46dd-cb18-fa01-a3bc81f99b8a
* Content: [iSCSI target boot overview](https://docs.microsoft.com/en-us/windows-server/storage/iscsi/iscsi-boot-overview)
* Content Source: [WindowsServerDocs/storage/iscsi/iscsi-boot-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/iscsi/iscsi-boot-overview.md)
* Product: **windows-server-threshold**
* GitHub Login: @micgray-ms
* Microsoft Alias: **micgray**

**Comment by illfated** [comment]
Would that I had seen this issue ticket 2 years ago, just to get such a simple and relatively easily verifiable report to be followed up on.

@stephc-msft : Thank you for reporting the issue, I just wish that someone had seen this easy detail earlier and acted on your report.

**Comment by illfated** [comment]
By the way, I was lucky enough to identify that the link URLs at the bottom of the page also needed to be updated to current documents instead of 2012, or using separate link URLs as described in the link text, instead of the previous identical URLs for link 2 and 3.

**Comment by illfated** [comment]
There you go. PR #5182 is now available for review, comments, and improvement suggestions. Would that this were 2 years ago or more.
