### ISSUE TITLE
no information on Modified file class of Robocopy

### ISSUE THREAD

**Issue by changbowen** [MicrosoftDocs/windowsserverdocs#1338]
if you change the archive bit on a file, the file is "tweaked";
then if you change it back, the file is "modified" instead of "same".
I found no document online about the "modified" class and whether it is copied or not.

**Comment by dawnwood** [comment]
Hi @changbowen Are you asking about [this](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy) topic? Your answer will help me route your feedback to the right person.
thanks,
Dawn

**Comment by changbowen** [comment]
@dawnwood Hi, yes I was asking about that. There are some documents about robocopy online with the file classes. But I think they are quite old and does not include the file class "modified".

**Comment by dawnwood** [comment]
@changbowen Thank you, I've assigned this to the author of the topic. I'll leave the issue open until it is addressed. Best, Dawn

**Comment by coreyp-at-msft** [comment]
Hi @changbowen,

I’m checking into this. Will get back to you soon.

Thanks,
Corey
