### ISSUE TITLE
Script fails

### ISSUE THREAD

**Issue by zandr14** [MicrosoftDocs/windowsserverdocs#1339]
Script on Step 1.4 when it's run says:
Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
    + CategoryInfo          : InvalidData: (:) [Install-WindowsFeature], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Windows.ServerManager.Commands.AddWindowsFeatureCommand
    + PSComputerName        : somename
 
It's on Win server 2016 upd. feb 2018.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34f775f8-fb30-69a2-dc05-ea0cdf807b16
* Version Independent ID: e1ed4345-d693-dfb5-35c2-e1e1ec64a383
* Content: [Deploy Storage Spaces Direct](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/deploy-storage-spaces-direct)
* Content Source: [WindowsServerDocs/storage/storage-spaces/deploy-storage-spaces-direct.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/deploy-storage-spaces-direct.md)
* Product: **windows-server-threshold**
* GitHub Login: @StevenEk
* Microsoft Alias: **stevenek**

**Comment by dawnwood** [comment]
@zandr14 I am forwarding this issue to our engineering team to help debug the script. I will keep this open until we fix your error.
Best,
Dawn

**Comment by JasonGerend** [comment]
Fixed! Thanks for letting us know!

Here's the updated section: [Step 1.4: Install roles and features](https://docs.microsoft.com/windows-server/storage/storage-spaces/deploy-storage-spaces-direct#step-14-install-roles-and-features)
