### ISSUE TITLE
Reorder connection list 

### ISSUE THREAD

**Issue by mrogerson** [MicrosoftDocs/windowsserverdocs#1340]
Please bring back the ability to reorder the connections manually, rather than being forced to order alphabetically. The groups is a good idea but all groups appear under the default 'Saved Desktops' and still sort by name.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5581a04a-e204-4a19-3eba-0852d2eb5d8e
* Version Independent ID: 820c77b6-2182-7e92-bbe6-0819f727d207
* Content: [Remote Desktop clients FAQ](https://docs.microsoft.com/en-gb/windows-server/remote/remote-desktop-services/clients/remote-desktop-client-faq)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by dawnwood** [comment]
Hi @mrogerson, thank you for your feedback. This looks like product feedback, not feedback on the topic. Am I interpreting your comment correctly? If so, you have two better options for communicating your feedback. The first is the "product feedback" button right next to the "documentation feedback" button on every topic. The second is the [product forum](https://techcommunity.microsoft.com/t5/Windows-Server-Insiders/bd-p/WindowsServerInsiders) where experts and product team members can help.
I'm closing this doc feedback but feel free to reply back if I am missing your point.
Best,
Dawn
