### ISSUE TITLE
Hice un bat que se cierra en diez (10) segundos después de abrirlo ;D.

### ISSUE THREAD

**Issue by PabloJoaquin** [MicrosoftDocs/windowsserverdocs#1341]
rem horo.bat
@echo off
choice /n /m "Esta ventana se cerrará en 10 segundos..." /t 10 /d N
@echo on

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fe2b031-5dfe-7549-a676-0aedcae2963a
* Version Independent ID: 4b35134f-d41e-9902-b9b6-94897325013a
* Content: [choice](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/choice)
* Content Source: [WindowsServerDocs/administration/windows-commands/choice.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/choice.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
#please-close
