### ISSUE TITLE
Hice un .bat que dice "I AM L" (jeje *death note). :D

### ISSUE THREAD

**Issue by PabloJoaquin** [MicrosoftDocs/windowsserverdocs#1342]
@echo off
title I AM L
choice /c IAML /n /t 2 /d I
cls
choice /c IAML /n /t 1 /m I /d A
cls
choice /c IAML /n /t 1 /m "I A" /d M
cls
choice /c IAML /n /t 1 /m "I AM" /d L
pause&gt;nul

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fe2b031-5dfe-7549-a676-0aedcae2963a
* Version Independent ID: 4b35134f-d41e-9902-b9b6-94897325013a
* Content: [choice](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/choice)
* Content Source: [WindowsServerDocs/administration/windows-commands/choice.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/choice.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
#please-close
