### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by eole210** [MicrosoftDocs/windowsserverdocs#1347]
"For more information about generating CI policies and the enforcement mode, see:", the 2 links are returning page 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb3c9556-5169-8a1c-b8fe-f551a81a7382
* Version Independent ID: 720bbbd9-70ef-d058-e5e7-0f15ebe7512a
* Content: [Capture TPM-mode information required by HGS](https://docs.microsoft.com/en-us/windows-server/virtualization/guarded-fabric-shielded-vm/guarded-fabric-tpm-trusted-attestation-capturing-hardware#create-and-apply-a-code-integrity-policy)
* Content Source: [WindowsServerDocs/virtualization/guarded-fabric-shielded-vm/guarded-fabric-tpm-trusted-attestation-capturing-hardware.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/guarded-fabric-shielded-vm/guarded-fabric-tpm-trusted-attestation-capturing-hardware.md)
* Product: **windows-server-threshold**
* GitHub Login: @rpsqrd

**Comment by dawnwood** [comment]
Hi @eole210 Thank you for reporting the broken links. I will look into this right away and keep this issue open until we have an update.
