### ISSUE TITLE
SQL Server Connectivity

### ISSUE THREAD

**Issue by mmannoni** [MicrosoftDocs/windowsserverdocs#1348]
How should that work?

If the WID is used initally, the Windows Server Update Services are installed with the WID Connectivity sub feature. If I go through this guideline, WSUS will not start afterwards as the SQL Server Connectivity is not installed. Server Manager comes up with the post tasks and fails immediately. 

I had to uninstall the WID subfeature and install the SQL Server Connectivity subfeature until it worked like described here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e2a5a31-29b9-5599-2f14-bc244c5da034
* Version Independent ID: 393db29c-0866-46f4-9ee6-7ae82e8cb29f
* Content: [Migrating the WSUS Database from (Windows Internal Database) WID to SQL](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/manage/wid-to-sql-migration)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/manage/wid-to-sql-migration.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/manage/wid-to-sql-migration.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by coreyp-at-msft** [comment]
Hi @mmannoni,

Thanks for bringing this to our attention. So you were able to get it to work eventually?  Did you have to install and reinstall multiple times, or just once? I have not seen this issue before, but will try to replicate it if you can provide more information about your experience.

Thanks,
Corey

**Comment by IngridAtMicrosoft** [comment]
#please-close
