### ISSUE TITLE
How to raise FBL for AD FS which is using external SQL Server with a SQL Server account login?

### ISSUE THREAD

**Issue by smahendrakumar** [MicrosoftDocs/windowsserverdocs#1352]
I do not see a way to call the FBL raise command where our server is using an external SQL server and using a SQL sa account for connections.

We continuously keep getting error while trying different options available with command **Invoke-AdfsFarmBehaviorLevelRaise**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51895e3f-6dcd-8669-ea9b-b46c01b9def7
* Version Independent ID: 5378f1e4-0965-f794-eb44-ceef88e33691
* Content: [Upgrading to AD FS in Windows Server 2016 with SQL Server](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server-sql)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server-sql.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server-sql.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by thibaultchatiron** [comment]
What is the error ?
Did you try Invoke-AdfsFarmBehaviorLevelRaise -Credential _AdminCredential_ -ServiceAccountCredential _ADFS_Service_AccountCredential_ ?

The credentials that you put as admin should be admin of the ADFS servers too

The other way would be to launch the following cmdlet : 
Export-AdfsDeploymentSQLScript -ScriptDestinationFolder ".\ScriptFolder" -ServiceAccountName  _ADFS_Service_AccountCredential_

And then, run the script.

But the first way is just to ensure that the account that you use to raise the FBL is ADFS admin / SQL Admin

**Comment by smahendrakumar** [comment]
Thanks @thibaultchatiron ,
We have used a custom connection string using a SQL sa user to configure AD FS 3. We then aded AD FS 4 to the group and tried raising level.

We tried Credentials and ServiceAccountCredentials but it failed with error: 
_Invoke-AdfsFarmBehaviorLevelRaise : Database upgrade could not be performed on localhost. Error: An error occurred during an attempt to connect to the AD FS configuration database. Error: Name cannot be NULL. Changed database context to 'AdfsConfigurationV3'.. Confirm that the database hostname and instance name are correct and that the specified service account has logon access to the database. ._ 

Even after throwing error we can see that DB is getting created on the SQL server.

**Comment by thibaultchatiron** [comment]
Ok then!

If the database is created, can you verify that the ADFS service account has the right on the AdfsConfigurationV3 ?
It should have the db_genevaservice role on the database.

Do you have SQL Always On ?

What do you have in "ConfigurationDatabaseConnectionString" when you launch : 
GEt-WmiObject -namespace root/ADFS -class SecurityTokenService

Finally, what is the output of Get-AdfsFarmInformation ?

**Comment by smahendrakumar** [comment]
This is what I get on command execution:

_ConfigurationDatabaseConnectionString     : Data Source=SQLSERVER101;Initial Catalog=AdfsConfiguration;Integrated Security=False;User ID=sqladmin;Password=*********_											
											
_CurrentFarmBehavior FarmNodes
                  1 {server2016.com}_

To add complexity our AD FS server and SQL server are on different domains.

**Comment by smahendrakumar** [comment]
When I execute _Test-AdfsFarmBehaviorLevelRaise_, all tests pass. I can use WMI to change connection string but I have to then manually import all configurations and I am not sure what other things may be missing which is done by _Invoke-AdfsFarmBehaviorLevelRaise_. I am not sure why this command is not using current connection string configured and trying to use current/passed credentials to connect to DB.

**Comment by thibaultchatiron** [comment]
You can test the connectivity to AdfsConfigurationV3
https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-sql

**Comment by thibaultchatiron** [comment]
That's why you have the sql user on the output of the WMI (Data Source=SQLSERVER101;Initial Catalog=AdfsConfiguration;Integrated Security=False;User ID=sqladmin;Password=*********)

Normally, the user id is not present because of Integrated Security is equal to True

So, if the connectivity is good, you could update the configuration via the WMI commands that I gave you sooner.

**Comment by smahendrakumar** [comment]
Sure,
Let me setup a test environment and run this through. If it works there I will execute this in our Prod servers if tests pass. This may take a while.

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
