### ISSUE TITLE
:,v

### ISSUE THREAD

**Issue by PabloJoaquin** [MicrosoftDocs/windowsserverdocs#1356]
me dice que el comando no existe alv :,v

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efb47966-3b98-31b5-0fcf-bb37dfb05a0c
* Version Independent ID: aa37aaaa-eebe-8529-afd8-eb7919b277eb
* Content: [dcgpofix](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/dcgpofix)
* Content Source: [WindowsServerDocs/administration/windows-commands/dcgpofix.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/dcgpofix.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by lizap** [comment]
This is a server command. It's not available in Windows 10 but it IS available in Windows Server 2016. Thanks!
