### ISSUE TITLE
Guidelines for a non-internet connected environment

### ISSUE THREAD

**Issue by StevenWDK** [MicrosoftDocs/windowsserverdocs#1358]
I am missing guidelines to do an offline installation. As in installing it on a non-internet connected environment. 
Where you can't get Nuget and get the cmdlets to download stuff from internet...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Product: **windows-server-threshold**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Heidilohr** [comment]
@StevenWDK We're currently investigating offline installation. We'll post any new developments on the [What's new for the Remote Desktop web client?](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/web-client-whatsnew) page. Stay tuned.

**Comment by lizap** [comment]
We've updated the article with info on how to install the client when you're offline: https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin#how-to-install-the-remote-desktop-web-client-without-an-internet-connection
