### ISSUE TITLE
ALT, CTRL + left|right - word jumping

### ISSUE THREAD

**Issue by ertn0** [MicrosoftDocs/windowsserverdocs#1359]
Hi there, 
I haven't managed to use a macOS UI / hardware to do proper word jumping to a connected windows 7 via RDP 10. 
my googling attempts didn't present helpful answers. 

is a sort of out of the box setting present after all? or can I arrange it via mapping this or that? 

regards, ertn

**Comment by dawnwood** [comment]
Hi @ertn0 Can you tell me what word jumping is?

**Comment by ertn0** [comment]
It is like on macOS using the ALT key + left or right ... to literally jump across whole words instead of the individual letters/chars. 
the issue is, when you are in a macOS rdpee'ing (Scnr) into a windows 7, you have no chance other than scrolling the entire line including all chars when writing text.
