### ISSUE TITLE
Syntax Update

### ISSUE THREAD

**Issue by TheMichaelRoth** [MicrosoftDocs/windowsserverdocs#1360]
Great content! I noticed one typo in the note under the Installation Options section. The sentence should have "use" instead of "user" in the section where it reads "later decide to user Server with".

For example, if you install Server Core and later decide to user Server with Desktop Experience, you should do a fresh installation (and vice versa).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b400e326-face-ddc7-d9ac-ab08488bb75a
* Version Independent ID: 1da91dfc-2a76-5be4-1376-959e6c3635a9
* Content: [Windows Server](https://docs.microsoft.com/en-us/windows-server/windows-server)
* Content Source: [WindowsServerDocs/Windows-Server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/Windows-Server.md)
* Product: **windows-server-threshold**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
Hello and thanks for your feedback. If click the "edit" button on any live topic, you can easily make edits to it directly--we'll process it and get it updated.

**Comment by josevidal1970** [comment]
lazy bum, talk about lack of publishing and proofreading knowhow....
why should the reader have to edit the publishers mistake? Stop being lazy

**Comment by valerianpereira** [comment]
I believe this is done. Could you close the issue?

**Comment by valerianpereira** [comment]
Close the issue if this is done already.
