### ISSUE TITLE
TCP Fast Open information incorrect

### ISSUE THREAD

**Issue by MikeBazMSFT** [MicrosoftDocs/windowsserverdocs#1361]
TCP Fast Open was added in Windows Server 2016 (https://docs.microsoft.com/en-us/windows-server/get-started/whats-new-in-windows-server-2016#networkingnetworkingnetworkingmd) - the improvements in 1709 were around fallback improvements (cf. https://datatracker.ietf.org/meeting/100/materials/slides-100-tcpm-updates-on-windows-tcp/) and load balancer support (reg add HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters /v TcpFastopenKey /t REG_BINARY /f /d 0123456789abcdef0123456789abcdef)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 570e0a36-5369-ae26-7df8-f7beee1b61b2
* Version Independent ID: 239cfd6f-e9d1-b909-f48e-2164fb70b6e4
* Content: [What's New in Windows Server, version 1709](https://docs.microsoft.com/en-us/windows-server/get-started/whats-new-in-windows-server-1709#networking)
* Content Source: [WindowsServerDocs/get-started/whats-new-in-windows-server-1709.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/whats-new-in-windows-server-1709.md)
* Product: **windows-server-threshold**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by IngridAtMicrosoft** [comment]
#please-close
