### ISSUE TITLE
PowerShell equivalent to netsh interface portproxy show all

### ISSUE THREAD

**Issue by johnsivertsen** [MicrosoftDocs/windowsserverdocs#1363]
Spending many hours searching through https://docs.microsoft.com/en-us/powershell/windows/get-started?view=win10-ps I am not able to figure out which PowerShell command replaces the netsh interface portproxy commands, like:
```netsh interface portproxy show all```

Can you point me in the right direction?

portproxy seems to be entirely undocumented on docs.microsoft.com... should I be concerned about that?
Googleing ```"portproxy" site:docs.microsoft.com``` only gives a single result, which is from a blog post comment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104c0791-b5a1-6502-401a-d472ff6144bb
* Version Independent ID: 5a8faa14-9cef-6a9b-26af-9782a799b23a
* Content: [Network Shell (Netsh)](https://docs.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh#feedback)
* Content Source: [WindowsServerDocs/networking/technologies/netsh/netsh.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/netsh/netsh.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@johnsivertsen, thank you for pointing this out.  I'll work with the team to get it updated.

**Comment by shortpatti** [comment]
Content added.

**Comment by cgevans** [comment]
There appears to have been some mistake here.  The PR above has nothing to do with this issue, and no content addressing this appears to have been added anywhere.

**Comment by John0King** [comment]
so why this issue is been closed anyway ?
