### ISSUE TITLE
Missing hyperlink

### ISSUE THREAD

**Issue by amasse3** [MicrosoftDocs/windowsserverdocs#1364]
https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-faq#i-need-to-return-profile-and-email-scopes-as-well-in-addition-to-the-openid-scope-can-i-obtain-additional-information-using-scopes-how-to-do-it-in-ad-fs

"for more info, read here" missing hyperlink.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8396683-4498-71bd-60a1-345277e1433e
* Version Independent ID: 36ed02b0-555a-4714-32f8-f4e0434adf51
* Content: [AD FS 2016 FAQ](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-faq#i-need-to-return-profile-and-email-scopes-as-well-in-addition-to-the-openid-scope-can-i-obtain-additional-information-using-scopes-how-to-do-it-in-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/AD-FS-FAQ.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/AD-FS-FAQ.md)
* Product: **windows-server-threshold**
* GitHub Login: @jenfieldmsft
* Microsoft Alias: **billmath**

**Comment by tvuylsteke** [comment]
Fixed the link in this PR: https://github.com/MicrosoftDocs/windowsserverdocs/pull/1771 . Thanks for reporting!
