### ISSUE TITLE
Hice un ejemplo del uso de "setlocal" y "endlocal" :).

### ISSUE THREAD

**Issue by PabloJoaquin** [MicrosoftDocs/windowsserverdocs#1367]
---potato.bat---
@echo off
set nombre=Harold
echo.
echo Nombre = %nombre%
pause&gt;nul
echo.
setlocal
set nombre=Eduardo
echo Nombre = %nombre%
pause&gt;nul
endlocal
echo.
echo Nombre = %nombre%
pause&gt;nul

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d76e22e-da8d-fef5-af13-b35fe27379ed
* Version Independent ID: cce33bdb-799b-165e-8a73-c1d3ce57d970
* Content: [setlocal](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/setlocal)
* Content Source: [WindowsServerDocs/administration/windows-commands/setlocal.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/setlocal.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
#please-close
