### ISSUE TITLE
Hice un ejemplo del uso de "setlocal" y "endlocal" :).

### ISSUE THREAD

**Issue by PabloJoaquin** [MicrosoftDocs/windowsserverdocs#1368]
---potato.bat---
@echo off
set nombre=Harold
echo.
echo Nombre = %nombre%
pause&gt;nul
echo.
setlocal
set nombre=Eduardo
echo Nombre = %nombre%
pause&gt;nul
endlocal
echo.
echo Nombre = %nombre%
pause&gt;nul

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d5643c3-d94b-0741-dfd6-9f88b6e70b68
* Version Independent ID: 45f1039c-d5cd-239a-bb62-d581ad8471b4
* Content: [endlocal](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/endlocal)
* Content Source: [WindowsServerDocs/administration/windows-commands/endlocal.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/endlocal.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
#please-close
