### ISSUE TITLE
Issue with Non English Editions

### ISSUE THREAD

**Issue by juanorphanos** [MicrosoftDocs/windowsserverdocs#137]
Hi Team!

When trying to clone a DC in a SPanish Edition Windows Server, we have the "Controladores de dominio clonables" Security group instead of "Cloneable Domain Controllers",  if you add the computer account to that Group, the New-ADDCCloneConfigFile cmdlet fails, because it wants to look for the group in english "Cloneable Domain Controllers". I don't know if this happens for all non English editions, but it might be worth to check. The workaround is to create a group called Cloneable Domain Controllers (in English).

Thanks and best regards!

**Comment by lizap** [comment]
Hi, Juan - this is great feedback, but this is not the best place for it. Can you post this to the Windows Server UserVoice forum? https://windowsserver.uservoice.com/forums/295047-general-feedback

These issues are intended to focus just on the Windows Server content. As such, I'm going to close this comment. Please DO visit the UserVoice site, though.
