### ISSUE TITLE
Image quality of RemoteApp

### ISSUE THREAD

**Issue by wallbanger123** [MicrosoftDocs/windowsserverdocs#1371]
The image quality of the app seems to be very low. Text is unclear, and everything seems to be either at a low resolution or low quality setting. Is there any way to adjust this? See attached.

![image](https://user-images.githubusercontent.com/24628513/44436600-be799680-a57b-11e8-8c68-c199efebbf8c.png)

**Comment by Heidilohr** [comment]
@wallbanger123 Could you please clarify which topic you're looking at?

**Comment by IngridAtMicrosoft** [comment]
#please-close
