### ISSUE TITLE
See the article here?

### ISSUE THREAD

**Issue by mchudinov** [MicrosoftDocs/windowsserverdocs#1373]
If you are interested in developer guidance for these protocols, see the article here.
Where "here"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3824263-5c49-03e9-9063-b44b1c636540
* Version Independent ID: 31684400-9100-b442-8957-c1300ad35cb8
* Content: [AD FS Scenarios for Developers](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-scenarios-for-developers)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/AD-FS-Scenarios-for-Developers.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/AD-FS-Scenarios-for-Developers.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 1352 -b #assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
