### ISSUE TITLE
High Availability support 'Windows Admin Center Preview 1808'

### ISSUE THREAD

**Issue by rrickrrick** [MicrosoftDocs/windowsserverdocs#1374]
Is High Availability still supported for 'Windows Admin Center Preview 1808'? When we execute a failover to another node users ending up with de default first time welcome message and all connections and configuration is lost.
If we fail back to the original node connections and configuration is restored.
 
I've checked the files that sme.exe opens and found out that it uses the local sme.edb file (C:\Windows\ServiceProfiles\NetworkService\AppData\Roaming\Microsoft\ServerManagementExperience\sme.edb).

**Comment by dawnwood** [comment]
Hi @rrickrrick This looks like product feedback, not feedback on the topic. Am I interpreting your comment correctly? If so, you have two better options for communicating your feedback. The first is the "product feedback" button right next to the "documentation feedback" button at the bottom of every topic. The second is the [product forum](https://techcommunity.microsoft.com/t5/Windows-Server-Insiders/bd-p/WindowsServerInsiders) where experts and product team members can help.
I'm closing this doc feedback but feel free to reply back if I am missing your point.
Best,
Dawn
