### ISSUE TITLE
Solution Extension examples

### ISSUE THREAD

**Issue by NJArcher** [MicrosoftDocs/windowsserverdocs#1375]
The SDK on GitHub has a broken link to solution examples. Are there any? I followed the ones in this documentation for solutions and still only ended up with a tool extension. Or was that my mistake somewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac61f326-7fa7-15c7-8b0a-67e50d100dfb
* Version Independent ID: fd98eee8-3b3c-65d6-c704-b84b6c1eefac
* Content: [Develop a solution extension](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/extend/develop-solution)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/extend/develop-solution.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/extend/develop-solution.md)
* Product: **windows-server-threshold**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by NJArcher** [comment]
OK, it was my fault. I thought this was going to add a new connection but it adds my solution in main window in drop down alongside the "Windows admin center". Not very intuitive and they don't really look like tabs.

**Comment by dawnwood** [comment]
@NJArcher thanks for the feedback and for letting us know that you were able to unblock yourself. I will pass your UX feedback on to our designer team.
