### ISSUE TITLE
Numbered bullet improperly configured as code in section "Create the VPN Server Authentication Template"

### ISSUE THREAD

**Issue by bryhall** [MicrosoftDocs/windowsserverdocs#1377]
Under the section "Create the VPN Server Authentication Template", under the Procedures sub-section step 4, the two subsequent steps which should be step 5 and 6 are instead formatted as in-line code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e886cf2-b2cc-1942-2e93-b83ba3f5c81a
* Version Independent ID: 14185f76-c920-66a5-9d3b-51ddc4845ee8
* Content: [Configure the Server Infrastructure](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure#create-the-vpn-server-authentication-template)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@bryhall, thank you for catching the odd formatting.  I'll get that fixed.
