### ISSUE TITLE
ciclo FOR que cuenta hasta tres (3) :)

### ISSUE THREAD

**Issue by PabloJoaquin** [MicrosoftDocs/windowsserverdocs#1378]
for /l %V IN (1,1,3) DO @choice /n /t 1 /c YN /d Y /M %V

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd23b3f6-0f24-3742-8588-bc3c901b6c8f
* Version Independent ID: 1c5aa825-ee30-5e1b-5f58-b8aa3ccff22c
* Content: [for](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/for)
* Content Source: [WindowsServerDocs/administration/windows-commands/for.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/for.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
#please-close
