### ISSUE TITLE
The image have an unrelated text.

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/windowsserverdocs#1386]
This issue was created by @blackfoxsar from https://github.com/MicrosoftDocs/feedback/issues/629
🛑 IMPORTANT: You can get your feedback addressed faster if you use the comment section for the article in which you encountered a problem.
Link to article:
https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server
Problem:
The image have an unrelated text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7899bfcb-2e9c-2738-5e7f-468a6eb643ce
* Version Independent ID: 482cc911-c7ef-c680-b6ff-f634530b1424
* Content: [What's new in Active Directory Federation Services for Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by blackfoxsar** [comment]
![adfs_itpro4](https://user-images.githubusercontent.com/15705262/44567759-dd13a380-a7ae-11e8-8157-14aa56dd49c1.png)
