### ISSUE TITLE
EULA for Hyper-V Server 2016

### ISSUE THREAD

**Issue by DSPatrick** [MicrosoftDocs/windowsserverdocs#1399]
where is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b3dda64-983d-903e-8896-0bd6696efee1
* Version Independent ID: ef15883c-6776-79c9-56da-5a96123c530a
* Content: [Microsoft Hyper-V Server 2016](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/hyper-v-server-2016)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Hyper-V-Server-2016.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/Hyper-V-Server-2016.md)
* Product: **windows-server-threshold**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by dawnwood** [comment]
Hi @DSPatrick I am following up with the engineering team but you should also feel free to ask your question on the [product forum](https://techcommunity.microsoft.com/t5/Windows-Server-Insiders/bd-p/WindowsServerInsiders) where experts and product team members can help.
Best,
Dawn

**Comment by DSPatrick** [comment]
Thanks, I found this document while looking for the EULA for Microsoft Hyper-V Server 2016 on behalf of a TechNet forums user. I am suggesting it should be added to this document for completeness.

https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/hyper-v-server-2016

**Comment by dawnwood** [comment]
@DSPatrick Ah, understood. I'll find the license and add it to the page. Until that happens, I'll leave this issue open. 
Dawn

**Comment by LTUTE** [comment]
Is it still opened?

**Comment by DSPatrick** [comment]
Looks like nothing ever happened.
