### ISSUE TITLE
14393.0.161119-1705.RS1_REFRESH CORE Cannot upgrade to any version

### ISSUE THREAD

**Issue by skalg** [MicrosoftDocs/windowsserverdocs#1405]
I have two VMs with a trial version installed of windows server 2016 (14393.0.161119-1705.RS1_REFRESH). On is core and the other one is with Desktop Experience. I've successfully upgraded the Desktop Experience one to a full version but there's not upgrade path available for the "Core" version. In the Microsoft docs it's saying [https://docs.microsoft.com/en-us/windows-server/get-started/supported-upgrade-paths](url)
> Starting with version 14393.0.161119-1705.RS1_REFRESH and later releases, you can convert evaluation editions to retail regardless of the installation option used

What am I missing ?
- slmgr.vbs /dlv is giving me a TIMEBASED_EVAL channel with a Retail:TB:Eval
- DISM /online /Get-CurrentEdition is returning : ServerStandardEvalCor
- DISM /online /Get-TargetEditions.
Deployment Image Servicing and Management tool
Version: 10.0.14393.0
Image Version: 10.0.14393.0
Editions that can be upgraded to:
(The current edition cannot be upgraded to any target editions.)
The operation completed successfully.

Please I need help ! :)

**Comment by dawnwood** [comment]
Hi @skalg Thank you for contacting Microsoft and communicating this issue. Unfortunately, you are running into a known issue that prevents this particular installation type from converting to anything else.

**Comment by skalg** [comment]
Since it's a known issue is there a place where I can follow the development of this issue ? Because this issue invalidate the documentation provided by Microsoft [https://docs.microsoft.com/en-us/windows-server/get-started/supported-upgrade-paths](url) Stating that we can convert an evaluation version to any version if we are running 14393.0.161119-1705.RS1_REFRESH. Thanks

**Comment by dawnwood** [comment]
@skalg  you are absolutely right that this should be documented. I am working on that now and will let you know when it's in the topic you sight above.
