### ISSUE TITLE
What to tool to use for securing a Windows Server 2016 Domain Controller?

### ISSUE THREAD

**Issue by kmchannon** [MicrosoftDocs/windowsserverdocs#1407]
This article says to use the Security Configuration Wizard for Windows Server 2016, but another article (https://docs.microsoft.com/en-us/windows-server/get-started/deprecated-features)  says that it has been depricated?   The Security Compliance Manager solution accelerator has also been retired / not updated for Server 2016. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4762d9fe-e510-df71-a718-aa0d018db38f
* Version Independent ID: fc2f30ef-e71d-5167-6d41-7abadbc2892a
* Content: [Securing Domain Controllers Against Attack](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/securing-domain-controllers-against-attack)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Securing-Domain-Controllers-Against-Attack.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Securing-Domain-Controllers-Against-Attack.md)
* Product: **windows-server-threshold**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
@kmchannon The item below it will help the Microsoft Security Compliance Toolkit provides additional assistance in this regard.

https://docs.microsoft.com/windows-server/identity/ad-ds/plan/security-best-practices/securing-domain-controllers-against-attack#microsoft-security-compliance-toolkit

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
