### ISSUE TITLE
/RemoveCredentials -> /SetCredentials

### ISSUE THREAD

**Issue by jjkraak** [MicrosoftDocs/windowsserverdocs#1412]
I don't think "/RemoveCredentials" in the example will actually set the credentials.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e2aa2f7-d8f0-53d3-bdf8-1bbbed26653f
* Version Independent ID: 8e8bfc6f-2921-780b-018d-afc2a46f9751
* Content: [bitsadmin setcredentials](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/bitsadmin-setcredentials)
* Content Source: [WindowsServerDocs/administration/windows-commands/bitsadmin-setcredentials.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/bitsadmin-setcredentials.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
#please-close
