### ISSUE TITLE
sysprep guide doesn't work

### ISSUE THREAD

**Issue by techiemctechface** [MicrosoftDocs/windowsserverdocs#1413]
https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/EssentialsDocs/install/Preparing-the-Image-for-Deployment.md

has an issue where now i need to reinstall windows on the server over again because the sysprep step logged me out, insisted i set a password, and then the computer locked up and went into a boot loop after i restarted it.

another quality microsoft guide.

**Comment by dawnwood** [comment]
@techiemctechface I'm sorry you had trouble with these instructions. I'm assigning this feedback to @coreyp-at-msft to follow up. What step were you on when things went awry?

**Comment by techiemctechface** [comment]
%systemroot%\system32\sysprep\sysprep.exe /generalize /OOBE /unattend:xxx.xml /Quit 

i interpolated xxx.xml to e:\unattend.xml (which had volume license key, admin password changed)
sysprep ran, logged me out, when i tried to log back in, my admin password was blanked and it wanted me to set it. i did, it tried logging in, my keyboard locked up (num lock wouldn't work), screen blanked and eventually went into low power mode. I gave it an hour and a half as there was periodic activity, and hard powered it down. when it came back up, told me that unattended file in c:\something\panther\unattend.xml was incorrect and rebooted. kept coming up that i had to reboot the machine and finish installation (was a boot loop).

I did this on 2012 standard.

currently trying with this unattend.xml template:  https://gallery.technet.microsoft.com/Basic-Sysprep-unattend-XML-035a2522#content

reinstalling windows and doing hundred of updates is a long pain in the ass. going to make an image prior to running sysprep just in case it does this again.

**Comment by techiemctechface** [comment]
also would like to add that step 4 is a bit odd. maybe you should change the verbiage on it.

**Comment by techiemctechface** [comment]
also, would be nice if it described how to make generalize not remove system specific drivers.

**Comment by dawnwood** [comment]
Thanks, @techiemctechface We'll leave this issue open until we can update the documentation.

**Comment by IngridAtMicrosoft** [comment]
#please-close
