### ISSUE TITLE
Migrate relevant command docs from slashes to dashes

### ISSUE THREAD

**Issue by aaronfranke** [MicrosoftDocs/windowsserverdocs#1418]
Full list of commands: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/commands-by-server-role

For example, `timeout -t 5` does the same thing as `timeout /t 5`

A few reasons why:

* Commands also support `/` as a path separator (`cd a/b` works the same as `cd a\b`). Best not to cause unnecessary confusion between arguments and paths.

* PowerShell, Microsoft's newer CLI interface, uses dashes for arguments, and uses `/` as a path separator. Again, better to avoid confusion if `-` works just fine everywhere.

* It would be consistent with other Microsoft products such as the .NET docs, which yet again use `-` for arguments and `/` as a path separator: https://github.com/dotnet/docs/issues/4072

* Many 3rd-party CLI programs that run on Windows exclusively use dashes for cross-platform compatibility. It would be better if users only need to know dashes for all commands.

I can't really think of any upside to having the docs keep using `/`. Windows has supported dashes for arguments in most of its command-line programs for decades, so backwards compatibility is not an issue (unless you intend the docs to be relevant for MS-DOS... which is very dead). And for users who are used to using `/` and scripts that use `/`, those will continue to work no matter what the docs say.

I haven't tested all of these commands, it's possible that some don't support dashes. Each command would need to be tested before having their documentation changed.

**Comment by aaronfranke** [comment]
By the way, I would be willing to help out with this. I just need to know if this is what's preferred.

**Comment by coreyp-at-msft** [comment]
Hi @aaronfranke, 

Thank you for the suggestion. Your reasoning makes sense, although this wouldn’t fall among our higher priorities. We wouldn’t undertake this effort ourselves for that reason. We appreciate your willingness to help get it done, but it would be difficult for you to do for two reasons: First, it would have to be consistently applied throughout the commands, so we wouldn’t merge it until a complete PR was submitted, and that would be a substantial undertaking. Second, the testing component you mention would be tedious for you and difficult for us to verify. We wouldn’t make a global change like this without testing it ourselves, and that comes back again to this falling below our current priorities. With that said, we do appreciate your suggestion and will consider it if we do an overhaul of the commands docs in the future.

(Alternatively, you could submit a PR to the page you site with your explanation of dash and slash usage so others are aware and can apply them appropriately.

Thanks,
Corey
