### ISSUE TITLE
Per-Device CALs

### ISSUE THREAD

**Issue by johnathan-agentdesign** [MicrosoftDocs/windowsserverdocs#1421]
I understand that per-device CALs is not supported (can fully understand why, as this way multiple users can use a single device CAL).
However, what are the knock-on effects from doing this? Is 1 CAL used per username? Or does it "eat" CALs until there are none left?
1 CAL per username would make sense, as in a way this is honouring the "per device" licencing (maybe a bit too much, if many users use 1 device).
I have this installed and running, we're currently in "per device" licencing as 95% of users have mac or windows machines which connect via RDP. There's an odd couple who dont have compatible devices so use Apache Guacamole.
Apache Guacamole is web based RDP client - https://guacamole.apache.org/ - exactly the same as this!
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Product: **windows-server-threshold**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Heidilohr** [comment]
@johnathan-agentdesign Our currently supported Remote Desktop applications can reliably track the usage of RDS CALs in a persistent storage that they can access. However, since this is not guaranteed for browsers where the applications might overconsume RDS CALs, our web client doesn’t support that feature.

**Comment by johnathan-agentdesign** [comment]
@Heidilohr To clarify, in our scenario, the RDS per device CALs are stored in the browser's persistent storage?  So in theory, we could still use the client for those odd couple of users.

However we should be aware that if there is an issue with the persistent storage, then a new CAL will be issued (and the old one will not be available until it expires)?

If this is correct, then I think we're ok, as we have a large handful of CALs free, so could monitor this going forwards?

**Comment by Heidilohr** [comment]
@johnathan-agentdesign If you're focused on per-device CALs, we recommend either using our native application offers for all supported OSes in the App Store or building in a Windows remoting application.

**Comment by johnathan-agentdesign** [comment]
A good example of a solution which does not have very good RDP access and no native client is ChromeOS.  Having something which runs within a browser tab is useful for multiple users swapping machines - especially in dusty environments, as chromeOS machines are very cheap in comparison to windows machines!  Users swapping on and off 

If there was a concern on usage of CALs, the use of Apache Guacamole bypasses all device CAL checks anyways (it's 1 client and uses 1 licence, even with multiple users).

Anways… Going back on topic,

Are device CALs stored in the client browser's persistent storage?  If so, then this should cover our scenario and monitor?

Also, would it not be better to request CALs based on some identifiable information from the browser?  (Maybe IP address/User Agent String?)

**Comment by tommls** [comment]
And when those ChromeOS devices are taken "out" of the local network because the person is traveling and only has hotel wifi?? Then what?? People with such devices then need a web client to hit the RDS farm containing their apps, files, work, etc.

**Comment by johnathan-agentdesign** [comment]
Possibly use a mixture of options available in the back end:

- Store CAL in Browser Persistent Storage (May use multiple CALs if storage not available)

- Store CAL Locally using IP / User Agent (May use multiple CALs if IP changes)

The other alternative, is to issue 1 CAL for all devices (just like Apache Guacamole does), have a disclaimer (to cover ass) and let server admin's enforce and monitor the CAL usage. (Just like User CALs for Windows Server etc)

**Comment by tommls** [comment]
It's hard to believe that the server containing the RDS web client can not do the following:
1) query the domain controller how many device CALs exist -- used, not used, etc.
2) monitor the web connections and allow +/- 10 or however many connections to the server via browser
This is probably how RDS works in the first place...
User agent would not work well b/c it would frequently be the same, but one could tally how many user agents are seen.
IPs get re-used in DHCP scenarios, not always by the same device.

**Comment by johnathan-agentdesign** [comment]
Aye IP / UserAgent is a bit naff... But all I could think of which is available on all browsers.   It's not as if you can get the MAC address or Computer Name via HTTP/Javascript

**Comment by tommls** [comment]
Ah, you're British. :) The server hosting the web client app and whatnot should be doing this stuff, not the browser. And you'd be surprised what data Javascript can get, nowadays it can tell when you drink your coffee or when you comb your hair. :)

**Comment by johnathan-agentdesign** [comment]
Yep I am 😄 

Aye definitely should be server side, which restricts you to pretty much what is in the headers.... Hence UserAgent / IP.

Not perfect, but usable.

Obviously the best solution would be to do what Guacamole does and just request 1 licence for multiple devices, and let the Sysadmin monitor / police as required.  Makes life so much easier!   (If the fear is that user's bypass CALs with this, then the sysadmin could simply use Guacamole which does this anyways!)

**Comment by tommls** [comment]
It appears the problem is solvable...does M$ have the will/time/opportunity/etc. to solve it?? :) :)

**Comment by johnathan-agentdesign** [comment]
To Clarify @lizap, will "Per Device" cals never be officially supported?
