### ISSUE TITLE
The /r option

### ISSUE THREAD

**Issue by Lockszmith-GH** [MicrosoftDocs/windowsserverdocs#1423]
The article (as of Aug 31st, 2018) states "This option is available only in the Windows Server 2003 operating system." about the /r option.
It seems to work in newer versions as well.

Can someone clear up whether this just should means that the option was introduced in Win 2003?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d23ea9c-cf2e-c913-faf9-fe844f4d5a21
* Version Independent ID: 2ce70a9f-70ac-d0fa-e720-3765cda4666a
* Content: [lodctr](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/lodctr)
* Content Source: [WindowsServerDocs/administration/windows-commands/lodctr.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/lodctr.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
#please-close
