### ISSUE TITLE
Where is Microsoft?

### ISSUE THREAD

**Issue by altimmons** [MicrosoftDocs/windowsserverdocs#1435]
FOR THE LOVE OF GOT, WILL SOMEONE PUT OUT THE F-ING  ANSWER??  95% of us are trying to load the same software on the same version of windows the same way.  And where the F- is microsoft in all this.  Is there some embargo against the developers actually getting out there and helping a bit.  Or they just eat their free sushi lunch and give 2 $jits whethe it works or not?  I've read  40 different websites with "answers" now.  Fu&lt;|&lt; all works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52db1d76-fb68-c44f-1162-3e30e8c2b793
* Version Independent ID: 696aa3ee-bd95-2acf-9021-ef4b67663f1a
* Content: [Supported Ubuntu virtual machines on Hyper-V](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-ubuntu-virtual-machines-on-hyper-v)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Supported-Ubuntu-virtual-machines-on-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/Supported-Ubuntu-virtual-machines-on-Hyper-V.md)
* Service: **na**
* Product: **windows-server-threshold**
* GitHub Login: @shirgall
* Microsoft Alias: **kathydav**

**Comment by dawnwood** [comment]
Hi 
@altimmons if you have a question about a specific step I will try to find the right person to answer.
Best,
Dawn
