### ISSUE TITLE
Hyper-V Technology Overview

### ISSUE THREAD

**Issue by Donald-CWRU-Research** [MicrosoftDocs/windowsserverdocs#1436]
This article was really well-written and properly linked to sources. I found no discernable errors. Thanks, Microsoft!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c79949-9813-1fff-3511-51eeda5fe1d0
* Version Independent ID: d7e79834-ca2c-e8da-0cf5-285c4785c6be
* Content: [Hyper-V Technology Overview](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/hyper-v-technology-overview#what-features-does-hyper-v-have)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Hyper-V-Technology-Overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/Hyper-V-Technology-Overview.md)
* Service: **na**
* Product: **windows-server-threshold**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by dawnwood** [comment]
@Donald-CWRU-Research Thank you!!
