### ISSUE TITLE
Installing the Hyper-V Role using PowerShell

### ISSUE THREAD

**Issue by Donald-CWRU-Research** [MicrosoftDocs/windowsserverdocs#1437]
This article is great. It shows the laborious set of tasks required to install the server role through the GUI, then follows-up with a single line of code that will install the Hyper-V role on my local Windows machine. It is a testament to the terseness and power of the PowerShell scripting language and environment. Thanks, Microsoft!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df371b9-1306-2ef2-f3d0-9e09396ee6bf
* Version Independent ID: 9a6e039c-b123-03b2-f130-528d73849155
* Content: [Install the Hyper-V role on Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/get-started/install-the-hyper-v-role-on-windows-server)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/get-started/Install-the-Hyper-V-role-on-Windows-Server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/get-started/Install-the-Hyper-V-role-on-Windows-Server.md)
* Service: **na**
* Product: **windows-server-threshold**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by dawnwood** [comment]
Thanks, @Donald-CWRU-Research !
