### ISSUE TITLE
DisabledByDefault is not a subkey but a value

### ISSUE THREAD

**Issue by MikhailTrukhmanov** [MicrosoftDocs/windowsserverdocs#1441]
DisabledByDefault is described as a subkey name while it is a name of a value within both a Client and a Server subkeys.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38fcd9dd-91c8-e79b-5f4d-28a435a8ada8
* Version Independent ID: 0d79a0c8-0b73-c783-4d5c-b107d24acf55
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server-threshold**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by jordanmills** [comment]
Looks like this just got closed, but was never fixed.
