### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by demovirus** [MicrosoftDocs/windowsserverdocs#1442]
https://docs.microsoft.com/ru-ru/windows-server/identity/ad-fs/technical-reference/the-role-of-claims

In Russian version of this page in table under "What are claim types?" block there are bad links: http://// instead of http://

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17871695-deb5-8178-a970-71b7d6fabd72
* Version Independent ID: ae86889c-8f5d-bbc2-d713-4f1a6678af5b
* Content: [The Role of Claims](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/technical-reference/the-role-of-claims)
* Content Source: [WindowsServerDocs/identity/ad-fs/technical-reference/The-Role-of-Claims.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/technical-reference/The-Role-of-Claims.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by demovirus** [comment]
2 weeks just for correcting links?

**Comment by illfated** [comment]
@TinaMcN : I don't know if this belongs to your department, but anyway; The Machine Translated Russian page contains incorrect spacing, both for forward slashes // and around parentheses ( ) inside regular text lines.

Link to the most affected part of the page: https://docs.microsoft.com/ru-ru/windows-server/identity/ad-fs/technical-reference/the-role-of-claims#what-are-claim-types

image view of the issue:

***

![image](https://user-images.githubusercontent.com/38162891/100392854-20b58180-3038-11eb-9e31-399f96dba974.png)

***

Is this something you can report to the translation team and ask if this can be improved in the automatic translation tools? 

The English page does not have this issue, and I don't see how the English page can be improved to avoid this issue, both in the regular text and the URLs in the tables, so I am unable to provide any solutions for the English page to avoid this issue appearing in the translated pages. Wish I could help, though.

**Comment by TinaMcN** [comment]
@SonjaSaltzman do you know who manages the Windows Server content localization?

**Comment by SonjaSaltzman** [comment]
Should be @cnicco

**Comment by IngridAtMicrosoft** [comment]
#please-close
