### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by prof79** [MicrosoftDocs/windowsserverdocs#1445]
This also impacts the "About Hyper-V scheduler type selection" topic - how do the virtual threads resulting from the HwThreadsPerCore setting affect licensing in products like SQL Server w/ core licensing? I see confusion and problems rising.
On a SQL VM that had 4 virtual cores (virtual processors) before core scheduler it will now display 8 virtual processors in task manager - msinfo32 will correctly show 4 cores and 8 logical processors; however, the per core licensing brief from April 2017 states:
"To license individual VMs using the Per Core model, customers must purchase a core license for each v-core (or virtual processor, virtual CPU, virtual thread) allocated to the VM, subject to a four-core license minimum per VM. For licensing purposes, a v-core maps to a hardware thread."
Thus, if I understand correctly, a 4-core SQL VM would now require 8 cores to be licensed because there are 8 virtual threads that map to 8 hardware threads - where by definition "A hardware thread is either a physical core or a hyper-thread in a physical processor."
So my assumption is we would either have to set HwThreadsPerCore to 1 for those VMs or halve their vCPU count.
Or the licensing team would need to clarifiy that it is the cores/the vCPU count in VM settings that count but it sounds differently to me from the briefs.
Please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b739fc5c-de44-7299-28a5-21e95bccf400
* Version Independent ID: 3a607530-01e6-e73a-0168-4e03a262a59c
* Content: [Understanding and using Hyper-V hypervisor scheduler types](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types.md)
* Product: **windows-server-hyper-v**
* GitHub Login: @allenma
* Microsoft Alias: **allenma**

**Comment by prof79** [comment]
Sorry I need to correct myself, I got confused with the lot of VMs in my farm - the virtual processors in VM settings get AUTOMATICALLY HALVED! So if I have an Exchange VM with 8 virtual processors in VM settings then with HwThreadsPerCore = 2 the VM will boot with 4 cores and 8 threads/virtual processors - so the virtual threads equal the number of processors in VM settings. That also indirectly proves my understanding of virtual threads being relevant for core licensing. (To be exact on systems with more than 2 threads per core calculation probably goes like this: (VM vCPUs) / HwThreadsPerCore at least for vCPUs >= HwThreadsPerCore)

**Comment by IngridAtMicrosoft** [comment]
#please-close
