### ISSUE TITLE
question regarding Exchange ECP publishing

### ISSUE THREAD

**Issue by partyfacemsn** [MicrosoftDocs/windowsserverdocs#1446]
Hi,

I'm preparing to upgrade my MCSA certificate to Server 2016 and I recognized this site mentioned publishing of Exchange Control panel Pre-authentication supports only pass-through but this site ( https://docs.microsoft.com/en-us/Exchange/clients/outlook-on-the-web/ad-fs-claims-based-auth#step-4-create-a-relying-party-trust-and-custom-claim-rules-in-ad-fs-for-outlook-on-the-web-and-the-eac ) said there is a possibility to publish with ADFS.  Please check it.

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6eab4e1f-d36f-3af5-a470-748544db10c6
* Version Independent ID: 507b5d01-0566-2459-a9c4-006ce7681a54
* Content: [Publishing Applications with SharePoint, Exchange and RDG](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/web-application-proxy/publishing-applications-with-sharepoint%2c-exchange-and-rdg)
* Content Source: [WindowsServerDocs/remote/remote-access/web-application-proxy/Publishing-Applications-with-SharePoint,-Exchange-and-RDG.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/web-application-proxy/Publishing-Applications-with-SharePoint,-Exchange-and-RDG.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#please-close
