### ISSUE TITLE
is it supported to use "Microsoft Report Viewer Runtime 2015" for WSUS reporting ?

### ISSUE THREAD

**Issue by HarishsabarinathanMSFT** [MicrosoftDocs/windowsserverdocs#1451]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa4be2a-4045-4135-353a-ed882ada9402
* Version Independent ID: c43f3896-9f9b-2754-9b5d-d73f9650592b
* Content: [Plan Your WSUS Deployment](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/plan/plan-your-wsus-deployment)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/plan/plan-your-wsus-deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/plan/plan-your-wsus-deployment.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by shortpatti** [comment]
Closing as no feedback was provided.
