### ISSUE TITLE
remoteapp first screen ok, after nothing

### ISSUE THREAD

**Issue by Condorello** [MicrosoftDocs/windowsserverdocs#1456]
Hi, i've setup the whole system and works fine for app like Paint, WordPad etc.
With one of my software, which works fine with standard remoteapp, in the webclient when i launch that the first screen appear (EULA license to confirm), after black. The backbone process appear in the task manager of the remote user so it's launched, but not appear the gui in the web client. How can i debug that?
THanks

**Comment by IngridAtMicrosoft** [comment]
#please-close
