### ISSUE TITLE
FamiliarLockout and UnknownLockout

### ISSUE THREAD

**Issue by Alneowyld** [MicrosoftDocs/windowsserverdocs#1457]
Currently these entries state: "...this indicates if the user is currently in a state of lockout for correct password attempts..."
Shouldn't this be for incorrect password attempts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8634165-2ff5-9b01-e3fc-17827360a5f3
* Version Independent ID: a5a91921-3193-93ad-df22-d486e65b19f8
* Content: [Configure AD FS Extranet Lockout Protection](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-extranet-smart-lockout-protection)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by xXxOlivierxXx** [comment]
This request is only asking for a typo correction in the article, why has it been open for so long without resolution?

**Comment by MicrosoftGuyJFlo** [comment]
Sorry @xXxOlivierxXx I did not get a notification that this was assigned to me. Not usually my area of expertise but that sounds accurate. I can get this added to my backlog to update or if you would like to make the edit with the edit button at the top of the page I am happy to approve the PR.

**Comment by xXxOlivierxXx** [comment]
It's all good. I just corrected likes 296 and 298, replaced the word "Correct" with "Incorrect"
