### ISSUE TITLE
Error in Internet Explorer

### ISSUE THREAD

**Issue by FC-EricWeller** [MicrosoftDocs/windowsserverdocs#1458]
There's a minor error in the Internet Explorer section, after the "Delete Browsing History" section.  Specifically, it states that "Advanced Settings" is at the "Internet Explorer" level.  In fact it's under the "Internet Settings" subfolder.  Specifically: Administrative Templates\Windows Components\Internet Explorer\Internet Settings\Advanced Settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a83e1751-011c-9add-2c0a-63159fef97da
* Version Independent ID: 119b5192-3775-f71e-579d-9ead105ed1b0
* Content: [Recommended configuration for VDI desktops](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-vdi-recommendations)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-vdi-recommendations.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-vdi-recommendations.md)
* Product: **windows-server-threshold**
* GitHub Login: @jaimeo
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
#please-close
