### ISSUE TITLE
Publish-RDWebClientPackage Errors

### ISSUE THREAD

**Issue by szolla** [MicrosoftDocs/windowsserverdocs#1459]
I am trying to follow along in this guide for a server that is not connected to the internet.  I was able to download the module RDWebClientManagement successfully and import the module.  I have problems with steps 5 and 6.  I can't do the install-RDWebClientPackage because i am not online.  Then when i go to run the command 'Publish-RDWebClientPackage -Type Test -Latest' on my server it failes with The requested Client Package is not installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Product: **windows-server-threshold**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Heidilohr** [comment]
@szolla Please see [this thread](https://github.com/MicrosoftDocs/windowsserverdocs/issues/695) for more details.

**Comment by Heidilohr** [comment]
@szolla I'm contacting the dev team right now to see if they can help you. I also recommend emailing the team directly through the link at the bottom of the page.

**Comment by Heidilohr** [comment]
@szolla The dev team told me that the current version of the web client doesn't support offline installation. I suggest that you make a request to add the feature in the [Remote Desktop suggestion box](https://aka.ms/rdwebfbk). If you have any further questions, please [email the dev team](mailto:rdwbclnt@microsoft.com).

**Comment by GMKBabu** [comment]
Hi,
i'm getting this error can you help me how to fix this?

PS C:\Windows\system32> Publish-RDWebClientPackage -Type Production -Latest
UpdateIISContext : RD Web Access does not appear to be installed on the system.
At C:\Program Files\WindowsPowerShell\Modules\RDWebClientManagement\1.0.3\RDWebClientManagement.psm1:865 char:11

if (!(UpdateIISContext $iisContext))
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException
FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,UpdateIISContext
