### ISSUE TITLE
Clarify That MkLink Is an Internal Command

### ISSUE THREAD

**Issue by txwizard** [MicrosoftDocs/windowsserverdocs#1463]
Though it is hardly the end of the world, I just wasted several minutes running a couple of volume-wide searches for the non-existent mklink.exe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe72a6d-c0c6-8cc1-fc16-9912594fbe3e
* Version Independent ID: b6ce16a6-8f41-5551-d55f-244238814459
* Content: [mklink](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink)
* Content Source: [WindowsServerDocs/administration/windows-commands/mklink.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/mklink.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by mdougc** [comment]
Me too. I get error message in PowerShell:
mklink : The term 'mklink' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
