### ISSUE TITLE
Discrepancy

### ISSUE THREAD

**Issue by tbkobberoe** [MicrosoftDocs/windowsserverdocs#1464]
In the "Applies to" section Windows 10 and Server 2016 is mentioned, but not in the Prerequisites section. Is it still applicable for these versions?

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: bb523d20-85bb-82b5-7e0a-f0455c48944c
* Version Independent ID: 7663ccd7-eb64-b461-4fbb-8bd669cda9b2
* Content: [Enable optimized moves of redirected folders](https://docs.microsoft.com/da-dk/windows-server/storage/folder-redirection/enable-optimized-moving)
* Content Source: [WindowsServerDocs/storage/folder-redirection/enable-optimized-moving.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/folder-redirection/enable-optimized-moving.md)
* Product: **windows-server-threshold**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by JasonGerend** [comment]
Great catch--thanks for letting us know about this. I'm fixing it right now and an update should be live by this evening (Pacific Time).
