### ISSUE TITLE
which one is used in a mix environement?

### ISSUE THREAD

**Issue by sasanmcp** [MicrosoftDocs/windowsserverdocs#1467]
so, what happens when I have both per device and per user licenses installed on a licensing server, and a brand new user using a brand new workstation connects to RDS? will it trigger the user license or the device license? how would RDS determine with one to assign?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d69b9ea-9672-c267-03e4-a34bf105d31b
* Version Independent ID: bddcfc0f-77d6-ff1c-9af3-c5b3ad11ba63
* Content: [License your RDS deployment with client access licenses (CALs)](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-client-access-license)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-client-access-license.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-client-access-license.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
#please-close
