### ISSUE TITLE
/Y - not a clear description

### ISSUE THREAD

**Issue by schittli** [MicrosoftDocs/windowsserverdocs#1474]
it's really very annoying that M$$ is more focused to hoard money and raise prices instead of doing basic homework and reading the own docs. Of course, it's cheap to ask the paying customers if the docs are useful. 
But it's a shame. 
Anyway.

For /Y you explain:
"Suppresses prompting to confirm that you want to overwrite an existing destination file."

Of course, the most imporant question is:
Does it just suppress the question and overwrite the file
or does it suppress the question and therefore will not overwrite the file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 544925b9-8587-3e0e-9d49-44b77dbd290d
* Version Independent ID: e9969211-1085-ca1f-afb5-b619edbbfab3
* Content: [xcopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/xcopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/xcopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/xcopy.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by dawnwood** [comment]
Hi @schittli It will overwrite the file.

**Comment by schittli** [comment]
Good evening dawnwood
Thank you for your information, but the issue is not to understand what's happening - every user can do that himself - but in the fact that the documentation is unclear.

**Therefore such tickets should not be closed until the problem has been corrected, i.e. the documentation is updated.**

**It's really very strange that customers must explain such fundamental principles.** 
It looks like M$ is not interested in doing the homework and offer the most basic Docs to the paying customers. Yes, I'm very sorry, but M$ is a shame.

**Comment by dawnwood** [comment]
Hello @schittli I do not wish to upset you but I disagree that the documentation is not clear on this point. The sentence says that the prompt is suppressed. That's all that is changed from the normal behavior. That said, I will pass this feedback on.
Best,
Dawn
