### ISSUE TITLE
Principle of least privilege for credential calling 'New-ADServiceAccount' and 'Add-ADComputerServiceAccount'

### ISSUE THREAD

**Issue by SQLHorizons** [MicrosoftDocs/windowsserverdocs#1476]
We wish to automate the deployment of SQL Services without exposing unnecessary permissions to the calling process, what are the least permissions required to enable the creation of a MSA object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b34e4807-4310-c1cd-5ae5-a4bba32cb532
* Version Independent ID: a2739dc4-3ddd-34eb-1619-e2bffc6619c7
* Content: [What's New for Managed Service Accounts](https://docs.microsoft.com/en-us/windows-server/security/group-managed-service-accounts/what-s-new-for-managed-service-accounts)
* Content Source: [WindowsServerDocs/security/group-managed-service-accounts/what-s-new-for-managed-service-accounts.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/group-managed-service-accounts/what-s-new-for-managed-service-accounts.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Justinha** [comment]
@SQLHorizons This topic says you need Create/Delete msDS-ManagedServiceAccount

https://docs.microsoft.com/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd548356(v=ws.10) 

We will look at migrating that topic to the current library.

**Comment by SQLHorizons** [comment]
@Justinha  Thank you.

But to be complete we need Create/Delete on both **msDS-ManagedServiceAccoun**t and **msDS-GroupManagedServiceAccount** for this to work. (based on the test I've just completed on Windows 2016).  In addition you'll need Read\Write msDS-HostServiceAccount on dependent computer objects within the OU of the computer objects where you wish to assign the MSA.
