### ISSUE TITLE
them script are not really working

### ISSUE THREAD

**Issue by jakko101** [MicrosoftDocs/windowsserverdocs#1477]
it says to copy paste the script to powershell and run it (just need to change false_or_true, which I've done)

To configure MFA globally based on user’s location

PS C:\Windows\system32&gt; $MfaClaimRule = “c:[Type == '" https://schemas.microsoft.com/ws/2012/01/insidecorporatenetwork’"
, Value == '"false’"]
At line:1 char:32
+ ... [Type == '" https://schemas.microsoft.com/ws/2012/01/insidecorporaten ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'https://schemas.microsoft.com/ws/2012/01/insidecorporatenetwork’", Value == '"false’"]' in expression
 or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe724261-c768-f16a-7bee-e2d46c3c8118
* Version Independent ID: 85581459-30f8-a946-db97-4f94ccf7e8ad
* Content: [Configure Authentication Policies](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-authentication-policies#to-configure-mfa-globally-based-on-users-group-membership-data)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-Authentication-Policies.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-Authentication-Policies.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#please-close
