### ISSUE TITLE
What is the behavior of the new scheduler on older AMD CPUs with CMT?

### ISSUE THREAD

**Issue by nmdange2** [MicrosoftDocs/windowsserverdocs#1479]
Will Hyper-V use the Core scheduler on Bulldozer-based AMD Opteron CPUs?   The CMT technology in these CPUs is different from SMT but Windows reports it as 2 threads per core.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b739fc5c-de44-7299-28a5-21e95bccf400
* Version Independent ID: 3a607530-01e6-e73a-0168-4e03a262a59c
* Content: [Understanding and using Hyper-V hypervisor scheduler types](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types.md)
* Product: **windows-server-hyper-v**
* GitHub Login: @allenma
* Microsoft Alias: **allenma**

**Comment by IngridAtMicrosoft** [comment]
#please-close
