### ISSUE TITLE
Side menu Spelling Error

### ISSUE THREAD

**Issue by ChrisParrBIE** [MicrosoftDocs/windowsserverdocs#1482]
Configure - Manage Azure VMs with "Widnows" Admin Center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae730e6-5e1e-1ae6-5cbd-9eb6d271690b
* Version Independent ID: a79daa4b-e8fb-0ed4-867c-430b3c61ceea
* Content: [Configuring Azure Integration](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/configure/azure-integration)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/configure/azure-integration.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/configure/azure-integration.md)
* Product: **windows-server-threshold**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by dawnwood** [comment]
@ChrisParrBIE Nice catch! Thank you for sending this feedback. I've updated the page.
