### ISSUE TITLE
Format of `.reg` File

### ISSUE THREAD

**Issue by TSlivede** [MicrosoftDocs/windowsserverdocs#1483]
It would be nice, to have a link to a page, that documents the `.reg` file format.

Are there references, that are more complete and up to date than these?
 - [How to add, modify, or delete registry subkeys and values by using a .reg file](https://support.microsoft.com/en-us/help/310516/how-to-add-modify-or-delete-registry-subkeys-and-values-by-using-a-reg) (Does not mention how to escape strings and how to add comments.)
 - [Registry File (Compact 2013)](https://docs.microsoft.com/en-us/previous-versions/windows/embedded/gg469889(v=winembedded.80)) (Old and not written for `regedit.exe` or `reg.exe` but for `Makeimg.exe`, so I don't know if everything applies here.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f97c3a2-583c-05ec-da3d-10440e32c935
* Version Independent ID: eee69a85-9306-720e-d85b-9fb0740901b0
* Content: [reg import](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/reg-import)
* Content Source: [WindowsServerDocs/administration/windows-commands/reg-import.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/reg-import.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by TSlivede** [comment]
As @IngridAtMicrosoft [said](https://github.com/MicrosoftDocs/windowsserverdocs/pull/5971#issuecomment-946095953)

>Please go back to the issues that you have opened and comment on them asking for them to be reopened.

Please reopen!

**Comment by IngridAtMicrosoft** [comment]
#please-reopen

**Comment by dknappettmsft** [comment]
Hi @TSlivede, thanks for this feedback.  There isn't anything that's more up to date or comprehensive that I'm aware of, so I've added it to the Docs backlog as a new content request.

As this isn't a particular issue with this specific article, but a new content request I will close this issue.  The content you're requesting isn't appropriate to go in this article as it's a command (exe) reference, hence it would be new content in a different location.

#please-close
