### ISSUE TITLE
Add document about Sign in Header

### ISSUE THREAD

**Issue by hilfans** [MicrosoftDocs/windowsserverdocs#1485]
there is already document about change sign in description, please also add documents about sign in header, witch is by default the sign in header is "Sign in with your organizational account".

It would be valuable, if it can be edited, so it can be add another information, like add information direction to use custom own domain, example "Please enter username with user@domain.com"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2c2dc96-10bc-9afe-905e-7873377cdb16
* Version Independent ID: 2c2c76d8-9a59-6c6a-4890-d48a15315a63
* Content: [AD FS user sign-in customization](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/ad-fs-user-sign-in-customization)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/AD-FS-user-sign-in-customization.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/AD-FS-user-sign-in-customization.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by MicrosoftGuyJFlo** [comment]
@billmath Can you take a look at this?

**Comment by billmath** [comment]
Thanks @MicrosoftGuyJFlo 

@hilfans thank you for the submission.  Let me try and clarify what you are asking.  Are you requesting additional documentation on how to customize the header for the sign-in page?  Thanks!

**Comment by hilfans** [comment]
Hi @MicrosoftGuyJFlo and @billmath  Thank you for your kind attention and fast response,

Yes Bill, it's a good idea if in this page: https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/AD-FS-user-sign-in-customization.md

there is also put a step documentation for change the header information (text before input username box), using Windows PowerShell PowerShell cmdlet and syntax.

see this pic.
![change header login adfs](https://user-images.githubusercontent.com/756550/46052767-f7ec8580-c169-11e8-926c-d1c016885e5b.jpg)

**Comment by Icebird** [comment]
@MicrosoftGuyJFlo @billmath This would be valuable to my organization as well.  We are also hoping to be able to modify:

1. Meta tags such as "description" and "keywords" for SEO 
2. The HTML page Title tag which shows in your browser tab and may be used for search results as well

The bottom line for us is the ADFS 3 sign-in page makes for a pretty generic-looking search result, even after customizing with the available commands.

**Comment by stevema4567** [comment]
@hilfans I don't see that you ever got a response to your request to change the “Sign in with organizational account” string. I found the answer a long time ago and have used it, but I am just now coming across this thread. The answer can be found at https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn636121(v=ws.11)?redirectedfrom=MSDN.

Additional Customization Examples

The following are the examples of custom code added to onload.js for different fine-tune purposes. When adding the custom code, please always append your custom code to the bottom of the onload.js.

Example 1: change “Sign in with organizational account” string

The default AD FS form-based sign-in page has a title of “Sign in with your organizational account” above user input boxes.

If you want to replace this string with your own string, you can add the following code to onload.js.

 ＝ Copy 
// Sample code to change “Sign in with organizational account” string.

// Check whether the loginMessage element is present on this page.
var loginMessage = document.getElementById('loginMessage');
if (loginMessage)
{
       // loginMessage element is present, modify its properties.
       loginMessage.innerHTML = 'Your company description text';
}


Example 2: accept SAM-account name as a login format on an AD FS form-based sign-in page

The default AD FS form-based sign-in page supports login format of User Principal Names (UPNs) (for example, **johndoe@contoso.com**) or domain qualified sam-account names (contoso\johndoe or contoso.com\johndoe). In case all of your users come from the same domain and they only know about sam-account names, you may want to support the scenario where the users can sign in using them sam-account names only. You can add the following code to onload.js to support this scenario, just replace the domain “contoso.com” in the example below with the domain that you want to use.

 ＝ Copy 
if (typeof Login != 'undefined'){
    Login.submitLoginRequest = function () { 
    var u = new InputUtil();
    var e = new LoginErrors();
    var userName = document.getElementById(Login.userNameInput);
    var password = document.getElementById(Login.passwordInput);
    if (userName.value && !userName.value.match('[@\\\\]')) 
    {
        var userNameValue = 'contoso.com\\' + userName.value;
        document.forms['loginForm'].UserName.value = userNameValue;
    }

    if (!userName.value) {
       u.setError(userName, e.userNameFormatError);
       return false;
    }


    if (!password.value) 
    {
        u.setError(password, e.passwordEmpty);
        return false;
    }
    document.forms['loginForm'].submit();
    return false;
};
}

**Comment by hilfans** [comment]
hi @stevema4567 thank you, I'm already did that and it was great...
