### ISSUE TITLE
Windows Admin Center: FQDN interpretation cause connection impossible (Server management)

### ISSUE THREAD

**Issue by eda2000** [MicrosoftDocs/windowsserverdocs#1486]
Background:
We have domains AAA.com and BBB.com . Some servers are registered in domain AAA.com, but are accessible from domain BBB.com using BBB.com suffix (but not using AAA.com).
Issue:
I have installed Windows Admin Center on server with domain suffix AAA.com and added server registered in BBB.com domain using AAA.com suffix (=> typed to hostname S1.AAA.com). But server was added to list as S1.BBB.com . Such a hostname (S1.BBB.com) is not pingable from AAA.com domain (S1.AAA.com is), so I am not able to connect to and manage the server,

Can you fix it, please?

Thank you. Ondrej.

**Comment by dawnwood** [comment]
Hi @eda2000 thank you for your question. This looks like a question about how to use the product, not feedback on a topic on docs.microsoft.com. Am I interpreting your comment correctly? If so, you have two better options for communicating your question. The first is the "product feedback" button right next to the "documentation feedback" button at the bottom of  every topic. The second is the [product forum](https://techcommunity.microsoft.com/t5/Windows-Server-Insiders/bd-p/WindowsServerInsiders) where experts and product team members can help.
I'm closing this doc feedback but feel free to reply back if I am misunderstanding your question.
Best,
Dawn
