### ISSUE TITLE
Remote Desktop Web Client Windows button causes freeze

### ISSUE THREAD

**Issue by JacobT14** [MicrosoftDocs/windowsserverdocs#1487]
Hey all!

Basically if I am inside of a remote app while using the RD Web client, if I hit the windows button it opens my local start menu, and after about 5 seconds the RD client's start menu opens.  At this point, everything is frozen and to unfreeze I have to hit the windows button again.

**Comment by dawnwood** [comment]
Hi @JacobT14 thank you for your feedback. This looks like product feedback, not feedback on a topic on docs.microsoft.com. Am I interpreting your comment correctly? If so, you have two better options to communicate your feedback and to ask for help. The first is the "product feedback" button right next to the "documentation feedback" button at the bottom of  every topic. The second is the [product forum](https://techcommunity.microsoft.com/t5/Windows-Server-Insiders/bd-p/WindowsServerInsiders) where experts and product team members can help.
I'm closing this doc feedback but feel free to reply back if I am missing your point.
Best,
Dawn
