### ISSUE TITLE
/add and /generic can be used to update records

### ISSUE THREAD

**Issue by mkupper** [MicrosoftDocs/windowsserverdocs#1491]
At present the documentation has
/add: 	 	adds a user name and password to the list.
/generic: 	adds generic credentials to the list.

As both options support updating or changing an existing record the wording should be:
/add: 	 	adds a user name and password to the list or updates the user name and/or password for an existing record.
/generic: 	adds generic credentials to the list or updates the generic credentials for an existing record..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caebc8e0-4c03-4714-b7a8-3d55ef0f6ab1
* Version Independent ID: 5a7b7ad8-8f55-fb3e-54ee-b8aff333b7c7
* Content: [cmdkey](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cmdkey)
* Content Source: [WindowsServerDocs/administration/windows-commands/cmdkey.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/cmdkey.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
#please-close
