### ISSUE TITLE
coudl not figure it out

### ISSUE THREAD

**Issue by heschelpop** [MicrosoftDocs/windowsserverdocs#1492]
when I pasted the command:  PS C:\Windows\system32&gt; Set-Item WSMan:\localhost\Client\TrustedHosts -Value "fqdn-of-hyper-v-host"
Set-Item : The client cannot connect to the destination specified in the request. Verify that the service on the destination is running and is accepting requests. 
Consult the logs and documentation for the WS-Management service running on the destination, most commonly IIS or WinRM. If the destination is the WinRM service, run 
the following command on the destination to analyze and configure the WinRM service: "winrm quickconfig". 
At line:1 char:1
+ Set-Item WSMan:\localhost\Client\TrustedHosts -Value "fqdn-of-hyper-v ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-Item], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.SetItemCommand

Do I need to make any entry of the above specific - ie change generic placeholder text - if so, specific hypotheticals would be infinitely valuable to demonstrate this, which might take another 30 seconds of the technical writers time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c4bb2d4-9b81-b153-6936-3ca0f95bf631
* Version Independent ID: 968f574d-3be8-2af6-7470-d4e1f65b4a48
* Content: [Remotely manage Hyper-V hosts](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/remotely-manage-hyper-v-hosts)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/Remotely-manage-Hyper-V-hosts.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/Remotely-manage-Hyper-V-hosts.md)
* Service: **na**
* Product: **windows-server-threshold**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by dawnwood** [comment]
Hi @heschelpop In the example you use, you do have to replace the text in quotes with a specific value from your system, so that "fqdn-of-hyper-v-host" is the fully qualified domain name of the Hyper-V host that you are connecting to.
