### ISSUE TITLE
Windows Server 2012 R2 Setup error

### ISSUE THREAD

**Issue by VolodymyrZhyla** [MicrosoftDocs/windowsserverdocs#1493]
Hi, I wanted to set up Windows Server 2012 R2 on my laptop for the training and learning. 
Downloaded ISO trial version form Windows evaluation center there- https://www.microsoft.com/ru-ru/evalcenter/evaluate-windows-server-2012-r2

However, the error pops-up every time during installation when the restart is needed. The blue screen is there. But this is not the BSOD. It tells like "the error appears on your PC and it must be restarted". Then multiple restarts with this error continue. 

If press on CTRL+ALT+DEL and boot the ordinary Windows 10, then I have the next:
"This version of Windows can't be installed. Your previous version of Windows has been restored, and you can continue to use it. Before trying to install this version of Windows again, check online to see if it is compatible with your computer."

But my laptop characteristics are OK for this soft. 
Processor: AMD A6-7310 APU with AMD Radeon R4 Graphics 2 GHz. 
RAM: 4 GB
x64 based operational system type, processor x64

Before installation of Windows Server 2012 R2, I tried also the next instruction from there - https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/jj134246(v=ws.11)
To disable the signature requirement for the current boot process:

Restart the computer and during startup, press F8.

Select Advanced Boot Options.

Select Disable Driver Signature Enforcement.

Boot into Windows® and uninstall the unsigned driver.

As well I tried to install similar versions, Windows Server 2012, Windows Server 2008 R2. There the same error pops-up. 

I downloaded  Virtual Labs and VHD files for the installment of Windows Server 2012 R2, but the same error. 

Have found similar cases in the Interner that BIOS must be updated. Particularly, there - www.supermicro.com/support/resources/results
But I am afraid the situation that even BIOS can't not properly after such an update. 

Please, help!

**Comment by dawnwood** [comment]
Hi @VolodymyrZhyla I am sorry to say that the topic you followed is no longer maintained. It looks like you have a lot of detail about what is happening. I suggest that you try posting this question in the [product forum](https://social.technet.microsoft.com/Forums/windowsserver/en-US/home), where experts and product team members can help.
