### ISSUE TITLE
Example that works immediately is missing.

### ISSUE THREAD

**Issue by kjeasy** [MicrosoftDocs/windowsserverdocs#1495]
I find the example, using some arbitrary (?) paths and file names not helpful.
What about an example that works out of the box, e.g. an example to export the current standard operating system data to stdout?
Thanks. Klaus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2ee3438-0dfd-bfa8-4ec4-32cd1eafe1f8
* Version Independent ID: fb80b624-fcaf-b317-a999-8f6074be3feb
* Content: [secedit:export](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/secedit-export)
* Content Source: [WindowsServerDocs/administration/windows-commands/secedit-export.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/secedit-export.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
#please-close
