### ISSUE TITLE
Backend Pool before Load Balancing Rules

### ISSUE THREAD

**Issue by bozford** [MicrosoftDocs/windowsserverdocs#1497]
In Section "Step 3: Configure load balancing for the RD Web and RD Gateway servers"
Step 4 (Create the backend pool for the RD Web and RD Gateway servers) needs to happen before Step 3 (Create the HTTPS and UDP load balancing rules).

Creating them in the order described above gives the following error:
"A backend pool must exist before you can create a rule. You can create one at Settings &gt; Backend pools, or by clicking here."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b83e43bd-69b6-783d-b377-af76e15e82e6
* Version Independent ID: e65dbfd5-6a8e-09b4-e104-871f7a58a71e
* Content: [Add high availability to the RD Web and Gateway web front](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-rdweb-gateway-ha#step-3-configure-load-balancing-for-the-rd-web-and-rd-gateway-servers)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-rdweb-gateway-ha.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-rdweb-gateway-ha.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
#please-close
