### ISSUE TITLE
Please verify option 118 accuracy

### ISSUE THREAD

**Issue by somewhatlogical** [MicrosoftDocs/windowsserverdocs#1498]
Based on the DHCP subnet selections options page, 118 was removed from the documentation since it is not available in 2016 (https://github.com/MicrosoftDocs/windowsserverdocs/issues/1012).  Can you verify the statement on this page "DHCP now supports options 118 and 82 (sub-option 5). You can use these options to allow DHCP proxy clients and relay agents to request an IP address for a specific subnet, and from a specific IP address range and scope." is accurate, or adjust it to remove 118 accordingly?  Don't know if it just came in update and is now available, or if it is referencing the now-defunct information from the subnet selection options page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e6bf5e2-7bc5-bbd5-54e2-772fbcc3cd8e
* Version Independent ID: 181cd9db-73b5-510c-f259-6fa28134e566
* Content: [What's New in DHCP](https://docs.microsoft.com/en-us/windows-server/networking/technologies/dhcp/what-s-new-in-dhcp)
* Content Source: [WindowsServerDocs/networking/technologies/dhcp/What-s-New-in-DHCP.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/dhcp/What-s-New-in-DHCP.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by IngridAtMicrosoft** [comment]
#please-close
