### ISSUE TITLE
Typos in Enabling or Disabling additional cipher suites section

### ISSUE THREAD

**Issue by mike-crist** [MicrosoftDocs/windowsserverdocs#1506]
The path to the registry entry is incorrect, it should be HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Cryptography\Configuration\Local\SSL\00010002

This sentence is also incorrect: "To enable a cipher suite, at it's string value to the Functions multi-string value key." It should be "To enable a cipher suite, add its string value to the Functions multi-string value key."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ae56e74-1346-a822-2800-70db6d365376
* Version Independent ID: ccf848e1-5276-1f3f-73e8-036dba9c66a7
* Content: [Managing SSL/TLS Protocols and Cipher Suites for AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/manage-ssl-protocols-in-ad-fs#enabling-or-disabling-additional-cipher-suites)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Manage-SSL-Protocols-in-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Manage-SSL-Protocols-in-AD-FS.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by doctordns** [comment]
which registry value is incorrect - there are a lot of registry addresses in this article.

**Comment by doctordns** [comment]
I think the PR #2150 resolves these two issues. Good catch.

**Comment by doctordns** [comment]
I think this can probably be closed.

As an aside, why so many issues being closed then reopened today? :-)

**Comment by illfated** [comment]
@doctordns : Thank you for following up on this ticket. I may not know the exact answer to your question about the closing & reopening of lots of tickets, but I think it could be an attempt to have the ticket author re-check their tickets to see if they can be closed, or at least reactivate the "Unread" state of the ticket for other users involved.

Anyway, thank you for your PR contribution too. I will ask for this ticket to be closed.

#please-close

**Comment by doctordns** [comment]
Thanks for the explanation.  I still have a lot to learn about how to best use Github. :-)
