### ISSUE TITLE
Gpupdate /H flag 

### ISSUE THREAD

**Issue by David-H-Bolton** [MicrosoftDocs/windowsserverdocs#1509]
Gpupdate /H doesn't seem to work on Windows 10. An error message from gpupdate suggested doing this to identify the cause of an error but when I do Gpudate /H filename.html it just lists the Gpupdate commands.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e814d48a-81cc-ed0c-13be-960767ea6e2b
* Version Independent ID: c9a790b8-1b19-2a67-b620-e09061379365
* Content: [gpupdate](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/gpupdate)
* Content Source: [WindowsServerDocs/administration/windows-commands/gpupdate.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/gpupdate.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Robert-LTH** [comment]
If i am not mistaken the command you use that parameter with is gpresult.

**Comment by poundy** [comment]
agreed - you're looking for GPResult not GPUPDATE ;-) That's why there was no description for the /H switch in the above
