### ISSUE TITLE
No longer in preview?

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/windowsserverdocs#1514]
It looks like this feature was included in the GA release of Windows Admin Center v1809.  Can I assume that it's out of 'preview' status and fully supported for production use now?
Also, the note at the top of this article says the feature is only supported when Windows Admin Center preview is installed on a Windows 10 computer.  Is it still true for the GA release of WAC v1809 that this feature only works when WAC is installed on a Windows 10 computer?  Or is it available when WAC is installed on a server OS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a6e5837-7436-063b-96db-6a6fb481b842
* Version Independent ID: d42ec8cb-c614-896e-50fb-34b6e7906c53
* Content: [Use Windows Admin Center to manage operating system updates with Azure Update Management](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/azure-update-management)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/use/azure-update-management.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/use/azure-update-management.md)
* Product: **windows-server-threshold**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by jwwool** [comment]
This feature is GA and supported on both desktop and server installations. I will update the page.
