### ISSUE TITLE
Return Codes

### ISSUE THREAD

**Issue by jasminrueegger** [MicrosoftDocs/windowsserverdocs#1517]
Please also document the possible return codes for correct error handling

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ae343da-c309-25a7-de46-7686c52d67a6
* Version Independent ID: 31528308-97c6-8bdd-bea8-c091c26a191b
* Content: [regsvr32](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/regsvr32)
* Content Source: [WindowsServerDocs/administration/windows-commands/regsvr32.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/regsvr32.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by 256tjq1l9mbzvh17lmosharklaserscom** [comment]
This is a great source on the topic, for anybody who ends up here from the docs, and for @coreyp-at-msft to do the writing: https://devblogs.microsoft.com/oldnewthing/?p=99785

**Comment by IngridAtMicrosoft** [comment]
#please-close
