### ISSUE TITLE
No BREAK key on microsoft laptops

### ISSUE THREAD

**Issue by ricardoogsequeira** [MicrosoftDocs/windowsserverdocs#1521]
Hello, an alternative should be provided for people who have Microsoft hardware (surface Pro or Book), as there's no BREAK key, which means there's no easy way to switch back to host system. Most people use this fuctionality all the time, so it becomes almost unusable. Better would be able to simply allow for customization.
Thanks in advance.

---
#### Detalhes do Documento

⚠ *Não edite esta secção. É necessário para a ligação de problemas docs.microsoft.com ➟ GitHub.*

* ID: 7c67eb5e-7fb1-0840-dfe0-40955b3f9489
* Version Independent ID: f30efc81-d336-2ff2-3fe5-5eb3f9432d82
* Content: [Hyper-V Virtual Machine Connection](https://docs.microsoft.com/pt-pt/windows-server/virtualization/hyper-v/learn-more/hyper-v-virtual-machine-connect)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/learn-more/hyper-v-virtual-machine-connect.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/learn-more/hyper-v-virtual-machine-connect.md)
* Product: **windows-server-threshold**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by IngridAtMicrosoft** [comment]
#please-close
