### ISSUE TITLE
'User Name' field cannot contain '%' character.

### ISSUE THREAD

**Issue by michalzindulka** [MicrosoftDocs/windowsserverdocs#1526]
Some of the 3rd party Gateway solutions may use '%' character to parse the connection string. Old version of client had no problem with that. Example of 'User Name' connection string: mycompany\ticketid~12345%johndoe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 526c6220-c5f5-7dce-3239-66e5134cd40e
* Version Independent ID: 598ceeef-0f46-fff1-8528-45c12e112612
* Content: [Get started with Remote Desktop on Mac](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-mac)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
#please-close
