### ISSUE TITLE
2016? 

### ISSUE THREAD

**Issue by Curtmcgirt** [MicrosoftDocs/windowsserverdocs#1528]
"step 1" doesn't mention server 2016. does that imply that the registry change is not needed on server 2016, and that RDS users will automatically get a .v6 profile folder? because that's not what i'm seeing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7825e3cd-33bc-1264-f3ee-50fa93640ae4
* Version Independent ID: 3c00f44e-85a4-126f-c914-eb5ffc1fcb72
* Content: [Deploying Roaming User Profiles](https://docs.microsoft.com/en-us/windows-server/storage/folder-redirection/deploy-roaming-user-profiles)
* Content Source: [WindowsServerDocs/storage/folder-redirection/deploy-roaming-user-profiles.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/folder-redirection/deploy-roaming-user-profiles.md)
* Product: **windows-server-threshold**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#please-close
