### ISSUE TITLE
Clarification regarding the construction of the the sub claim

### ISSUE THREAD

**Issue by michaelkc** [MicrosoftDocs/windowsserverdocs#1534]
The value of the sub claim in ADFS 2016 is generated as a hash of the client ID, the anchor claim value and an array of crypto-random bytes. The array of crypto-random bytes is generated when ADFS 2016 is installed, and persisted in the ADFS configuration database.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8396683-4498-71bd-60a1-345277e1433e
* Version Independent ID: 36ed02b0-555a-4714-32f8-f4e0434adf51
* Content: [AD FS 2016 FAQ](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-faq)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/AD-FS-FAQ.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/AD-FS-FAQ.md)
* Product: **windows-server-threshold**
* GitHub Login: @jenfieldmsft
* Microsoft Alias: **billmath**

**Comment by jeremycook** [comment]
I am needing to calculate this value for pre-populating a database as part of a migration. The following is not enough information to do that. I've experimented but found nothing that works. Below is the closest I got.

> When generating an id_token with ADFS for a user authenticated against AD, how is the “sub” claim generated in the id_token?
> The value of “sub” claim is the hash of client ID + anchor claim value.

My best guess, but `sub` does not match what I get from ADFS:

```csharp
var clientId = Guid.Parse("ca6ed5af-82dc-4cc1-b311-fddbb4f98f05");
var mSDSConsistencyGuid = Guid.Parse("d0b0a8ed-2c11-4670-9e12-a6777f9d7e66");
string sub = Convert.ToBase64String(SHA256.Create().ComputeHash(clientId.ToByteArray().Concat(mSDSConsistencyGuid.ToByteArray()).ToArray()));
```

**Comment by michaelkc** [comment]
Just checked the docs, and unless something fundamentally changed internally in ADFS since this issue was opened, they remain incorrect.
https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-faq

**Comment by IngridAtMicrosoft** [comment]
Hi @michaelkc Thank you for your response.  The issue has been reopened.

**Comment by BennieCopeland** [comment]
Can the documentation for this be updated, or at least something added to this issue on how exactly the sub claim is constructed?

What I am trying to do in my application is use ADFS for OAuth, but use LDAP queries to Active Directory to allow users to manage permissions to data within my application. Without knowing how the sub claim is created, I cannot correlate user data queried from AD to a currently logged in user unless I add an additional claim using `objectGUID`, and then what is point of `sub`?

**Comment by jeremycook** [comment]
@BennieCopeland I hope this still helps you or someone else who reads this. Adding [objectGUID](https://learn.microsoft.com/en-us/windows/win32/ad/naming-properties#objectguid) seems like the way to go in your scenario. `sub` is unique per client+user pair which seems reasonable in hindsight even though when I first discovered that I was surprised. I believe that `sub` in an OAuth or OpenID Connect context is equivalent to [http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier claim type](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/technical-reference/the-role-of-claims#what-are-claim-types) in a SAML or WS-Federatíon context.

**Comment by svenso** [comment]
I had to calculate this id today.
if still anyone is interested, here is how:


```
 var appidBytes = Encoding.Unicode.GetBytes(appid);
 var userIdBytes = Encoding.Unicode.GetBytes(issuedNameId);
 var privacyEntropyBytes = ppid; // Get it from SELECT [ServiceSettingId], [ServiceSettingsData] FROM [IdentityServerPolicy].[ServiceSettings] --> with xpath "a:ServiceSettingsData/a:SecurityTokenService/a:PpidPrivacyEntropy"

 var completeBytes = appidBytes.Concat(userIdBytes).Concat(privacyEntropyBytes).ToArray();
 var hash = SHA256.HashData(completeBytes);
 var b64Hash = Convert.ToBase64String(hash);
```

**Comment by robinharwood** [comment]
We hugely appreciate your contribution, feedback, and support to our technical documentation.

We’ve phased out GitHub Issues on this repository as the feedback mechanism for content and have replaced it with a new feedback system. For more information see, [Content User Feedback](https://aka.ms/ContentUserFeedback). As part of this rollout, we are migrating your issue where our team will use your comments to improve the documentation experience. Unfortunately, this does mean you won't be able to access this issue after the migration is complete.

All issues will be migrated by Thursday 29th August 2024.

Once again, thank you for your valuable feedback, we hope you’ll continue to contribute using our new feedback system.
