### ISSUE TITLE
Seems some information is too old.

### ISSUE THREAD

**Issue by moskvach** [MicrosoftDocs/windowsserverdocs#1540]
15% free space needed for defragmentation - it is correct for Windows XP and Windows Server 2003 with 12.5% total disk space used for MFT zone. Since Vista and WS2008 MFT zone is 200MB by default and 800MB maximum so there is no need to free 15%.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd2e03d-280d-2122-4205-fa0c891f558a
* Version Independent ID: a6f868d1-78df-0bc3-3759-925521956192
* Content: [defrag](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/defrag)
* Content Source: [WindowsServerDocs/administration/windows-commands/defrag.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/defrag.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
#please-close
