### ISSUE TITLE
Still no complete list of guides for Server 2016 migration

### ISSUE THREAD

**Issue by TimAtNECS** [MicrosoftDocs/windowsserverdocs#1546]
Over 2 years on and still no complete list of guides for migration to Server 2016. When is this likely to be finished?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b4d9c0-d713-59ec-4880-0fb6a2a709fb
* Version Independent ID: 41ceb987-04f4-60ec-0bbd-32ee903de53e
* Content: [Migrating Roles and Features](https://docs.microsoft.com/en-us/windows-server/get-started/migrate-roles-and-features)
* Content Source: [WindowsServerDocs/get-started/Migrate-Roles-and-Features.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/Migrate-Roles-and-Features.md)
* Product: **windows-server**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by GLComputing** [comment]
Still not done ... and nothing in 2019 :-( 
Makes it difficult for those on 2008R2 or SBS2011 to plan and execute before the end-of-life

**Comment by jaimeo** [comment]
@eross-msft

**Comment by GLComputing** [comment]
How about some detailed ones on going to Server 2019, then?

**Comment by eross-msft** [comment]
@GLComputing  We're in the process of updating/moving this content into the 2019 Windows Server area. It should be complete in September.

**Comment by IngridAtMicrosoft** [comment]
#please-close
