### ISSUE TITLE
Migrate RD Licensing servers section

### ISSUE THREAD

**Issue by alears01** [MicrosoftDocs/windowsserverdocs#1547]
In the intro of this section it should be written "... to a destination server running Windows Server 2016" instead of "...to a destination server running Windows Server 2012 R2."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9ac782d-d585-fa70-6142-4c1524d70c75
* Version Independent ID: f280543a-f892-8891-8760-74f8dd12f746
* Content: [Migrate your Remote Desktop Services deployment to Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/migrate-rds-role-services#migrate-rd-licensing-servers)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/migrate-rds-role-services.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/migrate-rds-role-services.md)
* Product: **windows-server-threshold**
* GitHub Login: @ChristianMontoya
* Microsoft Alias: **chrimo**

**Comment by lizap** [comment]
Thanks for raising the issue - Christian submitted a fix, so we should be good.
