### ISSUE TITLE
Links broken when exporting to PDF

### ISSUE THREAD

**Issue by kimoppalfens** [MicrosoftDocs/windowsserverdocs#1551]
The Table of content links and most other links are currently broken when using the Download PDF button. This results in a PDF that is hardly usable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebd94ce7-2cab-c2b8-af5b-2cd022fd6dc7
* Version Independent ID: 860530bf-6f98-63fe-c242-1402a82051da
* Content: [Identity and Access](https://docs.microsoft.com/en-us/windows-server/identity/identity-and-access)
* Content Source: [WindowsServerDocs/identity/Identity-and-Access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/Identity-and-Access.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
