### ISSUE TITLE
Configure Internal Network Perimeter Firewall

### ISSUE THREAD

**Issue by IanCurrie** [MicrosoftDocs/windowsserverdocs#1552]
More inbound ports, besides those RADIUS ones, will need opening on the Internal perimeter firewall.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbeab4b7-f8d6-59ee-49df-fc4646fcbaea
* Version Independent ID: 1fceb417-3029-7b89-f583-560c05a68ad2
* Content: [Configure DNS and Firewall Settings](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-dns-firewall)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-dns-firewall.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-dns-firewall.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@MihaiSP, can you take a look at this issue?

**Comment by gerane** [comment]
+1

**Comment by IngridAtMicrosoft** [comment]
#please-close
