### ISSUE TITLE
Chromebook Screen Resolution Issue Samsung Pro / Plus for Microsoft RDP Client Android

### ISSUE THREAD

**Issue by rogerl19** [MicrosoftDocs/windowsserverdocs#1554]
When opening on RDP Client for Android on Chromebook, the screen does not scale correctly.  All the custom resolutions are wrong (aspect ratio) for the screen or attached monitor.  

If we use the default, the screen looks decent but still small.  However if you minimize the RDPClient window and come back, everything looks super small.  I found if you change the Chromebook Display size (Settings --> Displays) to anything other than 100%, then this problem does not happen.

Please fix the RDPClient app so that it can work properly if Display Size is set to 100%.  Also, please fix the Custom Resolutions to offer realistic screen resolution selections (such as 1920x1080 or common Chromebook aspect ratios)

**Comment by IngridAtMicrosoft** [comment]
#please-close
