### ISSUE TITLE
link is dead

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/windowsserverdocs#1561]
For the IPAM Windows PowerShell command reference, see IP Address Management (IPAM) Server Cmdlets in Windows PowerShell. 
Goes to a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10697246-b2b8-6cd8-a4f9-9ec3d38a3a0a
* Version Independent ID: 9c4c07c6-bd9c-c6a6-4dc5-f9c3d705f8c5
* Content: [Manage Role Based Access Control with Windows PowerShell](https://docs.microsoft.com/en-us/windows-server/networking/technologies/ipam/manage-role-based-access-control-with-windows-powershell)
* Content Source: [WindowsServerDocs/networking/technologies/ipam/Manage-Role-Based-Access-Control-with-Windows-PowerShell.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/ipam/Manage-Role-Based-Access-Control-with-Windows-PowerShell.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
Closing. Added the correct link: https://docs.microsoft.com/en-us/powershell/module/ipamserver/?view=win10-ps.
