### ISSUE TITLE
FWLink 73076 is broken

### ISSUE THREAD

**Issue by exchange12rocks** [MicrosoftDocs/windowsserverdocs#1573]
There's a link https://go.microsoft.com/fwlink/?LinkID=73076 used at [WindowsServerDocs/get-started-19/activation-19](../blob/master/WindowsServerDocs/get-started-19/activation-19.md) and at [WindowsServerDocs/get-started/Server-2016-activation](../blob/master/WindowsServerDocs/get-started/Server-2016-activation.md). The link redirects to https://www.microsoft.com/licensing/default.mspx which is a non-existent page.
Obviously, the link should just point to https://www.microsoft.com/licensing/ letting the web-server to decide what is the default page for that section.

What would be better? To fix the FWLink, or to fix the links in Markdown pages?

**Comment by jaimeo** [comment]
Assign to Corey; I don’t do Server anymore.
vv
J.O.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by doctordns** [comment]
I think PR #2146 addresses this issue.

**Comment by exchange12rocks** [comment]
I am sorry @doctordns , the PR is not complete: there are two documents affected, but you changed only one of them.

**Comment by exchange12rocks** [comment]
Furthermore, maybe it would be better to solve the root of the problem — the FWLink. But it is for @coreyp-at-msft to decide.

**Comment by doctordns** [comment]
I was under the impression that fwlinks were to be replaced by direct links. This was, as I under stood it since FWLinks require a MS employee to manage but the documents are open source. But @coreyp-at-msft can make the call.

**Comment by IngridAtMicrosoft** [comment]
#please-close
