### ISSUE TITLE
2019 AVMA keys

### ISSUE THREAD

**Issue by DSPatrick** [MicrosoftDocs/windowsserverdocs#1574]
Where are the Server 2019 AVMA keys?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc9df0c0-db17-3226-b734-59ebd27fa212
* Version Independent ID: 5b7ddecc-b700-9726-30af-bda0989146e2
* Content: [KMS client setup keys](https://docs.microsoft.com/en-us/windows-server/get-started/kmsclientkeys)
* Content Source: [WindowsServerDocs/get-started/KMSclientkeys.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/KMSclientkeys.md)
* Product: **windows-server-threshold**
* GitHub Login: @jaimeo

**Comment by exchange12rocks** [comment]
@DSPatrick https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn303421(v=ws.11)

**Comment by DSPatrick** [comment]
Thank you very much. Wonder why they would hide them in a 2012 / 2012 R2 (url) document? I also wonder about indexing on docs.microsoft.com on google and bing as a lot of things that used to show on support.microsoft.com do not show on news docs site.

**Comment by jaimeo** [comment]
They are in the process of being added right now.
vv
J.O.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jaimeo** [comment]
Assign to Corey (or Liza, in this case, who just updated this topic); I don’t do Server anymore.

vv
J.O.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by lizap** [comment]
The 2019, 2016, SAC, and 2012R2 AVMA keys have just been published to the library: https://docs.microsoft.com/en-us/windows-server/get-started-19/vm-activation-19

Please let us know if there's other info you need. Thanks!

**Comment by DSPatrick** [comment]
Fast response again! Thank you
