### ISSUE TITLE
Activate key at install or upgrade

### ISSUE THREAD

**Issue by hdornemann** [MicrosoftDocs/windowsserverdocs#1580]
The Windows Server 2019 key does not appear to work during install or upgrade.  During install I am able to skip the key and then activate it later using slmgr /ipk.  When running setup directly to upgrade a virtual machine it does not allow the key to be skipped and entering the AVMA key returns the error "This key doesn't work with this edition of Windows.  Try a different key."  Is there an alternate way to upgrade virtual machines that are using AVMA?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 960f9460-e1de-949c-ae1a-ad24a34cc1c2
* Version Independent ID: c9b5b530-5a39-0136-fb9a-15389ccd6691
* Content: [Automatic virtual machine activation](https://docs.microsoft.com/en-us/windows-server/get-started-19/vm-activation-19)
* Content Source: [WindowsServerDocs/get-started-19/vm-activation-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/vm-activation-19.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by dcleaver** [comment]
I got around this by using a KMS client key from [here](https://docs.microsoft.com/en-us/windows-server/get-started/kmsclientkeys) during the upgrade.

Once the upgrade is complete, switch to an AVMA key from [here](https://docs.microsoft.com/en-us/windows-server/get-started-19/vm-activation-19).

**Comment by IngridAtMicrosoft** [comment]
#please-close
