### ISSUE TITLE
Load Balancer Configuration - Inaccurate Ordering. 

### ISSUE THREAD

**Issue by jameswestall** [MicrosoftDocs/windowsserverdocs#1588]
Azure portal now requires the backend pool prior to the load balancing rules.
Step 3+ 4 to be swapped under section 3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b83e43bd-69b6-783d-b377-af76e15e82e6
* Version Independent ID: e65dbfd5-6a8e-09b4-e104-871f7a58a71e
* Content: [Add high availability to the RD Web and Gateway web front](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-rdweb-gateway-ha#step-2-configure-rd-web-and-rd-gateway-properties-on-the-new-server)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-rdweb-gateway-ha.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-rdweb-gateway-ha.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
#please-close
