### ISSUE TITLE
The Storage Migration service in the Windows Admin Center does not stop.

### ISSUE THREAD

**Issue by gabrielluizbh** [MicrosoftDocs/windowsserverdocs#1601]
The migration migration service simply does not appear. I am using Windows Server 2019 and Windows Admin Center version 1809.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c3b0886-820a-0b3c-8382-8d65fc8c3b27
* Version Independent ID: 3e310218-abc0-5249-bb16-7c21402e32c0
* Content: [Storage Migration Service overview](https://docs.microsoft.com/en-us/windows-server/storage/storage-migration-service/overview#requirements)
* Content Source: [WindowsServerDocs/storage/storage-migration-service/overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-migration-service/overview.md)
* Product: **windows-server-threshold**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
