### ISSUE TITLE
Future version of this article...

### ISSUE THREAD

**Issue by RobbieCrash** [MicrosoftDocs/windowsserverdocs#1602]
It's been just shy of a year since this was published. When can we expect the updated article?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a0b9357-80eb-21f2-2a6e-0bb568f380f6
* Version Independent ID: b6c1cce2-1055-74f1-9625-c364ac02d889
* Content: [Hyper-V Network I/O Performance](https://docs.microsoft.com/en-us/windows-server/administration/performance-tuning/role/hyper-v-server/network-io-performance)
* Content Source: [WindowsServerDocs/administration/performance-tuning/role/hyper-v-server/network-io-performance.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/performance-tuning/role/hyper-v-server/network-io-performance.md)
* Product: **windows-server-threshold**
* GitHub Login: @phstee
* Microsoft Alias: **Asmahi; SandySp; JoPoulso**

**Comment by IngridAtMicrosoft** [comment]
#please-close
