### ISSUE TITLE
Windows Admin Center fails to load after installation of RSAT tools

### ISSUE THREAD

**Issue by neyaki** [MicrosoftDocs/windowsserverdocs#1604]
Installed Admin Center on a Windows 2016 server, all fine.  Then RSAT were installed via the Roles/Features and now Admin Center fails to load its webpage.

The service still runs, and there have been no firewall changes at play either...

Nothing in the EventLog either.

**Comment by JasonGerend** [comment]
Hi Corey,
Can you assign all future Windows Admin Center doc issues to Jeff Woolslayer?

Thanks!
Jason

**Comment by coreyp-at-msft** [comment]
Sure. Will do.

________________________________

**Comment by neyaki** [comment]
Hi all, Any thoughts?

-thx

**Comment by jwwool** [comment]
You mentioned that you checked to make sure the service was running, could you please review the other [troubleshooting ](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/troubleshooting#whitescreenws) steps? Even though you did not make any changes to the firewall, it would be valuable to make sure that nothing happened to the rule.
There are two locations in the event logs to look:
```Windows Logs \ Application``` and ```Application and Service Logs \ Microsoft-ServerManagementExperience```

When you are trying to access the gateway open the browsers development tools (F12), look in the console tab as well as the network traffic tab. Reply here with any errors.

Finally, check the output of the following commands (replace 443 with the port your specificed, if applicable):

```cmd
netsh http show urlacl url=https://+:443/
netsh http show sslcert ipport=0.0.0.0:443
netstat -a
```
