### ISSUE TITLE
Is SMB 3.0 Internet safe?

### ISSUE THREAD

**Issue by namnam0610** [MicrosoftDocs/windowsserverdocs#1605]
So after reading this document, my question is: "should we expose our file server to the internet with SMB 3.0"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a9439ec-4594-c9b5-a52c-907ae2ce582d
* Version Independent ID: d97a748a-6493-f1a0-a101-0bea0bd9faab
* Content: [Overview of file sharing using the SMB 3 protocol in Windows Server](https://docs.microsoft.com/en-us/windows-server/storage/file-server/file-server-smb-overview)
* Content Source: [WindowsServerDocs/storage/file-server/file-server-smb-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/file-server-smb-overview.md)
* Product: **windows-server-threshold**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by jordanmills** [comment]
Probably pointless.  Most ISPs block it to try to force you to pay them to use their file sharing services.
