### ISSUE TITLE
Entry missing from the TOC

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/windowsserverdocs#1610]
Not sure if this is by design or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1efdff7-79ba-6f27-78ba-20d6bf4de4a5
* Version Independent ID: 77fc9af3-35e3-2a31-3385-dcd2ce47d37d
* Content: [Sc delete](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/sc-delete)
* Content Source: [WindowsServerDocs/administration/windows-commands/sc-delete.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/sc-delete.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
As mentioned in the issue ticket #2272 , there are a quite a few `sc` command options (parameters/arguments) that do not even have a page.
The existing pages, though,
- sc-config.md
- sc-create.md
- sc-delete.md
- sc-query.md

should be fairly easy to add to the TOC page (https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/TOC.md), as well as in the Windows Commands list (https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands#s) page.

**Comment by illfated** [comment]
The pages `sc-config.md`, `sc-create.md`, `sc-delete.md`, and `sc-query.md` were added in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/5671c3dd594f6cb2dbfc9cd6fa344012edee3b60 (file `TOC.md` https://github.com/MicrosoftDocs/windowsserverdocs/commit/5671c3dd594f6cb2dbfc9cd6fa344012edee3b60#diff-0bd2367ebb44fa70d732dcb912f0e37f02293a43549ebd16f65b1333dd5f649d).

**Comment by illfated** [comment]
#please-close
