### ISSUE TITLE
Horrible documentation

### ISSUE THREAD

**Issue by vitaprimo** [MicrosoftDocs/windowsserverdocs#1615]
Not only does your on-prem software comes without documentation, and the links you remember to put within the apps aren't even for a direct resource, you still go on to hawking on and on Azure and go on without documenting how stuff is done with the undocumented bloat we pay thousands for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 428e9e07-ca35-27d2-e63a-92930cec0118
* Version Independent ID: 9a452a85-9afa-42d5-f319-bf1c4c50d01d
* Content: [Remote Desktop Services architecture](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/desktop-hosting-logical-architecture)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/Desktop-hosting-logical-architecture.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/Desktop-hosting-logical-architecture.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by coreyp-at-msft** [comment]
Hi @vitaprimo,
We do actually have quite a lot of on-premises documentation. We're sorry you didn't find what you were looking for specifically. We can address your concerns better when you reference the particular documentation that’s not meeting your needs.

Thanks,
Corey
