### ISSUE TITLE
Can't add DOMAIN\Administrators

### ISSUE THREAD

**Issue by MichaelFirsov** [MicrosoftDocs/windowsserverdocs#1618]
Hello!
Adding DOMAIN\Administrators to Deny Logon Locally, Deny Logon as a service... gpo settings either leads to the error "The following account could not be validated: DOMAIN\Administrators" (where DOMAIN is the name of the domain) - if TYPED as domain\Administrator in the Add User or Group window - or to adding the Administrators group (local, not a domain group!) - if you click on Browse in the Add User or Group window , type the Administrators in the "Select Users, Computers..." window, click Check Names and then OK. 
In other words, inspite of searching for the Administrators group in the DOMAIN (the filed "From this location" contains the name of the domain), the group name to add becomes Administrators - not DOMAIN\Administrators.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd5878a8-a83e-e75d-ddae-59edc04e7138
* Version Independent ID: 0f0cbbe4-20da-3abe-1a7c-effc608d8cca
* Content: [Privileged Access Workstations](https://docs.microsoft.com/en-us/windows-server/identity/securing-privileged-access/privileged-access-workstations)
* Content Source: [WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by 4fd81048a9cd8a3fd43f1f4e52f84181** [comment]
Based on the Tier-0 Equivalency list linked below, I think the correct value should be BUILTIN\Administrators which does work.  (I think an editor thought BUILTIN was an example domain name and replaced it with DOMAIN)

https://docs.microsoft.com/en-us/windows-server/identity/securing-privileged-access/securing-privileged-access-reference-material?redirectedfrom=MSDN#tier-0-equivalency
