### ISSUE TITLE
Using NIC Teaming within VMs

### ISSUE THREAD

**Issue by conorpcleary** [MicrosoftDocs/windowsserverdocs#1620]
At the end of the Compatibility section there is the following statement: 

"To learn about using NIC Teaming within virtual machines (VMs) that run on a Hyper-V host, see"

I'm assuming there is supposed to be some link to another article after see but all I see is blank space.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa790b8c-1e37-0608-b93e-ef0a0eb5d930
* Version Independent ID: c8d1a328-5da5-2534-e684-ef7a4bc275e0
* Content: [NIC Teaming](https://docs.microsoft.com/en-us/windows-server/networking/technologies/nic-teaming/nic-teaming)
* Content Source: [WindowsServerDocs/networking/technologies/nic-teaming/NIC-Teaming.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/nic-teaming/NIC-Teaming.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@conorpcleary, good catch.  I'll add that in especially since the NIC teaming content has been refreshed recently.

**Comment by shortpatti** [comment]
Closing.  The incomplete sentence should read:

> To learn about using NIC Teaming within virtual machines (VMs) that run on a Hyper-V host, see [Create a new NIC Team on a host computer or VM](Create-a-New-NIC-Team-on-a-Host-Computer-or-VM.md).
