### ISSUE TITLE
Completed Step 4 - THEN what?

### ISSUE THREAD

**Issue by dnienhis** [MicrosoftDocs/windowsserverdocs#1626]
I assume I go to:  hhttps://webserv1.contoso.com/claimapp/federationmetadata/2007-06/federationmetadata.xml  ??  What should I see if it's working?  What should I see if its not?   Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 321ba1ae-3024-a568-670d-5a6419035c03
* Version Independent ID: c648a448-7492-543b-cc54-0999cadf5455
* Content: [Set up the lab environment for AD FS in Windows Server 2012 R2](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/set-up-the-lab-environment-for-ad-fs-in-windows-server-2012-r2#BKMK_10)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Set-up-the-lab-environment-for-AD-FS-in-Windows-Server-2012-R2.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Set-up-the-lab-environment-for-AD-FS-in-Windows-Server-2012-R2.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
