### ISSUE TITLE
Port number should I specify for the <port> field

### ISSUE THREAD

**Issue by itguy007z** [MicrosoftDocs/windowsserverdocs#1632]
What port number should I specify for the &lt;port&gt; field in this command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe84fb4b-3420-bc1e-6a1d-b64ecc56fc5e
* Version Independent ID: f089767e-4613-d595-a0ee-0dab012724a1
* Content: [Install Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/install)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/deploy/install.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/deploy/install.md)
* Product: **windows-server-threshold**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by loozhengyuan** [comment]
I think it depends on which ports you have used and if you are comfortable using non-default ports. For myself, since I solely dedicate a VM to serve as a gateway, I used port 443 so I can easily access it via https://<hostname>

**Comment by jwwool** [comment]
Confirming - this value is arbitrary, it's up to you. You can use any port you wish, except port 80.
Port 443 is the default when you use the GUI installer, and makes it so that you don't have specify the port in the browser's address bar like @loozhengyuan mentioned above.
