### ISSUE TITLE
WAC Update Tab Error for Hyper-V 2012 (Not R2)

### ISSUE THREAD

**Issue by ArigornStrider** [MicrosoftDocs/windowsserverdocs#1635]
As best as I can tell from the documentation for Windows Admin Center (WAC), Microsoft Hyper-V Server 2012 is supported, but when I connect to a Hyper-V 2012 server and navigate to the Updates tab, the following error is generated in the UI:

> Notification Details
> Error
> (1) RemoteException: The specified module 'ScheduledTasks' was not loaded because no valid module file was found in any module directory. (2) RemoteException: The term 'Get-ScheduledTask' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

I have confirmed that this module is not present on any of my Hyper-V 2012 servers, but per the documentation for Windows Server 2012, the module was introduced and is standard on this generation of server operating systems. The [WAC prep instructions](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/prepare-environment) do not list any additional steps beyond install WMF 5.1 (which has been manually applied to these systems) for Server 2012 systems, and there are no specific instructions for Hyper-V 2012 (while there are for Hyper-V 2012 R2 and Hyper-V 2016). Searching for ways to manually install this module has not been fruitful.

Having update management in a central console like this would be a huge help to administer systems over the long term. I am happy to provide further information if required, let me know what is needed.

**Comment by ArigornStrider** [comment]
Any word on if this is expected or not? Anything that can be done about getting this bug resolved?

**Comment by jwwool** [comment]
Thanks for catching this! I've created a bug to investigate.
