### ISSUE TITLE
Will not launch

### ISSUE THREAD

**Issue by dalessit** [MicrosoftDocs/windowsserverdocs#1642]
Initially had folder protection turned on and install failed, turned it off and installation succeeds but service will not start Running Windows 10 enterprise v 1803.  Errors in logs as follows 

Application: SmeDesktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception
   at System.Diagnostics.Process.StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
   at System.Diagnostics.Process.Start(System.Diagnostics.ProcessStartInfo)
   at Microsoft.ManagementExperience.Desktop.Program.Launch()
   at Microsoft.ManagementExperience.Desktop.Program.Main()

Faulting application name: SmeDesktop.exe, version: 1.1.1809.17002, time stamp: 0xcd825564
Faulting module name: KERNELBASE.dll, version: 10.0.17134.319, time stamp: 0x1e206b26
Exception code: 0xe0434352
Fault offset: 0x000000000003a388
Faulting process id: 0x1840
Faulting application start time: 0x01d4623b76432a4e
Faulting application path: C:\Program Files\Windows Admin Center\SmeDesktop.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: e0f61e18-a5b1-405a-83d0-cfba0df256ba
Faulting package full name: 
Faulting package-relative application ID: 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05df3d17-6978-2214-dad9-3eace6d7ee92
* Version Independent ID: ef8e8662-7c07-3118-59b3-0ac30af285f0
* Content: [Windows Admin Center Common Troubleshooting Steps](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/troubleshooting#filebug)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/use/troubleshooting.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/use/troubleshooting.md)
* Product: **windows-server-threshold**
* GitHub Login: @jwwool
* Microsoft Alias: **jeffrew**

**Comment by jwwool** [comment]
This looks like it's from the **Windows Logs \ Application** channel. Is there an entry in **Applications and Service Logs \ Microsoft-ServerManagementExperiance** channel as well?

**Comment by dalessit** [comment]
Only informational messages

"SME frontend service is starting" and "Validation complete.  All
assemblies have valid signatures."

The icon does pop up in the Notification area when I attempt to launch, but
then disappears.

**Comment by dalessit** [comment]
Controlled folder access blocked the following during the initial install (providing as much info as possible)

C:\Windows\System32\rundll32.exe has been blocked from modifying %userprofile%\Documents\20181012 by Controlled Folder Access.

C:\Windows\System32\msiexec.exe has been blocked from modifying %userprofile%\Desktop by Controlled Folder Access.

I uninstalled and turned off Controlled folder access, rebooted and re-installed and still no go.

**Comment by jwwool** [comment]
> I uninstalled and turned off Controlled folder access, rebooted and re-installed and still no go.

It was not my understanding that Controlled folder access was something that could be uninstalled, can you tell me more?

What exact steps did you take to turn off Controlled folder access, [was it this](https://support.microsoft.com/en-us/help/4046851/windows-10-allow-blocked-app-windows-security) or another way?

**Comment by dalessit** [comment]
Sorry, I uninstalled Admin center and re-installed,  I just turned off
Folder Access using the method you linked.

**Comment by RichardFD** [comment]
I'm having this same issue. Windows is not managing this, SEP is.

**Comment by deweycheetumandhowe** [comment]
In what way was this "answered"?  I am trying to resolve this issue, but so not see any useful suggestions for resolving this
