### ISSUE TITLE
RDP and RDP Settings not working via Admn Center

### ISSUE THREAD

**Issue by grawerpl** [MicrosoftDocs/windowsserverdocs#1644]
When i try after installing windows server 2016/2019 and change RDP settings i got this:

ERROR (1) RemoteException: You must specify an object for the Get-Member cmdlet. (2) RemoteException: You must specify an object for the Get-Member cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc4cb072-7157-55b4-dbe1-c5723d2873b3
* Version Independent ID: 70a3605d-6d21-5719-b661-6023bad96627
* Content: [Windows Admin Center Overview](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/overview)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/overview.md)
* Product: **windows-server-threshold**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by xahmedali** [comment]
Hello I'm facing an issue to make the RDP work, I tried everthing but still not Working.
Power shell, Events are working..
I need Help

**Comment by Heidilohr** [comment]
Hi @xahmedali. I recommend [submitting a bug report on UserVoice](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/troubleshooting#still-not-working-or-is-your-issue-not-captured-here-troubleshooting-common-questions). The team there will be able to help you with your issue.
