### ISSUE TITLE
00962791526041

### ISSUE THREAD

**Issue by mohmad000** [MicrosoftDocs/windowsserverdocs#1645]
jast

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54585ff0-1a67-0fd0-3169-e0cc98d45b4b
* Version Independent ID: 702fd06d-fd2f-48c6-ac57-5f8a6afe84da
* Content: [Welcome to Remote Desktop Services in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/welcome-to-rds)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/Welcome-to-rds.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/Welcome-to-rds.md)
* Product: **windows-server-threshold**
* GitHub Login: @ChristianMontoya
* Microsoft Alias: **chrimo**

**Comment by coreyp-at-msft** [comment]
Not enough info to take action.
