### ISSUE TITLE
Wrong Querying the Hyper-V hypervisor scheduler type launch event using PowerShell

### ISSUE THREAD

**Issue by AlexeyRipenko** [MicrosoftDocs/windowsserverdocs#1646]
```powershell
 Get-WinEvent -FilterHashTable @{ProviderName="Microsoft-Windows-Hyper-V-Hypervisor"; ID=2} | Sor
t-object -property TimeCreated | select -Last 1
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b739fc5c-de44-7299-28a5-21e95bccf400
* Version Independent ID: 3a607530-01e6-e73a-0168-4e03a262a59c
* Content: [Understanding and using Hyper-V hypervisor scheduler types](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types#enabling-smt-in-guest-virtual-machines)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types.md)
* Product: **windows-server-hyper-v**
* GitHub Login: @allenma
* Microsoft Alias: **allenma**

**Comment by larsiwer** [comment]
@AlexeyRipenko I've submitted a [PR ](https://github.com/MicrosoftDocs/windowsserverdocs/pull/1782/files) to update the PowerShell command used -- please let me know if there are additional questions/concerns.
