### ISSUE TITLE
JScript, VBScript & WSH documentation?

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/windowsserverdocs#1648]
Where have the documentation for JScript, VBScript for Windows Scripting Host (WSH) gone?
JScript is NOT JavaScript and you can't just link to the Mosilla JavaScript documentation!
I still have these scripts running in Production with a lot of customers!!  Bring back all the Windows Scripting Documentation!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bec91ccf-1a12-c610-d54e-ba613ae08dc5
* Version Independent ID: d344ee16-f684-93f1-9b02-bad55075d733
* Content: [cscript](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cscript)
* Content Source: [WindowsServerDocs/administration/windows-commands/cscript.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/cscript.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by coreyp-at-msft** [comment]
Hi @Bartolomeus-649, I don't think we've ever had documentation for JScript, VBScript for Windows Scripting Host (WSH) on the Windows commands cscript page. I also don't see the link to Mozilla JavaScript on this page to which you refer.  Here is our Windows Script Hosts documentation: https://docs.microsoft.com/en-us/scripting/winscript/windows-script-interfaces.

**Comment by woytu** [comment]
> 用于Windows脚本宿主（WSH）的JScript和VBScript的文档哪里去了？
> JScript不是JavaScript，您不能仅链接到Mosilla JavaScript文档！
> 我仍然有许多客户在生产环境中运行这些脚本！！带回所有Windows脚本文档！
> 
> #### 文件详细资料
> ⚠ _请勿编辑此部分。docs.microsoft.com➟GitHub问题链接是必需的。_
> 
> * ID（标识号）：bec91ccf-1a12-c610-d54e-ba613ae08dc5
> * 版本独立ID：d344ee16-f684-93f1-9b02-bad55075d733
> * 内容：[cscript](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cscript)
> * 内容来源：[WindowsServerDocs / administration / windows-commands / cscript.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/cscript.md)
> * 产品：**Windows服务器阈值**
> * GitHub登录：@ coreyp-at-msft
> * Microsoft别名：**coreyp**

https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cscript
