### ISSUE TITLE
Any chance you can elaborate on what this means?

### ISSUE THREAD

**Issue by jeffjblack** [MicrosoftDocs/windowsserverdocs#1650]
4.
b) Grant Resource Forest certificate templates Read/Write permissions to the \. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e44046a-24a4-3b86-7978-1bd7f01a2261
* Version Independent ID: 63c62e77-d18f-5971-1c53-58484af3c6df
* Content: [Configure a Multi-Forest Deployment](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/ras/multi-forest/configure-a-multi-forest-deployment)
* Content Source: [WindowsServerDocs/remote/remote-access/ras/multi-forest/Configure-a-Multi-Forest-Deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/ras/multi-forest/Configure-a-Multi-Forest-Deployment.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@jeffjblack, I've added the markdown escape characters :)  So it now reads:

> Grant Resource Forest certificate templates Read/Write permissions to the <Account Forest>\<Administrator account>.
