### ISSUE TITLE
Missing Characters

### ISSUE THREAD

**Issue by natelee123** [MicrosoftDocs/windowsserverdocs#1678]
Windows 10 Enterprise N LTSC 2019 is missing the first character, 9. Windows 10 Enterprise N LTSB 2016 is missing the first character, Q. Please don't fix this article. I believe users enjoy discovering this comment at the bottom of the document more than they enjoy finding accurate product information. I know I do!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc9df0c0-db17-3226-b734-59ebd27fa212
* Version Independent ID: 5b7ddecc-b700-9726-30af-bda0989146e2
* Content: [KMS client setup keys](https://docs.microsoft.com/en-us/windows-server/get-started/kmsclientkeys)
* Content Source: [WindowsServerDocs/get-started/KMSclientkeys.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/KMSclientkeys.md)
* Product: **windows-server-threshold**
* GitHub Login: @jaimeo

**Comment by coreyp-at-msft** [comment]
Fixed in private
