### ISSUE TITLE
I made a huge mistake and need help.

### ISSUE THREAD

**Issue by GynnTEK** [MicrosoftDocs/windowsserverdocs#1688]
I was unaware of the system requirements and installed Hyper V on my laptop. Now I am stuck at the command prompt. I cannot not uninstall it or go back to the way the laptop was sold to me two weeks ago.

Thank you,

Gia M Johnson

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ffd6db1-5e21-d24c-d824-99b9a610d9f4
* Version Independent ID: 83a510fc-03b0-492e-85e1-28310939da92
* Content: [Manage Hyper-V on Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/manage-hyper-v-on-windows-server)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/Manage-Hyper-V-on-Windows-Server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/Manage-Hyper-V-on-Windows-Server.md)
* Service: **na**
* Product: **windows-server-threshold**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by larsiwer** [comment]
Sorry to hear that you are experiencing an issue here.

Usually, the manufacturer of the laptop provides a recovery disc or some way to create a recovery flash drive. E.g. 
HP: https://support.hp.com/us-en/document/bph07143
DELL: https://www.dell.com/support/article/us/en/04/sln297924/create-windows-10-recovery-media-for-your-dell-computer?lang=en
Lenovo: https://support.lenovo.com/us/en/solutions/ht035659

Typically you can find guidance for other OEMs by searching for "recovery media" and your laptop manufacturer.

**Comment by GynnTEK** [comment]
Thank you, 

It came right down to doing just that! I will never forget to check system requirements before an install of any kind.

**Comment by GynnTEK** [comment]
The laptop is running well after I used a Windows 10 recovery disc. I learned a valuable lesson about going down a checklist and confirming system requirements prior to an install. Thank you to everyone that offered guidance.
