### ISSUE TITLE
Powershell command does not work

### ISSUE THREAD

**Issue by bjcline** [MicrosoftDocs/windowsserverdocs#1691]
We are running the 2016 version of ADFS
The following command Reset-ADFSAccountLockout user@forsythtech.edu -Familiar does not work. I get the following error
Reset-AdfsAccountLockout : A parameter cannot be found that matches parameter name 'Familiar'.

I get results if I run it as Reset-ADFSAccountLockout user@forsythtech.edu Familiar (no dash before the Familar property)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8634165-2ff5-9b01-e3fc-17827360a5f3
* Version Independent ID: a5a91921-3193-93ad-df22-d486e65b19f8
* Content: [Configure AD FS Extranet Lockout Protection](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-extranet-smart-lockout-protection)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
Verifying with PM

**Comment by Mike-Crowley** [comment]
"These cmdlets automatically connect to the node in the farm which holds the master role" According to a support case I have open, this is not correct. You must enable and use PSRemoting.

**Comment by jordanmills** [comment]
If you use ps remoting but not credssp (which is generally a bad idea to use), then many of the cmdlets (like get-adfsaccountactivity) don't work.  I think it's making direct calls to the ADFS database as the caller's identity, but the remoting session doesn't have credentials that can be reused.  I'm working on cooking up something with delegation to address that, but this should really be fixed in the module.

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
