### ISSUE TITLE
Powershell command incorrect of 2016 version

### ISSUE THREAD

**Issue by bjcline** [MicrosoftDocs/windowsserverdocs#1692]
For ADFS 2016 version
Set-ADFSAccountActivity user@upnsuffix.com -FamiliarLocation “1.2.3.4” does not work
The command that works for me is Set-ADFSAccountActivity user@upnsuffix.com -AdditionalFamiliarIps “1.2.3.4”
Is there a way to remove Familiar IP addresses from the account?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8634165-2ff5-9b01-e3fc-17827360a5f3
* Version Independent ID: a5a91921-3193-93ad-df22-d486e65b19f8
* Content: [Configure AD FS Extranet Lockout Protection](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-extranet-smart-lockout-protection)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by leohoknows** [comment]
Did you ever get an answer for this? I'm also trying to remove a familiar ip and unable to find any commands for it.

**Comment by Guy94** [comment]
You can use  Set-AdfsAccountActivity -UserPrincipalName [UserName] -Clear
But that clear all Familiar IPs

**Comment by IngridAtMicrosoft** [comment]
#please-close
