### ISSUE TITLE
Duplicate Steps

### ISSUE THREAD

**Issue by joshwright10** [MicrosoftDocs/windowsserverdocs#1708]
The following steps look to be duplicated. Steps 1-4, repeat as 5-8:

To create the management accounts, perform the following steps:
1. Log on to a domain controller with an account that is a member of the domain's DA group.
2. Launch Active Directory Users and Computers and navigate to the OU where you will be creating the management account.
3. Right-click the OU and click New and click User.
4. In the New Object - User dialog box, enter your desired naming information for the account and click Next.
5. Log on to a domain controller with an account that is a member of the domain's DA group.
6. Launch Active Directory Users and Computers and navigate to the OU where you will be creating the management account.
7. Right-click the OU and click New and click User.
8. In the New Object - User dialog box, enter your desired naming information for the account and click Next.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c527ef44-6070-fc70-1d4c-fbb19e37321f
* Version Independent ID: b09359d5-8f53-631b-6631-5c4a3d0977c3
* Content: [Appendix I - Creating Management Accounts for Protected Accounts and Groups in Active Directory](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/component-updates/appendix-i--creating-management-accounts-for-protected-accounts-and-groups-in-active-directory)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/component-updates/Appendix-I--Creating-Management-Accounts-for-Protected-Accounts-and-Groups-in-Active-Directory.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/manage/component-updates/Appendix-I--Creating-Management-Accounts-for-Protected-Accounts-and-Groups-in-Active-Directory.md)
* Product: **windows-server-threshold**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
Resolved in private repo PR 12186
