### ISSUE TITLE
Prerequisite Users Windows 10 and WS 2008r2 or later

### ISSUE THREAD

**Issue by MartinLalanne** [MicrosoftDocs/windowsserverdocs#1713]
Make sure that any computers your users will connect to are running one of the following OS versions Windows 10 and Windows Server 2008R2.

What does it mean?

From the blog The RD web client is supported on Edge, IE11+, Chrome, Firefox, and Safari browsers for desktop platforms like Windows, macOS, Chromebook, and Linux.

Thanks.

**Comment by IngridAtMicrosoft** [comment]
#please-close
