### ISSUE TITLE
What constitutes a "specialized Windows Server 2008 R2 VM"?

### ISSUE THREAD

**Issue by benjamin-maynard** [MicrosoftDocs/windowsserverdocs#1716]
There are several references made to a "Specialized image" or "specialized Windows Server 2008 R2 VMs". Reading this document, it leads me to believe that if I wish to take advantage of the free Windows 2008 extended support on Azure, I need to use a specialised Azure Windows 2008 R2 VM and re-install my application onto it.

Further reading into https://docs.microsoft.com/en-us/windows-server/get-started/uploading-specialized-ws08-image-to-azure, it actually seems like existing Windows Server 2008 servers can be uploaded to Azure providing they meet a couple of requirements (namely SP2, and non-expiring administrator passwords).

Please can the documentation be updated to be clearer?

Can I upload my existing Windows Server 2008 images to Azure, or do I need to use Azure provided "specialized Windows Server 2008 R2 VMs"? I suspect it is the former but this could do with being a little clearer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88d8e06f-1416-57d1-84b9-fd82d217a481
* Version Independent ID: 9047ff8c-95f0-ffea-38d6-9a6d6c56e383
* Content: [Windows Server Installation and Upgrade](https://docs.microsoft.com/en-us/windows-server/get-started/installation-and-upgrade)
* Content Source: [WindowsServerDocs/get-started/Installation-and-Upgrade.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/Installation-and-Upgrade.md)
* Product: **windows-server**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by benjamin-maynard** [comment]
@coreyp-at-msft - Is there a timeline for when this question might be addressed?

**Comment by RAJU2529** [comment]
you can create  system images  of  any windows version , You may  share to online  storage  or  to local  hard disk   or to   USB pen drive

**Comment by IngridAtMicrosoft** [comment]
#please-close
