### ISSUE TITLE
Clear Statement on availability 

### ISSUE THREAD

**Issue by Aebian** [MicrosoftDocs/windowsserverdocs#1733]
It would be great to see a clear statement which Versions are available on which Version of Windows and if Server or Client 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bffd204-80d9-38fe-898b-5b290e6466ee
* Version Independent ID: e0fe16d9-6424-fab1-0759-4a36a74a3c94
* Content: [Network File System overview](https://docs.microsoft.com/en-us/windows-server/storage/nfs/nfs-overview)
* Content Source: [WindowsServerDocs/storage/nfs/nfs-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/nfs/nfs-overview.md)
* Product: **windows-server-threshold**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by AspenForester** [comment]
Like this?
https://docs.microsoft.com/en-us/windows-server/storage/nfs/nfs-overview#windows-and-windows-server-versions

**Comment by Aebian** [comment]
Yes, thank you.
