### ISSUE TITLE
Unclear Description for Spoke Sites

### ISSUE THREAD

**Issue by ld0614** [MicrosoftDocs/windowsserverdocs#1735]
While the description is clear for hub sites such as Site_B it is unclear if Site Bridging is taken into account such that if Site_A didn't have a domain controller and site_B was offline would Site_C be chosen over Site_D due to the lower site link cost?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ebb9c61-58fc-403b-647f-f3c6d714411b
* Version Independent ID: 4146f677-abc3-eded-3f2b-0bec5b810d7c
* Content: [Enabling Clients to Locate the Next Closest Domain Controller](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/enabling-clients-to-locate-the-next-closest-domain-controller)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/Enabling-Clients-to-Locate-the-Next-Closest-Domain-Controller.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/Enabling-Clients-to-Locate-the-Next-Closest-Domain-Controller.md)
* Product: **windows-server-threshold**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
@ld0614 there should probably be an addition to the note 

The Try Next Closest Site setting works in coordination with automatic site coverage. For example, if the next closest site has no domain controller, DC Locator tries to find the domain controller that performs automatic site coverage for that site. 

That says something about it being done in conjunction with site bridging. What do you think?

**Comment by ld0614** [comment]
I like the statement, ideally I think having a second diagram and example would make it more illustrative and easier to understand overall, unfortunately this would require a tweak to the existing diagram, are you able to produce a second version of the diagram with site A having a client computer and site B having noting or a client computer?

**Comment by MicrosoftGuyJFlo** [comment]
Updating the diagram would require recreating it. That would have to be a longer term update at this point.

**Comment by MicrosoftGuyJFlo** [comment]
Being worked in Public PR
https://github.com/MicrosoftDocs/windowsserverdocs/pull/1786

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
