### ISSUE TITLE
Explicit use of OS Versions

### ISSUE THREAD

**Issue by ld0614** [MicrosoftDocs/windowsserverdocs#1736]
It clearly states 'only Windows Server 2008 and Windows Server 2008 R2 domain controllers support the next closest site functionality' I would assume that its Windows Server 2008+ rather than the functionality was removed in Windows Server 2012.  Overall the OS version support statements could use an update

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ebb9c61-58fc-403b-647f-f3c6d714411b
* Version Independent ID: 4146f677-abc3-eded-3f2b-0bec5b810d7c
* Content: [Enabling Clients to Locate the Next Closest Domain Controller](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/enabling-clients-to-locate-the-next-closest-domain-controller)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/Enabling-Clients-to-Locate-the-Next-Closest-Domain-Controller.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/Enabling-Clients-to-Locate-the-Next-Closest-Domain-Controller.md)
* Product: **windows-server-threshold**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
@ld0614 that is correct. Windows Server 2008 or newer is what it should say. If you would like to make the edit using the edit button in the article I am happy to approve that change. Otherwise I will add it to my backlog and try to get to it as soon as I can.

**Comment by MicrosoftGuyJFlo** [comment]
#in-progress

**Comment by MicrosoftGuyJFlo** [comment]
Being worked in Public PR
https://github.com/MicrosoftDocs/windowsserverdocs/pull/1786

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
