### ISSUE TITLE
Error running the tool on migrated ADFS 2016 from ADFS 2012 R2

### ISSUE THREAD

**Issue by johnz333** [MicrosoftDocs/windowsserverdocs#1740]
The tool fails to run on an ADFS farm that was migrated from 2012 R2 that is still at FBL of 2012 R2:
(We cannot update our schema at this time but we need the tool to run under the lower level.

Get-AdfsLocalClaimsProviderTrust : PS0159: The operation is not supported at the current Farm Behavior Level '1'.
Raise the farm to at least version '2' before retrying.
At line:1 char:1
+ Backup-ADFS -StorageType "FileSystem" -StoragePath "C:\ADFS\Backup" - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AdfsLocalClaimsProviderTrust], DisplayableArgumentException
    + FullyQualifiedErrorId : Microsoft.IdentityServer.Diagnostics.Exceptions.DisplayableArgumentException,Microsoft.I
   dentityServer.Management.Commands.GetLocalClaimsProviderTrustCommand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a58b49ca-ae39-132e-adbd-6766a8019a89
* Version Independent ID: fdf31266-bc9e-8880-0073-00cf1cad2897
* Content: [AD FS Rapid Restore Tool](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/ad-fs-rapid-restore-tool)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/AD-FS-Rapid-Restore-Tool.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/AD-FS-Rapid-Restore-Tool.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by jodyhendrix** [comment]
Thanks for reporting this problem.  I've created a bug to track this issue and we'll look to address it in a future update.
