### ISSUE TITLE
Missing Character.

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/windowsserverdocs#1741]
This feedback is original created by @fearless-hasan from https://github.com/MicrosoftDocs/feedback/issues/763
Link to article:
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/nbtstat
Problem:
In this page, first example on the Examples section, the command should be "nbtstat /a CORP07"
rather than "btstat /a CORP07".
Simply it should add a single "n" in the beginning of the command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46f4640c-fc85-c199-f325-19f8ffb4c952
* Version Independent ID: e2bbe7f5-2e18-5f53-3d65-d9ee7b3e6b4e
* Content: [nbtstat](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/nbtstat)
* Content Source: [WindowsServerDocs/administration/windows-commands/nbtstat.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/nbtstat.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by doctordns** [comment]
Looking at the online documentation website and this git hub repo, no example begins with just Btstat The first example (which retrieves the NBT table from Corp07) is correct in both places.

Can you provide any more context? Otherwise, can this issue get closed?
