### ISSUE TITLE
RDWeb webclient (Basic) authentication

### ISSUE THREAD

**Issue by finalbeta** [MicrosoftDocs/windowsserverdocs#1755]
**Use case:** I'm evaluating options for implementing RDWeb webclient behind a loadbalancer that handles authentication and achieve the **passing of credentials to the RDWeb webclient**. On "Default Website\RDWeb\Pages" I can do this **using "Basic Authentication"** simply by changing the IIS Authentication.

Issue: It seems that "Default Website\RDWeb\webclient" allows to use "Windows Authentication" by changing "C:\Windows\Web\RDWeb\Pages\web.config", but "Basic Authentication" is not supported. (or documented?) I was unable to make Basic Authentication work.

Could basic auth be made to work?

**Comment by theoneandonly-vector** [comment]
any update/idea on this?

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by jacobegan1** [comment]
Does anyone know if this is possible?

**Comment by ne0YT** [comment]
> Does anyone know if this is possible?

did you find a way?
