### ISSUE TITLE
What about on Premise physical or VM deployments?

### ISSUE THREAD

**Issue by absentspace** [MicrosoftDocs/windowsserverdocs#1757]
Why is everything here geared toward Azure? I realize that this is a big cash cow for MS, but many Enterprises own their infrastructure. This guide is next to useless for those scenarios.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb4ff40d-9eb9-06ce-38cd-4b95bcbfafd8
* Version Independent ID: 4195f094-f79c-9b3e-c97f-94c093d4c696
* Content: [Remote Desktop Services roles](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-roles)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-roles.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-roles.md)
* Product: **windows-server-threshold**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by IngridAtMicrosoft** [comment]
#please-close
