### ISSUE TITLE
Cannot set up WAC connections

### ISSUE THREAD

**Issue by funnybunnyQAQ** [MicrosoftDocs/windowsserverdocs#1761]
I have read your documentation, but it is still difficult to set up connection between Windows 10 client and Server 1709 instances.  I also watched the videos posted by Haley, she added multiple server but I cannot make it. So is there additional requirement I did not satisfy? The error says cannot find the specified IP address. Hope you will give me instructions so I can move forward. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc4cb072-7157-55b4-dbe1-c5723d2873b3
* Version Independent ID: 70a3605d-6d21-5719-b661-6023bad96627
* Content: [Windows Admin Center Overview](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/overview)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/overview.md)
* Product: **windows-server-threshold**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by jwwool** [comment]
Please review our [troubleshooting guide](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/troubleshooting).
