### ISSUE TITLE
Remote Management

### ISSUE THREAD

**Issue by jcovalt** [MicrosoftDocs/windowsserverdocs#1765]
We've configured ELP, and it is working. However, I've discovered that it appears we cannot manage it remotely; in order to do either Get-ADFSAccountActivity, or Reset-ADFSLockout, you have to logged in to the ADFS server itself. Trying to run these commands remotely (through Invoke-Command) returns the error 'Exception of type 'Microsoft.IdentityServer.User.UserActivityRestServiceException' was thrown.'

We'd like to allow our help desk users to check these lockouts and reset them when necessary without giving them more rights than necessary. Anyone know a way to be able to manage the lockouts without having to RDP into the server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8634165-2ff5-9b01-e3fc-17827360a5f3
* Version Independent ID: a5a91921-3193-93ad-df22-d486e65b19f8
* Content: [Configure AD FS Extranet Lockout Protection](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-extranet-smart-lockout-protection)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by xXxOlivierxXx** [comment]
Apparently is on the radar to be fixed in a future update https://social.technet.microsoft.com/Forums/windows/en-US/187db7f0-6438-4a16-862e-61662899e687/adfssmartlockoutenforce-issue?forum=ADFS

**Comment by jordanmills** [comment]
I'm a little late here, but if you use -authentication credssp on invoke-command, new-pssession, or enter-pssession then it will get around the design flaw and work.  it's not the most secure, but it's a lot better than remote desktop.

**Comment by jdelaughter** [comment]
> Apparently is on the radar to be fixed in a future update https://social.technet.microsoft.com/Forums/windows/en-US/187db7f0-6438-4a16-862e-61662899e687/adfssmartlockoutenforce-issue?forum=ADFS

lol, guess they changed their mind, still isn't working on the latest version :(

**Comment by xXxOlivierxXx** [comment]
> > Apparently is on the radar to be fixed in a future update https://social.technet.microsoft.com/Forums/windows/en-US/187db7f0-6438-4a16-862e-61662899e687/adfssmartlockoutenforce-issue?forum=ADFS
> 
> lol, guess they changed their mind, still isn't working on the latest version :(

That's sad

**Comment by jdelaughter** [comment]
> > > Apparently is on the radar to be fixed in a future update https://social.technet.microsoft.com/Forums/windows/en-US/187db7f0-6438-4a16-862e-61662899e687/adfssmartlockoutenforce-issue?forum=ADFS
> > 
> > 
> > lol, guess they changed their mind, still isn't working on the latest version :(
> 
> That's sad

I did find this though, maybe they just went in a different direction with getting this working: https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/operations/delegate-ad-fs-pshell-access
