### ISSUE TITLE
Copy paste error on Forest-Wide-Updates.md

### ISSUE THREAD

**Issue by GSam** [MicrosoftDocs/windowsserverdocs#177]
https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/RODC/Forest-Wide-Updates.md

On operation 118: {3fb79c05-8ea1-438c-8c7a-81f213aa61c2}, on the Impact property, there appears to be a copy-paste error as it reproduces the Department property description.

**Comment by MicrosoftGuyJFlo** [comment]
Taking a look at this.

**Comment by MicrosoftGuyJFlo** [comment]
@GSam Quick answer below so that you can be unblocked if you are. Sorry about the delay. This will be added to the doc later today let me know if you need anything else.

"objectClass", "msDS-ResourceProperty"
"displayname", "Impact"
"description", "The Impact property specifies the degree of organizational impact from inappropriate access or loss of the resource."
"Enabled", "FALSE"
"msDS-IsUsedAsResourceSecurityAttribute", "TRUE"
"msDS-ValueTypeReference", "CN=MS-DS-OrderedList,CN=Value Types,CN=Claims Configuration,CN=Services,%ws"
"msDS-ClaimPossibleValues", 
         High - High business impact (HBI) - 3000
	 Moderate - Medium business impact (MBI) - 2000
	 Low - Low business impact (LBI) - 1000

**Comment by GSam** [comment]
While doing some diffs, I did notice one other oddity on Operation 117: {261b5bba-3438-4d5c-a3e9-7b871e5f57f0}:

When I spun up a 2012 R2 box, the description of CN=Department_MS,CN=Resource Properties,CN=Claims Configuration,CN=Services differs slightly (with a double space).

Documentation:
"The Department property specifies the name of the department to which the resource belongs."

2012 R2 Directory:
"The Department property specifies the name of the department to which  the resource belongs."

I wouldn't exactly consider it a documentation issue, more a directory typo but I thought I may as well raise it here.

**Comment by MicrosoftGuyJFlo** [comment]
Yes @GSam in the code it has a double space but that does not change the meaning of the string as I have it in the article. 

    {LDAP_MOD_ADD,
     L"description",
     L"The Department property specifies the name of the department to which  the resource belongs."
    },

**Comment by GSam** [comment]
Ah, I see. That's all the issues I have for this individual page. But I do still have some issues in regards adprep for schema updates:

https://github.com/microsoftdocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/Schema-Updates.md

I don't currently have a copy of adprep, so I'm not sure if it's a documentation issue or a functionality issue. I'll describe the problem and maybe you can point me to the right person or issue tracker.

In Sch50.ldf, there appears to be a problem with endianness. On the add of CN=ms-Kds-SecretAgreement-Param,CN=Schema,CN=Configuration,DC=X, the schemaIDGUID is set to a value which has bytes swapped (and this is the only example in the ldf files of such an occurrence). 

AD_DS_Attributes__Windows_Server_2012_R2.ldf (sourced elsewhere):
base64: 2ZmwMP7tSXW4B+ukRNp56Q==
30b099d9-edfe-7549-b807-eba444da79e9

Adprep Sch50.ldf:
base64: MLCZ2e3+dUm4B+ukRNp56Q==
d999b030-feed-4975-b807-eba444da79e9

https://msdn.microsoft.com/en-us/library/partnercenter/hh446686(v=vs.85).aspx
I've looked at a 2012R2 domain and checked the GUID and it agrees with the link above as 30b099d9-edfe-7549-b807-eba444da79e9.

**Comment by MicrosoftGuyJFlo** [comment]
Take a look at this doc. Windows Server Docs including AD DS are now in docs.microsoft.com this should be up to date. Are you saying that you see something different in the schema ldf file? 

Do you work for Microsoft? Just wondering where these deep questions are coming from? 

https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/schema-updates#BKMK_Sch50

**Comment by GSam** [comment]
I was wondering if you'd ask the question. No, but I have contact with some of the Microsoft protocols interop team. I work on Samba Active Directory, and I'm currently seeing if I could write my own an adprep tool with the current available open documentation.

**Comment by MicrosoftGuyJFlo** [comment]
@GSam shoot me an email Flores.John (at) Microsoft (dot) com I might be able to shine some light on this for you.
