### ISSUE TITLE
Additional scenarios need describing

### ISSUE THREAD

**Issue by Amethi** [MicrosoftDocs/windowsserverdocs#1772]
It would help complete this article if the following points were discussed:
- What happens when self-signed certificates are used (default AD FS configuration). i.e. is one self-signed cert shared across the farm, or are unique self-signed certs created.
- Are CA or self-signed certs recommended/best-practice?
- Impact of using unique token signing certificates, i.e. resource partner has to trust them all, which might not be supported (many apps only support one token signing cert)
- What does the renewal process look like? Both from an AD FS and resource partner perspective.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 751704ba-23fd-e9a8-9037-9da8d2cd1f27
* Version Independent ID: 530dd7b4-7607-2a90-e49c-91268f8daf04
* Content: [Token-Signing Certificates](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/design/token-signing-certificates)
* Content Source: [WindowsServerDocs/identity/ad-fs/design/Token-Signing-Certificates.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/design/Token-Signing-Certificates.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#please-close
