### ISSUE TITLE
Credential Issues

### ISSUE THREAD

**Issue by dw2099** [MicrosoftDocs/windowsserverdocs#1773]
Every time I reload the admin center and choose to use my current windows credentials to connect to a computer, I can't connect.  I am able to manually enter the same credentials and it works fine.  

Desired result - I should not have to enter the same credentials as my current session credentials to connect to a computer or server.

**Comment by dw2099** [comment]
Here is a short video demonstrating the issue.  https://www.screencast.com/t/3lMPt5Cv7sU

**Comment by jwwool** [comment]
When you install Windows Admin Center on Windows 10, it's ready to use single sign-on. **If you're going to use Windows Admin Center on Windows Server, however, you need to set up some form of Kerberos delegation in your environment before you can use single sign-on**. The delegation configures the gateway computer as trusted to delegate to the target node. 

See documentation: [Configure single sign-on](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/configure/user-access-control#configure-single-sign-on)

**Comment by dw2099** [comment]
> When you install Windows Admin Center on Windows 10, it's ready to use single sign-on. **If you're going to use Windows Admin Center on Windows Server, however, you need to set up some form of Kerberos delegation in your environment before you can use single sign-on**. The delegation configures the gateway computer as trusted to delegate to the target node.
> 
> See documentation: [Configure single sign-on](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/configure/user-access-control#configure-single-sign-on)

While this works, if this is meant to be a replacement for server manager, i'd think this would be done automatically without any additional config as it is in that app.  Thanks for your help.
