### ISSUE TITLE
Web Client Support for Azure AD Application Proxy

### ISSUE THREAD

**Issue by tFable** [MicrosoftDocs/windowsserverdocs#1774]
Hello,

Is there a timeline as to when RD Web Client will work with Azure AD Application Proxy? Is this something that's on the road-map?

Thanks,
t

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7242a6c0-8f40-bb91-c23e-0081a4d4a94a
* Version Independent ID: 9a1213ac-baf5-c1f3-e735-33a0b818fb6f
* Content: [Supported configurations for Remote Desktop Services](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-supported-config#using-remote-desktop-services-with-application-proxy-services)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-supported-config.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-supported-config.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by Trundlore** [comment]
really interested in whether/how to publish this so that it functions with Azure AD SSO (MFA/conditional access), I would have thought this would be provided through AAD AP?

**Comment by stewartmyles** [comment]
I'm also interested in using the web client with Azure MFA, is there a timeline for this ?

**Comment by stevep4** [comment]
Any news on this yet please MS?

**Comment by ChrisM80** [comment]
Yes, would please somone from the product group shed some light on this. One portal (myapps) to rule them all (legacy apps included) once AAD Proxy supports RDWebClient.

**Comment by micahcastorina** [comment]
Very interested in this as well. Currently requiring only IE to use Azure App Proxy to rweb/gateway is not good.

**Comment by aahmad81** [comment]
Also hoping the they support all browers with Azure App Proxy and Azure AD authentication

**Comment by cgibsonmbs** [comment]
Yes me too, when will this be a thing?

**Comment by leonmeijer** [comment]
Microsoft in October 2019: "We are starting investigation to make this integration happen".

See https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/33918046-support-remote-desktop-web-client-html5-on-azure-a

**Comment by IngridAtMicrosoft** [comment]
#please-close
