### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by xXxOlivierxXx** [MicrosoftDocs/windowsserverdocs#1778]
Title "Additional advantages of Extranet Smart Lockout in AD FS 2019" and "Pre-requisites for Extranet Smart Lockout in AD FS 2019" should be 2016 instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8634165-2ff5-9b01-e3fc-17827360a5f3
* Version Independent ID: a5a91921-3193-93ad-df22-d486e65b19f8
* Content: [Configure AD FS Extranet Lockout Protection](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-extranet-smart-lockout-protection#pre-requisites-for-extranet-smart-lockout-in-ad-fs-2019)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by xXxOlivierxXx** [comment]
Nevermind, I read wrong, you can close this item.

**Comment by billmath** [comment]
#please-close
