### ISSUE TITLE
FamiliarIPs vs Observation Window

### ISSUE THREAD

**Issue by xXxOlivierxXx** [MicrosoftDocs/windowsserverdocs#1779]
From this statement in ADFS 2016: "Protects your users from experiencing extranet account lockout from malicious authentication requests. Smart lockout will prevent potentially malicious requests from unfamiliar locations while allowing the real user to sign on from the extranet from familiar locations (locations from which the user has successfully logged in before)"

If I have the IP 1.2.3.4 flagged as a Familiar IP, and an attacker makes X amount of failed login attempts, exceeding the ExtranetLockoutThreshold and putting my account in Observation mode. Will I still be able to authenticate using ADFS with my Familiar IP? or does the Observation window Freeze apply to all IPs regardless if they are Familiar or unknown?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8634165-2ff5-9b01-e3fc-17827360a5f3
* Version Independent ID: a5a91921-3193-93ad-df22-d486e65b19f8
* Content: [Configure AD FS Extranet Lockout Protection](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-extranet-smart-lockout-protection#additional-advantages-of-extranet-smart-lockout-in-ad-fs-2019)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by xXxOlivierxXx** [comment]
And I want to know what happens in the oppositve escenario. If I get too many bad logins from FamiliarIPs and my FamiliarLockout attribute switches to TRUE, are logins from unknown locations blocked as well?

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 1777 -b #assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
