### ISSUE TITLE
Certain doubts on content

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windowsserverdocs#1784]
Thanks for information about the hardware optimization , today only I came to know these considerations , thanks a lot. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a1a1b9a-b3d9-c1d8-bc17-847e0e6c4bdb
* Version Independent ID: 996ddf0d-b433-fc94-cb2d-f67fbc6c6222
* Content: [Server Hardware Performance Considerations](https://docs.microsoft.com/en-us/windows-server/administration/performance-tuning/hardware/index)
* Content Source: [WindowsServerDocs/administration/performance-tuning/hardware/index.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/performance-tuning/hardware/index.md)
* Product: **windows-server-threshold**
* GitHub Login: @phstee
* Microsoft Alias: **phstee**

**Comment by OranguTech** [comment]
You are asking a bunch of questions, many elementary/beginner questions, about a bunch of topics, all the server hardware performance page. This is not the place. (I recommend/ask the mods to move or delete this issue)

**Comment by RAJU2529** [comment]
Sorry for the trouble caused to you. could you tell me , where I can ask the same questions to get answers.
But I could not able to login social.TechNet.com so I cannot ask there sir.
Will you give me exact link?

**Comment by RAJU2529** [comment]
Sorry for the trouble caused to you. could you tell me , where I can ask the same questions to get answers.
But I could not able to login social.TechNet.com so I cannot ask there sir.
Will you give me exact link?
