### ISSUE TITLE
Contributor Guide has invalid links

### ISSUE THREAD

**Issue by ld0614** [MicrosoftDocs/windowsserverdocs#1788]
I was just browsing the [contributor guide](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/Contributor-guide/Contributor-index.md) and noticed that a number of the links are now invalid or MS employee only.

Content channel guidance - Employee Only
Style and voice - Employee Only

Tools and setup for authoring in GitHub - Links to a page which links to an Employee Only site
Linking guidelines - Page Missing

Markdown syntax, OPS-supported Markdown extensions and HTML - Employee Only

Printable markdown cheatsheet - Page Missing
Create tables in markdown - Employee Only
Create images in markdown - Page Missing
Metadata for Windows Server technical articles - Employee Only + possibly page missing?

While I'm sure the majority of document edits come from MS Employees it might make sense to post at least summaries of the guidance to support high quality contributions and avoid (or easily correct) common mistakes from contributors.

**Comment by coreyp-at-msft** [comment]
Thanks, @ld0614. You are correct that the contributor guide needs an update. I've taken note of it and we will start updating it soon.

Thanks,
Corey
