### ISSUE TITLE
When using S2D with HDDs, you cannot disable or avoid the cache.

### ISSUE THREAD

**Issue by shebaldenkov** [MicrosoftDocs/windowsserverdocs#1789]
&gt; When using S2D with HDDs, you cannot disable or avoid the cache.
Maybe this is incorrect?

With S2D I can create HDD-only virtual disks and SSD-only virtual disks. Both without any cache enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f70b91f-1cbc-3ea4-3760-d8945f9ff1fb
* Version Independent ID: 5372fa26-d2b9-8fa9-c4ec-7ce34f062b57
* Content: [Cluster to cluster Storage Replication](https://docs.microsoft.com/en-us/windows-server/storage/storage-replica/cluster-to-cluster-storage-replication)
* Content Source: [WindowsServerDocs/storage/storage-replica/cluster-to-cluster-storage-replication.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-replica/cluster-to-cluster-storage-replication.md)
* Product: **windows-server-threshold**
* GitHub Login: @nedpyle
* Microsoft Alias: **nedpyle**

**Comment by StevenEk** [comment]
Storage Spaces Direct (S2D) requires that a system that is using HDD for capacity drives is required to have S2D cache devices enabled.  https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/choosing-drives  When you create a storage spaces virtual disk you specify HDD, but there needs to be S2D cache devices on the system.  The exception to this is when it's in a virtual environment and there is only one media type of disk available, then there is no cache device and the available capacity disks may show up as HDD's, depending on the hyper-visor that is hosting the VMs.
