### ISSUE TITLE
Windows Server 2019

### ISSUE THREAD

**Issue by gabrielluizbh** [MicrosoftDocs/windowsserverdocs#1793]
Why the delay in launching Windows Server 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 844864ef-2c94-77ff-b85e-301331d283a6
* Version Independent ID: 960ddbd0-a265-7730-859d-a0a308d7a3b1
* Content: [What's new in Windows Server 2019](https://docs.microsoft.com/en-us/windows-server/get-started-19/whats-new-19)
* Content Source: [WindowsServerDocs/get-started-19/whats-new-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/whats-new-19.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by coreyp-at-msft** [comment]
Hi @gabrielluizbh , see, https://blogs.windows.com/windowsexperience/2018/10/09/updated-version-of-windows-10-october-2018-update-released-to-windows-insiders/ for information about the rollout pause.
