### ISSUE TITLE
Witness in manual failover

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/windowsserverdocs#1795]
Can you expand a little bit on the recommendations for high availability for witnesses?
I have a customer with two SQL Server VMs each across two Azure regions (four servers total). They currently also have a witness configured in each region, but it's unclear from the documents how the witness in the second region should be configured or if it is needed at all. If there are even numbers of nodes at both sites, wouldn't you need a witness in the case of failover to the second site?
This is assuming some kind of disaster that makes the entire first site (including the witness) unusable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9bf06da-0739-c826-6b28-c942f394b1a9
* Version Independent ID: 6a1651c0-fa3f-037e-4caa-d255097e048f
* Content: [Configure and manage the quorum in a failover cluster](https://docs.microsoft.com/en-us/windows-server/failover-clustering/manage-cluster-quorum#span-data-ttu-id8ba12-297クォーラムせずに起動してクラスターを回復しますspanspan-classsxs-lookupspan-data-stu-id8ba12-297recover-a-cluster-by-starting-without-quorumspanspan)
* Content Source: [WindowsServerDocs/failover-clustering/manage-cluster-quorum.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/manage-cluster-quorum.md)
* Product: **windows-server-threshold**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
