### ISSUE TITLE
Update documentation with Windows Server 2019

### ISSUE THREAD

**Issue by Nicolewuch** [MicrosoftDocs/windowsserverdocs#1797]
Hi, could you please update the content and also include Windows Server 2019 in those release information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 738f3265-e459-da12-0f2c-d4fc1eff4fff
* Version Independent ID: 679afb77-9852-4608-291c-74bf2739890f
* Content: [Windows Server release information](https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info)
* Content Source: [WindowsServerDocs/get-started/windows-server-release-info.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/windows-server-release-info.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by lizap** [comment]
We've just updated the page with the latest versions, release dates, and servicing dates. Thanks!

**Comment by EugenePugin** [comment]
what about Version for Win2019 LTSC?
