### ISSUE TITLE
Login issue using Microsoft Account.

### ISSUE THREAD

**Issue by xkevlar7x** [MicrosoftDocs/windowsserverdocs#1808]
When I'm on my LAN, I can RDP in to my Windows 10 systems from any other system using "Microsoft Account\myemailaddress@gmail.com" But when I attempt to use the RDP iOS app, it will not accept that user name format. It says "User name must be in the form of user, user@domain, or domain\user" I've tried every conceivable combination/possibility. Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef479a2e-4ca4-1c81-a465-dd476ef95ff0
* Version Independent ID: 877f5d0b-3849-4ff3-7ebd-e109cc1508ab
* Content: [Get started with Remote Desktop on iOS](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-ios)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-ios.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-ios.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
#please-close
