### ISSUE TITLE
SET is not compatible with the following networking technologies in Windows Server 2016

### ISSUE THREAD

**Issue by runemy** [MicrosoftDocs/windowsserverdocs#181]
Hi

It's written in: https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v-virtual-switch/rdma-and-switch-embedded-teaming

"SET is not compatible with the following networking technologies in Windows Server 2016"
- 802.1X authentication
- IPsec Task Offload (IPsecTO)
- QoS in host or native operating systems
- Receive side coalescing (RSC)
- Receive side scaling (RSS)
- TCP Chimney Offload
- Virtual Machine QoS (VM-QoS)

It would be a good improvement of the documentation if it was described how to properly disable these technologies with use of PowerShell/commandline.

Br. Rune

**Comment by jamesmci** [comment]
My understanding is that none of these technologies is enabled by default. Verifying as much with PM.

**Comment by jamesmci** [comment]
New content is now added to the topic at https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v-virtual-switch/rdma-and-switch-embedded-teaming#bkmk_compat
