### ISSUE TITLE
Smart card explanation

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/windowsserverdocs#1817]
I believe it would be worthwhile to explain why we should implement the policy setting Smart card is required for interactive logon and what the implications are.  Such as what does this mean when you need to do a first recovery and you need to boot into DSRM. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8499f8c0-64c7-2b6e-9022-115ed3d69904
* Version Independent ID: 9bf515dd-a4e4-baf2-8c18-0d0d76dd5eb0
* Content: [Appendix D - Securing Built-In Administrator Accounts in Active Directory](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/appendix-d--securing-built-in-administrator-accounts-in-active-directory)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-D--Securing-Built-In-Administrator-Accounts-in-Active-Directory.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-D--Securing-Built-In-Administrator-Accounts-in-Active-Directory.md)
* Product: **windows-server-threshold**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
@poortom1004 these are just recommendations. Organizations must look at these and determine what is feasible for their environment and what changes they are comfortable with.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close

**Comment by poortom1004** [comment]
ok, this makes sense to implement even if smart cards aren't being used in the org based on what you're saying, by ensuring that physical access is required to log into the server, instead of simply opening a remote console to the server.

**Comment by poortom1004** [comment]
Perhaps it may make sense to explain this in the article for admins unfamiliar with PKI experience or with no PKI environment.  Would hate for an admin to configure the requirement for a smart card to login, only to realize the account can't be logged in to if they have no PKI environment.
