### ISSUE TITLE
Configuring TLS Cipher Suite Order

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windowsserverdocs#1829]
sir i have already enabled below "  SSL Cipher Suite Order" in gpo on windows 10 1803 64bit

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec3386bb-58b2-ef3f-aa14-c9a7bce7f007
* Version Independent ID: c884c253-2b2c-d77d-f705-1e00f34dd808
* Content: [Manage Transport Layer Security (TLS)](https://docs.microsoft.com/en-in/windows-server/security/tls/manage-tls#configuring-tls-cipher-suite-order)
* Content Source: [WindowsServerDocs/security/tls/manage-tls.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/manage-tls.md)
* Product: **windows-server-threshold**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by coreyp-at-msft** [comment]
Hi @RAJU2529 , was there a problem when you did that?

**Comment by RAJU2529** [comment]
two months before I enabled. I share the Group policy report afternoon

**Comment by RAJU2529** [comment]
currently  I am using 1809 build no 17763.379

**Comment by IngridAtMicrosoft** [comment]
#please-close
