### ISSUE TITLE
See also link

### ISSUE THREAD

**Issue by EdgarSpruijt** [MicrosoftDocs/windowsserverdocs#1838]
Link under the See Also section doesn't work anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3785c77-4b26-9f6d-b170-dc55a46a113a
* Version Independent ID: 773f980f-d00f-deb3-495c-584b7389fe4f
* Content: [Monitor connected remote clients for activity and status](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/ras/monitoring-and-accounting/monitor-connected-remote-clients-for-activity-and-status)
* Content Source: [WindowsServerDocs/remote/remote-access/ras/monitoring-and-accounting/Monitor-connected-remote-clients-for-activity-and-status.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/ras/monitoring-and-accounting/Monitor-connected-remote-clients-for-activity-and-status.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by lizap** [comment]
Thanks for raising this issue - we've removed the link.
