### ISSUE TITLE
Registry value is incorrect

### ISSUE THREAD

**Issue by paulrichwine** [MicrosoftDocs/windowsserverdocs#1842]
The correct registry string value to enable and provide a path for advanced logging is LogFileName, not NameLogFile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46ce4217-ff6a-18f8-6aef-a97c5b0fbcbe
* Version Independent ID: a74b82d9-d8c4-ffe1-707a-2b05d8b056ca
* Content: [Determine Allow-Deny List and Application Inventory for Software Restriction Policies](https://docs.microsoft.com/en-us/windows-server/identity/software-restriction-policies/determine-allow-deny-list-and-application-inventory-for-software-restriction-policies)
* Content Source: [WindowsServerDocs/identity/software-restriction-policies/determine-allow-deny-list-and-application-inventory-for-software-restriction-policies.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/software-restriction-policies/determine-allow-deny-list-and-application-inventory-for-software-restriction-policies.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IN-jwink** [comment]
You are correct, but Microsoft does not care when they put Gibberish in an article.

**Comment by IngridAtMicrosoft** [comment]
#please-close
