### ISSUE TITLE
Windows Admin Center - server listing

### ISSUE THREAD

**Issue by pkuzniasz** [MicrosoftDocs/windowsserverdocs#1845]
Working on setting this up and adding servers under my domain username.  Shared link with another admin, but servers I added do not appear in Admin Center.  Why?  Is there a way for the admins to all have access to servers I have already setup?

**Comment by jwwool** [comment]
Server lists are currently user-specific. Shared lists are on the roadmap. The associated request is [here](https://windowsserver.uservoice.com/forums/295071-management-tools/suggestions/34015741--deployment-allow-windows-admin-center-to-be-conf).
