### ISSUE TITLE
Odd... this article was posted while MS has blocked all DLs of Server 2019 due to bugs

### ISSUE THREAD

**Issue by jagarrison** [MicrosoftDocs/windowsserverdocs#1846]
I was just looking around to see if there was an update on when MS plans to have the 1809 version issues resolved and came across this article. Might want to add the section about files being deleted. If you make it a feature then when customers complain you can update the feature to work the way we want and add it to your success numbers. At least that seems to be the SOP for MS these past 10 years. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 844864ef-2c94-77ff-b85e-301331d283a6
* Version Independent ID: 960ddbd0-a265-7730-859d-a0a308d7a3b1
* Content: [What's new in Windows Server 2019](https://docs.microsoft.com/en-us/windows-server/get-started-19/whats-new-19)
* Content Source: [WindowsServerDocs/get-started-19/whats-new-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/whats-new-19.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by coreyp-at-msft** [comment]
Thanks, @jagarrison. We've logged your suggestion.
