### ISSUE TITLE
WinRM Protocol

### ISSUE THREAD

**Issue by roryschmitz** [MicrosoftDocs/windowsserverdocs#1848]
Hello, can we have the protocol added for WinRM port 5985?  Is it TCP, UDP, both, other?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a834de4-c696-4599-6ab2-94ae03d31471
* Version Independent ID: 78658bfd-8bcc-0d71-5139-77733f1a795e
* Content: [Best Practices for securing AD FS and Web Application Proxy](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/best-practices-securing-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Best-Practices-Securing-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Best-Practices-Securing-AD-FS.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#please-close
