### ISSUE TITLE
Is there a way to remap shortcut keys

### ISSUE THREAD

**Issue by rdcoe** [MicrosoftDocs/windowsserverdocs#1855]
Linux virtual desktops use ctrl-alt-arrow, so the default mouse release shortcut is a problem.  Would be good to provide settings to re-map those shortcuts, perhaps following VBox's example shortcuts would be good.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c67eb5e-7fb1-0840-dfe0-40955b3f9489
* Version Independent ID: f30efc81-d336-2ff2-3fe5-5eb3f9432d82
* Content: [Hyper-V Virtual Machine Connection](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/learn-more/hyper-v-virtual-machine-connect#keyboard-shortcuts)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/learn-more/hyper-v-virtual-machine-connect.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/learn-more/hyper-v-virtual-machine-connect.md)
* Product: **windows-server-threshold**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by IngridAtMicrosoft** [comment]
#please-close
