### ISSUE TITLE
Needs to be updated for Ubuntu 18.10

### ISSUE THREAD

**Issue by jrp2014** [MicrosoftDocs/windowsserverdocs#1856]
Perhaps it all works fine out of the box, but it would be good to have that confirmed, and the documentation updated for the latest tools / features such as xRDP (on Server 2016, 2019, etc).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07bfc89-b3b5-7090-768b-75412724e1c2
* Version Independent ID: 72e55502-a116-a71c-a9b2-a65c3f74b27c
* Content: [Feature Descriptions for Linux and FreeBSD virtual machines on Hyper-V](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/feature-descriptions-for-linux-and-freebsd-virtual-machines-on-hyper-v)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Feature-Descriptions-for-Linux-and-FreeBSD-virtual-machines-on-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/Feature-Descriptions-for-Linux-and-FreeBSD-virtual-machines-on-Hyper-V.md)
* Service: **na**
* Product: **windows-server-threshold**
* GitHub Login: @shirgall
* Microsoft Alias: **kathydav**

**Comment by shirgall** [comment]
We are in the process of updating this with PR https://github.com/MicrosoftDocs/windowsserverdocs/pull/1958

Be aware that there's a known issue with SRIOV and Ubuntu 18.10

**Comment by illfated** [comment]
Is the issue resolved now? Can this ticket be closed?

**Comment by illfated** [comment]
#please-close
