### ISSUE TITLE
Server 2019?

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/windowsserverdocs#1861]
Server 2019 is mentioned once on this page, any more details coming?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adf594c8-5d55-8bfe-99b8-e1a1f91081fd
* Version Independent ID: 32ba9200-79f5-671d-bcc5-650540e8e94f
* Content: [Upgrade and Conversion Options for Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/get-started/supported-upgrade-paths)
* Content Source: [WindowsServerDocs/get-started/Supported-Upgrade-Paths.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/Supported-Upgrade-Paths.md)
* Product: **windows-server-threshold**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by doctordns** [comment]
The page in question is about upgrading to Server 2016, so I would not expect Server 2019 content.

Having said that, there is an urgent need to clarify the documentation situation with respect to 2019 content. From what I can tall, everything that worked in 2016 works the same in 2019. 

There are several duplicate or related issues regarding 2019 content, including:
#1722 
#1737 
#1860 
#1861
#1870 
#1883
#1989 
#2041
#2118

**Comment by eponerine** [comment]
I'm shocked that this hasn't even been addressed in almost 10 months. Need to get _**SOME**_ clarification here.
