### ISSUE TITLE
Explain status output in general and encryption method specifically

### ISSUE THREAD

**Issue by valentijnscholten** [MicrosoftDocs/windowsserverdocs#1868]
Hi,
With regards to the vulnerabilities found in hardware encryption of SSDs, it would be helpful if more information about the output of the status command was added.

How can we know if hardware encryption is in use for a drive or software encryption?

According to this blog: https://helgeklein.com/blog/2015/01/how-to-enable-bitlocker-hardware-encryption-with-ssd/

the encryptionmethod field will return something with "hardware encryption" in the value if hardware encryption is enabled and something like XTS-AES when using software encryption?

cheers,
Valentijn

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d84ea616-7dad-0931-2ccf-1966836114c1
* Version Independent ID: 98591e29-4ce2-f2b0-67b2-34e3a6a0f152
* Content: [manage-bde status](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/manage-bde-status)
* Content Source: [WindowsServerDocs/administration/windows-commands/manage-bde-status.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/manage-bde-status.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by tghosth** [comment]
Yes and this issue has clearly now become a lot more important!
https://www.howtogeek.com/fyi/you-cant-trust-bitlocker-to-encrypt-your-ssd-on-windows-10/

**Comment by IngridAtMicrosoft** [comment]
#please-close
