### ISSUE TITLE
Steps 5 and 6 identical under "Configure certificate autoenrollment in Group Policy"

### ISSUE THREAD

**Issue by Jammrock** [MicrosoftDocs/windowsserverdocs#1876]
Steps 5 and 6 under "Configure certificate autoenrollment in Group Policy" appear word for word identical.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e886cf2-b2cc-1942-2e93-b83ba3f5c81a
* Version Independent ID: 14185f76-c920-66a5-9d3b-51ddc4845ee8
* Content: [Configure the Server Infrastructure](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by Jammrock** [comment]
Never mind, there's a one word difference. I just didn't catch it at first glance. Perhaps some emphasis on User versus Computer would help in the future?

**Comment by IngridAtMicrosoft** [comment]
#please-close
