### ISSUE TITLE
Symbolic link friendly

### ISSUE THREAD

**Issue by jackshlin** [MicrosoftDocs/windowsserverdocs#1890]
Can you add options to make dir interoperate more friendly with symbolic links? We use symbolic links to link to a parent directory, and dir would keep recursing into the symbolic link over and over. The Windows Explorer search box does not appear to have this issue, so if you could make dir do that, it would be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6338eb04-7d95-0ef7-1774-8cf66d46925f
* Version Independent ID: dfb840da-3995-9755-ca10-bf41b0f3a863
* Content: [dir](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/dir)
* Content Source: [WindowsServerDocs/administration/windows-commands/dir.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/dir.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
#please-close
