### ISSUE TITLE
Work Resource Connection Issue

### ISSUE THREAD

**Issue by Aslamfarook** [MicrosoftDocs/windowsserverdocs#1893]
Hai 
I  have done the all setup i am stuck up while accessing the work resource i got error like 
"Oops could not connect The connection to the remote PC was lost. This might be because of a network connection problem. If this keeps happening, ask your admin or tech support for help."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Product: **windows-server-threshold**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by mlynnyds** [comment]
Getting the same issue. UI says "Opening Remote Port" and then the same Oops could not connect.
Developer console says "reason=WebSocket closed with code: 1006 reason"

**Comment by nj28sharp** [comment]
Same issue here in two environments, i'm sure I'm missing something

**Comment by leonmeijer** [comment]
Had something like this with the HTML5 client. Fixed it by disabling HTTP/2 in IIS under the bindings. Found Firefox more verbose around websocket errors (in console and network tabs) than Chrome and Edge.
