### ISSUE TITLE
Command to enable remote administration of Windows Firewall incorrect

### ISSUE THREAD

**Issue by mbtxau** [MicrosoftDocs/windowsserverdocs#1894]
Inside "Administrative tasks from the command line" and then the subsection "Networking and Firewall" it lists to "Enable remote administration of the firewall" the command is 

netsh advfirewall firewall set rule group=”Windows Firewall Remote Management” new enable=yes

However that command will not work, at least on Server Core 2016 or 1709, 1803 and 1809.  The correct command should be

netsh advfirewall firewall set rule group=”Windows Defender Firewall Remote Management” new enable=yes

This is because the the remote management display group for the Windows Firewall with Advanced Security featured in Server 2016 and newer is called "Windows Defender Firewall Remote Management" and not just "Windows Firewall Remote Management".  

This display group name can also be verified in PowerShell by running a "Get-NetFirewallRule -DisplayGroup "*Firewall*" with a wildcard both before Firewall and after it, which will show any display group firewall rule that contains the word Firewall. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a821622a-23dd-f730-6063-e9e7445876ff
* Version Independent ID: 1b8404ba-31fd-ee15-e10b-b255fc0c53fd
* Content: [Administer Server Core](https://docs.microsoft.com/en-us/windows-server/administration/server-core/server-core-administer#administrative-tasks-from-the-command-line)
* Content Source: [WindowsServerDocs/administration/server-core/server-core-administer.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/server-core/server-core-administer.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap

**Comment by maanku** [comment]
@mbtxau is correct. Also, I am confirming that the same applies to Server Core 1903.
