### ISSUE TITLE
ReFS - Data Deduplication correction for Spanish version

### ISSUE THREAD

**Issue by AlexZ005** [MicrosoftDocs/windowsserverdocs#1902]
Spanish [version](https://docs.microsoft.com/es-es/windows-server/storage/refs/refs-overview) should state 'Data deduplication' (Desduplicación de datos) available on Windows Server, since version 1709 and later. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb95c569-f9ad-8e2d-3423-2c9629e65b72
* Version Independent ID: e2a4c64a-97c0-b310-2e47-d0c348a8ead7
* Content: [Resilient File System (ReFS) overview](https://docs.microsoft.com/en-us/windows-server/storage/refs/refs-overview)
* Content Source: [WindowsServerDocs/storage/refs/refs-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/refs/refs-overview.md)
* Product: **windows-server-threshold**
* GitHub Login: @gawatu
* Microsoft Alias: **gawatu**

**Comment by AlexZ005** [comment]
Please also correct it to 'Deduplicación de datos', currently there is a typo in the fist word. Thanks.

**Comment by IngridAtMicrosoft** [comment]
#please-close
