### ISSUE TITLE
Typo!

### ISSUE THREAD

**Issue by PhrygianMode** [MicrosoftDocs/windowsserverdocs#1904]
"security of the enviornment"

(courtesy of Microsoft Word)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3744c801-de52-6954-f091-37679a81908a
* Version Independent ID: 753442ac-9407-f77a-4b23-97a8c70dbb72
* Content: [Remote Desktop Services - Access from anywhere](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-plan-access-from-anywhere)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-plan-access-from-anywhere.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-plan-access-from-anywhere.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by lizap** [comment]
Thanks for catching this typo. The fix will be live on the morning of 11/13/2018.
