### ISSUE TITLE
Examples provide invalid syntax

### ISSUE THREAD

**Issue by rbeesley** [MicrosoftDocs/windowsserverdocs#1906]
Many (if not all) of the provided examples for using manage-bde are simply wrong and executing them will generate an "Invalid Syntax" error. This is because the arguments before the Volume have dropped their leading "dash." For example, the command `manage-bde -protectors -adbackup C:` is incorrectly shown as `managed-bde protectors adbackup C:`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dd9f8b1-7b5e-844d-fcab-94ec6741dd4a
* Version Independent ID: 52ed5d26-1606-0afb-4812-c3eefb534896
* Content: [manage-bde protectors](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/manage-bde-protectors#BKMK_disableprot)
* Content Source: [WindowsServerDocs/administration/windows-commands/manage-bde-protectors.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/manage-bde-protectors.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by rbeesley** [comment]
@steved0x, it looks like the defect I logged was fixed with 08645b607215017b85440074f1e196b2899c513a.

**Comment by illfated** [comment]
@rbeesley : Thank you for pointing out that detail and that it seems to be corrected.

**Comment by illfated** [comment]
This issue ticket was in effect resolved by PR #3437 and commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/08645b607215017b85440074f1e196b2899c513a .

**Comment by illfated** [comment]
#please-close
