### ISSUE TITLE
Enhance info on supplying obj and 'Log on as a service' right

### ISSUE THREAD

**Issue by guardrex** [MicrosoftDocs/windowsserverdocs#1912]
The topic doesn't explicitly say that when obj is supplied to `sc create` that the user account is granted `Log on as a service` rights. It looks like that's the case, so I wonder if it makes sense to call it out here for the obj entry in the table? ... and if this is the case, we won't need to make any changes to our topic, which uses `sc create` to set up the service.

<img width="458" alt="capture" src="https://user-images.githubusercontent.com/1622880/48441690-c9def700-e751-11e8-896d-2eff87655aeb.PNG">

Cross-ref: https://github.com/aspnet/Docs/issues/9573

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca7f3a23-37b7-f9f3-4f59-91b98c1c8254
* Version Independent ID: fda7f21d-f770-50fa-4cc1-e7139efeaa80
* Content: [Sc create](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/sc-create)
* Content Source: [WindowsServerDocs/administration/windows-commands/sc-create.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/sc-create.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by pherbel** [comment]
No. This sc create command will not grant "log on as a service" rights for user.
It would be great, but currently it is not working. Also it is true for "sc config"

**Comment by guardrex** [comment]
Correct ..... re-evaluation indicates that the privilege was assigned to the account in *some other way* when I was testing to set up the topic updates. The topic didn't use a dedicated user account prior to that, so this cropped up on the last update. This topic on `sc create` is fine. I plan to cover using the Local Security Policy console to grant `Log on as a service` to the user. Thanks @pherbel for calling this out.
