### ISSUE TITLE
Extensions Issues 

### ISSUE THREAD

**Issue by slomond** [MicrosoftDocs/windowsserverdocs#1918]
I am not able to see the extensions that are installed. I get the below error.. 

A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 23.212.169.122:443

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05df3d17-6978-2214-dad9-3eace6d7ee92
* Version Independent ID: ef8e8662-7c07-3118-59b3-0ac30af285f0
* Content: [Windows Admin Center Common Troubleshooting Steps](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/troubleshooting)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/use/troubleshooting.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/use/troubleshooting.md)
* Product: **windows-server-threshold**
* GitHub Login: @jwwool
* Microsoft Alias: **jeffrew**

**Comment by IngridAtMicrosoft** [comment]
#please-close
