### ISSUE TITLE
Sample script does not include an exit line

### ISSUE THREAD

**Issue by gkzone** [MicrosoftDocs/windowsserverdocs#1924]
See the title, but I'll repeat. The sample script above does not include an exit line. Which causes some people to forget to add it in their own script and brick a computer running an OSD test. Not me, I'm submitting this for a friend.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74c91c9d-b904-02a0-11e3-8053f9bd34b2
* Version Independent ID: 74ec4390-f6f6-6bc6-36c4-afe5c57350f8
* Content: [Diskpart Scripts and Examples](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/diskpart-scripts-and-examples)
* Content Source: [WindowsServerDocs/administration/windows-commands/diskpart-scripts-and-examples.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/diskpart-scripts-and-examples.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
#please-close
