### ISSUE TITLE
Missing Active Directory Domain Services

### ISSUE THREAD

**Issue by Doug1943** [MicrosoftDocs/windowsserverdocs#1926]
I have got a new computer which is downstairs.  I have another computer, upstairs, attached to a printer. My previous downstairs computer could print on the upstairs computer's printer. The new one will not. When I click on 'Find Printer' I am told that  Active Director Domain Services is 'currently unavailable'.  

What can I do?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94251036-29c8-87b0-eb8f-2516600d4aac
* Version Independent ID: f5309f09-ad43-619b-c23c-269f37177d2c
* Content: [Active Directory Domain Services Overview](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/get-started/virtual-dc/active-directory-domain-services-overview)
* Content Source: [WindowsServerDocs/identity/ad-ds/get-started/virtual-dc/Active-Directory-Domain-Services-Overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/get-started/virtual-dc/Active-Directory-Domain-Services-Overview.md)
* Product: **windows-server-threshold**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
You may want to look at the following support articles. This is not a forum for support for Windows 10. 

https://support.microsoft.com/help/4015397
https://support.microsoft.com/en-us/help/4089224/windows-10-share-network-printer

#please-close
