### ISSUE TITLE
can't use with 2nd monitor now.

### ISSUE THREAD

**Issue by jackfruhecolab** [MicrosoftDocs/windowsserverdocs#1928]
In this latest update, if I drag a window to my second monitor, it snaps back to the primary display, this presents a challenge when I need to open multiple remote desktops, as there is not enough room on my primary display to show them side by side.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 526c6220-c5f5-7dce-3239-66e5134cd40e
* Version Independent ID: 598ceeef-0f46-fff1-8528-45c12e112612
* Content: [Get started with Remote Desktop on Mac](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-mac)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by cmcgoo** [comment]
I have this too. The remote sessions start jumping to whichever monitor has focus.
To minimise the issue, click in the monitor you want it on then drag the remote session window over to that monitor and quickly click inside that window to ensure that monitor has focus. Have sent feedback directly through the app about this but no responses yet.
