### ISSUE TITLE
Article about RDP should have hint about restricting source IP.

### ISSUE THREAD

**Issue by sebastiannielsen** [MicrosoftDocs/windowsserverdocs#193]
On this article:
https://github.com/microsoftdocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-allow-outside-access.md

I suggest that this are added:
After:
then the router's port forwarding will always point to the correct IP address.

But before VPN section:

add this:
"You can in most routers, set which source IP or source network, that are able to utilize the port mapping. So if you know you are only connecting from work, you can add the IP of your workplace, and then you avoid opening the port to the public internet. If the host you are connecting from have a dynamic IP, you can set the source restriction to allow the whole range of that particular ISP."

**Comment by lizap** [comment]
Thanks, Sebastian, for the suggestion. It makes sense, so give me just a bit of time to validate and then I'll get it added.

Not sure if you're aware, but you can also make this kind of change yourself by clicking **Edit** on the published page. Edit the file directly and then follow the on-screen steps to submit the change to us. Your ID will go into the system as a contributor to the topic, ensuring you get some credit for your help. If you're interested but need more info, I'm happy to help onboard you. 

THANKS!

**Comment by sebastiannielsen** [comment]
@lizap I tried to edit the document but I don't have permission to do it.

**Comment by lizap** [comment]
Article was updated to include the requested information. Thanks!
