### ISSUE TITLE
The link to Windows Server 2008 Service Pack 2 (SP2) returns "404 - Page not found" error

### ISSUE THREAD

**Issue by jvopalensky** [MicrosoftDocs/windowsserverdocs#1930]
See https://docs.microsoft.com/www.microsoft.com/en-us/download/details.aspx?id=16468

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eb610cb-6ff0-e164-7694-ef22d4a2ccaa
* Version Independent ID: e4a98df5-1192-6cd0-1410-f80ddb69e144
* Content: [Upload a Windows Server 2008/2008 R2 specialized image to Azure](https://docs.microsoft.com/en-us/windows-server/get-started/uploading-specialized-ws08-image-to-azure)
* Content Source: [WindowsServerDocs/get-started/uploading-specialized-WS08-image-to-azure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/uploading-specialized-WS08-image-to-azure.md)
* Product: **windows-server-threshold**
* GitHub Login: @MikeBlodge
* Microsoft Alias: **mikeblodge**

**Comment by lizap** [comment]
Thanks for raising this issue. The link's been removed.
