### ISSUE TITLE
FSMO role transfer question

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/windowsserverdocs#1932]
Is it a requirement to move all FSMO roles to the new OS running on the new DC if you don't plan on immediately demoting all other domain controllers in your environment?  Step 10 seems to indicate that moving all FSMO roles to the new DC running the new OS is a requirement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e32288e6-1a81-01da-51bf-d1564049a28a
* Version Independent ID: 7388c199-ee35-63fa-deda-e3f6399de3ee
* Content: [Upgrade Domain Controllers to Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/upgrade-domain-controllers)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/upgrade-domain-controllers.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/upgrade-domain-controllers.md)
* Product: **windows-server-threshold**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
No you don't have to move them all immediately. That is just saying if all of the roles are on that server on a downlevel OS you need to move them over. You can do the FSMO role moves in phases. Whatever works best in your testing for your environment.

**Comment by poortom1004** [comment]
Hmmm, I just came across this part in this document here:
https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/domain-wide-updates#windows-server-2016-domain-wide-updates

says at the bottom of that section that "The Enterprise Key Admins and Key Admins groups are only created after a Windows Server 2016 Domain Controller is promoted and takes over the PDC Emulator FSMO role."

**Comment by MicrosoftGuyJFlo** [comment]
@poortom1004 yes if you need to use features that depend on that you will need to move the PDC Emulator role.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close

**Comment by kaolah** [comment]
One more commnet, if you upgrade the schema from Windows Server 2016 ISO media you will give Enterprise Key Admins group a full controll to your root domain. This is too much and it should be changed to read and write permission for msDS-KeyCredentialLink attribute. There is a script to check it and fix it. 

https://gallery.technet.microsoft.com/scriptcenter/Enterprise-Key-Admins-720eb270

Or you can just run dsacls dc=contoso,dc=com and look for the permission. If you have not moved PDC to 2016 DC you will see the SID only which will end with 527.

**Comment by kaolah** [comment]
The permissions was corrected in Windows Server 2019 so in case you will upgrade schema from 2019 ISO media the Enterprise Key Admins will have correct permissions.
