### ISSUE TITLE
Start-DscConfiguration doesn't work

### ISSUE THREAD

**Issue by leon831** [MicrosoftDocs/windowsserverdocs#1937]
There is no distecrory like InstallJeaFeature in WindowsAdminCenter_RBAC

Script line:
Start-DscConfiguration -Path "$PSScriptRoot\InstallJeaFeature" -JobName "Installing JEA for Windows Admin Center" -Force

Result:
Start-DscConfiguration : C:\install\WindowsAdminCenter_RBAC\InstallJeaFeature is not a valid directory.

InstallJeaFeature is a ps1 file not a directory. Start-DSCconfiguration can't read configuration

**Comment by IngridAtMicrosoft** [comment]
#please-close
