### ISSUE TITLE
CA configuration for non-domain joined computers - missing Appendix

### ISSUE THREAD

**Issue by nickpoore** [MicrosoftDocs/windowsserverdocs#1940]
The documentation says: 
On the RRAS server, generate a file called VPNGateway.inf based upon the example certificate policy request provided in Appendix A (section 0) and customize the following entries:

There is no appendix.

Please will you complete the documentation so that we can actually follow the instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e886cf2-b2cc-1942-2e93-b83ba3f5c81a
* Version Independent ID: 14185f76-c920-66a5-9d3b-51ddc4845ee8
* Content: [Configure the Server Infrastructure](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure#next-step)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by talrashha** [comment]
@MS: Hi, any update on this?

**Comment by talrashha** [comment]
Actually found it elsewhere:

[Version]

Signature=”$Windows NT$”

[NewRequest]
Subject = “CN=vpn.preferred-it.com”
Exportable = FALSE 
KeyLength = 2048 
KeySpec = 1 
KeyUsage = 0xA0 
MachineKeySet = True
ProviderName = “Microsoft RSA SChannel Cryptographic Provider”
RequestType = PKCS10

[Extensions]
2.5.29.17 = “{text}”
_continue_ = “dns=vpn.preferred-it.com&”

**Comment by alschneiter** [comment]
You can use this inf File:

[Version]
 
Signature="$Windows NT$"
 
[NewRequest]
Subject = "CN=vpn1.your.url"
Exportable = FALSE
KeyLength = 2048
KeySpec = 1
KeyUsage = 0xA0
MachineKeySet = True
ProviderName = "Microsoft RSA SChannel Cryptographic Provider"
RequestType = PKCS10
 
[Strings]
szOID_SUBJECT_ALT_NAME2 = "2.5.29.17"
 
[Extensions]
%szOID_SUBJECT_ALT_NAME2% = "{text}dns=vpn1.your.url"

**Comment by illfated** [comment]
(ref. #4916 )

**Comment by illfated** [comment]
No comment, reply or follow-up for more than 20 months.

#please-close
