### ISSUE TITLE
Connection Name as App Title/Name instead of "Microsoft Remote Desktop"

### ISSUE THREAD

**Issue by fiejen** [MicrosoftDocs/windowsserverdocs#1952]
Hi

![image](https://user-images.githubusercontent.com/26218590/48702071-3c3b5580-ebf0-11e8-934f-ebc65938d8b1.png)

Is it possible to name the appearance of MS RDP instead if its name as the connection name? So one could jump there via "spotlight search" on mac ?

**Comment by fiejen** [comment]
this gets more interesting when you have multiple connections at the same time.

**Comment by IngridAtMicrosoft** [comment]
#please-close
