### ISSUE TITLE
–StorageSubsystemFriendlyName “Storage Spaces*”

### ISSUE THREAD

**Issue by thedxt** [MicrosoftDocs/windowsserverdocs#1954]
–StorageSubsystemFriendlyName “Storage Spaces*” appears to be wrong as it will result in an error if you change the command to  –StorageSubsystemFriendlyName “Windows Storage*”  then it works correctly. Specifically on server 2016 Standard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acd8af43-5256-169f-fe3c-c890521cf888
* Version Independent ID: 6052c6dc-af27-eb51-1cbc-53ca1d026f26
* Content: [Deploy Storage Spaces on a stand-alone server](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/deploy-standalone-storage-spaces)
* Content Source: [WindowsServerDocs/storage/storage-spaces/deploy-standalone-storage-spaces.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/deploy-standalone-storage-spaces.md)
* Product: **windows-server-threshold**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by mossywell** [comment]
@thedxt thank you - you are right. The subsystem "Storage Spaces*" is an over-zealous copy and paste from the S2D installation process. ;-)
