### ISSUE TITLE
Error code: 0x807

### ISSUE THREAD

**Issue by naaronne** [MicrosoftDocs/windowsserverdocs#1955]
Attempting to connect from my MacBook running macOS 10.14 with MS Remote Desktop 10.2.3 (1343) I receive the following error:

"Your session ended because of an error. If this keeps happening, contact your network administrator for assistance.

Error code: 0x807"

I'm using my AzureAD\FirstnameLastname for credentials

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 526c6220-c5f5-7dce-3239-66e5134cd40e
* Version Independent ID: 598ceeef-0f46-fff1-8528-45c12e112612
* Content: [Get started with Remote Desktop on Mac](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-mac)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by imcasablanca** [comment]
Same problem here, same credential format. Any update?

**Comment by imcasablanca** [comment]
It seems to be working without the "Network Level Authentication".

**Comment by Arash-Sabet** [comment]
I have the same problem too!

**Comment by EscapeLife** [comment]
I have the same problem too!

**Comment by tnagels** [comment]
> It seems to be working without the "Network Level Authentication".

I can confirm this works.

**Comment by Wenyi-Jhang** [comment]
I have the same problem too!

**Comment by knuth** [comment]
beta version 10.2.13(1593) has the same issue
