### ISSUE TITLE
Azure Activity Directory

### ISSUE THREAD

**Issue by chester23491** [MicrosoftDocs/windowsserverdocs#1965]
There is no "Azure Activity Directory" product at Microsoft. It should be called "Azure Active Directory".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5211e91c-a9a6-119e-8cc9-f4638d53c895
* Version Independent ID: 47c3a65d-d77a-1246-6863-f46f616c5f50
* Content: [Windows Admin Center Case Studies](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/understand/case-studies)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/understand/case-studies.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/understand/case-studies.md)
* Product: **windows-server-threshold**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by chester23491** [comment]
Anyone change this?

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by chester23491** [comment]
Still not corrected after 3 years… 🙈😂🤦‍♂️
