### ISSUE TITLE
Supported for FSMO role holder?

### ISSUE THREAD

**Issue by StrandFC** [MicrosoftDocs/windowsserverdocs#1967]
What about if the DC being replicated holds all FSMO roles? Still supported?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56104821-a5aa-3f9b-abdd-a5055e9d4b3f
* Version Independent ID: 9ccca97a-2089-6197-95fb-227e431683d2
* Content: [Support for using Hyper-V Replica for virtualized domain controllers](https://docs.microsoft.com/en-au/windows-server/identity/ad-ds/get-started/virtual-dc/support-for-using-hyper-v-replica-for-virtualized-domain-controllers)
* Content Source: [WindowsServerDocs/identity/ad-ds/get-started/virtual-dc/Support-for-using-Hyper-V-Replica-for-virtualized-domain-controllers.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/get-started/virtual-dc/Support-for-using-Hyper-V-Replica-for-virtualized-domain-controllers.md)
* Product: **windows-server-threshold**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
Guidance for FSMO role placement can be found in the support article below.

https://support.microsoft.com/help/223346/fsmo-placement-and-optimization-on-active-directory-domain-controllers

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
