### ISSUE TITLE
No issue from my Production Environment

### ISSUE THREAD

**Issue by milivhann** [MicrosoftDocs/windowsserverdocs#1969]
The Only I want to say is that Yod did a GREAT JOB it helps me monitr all of my Server in a one glance GOD BLESS YOU a great app you did YAHOOO!!! I can even connect remotely together with my DirectAccess gee what a great WEB you made I give it thumbs up or HI5 AHAHAHAHA!!! Thank you guys!!1 You are GURU!!! tnx you very much this is much better than RSAT i recently using but everything is A OKAY ILOVE IT GOD BLESS YOU ALL YOU HAVE GREAT MINDS!!! MARAMING SALAMAT!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc4cb072-7157-55b4-dbe1-c5723d2873b3
* Version Independent ID: 70a3605d-6d21-5719-b661-6023bad96627
* Content: [Windows Admin Center Overview](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/overview)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/overview.md)
* Product: **windows-server-threshold**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by milivhann** [comment]
I LOVE WAC "WindowsAdminCenter" Yeahhhhhhh!!! NICE!!!!

**Comment by IngridAtMicrosoft** [comment]
#please-close
