### ISSUE TITLE
Syntax example error

### ISSUE THREAD

**Issue by zjunsen** [MicrosoftDocs/windowsserverdocs#1970]
Add-DnsServerQueryResolutionPolicy -Name "RestOfWorldPolicy" -Action ALLOW --ZoneScope "DublinZoneScope,1;SeattleZoneScope,1" -ZoneName "contosogiftservices.com" -ProcessingOrder 5
This sentence is unexecutable and will report an error, stating "Parameter "--ZoneScope" is not a ValidateSet attribute.
The set "AND, OR". Please provide a parameter in this collection and retry this command"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a13dbc48-6366-326b-b108-b604b1440823
* Version Independent ID: b455c4c2-558e-7b56-8c52-7be8daae53b5
* Content: [Use DNS Policy for Intelligent DNS Responses Based on the Time of Day](https://docs.microsoft.com/en-us/windows-server/networking/dns/deploy/dns-tod-intelligent)
* Content Source: [WindowsServerDocs/networking/dns/deploy/dns-tod-intelligent.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/dns/deploy/dns-tod-intelligent.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by dknappettmsft** [comment]
Thanks for the feedback. This has been corrected and the changes should be visible in the next couple of hours.

#please-close
