### ISSUE TITLE
Fully customizable resolution

### ISSUE THREAD

**Issue by gy6221** [MicrosoftDocs/windowsserverdocs#1972]
Is it possible to let user to specify the width/height to use in the RDP session instead of select a pre-defined one in the drop down list? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45d9f311-2994-948d-ad91-f5c7370d73ec
* Version Independent ID: 5f978676-6f53-3f2d-fabb-3554027edbcc
* Content: [Get started with Remote Desktop on Android](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-android)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-android.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-android.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by holyavengerone** [comment]
Same here.

**Comment by IngridAtMicrosoft** [comment]
#please-close
