### ISSUE TITLE
Problems with RDP Client on MAC

### ISSUE THREAD

**Issue by JZdziech** [MicrosoftDocs/windowsserverdocs#1973]
Hi
Was working one day very Happy with the RDP Client for my new mac in my office. The first day all working fine. Since yesterday i am unable to connect all Desktops, i was able to connect til the problems started. Also i am unable to connect different internal url's from our company, which worked also very well the first day.
I have nothing changed on my mac.
When i deinstall the rdp Client, i am able to connect the url's they i am unable to connect with the rdp client.
After reinstall is it no more possible. Also the connections to the windows Server and my Notebook dosnt work any more.
This Problem drives me Crazy.
I have installed the latest mojave on my mac.
i tried to change the network from the internal to an external and connect thru vpn.
Maybe someone have the same problem or know a good solution

Kindly Regards
Jacek Zdziech

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dca80301-5517-3479-c79f-96c7e5e3f4eb
* Version Independent ID: f6c2df89-25dc-2d34-ef78-36cbadb4031b
* Content: [What's new for Remote Desktop on Mac?](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/mac-whatsnew)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/mac-whatsnew.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/mac-whatsnew.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
#please-close
