### ISSUE TITLE
this is issue

### ISSUE THREAD

**Issue by zjunsen** [MicrosoftDocs/windowsserverdocs#1984]
PS C:\Users\Administrator&gt; Get-DnsServerQueryResolutionPolicy -ZoneName "basehome.com.cn" -ComputerName "Primary-DNS" | Add-DnsServerQueryResolutionPolicy -ZoneName "basehome.com.cn"
Add-DnsServerQueryResolutionPolicy : parameter error。
Position line :1 character: 94
+ ... mary-DNS" | Add-DnsServerQueryResolutionPolicy -ZoneName "basehome.co ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (PS_DnsServerQueryResolutionPolicy:root/Microsoft/...esolutionPolicy) [
   Add-DnsServerQueryResolutionPolicy]，CimException
    + FullyQualifiedErrorId : WIN32 87,Add-DnsServerQueryResolutionPolicy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97f9525b-1c18-6d19-64f2-86226aa6ce93
* Version Independent ID: abeb8d81-a426-5b0e-1786-0e7709ea2603
* Content: [Use DNS Policy for Geo-Location Based Traffic Management with Primary-Secondary Deployments](https://docs.microsoft.com/en-us/windows-server/networking/dns/deploy/primary-secondary-geo-location)
* Content Source: [WindowsServerDocs/networking/dns/deploy/primary-secondary-geo-location.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/dns/deploy/primary-secondary-geo-location.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by zjunsen** [comment]
PS C:\Users\Administrator> Get-DnsServerQueryResolutionPolicy -ZoneName "basehome.com.cn" -ComputerName "primary-dns"

Name              ProcessingOrder IsEnabled Action
----              --------------- --------- ------
ChengduPolicy     1               True      Allow
BeijingPolicy     2               True      Allow
RestOfWorldPolicy 3               True      Allow

**Comment by Adam-Driver** [comment]
Was this issue ever looked in to, have the same issue.

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by Sloanstar** [comment]
This is still an issue. When passing a Server Policy Object to Add-DnsServerQueryResolutionPolicy the command bombs out with error 87, invalid parameter. Apparently since at least 2018.... Issues stay open until they are fixed, that way people know they are issues. You can merge duplicates onto a master issue.... but issues stay open until they are fixed.
