### ISSUE TITLE
Pictures missing

### ISSUE THREAD

**Issue by jakob-schaefer** [MicrosoftDocs/windowsserverdocs#1985]
There are images missing in this article. For example at 1.2: autonomous mode:
...The following image shows how you might deploy autonomous WSUS servers in a branch office environment:
No image here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa4be2a-4045-4135-353a-ed882ada9402
* Version Independent ID: c43f3896-9f9b-2754-9b5d-d73f9650592b
* Content: [Plan Your WSUS Deployment](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/plan/plan-your-wsus-deployment)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/plan/plan-your-wsus-deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/plan/plan-your-wsus-deployment.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
#please-close
