### ISSUE TITLE
Net command Syntaxis

### ISSUE THREAD

**Issue by frailefeijoo** [MicrosoftDocs/windowsserverdocs#1990]
Where the "net" commandline for W10 versions??

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 8a79c2cc-8610-e611-b452-f72927d05031
* Version Independent ID: 94549755-e1e2-b092-743c-625ebde5943b
* Content: [Windows Commands](https://docs.microsoft.com/es-es/windows-server/administration/windows-commands/windows-commands)
* Content Source: [WindowsServerDocs/administration/windows-commands/windows-commands.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/windows-commands.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by stefan-johansson-hem** [comment]
I miss this content too, does anyone at Microsoft even check this page?
