### ISSUE TITLE
Plan Networking

### ISSUE THREAD

**Issue by heimiro** [MicrosoftDocs/windowsserverdocs#1992]
Should not be more detailed information about networking setup for Always On VPN, missing diagram for network adapters, static routing, how to configure and plan for allowing to set client ip subnet based on user/device group in Active Directory .e.t.c

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5e3fad1-d6be-30ec-1555-4eed3041d470
* Version Independent ID: 7c6dd6fd-9171-19b6-f0eb-9291edd07fa6
* Content: [Plan the Always On VPN Deployment](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-planning)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-planning.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-planning.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by dcaddick** [comment]
+1

**Comment by tmaguire** [comment]
+1

**Comment by gerane** [comment]
+1

**Comment by IngridAtMicrosoft** [comment]
#please-close
