### ISSUE TITLE
Allow web-client only for users

### ISSUE THREAD

**Issue by Mogaba** [MicrosoftDocs/windowsserverdocs#1993]
Is it possible to configure RDS-server to disable connections through regular rdp-clients to users so that they can use web-client only? And to allow both to admins?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Product: **windows-server-threshold**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by dgnice** [comment]
Use Applocker for disable tse connections :

My XML for rules :

<AppLockerPolicy Version="1">
  <RuleCollection Type="Appx" EnforcementMode="AuditOnly">
    <FilePublisherRule Id="57f076e9-b5a7-44ce-95f0-20285297fea8" Name="Toutes les applications empaquetées signées" Description="Permet aux membres du groupe Tout le monde d’exécuter les applications empaquetées qui sont signées." UserOrGroupSid="S-1-1-0" Action="Deny">
      <Conditions>
        <FilePublisherCondition PublisherName="*" ProductName="*" BinaryName="*">
          <BinaryVersionRange LowSection="0.0.0.0" HighSection="*" />
        </FilePublisherCondition>
      </Conditions>
    </FilePublisherRule>
  </RuleCollection>
  <RuleCollection Type="Dll" EnforcementMode="NotConfigured" />
  <RuleCollection Type="Exe" EnforcementMode="Enabled">
    <FilePathRule Id="0181cf77-b411-494b-ae1d-5790bacf7d8b" Name="%SYSTEM32%\USERINIT.EXE" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions>
        <FilePathCondition Path="%SYSTEM32%\USERINIT.EXE" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="073d7f05-394b-4698-978b-59eee1120e19" Name="Tous les fichiers" Description="Permet aux membres du groupe Administrateurs local d’exécuter toutes les applications." UserOrGroupSid="S-1-5-32-544" Action="Allow">
      <Conditions>
        <FilePathCondition Path="%OSDRIVE%\*" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="0863dbb4-6078-4d4a-b276-e7f2118f4603" Name="%SYSTEM32%\TSTHEME.EXE" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions>
        <FilePathCondition Path="%SYSTEM32%\TSTHEME.EXE" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="0c1065d4-f63b-4b8d-97db-74dbbd479c77" Name="%SYSTEM32%\DLLHOST.EXE" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions>
        <FilePathCondition Path="%SYSTEM32%\DLLHOST.EXE" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="111fe08a-a107-4e16-987c-05cab89ffa86" Name="%SYSTEM32%\DWM.EXE" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions>
        <FilePathCondition Path="%SYSTEM32%\DWM.EXE" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="1b6d3dfb-ad69-4ad7-85af-e4d39012c875" Name="%OSDRIVE%\*" Description="" UserOrGroupSid="S-1-5-32-544" Action="Allow">
      <Conditions>
        <FilePathCondition Path="%OSDRIVE%\*" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="254e9ccb-8f51-4860-a074-88199db4c563" Name="%SYSTEM32%\SETHC.EXE" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions>
        <FilePathCondition Path="%SYSTEM32%\SETHC.EXE" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="4344e3b6-949e-4ce3-b21c-ecf2a1764ede" Name="%WINDIR%\SPLWOW64.EXE" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions>
        <FilePathCondition Path="%WINDIR%\SPLWOW64.EXE" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="458df1e6-0483-431e-bd6b-cb7a915ce13f" Name="%SYSTEM32%\SESSIONMSG.EXE" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions>
        <FilePathCondition Path="%SYSTEM32%\SESSIONMSG.EXE" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="49ae31bf-4e08-49d1-aed2-4e4b86fe6ecf" Name="%SYSTEM32%\SVCHOST.EXE" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions>
        <FilePathCondition Path="%SYSTEM32%\SVCHOST.EXE" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="732798b0-ccdb-4213-8313-92b88140aef9" Name="%SYSTEM32%\SIHOST.EXE" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions>
        <FilePathCondition Path="%SYSTEM32%\SIHOST.EXE" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="90045f57-888f-48aa-bdd5-7d6abcaf5cc7" Name="%SYSTEM32%\RUNONCE.EXE" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions>
        <FilePathCondition Path="%SYSTEM32%\RUNONCE.EXE" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="c11f1b09-54ee-4da6-a16c-a5834c949dd5" Name="%SYSTEM32%\RDPSA.EXE" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions>
        <FilePathCondition Path="%SYSTEM32%\RDPSA.EXE" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="c2a30e1a-0a10-477c-b0af-c78979b7ff54" Name="%SYSTEM32%\RDPSHELL.EXE" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions>
        <FilePathCondition Path="%SYSTEM32%\RDPSHELL.EXE" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="c5368472-7b22-4e9c-8c75-024230c06a7c" Name="%SYSTEM32%\TASKHOSTW.EXE" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions>
        <FilePathCondition Path="%SYSTEM32%\TASKHOSTW.EXE" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="c6788372-3096-429e-84fa-dbc322d101cc" Name="%SYSTEM32%\ATBROKER.EXE" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions>
        <FilePathCondition Path="%SYSTEM32%\ATBROKER.EXE" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="c6c3e1c4-5e64-48eb-8e67-60d2d3ec6685" Name="D:\LOGICIEL\*" Description="" UserOrGroupSid="S-1-5-21-2510480279-3485226251-3631845024-513" Action="Allow">
      <Conditions>
        <FilePathCondition Path="D:\LOGICIEL\*" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="c793bc78-125f-47d2-a48a-a5449cbb7243" Name="%SYSTEM32%\SEARCHPROTOCOLHOST.EXE" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions>
        <FilePathCondition Path="%SYSTEM32%\SEARCHPROTOCOLHOST.EXE" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="db599c76-1bbb-45f4-ab46-6713c733b898" Name="%OSDRIVE%\*" Description="" UserOrGroupSid="S-1-5-21-2510480279-3485226251-3631845024-1106" Action="Allow">
      <Conditions>
        <FilePathCondition Path="%OSDRIVE%\*" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="de991bb0-8103-4a94-a93d-b1147eb74b0d" Name="%SYSTEM32%\RDPCLIP.EXE" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions>
        <FilePathCondition Path="%SYSTEM32%\RDPCLIP.EXE" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="e06fdde8-da5d-47c0-a0eb-b10ce3ed2636" Name="%SYSTEM32%\RDPSAPROXY.EXE" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions>
        <FilePathCondition Path="%SYSTEM32%\RDPSAPROXY.EXE" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="e2d0f72c-aaf0-4218-adfb-e8ad18279c9a" Name="%SYSTEM32%\RDPINIT.EXE" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions>
        <FilePathCondition Path="%SYSTEM32%\RDPINIT.EXE" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="ee2ccc0c-87ff-4c79-8bc0-83abaadf3b74" Name="%SYSTEM32%\RUNTIMEBROKER.EXE" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions>
        <FilePathCondition Path="%SYSTEM32%\RUNTIMEBROKER.EXE" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="f1035f65-a030-4346-972c-0182fb066250" Name="%SYSTEM32%\RUNDLL32.EXE" Description="" UserOrGroupSid="S-1-1-0" Action="Allow">
      <Conditions>
        <FilePathCondition Path="%SYSTEM32%\RUNDLL32.EXE" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="1f607ee9-499c-4405-b3ba-cfae872a0ae3" Name="D:\*" Description="" UserOrGroupSid="S-1-5-32-544" Action="Allow">
      <Conditions>
        <FilePathCondition Path="D:\*" />
      </Conditions>
    </FilePathRule>
  </RuleCollection>
  <RuleCollection Type="Msi" EnforcementMode="AuditOnly">
    <FilePublisherRule Id="b9fe11a5-8045-411e-b05d-d637cca811dd" Name="Tous les fichiers Windows Installer signés numériquement" Description="Permet aux membres du groupe Tout le monde d’exécuter les fichiers Windows Installer signés numériquement." UserOrGroupSid="S-1-1-0" Action="Deny">
      <Conditions>
        <FilePublisherCondition PublisherName="*" ProductName="*" BinaryName="*">
          <BinaryVersionRange LowSection="0.0.0.0" HighSection="*" />
        </FilePublisherCondition>
      </Conditions>
    </FilePublisherRule>
    <FilePathRule Id="64ad46ff-0d71-4fa0-a30b-3f3d30c5433d" Name="(Règle par défaut) Tous les fichiers Windows Installer" Description="Permet aux membres du groupe Administrateurs local d’exécuter tous les fichiers Windows Installer." UserOrGroupSid="S-1-5-32-544" Action="Allow">
      <Conditions>
        <FilePathCondition Path="*.*" />
      </Conditions>
    </FilePathRule>
    <FilePathRule Id="c1c6c80e-9d87-4b7d-ae07-3fb751d8ed45" Name="Tous les fichiers Windows Installer se trouvant dans le dossier %systemdrive%\Windows\Installer" Description="Permet aux membres du groupe Tout le monde d’exécuter tous les fichiers Windows Installer se trouvant dans le dossier %systemdrive%\Windows\Installer." UserOrGroupSid="S-1-1-0" Action="Deny">
      <Conditions>
        <FilePathCondition Path="%WINDIR%\Installer\*" />
      </Conditions>
    </FilePathRule>
  </RuleCollection>
  <RuleCollection Type="Script" EnforcementMode="AuditOnly">
    <FilePathRule Id="ed97d0cb-15ff-430f-b82c-8d7832957725" Name="(Règle par défaut) Tous les scripts" Description="Permet aux membres du groupe Administrateurs local d’exécuter tous les scripts." UserOrGroupSid="S-1-5-32-544" Action="Allow">
      <Conditions>
        <FilePathCondition Path="*" />
      </Conditions>
    </FilePathRule>
  </RuleCollection>
</AppLockerPolicy>

**Comment by IngridAtMicrosoft** [comment]
#please-close
