### ISSUE TITLE
Cannot Install windows update on the server

### ISSUE THREAD

**Issue by akramadel** [MicrosoftDocs/windowsserverdocs#1995]
Hi,
I've tried to install KB4025334 update on windows server 2016 using the independent installer, it is giving me an error "the update is not applicable to your computer". and when I try to run "Install-Module -Name PowerShellGet -Force" in power shell it is showing an error "PackageManagement\Install-Package : No match was found for the specified search criteria and module name
'PowerShellGet'."  I tried on other windows 2016 server has all updates up to date but same error messages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Product: **windows-server-threshold**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by almalos** [comment]
I'm facing the same issue on a newly deployed 2016 server.

**Comment by IngridAtMicrosoft** [comment]
#please-close
