### ISSUE TITLE
Issue or typing error ?

### ISSUE THREAD

**Issue by ggbce** [MicrosoftDocs/windowsserverdocs#1997]
I observed in this document that using WS2019 KMS licence can be done on Windows Server 2012R2, 2016 or 2019 KMS host... But allow to activate Windows 8.1 and more recent only. Windows 7 is not listed. If I follow some Microsoft forum, many people have problem using WS2019 KMS licence, but no one tell Windows 7 is no more supported... And some tell Windows 7/2008R2 KMS client activation still working fine. Please confirm is document supported and "not supported" to ensure the right answer to everyone. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70e8d8e6-a5fc-9089-5849-a6eb1022d7ca
* Version Independent ID: 6a1b4ab9-8b3d-3cb6-915f-c53e61d39a1d
* Content: [Windows Server 2019 Activation](https://docs.microsoft.com/en-us/windows-server/get-started-19/activation-19)
* Content Source: [WindowsServerDocs/get-started-19/activation-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/activation-19.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Geogboe** [comment]
For anyone else looking at this, the docs have been updated to include Windows 7 and Server 2008. See this pull request. https://github.com/MicrosoftDocs/windowsserverdocs/commit/f2d5ae09d5fdc6cd7a0a00af5f6f70dbf18d7e50#diff-a196d2273ce2b285bb77da1eb8b4b627

I think it's safe to confirm that Windows 7 and 2008 are supported by this VL

**Comment by sasanmcp** [comment]
the support matrix needs to be aligned in all links below:
https://docs.microsoft.com/en-us/windows-server/get-started-19/activation-19
https://docs.microsoft.com/en-us/windows-server/get-started/server-2016-activation
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/jj134256(v%3dws.11)#12-plan-for-key-management-services-activation
the last one, although it says the link won't be updated we can see it has been recently updated indeed.
