### ISSUE TITLE
More Guidance

### ISSUE THREAD

**Issue by RonaldCarter** [MicrosoftDocs/windowsserverdocs#2001]
With Nested Mirror Accelerated Parity using SSD + HDD is the recommendation still 20% usable storage? so for 6Tb usable HDD space I would need 1.2Tb SSD mirror?
With the Nested Mirror part of a nested mirror accelerated parity is that always a 2 way mirror or does it scale to 3 way?
In my scenerio above of needing 1.2Tb SSD usabale space what would be the recommended size of the SSDs assuming a limit of 4 per server

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddf99f5c-63da-b6cf-120b-ff471bc1d23d
* Version Independent ID: 352986ad-3c3d-8710-9c25-1dfa83e04899
* Content: [Nested resiliency for Storage Spaces Direct](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/nested-resiliency#frequently-asked-questions)
* Content Source: [WindowsServerDocs/storage/storage-spaces/nested-resiliency.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/nested-resiliency.md)
* Product: **windows-server-threshold**
* GitHub Login: @cosmosdarwin
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#please-close
