### ISSUE TITLE
functional levels

### ISSUE THREAD

**Issue by DSPatrick** [MicrosoftDocs/windowsserverdocs#2005]
please clarify the domain and forest functional level requirements for Server 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86e4b814-7c4a-0895-2eea-667e3870053f
* Version Independent ID: 740cea70-5958-4560-617f-d9f55e7dc78d
* Content: [Windows Server 2016 Functional Levels](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/active-directory-functional-levels)
* Content Source: [WindowsServerDocs/identity/ad-ds/active-directory-functional-levels.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/active-directory-functional-levels.md)
* Product: **windows-server-threshold**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
@DSPatrick Windows Server, version 1809 is Windows Server 2019. There is no new functional level.

**Comment by DSPatrick** [comment]
I meant the minimum requirements for introducing the first 2019 domain controller. For 2016 minimum DFL needs to be 2003. I have heard but cannot confirm for 2019 minimum DFL needs to be 2008?

**Comment by DSPatrick** [comment]
The minimum DFL/FFL requirements for introducing the first domain controller (2016 or 2019) is always a hot topic in forums discussions so it would be great to have this clearly presented in this document.

**Comment by MicrosoftGuyJFlo** [comment]
@DSPatrick I spoke to the PG this morning and they are saying 2008R2 to introduce Windows Server 2019 DCs.

**Comment by DSPatrick** [comment]
Thanks for confirming. Can we add the info for 2016 and 2019 to this document?

**Comment by MicrosoftGuyJFlo** [comment]
@DSPatrick I am submitting a PR to our private repo to update this topic and add the schema change to https://docs.microsoft.com/windows-server/identity/ad-ds/deploy/schema-updates

**Comment by MicrosoftGuyJFlo** [comment]
it-server/pullrequest/13112

**Comment by MicrosoftGuyJFlo** [comment]
#please-close

**Comment by DSPatrick** [comment]
Thanks a lot for doing
