### ISSUE TITLE
A download page returns Not Found error

### ISSUE THREAD

**Issue by KexyBiscuit** [MicrosoftDocs/windowsserverdocs#201]
[Link](https://www.microsoft.com/download/details.aspx?id=41182) in [this file](https://github.com/microsoftdocs/windowsserverdocs/blob/master/`WindowsServerDocs/get-started/Migrate-Roles-and-Features.md) returns a HTTP 404 code.

**Comment by jaimeo** [comment]
I am fixing this in a separate PR.

**Comment by brianlic-msft** [comment]
@jaimeo Was this fixed? If so, I'll close this issue.

**Comment by jaimeo** [comment]
It's been...worked around. Given the uncertain status and future of the DLC, I've just deleted the link and reference to it. Go ahead and close this issue please.
