### ISSUE TITLE
Broken Links to Get-DedupStatus = 404 page

### ISSUE THREAD

**Issue by ajstadlin** [MicrosoftDocs/windowsserverdocs#2013]
https://docs.microsoft.com/en-us/powershell/module/data-deduplication/get-dedupstatus

Get-DedupStatus in Windows Server 2019 is not returning details beyond simple space saving statistics. How do we get the Last...Results details in Windows Server 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 249ee761-6eae-6551-8ede-75a98f08a3af
* Version Independent ID: 22b3d75e-2759-2043-cc00-b04cd5c82d23
* Content: [Running Data Deduplication](https://docs.microsoft.com/en-us/windows-server/storage/data-deduplication/run#monitoring-dedup)
* Content Source: [WindowsServerDocs/storage/data-deduplication/run.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/data-deduplication/run.md)
* Product: **windows-server-threshold**
* GitHub Login: @wmgries
* Microsoft Alias: **wgries**

**Comment by ajstadlin** [comment]
The 404 page suggestions worked for me just now.  For example:

[https://docs.microsoft.com/en-us/powershell/module/deduplication/get-dedupstatus?view=win10-ps](https://docs.microsoft.com/en-us/powershell/module/deduplication/get-dedupstatus?view=win10-ps)

When I received the 404 error, I must have somehow navigated to the document without the `?view=win10-ps` parameter.  I was probably in a Windows Server 2019 Help context at the time.

I suggest the suggestions page not be a big 404 error page or use a default `?view` parameter if not specified or invalid.

Thanks!

**Comment by illfated** [comment]
Thank you for following up on your own ticket with a suggested solution.

I am not sure if I understand on which page the broken URL resides, the one that results in a 404 error.

Are you starting from the page https://docs.microsoft.com/en-us/windows-server/storage/data-deduplication/run#monitoring-dedup ?

**Comment by ajstadlin** [comment]
It has been a long time, so I do not remember where the "https://docs.microsoft.com/en-us/powershell/module/data-deduplication/get-dedupstatus" link came from.  I am pretty sure I did not type it in, and it was through either a Windows Help method or a docs.microsoft.com referral (not from a search engine).  It is probable that this has been fixed since 2018.  Thank you for the updated working link.  In the future, if I find a broken link, I will make sure I include the original source page or context with the broken link.

**Comment by ajstadlin** [comment]
Actually, I notice the source page is listed as "Content Source" appended to my original feedback.

When I click on the "Get-DedupStatus" link in the "Job successes" or "Optimization rates" first paragraphs, it now redirects to: *Data Protection Manager (DPM)"
`https://docs.microsoft.com/en-us/previous-versions/system-center/system-center-2012-R2/hh758173(v=sc.12)`

Maybe that was the broken link before?  

![Get-DedupStatus_BrokenLink](https://user-images.githubusercontent.com/14024430/98379071-dd598b80-2014-11eb-8940-fd9344575748.png)

**Comment by illfated** [comment]
Thank you for your update. That is welcome news. Your suggestion, that it could have been a 404 link before, makes sense.

Do you think we need to do anything more about this ticket, like find any corrections to add to the page, or is it ready to be closed?

**Comment by IngridAtMicrosoft** [comment]
#please-close
