### ISSUE TITLE
No documentation on the output of compression state

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/windowsserverdocs#2014]
According to the documentation: " If used without parameters, compact displays the compression state of the current directory and the files it contains."

But what exactly does the different columns in the output mean?
In the example below there seem to be a column to the right of the compression info which can be blank, l or X, what does this mean?

For example:
PS C:\Windows\System32&gt; compact
 Listing C:\Windows\System32\
 New files added to this directory will not be compressed.
        0 :         0 = 1,0 to 1   0409
      308 :       308 = 1,0 to 1   @AudioToastIcon.png
      450 :       450 = 1,0 to 1   @BackgroundAccessToastIcon.png
      199 :       199 = 1,0 to 1   @bitlockertoastimage.png
    14791 :      4096 = 3,6 to 1 l @edptoastimage.png
      330 :       330 = 1,0 to 1   @EnrollmentToastIcon.png
      563 :       563 = 1,0 to 1   @language_notification_icon.png
      483 :       483 = 1,0 to 1   @optionalfeatures.png
      404 :       404 = 1,0 to 1   @VpnToastIcon.png
    15106 :      4096 = 3,7 to 1 l @WiFiNotificationIcon.png
   195443 :    106496 = 1,8 to 1 l @windows-hello-V4.1.gif
   188416 :     77824 = 2,4 to 1 l aadauthhelper.dll
   670720 :    339968 = 2,0 to 1 X aadcloudap.dll
    66048 :     28672 = 2,3 to 1 l aadjcsp.dll
  1371136 :    634880 = 2,2 to 1 X aadtb.dll
   143264 :     61440 = 2,3 to 1 l aadWamExtension.dll
   255904 :    114688 = 2,2 to 1 l AboutSettingsHandlers.dll
   391680 :    155648 = 2,5 to 1 l AboveLockAppHost.dll
  3834880 :   1638400 = 2,3 to 1 l accessibilitycpl.dll
   267776 :     98304 = 2,7 to 1 l accountaccessor.dll
   434176 :    159744 = 2,7 to 1 l AccountsRt.dll
   345600 :    176128 = 2,0 to 1 X AcGenral.dll
   301568 :    139264 = 2,2 to 1 X AcLayers.dll
    11264 :      8192 = 1,4 to 1 l acledit.dll

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3df310da-3633-d25a-d982-f95ae4e0fe5b
* Version Independent ID: 4219e5f8-c228-4dee-f209-b94eba2a68b5
* Content: [compact](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/compact)
* Content Source: [WindowsServerDocs/administration/windows-commands/compact.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/compact.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
#please-close
