### ISSUE TITLE
Missing example in the Azure AD style resource specification in scope parameter Section

### ISSUE THREAD

**Issue by frostygoth** [MicrosoftDocs/windowsserverdocs#2018]
Text reads " &lt; create a valid sample request&gt; " , which I assume is a place holder for a sample request. Should probably be replaced with a valid sample request.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7899bfcb-2e9c-2738-5e7f-468a6eb643ce
* Version Independent ID: 482cc911-c7ef-c680-b6ff-f634530b1424
* Content: [What's new in Active Directory Federation Services for Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server#azure-ad-style-resource-specification-in-scope-parameter)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
