### ISSUE TITLE
Graphics are pretty much unusable when viewing the website in dark mode. 

### ISSUE THREAD

**Issue by frostygoth** [MicrosoftDocs/windowsserverdocs#2019]
I use docs.microsoft.com in dark mode and images with black text and a transparent background can't be read. Minor issue but very inconvenient. See section located at --&gt; https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-scenarios-for-developers#native-client-to-web-api for an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3824263-5c49-03e9-9063-b44b1c636540
* Version Independent ID: 31684400-9100-b442-8957-c1300ad35cb8
* Content: [AD FS Scenarios for Developers](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-scenarios-for-developers)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/AD-FS-Scenarios-for-Developers.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/AD-FS-Scenarios-for-Developers.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
