### ISSUE TITLE
2019 CALs for 2016 license/host Server

### ISSUE THREAD

**Issue by Rombecchi** [MicrosoftDocs/windowsserverdocs#2022]
Can I install Windows Server 2019 RDS CAL on a Windows Server 2016 license+host server ?
Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d69b9ea-9672-c267-03e4-a34bf105d31b
* Version Independent ID: bddcfc0f-77d6-ff1c-9af3-c5b3ad11ba63
* Content: [License your RDS deployment with client access licenses (CALs)](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-client-access-license)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-client-access-license.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-client-access-license.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by sgsledz** [comment]
Hello,

Anything already known in this matter ??

**Comment by Rombecchi** [comment]
Nope

**Comment by philkloose** [comment]
Still nothing?  Has anyone tried this?

**Comment by JtheBAB** [comment]
It is not possible. As usual you need a Server 2019 to install 2019 RDS CAL

**Comment by gilbertovm** [comment]
But that will allow the RDS licensing server provision licenses to users and devices to access 2016, 2012, 2008 servers right? it is just for the license installartion process.

**Comment by tsexton2** [comment]
A little late to the party but you **can** run 2019 licenses on a 2016 server. If you call the Microsoft Clearinghouse they will automatically downgrade them to your host level. 

Microsoft allows up to a two version rollback - i.e. 2019 will work all the way back to a 2012 host/license server for RDP licensing.

**Comment by IngridAtMicrosoft** [comment]
#please-close
