### ISSUE TITLE
Relying party trusts?

### ISSUE THREAD

**Issue by xXxOlivierxXx** [MicrosoftDocs/windowsserverdocs#2025]
Are relying party trusts not included in the backups created by rapid restore? I just noticed in 2 different adfs environments that everything is restored except for relying party trusts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a58b49ca-ae39-132e-adbd-6766a8019a89
* Version Independent ID: fdf31266-bc9e-8880-0073-00cf1cad2897
* Content: [AD FS Rapid Restore Tool](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/ad-fs-rapid-restore-tool#what-is-backed-up)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/AD-FS-Rapid-Restore-Tool.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/AD-FS-Rapid-Restore-Tool.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
