### ISSUE TITLE
second factor authenticator

### ISSUE THREAD

**Issue by jv-public** [MicrosoftDocs/windowsserverdocs#2031]
There is a free second factor authenticator https://www.securemfa.com/ for ADFS servers. It provides multi-factor authentication (MFA) using a Time-Based One-Time Password (TOTP) Algorithm which is based on RFC6238. Using this MFA provider users can use authenticator applications like Microsoft Authenticator , Google Authenticator , Symantec VIP etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8348816f-fc89-4d25-d077-24cd86cdd38c
* Version Independent ID: 5f49fb4b-72da-f818-e87d-8fe002fc8ddc
* Content: [Configure Additional Authentication Methods for AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-additional-authentication-methods-for-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-Additional-Authentication-Methods-for-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-Additional-Authentication-Methods-for-AD-FS.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by cloudinnovating** [comment]
Thank you for sharing this!

**Comment by piaudonn** [comment]
This has been added.

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
