### ISSUE TITLE
free mfa module

### ISSUE THREAD

**Issue by jv-public** [MicrosoftDocs/windowsserverdocs#2032]
There is a free second factor authenticator https://www.securemfa.com/ for ADFS servers. It provides multi-factor authentication (MFA) using a Time-Based One-Time Password (TOTP) Algorithm which is based on RFC6238. Using this MFA provider users can use authenticator applications like Microsoft Authenticator , Google Authenticator , Symantec VIP etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68fadc64-03c2-b05c-c208-bc3ae4eaacc6
* Version Independent ID: ec2807b9-395b-db17-7bcc-ccd82d5a0bdc
* Content: [Multi-factor authentication and external authentication providers customization](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/multi-factor-authentication-and-external-auth-providers-customization)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Multi-factor-authentication-and-external-auth-providers-customization.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Multi-factor-authentication-and-external-auth-providers-customization.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
