### ISSUE TITLE
Mistake on step 2

### ISSUE THREAD

**Issue by rwvoss** [MicrosoftDocs/windowsserverdocs#2035]
The command: repadmin /showrepl * /csv &gt;showrepl.csv 
The &gt; got replaced by the character entity reference.  Should be repadmin /showrepl * /csv &gt; showrepl.csv 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 190492f7-b2ce-d6ba-cfc4-eac02663c68b
* Version Independent ID: f8271a41-49ff-5236-92ba-236cb8442b3c
* Content: [Troubleshooting Active Directory Replication Problems](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/troubleshoot/troubleshooting-active-directory-replication-problems)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/troubleshoot/Troubleshooting-Active-Directory-Replication-Problems.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/manage/troubleshoot/Troubleshooting-Active-Directory-Replication-Problems.md)
* Product: **windows-server-threshold**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by lizap** [comment]
Fixed - thanks!
