### ISSUE TITLE
Hyper-V 2019/2016

### ISSUE THREAD

**Issue by AlexSchwerzmann** [MicrosoftDocs/windowsserverdocs#2041]
Hi 
Is there anything you can tell about changes in CSV-behaviour since 2016? We are specially interested into changes within the Owner Node logic? Till 2012 it was a problem for the whole HA-Setup if the CSV Owner Node crashed because the other nodes were not able to access the storage anymore (as the owner disappeared). Is this solved with 2016 or 2019?
Thanks
Alex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b21de163-2f54-75bb-de9f-c3df79a1eb96
* Version Independent ID: fa962719-758d-a7b6-1ea7-f8874f4b1242
* Content: [Use Cluster Shared Volumes in a failover cluster](https://docs.microsoft.com/en-us/windows-server/failover-clustering/failover-cluster-csvs)
* Content Source: [WindowsServerDocs/failover-clustering/failover-cluster-csvs.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/failover-cluster-csvs.md)
* Product: **windows-server-threshold**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#please-close
