### ISSUE TITLE
/save doesn't save /mt switch

### ISSUE THREAD

**Issue by jelatta** [MicrosoftDocs/windowsserverdocs#2042]
You can edit the RCJ job file and load it though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af94ad3b-6603-2b26-1010-073fb2c07c2a
* Version Independent ID: 09fd75d0-8624-5cfd-5122-b40ba50055f9
* Content: [robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by egallagh** [comment]
What OS are you running? Thanks.

**Comment by jelatta** [comment]
Tested on server 2016

**Comment by egallagh** [comment]
According to the documentation, the /MT parameter is valid only on Server 2008 R2 and Windows 7

**Comment by jelatta** [comment]
Yeah wasn't sure if it just want updated though.

**Comment by IngridAtMicrosoft** [comment]
#please-close
