### ISSUE TITLE
Windows Server 2019 Essentials | ISO de 64 bits

### ISSUE THREAD

**Issue by FARRUQUITO-BCN** [MicrosoftDocs/windowsserverdocs#2044]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38acb737-4d4d-97a3-1f8c-4c36f4429be9
* Version Independent ID: 17a853fc-e6aa-108e-95eb-50753ef13ade
* Content: [What's New in Windows Server, version 1809](https://docs.microsoft.com/en-us/windows-server/get-started/whats-new-in-windows-server-1809)
* Content Source: [WindowsServerDocs/get-started/whats-new-in-windows-server-1809.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/whats-new-in-windows-server-1809.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by doctordns** [comment]
Not sure what the feedback is here?
