### ISSUE TITLE
This is error for Windows Server 2019

### ISSUE THREAD

**Issue by zjunsen** [MicrosoftDocs/windowsserverdocs#2045]
Add-HgsAttestationTpmHost -Path &lt;Path&gt;&lt;Filename&gt;.xml -Name &lt;HostName&gt; -PolicyVersion v1
this command is error for windows server 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 205351f5-e94b-81d2-ab07-d675866feceb
* Version Independent ID: 9ac7c7d8-a33c-6404-4372-9d0341549230
* Content: [Capture TPM-mode information required by HGS](https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-tpm-trusted-attestation-capturing-hardware)
* Content Source: [WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-tpm-trusted-attestation-capturing-hardware.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-tpm-trusted-attestation-capturing-hardware.md)
* Product: **windows-server-threshold**
* GitHub Login: @rpsqrd

**Comment by zjunsen** [comment]
PS C:\Users\Administrator> Add-HgsAttestationTpmHost -Path c:\hyper-v01.xml -Name "hyper-v01" -PolicyVersion v1
Add-HgsAttestationTpmHost : Certificate with thumbprint 7A4912AA2359375DFECF645BE980BB5FA68C13ED cannot be trusted
because of error UntrustedRoot. For help, refer to https://go.microsoft.com/fwlink/?LinkId=734845
At line:1 char:1
+ Add-HgsAttestationTpmHost -Path c:\hyper-v01.xml -Name "hyper-v01" -P ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-HgsAttestationTpmHost], AttestationManagementException
    + FullyQualifiedErrorId : Microsoft.Windows.RemoteAttestation.Server.PowerShell.AddHgsAttestationTpmHost

**Comment by rpsqrd** [comment]
Hi @zjunsen, thanks for reporting this! The error you are seeing indicates that the endorsement key certificate (also called the manufacturer's certificate) from the TPM is not trusted by the HGS server. For most servers, you can import the known, trusted TPM certificates by following the steps in [this article](https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-install-trusted-tpm-root-certificates).

Some newer servers have TPMs with different certificates not maintained in this cab file, so you would need to reach out to your OEM to get the correct endorsement certificate. Intermediate CAs should be placed in the `Cert:\LocalMachine\TrustedTPM_IntermediateCA` certificate store, while root CAs go in the `TrustedTPM_RootCA` store. We only perform a partial chain validation, so if you only add the root or intermediate CA, you should still be fine.

**Comment by zjunsen** [comment]
I want say:” If you encounter an error when adding a TPM identifier regarding an untrusted Endorsement Key Certificate (EKCert), ensure that the trusted TPM root certificates have been added<https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-install-trusted-tpm-root-certificates> to the HGS node. Additionally, some TPM vendors do not use EKCerts. You can check if an EKCert is missing by opening the XML file in an editor such as Notepad and checking for an error message indicating no EKCert was found. If this is the case, and you trust that the TPM in your machine is authentic, you can use the -PolicyVersion v1 parameter beginning with Windows Server 2019, or the -Force parameter in Windows Server 2016, to add the host identifier to HGS by using v1 attestation. The CI policy and the TPM baseline need to be created by using the same attestation version.” Try “-PolicyVersion v1” is error

Jason Zhang

发件人: Ryan Puffer <notifications@github.com>
发送时间: 2018年12月11日 1:42
收件人: MicrosoftDocs/windowsserverdocs <windowsserverdocs@noreply.github.com>
抄送: zjunsen <zjunsen@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [MicrosoftDocs/windowsserverdocs] This is error for Windows Server 2019 (#2045)


Hi @zjunsen<https://github.com/zjunsen>, thanks for reporting this! The error you are seeing indicates that the endorsement key certificate (also called the manufacturer's certificate) from the TPM is not trusted by the HGS server. For most servers, you can import the known, trusted TPM certificates by following the steps in this article<https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-install-trusted-tpm-root-certificates>.

Some newer servers have TPMs with different certificates not maintained in this cab file, so you would need to reach out to your OEM to get the correct endorsement certificate. Intermediate CAs should be placed in the Cert:\LocalMachine\TrustedTPM_IntermediateCA certificate store, while root CAs go in the TrustedTPM_RootCA store. We only perform a partial chain validation, so if you only add the root or intermediate CA, you should still be fine.

**Comment by rpsqrd** [comment]
Which OS are you running on HGS? This is a new parameter introduced in Windows Server 2019.

**Comment by zjunsen** [comment]
I was testing this problem with HGS found in Windows Server 2019 Datacenter
This Windows Server 2019 is RTM

Jason Zhang

发件人: Ryan Puffer <notifications@github.com>
发送时间: 2018年12月13日 8:43
收件人: MicrosoftDocs/windowsserverdocs <windowsserverdocs@noreply.github.com>
抄送: zjunsen <zjunsen@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [MicrosoftDocs/windowsserverdocs] This is error for Windows Server 2019 (#2045)


Which OS are you running on HGS? This is a new parameter introduced in Windows Server 2019.

**Comment by zjunsen** [comment]
In the documentation, I saw that Windows Server 2016 uses -force, Windows Server 2019 uses -PolicyVersion v1, I try to “-PolicyVersion v1 -force” is Ok, but the documentation says：“you can use the -PolicyVersion v1 parameter beginning with Windows Server 2019, or the -Force parameter in Windows Server 2016, to add the host identifier to HGS by using v1 attestation.”

Jason Zhang

发件人: Ryan Puffer <notifications@github.com>
发送时间: 2018年12月13日 9:29
收件人: MicrosoftDocs/windowsserverdocs <windowsserverdocs@noreply.github.com>
抄送: zjunsen <zjunsen@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [MicrosoftDocs/windowsserverdocs] This is error for Windows Server 2019 (#2045)


Can you run it with -PolicyVersion v1 and -Force at the same time? If the endorsement key certificate is present but not trusted by HGS, you need to use the -Force flag to allow that host to be registered. -Force is only supported with version 1 policies, which is why you need both parameters on WS2019.

Note that it is strongly recommended that you register the EKcert root and intermediate CAs on HGS instead of using -Force. In a production environment, an EKcert which has an untrusted root could be a sign of a TPM which is not authentic.

**Comment by rpsqrd** [comment]
Okay, glad to hear it worked with both parameters. I'll update the docs to make it more clear. Thanks for bringing this to our attention!

FYI - PR is #2080

**Comment by lizap** [comment]
Closing this issue as @rpsqrd's change has been merged. Thanks!
