### ISSUE TITLE
windows 10 mount

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windowsserverdocs#2050]
I'd like some examples and a link to where to find more info

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d8c89a0-b076-8f84-8f3f-066c4690c3ef
* Version Independent ID: f119e2ee-1c14-077e-ab22-31ecfe2c8978
* Content: [mount](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mount)
* Content Source: [WindowsServerDocs/administration/windows-commands/mount.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/mount.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by mys007** [comment]
Is there a way to set different `fileaccess` for files and directories? Currently if I want to create directories then all files are made executable. See also:
https://social.technet.microsoft.com/Forums/windows/en-US/64368911-80c3-43b6-9c6a-293f409a126a/win7-nfs-client-woes-uid-mapping-amp-fileaccess?forum=w7itpronetworking
