### ISSUE TITLE
Extend coverage of this repo to Server 2019?

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/windowsserverdocs#2055]
The readme for the MicrosoftDocs/windowsserverdocs (https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/README.md) says if covers explicitly Server 2016. 

With the launch of Windows Server 2019, I'd like to see this page, and the repo, be extended to cover 2019. From my work with 2019. existing 2016 content is still valid except possibly in a few minor cases.

**Comment by lizap** [comment]
Thanks for pointing this out - hadn't looked at the readme for a long time. I've cleaned it up and added reference to 2019.

**Comment by doctordns** [comment]
I ask this because I want to start adding some 2019 content to some of these pages...

**Comment by lizap** [comment]
Fantastic!
