### ISSUE TITLE
Standard error misusage

### ISSUE THREAD

**Issue by Bertrand67** [MicrosoftDocs/windowsserverdocs#2060]
There is a bug with "reg import" command, success message is written to stderr!
try this :
reg import script.reg 2&gt;stderr.txt
script.reg content (one single line) : Windows Registry Editor Version 5.00
"The operation completed successfully." is written is stderr.txt
I hope you'll fix it quickly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f97c3a2-583c-05ec-da3d-10440e32c935
* Version Independent ID: eee69a85-9306-720e-d85b-9fb0740901b0
* Content: [reg import](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/reg-import)
* Content Source: [WindowsServerDocs/administration/windows-commands/reg-import.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/reg-import.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Bertrand67** [comment]
Confirmed on Windows 10 [version 1809 build 17763.194]

**Comment by VectorBCO** [comment]
confirmed on windows 10 1903

**Comment by Bertrand67** [comment]
Confirmed on Windows 10 [version 20H2 build 19042.572]
