### ISSUE TITLE
Group Policy Settings, Internet Explorer section

### ISSUE THREAD

**Issue by jeroenebus** [MicrosoftDocs/windowsserverdocs#2069]
In the Internet Explorer Group policy section there is a typo in the following line:

Use the back arrow in the upper left of Local Group Policy Editor to go back to the Internet Explorer level. Double-click Advanced Settings, and then adjust the settings in the subfolders as follows:

It has to be:

Use the back arrow in the upper left of Local Group Policy Editor to go back to the Internet Explorer level, then double-click Internet Settings. Double-click Advanced Settings, and then adjust the settings in the subfolders as follows:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a83e1751-011c-9add-2c0a-63159fef97da
* Version Independent ID: 119b5192-3775-f71e-579d-9ead105ed1b0
* Content: [Recommended configuration for VDI desktops](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-vdi-recommendations)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-vdi-recommendations.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-vdi-recommendations.md)
* Product: **windows-server-threshold**
* GitHub Login: @jaimeo
* Microsoft Alias: **elizapo**

**Comment by lizap** [comment]
Good catch - I've made the fix. Will close this issue when the fix publishes. Thanks!
