### ISSUE TITLE
Add-WindowsCapability : Add-WindowsCapability failed. Error code = 0x800f0950

### ISSUE THREAD

**Issue by dpareit** [MicrosoftDocs/windowsserverdocs#2074]
Performing a
Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0 fails on Windows Server 2019 Datacenter edition, build 17763.1 . Both on 'Full Desktop Experience' and the 'Core' installation option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07417484-bd6d-e6f4-110e-e42c2428a369
* Version Independent ID: 844743a6-f67b-421f-9591-13da36b23b14
* Content: [Installation of OpenSSH For Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* GitHub Login: @maertendMSFT

**Comment by Blankf** [comment]
experiencing the same issue here ( core and gui )

**Comment by dpareit** [comment]
thanks for the suggestion! KB4470788 and KB4470502 did however not yet solve the issue. I had to install KB4471332 as well and this solved it for me. This implies a shift from build 17763.1 to build 17763.194 (december 2018).

**Comment by MaDjiDoU0911** [comment]
Impossible to install the French language on windows server 2019

**Comment by Geogboe** [comment]
Looks like these updates have all been superseded. Installing KB4480116 ( latest cumulative update ) resolved this issue for me. 

So it looks like, for any new installs, just make sure you have the *Latest* cumulative update.

**Comment by lixaotec** [comment]
Having similiar issue. 

Its an offline machine. Windows 10 1809 offline os build 17763.404

Add-WindowsCapability : Falha em Add-WindowsCapability. Código do erro = 0x8024402c
No linha:1 caractere:1
+ Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-WindowsCapability], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.AddWindowsCapabilityCommand

**Comment by ingarb** [comment]
Same issue here, on Server 2019 vNext (Insider Build 18356). I already installed OpenSSH client via Powerhsell, worked ok.. But the OpenSSH server just fails with  0x800f0950 / COMException - and there is no update available for the INsider Server Build?

**Comment by andrm** [comment]
gpedit.msc (Group Policy) -> Computer Configuration  -> Admin. Templates -> Windows Components -> Windows Update -> Specify intranet Microsoft update service location -> Disabled
seemed to help me with Win2019.

**Comment by aiuex79** [comment]
> gpedit.msc (Group Policy) -> Computer Configuration -> Admin. Templates -> Windows Components -> Windows Update -> Specify intranet Microsoft update service location -> Disabled
> seemed to help me with Win2019.

worked for me as well.. Thanks for pointing this out.

**Comment by dralausky** [comment]
Well ,I solved this problem just with settings->update and security->Transfer optimization->allow download from other computer open ,select the second one ,download from other computer and internet

**Comment by mmaysami** [comment]
> 
> 
> gpedit.msc (Group Policy) -> Computer Configuration -> Admin. Templates -> Windows Components -> Windows Update -> Specify intranet Microsoft update service location -> Disabled
> seemed to help me with Win2019.

It resolved my issue with adding SSHClient! Thanks for the tip!

**Comment by jonesbusy** [comment]
> > gpedit.msc (Group Policy) -> Computer Configuration -> Admin. Templates -> Windows Components -> Windows Update -> Specify intranet Microsoft update service location -> Disabled
> > seemed to help me with Win2019.
> 
> It resolved my issue with adding SSHClient! Thanks for the tip!

Same issue on Azure Cloud with this SKU `MicrosoftWindowsServer:WindowsServer:2019-Datacenter-smalldisk:2019.0.20190410`.

Is there a way to automate this change ? I'm using packer to create base images, that's why.

Thanks!

**Comment by mattwak** [comment]
I've encoutered this issue today after setting a deployment in SCCM for this. 
Get-WindowsCapability -Name "RSAT*" -Online | Add-WindowsCapability –Online -Verbose

I have the group policy setting on but I still get error code. 0x800f0950
I'm trying KB4495667 to see if it resolves it.

**Comment by mattwak** [comment]
> 
> 
> I've encoutered this issue today after setting a deployment in SCCM for this.
> Get-WindowsCapability -Name "RSAT*" -Online | Add-WindowsCapability –Online -Verbose
> 
> I have the group policy setting on but I still get error code. 0x800f0950
> I'm trying KB4495667 to see if it resolves it.

After Installing KB4495667 which is the latest CU for 1809 it is resolved. As this week is patch Tuesday/Wednesday (depending on your location) the fi should be rolled into the A week update.

I'm using this command.
Get-WindowsCapability -Online -Name "*RSAT*" | Add-WindowsCapability -Online -Verbose

**Comment by voltagex** [comment]
Getting this on a Server Insider Preview VM - 10.0.18356.1

**Comment by SunHaozhe** [comment]
> Having similiar issue.
> 
> Its an offline machine. Windows 10 1809 offline os build 17763.404
> 
> Add-WindowsCapability : Falha em Add-WindowsCapability. Código do erro = 0x8024402c
> No linha:1 caractere:1
> 
> * Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
> * ```
>     + CategoryInfo          : NotSpecified: (:) [Add-WindowsCapability], COMException
>     + FullyQualifiedErrorId : Microsoft.Dism.Commands.AddWindowsCapabilityCommand
>   ```

I have exactly the same problem

**Comment by nidhinckgithub** [comment]
`$currentWU = Get-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU" -Name "UseWUServer" | select -ExpandProperty UseWUServer
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU" -Name "UseWUServer" -Value 0
Restart-Service wuauserv
Get-WindowsCapability -Name RSAT* -Online | Add-WindowsCapability –Online
Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU" -Name "UseWUServer" -Value $currentWU
Restart-Service wuauserv`

Source: https://community.spiceworks.com/topic/2166885-rsat-and-wsus-locations

**Comment by terryxychan** [comment]
This issue appears in my setup:
```
Edition: Windows Server 2019 Standard
Version: 1809
Build: 17763.740
```
I've tried @andrm's methond and it's still not working. 

I've encountered Error code 0x800f0950 and 0x800f0954 each on one of my server machines with the same setup. 
Error #1:
```
Add-WindowsCapability : Add-WindowsCapability failed. Error code = 0x800f0950
At line:1 char:1
+ Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-WindowsCapability], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.AddWindowsCapabilityCommand
```

**Comment by ctivanovich** [comment]
Same error message:
```
Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0                  Add-WindowsCapability : Add-WindowsCapability failed. Error code = 0x800f0954
At line:1 char:1
+ Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-WindowsCapability], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.AddWindowsCapabilityCommand
```
Windows 10 ver 1903, insider build 18995.1.

**Comment by Rusty-Shackleford** [comment]
This is bullshit microsoft.  Getting tired of your crap.

**Comment by nikking** [comment]
I'm encountering the same issue. None of the workarounds above work for me 😔
**
Windows 10 Education N
Version 2004
OS Build 19037.1
**
`
PS C:\WINDOWS\system32> Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
Add-WindowsCapability : Add-WindowsCapability failed. Error code = 0x800f0950
At line:1 char:1
+ Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-WindowsCapability], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.AddWindowsCapabilityCommand
`

**Comment by ctivanovich** [comment]
I found out the cause, at least in my case--my workplace sysadmin did not have OptionalFeatures covered by the domain group policy, so that was blocking the download as well as just generally getting in the way of the windows update processes.

**Comment by E05a613** [comment]
This resolved the issue for me - https://social.technet.microsoft.com/Forums/en-US/42bfdd6e-f191-4813-9142-5c86a2797c53/windows-10-1809-rsat-toolset-error-code-of-0x800f0954?forum=win10itprogeneral

**Comment by mrartanis** [comment]
**Windows 10 enterprise**
**Build 19035.1**
Can't install Openssh server neither from gui/dism/posh got 0x800f0950
dism log: https://paste.ubuntu.com/p/PmKVD4hBk7

**Comment by McAndersDK** [comment]
I fixed it by just using:
`Add-WindowsCapability -Online -Name OpenSSH.Server`

**Comment by bschapendonk** [comment]
I'm having the same problem, during a unattended installation using the `17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.iso` (internet is available). 

This workaround seems to be stable for me. I'm running the following powershell script using the `FirstLogonCommands` during the unattended installation, eventually this succeeds, but it may fail a number of times with the 0x800f0950 error. Just retry until it is installed.

```
do {
  Start-Sleep -Seconds 5
  Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0 -ErrorAction Ignore | Out-Null
} 
until ((Get-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0).State -eq 'Installed')
```

**Comment by Vijayasundhari** [comment]
> Well ,I solved this problem just with settings->update and security->Transfer optimization->allow download from other computer open ,select the second one ,download from other computer and internet

Thanks a ton. It worked.

**Comment by joshuayoerger** [comment]
Has anyone tried resetting their WUServer registry key? This resolved the error for me.

- Open regedit
- Navigate to `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU`
- Set `UseWUServer = 0x00000000 (0)`
- Restart

**Comment by hizukiayaka** [comment]
> 
> 
> I found out the cause, at least in my case--my workplace sysadmin did not have OptionalFeatures covered by the domain group policy, so that was blocking the download as well as just generally getting in the way of the windows update processes.

Click Computer Configuration, click Administrative Templates, click System, and then double-click the Specify settings for optional component installation and component repair setting

That works for me

**Comment by trgrassijr55** [comment]
> Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0

Josh,

The registry changed worked for me 
Open regedit
Navigate to Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
Set UseWUServer = 0x00000000 (0)
Restart my server

PS C:\util> Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0

Path          :
Online        : True
RestartNeeded : False

My question is should I revert back the registry setting?  I use WSUS to update my servers?

Thank you

Tom

**Comment by grk1986** [comment]
> `$currentWU = Get-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU" -Name "UseWUServer" | select -ExpandProperty UseWUServer Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU" -Name "UseWUServer" -Value 0 Restart-Service wuauserv Get-WindowsCapability -Name RSAT* -Online | Add-WindowsCapability –Online Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU" -Name "UseWUServer" -Value $currentWU Restart-Service wuauserv`
> 
> Source: https://community.spiceworks.com/topic/2166885-rsat-and-wsus-locations

Thanks, it worked !!!!

**Comment by sguidos** [comment]
> Ultimately, this worked for our company:
> https://dailysysadmin.com/KB/Article/3244/add-windowscapability-failed-error-code-0x800f0954/

I found this page while searching for the 0x800f0954 error code, and the solution described int the link above worked for me.

**Comment by sailfish009** [comment]
i have installed openssh server (sshd)  directly from github:

https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

**Comment by ethancedrik** [comment]
Windows Server 2019 Core Semi-Annual Insider Preview Build 20226 [Windows_InsiderPreview_Server_en-us_20226.iso]

Microsoft Windows [Version 10.0.20226.1000]

C:\Users\Administrator>powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\Administrator> Add-WindowsCapability -Online -Name ServerCore.AppCompatibility~~~~0.0.1.0
Add-WindowsCapability : Add-WindowsCapability failed. Error code = 0x800f0950
At line:1 char:1
+ Add-WindowsCapability -Online -Name ServerCore.AppCompatibility~~~~0. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-WindowsCapability], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.AddWindowsCapabilityCommand

For Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU there are two keys, one AUOptions with value 3, and the other UserWUServer set to 0 and the command still fails as above

Overall I cannot accomplish or find a way to do what I'm trying to do with this system and gave up

**Comment by jayunit100** [comment]
https://www.catalog.update.microsoft.com/Search.aspx?q=2020-09%202019 evidently theres updates you need to install for this ?

**Comment by doctordns** [comment]
I am seeing this error too on all the latest insiders server build.

Fooling around with WSUS did not resolve the problem and this is a late insiders build so there is no older CU to deal with.;

Is there any solution to this?

**Comment by ggondim** [comment]
> I am seeing this error too on all the latest insiders server build.
> 
> Fooling around with WSUS did not resolve the problem and this is a late insiders build so there is no older CU to deal with.;
> 
> Is there any solution to this?

I'm also getting this on Windows 10 Enterprise Insider Preview Build `20150.rs_prerelease.200612-1734`

Tried the workarounds (none worked):

- group policy
- registry (both HKLM\Software\Policies\Microsoft\Windows\WindowsUpdate\AU and HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate)
- disabling delivery optimization in settings
- tried to install all RSAT capabilities (same error code 0x800f0950)
- tried to restart wuauserv

**Powershell output**

```
Add-WindowsCapability : Falha em Add-WindowsCapability. Código do erro = 0x800f0950                                     No linha:1 caractere:1
+ Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-WindowsCapability], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.AddWindowsCapabilityCommand
```

**Windows Event Log Report**

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Windows Error Reporting" /> 
  <EventID Qualifiers="0">1001</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-11-12T01:44:26.9471416Z" /> 
  <EventRecordID>28689</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>NOALVO-CTO</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>1869761896635289786</Data> 
  <Data>5</Data> 
  <Data>CbsPackageServicingFailure2</Data> 
  <Data>Não disponível</Data> 
  <Data>0</Data> 
  <Data>10.0.20150.1000</Data> 
  <Data>OpenSSH-Server-Package</Data> 
  <Data>10.0.20150.1000</Data> 
  <Data>amd64</Data> 
  <Data>unknown</Data> 
  <Data>800f0950</Data> 
  <Data>CBS Other</Data> 
  <Data>Absent</Data> 
  <Data>Absent</Data> 
  <Data>DISM Package Manager Provider</Data> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1FA.tmp.WERInternalMetadata.xml</Data> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\Critical_10.0.20150.1000_e7a717011ce11c59fb1426e6964f30604654ab_00000000_b9b98b00-3723-468d-ac7f-f442daa7221f</Data> 
  <Data /> 
  <Data>0</Data> 
  <Data>b9b98b00-3723-468d-ac7f-f442daa7221f</Data> 
  <Data>2147487744</Data> 
  <Data>f7601e678ae448da69f2ba89df81d0ba</Data> 
  <Data>0</Data> 
  </EventData>
  </Event>
```

**Comment by ggondim** [comment]
Somehow it was related to Insider Preview update...

Before the error, I installed a Dev release manually but I stayed in the Beta release channel. Today I changed it to Dev channel and updated to `Build 20257.fe_release.201106-1554` and it solved the problem.

Windows Update seems to be confused if you install a Dev release manually and stays at Beta release channel.

**Comment by Bonifaciy1** [comment]
Plus to the everything above adding a couple of key did the thing:

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Servicing]
"LocalSourcePath"=hex(2):00,00
"RepairContentServerSource"=dword:00000002

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Policies\Servicing]
"LocalSourcePath"=hex(2):00,00
"RepairContentServerSource"=dword:00000002

**Comment by jamescookrfs** [comment]
Thanks Bonifaciy1 this solved the issue on my Server 2019 machine.

Fully patched, GPEdit done, added both regkeys and install 'Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0' completed (agent installed fine first go)

**Comment by perithompson** [comment]
I just started to see this with the Feb2021 window 2019 media, this has only just started happening

```
TASK [systemprep : Install OpenSSH] ********************************************
fatal: [default]: FAILED! => {"changed": true, "cmd": "Get-WindowsCapability -Online -Name OpenSSH.Server* | Add-WindowsCapability -Online", "delta": "0:00:08.388772", "end": "2021-04-30 10:58:33.105127", "msg": "non-zero return code", "rc": 1, "start": "2021-04-30 10:58:24.716355", "stderr": "Add-WindowsCapability : Add-WindowsCapability failed. Error code = 0x800f0950\r\nAt line:1 char:119\r\n+ ... ability -Online -Name OpenSSH.Server* | Add-WindowsCapability -Online\r\n+                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [Add-WindowsCapability], COMException\r\n    + FullyQualifiedErrorId : Microsoft.Dism.Commands.AddWindowsCapabilityCommand", "stderr_lines": ["Add-WindowsCapability : Add-WindowsCapability failed. Error code = 0x800f0950", "At line:1 char:119", "+ ... ability -Online -Name OpenSSH.Server* | Add-WindowsCapability -Online", "+                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "    + CategoryInfo          : NotSpecified: (:) [Add-WindowsCapability], COMException", "    + FullyQualifiedErrorId : Microsoft.Dism.Commands.AddWindowsCapabilityCommand"], "stdout": "", "stdout_lines": []}
```

**Comment by illfated** [comment]
Would it be possible to gather enough information from the various comments in this ticket page to open a Pull Request for the article to be properly updated as required?

**Comment by TheBigBear** [comment]
I am seeing this on the latest windows server 2022 insider preview version 21H2 (OS Build 20344.1)
```
dism /online /Add-Capability /CapabilityName:OpenSSH.Server~~~~0.0.1.0

Deployment Image Servicing and Management tool
Version: 10.0.20344.1

Image Version: 10.0.20344.1

[==========================100.0%==========================]

Error: 0x800f0950

DISM failed. No operation was performed.
For more information, review the log file.

The DISM log file can be found at C:\WINDOWS\Logs\DISM\dism.log
```

```
Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0 -Debug -Verbose
VERBOSE: Target Image Version 10.0.20344.1
Add-WindowsCapability : Add-WindowsCapability failed. Error code = 0x800f0950
At line:1 char:1
+ Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0 -Debug  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-WindowsCapability], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.AddWindowsCapabilityCommand
```

**Comment by Nikhil-R-Patil** [comment]
If it is Azure VM with 2K19 just check your DNS address in network adaptor and make sure you do not have invalid proxy address in  internet explorer LAN settings.

**Comment by FelipeMiranda** [comment]
> Having similiar issue.
> 
> Its an offline machine. Windows 10 1809 offline os build 17763.404
> 
> Add-WindowsCapability : Falha em Add-WindowsCapability. Código do erro = 0x8024402c No linha:1 caractere:1
> 
> * Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
> * ```
>     + CategoryInfo          : NotSpecified: (:) [Add-WindowsCapability], COMException
>     + FullyQualifiedErrorId : Microsoft.Dism.Commands.AddWindowsCapabilityCommand
>   ```

I had the same error and check my network, indeed it was disconnected, after connecting to internet the command went fine

**Comment by dduportal** [comment]
Same issue with any Windows Server 2019 build on AWS EC2 with the 2022-05-25 version on the Jenkins public infrastructure (https://github.com/jenkins-infra/packer-images/issues/253).
We're going to stick to an older build until we have a new one that is published and work, but worth sharing it publicly if it is any help.

Error is the following:

```
==> amazon-ebs.windows: Provisioning with powershell script: ./provisioning/windows-provision.ps1
    amazon-ebs.windows: = Setting up OpenSSH Server
    amazon-ebs.windows: Add-WindowsCapability : Add-WindowsCapability failed. Error code = 0x800f0950
    amazon-ebs.windows: At C:\Windows\Temp\script-62a1ba9d-107e-c1ff-1190-b7e16605f4f2.ps1:71 char:1
    amazon-ebs.windows: + Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
    amazon-ebs.windows: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    amazon-ebs.windows:     + CategoryInfo          : NotSpecified: (:) [Add-WindowsCapability], COMException
    amazon-ebs.windows:     + FullyQualifiedErrorId : Microsoft.Dism.Commands.AddWindowsCapabilityCommand
    amazon-ebs.windows:
==> amazon-ebs.windows: Provisioning step had errors: Running the cleanup provisioner, if present...
```

**Comment by bryannso** [comment]
Bullshit.   There's no resolution to the numerous instances of issues here.   Why would this be closed?

**Comment by dduportal** [comment]
> Bullshit. There's no resolution to the numerous instances of issues here. Why would this be closed?

Please stay polite. Being rude is clearly the worst way to ask for resolution.

**Comment by bryannso** [comment]
Likewise.   Here's the scoop.    MS releases (in a blog) that a feature is now available in its products.   Yet, the official documentation is prone to errors, which have been outlined repeatedly on this page.   No official response from MS, the project leaders, etc.   

Yes, there are some recommended things to check that have been provided by other USERS, but everyone's mileage may very, and none of the "workarounds" apply.   No official response from anyone managing the project - nope - but let's go ahead and close this anyway.

How rude, indeed.
