### ISSUE TITLE
I Can't Initialize New Disk

### ISSUE THREAD

**Issue by MarKeremid** [MicrosoftDocs/windowsserverdocs#2079]
Hello,

I find difficulties to "Initialize" my disk partitions when right-clicking the HDD where I want to create more logical separations. E.g.: I want (D:), but after I tried to install Linux all partitions have disappeared, except (C:) for some reason. Anyway, I'm going to bed (z-z-Z). Tomorrow I'll find the answer, but I wouldn't mind if you share your thoughts about that. :) 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aed88c8d-c15e-9dad-4cf4-9cc92e625f41
* Version Independent ID: 3ba55b69-bea2-a674-d08f-e93a03de1ffa
* Content: [Initialize new disks](https://docs.microsoft.com/en-gb/windows-server/storage/disk-management/initialize-new-disks)
* Content Source: [WindowsServerDocs/storage/disk-management/initialize-new-disks.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/initialize-new-disks.md)
* Product: **windows-server-threshold**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by doctordns** [comment]
What results do you get from using the following PowerShell cmdlets:
```powershell
Get-DIsk
Get-Volume
Get-Partition
```
This does not appear to be a documentation error.

**Comment by BambamPewpew32** [comment]
Yeah I'm having the same problem, there simply isn't an initialize option when I right click on the drive, and it's not even in the top list, it's on the bottom.

**Comment by take0ff** [comment]
I have the same issue PowerShell for the previous commands not showing any info for the corrupted hard, but the device are showing in Device and Printers window Also showing in Device Manager with correct name

**Comment by BambamPewpew32** [comment]
> I have the same issue PowerShell for the previous commands not showing any info for the corrupted hard, but the device are showing in Device and Printers window Also showing in Device Manager with correct name

I forgot how I did it but I randomly figured it out awhile ago lol

**Comment by BambamPewpew32** [comment]
> I have the same issue PowerShell for the previous commands not showing any info for the corrupted hard, but the device are showing in Device and Printers window Also showing in Device Manager with correct name

actually I think I went into my bios and changed the primary boot drive on every setting to my SSD and then reinstalled everything, idk if this helps you but that's what I did

**Comment by illfated** [comment]
If the `Initialize` option is not available and the partitions don't appear, you may have to reset the entire drive device and start from scratch (wiping the drive, maybe even using a different computer). Just make sure you either have a backup of things you want to keep, or that the drive does not contain anything important at all.

**Comment by take0ff** [comment]
I tried to do that step but it's show to me access denied, also i tried many of wiping software to solve the issue but Error massage showing to me.
the hard in Hex viewer is READ ERROR
![Untitled](https://user-images.githubusercontent.com/8926168/67168480-a682ea00-f3ad-11e9-89f4-d398f3eb52b7.gif)

**Comment by illfated** [comment]
Looks like another case of too many unknown factors there. You should either test that disk in a different computer to find out if it is working at all, or find out if there is anything incompatible in its firmware versus the computer BIOS you are using. Not enough information to tell if that error is caused by hardware or software.

**Comment by take0ff** [comment]
I already test it in another computer, its same issue attached company LifeGuard test result, any idea if can be fixed or not please?

**Comment by illfated** [comment]
Classic example of defective hardware. "Too many bad sectors detected." -- defective hardware error messages do not become much more clear than that. Please contact your Western Digital vendor regarding warranty options for your harddrive -- it can not be recovered without the use of Data Rescue Equipment -- and the harddrive will likely not be usable even after any data recovery attempt.

**Comment by illfated** [comment]
#please-close
