### ISSUE TITLE
Add-WindowsFeature FS-NFS-Services not found

### ISSUE THREAD

**Issue by lstomberg** [MicrosoftDocs/windowsserverdocs#2082]
There is a typo here.  It should be:
```
Add-WindowsFeature FS-NFS-Service
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06290341-e4fb-48cf-7e26-113810965321
* Version Independent ID: cede637e-427b-b684-786c-d3222811352c
* Content: [Deploy Network File System](https://docs.microsoft.com/en-us/windows-server/storage/nfs/deploy-nfs)
* Content Source: [WindowsServerDocs/storage/nfs/deploy-nfs.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/nfs/deploy-nfs.md)
* Product: **windows-server-threshold**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by stevenfollis** [comment]
Looks like this was fixed - ready to close issue?
