### ISSUE TITLE
Remote Desktop client on macOS 10.2.4

### ISSUE THREAD

**Issue by rholleron** [MicrosoftDocs/windowsserverdocs#2086]
There are no feature updates in this doc for 10.2.4
Shouldn't this be posted BEFORE the update is released?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dca80301-5517-3479-c79f-96c7e5e3f4eb
* Version Independent ID: f6c2df89-25dc-2d34-ef78-36cbadb4031b
* Content: [What's new for Remote Desktop on Mac?](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/mac-whatsnew)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/mac-whatsnew.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/mac-whatsnew.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by lizap** [comment]
David pushed an update today, so I'm going to close this issue. Thank you!
