### ISSUE TITLE
Typos in doc of configuring proxy section.

### ISSUE THREAD

**Issue by d0lphis** [MicrosoftDocs/windowsserverdocs#2089]
In https://docs.microsoft.com/en-us/windows-server/administration/server-core/server-core-administer

Task | Command
-- | --
... | ...
Configure your server to bypass the proxy for Internet addresses | **netsh winttp set proxy \<servername\>:\<port number\>bypass-list="\<local\>"**
... | ...

The command should be:
**netsh winhttp set proxy \<servername\>:\<port number\> bypass-list="\<local\>"**

**Comment by lizap** [comment]
Thanks for catching this - we'll get the spacing fixed.
