### ISSUE TITLE
The access token is invalid

### ISSUE THREAD

**Issue by leonmeijer** [MicrosoftDocs/windowsserverdocs#2093]
After linking my Azure account, I'm unable to setup Azure Site Recovery. After clicking on the link 'Set up now' I get a notification 'The access token is invalid.'. My Azure account is Global Admin, I can see the Azure AD app registration in the Azure Portal. Cleared cookies. Any suggestions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae730e6-5e1e-1ae6-5cbd-9eb6d271690b
* Version Independent ID: a79daa4b-e8fb-0ed4-867c-430b3c61ceea
* Content: [Configuring Azure Integration](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/configure/azure-integration)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/configure/azure-integration.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/configure/azure-integration.md)
* Product: **windows-server-threshold**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by g2gitdept** [comment]
I am seeing this same issue.

**Comment by leonmeijer** [comment]
> I am seeing this same issue.

I managed to work around it by installing the regular Site Recovery agent. It does support Windows Server 2019 and replication works fine with Azure.

**Comment by IngridAtMicrosoft** [comment]
#please-close
