### ISSUE TITLE
reg-add "space"

### ISSUE THREAD

**Issue by dlwlb** [MicrosoftDocs/windowsserverdocs#2095]
Explain that double quotes are needed around a key that contains a space character.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3deae269-de28-fb85-f52e-334e5b222de8
* Version Independent ID: 792402db-afda-e1fc-18e5-551a4b625b83
* Content: [reg add](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/reg-add)
* Content Source: [WindowsServerDocs/administration/windows-commands/reg-add.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/reg-add.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by doctordns** [comment]
Raised a PR to address this - good catch.

**Comment by VikingByNature** [comment]
I provided 6 detailed articles including proper use of key names, value names and data names that require the use of double quotes if they contain spaces and/or special characters.

**Comment by illfated** [comment]
Shouldn't this issue ticket be closed if it is resolved by PR #2114 ?

**Comment by illfated** [comment]
Thank you for following up and closing the ticket. Happy holidays to you as well. 😃 👍
