### ISSUE TITLE
SSH means secure shell, not "secure scripting host"

### ISSUE THREAD

**Issue by aperally** [MicrosoftDocs/windowsserverdocs#2097]
https://tools.ietf.org/html/rfc4253

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a65b1859-4593-6240-5466-949cf4d0d97c
* Version Independent ID: f35f1097-2829-b447-7744-7a1dcb4a1b2c
* Content: [Open](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_overview)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Overview.md)
* GitHub Login: @maertendMSFT

**Comment by lizap** [comment]
Thanks for raising this. Like you, @doctordns also saw this error and fixed it. You should see the corrected text soon.
