### ISSUE TITLE
result = await authContext.AcquireTokenAsync(...); causing errors.

### ISSUE THREAD

**Issue by amanmcse** [MicrosoftDocs/windowsserverdocs#2099]
result = await authContext.AcquireTokenAsync(...); in ToDoListController.cs file is causing following errors:
Error: CS1001 Identifier expected
Error: CS1501 No overload for method 'AcquireTokenAsync' takes 0 arguments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e13f162-0b92-091e-f811-8645f786185f
* Version Independent ID: 68332cf9-44a5-8f19-d149-d294c8c4db5c
* Content: [Build a multi-tiered application using On-Behalf-Of (OBO) using OAuth with AD FS 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/ad-fs-on-behalf-of-authentication-in-windows-server#running-the-solution)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/ad-fs-on-behalf-of-authentication-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/ad-fs-on-behalf-of-authentication-in-windows-server.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by akgoel23** [comment]
Hi amanmcse,

Thanks for pointing out the issue. The sample code has been fixed. 

Thanks.
