### ISSUE TITLE
Link Broken : Plann for Automatic File Classification

### ISSUE THREAD

**Issue by johnwildes** [MicrosoftDocs/windowsserverdocs#2102]
The link for "Plan for Automatic File Classification" points to assetid:///e3c3bb4b-3034-42b7-b391-8ef5f5851955 and nothing that you can reference from here.  I couldn't find that section of the documentation as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f5b0e02-22cf-ddea-dc85-3269f65a746f
* Version Independent ID: 8202ff1a-a6f4-3903-d144-e18980636133
* Content: [Deploy Automatic File Classification (Demonstration Steps)](https://docs.microsoft.com/en-us/windows-server/identity/solution-guides/deploy-automatic-file-classification--demonstration-steps-)
* Content Source: [WindowsServerDocs/identity/solution-guides/Deploy-Automatic-File-Classification--Demonstration-Steps-.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/solution-guides/Deploy-Automatic-File-Classification--Demonstration-Steps-.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by lizap** [comment]
I've updated the link to this: https://docs.microsoft.com/en-us/previous-versions/orphan-topics/ws.11/jj574209(v%3dws.11)

Will close when the change is published. Thanks!
