### ISSUE TITLE
Volume Health Info Incorrect

### ISSUE THREAD

**Issue by migrande** [MicrosoftDocs/windowsserverdocs#2103]
It looks like the information in this article about the Get-VirtualDisk info is incorrect.  Per a post at https://social.technet.microsoft.com/Forums/en-US/4533b4f0-b955-4f5b-bdd1-6a183f5e58f2/how-to-take-a-s2d-server-offline-for-maintenance-correctly?forum=winserverClustering by Steven Ekren, the PM for Storage Spaces Direct, it is now expected that the nodes will continue serving reads/writes until they are shut down.  However, this article says that pausing the nodes will pause read/writes.  In effect, the Get-VirtualDisk commands now show healthy until you actually power down one of the nodes.  This needs to be reviewed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 393d4e4d-1975-93bf-f405-e81ae50dcb40
* Version Independent ID: a38288af-3054-eebe-2d81-8c2f3be3eb60
* Content: [Taking a Storage Spaces Direct server offline for maintenance](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/maintain-servers#feedback)
* Content Source: [WindowsServerDocs/storage/storage-spaces/maintain-servers.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/maintain-servers.md)
* Product: **windows-server-threshold**
* GitHub Login: @EldenChristensen
* Microsoft Alias: **eldenc**

**Comment by migrande** [comment]
Paging @EldenChristensen

**Comment by easonlauys** [comment]
Nobody even cares to reply from MSFT?
