### ISSUE TITLE
john or jane doe

### ISSUE THREAD

**Issue by pauly7300** [MicrosoftDocs/windowsserverdocs#2125]
In top section of document where there is an example of jdoe@contoso.com, there is a typo where jane is referenced as john doe.  confusing...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02d8b61-29e8-c0a7-b3b2-79be7212a91c
* Version Independent ID: b4346d87-0727-c7fe-7896-7fd79098825c
* Content: [Configuring Alternate Login ID](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configuring-alternate-login-id)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configuring-Alternate-Login-ID.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configuring-Alternate-Login-ID.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by doctordns** [comment]
Good catch - PR issues to revolve this.
