### ISSUE TITLE
CRLDistributionPoint URL is https

### ISSUE THREAD

**Issue by mjgar** [MicrosoftDocs/windowsserverdocs#2138]
The URL should be updated to be http as opposed to https in the CRLDistributionPoint section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8ffdaef-7179-7cfc-ceb3-7443fe3e9476
* Version Independent ID: e5c1e3a8-9b73-d314-df06-c6da3a3adf67
* Content: [Prepare the CAPolicy.inf File](https://docs.microsoft.com/en-us/windows-server/networking/core-network-guide/cncg/server-certs/prepare-the-capolicy-inf-file)
* Content Source: [WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Prepare-the-CAPolicy-inf-File.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Prepare-the-CAPolicy-inf-File.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by bigmaggot** [comment]
All CRL locations are HTTP.

Policy Statements are using HTTPS.

I don't see an issue here...

**Comment by mjgar** [comment]
> All CRL locations are HTTP.
> 
> Policy Statements are using HTTPS.
> 
> I don't see an issue here...

Because it was fixed the same day I reported it. 

https://github.com/MicrosoftDocs/windowsserverdocs/commit/a37a46d1c2a270e91d0bdd7d6ac55d1a2eb2b554#diff-16e9a270568327bf0f1080a1c40cf591
