### ISSUE TITLE
Only targets the user you are log in on

### ISSUE THREAD

**Issue by Mradr** [MicrosoftDocs/windowsserverdocs#2141]
This is limited to the targeted log in user for creates, lists, and deletes stored user names and passwords or credentials. You can not target another user with this information until you log into that user.

Request a option to target another user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caebc8e0-4c03-4714-b7a8-3d55ef0f6ab1
* Version Independent ID: 5a7b7ad8-8f55-fb3e-54ee-b8aff333b7c7
* Content: [cmdkey](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cmdkey)
* Content Source: [WindowsServerDocs/administration/windows-commands/cmdkey.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/cmdkey.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by luffjr** [comment]
cmdkey /list should also show the users that the credentials have been applied to.

Is there any way round this problem? In my case I need to apply the credentials to a service account that I cannot log in as.

**Comment by dustinbrooks** [comment]
Anyone have a workaround for this yet? I'm in the same boat as luffjr. My service user can't be logged into directly
