### ISSUE TITLE
How to use with Microsoft account

### ISSUE THREAD

**Issue by lukegackle** [MicrosoftDocs/windowsserverdocs#2142]
How can we use the ICACLS command when signed in with a Microsoft account simply typing out the username does not work, using the prefix MicrosoftAccount\email also doesn't work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a990d09-b5b1-3aba-de57-0aec79c12784
* Version Independent ID: 36d90c17-ba95-4ed6-de9d-f379dcad6c4d
* Content: [icacls](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/icacls)
* Content Source: [WindowsServerDocs/administration/windows-commands/icacls.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/icacls.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by doctordns** [comment]
In general, ICALCS is designed to use local or domain accounts. I am not sure it is capable of handling external authentication schemes like Live IDs.

**Comment by lukegackle** [comment]
Thank you, it's just my Windows 10 is logged in with a Microsoft account
rather than a local account so I didn't know what to enter, however I was
able to use the PowerShell command Get-LocalUser to find out what the local
username is 😁

**Comment by doctordns** [comment]
Can this issue be closed then?

**Comment by lukegackle** [comment]
Sure thing!

**Comment by lukegackle** [comment]
I received a notification that this issue had been reopened, for reference my solution was to use the Get-LocalUser PowerShell command to find the local username for the Microsoft account, obviously this was not something that was easily discoverable without using a command like this.

**Comment by IngridAtMicrosoft** [comment]
#please-close
