### ISSUE TITLE
Server 2019 guests on 2016 host

### ISSUE THREAD

**Issue by DSPatrick** [MicrosoftDocs/windowsserverdocs#2143]
Is the note about Server 2019 guests "Not supported on Windows Server 2016 hosts" a temporary or permanent status?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db545402-d0df-dbfc-311a-b7b2f0cdbb2a
* Version Independent ID: 8255de57-a41a-0dbd-7197-3915ebb32ed2
* Content: [Supported Windows guest operating systems for Hyper-V on Windows Server](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-windows-guest-operating-systems-for-hyper-v-on-windows)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Supported-Windows-guest-operating-systems-for-Hyper-V-on-Windows.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/Supported-Windows-guest-operating-systems-for-Hyper-V-on-Windows.md)
* Service: **na**
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by fowl2** [comment]
[Note appears to have been removed](https://github.com/MicrosoftDocs/windowsserverdocs/commit/2c54e781c64e0cc3fec2cef349a762b972987870#diff-5347e6e782aa2be9a9ec94ff6ef0436b)
