### ISSUE TITLE
typographical error

### ISSUE THREAD

**Issue by Y32Xe4F86fJWJDqTNSnb** [MicrosoftDocs/windowsserverdocs#2144]
not that it is too hard to figure out for people, still just wanted to mention that its "encryptpagingfile" not "encryppagingfile", you're missing a "t".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8d32e48-6eae-56c6-2e88-47ff6edf0834
* Version Independent ID: ebad240a-f3c1-31e2-ffd7-dd267f747e8b
* Content: [Fsutil behavior](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil-behavior)
* Content Source: [WindowsServerDocs/administration/windows-commands/fsutil-behavior.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/fsutil-behavior.md)
* Product: **windows-server-threshold**
* GitHub Login: @toklima
* Microsoft Alias: **toklima**

**Comment by doctordns** [comment]
hopefully #2145 fixes this issue - good catch

**Comment by doctordns** [comment]
Since we have #2145, this issue can probably be closed.

**Comment by illfated** [comment]
> Since we have #2145, this issue can probably be closed.

Thank you, both for your PR #2145 and for confirming the resolved issue.

**Comment by illfated** [comment]
#please-close
