### ISSUE TITLE
Storage Migration Service and Clustered File Servers

### ISSUE THREAD

**Issue by klawnv** [MicrosoftDocs/windowsserverdocs#2153]
Any idea when the Storage Migration Service will get updated so that we can use it to migrate to a clustered file server?  We're hoping to be able to consolidate all of our existing file servers very soon to one new clustered file server, and we're really wanting to be able to use the Storage Migration Service to help us with that but it currently won't allow us to migrate data and such to a clustered file server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c3b0886-820a-0b3c-8382-8d65fc8c3b27
* Version Independent ID: 3e310218-abc0-5249-bb16-7c21402e32c0
* Content: [Storage Migration Service overview](https://docs.microsoft.com/en-us/windows-server/storage/storage-migration-service/overview)
* Content Source: [WindowsServerDocs/storage/storage-migration-service/overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-migration-service/overview.md)
* Product: **windows-server-threshold**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#please-close
