### ISSUE TITLE
Install fails: Failed to reserve port 6516

### ISSUE THREAD

**Issue by Vikhrenko** [MicrosoftDocs/windowsserverdocs#2154]
Installing WindowsAdminCenter1809.msi on computer:
- Windows 10 Enterprise, version 1809, all updates applied
- member of a domain
- under domain account with local administrator privileges.
All setting in the installer are kept default.
On "Creating SSL certificate" step an error box appears:
"1: Unhandled Exception: Microsoft.Deployment.WindowsInstaller.InstallerException Failed to reserve port 6516". Only “Ok” is available, which rolls back the installation.
All possible letters are chosen in the policy for installer log details, so here is the fragment of log concerning the error:
-------------------------begin-------------------------
Calling custom action Microsoft.ManagementExperience.Setup.CustomActions!Microsoft.ManagementExperience.Setup.CustomActions.CustomAction.GenerateDesktopSslCertificate
MSI (s) (A8!E0) [01:37:40:324]: Closing MSIHANDLE (70) of type 790531 for thread 13792
MSI (s) (A8!E0) [01:37:40:343]: Creating MSIHANDLE (71) of type 790531 for thread 13792
Action 01:37:40: Creating SSL certificate. Creating SSL certificate
MSI (s) (A8!E0) [01:37:40:346]: Closing MSIHANDLE (71) of type 790531 for thread 13792
MSI (s) (A8!E0) [01:37:44:573]: Creating MSIHANDLE (72) of type 790531 for thread 13792
Exception: 
Microsoft.Deployment.WindowsInstaller.InstallerException
Failed to reserve port 6516 
   at Microsoft.ManagementExperience.Setup.CustomActions.CustomAction.&lt;&gt;c__DisplayClass30_0.&lt;GenerateDesktopSslCertificate&gt;b__0()
   at Microsoft.ManagementExperience.Setup.CustomActions.CustomAction.RunInstallerAction(Session session, Func`1 action)
MSI (s) (A8!E0) [01:37:44:574]: Closing MSIHANDLE (72) of type 790531 for thread 13792
MSI (s) (A8!E0) [01:37:44:575]: Creating MSIHANDLE (73) of type 790531 for thread 13792
1: Unhandled Exception: Microsoft.Deployment.WindowsInstaller.InstallerException Failed to reserve port 6516 
MSI (s) (A8!E0) [01:37:47:540]: Transforming table Error.

MSI (s) (A8!E0) [01:37:47:540]: Product: Windows Admin Center -- 1: Unhandled Exception: Microsoft.Deployment.WindowsInstaller.InstallerException Failed to reserve port 6516 

MSI (s) (A8!E0) [01:37:47:541]: Closing MSIHANDLE (73) of type 790531 for thread 13792
CustomAction GenerateDesktopSslCertificate returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
MSI (s) (A8:A8) [01:37:47:566]: Closing MSIHANDLE (67) of type 790536 for thread 17904
Action ended 01:37:47: InstallFinalize. Return value 3.
MSI (s) (A8:F0) [01:37:47:572]: Note: 1: 2265 2:  3: -2147287035
-------------------------end-------------------------
I’ve already heard this error actually doesn’t mean any port reservation problem, but concerns to certificate generating. So, what’s the problem with 60-days certificate? And what can I do to install the WAC?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05df3d17-6978-2214-dad9-3eace6d7ee92
* Version Independent ID: ef8e8662-7c07-3118-59b3-0ac30af285f0
* Content: [Windows Admin Center Common Troubleshooting Steps](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/troubleshooting)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/use/troubleshooting.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/use/troubleshooting.md)
* Product: **windows-server-threshold**
* GitHub Login: @jwwool
* Microsoft Alias: **jeffrew**

**Comment by jwwool** [comment]
Does it succeed if you specify antoher port?

**Comment by Vikhrenko** [comment]
I've tried several other ports with high numbers like 42562 surely not used, but I've got the same error. In the meantime, the new version WindowsAdminCenter1809.5.msi became available, but result is the same. And this is an absolutely new install.

**Comment by efcadu** [comment]
I have the same problem. 
And with the newest WindowsAdminCenterPreview1812/

**Comment by borgez** [comment]
Same issue

**Comment by DennisT1** [comment]
This is still a problem under 2306.  Is there a fix in the works?

**Comment by rcpalomino** [comment]
I have the same problem, is there a solution here?
Win10Pro / WAC2306
![grafik](https://github.com/MicrosoftDocs/windowsserverdocs/assets/124862491/90401fd2-41d7-4f7d-ae26-1b82c5f69c8d)

**Comment by rhinoroo** [comment]
Same issue, any fix?

**Comment by HolzapfelIT** [comment]
same problem here.
NO WAY OUT of that?

**Comment by GLComputing** [comment]
Same issue - Windows 2019 / WAC 2306.

**Comment by aude311** [comment]
I was able to install this on a windows server 2 weeks ago, no problems. Today Windows 11 local. This issue I cant get past.

**Comment by DennisT1** [comment]
I've created an issue to reopen this issue.  Hopefully that will get the attention of someone that can address it.

**Comment by jjjjjjjjjjjjjjjjljljlk** [comment]
Same problem... how to fix it??
