### ISSUE TITLE
This would be a great place to explain the differences....

### ISSUE THREAD

**Issue by boomalator** [MicrosoftDocs/windowsserverdocs#2157]
Between hard links, sym links, and junctions.

Or at least link to:
- https://docs.microsoft.com/en-us/windows/desktop/fileio/hard-links-and-junctions (which strangely doesn't include sym links)
- https://social.technet.microsoft.com/Forums/windows/en-US/96813c92-5476-44d3-bdb9-d46fc7f4c901/symlinks-vs-junction-points-vs-hard-links?forum=w7itprogeneral

The best concise explanation I've found so far is https://www.2brightsparks.com/resources/articles/NTFS-Hard-Links-Junctions-and-Symbolic-Links.pdf (Non-Microsoft content).

I mean, ya, sure, if all you want to do is post the same thing that /? gives you, this page is great. If you want to be helpful, explanation would be good.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe72a6d-c0c6-8cc1-fc16-9912594fbe3e
* Version Independent ID: b6ce16a6-8f41-5551-d55f-244238814459
* Content: [mklink](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink)
* Content Source: [WindowsServerDocs/administration/windows-commands/mklink.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/mklink.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
#please-close
