### ISSUE TITLE
Missing RAS and IAS Servers template.

### ISSUE THREAD

**Issue by JohnnyMarauder** [MicrosoftDocs/windowsserverdocs#2163]
Following these docs and there are default templates, but the RAS and IAS Servers template is not there.  Running Server 2016 too and used the Powershell commands to install certificate services.
What did I miss?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daa5ac60-a6aa-b44a-b769-1b264eb3d1ab
* Version Independent ID: 796da0f4-4739-864d-ce7f-769fbffe023b
* Content: [Configure the Server Certificate Template](https://docs.microsoft.com/en-us/windows-server/networking/core-network-guide/cncg/server-certs/configure-the-server-certificate-template)
* Content Source: [WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Configure-the-Server-Certificate-Template.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Configure-the-Server-Certificate-Template.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by JohnnyMarauder** [comment]
Nevermind, missed a step.

**Comment by amang2205** [comment]
For anyone wondering what Johnny refers to as by "missed a step", he's referring to the fact that only the default enabled certificate templates are added. What you need to do is first manage the templates and create the copy of the RAS and IAS Server template.
