### ISSUE TITLE
Typo in link to github repo

### ISSUE THREAD

**Issue by ScottHoff** [MicrosoftDocs/windowsserverdocs#2167]
Currently shows as "OpenSSG Github repo", and it seems like you'd want that to be "OpenSSH Github repo".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a65b1859-4593-6240-5466-949cf4d0d97c
* Version Independent ID: f35f1097-2829-b447-7744-7a1dcb4a1b2c
* Content: [Open](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_overview)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Overview.md)
* GitHub Login: @maertendMSFT

**Comment by TBBle** [comment]
Looks like this has been fixed.

**Comment by illfated** [comment]
Yes, this was resolved in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/66c5dc16adcf911fe5660133dd6c2069bf03bde8, more specifically to the file https://github.com/MicrosoftDocs/windowsserverdocs/commit/66c5dc16adcf911fe5660133dd6c2069bf03bde8#diff-6f20c8fe8497a64f6a10d449e0ff0612.
This ticket can now be closed.

**Comment by illfated** [comment]
#sign-off
#please-close

**Comment by illfated** [comment]
#please-close
