### ISSUE TITLE
Very Confusing Doc

### ISSUE THREAD

**Issue by PJMarcum** [MicrosoftDocs/windowsserverdocs#2170]
I'm really struggling to understand this document. I have manually created a tested a VPN profile on my test PC. "The Windows PowerShell script in Listing 1....", which is MakeProfile.ps1 so why not just say "MakeProfile.ps1, creates two files on the desktop" would read the info from my manually created VPN profile and write out the XML based on that. However it appears that MakeProfile.ps1 actually just created the XML based on the the parameters in the script. If my VPN is not configured exactly as the VPN that the script creates an XML for this is totally useless to me. My ultimate goal here is to deploy the XML from Intune so I go to the section "Configure the VPN client by using Intune" and I'm instructed to "configure the ProfileXML CSP node by using the VPN profile you created in the section Create the ProfileXML configuration files" but as I've already mentioned that XML is not any good for my scenario so I go to option 2, "Or you can use the base EAP XML sample provided below" which again seems to indicate that the VPN is configured a certain way. I want to deploy my VPN profile to devices during Autopilot, I a want it to be always on and use Ikev2 machine certificates for authentication. While I very much appreciate what this document is attempting to do I do not understand why it tells me to create a profile, confirm it works but does not attempt to export that working profile in to an XML. Nor does this tell me how to create an XML that will work in my scenario. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7453068-95eb-2a42-fd0b-553ae593adb0
* Version Independent ID: b39b2cb7-25b1-2af3-4954-dbcc04c836e9
* Content: [Configure Windows 10 Client Always On VPN Connections](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections#bkmk_ProfileXML)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by ABitBA** [comment]
Same here, it's like rocket sience!
Why the hell i need to use a powershell script as a package in configmgr to deploy a vpn. In configmgr there is a VPN section. It's not straight forward what ms do.
