### ISSUE TITLE
Repair-AuthorizedKeyPermission breaks public key authentication

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windowsserverdocs#2171]
I could log in using public key authentication by simply creating the `.ssh\authorized_keys` file with Notepad++ until I executed the `Repair-AuthorizedKeyPermission` command. After executing this I could no longer log in using public key authentication and got a password prompt instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 337c4ea8-1806-92a3-1501-b3ff5dde37bb
* Version Independent ID: c411d389-578d-57c6-cd6e-eaca7f2837db
* Content: [OpenSSH Server Configuration for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* GitHub Login: @maertendMSFT

**Comment by mgkuhn** [comment]
See https://github.com/PowerShell/Win32-OpenSSH/issues/1245#issuecomment-440388604

**Comment by jeffwilcox** [comment]
+1 having a lot of issues here... hoping to learn from others. The docs feel out-of-date.
