### ISSUE TITLE
Azure Files as UPD Target

### ISSUE THREAD

**Issue by sasanmcp** [MicrosoftDocs/windowsserverdocs#2175]
can we use Azure Files as a UPD Target? specially now that they support ACLs?
https://docs.microsoft.com/en-us/azure/storage/files/storage-files-active-directory-enable

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 428e9e07-ca35-27d2-e63a-92930cec0118
* Version Independent ID: 9a452a85-9afa-42d5-f319-bf1c4c50d01d
* Content: [Remote Desktop Services architecture](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/desktop-hosting-logical-architecture)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/Desktop-hosting-logical-architecture.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/Desktop-hosting-logical-architecture.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
