### ISSUE TITLE
Are UNC paths really supported ?

### ISSUE THREAD

**Issue by shueybubbles** [MicrosoftDocs/windowsserverdocs#2176]
I have Server 2012 and attempting to use a UNC path fails.

C:\&gt;wbadmin start systemstatebackup -backuptarget:\\david-yoga\backup\
wbadmin 1.0 - Backup command-line tool
(C) Copyright 2012 Microsoft Corporation. All rights reserved.

ERROR - Command syntax incorrect. Error: -backuptarget:\\david-yoga\backup\. See the command
syntax below.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f45ec88-d0c5-fb27-031c-23cae9fcf9cf
* Version Independent ID: 7f05d1c8-5ef9-e747-1655-8d2b2fce81c3
* Content: [wbadmin start systemstatebackup](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/wbadmin-start-systemstatebackup)
* Content Source: [WindowsServerDocs/administration/windows-commands/wbadmin-start-systemstatebackup.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/wbadmin-start-systemstatebackup.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by shueybubbles** [comment]
hmm it fails with d: too

C:\>wbadmin start systemstatebackup -backupTarget:d:
wbadmin 1.0 - Backup command-line tool
(C) Copyright 2012 Microsoft Corporation. All rights reserved.

ERROR - Command syntax incorrect. Error: -backupTarget:d:. See the command
syntax below.

Syntax: WBADMIN START SYSTEMSTATEBACKUP
    -backupTarget:<VolumeName>
    [-quiet]

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
