### ISSUE TITLE
High Availability - HTTP Redirection Support

### ISSUE THREAD

**Issue by rmilojkovic** [MicrosoftDocs/windowsserverdocs#2178]
I haven't noticed an option in Windows Admin Center High Availability PowerShell script to configure redirection from HTTP to HTTPS, which is available if MSI setup is executed directly. Is there a way to configure it manually?

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
