### ISSUE TITLE
is the 1PB limit still valid for 2019?

### ISSUE THREAD

**Issue by sasanmcp** [MicrosoftDocs/windowsserverdocs#2183]
question is in the subject.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59a34d58-2212-912a-bdd5-3737bf724be4
* Version Independent ID: fe26a043-675e-d702-d499-522b1fdf080f
* Content: [Choosing drives for Storage Spaces Direct](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/choosing-drives)
* Content Source: [WindowsServerDocs/storage/storage-spaces/choosing-drives.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/choosing-drives.md)
* Product: **windows-server-threshold**
* GitHub Login: @cosmosdarwin
* Microsoft Alias: **cosdar**

**Comment by WillyMoselhy** [comment]
No, the limit now is 4 TB 
https://blogs.technet.microsoft.com/filecab/2018/06/27/windows-server-summit-recap/
https://docs.microsoft.com/en-us/windows-server/storage/whats-new-in-storage

**Comment by sasanmcp** [comment]
You mean 4PB?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by WillyMoselhy** [comment]
Yup! 4PB

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
