### ISSUE TITLE
IO Scheduler

### ISSUE THREAD

**Issue by bigpercy** [MicrosoftDocs/windowsserverdocs#2195]
"To change the scheduler for a specific device, in the boot loader's configuration (/etc/grub.conf, for example), add elevator=noop to the kernel parameters, and then restart."

To the uninitiated (like me) this is misleading, simply adding 'elevator=noop' doesn't work, you have to change:
GRUB_CMDLINE_LINUX_DEFAULT="", to
GRUB_CMDLINE_LINUX_DEFAULT="elevator=noop", then run sudo update-grub2.

Also you can change scheduler without restart, using:
echo noop &gt; /sys/block/sda/queue/scheduler,  to check it has worked use:
cat /sys/block/sda/queue/scheduler

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17bc364f-8fd0-b273-50bc-63a0d240f8d0
* Version Independent ID: dd4c402b-1f9f-f3d9-bb98-4b9c2c20f04a
* Content: [Best Practices for running Linux on Hyper-V](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/best-practices-for-running-linux-on-hyper-v)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Best-Practices-for-running-Linux-on-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/Best-Practices-for-running-Linux-on-Hyper-V.md)
* Service: **na**
* Product: **windows-server-threshold**
* GitHub Login: @shirgall
* Microsoft Alias: **kathydav**

**Comment by steven-peralta** [comment]
Single-queue schedulers are deprecated and have been completely removed in Linux 5.0 (more about that [here](https://wiki.archlinux.org/index.php/Improving_performance#Kernel's_I/O_schedulers)). On distros running newer versions of Linux, some users may find that their I/O block has defaulted to using the multi-queue schedulers (mq-deadline, bfq, kyber). It's best to add a udev rule to change the I/O scheduler to `none` and let Hyper-V do all of the scheduling..

The following rule worked for me on Arch Linux. Put this in a file called 60-ioschedulers.rules in /etc/udev/rules.d and reboot:

    ACTION=="add|change", KERNEL=="sd[a-z]*", ATTR{queue/scheduler}="none"

**Comment by jcpro** [comment]
I'm unable to change the scheduler from [none] to noop using any of the instructions on how to do this.  Is there something preventing modifying the I/O scheduler on systems using the linux-azure kernel?

**Comment by james-d-elliott** [comment]
@jcpro noop was depreciated in kernel 5.0.  You can re-enable it with the kernel boot params: scsi_mod.use_blk_mq=0 however none is the multi-queue equivalent of noop.

See this doc: https://wiki.ubuntu.com/Kernel/Reference/IOSchedulers

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
