### ISSUE TITLE
Undocumented formatting for ~

### ISSUE THREAD

**Issue by markyoung2u** [MicrosoftDocs/windowsserverdocs#2196]
Where is this behavior documented fully? It is not in Win10 FOR nor DATE/TIME help
C:\&gt;echo [%time%]
[ 9:00:05.75] &lt;-- There is a SPACE after '['

C:\&gt;echo [%time:~-10%]
[9:00:10.72]

C:]&gt;echo [%time:~-9%]
[:00:15.81]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd23b3f6-0f24-3742-8588-bc3c901b6c8f
* Version Independent ID: 1c5aa825-ee30-5e1b-5f58-b8aa3ccff22c
* Content: [for](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/for)
* Content Source: [WindowsServerDocs/administration/windows-commands/for.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/for.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
