### ISSUE TITLE
SCM storage

### ISSUE THREAD

**Issue by mschauf** [MicrosoftDocs/windowsserverdocs#2197]
Please update infos for Server 2019 SCM storage - e.g. integration of NVDIMM as Read/Write Cache. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 248105ac-a91a-9f38-1331-da2175cd013f
* Version Independent ID: 70098ddb-576f-f7b4-2524-5c5b1ea49e2b
* Content: [Understanding the cache in Storage Spaces Direct](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/understand-the-cache)
* Content Source: [WindowsServerDocs/storage/storage-spaces/understand-the-cache.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/understand-the-cache.md)
* Product: **windows-server-threshold**
* GitHub Login: @cosmosdarwin
* Microsoft Alias: **cosdar**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
