### ISSUE TITLE
"The table below describes the basic types of audit events. " - rephrase...?

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/windowsserverdocs#2200]
I'm not certain whether the events in the table are logged at which audit level; the sentence "The table below describes the basic types of audit events. " *suggests* an audit level of basic will log these events.  Is my interpretation correct?  If so, perhaps rephrase that sentence
"With Audit Level set to Basic, AD FS logs these audit events;"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b97a9e9-7fb7-1938-d023-4c3070511c8e
* Version Independent ID: 3484cb96-6a87-13fb-a015-2cbb37f6f7f4
* Content: [Auditing Enhancements to AD FS in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/technical-reference/auditing-enhancements-to-ad-fs-in-windows-server)
* Content Source: [WindowsServerDocs/identity/ad-fs/technical-reference/auditing-enhancements-to-ad-fs-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/technical-reference/auditing-enhancements-to-ad-fs-in-windows-server.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by anwarmahmood1** [comment]
Incorporating Leon's comment,

"With Audit Level set to Basic, AD FS logs these events to the Security log;"

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
