### ISSUE TITLE
cmdkey targetname argument not fully documented

### ISSUE THREAD

**Issue by gbritton1** [MicrosoftDocs/windowsserverdocs#2201]
The windows cmdkey command can be used to add credentials for accessing remote resources.

[cmdkey](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cmdkey)

For the most part, it is clearly documented. One part that is not is the _targetname_ parameter. For example, I use it to connect to SQL Server databases like this:

`cmdkey /add:my.remote.sqlserver:1234 /user:me /pass:secret`

I discovered that I can add the port number on the end quite by accident. I need it since my company uses non-standard ports for SQL Server. Recently, I discovered that you can also specify:

`cmdkey /add:*.my.domain`

to add a default credential for all remotes in a certain domain. Apparently you can't add a port number to the end (or I can't figure out how).

What I'm now wondering is, can the full specification for _targetname_ be documented?

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
