### ISSUE TITLE
Please document return codes (errorlevel) for use in batch files!

### ISSUE THREAD

**Issue by DRNadler** [MicrosoftDocs/windowsserverdocs#2202]
...and for other commands as well...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c64ec3fa-17a9-0caf-f459-e60f308b1d33
* Version Independent ID: 13249036-78aa-af61-1a50-8ee7aa853876
* Content: [fc](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fc)
* Content Source: [WindowsServerDocs/administration/windows-commands/fc.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/fc.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
