### ISSUE TITLE
Missing URL in "Using NPS in large organizations" section

### ISSUE THREAD

**Issue by KeepSloanWeird** [MicrosoftDocs/windowsserverdocs#2205]
The third bullet in the "Using NPS in large organizations" (https://docs.microsoft.com/en-us/windows-server/networking/technologies/nps/nps-best-practices#using-nps-in-large-organizations) section ends with "For more information see" but never supplies the referenced URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52dc4a44-6ac8-7ddc-23df-4c17558b21ed
* Version Independent ID: 959c9636-dbc0-5d51-0477-ca73583b1294
* Content: [Network Policy Server Best Practices](https://docs.microsoft.com/en-us/windows-server/networking/technologies/nps/nps-best-practices)
* Content Source: [WindowsServerDocs/networking/technologies/nps/nps-best-practices.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/nps/nps-best-practices.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by miejas** [comment]
Should be this, I suppose: https://docs.microsoft.com/en-us/windows-server/networking/technologies/nps/nps-concurrent-auth

**Comment by KeepSloanWeird** [comment]
Yep, that looks right.
