### ISSUE TITLE
Errors in Deploying Storage Spaces Direct

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/windowsserverdocs#2208]
I am attempting to create a S2D cluster using VMs. However the directions at step 3.5 fail for me.

If I try:

```powershell
$s = New-CimSession -ComputerName SSRV1
Enable-ClusterStorageSpacesDirect -PoolFriendlyName 'ReskitS2D' -CimSession $s
```
Then I get this error:

```powershell
Enable-ClusterStorageSpacesDirect : Microsoft recommends deploying SDDC on WSSD [https://www.microsoft.com/en-us/cloud-platform/software-defined-datacenter] certified hardware offerings for 
production environments. The WSSD offerings will be pre-validated on Windows Server 2019 in the coming months. In the meantime, we are making the SDDC bits available early to Windows Server 2019 
Insiders to allow for testing and evaluation in preparation for WSSD certified hardware becoming available. Customers interested in upgrading existing WSSD environments to Windows Server 2019 
should contact Microsoft for recommendations on how to proceed. Please call Microsoft support [https://support.microsoft.com/en-us/help/4051701/global-customer-service-phone-numbers].
At line:1 char:1
+ Enable-ClusterStorageSpacesDirect -PoolFriendlyName 'ReskitS2D' -CimS ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (MSCluster_StorageSpacesDirect:root/MSCLUSTER/...ageSpacesDirect) [Enable-ClusterStorageSpacesDirect], CimException
    + FullyQualifiedErrorId : HRESULT 0x80070032,Enable-ClusterStorageSpacesDirect
    + PSComputerName        : SSRV1
 
Enable-ClusterStorageSpacesDirect : SSRV1: Failed to run CIM method EnableStorageSpacesDirect on the root/MSCLUSTER/MSCluster_StorageSpacesDirect CIM object.  The CIM method returned the following 
error code: 50
At line:1 char:1
+ Enable-ClusterStorageSpacesDirect -PoolFriendlyName 'ReskitS2D' -CimS ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (MSCluster_StorageSpacesDirect:String) [Enable-ClusterStorageSpacesDirect], CimJobException
    + FullyQualifiedErrorId : CimJob_EnableStorageSpacesDirect_50,Enable-ClusterStorageSpacesDirect
    + PSComputerName        : SSRV1
```

Also, the example in 3.5 is not complete. It does not (currently) show creating the CIM session, or show creating a freiendly pool name as suggested.

Is S2D supported using Hyper-V, and VHDX drives with Server 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34f775f8-fb30-69a2-dc05-ea0cdf807b16
* Version Independent ID: e1ed4345-d693-dfb5-35c2-e1e1ec64a383
* Content: [Deploy Storage Spaces Direct](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/deploy-storage-spaces-direct#feedback)
* Content Source: [WindowsServerDocs/storage/storage-spaces/deploy-storage-spaces-direct.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/deploy-storage-spaces-direct.md)
* Product: **windows-server-threshold**
* GitHub Login: @StevenEk
* Microsoft Alias: **stevenek**

**Comment by StevenEk** [comment]
https://support.microsoft.com/en-us/help/4464776/software-defined-data-center-and-software-defined-networking

I believe the article linked above will explain this.

Sincerely,
Steven Ekren
Senior Program Manager
Windows Server
Microsoft

**Comment by doctordns** [comment]
Thanks for the message.

However:
1. The document on deploying S2D makes no mention of this issue. The article says supported by Server 2019, but the steps simply do not work.  The article needs to be updated to say S2D does now work as previously.
2. The KB article you talk about simply gives 'Recommendations'.  It fails to mention that you can not currently install S2D. That KB could be updated to be clearer (ie this does not work (currently?).
3. Finally, are you really saying that S2D in converged/hyper-converged is NOT supported using Hyper-V for cluster servers and VHDXs for disks?  I hope that is not the message. But if it is, then the doc7ument needs to be updated.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by daniel-tron** [comment]
Per this doc, Windows Server Standard Edition doesn't support S2D, S2D side doc should point out this, waste my lots of time.
https://learn.microsoft.com/en-us/windows-server/get-started/editions-comparison-windows-server-2019?tabs=full-comparison
