### ISSUE TITLE
Different port

### ISSUE THREAD

**Issue by SanoKriss** [MicrosoftDocs/windowsserverdocs#2217]
How can I define remote desktop client connection when port is different than default 3389?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588d12d1-fdd1-892a-eb5e-9e2d86302368
* Version Independent ID: 5eceac91-1d90-a663-2856-19e13da59351
* Content: [Remote Desktop clients](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-clients)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md)
* Product: **windows-server-threshold**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Heidilohr** [comment]
@SanoKriss Depending on which client you're using, you can append the port number to the connection name after a colon. For example, MyDesktop:3389. Here are the instructions for the [Windows](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windows#add-a-remote-desktop-connection), [Mac](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-mac#add-a-remote-desktop-connection), [Android](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-android#add-a-remote-desktop-connection), and [iOS](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-ios#add-a-remote-desktop-connection) clients.

**Comment by SanoKriss** [comment]
This works in "old" remote desktop app (mstsc.exe), not in new Microsoft Remote Dektop available from Microsoft store.

**Comment by Delurkdotcom** [comment]
Add this feature please. Specific port is require to use tunneling SSH for example.

**Comment by Harrioson** [comment]
The Microsoft office account is an existing user account on Microsoft account.
https://www.techsovibe.com/microsoft-office-account/

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
