### ISSUE TITLE
Clear-PhysicalDiskHealthData doesn't accept Serial Number

### ISSUE THREAD

**Issue by technion** [MicrosoftDocs/windowsserverdocs#2218]
Hi,
This command format:
```
Clear-PhysicalDiskHealthData -Intent -Policy -SerialNumber 000000000000000 -Verbose -Force
```
Does not appear valid. 
```
[prod-host-01]: PS C:\temp&gt; Clear-PhysicalDiskHealthData -SerialNumber Z4D4QXLP -Intent -Policy -Verbose
VERBOSE: Compiling code to create type
VERBOSE: Attempting to get physical disk uniqueid
Get-PhysicalDisk : Cannot validate argument on parameter 'UniqueId'. The argument is null or empty. Provide an
argument that is not null or empty, and then try the command again.
At C:\temp\Clear-PhysicalDiskHealthData.ps1:182 char:50
+                 $pd = Get-PhysicalDisk -uniqueid $UniqueId
+                                                  ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-PhysicalDisk], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Get-PhysicalDisk

Clear-PhysicalDiskHealthData : Unable to find Physical Disk with UniqueId
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Clear-PhysicalDiskHealthData
```
The alternative presented, to use UniqueID, appears to be the only workable option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d66052f1-eb2d-6766-1fbd-631774a8de71
* Version Independent ID: 33c46626-4758-8533-98e2-59068b5d5f7c
* Content: [Storage Spaces Direct troubleshooting](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/troubleshooting-storage-spaces#physical-disk-healthy-and-operational-status-is-removing-from-pool)
* Content Source: [WindowsServerDocs/storage/storage-spaces/troubleshooting-storage-spaces.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/troubleshooting-storage-spaces.md)
* Product: **windows-server-threshold**
* GitHub Login: @kaushika-msft

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
