### ISSUE TITLE
The 'Isssues' since September taking time and power from me 

### ISSUE THREAD

**Issue by ThomasStumpf** [MicrosoftDocs/windowsserverdocs#2219]
Hi,
Maybe I'm not Right with this here, but it is really imprtant.
Just read what now could possibly all sorted to the strange  'things' lastly.
Now if I'm knowing about I'm thinking it's a great thing especially in times I have to overcome my qualification and would be happy for every help. The time without my Knowledge (Maybe partly my fault) was in many views negative, mental reducing, stress-linked etc.. What I would wish is that I get info where I can find out what was done, how deep was my personal pricacy impacted, and on which 'channels' is still a Connection what Kind else. If bigger privay data went out I'm asking (with penetrating voice) for an overview. Data from Buz I hope mostly untouched / that could be spoke about later. At least I hope so (!) that until know work at the restructuring will always be told before, I also have not a great wanting to slowly fade out of my job, and, like I understood so far it would rather more light help than a nearly full outsource event. A Little bit scary I#m getting, because I know I talked (but in an condition with strong amnesia after), so I'm asking me, what is your profitable part? Sorry for months I was nor productive/helpful and mostly some form of aggressive B. (don't know how much went out..) Would rly pleased if I get my Q answered asap and hope we can talk out a plan which is pos for everybody, that were the 100%opposite and a great thing!
Greets

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200c79d5-e489-fdd1-3d0b-1fb7c1c24a30
* Version Independent ID: 6a6e73a4-13bd-6a8c-543b-d0d8a051e981
* Content: [Install a New Windows Server 2012 Active Directory Child or Tree Domain (Level 200)](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/install-a-new-windows-server-2012-active-directory-child-or-tree-domain--level-200-)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/Install-a-New-Windows-Server-2012-Active-Directory-Child-or-Tree-Domain--Level-200-.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/Install-a-New-Windows-Server-2012-Active-Directory-Child-or-Tree-Domain--Level-200-.md)
* Product: **windows-server-threshold**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
Don't understand what you are asking for @ThomasStumpf. Please clarify what I can do for you.
