### ISSUE TITLE
Windows version information missing

### ISSUE THREAD

**Issue by ojutan** [MicrosoftDocs/windowsserverdocs#2221]
after stepping over this article I tried to use it on Windows 2012 R2, but it seems the registry value is not evaluated there... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65558184-a52d-7b81-c2ed-874fe85078a4
* Version Independent ID: fe830182-032f-8bd4-bd8f-3dd1afd8bb11
* Content: [Use performance counters to diagnose application responsiveness problems on Remote Desktop Session Hosts](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-rdsh-performance-counters)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-rdsh-performance-counters.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-rdsh-performance-counters.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
