### ISSUE TITLE
 Missing the setspn Command

### ISSUE THREAD

**Issue by JediSQL** [MicrosoftDocs/windowsserverdocs#2223]
Please put a link to documentation for the setspn command (writing that documentation if necessary).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a79c2cc-8610-e611-b452-f72927d05031
* Version Independent ID: 94549755-e1e2-b092-743c-625ebde5943b
* Content: [Windows Commands](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands)
* Content Source: [WindowsServerDocs/administration/windows-commands/windows-commands.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/windows-commands.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
