### ISSUE TITLE
Confused by logical conditions

### ISSUE THREAD

**Issue by VaSquirrel** [MicrosoftDocs/windowsserverdocs#2230]
It seems the following, oft repeated note, is confusing and perhaps misleading.
For TLS 1.1 to be enabled and negotiated on servers that run Windows Server 2008 R2, you MUST create the DisabledByDefault entry in the appropriate subkey (Client, Server) and set it to "0". The entry will not be seen in the registry and it is set to "1" by default.

What do you mean by "The entry will not be seen in the registry and it is set to "1" by default"?
Perhaps the word "Otherwise" should begin that sentence?  i.e., "Otherwise, the entry will not be seen in the registry and it the protocol will be assume to be enabled by default."

This is note is repeated in each of the protocol sections.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38fcd9dd-91c8-e79b-5f4d-28a435a8ada8
* Version Independent ID: 0d79a0c8-0b73-c783-4d5c-b107d24acf55
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server-threshold**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@VaSquirrel Thanks for the feedback. This has been rewritten and screenshots added to help clarify.

**Comment by VaSquirrel** [comment]
Thanks Justinha,
Now my devs can't claim to misunderstand :)
