### ISSUE TITLE
wildcard character (\*)

### ISSUE THREAD

**Issue by joefiesta** [MicrosoftDocs/windowsserverdocs#2231]
you use the phrase "wildcard character (\*)".   This is enigmatic.   Character is singular.  Is the \ an escape character or something or should the phrase be "wildcard characterS" (plural)?  

Secondly, the use of quotation marks to enclose items in a filter seems to only be clarified in the examples.  I should not have to read examples to fully understand the syntax.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31d4d309-5a67-bfc2-8bdf-1149260e1af5
* Version Independent ID: 37cf9db4-8ee3-9ade-e271-46d2111fb087
* Content: [taskkill](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/taskkill)
* Content Source: [WindowsServerDocs/administration/windows-commands/taskkill.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/taskkill.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
