### ISSUE TITLE
SSH Agent disappeared after October update

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windowsserverdocs#2235]
I just upgraded to the October update:

```powershell
PS C:\> systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.17763 N/A Build 17763
PS C:\> ssh -V
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
```

I do appear to have the OpenSSH client installed:

```powershell
PS C:\> Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'

Name  : OpenSSH.Client~~~~0.0.1.0
State : Installed

Name  : OpenSSH.Server~~~~0.0.1.0
State : NotPresent
```

However, I am now unable to add my SSH key to the agent:

```powershell
PS C:\> ssh-add
Error connecting to agent: No such file or directory
```

I am also unable to manually start `ssh-agent`:

```powershell
PS C:\> ssh-agent
unable to start ssh-agent service, error :1058
```

This worked before the update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07417484-bd6d-e6f4-110e-e42c2428a369
* Version Independent ID: 844743a6-f67b-421f-9591-13da36b23b14
* Content: [Installation of OpenSSH For Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* GitHub Login: @maertendMSFT

**Comment by cniekerk** [comment]
This resolved the problem in my case:

```powershell
Start-Process PowerShell -Verb RunAs -ArgumentList "Set-Service ssh-agent -StartupType Automatic"
Start-Service ssh-agent
Get-Service ssh-agent | select -property Name, Status, StartType, DisplayName
```

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
