### ISSUE TITLE
On a 2012 R2 KMS/ADBA Host, what is the patch that officially supports 2019 server activations?

### ISSUE THREAD

**Issue by roryschmitz** [MicrosoftDocs/windowsserverdocs#2242]
When this article first came out, fully updated Server 2012 R2 Hosts did not activate 2019 servers, even though it listed it in the chart above.  Has this been fixed?  If so, what's the KB or patch that remedies the problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70e8d8e6-a5fc-9089-5849-a6eb1022d7ca
* Version Independent ID: 6a1b4ab9-8b3d-3cb6-915f-c53e61d39a1d
* Content: [Windows Server 2019 Activation](https://docs.microsoft.com/en-us/windows-server/get-started-19/activation-19)
* Content Source: [WindowsServerDocs/get-started-19/activation-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/activation-19.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by CraigHumphrey** [comment]
This article:
https://blogs.technet.microsoft.com/askpfeplat/2018/10/08/kms-activation-in-windows-server-2019/

Suggests that at least the July 2016 and November 2018 Preview updates are required.  Or any CU after November 2018.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
