### ISSUE TITLE
Problem with adding TLSExtension tags between </AcceptServerName></EapType>

### ISSUE THREAD

**Issue by tofteit** [MicrosoftDocs/windowsserverdocs#2245]
I have a working Microsoft Always On VPN environment using IKEv2. I want to use conditional access through Azure AD on user tunnels.

Followed the steps to setup the conditional access. I'm trying to update the profile XML file with the TLSExtensions tags between &lt;/AcceptServerName&gt; and &lt;/EapType&gt; XML:

&lt;TLSExtensions xmlns="https://www.microsoft.com/provisioning/EapTlsConnectionPropertiesV2"&gt;&lt;FilteringInfo xmlns="https://www.microsoft.com/provisioning/EapTlsConnectionPropertiesV3"&gt;&lt;EKUMapping&gt;&lt;EKUMap&gt;&lt;EKUName&gt;AAD Conditional Access&lt;/EKUName&gt;&lt;EKUOID&gt;1.3.6.1.4.1.311.87&lt;/EKUOID&gt;&lt;/EKUMap&gt;&lt;/EKUMapping&gt;&lt;ClientAuthEKUList Enabled="true"&gt;&lt;EKUMapInList&gt;&lt;EKUName&gt;AAD Conditional Access&lt;/EKUName&gt;&lt;/EKUMapInList&gt;&lt;/ClientAuthEKUList&gt;&lt;/FilteringInfo&gt;&lt;/TLSExtensions&gt;
as described in step 3.

When I try to add the profile through PowerShell locally on a device (not through an Intune configuration profile), I get an response that the profile couldn't be added due to an unknown error. I suspect a syntax error, but when I run it through XML checkers such as https://codebeautify.org/xmlvalidator is passes. The profile works, if I leave out the above, but then it will not use the Azure AD certificate as described in step 2.

Any suggestions on how to fix it? -As mentioned earlier I don't want to use a configuration profile in Intune, but manually deploy it through SCCM or PowerShell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 081d2fcb-f8d2-2b5b-d6d4-13d053ef179b
* Version Independent ID: 583334b3-7c78-a3a9-e73e-d9cfb3a74224
* Content: [Create OMA-DM based VPNv2 Profiles to Windows 10 devices](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/vpn-create-oma-dm-based-vpnv2-profiles)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/vpn-create-oma-dm-based-vpnv2-profiles.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/vpn-create-oma-dm-based-vpnv2-profiles.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by ph1ll** [comment]
I've just run into the same problem. The URLs for the xmlns should be HTTP not HTTPS, if you use the following XML it will work.

```xml
<TLSExtensions xmlns="http://www.microsoft.com/provisioning/EapTlsConnectionPropertiesV2">
<FilteringInfo xmlns="http://www.microsoft.com/provisioning/EapTlsConnectionPropertiesV3">
    <EKUMapping>
    <EKUMap>
        <EKUName>AAD Conditional Access</EKUName>
        <EKUOID>1.3.6.1.4.1.311.87</EKUOID>
    </EKUMap>
    </EKUMapping>
    <ClientAuthEKUList Enabled="true">
    <EKUMapInList>
        <EKUName>AAD Conditional Access</EKUName>
    </EKUMapInList>
    </ClientAuthEKUList>
</FilteringInfo>
</TLSExtensions>
```
