### ISSUE TITLE
DNS Admins?

### ISSUE THREAD

**Issue by dstreefkerk** [MicrosoftDocs/windowsserverdocs#2250]
> The DNS Admins group, unlike more highly privileged groups, has few powerful rights across Active Directory, although members of this group have been delegated permissions that allow them to administer DNS.

This wording makes it sound like the DNS Admins group can't be abused. Perhaps the article could be updated to indicate that is not the case, and that the group's membership can be abused to gain SYSTEM-level access on a DC in certain scenarios?
* https://medium.com/@esnesenon/feature-not-bug-dnsadmin-to-dc-compromise-in-one-line-a0f779b8dc83
* https://adsecurity.org/?p=4064
* http://www.labofapenetrationtester.com/2017/05/abusing-dnsadmins-privilege-for-escalation-in-active-directory.html

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19620533-3f60-a1cb-a679-ff6ff5dde2bc
* Version Independent ID: 54583dac-de23-b64c-3396-fac964724595
* Content: [Implementing Least-Privilege Administrative Models](https://docs.microsoft.com/en-au/windows-server/identity/ad-ds/plan/security-best-practices/implementing-least-privilege-administrative-models)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Implementing-Least-Privilege-Administrative-Models.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Implementing-Least-Privilege-Administrative-Models.md)
* Product: **windows-server-threshold**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
@dstreefkerk I added some language to the section that should cover this and will be published in the next few days. Thanks for calling that out.
