### ISSUE TITLE
Mount-SRDestination throws error "Element not found" in Windows Server 2019

### ISSUE THREAD

**Issue by cnschindler** [MicrosoftDocs/windowsserverdocs#2251]
I have a lab for testing purposes. Recently I rebuilt my lab with Windows Server 2019. Now when I use Mount-SRDestination an error is thrown that the system is unable to mount the group with "element not found". Windows System Error 1168. Any comments on this? Any help would be appreciated.. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79167b1b-8849-9fe5-3ba8-c64e1b541bf3
* Version Independent ID: d837090d-6406-d5b5-562d-98bd3039b49a
* Content: [Known issues with Storage Replica](https://docs.microsoft.com/en-us/windows-server/storage/storage-replica/storage-replica-known-issues)
* Content Source: [WindowsServerDocs/storage/storage-replica/storage-replica-known-issues.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-replica/storage-replica-known-issues.md)
* Product: **windows-server-threshold**
* GitHub Login: @nedpyle
* Microsoft Alias: **nedpyle**

**Comment by nedpyle** [comment]
I'd expect that error with a missing or typed RG name. Can you post the commands and outputs of 

Get-SRGroup

and your mount command?

Note: this is not a support area, it's for documentation issues. I really recommend you go to the MS Windows Server Support Forums https://social.technet.microsoft.com/Forums/windowsserver/en-US/home?forum=ws2019 or open a support case https://support.microsoft.com/en-us/contactus/. I will not be allowed to get logs or PII from you through this comment section.
