### ISSUE TITLE
How about the other limits

### ISSUE THREAD

**Issue by storkinsj** [MicrosoftDocs/windowsserverdocs#2252]
Great to do a comprehensive article on NTFS. Unfortunately it is not comprehensive. It does not answer questions like :
How many folders can I have under c:\
How many files can I have under c:\
How many files can I have in a folder

etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30461547-c60c-0d37-47ef-4fe4cb35f4e5
* Version Independent ID: d28e956c-87b6-67c1-38e0-afc06ae98f0b
* Content: [NTFS overview](https://docs.microsoft.com/en-us/windows-server/storage/file-server/ntfs-overview)
* Content Source: [WindowsServerDocs/storage/file-server/ntfs-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/ntfs-overview.md)
* Product: **windows-server-threshold**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
