### ISSUE TITLE
Firewall rules for Server 2019

### ISSUE THREAD

**Issue by DSPatrick** [MicrosoftDocs/windowsserverdocs#2254]
Is there an update for problems with Server 2019? 
https://social.technet.microsoft.com/Forums/windowsserver/en-US/cf047df5-ed4a-46b9-9564-c9db5a9bc8dc/windows-server-2019-default-nps-firewall-rules-port-1812-udp-not-working?forum=ws2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a87054fe-8196-0008-858e-adbc35c41d6b
* Version Independent ID: 78b7fa57-c93e-bb45-d865-502bb704932f
* Content: [Configure Firewalls for RADIUS Traffic](https://docs.microsoft.com/en-us/windows-server/networking/technologies/nps/nps-firewalls-configure)
* Content Source: [WindowsServerDocs/networking/technologies/nps/nps-firewalls-configure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/nps/nps-firewalls-configure.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by pyoungberg** [comment]
Any update?
