### ISSUE TITLE
What is the difference between Windows Server 2019 and Windows Server, version 1809

### ISSUE THREAD

**Issue by devinmcafee** [MicrosoftDocs/windowsserverdocs#2262]
The OS Build numbers are the exact same for both "Windows Server, version 1809" and "Windows Server 2019". Are the 2 builds the same?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 738f3265-e459-da12-0f2c-d4fc1eff4fff
* Version Independent ID: 679afb77-9852-4608-291c-74bf2739890f
* Content: [Windows Server release information](https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info)
* Content Source: [WindowsServerDocs/get-started/windows-server-release-info.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/windows-server-release-info.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by hoyty76** [comment]
One is SAC and one is LTSC. One will be supported for 30 months and one will be supported for 10 years. One has a desktop version and one is meant for container / VM usage.

**Comment by daveba** [comment]
@devinmcafee I will close this issue now.  Please reopen if you need further answers.  Thanks!

**Comment by ghkamfung** [comment]
Do I unsderstand correctly?
SAC: 30 months, has desktop version
LTSC: 10 years, container / VM

LTSC also has desktop version BUT intended for container?
