### ISSUE TITLE
Windows Server 2019 was released in 1809 not 1804

### ISSUE THREAD

**Issue by WillyMoselhy** [MicrosoftDocs/windowsserverdocs#2263]
https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types#required-updates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b739fc5c-de44-7299-28a5-21e95bccf400
* Version Independent ID: 3a607530-01e6-e73a-0168-4e03a262a59c
* Content: [Understanding and using Hyper-V hypervisor scheduler types](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types#required-updates)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types.md)
* Product: **windows-server-hyper-v**
* GitHub Login: @allenma
* Microsoft Alias: **allenma**

**Comment by evan-morris** [comment]
Easy doc fix, but 5 months later...

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
