### ISSUE TITLE
The sub-headings in section 1.4 are out of place

### ISSUE THREAD

**Issue by davidpaMSFT** [MicrosoftDocs/windowsserverdocs#2266]
The sub-headings (e.g. "Upstream servers") in section 1.4 are out of place and step 1. is followed by step 1. under "To choose update languages for a downstream server".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa4be2a-4045-4135-353a-ed882ada9402
* Version Independent ID: c43f3896-9f9b-2754-9b5d-d73f9650592b
* Content: [Plan Your WSUS Deployment](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/plan/plan-your-wsus-deployment#BKMK_1.4.)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/plan/plan-your-wsus-deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/plan/plan-your-wsus-deployment.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
