### ISSUE TITLE
Missing a step, I think

### ISSUE THREAD

**Issue by donyoung** [MicrosoftDocs/windowsserverdocs#2267]
If you need to change the profile and re-deploy you will need to add to the PowerShell script to remove the existing device tunnel, then the script will create a new connection.  I ran into this re-deploying with a new route.  I used the following  code:

try
{
	Get-VpnConnection -AllUserConnection -Name $ProfileName | Remove-VpnConnection -Force
}
catch [Exception]
{
    $Message = "Unable to remove existing outdated instance(s) of $ProfileName profile: $_"
    Write-Host "$Message"
    exit
}
 And I put it just before the line "$session = New-CimSession"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06629f78-c4b1-4345-578c-596e92dff977
* Version Independent ID: e3686eef-c2c6-5a21-ac76-6bac575e7cfc
* Content: [Configure the VPN device tunnel in Windows 10](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/vpn-device-tunnel-config)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/vpn-device-tunnel-config.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/vpn-device-tunnel-config.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
