### ISSUE TITLE
Should specify only local folders are valid

### ISSUE THREAD

**Issue by AaronBertrand** [MicrosoftDocs/windowsserverdocs#2270]
I spent some time developing a solution to delete files older than x in a folder, and didn't find out until I was done testing locally and deployed to a server environment that `forfiles` does not support UNC paths. This should be called out somewhere in the doc. (https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/forfiles)

**Comment by AaronBertrand** [comment]
Ugh, were **not** supported.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
