### ISSUE TITLE
There should be a warning that NPS role cannot be installed on Server Core

### ISSUE THREAD

**Issue by altwohill** [MicrosoftDocs/windowsserverdocs#2273]
There should be a warning that the NPS role cannot be installed on Server Core.
The only documentation I could find that mentioned this is for 2012R2     https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh831683(v=ws.11)#special-considerations-for-managing-the-role-on-the-server-core-installation-option

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ab1fbbd-6f89-9fa6-1e82-185f0cbfcd03
* Version Independent ID: f3ae30f5-1e13-3295-9380-4b61df400d0d
* Content: [Install and Configure the NPS Server](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-nps)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-nps.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-nps.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by doctordns** [comment]
Addressed in PR #2306

**Comment by visualblind** [comment]
Seriously, where is that little tidbit in the mountains of documentation regarding how to install NPS? Thanks for wasting more time than necessary, Microsoft. Added up, I'm sure everyone would suck the air out of the room due to the gasp being so large.
