### ISSUE TITLE
Error: Element IsMounted not found 

### ISSUE THREAD

**Issue by fentor** [MicrosoftDocs/windowsserverdocs#2275]
Great guide - works fine however, when I manage Storage Replica via the Windows Admin Centre.  Whenever I switch the direction of the replica I get the following error in the Event log 

Error: Element IsMounted not found.
(this is directed at the node of the source) 

The Relationship fails over as expected.   Is this a warning that the drive was mounted prior to the failover? 

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f58b836-4eb3-562a-9ca1-92202c267db0
* Version Independent ID: f8674fad-5571-57e1-8afd-cf21cb044525
* Content: [Server-to-server storage replication](https://docs.microsoft.com/en-us/windows-server/storage/storage-replica/server-to-server-storage-replication)
* Content Source: [WindowsServerDocs/storage/storage-replica/server-to-server-storage-replication.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-replica/server-to-server-storage-replication.md)
* Product: **windows-server-threshold**
* GitHub Login: @nedpyle
* Microsoft Alias: **nedpyle**

**Comment by win2000b** [comment]
Same issue here.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
