### ISSUE TITLE
Is the documentation outdated?

### ISSUE THREAD

**Issue by jflopezfernandez** [MicrosoftDocs/windowsserverdocs#2284]
When you click on the link "Configure NLA for RDS Connections," the page it links you to says it is no longer being updated because it is part of the Windows 2008 server documentation. It does have a button to go to the recommended version, but that only links to the Windows Server landing page, not an updated version of the configuration documentation.

Does the page being linked to contain functional documentation? Or is the updated documentation just not linked yet?

Link: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc732713(v=ws.11)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71cfbf1a-c5b7-df0f-8194-6ebc03afcc7d
* Version Independent ID: f36b567f-aa48-2c8f-4908-b1fe18cd2842
* Content: [Remote Desktop - Allow access to your PC](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-allow-access)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-allow-access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-allow-access.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
