### ISSUE TITLE
Parameter descriptions seem mixed up, missing how to find categories.

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/windowsserverdocs#2286]
Part 1:
The description for /user talks about categories and subcategories.
The description for /category talks about user (in the second sentence)
Part 2:
Please describe or link to a description where/how to find categories.
Regards
Bart

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6277645c-a679-86bd-3678-ce0f22e0fbd7
* Version Independent ID: 186581ae-c5d9-e98c-ffb8-d36c8fc56de3
* Content: [auditpol set](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/auditpol-set)
* Content Source: [WindowsServerDocs/administration/windows-commands/auditpol-set.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/auditpol-set.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
