### ISSUE TITLE
Local account must be used for setup and install, not a Microsoft account.

### ISSUE THREAD

**Issue by juliuso** [MicrosoftDocs/windowsserverdocs#2288]
It should be prefaced in the article that setup and installation will likely fail when signed into Windows 10 with a Microsoft account. After a clean install of W10 v.1809, I was getting errors in PowerShell after installing OpenSSH server, then following the steps for the Initial Configuration. ssh would failed to start, and couldn't complete the remaining steps. Changing to a local account and repeating the installation process worked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07417484-bd6d-e6f4-110e-e42c2428a369
* Version Independent ID: 844743a6-f67b-421f-9591-13da36b23b14
* Content: [Installation of OpenSSH For Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* GitHub Login: @maertendMSFT

**Comment by metathinker** [comment]
I didn't see anything like this happen on my computer. I can install and set up the OpenSSH client and server features just fine when signed in using my Microsoft account which is an administrator on the computer. And I can log in to the server using `ssh microsoft.account.username@microsoft.account.domain@computer.hostname` just fine.

**Comment by daveba** [comment]
@juliuso I will close this issue now.  Please reopen if you are still experiencing the same problem.
