### ISSUE TITLE
Subcategory needs better explaining

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/windowsserverdocs#2289]
The subcategory syntax as described is accepted by the auditpol command yet when following its syntax, it always completes the setting for the whole category. 
So either document how we get the GUID for a subcategory or tell us how to get the syntax working. 
For instance 
auditpol /set /category:"Object Access" /subcategory:"SAM" /success:disable
applies the change to the whole category NOT just to the subcategory. Maybe the documentation is not correct or the auditpol application does not work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e25b2b95-37c3-bc34-7c3d-d8f5351f63f9
* Version Independent ID: 4e2abc4c-64e0-ba5b-2176-14a908678cb2
* Content: [auditpol get](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/auditpol-get)
* Content Source: [WindowsServerDocs/administration/windows-commands/auditpol-get.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/auditpol-get.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
