### ISSUE TITLE
HA script doesn't apply CA signed certificate

### ISSUE THREAD

**Issue by Bman21** [MicrosoftDocs/windowsserverdocs#2292]
I've successfully implemented WAC in high availability on my S2D cluster. (1812 preview installer and HA script).

I specified a CA signed PFX file and entered its password (as per the HA documentation), the PS script successfully imports the cert onto all cluster nodes, however it also generates its own self-signed certificate, and applies that to Windows Admin Center.

Running commands to update the certificate (only) results in the script auto-generating another self-signed certificate, and setting that instead of the CA cert.

**Comment by doctordns** [comment]
Can you be more specific? WHAT HA script are you referring to?

**Comment by doctordns** [comment]
This does not appear to be a documentation issue. The OP might get tech assistance at: https://social.technet.microsoft.com/Forums/windowsserver/en-us/home?category=windowsserver
