### ISSUE TITLE
Verify the current Windows Update setting:

### ISSUE THREAD

**Issue by teklone** [MicrosoftDocs/windowsserverdocs#2294]
Command needs to be change to:

cd /d %systemroot%\system32
Cscript scregedit.wsf /AU /v 

OR 

%systemroot%\system32\Cscript %systemroot%\system32\scregedit.wsf /AU /v 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c87e4b6-b5d7-bd9a-7b56-efb0bcaf5a81
* Version Independent ID: c161ac24-d4ac-df44-1867-8380b15ec98d
* Content: [Patching Server Core](https://docs.microsoft.com/en-us/windows-server/administration/server-core/server-core-servicing)
* Content Source: [WindowsServerDocs/administration/server-core/server-core-servicing.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/server-core/server-core-servicing.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap

**Comment by lukealton** [comment]
Is wuauclt.exe /detectnow actually still a viable way to patch Server Core? This other document shows that feature as removed in Windows Server 2016:
https://docs.microsoft.com/en-us/windows-server/get-started/deprecated-features

Can we clarify in this document or the other if this is still a viable method for patching Server Core anymore?
