### ISSUE TITLE
Add additional info to change anchor claimtype when Azure MFA

### ISSUE THREAD

**Issue by samueldeva** [MicrosoftDocs/windowsserverdocs#2295]
Add additional info to change anchor claimtype when Azure MFA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 404ed1e0-3d50-5f22-4721-ba79ce56589f
* Version Independent ID: 7cb551c4-cdb2-d96d-4167-1bb074064453
* Content: [Additional authentication methods in AD FS 2019](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/additional-authentication-methods-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Additional-Authentication-Methods-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Additional-Authentication-Methods-AD-FS.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
