### ISSUE TITLE
This page really needs a diagram 

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/windowsserverdocs#2300]
It would be good to have a diagram showing the components involved in deploying a guarded fabric and shielded vms.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cebcf3a-aeb6-cb12-7c3d-682a128885de
* Version Independent ID: 7cdf9180-2620-badc-d960-ef4abf3788b3
* Content: [Guarded fabric and shielded VMs](https://docs.microsoft.com/en-gb/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-and-shielded-vms-top-node#feedback)
* Content Source: [WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-and-shielded-vms-top-node.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-and-shielded-vms-top-node.md)
* Product: **windows-server-threshold**
* GitHub Login: @rpsqrd
* Microsoft Alias: **justinha**

**Comment by rpsqrd** [comment]
Hey @doctordns thanks for sharing your feedback!

We have a simple diagram in our [Quick Start page](https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-deployment-overview#step-3-extract-identities-hardware-baselines-and-code-integrity-policies) and a video on the [deployment overview page](https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-deploying-hgs-overview). Are either of those what you're looking for, or is there a different type of diagram we should build for this page?

**Comment by doctordns** [comment]
The diagram just above 'step 3' in the Quick Start Page is partly what I had in mind. And it's a good start. However - that diagram adds components (ie SQL, Azure Pack, and VMM) that are missing from the overview page.

What I had in mind for the overview page was a picture the HGS Cluster, the guarded hosts and the protected VMs.

Also, the overview page should, in my view, address:
1. The diagram should show the components advised in the page (so the HGS cluster, the guarded VM hosts and the guarded VMs). 
1. Does the HGS NEED to be a cluster? If so why? And will a 'cluster' of one node work?
2. Is VMM, SQL and Azure Pack required? What added value do they provide? If you omit one, does the HGS scheme fall apart? If they are useful, then overview details should be on the start page and shown in the diagram.
3. The VMs - what do they look like? The noted diagram does not show the guarded VMs.
4. Possibly one diagram to show the minimum HGS deployment, then another diagram adding in all the cool stuff.

HGS is a complex technology. At first sight is kind of appears this is only for Azure and hosters, but I believe there is value for on-premise implementations for some organisations (think of a multinational conglomerate using internal data centres).

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
