### ISSUE TITLE
More PowerShell please

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/windowsserverdocs#2304]
This page shows how to get started. In step 4, the user loads the RSAT tools - but then NEVER USES THEM?

I'd prefer to see TWO pages here: one for the folks that haven't yet learned PowerShell and want GUI instructions and the other for those in the know and just want to do it in PowerShell (I am in the latter camp FWIW!).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca6dbe44-5125-6d2b-4720-f5fdd8515e85
* Version Independent ID: 5d8fbf3f-4dae-c9b1-e306-c522db783ef4
* Content: [Quick start for guarded fabric deployment](https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-deployment-overview#step-3-extract-identities-hardware-baselines-and-code-integrity-policies)
* Content Source: [WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-deployment-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-deployment-overview.md)
* Product: **windows-server-threshold**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@doctordns Thanks for the feedback! @rpsqrd to keep me honest but I don't think there is a PS option to create the shielded VM template disk; there is only the wizard option included in the RSAT.

**Comment by rpsqrd** [comment]
RSAT tools include both our GUI and PowerShell tools for shielded VMs, so it is required even if you're using TemplateDiskWizard.exe

@Justinha We should probably document the PS cmdlet (Protect-TemplateDisk) as an alternative on the full [Windows template disk page](https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-create-a-shielded-vm-template#prepare-and-protect-the-vhdx-with-the-template-disk-wizard). It looks like we already have it documented with the cmdlet for [Linux](https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-create-a-linux-shielded-vm-template#protect-the-template-disk).

Same feedback applies to our shielding data file wizard -- it has a corresponding cmdlet (New-ShieldingDataFile) that isn't documented on the [shielding data file page](https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-tenant-creates-shielding-data).

I am traveling this week but can probably get to this next week, unless you have time to write it up sooner?

**Comment by Justinha** [comment]
@rpsqrd thanks Ryan! I'll submit the pull request tomorrow and add you as a reviewer. The New-ShieldingDataFile example will need help for sure.

**Comment by doctordns** [comment]
@rpsqrd  thanks for the comment.
1. Since the RSAT tools include the GUI, this page could usefully say something along the lines of 'install the RSAT tools to get the GUI'.
2. Yes please to documenting the cmdlets!
3. Does that mean that there IS a way to do all this with cmdlets? If so, then can you reconsider the original suggestion and either have a page of two parts (install via GUI, install via PowerShell) or have two pages that show, respectively, the GUI and PowerShell approach.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
