### ISSUE TITLE
What do those paths refer to?

### ISSUE THREAD

**Issue by SylwesterKogowski** [MicrosoftDocs/windowsserverdocs#2308]
What is this "VPNv2/ProfileName/DnsSuffix"?
Is this a path to some configuration ? Registry? What is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c50c357-dbcc-c94e-e445-b023bd92b586
* Version Independent ID: 7953a501-32bb-e482-e62f-a5a881d6a355
* Content: [Always On VPN features](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/vpn-map-da)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/vpn-map-da.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/vpn-map-da.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by citizen-az** [comment]
It's how you would go about configuring the profile XML - for example

<DnsSuffix>.examplednssuffix.com</DnsSuffix>

Check out the following links for more info on this:

https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-csp 

https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections
