### ISSUE TITLE
Incorrect Contributor Info on Article

### ISSUE THREAD

**Issue by EisenbergEffect** [MicrosoftDocs/windowsserverdocs#231]
**Updating Issue Description**

The published page is displaying incorrect contributor info for this article:

https://github.com/microsoftdocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/honolulu/deployment-guide.md

This may be a docs publishing platform bug. Exploring...

**Comment by dend** [comment]
@EisenbergEffect it is published, though. This repo runs out of the `master` branch, not `live` like others (this branch does not exist here). Compare the contributions from @WithinRafael and you will notice that those are on the site.

**Comment by EisenbergEffect** [comment]
I wasn't aware that was even possible. In my understanding, live is required. The other publish issue, I was able to validate that content was not present on the site.

**Comment by dend** [comment]
@EisenbergEffect yep, some teams skip the middle validation. I wonder if this has anything to do with how the commit conflicts were potentially resolved (if any) that might've caused Git history rewrite. Although it does show everything in the Git tree, so something is amiss.

**Comment by EisenbergEffect** [comment]
Note, the contributors displayed do match the publish date. The publish date does not match master either.

**Comment by EisenbergEffect** [comment]
Is this a private/public repo pair?

**Comment by dend** [comment]
The publish date is being picked up from metadata @EisenbergEffect 

![image](https://user-images.githubusercontent.com/1389609/31711417-da2e9ff4-b3ac-11e7-8b3b-2172f011ccdc.png)

**Comment by EisenbergEffect** [comment]
Notice the discrepancy between the updated_at and ms.date.

**Comment by EisenbergEffect** [comment]
😆

**Comment by dend** [comment]
@EisenbergEffect yep, see above. I think that's because whoever is updating the article has to manually change `ms.date` and they did not do so here.

**Comment by EisenbergEffect** [comment]
Is it possible that the contrib info is retrieved based on ms.date?

**Comment by EisenbergEffect** [comment]
Another note is that the commit urls are pointing to VSTS. There could be a VSTS/GitHub feature parity issue here as well.

**Comment by dend** [comment]
@EisenbergEffect good catch. That's the likely problem, since VSTS has no concept of GitHub IDs to link to. This still sounds like a bug that we should track and fix, otherwise it does seem like we are ignoring giving credit.

**Comment by EisenbergEffect** [comment]
I agree. Let's see what Ying says. We can update this thread based on that.

**Comment by brianlic-msft** [comment]
There is a public/private pair here and the live branch publishes out of the private repo. VSTS is supposed to pull in the GitHub profile information to show contributors.

**Comment by EisenbergEffect** [comment]
It looks like there's some on-boarding to a VSTS-related feature on our end that needs to happen. We're following up with engineering.

**Comment by riverar** [comment]
Any updates on this?

**Comment by EisenbergEffect** [comment]
@herohua Were you able to pick up this issue related to VSTS/GitHub repo pairing? I think @yunyunyunyun was working on the VSTS parity work items, but I wasn't sure what the status of this was.

**Comment by riverar** [comment]
Heartbeat: Still broken. 🌵

**Comment by brianlic-msft** [comment]
@EisenbergEffect were you able to track this down?

**Comment by EisenbergEffect** [comment]
@herohua can you comment on the above?

**Comment by EisenbergEffect** [comment]
Also @cillroy can you take a look at this and dig in with @herohua on what's going on here? It's very important that we get any issues regarding correct contributor attribution fixed.

**Comment by lizap** [comment]
Has this been fixed? And if so, can I please close this issue? In the GitHub source, we see 5 contributors. On the published article, 5 contributor bubbles. In the VSTS repo, the true source for the article, 5 contributors, all of whom are displayed on the published article.

**Comment by EisenbergEffect** [comment]
Let's close this out. It seems to be fixed. I'll circle back with @herohua internally and double confirm as well.

**Comment by riverar** [comment]
This is not fixed. Come on guys, all you had to do was load https://docs.microsoft.com/en-us/windows-server/manage/honolulu/deployment-guide and notice my boring face isn't there.

**Comment by EisenbergEffect** [comment]
Apologies @riverar Next time I will confirm for myself.

@herohua Can we get this fixed please? It's a bug that's apparently still present after 3 months.

@cillroy Can you help drive any fixes that are needed here? Please escalate this as a top priority fix for S131.

**Comment by EisenbergEffect** [comment]
Actually, @newyunyunyunyun Can you follow up on this instead of @cillroy This may in fact be a VSTS parity issue. This is high priority.

**Comment by riverar** [comment]
We're approaching 5 months now on this issue. Just a very friendly thorn 🌵 to keep in everyone's side. 

☮️

**Comment by dend** [comment]
ACK. Raising this with engineering. @riverar

**Comment by cillroy** [comment]
@riverar this had slipped through the cracks - sorry about that, I was not used to monitoring github comments.  Let me follow up with @dend

**Comment by herohua** [comment]
@riverar , GitHub page (https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/honolulu/deployment-guide.md) also fails to show up your contribution info. Can you confirm your email address (rafael@withinwindows.com) is linked to your GitHub account?

FYI @dend @cillroy

**Comment by riverar** [comment]
Mentioned earlier, see https://github.com/MicrosoftDocs/windowsserverdocs/pull/199. Also, read up, the core issue appears to be the site repro is served up from non-master.

**Comment by dend** [comment]
@riverar we are currently looking at the source of the problem - likely it was a squash merge, that resulted in losing contribution info. This will help us better craft the policy in the future. 

In the meantime, I think we can properly ACK the contribution via an empty PR - if you can open one with a minor file change (e.g. space), that way your name will be associated with the article.

cc: @cillroy @herohua

**Comment by brianlic-msft** [comment]
This change should go live in a few hours.

**Comment by dend** [comment]
@riverar attribution is now properly displayed on the [live page](https://docs.microsoft.com/en-us/windows-server/manage/honolulu/deployment-guide):

![image](https://user-images.githubusercontent.com/1389609/37128186-c3ce7bfe-222d-11e8-85d3-562baf2ef625.png)

Apologies once again for the mix-up! We are taking precautions to make sure attribution is preserved in the future.
