### ISSUE TITLE
No details for 'Adding your own PowerShell script'

### ISSUE THREAD

**Issue by comnam90** [MicrosoftDocs/windowsserverdocs#2311]
Can the section for 'Adding your own PowerShell script' please be updated to have some detail?
https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/extend/guides/powershell#adding-your-own-powershell-script

It's been empty for over 6 months

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08b73b6a-17c3-e5e4-b77f-56568f01dc86
* Version Independent ID: f0d4a76f-1aec-ba4f-4596-6dbc94e1d11a
* Content: [Using PowerShell in your extension](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/extend/guides/powershell#adding-your-own-powershell-script)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/extend/guides/powershell.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/extend/guides/powershell.md)
* Product: **windows-server-threshold**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
