### ISSUE TITLE
"Connection Center"

### ISSUE THREAD

**Issue by ryanhelmer** [MicrosoftDocs/windowsserverdocs#2314]
"To add a remote resource:

In the Connection Center click +"

I'm supporting this for an end user; I don't have a Mac. They are sending screenshots. Nothing is labeled Connection Center; it just shows "Microsoft Remote Desktop" in the title bar, then there are buttons for "Add Desktop" and "Import". Where does it call something "Connection Center"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 526c6220-c5f5-7dce-3239-66e5134cd40e
* Version Independent ID: 598ceeef-0f46-fff1-8528-45c12e112612
* Content: [Get started with Remote Desktop on Mac](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-mac)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
