### ISSUE TITLE
Multiple question on host caching

### ISSUE THREAD

**Issue by stgeorgi** [MicrosoftDocs/windowsserverdocs#2321]
In step 7 can we add link to https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/understand-the-cache in order to indicate that the option of None is recommended 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 706b2e1a-e90e-d70e-431f-5476b0ca52c1
* Version Independent ID: 70721d4c-642c-61f8-6c61-84b1dd1ae96c
* Content: [Deploy a two-node Storage Spaces Direct SOFS for UPD storage in Azure](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-storage-spaces-direct-deployment)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-storage-spaces-direct-deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-storage-spaces-direct-deployment.md)
* Product: **windows-server-threshold**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
