### ISSUE TITLE
No multi-monitor option in remote desktop app

### ISSUE THREAD

**Issue by leeray86** [MicrosoftDocs/windowsserverdocs#2322]
Love the look and feel of the new remote desktop client but as of version 10.1.1088.0 there is no option to use all my monitors for the remote session. Hope this is coming in a future release.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e60920-eb48-3d03-0cbb-edf4f0afd7e1
* Version Independent ID: 8b50ceec-5da0-b064-3fa9-bfe408bef243
* Content: [What's new for Remote Desktop on Windows?](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windows-whatsnew)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windows-whatsnew.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windows-whatsnew.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by staromlynski** [comment]
When can we expect multi-monitor option be active.?

**Comment by ChrisThomas-gamer** [comment]
no multi-monitor is a dealbreaker for me.  will just have to trudge along with the non store version.  :|

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
