### ISSUE TITLE
Would be nice to detail the logs that used for setup and day to day use.

### ISSUE THREAD

**Issue by Absoblogginlutely** [MicrosoftDocs/windowsserverdocs#2326]
Attempting to install when a 2016 server doesn't meet the prerequisites gives the error "This server does not comply with some DirectAccess prerequisites. Resolve all issues before proceeding with DirectAccess deployment" but nowhere does it state what the prerequisite failure is.
The gui should either detail the failures  for the best user friendly experience or the documentation should detail where to find the results of this check.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f8bd59-ec12-39a5-b9d9-ef516ca15244
* Version Independent ID: e9d5036f-118e-8dda-004c-ed6e2c686911
* Content: [Troubleshooting DirectAccess](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/directaccess/troubleshooting-directaccess)
* Content Source: [WindowsServerDocs/remote/remote-access/directaccess/Troubleshooting-DirectAccess.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/directaccess/Troubleshooting-DirectAccess.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
