### ISSUE TITLE
Guidance for Server 2019

### ISSUE THREAD

**Issue by bieberium** [MicrosoftDocs/windowsserverdocs#2337]
Hi,
this is a very good article, thank you for it.

I read this document and the blog post on the "Security Guidance" blog on technet [1] about disabling these services. Unfortunately, both documents either only state Server 2016 as an applicable OS, or in case of the blog, offer a specific warning about Server 2019:
[Note that this guidance applies only to Windows Server 2016 with Desktop Experience. It does not need to be applied to Windows Server 2019.]

Is there a plan to update this guidance to Server 2019?

Thanks!

[1] https://blogs.technet.microsoft.com/secguide/2017/05/29/guidance-on-disabling-system-services-on-windows-server-2016-with-desktop-experience/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bf0fae6-d821-8220-87c0-b1e71b48260f
* Version Independent ID: afa6c125-4c14-baf2-ae10-7096d65cda04
* Content: [Security guidelines for system services in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server)
* Content Source: [WindowsServerDocs/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server.md)
* Product: **windows-server-threshold**
* GitHub Login: @nirb
* Microsoft Alias: **nirb**

**Comment by BryanEaay** [comment]
Hi there,

I'm also wondering where i could find this document applied to WS2019.
It would be really appreciated here !

Hope to have news soon..

Thanks.
Bryan.F

**Comment by Soolkiki** [comment]
Bump!

**Comment by tgtcat6** [comment]
This would be great to have

**Comment by rrsit** [comment]
interested as well - is there a 2019 version of the guide?

**Comment by janmadera** [comment]
I am very interested in a 2019 version! Please update this spreadsheet, it was very valuable for us.

**Comment by yrwins** [comment]
I need to wait.

**Comment by mccabejr** [comment]
Bumping as this would be a very useful resource to have as our organization begins our introduction of 2019 platforms.

**Comment by powertoaster** [comment]
Also very interested.

**Comment by DevFinGovSecOps** [comment]
We used this guide as part of our windows server 2016 hardening measures - would be nice to have a version for windows server 2019 as well.

**Comment by gbryant200** [comment]
still looking forward to this . . .

**Comment by yllekz** [comment]
Also looking for an update on this.

**Comment by Barsug** [comment]
Please, assign this issue to engineer. Thank You

**Comment by kort3x** [comment]
bump

**Comment by cwestwater** [comment]
Bump!

**Comment by laperfidanto** [comment]
Bump!

**Comment by gbryant200** [comment]
This one has been updated

https://docs.microsoft.com/en-us/windows-server/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server

**Comment by 768kb** [comment]
Thank you very much for this link. Tooks a very long time until someone found that. And even worse, compared to the excel spreadsheet before, it is in a unusable format. How can I quickly find all services which are safe to disable? I have to create my own list now based on this webpage. Parsing with RegEx will help, but hey guys, why can't you just provide a spreadsheet like before? .....

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by An-dir** [comment]
Just to add something useful because of the 

> unusable format

any other useful (integrated / automated) export of data would be appreciated

```
$fields = "ServiceTitle","ServiceName","Description","Installation","StartupType","Recommendation","Comments"
$RequestData = Invoke-WebRequest -UseBasicParsing -Uri https://raw.githubusercontent.com/MicrosoftDocs/windowsserverdocs/main/WindowsServerDocs/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server.md
$regexString = '(?m)^##\s(?<ServiceTitle>.*)$(?s).*?\*\*Service name\*\* \| (?<ServiceName>.*?(?=\s+\|)).*?\*\*Description\*\* \| (?<Description>.*?(?=\s+\|)).*?\*\*Installation\*\* \| (?<Installation>.*?(?=\s+\|)).*?\*\*Startup type\*\* \| (?<StartupType>.*?(?=\s+\|)).*?\*\*Recommendation\*\* \| (?<Recommendation>.*?(?=\s+\|)).*?\*\*Comments\*\* \| (?<Comments>.*?(?=\s+\|))'
$out = $RequestData.Content |
    Select-String -Pattern $regexString -AllMatches |
        Foreach-Object { $_.Matches | Foreach-Object {
            $hash = [ordered]@{}
            foreach ($field in $fields) {
                $hash.$field = $_.Groups.where{$_.Name -eq $field}.Value}
                [pscustomobject]$hash
            }
        };
$out | Export-Csv -Path file.csv -Delimiter ";" -NoTypeInformation
 .\file.csv
```
This PowerShell code generates an object with all the services in the GitHub version of the Microsoft website and then exports and opens a CSV in excel if it is installed

thanks to AdminOfThings at https://stackoverflow.com/questions/70696733/can-someone-optimize-my-net-regex-for-powershell-parsing-a-table-with-errors

**Comment by RussatVMO2** [comment]
> Just to add something useful because of the
> 
> > unusable format
> 
> any other useful (integrated / automated) export of data would be appreciated
> 
> ```
> $fields = "ServiceTitle","ServiceName","Description","Installation","StartupType","Recommendation","Comments"
> $RequestData = Invoke-WebRequest -UseBasicParsing -Uri https://raw.githubusercontent.com/MicrosoftDocs/windowsserverdocs/main/WindowsServerDocs/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server.md
> $regexString = '(?m)^##\s(?<ServiceTitle>.*)$(?s).*?\*\*Service name\*\* \| (?<ServiceName>.*?(?=\s+\|)).*?\*\*Description\*\* \| (?<Description>.*?(?=\s+\|)).*?\*\*Installation\*\* \| (?<Installation>.*?(?=\s+\|)).*?\*\*Startup type\*\* \| (?<StartupType>.*?(?=\s+\|)).*?\*\*Recommendation\*\* \| (?<Recommendation>.*?(?=\s+\|)).*?\*\*Comments\*\* \| (?<Comments>.*?(?=\s+\|))'
> $out = $RequestData.Content |
>     Select-String -Pattern $regexString -AllMatches |
>         Foreach-Object { $_.Matches | Foreach-Object {
>             $hash = [ordered]@{}
>             foreach ($field in $fields) {
>                 $hash.$field = $_.Groups.where{$_.Name -eq $field}.Value}
>                 [pscustomobject]$hash
>             }
>         };
> $out | Export-Csv -Path file.csv -Delimiter ";" -NoTypeInformation
>  .\file.csv
> ```
> 
> This PowerShell code generates an object with all the services in the GitHub version of the Microsoft website and then exports and opens a CSV in excel if it is installed
> 
> thanks to AdminOfThings at https://stackoverflow.com/questions/70696733/can-someone-optimize-my-net-regex-for-powershell-parsing-a-table-with-errors

I cannot believe this doesn't have more replies. What a massively helpful bit of code. Thank you so much
(I change the delimiter to "," as it works better in Excel)
