### ISSUE TITLE
There is no document reference location for SSH Config

### ISSUE THREAD

**Issue by FredSamuels** [MicrosoftDocs/windowsserverdocs#2338]
Please present a path to the config location in the documentation as there is no reference.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
