### ISSUE TITLE
Are Certificates using CNG keys supported in 2016 and later?

### ISSUE THREAD

**Issue by rodsaw11** [MicrosoftDocs/windowsserverdocs#2339]
In ADFS 3.0 on Server 2012r2, support for certificates with CNG keys was explicitly not supported.  https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/ad-fs-support-for-alternate-hostname-binding-for-certificate-authentication
This limitation is not listed on this page in the Certificate Requirements, has this limitation been removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68bac2aa-024c-a014-eeaf-f28a44b31c5e
* Version Independent ID: 86c83819-91d6-c990-16f1-d05ebdf07b58
* Content: [AD FS 2016 Requirements](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-requirements#BKMK_7)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/ad-fs-requirements.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/ad-fs-requirements.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
