### ISSUE TITLE
Support for 3+ Connection Brokers in SVR2012R2 HA

### ISSUE THREAD

**Issue by tusharchandwani** [MicrosoftDocs/windowsserverdocs#2341]
The table entry for *// Windows Server 2012 R2 Connection Broker + RDSH/RDVH 2012 R2 //* should read **"Not Supported"**, instead of Supported, since a maximum of 2 Connection Brokers is supported in an SVR2012R2 Connection Broker setup. The leading paragraph already explains that "*Windows Server 2016 **removes** the restriction* for the number of Connection Brokers you can have in a deployment when using Remote Desktop Session Hosts (RDSH) and Remote Desktop Virtualization Hosts (RDVH) that also run Windows Server 2016.".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7242a6c0-8f40-bb91-c23e-0081a4d4a94a
* Version Independent ID: 9a1213ac-baf5-c1f3-e735-33a0b818fb6f
* Content: [Supported configurations for Remote Desktop Services](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-supported-config)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-supported-config.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-supported-config.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
