### ISSUE TITLE
Highlight differences

### ISSUE THREAD

**Issue by klang-uofi** [MicrosoftDocs/windowsserverdocs#2363]
I would love to see an option to highlight the differences in editions on this page. Since there are so many lines, it takes longer to scroll through and spot differences. Any sort of improvement to this would be nice!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5acee3a-b458-172f-127d-07e0406bd46f
* Version Independent ID: a11c4876-e20a-4307-b1b7-38f414a4532c
* Content: [Windows Server 2016 Products and Editions](https://docs.microsoft.com/en-us/windows-server/get-started/2016-edition-comparison)
* Content Source: [WindowsServerDocs/get-started/2016-Edition-Comparison.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/2016-Edition-Comparison.md)
* Product: **windows-server-threshold**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by MateuszGrabuszynski** [comment]
Wrote a small piece of script that does that:
```JavaScript
let tables = document.getElementsByClassName('table-scroll-wrapper');

for(let i=0; i<tables.length; i++){
	let trows = tables[i].getElementsByTagName('tr');
	for(let j=0; j<trows.length; j++){
		let tds = trows[j].getElementsByTagName('td');
		let len = tds.length;
		try{
			if(tds[len-2].innerHTML != tds[len-1].innerHTML){
				trows[j].setAttribute('style','background-color: yellow;');
			}
		}
		catch(ex){}
	}
}
```

**Comment by jaimeo** [comment]
@JasonGerend

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
