### ISSUE TITLE
Need documentation for HTTP Header customization

### ISSUE THREAD

**Issue by dumpkopf** [MicrosoftDocs/windowsserverdocs#2364]
There is not public documentation around Set-AdfsResponseHeader and it's proper use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7899bfcb-2e9c-2738-5e7f-468a6eb643ce
* Version Independent ID: 482cc911-c7ef-c680-b6ff-f634530b1424
* Content: [What's new in Active Directory Federation Services for Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
