### ISSUE TITLE
Communication Skills

### ISSUE THREAD

**Issue by chumunga** [MicrosoftDocs/windowsserverdocs#2365]
I won't argue that there will be individuals who can read this artical

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02a070e0-13ae-2ec0-fb59-f53e76c447a5
* Version Independent ID: 6689fc76-46a7-5091-0e3b-ddec78385326
* Content: [Set up Hyper-V Replica](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/set-up-hyper-v-replica)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/Set-up-Hyper-V-Replica.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/Set-up-Hyper-V-Replica.md)
* Service: **na**
* Product: **windows-server-threshold**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by chumunga** [comment]
Didn't mean to send right away the first time, anyways....

Hire people who know how to communicate. I'm sure there are plenty of highly technical individuals and maybe even with experience on this topic that can understand this article, but is that your only intend audience?

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
