### ISSUE TITLE
Incorrect link to 'Local accounts' page

### ISSUE THREAD

**Issue by RajeevSatarkar** [MicrosoftDocs/windowsserverdocs#2366]
[Enter feedback here]

The target URL for the 'Local Accounts' link is incorrect. 

It is configured to - https://technet.microsoft.com/itpro/windows/keep-bastion.local-accounts

The correct URL is - https://technet.microsoft.com/itpro/windows/keep-secure/local-accounts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92662f92-0102-783a-b05a-9f5dea982ea9
* Version Independent ID: bd3fbec9-22dc-b674-9d8c-b2e06a56d0dd
* Content: [Windows Authentication Concepts](https://docs.microsoft.com/en-us/windows-server/security/windows-authentication/windows-authentication-concepts)
* Content Source: [WindowsServerDocs/security/windows-authentication/windows-authentication-concepts.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/windows-authentication/windows-authentication-concepts.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
