### ISSUE TITLE
Firmware Mismatch between Powershell and Vendor Utility

### ISSUE THREAD

**Issue by maglaubig** [MicrosoftDocs/windowsserverdocs#2371]
I have 2 drives types in my S2D deployment, Micron 5100 MAX 1.9TB and Seagate ST4000NM0035-1V4.  When querying the drives with the vendor supplied utility (command) versus Powershell the versions match.  However when using Powershell versus the Micron utility (Micron Storage Executive, which is a GUI) the versions don't match exactly.  The Micron utility appends a few characters to the front of the firmware version that Powershell reports.  For example, Micron Utility says "D0MU051" and Powershell says "U051".  Should I be using the Powershell value or the vendor utility in the XML doc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84104ccc-94a6-5d06-d300-b3c8cc707075
* Version Independent ID: a298fd72-2fd2-ee19-4992-d11b13797523
* Content: [Updating drive firmware in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/storage/update-firmware)
* Content Source: [WindowsServerDocs/storage/update-firmware.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/update-firmware.md)
* Product: **windows-server-threshold**
* GitHub Login: @toklima
* Microsoft Alias: **toklima**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
