### ISSUE TITLE
Error in ADFS Lab setup docs

### ISSUE THREAD

**Issue by mshindal** [MicrosoftDocs/windowsserverdocs#2375]
> [When you are prompted for a service account, type contosofsgmsa$.](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/set-up-an-ad-fs-lab-environment#to-configure-device-registration-service-for-windows-server-2012-rtm)

Shouldn't this be FsGmsa, which is created [here](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/set-up-an-ad-fs-lab-environment#to-create-a-gmsa-account)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4bc6fcc-47a6-96c1-f76e-e58573f17575
* Version Independent ID: 80d762b0-b1c2-e3ee-68a0-7112bca50afc
* Content: [Set up an AD FS lab environment](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/set-up-an-ad-fs-lab-environment)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Set-up-an-AD-FS-lab-environment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Set-up-an-AD-FS-lab-environment.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
