### ISSUE TITLE
IaaS VM in Azure as a destination server is not fully supported

### ISSUE THREAD

**Issue by johnwildes** [MicrosoftDocs/windowsserverdocs#2379]
I think there should be mention of the fact that you cannot use the cutover phase of the Storage Migation Service Wizard against an Azure VM.  It will fail every time and actually end up leaving the IaaS VM in Azure in an unreachable state if you have only ONE NIC configured on it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47e8f561-963a-50f0-347c-5c6d40c5b693
* Version Independent ID: e91fc4e1-e9df-6253-88d1-cab878edb0fd
* Content: [Storage Migration Service known issues](https://docs.microsoft.com/en-us/windows-server/storage/storage-migration-service/known-issues)
* Content Source: [WindowsServerDocs/storage/storage-migration-service/known-issues.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-migration-service/known-issues.md)
* Product: **windows-server-threshold**
* GitHub Login: @nedpyle
* Microsoft Alias: **nedpyle**

**Comment by nedpyle** [comment]
I agree, and just wrote it up. Should land on Docs by tomorrow. Thanks John!

**Comment by johnwildes** [comment]
Thanks @nedpyle !!
