### ISSUE TITLE
Transfer Again?  Needs more detail on how to do this successfully

### ISSUE THREAD

**Issue by johnwildes** [MicrosoftDocs/windowsserverdocs#2380]
I've had one server that I've been able to successfully inventory and transfer.  We have been working for about a week to cut it over, and data on the source has changed again, and there's about a 10% difference in the files on the source from what currently exists on the destination.  How do we "transfer again" and only those files that have changed?  I went through the transfer process again, and all it did was copy over all the same files to the destination server.  It would be helpful to have more information on this "transfer again" scenario as I think it could be quite common especially if you have a large volume of data that you want to transfer with a sizable change rate, and then a gap between when files are finally copied up and the server is actually cutover.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6614c040-d1c5-efb2-e29e-7cd93b3c9e55
* Version Independent ID: f268e6ad-a69a-174d-0630-ad41aae0a9f1
* Content: [Migrate a file server by using Storage Migration Service](https://docs.microsoft.com/en-us/windows-server/storage/storage-migration-service/migrate-data)
* Content Source: [WindowsServerDocs/storage/storage-migration-service/migrate-data.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-migration-service/migrate-data.md)
* Product: **windows-server-threshold**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by jte369** [comment]
It seems disappointing to see that this was asked 3 months ago, and nothing.  I found this today, when I was looking for the answer to the same question.

**Comment by jte369** [comment]
Choosing to Start Transfer should do the incremental sync. You may get a warning that this will start the transfer all over again, but this is a bug. From my testing, it does actually do an incremental transfer, after the first time it runs.

**Comment by aVa-09** [comment]
Hello,
When i tried to transfert again, it's always all folders and files....
Did you do it in a particular way ?

**Comment by johnwildes** [comment]
Closing issue abandoned storage migration service.
