### ISSUE TITLE
Endpoint

### ISSUE THREAD

**Issue by robert-bunch** [MicrosoftDocs/windowsserverdocs#2384]
In the table of endpoints it lists:

/adfs/ls/federationmetadata/2007-06/federationmetadata.xml instead of  /federationmetadata/2007-06/federationmetadata.xml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a834de4-c696-4599-6ab2-94ae03d31471
* Version Independent ID: 78658bfd-8bcc-0d71-5139-77733f1a795e
* Content: [Best Practices for securing AD FS and Web Application Proxy](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/best-practices-securing-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Best-Practices-Securing-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Best-Practices-Securing-AD-FS.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
