### ISSUE TITLE
Upgrade to Windows 2016 AD with separated roles keeping IP and Name

### ISSUE THREAD

**Issue by falarcon10** [MicrosoftDocs/windowsserverdocs#2388]
I am studying to update my active directory from Windows 2012 to Windows 2016.
After reading articles and tech notes I have several doubts.
The FSMO roles are distributed among the 3 DCs. For migration, are the 3 new servers installed and are the corresponding roles transferred to each one?
On the DNS, if the 3 new servers have different names and IPs when transferring the DNS service, all the PCs and servers would stop responding correctly since they have the DNS manually configured to the old DCs.
What would be the correct procedure to minimize the impact of migration? Is it possible and is there a procedure to change the name and IP of the new DCs to the old ones?
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2a85898-01c1-47ac-a186-b40237462d71
* Version Independent ID: 7004b4de-2679-c668-6968-d0580e9c518e
* Content: [Server Role Upgrade and Migration Matrix for Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/get-started/server-role-upgradeability-table)
* Content Source: [WindowsServerDocs/get-started/Server-Role-Upgradeability-Table.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/Server-Role-Upgradeability-Table.md)
* Product: **windows-server-threshold**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
