### ISSUE TITLE
What's new in Server 1709 doc - VM Loadbalancing mixes in storage-class memory section

### ISSUE THREAD

**Issue by csharmath** [MicrosoftDocs/windowsserverdocs#239]
https://raw.githubusercontent.com/MicrosoftDocs/windowsserverdocs/master/WindowsServerDocs/get-started/whats-new-in-windows-server-1709.md

The VM Loadbalancing section seems to just switch over to copy-pasted storage-class memory section or at least it looks weird to me. 
Pasting it here ( emphasis mine )

> VM Load Balancing is also improved with OS and Application awareness, ensuring optimal load balancing and application performance. **Storage-class memory support** for VMs enables NTFS-formatted direct access volumes to be created on non-volatile DIMMs and exposed to Hyper-V VMs. This enables Hyper-V VMs to leverage the low-latency performance benefits of storage-class memory devices.

Also this doc is a bit too high level to me. Would be nice to have more details or links to the details.

**Comment by lizap** [comment]
Good catch - we've just processed a fix to this and will republish later today. 

We'll also work on adding additional detail - in most cases, if you go to the content area for the technology, you'll find more information. Thanks!

**Comment by csharmath** [comment]
was about to ask if you guys seen this? 
thanks Liza!

**Comment by csharmath** [comment]
Could we have a section about Windows Server **Core** and what's is not supported ? 

Things like WDS, Echange, SQL SSIS/SSRS, SCCM, SCOM. Right now is a hunt between outdated posts and forums and trials to figure out what's going to work, which is far from ideal.
Plus once someone figures this out, it would benefit the community to properly document it.

I would love to run everything on core preferably. Who needs GUI for servers, can't understand, but seemingly even some Msft products won't run on it like WDS, which is very weird to me as it only does TFTP, Jet DB, SMB share none of which would require GUI. ( at least per random blogs or old MSDN docs )
So yeah, would love to have some clarity here from the Server TEAM. 

Ah, should this be it's own issue ? let me know

thanks

**Comment by csharmath** [comment]
#246 - added a new issue for the Server Core question

**Comment by csharmath** [comment]
Closing - thanks
