### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windowsserverdocs#2390]
Windows IT Pro Center link (https://www.microsoft.com/en-gb/itpro/windows) not working

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc4cb072-7157-55b4-dbe1-c5723d2873b3
* Version Independent ID: 70a3605d-6d21-5719-b661-6023bad96627
* Content: [Windows Admin Center Overview](https://docs.microsoft.com/en-gb/windows-server/manage/windows-admin-center/overview#latest-features)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/overview.md)
* Product: **windows-server-threshold**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
