### ISSUE TITLE
How do I force cache invalidation after updating localization files?

### ISSUE THREAD

**Issue by wjens** [MicrosoftDocs/windowsserverdocs#2394]
I'm updating the assets\loc\en-US\strings.json file for the HTML5 web client. I'm adding a Reset Password link to the login failed message. I can see it if I open a private browsing session or if I clear my cache, but I'd really like to do something on the server to invalidate end user cache files so my changes can be seen by everyone.

Is this possible?

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
