### ISSUE TITLE
Step 11 Image Incorrect

### ISSUE THREAD

**Issue by calamonkey** [MicrosoftDocs/windowsserverdocs#2404]
This is currently a repeat image of step 13, but should have a different image from the "Configure Web API" section of the setup on the ADFS side.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 473bc6ea-017f-52f3-7e58-81ecf58d2db8
* Version Independent ID: 20965612-d6a9-35ea-c030-91c09372962e
* Content: [Build a web application using OpenID Connect with AD FS 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/enabling-openid-connect-with-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/enabling-openId-connect-with-ad-fs.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/enabling-openId-connect-with-ad-fs.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by akgoel23** [comment]
Thanks for the feedback. The document has been updated. Please let us know if you still see the issue. Thanks.
