### ISSUE TITLE
Document for how to implement Pluggable Threat Module Framework feature in ADFS 2019

### ISSUE THREAD

**Issue by JimmyLS** [MicrosoftDocs/windowsserverdocs#2407]
You mentioned this new feature available in ADFS 2019, but unfortunately we haven't see any detailed document on the official documentation. Could you please let us know if this feature is available and if so how to implement this in step-by step details? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7899bfcb-2e9c-2738-5e7f-468a6eb643ce
* Version Independent ID: 482cc911-c7ef-c680-b6ff-f634530b1424
* Content: [What's new in Active Directory Federation Services for Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
