### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/windowsserverdocs#2408]
"NTP uses calculations to adjust the time that assume the network patch is symmetrical."

I think "patch" should be "path".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 263f01e6-3b60-b944-99ed-ecaf99ec0ebe
* Version Independent ID: f3b25a25-e3c9-c662-dd2a-c1f9b2140b30
* Content: [Accurate Time for Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/accurate-time)
* Content Source: [WindowsServerDocs/networking/windows-time-service/accurate-time.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/windows-time-service/accurate-time.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **dacuo**

**Comment by illfated** [comment]
You are definitely correct. Both 2 sentences following the one with the typo "patch" in it use the word 'path' instead of "patch".

I will make sure that typo gets fixed.

**Comment by illfated** [comment]
There you go. PR #5152 is ready for review, comments, and suggestions.

Thanks for pointing out the typo. I found one more, in addition to cleaning up some source format abuse. 
My only regret is that I didn't start going through the old cases earlier than this year, but 2020 has changed a lot of things.
