### ISSUE TITLE
"Understanding Hyper-V scheduler type selection" Link is broken

### ISSUE THREAD

**Issue by emmanuelrd** [MicrosoftDocs/windowsserverdocs#2418]
In this article, the link "Understanding Hyper-V scheduler type selection" (https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/understanding-hyper-v-scheduler-type-selection) in the "Windows Server 2019 Hyper-V defaults to using the core scheduler" section is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b739fc5c-de44-7299-28a5-21e95bccf400
* Version Independent ID: 3a607530-01e6-e73a-0168-4e03a262a59c
* Content: [Understanding and using Hyper-V hypervisor scheduler types](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types#windows-server-2019-hyper-v-defaults-to-using-the-core-scheduler)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types.md)
* Product: **windows-server-hyper-v**
* GitHub Login: @allenma
* Microsoft Alias: **allenma**

**Comment by janis-veinbergs** [comment]
For over half a year, broken link still persists in Hyper-V documentation...

**Comment by Conan1989** [comment]
yep, still getting a 404 on "https://docs.microsoft.com/windows-server/virtualization/hyper-v/manage/understanding-hyper-v-scheduler-type-selection"

**Comment by illfated** [comment]
Duh, the correct link is the next one in the TOC, named "**About Hyper-V hypervisor scheduler type selection**" :
- https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/about-hyper-v-scheduler-type-selection

**Comment by illfated** [comment]
> (ref. #4095 )
