### ISSUE TITLE
Datacenter to Standard

### ISSUE THREAD

**Issue by joaoarenhart** [MicrosoftDocs/windowsserverdocs#2421]
Hi,
it is possible convert a Windows Server 2016 Datacenter to Windows Server 2016 Standard using DISM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adf594c8-5d55-8bfe-99b8-e1a1f91081fd
* Version Independent ID: 32ba9200-79f5-671d-bcc5-650540e8e94f
* Content: [Upgrade and Conversion Options for Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/get-started/supported-upgrade-paths#converting-a-current-evaluation-version-to-a-current-retail-version)
* Content Source: [WindowsServerDocs/get-started/Supported-Upgrade-Paths.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/Supported-Upgrade-Paths.md)
* Product: **windows-server-threshold**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
You should be able to check by running DISM /online /Get-TargetEditions . If Standard is on the list that returns, then you should be able to convert it by that method.

**Comment by baardhermansen** [comment]
Short answer: No, if you try you'll get an error message.
close #2421

**Comment by kinipradeep** [comment]
I thought so as well.. there is always an upgrade path but downgrade requires a reinstall.
