### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jbrines** [MicrosoftDocs/windowsserverdocs#2422]
he client shows offline with background sync, when I click on my documents and a folder with that and go up tot the address bar it still shows it pointing to the server share that hold the My Documents redirect. If I create a file or folder in My Documents it is immediately created in the server share.

Windows 10 and Server 2012r2.

Any idea what could be causing this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82efbfe0-c2b6-5b37-75a2-6cbfe2da7a41
* Version Independent ID: d18eab53-f4dc-2425-9603-adba16d40096
* Content: [Enable Always Offline mode for faster access to files](https://docs.microsoft.com/en-us/windows-server/storage/folder-redirection/enable-always-offline)
* Content Source: [WindowsServerDocs/storage/folder-redirection/enable-always-offline.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/folder-redirection/enable-always-offline.md)
* Product: **windows-server-threshold**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
