### ISSUE TITLE
Chkdsk can't check "hidden" volumes on PC HD

### ISSUE THREAD

**Issue by f6gnz** [MicrosoftDocs/windowsserverdocs#2428]
PC Computer window displays HD with partitions C: and D:, but Disk Manager shows two more volumes, the  39MB healthy OEM volume partition and the 14,65GB "RECOVERY" healthy partition, but without any partition number. Chkdsk /F /R performed on partitions C: and D: indicated no errors, but running Image backup indicates sector errors, which are suspected to be on OEM or RECOVERY partition. No way to run Chkdsk on these two partitions in order to be able to have a correct Image of complete PC HD. While Disk Manager allows to change Drive Letter and Path of the RECOVERY partition to make it available for Chkdsk, nothing is available to do it for the OEM partition!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d990aaa2-95c8-7cf2-5bfe-87248b6df6b5
* Version Independent ID: 0871aa5d-0a6f-6383-cf92-6b33f2d745ea
* Content: [chkdsk](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/chkdsk)
* Content Source: [WindowsServerDocs/administration/windows-commands/chkdsk.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/chkdsk.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by f6gnz** [comment]
Hi Steve,
I see there has been no reaction nor answers to my topic. If during one year nobody seemed interested, I think nobody will come back in the next year. So  it's better to close this issue as unsolved.
Best regards,
Radi
________________________________

**Comment by illfated** [comment]
Sorry, I was unaware that this ticket existed. I have just recently started looking up forgotten tickets to see what I can do to help.
( Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub. )

By the way, I am slightly confused by details in the main ticket post and not finding anything about "hidden" or "OEM" partitions. If that was taken from a real life scenario, I don't think it will be practical to make any related changes in the document. I remember some branded computers were even sold with discrepancies in the OEM or Recovery partitions, just to make it near impossible to replace the disk with a non-branded disk drive and install a new OS on that drive instead, or even create ISO images of the drive contents before reformatting the drive and placing a clean OS on the drive.

Please also note: Most of the [Windows Commands / Commands by Server Role] pages are meant to be as plain as possible for simple reference only. Most of them have even been around for so long, that we only have time to correct the most obvious incorrect information in those pages these days.

**Comment by illfated** [comment]
Anyway, I take it you are prepared to have this ticket closed, as you indicated in your comment today. Very well, at least we can assist you with that.

Feel free to open a new ticket if you find something that is really worth correcting, updating or improving for IT Pro Server Admins.

#please-close
