### ISSUE TITLE
Content Flow and Processes with "Enable Automatic Hosted Cache Discovery by Service Connection Point"

### ISSUE THREAD

**Issue by TehEdges** [MicrosoftDocs/windowsserverdocs#2430]
This document does not list how the content flow happens when enabling automatic hosted cache discovery by scp. I did not find this information anywhere else either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eecdfa9a-8c6b-25e7-3191-14773a6e03cd
* Version Independent ID: 58240bae-1751-28db-8e22-c4a9937b40f0
* Content: [BranchCache](https://docs.microsoft.com/en-us/windows-server/networking/branchcache/branchcache#BKMK_9)
* Content Source: [WindowsServerDocs/networking/branchcache/BranchCache.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/branchcache/BranchCache.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
