### ISSUE TITLE
Misspelled Word

### ISSUE THREAD

**Issue by JSaja** [MicrosoftDocs/windowsserverdocs#2431]
Paragraph 2, sentence 2, under heading, "How token-signing certificates are used across partners". "signing" is misspelled as "singing".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 751704ba-23fd-e9a8-9037-9da8d2cd1f27
* Version Independent ID: 530dd7b4-7607-2a90-e49c-91268f8daf04
* Content: [Token-Signing Certificates](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/design/token-signing-certificates)
* Content Source: [WindowsServerDocs/identity/ad-fs/design/Token-Signing-Certificates.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/design/Token-Signing-Certificates.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by doctordns** [comment]
Resolved, hopefully, in #2496
