### ISSUE TITLE
Incomplete and unclear

### ISSUE THREAD

**Issue by ekzp** [MicrosoftDocs/windowsserverdocs#2432]
I would like to see the following included on the poster:
- Namespace planning
- Certificate requirements
- Protocol flow
Similar to what the SfB team developed in its protocol workloads poster at https://www.microsoft.com/en-us/download/details.aspx?id=46448.

Also, some clear guidance on namespace planning would be in order to avoid those annoying certificate warnings. RDS has been around for quite some time, one would think it is about time to develop a solution that would work with a single certificate for the publicly facing namespace, without getting those annoying certificate warnings for NETBIOSNAME.domain.local. Citrix got it sorted quite nicely, hiding internal namespaces from the remote client. Why can't Microsoft do it? Why does Microsoft still think that loading the internal CA's cert on random public machines is the way to go?

According to https://blogs.technet.microsoft.com/askpfeplat/2017/12/18/remote-desktop-connection-rdp-certificate-warnings/, "The warning messages / pop-ups that end users see connecting via RDP are a GOOD THING."

WRONG. It is a BAD thing. The GOOD thing would be an RDS infrastructure that is consistent, secure, and it adheres to best practice (a.k.a. doesn't expose internal namespaces), to the point where there is NO NEED for these warnings.

Please fix it for once.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5daa735c-67fc-4461-682c-def85c8732d6
* Version Independent ID: 831c1ab7-2fda-55a9-ffb2-98d59c915989
* Content: [Remote Desktop Services - planning poster](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-poster)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-poster.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-poster.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
