### ISSUE TITLE
Virtual Ip address 

### ISSUE THREAD

**Issue by aasthana42** [MicrosoftDocs/windowsserverdocs#2445]
If we have Virtual Ip address configured between tow nodes but unable to talk to application server  and we want to access from another server how we configure that  ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14f5f554-e399-e711-5fb5-a48c421a6bff
* Version Independent ID: 95152750-cf7f-56aa-8df4-50066d88d103
* Content: [Deploying a two-node clustered file server](https://docs.microsoft.com/en-us/windows-server/failover-clustering/deploy-two-node-clustered-file-server)
* Content Source: [WindowsServerDocs/failover-clustering/deploy-two-node-clustered-file-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/deploy-two-node-clustered-file-server.md)
* Product: **windows-server-threshold**
* GitHub Login: @JohnMarlin-MSFT

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
