### ISSUE TITLE
Its not clear for cx , which load balancer you are talking about 

### ISSUE THREAD

**Issue by mohdabdulhameed542** [MicrosoftDocs/windowsserverdocs#2447]
The load balancer MUST NOT terminate SSL. AD FS supports multiple use cases with certificate authentication which will break when terminating SSL. Terminating SSL at the load balancer is not supported for any use case.

Cx deployed a load balancer to load balance WAP servers, but in ADFS he is not seeing the client Ip address, as SSL termination is required to see the client ip.

Cx was pretty mad about the documentation, If there is any way you can change the doc to make it more clear on requirements on the LB between WAP and ADFS and one before WAP Server!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68bac2aa-024c-a014-eeaf-f28a44b31c5e
* Version Independent ID: 86c83819-91d6-c990-16f1-d05ebdf07b58
* Content: [AD FS 2016 Requirements](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-requirements)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/ad-fs-requirements.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/ad-fs-requirements.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
