### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by lisasorenson** [MicrosoftDocs/windowsserverdocs#2448]
Connecting to remote server "servername" failed with the following error message : The WS-Management service cannot process the request. Cannot find the microsoft.sme.powershell session configuration in the WSMan: drive on the "servername" computer. For more information, see the about_Remote_Troubleshooting Help topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05df3d17-6978-2214-dad9-3eace6d7ee92
* Version Independent ID: ef8e8662-7c07-3118-59b3-0ac30af285f0
* Content: [Windows Admin Center Common Troubleshooting Steps](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/troubleshooting#filebug)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/use/troubleshooting.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/use/troubleshooting.md)
* Product: **windows-server-threshold**
* GitHub Login: @jwwool
* Microsoft Alias: **jeffrew**

**Comment by lisasorenson** [comment]
Windows Admin Center version 1809.5 Build 1.1.1812.03003

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
