### ISSUE TITLE
assign letter=*

### ISSUE THREAD

**Issue by verdy-p** [MicrosoftDocs/windowsserverdocs#2451]
Your doc incorrectly says that "You cannot assign drive letters to boot volumes, or volumes that contain the paging file. In addition, you cannot assign a drive letter to an Original Equipment Manufacturer (OEM) partition, EFI system partition, or any GPT partition other than a basic data partition."

In fact you can assign letters (using the DISKPART command line, or in Powershell, instead of the GUI Disk Management tool) to any partition which uses a supported filesystem (such as FAT32, exFAT, NTFS or ReFS), including the EFI system partition (FAT version EFI), and most OEM partitions (generally they are using FAT32 or NTFS), the Recovery partition... even if their partition type id is 27 (MBR partitioning), or if there are GPT volume attributes used to hide them, or it uses one of their known GPT partitition types.

The only partitions you cannot mount with a drive letter or mount point are those that have no supported filesystem, such as
- the small "MSR" partition of GPT disks (31 or 32MB in the past, now only 16MB is needed in Windows 10, for safely-recoverable offline management of other partitions for moves/resizings),
- "raw" partitition for database storage (when separate partitions are used instead of files on a filesystem).
- Linux/Unix swap or hibernation partitions (when separate partitions are used instead of files in a filesystem).
- encrypted partitions whose inner filesystem is protected by a missing/unconfigured external device or stopped service (including encrypted BitLocker volumes encrypted from another system with TPM modules and no authorization has been granted to remount it elsewhere with their decryption key or a TPM recovery drive to validate the authorization, or the PC trying to use it is authorized to use the volume created and managed in a private domain).
- unsupported filesystems such as Linux/Unix filesystems (UFS/Ext2/.../Ext4) or MacOS filesystems (HFS...); third party installable filesystem drivers may allow mounting them (including in read-write mode, with a configuration mapping for security: ACLs, group/user owner, basic access rights, filename mappings); a third party volume manager driver may also be needed.
- special formats created by external hardware RAID requiring their own BIOS/EFI extender in their controler or motherboard firmware (e.g. Intel RST).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b6ccbaf-f43c-2cf7-e0cb-3f1b1ab78e88
* Version Independent ID: c20575d9-8b0a-130e-406e-c2e2f73caf8a
* Content: [Assign a mount point folder path to a drive.](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/assign-a-mount-point-folder-path-to-a-drive)
* Content Source: [WindowsServerDocs/storage/disk-management/assign-a-mount-point-folder-path-to-a-drive.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/assign-a-mount-point-folder-path-to-a-drive.md)
* Product: **windows-server-threshold**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
