### ISSUE TITLE
MultiPoint Service is not available on Windows Server 2019.

### ISSUE THREAD

**Issue by sosato** [MicrosoftDocs/windowsserverdocs#2452]
MultiPoint Service is not available on Windows Server 2019.  We cannot enable the feature on Windows Server 2019.

https://social.technet.microsoft.com/Forums/en-US/5a5a1775-9265-4ab5-9e6d-09455265d5eb/windows-server-2019-and-multipoint-support?forum=windowsmultipointserver
https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-1803-removed-features

Multipoint Service removal was announced at 1803 release.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6f2b272-1c80-2d9b-590d-81c9970ee147
* Version Independent ID: 72474f8e-7705-df9f-f12f-02e0926f0901
* Content: [Comparison of Standard and Datacenter editions of Windows Server 2019](https://docs.microsoft.com/en-us/windows-server/get-started-19/editions-comparison-19#feedback)
* Content Source: [WindowsServerDocs/get-started-19/editions-comparison-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/editions-comparison-19.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by dad98253** [comment]
As far as I can tell, the release notes for 1803 indicated that ms was no longer developing Multipoint. It didn't say that it was being deleted.
So then, if we presently have clients connected to a Multipoint Server, we **must** not upgrade that server. Is that correct?

**Comment by IngridAtMicrosoft** [comment]
Hi @dad98253 Thank you for your comments.  GitHub issues on this repo are for reporting problems with documentation.  Please open a support incident to get help with your Multipoint Server issue.
