### ISSUE TITLE
Storage Replica

### ISSUE THREAD

**Issue by robbrown0** [MicrosoftDocs/windowsserverdocs#2455]
I believe Storage Replica should be listed as YES for 2019 Standard Edition (though with limitations compared to Data Center Edition).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6f2b272-1c80-2d9b-590d-81c9970ee147
* Version Independent ID: 72474f8e-7705-df9f-f12f-02e0926f0901
* Content: [Comparison of Standard and Datacenter editions of Windows Server 2019](https://docs.microsoft.com/en-us/windows-server/get-started-19/editions-comparison-19)
* Content Source: [WindowsServerDocs/get-started-19/editions-comparison-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/editions-comparison-19.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Orin-Thomas** [comment]
Ned Pyle Likely Approves This Comment

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
