### ISSUE TITLE
The contents of the document contain incorrect information

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/windowsserverdocs#2459]
[Enter feedback here]
The command line in the Help document is/replace-imagmedia, and the correct command line is/replace-image

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 802ad331-d652-e9f8-3da3-3eda4cb63b6e
* Version Independent ID: a3fb4882-7167-af7d-a7db-b927a104a7c3
* Content: [Using the replace-Image Command](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/using-the-replace-image-command)
* Content Source: [WindowsServerDocs/administration/windows-commands/using-the-replace-image-command.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/using-the-replace-image-command.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
