### ISSUE TITLE
Clarify the supported features on Windows Server Core 1709

### ISSUE THREAD

**Issue by csharmath** [MicrosoftDocs/windowsserverdocs#246]
as mentioned in #239 

Could we have a section about Windows Server Core and what's is not supported ?

Things like WDS, Echange, SQL SSIS/SSRS, SCCM, SCOM. 
Right now its a hunt between outdated posts and forums and trials to figure out what's going to work, which is far from ideal.
Plus once someone figures this out, it would benefit the community to properly document it.

I would love to run everything on core preferably. Who needs GUI for servers, can't understand, but seemingly even some Msft products won't run on it like WDS, which is very weird to me as it only does TFTP, Jet DB, SMB share none of which would require GUI. ( at least per random blogs or old MSDN docs )
So yeah, would love to have some clarity here from the Server TEAM.

Thanks

**Comment by csharmath** [comment]
See, there is an unanswered user voice as well about the WDS on Core question:
https://windowsserver.uservoice.com/forums/304618-installation-and-patching/suggestions/14794272-windows-deployment-services-should-not-need-the-gu

Which means that I am not the only one interested about these !

**Comment by lizap** [comment]
Have you seen the server core content we just published? Here's the starting point: https://docs.microsoft.com/en-us/windows-server/administration/server-core/what-is-server-core

**Comment by csharmath** [comment]
Thanks Liza, this is what I was looking for ( linked from the main page)
https://docs.microsoft.com/en-us/windows-server/administration/server-core/server-core-removed-roles

On a related note, it would be nice to get some closure on the why WDS is not supported on Core topic.
If someone from WDS team could comment, that would be awesome.
WDS seems to me a perfect target to be hosted on core and just simply can't wrap my head around why would it need a full GUI version to server TFTP, SMB and do it's business with a JetDB. 
Is there something else going on which needs full GUI features ?

Thanks

**Comment by lizap** [comment]
Wow, I didn't realize it'd been 26 days since responded. I'll see what I can find out about WDS. Thanks, as always, for your feedback and advice on the content!

**Comment by csharmath** [comment]
Will it be addressed for Server 2019 ? Should we close this ?

**Comment by csharmath** [comment]
This is great news, thank you @lizap !
