### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by bigmaggot** [MicrosoftDocs/windowsserverdocs#2461]
In GPOs linked to OUs containing member servers and workstations in each domain, the DA group should be added to the following user rights in Computer Configuration\Policies\Windows Settings\Security Settings\Local Policies\ User Rights Assignment:

Shouldn't it say "the BA group"?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d13782b-241a-1118-d348-c703523db75b
* Version Independent ID: c1307729-8e3f-921b-e7e2-4e43b1760f97
* Content: [Appendix G - Securing Administrators Groups in Active Directory](https://docs.microsoft.com/en-gb/windows-server/identity/ad-ds/plan/security-best-practices/appendix-g--securing-administrators-groups-in-active-directory)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-G--Securing-Administrators-Groups-in-Active-Directory.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-G--Securing-Administrators-Groups-in-Active-Directory.md)
* Product: **windows-server-threshold**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
No it is correct. Domain Admins should not be logging into member servers or workstations. Opens them up to credential theft via pass-the-hash and pass-the-ticket attacks. Each organization should make their own determination as to how they want to interpret these recommendations.

**Comment by bigmaggot** [comment]
I agree domain admins shouldn’t be logging in to workstations and member servers but this page is about built-in Administrators (BA). The other pages are about Enterprise Admins (EA) and Domain Admins (DA) groups, section E and F respectively

**Comment by MicrosoftGuyJFlo** [comment]
Yeah after re-reading this and the other articles that is correct. Should be built-in admins group. If you would like to propose the edit using the edit button at the top of the article I would be happy to approve.
