### ISSUE TITLE
Table doesn't match note

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windowsserverdocs#2465]
In the note about CAL versions, you state that older CALs can't access newer server versions, but in the table below that paragraph it says "yes" next to new server versions under the old CAL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d69b9ea-9672-c267-03e4-a34bf105d31b
* Version Independent ID: bddcfc0f-77d6-ff1c-9af3-c5b3ad11ba63
* Content: [License your RDS deployment with client access licenses (CALs)](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-client-access-license)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-client-access-license.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-client-access-license.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by wright-is** [comment]
The table shows which CALs a license server can serve, so it is correct. The 2019 license server can handle 2019 and older CALs, the 2012R2 can only handle 2008R2, 2012 and 2012R2 CALs.
That has nothing to do with the actual RD hosts. The CALs for older hosts only work with hosts of that version or older, as the note states.
E.g. you have a 2019 RD host, you need a 2019 license server to store the 2019 CALs on. If you have a 2008R2 RD host, you can use any supported version of Windows license server and CALs for any support server version.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
