### ISSUE TITLE
Deny access to this computer from the network

### ISSUE THREAD

**Issue by bigmaggot** [MicrosoftDocs/windowsserverdocs#2466]
Adding Administrators to "Deny access to this computer from the network" also blocks connections to RDP with error 4871:

The system administrator has restricted the types of logon (network or interactive) that you may use. For assistance, contact your system administrator or technical support.

I can confirm "Deny log on through Remote Desktop Services" is not being confused with "Deny access to this computer from the network".

This behaviour is the same for Windows 2019 and 2016, please advise?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d13782b-241a-1118-d348-c703523db75b
* Version Independent ID: c1307729-8e3f-921b-e7e2-4e43b1760f97
* Content: [Appendix G - Securing Administrators Groups in Active Directory](https://docs.microsoft.com/en-gb/windows-server/identity/ad-ds/plan/security-best-practices/appendix-g--securing-administrators-groups-in-active-directory)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-G--Securing-Administrators-Groups-in-Active-Directory.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-G--Securing-Administrators-Groups-in-Active-Directory.md)
* Product: **windows-server-threshold**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by bigmaggot** [comment]
The same behaviour occurs with NLA turned off too.

**Comment by MicrosoftGuyJFlo** [comment]
"as with all of the recommendations in this section, you should thoroughly test settings for applicability in your environment."

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
