### ISSUE TITLE
Changing the SSL cert on the WAP server

### ISSUE THREAD

**Issue by Dustefan** [MicrosoftDocs/windowsserverdocs#2479]
Would be a good idea to also include the fact that if you are publishing applications through the WAP, the certificate should be also changed through something like: Get-WebApplicationProxyApplication | Set-WebApplicationProxyApplication -ExternalCertificateThumbprint "new thumbprint" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d10177c6-b241-0a3e-d6ba-3619c094812a
* Version Independent ID: 7a42691f-7f28-eee2-0c69-294e24cccdbe
* Content: [Managing SSL Certificates in AD FS and WAP in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/manage-ssl-certificates-ad-fs-wap)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/manage-ssl-certificates-ad-fs-wap.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/manage-ssl-certificates-ad-fs-wap.md)
* Product: **windows-server-threshold**
* GitHub Login: @jenfieldmsft
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
