### ISSUE TITLE
RDS Farm

### ISSUE THREAD

**Issue by ctimon** [MicrosoftDocs/windowsserverdocs#2481]
Will there ever be a scenario where WAC can be in stalled on an RDS Server Farm as an application that all users connected to the farm will be able to use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc4cb072-7157-55b4-dbe1-c5723d2873b3
* Version Independent ID: 70a3605d-6d21-5719-b661-6023bad96627
* Content: [Windows Admin Center Overview](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/overview#follow-us-nbsp-a-targetblank-classmscom-link-twitter-follow-link-titlefollow-us-on-twitter-aria-labelfollow-us-on-twitter-data-infotwitter-hrefhttpstwittercomservermgmtpicturesource-srcsetimg-prod-cms-rt-microsoft-comakamaizednetcmsapiamimagefiledatareoolr-mediamin-width0img-srcsetimg-prod-cms-rt-microsoft-comakamaizednetcmsapiamimagefiledatareoolr-altfollow-us-on-twitter-srcimg-prod-cms-rt-microsoft-comakamaizednetcmsapiamimagefiledatareoolrpictureanbsp-a-targetblank-classmscom-link-blogs-follow-link-titlefollow-us-on-blogs-aria-labelfollow-us-on-blogs-data-infoblogs-hrefhttpsblogstechnetmicrosoftcomservermanagementpicturesource-srcsetimg-prod-cms-rt-microsoft-comakamaizednetcmsapiamimagefiledatareotyw-mediamin-width0img-srcsetimg-prod-cms-rt-microsoft-comakamaizednetcmsapiamimagefiledatareotyw-altfollow-us-on-blogs-srcimg-prod-cms-rt-microsoft-comakamaizednetcmsapiamimagefiledatareotywpicturea)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/overview.md)
* Product: **windows-server-threshold**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by fbifido** [comment]
WAC is web base, just share a web-link as an application, or just share Chome with the WAC web address as the start page.
