### ISSUE TITLE
Azure LB Session Persistance configurations

### ISSUE THREAD

**Issue by husamhilal** [MicrosoftDocs/windowsserverdocs#2483]
What's the configuration of Azure (Internal) Load Balancer session persistence (i.e.: None, Client IP, Client IP & Protocol) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1eac8a5-9217-7d91-d775-e062e7ea9c74
* Version Independent ID: ee080620-cc4f-bf5f-2c55-ca06d8deca63
* Content: [Active Directory Federation Services in Azure](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/how-to-connect-fed-azure-adfs)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/how-to-connect-fed-azure-adfs.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/how-to-connect-fed-azure-adfs.md)
* Service: **active-directory**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by calethix** [comment]
From https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-requirements

"It is NOT recommended to use IP based session affinity or sticky sessions for authentication traffic to AD FS within the load balancer."

**Comment by husamhilal** [comment]
makes sense @calethix. Thank you very much!
