### ISSUE TITLE
Issues with Sample Configuration file

### ISSUE THREAD

**Issue by dsolodow** [MicrosoftDocs/windowsserverdocs#2484]
@{
SchemaVersion = '2.0.0.0'
GUID = '54c8d41b-6425-46ac-a2eb-8c0184d9c6e6'
SessionType = 'RestrictedRemoteServer'
GroupManagedServiceAccount = gMSAcontoso
RoleDefinitions = @{ JEAcontoso = @{ RoleCapabilityFiles = ':\Program Files\WindowsPowershell\Modules\AccountActivityJEA\RoleCapabilities\JEAAccountActivityResetRole.psrc' } }
}

Should be:

@{
SchemaVersion = '2.0.0.0'
GUID = '54c8d41b-6425-46ac-a2eb-8c0184d9c6e6'
SessionType = 'RestrictedRemoteServer'
GroupManagedServiceAccount = 'CONTOSO\gMSAcontoso'
RoleDefinitions = @{ JEAcontoso = @{ RoleCapabilityFiles = 'C:\Program Files\WindowsPowershell\Modules\AccountActivityJEA\RoleCapabilities\JEAAccountActivityResetRole.psrc' } }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2f0b5c2-c56f-36d7-7457-ad7a5860f4a1
* Version Independent ID: 6f08f255-1abc-cf70-da2c-64b3e49fef06
* Content: [Delegate AD FS Powershell Commandlet Access to Non-Admin Users](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/delegate-ad-fs-pshell-access)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/delegate-ad-fs-pshell-access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/delegate-ad-fs-pshell-access.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by doctordns** [comment]
Good catch!

Fixed (I hope!) in #2495

**Comment by billmath** [comment]
@dsolodow Thanks for catching this.  I have just had an email from engineering and this has been fixed.  Thanks!

#please-close

**Comment by illfated** [comment]
#please-close
