### ISSUE TITLE
There is no Japanese docs for WSUS

### ISSUE THREAD

**Issue by reiikei** [MicrosoftDocs/windowsserverdocs#2490]
Previously, There were Japanese Technet pages for WSUS like following.
https://web.archive.org/web/20141230152746/https://technet.microsoft.com/ja-jp/library/hh852338.aspx

But now there were no Japanese pages in Docs like following. There should be Japanese page in Docs too.
https://docs.microsoft.com/ja-jp/windows-server/administration/windows-server-update-services/get-started/windows-server-update-services-wsus

Thanks,
Rei

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
