### ISSUE TITLE
Cloning/ARM templates are awesome, but not always helpful

### ISSUE THREAD

**Issue by lynnhtowle** [MicrosoftDocs/windowsserverdocs#2491]
Much of the new documentation deals with cloning or deploying and AD Farm with an ARM template, but not every scenario can be solved by either of those. Case in point: I want to build new Server 2019 DC's in Azure.

There is no base image I can clone my DC from.
I only want to deploy 2 DC's, where I have existing 2012 and 2016 DC's and also an ExpressRoute and Gateway.
Also, the page on MSDN for ""Guidelines for Deploying Windows Server Active Directory on Azure Virtual Machines" seems to have disappeared, which was EXTREMELY helpful as a reference when building a new virtual DC.

Lastly, there still seems to be a gap in documentation when dealing with DC's in an availability group with regards to DNS for the availability group. 

I'm for automation, but building documentation around the assumption that automation/cloning is going to be the default way of deploying a resource is going to lead to more questions than solutions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc4f453-8f97-78d9-beaf-a7f2169e7a49
* Version Independent ID: 90182e74-3e05-7be4-4bab-373b438d798f
* Content: [Introduction to Active Directory Domain Services (AD DS) Virtualization (Level 100)](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/introduction-to-active-directory-domain-services-ad-ds-virtualization-level-100)
* Content Source: [WindowsServerDocs/identity/ad-ds/Introduction-to-Active-Directory-Domain-Services-AD-DS-Virtualization-Level-100.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/Introduction-to-Active-Directory-Domain-Services-AD-DS-Virtualization-Level-100.md)
* Product: **windows-server-threshold**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
New article is coming that will address these items. Look for it in a couple weeks. I will send you a comment when it is published.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
