### ISSUE TITLE
Useful but no wild cards

### ISSUE THREAD

**Issue by Opportunivore** [MicrosoftDocs/windowsserverdocs#2492]
Hi this utility would be far more useful if it allowed wild cards or the ability to list hardlinks for files in subfolders (recursive)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2190368d-26b5-ce9c-69f0-572a26dfd3e8
* Version Independent ID: 8c513170-c256-af58-7197-b3aeaeb69440
* Content: [Fsutil hardlink](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil-hardlink)
* Content Source: [WindowsServerDocs/administration/windows-commands/fsutil-hardlink.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/fsutil-hardlink.md)
* Product: **windows-server-threshold**
* GitHub Login: @toklima
* Microsoft Alias: **toklima**

**Comment by doctordns** [comment]
Consider using PowerShell to create your symlinks.

**Comment by Opportunivore** [comment]
Symlinks are already created.  Trying to find verify previously existing.

**Comment by doctordns** [comment]
YOu can do that too in PowerShell: see: https://docs.microsoft.com/en-us/powershell/wmf/5.0/feedback_symbolic to get started.
