### ISSUE TITLE
Spell-checking underline has to be removed from screenshots

### ISSUE THREAD

**Issue by mikerodionov** [MicrosoftDocs/windowsserverdocs#25]
On the following screenshot:
https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/media/NIC-Teaming/nict_overview.jpg

There is a red spell checker underline which has to be removed.

**Comment by jamesmci** [comment]
Thanks much for pointing this out! Fixing this graphic is now in our queue for an eventual fix.

**Comment by lizap** [comment]
Closing the issue as we've added a work item to the backlog.
