### ISSUE TITLE
Cannot install on Domain Controller

### ISSUE THREAD

**Issue by jjindrich** [MicrosoftDocs/windowsserverdocs#2504]
I cannot install Windows Admin Center on Windows 2019 server with AD controller. Why ? My server is only one replacing previous SBS server.

**Comment by jjindrich** [comment]
Hi, please why are you blocking installation ?

**Comment by RichardDuaneWolford** [comment]
Seconded, this needs to be installable on a domain controller, or at least a reply as to why this can't be the case.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
