### ISSUE TITLE
Missing NSP Configuration

### ISSUE THREAD

**Issue by MariusWeiss** [MicrosoftDocs/windowsserverdocs#2507]
This step by step documentation completely missed the part with the necessary NPS server configuration as described here:
https://www.vroege.biz/?p=4038

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
