### ISSUE TITLE
What is "PSH" in the context of this document?

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/windowsserverdocs#2514]
"Remote PSH using SmartCard Login - Customers can now use smartcards to remote connect to ADFS via PSH and use that to manage all PSH functions include multi-node PSH cmdlets."

Should that be PHS for some azure feature tie-in?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7899bfcb-2e9c-2738-5e7f-468a6eb643ce
* Version Independent ID: 482cc911-c7ef-c680-b6ff-f634530b1424
* Content: [What's new in Active Directory Federation Services for Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by husamhilal** [comment]
PSH = PowerShell

**Comment by jordanmills** [comment]
So why not use the product name instead of making up acronyms?

**Comment by schnitz76** [comment]
Yes, please update the documentation to include the actual product name instead of some shorthand that is unclear.

**Comment by illfated** [comment]
Fair point. PowerShell does not enter the top 3 meanings for the acronym "PSH" in many lists, as well as not necessarily showing up on your first page of web search results.

@billmath or @daveba : Are there any authoritative pages showing that "PSH" is an established short form of "PowerShell" ?

**Comment by jgallucci32** [comment]
+1

This ticket was the first hit on my Google search because I had absolutely no clue what PSH was. First reference to acronyms should always have the full version plus acronym, i.e. PowerShell (PSH), in order to educate the reader who may not be familiar with the term.

**Comment by ThomasKur** [comment]
Same to me. Totally unclear what this means.

**Comment by illfated** [comment]
Thank you all for the feedback. I am considering writing a Pull Request to have PSH followed by (PowerShell) for at least 1 occurrence in this document, seeing that there are 5 occurrences of PSH, but only 1 occurrence of "Powershell" (which in itself should be corrected to `PowerShell` with a capital S).

My only uncertainty is whether the addition of "(PowerShell)" after one of the 4 mentions of "PSH" in the same paragraph should be after the first occurrence in the bold text, or if it should be added in the following sentence in normal text (not bold). Any suggestions, whether it should be after the first occurrence, if it should be more than one, or if the number of "PSH" entries should be reduced in that paragraph?

**Comment by jordanmills** [comment]
If you’re going to do that, why not just fix them all?

**Comment by illfated** [comment]
> If you’re going to do that, why not just fix them all?

Well, fair point I suppose. I was mostly "hedging my bets" in case that replacing all of them would be considered to be too much of a change by the Microsoft Docs team members, making it less likely that my suggestion would be accepted.

**Comment by jgallucci32** [comment]
@jordanmills The generally accepted method is to spell out the word first followed by the acronym in parenthesis, i.e. PowerShell (PSH). When done this way, you can use the acronym by itself in subsequent sentences.

This is discussed here and the common consensus is to spell out the word first
https://english.stackexchange.com/questions/131045/placement-of-acronym-vs-words-spelled-out

**Comment by illfated** [comment]
Thank you. That is exactly what I needed to feel more certain before I start making the PR.

**Comment by illfated** [comment]
There you go, PR #4483 is now available for review. Feel free to join in to comment, approve, or suggest further improvements.

**Comment by MrBrain295** [comment]
lol

**Comment by SideFli** [comment]
@MrBrain295  oh, hi
