### ISSUE TITLE
Rename-Computer invalid parameter

### ISSUE THREAD

**Issue by khalil2535** [MicrosoftDocs/windowsserverdocs#2530]
If you got this error
```
PS C:\Users\Administrator&gt; Rename-Computer -Name DHCP1
Rename-Computer : A parameter cannot be found that matches parameter name 'Name'.
At line:1 char:17
+ Rename-Computer -Name DHCP1
+                 ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Rename-Computer], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.RenameComputerCommand
```

This is the solution :
```
PS C:\Users\Administrator&gt; Rename-Computer DHCP1 #-Name DHCP1
WARNING: The changes will take effect after you restart the computer (you old computer name).
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe047b9e-1cef-6930-1473-a3e1a2a3b5f7
* Version Independent ID: 86bb5d90-1e18-f0a6-f688-d20d502c51a4
* Content: [Deploy DHCP Using Windows PowerShell](https://docs.microsoft.com/en-us/windows-server/networking/technologies/dhcp/dhcp-deploy-wps#feedback)
* Content Source: [WindowsServerDocs/networking/technologies/dhcp/dhcp-deploy-wps.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/dhcp/dhcp-deploy-wps.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
