### ISSUE TITLE
Broken link at: Introduction and resources for troubleshooting Active Directory replication

### ISSUE THREAD

**Issue by Saggiehaim** [MicrosoftDocs/windowsserverdocs#2531]
Hey,
The link for the "Hands-on lab" at the Introduction and resources for troubleshooting Active Directory replication section is broken and linking to 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 190492f7-b2ce-d6ba-cfc4-eac02663c68b
* Version Independent ID: f8271a41-49ff-5236-92ba-236cb8442b3c
* Content: [Troubleshooting Active Directory Replication Problems](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/troubleshoot/troubleshooting-active-directory-replication-problems#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/troubleshoot/Troubleshooting-Active-Directory-Replication-Problems.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/manage/troubleshoot/Troubleshooting-Active-Directory-Replication-Problems.md)
* Product: **windows-server-threshold**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
Resolving via PR in private repo 14756

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
