### ISSUE TITLE
Can this be updated to Server 2019?

### ISSUE THREAD

**Issue by danielniccoli** [MicrosoftDocs/windowsserverdocs#2534]
Can this be updated to Server 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abe32092-a430-3fa1-d0ae-789f04b0050f
* Version Independent ID: 65ba98d0-5af2-bdd0-3c51-9a287d83b430
* Content: [AD FS Design Guide](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/design/ad-fs-design-guide)
* Content Source: [WindowsServerDocs/identity/ad-fs/design/AD-FS-Design-Guide.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/design/AD-FS-Design-Guide.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by trek-e** [comment]
Would love to see this updated for 2019, otherwise people will keep deploying on 2012 because that's whats available.

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
