### ISSUE TITLE
Traffic route decision

### ISSUE THREAD

**Issue by xXxOlivierxXx** [MicrosoftDocs/windowsserverdocs#2535]
I understand that if one site has multiple site links, AD will chose the one with the lower cost for replication, but what happens if all links have the same cost? How does AD decide which path to follow, if all of them have the same cost?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb147d3e-94b6-f325-cb1c-5811cdc35fec
* Version Independent ID: be2ee9b6-e207-edcd-d6b4-fdc159969276
* Content: [Determining the Cost](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/determining-the-cost)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/Determining-the-Cost.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/Determining-the-Cost.md)
* Product: **windows-server-threshold**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
Take a look at the following for more inforation about the interval
https://docs.microsoft.com/windows-server/identity/ad-ds/plan/determining-the-interval

**Comment by MicrosoftGuyJFlo** [comment]
#please-close

**Comment by xXxOlivierxXx** [comment]
The link shared does not answer my question, but feel free to close the thread if you want.
Replication interval has nothing do with selecting the best path to follow for replication.

**Comment by illfated** [comment]
#please-close
