### ISSUE TITLE
Where is the overview?

### ISSUE THREAD

**Issue by cliffhobbs** [MicrosoftDocs/windowsserverdocs#2537]
I would expect at least a single paragraph on here giving me a definition of what ADFS is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14a12c12-4de3-c180-cffe-8a1e61c49037
* Version Independent ID: 3c418504-fd6c-9ace-c6d9-2f59569db329
* Content: [AD FS 2016 Overview](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/ad-fs-overview)
* Content Source: [WindowsServerDocs/identity/ad-fs/ad-fs-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/ad-fs-overview.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by biren1234** [comment]
yaa there is no word

**Comment by dsstao** [comment]
Found it (though it should be here): https://msdn.microsoft.com/en-us/library/ms674895(v=VS.85).aspx

**Comment by dcbrown16** [comment]
Yes, please fall in line with other Azure services and provide an actual overview topic here.

**Comment by sarin-rajendran** [comment]
Also, https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/technical-reference/understanding-key-ad-fs-concepts#overview-of-ad-fs

**Comment by PRMerger18** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: ingridatmicrosoft 
gh issue comment 2534 -b ingridatmicrosoft
