### ISSUE TITLE
Tools missing after enabling

### ISSUE THREAD

**Issue by hueyg** [MicrosoftDocs/windowsserverdocs#2540]
I am not sure who has decided that improving Windows means adding 50 steps and hiding an old application through 10 menu trees is an improvement.  1809 destroyed my RSAT tools that I actually use for work.  So now they are a feature.  Great, I enable the feature and they appear no where.  Uninstalled/reinstalled/changed policy settings and nothing.  Windows 10 is a constant battle as to what tool will break next or where it will be moved so I might click on a mobile game instead.  Please bring back any UI designer that is over 50 so I can actually get back to work.  You guys are making me lose my mind.  Sorry for the meltdown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36ff1fe9-9cfb-6227-8502-e43093b0c804
* Version Independent ID: cba8ee81-dcb4-1a6d-0f8c-407db54df109
* Content: [Remote Server Administration Tools](https://docs.microsoft.com/en-us/windows-server/remote/remote-server-administration-tools#feedback)
* Content Source: [WindowsServerDocs/remote/remote-server-administration-tools.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-server-administration-tools.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by dridenhour** [comment]
I agree, this is the STUPIDEST IDEA EVER!!!

I have installed this several times in the past on different machines - it took 5-10 minutes depending upon download speed for the tools.

I have now wasted ONE HOUR at least on this and still don't have it installed and working.

WHAT A DUMB IDEA!!!

Go back to the simple install that you download PLEASE!!!

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
