### ISSUE TITLE
Windows 10 VM Activation

### ISSUE THREAD

**Issue by yoer1** [MicrosoftDocs/windowsserverdocs#2543]
Question: When you are running a Windows Server 2016 and you want to activate your windows 10 vm. Is AVMA keys will work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 960f9460-e1de-949c-ae1a-ad24a34cc1c2
* Version Independent ID: c9b5b530-5a39-0136-fb9a-15389ccd6691
* Content: [Automatic virtual machine activation](https://docs.microsoft.com/en-us/windows-server/get-started-19/vm-activation-19#feedback)
* Content Source: [WindowsServerDocs/get-started-19/vm-activation-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/vm-activation-19.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by niceysj** [comment]
Is this available???

**Comment by jdravet** [comment]
Would be a great feature to add if not already supported.
