### ISSUE TITLE
[WAC] How to get session (credentials) of the Server Manager connection provider in the custom gateway plugin?

### ISSUE THREAD

**Issue by akviacode** [MicrosoftDocs/windowsserverdocs#2547]
Hello,

We are developing WAC Extension. And according to provided documentation [here](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/extend/develop-gateway-plugin):

> If you would like to communicate with a protocol other than PowerShell or WMI, such as with REST, you can build your own gateway plugin.

we need to develop custom gateway plugin to communicate with our WCF service. In this case we need to pass to the WCF request the credentials (login and password), that was previously entered by the user to open the session with this host.
If it is a custom Solution Extension, we can store entered connection provider credentials on the Login page. But if it is a Tool Extension added for example to the Server Manager Solution, we have no access to the entered credentials. How to get session (credentials) of the Server Manager connection provider in the custom gateway plugin?

So described workflow based on your example gateway plugin from WAC SDK:
1) User enters credentials here:
![image](https://user-images.githubusercontent.com/48491327/54231649-f47f6780-4519-11e9-950f-f0f4f7a9fae9.png)
2) In the sample extension Users clicks the button.
![image](https://user-images.githubusercontent.com/48491327/54233586-44f8c400-451e-11e9-92cb-852eb078c30f.png)
Where button is subscribed on this code:
```
let test = this.appContextService.gateway.gatewayUrl
let callUrl = this.appContextService.activeConnection.nodeName;

return this.appContextService.node.get(callUrl, 'features/Sample%20Uno').map(
 (response: any) => {
	 return response;
 }
)
```
3) And here in C# class we need credentials, that was entered on step 1. But there are no appropriate headers in passed parameters. And there are no known way to get this information from this.appContextService on step 2.
```
protected override async Task<HttpResponseMessage> Process(PlugInUrl url, HttpRequestMessage request, CancellationToken cancellationToken)
{
	// simulate long-running operation
	await Task.Delay(1000).ConfigureAwait(false);

	try
	{
		//TODO: need to get login password here
		var credentials = ...

		this._serviceAgent.Connect(url.TargetNode, credentials);
	}
	catch (Exception e)
	{
		// ignored
	}
	
	return new HttpResponseMessage()
	{
		StatusCode = HttpStatusCode.OK,
		Content = new StringContent($"{{\"message\":\"Hello world from '{this.Name}'\"}}", Encoding.UTF8, "application/json"),
	};
}
```

And after some research of JS code we've got that this.appContextService.authorizationManager.nodeTokens[] contain properties Username and​​​ Value. Where Value is base64 string. After decoding it, got something like this:
`{"domain":"...","username":"...","password":"g+...==","passwordEncryptedWith":"JWK"}`
Password here is encoded.
So, looks like should be the way to get this credentials, pass them to the custom gateway plugin, and communicate with our WCF service. But we cannot find information about this in Microsoft provided documentation. Can you help us and explain the way it should be implemented? 

Thanks,
Alexey

**Comment by mattatmsft** [comment]
Check out the examples "PlugInIdentityExample" and "PromptForCreds" here: https://github.com/Microsoft/windows-admin-center-sdk/tree/master/Examples
