### ISSUE TITLE
Wait time between two reset

### ISSUE THREAD

**Issue by Aghonge** [MicrosoftDocs/windowsserverdocs#2573]
In Note section:  How long do we have to wait between the first and second resets?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f60e6dd-9b73-a29f-e40a-34859c3917f4
* Version Independent ID: 4c7edf07-0546-f755-1633-4dba68389dbe
* Content: [AD Forest Recovery - Resetting the krbtgt password](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/ad-forest-recovery-resetting-the-krbtgt-password#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/AD-Forest-Recovery-Resetting-the-krbtgt-password.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/manage/AD-Forest-Recovery-Resetting-the-krbtgt-password.md)
* Product: **windows-server-threshold**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by dbznico** [comment]
You have to wait at least 10h, this add in note section will be welcome :)
