### ISSUE TITLE
all this is DirectAccess only, not Remote Access

### ISSUE THREAD

**Issue by sasanmcp** [MicrosoftDocs/windowsserverdocs#2580]
we should be clear in the documentation that all this multi-site features are something DirectAccess can use. VPN servers will not use these multi-site features and rely on external geo-balancers for multi-site scenarios.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f87fe38-1657-d659-0feb-b9e415b9114f
* Version Independent ID: 2cb254e7-3060-ed1b-b8f1-117931350bcd
* Content: [Deploy Multiple Remote Access Servers in a Multisite Deployment](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/ras/multisite/deploy-multiple-remote-access-servers-in-a-multisite-deployment)
* Content Source: [WindowsServerDocs/remote/remote-access/ras/multisite/Deploy-Multiple-Remote-Access-Servers-in-a-Multisite-Deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/ras/multisite/Deploy-Multiple-Remote-Access-Servers-in-a-Multisite-Deployment.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
