### ISSUE TITLE
In RD client keyboard when I press a key it pressed 3 times

### ISSUE THREAD

**Issue by gunasekaranarts** [MicrosoftDocs/windowsserverdocs#2582]
In Android RD client when I started to type, each key when i am pressing get printed 3 times. For eg If I type a letter "a" it showing "aaa"

**Comment by WeirdExponent** [comment]
I have this issue also, running Android app in ChromeOS

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
