### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by kaevans** [MicrosoftDocs/windowsserverdocs#2585]
Link to "Active Directory in Networks Segmented by Firewalls" is a dead link. https://go.microsoft.com/fwlink/?LinkId=107074 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a52f2469-d5d9-b9de-e140-c899b2dec1ea
* Version Independent ID: 65bca3ea-50a6-36de-6398-b97324cc0917
* Content: [Creating a Site Link Bridge Design](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/creating-a-site-link-bridge-design)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/Creating-a-Site-Link-Bridge-Design.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/Creating-a-Site-Link-Bridge-Design.md)
* Product: **windows-server-threshold**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
There is a KB Article located below that has information about this topic.
https://support.microsoft.com/help/179442/how-to-configure-a-firewall-for-domains-and-trusts

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
