### ISSUE TITLE
The system could not find the phone book entry for this connection. 

### ISSUE THREAD

**Issue by FareeZz** [MicrosoftDocs/windowsserverdocs#2586]
When i run the Makeprofile script i get the following error.

Get-VpnConnection :  VPN connection ~VPNNAME~ was not found. : The system could not find the phone book entry for this connection.
At line:9 char:16
+  $Connection = Get-VpnConnection -Name $TemplateName
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (~VPNNAME~:root/Microsoft/...S_VpnConnection) [Get-VpnConnection], CimException
    + FullyQualifiedErrorId : VPN 623,Get-VpnConnection
 
I looked everywhere on the internet to find a solution but i cant find it anywhere

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7453068-95eb-2a42-fd0b-553ae593adb0
* Version Independent ID: b39b2cb7-25b1-2af3-4954-dbcc04c836e9
* Content: [Configure Windows 10 Client Always On VPN Connections](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections#feedback)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by FareeZz** [comment]
I checked if there was a phonebook entry and there was one of my VPN

**Comment by daveba** [comment]
@FareeZz It seems like your issue is solved.  I will close now.  Please feel free to reopen if you still have a problem.

**Comment by ceztko** [comment]
In my case I was really just misspelling the VPN connection name. I just enumerated the connections first with `Get-VpnConnection` in powershell to find the correct name.
