### ISSUE TITLE
What clustered workloads are supported in this configuration?

### ISSUE THREAD

**Issue by daveberm** [MicrosoftDocs/windowsserverdocs#2590]
When the cluster uses S2D as shown here, what clustered workloads could you run on top of this? My understanding is that the primary use case is Scale Out File Servers and Hyper-V HCI. What about running a 2-node SQL Server FCI with S2D in Region 1 and then use SR to replicate to a 2-node SQL Server FCI in in Region 2. I have heard from a SQL Server MVP that this configuration does not work. Is that true? If it does not work can you clarify the documentation to specify which clustered workloads are supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7427fc8-7930-7ff0-dbd1-8805731002ae
* Version Independent ID: e36fb931-b5fd-8d41-75eb-aacf447fb358
* Content: [Cluster to Cluster Storage Replica cross region in Azure](https://docs.microsoft.com/en-us/windows-server/storage/storage-replica/cluster-to-cluster-azure-cross-region)
* Content Source: [WindowsServerDocs/storage/storage-replica/cluster-to-cluster-azure-cross-region.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-replica/cluster-to-cluster-azure-cross-region.md)
* Product: **windows-server-threshold**
* GitHub Login: @arduppal
* Microsoft Alias: **arduppal**

**Comment by arduppal** [comment]
Storage replica is a block-level replication solution. For Cluster-to-Cluster replication it should copy the data from source to destination. But it requires manual intervention for failover. It depends on app how it comes back up on the other-side during disaster.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
