### ISSUE TITLE
AAD Connect  - Express or Custom install?

### ISSUE THREAD

**Issue by josuvil** [MicrosoftDocs/windowsserverdocs#2592]
Hello,
According to the pre-requisites section, it points to using custom installation method of AAD Connect without explaining which custom feature to add. However, Step 1 points you to setting up AAD Connect using the Express method which installs basic features. Which method is really required: Custom or Express? Also, can you please add which specific synchronization feature or component of AAD Connect is required in order for Hybrid Cloud Print to work properly? Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21d1d072-911f-92c0-248a-9e44efbff42d
* Version Independent ID: 0fdb921d-d97d-5b12-ae28-286216e130df
* Content: [Deploy Windows Server Hybrid Cloud Print](https://docs.microsoft.com/en-us/windows-server/administration/hybrid-cloud-print/hybrid-cloud-print-deploy)
* Content Source: [WindowsServerDocs/administration/hybrid-cloud-print/hybrid-cloud-print-deploy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/hybrid-cloud-print/hybrid-cloud-print-deploy.md)
* Product: **windows-server-threshold**
* GitHub Login: @msjimwu
* Microsoft Alias: **coreyp**

**Comment by Bigblackshinyclock** [comment]
I Need to know this too, it does not specify which type of sync is supported. can anybody please provide some additional information about this?
