### ISSUE TITLE
Cannot Remove Admin Center

### ISSUE THREAD

**Issue by jlivingston91** [MicrosoftDocs/windowsserverdocs#2595]
I tried to simply remove the installation (Windows Server 2019) and I am now receiving this during the removal process. 

       Product: Windows Admin Center -- 1: Unhandled Exception: System.NullReferenceException Object reference not set to an 
       instance of an object. 

Do we have all of the locations that I can clean out manually? I have tried the ones mentioned here with no luck.
1. Registry under Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall
2. Removing the folder under C:\Windows\ServiceProfiles\NetworkService\AppData\Roaming\Microsoft
3. Removing the folder under C:\Program Files the Admin Center folder
4. Removing the folder under C:\Program Data the Admin Center folder

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1c16ba9-2fc0-4c4e-8e98-71fa6149224c
* Version Independent ID: 95a061bd-a176-1ec3-259d-2a3925ca279e
* Content: [Windows Admin Center Known Issues](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/known-issues#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/use/known-issues.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/use/known-issues.md)
* Product: **windows-server-threshold**
* GitHub Login: @jwwool
* Microsoft Alias: **jeffrew**

**Comment by fbreuker** [comment]
I had the same thing. After manually removing the self signed Windows Admin Center certificates, i could uninstall Windows Admin Center.

**Comment by bigmaggot** [comment]
I fixed by deleting the self signed certificate:

certutil -store my

Find the self signed certificate from "Issuer: CN=Windows Admin Center Encryption", take note of the Serial Number (or Cert Hash or anything really that identified the cetifcate), i.e. XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

certutil -delstore my XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by eugeniomiro** [comment]
This also happened to me when trying to upgrade to Admin Center 2007 when having 1904.1 installed, 
Even if I deleted the self signed cert it didn't update, until I uninstalled the old and then install the new one. 
Hope that helps

**Comment by illfated** [comment]
I suppose the moral here is that a non-functioning Windows Admin Center is unlikely to be removed successfully, so you need to restore it to a working state before removal.

**Comment by williamgh2019** [comment]
Use Free iOBIT Uninstaller to uninstall Admin Center, it work for me.
https://www.iobit.com/en/advanceduninstaller.php

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
