### ISSUE TITLE
Connection tools import

### ISSUE THREAD

**Issue by redmondp** [MicrosoftDocs/windowsserverdocs#2599]
The tools do not exist in this location. I cannot import using powershell
ProgramFiles\windows admin center\PowerShell\Modules\ConnectionTools

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 239ce76b-e4b8-77d0-8e89-f35d85580e23
* Version Independent ID: 4c8f067e-2a3d-2058-6a77-8028e3889843
* Content: [Get started with Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/get-started#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/use/get-started.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/use/get-started.md)
* Product: **windows-server-threshold**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by Billabongodysee** [comment]
You have to finish it off with "ConnectionTools.psm1". The entire command would be "Import-Module "$env:ProgramFiles\windows admin center\PowerShell\Modules\ConnectionTools\ConnectionTools.psm1"
