### ISSUE TITLE
Graphics I/O performance

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windowsserverdocs#2604]
Please add a section on Graphics I/O performance. I am stuck on slow GUI updates in Ubuntu 18.
I am using Windows Server 2019.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3488db8-ef2d-1814-8276-a95193f21207
* Version Independent ID: 8ebe7f9e-93dc-f27c-9ddf-cc21301ceb99
* Content: [Linux Virtual Machine Considerations](https://docs.microsoft.com/en-us/windows-server/administration/performance-tuning/role/hyper-v-server/linux-virtual-machine-considerations#feedback)
* Content Source: [WindowsServerDocs/administration/performance-tuning/role/hyper-v-server/linux-virtual-machine-considerations.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/performance-tuning/role/hyper-v-server/linux-virtual-machine-considerations.md)
* Product: **windows-server-threshold**
* GitHub Login: @phstee
* Microsoft Alias: **Asmahi; SandySp; JoPoulso**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
