### ISSUE TITLE
w32tm parameters in angle brackets being interpreted as HTML tags

### ISSUE THREAD

**Issue by kenyon** [MicrosoftDocs/windowsserverdocs#2605]
There are a bunch of w32tm parameters in angle brackets (&lt; and &gt;) that are not shown in the rendered document because markdown interprets them as HTML tags. These brackets need to be replaced with the HTML entities `&lt;` and `&gt;`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc978a2-5a8b-c6af-0c56-f762ea9edf16
* Version Independent ID: 33693e91-d1a2-10c0-0dd7-43167114868a
* Content: [Windows Time Service Tools and Settings](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings#feedback)
* Content Source: [WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
