### ISSUE TITLE
"There are no configuration steps necessary"

### ISSUE THREAD

**Issue by ewest305** [MicrosoftDocs/windowsserverdocs#2607]
Under "Server Manager information", it says there are no configuration steps necessary. However, there are sub articles explaining registry changes. See 'TLS Registry Settings'. This is confusing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e768bd7f-6ba6-3f69-6c0b-71d0828f74d8
* Version Independent ID: 1b969189-7cc7-0320-e0a4-14690ae4c8dd
* Content: [TLS/SSL overview (Schannel SSP)](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-ssl-schannel-ssp-overview#feedback)
* Content Source: [WindowsServerDocs/security/tls/tls-ssl-schannel-ssp-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-ssl-schannel-ssp-overview.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
