### ISSUE TITLE
Link missing for reference to Article

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/windowsserverdocs#2608]
In **Applications and user experience after the additional configuration** section it says "_We recommend using the client side registry key noted in this article_" but a link to an article is missing. 

Also, it would be great to add actually WHICH registry keys needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02d8b61-29e8-c0a7-b3b2-79be7212a91c
* Version Independent ID: b4346d87-0727-c7fe-7896-7fd79098825c
* Content: [Configuring Alternate Login ID](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configuring-alternate-login-id)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configuring-Alternate-Login-ID.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configuring-Alternate-Login-ID.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by DeanGross** [comment]
please add the link

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by PRMerger17** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: ingridatmicrosoft 
gh issue comment 2574 -b ingridatmicrosoft
