### ISSUE TITLE
Needs details about Feature Upgrades

### ISSUE THREAD

**Issue by pilcherd** [MicrosoftDocs/windowsserverdocs#2610]
Arrived here looking for how to upgrade 2016 Standard 14393 to 2016 Standard 17763 (1809).  Page should say how to obtain and install Feature Upgrades for Windows Server 2016.  Windows Update is showing nothing after a clean install and all 14393 CU's installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adf594c8-5d55-8bfe-99b8-e1a1f91081fd
* Version Independent ID: 32ba9200-79f5-671d-bcc5-650540e8e94f
* Content: [Upgrade and Conversion Options for Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/get-started/supported-upgrade-paths)
* Content Source: [WindowsServerDocs/get-started/Supported-Upgrade-Paths.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/Supported-Upgrade-Paths.md)
* Product: **windows-server-threshold**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
