### ISSUE TITLE
Set-WebApplicationProxySslCertificate example doesn't include the -Thumbprint flag

### ISSUE THREAD

**Issue by msorri** [MicrosoftDocs/windowsserverdocs#2614]
The example command "Set-WebApplicationProxySslCertificate '&lt;thumbprint of new cert&gt;'" is incorrect. The correct command would be "Set-WebApplicationProxySslCertificate -Thumbprint '&lt;thumbprint of new cert&gt;'".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d10177c6-b241-0a3e-d6ba-3619c094812a
* Version Independent ID: 7a42691f-7f28-eee2-0c69-294e24cccdbe
* Content: [Managing SSL Certificates in AD FS and WAP in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/manage-ssl-certificates-ad-fs-wap#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/manage-ssl-certificates-ad-fs-wap.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/manage-ssl-certificates-ad-fs-wap.md)
* Product: **windows-server-threshold**
* GitHub Login: @jenfieldmsft
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
