### ISSUE TITLE
'/m' under Windows 10

### ISSUE THREAD

**Issue by VBScab** [MicrosoftDocs/windowsserverdocs#2622]
Every test I've performed shows that, unless '/m' is the very first argument rather than the last as shown in your examples, the variable is set in the logged-in user's context not the machine's.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 729e13a6-1bda-9c54-94ee-6171371c1085
* Version Independent ID: 3c6b2c92-59fc-08df-587e-0f68aa73e94a
* Content: [setx](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/setx#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/setx.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/setx.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
