### ISSUE TITLE
Provide information on how to remove a link

### ISSUE THREAD

**Issue by varnk** [MicrosoftDocs/windowsserverdocs#2626]
The current documentation isn't very clear about how to remove a link created with MKLink.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe72a6d-c0c6-8cc1-fc16-9912594fbe3e
* Version Independent ID: b6ce16a6-8f41-5551-d55f-244238814459
* Content: [mklink](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/mklink.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/mklink.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by guruqiu** [comment]
Hi, varnk
Just use rd... command to delete the pseudo folder which you created by symbolic link. Don't worry about the actual contents in the linked real folder, they will be remained as they were.

**Comment by guruqiu** [comment]
However please pay attention to use Junction mode or hard link mode(/J /H). They are powerful than symbolic link (/D) but lead to more complex status in file system.

**Comment by NeoBeum** [comment]
This issue can now be closed.
https://github.com/MicrosoftDocs/windowsserverdocs/commit/709c0ffb97cd2c4547b4f277c2ca3135009ac387
