### ISSUE TITLE
Missing parameters

### ISSUE THREAD

**Issue by edseidman** [MicrosoftDocs/windowsserverdocs#2632]
I just took a quick look, and notice at least the following missing parameters:

gatewayaccesstoken:s: - used for PAA cookies
gatewaycredentialssource - value 5 is for PAA tokens
gatewaybrokeringtype
DisableDpiCursorScalingForProcess - added recently
camerastoredirect - added recently

There may be more.  This was just from a cursory look

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44146ebc-7180-8e26-2f06-3e044a25c458
* Version Independent ID: e63558c7-8fd1-fa3c-8a8b-03ea844e77bb
* Content: [Remote Desktop - compare the client apps](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-app-compare)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-app-compare.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-app-compare.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
