### ISSUE TITLE
2560x1440 Resolution DEX Android RD Client

### ISSUE THREAD

**Issue by giz02** [MicrosoftDocs/windowsserverdocs#2634]
I run DEX @ 2560x1440 on an SGS10 and i was previouslly able to use RDP full screen - this stopped working unexectedly.

Now when Iauch, RDP launches full screen but the rdp session is scalled into the upperf left corner of my screenu. What makes this unusable is that the video display is lower than the actual mouse geography, resulting in scaled mouse movement that makes moused navigation it difficult /unuseable. This happens regardless of what I set the RDP session resolution to .

The problem is resolved if I set my Dex to resolution to 1920x1080.  When I do this, RDP launches full screen.

Has something in the app changed

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
