### ISSUE TITLE
See my last comment on the only closed issue

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/windowsserverdocs#2636]
This article does still need improving.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54d73e9d-e08d-9184-e357-65b9f5a19bc1
* Version Independent ID: 8c60d2ba-8fe4-cabf-0dda-72dbf58f1b73
* Content: [Add an Attribute Store](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/add-an-attribute-store#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Add-an-Attribute-Store.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Add-an-Attribute-Store.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
