### ISSUE TITLE
Import Bulk Connections from CSV, TXT, or XML file

### ISSUE THREAD

**Issue by abarber229** [MicrosoftDocs/windowsserverdocs#2645]
Would you guys be able to add a bulk import option into the RDP app. It would be very nice, instead of having to manually type in every server name again. I currently have 75 connections in my remote desktop connection manager. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef479a2e-4ca4-1c81-a465-dd476ef95ff0
* Version Independent ID: 877f5d0b-3849-4ff3-7ebd-e109cc1508ab
* Content: [Get started with Remote Desktop on iOS](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-ios#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-ios.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-ios.md)
* Product: **windows-server-threshold**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by adresner** [comment]
I also agree with adding this feature, in addition, sync connections between iOS devices via iCloud should be very easy for developers

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
