### ISSUE TITLE
Database connection from sample project does not match instructions

### ISSUE THREAD

**Issue by utmab04** [MicrosoftDocs/windowsserverdocs#2646]
Loaded the project sample through Visual Studio 2015 following up to Step 3 of Database Upgrade.  Connections listed included "DefaultConnection (OAuth2-UserIdentity)" as a Microsoft SQL Server data source instead of a Microsoft SQL Server Database File titled "DefaultConnection (WebApp)" as presented in the instructions.  Project is also titled "OAuth2-UserIdentity" instead of "WebApp".  This may also affect Step 11 of Create Application Group if the Identifier is no longer valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29422078-e443-7a9a-7342-ca6915e4ffaa
* Version Independent ID: f19ea02c-4bbc-7b65-78c3-b8613a8154e5
* Content: [Build a server side application using OAuth confidential clients with AD FS 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/enabling-oauth-confidential-clients-with-ad-fs#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/enabling-oauth-confidential-clients-with-ad-fs.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/enabling-oauth-confidential-clients-with-ad-fs.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
