### ISSUE TITLE
Document Links in 'What's New in Active Directory Domain...'

### ISSUE THREAD

**Issue by haselton** [MicrosoftDocs/windowsserverdocs#265]
Is there a reason for that the following links are pointing to the technet website link rather than the sub-topics within the document?

- Privileged access management
- Extending cloud capabilities to Windows 10 devices through Azure Active Directory Join
- Connecting domain-joined devices to Azure AD for Windows 10 experiences
- Enable Microsoft Passport for Work in your organization
- Deprecation of File Replication Service (FRS) and Windows Server 2003 functional levels

It breaks the PDF document if downloaded; rather than going to the subtopic it opens a webpage.

If the links should be going to technet, perhaps they could be added to a More Information... section at the end of the document or after each section.

For example:

- [Privileged access management](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/whats-new-active-directory-domain-services.md#privileged-access-management)
  Privileged Access Management
  verbiage about PAM
  For more information on PAM see:  [Privileged Access Management for Active Directory Domain Services](https://docs.microsoft.com/en-us/microsoft-identity-manager/pam/privileged-identity-management-for-active-directory-domain-services)

**Comment by lizap** [comment]
This is excellent feedback - I'll share it with the writing team for this set of content. Thanks!

**Comment by lizap** [comment]
We've updated the links - thanks!
