### ISSUE TITLE
Typo in task name

### ISSUE THREAD

**Issue by madsamuel** [MicrosoftDocs/windowsserverdocs#2652]
there is a type in the Task Scheduler the task is RecoveryEnviornment, not Recovery Enviornment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a83e1751-011c-9add-2c0a-63159fef97da
* Version Independent ID: 119b5192-3775-f71e-579d-9ead105ed1b0
* Content: [Recommended configuration for VDI desktops](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-vdi-recommendations#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-vdi-recommendations.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-vdi-recommendations.md)
* Product: **windows-server-threshold**
* Technology: **remote-desktop-services**
* GitHub Login: @jaimeo
* Microsoft Alias: **elizapo**

**Comment by baardhermansen** [comment]
There's a typo in your typo :P
RecoveryEnvironment is correct.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
