### ISSUE TITLE
Command syntax

### ISSUE THREAD

**Issue by dwvanallen** [MicrosoftDocs/windowsserverdocs#2663]
https://docs.microsoft.com/en-us/windows-server/identity/securing-privileged-access/privileged-access-workstations#feedback

On the following:
> 8. Force the Group Policy application.
> Open an elevated command prompt and enter the following command: `Gpupdate /force /sync`

According to gpupdate documentation:
> /Sync
> Causes the next foreground policy application to
> be done synchronously. Foreground policy
>                             applications occur at computer start up and user
>                             logon. You can specify this for the user,
>                             computer or both using the /Target parameter.
>                             **The /Force and /Wait parameters will be ignored
>                             if specified.**

**Comment by illfated** [comment]
The documentation page has moved, or is integrated in a different document location.
I am currently unable to identify where this issue can be found. Sorry about that.
Please look for the new documentation and report any issues from there.

#please-close
