### ISSUE TITLE
Here is no description how to deal with disk security issues!

### ISSUE THREAD

**Issue by dmitrybond173** [MicrosoftDocs/windowsserverdocs#2668]
A simple example: I moved data HDD from one system (Win2012 R2) to another (Win 2016). 
But now programs does not work because some disk permissions do not match 'some tricky conditions'. 
Please note: ALL PERMISSIONS on HDD ARE DEFAULT ONES! So, I did not configured anything special. All folders structure were created from Windows Explorer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1523bcb-77d6-5e4c-bdd7-e71598ef43ef
* Version Independent ID: 9dbb2dcb-eaac-18d4-b324-f0130ba7a1da
* Content: [Move disks to another computer](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/move-disks-to-another-computer#feedback)
* Content Source: [WindowsServerDocs/storage/disk-management/move-disks-to-another-computer.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/move-disks-to-another-computer.md)
* Product: **windows-server-threshold**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
