### ISSUE TITLE
PowerShell command does not include Windows 10 OS

### ISSUE THREAD

**Issue by MaximeRastello** [MicrosoftDocs/windowsserverdocs#2669]
Please update the PowerShell cmdlet to include Windows 10 PCs for WIA support

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d6a8f34-a392-d1f2-fb61-0d34bca5ab0d
* Version Independent ID: a6cb49c5-2ac2-77e8-7f39-493713f7e9a8
* Content: [Configuring intranet forms-based authentication for devices that do not support WIA](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-intranet-forms-based-authentication-for-devices-that-do-not-support-wia)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-intranet-forms-based-authentication-for-devices-that-do-not-support-WIA.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-intranet-forms-based-authentication-for-devices-that-do-not-support-WIA.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Eameener** [comment]
Does the PowerShell cmdlet applicable for Windows Server 2012, if not how can it be enabled on Windows Server 2012.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
