### ISSUE TITLE
RDP to Azure AD Joined PC from Android

### ISSUE THREAD

**Issue by sadjadbp** [MicrosoftDocs/windowsserverdocs#2672]
Starting the latest update v8.1.67.369, I cannot connect to my Azure AD joined PC from my Android. Issue is as explained here
https://docs.microsoft.com/en-us/windows/client-management/connect-to-remote-aadj-pc#set-up in the Notes section
"When you connect to the remote PC, enter your account name in this format: AzureAD\YourAccountName". but with this new update how ever I tried I won't work anymore. The older version used to give me access to the Login Page on the PC so I could enter AzureAD\me@mydomain.com, but now that don't show up, it just gives me the Anrdoid App login page. I've tried all these combinations and nothing worked

me@mydomain.com
mydomain\me
AzureAD\me@mydomain.dom

Any work arounds?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45d9f311-2994-948d-ad91-f5c7370d73ec
* Version Independent ID: 5f978676-6f53-3f2d-fabb-3554027edbcc
* Content: [Get started with Remote Desktop on Android](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-android#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-android.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-android.md)
* Product: **windows-server-threshold**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by jasonkatz424** [comment]
I have this same question.  I've tried all of the variations you would normally including AzureAD\xyz@zyz.onmicrosoft.com.

Curious if this is possible.

**Comment by michevnew** [comment]
Same. This was working in older versions...

**Comment by piotr-boronczyk** [comment]
What's the status of this issue?

**Comment by iceman3000** [comment]
Can we have an update on this? It would seem that connecting to AzureAD joined PC's via Remote Desktop is a somewhat impossible task. The workaround seems to be disable Network Level Auth on the Host PC and then update the Remote Desktop Client to connect without Auth (to then provide it at the hosted login screen). That solution only works on Windows Host machines, what about Mac, Android and iOS where connect without Auth is not an option? Disappointed that such a critical feature doesn't work properly with AzureAD. Anyone have any solutions?

**Comment by sadjadbp** [comment]
> Can we have an update on this? It would seem that connecting to AzureAD joined PC's via Remote Desktop is a somewhat impossible task. The workaround seems to be disable Network Level Auth on the Host PC and then update the Remote Desktop Client to connect without Auth (to then provide it at the hosted login screen). That solution only works on Windows Host machines, what about Mac, Android and iOS where connect without Auth is not an option? Disappointed that such a critical feature doesn't work properly with AzureAD. Anyone have any solutions?

Plus one, exactly to the point

**Comment by Jamie-Vangeysel** [comment]
wait, you thin Microsoft still cares about RDP on Windows? lol

**Comment by michevnew** [comment]
Um, is anyone monitoring this?

**Comment by jessenic** [comment]
Same issue, any update?

**Comment by logicalcom** [comment]
same issue!

**Comment by Torrentus** [comment]
Experiencing the same here unfortunately.

**Comment by hamistheman** [comment]
Confirming this is still an issue
