### ISSUE TITLE
AD FS 2019 on Windows 2016 domain

### ISSUE THREAD

**Issue by rphoon** [MicrosoftDocs/windowsserverdocs#2683]
Is it possible / supported to run an ADFS on server 2019 whilst there is a mixed domain with Windows 2008 R2 and 2016 domain controllers? Domain functional level is 2008 R2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68bac2aa-024c-a014-eeaf-f28a44b31c5e
* Version Independent ID: 86c83819-91d6-c990-16f1-d05ebdf07b58
* Content: [AD FS 2016 Requirements](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-requirements#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/ad-fs-requirements.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/ad-fs-requirements.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
