### ISSUE TITLE
Deploying a server from vm

### ISSUE THREAD

**Issue by Cbeg-76** [MicrosoftDocs/windowsserverdocs#2685]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fafb0b-fc45-7c65-8a22-43abb95c242c
* Version Independent ID: cbee5046-aa5e-eb1b-641c-cb044cb58f3a
* Content: [Install a New Windows Server 2012 Active Directory Forest (Level 200)](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/install-a-new-windows-server-2012-active-directory-forest--level-200-#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/Install-a-New-Windows-Server-2012-Active-Directory-Forest--Level-200-.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/Install-a-New-Windows-Server-2012-Active-Directory-Forest--Level-200-.md)
* Product: **windows-server-threshold**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by Cbeg-76** [comment]
Is it possible to deploy a home server from a vm?
Or would you need to have a stand alone server/pc for operation?

**Comment by MicrosoftGuyJFlo** [comment]
@Cbeg-76 Clarify what you want to do. I do not understand what you are asking here.

**Comment by Cbeg-76** [comment]
I want to run a VM on my desktop to deploy a server that can be used for a home network.
