### ISSUE TITLE
This is not true.

### ISSUE THREAD

**Issue by IN-jwink** [MicrosoftDocs/windowsserverdocs#2695]
"We're removing this secure scanning and scanner management capability - there are no devices that support this feature."

I support 2000 devices that all fully support this feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8cfdc3e-5fe2-e196-cc8d-8973bdd225f3
* Version Independent ID: 8c8bd580-8e2c-a927-9163-e764f44070ec
* Content: [Features removed or planned for removal in Windows Server 2019](https://docs.microsoft.com/en-us/windows-server/get-started-19/removed-features-19#feedback)
* Content Source: [WindowsServerDocs/get-started-19/removed-features-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/removed-features-19.md)
* Product: **windows-server-threshold**
* Technology: **server-general**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
