### ISSUE TITLE
Storage Spaces on Azure iaas and on VMWare

### ISSUE THREAD

**Issue by stephc-msft** [MicrosoftDocs/windowsserverdocs#2698]
Please clarify if Storage Spaces supported in a VM environment 
as https://social.technet.microsoft.com/wiki/contents/articles/11382.storage-spaces-frequently-asked-questions-faq.aspx#What_are_the_recommended_configuration_limits  
says/implies not.

There is a statement about S2D in such an environment in the Storage Spaces Direct section here (says it is supported with caveats), and those same caveats should apply to stand alone / local Storage Spaces as well

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acd8af43-5256-169f-fe3c-c890521cf888
* Version Independent ID: 6052c6dc-af27-eb51-1cbc-53ca1d026f26
* Content: [Deploy Storage Spaces on a stand-alone server](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/deploy-standalone-storage-spaces)
* Content Source: [WindowsServerDocs/storage/storage-spaces/deploy-standalone-storage-spaces.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/deploy-standalone-storage-spaces.md)
* Product: **windows-server-threshold**
* Technology: **storage-spaces**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
