### ISSUE TITLE
Maximum time duration for "Offline Mode" (AllowKeyMaterialCaching:$true)

### ISSUE THREAD

**Issue by milesgratz** [MicrosoftDocs/windowsserverdocs#2699]
What is the maximum duration of time for "Offline Mode" if `Set-HgsKeyProtectionConfiguration -AllowKeyMaterialCaching:$true` is configured? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebf450ef-374e-598a-082b-ab4aa9aa1245
* Version Independent ID: 835778b3-c196-66fc-dff9-e3a7d3d51a96
* Content: [Branch Office Considerations](https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-manage-branch-office#offline-mode)
* Content Source: [WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-manage-branch-office.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-manage-branch-office.md)
* Product: **windows-server-threshold**
* Technology: **security-guarded-fabric**
* GitHub Login: @rpsqrd

**Comment by rpsqrd** [comment]
Hi @milesgratz,

The lifetime of cached keys is determined by the health state of the host, not real time. You can re-use the cached key indefinitely until the security state of the host changes (under the hood, when the security measurements change, the key encrypting the cached keys is rolled, preventing the keys from being unsealed). The only other event that will invalidate a key is a successful online attestation attempt to an HGS node that is configured to disallow key caching.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
