### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by deisterhold** [MicrosoftDocs/windowsserverdocs#2701]
There is a broken link on [Windows Admin Center](https://www.microsoft.com/cloud-platform/windows-admin-center) when clicking "See how to use Windows Admin Center", it links to https://docs.microsoft.com/windows-server/manage/windows-admin-center/use/launch which results in a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 239ce76b-e4b8-77d0-8e89-f35d85580e23
* Version Independent ID: 4c8f067e-2a3d-2058-6a77-8028e3889843
* Content: [Get started with Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/get-started#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/use/get-started.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/use/get-started.md)
* Product: **windows-server-threshold**
* Technology: **manage**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
