### ISSUE TITLE
Remove the Vague-ness?

### ISSUE THREAD

**Issue by davo123456** [MicrosoftDocs/windowsserverdocs#2702]
Hi there,

I am looking at implementing Printing from my On-prem printers via newly Azure only joined Intune controlled devices.

The diagram and subsequent sub documents talk about installing on "Print Server" which is not clear which server,  the Azure Web Services Print Server or the existing on Prem server?  

Does the On Prem server need to be 2016? is step one of installing a feature on this server?  

Can this article be made less vague?  

otherwise love your work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c4e7221-25fc-1aff-75e4-47ce9ac6c285
* Version Independent ID: 36236322-05f4-8cf8-dfa2-a4943dc5bb58
* Content: [Windows Server Hybrid Cloud Print overview](https://docs.microsoft.com/en-us/windows-server/administration/hybrid-cloud-print/hybrid-cloud-print-overview#feedback)
* Content Source: [WindowsServerDocs/administration/hybrid-cloud-print/hybrid-cloud-print-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/hybrid-cloud-print/hybrid-cloud-print-overview.md)
* Product: **w10**
* Technology: **server-general**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by tusharchandwani** [comment]
Look at the next steps (about deployment) in the same article, they should answer all your questions.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
