### ISSUE TITLE
Setup behind a corporate proxy

### ISSUE THREAD

**Issue by fergusstrachan** [MicrosoftDocs/windowsserverdocs#2704]
I'm surprised nobody has raised the difficulty of following this procedure behind a corporate proxy.

The PublishCloudPrinter, SQLite, Add-Capability components don't install from behind a proxy, and while I've managed to get the Nuget-based components installed offline I'm now at the MopriaCloudService stage, but there is no download available and dism is just a black box regarding where it goes to download EnterpriseCloudPrint and Mopria.

For the purposes of whitelisting these destinations, can you list the web addresses the server needs to contact in order to install all the relevant components in this document? Some of us can't just open everything up to the internet.

Thanks.

**Comment by dknappettmsft** [comment]
Closing due to no specific article listed in the feedback. Please open a new issue using the link at the bottom of the article for which you want to raise an issue.

#please-close
