### ISSUE TITLE
RDS Performance Counters Download

### ISSUE THREAD

**Issue by jklein68** [MicrosoftDocs/windowsserverdocs#2705]
Hi,

Are these counters only available in the Insider Preview Versions of the Operating System or are they supposed to be available as an independent download.  I would like to leverage the counters on Server 2016 VMs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65558184-a52d-7b81-c2ed-874fe85078a4
* Version Independent ID: fe830182-032f-8bd4-bd8f-3dd1afd8bb11
* Content: [Use performance counters to diagnose application responsiveness problems on Remote Desktop Session Hosts](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-rdsh-performance-counters#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-rdsh-performance-counters.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-rdsh-performance-counters.md)
* Product: **windows-server-threshold**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by iamunrootable** [comment]
I Would like to know this as well.

**Comment by bcrnkovic** [comment]
Same here

**Comment by REDzero5** [comment]
Agreed - yet another fail. "Here's this great article about doing this thing you've always wanted to do, complete with 'download' links that really just let you download an entire operating system that you'd never run in production." And of course there's also the response to someone else's comment about adding the supported operating systems to the top of the article, which they then didn't do. :(

**Comment by MDanihy** [comment]
Another useless MS article that leads to a dead-end.  Where are these magical counters?

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by dknappettmsft** [comment]
#assign:dknappettmsft

**Comment by dknappettmsft** [comment]
These counters are part of the operating system in the performance monitor tool. There is nothing to download separately. It is available in Windows Server 2019 and later only, and not available for Windows Server 2016.

#please-close
