### ISSUE TITLE
LIS 4.3 Can not work correctly

### ISSUE THREAD

**Issue by YuanHan1975** [MicrosoftDocs/windowsserverdocs#2706]
Hi,
I installed LIS 4.3 on an Azure VM(CentOS 7.6 Kernel 3.10.0-957.10.1.el7.x86_64) , VM size NC24v3，but when I ran lspci，only one GPU appeared.
How can I fixed this issue?
Thanks.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
