### ISSUE TITLE
Mistype ?

### ISSUE THREAD

**Issue by TheOtherBillGates** [MicrosoftDocs/windowsserverdocs#2707]
"... servers tp be promoted to the..." TP ? or TO ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebfd725f-1b77-751c-1948-f8f88d26a9bc
* Version Independent ID: 7d9c78d9-7736-8f0a-9636-269125a10d6f
* Content: [Upgrading to AD FS in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by NomadRex** [comment]
still not fixed?

Please search the following paragraph and fix "tp" to "to".

Before the FBL can be raised, administrators must remove the AD FS nodes of previous Windows Server versions from the farm. In the case of a WID farm, note that this requires one of the new Windows Server 2019 federation servers tp be promoted to the role of primary node in the farm.

**Comment by illfated** [comment]
Sorry for not noticing this ticket before. A Pull Request to amend that typo will be available shortly.
