### ISSUE TITLE
MSI install fails with error code 1603

### ISSUE THREAD

**Issue by JimmyTheExploder** [MicrosoftDocs/windowsserverdocs#2712]
MSI install in the System context to a Windows 10 desktop (trying to deploy via Configuration Manager Current Branch) keeps failing with error code 1603. Log file reveals this info:
Calling custom action Microsoft.ManagementExperience.Setup.CustomActions!Microsoft.ManagementExperience.Setup.CustomActions.CustomAction.GenerateSslCertificate
CustomAction GenerateSslCertificate returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox).

Installs fine manually but we'd like to install this in automated fashion on a number of devices. Any suggestions to resolve the error? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe84fb4b-3420-bc1e-6a1d-b64ecc56fc5e
* Version Independent ID: f089767e-4613-d595-a0ee-0dab012724a1
* Content: [Install Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/install#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/deploy/install.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/deploy/install.md)
* Product: **windows-server-threshold**
* Technology: **manage**
* GitHub Login: @jwwool
* Microsoft Alias: **jeffrew**

**Comment by CaptainUnlikely** [comment]
Can confirm that adding SME_PORT=6516 (this is the default) resolved this issue for me.

**Comment by daveribs** [comment]
> 
> 
> Can confirm that adding SME_PORT=6516 (this is the default) resolved this issue for me.

Signed up to say THANK YOU! I was trying to deploy WindowsAdminCenter1904.1.msi through SCCM and was getting that nasty error when using the /qn switch. This fixed it!

**Comment by CaptainUnlikely** [comment]
No worries, glad it helped you out!  I do think this should be added to the docs.
