### ISSUE TITLE
New Cluster node IP in Azure?

### ISSUE THREAD

**Issue by bsonnek** [MicrosoftDocs/windowsserverdocs#2715]
I can't wrap my head around how I create a new Cluster node object in AD and create an IP address, and then magically everything in Azure routes to a made up IP on the Azure VNet? What am I missing here? How does traffic route to an IP without an interface in the Azure network? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 706b2e1a-e90e-d70e-431f-5476b0ca52c1
* Version Independent ID: 70721d4c-642c-61f8-6c61-84b1dd1ae96c
* Content: [Deploy a two-node Storage Spaces Direct SOFS for UPD storage in Azure](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-storage-spaces-direct-deployment#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-storage-spaces-direct-deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-storage-spaces-direct-deployment.md)
* Product: **windows-server-threshold**
* Technology: **remote-desktop-services**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by stephc-msft** [comment]
For a SOFS the client connects to the node address (and potentially gets redirected to the other node if that is better).   The SOFS name eg my-sofs1  should get regeistered in dns as the addresses of both nodes

**Comment by Dizaxx** [comment]
When I am creating the cluster it does not register the IP with Azure.  Meaning any system in Azure could grab that IP.  Where as on prem I would reserve that IP in DHCP.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
