### ISSUE TITLE
Typos / sloppy writing

### ISSUE THREAD

**Issue by ThomasRapidis** [MicrosoftDocs/windowsserverdocs#2726]
@MSFT: Please carefully review this important article for critical typos. I encountered two in the very first bits:

- You mention build # 176693.292. That looks very wrong to me. You probably mean some other number...

- The indentation in a bullet list looks fishy. It is unclear what this text refers to "When upgrading a cluster with ReFS volumes, there are a few limitations:"

Please clean this up, so that we can trust these instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3133c0d-6e03-da2b-f5ea-6ee3b9f02deb
* Version Independent ID: bf03e610-891d-e993-acad-aea77d8bb9f8
* Content: [Upgrade a Storage Spaces Direct cluster to Windows Server 2019](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/upgrade-storage-spaces-direct-to-windows-server-2019)
* Content Source: [WindowsServerDocs/storage/storage-spaces/upgrade-storage-spaces-direct-to-windows-server-2019.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/upgrade-storage-spaces-direct-to-windows-server-2019.md)
* Product: **windows-server-threshold**
* Technology: **storage-spaces**
* GitHub Login: @RobHindman
* Microsoft Alias: **robhind**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by dknappettmsft** [comment]
Thanks for the feedback. These have been rectified.
