### ISSUE TITLE
Error using JEA

### ISSUE THREAD

**Issue by MaxDiOrio** [MicrosoftDocs/windowsserverdocs#2727]
I have this configured, the PSSC validates fine.  However when I attempt to start the PS Session on the remote computer, I get:

PS U:\&gt; Enter-PSSession -ComputerName ADFSServerName -ConfigurationName AccountActivityAdministration
Enter-PSSession : Processing data from remote server ADFSServerName failed with the following error message: Invalid
role capability key: RoleCapabilityFiles. Make sure the role capability name is spelled correctly and is a valid
session configuration property. For more information, see the about_Remote_Troubleshooting Help topic.
At line:1 char:1
+ Enter-PSSession -ComputerName ADFSServerName -ConfigurationName Accoun ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (ADFSServerName:String) [Enter-PSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : CreateRemoteRunspaceFailed

@{
SchemaVersion = '2.0.0.0'
GUID = 'ffb4c0b2-f161-4ddc-a769-d2419b489170'
SessionType = 'RestrictedRemoteServer'
GroupManagedServiceAccount = 'INTERNAL\msvc_ADFSMgmt'
RoleDefinitions = @{ 'INTERNAL\ADFSAccountActivity' = @{ RoleCapabilityFiles = 'C:\Program Files\WindowsPowerShell\Modules\AccountActivityJEA\RoleCapabilities\JEAAccountActivityResetRole.psrc' } }
}

@{
GUID = '752d9f89-5dc8-4720-9baf-a9ea2749ab5b'
ModulesToImport = 'ADFS'
VisibleCmdlets = 'Reset-AdfsAccountLockout', 'Get-ADFSAccountActivity', 'Set-ADFSAccountActivity'
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2f0b5c2-c56f-36d7-7457-ad7a5860f4a1
* Version Independent ID: 6f08f255-1abc-cf70-da2c-64b3e49fef06
* Content: [Delegate AD FS Powershell Commandlet Access to Non-Admin Users](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/delegate-ad-fs-pshell-access#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/delegate-ad-fs-pshell-access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/delegate-ad-fs-pshell-access.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by MaxDiOrio** [comment]
So the instructions are essentially completely wrong.  I finally figured it out going through all the documentation on JEA.

Here's what I had to do to get it to work:

Create the folder and empty files needed to create a PowerShell Module 
$modulePath = Join-Path $env:ProgramFiles "WindowsPowerShell\Modules\ADFSActivity"

New-Item -ItemType Directory -Path $modulePath

New-Item -ItemType File -Path (Join-Path $modulePath "ADFSActivityFunctions.psm1")

​New-ModuleManifest -Path (Join-Path $modulePath "ADFSActivity.psd1") -RootModule "ADFSActivityFunctions.psm1"

$rcFolder = Join-Path $modulePath "RoleCapabilities"

New-Item -ItemType Directory $rcFolder
​
Create the PowerShell Roll Configuration File and place it into the $rcFolder path above

@{
GUID = '752d9f89-5dc8-4720-9baf-a9ea2749ab5b'
ModulesToImport = 'ADFS'
VisibleCmdlets = 'Reset-AdfsAccountLockout', 'Get-ADFSAccountActivity', 'Set-ADFSAccountActivity'
}​


Create the PowerShell Session File

@{
SchemaVersion = '2.0.0.0'
GUID = 'ffb4c0b2-f161-4ddc-a769-d2419b489170'
SessionType = 'RestrictedRemoteServer'
ModulesToImport = 'ADFSAtivity'
GroupManagedServiceAccount = 'INTERNAL\msvc_ADFSMgmt'
RoleDefinitions = @{ 'INTERNAL\ADFSAccountActivity' = @{ RoleCapabilities = 'ADFSActivity' } }
}


Register-PSSessionConfiguration -Name 'ADFSActivity' -Path .\ADFSActivity.pssc -Force


​​Enter-PSSession -ComputerName ADFSServer -ConfigurationName ADFSActivity

**Comment by susan1993** [comment]
@MaxDiOrio hello, how are you? I've been struggling with this JEA thing, I followed your steps and still not working I get the below error message, I'm realy losing the hope, maybe you have a clue of what could be wrong 


PS C:\Users\Administrator> Enter-pssession -ComputerName ADFS.suvargas.com -ConfigurationName "AccountActivityAdministration" -Credential Administrator
Enter-pssession : Processing data from remote server ADFS.suvargas.com failed with the following error message: Invalid role 
capability key: RoleCapabilityFiles. Make sure the role capability name is spelled correctly and is a valid session configuration 
property. For more information, see the about_Remote_Troubleshooting Help topic.
At line:1 char:1
+ Enter-pssession -ComputerName ADFS.suvargas.com -ConfigurationName "A ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (ADFS.suvargas.com:String) [Enter-PSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : CreateRemoteRunspaceFailed

**Comment by c0ryb4k3r** [comment]
> @MaxDiOrio hello, how are you? I've been struggling with this JEA thing, I followed your steps and still not working I get the below error message, I'm realy losing the hope, maybe you have a clue of what could be wrong
> 
> PS C:\Users\Administrator> Enter-pssession -ComputerName ADFS.suvargas.com -ConfigurationName "AccountActivityAdministration" -Credential Administrator
> Enter-pssession : Processing data from remote server ADFS.suvargas.com failed with the following error message: Invalid role
> capability key: RoleCapabilityFiles. Make sure the role capability name is spelled correctly and is a valid session configuration
> property. For more information, see the about_Remote_Troubleshooting Help topic.
> At line:1 char:1
> 
> * Enter-pssession -ComputerName ADFS.suvargas.com -ConfigurationName "A ...
> * ```
>     + CategoryInfo          : InvalidArgument: (ADFS.suvargas.com:String) [Enter-PSSession], PSRemotingTransportException
>     + FullyQualifiedErrorId : CreateRemoteRunspaceFailed
>   ```

You have to use the filename you saved the role capabilities as the parameter in the session configuration.  You can script the creation of those files I find it a little easier to understand:

$roleParameters = @{
	Path = "$rcFolder\\**JEARole_ADFSAccountActivity**.psrc"
	ModulesToImport = "adfs"
	VisibleCmdlets = 'Reset-AdfsAccountLockout', 'Get-ADFSAccountActivity', 'Set-ADFSAccountActivity'
}
New-PSRoleCapabilityFile @roleParameters

$configSettings = @{
    Path = "$modulePath\SessionConfigurations\JEASession_ADFSAccountActivity.pssc"
    SchemaVersion = '2.0.0.0'
	GUID = 'ffb4c0b2-f161-4ddc-a769-d2419b489170'
    SessionType = 'RestrictedRemoteServer'
	ModulesToImport = 'ADFSAtivity'
    GroupManagedServiceAccount =  '_AD\gMSA_YourServiceAccountHere_'
	RoleDefinitions = @{ '_AD\YourDelegatedGroupHere_' = @{ RoleCapabilities = '**JEARole_ADFSAccountActivity**' } }
}
New-PSSessionConfigurationFile @configSettings

Register-PSSessionConfiguration -Name 'ADFSActivity' -Path $configSettings.Path -Force

Thank you @MaxDiOrio your posts def. saved me a ton of research.

**Comment by divadiow** [comment]
though if you have "Disallow WinRM from storing RunAs credentials" enabled in group policy (present in the baseline), you're greeted with the below error. 

Register-PSSessionConfiguration : The supplied plugin configuration XML is not valid. To enable WinRM to store RunAs
credentials, change the "Disallow WinRM from storing RunAs credentials" Group Policy setting to Disabled.
At line:217 char:5
+     Register-PSSessionConfiguration -filepath $args[0] -pluginName $a ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Register-PSSessionConfiguration

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
