### ISSUE TITLE
Example 2 doesn't work with the AD FS 2019 paginated signon experience

### ISSUE THREAD

**Issue by f0rtezza** [MicrosoftDocs/windowsserverdocs#2737]
The code in example 2 to add the domain name at submission doesn't work in the new paginated signon interface in AD FS 2019. In order to get this functionality I modified the code as follows:

```
var contosoDomain = "ad.contoso.com";

if (typeof LoginManager != 'undefined'){  
    LoginManager.submitLoginRequest = function () {   
    var u = new InputUtil();  
    var e = new LoginErrors();  
    var userName = document.getElementById(Login.userNameInput);  
    var password = document.getElementById(Login.passwordInput);  
    if (userName.value && !userName.value.match('[@\\\\]'))   
    {  
        var userNameValue = contosoDomain + '\\' + userName.value;  
        document.forms['loginForm'].UserName.value = userNameValue;  
    }  

    if (!userName.value) {  
       u.setError(userName, e.userNameFormatError);  
       return false;  
    }  

    if (!password.value)   
    {  
        u.setError(password, e.passwordEmpty);  
        return false;  
    }  
    document.forms['loginForm'].submit();  
    return false;  
};  
}

if (typeof PaginationManager != 'undefined') {
    PaginationManager.validateAndNext = function () {
        var u = new InputUtil();
        var e = new LoginErrors();

        var userName = document.getElementById(Login.userNameInput);

        if (!userName.value) {
            u.setError(userName, e.userNameFormatError);
            return false;
        }

        if(!userName.value.match('[@\\\\]')) {
            var userNameValue = contosoDomain + '\\' + userName.value;  
            document.forms['loginForm'].UserName.value = userNameValue;
        }

        _self.updatePagesWithUsername(userName.value);
        u.clearError();

        if (_self.options.currentPageIndex + 1 >= _self.options.pages.length) {
            // POST back to ADFS since there are no more pages to go to 
            document.forms['loginFormPaginated'].submit();
            return true;
        } else {
            _self.displayNextPage();
        }

        return true;
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b075df1f-27d4-4589-9869-04d36f267bfd
* Version Independent ID: 6dd81fb2-4152-129d-be0c-5532f2f1b140
* Content: [Advanced Customization of AD FS Sign-in Pages](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/advanced-customization-of-ad-fs-sign-in-pages#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Advanced-Customization-of-AD-FS-Sign-in-Pages.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Advanced-Customization-of-AD-FS-Sign-in-Pages.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by philli77** [comment]
Thank you works like a charm now!!

**Comment by mandersonCC** [comment]
Thank you so much for this. I fought with this a couple weeks ago, but didn't have the knowledge to fix it!

**Comment by joeyaben** [comment]
I'm getting a script error with ADFS 2019 while using this script.

`if (_self.options.currentPageIndex + 1 &gt;= _self.options.pages.length) {
            // POST back to ADFS since there are no more pages to go to 
            document.forms['loginFormPaginated'].submit();
            return true;
        } else {
            _self.displayNextPage();
        }`

The webbrowser is complaining about the `;` within `&gt;=` syntax.

Can I replace this with some other syntax?

**Comment by MrMadpro** [comment]
Cheers, really helpful

**Comment by brightjdb** [comment]
I'm wondering if this code has been updated.  It doesn't seem to work with the onload.js I have for my paginated forms or I'm not putting it in the correct place.  I was thinking I should put it here in this section...


function PaginatedNext()
{
  // Check that a username was entered correctly 
    var u = new InputUtil();
    var e = new LoginErrors();
    var usernameInput = document.getElementById('userNameInput');
    if (!usernameInput.value || !usernameInput.value.match('[@\\\\]')) {
        u.setError(usernameInput, e.userNameFormatError);
        return false;
    }
    
    ShowPasswordPage();
}

**Comment by ericbrown613** [comment]
There were some errors in the original code for this post.  Below is the working code which is running in a production environment:

var contosoDomain = "@ad.contoso.com";

if (typeof LoginManager != 'undefined'){  
    LoginManager.submitLoginRequest = function () {   
    var u = new InputUtil();  
    var e = new LoginErrors();  
    var userName = document.getElementById(Login.userNameInput);  
    var password = document.getElementById(Login.passwordInput);  
    if (userName.value && !userName.value.match('[@\\\\]'))   
    {  
        var userNameValue =  userName.value + contosoDomain;  
        document.forms['loginForm'].UserName.value = userNameValue;  
    }  

    if (!userName.value) {  
       u.setError(userName, e.userNameFormatError);  
       return false;  
    }  

    if (!password.value)   
    {  
        u.setError(password, e.passwordEmpty);  
        return false;  
    }  
    document.forms['loginForm'].submit();  
    return false;  
};  
}

if (typeof PaginationManager != 'undefined') {
    PaginationManager.validateAndNext = function () {
        var u = new InputUtil();
        var e = new LoginErrors();

        var userName = document.getElementById(Login.userNameInput);

        if (!userName.value) {
            u.setError(userName, e.userNameFormatError);
            return false;
        }

        if(!userName.value.match('[@\\\\]')) {
            var userNameValue =  userName.value + contosoDomain;  
            document.forms['loginFormPaginated'].UserName.value = userNameValue;
        }

        _self.updatePagesWithUsername(userName.value);
        u.clearError();

        if (_self.options.currentPageIndex + 1 >= _self.options.pages.length) {
            // POST back to ADFS since there are no more pages to go to 
            document.forms['loginFormPaginated'].submit();
            return true;
        } else {
            _self.displayNextPage();
        }

        return true;
    }
}

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by keschnei42** [comment]
The above examples such as @ericbrown613 had did not work for me.  I'm thinking it has something to do with the new version of paginatedonboard.js that was made to fix a vulnerability [https://github.com/microsoft/adfsWebCustomization/issues/34](url).

I admit I don't have much javascript knowledge and I have been adding the additional functionality at the end of the js file, replacing nothing already present.  It made no difference if I minified the contents.
