### ISSUE TITLE
SHA2

### ISSUE THREAD

**Issue by Rvolvr** [MicrosoftDocs/windowsserverdocs#2749]
Under the following bullets, SHA2 is not a valid hash. The closest options are MD2, SHA1, or SHA256. 

Minimum server certificate requirements
 - Configure the server certificate with the required cryptography setting:
  3. Click the Cryptography tab and make sure to configure the following:
   + Hash Algorithm: SHA2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4de79f23-cacb-9d4c-c3cb-266346d043ac
* Version Independent ID: e858df36-4e46-d232-fb88-e011329cf989
* Content: [Configure Certificate Templates for PEAP and EAP Requirements](https://docs.microsoft.com/en-us/windows-server/networking/technologies/nps/nps-manage-cert-requirements#feedback)
* Content Source: [WindowsServerDocs/networking/technologies/nps/nps-manage-cert-requirements.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/nps/nps-manage-cert-requirements.md)
* Product: **windows-server-threshold**
* Technology: **networking**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by gitthubuser** [comment]
Theoretically, SHA2 is a family of hashing algorithm that includes SHA256, SHA384, SHA512.

In practical implementation, yes, it should be specified as 1 of the above hashing algorithm,
