### ISSUE TITLE
Changing the value PromptLoginBehavior can cause authentication issues.

### ISSUE THREAD

**Issue by mhunter77** [MicrosoftDocs/windowsserverdocs#2753]
NOTE - Changing the value of PromptLoginBehavior can impact authentication and cause problems.  See the following two article for examples of authentication issues relating to  PromptLoginBehavior 

Troubleshooting Azure AD Certificate-Based Authentication issues
https://support.microsoft.com/en-ph/help/4032987/troubleshooting-azure-ad-certificate-based-authentication-issues

4. Run the following commands to make sure that the ADFS settings are not set to PromptLoginBehavior : true. Otherwise, users will be prompted to enter their user name and password for some modern apps. 
PS C:\&gt; Connect-msolService
PS C:\&gt; Get-MSOLDomainFederationSettings -DomainName contoso.com

Note This occurs because some modern apps send "prompt=login" to Azure AD in their request. Azure AD translates this in the ADFS request to"wauth=usernamepassworduri" (this tells ADFS to do username/password authentication) and "wfresh=0" (tells ADFS to ignore the SSO state and do a fresh authentication). If users have to use Certificate Based Authentication, the PromptLoginBehavior must be set to False.

Federated users in Azure Active Directory may have to sign in two times before being prompted for MFA
https://support.microsoft.com/en-us/help/4037806/federated-users-in-azure-active-directory-may-have-to-sign-in-two-time
In this article, the issue was fixed by setting the value of  PromptLoginBehavior to Native.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fd38f15-29d2-383a-f529-c9e90e8877ba
* Version Independent ID: 44d9311f-16cd-c0ef-7624-9bd4b321a3b8
* Content: [AD FS prompt=login](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/ad-fs-prompt-login#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/AD-FS-Prompt-Login.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/AD-FS-Prompt-Login.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
