### ISSUE TITLE
Does COPY support UNC and mapped drive copying?

### ISSUE THREAD

**Issue by caspe15** [MicrosoftDocs/windowsserverdocs#2761]
If would be helpful if this page (COPY) indicated what level of support COPY has for copying to/from mapped and/or UNC locations.  If supported, examples should be shown.  If supported, details about how to handle authentication would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1673c6a2-c9e5-198c-a929-4d4641ea133f
* Version Independent ID: ad63774f-21ba-04c0-d1c5-1932246e8427
* Content: [copy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/copy#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/copy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/copy.md)
* Product: **windows-server-threshold**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
