### ISSUE TITLE
Teaming in 2016 Essentials?

### ISSUE THREAD

**Issue by DrDave242** [MicrosoftDocs/windowsserverdocs#2762]
Is NIC teaming supported in Windows Server 2016 Essentials? This page states "NIC Teaming is available in all versions of Windows Server 2016," but there is a widespread belief that the Essentials version doesn't support it. I can't find a clear statement from Microsoft on this anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa790b8c-1e37-0608-b93e-ef0a0eb5d930
* Version Independent ID: c8d1a328-5da5-2534-e684-ef7a4bc275e0
* Content: [NIC Teaming](https://docs.microsoft.com/en-us/windows-server/networking/technologies/nic-teaming/nic-teaming)
* Content Source: [WindowsServerDocs/networking/technologies/nic-teaming/NIC-Teaming.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/nic-teaming/NIC-Teaming.md)
* Product: **windows-server-threshold**
* Technology: **networking-nict**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
