### ISSUE TITLE
Custom Cryptography Settings Ignored

### ISSUE THREAD

**Issue by DanNHS** [MicrosoftDocs/windowsserverdocs#2765]
When defining the CryptographySuite element in the ProfileXML it only recognises the input if the NativeProtocolType is set to IKEv2. If the NativeProtocolType is set to automatic then the CryptographySuite config is ignored.
This means you can only use the default IKEv2 settings (that are not very secure) on the VPN server(s) if you want to configure a VPN that will fail over to SSTP in the event IKEv2 does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7453068-95eb-2a42-fd0b-553ae593adb0
* Version Independent ID: b39b2cb7-25b1-2af3-4954-dbcc04c836e9
* Content: [Configure Windows 10 Client Always On VPN Connections](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md)
* Product: **windows-server-threshold**
* Technology: **networking-ras**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by rlodev67** [comment]
Hey
Any news/fix about it ?

**Comment by rlodev67** [comment]
Up ?
