### ISSUE TITLE
Issues with third command

### ISSUE THREAD

**Issue by FISHMANPET** [MicrosoftDocs/windowsserverdocs#2770]
A few issues with this that I had to spend a while figuring out, that it might be nice to have explained here
--% is a special powershell character that tells powershell to stop parsing any farther variables on the line.  Presumably that prevents $ConfirmPreference being the value currently in your shell rather than running that command on the remote system.
As such, that command will only work in powershell, if you run it in the command shell it will fail.

Either way, that command only works if you haven't set the shell on the remote system to be Powershell.  It's not made explicit in "Configuring Windows for OpenSSH" but instructions are given, and I'm sure many admins will have already set their shell to powershell.  When the remote shell is already powershell, $ConfirmPreference is interpolated on the remote system, so you get an error message like "High : The term 'High' is not recognized as the name of a cmdlet, function, script file, or operable program."

This could be worked around by giving a command line like this:
`ssh  user1@domain1@contoso.com powershell -c Repair-AuthorizedKeyPermission C:\Users\user1\.ssh\authorized_keys -Confirm:0`

This worked for me from both cmd and powershell locally, with either cmd or powershell as the shell on the remote system

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 337c4ea8-1806-92a3-1501-b3ff5dde37bb
* Version Independent ID: c411d389-578d-57c6-cd6e-eaca7f2837db
* Content: [OpenSSH Server Configuration for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement#feedback)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* GitHub Login: @maertendMSFT

**Comment by canuzun** [comment]
Thanks for clarifying this. I was struggling the High is not recognized issue, and it is solved, so I have moved to the next struggling issue ;)

I think there is a typo in your suggestion;
ssh user1@domain1@contoso.com powershell -c Repair-AuthorizedKeyPermission C:\Users\user1.ssh\authorized_keys -Confirm:0

user1.ssh should be user1\ssh

ssh user1@domain1@contoso.com powershell -c Repair-AuthorizedKeyPermission C:\Users\user1\ssh\authorized_keys -Confirm:0

**Comment by FISHMANPET** [comment]
I had the path correct but the formatter was eating some slashes, I've edited it but the directory is `.ssh` not `ssh`.

**Comment by canuzun** [comment]
`user\.ssh` is correct, can't believe made a typo while suggesting a fix for yours :). 
For anyone here with issues for the confusing documentation, this answer helped me to pinpoint my problem. It may help you too.
https://stackoverflow.com/a/50502015/4768830

**Comment by maxisam** [comment]
I got The term 'Repair-AuthorizedKeyPermission' is not recognized as the name of a cmdlet,

**Comment by illfated** [comment]
Would any of you like to suggest changes to the referenced page, and if yes, what would that change look like?
(https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
