### ISSUE TITLE
Missing name for the registry value

### ISSUE THREAD

**Issue by JohniBlack** [MicrosoftDocs/windowsserverdocs#2774]
On chapter "Configure the TLS Handle Expiry Time on NPS" between step 5 and 6 is something missing?
How should we call the new registry value?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7a6ed8a-3ca9-0473-0d87-ea0b5ef49c4c
* Version Independent ID: 83a515a2-1ac2-717a-a414-4709dce9961c
* Content: [Manage Certificates Used with NPS](https://docs.microsoft.com/en-us/windows-server/networking/technologies/nps/nps-manage-certificates#feedback)
* Content Source: [WindowsServerDocs/networking/technologies/nps/nps-manage-certificates.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/nps/nps-manage-certificates.md)
* Product: **windows-server-threshold**
* Technology: **networking**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
