### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by lee-harrison** [MicrosoftDocs/windowsserverdocs#2776]
Just wanted to say thanks for these script examples - very useful!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e56fc8a-59e1-84e4-d618-688fc6502cf1
* Version Independent ID: 0edf6356-1e87-9117-09ec-6cb62a5549d2
* Content: [Scripting with Storage Spaces Direct performance history](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/performance-history-scripting#feedback)
* Content Source: [WindowsServerDocs/storage/storage-spaces/performance-history-scripting.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/performance-history-scripting.md)
* Technology: **storage-spaces**
* GitHub Login: @cosmosdarwin
* Microsoft Alias: **cosdar**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
