### ISSUE TITLE
Typos on syntax

### ISSUE THREAD

**Issue by win2000b** [MicrosoftDocs/windowsserverdocs#2777]
New-Cluster -Name SRAZC1 -Node az2az1,az2az2 – StaticAddress 10.3.0.100

Should read 

New-Cluster -Name SRAZC1 -Node az2az1,az2az2 –StaticAddress 10.3.0.100

Same for the other new-cluster command

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7427fc8-7930-7ff0-dbd1-8805731002ae
* Version Independent ID: e36fb931-b5fd-8d41-75eb-aacf447fb358
* Content: [Cluster to Cluster Storage Replica cross region in Azure](https://docs.microsoft.com/en-us/windows-server/storage/storage-replica/cluster-to-cluster-azure-cross-region#feedback)
* Content Source: [WindowsServerDocs/storage/storage-replica/cluster-to-cluster-azure-cross-region.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-replica/cluster-to-cluster-azure-cross-region.md)
* Product: **windows-server-threshold**
* Technology: **storage-replica**
* GitHub Login: @arduppal
* Microsoft Alias: **arduppal**

**Comment by arduppal** [comment]
Thank you. Will update the doc
