### ISSUE TITLE
Missing Switches

### ISSUE THREAD

**Issue by ericohlin** [MicrosoftDocs/windowsserverdocs#2778]
There are a lot of missing switches here.

Instead of listing the missing items, I'm going to just post to the full set. /Transport is what I am referencing specifically. If you compare you can see the missing items.

[/Transport]
        Configures settings used by transport server (when you install
        only the Transport Server role service).

  [/ObtainIpv4From:{Dhcp | Range}]
        Specifies the source of IPv4 addresses.

    [/Start:&lt;Start IPv4 Address&gt;]
        Specifies the start of the IP address range. This is required
        if /ObtainIpv4 is set to Range.

    [/End:&lt;End IPv4 Address&gt;]
        Specifies the end of the IP address range. This is required if
        /ObtainIpv4From is set to Range.

  [/ObtainIpv6From:Range]
        Specifies the source of IPv6 addresses. The only supported
        value is Range.

    [/Start:&lt;Start IPv6 Address&gt;]
        Specifies the start of the IP address range. This is required
        when /ObtainIpv6From is set to Range.

    [/End:&lt;End IPv6 Address&gt;]
        Specifies the end of the IP address range. This is required
        when /ObtainIpv6From is set to Range.

  [/PortPolicy:{Dynamic | Fixed}]
        Specifies the UDP port policy to use.  Set this to Dynamic for
        obtaining ports dynamically from Winsock.  Set this to Fixed
        for using ports from a fixed range.

  [/StartPort:&lt;Start Port&gt;]
        Specifies the start of the port range.

    [/EndPort:&lt;End Port&gt;]
        Specifies the end of the port range.  This is required when
        /PortPolicy is set to Fixed.

  [/Profile:{10Mbps | 100Mbps | 1Gbps | Custom}]
        Specifies the network profile to use.  Note: This option is
        only available for servers running Windows Server 2008 or
        Windows Server 2003.

  [/MulticastSessionPolicy]
        Configures transfer settings for multicast transmissions.

    [/Policy:{None | AutoDisconnect | Multistream}]
        Determines how to handle slow clients.  None means to keep all
        clients in one session at the same speed.  AutoDisconnect
        means that any clients that drop below the specified
        /Threshold will be disconnected.  Multistream means clients
        will be separated into multiple sessions as specified by
        /StreamCount.

    [/Threshold:&lt;Threshold in KBps&gt;]
        For /Policy:AutoDisconnect, this option sets the minimum
        transfer rate in KBps.Clients that drop below this rate will
        be disconnected from multicast transmissions.

    [/StreamCount:{2 | 3}]
        For /Policy:Multistream, this option determines the number of
        sessions.  2 means two sessions (fast and slow) 3 means three
        sessions (slow, medium, fast).

    [/Fallback:{Yes | No}]
        Determines whether clients that are disconnected will continue
        the transfer using another method (if supported by the
        client). If you are using the WDS client, the computer will
        fallback to unicasting.  Wdsmcast.exe does not support a
        fallback mechanism. This option also applies to clients that
        do not support Multistream. In that case, the computer will
        fall back to another method instead of moving to a slower
        transfer session.

  [/TftpMaximumBlockSize:&lt;Block size&gt;]
        Specifies the maximum block size that the TFTP server can use.

  [/EnableTftpVariableWindowExtension:{Yes | No}]
        Specifies if the TFTP variable window extension is enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03b393e6-b22c-d6ed-eda8-d2dc50e62680
* Version Independent ID: 77e487c6-711c-f1eb-7560-6e7b9f26c677
* Content: [Subcommand set-Server](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/subcommand-set-server#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/subcommand-set-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/subcommand-set-server.md)
* Product: **windows-server-threshold**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
