### ISSUE TITLE
You must *EXPLICITLY* enable TLS 1.2 on Windows Server 2016

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/windowsserverdocs#2783]
According to...
https://docs.microsoft.com/en-us/windows/desktop/SecAuthN/protocols-in-tls-ssl--schannel-ssp-

TLS 1.2 client and server are enabled by default.

But...

https://social.technet.microsoft.com/Forums/en-US/cb1a695b-a15c-4fa7-94f0-1aaa20c1279d/enabling-tls-12-on-windows-server-2012-amp-2016?forum=winserversecurity

...says

      Turns out it is, but not enabled for SCHANNEL service

Hence you *MUST* follow...

https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/manage-ssl-protocols-in-ad-fs#enable-and-disable-tls-12

Please articulate this!  Say...

You can enable and disable SSL 2.0 and 3.0 and TLS versions 1.0, 1.1, and 1.2 using Manage SSL Protocols in AD FS.  On Windows Server 2016, to use TLS 1.2, you must explicity enable it by following instructions at [https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/manage-ssl-protocols-in-ad-fs#enable-and-disable-tls-12]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8396683-4498-71bd-60a1-345277e1433e
* Version Independent ID: 36ed02b0-555a-4714-32f8-f4e0434adf51
* Content: [AD FS 2016 FAQ](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-faq)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/AD-FS-FAQ.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/AD-FS-FAQ.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
