### ISSUE TITLE
The link to capacity planning sheet for 2012R2 opens the capacity planning sheet for 2008R2

### ISSUE THREAD

**Issue by ivratche** [MicrosoftDocs/windowsserverdocs#2784]
Fix the link under section https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/design/planning-for-federation-server-capacity#how-to-use-this-spreadsheet 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 474d04f7-801c-578a-783d-f6ee9b7147b0
* Version Independent ID: 7f7bad26-cc81-b82a-7cbc-993a65d247d2
* Content: [Planning for Federation Server Capacity](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/design/planning-for-federation-server-capacity#bk_estimatefs)
* Content Source: [WindowsServerDocs/identity/ad-fs/design/Planning-for-Federation-Server-Capacity.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/design/Planning-for-Federation-Server-Capacity.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 2783 -b #assign:IngridAtMicrosoft
