### ISSUE TITLE
ESL is not prevented lock all accounts from spray password attack

### ISSUE THREAD

**Issue by tungduydo1989** [MicrosoftDocs/windowsserverdocs#2786]
ESL is good, but it does not prevent the lock of all accounts of the company

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8634165-2ff5-9b01-e3fc-17827360a5f3
* Version Independent ID: a5a91921-3193-93ad-df22-d486e65b19f8
* Content: [Configure AD FS Extranet Lockout Protection](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-extranet-smart-lockout-protection#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by jordanmills** [comment]
Yep.  Disable the usernamemixed endpoints on the ADFS web application proxies to stop that.  At least for now.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
