### ISSUE TITLE
Document install parameters

### ISSUE THREAD

**Issue by dsolodow** [MicrosoftDocs/windowsserverdocs#2795]
Having these documented is important for command line installs (used either for silent or Server Core)
The page currently describes:
SME_PORT=&lt;port&gt; (what port does HTTPS listen on)
SSL_CERTIFICATE_OPTION=generate/installed (generate = self-signed; installed = existing, requires SME_THUMBPRINT)
SME_THUMBPRINT=&lt;thumbprint&gt; (required for existing certificate)
RESTART_WINRM=0 (don't auto-restart WinRM service)

Not listed, but supported in 1904 is:
CHK_REDIRECT_PORT_80=0/1 (redirect  port 80)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe84fb4b-3420-bc1e-6a1d-b64ecc56fc5e
* Version Independent ID: f089767e-4613-d595-a0ee-0dab012724a1
* Content: [Install Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/install)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/deploy/install.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/deploy/install.md)
* Product: **windows-server-threshold**
* Technology: **manage**
* GitHub Login: @jwwool
* Microsoft Alias: **jeffrew**

**Comment by MCrank** [comment]
Thank you for this @dsolodow. Was looking for the Command Line option to set the redirect

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
