### ISSUE TITLE
wrong example numbers

### ISSUE THREAD

**Issue by stappel** [MicrosoftDocs/windowsserverdocs#2797]
in the picture below "example that maximizes fault tolerance" the last numbers are wrong, it says {2,5,6} but should say: {3,5,6}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34a7599-b46d-c14a-6038-18b889777bf0
* Version Independent ID: 00a62a44-2911-2644-5670-d47af39844b8
* Content: [Delimit the allocation of volumes in Storage Spaces Direct](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/delimit-volume-allocation#feedback)
* Content Source: [WindowsServerDocs/storage/storage-spaces/delimit-volume-allocation.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/delimit-volume-allocation.md)
* Technology: **storage-spaces**
* GitHub Login: @cosmosdarwin
* Microsoft Alias: **cosmosdarwin**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
