### ISSUE TITLE
Copying files with Microsoft Remote Desktop Beta for Android

### ISSUE THREAD

**Issue by animadversor** [MicrosoftDocs/windowsserverdocs#2799]
Microsoft Remote Desktop Beta v. 8.1.70.381
Support ID
613899f7-8f72-4dcd-bee2-3eca834fa815

There is surely a way to copy files from one device to another using this app, but for the life of me I cannot figure out how. Might someone be able to help, please? Thank you very much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45d9f311-2994-948d-ad91-f5c7370d73ec
* Version Independent ID: 5f978676-6f53-3f2d-fabb-3554027edbcc
* Content: [Get started with Remote Desktop on Android](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-android#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-android.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-android.md)
* Product: **windows-server-threshold**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
