### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by root9b-zz** [MicrosoftDocs/windowsserverdocs#2802]
"These steps can't be automated or done within a Windows PowerShell session for online virtual machines. You can apply them to offline VHDX images; see this blog post." link is dead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1c56e1b-ebdd-eefc-6a61-91ab0f09ad8a
* Version Independent ID: 359ead50-4b39-55cf-691f-f667c7a1389a
* Content: [Manage Hyper-V Integration Services](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/manage-hyper-v-integration-services#feedback)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/Manage-Hyper-V-integration-services.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/Manage-Hyper-V-integration-services.md)
* Service: **na**
* Product: **windows-server-threshold**
* Technology: **compute-hyper-v**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by codaamok** [comment]
Here you go: https://docs.microsoft.com/en-us/virtualization/community/team-blog/2013/20130418-how-to-install-integration-services-when-the-virtual-machine-is-not-running

**Comment by illfated** [comment]
The current link is https://blogs.technet.microsoft.com/virtualization/2013/04/18/how-to-install-integration-services-when-the-virtual-machine-is-not-running/
and without the `/en-us/` part, it seems to resolve to this page: https://techcommunity.microsoft.com/t5/Virtualization/bg-p/Virtualization (not sure if this is intended).

https://docs.microsoft.com/en-us/virtualization/community/team-blog/2013/20130418-how-to-install-integration-services-when-the-virtual-machine-is-not-running looks much more relevant, so maybe the link needs to be amended specifically to include `/en-us/` ?

**Comment by illfated** [comment]
#please-close
