### ISSUE TITLE
Root CA renewal

### ISSUE THREAD

**Issue by anthonynz** [MicrosoftDocs/windowsserverdocs#2804]
Hi folks, 
These instructions advise us to hardcode a certificate thumbprint into the profile (see step 8).
Can you please advise the recommended steps when the root CA cert renews?

All the remote devices loose access if this happens automatically.

Clearly this is a problem as once a remote device looses connectivity they cannot get a fix pushed out to them without returning to base.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7453068-95eb-2a42-fd0b-553ae593adb0
* Version Independent ID: b39b2cb7-25b1-2af3-4954-dbcc04c836e9
* Content: [Configure Windows 10 Client Always On VPN Connections](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections#feedback)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md)
* Product: **windows-server-threshold**
* Technology: **networking-ras**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
