### ISSUE TITLE
Statement "If you lose two nodes in a hyper-converged cluster, the entire cluster will go down." in Summary

### ISSUE THREAD

**Issue by AlexcFrench** [MicrosoftDocs/windowsserverdocs#2805]
Hi, we believe this statement to be wrong given that we have a 4-node cluster and we can shut down 3 nodes, and the cluster running node still works. 
Not a situation we want to be in, but it works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c41c516-7f82-2ab7-f099-1c9851913421
* Version Independent ID: 4b23f0d3-cd1e-829c-986b-ef1ada558b5d
* Content: [Disaster Recovery Scenarios for Hyper-Converged Infrastructure](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/storage-spaces-direct-disaster-recovery#feedback)
* Content Source: [WindowsServerDocs/storage/storage-spaces/Storage-Spaces-Direct-Disaster-Recovery.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/Storage-Spaces-Direct-Disaster-Recovery.md)
* Product: **windows-server-threshold**
* Technology: **storage-spaces**
* GitHub Login: @JohnMarlin-MSFT

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
