### ISSUE TITLE
Maybe-wrong Powershell command to query SSH Firewall rule after installation

### ISSUE THREAD

**Issue by imuzzolini** [MicrosoftDocs/windowsserverdocs#2806]
After installing OpenSSH server on my system, the following PS command provided no result:
```
Get-NetFirewallRule -Name *ssh*
```

Instead, by using the following, it returned the added SSH Firewall rule:
```
Get-NetFirewallRule -DisplayName *ssh*
```

I'm using the following Windows 10 Professional.
```
BuildNumber     : 16299
Version         : 10.0.16299
```

And the following Powershell version:
```
PSVersion                      5.1.16299.248
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.248
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
