### ISSUE TITLE
Bugs in Windows Server 2019

### ISSUE THREAD

**Issue by christophvw** [MicrosoftDocs/windowsserverdocs#2807]
LDAP queries with memberOf failing
https://social.technet.microsoft.com/Forums/windowsserver/en-US/4f14412f-dd81-4b9a-b6b5-aa69100e87d0/intermittent-not-enough-space-errors-when-doing-ldap-queries-against-2019-domain-controller?forum=winservergen

NPS Firewall rules are not working
https://social.technet.microsoft.com/Forums/en-US/cf047df5-ed4a-46b9-9564-c9db5a9bc8dc/windows-server-2019-default-nps-firewall-rules-port-1812-udp-not-working?forum=ws2019

BSOD when trying to hot add a CPU in VMware
https://kb.vmware.com/s/article/60223

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63cba9af-2e36-3027-3e36-98dc7167495d
* Version Independent ID: aa46a499-9b14-802c-5495-cedfdac8546d
* Content: [Release Notes - Important issues in Windows Server 2019](https://docs.microsoft.com/en-US/windows-server/get-started-19/rel-notes-19#feedback)
* Content Source: [WindowsServerDocs/get-started-19/rel-notes-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/rel-notes-19.md)
* Product: **windows-server-threshold**
* Technology: **server-general**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by chrios** [comment]
Another bug: Renaming a domain controller with 

netdom computername <name> /add:<newname>
netdom computername <name> /makeprimary:<newname>
restart-computer
netdom computername <newname> /remove:<name>

Will leave behind orphaned data in servicePrincipleName, msDS-AdditionalDnsHostNames and msDS-AdditionalSamAccountName attributes, causing SPNs on the domain controllers to be registered under both the new name and the old name. Ask me how I found this one out. The only acknowledgement I have seen is here:

https://blogs.windows.com/windowsexperience/2019/06/18/announcing-windows-server-vnext-preview-build-18917/#CZK7cKQ51YMrXQVT.97

**Comment by xicanoink** [comment]
Server 2019 Standard or Essentials.
Fresh install and promote to Domain Controller.
Install FSRM.
Use the default Passive screen for "System Files and Executables" and apply it to the C: drive which contains the SYSVOL share.
GPO management does not allow editing GPOs or creating new GPOs.
Error:  "The specified server cannot perform the requested operation"
You have to delete the passive screen and reboot or completely remove FSRM and reboot to get GPO Management working right again.
Bug.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
