### ISSUE TITLE
LIcencing infomation would be grate

### ISSUE THREAD

**Issue by LTUTE** [MicrosoftDocs/windowsserverdocs#2830]
It would be grate to find licensing information about this product as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46cb3de2-7e81-4872-5964-d35e5b3b55d2
* Version Independent ID: 47f38ed1-069f-e056-afe5-0cfdecf5d541
* Content: [Hyper-V on Windows Server](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/hyper-v-on-windows-server#feedback)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Hyper-V-on-Windows-Server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/Hyper-V-on-Windows-Server.md)
* Service: **na**
* Product: **windows-server-threshold**
* Technology: **compute-hyper-v**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
