### ISSUE TITLE
Exit codes for wevtutil.exe

### ISSUE THREAD

**Issue by SwiftOnSecurity** [MicrosoftDocs/windowsserverdocs#2837]
Hello, can exit codes for wevtutil be added to this page? I'm troubleshooting an issue an unable to determine what 13 means.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ca36bef-ea29-ad66-c0ab-6ccd4fc6dce1
* Version Independent ID: cb8cba87-dddd-05e9-4175-f547f01b774c
* Content: [wevtutil](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/wevtutil#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/wevtutil.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/wevtutil.md)
* Product: **windows-server-threshold**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by HenningSR** [comment]
I'm also having this problem. I couldn't immediately find what exit code 32 means.

**Comment by anporumb** [comment]
Same. What's 0x1a90 as a return code?

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by dknappettmsft** [comment]
#assign:dknappettmsft

**Comment by dknappettmsft** [comment]
Hi, you can find the list of the exit codes for inbuilt Windows apps and tools here: https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes, with them grouped by number across multiple articles, e.g. 0-499 are here: https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-. If you get a hexadecimal number, you can convert this to decimal first then lookup the code. I hope that helps.

**Comment by HenningSR** [comment]
Thanks @dknappettmsft How would I know if wevtutil uses these exit codes and does not have implemented its own?

**Comment by dknappettmsft** [comment]
These pages all fall under the parent section of [Windows commands](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands).  I've added a paragraph on there that implies this and provides a link to the debug codes, which should be visible in a few hours.

**Comment by dknappettmsft** [comment]
#please-close
