### ISSUE TITLE
DEV_MODE is not working for any msi

### ISSUE THREAD

**Issue by limulidae** [MicrosoftDocs/windowsserverdocs#2838]
not working in 1904 msi, but working for earlier version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 229f7b83-a501-f0b9-6b3b-bffc84b04554
* Version Independent ID: 7d5f608f-bc6d-6ab6-c186-83dda2ae922d
* Content: [Prepare your development environment](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/extend/prepare-development-environment#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/extend/prepare-development-environment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/extend/prepare-development-environment.md)
* Product: **windows-server-threshold**
* Technology: **manage**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by shashi2713** [comment]
not working for 1910 version as well
