### ISSUE TITLE
Insufficient information for VM version 8.3

### ISSUE THREAD

**Issue by 0xbadfca11** [MicrosoftDocs/windowsserverdocs#2850]
This page has only 9.0 and less than 8.2. However, 8.3 exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e87b5b7-56c5-2a76-270a-baf6925cbeb0
* Version Independent ID: 81f801b0-b310-3976-576c-78b61f7329ce
* Content: [About Hyper-V hypervisor scheduler type selection](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/about-hyper-v-scheduler-type-selection)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/about-hyper-v-scheduler-type-selection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/about-hyper-v-scheduler-type-selection.md)
* Product: **windows-server-hyper-v**
* Technology: **virtualization**
* GitHub Login: @allenma
* Microsoft Alias: **allenma**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
