### ISSUE TITLE
Active Directory Design consideration

### ISSUE THREAD

**Issue by sumanbikram** [MicrosoftDocs/windowsserverdocs#2852]
What about below mentioned flow?
1. Physical design ---&gt; Talks about network, subnet, sites and connectivity
2. Logical Design----&gt; Talks about OU, groups, users, service accounts. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c634e2db-1eda-569f-f8e8-e25da3024554
* Version Independent ID: 3da95bbe-dfc4-7104-9728-ed9c17ba7f1e
* Content: [Understanding AD DS Design](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/understanding-ad-ds-design#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/Understanding-AD-DS-Design.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/Understanding-AD-DS-Design.md)
* Product: **windows-server-threshold**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
