### ISSUE TITLE
Does this also apply to Windows Server 2019?

### ISSUE THREAD

**Issue by jaxidian** [MicrosoftDocs/windowsserverdocs#2853]
If so, it should be officially stated. If not, then the proper documentation for WS2019 should be linked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2604cc9-b00f-2983-a062-124fef5daa00
* Version Independent ID: 6c29a1d0-9dad-79a4-127d-f605f7cff7ac
* Content: [AD Forest Recovery - Backing up a full server](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/ad-forest-recovery-backing-up-system-state)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/AD-Forest-Recovery-Backing-up-System-State.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/manage/AD-Forest-Recovery-Backing-up-System-State.md)
* Product: **windows-server-threshold**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
