### ISSUE TITLE
CSV Cache link is broken

### ISSUE THREAD

**Issue by eponerine** [MicrosoftDocs/windowsserverdocs#2854]
The link under "Relationship to Other Caches" no longer leads to the blog post it originally intended on going to:
https://blogs.msdn.microsoft.com/clustering/2013/07/19/how-to-enable-csv-cache/

That link redirects to a generic Tech Community page for Failover Clustering.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 248105ac-a91a-9f38-1331-da2175cd013f
* Version Independent ID: 70098ddb-576f-f7b4-2524-5c5b1ea49e2b
* Content: [Understanding the cache in Storage Spaces Direct](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/understand-the-cache#relationship-to-other-caches)
* Content Source: [WindowsServerDocs/storage/storage-spaces/understand-the-cache.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/understand-the-cache.md)
* Product: **windows-server-threshold**
* Technology: **storage-spaces**
* GitHub Login: @cosmosdarwin
* Microsoft Alias: **cosdar**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
