### ISSUE TITLE
Storage Accounts

### ISSUE THREAD

**Issue by colinweiner** [MicrosoftDocs/windowsserverdocs#2866]
Storage accounts are mentioned multiple times but it's not clear what their purpose is.  Is it for VM diagnostic etc?

**Storage Accounts:** It is recommended to have two storage accounts. Having a single storage account can lead to creation of a single point of failure and can cause the deployment to become unavailable in an unlikely scenario where the storage account goes down. Two storage accounts will help associate one storage account for each fault line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1eac8a5-9217-7d91-d775-e062e7ea9c74
* Version Independent ID: ee080620-cc4f-bf5f-2c55-ca06d8deca63
* Content: [Active Directory Federation Services in Azure](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/how-to-connect-fed-azure-adfs)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/how-to-connect-fed-azure-adfs.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/how-to-connect-fed-azure-adfs.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by colinweiner** [comment]
I had the same question but it appears that maybe the VM's are not using managed storage for some reason?

**Comment by tplas** [comment]
Same question- Why have any emphasis in the article on storage accounts (used only for unmanaged disk), when best-practice for VM creation is to use managed disk?

**Comment by calethix** [comment]
This documentation needs to be updated.  Stepping through the process as of 1/15/2020, I had similar questions as I came across things that apparently didn't exist when the documentation was last updated.  storage accounts, load balancer SKU, and session persistence to name a few.

**Comment by billmath** [comment]
Thank for submitting this. I have created a work item for it and will reviewing this in the coming weeks. I am not sure what the timeline will be, so I am going to close this for now.  It does appear that the storage accounts were added for the VM creation in Azure.  This is not my area so I am going to have to research this.  But once I have an update I will drop it in here and let you know.

Thank you!

Bill

#please-close

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
