### ISSUE TITLE
Wrong command syntax for Set-RDWebClientDeploymentSetting

### ISSUE THREAD

**Issue by RGlintmeijer** [MicrosoftDocs/windowsserverdocs#2867]
Please remove the dash in the two examples under "How to pre-configure settings for Remote Desktop web client users", like this:

Set-RDWebClientDeploymentSetting SuppressTelemetry $true
Set-RDWebClientDeploymentSetting LaunchResourceInBrowser ($true|$false)

NOT

Set-RDWebClientDeploymentSetting -SuppressTelemetry $true
Set-RDWebClientDeploymentSetting -LaunchResourceInBrowser ($true|$false)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Product: **windows-server-threshold**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
