### ISSUE TITLE
Need version of this page for Windows Server 2019 versions.

### ISSUE THREAD

**Issue by apulliam** [MicrosoftDocs/windowsserverdocs#2871]
The information doesn't appear to be accurate for later versions of Windows Server

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95948764-6ad3-3f0a-0505-70e3bdef5c40
* Version Independent ID: 966dbded-9b19-54b2-d233-d1ffb4b3d03d
* Content: [PowerShell on Nano Server](https://docs.microsoft.com/en-us/windows-server/get-started/powershell-on-nano-server)
* Content Source: [WindowsServerDocs/get-started/PowerShell-on-Nano-Server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/PowerShell-on-Nano-Server.md)
* Service: **na**
* Product: **windows-server-threshold**
* Technology: **server-nano**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@JasonGerend can you vector this appropriately on your side?

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
