### ISSUE TITLE
Configure VLAN for host OS 

### ISSUE THREAD

**Issue by yarcod** [MicrosoftDocs/windowsserverdocs#2873]
[Enter feedback here]
Creating one or many VLAN enabled virtual switch/es does not seem to give host OS access to use those for network communication. The part that says "All traffic that goes through the physical network adapter connected to the virtual switch will be tagged with the VLAN ID you set." make it seem like also the host can utilize this.

Either I'm unaware of a way to connect host OS to these vNICs (is there a way?), or the text might need some clarification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96413472-06ea-691c-23df-b3cf6160e939
* Version Independent ID: daead0d8-ef43-d60d-1d55-9d97d693ed12
* Content: [Configure virtual local area networks for Hyper-V](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/deploy/configure-virtual-local-areal-networks-for-hyper-v)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/deploy/configure-virtual-local-areal-networks-for-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/deploy/configure-virtual-local-areal-networks-for-Hyper-V.md)
* Service: **na**
* Product: **windows-server-threshold**
* Technology: **compute-hyper-v**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
