### ISSUE TITLE
broken links in the WAC intro page

### ISSUE THREAD

**Issue by pipposera** [MicrosoftDocs/windowsserverdocs#2875]
the three links under the video give a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5d4a9c-11eb-3b85-91dd-cdbb0625db5a
* Version Independent ID: 01dad638-f8fb-61ff-4952-e3b25007a234
* Content: [Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/understand/windows-admin-center)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/understand/windows-admin-center.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/understand/windows-admin-center.md)
* Product: **windows-server-threshold**
* Technology: **manage**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by illfated** [comment]
This issue does no longer seem to be accurate. All links on the page are working, at least they do not result in any 404 error.

Please consider closing this issue ticket.

**Comment by illfated** [comment]
#sign-off

**Comment by illfated** [comment]
The page was rearranged after the reported issue, so the issue ticket is no longer accurate. To report any issues with this page, please open a new ticket.

**Comment by illfated** [comment]
#please-close
