### ISSUE TITLE
Common Things to Check with Certificates

### ISSUE THREAD

**Issue by mitchsprague** [MicrosoftDocs/windowsserverdocs#2880]
Would it be possible to add "how to" steps for these items?  Or perhaps links to the steps on how to do these things.  Checking the trust chain sounds like a good idea but how do I do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac07a579-f0ad-2bfa-f584-06cc226dc498
* Version Independent ID: 35fb1792-d791-0f21-6b63-96aa96aaea19
* Content: [AD FS Troubleshooting - Certificates](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-certs#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-certs.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-certs.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
