### ISSUE TITLE
Hmm... Something went wrong - try again

### ISSUE THREAD

**Issue by livestrong91** [MicrosoftDocs/windowsserverdocs#2914]
I have a problem with Windows Admin Center. After installation I get "Hmm... Something went wrong - try again".
Same error with 1904 and 1904.1
OS: Windows Server 2019 Standard Core
The console of the Chrome browser says: HTTP Error 500, Failed to load resource: the server responded with a status of 500 (Internal Server Error)
Same error with Edge.

Any ideas?

Thx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe84fb4b-3420-bc1e-6a1d-b64ecc56fc5e
* Version Independent ID: f089767e-4613-d595-a0ee-0dab012724a1
* Content: [Install Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/install#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/deploy/install.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/deploy/install.md)
* Product: **windows-server-threshold**
* Technology: **manage**
* GitHub Login: @jwwool
* Microsoft Alias: **jeffrew**

**Comment by mwucbs** [comment]
Yes got the same error.
I upgraded from 1904.1 to 1910 and got same error.
i ended up uninstalling and reinstalling, and then i was able to login again, ( ofcause with no connections)
Then i imported my connections, and tried to uninstall azure hybrid services ( something) extension and now it crashed again.

So it its to unstable to implement on Server 2016

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
