### ISSUE TITLE
Documentation doesn't make it clear which ReFS features apply to Windows 10 Pro for Workstations

### ISSUE THREAD

**Issue by jdrch** [MicrosoftDocs/windowsserverdocs#2917]
I'm trying to figure out which ReFS features apply to Windows 10 Pro for Workstations, but the document header says the ReFS docs apply to Server only.

Can someone clarify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb95c569-f9ad-8e2d-3423-2c9629e65b72
* Version Independent ID: e2a4c64a-97c0-b310-2e47-d0c348a8ead7
* Content: [Resilient File System (ReFS) overview](https://docs.microsoft.com/en-us/windows-server/storage/refs/refs-overview#feedback)
* Content Source: [WindowsServerDocs/storage/refs/refs-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/refs/refs-overview.md)
* Product: **windows-server-threshold**
* Technology: **storage-file-systems**
* GitHub Login: @gawatu
* Microsoft Alias: **gawatu**

**Comment by mbalcerzyk** [comment]
I think ReFS was used only in Windows 8. Note, that ReFS is NOT bootable.

**Comment by jdrch** [comment]
> ReFS was used only in Windows 8

It's listed among Windows 10 Pro for Workstations' features.

**Comment by stephc-msft** [comment]
ReFS version are listed on https://en.wikipedia.org/wiki/ReFS
Maybe should add that info here

**Comment by jdrch** [comment]
Agreed!
