### ISSUE TITLE
Page formatting

### ISSUE THREAD

**Issue by Lyko5** [MicrosoftDocs/windowsserverdocs#2920]
Page Headers and descriptions run together and are not formatted correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fc1255a-fc24-26b8-cf22-049b6f3d4988
* Version Independent ID: 3468d97b-4e31-f264-cbe8-3e87805b0eb9
* Content: [Configure a Server Core installation of Windows Server with Sconfig.cmd](https://docs.microsoft.com/en-us/windows-server/get-started/sconfig-on-ws2016#feedback)
* Content Source: [WindowsServerDocs/get-started/Sconfig-on-WS2016.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/Sconfig-on-WS2016.md)
* Product: **windows-server-threshold**
* Technology: **server-general**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
