### ISSUE TITLE
Tools for Forest Recovery automation

### ISSUE THREAD

**Issue by skalitin** [MicrosoftDocs/windowsserverdocs#2930]
This guide says that "Because of the complex and critical nature of the forest recovery process, there is currently no end-to-end automation of it", however there are commercial products which do automate Forest Recovery, for example Quest Recovery Manager for Active Directory Forest Edition or Disaster Recovery Edition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95e9deae-29e2-3ca6-3a38-430b383508c0
* Version Independent ID: 1a6b129b-8faf-6064-5283-52a1de86c9e8
* Content: [AD Forest Recovery - FAQ](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/ad-forest-recovery-faq#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/AD-Forest-Recovery-FAQ.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/manage/AD-Forest-Recovery-FAQ.md)
* Product: **windows-server-threshold**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
Microsoft does not test third party tools for forest recovery.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close

**Comment by izblah** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
