### ISSUE TITLE
POTS UTF8 ON

### ISSUE THREAD

**Issue by rdan461** [MicrosoftDocs/windowsserverdocs#2935]
Starting in Windows Server 2012 the default character is set to UTF8 and not ASCII. This breaks many existing FTP jobs. Details on how to turn UTF8 OFF is now needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eb507ae-f507-f400-714a-718dd663fa50
* Version Independent ID: 5d0e3fa1-50ab-cd91-1cb5-c82658e34ef9
* Content: [ftp ascii](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/ftp-ascii#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/ftp-ascii.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/ftp-ascii.md)
* Product: **windows-server-threshold**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
