### ISSUE TITLE
no redirection from onload.js if the language of the browser is Italian

### ISSUE THREAD

**Issue by pameruoso** [MicrosoftDocs/windowsserverdocs#2940]
Hi, if my computer language is set on italian i get a different message than this: "var mfaSecondFactorErr = "The selected authentication method is not available for";" The message on the browser is in italian and the redirection is not happening.

If I set the language in english everything works as expected. How to support multiple languages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae96cfcf-0a50-7e13-30c8-43e3730e184f
* Version Independent ID: 9d8ed7b7-eec6-1b95-40b8-24a13361f66d
* Content: [Configure AD FS 2016 and Azure MFA](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by ABerTSC** [comment]
same issue here in german

**Comment by Horgster** [comment]
Hi @ABerTSC  and @pameruoso 

I had the same issue for Norwegian Bokmål (nb-NO) and New Norwegian (nn-NO), so I modified the onload.js to check for the browser locale. Below code supports all English Locales and Norwegian, so just add more language that you need.

`//Custom Code
//Customize MFA exception - ref: https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa
//Begin

var domain_hint = "<YOUR_DOMAIN_NAME_HERE>";
var browserlocale = navigator.language.toLocaleLowerCase();
var authArea = document.getElementById("authArea");

if (browserlocale == "no" || browserlocale == "nb-no" || browserlocale == "nn-no") {
    var mfaSecondFactorErr = "Den valgte godkjenningsmetoden er ikke tilgjengelig for";
    var mfaProofupMessage = "Om 5 sekunder blir du automatisk omdirigert for oppsett av flerfaktor-autentisering (MFA) for din brukerkonto. Når du har fullført konfigurasjonen kan du returnere til applikasjonen du prøver å aksessere.<br><br>Hvis du ikke blir omdirigert automatisk, <br><br>vennligst trykk <a href='{0}'>her</a>."
}   
if (browserlocale == "en" || browserlocale == "en-au" || browserlocale == "en-bz" || browserlocale == "en-ca" || browserlocale == "en-gb" || browserlocale == "en-ie" || browserlocale == "en-in" || browserlocale == "en-jm" || browserlocale == "en-my" || browserlocale == "en-nz" || browserlocale == "en-ph" || browserlocale == "en-sg" || browserlocale == "en-tt" || browserlocale == "en-us" || browserlocale == "en-za") {
    var mfaSecondFactorErr = "The selected authentication method is not available for";
    var mfaProofupMessage = "You will be automatically redirected in 5 seconds to set up your account for additional security verification. Once you have completed the setup, please return to the application you are attempting to access.<br><br>If you are not redirected automatically, please click <a href='{0}'>here</a>."
}

if (authArea) {
        var errorMessage = document.getElementById("errorMessage");
        if (errorMessage) {
            if (errorMessage.innerHTML.indexOf(mfaSecondFactorErr) >= 0) {
    
                //Hide the error message
                var openingMessage = document.getElementById("openingMessage");
                if (openingMessage) {
                    openingMessage.style.display = 'none'
                }
                var errorDetailsLink = document.getElementById("errorDetailsLink");
                if (errorDetailsLink) {
                    errorDetailsLink.style.display = 'none'
                }
    
                //Provide a message and redirect to Azure AD MFA Registration Url
                var mfaRegisterUrl = "https://account.activedirectory.windowsazure.com/proofup.aspx?proofup=1&whr=" + domain_hint;
                errorMessage.innerHTML = "<br>" + mfaProofupMessage.replace("{0}", mfaRegisterUrl);
                window.setTimeout(function () { window.location.href = mfaRegisterUrl; }, 5000);
            }
        }
}`

**Comment by illfated** [comment]
@TinaMcN : Would it be possible for your team to take a look at this, or is this part of the repository beyond your workspace?

**Comment by TinaMcN** [comment]
@cnicco I think you manage localization of Windows Server content, can you help with this?

**Comment by Horgster** [comment]
Hi,

I have updated the onload.js to include more languages. Not all languages is translated correctly, but at least the error message will match with the browserlocale. The code can be optimized with RegEx to reduce code line, but just wanted to keep it simple.

Hence; Microsoft Product group should fix this for ADFS 2016 and ADFS 2019 if they want to have their customers to migrate from Azure MFA onPrem to Azure MFA cloud - ref [https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa)

```
//Custom Code
//Customize MFA exception - ref: https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa
//Begin

var domain_hint = "<YOUR_DOMAIN_NAME_HERE>";
var browserlocale = navigator.language.toLocaleLowerCase();
var authArea = document.getElementById("authArea");

// German Browser Locale
if (browserlocale == "de" || browserlocale == "de-de" || browserlocale == "de-lu" || browserlocale == "de-ch" || browserlocale == "de-en" || browserlocale == "de-li" || browserlocale == "de-no") {
    var mfaSecondFactorErr = "Die ausgewählte Authentifizierungsmethode ist für";
    var mfaProofupMessage = "You will be automatically redirected in 5 seconds to set up your account for additional security verification. Once you have completed the setup, please return to the application you are attempting to access.<br><br>If you are not redirected automatically, please click <a href='{0}'>here</a>."
}   

// Danish Browser Locale
if (browserlocale == "dk" || browserlocale == "da-dk" || browserlocale == "da-gl" ) {
    var mfaSecondFactorErr = "Den valgte godkendelsesmetode er ikke tilgængelig for";
    var mfaProofupMessage = "You will be automatically redirected in 5 seconds to set up your account for additional security verification. Once you have completed the setup, please return to the application you are attempting to access.<br><br>If you are not redirected automatically, please click <a href='{0}'>here</a>."
}   

// English Browser Locale
if (browserlocale == "en" || browserlocale == "us" || browserlocale == "us-en" || browserlocale == "en-au" || browserlocale == "en-bz" || browserlocale == "en-ca" || browserlocale == "en-gb" || browserlocale == "en-ie" || browserlocale == "en-in" || browserlocale == "en-jm" || browserlocale == "en-my" || browserlocale == "en-nz" || browserlocale == "en-ph" || browserlocale == "en-sg" || browserlocale == "en-tt" || browserlocale == "en-us" || browserlocale == "en-za" || browserlocale == "en_us" || browserlocale == "en_gb" || browserlocale == "en_ca") {
    var mfaSecondFactorErr = "The selected authentication method is not available for";
    var mfaProofupMessage = "You will be automatically redirected in 5 seconds to set up your account for additional security verification. Once you have completed the setup, please return to the application you are attempting to access.<br><br>If you are not redirected automatically, please click <a href='{0}'>here</a>."
}

// Spanish Browser Locale
if (browserlocale == "es" || browserlocale == "es_mx" || browserlocale == "es_US" || browserlocale == "es-ar" || browserlocale == "es-bo" || browserlocale == "es-br" || browserlocale == "es-cl" || browserlocale == "es-co" || browserlocale == "es-cr" || browserlocale == "es-do" || browserlocale == "es-ec" || browserlocale == "es-es" || browserlocale == "es-eu" || browserlocale == "es-gb" || browserlocale == "es-gt" || browserlocale == "es-hn" || browserlocale == "es-la" || browserlocale == "es-mx" || browserlocale == "es-pa" || browserlocale == "es-pe" || browserlocale == "es-pr" || browserlocale == "es-py" || browserlocale == "es-sv" || browserlocale == "es-us" || browserlocale == "es-uy" || browserlocale == "es-ve" || browserlocale == "es-xl" ) {
    var mfaSecondFactorErr = "El método de autenticación seleccionado no está";
    var mfaProofupMessage = "You will be automatically redirected in 5 seconds to set up your account for additional security verification. Once you have completed the setup, please return to the application you are attempting to access.<br><br>If you are not redirected automatically, please click <a href='{0}'>here</a>."
} 

// Finland Browser Locale
if (browserlocale == "fi" || browserlocale == "fi-fi") {
    var mfaSecondFactorErr = "Valittu todentamismenetelmä ei ole käytettävissä";
    var mfaProofupMessage = "You will be automatically redirected in 5 seconds to set up your account for additional security verification. Once you have completed the setup, please return to the application you are attempting to access.<br><br>If you are not redirected automatically, please click <a href='{0}'>here</a>."
} 

// French Browser Locale
if (browserlocale == "fr" || browserlocale == "fr-fr" || browserlocale == "fr_fr" || browserlocale == "fr-ar" || browserlocale == "fr-be" || browserlocale == "fr-ca" || browserlocale == "fr-ch" || browserlocale == "fr-cn" || browserlocale == "fr-dz" || browserlocale == "fr-lu" || browserlocale == "fr-ma" || browserlocale == "fr-mc" || browserlocale == "fr-mg" || browserlocale == "fr-pt" || browserlocale == "fr-tn" || browserlocale == "fr-us" || browserlocale == "french-france") {
    var mfaSecondFactorErr = "La méthode d'authentification sélectionnée n'est pas";
    var mfaProofupMessage = "Vous allez être redirigé dans 5 secondes pour pour la mise à jour de l'authentification multi-facteurs. Une fois que vous avez fait la mise à jour, merci de retourner dans l'application que vous essayez d'accéder.<br><br>Si vous n'êtes pas redirigé automatiquement, veuillez cliquer <a href='{0}'>ici</a>."
} 

// Italian Browser Locale
if (browserlocale == "it" || browserlocale == "it-it" || browserlocale == "it-ch" || browserlocale == "it-sm") {
    var mfaSecondFactorErr = "Il metodo di autenticazione selezionato non è";
    var mfaProofupMessage = "You will be automatically redirected in 5 seconds to set up your account for additional security verification. Once you have completed the setup, please return to the application you are attempting to access.<br><br>If you are not redirected automatically, please click <a href='{0}'>here</a>."
} 

// Dutch Browser Locale
if (browserlocale == "nl" || browserlocale == "nl-be" || browserlocale == "nl-cw" || browserlocale == "nl-gb" || browserlocale == "nl-nl" ) {
    var mfaSecondFactorErr = "De geselecteerde verificatiemethode is niet beschikbaar";
    var mfaProofupMessage = "You will be automatically redirected in 5 seconds to set up your account for additional security verification. Once you have completed the setup, please return to the application you are attempting to access.<br><br>If you are not redirected automatically, please click <a href='{0}'>here</a>."
} 

// Norwegian Browser Locale
if (browserlocale == "nb" || browserlocale == "nb-no" || browserlocale == "nn-no" || browserlocale == "nn-sj" || browserlocale == "no" || browserlocale == "nn") {
    var mfaSecondFactorErr = "Den valgte godkjenningsmetoden er ikke tilgjengelig for";
    var mfaProofupMessage = "Om 5 sekunder blir du automatisk omdirigert for oppsett av flerfaktor-autentisering (MFA) for din brukerkonto. Når du har fullført konfigurasjonen kan du returnere til applikasjonen du prøver å aksessere.<br><br>Hvis du ikke blir omdirigert automatisk, vennligst trykk <a href='{0}'>her</a>."
}   

// Sweedish Browser Locale
if (browserlocale == "se" || browserlocale == "sv-se" || browserlocale == "sv-fi") {
    var mfaSecondFactorErr = "Det går inte att använda den valda";
    var mfaProofupMessage = "Om 5 sekunder blir du automatisk omdirigert for oppsett av flerfaktor-autentisering (MFA) for din brukerkonto. Når du har fullført konfigurasjonen kan du returnere til applikasjonen du prøver å aksessere.<br><br>Hvis du ikke blir omdirigert automatisk, vennligst trykk <a href='{0}'>her</a>."
} 


if (authArea) {
        var errorMessage = document.getElementById("errorMessage");
        if (errorMessage) {
            if (errorMessage.innerHTML.indexOf(mfaSecondFactorErr) >= 0) {
    
                //Hide the error message
                var openingMessage = document.getElementById("openingMessage");
                if (openingMessage) {
                    openingMessage.style.display = 'none'
                }
                var errorDetailsLink = document.getElementById("errorDetailsLink");
                if (errorDetailsLink) {
                    errorDetailsLink.style.display = 'none'
                }
    
                //Provide a message and redirect to Azure AD MFA Registration Url
                var mfaRegisterUrl = "https://account.activedirectory.windowsazure.com/proofup.aspx?proofup=1&whr=" + domain_hint;
                errorMessage.innerHTML = "<br>" + mfaProofupMessage.replace("{0}", mfaRegisterUrl);
                window.setTimeout(function () { window.location.href = mfaRegisterUrl; }, 5000);
            }
        }
}

//End Customize MFA Exception
//End Custom Code


```

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
