### ISSUE TITLE
Missing link for the WS-Federation, WS-Trust, and SAML protocols and profiles

### ISSUE THREAD

**Issue by jfayatkim** [MicrosoftDocs/windowsserverdocs#2941]
Where is the link for the developer guidance for the WS-Federation, WS-Trust, and SAML protocols and profiles?  The page says
"If you are interested in developer guidance for these protocols, see the article here."  but the "here" is not a link.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3824263-5c49-03e9-9063-b44b1c636540
* Version Independent ID: 31684400-9100-b442-8957-c1300ad35cb8
* Content: [AD FS Scenarios for Developers](https://docs.microsoft.com/en-gb/windows-server/identity/ad-fs/overview/ad-fs-scenarios-for-developers)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/AD-FS-Scenarios-for-Developers.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/AD-FS-Scenarios-for-Developers.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 2940 -b #assign:IngridAtMicrosoft
