### ISSUE TITLE
Wrong URI or Link is dead at guarded-fabric-install-trusted-tpm-root-certificates.md

### ISSUE THREAD

**Issue by 8bb-glshk** [MicrosoftDocs/windowsserverdocs#2948]
`https://tpmsec.microsoft.com/OnPremisesDHA/TrustedTPM.cab` redirect to `https://microsoft.com/en-us`

**Comment by peledins** [comment]
looks like it is fixed and points to https://go.microsoft.com/fwlink/?linkid=2097925.
