### ISSUE TITLE
Lockout criteria mentioned in the Key points to remember section not correct

### ISSUE THREAD

**Issue by TheIT-Guy** [MicrosoftDocs/windowsserverdocs#2953]
I think the that the text "If badPwdCount &gt;= ExtranetLockoutThreshold AND badPasswordTime + ExtranetObservationWindow &lt; Current time, AD FS will reject authentication requests from extranet" is not correct. It should be "If badPwdCount &gt;= ExtranetLockoutThreshold AND badPasswordTime + ExtranetObservationWindow &gt; Current time, AD FS will reject authentication requests from extranet". Or in human language: when you tried more than allowed by the extranetlockouttreshold and the attempt was within the observation window started counting from the last failed login attempt.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f51716ad-72e5-c96a-9178-76b7b39ffa3f
* Version Independent ID: 4c3434ad-f50a-22ed-8b05-1aeb14f00706
* Content: [Configure AD FS Extranet Lockout Protection](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-extranet-soft-lockout-protection#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Soft-Lockout-Protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Soft-Lockout-Protection.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
