### ISSUE TITLE
error in the auditing levels powershell examples

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/windowsserverdocs#2956]
Each of the examples has a space between the dash and the parameter name.  For example:
Set-AdfsProperties - AuditLevel Verbose

There should be no space.  Example:
Set-AdfsProperties -AuditLevel Verbose

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c0d1afd-b14e-c932-895a-61d91c35de85
* Version Independent ID: dc863ee7-b43e-2db8-021e-e492610f49ab
* Content: [AD FS Troubleshooting - Auditing Events and Logging](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-logging)
* Content Source: [WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-logging.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-logging.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by markaldridge** [comment]
I've submitted a PR for this.
https://github.com/MicrosoftDocs/windowsserverdocs/pull/3025

**Comment by jordanmills** [comment]
Thanks.  I've never been able to get that to work right. Not a dev, I just make scripts go.

**Comment by markaldridge** [comment]
The following guide explains how to do it all from within the browser.
https://docs.microsoft.com/en-us/windows/whats-new/contribute-to-a-topic

**Comment by AndyChips** [comment]
Under the section "To enable security auditing", "User Rights Management" should read: "User Rights Assignment"

**Comment by illfated** [comment]
https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-logging#to-enable-security-auditing
