### ISSUE TITLE
2008R2 and earlier schema updates

### ISSUE THREAD

**Issue by abartlet** [MicrosoftDocs/windowsserverdocs#296]
It would be really helpful if WindowsServerDocs/identity/ad-ds/deploy/Schema-Updates.md could be extended historically, to include the earlier schema updates, including Windows 2003, 2003R2 but most importantly 2008R2?  I know these files are available elsewhere on technet, but the great thing about this new approach to doc publishing is that it is all in one place and is under a clear MIT licence. 

Thanks,

Andrew Bartlett

**Comment by lizap** [comment]
Thanks, Andrew - I'll get this feedback to the AD content team for their review. Thanks, Liza

**Comment by MicrosoftGuyJFlo** [comment]
@abartlet The schema files are all included in each version of Windows Server in the Windows\System32\adprep folder. If you need sch0-13 I can probably grab them from a Windows 2000 iso file.

**Comment by abartlet** [comment]
On Fri, 2017-12-08 at 19:36 +0000, John Flores wrote:
> @abartlet The schema files are all included in each version of
> Windows Server in the Windows\System32\adprep folder. If you need
> sch0-13 I can probably grab them from a Windows 2000 iso file.
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

Thanks.  If you could get me those and include it here it would be very
helpful and make this page a comprehensive guide to the schema changes.

Additionally, I should clarify:  The thing that is really, really great
is things in this repository are made available under the Open Source
MIT licence, which allows me to redistribute it as part of my work on
Samba.  

Samba is an Open Source implementation of the windows protocols,
including an AD DC, so we are really big fans of this documentation. 

Thanks!

Andrew Bartlett

-- 
Andrew Bartlett                       http://samba.org/~abartlet/
Authentication Developer, Samba Team  http://samba.org
Samba Developer, Catalyst IT          http://catalyst.net.nz/services/samba

**Comment by abartlet** [comment]
I'll also note that we (@GSam and I) are more than happy to do the work
to get this into the markdown format and prepared for publication if
the .ldf files are published into a branch of this repo by a Microsoft
employee. 

Thanks,

Andrew Bartlett

**Comment by abartlet** [comment]
On this now-closed issue.  Does this mean these files available under a permissive licence somewhere, or that this isn't possible at this time?

**Comment by abartlet** [comment]
Fixed by [fcbd5cf887dbd47bbff4e97f9a758debb1dbd0a7](https://github.com/MicrosoftDocs/windowsserverdocs/commit/fcbd5cf887dbd47bbff4e97f9a758debb1dbd0a7), thanks so much!
