### ISSUE TITLE
Information around best practises load balancers other than Azure LB

### ISSUE THREAD

**Issue by Nilis312** [MicrosoftDocs/windowsserverdocs#2974]
Good day,
Can you add best practices around creating load balancers with RDWeb and RDGW ? Now only limited info is available for Azure LB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b83e43bd-69b6-783d-b377-af76e15e82e6
* Version Independent ID: e65dbfd5-6a8e-09b4-e104-871f7a58a71e
* Content: [Add high availability to the RD Web and Gateway web front](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-rdweb-gateway-ha)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-rdweb-gateway-ha.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-rdweb-gateway-ha.md)
* Product: **windows-server-threshold**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by srinivasumekala** [comment]
Great article here.
I am looking for upgrading RDWebClient in production, without any down time.
With upgrade command, managed to revised version from 1.0.1 to 1.0.8.
But I can see latest is 1.0.18. Please help with some articles just upgrade without down time.
Or is it like need to remove RDWebClient and re-install again?
I was trying to get HELP from MS Support team with reference of case #119060724000422 but no use so far.

Thanks,
Sri

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
