### ISSUE TITLE
Incorrect attribute used.

### ISSUE THREAD

**Issue by IpsitoDutta** [MicrosoftDocs/windowsserverdocs#2981]
The section that says 

"Note

If the PreferredAuthenticationMethod property is empty ($null) it means the default behavior of TranslateToFreshPasswordAuth.
"

Should say

"Note

If the PromptLoginBehavior property is empty ($null) it means the default behavior of TranslateToFreshPasswordAuth.
"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fd38f15-29d2-383a-f529-c9e90e8877ba
* Version Independent ID: 44d9311f-16cd-c0ef-7624-9bd4b321a3b8
* Content: [AD FS prompt=login](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/ad-fs-prompt-login#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/AD-FS-Prompt-Login.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/AD-FS-Prompt-Login.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by student-forever** [comment]
Just to add the parameter 'PreferredAuthenticationMethod' is never blank. It will always say WsFed or SAMLP.

**Comment by petrkspb** [comment]
Moreover, there is no such property - PreferredAuthenticationMethod, but PreferredAuthenticationMethod instead is.

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
