### ISSUE TITLE
FOD on free Hyper-V Server

### ISSUE THREAD

**Issue by DSPatrick** [MicrosoftDocs/windowsserverdocs#2987]
Can FOD be installed on the free versions of Hyper-V Server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5da35d75-87fe-4432-9a86-d07f1b4f41b5
* Version Independent ID: 6e3f4dfd-d101-c26b-94a4-fe44093dba8e
* Content: [Server Core App Compatibility Feature on Demand (FOD)](https://docs.microsoft.com/en-us/windows-server/get-started-19/install-fod-19)
* Content Source: [WindowsServerDocs/get-started-19/install-fod-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/install-fod-19.md)
* Product: **windows-server-threshold**
* Technology: **server-general**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Karl-WE** [comment]
I'd say yes. It is an addition to the server product. Nowhere I read about a limitation or license requirement.
Try it out in your lab

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
