### ISSUE TITLE
Code about running a script has 'map' function but no indication of where this function comes from

### ISSUE THREAD

**Issue by bsosnader** [MicrosoftDocs/windowsserverdocs#2989]
I'm trying to use the example code to run a powershell script but the 'map' function does not exist, where does this function come from? Is it imported from some package? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08b73b6a-17c3-e5e4-b77f-56568f01dc86
* Version Independent ID: f0d4a76f-1aec-ba4f-4596-6dbc94e1d11a
* Content: [Using PowerShell in your extension](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/extend/guides/powershell)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/extend/guides/powershell.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/extend/guides/powershell.md)
* Product: **windows-server-threshold**
* Technology: **manage**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by alexanderboswell** [comment]
import { map } from 'rxjs/operators';
