### ISSUE TITLE
Drive-by download link is dead

### ISSUE THREAD

**Issue by KrypticChewie** [MicrosoftDocs/windowsserverdocs#2994]
The drive-by download link is dead
https://www.microsoft.com/security/sir/glossary/drive-by-download-sites.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ef7a418-b725-0030-01ba-a7a070723254
* Version Independent ID: 0b328a4c-8c72-9914-c1ae-9e291429c1d5
* Content: [Attractive Accounts for Credential Theft](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/attractive-accounts-for-credential-theft)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Attractive-Accounts-for-Credential-Theft.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Attractive-Accounts-for-Credential-Theft.md)
* Product: **windows-server-threshold**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
