### ISSUE TITLE
Protected accounts table needs to be updated for 2016

### ISSUE THREAD

**Issue by KrypticChewie** [MicrosoftDocs/windowsserverdocs#2996]
Default Protected Accounts and Groups in Active Directory by Operating System and Service Pack (SP) Version table needs to be updated for 2016

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7310691d-669a-4cfa-7480-622d72d52d85
* Version Independent ID: 0d8d756e-002a-4fc4-a12f-d3ac594dab34
* Content: [Reducing the Active Directory Attack Surface](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/reducing-the-active-directory-attack-surface)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Reducing-the-Active-Directory-Attack-Surface.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Reducing-the-Active-Directory-Attack-Surface.md)
* Product: **windows-server-threshold**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
