### ISSUE TITLE
`The parameter is incorrect` : consistent mountvol /p with drive letter failure

### ISSUE THREAD

**Issue by Tatsinnit** [MicrosoftDocs/windowsserverdocs#2998]
**Behaviou**r:

* `mountvol [Drive]<path> /p` gives back consistent error for `The parameter is incorrect`
* 📓 => please let me know\guide me: if there is any direct Dev tool I can contact internal dev as well.

**Documentation**: 

* https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mountvol 

Supporting Test via one of the az online vms.

cmd ver: `Microsoft Windows [Version 10.0.14393]`

![image](https://user-images.githubusercontent.com/6233295/59983104-8d706380-966f-11e9-9ec6-b6bf21baba1e.png)

:bulb: Please feel free to provide me internal alias and I can contact you guys via teams for screenshare in detail.

few git issues with similar failures:

* https://github.com/MicrosoftDocs/windows-itpro-docs/issues/1776 (No updates but was closed recently I think its the same issue)
* Long shot: not sure if cause of this issue: https://github.com/MicrosoftDocs/windowsserverdocs/issues/1317 (is possibly the root cause of `/p` behaviour as well)

Thanks,
^Tats

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
