### ISSUE TITLE
Typo in user_impersonation claim issuance that prevents tutorial from working

### ISSUE THREAD

**Issue by tobyartisan** [MicrosoftDocs/windowsserverdocs#3000]
The tutorial when followed as-is today fails. AD FS 2016 will issue the following error when the `ToDoListService` API attempts to get a token to call the `WebApiOBO` API, **"MSIS9650: Received invalid OAuth request. Access token in the 'assertion' parameter value doesn't contain required scope claim with value 'user_impersonation'."**

The reason is because there is a typo when creating the user_impersonation claims issuance rule. The actual rule should use http instead of https as the `Type`, as shown below. (This change will make AD FS 2016 issue the `scp` claim on the JWT token. Without the `scp` claim, AD FS 2016 will return an error when the ToDoListService attempts to fetch a token for the WebApiOBO service.)

```
@RuleName = "Issue user_impersonation scope"
=&gt; issue(Type = "http://schemas.microsoft.com/identity/claims/scope", Value = "user_impersonation");
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e13f162-0b92-091e-f811-8645f786185f
* Version Independent ID: 68332cf9-44a5-8f19-d149-d294c8c4db5c
* Content: [Build a multi-tiered application using On-Behalf-Of (OBO) using OAuth with AD FS 2016 or later](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/ad-fs-on-behalf-of-authentication-in-windows-server#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/ad-fs-on-behalf-of-authentication-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/ad-fs-on-behalf-of-authentication-in-windows-server.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by riesm** [comment]
I ran into the same issue and tobyartisan is right about the solution. please change the documentation accordingly.

**Comment by illfated** [comment]
Fair point, as it seems to be that the URL was changed in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/bbc102cb76ccad2c0ccc9f62641821836a3dd1e8 where 765 files were changed from using http to use https in all the links, regardless of code or non-code.

I am fairly sure the change in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/bbc102cb76ccad2c0ccc9f62641821836a3dd1e8 should not have been applied to the URL in the code sample.

I am making a PR to suggest the change.
