### ISSUE TITLE
Contradictory Remarks

### ISSUE THREAD

**Issue by alandraper** [MicrosoftDocs/windowsserverdocs#3002]
it says /s deletes a directory tree including all files. Immediately below, the remarks say you cannot delete a directory that contains files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fef1135b-12a8-19a8-cccb-13444d0cb76b
* Version Independent ID: d884c36f-5754-3cae-5c12-1a6948ab8f74
* Content: [rd](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/rd#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/rd.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/rd.md)
* Product: **windows-server-threshold**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by gowikel** [comment]
I think this is like in Gnu/Linux, by default you cannot remove directories that contains files unless you add the /s parameter.

So:

This will remove a directory if it is empty
>> rd my_directory

This will remove a directory, it it contains files, they will be removed too.
>> rd /s my_directory

**Comment by alandraper** [comment]
Yep, that's exactly what it means. I was just saying the wording on the documentation is unclear. The bullet point below should read:

You cannot delete a directory that contains files, including hidden or system files unless the /s parameter is specified. If you attempt to do so, the following message appears:
The directory is not empty
