### ISSUE TITLE
Table formatting error

### ISSUE THREAD

**Issue by ElizabethGreene** [MicrosoftDocs/windowsserverdocs#3013]
The Table that starts with "If you are running this edition:" is malformed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e32288e6-1a81-01da-51bf-d1564049a28a
* Version Independent ID: 7388c199-ee35-63fa-deda-e3f6399de3ee
* Content: [Upgrade Domain Controllers to Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/upgrade-domain-controllers#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/upgrade-domain-controllers.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/upgrade-domain-controllers.md)
* Product: **windows-server-threshold**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
Fixed in private repo. Should publish this afternoon. Thanks for reporting!

**Comment by MicrosoftGuyJFlo** [comment]
#please-close

**Comment by ElizabethGreene** [comment]
Thanks!
