### ISSUE TITLE
Windows Server Core limitations are outdated

### ISSUE THREAD

**Issue by Karl-WE** [MicrosoftDocs/windowsserverdocs#3016]
Hi there I have spent some time to merge the outcome of Server 2019 FOD and added them to the list. 

The current list, for newbies to the topic might result into wrong considerations and decisions.

Application | Server Core | Server with Desktop Experience
-- | -- | --
Command prompt | available | available
Windows PowerShell/ Microsoft   .NET | available | available
**Perfmon.exe | FOD 1903 | available**
Windbg (GUI) | supported | supported
**Resmon.exe | FOD 1903 | available**
Regedit | available | available
Fsutil.exe | available | available
Disksnapshot.exe | not available | available
Diskpart.exe | available | available
**Diskmgmt.msc | FOD 1903 | available
Devmgmt.msc | FOD 1903 | available**
Server Manager | not available | available
**Mmc.exe | FOD 1903 | available
Eventvwr | FOD 1903 | available**
Wevtutil (Event queries) | available | available
Services.msc | not available | available
Control Panel | not available | available
Windows Update (GUI) | not available | available
**Windows Explorer | FOD 1903 | available**
Taskbar | not available | available
Taskbar notifications | not available | available
Taskmgr | available | Available
**Task Scheduler (taskschd.msc) | Available with FOD 18346 | Available**
**Internet Explorer or Edge | FOD 1903 (IE) | available**
**Edge Dev / Can | no tested | available
Built-in help system | not available | available
Windows 10 Shell | not available | available
Windows Media Player | not available | available
PowerShell | available | available
PowerShell ISE | FOD 1903 | available
PowerShell IME | available | available
Mstsc.exe | not available | available
Remote Desktop Services | available | available
**Hyper-V Manager | Available   Starting with FOD   18346 | available**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a07e674-1b2d-b429-cbe0-85377e758659
* Version Independent ID: 503fa53f-90f8-69ef-ec4c-461c0f86c373
* Content: [Roles, Role Services, and Features not in Windows Server - Server Core](https://docs.microsoft.com/en-us/windows-server/administration/server-core/server-core-removed-roles#feedback)
* Content Source: [WindowsServerDocs/administration/server-core/server-core-removed-roles.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/server-core/server-core-removed-roles.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap

**Comment by Karl-WE** [comment]
Roles not in Server Core
•	Fax
•	MultiPointServerRole
•	NPAS / NPS (RADIUS)
•	WDS
 
 
Role Services not in Server Core
Note that some Remote Desktop role services are included in Server Core (Connection Broker, Licensing, Virtualization Host), but others are NOT (Gateway, RD Session Host, Web Access).
•	Print-Scan-Server
•	Print-Internet
•	RDS-Gateway
•	RDS-RD-Server
•	RDS-Web-Access
•	Web-Mgmt-Console (IIS Verwaltungskonsole, nicht IIS)
•	Web-Lgcy-Mgmt-Console (IIS Verwaltungskonsole, nicht IIS)
•	WDS-Deployment
•	WDS-Transport (before Windows Server version 1803)
**•	Remote Desktop Connection Broker (starting with 1809)
•	Remote Desktop Virtualization Host (starting with 1809)** 
 

Features not in Server Core
•	BITS-IIS-Ext
•	BitLocker-NetworkUnlock
•	Direct-Play
•	Internet-Print-Client
•	LPR-Port-Monitor
•	MSMQ-Multicasting
•	CMAK
•	Remote-Assistance
•	RSAT-SMTP
•	RSAT-Feature-Tools-BitLocker-RemoteAdminTool
•	RSAT-Bits-Server
•	RSAT-NLB
•	RSAT-SNMP
•	RSAT-WINS
•	Hyper-V-Tools
•	RSAT-RDS-Tools
•	RSAT-RDS-Gateway
•	RSAT-RDS-Licensing-Diagnosis-UI
•	RDS-Licensing-UI
•	UpdateServices-UI
•	RSAT-ADCS
•	RSAT-ADCS-Mgmt
•	RSAT-Online-Responder
•	RSAT-ADRMS
•	RSAT-Fax
•	RSAT-File-Services
•	RSAT-DFS-Mgmt-Con
•	RSAT-FSRM-Mgmt
•	RSAT-NFS-Admin
•	RSAT-NPAS
•	RSAT-Print-Services
•	RSAT-VA-Tools
•	WDS-AdminPack
•	SMTP-Server
•	TFTP-Client
•	WebDAV-Redirector
•	Biometric-Framework
•	Windows-Defender-Gui
•	Windows-Identity-Foundation
**•	PowerShell-ISE (before FOD 1903)**
•	Search-Service
•	Windows-TIFF-IFilter
•	Wireless-Networking
•	XPS-Viewer

**Comment by Karl-WE** [comment]
Please also consider to update your whitelist accordingly:
https://docs.microsoft.com/en-us/windows-server/administration/server-core/server-core-roles-and-services

**Comment by Karl-WE** [comment]
Hi there @illfated @jwwool @steved0x any news on whether this can be merged? 
It is really important to update it.

**Comment by illfated** [comment]
Thank you for asking. Myself, I would open a PR to get more feedback, since issue tickets may take too long to get any feedback at all from the MS Docs server team. Main reason: time limitation based on team overall capacity.

Please add your suggestion to the correct page, complete the PR, and I will comment on it to gain focus.

**Comment by jwwool** [comment]
Hi @Karl-WE, it's not clear to me why you tagged me in this. Were you intending to tag Jeff Woolsey?

**Comment by Karl-WE** [comment]
Oh sorry, you are right with your guess.

**Comment by Karl-WE** [comment]
@illfated that's a good advice. I would not have necroed this but out of the blue 4 or 5 of my really old reports - still relevant though - got closed and reopened by @steved0x unclear why.

**Comment by illfated** [comment]
@Karl-WE : That closing and reopening event for many (maybe most or all) of the tickets in this repository is an attempt to flush out which tickets, pointing to referenced pages/documents, are showing the wrong author of the document. Many of the tickets (and the pages they originate from) are still using MS Docs team members (authors) who have moved on to either a different team or a new area of expertise, and either no longer work in this department, or are now responsible for a different set of documents, depending on their new field of responsibilities.

Whenever any of your reopened tickets get a comment from a team member who posts a comment about no longer being the author (if they are at all still using GitHub), it is a sign that the referenced article needs to have a new responsible author assigned (even if they are not the original author), just to make sure that all the articles/documents/pages display the name of a current working member of the MS Docs team.

**Comment by Karl-WE** [comment]
Good to know! I wonder how you managed to learn so much about the processes here. It is great to have you as a mentor, if I may say!

**Comment by illfated** [comment]
Sure thing, I enjoy sharing the knowledge I have picked up during the 4-5 years I have been using GitHub. The last 2-3 years of those are also spent within the MS Docs repositories, so while being a highly functioning autistic, I notice a lot of details when something changes. The main downside, though, of having my mental disability, is that I struggle to maintain the overall "big picture" of things, but I usually focus on the areas where I can contribute.

**Comment by Karl-WE** [comment]
#closed new PR will be tracked in #5344
