### ISSUE TITLE
Missing / Mistargeted Links in Understanding Active Directory Section

### ISSUE THREAD

**Issue by poolmanjim** [MicrosoftDocs/windowsserverdocs#3036]
I have found the following issues with the links at the bottom of the page.
- Active Directory Schema is just text, no link.
- Understanding Trusts takes me to a page on "Domain and Forest Functionality"
- Active Directory Replication Technologies takes me to the same link as "Domain Controller Roles" does.
- Interoperating with DNS and Group Policy is just text, no link.

Some of this might be intentional but some of it probably isn't. Thought you would like to know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94251036-29c8-87b0-eb8f-2516600d4aac
* Version Independent ID: f5309f09-ad43-619b-c23c-269f37177d2c
* Content: [Active Directory Domain Services Overview](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/get-started/virtual-dc/active-directory-domain-services-overview)
* Content Source: [WindowsServerDocs/identity/ad-ds/get-started/virtual-dc/Active-Directory-Domain-Services-Overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/get-started/virtual-dc/Active-Directory-Domain-Services-Overview.md)
* Product: **windows-server-threshold**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
@poolmanjim Thanks!

**Comment by 211hari** [comment]
This is the correct link I guess: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc776877(v=ws.10)
