### ISSUE TITLE
Missing word in sentence

### ISSUE THREAD

**Issue by adumont** [MicrosoftDocs/windowsserverdocs#3043]
[Enter feedback here]

There seems to be a missing word in the following sentence:

> **NOTE**: Your attempt to use Get-Credential and type in a DN and password to be used to bind to an LDAP instance might result in a failure because the **[missing word here]** of the user interface requirement for specific input formats[...]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce6494d8-d525-8961-8dff-c5ee55a18849
* Version Independent ID: a3608a5f-26ed-1a93-2cd2-2fe2e5238248
* Content: [Configure AD FS to authenticate users stored in LDAP directories](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-to-authenticate-users-stored-in-ldap-directories#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-to-authenticate-users-stored-in-LDAP-directories.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-to-authenticate-users-stored-in-LDAP-directories.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by dplotnikov** [comment]
@adumont I think there was an extra word

@billmath feel free to merge the PR and then close this issue

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 2987 -b #assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
