### ISSUE TITLE
Minor typo: creates vs created

### ISSUE THREAD

**Issue by petertuton** [MicrosoftDocs/windowsserverdocs#3046]
"For more information on how the UPN is creates see" should be "For more information on how the UPN is created see" :) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02d8b61-29e8-c0a7-b3b2-79be7212a91c
* Version Independent ID: b4346d87-0727-c7fe-7896-7fd79098825c
* Content: [Configuring Alternate Login ID](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configuring-alternate-login-id)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configuring-Alternate-Login-ID.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configuring-Alternate-Login-ID.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by dplotnikov** [comment]
@ptuton thanks for noticing!

@billmath I've created a PR for it, please merge and close this issue

**Comment by illfated** [comment]
#please-close
