### ISSUE TITLE
What if I want to configure a static IP on my cluster but only have DHCP on all my NIC's?

### ISSUE THREAD

**Issue by ShawnPOWER** [MicrosoftDocs/windowsserverdocs#3050]
How would I go about setting up a static IP after the cluster is created as DHCP? The reason I ask is when I setup a new cluster and it is DHCP (all NIC's are DHCP and no static IP's are set, Azure is a good example here) the cluster calls the core resource "Distributed Server Name" and I have no open for IP Address as it is DHCP, nor one to create it. Seems odd that I would have to blow away the cluster just to set my NIC to static to get it setup as a "Server Name" cluster core resource. Cloud this document be updated to include that information please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa6a457c-f213-1d54-9dcb-d42d9ff84bd1
* Version Independent ID: 352fb2e9-2523-4d42-5c80-3199bf4e06ad
* Content: [Create a failover cluster](https://docs.microsoft.com/en-us/windows-server/failover-clustering/create-failover-cluster#create-a-failover-cluster-by-using-windows-powershell)
* Content Source: [WindowsServerDocs/failover-clustering/create-failover-cluster.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/create-failover-cluster.md)
* Product: **windows-server-threshold**
* Technology: **storage-failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by gbagate** [comment]
Hi Shawn,

I'm adding my finding here as well. 
My investigation found out this is the default design in this recent Windows Server 2019 Build 17733 and up.
So what you are experiencing is not related to DHCP setting on the network card but a new feature called "Distributed Network Name"
 Distributed Network Name (clusres.dll): A Distributed Network Name is a name in the Cluster that does not use a clustered IP Address.
 It is a name that is published in DNS using the IP Addresses of all the nodes in the Cluster. Client connectivity to this type name is reliant on DNS round robin.
 In Azure, this type name can be used in lieu of having the need for an Internal Load Balancer (ILB) address.
https://techcommunity.microsoft.com/t5/Failover-Clustering/Windows-Server-2016-2019-Cluster-Resource-Resource-Types/ba-p/372163

This is a relief as it removes lot of complexity regarding "Cluster Network Object" in Azure VM and everything is seamless to end-user.
 Additionally, the feature bring a new switch in the cluster cmdlet called : ManagementPointNetworkType which can take following value:
 1.Singleton: Use the traditional method of DHCP or static IP address.
 2.Distributed: Use a Distributed Network Name using node IP addresses.
 3.Automatic: Use detection. If running in Azure, use Distributed; if running on-premises, use Singleton (the default).
https://blogs.windows.com/windowsexperience/2018/08/14/announcing-windows-server-2019-insider-preview-build-17733/#W0YAxO8BfwBRbkzG.97

Suggestion:
 You can use below script to create the cluster as usual and follow the tutorial’steps or use the "Distributed Network Name" in Windows server 2019 and skip anything regarding cluster core name:
 New-Cluster -Name -Node ("","") –StaticAddress <n.n.n.n> -NoStorage -ManagementPointNetworkType Singleton

More information about Windows Server 2019 Failover Clustering New Features:
https://techcommunity.microsoft.com/t5/Failover-Clustering/Windows-Server-2019-Failover-Clustering-New-Features/ba-p/544029

##Documentation update:
I will make sure both documentations get updated but cannot provide any ETA for the same:
 1.https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sql/virtual-machines-windows-portal-sql-availability-group-tutorial#set-the-windows-server-failover-cluster-ip-address

2.https://docs.microsoft.com/en-us/windows-server/failover-clustering/create-failover-cluster

**Comment by ShawnPOWER** [comment]
I appreciate all the help, thank you!

SHAWN

**Comment by ShawnPOWER** [comment]
This one is resolved, thanks again for the help.
