### ISSUE TITLE
Server Core ??

### ISSUE THREAD

**Issue by Karr** [MicrosoftDocs/windowsserverdocs#3057]
Due to AZURE VM Size restraints (2 GB won't update Server) and Windows Server Update Service a question comes up.  Can we run AD FS PROXY in Server Core Mode ???  I don't see anything in the documentations regarding this matter.  This subject matter is very poorly covered in most Microsoft documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68bac2aa-024c-a014-eeaf-f28a44b31c5e
* Version Independent ID: 86c83819-91d6-c990-16f1-d05ebdf07b58
* Content: [AD FS 2016 Requirements](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-requirements)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/ad-fs-requirements.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/ad-fs-requirements.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
