### ISSUE TITLE
can not edit sshd_config_default 

### ISSUE THREAD

**Issue by amcorona** [MicrosoftDocs/windowsserverdocs#3059]
I can't change file permissions, can't replace the file as administrator.  I would like to just add PasswordAuthentication so I can only get in with a key.

This is windows 1903

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
