### ISSUE TITLE
SA Count tool cannot applicable for 16core server

### ISSUE THREAD

**Issue by meieda** [MicrosoftDocs/windowsserverdocs#3064]
license count for 16core server is wrong. for 16 core servers, 1 license should be counted but divided with 2 in "Required Windows Server 2-proc licenses (or sets of 16 cores):" field.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64ecde30-6c97-9426-978c-df2f018a88b8
* Version Independent ID: 46c06b02-9514-d7e4-90a1-3f2c8cae481f
* Content: [Azure Hybrid Benefit for Windows Server](https://docs.microsoft.com/en-us/windows-server/get-started/azure-hybrid-benefit#feedback)
* Content Source: [WindowsServerDocs/get-started/azure-hybrid-benefit.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/azure-hybrid-benefit.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by greg-lindsay** [comment]
This needs to be assigned to the topic owner, which is not me. I don't have permission to add an assignment.

**Comment by greg-lindsay** [comment]
@eross-msft can you look at issues 3981, 3926, and this one 3064.
