### ISSUE TITLE
Chromebook and Android based Microsoft RDP Shift Key Sticking Issue

### ISSUE THREAD

**Issue by WeirdExponent** [MicrosoftDocs/windowsserverdocs#3077]
Using Android based Microsoft RDP app.. the Shift key "sticks on" sometimes...  So when typing, it will sometimes stick, like when trying to type in  FreeMasons... it will come in as FREEmasons with the "second shift key hit resetting it to lower case...  Very frustrating when trying to reset passwords ;)

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
