### ISSUE TITLE
DNS example

### ISSUE THREAD

**Issue by Channveer** [MicrosoftDocs/windowsserverdocs#3085]
need more info on the dns with examples

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3159766e-0e7e-9e56-0cdb-a72a95af104a
* Version Independent ID: 752d61a9-6668-0e10-8efe-b763b345f261
* Content: [DNS and AD DS](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/dns-and-ad-ds#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/DNS-and-AD-DS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/DNS-and-AD-DS.md)
* Product: **windows-server-threshold**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
@Channveer What specifically?

**Comment by Channveer** [comment]
How dns is de-facto to adds explain it with a neat diagram

**Comment by MicrosoftGuyJFlo** [comment]
Ill add it to my backlog

**Comment by MicrosoftGuyJFlo** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
