### ISSUE TITLE
Identity Token No Longer Emitting Custom Claims

### ISSUE THREAD

**Issue by LastTribunal** [MicrosoftDocs/windowsserverdocs#3089]
This was working in the past, but seems like due to windows updates, the Id_token no longer returns any custom claims.  The access_token is fine..  Hence, this article is no longer valid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e04047c8-df0d-d752-afc1-0daa314e5d75
* Version Independent ID: 93cac62e-204f-b523-3751-51e420672555
* Content: [Customize claims to be emitted in id_token when using OpenID Connect or OAuth with AD FS 2016 or later](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/custom-id-tokens-in-ad-fs#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/Custom-Id-Tokens-in-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/Custom-Id-Tokens-in-AD-FS.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @anandyadavMSFT
* Microsoft Alias: **billmath**

**Comment by cristichiru** [comment]
Actually it does work, as long as you set the "Native application" **client identifier" to the same value in "Web API" **identifier**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
