### ISSUE TITLE
is the client id a static id or the clients actual client id?

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/windowsserverdocs#3105]
Set-AdfsAzureMfaTenant -TenantId &lt;tenant ID&gt; -ClientId 981f26a1-7f43-403b-a875-f8b09b8cd720

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae96cfcf-0a50-7e13-30c8-43e3730e184f
* Version Independent ID: 9d8ed7b7-eec6-1b95-40b8-24a13361f66d
* Content: [Configure AD FS 2016 and Azure MFA](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
