### ISSUE TITLE
Can someone please confirm the number of radius clients that are supported in Windows 2016 standard?

### ISSUE THREAD

**Issue by hmc25** [MicrosoftDocs/windowsserverdocs#3112]
THere is conflicting information. The following article states "With NPS in Windows Server 2016 Standard, you can configure a maximum of 50 RADIUS clients and a maximum of 2 remote RADIUS server groups. "

https://blogs.technet.microsoft.com/wsnetdoc/2017/01/26/download-the-new-network-policy-server-nps-technical-reference-for-windows-server-2016/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3604f4ae-1f55-b7e9-1239-8fe16555a82c
* Version Independent ID: 05543b0f-0bc5-5dc8-abb5-c360b1c6b5e0
* Content: [Network Policy Server (NPS)](https://docs.microsoft.com/en-us/windows-server/networking/technologies/nps/nps-top#feedback)
* Content Source: [WindowsServerDocs/networking/technologies/nps/nps-top.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/nps/nps-top.md)
* Product: **windows-server-threshold**
* Technology: **networking**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by v-andreyd** [comment]
[Network Policy Server (NPS) | Microsoft Learn](https://learn.microsoft.com/en-us/windows-server/networking/technologies/nps/nps-top)
With NPS in Windows Server 2016 Standard or Datacenter, you can configure **an unlimited number of RADIUS clients** and remote RADIUS server groups. In addition, you can configure RADIUS clients by specifying an IP address range.

WS2008 and 2012 standard: 50.
