### ISSUE TITLE
pattern examples either or

### ISSUE THREAD

**Issue by hmc25** [MicrosoftDocs/windowsserverdocs#3113]
Does anyone have or know of any examples how to use either/or pattern matching expressions for NPS in Windows 2016?

I would like to add multiple clients (at least 5) in a single NPS network policy and each client needs to be able to authenticate. 

`x y `  Matches either x or y.

https://docs.microsoft.com/en-us/windows-server/networking/technologies/nps/nps-crp-reg-expressions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be76aae5-dc86-e888-d16f-48d7e426874f
* Version Independent ID: 470cc71b-a76f-c24a-1a21-7b520cdd3f56
* Content: [Use Regular Expressions in NPS](https://docs.microsoft.com/en-us/windows-server/networking/technologies/nps/nps-crp-reg-expressions)
* Content Source: [WindowsServerDocs/networking/technologies/nps/nps-crp-reg-expressions.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/nps/nps-crp-reg-expressions.md)
* Product: **windows-server-threshold**
* Technology: **networking**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by JulioQc** [comment]
I use this for multiples IPs as follow:

^192.168.10.(2|25|101|102)$
