### ISSUE TITLE
Many links still pointing to Technet

### ISSUE THREAD

**Issue by MarcLafLigado** [MicrosoftDocs/windowsserverdocs#3133]
The links for the two commands Set-DhcpServerv4DnsSetting Set-DhcpServerDnsCredential still go to Technet. The proper links are https://docs.microsoft.com/en-us/powershell/module/dhcpserver/set-dhcpserverv4dnssetting?view=win10-ps and 
https://docs.microsoft.com/en-us/powershell/module/dhcpserver/set-dhcpserverdnscredential?view=win10-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe047b9e-1cef-6930-1473-a3e1a2a3b5f7
* Version Independent ID: 86bb5d90-1e18-f0a6-f688-d20d502c51a4
* Content: [Deploy DHCP Using Windows PowerShell](https://docs.microsoft.com/en-us/windows-server/networking/technologies/dhcp/dhcp-deploy-wps#feedback)
* Content Source: [WindowsServerDocs/networking/technologies/dhcp/dhcp-deploy-wps.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/dhcp/dhcp-deploy-wps.md)
* Product: **windows-server-threshold**
* Technology: **networking-dhcp**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by ingd** [comment]
Hey guys, any update about this case?

**Comment by illfated** [comment]
Sorry for not noticing this issue ticket before. The suggested solution looks good, so I will open a Pull Request to suggest this change in the doc article page.

**Comment by illfated** [comment]
Looks like I was able to find most of the pages, if not all of them, using both the search function on the main Windows PowerShell page as well as the filtering feature on the PS pages and other search options. Unfortunately, I could not find any links pointing to a replacement page for the TechNet Gallery page including the MS Word docx document. For now, that page only showed me a broken HTML page showing me only text and some text with links attached to them. Any CSS or page layout seems to be lost at the moment.

Other than that, I shall post the PR shortly, linking it back here for your approval.
