### ISSUE TITLE
RDS RDwebclient works internally and externally but HTML5 Client only works internally - Stuck on Opening Remote port when trying to launch Remote app 

### ISSUE THREAD

**Issue by Yas-90** [MicrosoftDocs/windowsserverdocs#3134]
Hi,

We are currently using Azure AD Proxy to allow our users to use the Remote Desktop application to remote into their office Pcs from home.

Login The RDWeb and starting a remote app works well internally and externally. 
Login to the Webclient however works internally and externally . However opening a remote app only works internally. When trying to open a published app externally its stuck on Opening Remote Port . No Event viewer entries on the Gateway at all. 

Setup: 
Gateway and Web-access on Server 2016-Server A
Session host, Connection Broker and licensing manager on Server 2016-Server B
Conditional access policy enabled for external users (Tried to disable it same outcome)
Azure AD Proxy used with custom Domain (Works well for RDWEB)

The only logs i have are from the Webclient when i record the session with Error:
Websocket Error recieved for UTL:------.com:443
The connection generated an internal expection with disconnect code=connectionBroken (8),Reason=websocket closed with code 1006

any help would be appreciated.
Thanks
Yasin

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
