### ISSUE TITLE
Incorrect details

### ISSUE THREAD

**Issue by dineshazure** [MicrosoftDocs/windowsserverdocs#3138]
5th step in Procedure topic under Add the VPN Server as a RADIUS Client, we have to enter the VPN server IP or FQDN but it is mentioned as NPS IP address. Please correct it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ab1fbbd-6f89-9fa6-1e82-185f0cbfcd03
* Version Independent ID: f3ae30f5-1e13-3295-9380-4b61df400d0d
* Content: [Install and Configure the NPS Server](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-nps#feedback)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-nps.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-nps.md)
* Product: **windows-server-threshold**
* Technology: **networking-ras**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
