### ISSUE TITLE
Please Clarify  Disable of WS-Trust Windows endpoints on the proxy

### ISSUE THREAD

**Issue by SB-o-matic** [MicrosoftDocs/windowsserverdocs#3145]
My confusion is around use of the word "Proxy". Are the PS commands to be run on AD FS servers or Web Application Proxy servers? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a834de4-c696-4599-6ab2-94ae03d31471
* Version Independent ID: 78658bfd-8bcc-0d71-5139-77733f1a795e
* Content: [Best Practices for securing AD FS and Web Application Proxy](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/best-practices-securing-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Best-Practices-Securing-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Best-Practices-Securing-AD-FS.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Johnnycash612** [comment]
Same here ,got an alert from Azure AD connect health alert on this. But there's no adfs powershell on proxy to execute it.

**Comment by joshmalik** [comment]
You configure that on the ADFS master server but 'disable on the proxy' means that those endpoints aren't available from the proxy server i.e. externally.

**Comment by SB-o-matic** [comment]
@joshmalik, so how then do you run the PS on the ADFS server without disabled the endpoints on the ADFS server itself but just on the proxies.

Microsoft, please assist. It's been 2 months.

**Comment by joshmalik** [comment]
With the commands below:

Set-AdfsEndpoint -TargetAddressPath /adfs/services/trust/2005/windowstransport -Proxy $false 
Set-AdfsEndpoint -TargetAddressPath /adfs/services/trust/13/windowstransport -Proxy $false

You don't have to use PowerShell to do this, you can disable the endpoints on the primary server via the ADFS management console if you so wish.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 3121 -b #assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
