### ISSUE TITLE
hard drive labeled as unknown

### ISSUE THREAD

**Issue by zombiemodz** [MicrosoftDocs/windowsserverdocs#3154]
My hard drive is labeled as unknown in the disk management program, what do I do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aed88c8d-c15e-9dad-4cf4-9cc92e625f41
* Version Independent ID: 3ba55b69-bea2-a674-d08f-e93a03de1ffa
* Content: [Initialize new disks](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/initialize-new-disks#feedback)
* Content Source: [WindowsServerDocs/storage/disk-management/initialize-new-disks.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/initialize-new-disks.md)
* Product: **windows-server-threshold**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
