### ISSUE TITLE
Correction: Change a Dynamic Disk Back to Basic

### ISSUE THREAD

**Issue by samh2221** [MicrosoftDocs/windowsserverdocs#3158]
Step 5 on this page results in a syntax error. I believe the correct input is:
"5. At the DISKPART prompt, type detail disk"
Cheers Sam

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97b90b12-6f66-7b7e-9df4-b3ef4cf9119f
* Version Independent ID: 88441e2c-3c34-ffcb-669c-98113c9523b7
* Content: [Change a dynamic disk back to a basic disk](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/change-a-dynamic-disk-back-to-a-basic-disk#feedback)
* Content Source: [WindowsServerDocs/storage/disk-management/change-a-dynamic-disk-back-to-a-basic-disk.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/change-a-dynamic-disk-back-to-a-basic-disk.md)
* Product: **windows-server-threshold**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Resolved in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/36b6d67455a992e0cee8eb05f5fb12bfd59cded0
(Private Repo PR # 3661)

**Comment by illfated** [comment]
#please-close

**Comment by samh2221** [comment]
Ack/Agree, Thank you
