### ISSUE TITLE
Install language

### ISSUE THREAD

**Issue by tene666** [MicrosoftDocs/windowsserverdocs#3162]
Hello, is there a way to affect UI language for installation? Right now I cannot install, as EULA is showing in a language that I do not understand that well (German - base language of installed OS, OS UI is (mostly) displayed in English).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe84fb4b-3420-bc1e-6a1d-b64ecc56fc5e
* Version Independent ID: f089767e-4613-d595-a0ee-0dab012724a1
* Content: [Install Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/install)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/deploy/install.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/deploy/install.md)
* Product: **windows-server-threshold**
* Technology: **manage**
* GitHub Login: @jwwool
* Microsoft Alias: **jeffrew**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
