### ISSUE TITLE
Additional connection example

### ISSUE THREAD

**Issue by jamie-tillman** [MicrosoftDocs/windowsserverdocs#3171]
In bullet 6, why not mention that you can connect directly to the VM that was created in bullet 4 by using this command?:
```vmconnect ($env:ComputerName) Win10VM```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 777f1c2d-8e47-f406-fe3b-466b93ca1520
* Version Independent ID: 6e87080a-cfcc-38ee-e675-e583365b5f3a
* Content: [Create a virtual machine in Hyper-V](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/get-started/create-a-virtual-machine-in-hyper-v#feedback)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/get-started/Create-a-virtual-machine-in-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/get-started/Create-a-virtual-machine-in-Hyper-V.md)
* Service: **na**
* Product: **windows-server-threshold**
* Technology: **compute-hyper-v**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
