### ISSUE TITLE
No documentation of options

### ISSUE THREAD

**Issue by cpowers534at** [MicrosoftDocs/windowsserverdocs#3175]
There is no documentation of the options.  Both this documentation and the text emitted by the tool include an opaque "[options]" without any further details.  I'm reduced to cargo-culting a few specific things that I've seen in various online sources.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 046b0cec-308c-697e-f3fa-c6ebfb18cfae
* Version Independent ID: c4874bed-0689-809d-0ec1-3be75802779a
* Content: [logman start](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/logman-start-stop)
* Content Source: [WindowsServerDocs/administration/windows-commands/logman-start-stop.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/logman-start-stop.md)
* Product: **windows-server-threshold**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
