### ISSUE TITLE
image size very small

### ISSUE THREAD

**Issue by LeonB87** [MicrosoftDocs/windowsserverdocs#3178]
The diagram at the top that shows the workflow process for the different scenarios is very small and cannot be clicked or enlarged.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ae99a07-be14-63a1-d5bb-1e92f9cde0b7
* Version Independent ID: ed219e40-9a0e-794b-110d-d82418d456e7
* Content: [Deploy Always On VPN](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-deployment#feedback)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-deployment.md)
* Product: **windows-server-threshold**
* Technology: **networking-ras**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by aamer-s** [comment]
The writing on the image is too small - not readable. Enlarging the image does not help.

**Comment by tmmjelde** [comment]
I found this image which is better:
https://www.advitum.se/wp-content/uploads/2018/06/always-on-vpn-deployment-workflow.png

**Comment by lXbalanque** [comment]
@tmmjelde Unfortunately, due to geolocation blocking, I'm unable to see that image.

Can someone from the documentation team please update the image or at least allow for a blown up version for us to click on? I can't make anything out from that screenshot. Thank you!

**Comment by illfated** [comment]
I am not a team member, but I will try to help you out.

1. Local image uploaded to Github:

![always-on-vpn-deployment-workflow](https://user-images.githubusercontent.com/38162891/67437886-4a5cd780-f5f2-11e9-9f0a-7ba211037ae3.png)

2. image uploaded to imgur.com : https://i.imgur.com/CcEzpr6.png

**Comment by illfated** [comment]
There is already a larger size image in the GitHub WindowsServerDocs repository:
- https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/media/Always-On-Vpn/always-on-vpn-deployment-workflow.png

![Flow chart of the Always On VPN deployment workflow](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/media/Always-On-Vpn/always-on-vpn-deployment-workflow.png?raw=true)

The actual issue with this image in that page is that it only links to itself, not to the larger image (which it used to do 2 years ago). I will suggest linking the larger image instead via a Pull Request to the page in question.

**Comment by illfated** [comment]
(Ref. duplicate ticket in issue page #3474 )

**Comment by shortpatti** [comment]
Unfortunately, the writer who replaced me didn't understand the HTML tags so they removed them and now all you see in the topic is the "thumbnail" image and you can't click on it for the larger image. Sad, really!

It's just unfortunate that a former employee has to help straighten this out now after almost 2 years after the topic was updated/improved.

And I really wish they would remove me from these topics that I haven't worked on in almost 2 years!!!! But, since it looks like they don't have anyone working on this topic full-time they're just leaving the metadata "as-is."

**Comment by illfated** [comment]
You have my sympathies. Thank you so much for posting, I was really wondering what the status of your relationship with Microsoft ServerDocs is these days. Glad to see that you are aware of the situation and are able to inform us in your spare time. Thank you again. 👍

**Comment by shortpatti** [comment]
No problem!  I haven't been with Microsoft since Nov 2018.

Good luck in getting help with the server docs :)  I really do feel for you IT Pros working on these products.

**Comment by illfated** [comment]
Very good. I have now opened up the PR #3943 to remedy the situation here, but I also wish I could contribute with metadata updates, which probably is quite a chore for those few remaining team members.

**Comment by shortpatti** [comment]
It's up to the Microsoft employee who owns the content to update the Microsoft alias and the GitHub login, but it looks like there is NO employee who has taken ownership of this topic or other topics I owned.

**Comment by illfated** [comment]
Yes, I see what you mean. Jaime Ondrusek has pointed out to me (and others) that some of his work is taken over by others, but the metadata still needs updating.

Thank you again for replying, it feels to me almost as if I have been given the chance to talk to a famous person (which you somehow still are, at least in the MS Docs community). 😄

**Comment by shortpatti** [comment]
You're welcome.  Famous?  LOL  That's funny :D

**Comment by illfated** [comment]
Well, I did mean that it is sort of the feeling it gives me. Any person with their name in international publications are notable to me and (at least to me) requires respect of some kind. That is the kind of fame I am talking about, I guess I also have some respect for people working with major brand names, especially when their name is spread around in various sites on the internet or other media, as long as they are not known for anything bad for the end users.

**Comment by illfated** [comment]
(Ref. #3886 )
