### ISSUE TITLE
RRAS for Always-On VPN and PDCs

### ISSUE THREAD

**Issue by cstone-f12** [MicrosoftDocs/windowsserverdocs#3191]
I have encountered some issues setting up RRAS on a PDC, and I see nothing in Microsoft's documentation explicitly stating that this should not be done. However, I have seen warnings not to do this on several private websites, but the most recent of those was from September 2011, or eight years ago. What is the official answer on this, and can this page be updated to include why/why not to setup RRAS on the PDC?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53ca42af-1e8b-7f41-a3b9-de1cb20d895d
* Version Independent ID: dc054edd-c916-28ba-78d2-ee7b10635201
* Content: [Configure the Remote Access Server for Always On VPN](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-ras#feedback)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-ras.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-ras.md)
* Product: **windows-server-threshold**
* Technology: **networking-ras**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by cstone-f12** [comment]
I will note that, per the setup in this page, RRAS is being used for VPN-only config.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
