### ISSUE TITLE
Typo in example command?

### ISSUE THREAD

**Issue by mliben** [MicrosoftDocs/windowsserverdocs#3195]
This document differs from another on the same subject: https://support.microsoft.com/en-us/help/325850/how-to-use-netdom-exe-to-reset-machine-account-passwords-of-a-windows.

This document specifies the parameter /passwordd (note the extra d in password). The other document specifies a shorter parameter name, /pd.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7763ee6f-e35f-8448-bad0-2fac7a80da50
* Version Independent ID: c432bbbf-7f7a-231e-5360-97f2b7797439
* Content: [AD Forest Recovery - Resetting the computer account on the DC](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/ad-forest-recovery-reset-computer-account-dc)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/AD-Forest-Recovery-Reset-Computer-Account-DC.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/manage/AD-Forest-Recovery-Reset-Computer-Account-DC.md)
* Product: **windows-server-threshold**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
