### ISSUE TITLE
No audio coming out of my iPad

### ISSUE THREAD

**Issue by MaurGi** [MicrosoftDocs/windowsserverdocs#3199]
There is no audio coming out, the driver is set to remote audio but nothing.
I can hear audio if I use Jump remote desktop but not with the Microsoft RDP client - 
I am an employee and can repro if you need to.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
