### ISSUE TITLE
Microsoft Remote Desktop on Chromebook-Shift key takes more than 1 sec to release

### ISSUE THREAD

**Issue by KKallium** [MicrosoftDocs/windowsserverdocs#3200]
Hi,
Microsoft Remote Desktop on Chromebook is working perfectly, except the Shift key.
Within the application in MS-Windows environment, upon select Shift + Key, it needs more than 1 sec to release. e.g. If we type Shell, we will type Shift+S followed by hell, it will appears SHELL. We need to type Shift+S, wait for 1 second, followed by hell. This is especially frustrating for password entry when it only appear *****.

Please advice.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
