### ISSUE TITLE
Misplaced article paragraph?

### ISSUE THREAD

**Issue by Weithenn** [MicrosoftDocs/windowsserverdocs#3201]
I am not sure why "Adding an Azure VM connected to your network via ExpressRoute" in this article. Because this is article focus Server-to-Server Replica, there is no Azure VM and ExpressRouote. thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f58b836-4eb3-562a-9ca1-92202c267db0
* Version Independent ID: f8674fad-5571-57e1-8afd-cf21cb044525
* Content: [Server-to-server storage replication](https://docs.microsoft.com/en-us/windows-server/storage/storage-replica/server-to-server-storage-replication#feedback)
* Content Source: [WindowsServerDocs/storage/storage-replica/server-to-server-storage-replication.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-replica/server-to-server-storage-replication.md)
* Product: **windows-server-threshold**
* Technology: **storage-replica**
* GitHub Login: @nedpyle
* Microsoft Alias: **nedpyle**

**Comment by nedpyle** [comment]
Because an Azure IaaS VM is a server. This step is necessary for customers who wish to use Azure as an secondary site.

**Comment by Weithenn** [comment]
Thank you for your quick reply and answering that.
