### ISSUE TITLE
Capitalize Letter

### ISSUE THREAD

**Issue by melkadze** [MicrosoftDocs/windowsserverdocs#3202]
Immediately under the subheading "2.3. Configure WSUS computer groups", the first letter of the first sentence should be capitalized.

The word "computer" should become "Computer".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80868bcd-a401-60a3-16b1-7817f4320dd1
* Version Independent ID: a7e9dc84-915a-9895-cf0d-0a0e89a062fe
* Content: [Step 2 - Configure WSUS](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/deploy/2-configure-wsus#feedback)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/deploy/2-configure-wsus.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/deploy/2-configure-wsus.md)
* Product: **windows-server-threshold**
* Technology: **manage-wsus**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
(ref. #4842 )

**Comment by illfated** [comment]
#please-close
