### ISSUE TITLE
Correct settings in screenshots

### ISSUE THREAD

**Issue by mstb5150** [MicrosoftDocs/windowsserverdocs#3204]
The screenshots are captioned to reflect disabled settings for a protocol but they are all set to Zero. If it's disabled - DisabledbyDefault should be 1 according to the previous instructions.
The screenshots show the protocol enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38fcd9dd-91c8-e79b-5f4d-28a435a8ada8
* Version Independent ID: 0d79a0c8-0b73-c783-4d5c-b107d24acf55
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server-threshold**
* Technology: **security-tls-ssl**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by brink668** [comment]
Agreed, I noticed this as well.  The screenshots are incorrect.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
