### ISSUE TITLE
Upgrading on same virtual hardware vs new virtual hardware

### ISSUE THREAD

**Issue by SamErde** [MicrosoftDocs/windowsserverdocs#3211]
When cluster nodes are virtual machines, is there any reason that these steps couldn't be followed using pre-staged temporary hardware in lieu of repeated OS rebuilds on the same VMs? If supported, this would save a large amount of work to be done during maintenance windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27fbfa55-039a-59bb-c1da-4cd7123d3e45
* Version Independent ID: 4fd712fd-77b3-a2a1-d74b-d410349647f5
* Content: [Upgrading Failover Clusters Using the Same Hardware](https://docs.microsoft.com/en-us/windows-server/failover-clustering/upgrade-option-same-hardware#feedback)
* Content Source: [WindowsServerDocs/failover-clustering/Upgrade-Option-Same-Hardware.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/Upgrade-Option-Same-Hardware.md)
* Product: **windows-server-threshold**
* Technology: **failover-clustering**
* GitHub Login: @JohnMarlin-MSFT

**Comment by SturdyErde** [comment]
Possible sidebar for this article. My Twitter Q&A with John Marlin indicates that it does not need to be the same hardware when virtualized. https://twitter.com/JohnMarlin_MSFT/status/1161346781168275456

**Comment by JohnMarlin-MSFT** [comment]
Any reason why all these are getting opened and assigned to me?

Thanks,
John Marlin | HAS PM
