### ISSUE TITLE
diskspd example is missing the -j parameter

### ISSUE THREAD

**Issue by eponerine** [MicrosoftDocs/windowsserverdocs#3227]
You cannot run `-i` without also specifying `-j`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f58b836-4eb3-562a-9ca1-92202c267db0
* Version Independent ID: f8674fad-5571-57e1-8afd-cf21cb044525
* Content: [Server-to-server storage replication](https://docs.microsoft.com/en-us/windows-server/storage/storage-replica/server-to-server-storage-replication#feedback)
* Content Source: [WindowsServerDocs/storage/storage-replica/server-to-server-storage-replication.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-replica/server-to-server-storage-replication.md)
* Product: **windows-server-threshold**
* Technology: **storage-replica**
* GitHub Login: @nedpyle
* Microsoft Alias: **nedpyle**

**Comment by nedpyle** [comment]
@steved0x this content was fixed a year ago why is this reopened?

**Comment by eponerine** [comment]
@nedpyle - I got a dozen notifications like this today from @steved0x on a bunch of other Github issues.

**Comment by nedpyle** [comment]
@eponerine Yep. All of mine were referencing items fixed 6-18 months ago or for products I don't own, with no action needed when I reviewed them. I reported into my Docs folks to see what's going on, they told me hold tight. Thanks for the reply, regardless

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
