### ISSUE TITLE
Broken Links - 404

### ISSUE THREAD

**Issue by aisog** [MicrosoftDocs/windowsserverdocs#3230]
In the section with links for SATA, SAS and NVMe:
"Contact your solution vendor for info about whether your hardware supports Windows updating the drive firmware. Here are links to the various requirements:"
Each link goes to 404 Page not found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84104ccc-94a6-5d06-d300-b3c8cc707075
* Version Independent ID: a298fd72-2fd2-ee19-4992-d11b13797523
* Content: [Updating drive firmware](https://docs.microsoft.com/en-us/windows-server/storage/update-firmware#feedback)
* Content Source: [WindowsServerDocs/storage/update-firmware.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/update-firmware.md)
* Product: **windows-server-threshold**
* Technology: **storage-spaces**
* GitHub Login: @toklima
* Microsoft Alias: **toklima**

**Comment by CoMMyCZ** [comment]
Links still broken / after 3 months...

**Comment by illfated** [comment]
Thank you for pointing this out, I missed out on this ticket when it was posted back in August.
Could you help me determine if the following link(s) work as a replacement?
- https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/storage-spaces-direct-hardware-requirements#drives
- https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/storage-spaces-direct-hardware-requirements#minimum-number-of-drives-excludes-boot-drive

(both links point to the same page, the second link is to the next linked section or chapter.

**Comment by aisog** [comment]
The section with broken links referring to the Firmware update and Download & Activate section  :
"Contact your solution vendor for info about whether your hardware supports Windows updating the drive firmware. Here are links to the various requirements:

SATA: Device.Storage.Hd.Sata - in the [If Implemented] Firmware Download & Activate section
SAS: Device.Storage.Hd.Sas - in the [If Implemented] Firmware Download & Activate section
NVMe: Device.Storage.ControllerDrive.NVMe - in sections 5.7 and 5.8. "

The topic in this section is not related to S2D Hard Drives Requirements

**Comment by illfated** [comment]
OK, so in other words, my suggested links to that page will not be a proper replacement, I presume.

Have you tried to find what the content should be, using web search with buffered results? Do you have any suggestions where to look, to find the proper pages?

**Comment by illfated** [comment]
Resolved in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/b679b452d9c3a2a38af885a356463fa77308beb8 (file https://github.com/MicrosoftDocs/windowsserverdocs/commit/b679b452d9c3a2a38af885a356463fa77308beb8#diff-2808a9145bf473018f194d5971d8ffe4ea71d2bd4e74c7797e71897711dc1185 ).

**Comment by illfated** [comment]
#please-close
