### ISSUE TITLE
General Purpose File Server refers to itself as Hyper-V Cluster

### ISSUE THREAD

**Issue by eponerine** [MicrosoftDocs/windowsserverdocs#3233]
Link to section:
https://docs.microsoft.com/en-us/windows-server/storage/storage-replica/stretch-cluster-replication-using-shared-storage#powershell-method

Section 2 under PowerShell refers to this General Purpose File Server as "Create the Hyper-V compute cluster"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e81b5767-e7e7-749f-2656-246a34882f5d
* Version Independent ID: 3a1235a0-3006-7855-0dce-5dcdf8160f91
* Content: [Stretch Cluster Replication Using Shared Storage](https://docs.microsoft.com/en-us/windows-server/storage/storage-replica/stretch-cluster-replication-using-shared-storage#powershell-method)
* Content Source: [WindowsServerDocs/storage/storage-replica/Stretch-Cluster-Replication-Using-Shared-Storage.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-replica/Stretch-Cluster-Replication-Using-Shared-Storage.md)
* Product: **windows-server-threshold**
* Technology: **storage-replica**
* GitHub Login: @nedpyle
* Microsoft Alias: **nedpyle**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
