### ISSUE TITLE
Disk 2 removable (U:) No Media

### ISSUE THREAD

**Issue by rad1959** [MicrosoftDocs/windowsserverdocs#3234]
Ok, disk shows up in disk manager with the above identification.  Via disk manager I can change the drive number, put it into a NTFS folder, as far as being able to use the disk, there are no options in disk manager except Change drive letter, properties, and help.  Nothing else.  In properties you get,  Disk:   Disk 2,  Type:  Removable (U:),  Status:  No Media,   Partition Style:  MBR Master Boot Record,  Capacity, Unallocated Space, and Reserved Space all show 0, zip, nada, nothing.  This is a 128 GB SSD M.2 Sata drive.
It crashed during a software update.  How do I get this drive back, it does not show up in file manager.  You can only see it in disk manager.  There has to be some way to force format this thing.  If I try to access the drive as an administrator from the cmd console I get drive not ready, DOS Sees the drive, but forget trying to do anything with it using chkdsk, format, dir, cd:\ U:\ That is another command that says its not ready.  I am lost with this????  Is it time to expose the chip to a strong magnetic field???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aed88c8d-c15e-9dad-4cf4-9cc92e625f41
* Version Independent ID: 3ba55b69-bea2-a674-d08f-e93a03de1ffa
* Content: [Initialize new disks](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/initialize-new-disks#feedback)
* Content Source: [WindowsServerDocs/storage/disk-management/initialize-new-disks.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/initialize-new-disks.md)
* Product: **windows-server-threshold**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
