### ISSUE TITLE
packages.microsoft.com - broken ubuntu 18.04 bionic amd64 repository

### ISSUE THREAD

**Issue by saphireee** [MicrosoftDocs/windowsserverdocs#3236]
It seems that repository packages.microsoft.com is broken again -> apt update:

Get:14 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages [66,6 kB]
Err:14 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
  File has unexpected size (66537 != 66619). Mirror sync in progress? [IP: 145.237.3.4 8080]
  Hashes of expected file:
   - Filesize:66619 [weak]
   - SHA512:4754fea65f57f35fc52e332a6d5cddaf65ea00bbd9e9f428d3a4325c1ac26856190ae82022cdb7a41bf1337e5c7fb1a429933bae9817bacaa8a5186c2aae9f1b
   - SHA256:f971467de90380c9920956be80642d7f6eb0e75042822ea4537d9f5190e13d9f
   - SHA1:0f8e0e8ac649a20ef2029c9f4ffc6bc1ef559257 [weak]
   - MD5Sum:8aa7d0d41b74ea8b84a434a726ea92fa [weak]
  Release file created at: Tue, 20 Aug 2019 22:43:21 +0000

But Packages.bz2 really is 66537 size, so either Release has proper hashes or files are not good. Please correct this.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
