### ISSUE TITLE
Whats the Point

### ISSUE THREAD

**Issue by amontaleone** [MicrosoftDocs/windowsserverdocs#3241]
So what is the point... I can only think of a scenario where the company is brand new and there is no network for the campus.. but your tasked with creating an environment of computers before the wiring is in.. ??  I have never used this feature.. I would love to hear of actual scenarios where this is useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 897789a9-e44e-c070-f1d0-ccd202820aff
* Version Independent ID: a0e06bde-8796-ffbd-3d07-fa8afbec4674
* Content: [DirectAccess Offline Domain Join](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/directaccess/directaccess-offline-domain-join#feedback)
* Content Source: [WindowsServerDocs/remote/remote-access/directaccess/DirectAccess-Offline-Domain-Join.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/directaccess/DirectAccess-Offline-Domain-Join.md)
* Product: **windows-server-threshold**
* Technology: **networking-da**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by Absoblogginlutely** [comment]
When prepping a machine for DirectAccess (as per this section of the documentation) you can have the machine ready with the appropriate group policies deployed without it being on the corporate network. Ship this to an enduser (or get them to run the app and you are poorman provisioning DirectAccess. Alternatively you can provision lots of machines this way without a broadcast storm of machines all trying to connect and join AD at the same time. See https://dirteam.com/sander/2012/09/17/new-features-in-active-directory-domain-services-in-windows-server-2012-part-19-offline-domain-join-improvements/ for an old document with more information.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
