### ISSUE TITLE
msSVSadmPwd - Wrong Attribute for LAPS?

### ISSUE THREAD

**Issue by JoeDibley** [MicrosoftDocs/windowsserverdocs#3242]
I've been reading through a bunch of stuff recently and in this [PAW Post](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md) and on a [Blog Post](https://blogs.technet.microsoft.com/poshchap/2015/07/03/the-joy-of/) I have found references to msSVSadmPwd where I am sure it should be msMCSadmpwd (ms-mcs-admpwd) for the LAPS password. 

![image](https://user-images.githubusercontent.com/23236842/63514444-8388a680-c4e0-11e9-9ad5-4367a88f1a45.png)

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
