### ISSUE TITLE
cmdkey /list should show the user accounts that the credentials have been applied to

### ISSUE THREAD

**Issue by luffjr** [MicrosoftDocs/windowsserverdocs#3248]
This issue is related to #2141 - because the credentials are on a per-user basis, the ability to list the users that a credential has been provided to is required.

**Comment by illfated** [comment]
Ref. issue linked above:

- ID: caebc8e0-4c03-4714-b7a8-3d55ef0f6ab1
- Version Independent ID: 5a7b7ad8-8f55-fb3e-54ee-b8aff333b7c7
- Content: [cmdkey](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cmdkey)
- Content Source: [WindowsServerDocs/administration/windows-commands/cmdkey.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/cmdkey.md)
- Product: **windows-server-threshold**
- GitHub Login: @coreyp-at-msft
- Microsoft Alias: **coreyp**
