### ISSUE TITLE
"eg" isn't a word

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/windowsserverdocs#3249]
You might mean "for example".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39982e20-024e-01a1-22bd-77ae25d58979
* Version Independent ID: 60db3fbe-72a7-706a-14b2-83f0d3a24ece
* Content: [Build Plug-ins with AD FS 2019 Risk Assessment Model](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/ad-fs-risk-assessment-model#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/ad-fs-risk-assessment-model.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/ad-fs-risk-assessment-model.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Good point. It is not even written as the initials for "exempli gratia" (e.g.), but more like the Norwegian Nynorsk word "eg" (nn-no) meaning "I" (me, myself).

Never mind the details. I will create a PR for it. Sorry it has taken so long. Sometimes I wish I had at least 1 twin brother with the same mindset as me.

**Comment by illfated** [comment]
There you go. PR #5153 is ready for review, comments, and suggestions. Better late than never, eh? Oh well. 🙂

**Comment by jordanmills** [comment]
I know the feeling about having a twin.  I'm familiar with the Latin, but "e.g." is not a drop in replacement for the word "example".  I was not aware of the Norwegian Nynorsk.  Thank you for the quick action once you were able to get to this!
