### ISSUE TITLE
HTML file not display correct

### ISSUE THREAD

**Issue by SpaceTimer** [MicrosoftDocs/windowsserverdocs#3250]
Section 2: Create the provider, Step 13: Now for the resource file containing the html fragment. the file content not dispaly correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c205a6b-d760-85c3-8307-62300e4a789e
* Version Independent ID: 84266aa7-287f-9b12-21be-70b1bc8d429d
* Content: [Build a Custom Authentication Method for AD FS in Windows Server](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/ad-fs-build-custom-auth-method#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/ad-fs-build-custom-auth-method.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/ad-fs-build-custom-auth-method.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
