### ISSUE TITLE
Shortcut key for full screen

### ISSUE THREAD

**Issue by Shashwat-Jain** [MicrosoftDocs/windowsserverdocs#3254]
Do we have a keyboard shortcut key to switch between fullscreen for remote desktop?
(Something similar to ctrl+ alt+ break on the existing mstsc for remote connections)

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
