### ISSUE TITLE
Windows 2019 Support

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/windowsserverdocs#3257]
This page needs updated with references to Windows Server 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60832ce0-4687-b723-afd3-0fba3fec54d7
* Version Independent ID: 28ce8f7a-0280-65e3-3fe5-d07cdfd6405f
* Content: [Cluster Operating System Rolling Upgrade](https://docs.microsoft.com/en-us/windows-server/failover-clustering/cluster-operating-system-rolling-upgrade)
* Content Source: [WindowsServerDocs/failover-clustering/Cluster-Operating-System-Rolling-Upgrade.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/Cluster-Operating-System-Rolling-Upgrade.md)
* Product: **windows-server-threshold**
* Technology: **storage-failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 3250 -b #assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
