### ISSUE TITLE
minor tipo

### ISSUE THREAD

**Issue by AntoineJo** [MicrosoftDocs/windowsserverdocs#3262]
Section Additional Details & consideration
point 3:
When Windows Integrated Authentication (WIA) is performed (for example, when users try to access a corporate application on a domain-joined machine from intranet and AD FS administrator has configured the authentication policy to use WIA for intranet), UPN **isused** for authentication. If you have configured any claim rules for the relying parties for alternate login ID feature, you should make sure those rules are still valid in the WIA case.

**issused** should be **is used**

**Comment by illfated** [comment]
https://github.com/MicrosoftDocs/windowsserverdocs/search?q=issused&type=code
"We couldn’t find any code matching 'issused' in MicrosoftDocs/windowsserverdocs"

Looks like this typo issue must have been sorted internally by the MS Docs team, since there is no public commit containing that word.

Handling this ticket as resolved/no longer applicable.

#please-close

**Comment by AntoineJo** [comment]
https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configuring-alternate-login-id#additional-details--considerations
it means that Bing is better than Github to search ;), look at the third "point"

**Comment by AntoineJo** [comment]
![Screenshot 2021-01-18 125550](https://user-images.githubusercontent.com/48328018/104912418-836a3000-598c-11eb-8a4e-3208606037a7.png)

**Comment by AntoineJo** [comment]
https://github.com/MicrosoftDocs/windowsserverdocs/search?q=isused&type=code
@illfated you made a mistake in your search due to a mistake in my original post, sorry

**Comment by illfated** [comment]
> [MicrosoftDocs/windowsserverdocs/search?q=isused&type=code](https://github.com/MicrosoftDocs/windowsserverdocs/search?q=isused&type=code)
> @illfated you made a mistake in your search due to a mistake in my original post, sorry

@AntoineJo : Very well. Good of you to look up the correct typo spelling. I will create a Pull Request to correct the typo. Thank you.

**Comment by illfated** [comment]
(ref. #5216 )
