### ISSUE TITLE
Uploading/dowloading files requires undocumented port to be open

### ISSUE THREAD

**Issue by DumboJetEngine** [MicrosoftDocs/windowsserverdocs#3265]
I cannot upload files on a Windows server with Windows Admin Center.
There is nothing documented about this and after some time of investigation, I found out that allowing all incoming TCP traffic solves the problem. But I did not manage to find the exact port that needs to be open.
Here: https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/support/troubleshooting
....it mentions the TCP 5985 port, but it doesn't seem to be it...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e5fc70f-7d73-a27a-dd16-caf965c849d0
* Version Independent ID: c0c463f4-52f4-3582-87fd-edd2c5263871
* Content: [Windows Admin Center Common Troubleshooting Steps](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/support/troubleshooting#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/support/troubleshooting.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/support/troubleshooting.md)
* Product: **windows-server-threshold**
* Technology: **manage**
* GitHub Login: @jwwool
* Microsoft Alias: **jeffrew**

**Comment by DumboJetEngine** [comment]
OK, I found it!
It is port 445!

**Comment by jwwool** [comment]
This was recently added to the documentation [here](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/prepare-environment#port-configuration-on-the-target-server).

**Comment by DumboJetEngine** [comment]
OK, good.
I have missed that.
Maybe it should be in the "Common troubleshooting steps" too? Because I feel that this is the only thing that does not work out-of-the-box. I would definitely don't need any documentation, if it wasn't for this "problem".

There is even an YouTube video from MS on how to use the upload feature on W.A.C., but it says nothing about this port.

Also, I guess it would make people's lives easier if there was a more detailed error message in W.A.C. about what may be wrong when file upload/download fails, but that's another story for another git repository...

Feel free to close this issue. :)
