### ISSUE TITLE
Headers twice in Require-Permissions table 

### ISSUE THREAD

**Issue by Takescake** [MicrosoftDocs/windowsserverdocs#3267]
https://docs.microsoft.com/en-us/windows-server/storage/folder-redirection/deploy-folder-redirection#required-permissions-for-the-file-share-hosting-redirected-folders has headers twice

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f26ab8e-4e08-c397-6b98-8a1937b9752a
* Version Independent ID: 7aeee835-12a9-73c3-b1f2-8cf9855c3719
* Content: [Deploy Folder Redirection with Offline Files](https://docs.microsoft.com/en-us/windows-server/storage/folder-redirection/deploy-folder-redirection#required-permissions-for-the-file-share-hosting-redirected-folders)
* Content Source: [WindowsServerDocs/storage/folder-redirection/deploy-folder-redirection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/folder-redirection/deploy-folder-redirection.md)
* Product: **windows-server-threshold**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
