### ISSUE TITLE
No Change Documentation for version 10.1.1107.0

### ISSUE THREAD

**Issue by EzraWard** [MicrosoftDocs/windowsserverdocs#3271]
Noticed there was an update to the app, but this page lacks documentation for the changes in version 10.1.1107.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e60920-eb48-3d03-0cbb-edf4f0afd7e1
* Version Independent ID: 8b50ceec-5da0-b064-3fa9-bfe408bef243
* Content: [What's new in the Windows Store client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windows-whatsnew)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windows-whatsnew.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windows-whatsnew.md)
* Product: **windows-server-threshold**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by ClaudioTorresAcevedo** [comment]
Having huge problems with this client on windows 1903 at least. Disconnects and black screen on session randomly. The html5 client works perfectly on the same machine on for exampe edge beta.

**Comment by EzraWard** [comment]
Looks like this no longer an issue. I see documentation for the version in question. Closing.
