### ISSUE TITLE
Typo - "truck" instead of "trunk"

### ISSUE THREAD

**Issue by eponerine** [MicrosoftDocs/windowsserverdocs#3272]
"VLAN ID on truck" is incorrectly labeled in the table header - https://docs.microsoft.com/en-us/windows-server/networking/sdn/plan/plan-a-software-defined-network-infrastructure#sample-network-topology

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaef2f0a-a246-ca79-59ba-1def1605a883
* Version Independent ID: 659e4847-2154-4ce4-893d-0f9f8eb1620a
* Content: [Plan a Software Defined Network Infrastructure](https://docs.microsoft.com/en-us/windows-server/networking/sdn/plan/plan-a-software-defined-network-infrastructure#sample-network-topology)
* Content Source: [WindowsServerDocs/networking/sdn/plan/Plan-a-Software-Defined-Network-Infrastructure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/sdn/plan/Plan-a-Software-Defined-Network-Infrastructure.md)
* Service: **virtual-network**
* Product: **windows-server-threshold**
* Technology: **networking-sdn**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
