### ISSUE TITLE
How to use findstr to return line number + file name without the matched string?

### ISSUE THREAD

**Issue by surfmuggle** [MicrosoftDocs/windowsserverdocs#3283]
I want to have a list of all files and line numbers that match the string "select " ignoring case. 

To search in all php-files in all sub directories i used this command

    findstr /s /i /n /m "\<select\> " *.php > c:\dev\php\search_select3.txt

This returns a list of filenames and pipes them to search_select3.txt but the line number is missing.  
This command includes the line number but also the the matched sting 

     findstr /s /i /n "\<select\> " *.php > c:\dev\php\search_select2.txt

Is there a way to only get the matching file + line number without including the matched string?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2673bff6-4e43-3d54-f58f-2f6f805d341f
* Version Independent ID: 9c9c8acd-5c0f-a681-58c8-86bab3942748
* Content: [findstr](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/findstr#examples)
* Content Source: [WindowsServerDocs/administration/windows-commands/findstr.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/findstr.md)
* Product: **windows-server-threshold**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by GhostInTheKayak** [comment]
Try something like this:
```
for /f "usebackq delims=: tokens=1,2" %x in (`findstr /s /i /n "\<select\>" *.php`) do @echo %x %y
```

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
