### ISSUE TITLE
[Remote Desktop client for Android] Get rid of control keys

### ISSUE THREAD

**Issue by duenni** [MicrosoftDocs/windowsserverdocs#3284]
I need the RD Client quite often on devices with a small screen. When showing the integrated keyboard there is also a black bar appearing on top of it which has special keys like the Windows key etc. I'd like to get rid of this "control key bar" because I don't need it and it's shrinking the small screen size further.

I tried different keyboards and also different settings for these keyboard like disable AutoFill and Suggestions and so on. Current keyboard is AOSP. I can't seem to find a way to disable the bar.

Is there any way to disable the control keys and use only the virtual keyboard?

![ObcKTl](https://user-images.githubusercontent.com/4258185/64520059-9fb88000-d2f5-11e9-83cc-ccc078efb0e6.jpg)

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
