### ISSUE TITLE
MSDT missing details

### ISSUE THREAD

**Issue by Opportunivore** [MicrosoftDocs/windowsserverdocs#3285]
Please add a link to the available /IDs

Troubleshooting Pack ID	Description	Application or Feature Dependency
AeroDiagnostic	Troubleshoots problems displaying Aero effects like transparency.	Aero Display Theme installed
NetworkDiagnosticsDA	Troubleshoots problems connecting to a workplace network over the Internet using Direct Access.	Direct Access installed
DeviceDiagnostic	Troubleshoots problems using hardware and access devices connected to the computer.	
HomeGroupDiagnostic	Troubleshoots problems viewing computers or shared files in a homegroup.	HomeGroup installed
NetworkDiagnosticsInbound	Troubleshoots problems with allowing other computers to communicate with the target computer through Windows Firewall.	
NetworkDiagnosticsWeb	Troubleshoots problems connecting to the Internet or to a specific Web site.	
IEDiagnostic	Helps the user prevent add-on problems and optimize temporary files and connections.	Internet Explorer installed
IESecurityDiagnostic	Helps the user prevent malware, pop-ups, and online attacks.	Internet Explorer installed
NetworkDiagnosticsNetworkAdapter	Troubleshoots problems with Ethernet, wireless, or other network adapters.	
PerformanceDiagnostic	Helps the user adjust settings to improve operating system speed and performance.	
AudioPlaybackDiagnostic	Troubleshoots problems playing sounds and other audio files.	Audio output device installed
PowerDiagnostic	Helps the user adjust power settings to improve battery life and reduce power consumption.	
PrinterDiagnostic	Troubleshoots problems printing.	
PCWDiagnostic	Helps the user configure older programs so that they can run in the current version of Windows.	
AudioRecordingDiagnostic	Troubleshoots problems recording audio from a microphone or other input source.	Audio input device installed
SearchDiagnostic	Troubleshoots problems with search and indexing using Windows Search.	Search enabled
NetworkDiagnosticsFileShare	Troubleshoots problems accessing shared files and folders on other computers over the network.	
MaintenanceDiagnostic	Helps the user clean up unused files and shortcuts and perform other maintenance tasks.	
WindowsMediaPlayerDVDDiagnostic	Troubleshoots problems playing a DVD using Windows Media Player.	Windows Media Player installed
WindowsMediaPlayerLibraryDiagnostic	Troubleshoots problems with adding media files to the Windows Media Player library.	Windows Media Player installed
WindowsMediaPlayerConfigurationDiagnostic	Helps the user reset Windows Media Player settings to the default configuration.	Windows Media Player installed
WindowsUpdateDiagnostic	Troubleshoots problems that prevent Windows Update from performing update tasks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb79e58-2c56-f4cf-6a80-97d964bb5722
* Version Independent ID: f58bf0b4-5300-41bb-5b62-31e45cedd1bb
* Content: [msdt](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/msdt#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/msdt.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/msdt.md)
* Product: **windows-server-threshold**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Yupiter2005** [comment]
I'd also add the default path for diagnostics logs/collected data and if there a switch to perform automatic upload.

Also /cab switch is not documented
