### ISSUE TITLE
Bad Microsoft FWLINK for this page

### ISSUE THREAD

**Issue by ggbce** [MicrosoftDocs/windowsserverdocs#3302]
When we follow the upgrade process from Windows Server 2008 R2 through Windows Server 2012, during the SETUP.EXE process at step "Compatibility Report (Saved you desktop)" an information tell that we can download tools and documentation to test application compatibility from linkID=243105... Where this link give this page... But inside this page no tools are available to download (Tools to test applications compatibility)... Just another step-by-step explain to make the upgrade In-Place. To help you in the research, tak a look to step #9 in this webpage: https://www.microsoft.com/upgradecenter/scenario/WS2008R2-on-prem-to-WS2019 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88d8e06f-1416-57d1-84b9-fd82d217a481
* Version Independent ID: 9047ff8c-95f0-ffea-38d6-9a6d6c56e383
* Content: [Windows Server Installation and Upgrade](https://docs.microsoft.com/en-us/windows-server/get-started/installation-and-upgrade)
* Content Source: [WindowsServerDocs/get-started/Installation-and-Upgrade.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/Installation-and-Upgrade.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
