### ISSUE TITLE
Which router allow source IP restriction?

### ISSUE THREAD

**Issue by shaohs** [MicrosoftDocs/windowsserverdocs#3306]
I didn't find any router that has source restriction allowing access from a whole range of that particular ISP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f03c4904-9756-3fcf-17ee-05a2e5717dc9
* Version Independent ID: ec3b6a31-7d65-5ab1-2721-40401a9b3b7f
* Content: [Remote Desktop - Allow access to your PC from outside your network](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-allow-outside-access#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-allow-outside-access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-allow-outside-access.md)
* Product: **windows-server-threshold**
* Technology: **remote-desktop-services**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **elizapo**

**Comment by Harrioson** [comment]
Seriously here out this >>> https://www.techsovibe.com/microsoft-windows/

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
