### ISSUE TITLE
Doc request: Build an ASP.NET Core app using OAuth and  with AD FS

### ISSUE THREAD

**Issue by Rick-Anderson** [MicrosoftDocs/windowsserverdocs#3312]
@billmath see https://github.com/aspnet/AspNetCore.Docs/issues/4556
Let me know what I can do to help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 731a5db9-3e53-0379-edcb-4c338dad0240
* Version Independent ID: 683ef16d-2cbd-7d01-a7da-842f4afb1d8f
* Content: [Build a single page web application using OAuth and ADAL.JS with AD FS 2016 or later](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/single-page-application-with-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/Single-Page-Application-with-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/Single-Page-Application-with-AD-FS.md)
* Product: **windows-server-threshold**
* Technology: **active-directory-federation-services**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
