### ISSUE TITLE
Typo PowerShell Command

### ISSUE THREAD

**Issue by gunterda** [MicrosoftDocs/windowsserverdocs#3328]
This:
To view the node selected as the User Activity master. Get-AdfsFarmInformation.FarmRoles
sould be: 
To view the node selected as the User Activity master. (Get-AdfsFarmInformation).FarmRoles

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8634165-2ff5-9b01-e3fc-17827360a5f3
* Version Independent ID: a5a91921-3193-93ad-df22-d486e65b19f8
* Content: [Configure AD FS Extranet Lockout Protection](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-extranet-smart-lockout-protection#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
(Ref. #4016 )

**Comment by illfated** [comment]
Issue resolved in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/986116ea2bc4bda2379eb20f6a96cd6d963e5342 / PR #4016.

**Comment by illfated** [comment]
#please-close
