### ISSUE TITLE
Are multiple network interfaces required?

### ISSUE THREAD

**Issue by jachin84** [MicrosoftDocs/windowsserverdocs#3333]
A typical Storage Space Direct cluster would require multiple networks for Storage, Cluster communication and client communication. In this article no mention is made about additional network interfaces. Running cluster validation on the configuration detailed in this article produces a warning about only having a single network.

Please provide guidance on the correct network configuration for Cluster to Cluster replication in Azure, specifically in relation to multiple network interfaces. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7427fc8-7930-7ff0-dbd1-8805731002ae
* Version Independent ID: e36fb931-b5fd-8d41-75eb-aacf447fb358
* Content: [Cluster to Cluster Storage Replica cross region in Azure](https://docs.microsoft.com/en-us/windows-server/storage/storage-replica/cluster-to-cluster-azure-cross-region#feedback)
* Content Source: [WindowsServerDocs/storage/storage-replica/cluster-to-cluster-azure-cross-region.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-replica/cluster-to-cluster-azure-cross-region.md)
* Product: **windows-server-threshold**
* Technology: **storage-replica**
* GitHub Login: @arduppal
* Microsoft Alias: **arduppal**

**Comment by StevenEk** [comment]
Better network guidance and documentation is being worked on.  Thank you for the feedback.
