### ISSUE TITLE
SSO with Workplace Join - the same or different from SSO from Azure AD Registered devices with PRT?

### ISSUE THREAD

**Issue by cap273** [MicrosoftDocs/windowsserverdocs#3341]
This page says the following:

" This functionality implies that users are prompted only one time during the lifetime of SSO to access company applications and resource from this device. If a device uses Workplace Join, the user who is registered to use this device gets persistent SSO, by default for seven days. This user has a seamless sign-in experience in the same session or in new sessions."

Workplace joining a device sounds the same as registering a device with Azure AD. The documentation (https://docs.microsoft.com/en-us/azure/active-directory/devices/concept-primary-refresh-token) on Primary Refresh Token (PRT) for Azure AD Registered and Azure AD Joined devices says the following:

"Once issued, a PRT is valid for 14 days and is continuously renewed as long as the user actively uses the device."

Is the SSO provided through Workplace Join the same as the SSO provided through Azure AD Registration? Is the persistency of these SSO sessions different (7 days or 14 days)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2646147-59ef-ae02-9923-742f1fd58508
* Version Independent ID: bba6f1ff-468f-f23c-f419-eba95096e131
* Content: [Join to Workplace from Any Device for SSO and Seamless Second Factor Authentication Across Company Applications](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/join-to-workplace-from-any-device-for-sso-and-seamless-second-factor-authentication-across-company-applications)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Join-to-Workplace-from-Any-Device-for-SSO-and-Seamless-Second-Factor-Authentication-Across-Company-Applications.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Join-to-Workplace-from-Any-Device-for-SSO-and-Seamless-Second-Factor-Authentication-Across-Company-Applications.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
