### ISSUE TITLE
How to (request to) reopen an issue that was not resolved

### ISSUE THREAD

**Issue by softwarecraft** [MicrosoftDocs/windowsserverdocs#3344]
This issue was closed with a claimed resolution, [https://github.com/MicrosoftDocs/windowsserverdocs/issues/444](https://github.com/MicrosoftDocs/windowsserverdocs/issues/444) but was not in fact resolved. @daveba comment does not provide an actual resolution and there has been no follow up since the issue was closed.

How do I (request to) re-open the issue?

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
