### ISSUE TITLE
Incorrect information about Alternate Login ID

### ISSUE THREAD

**Issue by AlexFilipin** [MicrosoftDocs/windowsserverdocs#3345]
Section: Additional Details & Considerations - First point states, that Alternate login ID is not supported in managed environments. I am pretty sure that is not correct.

See https://docs.microsoft.com/en-US/azure/active-directory/hybrid/how-to-connect-sso-faq Section: "Does Seamless SSO support Alternate ID as the username, instead of userPrincipalName?"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02d8b61-29e8-c0a7-b3b2-79be7212a91c
* Version Independent ID: b4346d87-0727-c7fe-7896-7fd79098825c
* Content: [Configuring Alternate Login ID](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configuring-alternate-login-id#additional-details--considerations)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configuring-Alternate-Login-ID.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configuring-Alternate-Login-ID.md)
* Product: **windows-server-threshold**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by AlexFilipin** [comment]
Assuming "managed environments" means "managed authentication" aka PHS, PTA, PHS+S-SSO and PTA + S-SSO.

**Comment by ArttuArstila** [comment]
It would be great to get this updated in the documentation, as new deployments are typically managed authentication deployments.

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
