### ISSUE TITLE
Note 8 is unclear

### ISSUE THREAD

**Issue by btb** [MicrosoftDocs/windowsserverdocs#3360]
"the kernel included Debian backports" - is there a word missing here? should it say "the kernel included _in_ Debian backports"?

There are multiple kernels in Debian backports, which kernel specifically? Any of them? The "cloud" one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef7e57c1-a0f5-126a-775c-7e99a607197b
* Version Independent ID: 22a9dc7b-18c2-6f73-d224-886757a65a7c
* Content: [Supported Debian virtual machines on Hyper-V](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/Supported-Debian-virtual-machines-on-Hyper-V?redirectedfrom=MSDN#feedback)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Supported-Debian-virtual-machines-on-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/Supported-Debian-virtual-machines-on-Hyper-V.md)
* Service: **na**
* Product: **windows-server**
* Technology: **compute-hyper-v**
* GitHub Login: @shirgall
* Microsoft Alias: **kathydav**

**Comment by prenetic** [comment]
Would also like clarification on this item. We are struggling with Dynamic Memory using a Windows Server 2019 host and Debian Buster guest. Having tried Linux kernel 4.19.0 (shipped with Buster), as well as backported kernels 5.2.0 (cloud and non-cloud), Dynamic Memory is still not working as intended -- memory continues to be allocated by the hypervisor, but not seen/consumed by the guest.

Some clarification around *exactly* which kernels/configurations are required to functionally enable Dynamic Memory would be GREATLY appreciated, as this statement is currently too ambiguous to be useful.

**Comment by illfated** [comment]
Looking at the sentence in note 8, I can see that it is open to misinterpretation:

> 8. The latest upstream kernel capabilities are only available by using the kernel included [Debian backports](https://wiki.debian.org/Backports).

To reduce the amount of misinterpretation without rewriting note 8 by changing the content, I imagine it can be read like this:

8. The latest upstream kernel capabilities are only available by using the [Debian backports](https://wiki.debian.org/Backports) included with the kernel.

**Comment by prenetic** [comment]
> Looking at the sentence in note 8, I can see that it is open to misinterpretation:
> 
> > 1. The latest upstream kernel capabilities are only available by using the kernel included [Debian backports](https://wiki.debian.org/Backports).
> 
> To reduce the amount of misinterpretation without rewriting note 8 by changing the content, I imagine it can be read like this:
> 
> 1. The latest upstream kernel capabilities are only available by using the [Debian backports](https://wiki.debian.org/Backports) included with the kernel.

While I agree this may read a bit better, it still fails to serve the reader. Additional information pertaining to precisely which backports support these features, along with any supplementary configurations would go a long way. Without this information documented somewhere, there's a lot left to interpretation by the reader.

**Comment by illfated** [comment]
@shirgall and/or @KBDAzure ; Would you be able to share your insight with us in this matter?
Otherwise, would you be able to refer to someone else who may look into this issue?

**Comment by BenLangers** [comment]
Is there any additional information on this available?
I am having the same issue, and the same problem understanding the note. I have got the backports repository enabled, but what do I need to install? A newer kernel? The hyperv-daemons? 
Getting dynamic memory working for Debian would be great!

**Comment by illfated** [comment]
@konstruktoid : Please, may I ask for your take on this issue, to see the problem from a different angle?

I would like the opportunity to create a PR and suggest an improvement to the reported confusion around parts of the document.
(By the way, if you would like to open a pull request yourself to suggest the improvement, feel free.)

**Comment by konstruktoid** [comment]
I would probably rephrase it as:
`The latest upstream kernel capabilities are only available by using the kernels available in the Debian backports repository.`

@BenLangers, try installing a newer kernel.
(In stable it's 4.19 I believe, and in Backports it's 5.4.8. Compared to 5.8.13 which is latest official stable kernel.)

What's missing in this document is in which kernel version the wanted functionality was added, `latest` is a pretty vague term.

**Comment by illfated** [comment]
True, I also subscribe to the fact that "Latest" is a very poor version description. Almost like "No, I won't tell you."
(Try using "latest" in any GH repository where the main content is updated more than once a week ... ) 😉 :trollface:

**Comment by illfated** [comment]
There you go. PR #4885 is ready for review. Feel free to comment, suggest or discuss the requested change.
