### ISSUE TITLE
Space missing

### ISSUE THREAD

**Issue by oneoneonepig** [MicrosoftDocs/windowsserverdocs#3372]
"Get-WindowsPackage--Online"

There should be a space before the "online" option

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e8be60e-5712-efd6-df26-0c6e74aff2bb
* Version Independent ID: 8a132ca9-3d8d-dd4a-847d-50d3bb77c31f
* Content: [Manage Nano Server](https://docs.microsoft.com/en-us/windows-server/get-started/manage-nano-server#feedback)
* Content Source: [WindowsServerDocs/get-started/Manage-Nano-Server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/Manage-Nano-Server.md)
* Service: **na**
* Product: **windows-server**
* Technology: **server-nano**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@JasonGerend

**Comment by illfated** [comment]
Unless someone else has started the process to add the required change,
feel free to ping me for a quick PR to solve the issue.

**Comment by jaimeo** [comment]
@illfated: go for it

**Comment by oneoneonepig** [comment]
Hmmmm, I think that should be '-online' instead of '--online'. Didn't notice that until now, sorry for that.

[https://docs.microsoft.com/en-us/powershell/module/dism/get-windowspackage](url)

**Comment by illfated** [comment]
Fair enough. Thanks for the link, although it is better to leave it unmodified in comments:
https://docs.microsoft.com/en-us/powershell/module/dism/get-windowspackage

I will get that change added in the PR.

**Comment by illfated** [comment]
There you go. Feel free to suggest other modifications to the page, if required.
