### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by GLComputing** [MicrosoftDocs/windowsserverdocs#3373]
In the Deprecated features section, the KB link to Disable the NoLMHash policy is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a169cc6-7051-17c0-2220-898cac8b65e4
* Version Independent ID: d793f335-3401-31b1-2f73-38255612613d
* Content: [Upgrade Domain Controllers to Windows Server 2012 R2 and Windows Server 2012](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/upgrade-domain-controllers-to-windows-server-2012-r2-and-windows-server-2012#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/Upgrade-Domain-Controllers-to-Windows-Server-2012-R2-and-Windows-Server-2012.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/Upgrade-Domain-Controllers-to-Windows-Server-2012-R2-and-Windows-Server-2012.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by illfated** [comment]
Indeed. Looks like it has been deprecated too, just like Windows Server 2003 and Windows Server 2000.

The page has moved to this archive friendly URL:
- https://support.microsoft.com/en-us/help/299656/how-to-prevent-windows-from-storing-a-lan-manager-hash-of-your-passwor

**Comment by illfated** [comment]
There you go, Pull Request #4989 is now available for viewing, comments or suggestions.
Even though this is more than a year after the report was made, I hope this helps.
