### ISSUE TITLE
Android client in Chromebook - Keyboard in Spanish missing keys

### ISSUE THREAD

**Issue by jrbuleo** [MicrosoftDocs/windowsserverdocs#3374]
Some keys are not correctly mapped on Spanish keyboard (using physical keyboard from the chromebook). 

In other keyboard layouts, looks like the key-mapping is working as intended.

Characters '_' and '-' for example are changed by a ',' .  

We can reproduce the issue in regular and Beta Client. 

ChromeOS 77 using Android client against Windows 10 Enterprise.

**Comment by illfated** [comment]
Which context is this related to, which page(s) contain the information you would like to see changed?

**Comment by jrbuleo** [comment]
Oh sorry my bad :( I was following links from the documentation and I saw some issues documented here with the client in this project, but it is not the correct place to write.
