### ISSUE TITLE
Missing some links

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/windowsserverdocs#3378]
If the links on this page are supposed to be a comprehensive list of the ones under this navigation heading, it's missing "AD Forest Recovery Guide" and a couple more of the single-page entries.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7cd10d3-56ba-96d8-999f-959cde3b41f3
* Version Independent ID: 827006e0-d880-88c2-6468-3a851256ca19
* Content: [AD DS Operations](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/component-updates/ad-ds-operations)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/component-updates/AD-DS-Operations.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/manage/component-updates/AD-DS-Operations.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
