### ISSUE TITLE
Developer Tools link is dead

### ISSUE THREAD

**Issue by IanJDan** [MicrosoftDocs/windowsserverdocs#3394]
Developer Tools link is dead: https://github.com/Microsoft/windows-admin-center-sdk/tree/master/windows-admin-center-developer-tools

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac61f326-7fa7-15c7-8b0a-67e50d100dfb
* Version Independent ID: fd98eee8-3b3c-65d6-c704-b84b6c1eefac
* Content: [Develop a solution extension](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/extend/develop-solution#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/extend/develop-solution.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/extend/develop-solution.md)
* Product: **windows-server**
* Technology: **manage**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by illfated** [comment]
Looks like the directory and its pages were deleted in commit https://github.com/microsoft/windows-admin-center-sdk/commit/ed5cc4b91449b19d58edb627378e0556e3b035b7 on March 1, 2019 8:00 PM GMT. Links pointing to the page should have been changed or removed at the same time, but seems to have been forgotten.

@mattatmsft : Is there a replacement feature to link to, or should we look into removing any sentence where links to that removed feature appears?

**Comment by mattatmsft** [comment]
@illfated - The Dev Tools extension is now built into the product itself, this document is out of date, and will be updated ASAP.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
