### ISSUE TITLE
Simply Wrong.

### ISSUE THREAD

**Issue by Dagriff** [MicrosoftDocs/windowsserverdocs#3399]
"There are two ways to start the AD FS Federation Server Configuration Wizard....".  Neither of these methods appear to be available in ADFS 4 (2016).  Please update this documentation to reflect that you have to run the configuration wizard on the additional server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe984b9f-e613-1d70-f4fc-89f21f2814a5
* Version Independent ID: cd46dde4-9fd2-1592-caa9-f538131649ac
* Content: [Add a Federation Server to a Federation Server Farm](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/add-a-federation-server-to-a-federation-server-farm#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Add-a-Federation-Server-to-a-Federation-Server-Farm.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Add-a-Federation-Server-to-a-Federation-Server-Farm.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
