### ISSUE TITLE
 Can't install the "OpenSSHUtils"

### ISSUE THREAD

**Issue by kljkyzsl** [MicrosoftDocs/windowsserverdocs#3400]
[Enter feedback here]
 can't install the "OpenSSHUtils" when I execute the command "Install-Module -Force OpenSSHUtils -Scope AllUsers" 
Error info:
PackageManagement\Install-Package : 无法安装或更新模块“OpenSSHUtils”，因为文件“OpenSSHUtils.psd1”的验证码签名无效。
所在位置 C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 字符: 21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package]，Exception
    + FullyQualifiedErrorId : InvalidAuthenticodeSignature,ValidateAndGetAuthenticodeSignature,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 337c4ea8-1806-92a3-1501-b3ff5dde37bb
* Version Independent ID: c411d389-578d-57c6-cd6e-eaca7f2837db
* Content: [OpenSSH Server Configuration for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* GitHub Login: @maertendMSFT

**Comment by zsluedem** [comment]
I have also met this issue.

**Comment by AnthonyMastrean** [comment]
In an Administrator PowerShell session:

```
❯ Install-Module -Force OpenSSHUtils -Scope AllUsers
PackageManagement\Install-Package : The module 'OpenSSHUtils' cannot be installed or updated       because the authenticode signature of the file 'OpenSSHUtils.psd1' is not valid.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21     + ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage     ) [Install-Package], Exception
    + FullyQualifiedErrorId : InvalidAuthenticodeSignature,ValidateAndGet-AuthenticodeSignature,M     icrosoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

**Comment by AnthonyMastrean** [comment]
Related?

https://github.com/PowerShell/Win32-OpenSSH/issues/1313

**Comment by darkvertex** [comment]
Getting an error also... :man_shrugging:

```
PS C:\WINDOWS\system32> Install-Module -Force OpenSSHUtils -Scope AllUsers
PackageManagement\Install-Package : No match was found for the specified search criteria and module name
'OpenSSHUtils'. Try Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex
   ception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

Will someone please fix the docs with complete instructions? :/

**Comment by darkvertex** [comment]
BTW I was able to get ssh key authentication working without OpenSSHUtils by following these helpful Stackoverflow steps:
https://stackoverflow.com/questions/16212816/setting-up-openssh-for-windows-using-public-key-authentication

**Comment by illfated** [comment]
Would you be able to suggest which parts to remove and which parts of the documentation to keep, maybe start working on a Pull Request to have these documents improved? If yes, feel free to choose between posting the changes you recommend here in this issue ticket, or open a Pull Request to change the document itself, if you are certain which parts need changing.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation
by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your questions, both due to the small size of the team and the big workload.

**Comment by brianhatchet** [comment]
Looks like we'll need to do it by hand using @darkvertex 's manual steps.

https://www.powershellgallery.com/packages/OpenSSHUtils/1.0.0.1

That package has been unlisted from the Powershell Gallery. I've reached out to the maintainers, but until them you either need to install the package manually or just set the permissions by hand.

**Comment by bjanders** [comment]
> Looks like we'll need to do it by hand using @darkvertex 's manual steps.

It's probably removed because you should not need it anymore, as Windows has a built in ssh-agent. See for example: https://github.com/MicrosoftDocs/windowsserverdocs/issues/4345

**Comment by illfated** [comment]
See Pull Request #4788 for a suggested improvement to this issue.
(The PR will close this issue ticket when it gets merged.)

**Comment by illfated** [comment]
Please comment in PR #4788 (**update OpenSSH key management**) if you think the suggested change needs to be improved.
