### ISSUE TITLE
Anyway to make a single DataTable cell editable instead of the entire column?

### ISSUE THREAD

**Issue by bchipman** [MicrosoftDocs/windowsserverdocs#3401]
Is there anyway to make a single DataTable cell editable instead of the entire column?  In the dev-guide examples for data table, it shows how to make a cell editable by modifying the &lt;sme-data-table-column&gt; in the .html.  But what if I only want to make certain cells modifiable?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 266315b8-eeac-a4b0-774c-ac1dfe14f4ea
* Version Independent ID: dcbe9fe4-46e4-5d0d-97b7-0cfcc4f688d2
* Content: [Develop an extension for Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/extend/developing-extensions)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/extend/developing-extensions.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/extend/developing-extensions.md)
* Product: **windows-server**
* Technology: **manage**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
