### ISSUE TITLE
Azure AD authentication not prompting

### ISSUE THREAD

**Issue by Bievens** [MicrosoftDocs/windowsserverdocs#3405]
"Users who's Windows account has Administrator rights on the gateway machine will not be prompted for the Azure AD authentication."

Why is this the case? We want MFA and conditional access regardless of local administrative permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6273f49-fe06-5a18-80e3-863bd3a0cf4e
* Version Independent ID: 4ed5bf3d-0c2a-a80e-5bd9-0e858dd8749b
* Content: [Configuring user access control and permissions](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/configure/user-access-control#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/configure/user-access-control.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/configure/user-access-control.md)
* Product: **windows-server**
* Technology: **manage**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by chris-dma** [comment]
I agree with this. It makes the Azure AD integration useless from my perspective.

**Comment by bwdur** [comment]
Same.  I don't really get why this is the case?

**Comment by sbgillett** [comment]
Agreed, this makes Azure AD integration pointless.

**Comment by sbgillett** [comment]
I've previously tried putting WAC behind Azure AD Application Proxy, but its (non-configurable) buffering kills certain functionality dead, for example Remote Desktop from WAC no longer works.
