### ISSUE TITLE
Command Help /? does not function as documented

### ISSUE THREAD

**Issue by CJMakris** [MicrosoftDocs/windowsserverdocs#3406]
Although not shown in the syntax, this reference for command line help does not function in any version of Windows I've tried:
/?	Displays help at the command prompt.
Typing "MMC /?" at a command line simply invokes the MMC console app (no help), does not display help in the commend window as expected. Tested on Windows Server 2008R2 and Windows 10.1903.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9056d431-5b2a-9a25-3d02-aa3653f679d8
* Version Independent ID: 82ae74c6-a8b3-dc8b-1e6f-3a10f6e3469a
* Content: [mmc](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mmc#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/mmc.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/mmc.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
I just tested this on Windows Server 2016 and it is definitely not working there. It seems to follow the Windows Server 2008 MMC command-line set of options where the "/? " option was not available.

I can also confirm that this option does not work on Windows 10 Professional 1903 18362.418 (as well as on Windows 10 Home x64 1903 18362.418, but it was expected on Windows 10 Home).

Unfortunately, I don't have access to a Windows Server 2019 setup (not even a trial version), so I don't know if it works there or not.

**Comment by illfated** [comment]
@CJMakris : Thank you for having reported this issue. I am only sorry I did not realize how obvious this documentation issue is, because the "help" parameter ( **/?** ) is not even mentioned in the command line options.

See also my closing PR #4999 for details on the table line removal. Thanks again for your contribution.

**Comment by CJMakris** [comment]
For the record, the same behavior is observed (no help is displayed using command line option: /?) in these various versions I tested today:

- Windows 2000 SP4 [5.00.2195]
- Windows Server 2019 [10.0.17763.805]
- Windows 10 (pre-release) [10.0.21343.1000]

Since it does not appear to function as far back as Windows 2000 nor in various current/forthcoming releases, removing it from the documentation appears to be the best resolution.
