### ISSUE TITLE
kkkk

### ISSUE THREAD

**Issue by adelabou** [MicrosoftDocs/windowsserverdocs#3407]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 247eb851-3274-a74b-2632-5c8cf4ec1914
* Version Independent ID: 0291e183-efd5-da46-da94-53e1f552f9e2
* Content: [Get Started](https://docs.microsoft.com/en-us/windows-server/get-started/server-basics#feedback)
* Content Source: [WindowsServerDocs/get-started/Server-Basics.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/Server-Basics.md)
* Service: **na**
* Product: **windows-server**
* Technology: **get-started**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
Unless you specify what you want to comment on or suggest an improvement for in the documentation, this issue ticket will be closed.

**Comment by jaimeo** [comment]
Listed author is wrong. @JasonGerend

**Comment by illfated** [comment]
Thanks, I will open a PR to have the document author changed as suggested.
