### ISSUE TITLE
Error attempting to containerize with Docker - Windows Admin Center

### ISSUE THREAD

**Issue by ironScripter** [MicrosoftDocs/windowsserverdocs#3408]
Getting an error when attempting to install and run this in a Docker container. I believe that i have narrowed it down to the firewall service being stopped/disabled. In Windows Docker containers the firewall service is disabled and permissions removed from the administrator for that service. I have tried with the 1909 version as well as 1904.1 version. The information below is for the attempts with the 1909 version. Both MSI's error in the same way. 

**The installer is failing with the following error:**
```
Calling custom action Microsoft.ManagementExperience.Setup.CustomActions!Microsoft.ManagementExperience.Setup.CustomActions.CustomAction.CreateFirewallRule
```
*Full Log Attached (Log.txt)*

**MSI Info**
WindowsAdminCenterPreview1909.msi

**Docker Version Info**
Client: Docker Engine - Enterprise
* Version:           19.03.3
* API version:       1.40
* Go version:        go1.12.10
* Git commit:        cde21d3829
* Built:             10/08/2019 17:59:26
* OS/Arch:           windows/amd64
* Experimental:      false

Server: Docker Engine - Enterprise
* Engine:
* Version:          19.03.3
* API version:      1.40 (minimum version 1.24)
* Go version:       go1.12.10
* Git commit:       cde21d3829
* Built:            10/08/2019 17:57:54
* OS/Arch:          windows/amd64
* Experimental:     false

**DockerFile**
```
FROM mcr.microsoft.com/windows/servercore:ltsc2019 AS WinAdminCenter
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
WORKDIR /
COPY *.msi ./
COPY *.exe ./
RUN Start-Process 'msiexec.exe' -ArgumentList '/i', 'WindowsAdminCenter1904.1.msi','/qn','/L*v log.txt','SME_PORT=8080', 'SSL_CERTIFICATE_OPTION=generate', 'RESTART_WINRM=0' -Wait
RUN CAT log.txt
ENTRYPOINT [ "ServiceMonitor.exe","SME.exe" ]
```

**Docker Image Info**
*mcr.microsoft.com/windows/servercore:ltsc2019*
```
[
    {
        "Id": "sha256:739b21bd02e70d010b6b75d41aad12b941ab49aeda66d7930dd7b3745511ca9c",
        "RepoTags": [
            "mcr.microsoft.com/windows/servercore:ltsc2019"
        ],
        "RepoDigests": [
            "mcr.microsoft.com/windows/servercore@sha256:404e0ee336a063619d1e93a2446061cf19cb3068bacb1775f5613e3b54e527e1"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2019-10-08T17:06:06.3854519Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": [
                "c:\\windows\\system32\\cmd.exe"
            ],
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "windows",
        "OsVersion": "10.0.17763.805",
        "Size": 4793612520,
        "VirtualSize": 4793612520,
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\docker\\windowsfilter\\4b9dc934b7e8ab6ba61b625232da5b0cce30f7f1c4a5a6fa6872756c74443bf2"
            },
            "Name": "windowsfilter"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:c4d02418787d264406bed4956f2faccd58932e4466bbd693c1795e3a64d60e90",
                "sha256:e1791151e4625ce1803aff4fe5e314a56bf6f99d77be2b721138f7c78fab5c11"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```
[log.txt](https://github.com/MicrosoftDocs/windowsserverdocs/files/3735410/log.txt)

**Comment by niranjan94** [comment]
I'm also facing the same issue. Would be useful to be able to run the windows admin center on a container. Is there is solution/workaround available for this ?

Thanks :)

**Comment by bvduijn** [comment]
Hi, I would also like to be able to run it in a container. I've edited the MSI file and it seems there is already a property on which the firewall rule checks. However the property is not listed in the MSIs property table. I've added SME_CONTAINER to it and changed the install command to:

`RUN Start-Process 'msiexec.exe' -ArgumentList '/i', 'WindowsAdminCenter1910.2.msi','/qn','/L*v log.txt','SME_PORT=8080', 'SSL_CERTIFICATE_OPTION=generate', 'SME_CONTAINER=true', 'RESTART_WINRM=0' -Wait`

Install is now successfull!! 

Entrypoint need to be changed as well to

` ENTRYPOINT [ "ServiceMonitor.exe","ServerManagementGateway" ]`

Then I ran my container and got a logon screen.... Apparently WIA is enabled. 

Via `docker exec -it <containerid> powershell` I entered a session into the container and created a user for myself using:

`
NET USER testing "Password01!" /ADD
NET LOCALGROUP "Administrators" "testing" /ADD
`

And behold... It's started. I don't think it's much use this way with local credentials but that's where gMSA comes in maybe?

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by gabrielluizbh** [comment]
Try to install Docker through Windows Admin Center on Windows Server 2022 Core and this error occurs.

![image](https://github.com/MicrosoftDocs/windowsserverdocs/assets/31531703/500172d2-a83d-4d90-bc19-89405c31b2c2)

Try to install Docker Powershell on Windows Server 2022 Core and this error occurs.

![image](https://github.com/MicrosoftDocs/windowsserverdocs/assets/31531703/d9fbead3-eba2-469e-89be-2645be100f6f)

![image](https://github.com/MicrosoftDocs/windowsserverdocs/assets/31531703/34e46e73-c3cd-49b1-a5fb-9638a5fabfd3)
