### ISSUE TITLE
Missing step in recreating database

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/windowsserverdocs#3411]
Before running the icacls command I needed to take ownership of the file first despite being logged in as an admininstrator.

takeown /f c:\ProgramData\Microsoft\StorageMigrationService /r /a

Then I was able to run the icacls commands.
There is also duplicate ICACLS commands at the end and the last one does not work (/GRANT networkservice:(GA)F /T /C

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47e8f561-963a-50f0-347c-5c6d40c5b693
* Version Independent ID: e91fc4e1-e9df-6253-88d1-cab878edb0fd
* Content: [Storage Migration Service known issues](https://docs.microsoft.com/en-us/windows-server/storage/storage-migration-service/known-issues)
* Content Source: [WindowsServerDocs/storage/storage-migration-service/known-issues.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-migration-service/known-issues.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @nedpyle
* Microsoft Alias: **nedpyle**

**Comment by nedpyle** [comment]
Something happened in the publishing of this update, where the TAKEOWN command wasn't added. The last line has a typo (should not include F, it is required to just have GA). Will get this all fixed up, thanks very much

**Comment by MarcLaf** [comment]
Thanks Ned!
