### ISSUE TITLE
Needs Section on Endpoint Options and Effects on Connecting Cloud Witness

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/windowsserverdocs#3413]
When creating a storage account, under the Networking tab, there are 3 Connectivity Methods: Public Endpoint (all networks), Public Endpoint (selected networks), and Private Endpoint.  It would be extremely helpful to have a short paragraph and links to assist setup of cloud witness depending on each of these.  I eventually resorted to using Public Endpoint (selected networks) and mapped it to the same subnet as my cluster, but not until after trying Private Endpoint and being unable to get Cloud Witness to work.  It would be very helpful to note the security implications of each of these in relation to the cloud witness.  It would also be helpful for those who want to create a Private Endpoint and connect their cloud witness with it to have more specific instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b112fd4-0bd2-ca4d-5d45-15396a00820a
* Version Independent ID: 34bffa79-1d32-aeeb-1577-8cc94808544c
* Content: [Deploy a cloud witness for a Failover Cluster](https://docs.microsoft.com/en-us/windows-server/failover-clustering/deploy-cloud-witness?redirectedfrom=MSDN#feedback)
* Content Source: [WindowsServerDocs/failover-clustering/deploy-cloud-witness.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/deploy-cloud-witness.md)
* Product: **windows-server**
* Technology: **storage-failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by PrometheusRising1** [comment]
Even worse, once I created a Private Endpoint, I had to delete all of the objects related and now cannot have a Public Endpoint made as I get the following error. {"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"DeploymentFailed\",\r\n \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.\",\r\n \"details\": [\r\n {\r\n \"code\": \"BadRequest\",\r\n \"message\": \"{\\r\\n \\\"error\\\": {\\r\\n \\\"code\\\": \\\"PrivateEndpointNetworkPoliciesCannotBeEnabledOnPrivateEndpointSubnet\\\",\\r\\n \\\"message\\\": \\\"Private endpoint network policies cannot be enabled on private endpoint subnet /subscriptions/ce8f443b-c05c-4b3c-83f0-d4edceabaa94/resourceGroups/SQLServerDomainDevFarm/providers/Microsoft.Network/virtualNetworks/PrimaryNetwork/subnets/PrimarySubnet.\\\",\\r\\n \\\"details\\\": []\\r\\n }\\r\\n}\"\r\n }\r\n ]\r\n }\r\n ]\r\n }\r\n}"}]}

**Comment by PrometheusRising1** [comment]
Even worse, after creating a private endpoint, I deleted the blob store and deleted the endpoint objects and now cannot add a new storage account with a Public Endpoint (selected networks) as I receive the following error: Private endpoint network policies cannot be enabled on private endpoint subnet

**Comment by angabe89** [comment]
Hi

I am implementing a Cluster and we need to confirm if Private Endpoints are supported for Cloud Witness. Any comments about this issue?

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
