### ISSUE TITLE
local Administrator account, not domain' Administrator

### ISSUE THREAD

**Issue by rafalfitt** [MicrosoftDocs/windowsserverdocs#3415]
"Configure GPOs to restrict the domain's Administrator account's use on domain-joined systems"

IMHO it should be local Administrator account, not domain' Administrator.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8d5b7ca-15b0-39bd-64ad-b279bc574511
* Version Independent ID: 1c0d66b4-ee6f-be09-30dd-3f719d481bb9
* Content: [Appendix H - Securing Local Administrator Accounts and Groups](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/appendix-h--securing-local-administrator-accounts-and-groups)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-H--Securing-Local-Administrator-Accounts-and-Groups.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-H--Securing-Local-Administrator-Accounts-and-Groups.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by jokezone** [comment]
I believe the article is referring to the SID-500 "administrator" account for the domain. But it should take it a step further and prevent any member of the "Domain Admins" security group from performing those user rights on any domain-joined system which is not a Domain Controller. Either way, there is room for clarification.

**Comment by rafalfitt** [comment]
I believe the article "Appendix D" is referring to the SID-500 "administrator" account for the domain
https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/appendix-d--securing-built-in-administrator-accounts-in-active-directory

**Comment by illfated** [comment]
Thank you both for making me dive into this rabbit hole for a short while.
In the section https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/appendix-h--securing-local-administrator-accounts-and-groups#configuring-gpos-to-restrict-administrator-account-on-domain-joined-systems, I noticed that the following sentence looks a bit odd, as if several words are missing:

> 2.  In the console tree, expand <Forest>\Domains\\<Domain>, and then **Group Policy Objects** (where <Forest> is the name of the forest and <Domain> is the name of the domain where you want to set the Group Policy). 

Missing words and keywords is actually the case, so I will propose a PR to mark those hidden words as code, using MD back ticks, to keep those tags from being hidden by MarkDown before migrating the document to HTML. The actual content is as follows:

`2.  In the console tree, expand <Forest>\Domains\\<Domain>, and then **Group Policy Objects** (where <Forest> is the name of the forest and <Domain> is the name of the domain where you want to set the Group Policy).`

Feel free to point out more weird parts of the document, that I may fix them and add them to my PR content before opening the PR here on Github.

**Comment by rafalfitt** [comment]
still, there is a confusion between local Administrator and domain Administrator:

For the **local Administrator account** in each domain in your forest, you should configure the following settings:

Configure GPOs to restrict the **domain's Administrator account**'s use on domain-joined systems

**Comment by illfated** [comment]
Fair enough, that is a good enough start as any. I can add that along with the things I have already noted. I will suggest emphasis (bold text) the same way as you have suggested.

**Comment by illfated** [comment]
> still, there is a confusion between local Administrator and domain Administrator:
> 
> For the **local Administrator account** in each domain in your forest, you should configure the following settings:
> 
> Configure GPOs to restrict the **domain's Administrator account**'s use on domain-joined systems

Hmm, I read this section/paragraph as meaning "make sure that the local Administrator account on all devices and all domains in the forest is not part of the Domain Administrators group". Am I missing the point here?

**Comment by illfated** [comment]
Ref. PR #5017 aiming to restore hidden placeholders by escaping the angle brackets with backslash or MD backticks encapsulation. Feel free to view, browse, comment and suggest further improvements.
