### ISSUE TITLE
And how to install the update versions?

### ISSUE THREAD

**Issue by cheesecracker** [MicrosoftDocs/windowsserverdocs#3416]
It's good to have this table.  It would be better to have the means to install to the updated versions.   Say I have Windows Server 2016 version 1607.  How to install version 1903?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 738f3265-e459-da12-0f2c-d4fc1eff4fff
* Version Independent ID: 679afb77-9852-4608-291c-74bf2739890f
* Content: [Windows Server release information](https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info)
* Content Source: [WindowsServerDocs/get-started/windows-server-release-info.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/windows-server-release-info.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
I concur with the comment from @sergeos. My workplace uses Windows Server 2016 version 1607, which can only be updated to newer minor versions under the OS Build number (14393.0). A 1903 version (Windows Server 2019) can only be installed as a new full installation of the operating system. See also the Note on the page from where you opened this issue ticket.

I do not think this is a required information for that referenced page, because it may be mentioned somewhere else in the documentation.

**Comment by cheesecracker** [comment]
> As i know, only full installing of new version. Last build of version 1607 is 14393.3300

By full installation, that implies some kind of installation media, eg some ISO?

> I concur [...deleted...] operating system. See also the Note on the page from where you opened this issue ticket.

The note is not helpful concerning what I asked.

> I do not think this is a required information for that referenced page, because it may be mentioned somewhere else in the documentation.

Of course it's not required.  I just wrote/said "it would be **better** to have ..."  But after all, the aim of documentation is to inform people.  Putting related info in the doc makes it better.

**Comment by illfated** [comment]
Fair enough. Time to ask one of the insiders for more info about this topic.

@JasonGerend : Are you available to share some of your insights with us regarding this issue?

**Comment by illfated** [comment]
No new updates or feedback during the last year.

#please-close
