### ISSUE TITLE
Missing step?

### ISSUE THREAD

**Issue by rhaley-starfish** [MicrosoftDocs/windowsserverdocs#3433]
To install OpenSSH, start Settings then go to Apps &gt; Apps and Features &gt; Manage Optional Features.

I'm on Windows 10 1903 and the instructions should likely be:
To install OpenSSH, start Settings then go to Apps &gt; Apps and features &gt; Optional features &gt; Add a feature.

I say likely because when I followed the instructions, I couldn't find the server so I installed it with powershell. I realized afterwards it was likely under the "Add a feature" window before it was "added". 

What does "added" really mean??? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07417484-bd6d-e6f4-110e-e42c2428a369
* Version Independent ID: 844743a6-f67b-421f-9591-13da36b23b14
* Content: [Installation of OpenSSH For Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse#feedback)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* GitHub Login: @maertendMSFT

**Comment by illfated** [comment]
"added" in this scenario means that a feature needs to be enabled, unpacked and installed to be active and available.

Features not yet enabled reduces the amount of software update data needed to be installed via Windows Update or other patching methods.
