### ISSUE TITLE
Clustered File Server content need updated for WS2016 / WS2019 ready

### ISSUE THREAD

**Issue by yamorish** [MicrosoftDocs/windowsserverdocs#3435]
Please update target platform and some functionality improvement as needed. 
And please clarify that SMB loopback on SoFS share is supported from Windows Server 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4bdb280-5e16-2ed0-df99-5a47b3a4b888
* Version Independent ID: 6fce588c-267a-5d28-d7f7-f4fa5bad20a2
* Content: [Scale-Out File Server for application data overview](https://docs.microsoft.com/en-us/windows-server/failover-clustering/sofs-overview#feedback)
* Content Source: [WindowsServerDocs/failover-clustering/sofs-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/sofs-overview.md)
* Product: **windows-server**
* Technology: **storage-failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by NAO-MSFT** [comment]
I filed a pull request on behalf of you, then now reflected ;)
https://docs.microsoft.com/windows-server/failover-clustering/sofs-overview

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
