### ISSUE TITLE
1903 AVMA keys

### ISSUE THREAD

**Issue by DSPatrick** [MicrosoftDocs/windowsserverdocs#3438]
[Enter feedback here]
Where are the Windows Server, version 1903 AVMA keys?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 960f9460-e1de-949c-ae1a-ad24a34cc1c2
* Version Independent ID: c9b5b530-5a39-0136-fb9a-15389ccd6691
* Content: [Automatic virtual machine activation](https://docs.microsoft.com/en-us/windows-server/get-started-19/vm-activation-19)
* Content Source: [WindowsServerDocs/get-started-19/vm-activation-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/vm-activation-19.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by DSPatrick** [comment]
Does anyone know?

**Comment by JasonGerend** [comment]
Sorry we didn't have version 1903 listed for a while! We added mention to the AVMA keys section that the 1809 keys work for 1903 and 1909.
Thanks!
