### ISSUE TITLE
Missing exit codes in chkdsk documentation

### ISSUE THREAD

**Issue by ralish** [MicrosoftDocs/windowsserverdocs#3439]
The documentation on exit codes returned by `chkdsk` is out-of-date. For example, I saw exit code 5 earlier today, which appears to indicate that issues were found but successfully repaired online. I assume there's an exit code 4 and quite possibly others, but nothing above 3 is documented.

Related to #2189 but that's primarily pertaining to parameters supported by `chkdsk`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d990aaa2-95c8-7cf2-5bfe-87248b6df6b5
* Version Independent ID: 0871aa5d-0a6f-6383-cf92-6b33f2d745ea
* Content: [chkdsk](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/chkdsk)
* Content Source: [WindowsServerDocs/administration/windows-commands/chkdsk.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/chkdsk.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by ralish** [comment]
Saw exit code 11 today. Would be really nice to get this sorted.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by ralish** [comment]
@IngridAtMicrosoft Sorry, why is this being closed? The documentation has not been updated, and closing this issue just means myself and others have no way to know when it has been fixed. Knowing what the exit codes for `chkdsk` are is I think incredibly useful and important documentation, especially where the utility is being called by automated tooling.
