### ISSUE TITLE
Support multiple monitors on Android Remote Desktop Client

### ISSUE THREAD

**Issue by Jhuynh760** [MicrosoftDocs/windowsserverdocs#3441]
As a user it would be fantastic to be able to remote in with multiple monitors to help boost productivity.

**Comment by ant0nwax** [comment]
I would like to state that I reached the point, too. I have a dual monitor windows setup and a Android 10 based Client solution for RDP, I was reading an article that if you run RDP Client on Windows you can select use multiple monitors on the RDP Client. On the RDP Client for Android this setting is missing afaik... Do I have to use a Windows 10 Client Machine for connecting to my Workstation DUAL Screen Windows 10 PC or is there anything on the horizon? I also seen that Android did already manage to address more than one external monitor in the current release, just Software Developers did not yet see that :)

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
