### ISSUE TITLE
Confusing language "Remote Desktop Services Session Hosts an singe-session client operating systems"

### ISSUE THREAD

**Issue by MegaSolstice** [MicrosoftDocs/windowsserverdocs#3448]
The "Support for graphics processing unit (GPU) acceleration section has an oddly worded sentence that leaves more confusion than clarification.

> "Remote Desktop Services Session Hosts an singe-session client operating systems can take an advantage of a physical or a virtual GPUs presented to the operating system in many ways including the Azure GPU optimized virtual machine sizes, GPUs available to the physical RDSH server, RemoteFX vGPUs (Only on Windows Server 2016) and GPUS presented to the VMs by supported hypervisors."

1.  Is "singe-session" supposed to be "single-session" instead?

2.  What is this supposed to mean for Windows Server 2019 RDSH (Remote Desktop Session Host) for full RemoteDesktop User Sessions?

3.  What GPUs (vendors and actual GPUs) are supported?

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
