### ISSUE TITLE
Misleading title/summary causing search confusion

### ISSUE THREAD

**Issue by ChrisDodd** [MicrosoftDocs/windowsserverdocs#3456]
No information about getting ssh-agent to run, despite saying in the top it has such information

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 337c4ea8-1806-92a3-1501-b3ff5dde37bb
* Version Independent ID: c411d389-578d-57c6-cd6e-eaca7f2837db
* Content: [OpenSSH Server Configuration for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement#feedback)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* GitHub Login: @maertendMSFT

**Comment by illfated** [comment]
Are you certain about this? I would have thought it is shown, reading the PowerShell code block underneath [**Host key generation**](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement#host-key-generation):

> To make key authentication easy with an SSH server, run the following commands from an elevated PowerShell prompt:
```PowerShell

# Install the OpenSSHUtils module to the server. This will be valuable when deploying user keys.
Install-Module -Force OpenSSHUtils -Scope AllUsers

# Start the ssh-agent service to preserve the server keys
Start-Service ssh-agent

# Now start the sshd service
Start-Service sshd
```

I am specifically referring to the middle part:
```PowerShell
# Start the ssh-agent service to preserve the server keys
Start-Service ssh-agent
```

**Comment by ChrisDodd** [comment]
That is apparently somehow connected with server keys -- it doesn't say anything about how to load a client key into the agent (nor how to get the agent to serve those client keys to apllications)

**Comment by illfated** [comment]
The document page presumes that the reader is professional and knows that **PowerShell cmdlets** are necessary to use to set up and manage the Server services.

**Comment by ChrisDodd** [comment]
That's what's so confusing -- ssh-agent is for Clients, not Servers.

**Comment by illfated** [comment]
Well, sure, I agree with you on that part. Still, it is usually something the IT department would cover in a business workplace.

**Comment by ChrisDodd** [comment]
But this is the page a web search will direct a win10 home user trying to set up an ssh client.

**Comment by illfated** [comment]
Hmm. That is a pity. Couldn't those users just use OpenSSL packages, like the one from the http://slproweb.com/products/Win32OpenSSL.html (both 64-bit and 32-bit) page?

**Comment by illfated** [comment]
See Pull Request #4788 for a suggested improvement to this issue.
(The PR will close this issue ticket when it gets merged.)

**Comment by ChrisDodd** [comment]
> See Pull Request #4788 for a suggested improvement to this issue.
> (The PR will close this issue ticket when it gets merged.)

I guess it removes the reference to ssh-agent from the server key setup instructions, but doesn't add anything to the user key section (where it belongs).

**Comment by illfated** [comment]
> > See Pull Request #4788 for a suggested improvement to this issue.
> > (The PR will close this issue ticket when it gets merged.)
> 
> I guess it removes the reference to ssh-agent from the server key setup instructions, but doesn't add anything to the user key section (where it belongs).

@konstruktoid : Would you like to comment on this?

**Comment by konstruktoid** [comment]
This doesn't help?

https://github.com/MicrosoftDocs/windowsserverdocs/blob/915609996119d43920e830f0c325b33f8fe0092c/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md#user-key-generation

```
Remember that private key files are the equivalent of a password should be protected the same way you protect your password. To help with that, use ssh-agent to securely store the private keys within a Windows security context, associated with your Windows login. To do that, start the ssh-agent service as Administrator and use ssh-add to store the private key.
```

**Comment by illfated** [comment]
@ChrisDodd : any comments regarding the reply from **konstruktoid** ?

**Comment by illfated** [comment]
List of related issue tickets:

- #2747 **A better explanation can be found here** (Open)
- #3400 **Can't install the "OpenSSHUtils"** (Closed)
- #3806 **OpenSSHUtils is deprecated** (Open)
- #3970 **OpenSSH installation** (Closed)
- #4345 **OpenSSHUtils Not Needed** (Open)
- #4518 **Unable to configure OpenSSH for public key auth following docs** (Open)
- #4598 **Instructions provided ends with an error** (Open)
- #4622 **Out-of-date - OpenSSHUtils no longer available.** (Open)
- #4634 **More documentation required** (Open)
- #4690 **OpenSSHUtils install reference no longer valid** (Open)
- #4702 **OpenSSHUtils got unlisted from the PowerShell gallery** (Open)
- #4743 **Nope. First example errors out.** (Open)
- #4770 **Error when following instructions to install OpenSSHUtils** (Open)
- #4787 **OpenSSHUtils module does not exist** (Open)
- #5000 **Clarification needed** (Open)
- #5138 **These instructions do not work on Windows 10 20h2** (Open)
