### ISSUE TITLE
Not Enough Documentation 

### ISSUE THREAD

**Issue by lnorton89** [MicrosoftDocs/windowsserverdocs#3457]
Attempting to run `Set-VMSwitch` with the `-EnableSoftwareRsc` parameter does not work. Checking the documentation on the `Set-VMSwitch` cmdlet shows zero parameters with that name. What am I missing here? 

```
Set-VMSwitch : A parameter cannot be found that matches parameter name 'EnableSoftwareRsc'.
At line:1 char:48
+ ... -VMSwitch -Name "Virtual Switch (External)" -EnableSoftwareRsc $false
+                                                 ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-VMSwitch], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.HyperV.PowerShell.Commands.SetVMSwitchCommand
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 650c0cf9-30bf-48d0-0735-6476554b9323
* Version Independent ID: 339539c3-161a-de17-6895-d32f3ca23e2c
* Content: [Receive Segment Coalescing (RSC) in the vSwitch](https://docs.microsoft.com/en-us/windows-server/networking/technologies/hpn/rsc-in-the-vswitch?view=vsts#feedback)
* Content Source: [WindowsServerDocs/networking/technologies/hpn/rsc-in-the-vswitch.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/hpn/rsc-in-the-vswitch.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @shortpatti
* Microsoft Alias: **dacuo**

**Comment by illfated** [comment]
Certainly not documented in https://docs.microsoft.com/en-us/powershell/module/hyper-v/set-vmswitch?view=win10-ps , but then again, that page does not have any view option for Windows Server 2019.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
