### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by lukebarone** [MicrosoftDocs/windowsserverdocs#3459]
Please spell check. Adminisitrators is a weird word

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f26ab8e-4e08-c397-6b98-8a1937b9752a
* Version Independent ID: 7aeee835-12a9-73c3-b1f2-8cf9855c3719
* Content: [Deploy Folder Redirection with Offline Files](https://docs.microsoft.com/en-us/windows-server/storage/folder-redirection/deploy-folder-redirection#feedback)
* Content Source: [WindowsServerDocs/storage/folder-redirection/deploy-folder-redirection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/folder-redirection/deploy-folder-redirection.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
@lukebarone : As you can see, the Pull Request #3462 has been opened to correct the typo you found.
Thank you for contributing to make the documentation better.

**Comment by illfated** [comment]
#please-close
