### ISSUE TITLE
Install steps broken

### ISSUE THREAD

**Issue by ebmarquez** [MicrosoftDocs/windowsserverdocs#3469]
When I try to start-service sshd I get 
```
Start-Service : Cannot find any service with service name 'sshd'.
At line:1 char:1
+ Start-Service sshd
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (sshd:String) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.StartServiceCommand

 Get-Service -Name *sshd*

Status   Name               DisplayName
------   ----               -----------
Stopped  SshdBroker         SshdBroker

```
It looks like it's installed according to powershell.

```Powershell
 Get-WindowsCapability -Online -Name openssh*


Name         : OpenSSH.Client~~~~0.0.1.0
State        : Installed
DisplayName  : OpenSSH Client
Description  : OpenSSH-based secure shell (SSH) client, for secure key management and access to remote machines.
DownloadSize : 1316207
InstallSize  : 5300763

Name         : OpenSSH.Server~~~~0.0.1.0
State        : Installed
DisplayName  : OpenSSH Server
Description  : OpenSSH-based secure shell (SSH) server, for secure key management and access from remote machines.
DownloadSize : 1291185
InstallSize  : 4947581
```

Windows and Powershell version.
```
$PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      18362  145


[System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      18363  0

```

**Comment by illfated** [comment]
It seems you have opened an issue ticket without any reference to a relevant documentation page. Please be aware that this site is primarily used for Microsoft documentation improvement suggestions and corrections, when there is incorrect information or a need for additional information to provide a working documentation page for IT professional workers using Microsoft Windows Server software. Without a Microsoft Windows Server documentation page reference, it is less likely that you will get a reply or follow-up from the MS Docs team members.

Have you tried looking up pages via web search to see if there are others who might have found answers to your issue question, like the following?
- https://www.bing.com/search?q=start-service+sshd
- https://github.com/PowerShell/Win32-OpenSSH/issues/907
- https://social.technet.microsoft.com/Forums/windows/en-US/5347fb87-5b90-4cf0-a80f-12d759af53a4/having-trouble-getting-the-builtin-openssh-server-to-work?forum=win10itprogeneral

**Comment by ebmarquez** [comment]
I have searched, it seems that something is broken in windows on this machine.  I'm going to pursue this with wdg.

**Comment by illfated** [comment]
Fair enough, feel free to close this issue ticket, unless there is a related Microsoft Docs Windows Server documentation page for which you want to suggest any improvements.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
