### ISSUE TITLE
if the "Configure Automatic Updates" policy setting is disabled, this policy has no effect.

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/windowsserverdocs#3472]
This doesn't appear to be the case when the SCCM client is installed.  Even if you set Configure Automatic Updates to Disabled, the SCCM client is still not able to control this registry value due to a GPO conflict and you get the error in WUAHandler: Group policy settings were overwritten by a higher authority (Domain Controller) to: Server https://fqdn and Policy ENABLED

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6598315d-3135-1144-3fa7-605bf9cb50a3
* Version Independent ID: 692a50dc-2892-69ec-f831-b17925fc3cc8
* Content: [Step 4 - Configure Group Policy Settings for Automatic Updates](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/deploy/4-configure-group-policy-settings-for-automatic-updates#specify-intranet-microsoft-update-service-location)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/deploy/4-configure-group-policy-settings-for-automatic-updates.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/deploy/4-configure-group-policy-settings-for-automatic-updates.md)
* Product: **windows-server**
* Technology: **manage-wsus**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
