### ISSUE TITLE
User privileges for operations on Highly Available Virtual Machines

### ISSUE THREAD

**Issue by KrupalJoshi** [MicrosoftDocs/windowsserverdocs#3473]
Hi,

Could you please provide information regarding what user rights/privileges required to perform operation on Highly Available Virtual Machines in Failover Hyper-V cluster? Operations like list HA VMs, Snapshot / checkpoint for HA VMs?

Thanks,
Krupal

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
