### ISSUE TITLE
Image in article is unreadable

### ISSUE THREAD

**Issue by tomdan-MSFT** [MicrosoftDocs/windowsserverdocs#3474]
The image listed below this section is unreadable :

The following diagram illustrates the workflow process for the different scenarios when deploying Always On VPN:

Can someone please update the image so it's readable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ae99a07-be14-63a1-d5bb-1e92f9cde0b7
* Version Independent ID: ed219e40-9a0e-794b-110d-d82418d456e7
* Content: [Deploy Always On VPN](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-deployment)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-deployment.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by illfated** [comment]
Duplicate ticket (or very, very similar to) issue ticket **#3178**
(with suggested solutions in the comments).

See the following comments:
- https://github.com/MicrosoftDocs/windowsserverdocs/issues/3178#issuecomment-525819269
- https://github.com/MicrosoftDocs/windowsserverdocs/issues/3178#issuecomment-545659464

**Comment by illfated** [comment]
@tomdan-MSFT : do you find the issue ticket #3178 to be helpful and that it covers the same issue as this ticket page?

**Comment by illfated** [comment]
There is already a larger size image in the GitHub WindowsServerDocs repository:
- https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/media/Always-On-Vpn/always-on-vpn-deployment-workflow.png

![Flow chart of the Always On VPN deployment workflow](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/media/Always-On-Vpn/always-on-vpn-deployment-workflow.png?raw=true)

The actual issue with this image in that page is that it only links to itself, not to the larger image (which it used to do 2 years ago). I will suggest linking the larger image instead via a Pull Request to the page in question.

**Comment by shortpatti** [comment]
Unfortunately, the writer who replaced me didn't understand the HTML tags so they removed them and now all you see in the topic is the "thumbnail" image and you can't click on it for the larger image.   Sad, really!  

It's just unfortunate that a former employee has to help straighten this out now after almost 2 years after the topic was updated/improved.

**Comment by illfated** [comment]
(Ref. #3943 )

**Comment by illfated** [comment]
(Ref. #3886 )
