### ISSUE TITLE
Server Cmdlets in Windows Powershell link inside note is BROKEN, please correct.

### ISSUE THREAD

**Issue by vicslive** [MicrosoftDocs/windowsserverdocs#3477]
when I click on the 3rd item insite the note, for Server Cmdlets, link is broken, goes nowhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab5ad1ab-fd26-a345-1734-07d0181ac11a
* Version Independent ID: 8224fe1d-0d39-e7b7-b96d-70932ca3797a
* Content: [IP Address Management (IPAM)](https://docs.microsoft.com/en-us/windows-server/networking/technologies/ipam/ipam-top#feedback)
* Content Source: [WindowsServerDocs/networking/technologies/ipam/ipam-top.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/ipam/ipam-top.md)
* Product: **windows-server**
* Technology: **networking-ipam**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by illfated** [comment]
Thank you for making a new issue on this.
There is an old comment on a closed issue ticket,
noting that the link was broken again after being fixed more than a year ago:
- https://github.com/MicrosoftDocs/windowsserverdocs/issues/608

The old issue page concludes that the correct link should be:
- https://docs.microsoft.com/en-us/powershell/module/ipamserver/?view=win10-ps

I will open a PR to get it fixed ASAP.

**Comment by illfated** [comment]
Looks like one of the mass update commits reverted that link correction from April 2018.
I can only presume that someone used an outdated repository to mass update all the pages.
