### ISSUE TITLE
Windows AD use case / best pratice docs

### ISSUE THREAD

**Issue by oldunclez** [MicrosoftDocs/windowsserverdocs#3479]
It seems that there are many many many docs about how to install AD and its related concepts (such as , forest , OU  ...) in the internet. 
I wonder that if there is  any docs "all  only" about  windows AD use cases / best pratices, such as :

1. how to config a domain user , so he/she can logon any computer (within the domain) (locally or remotely),  once login , it will fetch all his/her data files and programs 
2. how to "push" a  software to domain client computers ,and then install it sliently ,
3. how to change all the RDP service  setting of all domain client computers ?
4.  and so on  ..... 
    
Thank you .

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
