### ISSUE TITLE
Unclear which value is used with  MinPollInterval, MaxPollInterval and SpecialPollIntervall since Windows build 1702

### ISSUE THREAD

**Issue by Kriegel** [MicrosoftDocs/windowsserverdocs#3480]
„New for build 1702, SpecialPollInterval is contained by the MinPollInterval and MaxPollInterval Config registry values.“

If i set MinPollInterval = 6,  MaxPollInterval = 12  and SpecialPollIntervall = 3600 to the registry

If I call  w32tm.exe with the parameter 0x8 or 0x9 like so /manualpeerlist:"[server1],0x9 
Which value is used then?

**Comment by trinhan87** [comment]
> „New for build 1702, SpecialPollInterval is contained by the MinPollInterval and MaxPollInterval Config registry values.“
> 
> If i set MinPollInterval = 6, MaxPollInterval = 12 and SpecialPollIntervall = 3600 to the registry
> 
> If I call w32tm.exe with the parameter 0x8 or 0x9 like so /manualpeerlist:"[server1],0x9
> Which value is used then?
