### ISSUE TITLE
Please update article to include supported options for Server 2019

### ISSUE THREAD

**Issue by alexlushsevernunival** [MicrosoftDocs/windowsserverdocs#3488]
Please update article to include supported options for Server 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c4bb2d4-9b81-b153-6936-3ca0f95bf631
* Version Independent ID: 968f574d-3be8-2af6-7470-d4e1f65b4a48
* Content: [Remotely manage Hyper-V hosts](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/remotely-manage-hyper-v-hosts?source=docs#feedback)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/Remotely-manage-Hyper-V-hosts.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/Remotely-manage-Hyper-V-hosts.md)
* Service: **na**
* Product: **windows-server**
* Technology: **compute-hyper-v**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by kx001001** [comment]
I believe this article is also fit to Windows Server 2019, I just tried same between Server 2019 and Win 10, and it works well even it's in workgroup.

**Comment by alexlushsevernunival** [comment]
Yes, in my experience anywhere that Server 2016 is mentioned Server 2019 is also applicable. We just need the relevant team inside MS to confirm this and get it added to the docs.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
