### ISSUE TITLE
@echo off

### ISSUE THREAD

**Issue by kimrqwreswf34** [MicrosoftDocs/windowsserverdocs#3489]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1bd2afb-c69f-7032-6331-a44599b55ad5
* Version Independent ID: c206ae8f-d626-b779-a893-7eb7ceaf719d
* Content: [Command-Line Syntax Key](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/command-line-syntax-key)
* Content Source: [WindowsServerDocs/administration/windows-commands/command-line-syntax-key.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/command-line-syntax-key.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
`@echo off` is already covered in the article page about `echo` :
- https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/echo#examples

I think we can safely presume that this ticket can be closed (unless the author has any actual suggestions for improving this article).

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
