### ISSUE TITLE
Rendering Issue with "Before You Install Windows Server Essentials" page

### ISSUE THREAD

**Issue by bloudraak** [MicrosoftDocs/windowsserverdocs#3495]
It seems there is a rendering issue on the following page:

https://docs.microsoft.com/en-us/windows-server-essentials/install/before-you-install-windows-server-essentials

It looks something as follows:

<img width="1007" alt="Screen Shot 2019-11-09 at 11 24 16" src="https://user-images.githubusercontent.com/622724/68533935-c5f1a080-02e3-11ea-9fb2-5bd5a8effb6a.png">

I'm assuming the gray box with `[!IMPOARTANT]` should be rendered as HTML rather than a code block.

**Comment by illfated** [comment]
Well spotted, thank you for reporting this. It is the result from adding a MarkDown (MD) code block before & after the affected text, which should instead have been rendered as a normal [!IMPORTANT] MD Note blurb.

Current MD source text (https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/EssentialsDocs/install/Before-You-Install-Windows-Server-Essentials.md):
```
~~~
> [!IMPORTANT]
>  Before you install  Windows Server Essentials on a pre-existing computer, we recommend that you fully format and then repartition the hard disks of the pre-existing computer. By formatting and repartitioning the hard disks, you remove the possibility that hidden partitions remain on the hard disks.  
~~~
```
What it needs to look like to work as intended & expected:
```
> [!IMPORTANT]
>  Before you install  Windows Server Essentials on a pre-existing computer, we recommend that you fully format and then repartition the hard disks of the pre-existing computer. By formatting and repartitioning the hard disks, you remove the possibility that hidden partitions remain on the hard disks.  
```
Github MarkDown view of the correct format (unfortunately not showing the full HTML version of the Note blurb):

> [!IMPORTANT]
>  Before you install  Windows Server Essentials on a pre-existing computer, we recommend that you fully format and then repartition the hard disks of the pre-existing computer. By formatting and repartitioning the hard disks, you remove the possibility that hidden partitions remain on the hard disks.  

This is a simple task to amend. I will have a Pull Request ready shortly to remove the incorrect code block to restore the MD Note blurb.
