### ISSUE TITLE
shield an existing vm

### ISSUE THREAD

**Issue by thesearenotthedroidsyouarelookingfor** [MicrosoftDocs/windowsserverdocs#3500]
How do you shield an existing vm without using VMM. we have setup a HGS server and guarded hosts but would like to enable shielding for 1 vm and there appears to be no info on the process if your not using VMM?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ffc80d-5fb9-f7de-5c6d-44a1ff37c81b
* Version Independent ID: 7bc08841-1960-541e-370b-bd1c8218498e
* Content: [Deploy shielded VMs](https://docs.microsoft.com/en-gb/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-configuration-scenarios-for-shielded-vms-overview)
* Content Source: [WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-configuration-scenarios-for-shielded-vms-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-configuration-scenarios-for-shielded-vms-overview.md)
* Product: **windows-server**
* Technology: **security-guarded-fabric**
* GitHub Login: @rpsqrd

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
