### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by PeterVanEunen** [MicrosoftDocs/windowsserverdocs#3506]
The URL links above "BiitOps Product Page" and "free trial" Product the below error

Page not found
No umbraco document matches the url '/solutions/changes-for-wac'.
This page can be replaced with a custom 404. Check the documentation for "custom 404".

This page is intentionally left ugly ;-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec743534-9a53-a1c3-a1fc-afe6e71be0d8
* Version Independent ID: bada4428-35ac-8c98-4b2b-d30df62128ca
* Content: [Windows Admin Center SDK Case Study - BiitOps](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/extend/case-studies/biitops#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/extend/case-studies/biitops.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/extend/case-studies/biitops.md)
* Product: **windows-server**
* Technology: **extend**
* GitHub Login: @daniellee-msft
* Microsoft Alias: **jol**

**Comment by illfated** [comment]
Wow, haha, you were not kidding with that last line
(at first I thought you added the smiley to point out the irony, but it is on the 404 page).

See sample image below:
***
![image](https://user-images.githubusercontent.com/38162891/68738626-179d7200-05e7-11ea-88a8-9a027a4426cf.png)
***

The issue remains:: both links in the text above the image on the page https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/extend/case-studies/biitops are broken, they go to the 404 page shown above.

We need to find new links via the main page https://biitops.com/ .

**Comment by illfated** [comment]
OK, so in the meanwhile, the pages have changed quite a bit as well as supporting redirects from no longer existing pages.

Both links are now redirected to the landing page https://biitops.com/solutions/biitops-changes , which contains both of the options suggested in the text (although in separate sections of the page).

New links:
- https://biitops.com/solutions (instead of "Products")
- https://biitops.com/solutions/biitops-changes (instead of 'changes-for-wac')

**Comment by illfated** [comment]
There you go. The page and URLs will be corrected when PR #4961 gets merged.
