### ISSUE TITLE
Repeat or typo

### ISSUE THREAD

**Issue by PatrickLownds** [MicrosoftDocs/windowsserverdocs#3514]
Under prerequisites (1st bullet):

Configured security groups, log file locations, and dynamic DNS registration You must prepare your datacenter for Network Controller deployment, which requires "one or more computers or VMs" and "one computer or VM"

Says the same thing twice?.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaef2f0a-a246-ca79-59ba-1def1605a883
* Version Independent ID: 659e4847-2154-4ce4-893d-0f9f8eb1620a
* Content: [Plan a Software Defined Network Infrastructure](https://docs.microsoft.com/en-us/windows-server/networking/sdn/plan/plan-a-software-defined-network-infrastructure#feedback)
* Content Source: [WindowsServerDocs/networking/sdn/plan/Plan-a-Software-Defined-Network-Infrastructure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/sdn/plan/Plan-a-Software-Defined-Network-Infrastructure.md)
* Service: **virtual-network**
* Product: **windows-server**
* Technology: **networking-sdn**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by illfated** [comment]
Fair enough, it does look quite redundant, although I suspect that the intention is different, even though it is written in a rather awkward form.

Quote:

> **Configured security groups, log file locations, and dynamic DNS registration** You must prepare your datacenter for Network Controller deployment, which requires one or more computers or VMs and one computer or VM. Before you can deploy Network Controller, you must configure the security groups, log file locations (if needed), and dynamic DNS registration. If you have not prepared your datacenter for Network Controller deployment, see Installation and Preparation Requirements for Deploying Network Controller for details.

My best guess is that the intention is to explain that you need some amount of computers or VMs to simulate a computer network, data center or cluster. Secondly, you need a single computer or VM as your primary testing space or workstation. (Apologies for any misinterpretations or ignorance of the topic at hand.)

If someone could confirm in detail exactly what the requirements are for this scenario, it should be an easy task to create a PR to suggest a better phrasing for that sentence.

**Comment by illfated** [comment]
@eross-msft : I believe the referred article needs to have its author changed, as well as addressing the original issue reported above. I can easily manage that part directly.

Do you have any contacts who may be able to suggest some likely intentions under the first bullet point in the **Prerequisites** section?
- https://docs.microsoft.com/en-us/windows-server/networking/sdn/plan/plan-a-software-defined-network-infrastructure#prerequisites

(I also have the idea to add a hidden line break between the bold bullet point "title" line and the standard text, it just would be good to have some suggestions for the missing words before I create the PR.)
