### ISSUE TITLE
Start command missing docs for /elevate

### ISSUE THREAD

**Issue by BrandonDyer64** [MicrosoftDocs/windowsserverdocs#3520]
The `start` command, in the docs, seems to leave out `/elevate` from its list of flags.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f381cec-d200-7862-a0c3-afeeb617c279
* Version Independent ID: 08873192-45b4-fc90-aa47-c8780d2a395f
* Content: [start](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/start.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/start.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Looking forward to final review of PR #3521 by the document author or manager.
(PR #3521 should close this issue ticket, but does not have a ticket closure reference.)
