### ISSUE TITLE
How do i get  

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windowsserverdocs#3522]
How to get the tpmtool for windows 10 1909  to  get complete details about TPM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e06bc95d-bdae-ac58-be99-1b958f6b04d7
* Version Independent ID: 3051fa92-282e-7caa-2ae4-74367e9940c8
* Content: [tpmtool](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/tpmtool#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/tpmtool.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/tpmtool.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @ashleytqy
* Microsoft Alias: **ashleytqy**

**Comment by Harrioson** [comment]
Microsoft’s OneDrive service gives you access to store 
your files on the cloud and retrieve them whenever you need them.
https://www.techsovibe.com/how-to-access-onedrive/

**Comment by RAJU2529** [comment]
please upload TPMPOOL.exe    and share the link
