### ISSUE TITLE
Missing Instructions on to do a clean install

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/windowsserverdocs#3523]
While this page mentions that a clean install is an option, it does provide instructions for how to do a clean install or provide a link to instructions for how to do a clean install. Please fix this. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32c85362-611d-a5b7-c227-1e1c0c3f566a
* Version Independent ID: a5075486-6647-0348-564b-fb8cef6daa08
* Content: [Install, upgrade, or migrate to Windows Server 2019](https://docs.microsoft.com/en-us/windows-server/get-started-19/install-upgrade-migrate-19)
* Content Source: [WindowsServerDocs/get-started-19/install-upgrade-migrate-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/install-upgrade-migrate-19.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
... while the ticket comment above is missing a "not" in "it does provide instructions for how to do a clean install" ...

Seems to be resolved by [**DCtheGeek**](https://github.com/DCtheGeek) on Jul 21, 2020, 11:53 AM PDT, in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/53e30923ae5cdb35a1245958bff2f1c3317e413c (file link https://github.com/MicrosoftDocs/windowsserverdocs/commit/53e30923ae5cdb35a1245958bff2f1c3317e413c#diff-02231a570056a111a8b67ca6feade62ccc84f266c588d43667640b7c0133e316) :

```diff
  @@ -21,7 +21,7 @@ Is it time to move to a newer version of Windows Server? Depending on what you'r
  
  ## Clean install
  
- The simplest way to install Windows Server is to perform a clean installation, where you install on a blank server or overwrite an existing operating system. That is the simplest way, but you will need to back up your data first and plan to reinstall your applications. There are a few things to be aware of, such as system requirements, so be sure to check the details for [Windows Server 2019](https://go.microsoft.com/fwlink/?linkid=2006124), [Windows Server 2016](https://go.microsoft.com/fwlink/?LinkID=825558), [Windows Server 2012 R2](https://technet.microsoft.com/library/dn303418), and [Windows Server 2012](https://technet.microsoft.com/library/jj134246.aspx).
+ The simplest way to install Windows Server is to perform a clean installation, where you install on a blank server or overwrite an existing operating system. That is the simplest way, but you will need to back up your data first and plan to reinstall your applications. There are a few things to be aware of, such as system requirements, so be sure to check the details for [Windows Server 2019](https://go.microsoft.com/fwlink/?linkid=2006124), [Windows Server 2016](https://go.microsoft.com/fwlink/?LinkID=825558), [Windows Server 2012 R2](/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn303418(v=ws.11)), and [Windows Server 2012](/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/jj134246(v=ws.11)).
  
  ## In-place upgrade
  
  @@ -31,12 +31,12 @@ For step-by-step guidance on upgrading, review the [Windows Server upgrade conte
  
  ## Cluster OS rolling upgrade
  
- Cluster OS Rolling Upgrade enables an administrator to upgrade the operating system of the cluster nodes from Windows Server 2012 R2 and Windows Server 2016 without stopping the Hyper-V or the Scale-Out File Server workloads. This feature allows you to avoid downtime which could impact Service Level Agreements. This new feature is discussed in more detail at [Cluster operating system rolling upgrade](https://technet.microsoft.com/windows-server-docs/failover-clustering/cluster-operating-system-rolling-upgrade).
+ Cluster OS Rolling Upgrade enables an administrator to upgrade the operating system of the cluster nodes from Windows Server 2012 R2 and Windows Server 2016 without stopping the Hyper-V or the Scale-Out File Server workloads. This feature allows you to avoid downtime which could impact Service Level Agreements. This new feature is discussed in more detail at [Cluster operating system rolling upgrade](/windows-server/failover-clustering/cluster-operating-system-rolling-upgrade).
  
  ## Migration
  
  Windows Server migration is when you move one role or feature at a time from a source computer that is running Windows Server to another destination computer that is running Windows Server, either the same or a newer version. For these purposes, migration is defined as moving one role or feature and its data to a different computer, not upgrading the feature on the same computer. 
  
  ## License conversion
  
- In some operating system releases, you can convert a particular edition of the release to another edition of the same release in a single step with a simple command and the appropriate license key. This is called **license conversion**. For example, if your server is running Windows Server 2016 Standard, you can convert it to Windows Server 2016 Datacenter. Keep in mind that while you can move up from Server 2016 Standard to Server 2016 Datacenter, you are unable to reverse the process and go from Datacenter to Standard. In some releases of Windows Server, you can also freely convert among OEM, volume-licensed, and retail versions with the same command and the appropriate key.
+ In some operating system releases, you can convert a particular edition of the release to another edition of the same release in a single step with a simple command and the appropriate license key. This is called **license conversion**. For example, if your server is running Windows Server 2016 Standard, you can convert it to Windows Server 2016 Datacenter. Keep in mind that while you can move up from Server 2016 Standard to Server 2016 Datacenter, you are unable to reverse the process and go from Datacenter to Standard. In some releases of Windows Server, you can also freely convert among OEM, volume-licensed, and retail versions with the same command and the appropriate key.
```

![image](https://user-images.githubusercontent.com/38162891/100483872-a26de380-30fa-11eb-9437-bde87015ec12.png)

**Comment by illfated** [comment]
#please-close

**Comment by rossmpersonal** [comment]
I still do not think the issue is fix. It describes the requirements, prerequisites, and considerations for a clean install but does not provide instructions on how to execute a clean install. This needs to be fixed.

**Comment by illfated** [comment]
Very well, fair enough. Would you like to open a new ticket, using a link based on the existing content?

Updated ticket link for the page "Install, upgrade, or migrate to Windows Server":
- https://github.com/MicrosoftDocs/windowsserverdocs/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%208a9b52be-37b3-6f1f-21f1-bdb9e9036eb0%0A*%20Version%20Independent%20ID%3A%2089501699-9fd7-12a2-fa42-9564916aa78b%0A*%20Content%3A%20%5BInstall%2C%20upgrade%2C%20or%20migrate%20to%20Windows%20Server%202019%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fwindows-server%2Fget-started-19%2Finstall-upgrade-migrate-19)%0A*%20Content%20Source%3A%20%5BWindowsServerDocs%2Fget-started-19%2Finstall-upgrade-migrate-19.md%5D(https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fwindowsserverdocs%2Fblob%2Fmaster%2FWindowsServerDocs%2Fget-started-19%2Finstall-upgrade-migrate-19.md)%0A*%20Product%3A%20**windows-server**%0A*%20Technology%3A%20**getting-started**%0A*%20GitHub%20Login%3A%20%40JasonGerend%0A*%20Microsoft%20Alias%3A%20**jgerend**

**Comment by rossmpersonal** [comment]
1. The description of the original ticket clearly described that this was the issue. This is not a separate issue. There is no reason to create a new ticket. Please feel free to prove me wrong.
2. As far as I can tell there is not existing content that covers this. Hence the reason for opening this ticket. Therefore, using a link based on existing content is not possible.

**Comment by illfated** [comment]
#please-open

**Comment by illfated** [comment]
#please-reopen

**Comment by illfated** [comment]
#reopen
