### ISSUE TITLE
Support for more recent Windows 10 versions?

### ISSUE THREAD

**Issue by Kaedin** [MicrosoftDocs/windowsserverdocs#3528]
Hi there,

Does this article also cover the later Windows 10 versions such as 1809, 1903 and 1909? If not, is there a plan to update this article accordingly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c781d9a-6c94-d7f3-61dd-9a76151f8aed
* Version Independent ID: f172bbc7-3054-ef6d-707f-7c44a32db66c
* Content: [Optimizing Windows 10, version 1803, for a Virtual Desktop Infrastructure (VDI) role](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-vdi-recommendations-1803)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-vdi-recommendations-1803.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-vdi-recommendations-1803.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo, robsmi**

**Comment by jaimeo** [comment]
Excellent reminder. Let me check with the PM for this....

**Comment by jaimeo** [comment]
Turns out we have an update in the pipeline!

**Comment by Kaedin** [comment]
Good news, thank you! Even better news would be if there's any publication schedule available? 😊 Users would have a lot more confidence with switching/deploying solutions based on the latest offering while having documentation in line with the product releases. Could help with throubleshooting too! 🤩

**Comment by illfated** [comment]
This is pleasant to read, after thinking for so long that there is a huge backlog for online OS documentation. Even though I am a lowly IT supporter, it is still very useful to read up on OS news.

**Comment by jaimeo** [comment]
BTW, I just got a draft in hand and we're starting the process to edit and move to publishing.

**Comment by Kaedin** [comment]
@jaimeo Thank you for updating the optimization guidelines for 1909!
