### ISSUE TITLE
Issue with Active Directory integrated RBAC

### ISSUE THREAD

**Issue by svsc99** [MicrosoftDocs/windowsserverdocs#3529]
I'm currently working on implementing WAC in our AD envoiornment. Therefor i generated the zip file (it differs from the content in the documentation), customized the powershell, copied the components with the Powershell script and executed the "InstallJeaFeature.ps1". It seems to complete without errors, but the "Get-DscConfigurationStatus" shows the status Failure.
..
Name          : Microsoft.Sme.PowerShell
PSVersion     : 5.1
StartupScript :
RunAsUser     :
Permission    : NT-AUTORITÄT\INTERAKTIV AccessAllowed, VORDEFINIERT\Administrators AccessAllowed, VORDEFINIERT\Remote Management Users AccessAllowed

Unfortunatley i can not access the Servers using WAC with my test account which is member of one of the AD groups.

How can i check, if the correct AD groups were added? If I got this right, there shouldn't have been created any local groups.

I noticed one thing, after i generated the zip archive and startet customizing the Powershell script i noticed that the mentioned line:
'$env:COMPUTERNAME\Windows Admin Center Administrators'
does look a little different in my script:
"@{'Windows Admin Center Administrators' = @{RoleCapabilities =...
There is no COMPUTERNAME before the local group name.

Can someone help me?

**Comment by Harrioson** [comment]
Microsoft’s OneDrive service gives you access to store 
your files on the cloud and retrieve them whenever you need them.
https://www.techsovibe.com/how-to-access-onedrive/

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
