### ISSUE TITLE
problem when I installing WAC on Windows Server 2019

### ISSUE THREAD

**Issue by anggirg** [MicrosoftDocs/windowsserverdocs#3533]
Can you help me? I have a problem when I installing WAC on Windows Server 2019, show error message "windows admin center this software is not supported on domain controller machines"

**Comment by illfated** [comment]
According to https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/understand/what-is :
***
## How does Windows Admin Center work?

Windows Admin Center runs in a web browser and manages Windows Server 2019, Windows Server 2016, Windows Server 2012 R2, Windows Server 2012, Windows Server 2008 R2, Windows 10, and more through the **Windows Admin Center gateway** installed on Windows Server or Windows 10. The gateway manages servers by using Remote PowerShell and WMI over WinRM. The gateway is included with Windows Admin Center in a single lightweight .msi package that you can [download](https://aka.ms/windowsadmincenter).

The Windows Admin Center gateway, when published to DNS and given access through corresponding corporate firewalls, lets you securely connect to, and manage, your servers from anywhere with Microsoft Edge or Google Chrome.
***
You need to implement **Windows Admin Center gateway** on either the server or a connected Windows 10 computer. Windows Admin Center (browser page) should be used from a Windows 10 client computer, not the server.
