### ISSUE TITLE
Nested Shares

### ISSUE THREAD

**Issue by FrankyFromHR** [MicrosoftDocs/windowsserverdocs#3546]
We have a primary share that all of our data resides in, we also map some shares to folders directly in that same location. Storage Migration Manager doesn't appear to understand how to deal with this. It gives me a warning that I won't have enough space and then it fails to copy the files, just gives me a warning on the other shares. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c2d2cfd-cf69-3b4d-48bb-002f2816fc42
* Version Independent ID: 7e785f92-7042-809c-2740-56b8516d87f9
* Content: [Storage Migration Service frequently asked questions (FAQ)](https://docs.microsoft.com/en-us/windows-server/storage/storage-migration-service/faq)
* Content Source: [WindowsServerDocs/storage/storage-migration-service/faq.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-migration-service/faq.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @nedpyle
* Microsoft Alias: **nedpyle**

**Comment by nedpyle** [comment]
@steved0x I have no option to close this. Please close it.

**Comment by illfated** [comment]
#please-close

**Comment by sanglyb** [comment]
we have the same issue - nested shares not creating during migration process. We migrating standalone 2012R2 server to 2019 cluster. For all shares, that are made from folders, that were already shared, there are errors like:
`Error: -2147467259
Error Message: The resources must be online on the same node for this operation
Exception:    at Microsoft.StorageMigration.Common.ShareUtil.CreateShare(String serverName, String shareName, SHARE_INFO_502 shareInfo, ISmsEventProvider logger)
   at Microsoft.StorageMigration.Proxy.Service.Transfer.ShareCreationOperation.CreateOrUpdateEndpoint()
`

**Comment by nedpyle** [comment]
> we have the same issue - nested shares not creating during migration process. We migrating standalone 2012R2 server to 2019 cluster. For all shares, that are made from folders, that were already shared, there are errors like: `Error: -2147467259 Error Message: The resources must be online on the same node for this operation Exception: at Microsoft.StorageMigration.Common.ShareUtil.CreateShare(String serverName, String shareName, SHARE_INFO_502 shareInfo, ISmsEventProvider logger) at Microsoft.StorageMigration.Proxy.Service.Transfer.ShareCreationOperation.CreateOrUpdateEndpoint() `

sanglyb - I need you to create an MS Support cases on this issue, it's not expected & we need to investigate your config. If it turned out to be a bug there will be no charge for the case.
