### ISSUE TITLE
Dead end page

### ISSUE THREAD

**Issue by Moe1976** [MicrosoftDocs/windowsserverdocs#3548]
the link to "Network Switch Team Cmdlets in Windows PowerShell" is leading to dead end webpage.
https://docs.microsoft.com/en-us/powershell/module/network-switch-team/index?redirectedfrom=MSDN

 404 - Page not found 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9af6298a-44a5-255f-f459-8151878492a0
* Version Independent ID: 8a0de308-4ee0-a603-11d3-379ce995a993
* Content: [Hyper-V Virtual Switch](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v-virtual-switch/hyper-v-virtual-switch)
* Content Source: [WindowsServerDocs/virtualization/hyper-v-virtual-switch/Hyper-V-Virtual-Switch.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v-virtual-switch/Hyper-V-Virtual-Switch.md)
* Product: **windows-server**
* Technology: **networking-hv-switch**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by illfated** [comment]
Oh. I think I can see what has happened. The page seems to be deleted, in favor of a new hierarchical layout of the links.
https://docs.microsoft.com/en-us/powershell/module/netswitchteam/?view=win10-ps is also dead (404).

There are some other links to choose from, but I am too uncertain about which one can be used to replace it:
- https://docs.microsoft.com/en-us/powershell/module/netswitchteam/new-netswitchteam
- https://docs.microsoft.com/en-us/powershell/module/netswitchteam/get-netswitchteam
- https://docs.microsoft.com/en-us/powershell/module/netswitchteam/add-netswitchteammember
- https://docs.microsoft.com/en-us/powershell/module/netswitchteam/remove-netswitchteam
- https://docs.microsoft.com/en-us/powershell/module/netswitchteam/rename-netswitchteam

Please note that the link named "**netswitchteam**" in the dynamic tree content on the left side of the page is the dead (404) link.

**Comment by illfated** [comment]
New and working link in this page:
- https://docs.microsoft.com/en-us/powershell/module/netswitchteam/new-netswitchteam?view=win10-ps

- Resolved in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/7bd7fd09dbf324c7c03296ed0186e587a67af2e7 (file link https://github.com/MicrosoftDocs/windowsserverdocs/commit/7bd7fd09dbf324c7c03296ed0186e587a67af2e7#diff-b2770f84dc73b6f027ded0106fa42cd699237700e5641e739758390390f24f8c)

- Updated in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/a6c8e6fc6afc019f2b25b6bffaa234076766f6b6 (Hyper-V-Virtual-Switch.md file link https://github.com/MicrosoftDocs/windowsserverdocs/commit/a6c8e6fc6afc019f2b25b6bffaa234076766f6b6#diff-b2770f84dc73b6f027ded0106fa42cd699237700e5641e739758390390f24f8c)

**Comment by illfated** [comment]
Thank you for reporting the issue, @Moe1976. Keep up the good work.

**Comment by illfated** [comment]
#please-close
