### ISSUE TITLE
Cannot uninstall 

### ISSUE THREAD

**Issue by MythreyaK** [MicrosoftDocs/windowsserverdocs#3558]
I am unable to uninstall OpenSSH that is pre-packaged into the OS (the one under `C:\Windows\system32\OpenSSH`). The powershell prompts do not help.

```
PS C:\Windows\system32\OpenSSH> Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'

Name  : OpenSSH.Client~~~~0.0.1.0
State : NotPresent

Name  : OpenSSH.Server~~~~0.0.1.0
State : NotPresent
```

But the System32 folder is still present. Should I just 'own up' the OpenSSH dir in Sys32 and just delete it? I want to install the latest one from GitHub. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07417484-bd6d-e6f4-110e-e42c2428a369
* Version Independent ID: 844743a6-f67b-421f-9591-13da36b23b14
* Content: [Installation of OpenSSH For Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse#feedback)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* GitHub Login: @maertendMSFT

**Comment by illfated** [comment]
You could check to see if your local Settings UI can confirm that it is not installed first, just to see if your Windows setup is OK or messed up.

**Apps > Apps and Features > Manage Optional Features**
(browse the list of features to see if OpenSSH is in the list or not)

**Comment by MythreyaK** [comment]
Can confirm, it's not there.

**Comment by illfated** [comment]
Yes, it looks like you should be done uninstalling, so try installing the other version whenever you are ready to do so.
I don't know if you need to delete the old folder, so just decide for yourself if you want to install with or without.

**Comment by MythreyaK** [comment]
The issue is that the old folder still has the binaries, clashing with the new OpenSSH portable version I downloaded. 

The services, they're still there! I was thinking of replacing the contents in System32, but I do not have permissions to write. I was a bit worried of messing up the permissions. 

Suggestions would be great! I plan to just nuke the `sys32/OpenSSH` folder and use the path to where I installed it.

**Comment by illfated** [comment]
Hmm, if your login user does not have access and does not get a message that you can opt to get access to the files, I really think you should log in as a user account with Administrator privileges and try the procedures again to see what you can achieve. I don't know what you have tried so far, but this sounds like you either should talk to someone more directly and get help while you are doing it (Microsoft Support) or ask more about the details in one of the Microsoft TechNet forums.

**Comment by illfated** [comment]
Also, please note that this repository is not a forum page.
This repository is primarily intended for improving the Microsoft Docs pages by reporting errors or issues, or suggesting improvements by reporting what should be written there instead.
Please also note that the tickets here in this repository should mainly be generated by commenting directly on the Microsoft Docs page itself, instead of continuing on to the Github pages. Commenting on the Microsoft Docs pages will generate a full reference in the opening comment, pointing both to the originating Microsoft Docs page as well as the Github source page available for editing & suggesting improvements by creating Pull Requests (PR).

**Comment by MythreyaK** [comment]
The 'Product Feedback' redirects me to UserVoice, for Windows Server (I am on a personal laptop, and I _am_ the administrator). I did have second thoughts on opening the issue here, but since the commands straight from the docs didn't work, I thought I'd raise it in the docs, hoping there would additional info/help on how to fix this issue.
