### ISSUE TITLE
Unclear section on ReFS compaction

### ISSUE THREAD

**Issue by ThomasRapidis** [MicrosoftDocs/windowsserverdocs#3560]
It just says that this is available "In this Fall's semi-annual release". In which year? In which Windows version? 2016? 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 621d449f-4675-d504-e266-5933283b61e7
* Version Independent ID: c2bd816f-d617-0ac2-7f9f-0f17c06b84bf
* Content: [Mirror-accelerated parity](https://docs.microsoft.com/en-us/windows-server/storage/refs/mirror-accelerated-parity)
* Content Source: [WindowsServerDocs/storage/refs/mirror-accelerated-parity.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/refs/mirror-accelerated-parity.md)
* Product: **windows-server**
* Technology: **storage-file-systems**
* GitHub Login: @gawatu
* Microsoft Alias: **gawatu**

**Comment by dknappettmsft** [comment]
Thanks for the feedback. I have clarified the Windows Server version and the change should be visible in a few hours.

#please-close
