### ISSUE TITLE
Setting to Enable Log File?

### ISSUE THREAD

**Issue by brunerd** [MicrosoftDocs/windowsserverdocs#3563]
Can you turn on some sort of log output in Microsoft Remote Desktop 10 for Mac?
There are no logging options in Preferences... I've also looked in ~/Library/Logs and ~/Library/Application Support and not found anything

For now I am using macOS's log facility to get some output:
log stream --level info --process $(pgrep "Microsoft Remote Desktop") 

Just curious if there is a config plist value that can be written to enable logging or is 'log' via Terminal all I got? Thanks!

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
