### ISSUE TITLE
Confusing

### ISSUE THREAD

**Issue by CoMMyCZ** [MicrosoftDocs/windowsserverdocs#3565]
The whole sentence "(Windows Server 2019) You cannot enable VMMQ (VmmqEnabled = False) while setting VrssQueueSchedulingMode to Dynamic. The VrssQueueSchedulingMode does not change to Dynamic once VMMQ is enabled."
is very confusing.

Does it imply that enabling VMMQ is done by setting VmmqEnabled property to false? 
Or you cannot set VrssQueueSchedulingMode to Dynamic when VmmqEnabled = false (which means that VMMQ is actually disabled not enabled)? 
Or "VrssQueueSchedulingMode = Dynamic" will not work VMMQ is enabled AND does not have specific driver support? But it will work just fine when the specific driver is present?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dca8239e-221a-1af2-068c-22d54a0e7aa9
* Version Independent ID: f6e8f8a0-c187-2370-64af-134846e6be5e
* Content: [Resolve vRSS issues](https://docs.microsoft.com/en-us/windows-server/networking/technologies/vrss/vrss-resolve-issues)
* Content Source: [WindowsServerDocs/networking/technologies/vrss/vrss-resolve-issues.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/vrss/vrss-resolve-issues.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by IngridAtMicrosoft** [comment]
Hi @CoMMyCZ.  Thank you for your response. This document no longer exists, and has been redirected to https://docs.microsoft.com/en-us/windows-server/networking/technologies/hpn/hpn-top.  Please provide a link to the document you were referring to.
