### ISSUE TITLE
Add Troubleshooting content

### ISSUE THREAD

**Issue by matheus-santoro** [MicrosoftDocs/windowsserverdocs#3566]
When following the steps to add the Cloud Witness, i received an error regarding WinRM. I have seen in other forums people with this same issue. Is there a workaround or solution for this error?

Only happens in Win 2019. Win 2016 works fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b112fd4-0bd2-ca4d-5d45-15396a00820a
* Version Independent ID: 34bffa79-1d32-aeeb-1577-8cc94808544c
* Content: [Deploy a cloud witness for a Failover Cluster](https://docs.microsoft.com/en-us/windows-server/failover-clustering/deploy-cloud-witness#configure-cloud-witness-as-a-quorum-witness-for-your-cluster)
* Content Source: [WindowsServerDocs/failover-clustering/deploy-cloud-witness.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/deploy-cloud-witness.md)
* Product: **windows-server**
* Technology: **storage-failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by RobatDS** [comment]
I had this issue, amongst others.  I haven't reproduced but I made the below two changes and then tried again and was able to successfully use the cloud witness.
1.  Run IPCONFIG /FLUSHDNS on both nodes.
2.  Run the command from the node which is the current cluster HOST server.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
