### ISSUE TITLE
In Regard to Building the IP address range expression

### ISSUE THREAD

**Issue by V3ertigo83** [MicrosoftDocs/windowsserverdocs#3567]
Company has built a very large expression/IP Range. We've come up against a hard limit on what the field will allow for a regex. Could you please mention or link to the article that says what the character limit is for a relying party authorization claim? Advise if it changes version to version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b8250d-93bb-dac2-9cea-6925347fcb25
* Version Independent ID: 32c0ef8c-6495-6afe-2c35-3128a1d7822c
* Content: [Access Control Policies in AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/access-control-policies-w2k12#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Access-Control-Policies-W2K12.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Access-Control-Policies-W2K12.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by V3ertigo83** [comment]
Any update here? 4 months seems a bit long in the tooth for a simple check of the string limit.

**Comment by illfated** [comment]
@V3ertigo83 : I can only offer my sympathy with your troubles concerning this topic. Unfortunately, I don't have any working experience from a scenario remotely like yours. I also notice that this issue ticket seems to have lost its reference appearance in the feedback section of the linked page, but I don't know why or how that happened. That being said, I would like to inform you that this repository is managed by a very small team, where the members currently don't have more capacity than to follow up direct suggestions for how the articles can be improved, provided that the community provides the content or specific written changes, either in the ticket itself or in Pull Requests containing the recommended changes. It is currently not possible to follow up support related questions or any requests to make changes, unless the requests contain the exact phrasing needed to perform the requested change. See also the feedback comment from one of the team members in your newer ticket #4108 .

That being said, I would like to recommend trying other venues of support, like the Microsoft TechNet Forums (https://social.technet.microsoft.com/Forums/), the Microsoft Developer Network Forums (https://social.msdn.microsoft.com/Forums/). or the Microsoft Tech Community Windows Server forum (https://techcommunity.microsoft.com/t5/windows-server/ct-p/Windows-Server) to ask for the same advice as you did above. You may even want to contact your local Microsoft Support tenant to ask if they will be able to answer your question.

We would also like to hear back from you regarding any helpful information related to this issue you are able to find, so if you can post any findings related to this issue topic here in this ticket, we appreciate the opportunity that would give us to find ways to improve the related articles, based on your findings and feedback.

Also, if you do have any questions regarding how to submit information you would like to see added to the current documentation, feel free to post more comments regarding this.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
