### ISSUE TITLE
It appears there is a spelling mistake on the page.

### ISSUE THREAD

**Issue by termanix** [MicrosoftDocs/windowsserverdocs#3568]
As said above, it seems like there is a spelling mistake under Resolution part a. On the page it says: 
"To ensure that the service is running, type Get-Service iphlpsc at a Windows PowerShell prompt."
However, the correct code seems to be "Get-Service iphlpsvc". The missing "v" is troublesome for inattentive users who simply want to Copy-Paste and Run. 
Sincerely Mehmetcan TOPAL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc4ae26d-d493-f50c-8493-79eeb66427a9
* Version Independent ID: 8b3792e7-dba5-d83d-54e5-a13b10dc8d37
* Content: [Identify and resolve Remote Access server operations problems](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/ras/monitoring-and-accounting/identify-and-resolve-remote-access-server-operations-problems#feedback)
* Content Source: [WindowsServerDocs/remote/remote-access/ras/monitoring-and-accounting/Identify-and-resolve-Remote-Access-server-operations-problems.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/ras/monitoring-and-accounting/Identify-and-resolve-Remote-Access-server-operations-problems.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by illfated** [comment]
Well spotted, thank you for reporting this typo. It is hardly noticeable in the sentence, or as you said, "troublesome for inattentive users who simply want to Copy-Paste and Run."

I will open a Pull Request to get this typo resolved.
