### ISSUE TITLE
"users\username\ssh\authorized_keys" should be "users\username\.ssh\authorized_keys"

### ISSUE THREAD

**Issue by p-equals-np** [MicrosoftDocs/windowsserverdocs#3570]
Note the leading "." appended to ".ssh".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 337c4ea8-1806-92a3-1501-b3ff5dde37bb
* Version Independent ID: c411d389-578d-57c6-cd6e-eaca7f2837db
* Content: [OpenSSH Server Configuration for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement#feedback)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* GitHub Login: @maertendMSFT

**Comment by illfated** [comment]
I presume you are referring to the first sentence underneath the section title **Deploying the public key** (https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement#deploying-the-public-key):

## Deploying the public key

To use the user key that was created above, the public key needs to be placed on the server into a text file called *authorized_keys* under users\username\ssh. 
The OpenSSH tools include scp, which is a secure file-transfer utility, to help with this.
