### ISSUE TITLE
Links to outdated pages

### ISSUE THREAD

**Issue by spatters-git** [MicrosoftDocs/windowsserverdocs#3572]
This page is applicable to Windows Server 2016.  But, in several places it has important links to pages that exclude Windows Server 2016, some of which have deprecation warnings on them.  This leaves someone using 2016 wondering if they're wasting their time using resources that won't work on Windows 2016.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f70b91f-1cbc-3ea4-3760-d8945f9ff1fb
* Version Independent ID: 5372fa26-d2b9-8fa9-c4ec-7ce34f062b57
* Content: [Cluster to cluster Storage Replication](https://docs.microsoft.com/en-us/windows-server/storage/storage-replica/cluster-to-cluster-storage-replication#feedback)
* Content Source: [WindowsServerDocs/storage/storage-replica/cluster-to-cluster-storage-replication.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-replica/cluster-to-cluster-storage-replication.md)
* Product: **windows-server**
* Technology: **storage-replica**
* GitHub Login: @nedpyle
* Microsoft Alias: **nedpyle**

**Comment by arduppal** [comment]
@spatters-git can you point out which ones?

**Comment by nedpyle** [comment]
They cannot, as that is the email bot 😅. You will need to reply to the customer commenter at the original link if they didn’t give enough details

Sent from a phone so probably illegible
________________________________

**Comment by spatters-git** [comment]
I did my part - I let you know some of your links were broken.  If you're interested in having accurate documentation, you can spend a few minutes clicking them.  There aren't that many, and the supported OSs are right at the top of the link destinations.
