### ISSUE TITLE
"While CredSSP is enabled, there will be a badge on the Server Overview"

### ISSUE THREAD

**Issue by ryanhelmer** [MicrosoftDocs/windowsserverdocs#3576]
"Using the Updates tool in either the Failover or Hyper-Converged cluster management solutions"

There is no equivalent "CredSSP ENABLED" badge for the Hyper-Converged cluster--it's only seen on the individual nodes. 

Also, CredSSP is also used by Windows Admin Center Diagnostics for Hyper-Converged clusters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 136cbcd9-a631-587d-3b48-dded76d9e6c9
* Version Independent ID: d1ac1f79-89de-97d8-aec7-1c6a78212910
* Content: [Windows Admin Center Frequently Asked Questions](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/understand/faq#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/understand/faq.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/understand/faq.md)
* Product: **windows-server**
* Technology: **manage**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
