### ISSUE TITLE
Microsoft KB article link doesn't work

### ISSUE THREAD

**Issue by ramuvr** [MicrosoftDocs/windowsserverdocs#3577]
Microsoft KB article link doesn't work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 081e4892-c7cd-e02a-5251-64cc2655bc8c
* Version Independent ID: b9ebb826-7bb8-168a-062a-825d5910fcd0
* Content: [Virtualized Domain Controller Architecture](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/get-started/virtual-dc/virtualized-domain-controller-architecture)
* Content Source: [WindowsServerDocs/identity/ad-ds/get-started/virtual-dc/Virtualized-Domain-Controller-Architecture.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/get-started/virtual-dc/Virtualized-Domain-Controller-Architecture.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by illfated** [comment]
Fair point, the 2 links "see Microsoft KB article [2742970](https://support.microsoft.com/kb/2742970)." (https://support.microsoft.com/kb/2742970) currently resolve to the page https://support.microsoft.com/en-ph/help/2742970 which only displays

## Sorry, page not found
Try searching Microsoft Support to find a solution
(error 404)

I was hoping that the suggested solution in the issue ticket **Broken link to KB2549369 (and recipe to this particular broken link pattern) #3490** would resolve this ticket too, but that does not seem to be the case here. 

Further digging (research) is needed to find a correct way to resolve this broken link (x2).

**Comment by illfated** [comment]
Not even WayBack Machine has got any material stored for the missing page KB 2742970. I see no other option than to remove the 2 sentences referencing that lost KB article.

**Comment by illfated** [comment]
Even though long overdue, I have opened PR #4960 to remove the dead links. Feel free to view/comment/post or suggest changes.
