### ISSUE TITLE
Claim type url should be http schema

### ISSUE THREAD

**Issue by watahani** [MicrosoftDocs/windowsserverdocs#3583]
Those url should be http schema instead of https.
Those rule will not work correctly.

>On the Configure Rule page, under Claim rule name, type the display name for this rule; in Incoming claim type, type the following claim type URL, and then select Pass through all claim values.
>https://schemas.microsoft.com/2012/01/requestcontext/claims/x-ms-forwarded-client-ip

>To verify the rule, select it in the list and click Edit Rule, then click View Rule Language. The claim rule language should appear as follows: c:[Type == >"https://schemas.microsoft.com/2012/01/requestcontext/claims/x-ms-forwarded-client-ip"] => issue(claim = c);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b2bb486-00c8-2238-3f4e-297db3569277
* Version Independent ID: 9d517c40-13a9-c9ba-e940-b486310e6eab
* Content: [Client Access Control policies in Active Directory Federation Services 2.0](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/access-control-policies-in-ad-fs-2)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Access-Control-Policies-in-AD-FS-2.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Access-Control-Policies-in-AD-FS-2.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
