### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by Andrew-Coughlin-MSFT** [MicrosoftDocs/windowsserverdocs#3584]
The following links are broken on this page: "Creating a site-to-site VPN connection" and "Securing network traffic in Azure"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e3ea72d-d69c-15e6-74b0-d90c18c0b6ba
* Version Independent ID: fcb5f4fa-4636-0547-4030-87230ef02376
* Content: [Install Active Directory Domain Services on an Azure virtual machine](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
