### ISSUE TITLE
illustration.png bug - 2012 r2 to 2016 upgrade

### ISSUE THREAD

**Issue by Karr** [MicrosoftDocs/windowsserverdocs#3589]
New-AdfsWebTheme –Name ProofUp –SourceName default command generated ERROR in Server 2016 Standard primary ad fs server.
ILLUSTRATION BUG - 2012 &gt; 2016 ---- HOTFIX LINK would be nice

New-AdfsWebTheme : MSISMP0002: The specified relative URI '/adfs/portal/illustration/illustration.png' conflicts with

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae96cfcf-0a50-7e13-30c8-43e3730e184f
* Version Independent ID: 9d8ed7b7-eec6-1b95-40b8-24a13361f66d
* Content: [Configure AD FS 2016 and Azure MFA](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
