### ISSUE TITLE
I CANNOT UPDATE WINDOWS SERVER 2008 r "TO WINDOWS SERVER 2012R2

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/windowsserverdocs#3590]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/windowsserverdocs.it-it/issues/2

Hi, I tried to make the inplace upgrade from windows server 2008R2 Standard
Edition to windows server 2012R2; it starts regularly I accept the license
term and then select the 'upgrade' option, but at this time I get this
message: Impossibile eseguire l'aggiornamento da Windows Server 2008 R2
Standard a Windows Server 2012 R2 Standard Evaluation (installazione dei
componenti core del server)... so I don't know what to do. I looked for some
help on web but I didn't find any item. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88d8e06f-1416-57d1-84b9-fd82d217a481
* Version Independent ID: 9047ff8c-95f0-ffea-38d6-9a6d6c56e383
* Content: [Windows Server Installation and Upgrade](https://docs.microsoft.com/en-us/windows-server/get-started/installation-and-upgrade#feedback)
* Content Source: [WindowsServerDocs/get-started/Installation-and-Upgrade.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/Installation-and-Upgrade.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
First of all, I would like to point out that I have not participated much in the issue tickets here on MicrosoftDocs/windowsserverdocs, compared to my contributions in MicrosoftDocs/windows-itpro-docs.

To me, the original author's issue looks very much like a support issue in need of direct dialog with the customer/administrator of that specific computer system. Also note that the current original feedback does not contain any more technical information than the general error message:
> Unable to upgrade from Windows Server 2008 R2 Standard to Windows Server 2012 R2 Standard Evaluation (installation of core server components)

As a computer hardware & software support technician, to me, it seems more than difficult to follow up on the original author's issue without launching a full support action to set up & try to replicate the server hardware & software scenario while also getting hold of more detailed information about the installation error by requesting logs and other information directly from the originator.

In my experience, it would be much more productive for the originator to contact the nearest Microsoft Support tenant or Microsoft partner/provider for direct follow-up and detailed information access.

**Comment by illfated** [comment]
@CeciAc : Thank you for migrating the issue to the English docs page, although I am still quite certain that this type of issue can happen if the user's starting point is a less than ideal configuration of the server. The user's issue should be handled by a Microsoft Support tenant in the user's area, if possible, asking the user to post back if there are any points to be made in the documentation for this specific issue.

Please note that these pages are intended for reporting issues in the documentation itself. We are only able to follow up documentation issues when pointed out what is incorrect, and preferably the factual information required to correct the documentation.

As previously stated, I am fairly certain that the issue needs troubleshooting locally at the user's location, either via phone support or remote access to the user's server environment, whichever solution is available. Reporting back to the Microsoft Docs is encouraged, particularly if errors in the documentation have been found.

**Comment by illfated** [comment]
#please-close
