### ISSUE TITLE
404 on Creating a Site Design

### ISSUE THREAD

**Issue by deyjcode** [MicrosoftDocs/windowsserverdocs#3592]
There's a 404 for the link the Job Aids: https://go.microsoft.com/fwlink/?LinkID=102558

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c7feb50-baf0-4041-25f5-8fa96029d418
* Version Independent ID: 9426a72a-e27f-aadd-e01e-b73d3849f22f
* Content: [Creating a Site Design](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/creating-a-site-design#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/Creating-a-Site-Design.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/Creating-a-Site-Design.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by illfated** [comment]
At first, I thought the page or file had been deleted, but it is possible to get to the page using the following link:
- https://www.microsoft.com/download/details.aspx?id=9608

The broken link is as follows:
- https://go.microsoft.com/fwlink/?LinkID=102558

If the Microsoft Docs team wants to keep using the fwlink format, the correction needs to be done by one of Microsoft's own technicians.
The only request we end users are able to post, is a Pull Request to change it to the direct link to the download page.

**Comment by illfated** [comment]
Someone else also found the correct document in issue ticket #4147. I will start working on a PR to fix the link here too.
New and working link: https://www.microsoft.com/download/details.aspx?id=9608
