### ISSUE TITLE
Chrome information missing

### ISSUE THREAD

**Issue by mmmiller60** [MicrosoftDocs/windowsserverdocs#3594]
Information in this article should also be included about Chrome... "Mozilla/5.0 (Windows NT")  and  "Mozilla/5.0 (Macintosh; Intel Mac OS X")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 375a5fd8-c881-b6f7-c93f-b8898020c43f
* Version Independent ID: 0c58c9d1-cb1f-03b2-9456-3e5550e8d8ab
* Content: [Configure browsers to use Windows Integrated Authentication (WIA) with AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-browser-wia#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Browser-WIA.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Browser-WIA.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
(Ref. #4342)

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
