### ISSUE TITLE
Repair-AuthorizedKeyPermission

### ISSUE THREAD

**Issue by thanoskat** [MicrosoftDocs/windowsserverdocs#3601]
Repair-AuthorizedKeyPermission insists that 'NT SERVICE\sshd' needs Read access to authorized_keys.

BUT from sshd log file:"Bad permissions. Try removing permissions for user: (sshd's SID) on file C:/.../.ssh/authorized_keys. 
Authentication refused."

Removing that user from that file permissions fixes the problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 337c4ea8-1806-92a3-1501-b3ff5dde37bb
* Version Independent ID: c411d389-578d-57c6-cd6e-eaca7f2837db
* Content: [OpenSSH Server Configuration for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement#feedback)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* GitHub Login: @maertendMSFT

**Comment by Pearcekieser** [comment]
Had same issue and this fixed it for me.  Thanks!  I think that sshd read perm is erroneously set by `Repair-AuthorizedKeyPermission`
