### ISSUE TITLE
ReFS integrity streams. Any Sacrifice of File Integrity Checksumming With 64K Clusters vs 4K Clusters?

### ISSUE THREAD

**Issue by CrafterLaughter** [MicrosoftDocs/windowsserverdocs#3605]
The ReFS integrity streams page makes no mention if there is any sacrifice of file integrity checksumming when using 64k clusters vs 4k clusters?

It would be wonderful if users were reassured that ReFS integrity streams with 64k clusters have similar ability to recover from a flipped bit somewhere in the cluster.

Do the checksums for 64k clusters cover the whole 64k stream in such a way that recovery from corruption is just as likely as it would be with 4k clusters?

@JasonGerend @jgerend @gawatu @dmoss

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ca609fd-a4a8-c238-1f90-9e7223ca338d
* Version Independent ID: ed26c24f-a7bd-5041-c372-146527d6a600
* Content: [ReFS integrity streams](https://docs.microsoft.com/en-us/windows-server/storage/refs/integrity-streams?redirectedfrom=MSDN#feedback)
* Content Source: [WindowsServerDocs/storage/refs/integrity-streams.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/refs/integrity-streams.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @gawatu
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
