### ISSUE TITLE
Please clarify "This command is only applicable to Windows 7 and Windows Server 2008 R2."

### ISSUE THREAD

**Issue by rualthan** [MicrosoftDocs/windowsserverdocs#3610]
Please clarify "This command is only applicable to Windows 7 and Windows Server 2008 R2.".
This command works for me in 2016.

diskpart&gt; san policy=onlineall

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cbe4c24-052b-542d-1689-f956548f418b
* Version Independent ID: 3a30a05a-e78d-cad1-b980-2c0353cf3a65
* Content: [san](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/san#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/san.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/san.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by rualthan** [comment]
@steved0x Any update?

**Comment by illfated** [comment]
Would that I had discovered this issue ticket earlier, but anyway: I am looking through the updates now, just to see when the text you quoted above was removed.

**Comment by illfated** [comment]
Resolved as of August 27, 2020, 2:46 PM PDT, in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/1a63ac4e23a354a74b93c14cfce41448036ac78f (direct file link https://github.com/MicrosoftDocs/windowsserverdocs/commit/1a63ac4e23a354a74b93c14cfce41448036ac78f#diff-12a8b9a4606d80d6d1966e07db061de4e80298e32ee3dfdc427d3ea5931cca3f).

**Comment by illfated** [comment]
@rualthan : It looks like your reported issue has been solved, so I am going to close this ticket. If you still find that it has not been resolved, either reopen this ticket or open a new ticket with more details for the current version of the document page.

**Comment by illfated** [comment]
#please-close

**Comment by rualthan** [comment]
@illfated Sorry, what is the solution?

**Comment by illfated** [comment]
@rualthan : As far as I am aware, commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/1a63ac4e23a354a74b93c14cfce41448036ac78f seems to be the solution. If you still find that there is an issue in the document, please open [a new ticket](https://github.com/MicrosoftDocs/windowsserverdocs/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%207edff16f-948d-6381-7431-acb48bdb05c7%0A*%20Version%20Independent%20ID%3A%20f062f74b-6512-727f-c2c2-d3df63e0f9d4%0A*%20Content%3A%20%5Bsan%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fwindows-server%2Fadministration%2Fwindows-commands%2Fsan)%0A*%20Content%20Source%3A%20%5BWindowsServerDocs%2Fadministration%2Fwindows-commands%2Fsan.md%5D(https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fwindowsserverdocs%2Fblob%2Fmaster%2FWindowsServerDocs%2Fadministration%2Fwindows-commands%2Fsan.md)%0A*%20Product%3A%20**windows-server**%0A*%20Technology%3A%20**windows-commands**%0A*%20GitHub%20Login%3A%20%40eross-msft%0A*%20Microsoft%20Alias%3A%20**lizross**). Thank you.
