### ISSUE TITLE
Implicit flow from React.js cannot use post

### ISSUE THREAD

**Issue by ccoyle95** [MicrosoftDocs/windowsserverdocs#3616]
I have tried to modify my ADAL.js code in my React app to use "response_mode=form_post", but now I am getting the error "Cannot Post /". Is there any way to resolve this error? I've seen it in multiple github issue trackers but there is no resolution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e04047c8-df0d-d752-afc1-0daa314e5d75
* Version Independent ID: 93cac62e-204f-b523-3751-51e420672555
* Content: [Customize claims to be emitted in id_token when using OpenID Connect or OAuth with AD FS 2016 or later](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/custom-id-tokens-in-ad-fs#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/Custom-Id-Tokens-in-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/Custom-Id-Tokens-in-AD-FS.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @anandyadavMSFT
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
