### ISSUE TITLE
SUSE repository faulty

### ISSUE THREAD

**Issue by RobinR1** [MicrosoftDocs/windowsserverdocs#3625]
The packages-microsoft-prod.rpm for SLES (or opensuse which does seem to exists, but is not described in this document) installs a yum repository file in /etc/yum/yum.repos.d which obviously doesn't work on Suse based systems as those use zypper as package manager and expects a repo file with a slightly different format in /etc/zypp/repos.d .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e7ed059-d77f-6ce0-8501-fc3afd1c8048
* Version Independent ID: f2d249ee-50e4-52b4-4187-954a84a48ec1
* Content: [Linux Software Repository for Microsoft Products](https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software#feedback)
* Content Source: [WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md)
* Service: **na**
* Product: **windows-server**
* Technology: **compute**
* GitHub Login: @szarkos
* Microsoft Alias: **szark**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
