### ISSUE TITLE
Link on "Add a Claim" referencing not-supported page.

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/windowsserverdocs#3632]
Please, provide a link on up-to-date document for "Add a Claim Description"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17871695-deb5-8178-a970-71b7d6fabd72
* Version Independent ID: ae86889c-8f5d-bbc2-d713-4f1a6678af5b
* Content: [The Role of Claims](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/technical-reference/the-role-of-claims)
* Content Source: [WindowsServerDocs/identity/ad-fs/technical-reference/The-Role-of-Claims.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/technical-reference/The-Role-of-Claims.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
@SychevIgor Thanks for catching this.  It appears a lot of the older AD FS content, which is still relevant got archived because it was only referencing an older version of Windows Server.  I have created a work item to get this content moved back into the current AD FS doc set.  This may take a little while so I am going to close this out and I will drop an update once I have gotten it moved.  Thanks!

#please-close

**Comment by SychevIgor** [comment]
I hope it's not typical "we put it in a backlog and forgot"

**Comment by SychevIgor** [comment]
nobody care?

**Comment by illfated** [comment]
Sorry that it has taken me so long to dive back in the older issue tickets.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

@SychevIgor : I think I have found the necessary replacement. Can you confirm that these 2 pages are interchangeable, except for the fact that one is new and the one you have seen before is old (2012)?
- https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/add-a-claim-description
- https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dd807051(v=ws.11)

I am going to open a Pull Request to have this issue resolved. In the meantime, feel free to comment, confirm or join in if you have more suggestions for improvements.

**Comment by illfated** [comment]
Ref. PR #4482 , ready for review.
