### ISSUE TITLE
ssh with forward agent

### ISSUE THREAD

**Issue by thenger** [MicrosoftDocs/windowsserverdocs#3634]
Hello,
I want to connect to a local VM hosted on my windows only using ForwardAgent .

### Important points
1. I can use Pageant and ForwardAgent to connect to vim VM with Putty.
2. I can ssh to this vm with my private key using the same private key (w/ openssl format) and password authent.
3. I cannot ssh using `ForwardAgent=yes` and ssh-agent.exe

# Config part
### Windows %HOME%: .ssh\config
```
Host dtvm
    HostName 192.168.99.14
    #ForwardAgent yes
    #PasswordAuthentication no
    User boop
```
### On the VM (debian 10) : 
```
# grep -Ev '^\s*(#|$)' /etc/ssh/sshd_config
ChallengeResponseAuthentication no
UsePAM yes
AllowAgentForwarding yes
X11Forwarding yes
PrintMotd no
AcceptEnv LANG LC_*
Subsystem       sftp    /usr/lib/openssh/sftp-server
```
("AllowAgentForwarding" is now activated but before, I could connect w/ putty and ForwardAgent without this)

# Commands part on CMD

### On windows
```
C:\Users\boop>ssh-add.exe -l
2048 SHA256:*hidden manually* C:\Users\boop\Documents\private\keys\pkey.priv (RSA)

C:\Users\boop>ssh-add.exe -D
All identities removed.

C:\Users\boop>ssh-add.exe -l
The agent has no identities.

C:\Users\boop>ssh-add.exe C:\Users\boop\Documents\private\keys\pkey.priv
Enter passphrase for C:\Users\boop\Documents\private\keys\pkey.priv:
Identity added: C:\Users\boop\Documents\private\keys\pkey.priv (C:\Users\boop\Documents\private\keys\pkey.priv)

C:\Users\boop>ssh-add.exe -l
2048 SHA256:*hidden manually* C:\Users\boop\Documents\private\keys\pkey.priv (RSA)

C:\Users\boop>ssh-agent.exe

C:\Users\boop>ssh -V
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
```
So here 👆 I removed my key from ssh-agent and inserted it again.

### Connecting to the VM w/ password
ssh connection using password is OK
```
C:\Users\boop>ssh dtvm
warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)
boop@192.168.99.14's password:
Linux dtvm 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64
No mail.
Last login: Fri Dec 13 14:21:01 2019 from 192.168.99.1


boop - ~> cat /etc/debian_version
10.1
boop - ~> logout
Connection to 192.168.99.14 closed.
```

### Connecting w/ forwardAgent
```
C:\Users\boop>
C:\Users\boop>ssh -oForwardAgent=yes dtvm
warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)
boop@192.168.99.14's password:

C:\Users\boop>ssh -oForwardAgent=yes -oPasswordAuthentication=no dtvm
warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)
boop@192.168.99.14: Permission denied (publickey,password).
```

I don't know if the warning message is related but I cant get it to work

am I missing something ?

Including debug output in file: [debuglevel3_ssh_forward.txt](https://github.com/MicrosoftDocs/windowsserverdocs/files/3961724/debuglevel3_ssh_forward.txt)

Regards

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
