### ISSUE TITLE
about debian and sources

### ISSUE THREAD

**Issue by ivanottantuno** [MicrosoftDocs/windowsserverdocs#3635]
Hi, in this page you don't speak about the way to configure the debian repos.
Searching on the http view of the ftp server I found this package
http://packages.microsoft.com/repos/microsoft-debian-buster-prod/pool/main/p/packages-microsoft-prod/packages-microsoft-prod_1.0-debian10.1_amd64.deb
Description: Apt configuration for packages.microsoft.com
 This package contains the apt repo configuration
 for packages.microsoft.com and the public GPG key.

About the sources, why don't you have created the sources repos?
You think the git repos on github are enough?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc45b809-9722-3267-f65b-09b4ec9af6a2
* Version Independent ID: 6a463082-c030-cff6-2b50-b5252586ed20
* Content: [Linux Software Repository for Microsoft Products](https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software#feedback)
* Content Source: [WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md)
* Service: **na**
* Product: **windows-server**
* Technology: **compute**
* GitHub Login: @szarkos
* Microsoft Alias: **szark**

**Comment by sethmanheim** [comment]
Closing per #5169
