### ISSUE TITLE
How to resolve Disk Signature Collision after cloning to a SSD?

### ISSUE THREAD

**Issue by VashJuan** [MicrosoftDocs/windowsserverdocs#3637]
Right clicking and selecting ONLINE just generates a "The parameter is incorrect" error. Uggg.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30444fe3-ed53-126d-adfa-570c725f981f
* Version Independent ID: b8833a0b-25a8-cfe9-0156-0c6575d11c6d
* Content: [Troubleshooting Disk Management](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/troubleshooting-disk-management)
* Content Source: [WindowsServerDocs/storage/disk-management/troubleshooting-disk-management.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/troubleshooting-disk-management.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
