### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by Moe1976** [MicrosoftDocs/windowsserverdocs#3640]
the link in the important box that's leads to New-NetworkControllerServer is leading to dead end 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 644974d4-9c7c-f581-82f9-64ea55fc7d09
* Version Independent ID: b011f918-45a7-297d-6a69-45283bcbf591
* Content: [Install the Network Controller Server Role Using Server Manager](https://docs.microsoft.com/en-us/windows-server/networking/sdn/technologies/network-controller/install-the-network-controller-server-role-using-server-manager)
* Content Source: [WindowsServerDocs/networking/sdn/technologies/network-controller/Install-the-Network-Controller-server-role-using-Server-Manager.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/sdn/technologies/network-controller/Install-the-Network-Controller-server-role-using-Server-Manager.md)
* Product: **windows-server**
* Technology: **networking-sdn**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by illfated** [comment]
Based on a suggestion on the 404 page, it looks like this could be a useful replacement:
- https://docs.microsoft.com/powershell/module/networkcontroller/new-networkcontrollerserver

@Moe1976 : Can you confirm that the link gives you the correct page?

**Comment by illfated** [comment]
Oh man. Such a confusion. _A single hyphen_ (`-`) was enough to break the link. Oh well. I will make a PR to recommend the necessary change.

**Comment by illfated** [comment]
There you go. PR #4962 is now ready for review and comments.
