### ISSUE TITLE
Silent Installation didn´t work without SME_SERVER_HOST

### ISSUE THREAD

**Issue by PehDeh** [MicrosoftDocs/windowsserverdocs#3644]
I struggled for quite some time with SME_URL beeing set to HTTPS://:443 this was caused by setting SME_PORT=443 but missing SME_SERVER_HOST=FQDN

$sysinfo = Get-WmiObject -Class Win32_ComputerSystem
$server = “{0}.{1}” -f $sysinfo.Name, $sysinfo.Domain
$cert = gci Cert:\LocalMachine\My\ | ? Issuer -like "*Issuing CA *"|? NotAfter -gt $(get-date)| ? Subject -like "*$server*"
$cert.thumbprint
msiexec /i C:\temp\WindowsAdminCenter1910.msi /qn /L*v C:\temp\log.txt SME_SERVER_HOST=$server SME_PORT=443 SME_THUMBPRINT=$($cert.Thumbprint) SSL_CERTIFICATE_OPTION=installed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe84fb4b-3420-bc1e-6a1d-b64ecc56fc5e
* Version Independent ID: f089767e-4613-d595-a0ee-0dab012724a1
* Content: [Install Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/install?WT.mc_id=thomasmaurer-blog-thmaure)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/deploy/install.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/deploy/install.md)
* Product: **windows-server**
* Technology: **manage**
* GitHub Login: @jwwool
* Microsoft Alias: **jeffrew**

**Comment by jwwool** [comment]
SME_URL getting set to HTTPS://:443 will happen when using a wildcard certificate, will you please confirm?

**Comment by PehDeh** [comment]
Sorry, since i got it fixed it was out of my scope.
No we have Certificates based on the hostname.

I just wanted to get the Documentation right, if no FQDN is specified it didn´t work.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
