### ISSUE TITLE
Microsoft Account with Microsoft Authenticator and Windows Hello

### ISSUE THREAD

**Issue by cparker15** [MicrosoftDocs/windowsserverdocs#3645]
Does Remote Desktop support sign-in with Microsoft Accounts with Microsoft Authenticator enabled? Additionally, my user account has Windows Hello enabled. No combination I've tried thus far has worked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45d9f311-2994-948d-ad91-f5c7370d73ec
* Version Independent ID: 5f978676-6f53-3f2d-fabb-3554027edbcc
* Content: [Get started with the Android client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-android#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-android.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-android.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
