### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by ildrosos** [MicrosoftDocs/windowsserverdocs#3653]
Hello under section 2 there is a typo : 
 "it is import to take "
I guess it should say it is important.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb523d20-85bb-82b5-7e0a-f0455c48944c
* Version Independent ID: 7663ccd7-eb64-b461-4fbb-8bd669cda9b2
* Content: [Enable optimized moves of redirected folders](https://docs.microsoft.com/en-us/windows-server/storage/folder-redirection/enable-optimized-moving#feedback)
* Content Source: [WindowsServerDocs/storage/folder-redirection/enable-optimized-moving.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/folder-redirection/enable-optimized-moving.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by JasonGerend** [comment]
Thanks for catching this mistake - I'm fixing it right now and it should go live in the next couple days. 
Thanks again,

Jason Gerend - Technical Writer for Windows Server

**Comment by ildrosos** [comment]
You are welcome :)

Sent from Yahoo Mail on Android 
 
  On Thu, Dec 19, 2019 at 20:58, Jason Gerend<notifications@github.com> wrote:   
Thanks for catching this mistake - I'm fixing it right now and it should go live in the next couple days.
Thanks again,

Jason Gerend - Technical Writer for Windows Server

**Comment by exchange12rocks** [comment]
@ildrosos Fixed in d584800 - could you please close the issue?

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
Sorry, I forgot to take into context that @ildrosos might want to close it. Maybe I was too quick to ask for the issue ticket to be closed.

**Comment by ildrosos** [comment]
Hello no problem it should be closed since it's fixed no problem.
