### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by thanks4wifi** [MicrosoftDocs/windowsserverdocs#3654]
This section

&gt; For more information about Rundll32 requirements see article 164787 in the Microsoft Knowledge Base (https://go.microsoft.com/fwlink/?LinkID=165773).

The link just redirects back to this page, so one can not find more information on "Rundll32 requirements"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b8fddd9-37bf-a9b1-2494-a13c798d6add
* Version Independent ID: 0e979db8-7032-03c7-4920-1e05cad6eee6
* Content: [rundll32](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/rundll32#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/rundll32.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/rundll32.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
I have tried following links from external sites to Microsoft Knowledge Base article 164787, but the only practical result I get ends up in https://support.microsoft.com/en-us/support/kb/articles/q164/7/87.asp and the message "Try searching for what you need / This page doesn’t exist." Another hint that this information may be outdated/deprecated/removed is that references linking or pointing to Microsoft Knowledge Base article 164787 are from 20 years ago (1998-2000). I am thinking that the whole sentence needs to be removed.

**Comment by illfated** [comment]
(Ref. #3894 )
