### ISSUE TITLE
TCP Ports Used?

### ISSUE THREAD

**Issue by SpencerEardley** [MicrosoftDocs/windowsserverdocs#3655]
It would be helpful to know which ports wevtutil is configured to use so that I can configure my firewall accordingly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ca36bef-ea29-ad66-c0ab-6ccd4fc6dce1
* Version Independent ID: cb8cba87-dddd-05e9-4175-f547f01b774c
* Content: [wevtutil](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/wevtutil#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/wevtutil.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/wevtutil.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
According to https://jpcertcc.github.io/ToolAnalysisResultSheet/details/wevtutil.htm it looks like **135/tcp** is used. (I don't know anything useful about this topic.)

**Comment by illfated** [comment]
**RPC Endpoint Mapper**
- https://www.grc.com/port_135.htm

### [**Ports and protocols**](https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements#ports-and-protocols)
- https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements#ports-and-protocols

### 135 TCP RPC (Remote Procedure Call)
- Message Queuing
- Remote Procedure Call
- Exchange Server
- Certificate Services
- Cluster Service
- Distributed File System Namespaces
- Distributed Link Tracking
- Distributed Transaction Coordinator
- Distributed File Replication Service
- Fax Service
- Microsoft Exchange Server
- File Replication Service
- Group Policy
- Local Security Authority
- Remote Storage Notification
- Remote Storage
- Systems Management Server 2.0
- Terminal Services Licensing
- Terminal Services Session Directory

**Please note that the TCP port range 135 — 139 is often referred to as NetBIOS type ports and should never be exposed to the Internet.**

**Comment by illfated** [comment]
See also https://ss64.com/nt/wevtutil.html for more Desktop (non-Server) related details.

**Comment by illfated** [comment]
#please-close
