### ISSUE TITLE
Steps for certificate creation

### ISSUE THREAD

**Issue by DarrylvanderPeijl** [MicrosoftDocs/windowsserverdocs#3658]
There are no steps for selecting the newly created template to be added as "Certificate Template to issue". Also the appropriate security rights for enrolling are not set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 700a2985-99e1-26f8-ab0d-5be8490a0905
* Version Independent ID: e1b10466-21e1-1611-51b8-139083a6fe0a
* Content: [Manage certificates for Software Defined Networking](https://docs.microsoft.com/en-us/windows-server/networking/sdn/security/sdn-manage-certs)
* Content Source: [WindowsServerDocs/networking/sdn/security/sdn-manage-certs.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/sdn/security/sdn-manage-certs.md)
* Product: **windows-server**
* Technology: **networking-sdn**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
