### ISSUE TITLE
Hyperlink

### ISSUE THREAD

**Issue by marcosbabu** [MicrosoftDocs/windowsserverdocs#3660]
Where should this Hyperlink (Configure a site to use Integrated Authentication) should point to? It has a weird "assetid:///" URL...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6eab4e1f-d36f-3af5-a470-748544db10c6
* Version Independent ID: 507b5d01-0566-2459-a9c4-006ce7681a54
* Content: [Publishing Applications with SharePoint, Exchange and RDG](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/web-application-proxy/publishing-applications-with-sharepoint,-exchange-and-rdg#feedback)
* Content Source: [WindowsServerDocs/remote/remote-access/web-application-proxy/Publishing-Applications-with-SharePoint,-Exchange-and-RDG.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/web-application-proxy/Publishing-Applications-with-SharePoint,-Exchange-and-RDG.md)
* Product: **windows-server**
* Technology: **web-app-proxy**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Oh. Right. You are referring to the URL "Configure a site to use Integrated Windows authentication" ( assetid:///b0788958-627f-450f-877c-209b1bd0db52 )
(took me a few seconds extra to make sure I was looking at the correct text)

Sorry, I don't know. But this sure looks like a local link, just like the file:/// protocol identifier.

I can only guess that it might work in a local intranet environment where all the necessary tools are installed, but I would not trust it to work on a public web page.

**Comment by marcosbabu** [comment]
"I can only guess that it might work in a local intranet environment where all the necessary tools"

Yes, I got the protocol "hint", but we're reading a webpage usually on a browser. One could expect the URL to work on any regular browser, no matter the OS (nor the applications) that browser is running on. And even then, which application should be present?

Anyway, sounds like a mistake.

> I can only guess that it might work in a local intranet environment where all the necessary tools are installed, but I would not trust it to work on a public web page.
> 
> edit: While checking other random link URLs on the same page (https://docs.microsoft.com/en-us/windows-server/remote/remote-access/web-application-proxy/publishing-applications-with-sharepoint,-exchange-and-rdg), I noticed that some of the links are locale specific to /en-gb/ -- this should normally not be the case. Maybe the whole page needs a proper URL review.

**Comment by illfated** [comment]
Sure, it looks like a mistake to me as well. I can only suggest that we look around (web search) for what the actual page is supposed to be. Then, if we find the correct page, we can submit a PR to suggest a change to the page, correcting it to point to the page it was supposed to link to in the first place.

**Comment by illfated** [comment]
See also issue ticket #4000 and PR #4001 (commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/0354693263e840afc83ef7ba239e022795e303f9) where this has been resolved.

**Comment by illfated** [comment]
#please-close
