### ISSUE TITLE
Multi-line Strings

### ISSUE THREAD

**Issue by VikingByNature** [MicrosoftDocs/windowsserverdocs#3664]
For _String_ data that spans multiple lines, specify **`/T REG_MULTI_SZ`** and then the data after **`/D`** all on the same line with each desired line of text seperated by **`\0`**.  You can change the seperator character to any single character of your choice by specifying **`/S`** followed by the desired character without double quotes; in this case, only symbols should be used.

#### Samples:

**`REG ADD "HKCU\Test Key" /V "Multi-line String Value" /T REG_MULTI_SZ /F /D "This is a test string\0that spans 2 lines"`**
Value: `Multi-line String Value`
Data:
`This is a test string`
`that spans 2 lines`

**`REG ADD "HKCU\Test Key" /V "Multi-line String Value" /T REG_MULTI_SZ /S * /F /D "This is a test string*that spans 3 lines*using an asterisk as the seperator"`**
Value: `Multi-line String Value`
Data:
`This is a test string`
`that spans 3 lines`
`using an asterisk as the seperator`

**`REG ADD "HKCU\Test Key" /V "Multi-line String Value" /T REG_MULTI_SZ /S \0 /F /D "This is a test string\0that spans multiple lines"`**
**ERROR:** Do not explicitly specify **`\0`** when using the **`/S`** argument; it must simply be omitted when using **`\0`**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3deae269-de28-fb85-f52e-334e5b222de8
* Version Independent ID: 792402db-afda-e1fc-18e5-551a4b625b83
* Content: [reg add](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/reg-add)
* Content Source: [WindowsServerDocs/administration/windows-commands/reg-add.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/reg-add.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
