### ISSUE TITLE
Whole Number Data

### ISSUE THREAD

**Issue by VikingByNature** [MicrosoftDocs/windowsserverdocs#3666]
For all _DWord_ and _QWord_ numerical data, specify **`/T REG_DWORD`** or **`/T REG_QWORD`** and then the data after **`/D`** either in decimal or hexadecimal format.  For decimal format, use numbers only.  For hexadecimal format, specify **`0X`** followed only by hexadecimal numbers and no other characters.

#### Samples:

**`REG ADD "HKCU\Test Key" /V "DWord Value - Decimal" /T REG_DWORD /F /D 1000`**
Value: `DWord Value - Decimal`
Data: `0x3E8 (1000)`

**`REG ADD "HKCU\Test Key" /V "DWord Value - Hexadecimal" /T REG_DWORD /F /D 0X1000`**
Value: `DWord Value - Hexadecimal`
Data: `0x1000 (4096)`

**`REG ADD "HKCU\Test Key" /V "QWord Value - Decimal" /T REG_QWORD /F /D 1000000000000`**
Value: `QWord Value - Decimal`
Data: `0xE8D4A51000 (1000000000000)`

**`REG ADD "HKCU\Test Key" /V "QWord Value - Hexadecimal" /T REG_QWORD /F /D 0X1000000000000`**
Value: `QWord Value - Hexadecimal`
Data: `0x1000000000000 (281474976710656)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3deae269-de28-fb85-f52e-334e5b222de8
* Version Independent ID: 792402db-afda-e1fc-18e5-551a4b625b83
* Content: [reg add](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/reg-add)
* Content Source: [WindowsServerDocs/administration/windows-commands/reg-add.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/reg-add.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
