### ISSUE TITLE
ssh_askpass: posix_spawn: No such file or directory

### ISSUE THREAD

**Issue by chrisdonlan** [MicrosoftDocs/windowsserverdocs#3670]
When ssh'ing to a windows azure vm, I am currently using Cygwin.  The cygwin terminal formatting/fonts/etc. are not as good as powershell's and generally take more work to configure, so I would prefer to use PowerShell.  

However, I have password protected my ssh key, and when ssh'ing into the vm from powershell, I get the following error message:

```
:> ssh <userid>@123.231.123.231
CreateProcessW failed error:2
ssh_askpass: posix_spawn: No such file or directory
Host key verification failed.
```

To me, it seems as if the issue is not `ssh_askpass`, but the `posix_spawn` function.  Interestingly, I was able to `ssh` onto the Azure VM using powershell in a different network setup (again, powershell's ssh did not work intially, but after working with both terminals for many hours, it did).  However, at the time, I was `ssh
ing` and hopping between cygwin and powershell fairly rapidly. Ergo, I have no idea how to reproduce whatever "working state" I managed to get powershell's ssh into.

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
