### ISSUE TITLE
Missing character

### ISSUE THREAD

**Issue by lazna** [MicrosoftDocs/windowsserverdocs#3674]
backslash character misssing in 'remarks' part :

string&gt;	Word position: end of the word

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2673bff6-4e43-3d54-f58f-2f6f805d341f
* Version Independent ID: 9c9c8acd-5c0f-a681-58c8-86bab3942748
* Content: [findstr](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/findstr#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/findstr.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/findstr.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Looks like missing escape characters causing the remaining backslashes to become hidden.
Content source:
https://raw.githubusercontent.com/MicrosoftDocs/windowsserverdocs/master/WindowsServerDocs/administration/windows-commands/findstr.md

```
  |Metacharacter|Value|
  |-------------|-----|
  |.|Wildcard: any character|
  |*|Repeat: zero or more occurrences of the previous character or class|
  |^|Line position: beginning of the line|
  |$|Line position: end of the line|
  |[class]|Character class: any one character in a set|
  |[^class]|Inverse class: any one character not in a set|
  |[x-y]|Range: any characters within the specified range|
  |\x|Escape: literal use of a metacharacter x|
  |\\<string|Word position: beginning of the word|
  |string\>|Word position: end of the word|
```
Does the following table look correct to you, or do we need more corrections?

  | Metacharacter | Value |
  |:-------------:| ----- |
  |       .       | Wildcard: any character |
  |       *       | Repeat: zero or more occurrences of the previous character or class |
  |       ^       | Line position: beginning of the line |
  |       $       | Line position: end of the line |
  |    [class]    | Character class: any one character in a set |
  |   [^class]    | Inverse class: any one character not in a set |
  |     [x-y]     | Range: any characters within the specified range |
  |     \\x       | Escape: literal use of a metacharacter x |
  |   \\<string   | Word position: beginning of the word |
  |   string\\>   | Word position: end of the word |

**Comment by illfated** [comment]
Hmm. I thought there would have been some form of update to the referenced page (**findstr**) during this last year, but not regarding this ticket. Oh well. I could always have a go at adding that missing backslashes. (Have to remember to look for more than one line where the backslashes are not escaped properly.)

**Comment by illfated** [comment]
There you go. PR #5107 is ready for review. That PR will automatically close this ticket upon being merged.
