### ISSUE TITLE
Incorrect Parameter Descriptions

### ISSUE THREAD

**Issue by AdamTogether** [MicrosoftDocs/windowsserverdocs#3675]
In this article, descriptions for MINIMUM and DESIRED are incorrect. I got the real descriptions of these parameters by typing "help shrink" while in a diskpart session.

DESIRED=&lt;N&gt; specifies the desired amount of space in megabytes (MB) to reduce the size of the volume by. If a desired amount is not specified, the volume will be reduced by the maximum amount of free space available on the volume.

MINIMUM=&lt;N&gt; specifies the amount of space in MB to reduce the size of the volume by.

Example usage:
DISKPART&gt; shrink querymax
The maximum number of reclaimable bytes  is:    381 GB (391092 MB)
DISKPART&gt; shrink desired=391092 minimum=350000

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c239a12-7ff2-36a3-d958-0333c902f622
* Version Independent ID: affcc675-fb6c-4e2c-dffc-bc48ef5347e4
* Content: [Shrink a basic volume](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/shrink-a-basic-volume#feedback)
* Content Source: [WindowsServerDocs/storage/disk-management/shrink-a-basic-volume.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/shrink-a-basic-volume.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
