### ISSUE TITLE
The term 'Update-WebApplicationProxyDeviceRegistration' is not recognize d as the name of a cmdlet

### ISSUE THREAD

**Issue by Feredzhanov** [MicrosoftDocs/windowsserverdocs#3677]
I'm getting the following response, when running `Update-WebApplicationProxyDeviceRegistration`.
```
Update-WebApplicationProxyDeviceRegistration : The term 'Update-WebApplicationProxyDeviceRegistration' is not recognize
d as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
 included, verify that the path is correct and try again.
At line:1 char:1
+ Update-WebApplicationProxyDeviceRegistration
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Update-WebAppli...iceRegistration:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by illfated** [comment]
Did you get here from the page **Configure a federation server with Device Registration Service**
- https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/configure-a-federation-server-with-device-registration-service)
and its GitHub source page
- https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Configure-a-federation-server-with-Device-Registration-Service.md

?

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
