### ISSUE TITLE
specialization values and Linux

### ISSUE THREAD

**Issue by inorangestylee** [MicrosoftDocs/windowsserverdocs#3680]
is specialization values works with linux-based OS?
tried it with powershell and vmm, result - can't obtain IP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf31f5cf-8755-b0c4-7d17-f9f263ac0099
* Version Independent ID: d33ed427-44ed-ea0c-fb6d-efd45ce0b42b
* Content: [Create a shielded VM using PowerShell](https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-create-a-shielded-vm-using-powershell#feedback)
* Content Source: [WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-create-a-shielded-vm-using-powershell.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-create-a-shielded-vm-using-powershell.md)
* Product: **windows-server**
* Technology: **security-guarded-fabric**
* GitHub Login: @rpsqrd

**Comment by rpsqrd** [comment]
It should work. Did you install the [VMM guest agent](https://docs.microsoft.com/en-us/system-center/vmm/vm-linux?view=sc-vmm-2019#install-the-vmm-guest-agent) in the Linux template disk?

**Comment by inorangestylee** [comment]
Yeap, i tried with it and w/o. IP not assigned. Ubuntu 16.04.6

**Comment by inorangestylee** [comment]
is vmm guest agent used for IP injection? not LIS?

**Comment by rpsqrd** [comment]
It is, yes. LIS reports on the current IP of the VM, but the VMM guest agent is responsible for "specializing" the OS and setting the static IP.

Do you see other changes apply to the VM, like the hostname or SSH keys (if you provided your public key in the VMM deployment wizard)? I'm curious whether all of the guest specialization tasks are failing or if it's just the IP configuration.

**Comment by inorangestylee** [comment]
Im trying to deploy shielded linux vm (ubuntu 16.04.6). After first reboot i see old ip in hyper-v manager network tab of VM (icmp passed/ssh failed). Im tried deploy with VMM and powershell `New-ShieldedVM` - same result

**Comment by inorangestylee** [comment]
i found problem, `New-ShieldingDataAnswerFile` from `GuardedFabricTools` makes wrong format answerfile

**Comment by rpsqrd** [comment]
Can you share what the cmdlet is outputting vs. what the VMM guest agent is expecting? Was it the structure of the file or just the values?

**Comment by IngridAtMicrosoft** [comment]
Thanks for your dedication to our documentation. If we have been unable to review your issue in a timely manner, we sincerely apologize for the delayed response. We have captured the informtion you have provided for review. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
