### ISSUE TITLE
is it an scp server also? how to enable?

### ISSUE THREAD

**Issue by ttulinsky** [MicrosoftDocs/windowsserverdocs#3681]
I installed the Openssh server to my Windows 10 pc and it works fine for serving ssh and sftp. Scp to it does not work, however. 
(I installed by the Powershell method above because the Settings, Manage Optional Features method did not work (hung).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8761c3f4-36ea-6eb4-c10c-48c3c6b35e79
* Version Independent ID: 2afc10e3-47f8-7515-9ce5-5c4b79ccab1b
* Content: [OpenSSH Server Configuration for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_server_configuration#feedback)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Server_Configuration.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Server_Configuration.md)
* GitHub Login: @maertendMSFT

**Comment by illfated** [comment]
You may want to ask in other places than this. https://github.com/MicrosoftDocs/ is mostly meant for reporting issues in the documentation and suggestions to improve the docs. Of course, some times there may be someone with experience relevant to your issue, but there is no guarantee that you will get a solution here.

Based on this, I recommend asking in TechNet forum pages or social.microsoft.com pages, whichever suits your question best.

Should you find a solution to your question, we welcome any feedback to add a comment or note to the article in case that solution is useful for others as well (and within MS supported limits).

**Comment by illfated** [comment]
Just to make it clear; thank you for asking the question, feel free to contribute any verifiable and useful information you come across to improve the current documentation.

That being said, I still recommend asking questions in forums and support areas. We would like to see feedback based on verified answers for a possible use in the docs.microsoft.com pages. The MS Docs Server team usually does not have the capacity to follow up on questions, unless addressing issues in the documentation page along with suggestions for improvements.

**Comment by illfated** [comment]
#please-close
