### ISSUE TITLE
To many backslashes

### ISSUE THREAD

**Issue by tom1stein** [MicrosoftDocs/windowsserverdocs#3685]
The line "call :\&lt;Label&gt; &lt;Arguments&gt;" is wrong: There shall be no backslash in this line.
The sentence "The %~ modifiers cannot be used with %\*." is wrong: There shall be no backslash in this sentence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 144631f0-4625-641e-7bb5-63a5d0f49f27
* Version Independent ID: 8db973db-7eeb-acc6-0f1b-db598a8de43b
* Content: [call](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/call#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/call.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/call.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Yeah, well, someone went a bit overboard with the backslashes there when adding the backslash as an escape character to keep the asterisk from being used as a MarkDown formatting tag.

```
In the above examples, **%1** and PATH can be replaced by other valid values.
The <strong>%~</strong> syntax is terminated by a valid argument number.
The <strong>%~</strong> modifiers cannot be used with **%\\\***.
```

When adding the back ticks around the `call :\<Label> <Arguments>` example, they must have forgotten that back ticks will almost always cancel the need for escape characters.

Oh well. I will create a pull request to suggest getting rid of those redundant backslashes.

**Comment by illfated** [comment]
I goofed up my PR when I rebased it on more recent https://github.com/MicrosoftDocs/windowsserverdocs/tree/master content to have it within visible range in my Git Extensions application on my local computer. I will need to recreate the PR by basing it on the currently up-to-date content of the master branch.

(if I have not recreated a PR for this issue within this weekend, please remind me of my task.)

**Comment by illfated** [comment]
OK, so I just found my way back to this ticket, realizing that this has not been dealt with yet. Fair enough. I will update my local cloned repo and create a new PR based on the old one.
