### ISSUE TITLE
Example is not clear for beginners

### ISSUE THREAD

**Issue by mralmostperfect** [MicrosoftDocs/windowsserverdocs#3689]
Hello, 
Could you please make the example a little bit easier to read for beginners?
I can't understand most of the code used for the commands, but a course (https://learnpythonthehardway.org/book/appendix-a-cli/ex15.html) expect me to learn "forfiles" by myself.
For instance, maybe you can use "new-file text.txt" for an 'example' of example. It's easier to understand and only use the necessary command to run.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ebfe8b1-07af-a46f-d839-4ee4b15f55d1
* Version Independent ID: f96a4e35-724e-1bb0-1f6d-7c67ca500313
* Content: [forfiles](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/forfiles#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/forfiles.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/forfiles.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
As much as I would like to indulge you by opening a Pull Request to suggest a change to the page, I don't see the need in this case. There are several reasons why the documentation page is written as it is and why it should almost only be changed if there are any factual errors in the page. There is also the notion that you are expected, by the Python course, to find out and learn as much as possible on your own, maybe accompanied by one or more fellow students of that course, and I quote:

- "For your last set of exercises I'm going to have you use the help system to look up a set of commands you should **research and learn how to use on your own**."
- "Find out what these are, play with them, and then add them to your index cards."

I recommend checking out the [Command-Line Syntax Key](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/command-line-syntax-key) to understand how the doc page indicates when parameters (or arguments) are optional and when they are required.

Should you find that there are any discrepancies in this page, maybe even requiring that a better example should be included, feel free to post a reference or comparison to indicate how this page can be improved.

**Comment by illfated** [comment]
Also, to quote the Windows help text:

<details>
```
C:\Users\illfated>forfiles /?

FORFILES [/P pathname] [/M searchmask] [/S]
         [/C command] [/D [+ | -] {dd.MM.yyyy | dd}]

Description:
    Selects a file (or set of files) and executes a
    command on that file. This is helpful for batch jobs.

Parameter List:
    /P    pathname      Indicates the path to start searching.
                        The default folder is the current working
                        directory (.).

    /M    searchmask    Searches files according to a searchmask.
                        The default searchmask is '*' .

    /S                  Instructs forfiles to recurse into
                        subdirectories. Like "DIR /S".

    /C    command       Indicates the command to execute for each file.
                        Command strings should be wrapped in double
                        quotes.

                        The default command is "cmd /c echo @file".

                        The following variables can be used in the
                        command string:
                        @file    - returns the name of the file.
                        @fname   - returns the file name without
                                   extension.
                        @ext     - returns only the extension of the
                                   file.
                        @path    - returns the full path of the file.
                        @relpath - returns the relative path of the
                                   file.
                        @isdir   - returns "TRUE" if a file type is
                                   a directory, and "FALSE" for files.
                        @fsize   - returns the size of the file in
                                   bytes.
                        @fdate   - returns the last modified date of the
                                   file.
                        @ftime   - returns the last modified time of the
                                   file.

                        To include special characters in the command
                        line, use the hexadecimal code for the character
                        in 0xHH format (ex. 0x09 for tab). Internal
                        CMD.exe commands should be preceded with
                        "cmd /c".

    /D    date          Selects files with a last modified date greater
                        than or equal to (+), or less than or equal to
                        (-), the specified date using the
                        "dd.MM.yyyy" format; or selects files with a
                        last modified date greater than or equal to (+)
                        the current date plus "dd" days, or less than or
                        equal to (-) the current date minus "dd" days. A
                        valid "dd" number of days can be any number in
                        the range of 0 - 32768.
                        "+" is taken as default sign if not specified.

    /?                  Displays this help message.

Examples:
    FORFILES /?
    FORFILES
    FORFILES /P C:\WINDOWS /S /M DNS*.*
    FORFILES /S /M *.txt /C "cmd /c type @file | more"
    FORFILES /P C:\ /S /M *.bat
    FORFILES /D -30 /M *.exe
             /C "cmd /c echo @path 0x09 was changed 30 days ago"
    FORFILES /D 01.01.2001
             /C "cmd /c echo @fname is new since Jan 1st 2001"
    FORFILES /D +15.1.2020 /C "cmd /c echo @fname is new today"
    FORFILES /M *.exe /D +1
    FORFILES /S /M *.doc /C "cmd /c echo @fsize"
    FORFILES /M *.txt /C "cmd /c if @isdir==FALSE notepad.exe @file"

C:\Users\illfated>_
```

</details>

**Comment by illfated** [comment]
You could also search the web for usage examples that you may find easier to see how the command is used:
- https://www.bing.com/search?q=forfiles

Wikipedia has a page about it closely related to the Microsoft Docs page: 
- https://en.wikipedia.org/wiki/Forfiles

**Comment by illfated** [comment]
@mralmostperfect : Please note that the linked page is a reference page, and a limited reference as such. There are more complete reference pages available elsewhere, both in the /previous-versions/ directory and https://ss64.com/nt/forfiles.html .

Knowing that reference pages won't be changed unless actual errors are found and reported, I don't think there will ever be any attempts to change the reference page to be more user friendly for beginners.

Based on these known limitations, I will ask for this ticket to be closed. Feel free to reopen this ticket (if possible) or open a new one, preferably to report factual issues with the page, or suggest what the text should look like. Anyway, I believe beginner instructions belong in a different part of the documentation than in a reference page.

**Comment by illfated** [comment]
#please-close
