### ISSUE TITLE
Missing backslash

### ISSUE THREAD

**Issue by fceledon** [MicrosoftDocs/windowsserverdocs#3690]
on 'Syntax' [log  …] must be [/log …]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c311f8b4-82f9-e1cb-9b6a-e284a5fff8cc
* Version Independent ID: b0b9374c-2a7f-25be-d9e2-38d26c5047aa
* Content: [secedit:generaterollback](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/secedit-generaterollback)
* Content Source: [WindowsServerDocs/administration/windows-commands/secedit-generaterollback.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/secedit-generaterollback.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
That looks correct, the slash (as opposed to backslash) is missing in the start of the article, but present in the Secedit command.
I will open a pull request to suggest the correction.
