### ISSUE TITLE
Misleading application of comments in examples

### ISSUE THREAD

**Issue by ld0614** [MicrosoftDocs/windowsserverdocs#3691]
The initial example includes what looks like valid comment Syntax giving the impression that it is possible to comment the CAPolicy.inf file.  After an embarrassingly long time I found out that this was not the case (or not consistent).  It would be good to have a clarified statement as to what is possible when it comes to comments.

On a side note the quotes in the examples appear to be right quotation marks (https://unicode-table.com/en/201D/) rather than universal quotes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8ffdaef-7179-7cfc-ceb3-7443fe3e9476
* Version Independent ID: e5c1e3a8-9b73-d314-df06-c6da3a3adf67
* Content: [Prepare the CAPolicy.inf File](https://docs.microsoft.com/en-us/windows-server/networking/core-network-guide/cncg/server-certs/prepare-the-capolicy-inf-file)
* Content Source: [WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Prepare-the-CAPolicy-inf-File.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Prepare-the-CAPolicy-inf-File.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by illfated** [comment]
Fair point, I agree that it looks quite odd that some of the double quote characters are not standard double quote ( " ). Normally, standard quote characters would be used to border a string value, typically containing spaces, in most text values. Unfortunately, I don't know this topic well enough to provide any useful answers.

**Comment by RAJU2529** [comment]
@illfated . All most of the .inf files are device drivers correct. Then why CApolicy file should be saved .inf extension

Policies are in the form of .xml

**Comment by illfated** [comment]
I don't know. If you can find other information about `CAPolicy.inf` and its internal formatting, maybe that information should be added to the document article?

**Comment by RAJU2529** [comment]
@illfated . Thanks for replying. I will look

**Comment by dknappettmsft** [comment]
Thanks for the feedback @ld0614. I have removed those comments from the example code block as they're not correct and there is already some explanation of what the two lines are in the sentence immediately above. The code was incorrectly labelled as PowerShell.  I have also corrected the quotation marks.  The changes should be visible later today.

As a side note, here's an article we have on syntax rules for INF files, specifically how to add comments: https://docs.microsoft.com/en-us/windows-hardware/drivers/install/general-syntax-rules-for-inf-files#-line-format-continuation-and-comments.

#please-close

**Comment by ld0614** [comment]
Thanks for the update @dknappettmsft  and the link to the document was very useful 😄
