### ISSUE TITLE
Missing details on how to set up emergency access accounts for on-premises AD

### ISSUE THREAD

**Issue by jrbilodeau** [MicrosoftDocs/windowsserverdocs#3692]
In the Separate accounts section of the article it says to create at least two emergency access accounts in both your on-premises AD and Azure AD environments, but the article that it links to only describes the steps to do this in Azure AD. I've searched and can't find any details or Microsoft recommendation on doing this for an on-premises AD environment. It would be great if Microsoft could provide more detailed guidance on setting this up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd8b02b-0cf1-3664-d930-4f76b7f2a59d
* Version Independent ID: 8097a4ba-84b3-5bfd-6771-6cd1a4bf926a
* Content: [Securing privileged access](https://docs.microsoft.com/en-us/windows-server/identity/securing-privileged-access/securing-privileged-access#feedback)
* Content Source: [WindowsServerDocs/identity/securing-privileged-access/securing-privileged-access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/securing-privileged-access/securing-privileged-access.md)
* Product: **windows-server**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
Same guidance just in on-premises AD. Should be able to make the translation pretty easily. The only portion that doesn't really is monitoring.

https://docs.microsoft.com/azure/active-directory/users-groups-roles/directory-emergency-access#create-emergency-access-accounts

**Comment by dknappettmsft** [comment]
Answer provided above.

#please-close
