### ISSUE TITLE
ECMP and MUX?

### ISSUE THREAD

**Issue by cveld** [MicrosoftDocs/windowsserverdocs#3694]
When I issue a ping to the VIP I get a response back for every node in the cluster.
In contrast, an http call only arrives at one DIP. Is this done by ECMP and multiple MUXes behind one VIP? As explained on https://docs.microsoft.com/en-us/windows-server/networking/sdn/technologies/network-function-virtualization/software-load-balancing-for-sdn

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4033074-a430-bda9-66bf-3704bbbc38f5
* Version Independent ID: a12550bb-83a2-9c48-7d36-9b5d6336e017
* Content: [Network Load Balancing](https://docs.microsoft.com/en-us/windows-server/networking/technologies/network-load-balancing#feedback)
* Content Source: [WindowsServerDocs/networking/technologies/Network-Load-Balancing.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/Network-Load-Balancing.md)
* Product: **windows-server**
* Technology: **networking-nlb**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by robinharwood** [comment]
We hugely appreciate your contribution, feedback, and support to our technical documentation.

We’ve phased out GitHub Issues on this repository as the feedback mechanism for content and have replaced it with a new feedback system. For more information see, [Content User Feedback](https://aka.ms/ContentUserFeedback). As part of this rollout, we are migrating your issue where our team will use your comments to improve the documentation experience. Unfortunately, this does mean you won't be able to access this issue after the migration is complete.

All issues will be migrated by Thursday 29th August 2024.

Once again, thank you for your valuable feedback, we hope you’ll continue to contribute using our new feedback system.
