### ISSUE TITLE
RDC 10.3.7 (1733) - Issue - Consuming Space on Local Mac (Catalina (10.15.2))

### ISSUE THREAD

**Issue by stealth1188** [MicrosoftDocs/windowsserverdocs#3697]
I have been doing a lot of copying and pasting to a USB drive (attached to a Windows 10 laptop, not my Macbook) via RDC lately and I have started noticing my Mac local drive is starting to fill up. Upon further digging, I have noticed the files are also being copied to my local drive on my MacBook under a folder in "/private/var/folders/". Not sure if I'm the only one seeing this.

1. RDC to a windows 10 box
2. Start copying and pasting within windows 10
3. On your Mac, open a terminal session
   - su -
   - cd /private/var/folders/
   - du -hs * | sort -hr (repeatedly and you'll notice the diskspace is starting to grow on one of the folder. Feel free to naviagte to the folder and you'll find a copy of the files are stored on your local drive as well. The only way to resolve this is to use cmd "rm -Rf ..." or reboot.

**Comment by stealth1188** [comment]
Ha...similar issue mentioned at https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/mac-whatsnew ...

" Note

There is a bug in macOS 10.14.0 and 10.14.1 that can cause the ".com.microsoft.rdc.application-data_SUPPORT/_EXTERNAL_DATA" folder (nested deep inside the ~/Library folder) to consume a large amount of disk space. To resolve this issue, delete the folder content and upgrade to macOS 10.14.2. Note that a side-effect of deleting the folder contents is that snapshot images assigned to bookmarks will be deleted. These images will be regenerated when reconnecting to the remote PC."

**Comment by dknappettmsft** [comment]
As noted above, this is a known issue with macOS 10.14.0 and 10.14.1 that is resolved in macOS 10.14.2.

#please-close
