### ISSUE TITLE
some network connection states have weird capitalization

### ISSUE THREAD

**Issue by thetorpedodog** [MicrosoftDocs/windowsserverdocs#3698]
in the "state" list, parts of the possible values have been converted to lowercase:

&gt; The possible states are as follows: CLOSE_WAIT CLOSED ESTABLISHED FIN_WAIT_1 FIN_WAIT_2 LAST_ACK listEN SYN_RECEIVED SYN_SEND timeD_WAIT for more information about the states of a TCP connection, see Rfc 793.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32e22509-0790-98ec-29f0-f4a45af86079
* Version Independent ID: a8481c2f-a27e-ecff-6c79-0e4f63ce18a4
* Content: [netstat](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/netstat#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/netstat.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/netstat.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by dknappettmsft** [comment]
Thanks for the feedback. I notice this has been corrected in this commit: https://github.com/MicrosoftDocs/windowsserverdocs/commit/05d5af3f69ee8c235be86a28365859a8658a866c

#please-close
