### ISSUE TITLE
shared connections being converted to personal

### ISSUE THREAD

**Issue by themarkdiesel** [MicrosoftDocs/windowsserverdocs#3702]
We have an issue with connections that are set up as Shared Connections spontaneously being converted to a Personal connection for a single user. Seems to happen after configuring an on-prem for Azure Monitor.

Is there a way to convert a Personal Connection (back) to a Shared?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3594ea3-f917-d4b6-206e-91506ebb0199
* Version Independent ID: 4445d261-105e-cb44-87bf-e14af8253b34
* Content: [Configure shared connections for all users of the Windows Admin Center gateway](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/configure/shared-connections#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/configure/shared-connections.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/configure/shared-connections.md)
* Product: **windows-server**
* Technology: **manage**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by Weirdosrock** [comment]
Use the powershell module to export the share to a csv, edit the csv to include the global entry, and reimport the csv.

**Comment by themarkdiesel** [comment]
Which I've done, but after re-importing them, they eventually turn back into personal connections as they're accessed.

**Comment by dknappettmsft** [comment]
Hi @themarkdiesel, a better place to log this would be with the WAC team at https://aka.ms/wacfeedback as that is managed by the product group. They can help triage this to see if it's a bug and what the solution might be.  If there's something to alter in this article afterwards, they can also update it.

#please-close
