### ISSUE TITLE
Broken table and Missing State in Bitsadmin\getstate

### ISSUE THREAD

**Issue by WiVi71** [MicrosoftDocs/windowsserverdocs#3703]
https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/bitsadmin-getstate.md
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/bitsadmin-getstate

- The table in "Remarks"is broken.

The html table is broken; but the previous version of this article does not. [[Link]](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc770572(v%3Dws.11)#remarks)

- There is a missing state in "Remarks"

![이미지 5](https://user-images.githubusercontent.com/59140461/71869171-659ca500-3154-11ea-9a30-248d05cc69a3.png)
![이미지 6](https://user-images.githubusercontent.com/59140461/71869389-3dfa0c80-3155-11ea-977d-ecf18cdab20a.png)

The "TRANSFERRED" state does not exist in this article
The "TRANSFERRED" state sample is in [[this link]](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/bitsadmin-examples#monitoring-jobs-in-the-transfer-queue)

**Comment by illfated** [comment]
OK, I see. The table appears to be missing its header row, thereby broken by not containing its required row structure.

I will open a PR to suggest how it can be restored. Will also try to add the missing state in the table.
