### ISSUE TITLE
Need not be sitting

### ISSUE THREAD

**Issue by kdheerendra** [MicrosoftDocs/windowsserverdocs#3706]
The statement should be:
If you only want to access your PC when you are physically able to operate of it, you don't need to enable Remote Desktop.

instead of:
If you only want to access your PC when you are physically sitting in front of it, you don't need to enable Remote Desktop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71cfbf1a-c5b7-df0f-8194-6ebc03afcc7d
* Version Independent ID: f36b567f-aa48-2c8f-4908-b1fe18cd2842
* Content: [Remote Desktop - Allow access to your PC](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-allow-access#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-allow-access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-allow-access.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
Fair point, I do not believe there is any form of detection whether the user is sitting or not. We are not dealing with game characters, after all.

I have an idea to adjust your suggestion so it better describes a more general scenario of being present at the physical device, so I will open a Pull Request to have that sentence remediated.
