### ISSUE TITLE
Node Package Manager (8.12.0 or later) is misleading

### ISSUE THREAD

**Issue by itsTreble** [MicrosoftDocs/windowsserverdocs#3708]
Currently, the latest npm version is 6.13.4.  I think you mean Node.js version 8.12.0 or higher.  Node.js includes npm 6.13.4, running "npm install npm@latest" at this point in time gives you 6.13.4.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 229f7b83-a501-f0b9-6b3b-bffc84b04554
* Version Independent ID: 7d5f608f-bc6d-6ab6-c186-83dda2ae922d
* Content: [Prepare your development environment](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/extend/prepare-development-environment#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/extend/prepare-development-environment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/extend/prepare-development-environment.md)
* Product: **windows-server**
* Technology: **manage**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by ItzLevvie** [comment]
The wording used here is correct.

For more information visit [this](https://english.stackexchange.com/questions/112257/above-or-later-when-referencing-a-range-of-versions-of-software).

**Comment by dknappettmsft** [comment]
#assign:dknappettmsft

**Comment by dknappettmsft** [comment]
Thanks for the feedback. This has been corrected and should be visible later today.

#please-close
