### ISSUE TITLE
this is not referencing the official azure upload doc

### ISSUE THREAD

**Issue by ScottAzure** [MicrosoftDocs/windowsserverdocs#3712]
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/prepare-for-upload-vhd-image

You can reach me at scotro@micro...com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eb610cb-6ff0-e164-7694-ef22d4a2ccaa
* Version Independent ID: e4a98df5-1192-6cd0-1410-f80ddb69e144
* Content: [Upload a Windows Server 2008/2008 R2 specialized image to Azure](https://docs.microsoft.com/en-us/windows-server/get-started/uploading-specialized-ws08-image-to-azure)
* Content Source: [WindowsServerDocs/get-started/uploading-specialized-WS08-image-to-azure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/uploading-specialized-WS08-image-to-azure.md)
* Product: **windows-server**
* GitHub Login: @MikeBlodge
* Microsoft Alias: **mikeblodge**

**Comment by dknappettmsft** [comment]
I'm tidying up some of the issues in this repo and I've noticed that the article you flagged (https://docs.microsoft.com/en-us/windows-server/get-started/uploading-specialized-ws08-image-to-azure) no longer exists and now automatically redirects to https://docs.microsoft.com/en-us/azure/virtual-machines/windows/upload-generalized-managed.

If there's anything further you need on this (e.g. the redirection altering), please comment here and I'll get it updated.  Thanks.

#please-close
