### ISSUE TITLE
Warning needed when changing DNS of windows NIC

### ISSUE THREAD

**Issue by marcosgm** [MicrosoftDocs/windowsserverdocs#3713]
As shown in https://redmondmag.com/articles/2018/06/12/azure-vm-dns-settings.aspx
Using the UI widget to change DNS resolution servers in many windows server versions will cause RDP connection to fail and force the VM to be rebooted.
Using powershell to perform the change avoids that.

# Get-NetAdapter  #to see the interface index, in my case 2
# Set-DnsClientServerAddress  -interfaceIndex 2 -ServerAddresses ("192.168.0.4","8.8.4.4")

# to revert the settings to DHCP-provided
# Set-DnsClientServerAddress  -interfaceIndex 2 -resetserveraddress

Fore reference, https://docs.microsoft.com/en-us/powershell/module/dnsclient/set-dnsclientserveraddress?view=win10-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e3ea72d-d69c-15e6-74b0-d90c18c0b6ba
* Version Independent ID: fcb5f4fa-4636-0547-4030-87230ef02376
* Content: [Install Active Directory Domain Services on an Azure virtual machine](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by illfated** [comment]
The need for rebooting a VM after changing the DNS records is to some extent covered here:
- https://docs.microsoft.com/azure/virtual-network/manage-virtual-network#change-dns-servers
(Page linked from https://docs.microsoft.com/windows-server/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm#dns-and-active-directory .)

5. Select **Save**.
6. Restart the VMs that are connected to the virtual network, so they are assigned the new DNS server settings. VMs continue to use their current DNS settings until they are restarted.

Even so, the PowerShell commands to perform the changes without losing connection to the VM via RDP could possibly be a useful addition somewhere in this documentation. Not quite sure yet where to put it, how to phrase it, and if it should be a Note blob or not.

**Comment by dknappettmsft** [comment]
Hi @marcosgm, Azure configures the NIC inside the VM from the configuration of the VNet, any changes to IP configuration must be done from the Azure VNet, rather than in the VM itself.  This article does reference links of how to do this for a VNet and doesn't suggest making the change in the VM.

#please-close
