### ISSUE TITLE
2012R2 to 2019?

### ISSUE THREAD

**Issue by stokes776** [MicrosoftDocs/windowsserverdocs#3714]
Can I go directly from 2012R2 OS to OS 2019?

The document references 2012R2 to 2016, but also mentions this is for going to '2016 and beyond'. Do I need to go to 2016 FIRST or can I go straight to 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60832ce0-4687-b723-afd3-0fba3fec54d7
* Version Independent ID: 28ce8f7a-0280-65e3-3fe5-d07cdfd6405f
* Content: [Cluster Operating System Rolling Upgrade](https://docs.microsoft.com/en-us/windows-server/failover-clustering/cluster-operating-system-rolling-upgrade#frequently-asked-questions)
* Content Source: [WindowsServerDocs/failover-clustering/Cluster-Operating-System-Rolling-Upgrade.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/Cluster-Operating-System-Rolling-Upgrade.md)
* Product: **windows-server**
* Technology: **storage-failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by PRMerger12** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: ingridatmicrosoft 
gh issue comment 3675 -b ingridatmicrosoft

**Comment by dknappettmsft** [comment]
Hi, using the Cluster OS rolling upgrades feature you have to go through each OS version in sequence, i.e. 2012 R2 > 2016 > 2019 > 2022.  I've created an item in our backlog to update this article to cater for later releases of Windows Server and include this information.  Thank you for the feedback.

#please-close
