### ISSUE TITLE
Errors in `start` internal command documentation?

### ISSUE THREAD

**Issue by mpilgrem** [MicrosoftDocs/windowsserverdocs#3719]
The following appear to me to errors in the documentation of the internal `start` command:

1. The syntax is given as including : `[/b {<Command> | <Program>} [<Parameters>]]`. This conflicts with the command's built-in help, which specifies: ` [/B] [command/program] [parameters]`.

   I think the correct specification may be: `[/b] [<Command> [< Parameter>...] | <Program> [<Parameter>...]]`. That is, `Command` and `Program` are alternatives, but neither need be present, and each, if present, may have none, one or many `Parameters`; however, a `Parameter` cannot be given if there is no `Command` or `Program` specified. 

2. Similar to the above, there is a stray initial `/b` in the description of `/b <Command> | <Program>      Specifies the command or program to start.`

3. The default value for `PATHEXT` is said to be `.COM;.EXE;.BAT;.CMD` (including in the command's built-in help) but elsewhere (eg https://superuser.com/questions/1027078/what-is-the-default-value-of-the-pathext-environment-variable-for-windows or https://ss64.com/nt/syntax-variables.html) it is said that the default (for many versions of Windows) differs from that. It is `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC` on my Windows 10 machines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1bd2afb-c69f-7032-6331-a44599b55ad5
* Version Independent ID: c206ae8f-d626-b779-a893-7eb7ceaf719d
* Content: [Command-Line Syntax Key](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/command-line-syntax-key)
* Content Source: [WindowsServerDocs/administration/windows-commands/command-line-syntax-key.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/command-line-syntax-key.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
It took me a couple of minutes to realize that you have got an issue with the documentation page of the `start` command, but you posted this issue on the Command-Line Syntax Key page to point out the logical implications of the different brackets in the command syntax. Fair enough.

Just to make sure we are on the same page: is this page the start command documentation page you are referring to?
- https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start

**Comment by mpilgrem** [comment]
@illfated, yes, that is correct. I clicked on the link offered at the bottom of that page (Feedback/This page/You may also leave feedback directly on GitHub) and it took me here with a template to fill in.

**Comment by illfated** [comment]
Thank you for your reply. No, I think it will be fine for now, just make sure you report future findings on the right page so we don't start guessing. For now, it is quite OK to use the syntax page as a reference to what we should fix in the page https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start .

BTW, would you like to create a Pull Request for the change, or do you prefer that someone else like me to open a PR for this?

**Comment by mpilgrem** [comment]
@illfated, I have created a pull request that reflects my comments.

**Comment by illfated** [comment]
Very good. Now we start the waiting game, to see if the PR gets its deserved attention.
