### ISSUE TITLE
I have no idea what this page is trying to say.

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/windowsserverdocs#3723]
I think I'm more confused after reading it than I was before.

So if my domain fqdn is foo.bar.com, I need an A record for federation_service_name.foo.bar.com to have the same ip address as my ADFS STS (adfs.bar.com) and a CNAME record for enterpriseregistration.foo.bar.com with a cn of federation_service_farm_name.bar.com (even though that name doesn't exist)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d85340da-1faa-406d-5b40-b542e348e3e3
* Version Independent ID: 9c5d7601-81ef-f60a-a483-27b8ca144e8b
* Content: [Configure Corporate DNS for the Federation Service and DRS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/configure-corporate-dns-for-the-federation-service-and-drs)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Configure-Corporate-DNS-for-the-Federation-Service-and-DRS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Configure-Corporate-DNS-for-the-Federation-Service-and-DRS.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
Thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

#please-close
