### ISSUE TITLE
Must or must not terminate SSL before WAP?

### ISSUE THREAD

**Issue by Davidddddddddd** [MicrosoftDocs/windowsserverdocs#3725]
This document states that "Any load balancer or network device that does not forward at layer 3 (IP is preserved) should add the incoming client IP to the industry standard x-forwarded-for header.".  

The above cannot be achieved without terminating SSL.

Yet section "What are load balancing requirements for AD FS and WAP servers?" says
Load balancers MUST not terminate the HTTPS connections and reinitiate a new connection to the ADFS server.

Can the article please explain why you "MUST NOT" terminate SSL and yet you "should terminate SSL" under certain conditions?  Without clarification, these statements appear contradictory.  
1. Please clarify this in the document.  
2. If a specific feature such as "Certificate Authentication use cases" will be broken by a particular configuration such as termination / recreation of SSL connection before the WAP servers, then please state this in the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8396683-4498-71bd-60a1-345277e1433e
* Version Independent ID: 36ed02b0-555a-4714-32f8-f4e0434adf51
* Content: [AD FS FAQ](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-faq#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/AD-FS-FAQ.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/AD-FS-FAQ.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
Thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

#please-close
