### ISSUE TITLE
Another broken link

### ISSUE THREAD

**Issue by FredVH** [MicrosoftDocs/windowsserverdocs#3726]
"Instructions for applying a cab are available in this blog post" --&gt; link broken:
https://blogs.technet.com/b/virtualization/archive/2015/07/24/integration-components-available-for-virtual-machines-not-connected-to-windows-update.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1c56e1b-ebdd-eefc-6a61-91ab0f09ad8a
* Version Independent ID: 359ead50-4b39-55cf-691f-f667c7a1389a
* Content: [Manage Hyper-V Integration Services](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/manage-hyper-v-integration-services#feedback)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/Manage-Hyper-V-integration-services.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/Manage-Hyper-V-integration-services.md)
* Service: **na**
* Product: **windows-server**
* Technology: **compute-hyper-v**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by illfated** [comment]
Resolved in PR #3954 and commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/580bdd7c71d693d3bb196c017b2fe840bd5187c8 .

**Comment by illfated** [comment]
#please-close
