### ISSUE TITLE
Server 2008 and above have new defaults for MaxPosPhaseCorrection and MaxNegPhaseCorrection values

### ISSUE THREAD

**Issue by ChrisAtMAF** [MicrosoftDocs/windowsserverdocs#3729]
In Windows Server 2008, a new default value for the MaxPosPhaseCorrection and MaxNegPhaseCorrection registry entries has been adopted. This new default value is 48 hours. This 48-hour value can be represented as either of the following values:
2a300 (hexadecimal)
172800 (decimal)

https://support.microsoft.com/en-gb/help/884776/how-to-configure-the-windows-time-service-against-a-large-time-offset

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc978a2-5a8b-c6af-0c56-f762ea9edf16
* Version Independent ID: 33693e91-d1a2-10c0-0dd7-43167114868a
* Content: [Windows Time Service Tools and Settings](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings)
* Content Source: [WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by dknappettmsft** [comment]
Hi @ChrisAtMAF, thanks for the feedback. This default value of 48 hours is for Active Directory domain controllers, which I've added to the table in the article you logged this issue against (https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings).

The default value for domain members is still 0xFFFFFFFF, and the default value for stand-alone clients and servers is still 54,000 (15 hrs).

The changes should be visible later today.

#please-close

**Comment by dknappettmsft** [comment]
#assign:dknappettmsft
