### ISSUE TITLE
cannot use input field inside remote session

### ISSUE THREAD

**Issue by Inter-Psy** [MicrosoftDocs/windowsserverdocs#3730]
We are unable to use an input field within one of our web applications within our RDS farm.
To access this application we login to the html5 client. 

Start Firefox (inside the remote session)
then go to our web application and there is a special kind of input field which only accepts digits and it is this input field which doesn't play nice with the html5 client. 
Copy and paste keyboard shortcuts from notepad to this input field don't work but copy and paste via the context menu (right click) do work fine.
It seems this is a problem with the html5 client provided (version number 1.0.21.0)
Any suggestions are welcome.

**Comment by dknappettmsft** [comment]
Hi, GitHub issues in this repo are to raise issues with a specific article where there is something that needs correcting, clarifying, etc. If you need support, please visit https://support.microsoft.com/contactus. Thank you

#please-close
