### ISSUE TITLE
key based auth

### ISSUE THREAD

**Issue by ackvf** [MicrosoftDocs/windowsserverdocs#3731]
links for key based authentication instead of password would be handy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07417484-bd6d-e6f4-110e-e42c2428a369
* Version Independent ID: 844743a6-f67b-421f-9591-13da36b23b14
* Content: [Installation of OpenSSH For Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse#feedback)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* GitHub Login: @maertendMSFT

**Comment by ackvf** [comment]
this guide is great https://code.visualstudio.com/docs/remote/troubleshooting

**Comment by robinharwood** [comment]
Hi @ackvf 

Thanks for your dedication to our documentation. We've submitted a documentation change to add next steps and updated the code examples based on your suggestion, the updated article should be live by tomorrow.

#please-close
