### ISSUE TITLE
Failed to fetch debian/9/prod/dists/stretch/main/binary-amd64/Packages.bz2

### ISSUE THREAD

**Issue by briglx** [MicrosoftDocs/windowsserverdocs#3735]
Getting the following error:

Failed to fetch https://packages.microsoft.com/debian/9/prod/dists/stretch/main/binary-amd64/Packages.bz2  Writing more data than expected (72399 > 68862)
   Hashes of expected file:
    - Filesize:68862 [weak]
    - SHA512:c45a7156e5d4796ec88721f1385bdff78e7f0396031c008a31b75cf5faecdb726a52a428256d55c9424af16d23c939f24fbf2a0d467c7082c7cdcbfad4b323c2
    - SHA256:5bccd1a4be6d9e2b60465cad6bcc793d0bd1f60a29de8fe2239453b528f8cf20
    - SHA1:600a5c433ae084819b5efa743ec9ec0ea38dc130 [weak]
    - MD5Sum:964348da7a5707ac25aaca7577e46728 [weak]

**Comment by dknappettmsft** [comment]
Hi, GitHub issues in this repo is to raise issues with a specific article where there is something that needs correcting, clarifying, etc. If you need support, please visit https://support.microsoft.com/contactus. Thank you.

#please-close
