### ISSUE TITLE
debian/9/prod/dists/stretch/ not properly updated

### ISSUE THREAD

**Issue by Jeremytew** [MicrosoftDocs/windowsserverdocs#3736]
Please update the "inrelease" and the "release.gpg" file - "https://packages.microsoft.com/debian/9/prod/dists/stretch/" 
They were not updated with the patch today. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e7ed059-d77f-6ce0-8501-fc3afd1c8048
* Version Independent ID: f2d249ee-50e4-52b4-4187-954a84a48ec1
* Content: [Linux Software Repository for Microsoft Products](https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software#feedback)
* Content Source: [WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md)
* Service: **na**
* Product: **windows-server**
* Technology: **compute**
* GitHub Login: @szarkos
* Microsoft Alias: **szark**

**Comment by dknappettmsft** [comment]
Hi, GitHub issues in this repo is to raise issues with a specific article where there is something that needs correcting, clarifying, etc. If you need support, please visit https://support.microsoft.com/contactus. Thank you.

#please-close
