### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by estoces** [MicrosoftDocs/windowsserverdocs#3740]
The link to "Using DSC on Nano Server" is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95948764-6ad3-3f0a-0505-70e3bdef5c40
* Version Independent ID: 966dbded-9b19-54b2-d233-d1ffb4b3d03d
* Content: [PowerShell on Nano Server](https://docs.microsoft.com/en-us/windows-server/get-started/powershell-on-nano-server#feedback)
* Content Source: [WindowsServerDocs/get-started/PowerShell-on-Nano-Server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/PowerShell-on-Nano-Server.md)
* Service: **na**
* Product: **windows-server**
* Technology: **server-nano**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
Looks like the docs.microsoft.com pages will be the new home of that information:
- https://docs.microsoft.com/powershell/scripting/dsc/getting-started/nanodsc

**Comment by jaimeo** [comment]
Sorry I can't help--this topic lists me as the author in error.

**Comment by illfated** [comment]
Very well, fair enough. Would you like me to correct the metadata information to show the correct author in this case?

**Comment by jaimeo** [comment]
Yes please--if you know who that should be? I myself don't know for sure. I've been out of that area for quite a long time.

**Comment by illfated** [comment]
Oh. I see. Fair enough. I guess I can ask @daveba or maybe @e0i if someone can make that information available to be corrected in the same PR.

**Comment by jaimeo** [comment]
I'll ask around as well.

**Comment by e0i** [comment]
> Oh. I see. Fair enough. I guess I can ask @daveba or maybe @e0i if someone can make that information available to be corrected in the same PR.

Sadly the repository is outside the scope of our team.

**Comment by illfated** [comment]
Fair enough, thank you for confirming that. Maybe @lizap knows who could provide that information instead.

**Comment by jaimeo** [comment]
@eross-msft or @JasonGerend are better bets, as they are Server writers.

**Comment by illfated** [comment]
Thanks a lot for confirming that. I will wait for feedback from one or both of them and see if they can help out here.

**Comment by eross-msft** [comment]
@illfated  Due to a very small team of writers, we're unable to support this documentations set at this time. If you use the **Edit** button on the article itself and then make the change there, you can create a public PR for this issue. My team can then validate and accept your change, merging it into the content.

**Comment by illfated** [comment]
@eross-msft : Thank you for the feedback. Please see my PR #3742 **PowerShell/Nano Server: 404 MSDN Link replacement**
