### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by Morc001** [MicrosoftDocs/windowsserverdocs#3755]
The example with the "goto answer%errorlevel%" first line is wrong. The "goto end" line should be moved up 2 lines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e13348f3-3c91-ca88-b1bf-bf275243294e
* Version Independent ID: 7ba9aafa-ec9e-dd97-1445-091866053d97
* Content: [if](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/if)
* Content Source: [WindowsServerDocs/administration/windows-commands/if.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/if.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
I concur. The current order makes the `goto end` line pretty redundant, less useful than if it had not been there at all.

**Comment by illfated** [comment]
The PR and its commit above is only visible in the GitHub page at the moment, but it should migrate to the docs.microsoft.com pages within a week or so.

**Comment by illfated** [comment]
Resolved in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/37819a361c7de233ba130a0e24c066a679219b07 .

#please-close
