### ISSUE TITLE
ADFS 2016 

### ISSUE THREAD

**Issue by ZaherButt** [MicrosoftDocs/windowsserverdocs#3757]
Would you be able to please confirm if Scenario 1 is possible/supported on ADFS 2016? The exact requirement to be specific Prompting for Azure MFA as primary authentication and Username and password as additional authentication.

"Scenario 1
This scenario consists of two components:
* Prompting for Azure MFA or an external authentication factor as primary authentication
* Username and password as additional authentication in AD FS"

This doc suggests this capability is only possible with ADFS 2019. 

ADFS 2016 does support part of requirement by allowing primary auth with Azure MFA as documented here:
https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 404ed1e0-3d50-5f22-4721-ba79ce56589f
* Version Independent ID: 7cb551c4-cdb2-d96d-4167-1bb074064453
* Content: [Additional authentication methods in AD FS 2019](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/additional-authentication-methods-ad-fs#scenario-1-protect-the-password)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Additional-Authentication-Methods-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Additional-Authentication-Methods-AD-FS.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
@ZaherButt The document state: Starting with Windows Server 2016, you can now configure Azure MFA for primary authentication or use it as an additional authentication provider.  So yes, you can use AD FS 2016 as primary auth.  Thanks!

#please-close

**Comment by illfated** [comment]
#please-close
