### ISSUE TITLE
404 link

### ISSUE THREAD

**Issue by GrantHarrington** [MicrosoftDocs/windowsserverdocs#3760]
https://go.microsoft.com/fwlink/?LinkID=102558 results in 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 859bc683-ef8f-932f-653c-33da15147014
* Version Independent ID: 6394504f-2f04-28dc-2664-0a9d7775bb5f
* Content: [Finding Additional Resources for Logical Structure Design](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/finding-additional-resources-for-logical-structure-design#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/Finding-Additional-Resources-for-Logical-Structure-Design.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/Finding-Additional-Resources-for-Logical-Structure-Design.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by illfated** [comment]
This is the section referencing **Job Aids for Windows Server 2003 Deployment Kit**

https://go.microsoft.com/fwlink/?LinkID=102558 resolves to
https://www.microsoft.com/downloads/details.aspx?FamilyID=edabb894-4290-406c-87d1-607a58fc81f0&DisplayLang=en

which in turn shows the following page content:

![image](https://user-images.githubusercontent.com/38162891/72668500-d9c62b00-3a27-11ea-91f3-3bca688e44d0.png)

Given that this is about Windows Server 2003 material, it does not surprise me that it has been removed.

**Comment by GrantHarrington** [comment]
Understood.  Just pointing it out.  Perhaps remove that Resource from this page, or if there is a newer/modern document, post that one.

**Comment by illfated** [comment]
Fair point. Maybe the solution is to remove that section for now.

**Comment by illfated** [comment]
Someone else found the correct document in issue ticket #4147. I will start working on a PR to fix the link here too.
New and working link: https://www.microsoft.com/download/details.aspx?id=9608

**Comment by illfated** [comment]
The pull request is now merged, so the improved content should go live some time between 1-2 days and during the next week.

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
