### ISSUE TITLE
Android RDP - mouse pointer bug with rounded screens?

### ISSUE THREAD

**Issue by JesterOC3** [MicrosoftDocs/windowsserverdocs#3762]
![Screenshot_RDP android bug](https://user-images.githubusercontent.com/19354775/72690862-44847d00-3b74-11ea-813c-98c2a66c85e4.png)

On RDP Android Client, on my OPTUS X SLEEK (Android 9) 
The mouse actual press position and where the displayed mouse is don't match up...
My phone has rounded edges, I'm assuming that's the issue as my old phone was plain rectangle screen  and it worked fine.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5581a04a-e204-4a19-3eba-0852d2eb5d8e
* Version Independent ID: 820c77b6-2182-7e92-bbe6-0819f727d207
* Content: [Remote Desktop clients FAQ](https://docs.microsoft.com/en-au/windows-server/remote/remote-desktop-services/clients/remote-desktop-client-faq#specific-errors)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
Hello @JesterOC3. GitHub issues for this repo are for reporting problems with our documentation.  Please open a support ticket or post your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html).
