### ISSUE TITLE
Add Authlogics to the list

### ISSUE THREAD

**Issue by stevenh-authlogics** [MicrosoftDocs/windowsserverdocs#3764]
Authlogics has an MFA AD FS plugin for ADFS which supports also supports passwordless and deviceless logons.
http://authlogics.com/adfs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8348816f-fc89-4d25-d077-24cd86cdd38c
* Version Independent ID: 5f49fb4b-72da-f818-e87d-8fe002fc8ddc
* Content: [Configure Additional Authentication Methods for AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-additional-authentication-methods-for-ad-fs#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-Additional-Authentication-Methods-for-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-Additional-Authentication-Methods-for-AD-FS.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
#please-close

**Comment by stevenh-authlogics** [comment]
Does this mean the list of vendor solutions will be updated? At the moment Authlogics still isn't listed as a supported ADFS vendor. Thx.
