### ISSUE TITLE
Physical hardware requirements?

### ISSUE THREAD

**Issue by icelava** [MicrosoftDocs/windowsserverdocs#3767]
Does virtual TPM rely on the actual TPM of the host? I'm mostly operating Hyper-V on my Windows 10 PC and the (fairly old) motherboard does not have a TPM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2854f1b3-5af8-fea5-c0be-ea95033065ed
* Version Independent ID: 68acd194-7f2b-ec0b-b862-6a33b356c9bc
* Content: [Generation 2 virtual machine security settings for Hyper-V](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/learn-more/Generation-2-virtual-machine-security-settings-for-Hyper-V?redirectedfrom=MSDN)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/learn-more/Generation-2-virtual-machine-security-settings-for-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/learn-more/Generation-2-virtual-machine-security-settings-for-Hyper-V.md)
* Service: **na**
* Product: **windows-server**
* Technology: **compute-hyper-v**
* GitHub Login: @larsiwer
* Microsoft Alias: **kathydav**

**Comment by dknappettmsft** [comment]
Hi, thanks for the question. No it does not, it's all done in software.

#please-close
