### ISSUE TITLE
AD Management Gateway needed?

### ISSUE THREAD

**Issue by StChrist-MSFT** [MicrosoftDocs/windowsserverdocs#3768]
Hi There,

it is written:
"Like all Active Directory Windows PowerShell cmdlets, this new functionality requires installing the Active Directory Management Gateway Service on at least one domain controller (and preferably, all domain controllers)."

but the Active Directory Web Services only support up to 2008 R2, which isn't supported any more, so shouldn't this be clarified on the top of the page or did I miss something?

/Stefan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b549e9f-e280-5732-55e9-1daca539ad0d
* Version Independent ID: b5c3dfbe-0921-43c9-076f-c9a1610ba113
* Content: [Advanced Active Directory Replication and Topology Management Using Windows PowerShell (Level 200)](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/powershell/advanced-active-directory-replication-and-topology-management-using-windows-powershell--level-200-#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/powershell/Advanced-Active-Directory-Replication-and-Topology-Management-Using-Windows-PowerShell--Level-200-.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/manage/powershell/Advanced-Active-Directory-Replication-and-Topology-Management-Using-Windows-PowerShell--Level-200-.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by dknappettmsft** [comment]
Thanks for this feedback.  This isn't required anymore, so I've removed the paragraphs. The changes should be visible in a few hours.

#please-close
