### ISSUE TITLE
Update link for Microsoft MFA

### ISSUE THREAD

**Issue by DanielWahlgren** [MicrosoftDocs/windowsserverdocs#3772]
The link to Microsoft MFA is for Windows Server 2012r2 and the newer 2016-version is avaliable at this location:
https://docs.microsoft.com/sv-se/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa

I havn't followed it yet though, so can't give any information on how good it is yet.

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 8348816f-fc89-4d25-d077-24cd86cdd38c
* Version Independent ID: 5f49fb4b-72da-f818-e87d-8fe002fc8ddc
* Content: [Configure Additional Authentication Methods for AD FS](https://docs.microsoft.com/sv-se/windows-server/identity/ad-fs/operations/configure-additional-authentication-methods-for-ad-fs#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-Additional-Authentication-Methods-for-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-Additional-Authentication-Methods-for-AD-FS.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by dknappettmsft** [comment]
I've updated this link and a few others. The changes should be visible in a few hours.

#please-close
