### ISSUE TITLE
Default FileLogSize size

### ISSUE THREAD

**Issue by Mrkuff** [MicrosoftDocs/windowsserverdocs#3775]
Here the value is 1000000 instead of 10000000.  You miss a "0" for getting almost 10MB in bytes.
https://support.microsoft.com/en-ca/help/816043/how-to-turn-on-debug-logging-in-the-windows-time-service

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc978a2-5a8b-c6af-0c56-f762ea9edf16
* Version Independent ID: 33693e91-d1a2-10c0-0dd7-43167114868a
* Content: [Windows Time Service Tools and Settings](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings#feedback)
* Content Source: [WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by dknappettmsft** [comment]
Both these values are currently 10000000 (10,000,000), so I'll go ahead and close this.

#please-close
