### ISSUE TITLE
Bio-metrics With Tier 0 or Tier 1 Admin Accounts

### ISSUE THREAD

**Issue by toddportz** [MicrosoftDocs/windowsserverdocs#3776]
I noticed this recommends Windows Hello for Business for "admin accounts" Is it an acceptable practice to use Windows Hello for Business bio-metrics for a Tier 0 / Tier 1 admin accounts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd8b02b-0cf1-3664-d930-4f76b7f2a59d
* Version Independent ID: 8097a4ba-84b3-5bfd-6771-6cd1a4bf926a
* Content: [Securing privileged access](https://docs.microsoft.com/en-us/windows-server/identity/securing-privileged-access/securing-privileged-access#feedback)
* Content Source: [WindowsServerDocs/identity/securing-privileged-access/securing-privileged-access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/securing-privileged-access/securing-privileged-access.md)
* Product: **windows-server**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
Yes passwordless methods like Windows Hello for Business or FIDO2 security keys are ways to secure those accounts.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
