### ISSUE TITLE
I can't connect to my own host in WAC

### ISSUE THREAD

**Issue by Xporferus81** [MicrosoftDocs/windowsserverdocs#3777]
When I want to connect to my host via my Windows account, it doesn't work and tells you to enter your username and password, when I do, a message appears: Your credentials didn't work-try again.
Anybody have any idea how to solve this problem?

I use Chrome browser, PowerShell version 5.1.18362.145, WAC version 1910.

**Comment by dknappettmsft** [comment]
Hi, GitHub issues in this repo is to raise issues with a specific article where there is something that needs correcting, clarifying, etc. If you need support, please visit https://support.microsoft.com/contactus. Thank you.

#please-close
