### ISSUE TITLE
No shared connections in WAC

### ISSUE THREAD

**Issue by Xporferus81** [MicrosoftDocs/windowsserverdocs#3778]
In WAC settings, there is no Shared Connections option in the Gateway section.
There are several servers in the list, but this option no appears. What to do to make it appear?
![image](https://user-images.githubusercontent.com/54973987/72983090-d55f9080-3de0-11ea-93a0-02039571d489.png)

**Comment by dknappettmsft** [comment]
Hi, GitHub issues in this repo is to raise issues with a specific article where there is something that needs correcting, clarifying, etc. If you need support, please visit https://support.microsoft.com/contactus. Thank you

#please-close
