### ISSUE TITLE
Cannot sync repository https://packages.microsoft.com/rhel/7/prod/ #12

### ISSUE THREAD

**Issue by ticianaciminari** [MicrosoftDocs/windowsserverdocs#3780]
@mdig commented yesterday

Please fix metadata/faulty checksums for rpms in https://packages.microsoft.com/rhel/7/prod/

Syncing this repo localy hangs in state "processing metadata" (Red Hat Satellite)

https://github.com/MicrosoftDocs/windowsserverdocs.de-de/issues/12

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e7ed059-d77f-6ce0-8501-fc3afd1c8048
* Version Independent ID: f2d249ee-50e4-52b4-4187-954a84a48ec1
* Content: [Linux Software Repository for Microsoft Products](https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software#feedback)
* Content Source: [WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md)
* Service: **na**
* Product: **windows-server**
* Technology: **compute**
* GitHub Login: @szarkos
* Microsoft Alias: **szark**

**Comment by ticianaciminari** [comment]
Hi Team, user has reported that link to Microsoft's GPG public key is not working in target pages, please kindly let us know if this is something that could be fixed on your side or if I have to request the fix to other team. 

Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hi Team, can you please check issue reported by user? 

Kind regards,

Microsoft DOCS Global Experience Team

**Comment by Moumoutaru** [comment]
Is there any update on this?

**Comment by mdig** [comment]
It seem`s to work now, no more warnings about a missmatch in checksums in the last 2 sync attemps

**Comment by dknappettmsft** [comment]
Noted above that this is working now.

#please-close

**Comment by mdig** [comment]
Error reappears ...

Errors:

An error occurred during the sync 
{"checksum_type"=>"sha256", "expected_checksum"=>"6d9d4e5f2d50367aee889237fd29af87f95c95abbda0549dd9e318daa0c89a55", "error_code"=>"checksum_mismatch", "name"=>"dotnet-sdk-5.0", "actual_checksum"=>"5094b32ea172fdb7c8d15e1558501c35659aac9e52c6c203cbcfa52bb325574f"}
