### ISSUE TITLE
This document will not work read why.

### ISSUE THREAD

**Issue by where-is-the-remote** [MicrosoftDocs/windowsserverdocs#3786]
Our  local "domain name" is not the same as our public name ,   e.g. contoso.com and contoso.local , so I had to make these changes
Step 3  part 4- "Register and configure applications" is incorrect
Document says "Note the internal URL " . 
However This will will result in "OAuth token" error "The resource principal named http://MopriaDiscoveryService/CloudPrint was not found."

The document should say change the URI to these following settings 
Correct setting for the "discovery service" which can be set in "app reg/expose API, Application ID URI" to HTTP://MopriaDiscoveryService/CloudPrint
The same thing needs to be done for the "EnterprisePrint app", change it to http://MicrosoftEnterpriseCloudPrint/CloudPrint

When setting up the print server I added .net 3.5 with all its features

Step 4 Part 3 Install cloud print can fail to create folders in the Inetpub , if you have Windows update settings to local WSUS see. "http://memphistech.net/journey-in-hybrid-cloud-print/" 

Step 4 part 4 registry is wrong , it  should be 
EnterpriseCloudprintservice AzureAudience set to http://MicrosoftEnterpriseCloudPrint/CloudPrint
MopriaDiscoveryService AzureAudience set to  http://MopriaDiscoveryService/CloudPrint 
I did not need forward slashes the  end of the above URLs, the other URL settings they show are Ok.

4.8 failed I needed to install another package using 
"Install-Package System.Diagnostics.DiagnosticSource -RequiredVersion 4.5.1 -Provider nuget"

Step 5 (Optional) Don't wast time on this option.  I would say if you can't get pass through to work this Option won't help. No one seems to have this function working. It will also send you down changes to IIS which can break pass through. It gives false published printer statements even when IIS off, just confuses fault finding.

Step 5 (Optional)  part 3 Shows  IIS anonymous authentication enabled. Anonymous should never be enabled either for "pass through" or pre authentication. Pass through works with anonymous disabled , whcih is the default. So leave it disabled. 

Step 6 Settings 
Printer discovery URL = ( your discovery URI ending in ".msappproxy.net/mcs")
Print service resource URI =  http://MicrosoftEnterpriseCloudPrint/CloudPrint
Printer discovery service resource URI = http://MopriaDiscoveryService/CloudPrint
No forward slashes needed 

Step 7 - Publish the shared printer  
I received errors using their OrgLocation example , on the plus side at least I knew I was hitting the IIS service by this time 

for OrgLocation Just use the one parameter to test  {"attrs": [{"category":"country", "vs":"USA", "depth":0},]} and build from there.
For SDDL it will be the full outputted string with O:BA at the start

For certificates, I used the microsoft generated external URLs therefore I only needed one cert, this was for the 443 bindings on the IIS  of the print server , I used our local CA and added two subject alternate names one for the FQDN of the print server and one one for the non FQDN name of the server.

Good luck

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21d1d072-911f-92c0-248a-9e44efbff42d
* Version Independent ID: 0fdb921d-d97d-5b12-ae28-286216e130df
* Content: [Deploy Windows Server Hybrid Cloud Print](https://docs.microsoft.com/en-us/windows-server/administration/hybrid-cloud-print/hybrid-cloud-print-deploy#feedback)
* Content Source: [WindowsServerDocs/administration/hybrid-cloud-print/hybrid-cloud-print-deploy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/hybrid-cloud-print/hybrid-cloud-print-deploy.md)
* Product: **windows-server**
* Technology: **windows server 2016**
* GitHub Login: @msjimwu
* Microsoft Alias: **coreyp**

**Comment by dknappettmsft** [comment]
Thanks for your feedback. Hybrid Cloud Print is no longer supported. We recommend using [Universal Print](https://aka.ms/universalprint), which is a subscription-based cloud service offering with direct support from printer OEMs that provides a completely serverless print solution.

I have submitted a change to have these articles removed.

#please-close
