### ISSUE TITLE
ping Exit codes

### ISSUE THREAD

**Issue by ohadschn** [MicrosoftDocs/windowsserverdocs#3797]
Please document all possible exit codes for the `ping` command and the exact cases where they are returned - this is critical for scripting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60aec7a5-10e5-adfb-d841-99c6d7b9da8b
* Version Independent ID: 053bb578-44f6-ce79-70db-6033f9065fc3
* Content: [ping](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/ping#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/ping.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/ping.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by dknappettmsft** [comment]
Hi, you can find the list of the exit codes for inbuilt Windows apps and tools here: https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes, with them grouped by number across multiple articles, e.g. 0-499 are here: https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-.  If you get a hexadecimal number, you can convert this to decimal first then lookup the code.  I hope that helps.

#please-close
