### ISSUE TITLE
step g incorrect

### ISSUE THREAD

**Issue by challengelogic** [MicrosoftDocs/windowsserverdocs#3798]
References to "Volume1" should be "Vdisk01" if following previous the steps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 706b2e1a-e90e-d70e-431f-5476b0ca52c1
* Version Independent ID: 70721d4c-642c-61f8-6c61-84b1dd1ae96c
* Content: [Deploy a two-node Storage Spaces Direct SOFS for UPD storage in Azure](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-storage-spaces-direct-deployment#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-storage-spaces-direct-deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-storage-spaces-direct-deployment.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by dknappettmsft** [comment]
I can see these have been corrected.

#please-close
