### ISSUE TITLE
Step 2 Section 3 Verbage

### ISSUE THREAD

**Issue by Drehmini** [MicrosoftDocs/windowsserverdocs#3799]
&gt; Using an account with backup privileges, **move** the contents of the file share to the new location

The verb **"move"** implies that the example robocopy command will move all of the contents. Robocopy will only copy and not move.

My suggestion is to change the word **move** to **copy**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb523d20-85bb-82b5-7e0a-f0455c48944c
* Version Independent ID: 7663ccd7-eb64-b461-4fbb-8bd669cda9b2
* Content: [Enable optimized moves of redirected folders](https://docs.microsoft.com/en-us/windows-server/storage/folder-redirection/enable-optimized-moving#feedback)
* Content Source: [WindowsServerDocs/storage/folder-redirection/enable-optimized-moving.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/folder-redirection/enable-optimized-moving.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by dknappettmsft** [comment]
Thanks for the feedback. This has been updated and the changes should be visible later today.

#please-close
