### ISSUE TITLE
OpenSSHUtils is deprecated

### ISSUE THREAD

**Issue by FizzBuzz791** [MicrosoftDocs/windowsserverdocs#3806]
Trying to install OpenSSHUtils as per the "Host key generation" instructions gives the following error;

`PackageManagement\Install-Package : The module 'OpenSSHUtils' cannot be installed or updated because the authenticode signature of the file 'OpenSSHUtils.psd1' is not valid.`

The first result for that points at the Win32-OpenSSH repository and indicates that OpenSSHUtils is deprecated;
https://github.com/PowerShell/Win32-OpenSSH/issues/1313

It also links to the up-to-date method of correcting file permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH Server Configuration for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement#feedback)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* GitHub Login: @maertendMSFT

**Comment by jeffwilcox** [comment]
Hi,
Is anyone helping maintain docs on these topics?

**Comment by illfated** [comment]
See Pull Request #4788 for a suggested improvement to this issue.
(The PR will close this issue ticket when it gets merged.)

**Comment by illfated** [comment]
List of related issue tickets:

- #2747 **A better explanation can be found here** (Open)
- #3400 **Can't install the "OpenSSHUtils"** (Closed)
- #3456 **Misleading title/summary causing search confusion** (Open)
- #3970 **OpenSSH installation** (Closed)
- #4345 **OpenSSHUtils Not Needed** (Open)
- #4518 **Unable to configure OpenSSH for public key auth following docs** (Open)
- #4598 **Instructions provided ends with an error** (Open)
- #4622 **Out-of-date - OpenSSHUtils no longer available.** (Open)
- #4634 **More documentation required** (Open)
- #4690 **OpenSSHUtils install reference no longer valid** (Open)
- #4702 **OpenSSHUtils got unlisted from the PowerShell gallery** (Open)
- #4743 **Nope. First example errors out.** (Open)
- #4770 **Error when following instructions to install OpenSSHUtils** (Open)
- #4787 **OpenSSHUtils module does not exist** (Open)
- #5000 **Clarification needed** (Open)
- #5138 **These instructions do not work on Windows 10 20h2** (Open)

**Comment by dknappettmsft** [comment]
Thanks for submitting this issue. I have reworked this document to remove or replace parts that are no longer relevant or correct based on this and several other issues raised for this page.

The changes should be visible in around 6-12 hours.

#please-close
