### ISSUE TITLE
Information re Data Depuplication on ReFS not completely updated?

### ISSUE THREAD

**Issue by grnathan** [MicrosoftDocs/windowsserverdocs#3809]
The article has a **Supported** section advising that Data Depuplication on ReFS is supported as of Windows Server 2019 but shortly afterwards in the section on Failover Clustering mentions dedup is supported on S2D NTFS volumes, but not volumes with multiple tiers.  There's a link * [Data Deduplication on ReFS](https://docs.microsoft.com/en-us/windows-server/storage/data-deduplication/interop#unsupported) * that points to the */#unsupported section of the article but there is no mention of anything about deduplication or ReFS in the **unsupported** portion of the document. 

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbca43fe-2459-af79-0ab0-6c598217239f
* Version Independent ID: 7e824aea-3911-d256-4002-d62711005efd
* Content: [Data Deduplication interoperability](https://docs.microsoft.com/en-us/windows-server/storage/data-deduplication/interop#feedback)
* Content Source: [WindowsServerDocs/storage/data-deduplication/interop.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/data-deduplication/interop.md)
* Product: **windows-server**
* Technology: **storage-deduplication**
* GitHub Login: @wmgries
* Microsoft Alias: **wgries**

**Comment by MarvinBjor** [comment]
I too find this part of the doc to be unclear, is there a possibility for a clarification on this?

**Comment by illfated** [comment]
(ref. #1219 #2482 #5211 #429)

**Comment by dknappettmsft** [comment]
Thanks for the feedback.  This was an entry that wasn't tidied up last time.  I've made a change that should be visible later today.

#please-close
