### ISSUE TITLE
Issue with npm install after wac create

### ISSUE THREAD

**Issue by bchipman** [MicrosoftDocs/windowsserverdocs#3812]
There seems to be an issue with running npm install after doing the wac create command.  The issue is with node-sass dependency:

&gt; node-sass@4.10.0 install C:\Brian\WAC_SLDellGR1\BrianTest\node_modules\node-sass
&gt; node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.10.0/win32-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.10.0/win32-x64-72_binding.node":

HTTP error 404 Not Found

npm then goes on to try to compile it but fails.  I'm not very familiar with npm yet, can someone tell me how to resolve this?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d5eb994-82f2-a292-02fd-e21cf2d8f97f
* Version Independent ID: 80fcfe9d-4f12-287e-09ef-52d46a34b05a
* Content: [Develop a tool extension](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/extend/develop-tool)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/extend/develop-tool.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/extend/develop-tool.md)
* Product: **windows-server**
* Technology: **manage**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by dknappettmsft** [comment]
Thanks for the feedback. GitHub issues in this repo is to report issues with the article itself, e.g. for clarity, spelling and grammatical errors, etc., rather than product support. You can report bugs for WAC through that repo at [https://aka.ms/wacfeedback](https://aka.ms/wacfeedback) or contact Microsoft Support.

#please-close
