### ISSUE TITLE
Need help regarding Hyper-V VMs migration.

### ISSUE THREAD

**Issue by KrupalJoshi** [MicrosoftDocs/windowsserverdocs#3814]
[Enter feedback here]

I didn't found feedback/query page for "Msvm_VirtualSystemMigrationService" class. So, i am asking in this forum. If this is not right place for this, can you please point me to the correct one?

I am trying to migrate VMs using WMI classes in C++. I have some queries, given below.

1. Is this migration similar as migration done by "Msvm_VirtualSystemMigrationService" class and its sub classes?
2. Migration performed by "Msvm_VirtualSystemMigrationService" is VMs (disk files / VHDs, config riles) move or copy-paste operation (from source to destination)?
3. If migration fails in between, does source VMs (disk files and config files) remain as in the same state it was before starting migration at source side?
4. Can user operate VM at destination host while data (disk files) migration is going on? If yes, when user can be able to switch on the VM and start operation with VM?
5. Can we use "Msvm_VirtualSystemMigrationService" class for migration of VMs snapshot, taken by custom VSS provider?

Thanks,
Krupal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ca8148b-52ed-2aae-3458-7661a6575bd3
* Version Independent ID: 8a7b57da-bcde-fa61-cf0c-157e032f1501
* Content: [Live Migration Overview](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/live-migration-overview)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/live-migration-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/live-migration-overview.md)
* Service: **na**
* Product: **windows-server**
* Technology: **compute-hyper-v**
* GitHub Login: @johncslack
* Microsoft Alias: **joslack**

**Comment by dknappettmsft** [comment]
Hi, unfortunately this isn't the correct place.  The best place would be the Windows Server Community, which can be found here: https://techcommunity.microsoft.com/t5/windows-server/ct-p/Windows-Server.  Thank you.

#please-close
