### ISSUE TITLE
Add user agent string for new Edge Chromium 

### ISSUE THREAD

**Issue by cumbrianblues** [MicrosoftDocs/windowsserverdocs#3816]
this page doesn't show the new user agent string for Edge (Chromium) Edg/79.0.309.43 as described in this document
https://docs.microsoft.com/en-us/microsoft-edge/web-platform/user-agent-string 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd7eb3f6-c00a-453f-a596-6f8bde452cb7
* Version Independent ID: 3250a24b-8e71-a36c-a9a0-7c46bc36acd4
* Content: [Configure browsers to use Windows Integrated Authentication (WIA) with AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-browser-wia#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Browser-WIA.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Browser-WIA.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by ImNotSerious** [comment]
at this point, probably need to just put the more generic Edg/* as its already at 80.

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36 Edg/80.0.361.48

**Comment by illfated** [comment]
(Ref. #4342)

**Comment by illfated** [comment]
(ref. #3875)

**Comment by illfated** [comment]
#please-close (see commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/7b5ee81198368494ce1df12c021cb5d89a5fbbf8)

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
Possibly related: #5098
