### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by nOrphf** [MicrosoftDocs/windowsserverdocs#3817]
Hi

Is this app, or it's beta ever gonne get a new update?
For instance, the backup/restore beeing put into the GA version?

Regards Lars

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 67b7b5a4-647e-fee3-6533-6ed88ae45bfa
* Version Independent ID: d9102859-0147-346f-8268-6e2a75c8b0b7
* Content: [What's new in the Windows Store client](https://docs.microsoft.com/da-dk/windows-server/remote/remote-desktop-services/clients/windows-whatsnew#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windows-whatsnew.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windows-whatsnew.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by dknappettmsft** [comment]
Hi, GitHub issues in this repo is to raise issues with a specific article where there is something that needs correcting, clarifying, etc. It isn't for providing future roadmap information on products.  New versions have been released and added to this article when available.

#please-close
