### ISSUE TITLE
Invalid switch - "/elevate".

### ISSUE THREAD

**Issue by jetblackrlsh** [MicrosoftDocs/windowsserverdocs#3818]
Whenever I try to use the /elevate parameter for the start command I get the following error: Invalid switch - "/elevate".

Could examples of how to properly use the /elevate parameter be added to this doc?

When I run start /?, it gives me no information on the /elevate parameter or how to use it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a52b78b6-e846-0b32-25c0-f9aab145b112
* Version Independent ID: 0c56bb98-4f1f-dd55-63ae-8bb18535cee1
* Content: [start](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/start.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/start.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by dknappettmsft** [comment]
Thanks for the feedback. This parameter is no longer available, so I've updated the article and added another parameter that was missing.  The changes should be visible in the next few hours.

#please-close
