### ISSUE TITLE
"See Also" contains a broken link

### ISSUE THREAD

**Issue by charltonstanley** [MicrosoftDocs/windowsserverdocs#3819]
The link for "Managed Service Accounts: Understanding, Implementing, Best Practices, and Troubleshooting" no longer works. I believe the correct link is: &lt;https://docs.microsoft.com/en-us/archive/blogs/askds/managed-service-accounts-understanding-implementing-best-practices-and-troubleshooting&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 344b210a-650f-4f12-dd1c-4a20f6cf46eb
* Version Independent ID: 176eade9-04bd-a656-fc2c-ba04c1c0aab2
* Content: [What's New for Managed Service Accounts](https://docs.microsoft.com/en-us/windows-server/security/group-managed-service-accounts/what-s-new-for-managed-service-accounts#feedback)
* Content Source: [WindowsServerDocs/security/group-managed-service-accounts/what-s-new-for-managed-service-accounts.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/group-managed-service-accounts/what-s-new-for-managed-service-accounts.md)
* Product: **windows-server**
* Technology: **security-gmsa**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by dknappettmsft** [comment]
Thanks for the feedback. This link was corrected.

#please-close
