### ISSUE TITLE
START uses PATHEXT even if the token contains an extension

### ISSUE THREAD

**Issue by mpilgrem** [MicrosoftDocs/windowsserverdocs#3824]
The current documentation for cmd.exe's START command states: 'When you run a command _that uses a first token that does not contain an extension_, Cmd.exe uses the value of the PATHEXT environment variable to determine which extensions to look for and in what order.'

That is true, but it implies that 'that uses a first token that does not contain an extension' is a necessary pre-condition. It is not. For example:

```
>echo echo Run by: %0 > test.bat.bat

>test.bat

>echo Run by: test.bat
Run by: test.bat

>start test.bat
```
will run/start the simple `test.bat.bat` created by the first command.

I suggest that it would be more accurate to state: 'When you run a command _that uses a first token that is not a command or the file path to an existing file with an extension_, the Command Prompt (cmd.exe) uses the value of the PATHEXT environment variable to determine which extensions to add, to look for files, and in what order.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a52b78b6-e846-0b32-25c0-f9aab145b112
* Version Independent ID: 0c56bb98-4f1f-dd55-63ae-8bb18535cee1
* Content: [start](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start)
* Content Source: [WindowsServerDocs/administration/windows-commands/start.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/start.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by dknappettmsft** [comment]
Thanks for the feedback. I agree, so I've pushed a change to incorporate the wording you suggested, which should be visible in a few hours.

#please-close
