### ISSUE TITLE
Reference to "Understanding Cluster and Pool Quorum"

### ISSUE THREAD

**Issue by rammalkani** [MicrosoftDocs/windowsserverdocs#3826]
While I agree that the explanation on this page about Quorum is detailed. I believe the referencing should be in the reverse order.
The information about Cluster Quorum should be on this page and reference to this page should be provided on "Understanding Cluster and Pool Quorum" page. There is no need for someone who is deploying regular clusters to visit the S2D page to understand quorum and possibly get confused.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de0ec0e0-b3ad-c222-4a3d-940a7c6d8cc3
* Version Independent ID: 11bf5350-4a4f-8468-51c8-c8075e627164
* Content: [Configure and manage the quorum in a failover cluster](https://docs.microsoft.com/en-us/windows-server/failover-clustering/manage-cluster-quorum#feedback)
* Content Source: [WindowsServerDocs/failover-clustering/manage-cluster-quorum.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/manage-cluster-quorum.md)
* Product: **windows-server**
* Technology: **storage-failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by ManikaDhiman** [comment]
Hi @rammalkani, Thanks for your feedback. I included Storage Spaces Direct in the reference sentence to provide clarification. Here's the PR with the updates: https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/2733

Updates will be live shortly after the next publishing pass. Thanks!

**Comment by ManikaDhiman** [comment]
#please-close
