### ISSUE TITLE
Confusing Recommendations

### ISSUE THREAD

**Issue by christiandekker** [MicrosoftDocs/windowsserverdocs#3827]
The recommendations for the ExtranetLockoutThreshold state:
ExtranetLockoutThreshold: – 2x AD Threshold Value

But the example value is this, which is the exact opposite
AD value: 20, ExtranetLockoutThreshold: 10

I'm assuming the ExtranetLockoutThreshold value should be lower than the AD value, so I'm guessing the example values are correct. Can this be verified?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0238d6f-4073-172e-de62-e2d973d993b7
* Version Independent ID: 3789bcce-bebd-8a9d-c814-45ce6c1bfe47
* Content: [Configure AD FS Extranet Lockout Protection](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-extranet-smart-lockout-protection#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by dknappettmsft** [comment]
This was corrected to 'Half of AD Threshold Value' in February 2020.

#please-close
