### ISSUE TITLE
PubKey Auth not working [solution]

### ISSUE THREAD

**Issue by ackvf** [MicrosoftDocs/windowsserverdocs#3828]
https://github.com/PowerShell/Win32-OpenSSH/issues/1306#issuecomment-451280834 or few comments later
https://github.com/PowerShell/Win32-OpenSSH/issues/1306#issuecomment-484475323

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH Server Configuration for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* GitHub Login: @maertendMSFT

**Comment by ackvf** [comment]
t

**Comment by ackvf** [comment]
x

**Comment by dknappettmsft** [comment]
Thanks for submitting this issue. I have reworked this document to remove or replace parts that are no longer relevant or correct based on this and several other issues raised for this page.

The changes should be visible in around 6-12 hours.

#please-close
