### ISSUE TITLE
Community resources link

### ISSUE THREAD

**Issue by stacylaray** [MicrosoftDocs/windowsserverdocs#3830]
Community resources contains a link to "Managed Service Accounts: Understanding, Implementing, Best Practices, and Troubleshooting" but the link doesn't go to that document.  It goes to "Archived MSDN and TechNet Blogs" and when I search for "gMSA" or "Managed Service Accounts" it finds nothing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31492eef-b917-e663-8648-e08ab1410b24
* Version Independent ID: a20b80c8-995a-4963-91e3-643daf6ffff4
* Content: [Group Managed Service Accounts Overview](https://docs.microsoft.com/en-us/windows-server/security/group-managed-service-accounts/group-managed-service-accounts-overview#feedback)
* Content Source: [WindowsServerDocs/security/group-managed-service-accounts/group-managed-service-accounts-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/group-managed-service-accounts/group-managed-service-accounts-overview.md)
* Product: **windows-server**
* Technology: **security-gmsa**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by SqlBenjamin** [comment]
Looks like you can find that link here now: https://docs.microsoft.com/en-us/archive/blogs/askds/managed-service-accounts-understanding-implementing-best-practices-and-troubleshooting

**Comment by dknappettmsft** [comment]
Thanks for the feedback. This link appears to go to the correct place now.

#please-close
