### ISSUE TITLE
Typo in command

### ISSUE THREAD

**Issue by dawnthefawn** [MicrosoftDocs/windowsserverdocs#3831]
"Failover Cluster Manager (CluAdmin.msc)

Requires addition of the Failover Clustering Windows Server feature first.

From an elevated PowerShell session:

PowerShell

Copy
Install-WindowsFeature -NameFailover-Clustering -IncludeManagementTools"

This should be:

 Install-WindowsFeature -Name Failover-Clustering -IncludeManagementTools

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0017894c-49f1-6114-28cf-9e27411ee9d8
* Version Independent ID: d871e63a-6ad0-fbda-757f-95baef0301a8
* Content: [Server Core App Compatibility Feature on Demand (FOD)](https://docs.microsoft.com/en-us/windows-server/get-started-19/install-fod-19#feedback)
* Content Source: [WindowsServerDocs/get-started-19/install-fod-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/install-fod-19.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Thank you for pointing out the missing space. I will make a PR to suggest adding it to the command.

**Comment by illfated** [comment]
Looks like this has been resolved already. See the merged PR #3832 (**Fix typo in get-started-19/install-fod-19.md**).

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
