### ISSUE TITLE
Question?  Why not simply use one of the NTP implementations?

### ISSUE THREAD

**Issue by poundjd** [MicrosoftDocs/windowsserverdocs#3835]
NTP is open source software with implementations for windows computers.

Why not simply use one of the NTP implementations? 

This would greatly reduce the resources that you have to devote to Time Services.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7262e58-e138-fdeb-f961-76e9ef93f5a7
* Version Independent ID: 3c02281e-490b-9535-878f-3ccdd8c7c128
* Content: [Support boundary for high-accuracy time](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/support-boundary)
* Content Source: [WindowsServerDocs/networking/windows-time-service/support-boundary.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/windows-time-service/support-boundary.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @shortpatti
* Microsoft Alias: **dacuo**

**Comment by dknappettmsft** [comment]
Thanks for the feedback. GitHub issues in this repo is to raise issues with a specific article where there is something that needs correcting, clarifying, etc. A better place for this question would be the Windows Server Community: https://techcommunity.microsoft.com/t5/windows-server/ct-p/Windows-Server.

#please-close
