### ISSUE TITLE
Please provide an example that has '/k' option used in it 

### ISSUE THREAD

**Issue by ortymd** [MicrosoftDocs/windowsserverdocs#3836]
I get 'Invalid syntax error' for any combination that has /k used in it. It would be great if you elaborated how to work with this key. thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b712cc31-d8c9-7694-01b8-a85cda240f7f
* Version Independent ID: 9c95c177-9bef-03ec-5774-f92b7ea42c9e
* Content: [reg query](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/reg-query)
* Content Source: [WindowsServerDocs/administration/windows-commands/reg-query.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/reg-query.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by arjunpaudyal** [comment]
Recently I needed to find certain things in key only. Struggled hard, failed.

**reg query HKLM /f "Convert with Doxillion" /s /k**

using **/f** runs the query, but fails to find result(s) though exist(s) on **_regedit_** search.

**Comment by dknappettmsft** [comment]
Hi @ortymd, thank for the feedback.  `/k` has to be used in conjunction with `/f`. If you only use `/f`, it will find all keys, values and data that match the search term, but if you add `/k`, it will only find keys (not values and data too).

For example (`/s` in this example searches subkeys recursively):

`reg query HKLM\SOFTWARE\Microsoft /s /f asp.net` finds 10 matches.

> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET
> 
> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MMC\NodeTypes\{a841b6c2-7577-11d0-bb1f-00a0c922e79c}\Extensions\PropertySheet
>     {fedb2179-2335-48f1-aa28-5cda35a2b36d}    REG_SZ    ASP.NET MMC Extension IIS Snap in
> 
> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MMC\NodeTypes\{a841b6c3-7577-11d0-bb1f-00a0c922e79c}\Extensions\PropertySheet
>     {fedb2179-2335-48f1-aa28-5cda35a2b36d}    REG_SZ    ASP.NET MMC Extension Static Node
> 
> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MMC\NodeTypes\{a841b6c4-7577-11d0-bb1f-00a0c922e79c}\Extensions\PropertySheet
>     {fedb2179-2335-48f1-aa28-5cda35a2b36d}    REG_SZ    ASP.NET MMC Extension Machine Node
> 
> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MMC\NodeTypes\{a841b6c5-7577-11d0-bb1f-00a0c922e79c}\Extensions\PropertySheet
>     {fedb2179-2335-48f1-aa28-5cda35a2b36d}    REG_SZ    ASP.NET MMC Extension
> 
> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MMC\NodeTypes\{a841b6c6-7577-11d0-bb1f-00a0c922e79c}\Extensions\PropertySheet
>     {fedb2179-2335-48f1-aa28-5cda35a2b36d}    REG_SZ    ASP.NET MMC Extension
> 
> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MMC\NodeTypes\{a841b6c7-7577-11d0-bb1f-00a0c922e79c}\Extensions\PropertySheet
>     {fedb2179-2335-48f1-aa28-5cda35a2b36d}    REG_SZ    ASP.NET MMC Extension Instance Node
> 
> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MMC\NodeTypes\{a841b6c8-7577-11d0-bb1f-00a0c922e79c}\Extensions\PropertySheet
>     {fedb2179-2335-48f1-aa28-5cda35a2b36d}    REG_SZ    ASP.NET MMC Extension VDir Node
> 
> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MMC\NodeTypes\{a841b6c9-7577-11d0-bb1f-00a0c922e79c}\Extensions\PropertySheet
>     {fedb2179-2335-48f1-aa28-5cda35a2b36d}    REG_SZ    ASP.NET MMC Extension File Node
> 
> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MMC\SnapIns\{fedb2179-2335-48f1-aa28-5cda35a2b36d}
>     NameString    REG_SZ    ASP.NET Management Extension
> 
> End of search: 10 match(es) found.

...whereas `reg query HKLM\SOFTWARE\Microsoft /s /f asp.net /k` finds 1 match:

> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET
> End of search: 1 match(es) found.

I hope that helps.  I have added this example to the article and also stated that /k must be used with /f, which should be visible later today.

#please-close
