### ISSUE TITLE
The link for the diskpart import command actually points to the diskshadow import command

### ISSUE THREAD

**Issue by darwin-msft** [MicrosoftDocs/windowsserverdocs#3844]
The link for the diskpart IMPORT command actually points to the diskshadow IMPORT command.

Can someone fix this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bca0f8f7-da0d-6340-bf63-f269be5f64d1
* Version Independent ID: 39758423-e92d-d2db-88f3-260dc5a1a26a
* Content: [DiskPart commands](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/diskpart#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/diskpart.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/diskpart.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Wow. That should be easy to fix, now that there are 2 separate pages named "import":
- import (shadowdisk) (https://docs.microsoft.com/windows-server/administration/windows-commands/import)
- import (diskpart) (https://docs.microsoft.com/windows-server/administration/windows-commands/import_1)

Going to check the changelog (History) for the TOC file and the 2 pages, just to see how long these 2 alternatives have been there.

**Comment by illfated** [comment]
There you go. Sorry it took me so long to find this ticket. PR #5104 is ready for perusal.
