### ISSUE TITLE
Alignment with our latest baselines

### ISSUE THREAD

**Issue by bekirdur** [MicrosoftDocs/windowsserverdocs#3845]
These recommendations are not aligned with our latest baselines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ba42209-cc0a-d257-5566-a101d91b89ea
* Version Independent ID: 7973c0ca-3afd-619f-a08e-43873f2e8dbf
* Content: [Audit Policy Recommendations](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/audit-policy-recommendations#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Audit-Policy-Recommendations.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Audit-Policy-Recommendations.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by Borkason** [comment]
Any update on this?

**Comment by MicrosoftGuyJFlo** [comment]
@bekirdur What baselines? Just saying its not aligned to something doesn't help.

**Comment by bekirdur** [comment]
Alright.
