### ISSUE TITLE
/j

### ISSUE THREAD

**Issue by cbailiss** [MicrosoftDocs/windowsserverdocs#3847]
I understand /j enables unbuffered IO, but this doesn't seem to be documented on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Conan1989** [comment]
Hi MS, should really fix this one

**Comment by Conan1989** [comment]
https://ss64.com/nt/robocopy.html

**Comment by illfated** [comment]
Thanks for the motivational comments and the useful reference. I may just make a PR to update that page, but I have to postpone it for just a few days, until this main section has finished receiving a makeover or overhaul for other types of changes.

**Comment by dknappettmsft** [comment]
Thanks for the feedback. This article now includes the /j parameter.

#please-close
