### ISSUE TITLE
What happens when it won't find the files?

### ISSUE THREAD

**Issue by auroraeosrose** [MicrosoftDocs/windowsserverdocs#3848]
apparently incompatible versions mean hyper-v machines just don't appear
 what then?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acc00093-1f29-7e3b-ab30-9e6966598390
* Version Independent ID: bd281aaf-4e09-73a4-95a0-873ab4cc5de2
* Content: [Export and import virtual machines](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/deploy/export-and-import-virtual-machines)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/deploy/Export-and-import-virtual-machines.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/deploy/Export-and-import-virtual-machines.md)
* Product: **windows-server**
* Technology: **compute-hyper-v**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by dknappettmsft** [comment]
Thanks for the feedback. You can only import a virtual machine if the Hyper-V host supports that configuration version. Typically, this means that you can import a virtual machine to a Hyper-V host running a newer version of Hyper-V, but you cannot import a virtual machine created on a newer version of Hyper-V to an older version of Hyper-V.  You will need to find a Hyper-V host that supports that configuration version, or you can create a new VM of the same generation and attach the existing virtual hard disks.

I have added a note to this article to highlight this requirement, which should be visible later today.

#please-close
