### ISSUE TITLE
Server 2003 to a clustered file server seemingly not possible

### ISSUE THREAD

**Issue by feeked** [MicrosoftDocs/windowsserverdocs#3849]
I think this should be noted somewhere. Unless I'm wrong, you need to not have KB4512534 to migrate from Server 2003, and you need KB4512534 to migrate to a clustered file server. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f348eda3-6195-cd36-9bf9-769b6c37927b
* Version Independent ID: a2255385-394e-7ee0-a90d-dcaca017a3d4
* Content: [Storage Migration Service known issues](https://docs.microsoft.com/en-us/windows-server/storage/storage-migration-service/known-issues#feedback)
* Content Source: [WindowsServerDocs/storage/storage-migration-service/known-issues.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-migration-service/known-issues.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @nedpyle
* Microsoft Alias: **nedpyle**

**Comment by nedpyle** [comment]
@steved0x this content referenced was removed months ago. Please close this.

**Comment by illfated** [comment]
#please-close
