### ISSUE TITLE
ADFS and Passport for Work

### ISSUE THREAD

**Issue by alradmsft** [MicrosoftDocs/windowsserverdocs#3850]
There is no such thing as Passport for Work. It is called Windows Hello for Business. 

https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-requirements

**Comment by dknappettmsft** [comment]
Thanks for the feedback. I have updated the references on this article, as well as on other articles.  The changes should be visible later today.

#please-close
