### ISSUE TITLE
Typing Mistake for definition of Property- BadPwdCountFamiliar:

### ISSUE THREAD

**Issue by sayanchakraborty2k18** [MicrosoftDocs/windowsserverdocs#3851]
There is a typing mistake in the below section. Please get it corrected. 

https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-extranet-smart-lockout-protection#manage-user-account-activity

This section says the below

Properties: - BadPwdCountFamiliar: Incremented when an authentication is **_successful_** from a known location. -

The above statement is incorrect, and it should be unsuccessful instead of successful, probably a typo, but it can create confusion.

**Comment by dknappettmsft** [comment]
Hi, thanks for the feedback. This was corrected in March 2021.

#please-close
