### ISSUE TITLE
Please add screenshot for each step

### ISSUE THREAD

**Issue by kirancobe** [MicrosoftDocs/windowsserverdocs#3855]
For example. Step 1.Click the Storage Reports Management node.
[My comment]- WHere do i find this feature? it not clear. If there was screenshot, you would be usefull or atleast it might point the user in the right direction

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d72ab13-be6f-4b7b-2383-816509afd51d
* Version Independent ID: be3f4e21-bd51-e59c-0f50-fcdd59efeecb
* Content: [Generate Reports on Demand](https://docs.microsoft.com/en-us/windows-server/storage/fsrm/generate-reports-on-demand)
* Content Source: [WindowsServerDocs/storage/fsrm/generate-reports-on-demand.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/fsrm/generate-reports-on-demand.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 3827 -b #assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey kirancobe,

Thanks again for contacting Microsoft. We value your feedback. 

This documentation has been revamped to include prerequisites, separation of reporting methods, and a demonstration gif. Changes will be live next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
