### ISSUE TITLE
/unique switch

### ISSUE THREAD

**Issue by tsahi** [MicrosoftDocs/windowsserverdocs#3858]
In Windows 10, `sort` also supports a `/unique` switch, which returns only unique values from the input.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 763f3027-825b-b4fc-4731-fc98f7d94c3c
* Version Independent ID: 5ce32680-6bf9-5f3d-0eb8-30729e0d1351
* Content: [sort](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/sort)
* Content Source: [WindowsServerDocs/administration/windows-commands/sort.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/sort.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by dknappettmsft** [comment]
Thanks for the feedback.  I have added this to the table of parameters in this article.  The change should be visible later today.

#please-close
