### ISSUE TITLE
returned claim schema must be http in ADFS Additional Authentication Method walkthrough

### ISSUE THREAD

**Issue by dorsf** [MicrosoftDocs/windowsserverdocs#3859]
Hey,
In the function TryEndAuthentication the claim schema authenticationmethod must have http prefix, not https. otherwise it won't work.
The error ADFS will write on event viewer is:  The authentication provider did not return an authentication method claim.

the correct line is 
` Claim claim = new Claim("http://schemas.microsoft.com/ws/2008/06/identity/claims/authenticationmethod", "http://example.com/myauthenticationmethod1");
`

**Comment by dknappettmsft** [comment]
Thanks for the feedback. I tracked this down to https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/ad-fs-build-custom-auth-method and found that this was corrected in April 2020.

#please-close
