### ISSUE TITLE
Server 2019

### ISSUE THREAD

**Issue by mbroaders** [MicrosoftDocs/windowsserverdocs#3863]
This article applies to Server 2019 but only references Server 2016 in the detail. Is there an updated guide for Server 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 284d419d-f0b5-cfa0-8509-0dfc93fb37b6
* Version Independent ID: d3e5b827-3071-3df7-cdb4-1b3275c3fb92
* Content: [Cluster Operating System Rolling Upgrade](https://docs.microsoft.com/en-us/windows-server/failover-clustering/cluster-operating-system-rolling-upgrade#feedback)
* Content Source: [WindowsServerDocs/failover-clustering/Cluster-Operating-System-Rolling-Upgrade.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/Cluster-Operating-System-Rolling-Upgrade.md)
* Product: **windows-server**
* Technology: **storage-failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Conan1989** [comment]
Hi MS, please clarify for 2016 to 2019 upgrades

**Comment by dknappettmsft** [comment]
Thanks for the feedback. I have updated the article to cover newer versions of Windows Server, which should be visible later today.

#please-close
