### ISSUE TITLE
Blog links on page are dead, please update

### ISSUE THREAD

**Issue by bobfrankly** [MicrosoftDocs/windowsserverdocs#3869]
attempting to reference information on performance counters and what they indicate, there are blog links on the page at https://docs.microsoft.com/en-us/windows-server/administration/performance-tuning/role/file-server/smb-file-server but they are dead links.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eff7ae9-34b9-5047-b707-50bbd05dbe5a
* Version Independent ID: 8e6ae745-afb9-89d0-77ad-3a9059aac122
* Content: [Performance Tuning for SMB File Servers](https://docs.microsoft.com/en-us/windows-server/administration/performance-tuning/role/file-server/smb-file-server#feedback)
* Content Source: [WindowsServerDocs/administration/performance-tuning/role/file-server/smb-file-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/performance-tuning/role/file-server/smb-file-server.md)
* Product: **windows-server**
* Technology: **performance-tuning-guide**
* GitHub Login: @phstee
* Microsoft Alias: **NedPyle; Danlo; DKruse**

**Comment by dknappettmsft** [comment]
#assign:dknappettmsft

**Comment by dknappettmsft** [comment]
Thanks for the feedback. These are now fixed.

#please-close
