### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by Nick-C** [MicrosoftDocs/windowsserverdocs#3871]
The "Read More" links in the "Run a Failover Section" no longer seem to work since the blog posts they refer to have now been archived:

https://blogs.technet.com/b/virtualization/archive/2012/08/08/types-of-failover-operations-in-hyper-v-replica-part-iii-unplanned-failover.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6c70745-b594-09c8-5e68-b256c5716f72
* Version Independent ID: c6fa4b5a-0208-c236-720e-c106c3c9a515
* Content: [Set up Hyper-V Replica](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/set-up-hyper-v-replica#feedback)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/Set-up-Hyper-V-Replica.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/Set-up-Hyper-V-Replica.md)
* Service: **na**
* Product: **windows-server**
* Technology: **compute-hyper-v**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by illfated** [comment]
OK, I think the blogs have been exported to docs.microsoft.com - here is the first page:
- https://docs.microsoft.com/en-us/virtualization/community/team-blog/2012/20120725-types-of-failover-operations-in-hyper-v-replica-part-i-test-failover

Funnily enough, that page has an issue ticket (**#1183**) reporting that the second and third page as broken, because those link point back to the old archived technet pages.

**Comment by illfated** [comment]
Here is page 2: https://docs.microsoft.com/en-us/virtualization/community/team-blog/2012/20120731-types-of-failover-operations-in-hyper-v-replica-part-ii-planned-failover

Here is page 3: https://docs.microsoft.com/en-us/virtualization/community/team-blog/2012/20120808-types-of-failover-operations-in-hyper-v-replica-part-iii-unplanned-failover

**Comment by illfated** [comment]
Complete list from https://docs.microsoft.com/en-us/virtualization/community/team-blog/:
- part 1: [2012/20120725-types-of-failover-operations-in-hyper-v-replica-part-i-test-failover](https://docs.microsoft.com/en-us/virtualization/community/team-blog/2012/20120725-types-of-failover-operations-in-hyper-v-replica-part-i-test-failover)
- part 2: [2012/20120731-types-of-failover-operations-in-hyper-v-replica-part-ii-planned-failover](https://docs.microsoft.com/en-us/virtualization/community/team-blog/2012/20120731-types-of-failover-operations-in-hyper-v-replica-part-ii-planned-failover)
- part 3: [2012/20120808-types-of-failover-operations-in-hyper-v-replica-part-iii-unplanned-failover](https://docs.microsoft.com/en-us/virtualization/community/team-blog/2012/20120808-types-of-failover-operations-in-hyper-v-replica-part-iii-unplanned-failover)

**Comment by illfated** [comment]
These links should replace the old & archived technet links in at least 2 pages. Too late for me to start working on this right now, it is time to get some sleep (23:00). Maybe in a few days time.

**Comment by illfated** [comment]
Wow … looks like the pandemic really made me lose my overview of old and unfinished tickets. Really sorry about that.
(Good thing I am not paid to do this work. 😉 )

I will do my best to get if resolved ASAP.

**Comment by illfated** [comment]
Visible links:

- https://docs.microsoft.com/en-us/virtualization/community/team-blog/2012/20120725-types-of-failover-operations-in-hyper-v-replica-part-i-test-failover
- https://docs.microsoft.com/en-us/virtualization/community/team-blog/2012/20120731-types-of-failover-operations-in-hyper-v-replica-part-ii-planned-failover
- https://docs.microsoft.com/en-us/virtualization/community/team-blog/2012/20120808-types-of-failover-operations-in-hyper-v-replica-part-iii-unplanned-failover

**Comment by illfated** [comment]
There you go. PR #4886 is now available for review. Feel free to comment or suggest further improvements.
