### ISSUE TITLE
The specification of "manage-bde -protectors -adbackup" is incorrect

### ISSUE THREAD

**Issue by tiduseQ** [MicrosoftDocs/windowsserverdocs#3872]
No further words than below example is sufficient to prove it. It does not allow me to skip -ID

C:\Users\xxxxxx&gt;manage-bde  -protectors  -adbackup C:
BitLocker Drive Encryption: Configuration Tool version 10.0.17763
Copyright (C) 2013 Microsoft Corporation. All rights reserved.

ERROR: Specifying the parameter '-ID' is required to back up recovery
information.

C:\Users\xxxxxx&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82ef6d71-4070-a941-ccc2-868e435e7c18
* Version Independent ID: 1a9eac49-6fd4-de12-9c8a-452ee31f6bc7
* Content: [manage-bde protectors](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/manage-bde-protectors#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/manage-bde-protectors.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/manage-bde-protectors.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by dknappettmsft** [comment]
Thanks for the feedback. I have corrected the example on the page to include the -ID parameter.

#please-close
