### ISSUE TITLE
Screenshot for Configuration Options paragraph - wrong screenshot? 

### ISSUE THREAD

**Issue by ricofox959** [MicrosoftDocs/windowsserverdocs#3876]
In the sentence, it reads "For example, if we change Sample every x seconds to 5 seconds, we need to set this key to 5000 ms." But the screenshot is of the default of "Sample every 1 second(s)" Not sure if that was intentional

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9561716a-21fa-fd7c-1807-300a0bc73869
* Version Independent ID: 7aed7f1a-3924-1bd2-6cd1-02a94382a392
* Content: [Use performance counters to diagnose application responsiveness problems on Remote Desktop Session Hosts](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-rdsh-performance-counters#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-rdsh-performance-counters.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-rdsh-performance-counters.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by dknappettmsft** [comment]
Hi, if it's the screenshot above this paragraph you mean, it's referring to the paragraph above it: "An important thing to remember when using this performance counter is that it reports user input delay on an interval of 1,000 ms by default."  I hope that clears it up.

#please-close
