### ISSUE TITLE
Update content to WS 2019 LTSC version

### ISSUE THREAD

**Issue by carlosmayol** [MicrosoftDocs/windowsserverdocs#3879]
Cx needs updated content for WS 2019. changes in recommendations for SET LoadBalance algorithm, VMMQ support (aka vrss offload) and compatibilities, like RSC enabled in the vSwitch in WS2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcdc6c48-ad04-d715-5e7b-03ba9c50a709
* Version Independent ID: 141be0cf-264f-f0d8-9fdd-937d45df45e1
* Content: [Remote Direct Memory Access (RDMA) and Switch Embedded Teaming (SET)](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v-virtual-switch/rdma-and-switch-embedded-teaming#feedback)
* Content Source: [WindowsServerDocs/virtualization/hyper-v-virtual-switch/RDMA-and-Switch-Embedded-Teaming.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v-virtual-switch/RDMA-and-Switch-Embedded-Teaming.md)
* Product: **windows-server**
* Technology: **networking-hv-switch**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by dknappettmsft** [comment]
#assign:dknappettmsft

**Comment by carlosmayol** [comment]
hello, I am closing this issue, the referenced page was removed from @dcuomo and updated page has been added in the HCI docs.
thanks
