### ISSUE TITLE
Updating (device installation) requires admin privilege, please make auto update

### ISSUE THREAD

**Issue by felinepc** [MicrosoftDocs/windowsserverdocs#3880]
Why would Microsoft not make this client auto-update like the standard Office suite, Teams client etc? 

Right now, the user has to click the "update" button to initiate an update (normally IT would not want users to do these thing). Also in our environment we used per-device installation, and updating actually requires admin privilege that the users do not have, causing confusions.

Please make this simple app self-update like the rest of modern MS apps. Maybe give us a GPO/Intune policy or even just an registry option (like right now) to control update ring/interval, and that would be good enough.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b56197c8-e490-f6fe-a494-a8aa584a8faa
* Version Independent ID: 46d1a544-517b-a4eb-68a2-cd7194aca44b
* Content: [Windows Desktop client for admins](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop-admin.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by OffColour** [comment]
And put it in Marketplace for simple Intune deployment

**Comment by felinepc** [comment]
It seems Microsoft added the auto update feature as of version 1.2.1446, which is good.

However, the behavior is controlled by the same registry "AutomaticUpdates" DWORD, which many of us previously used to suppress the "update notification" (which only notified, but wouldn't auto update) by setting it to 0.

We now need to set this again back to 2 to per documentation
"0 = Disable notifications. 1 = Show notifications. 2 = Show notifications and auto-update on close."

The documentation suggests without setting this key, 2 is the default for new installations.
