### ISSUE TITLE
Link is broken for SDDC video

### ISSUE THREAD

**Issue by carlosmayol** [MicrosoftDocs/windowsserverdocs#3881]
this one: https://mva.microsoft.com/training-courses/whats-new-in-windows-server-2016-16457?l=YcsJR6sXC_1006218965 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b1c8c0c-6f18-b4fb-07e8-e02487d77dc6
* Version Independent ID: 74dcd07f-e53a-34fb-2b55-f1b1501324bb
* Content: [Windows Server Software-Defined Datacenter](https://docs.microsoft.com/en-us/windows-server/sddc)
* Content Source: [WindowsServerDocs/sddc.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/sddc.md)
* Product: **windows-server**
* Technology: **sddc**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by dknappettmsft** [comment]
Thanks for the feedback. This article has been retired and redirected.

#please-close
