### ISSUE TITLE
workflow process diagram is unreadable

### ISSUE THREAD

**Issue by amudamai** [MicrosoftDocs/windowsserverdocs#3886]
Hi, can you provide a higher res workflow diagram or a link to a readable diagram. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d888054d-078d-53a0-bf51-02f49d2beb5a
* Version Independent ID: 7f50c60f-b0ad-f62b-54a3-267178655767
* Content: [Deploy Always On VPN](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-deployment#feedback)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-deployment.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
It looks like they removed the clickable thumbnail link.  Here's the link to the bigger image

https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/media/Always-On-Vpn/always-on-vpn-deployment-workflow.png

**Comment by amudamai** [comment]
Great, thanks

**Comment by illfated** [comment]
Ref. already open issue tickets & PR to solve this:
- **#3178** **image size very small**
- **#3474** **Image in article is unreadable**
- **#3943** **Deploy Always On VPN: Restore Larger image Link**

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
