### ISSUE TITLE
Incorrect Wording

### ISSUE THREAD

**Issue by jayantabanerjee** [MicrosoftDocs/windowsserverdocs#3887]
The section for "Environment risks"says:
 - Because many other computers and accounts in the environment are exposed to internet risk **directory or indirectly

It should read:
 - Because many other computers and accounts in the environment are exposed to internet risk **directly or indirectly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1338ba44-301c-db33-d336-80dd50a77960
* Version Independent ID: 55abfb6d-3f63-9dce-1b70-36c6265fc37b
* Content: [Why Privileged Access Workstations can help secure your organization](https://docs.microsoft.com/en-us/windows-server/identity/securing-privileged-access/privileged-access-workstations)
* Content Source: [WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md)
* Product: **windows-server**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by illfated** [comment]
Nice. Welcome to AutoCorrect ... (just a guess from my side). Very well. I will post a correction PR.
