### ISSUE TITLE
/userinfo endpoint wrong description

### ISSUE THREAD

**Issue by pameruoso** [MicrosoftDocs/windowsserverdocs#3888]
Actually the page states that the userinfo endpoint returns the claims about the authenticated user. This is totally wrong as the userinfo endpoint is returning only the "SUB".  This is making confusion because everyone expects to see the user claims there. In azure ad it works, not in ADFS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 305d0726-a212-975f-822e-9a23af6e7ccb
* Version Independent ID: b88a9450-4376-2fd2-aaaa-3b2d086dd266
* Content: [AD FS OpenID Connect/OAuth Concepts](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/ad-fs-openid-connect-oauth-concepts#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/ad-fs-openid-connect-oauth-concepts.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/ad-fs-openid-connect-oauth-concepts.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by mattroot87** [comment]
Not sure I understand why calling the userinfo endpoint if it doesn't return any additional claims.  I just returns a "SUB" key with a value set as a guid.  What would be the purpose of calling this endpoint?

**Comment by idelfonsog2** [comment]
Hi there @pameruoso, I'm having an issue Can you add an example of how the response looks like?

**Comment by IngridAtMicrosoft** [comment]
Issue addressed.
