### ISSUE TITLE
Missing Deployment Information

### ISSUE THREAD

**Issue by elliot-huffman** [MicrosoftDocs/windowsserverdocs#3889]
The deployment instructions are missing for the powershell method.
It does not explain what is set up or how to get it set up. the next set of instructions (https://docs.microsoft.com/en-us/windows-server/administration/hybrid-cloud-print/hybrid-cloud-print-deploy) assumes that there is a configuration that is already deployed, however it does not state what is deployed.
These set of instructions are in complete for the above link to be satisfied with the pre-reqs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 427830e4-3523-d341-9228-ffc74125bf22
* Version Independent ID: d34465b7-59fe-c85f-9bac-1f4510a5018c
* Content: [Windows Server Hybrid Cloud Print overview](https://docs.microsoft.com/en-us/windows-server/administration/hybrid-cloud-print/hybrid-cloud-print-overview)
* Content Source: [WindowsServerDocs/administration/hybrid-cloud-print/hybrid-cloud-print-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/hybrid-cloud-print/hybrid-cloud-print-overview.md)
* Product: **w10**
* Technology: **server-general**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by IngridAtMicrosoft** [comment]
We will leave the document as-is as there is a statement on it that says it is no longer supported.  #please-close
