### ISSUE TITLE
drivestoredirect setting does not work on the Microsoft.RDInfra.RDPowerShell Module

### ISSUE THREAD

**Issue by urighi** [MicrosoftDocs/windowsserverdocs#3890]
When trying to set drivestoredirect via Set-RdsHostPool using the CustomProperty parameter, the only option that works is *. As it needs the colons for each drive, the parser recognizes it as a separator (propertyname:type:value). I tried escaping the character, using single quotes, double quotes, and it doesn't work.
 
&gt; Set-RdsHostPool -TenantName $tenantname -HostPoolName $hostpoolname -CustomRdpProperty "drivestoredirect:s:c:"

Set-RdsHostPool : CustomRdpProperty must be in the form of name:type:value.
ActivityId: 357aa52d-2ebd-42fc-9dc7-12fe9e3d025e
Powershell commands to diagnose the failure:
Get-RdsDiagnosticActivities -ActivityId 357aa52d-2ebd-42fc-9dc7-12fe9e3d025e
At line:1 char:1
+ Set-RdsHostPool -TenantName $tenantname -HostPoolName $hostpoolname ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (Microsoft.RDInf....SetRdsHostPool:SetRdsHostPool) [Set-RdsHostPool], RdsPowerShellException
    + FullyQualifiedErrorId : HostPoolIncorrectFormatCustomRdpProperties,Microsoft.RDInfra.RDPowershell.HostPool.SetRdsHostPool

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 630c940d-79fe-3f4e-104c-8e8b19b480e4
* Version Independent ID: 2c4d6608-8fa2-ca33-3a3e-97acfc995f4f
* Content: [Supported Remote Desktop RDP file settings](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/rdp-files?context=/azure/virtual-desktop/context/context)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/rdp-files.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/rdp-files.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @btaintor
* Microsoft Alias: **helohr**

**Comment by robinharwood** [comment]
We hugely appreciate your contribution, feedback, and support to our technical documentation.

We’ve phased out GitHub Issues on this repository as the feedback mechanism for content and have replaced it with a new feedback system. For more information see, [Content User Feedback](https://aka.ms/ContentUserFeedback). As part of this rollout, we are migrating your issue where our team will use your comments to improve the documentation experience. Unfortunately, this does mean you won't be able to access this issue after the migration is complete.

All issues will be migrated by Thursday 29th August 2024.

Once again, thank you for your valuable feedback, we hope you’ll continue to contribute using our new feedback system.
