### ISSUE TITLE
Heads up on password grant type

### ISSUE THREAD

**Issue by pinkrrr** [MicrosoftDocs/windowsserverdocs#3893]
For "Resource owner password credentials grant flow" it could be possible that one need to specify resource parameter that corresponds with relying party identifier of endpoint you trying to authorize for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5399f381-2744-9012-2575-b2d1dd110040
* Version Independent ID: c816cb8d-b7b5-6fe7-bcca-b5d0da9efefc
* Content: [AD FS OpenID Connect/OAuth flows and Application Scenarios](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-openid-connect-oauth-flows-scenarios#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/ad-fs-openid-connect-oauth-flows-scenarios.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/ad-fs-openid-connect-oauth-flows-scenarios.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by PRMerger7** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: ingridatmicrosoft 
gh issue comment 3888 -b ingridatmicrosoft

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
