### ISSUE TITLE
Link to article 164787 links back to this page

### ISSUE THREAD

**Issue by binki** [MicrosoftDocs/windowsserverdocs#3894]
There is text

&gt; Rundll32 can only call functions from a DLL that are explicitly written to be called by Rundll32. For more information about Rundll32 requirements see article [164787](https://go.microsoft.com/fwlink/?LinkID=165773) in the Microsoft Knowledge Base (https://go.microsoft.com/fwlink/?LinkID=165773).

I expect to find more information upon clicking that link. However, I end up redirected back to this page which does give the additional information that parameter suggests I should be able to find.

That information should be placed on this page or the link fixed to point to it.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09a448aa-499f-1489-5cd5-b519cb4be8d2
* Version Independent ID: f8c0c0a4-2ca0-a7a4-d56a-3457ea6eec46
* Content: [rundll32](https://docs.microsoft.com/en-gb/windows-server/administration/windows-commands/rundll32)
* Content Source: [WindowsServerDocs/administration/windows-commands/rundll32.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/rundll32.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Recursive by name, recursive by nature.

https://support.microsoft.com/kb/164787 = https://docs.microsoft.com/windows-server/administration/windows-commands/rundll32

(bug note: I keep getting the /bg-bg/ language page when going to KB 164787)

**Comment by illfated** [comment]
Bug confirmation aside, I am trying to search for a different KB number or page for the additional rundll32 information, but it seems to be difficult to find within the microsoft.com domain.

Could you suggest a reasonable microsoft.com page filling the criteria for "more information about Rundll32 requirements"?
If yes, we would like to suggest that page as a replacement for this recursiveness.

**Comment by illfated** [comment]
See also issue ticket #3654 (**Missing information**) about the same page & issue.
