### ISSUE TITLE
NIC Config

### ISSUE THREAD

**Issue by sawyerleftwich** [MicrosoftDocs/windowsserverdocs#3895]
This how to needs more documentation on configuring both the NICs on the Always On VPN RRAS Server. This article did a great job of stating what needs to be done as far as default gateways and routing to start with
https://directaccess.richardhicks.com/2019/08/19/always-on-vpn-and-rras-with-single-nic/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76dd49bb-b86e-f5b7-35b9-a8d246d36fcb
* Version Independent ID: dedfa83f-36d6-f60b-e839-ba382c5a7372
* Content: [Configure the Server Infrastructure](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure#feedback)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by anaharris-ms** [comment]
Thank you for providing feedback that helps improve our documentation. I have put your suggestion into our backlog, and we are closing the issue. #please-close

**Comment by anaharris-ms** [comment]
#please-open

**Comment by anaharris-ms** [comment]
#please-close Tutorial has been updated: https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/3398
