### ISSUE TITLE
Incorrect syntax

### ISSUE THREAD

**Issue by stevenmessick** [MicrosoftDocs/windowsserverdocs#3896]
In a few places in this document the backslash is used along with an asterisk: E.g. dir read*.\*. The DIR command considers that syntax invalid. Here's the output from that command in my users folder:

C:\Users\steve&gt;dir read*.\*
The filename, directory name, or volume label syntax is incorrect.

I believe you meant the example to be "dir read*.*" without the quotes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8095c8a1-5049-2eb1-2041-6392f2025cfa
* Version Independent ID: 6e63df5e-a455-33c7-22db-36f44121a2c0
* Content: [dir](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/dir#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/dir.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/dir.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
> In a few places in this document the backslash is used along with an asterisk: E.g. dir read*.*. The DIR command considers that syntax invalid. Here's the output from that command in my users folder:
> 
> C:\Users\steve>dir read*.*
> The filename, directory name, or volume label syntax is incorrect.
> 
> I believe you meant the example to be "dir read*.*" without the quotes.
> 
Looks like your comment has been interpreted by MarkDown and there may be some characters hidden as if they were HTML code.

I do not see any change between your error example and the suggested correction.

**Comment by illfated** [comment]
You may want to use MarkDown blockquote or code blocks to make sure your text stays untouched, for the HTML tag characters or escape characters to show up.
- https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by illfated** [comment]
Never mind, I see there is some quite confusing usage of backslash \\ in this page underneath the Remarks section title
(https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/dir#remarks):

## Remarks

- To use multiple *FileName* parameters, separate each file name with a space, comma, or semicolon.
- You can use wildcard characters (**&#42;** or **?**), to represent one or more characters of a file name and to display a subset of files or subdirectories.

  **Asterisk (\*):** Use the asterisk as a substitute for any string of characters, for example:  
  - **dir \*.txt** lists all files in the current directory with extensions that begin with .txt, such as .txt, .txt1, .txt_old.
  - **dir read\*.txt** lists all files in the current directory that begin with "read" and with extensions that begin with .txt, such as .txt, .txt1, or .txt_old.
  - **dir read\*.\\*** lists all files in the current directory that begin with "read" with any extension.

  The asterisk wildcard always uses short file name mapping, so you might get unexpected results. For example, the following directory contains two files (t.txt2 and t97.txt): 
 
  ```
  C:\test>dir /x
  Volume in drive C has no label.
  Volume Serial Number is B86A-EF32
    
  Directory of C:\test
    
  11/30/2004  01:40 PM <DIR>  .
  11/30/2004  01:40 PM <DIR> ..
  11/30/2004  11:05 AM 0 T97B4~1.TXT t.txt2
  11/30/2004  01:16 PM 0 t97.txt
  ```

**Comment by illfated** [comment]
Wow... I never noticed this. I must have fallen asleep when I was about to open the pull request based on my commit https://github.com/illfated/windowsserverdocs/commit/1ad64509e9be4bf887cd34f89a407e3fecb9a9f5 . Oh well, that is "water under the bridge" now. I will go ahead and open the PR now, even though it has been dormant for 3 weeks. Sorry about that. I must have been really tired back then.
