### ISSUE TITLE
Need some fix

### ISSUE THREAD

**Issue by CaioBauab** [MicrosoftDocs/windowsserverdocs#3897]
MD e:\share01 &lt;&lt; This need to be f:\share01

New-SmbShare -Name Share01 -Path f:\share01 -ContinuouslyAvailable $false

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5b8571f-1576-5c86-e257-1dad6c525ffc
* Version Independent ID: e2b0badd-9319-d81d-9cc9-e6a7010af3d7
* Content: [Stretch Cluster Replication Using Shared Storage](https://docs.microsoft.com/en-us/windows-server/storage/storage-replica/stretch-cluster-replication-using-shared-storage?redirectedfrom=MSDN#feedback)
* Content Source: [WindowsServerDocs/storage/storage-replica/Stretch-Cluster-Replication-Using-Shared-Storage.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-replica/Stretch-Cluster-Replication-Using-Shared-Storage.md)
* Product: **windows-server**
* Technology: **storage-replica**
* GitHub Login: @nedpyle
* Microsoft Alias: **nedpyle**

**Comment by dknappettmsft** [comment]
Thanks for raising this issue. I have corrected the line and the change should be visible in a few hours.

#please-close
