### ISSUE TITLE
The file server role didn't failover

### ISSUE THREAD

**Issue by CaioBauab** [MicrosoftDocs/windowsserverdocs#3900]
[Window Title]
Error

[Main Instruction]
The operation has failed.

[Content]
The action 'Move' did not complete.

[^] Hide Details  [OK]

[Expanded Information]
Error Code: 0x80071398
The operation failed because either the specified cluster node is not the owner of the group, or the node is not a possible owner of the group

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5b8571f-1576-5c86-e257-1dad6c525ffc
* Version Independent ID: e2b0badd-9319-d81d-9cc9-e6a7010af3d7
* Content: [Stretch Cluster Replication Using Shared Storage](https://docs.microsoft.com/en-us/windows-server/storage/storage-replica/stretch-cluster-replication-using-shared-storage?redirectedfrom=MSDN#BKMK_FileServer)
* Content Source: [WindowsServerDocs/storage/storage-replica/Stretch-Cluster-Replication-Using-Shared-Storage.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-replica/Stretch-Cluster-Replication-Using-Shared-Storage.md)
* Product: **windows-server**
* Technology: **storage-replica**
* GitHub Login: @nedpyle
* Microsoft Alias: **nedpyle**

**Comment by dknappettmsft** [comment]
Hi, GitHub issues in this repo is for documentation issues, not for product support. Please contact Microsoft Support (https://support.microsoft.com/) for help.

#please-close
