### ISSUE TITLE
Undocumented option

### ISSUE THREAD

**Issue by leifurhauks** [MicrosoftDocs/windowsserverdocs#3906]
The document lists an option `/b` with the description "Copies files in Backup mode." There is no explanation anywhere in the document about what "Backup mode" means in this context. Thus the behavior of this option is named but undocumented. I see that I'm not the first person to notice this, see also #811 which was closed but never resolved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Thank you for posting this question again. I think we should consider a possible answer posted in forum pages like the following:
- https://social.technet.microsoft.com/Forums/ie/en-US/899e3b9c-2576-4160-9c76-de6d0c8c4fc6/question-about-how-the-robocopy-b-switch-works
- https://superuser.com/questions/976864/what-is-backup-mode-in-robocopy

[Microsoft Technet forum post](https://social.technet.microsoft.com/Forums/ie/en-US/899e3b9c-2576-4160-9c76-de6d0c8c4fc6/question-about-how-the-robocopy-b-switch-works) by [**jrv**](https://social.technet.microsoft.com/profile/jrv):
> /B (backup mode) will allow Robocopy to override file and folder permission settings (ACLs).
>
> Backup mode requires RC to be run from an account with enough privileges to accomplish this trick. Normally RC respects the ACL restrictions.
>
> If you specify backup of security info, it will still be backed up.  That should be independent of the backup mode setting.

StackExchange [SuperUser forum post](https://superuser.com/questions/976864/what-is-backup-mode-in-robocopy) by [Justin Krejcha](https://superuser.com/users/312312/justin-krejcha):
> It uses the SeBackupPrivilege (reading) and SeRestorePrivilege (writing) in order to read/write any and all files, disregarding any ACEs that would prevent you from reading or writing a file.
>
> Normally when trying to copy or access a file, Windows performs a check to make sure you have permission to read or write to location, but with SeBackupPrivilege (granted to the Backup Operators and Administrators groups), and SeRestorePrivilege (also granted to the Backup Operators and Administrators groups), these checks are bypassed.
>
> To check if your account has these privileges, you can run the command whoami /priv at a command prompt.

I think we should be able to condense those two answers into one usable description for the docs.microsoft.com [Robocopy page](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy).

@mycroes, @WurstCommander, @ThrashAbaddon, @sammosov, @graham8, @daveba : 
Feel free to post suggestions for how you think it should look on the MS Docs page.

**Comment by dknappettmsft** [comment]
Thanks for the feedback. I can see that information for this parameter was added in March 2021 ([commit](https://github.com/MicrosoftDocs/windowsserverdocs/commit/b0a56d57f4a1c1d36710cb4be4efe5271f85493c)).

#please-close
