### ISSUE TITLE
Test is full #13

### ISSUE THREAD

**Issue by ticianaciminari** [MicrosoftDocs/windowsserverdocs#3907]
@Raffatronic commented 3 days ago — with docs.microsoft.com
Dear MS
I would love to test this one in our Office -&gt; We are a large account reseller. Yet the testgroup is full.
Could you provide me a code to test?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d21e96b-c8a6-7f9f-76e1-62ee4fbde62b
* Version Independent ID: 5530201e-2ff5-19de-5990-1a996cf5ef2e
* Content: [Get started with the iOS client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-ios#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-ios.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-ios.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by ticianaciminari** [comment]
Hi Team, could you please check the question from user? 

Kind regards,
Microsoft DOCS International Team

**Comment by dknappettmsft** [comment]
Closing as it's not an issue with the article.

#please-close
