### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by nashuatek** [MicrosoftDocs/windowsserverdocs#3909]
If you do a find for "Start Manu and Taskbar", it should be "Start Menu"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 897ba3ed-4e13-c34b-639a-4148c4acf057
* Version Independent ID: 23b08a31-3913-c41a-ae49-59091c01cd4b
* Content: [Recommended configuration for VDI desktops](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-vdi-recommendations#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-vdi-recommendations.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-vdi-recommendations.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @jaimeo
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
Thanks, good catch.

**Comment by jaimeo** [comment]
@eross-msft

**Comment by eross-msft** [comment]
Closing issue since this is now a pull request. Waiting on article owner to validate changes.

**Comment by illfated** [comment]
OK, fair enough. even though my PR would have closed this issue automatically.

End of the PR commit comment text:
***
**Ticket closure or reference:**

Closes MicrosoftDocs#3909
***
