### ISSUE TITLE
Stand-alone namespaces can run on Azure cluster

### ISSUE THREAD

**Issue by richardvogels** [MicrosoftDocs/windowsserverdocs#3912]
Stand-alone DFS namespaces can run on an Azure cluster with csv disks configured with storage spaces direct using premium ssd, running Windows Server 2016 or 2019. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea517059-9b5a-bc03-b1f6-f4b8f8871090
* Version Independent ID: d6c91daf-152c-ab4e-c446-ec2fee710184
* Content: [DFS Namespaces overview](https://docs.microsoft.com/en-us/windows-server/storage/dfs-namespaces/dfs-overview)
* Content Source: [WindowsServerDocs/storage/dfs-namespaces/dfs-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/dfs-namespaces/dfs-overview.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by dknappettmsft** [comment]
Thanks for the feedback. I can see this article has been updated since that added that you can cluster stand-alone namespaces in Azure virtual machines using failover clusters.

#please-close
