### ISSUE TITLE
Using ERRORLEVEL to Simplify Results of Binary Comparison

### ISSUE THREAD

**Issue by VikingByNature** [MicrosoftDocs/windowsserverdocs#3913]
For those of you who do not wish to see a lengthy list of differences when doing a binary comparison, you can use the **`ERRORLEVEL`** variable, along with output redirection, inside of a batch script for creating custom status messages.  The **`ERRORLEVEL`** variable is set to **`0`** if there are no differences and **`1`** if there are difference.  Here is the following batch file I created to simplify the use of **FC**:

```
@REM ChkFDiff.BAT
@REM Usage: CHKFDIFF "<Drive>:\[<Path>\]<File Name 1.EXT>" "<Drive>:\[<Path>\]<File Name 2.EXT>"

@ECHO OFF
FC /B "%~1" "%~2" 1> NUL: 2> NUL:
IF ERRORLEVEL 1 ECHO WARNING: Differences encountered while comparing "%~NX1" against "%~NX2". 1> CON: & GOTO Exit
IF ERRORLEVEL 0 ECHO No differences encountered between "%~NX1" and "%~NX2". 1> CON:

:Exit
@ECHO ON
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bdf968d-063d-902e-9437-7c28ef7d61f2
* Version Independent ID: f366d9ed-68cb-c949-4c1f-389570d906a0
* Content: [fc](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fc)
* Content Source: [WindowsServerDocs/administration/windows-commands/fc.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/fc.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by dknappettmsft** [comment]
Hi, thanks for the suggestion. This article is to document the parameters and syntax and basic examples of how to use them, rather than longer scripted examples. This would be good content to have on a blog, though.

#please-close
