### ISSUE TITLE
Step 13 image wrong

### ISSUE THREAD

**Issue by ticianaciminari** [MicrosoftDocs/windowsserverdocs#3914]
@nicogis commented yesterday
The image in step 13 has : 'Install Windows Server 2019 ...' . It should be 'Install Windows Server 2016 ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 465ee446-5e41-bd72-1305-976db9c3a4ec
* Version Independent ID: f7091237-826d-1e6e-d8f3-b688205f25fd
* Content: [Upgrade Windows Server 2012 to Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/upgrade/upgrade-2012-to-2016#feedback)
* Content Source: [WindowsServerDocs/upgrade/upgrade-2012-to-2016.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/upgrade/upgrade-2012-to-2016.md)
* Product: **windows server**
* Technology: **server-general**
* GitHub Login: @RobHindman
* Microsoft Alias: **robhind**

**Comment by illfated** [comment]
I have edited the image in question (https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/upgrade/media/upgrade-2012-2016/ready-to-install.png) by copying the text "Server 2016" from the previous image (license-terms.png) and replaced the text "Server 2019" with "Server 2016" seeing that it is of identical size by pixel and shading and with identical background.

I hope my suggested edit will be useful to you (PR incoming to update the image).

**Comment by illfated** [comment]
(also ref. https://github.com/MicrosoftDocs/windowsserverdocs.it-it/issues/4)
