### ISSUE TITLE
Update needed.

### ISSUE THREAD

**Issue by carlosmayol** [MicrosoftDocs/windowsserverdocs#3921]
This page requires update, there is unsupported Guest OS versions listed. N-1/N+1 its not honored which causes confusion. The mechanism to update Guest OS through Windows Update does not work properly for 2012R2 HOST hosting 2016/2012R2/2012

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf5eedca-3535-d00e-98ab-9e25496a30a7
* Version Independent ID: 797c37a7-ccd5-ed59-2dc3-5cf3892bbf3b
* Content: [Manage Hyper-V Integration Services](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/manage-hyper-v-integration-services?source=docs#keep-integration-services-up-to-date)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/Manage-Hyper-V-integration-services.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/Manage-Hyper-V-integration-services.md)
* Service: **na**
* Product: **windows-server**
* Technology: **compute-hyper-v**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by dknappettmsft** [comment]
Hi @carlosmayol - please could you provide a bit more information? I can remove the unsupported guest OS versions, but not sure what you're referring to for N-1/+1 and Windows Update not working properly for 2012R2 Host

**Comment by dknappettmsft** [comment]
#assign:dknappettmsft

**Comment by carlosmayol** [comment]
Hello, that has almost 2 years ago, happy someone is picking them at the end. Please just update OS versions. W11, WS2022 and check all out of support OSs

**Comment by dknappettmsft** [comment]
Thanks. I have tidied up this article, those version tables weren't hugely relevant anymore as integration services are updated through Windows Update or Linux kernel updates. There is a separate article already covering the supported guest OS versions in Hyper-V.  The updated article should be visible later today.

#please-close
