### ISSUE TITLE
Additional considerations

### ISSUE THREAD

**Issue by pwgrmi** [MicrosoftDocs/windowsserverdocs#3923]
Once you change a dynamic disk back to a basic disk, you can create only partitions and logical drives on that disk, or add it to a Storage Spaces Pool.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 722fedef-d6a4-5ed6-526b-d6dd1a4d0642
* Version Independent ID: 10f9b44a-5a88-cb84-293f-1baf62359299
* Content: [Change a dynamic disk back to a basic disk](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/change-a-dynamic-disk-back-to-a-basic-disk#feedback)
* Content Source: [WindowsServerDocs/storage/disk-management/change-a-dynamic-disk-back-to-a-basic-disk.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/change-a-dynamic-disk-back-to-a-basic-disk.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by dknappettmsft** [comment]
Thanks for the feedback. Being able to add the disk to a Storage Spaces pool would be implied as that is type of type needed for Storage Spaces. I'm going to leave this article as-is to keep it clear.

#please-close
