### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by carlosmayol** [MicrosoftDocs/windowsserverdocs#3925]
&lt;&lt;validating your HGS configuration&gt;&gt; LINK at the end is broken, this links appears in each setup mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fcd846e-32f9-c5c1-8522-582baac6240e
* Version Independent ID: 97308239-844e-9432-3580-34cad539bdee
* Content: [Initialize the HGS cluster using TPM mode in a new dedicated forest (default)](https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-initialize-hgs-tpm-mode-default)
* Content Source: [WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-initialize-hgs-tpm-mode-default.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-initialize-hgs-tpm-mode-default.md)
* Product: **windows-server**
* Technology: **security-guarded-fabric**
* GitHub Login: @rpsqrd

**Comment by illfated** [comment]
Broken link (404):
- https://docs.microsoft.com/windows-server/virtualization/guarded-fabric-shielded-vm/guarded-fabric-verify-hgs-configuration

I used web search engines and tried searching exclusively for the term "validating your HGS configuration", but all I could find was copies of the page where that link is used. I have also exhausted the links suggested by the 404 page, so it appears that the link page (`guarded-fabric-verify-hgs-configuration`) has been deleted (given that it has been there at some point back in the past).

The only existing trace I could find of the missing page is this one,
- https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/guarded-fabric-and-shielded-vms.md

but it only contains the following meagre content:

---
redirect_url: /guarded-fabric-shielded-vm/guarded-fabric-and-shielded-vms
---

There is a reference to the file back in 2017, but it does not show anything else than renaming of the path to the file:
- https://github.com/MicrosoftDocs/windowsserverdocs/commit/c1da762aba613cfd182d864957b3bd2084079984#diff-a32ef9d43b0bee65e0286f9c394c427a

**Comment by illfated** [comment]
Looks like the referenced page has been changed, but the change is not to be found. The only 2 links which are "at the end of the page" are these 2:
- https://docs.microsoft.com/en-us/windows-server/virtualization/guarded-fabric-shielded-vm/guarded-fabric-configure-additional-hgs-nodes
- https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-install-trusted-tpm-root-certificates

Both of the links above are OK and working, so no 404 error from links in the lower part of the page.

Point 3, on the other hand, contains a broken link:

2. Run [Initialize-HgsServer](https://technet.microsoft.com/library/mt652185.aspx) in an elevated PowerShell window [ ... ] (https://technet.microsoft.com/library/mt652185.aspx)

That link redirects to the following URL: https://docs.microsoft.com/en-us/powershell/module/host-guardian-service/server/initialize-hgsserver (which returns 404).

The correct link should have been: https://docs.microsoft.com/powershell/module/hgsserver/initialize-hgsserver
