### ISSUE TITLE
Updates to Server Versions

### ISSUE THREAD

**Issue by jantoney** [MicrosoftDocs/windowsserverdocs#3926]
Page mentions server 2016 but I believe should include Server 2019 as well

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90e335dd-0bc5-a7e3-650b-e3dd1823176b
* Version Independent ID: 18f34ef3-ff61-0473-a64b-ac5a64dbe1d7
* Content: [Azure Hybrid Benefit for Windows Server](https://docs.microsoft.com/en-us/windows-server/get-started/azure-hybrid-benefit)
* Content Source: [WindowsServerDocs/get-started/azure-hybrid-benefit.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/azure-hybrid-benefit.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by greg-lindsay** [comment]
This needs to be assigned to the topic owner, which is not me. I don't have permission to assign.

**Comment by illfated** [comment]
( also ref. issue ticket #488 from the same page, needs an update )

**Comment by dknappettmsft** [comment]
Thanks for the feedback. This article has been updated.

#please-close
