### ISSUE TITLE
Solution does not work

### ISSUE THREAD

**Issue by jelutz77** [MicrosoftDocs/windowsserverdocs#3933]
When I click on RD Licensing, I do not get any reporting options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5db2bb5f-5b0a-fe7f-acf8-5760dd0df259
* Version Independent ID: 8a3ba9d8-2696-7652-0c9c-90b3bb70d9dc
* Content: [Track your Remote Desktop Services client access licenses (RDS CALs)](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-track-cals)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-track-cals.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-track-cals.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
Sounds like an issue you need local troubleshooting help to deal with, for example by calling Microsoft Support or post in the techcommunity forum pages.

Please note that the main goal for these pages is to improve the current documentation. If you find incorrect or missing information in this page, please tell us about it.

By the way, did you consider the "Azure AD Domain Services in your environment" note tip on the page?

**Comment by jelutz77** [comment]
My comment pointed out incorrect information on the page. I’m not interested in your pitch.

**Comment by illfated** [comment]
> My comment pointed out incorrect information on the page. I’m not interested in your pitch.

Oh well, if you say so. From my point of view, that is not how I interpreted your sentence, but then again, I speak English only on a near-native level.

It would be very helpful if you point out which parts of the text is incorrect without others having to guess what you mean.

**Comment by gsi04598** [comment]
I've read this conversation about 20 times and it's just as hilarious as my first read.

**Comment by illfated** [comment]
Fair enough, I am just stumped. I do not know if anyone wants to have the page improved, and if so, how they want it improved.
