### ISSUE TITLE
Table not helpful B1

### ISSUE THREAD

**Issue by Kriegel** [MicrosoftDocs/windowsserverdocs#3936]
Hi there,

The main headline say "privileged" and the Table "B-1: Built-in and Default Accounts and Groups in Active Directory"
is a simple List of default Groups and accounts.
That is not helpful to identify privileged Groups and accounts.

Every admin can see these accounts List, by simply spinning up a new AD Test-Server....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1329c1d1-c6bd-6005-39e3-f04763735ae4
* Version Independent ID: 0915e4bb-7383-b971-9f9b-7aba95ab501c
* Content: [Appendix B - Privileged Accounts and Groups in Active Directory](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/appendix-b--privileged-accounts-and-groups-in-active-directory#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-B--Privileged-Accounts-and-Groups-in-Active-Directory.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-B--Privileged-Accounts-and-Groups-in-Active-Directory.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
Understood but many like it. #please-close
