### ISSUE TITLE
Please put privileged Groups (and Accounts) into a Table 

### ISSUE THREAD

**Issue by Kriegel** [MicrosoftDocs/windowsserverdocs#3937]
The 4 Privileged Group names are "hidden" in flow-text.
I think, to offer these in a separate table can be very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1329c1d1-c6bd-6005-39e3-f04763735ae4
* Version Independent ID: 0915e4bb-7383-b971-9f9b-7aba95ab501c
* Content: [Appendix B - Privileged Accounts and Groups in Active Directory](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/appendix-b--privileged-accounts-and-groups-in-active-directory#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-B--Privileged-Accounts-and-Groups-in-Active-Directory.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-B--Privileged-Accounts-and-Groups-in-Active-Directory.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by illfated** [comment]
Fair point. I see what you mean. I had to search and look for them myself:
> Within Active Directory, there are three built-in groups that comprise the highest privilege groups in the directory: the Enterprise Admins (EA) group, the Domain Admins (DA) group, and the built-in Administrators (BA) group.
>
> A fourth group, the Schema Admins (SA) group, has privileges that, if abused, can damage or destroy an entire Active Directory forest, but this group is more restricted in its capabilities than the EA, DA, and BA groups.

Do you have any suggestions for what else could be put in that table, for example a short description of their privileges?


| Privileged Group |          Name           | Properties |
| :--------------: | ----------------------- | ---------- |
|        EA        | Enterprise Admins       |            |
|        DA        | Domain Admins           |            |
|        BA        | built-in Administrators |            |
|        SA        | Schema Admins           |            |
