### ISSUE TITLE
Example Binpath info

### ISSUE THREAD

**Issue by bruceburge** [MicrosoftDocs/windowsserverdocs#3941]
I'm not sure it wise to include the "ntsd -d" part of the binpath it's outside the scope of the default use of the the command.
Additionally it is used here without explanation, which by default will cause the service to fail to start, and if they do have the debugger installed, this won't likely result in the service performing in the way the typically user would expect. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62f6080f-a19b-df74-7156-372dbce9e9de
* Version Independent ID: 80fbd3ca-27d0-b624-6e05-6d3cde5aed4e
* Content: [Sc config](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/sc-config#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/sc-config.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/sc-config.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by dknappettmsft** [comment]
Thanks for the feedback. I have removed 'ntsd -d' from the example and added a reference and link to further information in the table above. These changes should be visible later today.

#please-close
