### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by SauerKraut51** [MicrosoftDocs/windowsserverdocs#3947]
The following Links are broken ("Content Removed"):
https://go.microsoft.com/fwlink/?linkid=180896
https://go.microsoft.com/fwlink/?linkid=180897

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d7bd11a-e693-26a0-d374-5cfb1d2335d3
* Version Independent ID: bc9a2fb3-fa85-4ec0-8e0f-6e7c4906262b
* Content: [Volume Shadow Copy Service](https://docs.microsoft.com/en-us/windows-server/storage/file-server/volume-shadow-copy-service#feedback)
* Content Source: [WindowsServerDocs/storage/file-server/volume-shadow-copy-service.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/volume-shadow-copy-service.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Looks like a proper solution would be to remove those links (and their lines) altogether, seeing that the content they used to link to is
- Windows Server 2008 and Windows Vista SP1
- Windows Server 2008 R2 and Windows 7

Also note the content in the Note blob on the page https://docs.microsoft.com/windows/win32/vss/in-box-vss-writers :
> [!Note]  
> The MSDE in-box writer is not available in Windows Vista, Windows Server 2008, and later. Instead, the SQL Writer should be used to back up SQL Server databases. Only SQL Server 2005 SP2 and later are supported on Windows Vista, Windows Server 2008, and later.
