### ISSUE TITLE
No instructions for Internet Proxy settings

### ISSUE THREAD

**Issue by jgallucci32** [MicrosoftDocs/windowsserverdocs#3948]
The implementation as written does not support using AD FS behind an HTTP proxy server. When behind an HTTP proxy, the following error `Encountered error during federation passive request` appears in the logs with the details `System.Exception: Exception calling SAS. ---&gt; System.Net.WebException: The remote name could not be resolved: 'adnotifications.windowsazure.us'`

Other components of Azure such as the Azure App Proxy have you specify in the XML the settings for HTTP proxy access. These instructions cannot be found for using the Azure MFA adapter with AD FS.

Please identify the location of the HTTP proxy settings for the Azure MFA adapter or add a note that this is not supported and that direct internet access is reqiured.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f333e8cb-c046-ee06-d33d-d7dc8e8af695
* Version Independent ID: 10838695-f60e-42a7-b0e8-eed7820fd333
* Content: [Configure AD FS 2016 and Azure MFA](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by marcinfaza** [comment]
Hello, facing the same issue. Does it work with proxy or not?

**Comment by markal09** [comment]
I am facing the same issue, what was the resolution?

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
