### ISSUE TITLE
%SystemDisk% does not exist

### ISSUE THREAD

**Issue by HenningSR** [MicrosoftDocs/windowsserverdocs#3950]
I think %SystemDisk% in the above is an error, and should be corrected to %SystemDrive% (%SystemDrive%\ClusterStorage).
The system variables can be viewed in PowerShell with this command "Get-ChildItem env:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b417d33d-000d-5ae8-2525-663849e5e62a
* Version Independent ID: 16ccda8e-9d73-053f-4b67-20eaeac524bf
* Content: [Use Cluster Shared Volumes in a failover cluster](https://docs.microsoft.com/en-us/windows-server/failover-clustering/failover-cluster-csvs#feedback)
* Content Source: [WindowsServerDocs/failover-clustering/failover-cluster-csvs.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/failover-cluster-csvs.md)
* Product: **windows-server**
* Technology: **storage-failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Have you tested this theory on a cluster storage system, to see if that is correct? At first I was thinking that you are correct, but searching for "%SystemDisk%ClusterStorage" to see if anyone else have reported this as an issue elsewhere, it does not appear to be any issue when looking at SQL servers and large systems. Sure, I would have liked to open a Pull Request to have that changed, if this can be confirmed to be a verified issue somewhere else. Unless you have found this to be a working solution for a clustering failover system, I am hesitant to make any moves to change this content.

**Comment by HenningSR** [comment]
Yes I have tested it. See the attachment.
![Annotation 2020-02-27 201301](https://user-images.githubusercontent.com/49991320/75478080-9c957700-599d-11ea-9863-ed2be3f58d76.jpg)

**Comment by illfated** [comment]
Fair enough, I expected (and verified) that `%SystemDisk%` is invalid on regular Windows computers and standard Windows servers (in contrast to `%SystemDrive%`), but I could not easily find that someone else had made this complaint elsewhere on the web. I was sort of hoping that this could have been posted elsewhere too, but, as I said, it looked like there was no apparent issue to be found.

My question was mainly to make sure that this is not something based on a simple Windows 10 or Windows Server standard lookup.

**Comment by illfated** [comment]
Oh my. This COVID-19 situation really took a toll on my ability to follow up on tickets I have commented on earlier. Oh well. I checked a normal Windows Server 2016 (Standard) to see what the environment variables are, both in the VM and in the OS directly on the physical server. They are as follows:

Physical server (HP ProLiant):

<details>
<summary>Administrator CMD SET variables</summary>

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Administrator>set
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\Administrator\AppData\Roaming
CLIENTNAME=TROND-PC
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=SULEHV01
ComSpec=C:\Windows\system32\cmd.exe
HOMEDRIVE=C:
HOMEPATH=\Users\Administrator
LOCALAPPDATA=C:\Users\Administrator\AppData\Local
LOGONSERVER=\\SULEHV01
NUMBER_OF_PROCESSORS=16
OS=Windows_NT
Path=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\\Hewlett-Packard\HPSUT\bin;C:\Program Files\Symantec.cloud\PlatformAgent\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 79 Stepping 1, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=4f01
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=RDP-Tcp#11
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\ADMINI~1\AppData\Local\Temp\2
TMP=C:\Users\ADMINI~1\AppData\Local\Temp\2
USERDOMAIN=SULEHV01
USERDOMAIN_ROAMINGPROFILE=SULEHV01
USERNAME=Administrator
USERPROFILE=C:\Users\Administrator
windir=C:\Windows

C:\Users\Administrator>_
```

</details>

Windows Server 2016 (Standard) VM environment:

<details>
<summary>Administrator CMD SET variables</summary>

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Administrator>set
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\Administrator\AppData\Roaming
CLIENTNAME=TROND-PC
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=SULEDC01
ComSpec=C:\Windows\system32\cmd.exe
ERIC_INI_HOME=C:\Users\ADMINI~1\AppData\Local\Temp\
ERIC_LOG_HOME=C:\Users\ADMINI~1\AppData\Local\Temp\
HOMEDRIVE=C:
HOMEPATH=\Users\Administrator
LOCALAPPDATA=C:\Users\Administrator\AppData\Local
LOGONSERVER=\\SULEDC01
NUMBER_OF_PROCESSORS=2
OS=Windows_NT
Path=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Symantec.cloud\PlatformAgent\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 79 Stepping 1, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=4f01
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\PowerShell\Modules\
PUBLIC=C:\Users\Public
SESSIONNAME=RDP-Tcp#18
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\ADMINI~1\AppData\Local\Temp\2
TMP=C:\Users\ADMINI~1\AppData\Local\Temp\2
USERDNSDOMAIN=SULEIMAN.LOCAL
USERDOMAIN=SULEIMAN
USERDOMAIN_ROAMINGPROFILE=SULEIMAN
USERNAME=Administrator
USERPROFILE=C:\Users\Administrator
windir=C:\Windows

C:\Users\Administrator>_
```

</details>

None of these use the environment variable `%SystemDisk%` , only `%SystemDrive%` , which in both cases redirect to `C:` which I expect is default for Windows Server Standard.

Very well. I will go ahead and create a PR to have the incorrect term corrected, based on both our findings. Thanks.

**Comment by illfated** [comment]
There you go. PR #4972 is now ready for review. Luckily, I found a handful of other issue details to correct there as well, as noted in my main PR comment.
