### ISSUE TITLE
80 and/or 443?

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/windowsserverdocs#3951]
Which one of these two quotes is correct? Is only 443 required, or both 80 and 443?

"To obtain updates from Microsoft Update, the WSUS server uses port 443 for HTTPS protocol."
"Although the connection between Microsoft Update and WSUS requires ports 80 and 443 to be open, you can configure multiple WSUS servers to synchronize with a custom port."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85eb6a21-2659-019a-71ab-66f2e3a7f474
* Version Independent ID: ee2ab576-3c19-15a5-8c41-29a00275614b
* Content: [Step 2 - Configure WSUS](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/deploy/2-configure-wsus#211-connection-from-the-wsus-server-to-the-internet)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/deploy/2-configure-wsus.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/deploy/2-configure-wsus.md)
* Product: **windows-server**
* Technology: **manage-wsus**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by dknappettmsft** [comment]
Thanks for the feedback. This has been clarified that it's both port 80 and 443. The change should be visible later today.

#please-close
