### ISSUE TITLE
Clean up server metadata by using a script

### ISSUE THREAD

**Issue by VinodSP1980** [MicrosoftDocs/windowsserverdocs#3953]
Clean up server metadata by using a script. I donot see any script mentioned in this article. Please let me know

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb8953da-5964-7dde-4496-90c1e3b7254f
* Version Independent ID: c2988ec5-9744-2755-679e-0b03c3c96776
* Content: [Clean up AD DS server metadata](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/ad-ds-metadata-cleanup#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/ad-ds-metadata-cleanup.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/ad-ds-metadata-cleanup.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by dknappettmsft** [comment]
Thanks for the feedback. I have corrected this and the change should be visible later today.

#please-close
