### ISSUE TITLE
WVD client in Windows 7 is not working

### ISSUE THREAD

**Issue by agassijoelbrio** [MicrosoftDocs/windowsserverdocs#3955]
Hi, we have 5-6 users using WVD client in Windows 7 SP1. After updating the client, users are not able to login to WVD. They are getting this error: remote desktop cannot connect to the remote computer.  with web URL we are able to log in. Is there any bug in the new update?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ab98fc-fea2-a11a-e5ca-de1430211d97
* Version Independent ID: 4d9943c3-fef7-ca86-bd03-1241a04b8135
* Content: [Get started with the Windows Desktop client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Mohammedaill** [comment]
201808230653294

**Comment by Mohammedaill** [comment]
> Hi, we have 5-6 users using WVD client in Windows 7 SP1. After updating the client, users are not able to login to WVD. They are getting this error: remote desktop cannot connect to the remote computer.  with web URL we are able to log in. Is there any bug in the new update?
> 
> ---
> #### Document Details
> 
> ⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*
> 
> * ID: 09ab98fc-fea2-a11a-e5ca-de1430211d97
> * Version Independent ID: 4d9943c3-fef7-ca86-bd03-1241a04b8135
> * Content: [Get started with the Windows Desktop client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop)
> * Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md)
> * Product: **windows-server**
> * Technology: **remote-desktop-services**
> * GitHub Login: @Heidilohr
> * Microsoft Alias: **helohr**

**Comment by panovattack** [comment]
Same issue after updating client on Win 7 SP1

**Comment by illfated** [comment]
Disclaimer: I am not affiliated with Microsoft or Microsoft Docs here on GitHub.

I recommend asking in forums, like MSDN TechNet, the Microsoft Community (https://answers.microsoft.com) or Microsoft support. You can also try getting in touch with the developers via the Feedback Hub.

This repository is intended for documentation reporting, improvement and documentation issues. The Microsoft ServerDocs team does not have enough bandwidth to provide technical support.

Unless you want to provide an improvement to this document page, report a factual error or otherwise argument for documentation changes, I would advise closing this ticket.

**Comment by dknappettmsft** [comment]
As mentioned above, the best place for help like this is Microsoft Support. I'll go ahead and close this.

#please-close
