### ISSUE TITLE
RDMA Teaming warning out of date

### ISSUE THREAD

**Issue by mmmiller60** [MicrosoftDocs/windowsserverdocs#3959]
The warning about RDMA not supported with NIC teaming is now incorrect.  SET NIC teaming does support RDMA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85ab8371-7782-ad6f-b564-5fd93b3b879a
* Version Independent ID: 5d91cde1-786d-6c7b-f8c3-9667f9df84d7
* Content: [Improve performance of a file server with SMB Direct](https://docs.microsoft.com/en-us/windows-server/storage/file-server/smb-direct)
* Content Source: [WindowsServerDocs/storage/file-server/smb-direct.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/smb-direct.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Would you mind quoting the section you are referring to (from the page https://docs.microsoft.com/en-us/windows-server/storage/file-server/smb-direct)?

**Comment by mmmiller60** [comment]
Note

You should not team RDMA-capable network adapters if you intend to use the RDMA capability of the network adapters. When teamed, the network adapters will not support RDMA



SET or switch embedded teaming, does support RDMA



Thanks
Sam



-------- Original message --------

**Comment by dknappettmsft** [comment]
Thanks for the feedback. I have updated the article, and the changes should be visible later today.

#please-close
