### ISSUE TITLE
What about SSL offloading?

### ISSUE THREAD

**Issue by sasanmcp** [MicrosoftDocs/windowsserverdocs#3961]
I know RDGW has SSL Bridging you can use with load balancers to do SSL offloading; but what is the proper way to do SSL Bridging with Web Access? I tried simply unchecking "require SSL" settings in IIS /RDWeb along with /Feed /Feedlogon /Page sub-apps, no luck.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ad7cf8-46bf-33b9-5297-f4475a4b7a1d
* Version Independent ID: 63da3e0d-f6ef-c3ff-ca66-f0e22ae51b43
* Content: [Add high availability to the RD Web and Gateway web front](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-rdweb-gateway-ha)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-rdweb-gateway-ha.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-rdweb-gateway-ha.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
Hi @sasanmcp. GitHub issues for this repo are for reporting problems with our documentation.  Please open a support ticket or post your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html).
