### ISSUE TITLE
date and time formatting?

### ISSUE THREAD

**Issue by Almenon** [MicrosoftDocs/windowsserverdocs#3966]
It would be nice if this page mentioned that you can do date and time formatting.

https://serverfault.com/questions/16706/current-date-in-the-file-name

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff097c0e-ea9f-9d7c-7900-d8c0be602d5d
* Version Independent ID: 8b17895a-ddd8-1737-9e7d-8deaa69d5b0f
* Content: [copy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/copy#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/copy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/copy.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Almenon** [comment]
Actually guess that's kinda obvious if you have experience with windows CMD and not really directly related to COPY.
Unfortunately I can't delete my own comment.... >_<

**Comment by illfated** [comment]
If you are certain that this issue is resolved (or not an issue after all), we can ask for it to be closed by the MS Docs team maintainers.
