### ISSUE TITLE
OpenSSH installation

### ISSUE THREAD

**Issue by DavidA2014** [MicrosoftDocs/windowsserverdocs#3970]
These instructions entail manual installation of the OpenSSHUtils module (using Add-WindowsCapability), but these instructions don't work anymore. I guess that the correct way to install OpenSSH now is through Optional Features. So these instructions should reflect that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Installation of OpenSSH For Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* GitHub Login: @maertendMSFT

**Comment by szeestraten-ntnu** [comment]
Both OpenSSH client and server seem to have been removed from Windows Server 2016. It is also not available in Optional Features. How do you install in on Server 2016 now?

**Comment by illfated** [comment]
```powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\WINDOWS\system32> Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'


Name  : OpenSSH.Client~~~~0.0.1.0
State : NotPresent

Name  : OpenSSH.Server~~~~0.0.1.0
State : NotPresent


PS C:\WINDOWS\system32> # Install the OpenSSH Client
PS C:\WINDOWS\system32> Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0


Path          :
Online        : True
RestartNeeded : False


PS C:\WINDOWS\system32> # Install the OpenSSH Server
PS C:\WINDOWS\system32> Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0


Path          :
Online        : True
RestartNeeded : False


PS C:\WINDOWS\system32> # Install the OpenSSH Server
PS C:\WINDOWS\system32> Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0


Path          :
Online        : True
RestartNeeded : False



PS C:\WINDOWS\system32> Start-Service sshd
PS C:\WINDOWS\system32> # OPTIONAL but recommended:
PS C:\WINDOWS\system32> Set-Service -Name sshd -StartupType 'Automatic'
PS C:\WINDOWS\system32> # Confirm the Firewall rule is configured. It should be created automatically by setup.
PS C:\WINDOWS\system32> Get-NetFirewallRule -Name *ssh*


Name                  : OpenSSH-Server-In-TCP
DisplayName           : OpenSSH SSH Server (sshd)
Description           : Inbound rule for OpenSSH SSH Server (sshd)
DisplayGroup          : OpenSSH Server
Group                 : OpenSSH Server
Enabled               : True
Profile               : Any
Platform              : {}
Direction             : Inbound
Action                : Allow
EdgeTraversalPolicy   : Block
LooseSourceMapping    : False
LocalOnlyMapping      : False
Owner                 :
PrimaryStatus         : OK
Status                : The rule was parsed successfully from the store. (65536)
EnforcementStatus     : NotApplicable
PolicyStoreSource     : PersistentStore
PolicyStoreSourceType : Local


PS C:\WINDOWS\system32> # There should be a firewall rule named "OpenSSH-Server-In-TCP", which should be enabled
PS C:\WINDOWS\system32> # If the firewall does not exist, create one
PS C:\WINDOWS\system32> New-NetFirewallRule -Name sshd -DisplayName 'OpenSSH Server (sshd)' -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22


Name                  : sshd
DisplayName           : OpenSSH Server (sshd)
Description           :
DisplayGroup          :
Group                 :
Enabled               : True
Profile               : Any
Platform              : {}
Direction             : Inbound
Action                : Allow
EdgeTraversalPolicy   : Block
LooseSourceMapping    : False
LocalOnlyMapping      : False
Owner                 :
PrimaryStatus         : OK
Status                : The rule was parsed successfully from the store. (65536)
EnforcementStatus     : NotApplicable
PolicyStoreSource     : PersistentStore
PolicyStoreSourceType : Local



PS C:\WINDOWS\system32> Ssh illfated@VPCSE2N1E
The authenticity of host 'vpcse2n1e (fe80::c97c:af76:7a45:f78b%18)' can't be established.

ECDSA key fingerprint is SHA256:YFo7UR/MvjSaY7JFXeOZrnX71y9gceX7F9wUZwnpiBw.
Are you sure you want to continue connecting (yes/no)? _

Warning: Permanently added 'vpcse2n1e,fe80::c97c:af76:7a45:f78b%18' (ECDSA) to the list of known hosts.
illfated@vpcse2n1e's password: _

Microsoft Windows [Version 10.0.18363.752]
(c) 2019 Microsoft Corporation. All rights reserved.

illfated@VPCSE2N1E C:\Users\illfated>_
```

**Comment by illfated** [comment]
Please note that I had to close and reopen my PowerShell window at least once during the testing. I did not make a note of exactly when and where in the log above, but it could have something to do with a pending Windows Update.

**Comment by Djago** [comment]
I can install the server with

Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0

But I can't start the service:

Start-Service sshd
gives an error telling that there's no sshd service. But I looked up the services.msc and I found a service called sshd-agent. Is this what I must start?:
Start-Service ssh-agent
If I try to start it this way I get another error, telling me that the service can't be started. So I went again to services.msc and had to change Startup type from Disabled to Automatic, and start the service from there. I suppose this should be taken care with the line:

Set-Service -Name sshd -StartupType 'Automatic'

But again, sshd is nowhere to be found.

**Comment by AK611** [comment]
how do i find the name of my server?

**Comment by illfated** [comment]
As long as you are on the local machine you want to connect to (which I used in my example), you can use `%USERNAME%@%USERDOMAIN%` - but you may want to look up your credentials on the remote machine if you don't know all the details for a remote SSH server computer. This may depend on how you connect to your remote computer and how the Windows username looks when connecting via SMB or regular Windows connections.

**Comment by illfated** [comment]
@konstruktoid : Thank you for responding to all of my previous "pings" here on GitHub. When I look at the open tickets for this particular page, I feel torn between thinking that the page needs more information about the installation procedure, although I managed to do it on my own (using Windows 10 Home edition as my testing environment). On the other hand, I find it somewhat difficult to point out which tickets are asking simple support questions (which this repository is not meant for), so it would be nice to have a second opinion with feedback on which tickets don't belong here. Do you think you could have a look into those tickets and see which ones are easy for you to point out as non-improvement tickets, in contrast to those that indicate a need for improvement?

**Comment by konstruktoid** [comment]
@illfated: Hi and no worries, I try to help out when I can.
I'll have a look at the referenced issues.

**Comment by illfated** [comment]
See Pull Request #4788 for a suggested improvement to this issue.
(The PR will close this issue ticket when it gets merged.)

**Comment by illfated** [comment]
#please-close
