### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by cjsimcoxjr** [MicrosoftDocs/windowsserverdocs#3971]
The Windows Security Baselines link under the PAW Phased Implementation section is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1338ba44-301c-db33-d336-80dd50a77960
* Version Independent ID: 55abfb6d-3f63-9dce-1b70-36c6265fc37b
* Content: [Why Privileged Access Workstations can help secure your organization](https://docs.microsoft.com/en-us/windows-server/identity/securing-privileged-access/privileged-access-workstations#paw-phased-implementation)
* Content Source: [WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md)
* Product: **windows-server**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by illfated** [comment]
Current incorrect link (aka.ms redirection): https://aka.ms/win10baselines (shown as [**Windows 10 Security Baselines**](https://aka.ms/win10baselines))
(that link ends up on the page https://www.microsoft.com/?ref=aka )

The actual page the aka.ms link should redirect to: https://docs.microsoft.com/windows/security/threat-protection/windows-security-baselines

Not sure yet if it will be acceptable to replace the aka.ms link with the direct link.

**Comment by illfated** [comment]
Resolved in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/b813b5c92b6ddb6b55a66bbf568d5f7fca80d148 (direct file link: https://github.com/MicrosoftDocs/windowsserverdocs/commit/b813b5c92b6ddb6b55a66bbf568d5f7fca80d148#diff-117510d86bb1a3ec98751d0849660942cc7230c67acf24eb2760a6bc86114b26) (no Pull Request linked in the commit page).

See also the complete file history (list of commits): https://github.com/MicrosoftDocs/windowsserverdocs/commits/master/WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md

**Comment by illfated** [comment]
#please-close
