### ISSUE TITLE
Many errors/issues with icacls documentation

### ISSUE THREAD

**Issue by chrisgraham** [MicrosoftDocs/windowsserverdocs#3972]
1) Misspelling: "enheritance"

2) "Removes all inherited ACEs" should be "Disables inheritance (removes all inherited ACEs)" for clarity.

3) I think "read control" (and "write control") means "read permissions" - it would be good to make sure everything in the Windows UI is listed the same in this document. If the Windows UI is using more-friendly names rather than official ones, include both in this document.

4) "Specifies the file for which to display DACLs." --> "Specifies the file/directory for which to display/modify DACLs." [the given first form of syntax is for both files and directories not just files & it's for displaying and modifying, not just displaying]

5) "Specifies the directory for which to display DACLs." --> "Specifies the directory for which to perform higher-level DACL operations".

6) Ideally you'd put hyperlinks on the first use of each item of jargon (DACL, ACE, DACL, ACL, SID), as the document is very jargon heavy.

7) RX described as "read and execute access" is confusing, because this is referred to as "list folder contents" in the Windows UI, and the Windows UI has a separate "read and execute access" setting which acts as UI magic for setting "list folder contents" & "read". I think it is meant to say "list folder contents", because I did a test where I set "list folder contents" in the Windows UI and not "read" and iacls showed that as RX.

8) The "inheritance rights" part is confusing. I don't think this has any representation in the Windows UI. This page seems to document it much better :+1: https://superuser.com/questions/322423/explain-the-output-of-icacls-exe-line-by-line-item-by-item
Clarify this.

9) Further from this, there doesn't seem to be documentation here for "(I)", meaning "inherits from parent". This is the kind of inheritance the reader is going to be familiar with and needs to see in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5906879b-e678-e3da-c404-07a437b42cc2
* Version Independent ID: 0779c597-9e20-38e0-3ae7-40126f5c2bcb
* Content: [icacls](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/icacls#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/icacls.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/icacls.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by dknappettmsft** [comment]
Thanks for the feedback. To address each of these:

> Misspelling: "enheritance"

This is no longer present.

> "Removes all inherited ACEs" should be "Disables inheritance (removes all inherited ACEs)" for clarity.

Thanks, I have clarified this.

> I think "read control" (and "write control") means "read permissions" - it would be good to make sure everything in the Windows UI is listed the same in this document. If the Windows UI is using more-friendly names rather than official ones, include both in this document.

I have updated these where they have a single corresponding value.

> "Specifies the file for which to display DACLs." --> "Specifies the file/directory for which to display/modify DACLs." [the given first form of syntax is for both files and directories not just files & it's for displaying and modifying, not just displaying]

> "Specifies the directory for which to display DACLs." --> "Specifies the directory for which to perform higher-level DACL operations".

I have updated these to include 'modify' too, but I haven't changed the rest of the text. An object here can only be a file or a directory, so I've left them separated.

> Ideally you'd put hyperlinks on the first use of each item of jargon (DACL, ACE, DACL, ACL, SID), as the document is very jargon heavy.

We don't have a hyperlink for each of these terms, but each one is written out in its full form first before being the acronym is used.

> RX described as "read and execute access" is confusing, because this is referred to as "list folder contents" in the Windows UI, and the Windows UI has a separate "read and execute access" setting which acts as UI magic for setting "list folder contents" & "read". I think it is meant to say "list folder contents", because I did a test where I set "list folder contents" in the Windows UI and not "read" and iacls showed that as RX.

"Read and execute" is how it is defined in the Windows UI.  It's a basic permission reference rather than the five advanced permissions to which this correlates.  RX is for this basic permission, so to make this clearer I have changed "A sequence of simple rights:" to "A sequence of simple rights (basic permissions):" to make this clearer.

> The "inheritance rights" part is confusing. I don't think this has any representation in the Windows UI. This page seems to document it much better 👍 https://superuser.com/questions/322423/explain-the-output-of-icacls-exe-line-by-line-item-by-item
Clarify this.

> Further from this, there doesn't seem to be documentation here for "(I)", meaning "inherits from parent". This is the kind of inheritance the reader is going to be familiar with and needs to see in this document.

I have clarified these.

#please-close
