### ISSUE TITLE
More specific supported on version xx info desired

### ISSUE THREAD

**Issue by cking22001** [MicrosoftDocs/windowsserverdocs#3979]
I am unclear if this applies to 2016 and above. I cannot find specific information if this might be supported on 2012R2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58c9a735-22a3-4123-e386-407f49a19bbd
* Version Independent ID: e1704867-4a1c-8446-52da-ecd07ddc35d7
* Content: [DHCP Subnet Selection Options](https://docs.microsoft.com/en-us/windows-server/networking/technologies/dhcp/dhcp-subnet-options#feedback)
* Content Source: [WindowsServerDocs/networking/technologies/dhcp/dhcp-subnet-options.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/dhcp/dhcp-subnet-options.md)
* Product: **windows-server**
* Technology: **networking-dhcp**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@steved0x I am no longer the author to this article. please assign it to someone on the Windows Server docs team.
