### ISSUE TITLE
Wrong values

### ISSUE THREAD

**Issue by MiguelCaldasMS** [MicrosoftDocs/windowsserverdocs#3981]
In the "Windows Server with SA Requirements Reference Table", the "VM Core Density"=20 column has multiple wrong values. Also the Excel Spreadsheet linked to in "Azure Hybrid Benefit WS SA Count Tool" calculates the wrong values. The calc formula should be MAX(CEILING("VMs"/2, 1), CEILING("Cores"/16, 1)).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90e335dd-0bc5-a7e3-650b-e3dd1823176b
* Version Independent ID: 18f34ef3-ff61-0473-a64b-ac5a64dbe1d7
* Content: [Azure Hybrid Benefit for Windows Server](https://docs.microsoft.com/en-us/windows-server/get-started/azure-hybrid-benefit#feedback)
* Content Source: [WindowsServerDocs/get-started/azure-hybrid-benefit.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/azure-hybrid-benefit.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by greg-lindsay** [comment]
This needs to be assigned to the topic owner, which is not me. I don't seem to have perms to do the assignment.

**Comment by illfated** [comment]
( also ref. issue ticket #488 from the same page, needs an update )

**Comment by dknappettmsft** [comment]
Thanks for the feedback. I have reworked this article and removed the table. The spreadsheet has also been retired in favor of the [Azure Hybrid Benefit Savings Calculator](https://azure.microsoft.com/en-gb/pricing/hybrid-benefit/#calculator). The changes should be visible later today.

#please-close
