### ISSUE TITLE
HSTS security advice dangerously incorrect

### ISSUE THREAD

**Issue by mikenor** [MicrosoftDocs/windowsserverdocs#3982]
The section on HSTS contains dangerously wrong advice and shows a fundamental serious lack of understanding of how protocol downgrade attacks work and how HSTS prevents them.

In a protocol downgrade attack, the HTTP listener is the *man-in-the-middle's* HTTP listener, not an HTTP listener on the ADFS server. Thus, the absence of an HTTP listener on the ADFS server does NOT in any way provide the sort of mitigation that HSTS does and this document is dangerously incorrect in stating otherwise.

The whole point of HSTS is to prevent the client from connecting to a MITM's HTTP listener. The lack of an HTTP listener on the ADFS server does NOT accomplish that because there could still easily be a MITM between the client and the ADFS server, regardless of what protocols the ADFS server listens for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7958465-7224-0c4b-8771-eba606511922
* Version Independent ID: ff44e422-e4b1-134a-47bd-88d9abc843e3
* Content: [AD FS FAQ](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-faq)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/AD-FS-FAQ.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/AD-FS-FAQ.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 3978 -b #assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
