### ISSUE TITLE
icacls X:\FULL_PATH_TO_FOLDER /grant Administrators:F

### ISSUE THREAD

**Issue by courtens** [MicrosoftDocs/windowsserverdocs#3985]
What would this do?
Command found on this page: https://thegeekpage.com/solved-failed-to-enumerate-objects-in-the-container-windows-10-error/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5906879b-e678-e3da-c404-07a437b42cc2
* Version Independent ID: 0779c597-9e20-38e0-3ae7-40126f5c2bcb
* Content: [icacls](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/icacls#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/icacls.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/icacls.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by courtens** [comment]
just found the answer here: https://www.winhelponline.com/blog/take-ownership-of-file-or-folder/

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @courtens,

Looking at the documentation, the `/grant` switch with the `f` perm performs the following: 

> Grants specified user access rights. Permissions replace previously granted explicit permissions.
Not adding the :r, means that permissions are added to any previously granted explicit permissions.

> The `<perm>` option is a permission mask that can be specified in one of the following forms:
> **F** - Full access

It is described similarly per the article you have referenced. We're glad you were able to find an answer so quickly. If there are no further concerns, we will be closing this thread. We do wish you a most pleasant day!
#please-close
