### ISSUE TITLE
/b option not documented

### ISSUE THREAD

**Issue by druske** [MicrosoftDocs/windowsserverdocs#3990]
The /b (for bindings?) option is presented in an example, but is not otherwise documented on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1a5d57a-9b6d-97b5-68ef-596ea616ab3f
* Version Independent ID: 74c36f72-cfee-5fbb-e410-fb4cb7449cdc
* Content: [netcfg](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/netcfg#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/netcfg.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/netcfg.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Fair enough, there is also a typo and slightly bad choice of word connected to that typo as well. The page should have had more UNIX-like descriptions of the parameters, including mnemonic phrases to aid in associating the parameters with their description. I will open a PR to make some adjustments and suggest a row in the table for the /b paramater.

**Comment by illfated** [comment]
Please note that running the `netcfg` command on Windows 10 version 1909 will list more options in the examples than those present on this page, as well as using a dash (`-`) character instead of the slash (`/`) as the indicating character for that parameter.

<details>

```
Microsoft Windows [Version 10.0.18363.693]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>netcfg /?
netcfg [-v] [-winpe] [-l <full-path-to-component-INF>] -c <p|s|c>
       -i <comp-id>

    -winpe installs TCP/IP, NetBIOS and Microsoft Client for Windows
           preinstallation environment
    -l     provides the location of INF
    -c     provides the class of the component to be installed (p == Protocol,
           s == Service, c == Client)
    -i     provides the component ID

    The arguments must be passed in the order shown.

    Examples:

    netcfg -l c:\oemdir\myprot.inf -c p -i myprot

        Installs protocol 'myprot' using c:\oemdir\myprot.inf

    netcfg -c s -i MS_Server

        Installs service 'MS_Server'

OR

netcfg [-v] -winpe

    Example:

    netcfg -v -winpe

        Installs TCP/IP, NetBIOS, and Microsoft Client for Windows
        preinstallation environment

OR

netcfg [-v] -q <comp-id>

    Example:

    netcfg -q MS_IPX

        Displays if component 'MS_IPX' is installed

OR

netcfg [-v] -u <comp-id>

    Example:

    netcfg -u MS_IPX

        Uninstalls component 'MS_IPX'

OR

netcfg [-v] -s <a|n>

    -s  provides the type of components to show (a == adapters,
        n == net components)

    Example:

    netcfg -s n

        Shows all installed net components

OR

netcfg [-v] -b <comp-id>

    Example:

    netcfg -b ms_tcpip

        Shows binding paths containing 'MS_TCPIP'

OR

netcfg [-v] -m

    Example:

    netcfg -m

        Outputs the binding map to NetworkBindingMap.txt in the current directory.
        -v will also display the binding map to the console.

OR

netcfg -d

    Example:

    netcfg -d

        Performs a cleanup on all networking devices.
                This will require a reboot.

OR

netcfg -x

    Example:

    netcfg -x

        Performs a cleanup on networking devices, skipping those without physical
        object names.
                This will require a reboot.

General Notes:
  -v    Run in verbose (detailed) mode
  -?    Displays this help information


C:\WINDOWS\system32>_
```

</details>

Also, I don't know if this is indicative of this command being updated closer to what will be available on Windows Server 2019 (I don't have access to WS 2019 yet).

**Comment by illfated** [comment]
(Ref. #3997 )
