### ISSUE TITLE
Upgrade path at the top of this article doesn't make sense

### ISSUE THREAD

**Issue by bkell904** [MicrosoftDocs/windowsserverdocs#3995]
The "applies to" and supported upgrade path is either incorrect or so ambiguous to make the article suspect in it's accuracy. 
If the article applies to: Windows Server (Semi-Annual Channel), Windows Server 2019, Windows Server 2016. Then why does't the supported OS upgrades role include all applicable OS's.  It's almost as if the following statement should read "Upgrades to Windows Server 2019 are supported only from Windows Server 2012 R2 and Windows Server 2016.
 NOT

Upgrades to Windows Server 2016 are supported only from Windows Server 2012 R2 and Windows Server 2016.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16d840ef-5cbe-ac40-e060-0f12df515ad1
* Version Independent ID: ec32cdb6-ecc7-cf6d-b487-9443b2260c4d
* Content: [Upgrading your Remote Desktop Services deployments to Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/upgrade-to-rds#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/upgrade-to-rds.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/upgrade-to-rds.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @spatnaik
* Microsoft Alias: **spatnaik**

**Comment by illfated** [comment]
Fair point, it looks dubious to suggest upgrading from Windows Server 2016 to Windows Server 2016.

**Comment by illfated** [comment]
Searching the web (via Bing), it looks like the sentence is missing a version description detail at the end, so maybe it should look similar to the same line in **Upgrading your Remote Desktop Session Host to Windows Server 2016** (https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/upgrade-to-rdsh):
> ## Supported OS upgrades with RDS role installed
> Upgrades to Windows Server 2016 are supported only from Windows Server 2012 R2 and Windows Server 2016 TP5.

**Comment by jspcstl** [comment]
https://github.com/MicrosoftDocs/windowsserverdocs/issues/4153

**Comment by spatnaik** [comment]
I've moved teams. Someone on Remote Desktop team should look in to this. Contact: KamV (alias)

**Comment by IngridAtMicrosoft** [comment]
#assign:dknappettmsft

**Comment by dknappettmsft** [comment]
I've pushed a change to correct the 'applies to' line as well as 'Upgrades to Windows Server 2016 are supported only from Windows Server 2012 R2' for now.  These should be visible later today.

I appreciate this needs substantial rework to update the article (and companion articles) for later Windows Server versions, to which I cannot commit a timeframe, and will be tracked internally.

#please-close
