### ISSUE TITLE
verb case tweak

### ISSUE THREAD

**Issue by EricUniqueUsername** [MicrosoftDocs/windowsserverdocs#3996]
Hello-
First, thanks for this resource.
In several of the above parameter descriptions, if I understand their intent correctly, the construction "Specifies that xxx is/are used..." should be changed to "Specifies that xxx be used..." (imperative rather than indicative case).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecb04dc8-7ab3-71e9-9773-41c080b40109
* Version Independent ID: 435a4517-0c3f-6af6-d75d-faed7282c86a
* Content: [ping](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/ping#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/ping.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/ping.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
I sort of see what you mean. I presume you are referring to the Description field in the Parameters table (https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/ping#parameters):

### Parameters

|Parameter|Description|
|-------|--------|
|/t|Specifies that ping continue sending echo Request messages to the destination until interrupted. To interrupt and display statistics, press CTRL+break. To interrupt and quit **ping**, press CTRL+C.|
|/a|Specifies that reverse name resolution is performed on the destination IP address. If this is successful, ping displays the corresponding host name.|
|/n \<Count\>|Specifies the number of echo Request messages sent. The default is 4.|
|/l \<Size\>|Specifies the length, in bytes, of the Data field in the echo Request messages sent. The default is 32. The maximum Size is 65,527.|
|/f|Specifies that echo Request messages are sent with the Do not Fragment flag in the IP header set to 1 (available on IPv4 only). The echo Request message cannot be fragmented by routers in the path to the destination. This parameter is useful for troubleshooting path Maximum Transmission Unit (PMTU) problems.|
|/I \<TTL\>|Specifies the value of the TTL field in the IP header for echo Request messages sent. The default is the default TTL value for the host. The maximum *TTL* is 255.|
|/v \<TOS\>|Specifies the value of the type of Service (TOS) field in the IP header for echo Request messages sent (available on IPv4 only). The default is 0. *TOS* is specified as a decimal value from 0 through 255.|
|/r \<Count\>|Specifies that the Record Route option in the IP header is used to record the path taken by the echo Request message and corresponding echo Reply message (available on IPv4 only). Each hop in the path uses an entry in the Record Route option. If possible, specify a *Count* that is equal to or greater than the number of hops between the source and destination. The *Count* must be a minimum of 1 and a maximum of 9.|
|/s \<Count\>|Specifies that the Internet timestamp option in the IP header is used to record the time of arrival for the echo Request message and corresponding echo Reply message for each hop. The *Count* must be a minimum of 1 and a maximum of 4. This is required for link-local destination addresses.|
|/j \<Hostlist\>|Specifies that the echo Request messages use the Loose Source Route option in the IP header with the set of intermediate destinations specified in *Hostlist* (available on IPv4 only). With loose source routing, successive intermediate destinations can be separated by one or multiple routers. The maximum number of addresses or names in the host list is 9. The host list is a series of IP addresses (in dotted decimal notation) separated by spaces.|
|/k \<Hostlist\>|Specifies that the echo Request messages use the Strict Source Route option in the IP header with the set of intermediate destinations specified in *Hostlist* (available on IPv4 only). With strict source routing, the next intermediate destination must be directly reachable (it must be a neighbor on an interface of the router). The maximum number of addresses or names in the host list is 9. The host list is a series of IP addresses (in dotted decimal notation) separated by spaces.|
|/w \<timeout\>|Specifies the amount of time, in milliseconds, to wait for the echo Reply message that corresponds to a given echo Request message to be received. If the echo Reply message is not received within the time-out, the "Request timed out" error message is displayed. The default time-out is 4000 (4 seconds).|
|/R|Specifies that the round-trip path is traced (available on IPv6 only).|
|/S \<Srcaddr\>|Specifies the source address to use (available on IPv6 only).|
|/4|Specifies that IPv4 is used to ping. This parameter is not required to identify the target host with an IPv4 address. It is only required to identify the target host by name.|
|/6|Specifies that IPv6 is used to ping. This parameter is not required to identify the target host with an IPv6 address. It is only required to identify the target host by name.|
|\<TargetName\>|Specifies the host name or IP address of the destination.|
|/?|Displays help at the command prompt.|

****

Would you like to edit the text the way you think it should be presented and post a comment containing this table with your version of the text, so we others can see the full effect of the changes you have in mind? If yes, here is a link to the raw GitHub source text for the page: https://raw.githubusercontent.com/MicrosoftDocs/windowsserverdocs/master/WindowsServerDocs/administration/windows-commands/ping.md

**Comment by EricUniqueUsername** [comment]
Hi Trond-
Yes, I'd be happy to do that. I'll take care of it this evening, maybe
after midnight UT.
(Also testing here to see if it works to reply directly to the notification
e-mail.)
Thanks,
Eric

**Comment by EricUniqueUsername** [comment]
Here is my proposed version as a text file
[parameter_descriptions_proposed.txt](https://github.com/MicrosoftDocs/windowsserverdocs/files/4304344/parameter_descriptions_proposed.txt)
, changing "is" and "are" to "be" where called for.
In my initial post, I referred to this being the imperative, but I now realized it should be called the "[mandative](https://english.lingolia.com/en/grammar/verbs/subjunctive)" subjunctive.

**Comment by EricUniqueUsername** [comment]
...in case it's better to paste than attach:

### Parameters

|Parameter|Description|
|-------|--------|
|/t|Specifies that ping continue sending echo Request messages to the destination until interrupted. To interrupt and display statistics, press CTRL+break. To interrupt and quit **ping**, press CTRL+C.|
|/a|Specifies that reverse name resolution be performed on the destination IP address. If this is successful, ping displays the corresponding host name.|
|/n \<Count\>|Specifies the number of echo Request messages sent. The default is 4.|
|/l \<Size\>|Specifies the length, in bytes, of the Data field in the echo Request messages sent. The default is 32. The maximum Size is 65,527.|
|/f|Specifies that echo Request messages be sent with the Do not Fragment flag in the IP header set to 1 (available on IPv4 only). The echo Request message cannot be fragmented by routers in the path to the destination. This parameter is useful for troubleshooting path Maximum Transmission Unit (PMTU) problems.|
|/I \<TTL\>|Specifies the value of the TTL field in the IP header for echo Request messages sent. The default is the default TTL value for the host. The maximum *TTL* is 255.|
|/v \<TOS\>|Specifies the value of the type of Service (TOS) field in the IP header for echo Request messages sent (available on IPv4 only). The default is 0. *TOS* is specified as a decimal value from 0 through 255.|
|/r \<Count\>|Specifies that the Record Route option in the IP header be used to record the path taken by the echo Request message and corresponding echo Reply message (available on IPv4 only). Each hop in the path uses an entry in the Record Route option. If possible, specify a *Count* that is equal to or greater than the number of hops between the source and destination. The *Count* must be a minimum of 1 and a maximum of 9.|
|/s \<Count\>|Specifies that the Internet timestamp option in the IP header be used to record the time of arrival for the echo Request message and corresponding echo Reply message for each hop. The *Count* must be a minimum of 1 and a maximum of 4. This is required for link-local destination addresses.|
|/j \<Hostlist\>|Specifies that the echo Request messages use the Loose Source Route option in the IP header with the set of intermediate destinations specified in *Hostlist* (available on IPv4 only). With loose source routing, successive intermediate destinations can be separated by one or multiple routers. The maximum number of addresses or names in the host list is 9. The host list is a series of IP addresses (in dotted decimal notation) separated by spaces.|
|/k \<Hostlist\>|Specifies that the echo Request messages use the Strict Source Route option in the IP header with the set of intermediate destinations specified in *Hostlist* (available on IPv4 only). With strict source routing, the next intermediate destination must be directly reachable (it must be a neighbor on an interface of the router). The maximum number of addresses or names in the host list is 9. The host list is a series of IP addresses (in dotted decimal notation) separated by spaces.|
|/w \<timeout\>|Specifies the amount of time, in milliseconds, to wait for the echo Reply message that corresponds to a given echo Request message to be received. If the echo Reply message is not received within the time-out, the "Request timed out" error message is displayed. The default time-out is 4000 (4 seconds).|
|/R|Specifies that the round-trip path be traced (available on IPv6 only).|
|/S \<Srcaddr\>|Specifies the source address to use (available on IPv6 only).|
|/4|Specifies that IPv4 be used to ping. This parameter is not required to identify the target host with an IPv4 address. It is only required to identify the target host by name.|
|/6|Specifies that IPv6 be used to ping. This parameter is not required to identify the target host with an IPv6 address. It is only required to identify the target host by name.|
|\<TargetName\>|Specifies the host name or IP address of the destination.|
|/?|Displays help at the command prompt.|

**Comment by illfated** [comment]
That is a very good start. I will need a couple of days to set aside enough time to compare & take notes, maybe post a follow-up with my ideas of how those sentences might be phrased.

**Comment by EricUniqueUsername** [comment]
Takk, Trond. Let me know if you'd like any more info.
Eric

**Comment by illfated** [comment]
... and here is another ticket I forgot to follow up due to the COVID-19 crisis development only a week after the discussion above.

I notice that the article itself has changed a bit since then, so I will create a PR based on what I deem to be useful changes in the grammar of the sentences.

**Comment by EricUniqueUsername** [comment]
Ok, let me know if you have any questions.
Eric

**Comment by illfated** [comment]
(This is the content I have edited so far. You will be able to see the diff as soon as I finalize the PR page.)

***

You can also use this command to test both the computer name and the IP address of the computer. If pinging the IP address is successful, but pinging the computer name isn't, you might have a name resolution problem. In this case, make sure the computer name you are specifying can be resolved through the local Hosts file, by using Domain Name System (DNS) queries, or through NetBIOS name resolution techniques.

> [!NOTE]
> This command is available only if the Internet Protocol (TCP/IP) is installed as a component in the properties of a network adapter in Network Connections.

## Syntax

```
ping [/t] [/a] [/n <count>] [/l <size>] [/f] [/I <TTL>] [/v <TOS>] [/r <count>] [/s <count>] [{/j <hostlist> | /k <hostlist>}] [/w <timeout>] [/R] [/S <Srcaddr>] [/4] [/6] <targetname>
```

### Parameters

| Parameter | Description |
|--|--|
| /t | Specifies that ping continues sending echo Request messages to the destination until interrupted. To interrupt and display statistics, press CTRL+ENTER. To interrupt and quit this command, press CTRL+C. |
| /a | Specifies reverse name resolution to be performed on the destination IP address. If this is successful, ping displays the corresponding host name. |
| /n `<count>` | Specifies the number of echo Request messages to be sent. The default is 4. |
| /l `<size>` | Specifies the length, in bytes, of the **Data** field in the echo Request messages to be sent. The default is 32. The maximum size is 65,527. |
| /f | Specifies that echo Request messages are sent with the **Do not Fragment** flag in the IP header set to 1 (available on IPv4 only). The echo Request message can't be fragmented by routers in the path to the destination. This parameter is useful for troubleshooting path Maximum Transmission Unit (PMTU) problems. |
| /I `<TTL>` | Specifies the value of the Time To Live (TTL) field in the IP header for echo Request messages sent. The default is the default TTL value for the host. The maximum *TTL* is 255. |
| /v `<TOS>` | Specifies the value of the Type Of Service (TOS) field in the IP header for echo Request messages sent (available on IPv4 only). The default is 0. *TOS* is specified as a decimal value from 0 through 255. |
| /r `<count>` | Specifies that the **Record Route** option in the IP header is used to record the path taken by the echo Request message and corresponding echo Reply message (available on IPv4 only). Each hop in the path uses an entry in the **Record Route** option. If possible, specify a *count* equal to or greater than the number of hops between the source and destination. The *count* must be a minimum of 1 and a maximum of 9. |
| /s `<count>` | Specifies that the **Internet timestamp** option in the IP header is used to record the time of arrival for the echo Request message and corresponding echo Reply message for each hop. The *count* must be a minimum of 1 and a maximum of 4. This is required for link-local destination addresses. |
| /j `<hostlist>` | Specifies that the echo Request message uses the **Loose Source Route** option in the IP header with the set of intermediate destinations specified in *hostlist* (available on IPv4 only). With loose source routing, successive intermediate destinations can be separated by one or multiple routers. The maximum number of addresses or names in the host list is 9. The host list is a series of IP addresses (in dotted decimal notation) separated by spaces. |
| /k `<hostlist>` | Specifies that the echo Request message uses the **Strict Source Route** option in the IP header with the set of intermediate destinations specified in *hostlist* (available on IPv4 only). With strict source routing, the next intermediate destination must be directly reachable (it must be a neighbor on an interface of the router). The maximum number of addresses or names in the host list is 9. The host list is a series of IP addresses (in dotted decimal notation) separated by spaces. |
| /w `<timeout>` | Specifies the amount of time, in milliseconds, to wait for the echo Reply message corresponding to a given echo Request message to be received. If the echo Reply message is not received within the time-out, the "Request timed out" error message is displayed. The default time-out is 4000 (4 seconds). |
| /R | Specifies that the round-trip path is traced (available on IPv6 only). |
| /S `<Srcaddr>` | Specifies the source address to use (available on IPv6 only). |
| /4 | Specifies IPv4 to be used to ping. This parameter is not required to identify the target host with an IPv4 address. It is only required to identify the target host by name. |
| /6 | Specifies IPv6 to be used to ping. This parameter is not required to identify the target host with an IPv6 address. It is only required to identify the target host by name. |
| `<targetname>` | Specifies the host name or IP address of the destination. |
| /? | Displays help at the command prompt. |

**Comment by EricUniqueUsername** [comment]
Hi Trond-
I'm a bit lost now. I followed your above link "Windows Commands/ping: minor grammar update #4963", then followed a link from there to
https://github.com/MicrosoftDocs/windowsserverdocs/pull/4963/files,
which shows some of the text fixes I suggested with pink shading, and some apparently new, green-shaded text that has what I think are new changes, as well as some of the original errors I suggested fixing (e.g. "continues" instead of "continue"). It also has several instances of "to be" that should read simply "be".
Eric

**Comment by illfated** [comment]
Sure, the deal with pink and green is indeed old (pink/red) and new (green/light green) text.

As I tried to mention before, I have only suggested what I found to be reasonable formulations of the sentences. You are of course free to post comments in the PR if you believe it makes more sense to use a different phrasing. Even though English is not my native language, I speak and write English on a near-native level, as well as reading some English literature in preference to my own language. Proofreading has also figured prominent during my educational years, so I feel I have a reasonable grasp of English grammar.

But indeed, feel free to post improvement suggestions in my PR #4963 .

**Comment by EricUniqueUsername** [comment]
Hi Trond-
I'm not sure if by replying here I'm sending you an e-mail, or adding a
comment to the forum at the page you link, but I wanted to make sure you
got my message. Your English is of course excellent, your grasp of grammar
is well beyond reasonable. But the changes I suggested relate to a problem
that even many native speakers have these days. For example, they will
write "I suggested she gives the child less candy" when they really mean "I
suggested she give the child less candy". The latter is in the mandative
subjunctive, which applies to the changes I suggested in the ping doc. The
former has a different meaning.
Eric

**Comment by illfated** [comment]
Fair enough, your email does end up as a comment on the GitHub issue ticket when replying to the update in your mailbox.

Anyway, I see that you are pointing to the fine detail of semantics and grammar. I know it is especially important to use the right tense and form in documentation, to keep the intended meaning clear, to avoid misinterpretation. I will do my best to follow up on your comments in the PR.
