### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by joshtransient** [MicrosoftDocs/windowsserverdocs#4000]
Link named "Configure a site to use Integrated Windows authentication" under "Publish SharePoint Server" has a URL starting with assetid://; please update

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dbee2ba-d766-93b9-77fa-c727528e35d9
* Version Independent ID: 78b6df02-dc9d-f5b0-15ce-01f3175e3d3c
* Content: [Publishing Applications with SharePoint, Exchange and RDG](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/web-application-proxy/publishing-applications-with-sharepoint,-exchange-and-rdg#feedback)
* Content Source: [WindowsServerDocs/remote/remote-access/web-application-proxy/Publishing-Applications-with-SharePoint,-Exchange-and-RDG.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/web-application-proxy/Publishing-Applications-with-SharePoint,-Exchange-and-RDG.md)
* Product: **windows-server**
* Technology: **web-app-proxy**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Good catch, this is likely similar to issue ticket #2863 (**Broken Links**) and its closing PR #3945 (**AD FS/Deployment: resurrect 2 internal links**) merged in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/a12970c26d5414955b90546fd495c7fd28712264 .

I will open a PR to amend this broken link, presuming it is supposed to point to a different section in the same page (seeing that this was the intended usage in my linked PR & commit).

**Comment by illfated** [comment]
Looks like the link was supposed to point to an external page (notice the page message "We're no longer updating this content regularly. Check the Microsoft Product Lifecycle for information about how this product, service, technology, or API is supported."), which can now be found here:
- https://docs.microsoft.com/en-us/previous-versions/orphan-topics/ws.11/dn308246(v=ws.11)

The page used to be a Technet/MSDN page, which now redirects permanently to the page above. The outdated link used to be this one:
- https://technet.microsoft.com/en-us/library/Dn308246 (now permanently redirected to the page linked above)

**Comment by illfated** [comment]
There you go. Hope you find the PR #4001 interesting to read, maybe even enough to see any possible improvements I might have missed.

**Comment by illfated** [comment]
> (ref. **Hyperlink** #3660)
