### ISSUE TITLE
System Requirements table is unclear

### ISSUE THREAD

**Issue by garywatson-pilbeam** [MicrosoftDocs/windowsserverdocs#4004]
It's not clear whether the columns in the table represent the host version, or the guest version.  At first glance, the columns appear to represent the host version but that's unlikely to be the case, otherwise it suggests that a 2016 host can activate a 2019 guest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac93bb4-09b7-c1ae-255d-744ea719a0a7
* Version Independent ID: ec6ff685-ea93-cb5f-af9b-45ffe0857db1
* Content: [Automatic virtual machine activation](https://docs.microsoft.com/en-us/windows-server/get-started-19/vm-activation-19#feedback)
* Content Source: [WindowsServerDocs/get-started-19/vm-activation-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/vm-activation-19.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by dknappettmsft** [comment]
Thanks for the feedback. This page has had several updates since this was logged and the table seems to be updated and clear now. I'll close this.

#please-close
