### ISSUE TITLE
Incomplete info

### ISSUE THREAD

**Issue by krlinus** [MicrosoftDocs/windowsserverdocs#4006]
Please include the exit codes for this and commands in general
Why doesn't dir /s return a 0 if it finds a file? it is throwing off my script!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8095c8a1-5049-2eb1-2041-6392f2025cfa
* Version Independent ID: 6e63df5e-a455-33c7-22db-36f44121a2c0
* Content: [dir](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/dir#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/dir.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/dir.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @krlinus, 

Thanks again for contacting Microsoft. We value your feedback. 

We're taking in consideration for these exit codes. As for the issue with your script, we understand you're describing a problem with the product itself. To get assistance or support for your product issue, we recommend that you engage with the product community or open a ticket with Microsoft Support. For more information, see [Contact Microsoft Support](https://support.microsoft.com/ContactUs).

We will be closing this thread. Thank you and have a most pleasant day. #please-close
