### ISSUE TITLE
Typo in step 4 in "Create a VM and connect to a VLAN"

### ISSUE THREAD

**Issue by george-guirguis** [MicrosoftDocs/windowsserverdocs#4007]
Under "Create a VM and connect to a VLAN by using NetworkControllerRESTWrappers":
Step 4, Line 8 (counting the blank lines)
Current:
$CurrentFeature = Get-VMSwitchExtensionPortFeature -FeatureId $FeatureId -VMNetworkAdapter $vmNic
Correct:
$CurrentFeature = Get-VMSwitchExtensionPortFeature -FeatureId $FeatureId -VMNetworkAdapter $vmNics

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0dd73bf-1bfd-57dc-117d-fe885daf10ec
* Version Independent ID: 1d5b4ccd-07b5-21c5-937b-eeff00c57449
* Content: [Create a VM and connect to a tenant virtual network or VLAN](https://docs.microsoft.com/en-us/windows-server/networking/sdn/manage/create-a-tenant-vm)
* Content Source: [WindowsServerDocs/networking/sdn/manage/Create-a-Tenant-VM.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/sdn/manage/Create-a-Tenant-VM.md)
* Product: **windows-server**
* Technology: **networking-sdn**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by dknappettmsft** [comment]
Thanks for the feedback. I've made the corrections and the changes should be visible later today.

#please-close
