### ISSUE TITLE
Installing OpenSSH with PowerShell - Does not seems to works

### ISSUE THREAD

**Issue by aurelien-git** [MicrosoftDocs/windowsserverdocs#4009]
Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'
&gt;&gt;
&gt;&gt; # This should return the following output:
&gt;&gt;
&gt;&gt; Name  : OpenSSH.Client~~~~0.0.1.0
&gt;&gt; State : NotPresent
&gt;&gt; Name  : OpenSSH.Server~~~~0.0.1.0
&gt;&gt; State : NotPresent

Name  : OpenSSH.Client~~~~0.0.1.0
State : Installed

Name  : OpenSSH.Server~~~~0.0.1.0
State : NotPresent

Name : The term 'Name' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:5 char:1
+ Name  : OpenSSH.Client~~~~0.0.1.0
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (Name:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

State : The term 'State' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:6 char:1
+ State : NotPresent
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (State:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Name : The term 'Name' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:7 char:1
+ Name  : OpenSSH.Server~~~~0.0.1.0
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (Name:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

State : The term 'State' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:8 char:1
+ State : NotPresent
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (State:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Installation of OpenSSH For Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse#feedback)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* GitHub Login: @maertendMSFT

**Comment by aurelien-git** [comment]
error was coming from me.

**Comment by illfated** [comment]
👍 Thank you for the follow-up, for finding the error, and enlightening us about your side of the issue.

**Comment by aurelien-git** [comment]
I have stupidly copy paste the whole stuff with the comment -_-'
