### ISSUE TITLE
Server Sizing and Capacity Planning Document Would Be Useful

### ISSUE THREAD

**Issue by CBrasga** [MicrosoftDocs/windowsserverdocs#4010]
A server sizing and capacity planning document would be useful. Similar to what is available for DirectAccess: https://docs.microsoft.com/en-us/windows-server/remote/remote-access/directaccess/directaccess-capacity-planning

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68492851-b870-4765-04c6-034f470ba464
* Version Independent ID: 0330ea6f-c2a9-c848-56b1-5fa615843bfa
* Content: [Plan the Always On VPN Deployment](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-planning)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-planning.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-planning.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
Can a Microsoft employee please assign a writer to these topics so my name can be removed from them?  I signed the divorce papers in Nov 2018.

**Comment by anaharris-ms** [comment]
Hey there, @CBrasga! Thanks for your hard work on our docs. We’re really sorry we couldn’t get to your pull request in time. We’re closing this issue for now. If you have any other ideas for our docs, don’t hesitate to reach out again. Thanks!
