### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by ulysesramos** [MicrosoftDocs/windowsserverdocs#4022]
The Additional Information Link under Azure SQL DB is broken.

**Comment by illfated** [comment]
Not enough information, there are too many pages containing the phrases "Azure SQL DB", "Azure SQL Database", and "Additional Information" to know which one you mean.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Question is not linked to a specific document. Closing issue due to no response.
#please-close
