### ISSUE TITLE
Conflicting information regarding automatic NativeProtocolType (IKEv2 to SSTP or SSTP to IKEv2)

### ISSUE THREAD

**Issue by Silencer0001** [MicrosoftDocs/windowsserverdocs#4027]
The option "NativeProtocolType" has conflicting information with the following URL: 
https://docs.microsoft.com/en-us/windows/client-management/mdm/vpnv2-csp

Could you please confirm which protocol type is used first when configuring "automatic protocol type"?
Does IKEv2 fallback to SSTP? Or does SSTP fallback to IKEv2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3e10ece-cd5d-0080-a1d3-df64466d1a0b
* Version Independent ID: 5b0e8894-8d85-7d93-9dc7-d79fd15504d3
* Content: [Always On VPN features](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/vpn-map-da)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/vpn-map-da.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/vpn-map-da.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
Can a Microsoft employee PLEASE remove my name from all the content I owned before I was forced to sign the divorce papers?  I'm really getting tired of these emails; I haven't worked at Microsoft since Nov 2018.
