### ISSUE TITLE
Confusing certificate management

### ISSUE THREAD

**Issue by cameron-interactive** [MicrosoftDocs/windowsserverdocs#4028]
This page is quite confusing with what it's trying to achieve and how it all hangs together. There's a combination of AD GPO instructions and non AD instructions. Group policy is mentioned frequently, but this solution being deployed has no requirements for domain joined machines.

We see this - 

Prerequisites:
Domain-joined VPN servers

Which seems to go against the recommendations of not joining VPN servers in the DMZ to the domain, but there are no instructions for Non-Domain joined VPN servers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76dd49bb-b86e-f5b7-35b9-a8d246d36fcb
* Version Independent ID: dedfa83f-36d6-f60b-e839-ba382c5a7372
* Content: [Configure the Server Infrastructure](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure#ca-configuration-for-non-domain-joined-computers)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by norphus** [comment]
I have to agree, this is ultra confusing and very unclear.

**Comment by shortpatti** [comment]
Can a Microsoft employee PLEASE PLEASE PLEASE take ownership of this topic and remove my name.  I signed the divorce papers from them in Nov 2018.

**Comment by Macel** [comment]
The section on the VPN server certificate implies that you are giving directions for a non-domain joined VPN server, but the steps outline the process for one that IS domain joined.

My suggestion to anyone following this article: Just join the damn VPN server to the domain.

**Comment by cameron-interactive** [comment]
> The section on the VPN server certificate implies that you are giving directions for a non-domain joined VPN server, but the steps outline the process for one that IS domain joined.
> 
> My suggestion to anyone following this article: Just join the damn VPN server to the domain.

You generally don't want servers in the DMZ to be joined to the domain, the nature of their location makes them very high risk for attacks, you want the least amount of information on there as possible (basically stop silly sys admins from logging on and caching DA credentials).

**Comment by Tof06250** [comment]
I completely agree with those comments and cannot understand why MS doesn't do anything about it. It seems that no one is reading those docs and validate them before posting... 
Guys, if you need a validation process, I can help... I'm really good at testing before publishing.
Please, update this doc and help us using those docs in a moment where EVERYONE is asked to enable Always On VPN because of CoVid outbreak... Thanks
Other incomprehensible guide is where did you configure this "CertificateTemplate:[Customer]VPNGateway" ? Mine is constantly rejecting this request and I don't know why.

**Comment by wazzaworld** [comment]
> I completely agree with those comments and cannot understand why MS doesn't do anything about it. It seems that no one is reading those docs and validate them before posting...
> Guys, if you need a validation process, I can help... I'm really good at testing before publishing.
> Please, update this doc and help us using those docs in a moment where EVERYONE is asked to enable Always On VPN because of CoVid outbreak... Thanks
> Other incomprehensible guide is where did you configure this "CertificateTemplate:[Customer]VPNGateway" ? Mine is constantly rejecting this request and I don't know why.

I was just about to raise a separate issue on this particular command - the template referred to is the one created further down the document, namely the one entitled "VPN Server Authentication" or "RADIUS Server". In this case this whole section for non-domain joined certificate enrollment should be put below the section for enrolling the VPN Server. 

The actual command that worked for me is as follows - note that the Certificate Template name used is without spaces as that's the real template name, not the display name (but I think it may be ok to use spaces):
certreq -attrib "CertificateTemplate:VPNServerAuthentication" -submit VPNgateway.req VPNgateway.cer

Oh, and there is no mention that you have to export the root CA certificate from the CA server and import to "Trusted Root Certification Authorities" in certlm.msc on non-domain joined servers.

I'll create a separate issue for this to track it properly.

**Comment by anaharris-ms** [comment]
#please-close Fixed in: https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/3398
