### ISSUE TITLE
AD Deployment

### ISSUE THREAD

**Issue by cameron-interactive** [MicrosoftDocs/windowsserverdocs#4029]
Is this required if the clients are not domain joined, and the VPN servers are not domain joined? It's a little unclear as to what is using the root certificates here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e575e6c6-ee12-fee9-fa27-f88f56643325
* Version Independent ID: fe0b17a1-4f40-3a9e-1be1-6d36eb870293
* Content: [Deploy Conditional Access root certificates to on-premises AD](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/vpn-deploy-cond-access-root-cert-to-on-premise-ad)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/vpn-deploy-cond-access-root-cert-to-on-premise-ad.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/vpn-deploy-cond-access-root-cert-to-on-premise-ad.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by anaharris-ms** [comment]
#please-close Fixed in: https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/3398
