### ISSUE TITLE
DTLS 1.1

### ISSUE THREAD

**Issue by Garthmj** [MicrosoftDocs/windowsserverdocs#4031]
Since there is not DTLS 1.1 based on this page. "DTLS 1.0 is based on TLS 1.1, and DTLS 1.2 is based on TLS 1.2. There is no DTLS 1.1; that version number was skipped in order to harmonize version numbers with TLS" https://en.wikipedia.org/wiki/Datagram_Transport_Layer_Security

Is the DTLS 1.1 reg key display above correct or should it be DTLS1.2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd180142-4c19-8abc-ecce-e4c7e5ac8951
* Version Independent ID: fc5bba87-afad-1729-8f7e-333c73188b73
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server**
* Technology: **security-tls-ssl**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by illfated** [comment]
It is meant to be DTLS 1.2 -- see 2 previous attempts (incomplete) at updating the image.

I have just started working on my own PR to have that image and text updated to no longer use "DTLS 1.1", but use 1.2 as the only version.

**Comment by illfated** [comment]
There you go. PR #4988 is available for viewing, comments and suggestions. Take care of yourself and those near you.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. A documentation change was made and changes are live. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
