### ISSUE TITLE
RL option is missing

### ISSUE THREAD

**Issue by iwiwsb** [MicrosoftDocs/windowsserverdocs#4040]
According to this [Schtasks.exe](https://docs.microsoft.com/en-us/windows/win32/taskschd/schtasks ) article, **schtasks** has option `/RL` that "sets the run level for the task. Valid values are LIMITED and HIGHEST. The default is LIMITED." But [here](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/schtasks) `/RL` option is not even mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 017089b7-e7fe-f1d8-854f-91d1619164b6
* Version Independent ID: 766063ce-6e31-fa5f-da41-27b75ecec05d
* Content: [schtasks](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/schtasks#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/schtasks.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/schtasks.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. A documentation change has been made for schtasks /rl parameter and can be found at:

https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/schtasks-create
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/schtasks-change

 We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
