### ISSUE TITLE
DNS Suffixes

### ISSUE THREAD

**Issue by archgriffin** [MicrosoftDocs/windowsserverdocs#4047]
Is listed to comma separate them, but it wants them semi-colon separated in the VPN profile XML file. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e14da1-102d-3ddf-e2a1-a20ce533b95a
* Version Independent ID: 374edc4c-f527-b7b7-c291-353928b97d8d
* Content: [Configure Windows 10 Client Always On VPN Connections](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections#feedback)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
Can a Microsoft employee take ownership of this topic?  I haven't worked there since Nov 2018.

**Comment by hosebei** [comment]
On my system I was required to use comma (,). I have tested with a semi-colon (;) and the DNS Suffix entry is incorrectly listed. So it might be a Language/Cultural issue?
I have used en-US OS with de-CH settings (without LP)

**Comment by shortpatti** [comment]
Can a Microsoft employee PLEASE remove my name from all the documents I used to own and manage? I signed the divorce papers from Microsoft in Nov 2018 and would LOVE IT if a Microsoft writer would take ownership of the content. I don't work there, and don't get paid to correct these documents anymore. I feel sorry for the IT Professionals using these products because there's no one at Microsoft who really cares about the IT Pro :( It's obvious because these documents haven't been maintained for over 18 months.

PLEASE PLEASE PLEASE someone remove my name from these documents!!!!! I can unsubscribe until my face turns blue, but that's 100s if not 1000s of documents.

**Comment by illfated** [comment]
@eross-msft : Maybe you could ask a web technician if it would be possible to mass remove the @ character from the username "shortpatti" in every open issue ticket? That would certainly make it more bearable for Patti Short to keep using her existing username. (If it had been me in this situation, I would have renamed my account, but that would also mean making all existing comments/posts seem to be created by @ghost (which is less than useful).

Please note that I have already changed my account name once, 3 years ago, so I know how that distancing works. You basically delete your old GitHub log entries from your name, as well as turning off the ability to "ping" that user account.

**Comment by eross-msft** [comment]
@illfated  Thank you for the suggestion. I've gone ahead and just assigned the articles to myself to end that part of this conversation.

**Comment by illfated** [comment]
Very good, thank you for following up on this. I was pre-worried that I would need to map the pages I would have to edit to make it work interchangeably. 😉

**Comment by anaharris-ms** [comment]
#please-close Fixed in: https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/3398
