### ISSUE TITLE
Are we sure this applies to Windows 10 / Ws2016 and beyond?

### ISSUE THREAD

**Issue by carlosmayol** [MicrosoftDocs/windowsserverdocs#4056]
This protection AFAIK was created in early days of win8.1/2012 R2 to protect LSSAS before VBS/CG has available. if so, please move this content to older OS versions so we do not confuse our customers.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b04bc4d-9435-cdbc-429f-2433ada7bd37
* Version Independent ID: 5c902397-b2e7-4435-2b37-a57919434c9e
* Content: [Configuring Additional LSA Protection](https://docs.microsoft.com/en-us/windows-server/security/credentials-protection-and-management/configuring-additional-lsa-protection#how-to-identify-lsa-plug-ins-and-drivers-that-fail-to-run-as-a-protected-process)
* Content Source: [WindowsServerDocs/security/credentials-protection-and-management/configuring-additional-lsa-protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/credentials-protection-and-management/configuring-additional-lsa-protection.md)
* Product: **windows-server**
* Technology: **security-credential-protection**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by RAJU2529** [comment]
@carlosmayol . It's applicable to windows 10 1909 build no 18363.752  
I enabled already and working fine together with the device guard.

**Comment by carlosmayol** [comment]
Hmm, sorry I am missing something, we are using CG (credential Guard) to protect the LSASS process since Windows 10, for win8.1/2012R2 we didnt have CG as it is implemented using VBS (VTL) and there fore I believe this content as explains in it (applies to Win8.1) was just a mechanism we had then. I am not discussing if it work in your laptop/VM when Credential Guard is not in use, but this approach was suggested in Win8.1 time and it confuses customers with our direction to use CG instead. Please confirm this.

**Comment by RAJU2529** [comment]
@coreyp-at-msft . Please reply to me this issue.  
@elliot-labs . Please reply to this issue

**Comment by illfated** [comment]
@RAJU2529 : Take a look at their profile pages. Corey Plett has not been publicly active on GitHub since November 2018, so it is unlikely that he will reply (I tried asking in one or two PRs I made last year, no response). I don't know anything about Elliot Huffman, though, except for what I can read on his GitHub profile page.

**Comment by illfated** [comment]
@eross-msft : Sorry for troubling you, but could you assign this ticket to someone, or maybe locate a suited team member to comment on this topic?

**Comment by elliot-labs** [comment]
Hi @RAJU2529,

I just wanted to let you know that I am not part of the docs team.

Thanks!

**Comment by v-thepet** [comment]
Hello @carlosmayol, 

Thank you for contacting Microsoft. We value your feedback and apologize for the delay in responding to your issue.

We've updated the documentation to clarify that both LSA protection and CG can be enabled on systems that support them. The update will be live after the next business day.

We'll now be closing this thread. Thank you again for your feedback, and have a most pleasant day.

#please-close
