### ISSUE TITLE
Page not found of the Windows Admin Center Preview link

### ISSUE THREAD

**Issue by tksh164** [MicrosoftDocs/windowsserverdocs#4058]
The page does not available.

> For info about Windows Admin Center Preview releases, see Windows Insider Preview releases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c65345dc-dabb-71b9-9e6f-f6ec85656f0b
* Version Independent ID: 44114459-aa8a-d830-d29d-08b6e36cc154
* Content: [Windows Admin Center support policy](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/support/)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/support/index.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/support/index.md)
* Product: **windows-server**
* Technology: **manage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Broken link:
- https://www.microsoft.com/software-download/windowsinsiderpreviewserver

Unbroken link:
- https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewserver
(Yes, this time the language agnostic link refuses to work, for some unknown reason.)

**Comment by illfated** [comment]
I have tried a couple of other languages (other than /en-us/), like /en-gb/, /de-de/ and /fr-fr/ but this page seems to be _locked solid_ to the language specific **/en-us/** link. Windows OS preview is only available in US English anyway, so it should not come as a surprise to anyone who has downloaded and installed preview editions of Windows 10 and similar.

**Comment by illfated** [comment]
@tksh164 : if you are able to and would like to do so, you can submit a Pull Request (PR) by editing the GitHub page to add the missing **/en-us/** part of the link :

- https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/includes/support-policy.md

(Raw text view: https://raw.githubusercontent.com/MicrosoftDocs/windowsserverdocs/master/WindowsServerDocs/manage/windows-admin-center/includes/support-policy.md )

**Comment by tksh164** [comment]
@illfated Thanks. I sent a pull request.

**Comment by illfated** [comment]
(similar: ref. #4059 )

**Comment by illfated** [comment]
(also: ref. #4071 )

**Comment by illfated** [comment]
#please-close (ref. commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/5b4100c6528b7acf8cf51a2b5448d5db9204d5e0)
