### ISSUE TITLE
Fail to install OpenSSH via PS

### ISSUE THREAD

**Issue by itorrestamanaja** [MicrosoftDocs/windowsserverdocs#4070]
Add-WindowsCapability : Add-WindowsCapability failed. Error code = 0x800f0954
At line:1 char:1
+ Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-WindowsCapability], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.AddWindowsCapabilityCommand

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
