### ISSUE TITLE
Print Spooler

### ISSUE THREAD

**Issue by grbray** [MicrosoftDocs/windowsserverdocs#4073]
Link for Print Spooler should go from the legacy Technet blogs to here: https://techcommunity.microsoft.com/t5/ask-the-performance-team/disabling-unnecessary-services-a-word-to-the-wise/ba-p/373444

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d867f27-5abb-be93-6bad-13eaa2e57ca6
* Version Independent ID: 8e8d603f-f93f-57f2-dec2-098433885624
* Content: [Security guidelines for system services in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server)
* Content Source: [WindowsServerDocs/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server.md)
* Product: **windows-server**
* Technology: **techgroup-security**
* GitHub Login: @nirb
* Microsoft Alias: **nirb**

**Comment by illfated** [comment]
(Just making a note here for later, to revisit this issue ticket to remember to contribute with a PR.)
- https://docs.microsoft.com/windows-server/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server#print-spooler

**Comment by dksimpson** [comment]
Hi @grbray,

Thanks for contacting Microsoft; we value your feedback. The link has been updated in the documentation.

If you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.

#please-close
