### ISSUE TITLE
CMD opened by sshd in win10 can not use remote file

### ISSUE THREAD

**Issue by lin-ww** [MicrosoftDocs/windowsserverdocs#4077]
CMD opened in win10(192.168.1.10) sshd connected from any other computer. Then I want to use the remote files in server 192.168.1.12. I opened python in this ssh CMD, and input 
```python
>>import os
>>os.path.exists(r'\\192.168.1.12\shared')
False
```

It can not find the remote file. But it returns `True` when I login in the win10(192.168.1.10) without ssh.  
It means that the windows openssh-server can not use remote file. How can I deal with this problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89f816fb-37f4-ce80-1723-783f534acaf7
* Version Independent ID: 817a16e8-741f-0f38-cee3-ae4a36e6e83e
* Content: [OpenSSH in Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_overview#feedback)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Overview.md)
* GitHub Login: @maertendMSFT

**Comment by robinharwood** [comment]
Hi @lin-ww,

Thanks for your dedication to our documentation. I don't have a lot of Python knowledge, however we've submitted a documentation change based to highlight remote sessions opened via key based authentication does not have associated user credentials and hence is not capable of outbound authentication as the user, the updated article should be live by tomorrow. This is found within the (Key management)[https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement] article and could be related to your issue. 

Alternatively, this could be related to authentication on the remote file share. Please review this issue from our Win32-OpenSSH repo, which covers the product code (Cannot access network drive from ssh session #139)[https://github.com/PowerShell/Win32-OpenSSH/issues/139].

To get further assistance or support for your product issue, we recommend that you engage with the product community or open a ticket with Microsoft Support. For more information, see [Contact Microsoft Support](https://support.microsoft.com/ContactUs).

Hope this helps

#please-close
