### ISSUE TITLE
Suggestion from customer on the Connection string

### ISSUE THREAD

**Issue by Daisy429** [MicrosoftDocs/windowsserverdocs#4080]
Customer suggest use variable for Driver name in connection string "Driver={SQL Server Native Client 13.0};Server=tcp:cb-sqls1.database.windows.net,1433;Database=CB-DB1;Uid=sqladmin@contoso;Pwd={your_password_here};Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;".  Modify driver name "Driver={SQL Server Native Client 13.0}" according to the driver which is used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5238c11b-240b-ff1c-42f1-8381048912f9
* Version Independent ID: 98ec3637-8be0-5500-8b8d-cf1062c3271d
* Content: [Add an RD Connection Broker server to configure high availability in RDS](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-connection-broker-cluster#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-connection-broker-cluster.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-connection-broker-cluster.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
Looks like the suggested solution is to use the ODBC name of the downloadable SQL package: **ODBC Driver 13 for SQL Server**

See issue ticket #4455 for more details why this seems to be the solution.

**Comment by illfated** [comment]
(ref. #4455 and #4840 )

**Comment by illfated** [comment]
PR #4974 is now ready for review. Feel free to browse, comment, or suggest changes.
