### ISSUE TITLE
Excellent ftp reference

### ISSUE THREAD

**Issue by pernak01** [MicrosoftDocs/windowsserverdocs#4086]
Excellent ftp "put" reference with examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96757e07-4741-6375-3ced-0dce0713120b
* Version Independent ID: 2b85a083-f842-6fbf-ca94-0ae010cbb033
* Content: [ftp put](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/ftp-put#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/ftp-put.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/ftp-put.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Actually, thank you for posting this comment. I just noticed that the "Parameters" table contains hidden information because of the interpretation of `<>` as HTML tags. I don't know if anything else is missing at the moment, but if you do notice anything, feel free to comment here again.
