### ISSUE TITLE
the slammer

### ISSUE THREAD

**Issue by popebombizzle** [MicrosoftDocs/windowsserverdocs#4087]
all of yall ready to be charged with federal crimes. 15+ years

**Comment by illfated** [comment]
#please-close

**Comment by popebombizzle** [comment]
Please explain why I’m being remotely connected to and maliciously attacked seemingly by the same project you guys have going here?

**Comment by illfated** [comment]
@popebombizzle : Get someone to clean your computer. Your software or browsers seem to be affected by malware.
