### ISSUE TITLE
How does one find valid options for certstorename ?

### ISSUE THREAD

**Issue by ayeltsov** [MicrosoftDocs/windowsserverdocs#4088]
For example, how does one specify cert from Trusted Root?
If not all cert stores are allowed, how does one find out which are allowed and which aren't?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48a10fe2-2374-889f-cc3b-4b078f9a2418
* Version Independent ID: 9e6e1e81-ad12-ac11-9464-4c5c8f6b192c
* Content: [Netsh Commands for Hypertext Transfer Protocol (HTTP)](https://docs.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh-http#add-sslcert)
* Content Source: [WindowsServerDocs/networking/technologies/netsh/netsh-http.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/netsh/netsh-http.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by RAJU2529** [comment]
@ayeltsov, Answering your query is difficult to me

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
Hello @ayeltsov. GitHub issues for this repo are for reporting problems with our documentation.  Please open a support ticket or post your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html).
