### ISSUE TITLE
Same approach for Azure

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windowsserverdocs#4090]
how should an organization do this if they are cloud only and don't have anything on-premises?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f43fec44-fdc4-3f92-291e-a46c10cd4aee
* Version Independent ID: 0ed1458c-2026-696f-a7d1-f964137e1377
* Content: [Securing privileged access](https://docs.microsoft.com/en-us/windows-server/identity/securing-privileged-access/securing-privileged-access)
* Content Source: [WindowsServerDocs/identity/securing-privileged-access/securing-privileged-access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/securing-privileged-access/securing-privileged-access.md)
* Product: **windows-server**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by illfated** [comment]
The login consoles will still need attention from IT technicians or managers to make sure the end user computers, laptops, tablets, or phones are kept safe from malware, keyloggers and similar security breaches. Remember that one of the more common weak spots is browser-stored passwords for important login accounts.

**Comment by MicrosoftGuyJFlo** [comment]
Content updates in progress #please-close
