### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by jeffstokes72** [MicrosoftDocs/windowsserverdocs#4095]
https://docs.microsoft.com/windows-server/virtualization/hyper-v/manage/understanding-hyper-v-scheduler-type-selection

is a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44c77ecb-1822-a712-cad3-a4f9ba84f2a3
* Version Independent ID: 195f045d-cf48-fec1-93a8-48663d21ab04
* Content: [Understanding and using Hyper-V hypervisor scheduler types](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types#feedback)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/manage-hyper-v-scheduler-types.md)
* Product: **windows-server-hyper-v**
* Technology: **virtualization**
* GitHub Login: @allenma
* Microsoft Alias: **allenma**

**Comment by RAJU2529** [comment]
@allenma10 . The issue is confirmed, 
the link for ** Understanding Hyper-V scheduler type selection**  gives 404 error.
i could not found best alternative link.

**Comment by illfated** [comment]
This issue is basically the same as #2418 (**"Understanding Hyper-V scheduler type selection" Link is broken**), although that issue ticket is not present in the Feedback section of the page.

**Comment by jeffstokes72** [comment]
If I had to hazard a guess, someone updated the folder that contained this missing .md file without including it and overwrote... (I used to work in Azure docs and made that mistake once..)

**Comment by illfated** [comment]
> If I had to hazard a guess, someone updated the folder that contained this missing .md file without including it and overwrote... (I used to work in Azure docs and made that mistake once..)

Thanks for that feedback, it sounds quite likely and possible. I can only suggest asking for a comment from the author (@allenma - if available?) or one of the project managers.

**Comment by illfated** [comment]
The correct link seems to be the next one in the TOC, named "**About Hyper-V hypervisor scheduler type selection**" :
- https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/about-hyper-v-scheduler-type-selection
