### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by k-takai** [MicrosoftDocs/windowsserverdocs#4096]
[Enter feedback here]
"Hyper-V Script: Looking at KVP GuestIntrinsicExchangeItems" is linked to https://blogs.msdn.com/b/virtual_pc_guy/archive/2008/11/18/hyper-v-script-looking-at-kvp-guestintrinsicexchangeitems.aspx , but not working correctly (redirected to https://docs.microsoft.com/ja-jp/archive/blogs/).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac93bb4-09b7-c1ae-255d-744ea719a0a7
* Version Independent ID: ec6ff685-ea93-cb5f-af9b-45ffe0857db1
* Content: [Automatic virtual machine activation](https://docs.microsoft.com/en-us/windows-server/get-started-19/vm-activation-19)
* Content Source: [WindowsServerDocs/get-started-19/vm-activation-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/vm-activation-19.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
The link is language agnostic, meaning that it decides the user language for the resulting page based on your browser locale.

The main issue here is that the link points to the top level menu of the blog archive **Archived MSDN and TechNet Blogs**, not to a specific page where the information is supposed to be.

Page link: [Hyper-V Script: Looking at KVP GuestIntrinsicExchangeItems](https://blogs.msdn.com/b/virtual_pc_guy/archive/2008/11/18/hyper-v-script-looking-at-kvp-guestintrinsicexchangeitems.aspx)
 (https://blogs.msdn.com/b/virtual_pc_guy/archive/2008/11/18/hyper-v-script-looking-at-kvp-guestintrinsicexchangeitems.aspx)

Redirected result page: https://docs.microsoft.com/archive/blogs/

**Comment by illfated** [comment]
To me, it seems to be a challenge to find a page containing the original text or even trace the content to a new page to see if there has been any attempt to move or convert the content to docs.microsoft.com material. To see the difficulty for yourself, try this Bing search for the term `"Hyper-V Script: Looking at KVP GuestIntrinsicExchangeItems" site:microsoft.com`

(https://www.bing.com/search?q=%22Hyper-V+Script%3A+Looking+at+KVP+GuestIntrinsicExchangeItems%22+site%3Amicrosoft.com)

**Comment by illfated** [comment]
issue resolved in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/bd229f0504bd5f3a90b51733b8514905a4679800 of August 7, 2020 (direct file link: https://github.com/MicrosoftDocs/windowsserverdocs/commit/bd229f0504bd5f3a90b51733b8514905a4679800#diff-5dac0b656820a8c12d05d22b085bb300beb49e3b77560696efd2185f3e8ca061) (no Pull Request link on the commit page).

**Comment by illfated** [comment]
#please-close
