### ISSUE TITLE
Change the congestion control settings from its default values to ‘'.

### ISSUE THREAD

**Issue by paulrichwine** [MicrosoftDocs/windowsserverdocs#4099]
This line:
Change the congestion control settings from its default values to ‘'.

Should read:
Change the congestion control settings from its default values to ‘&lt;congestionControl latencyThresholdInMSec="8000" minCongestionWindowSize="64" enabled="true" /&gt;’.

Reference:
https://docs.microsoft.com/en-us/previous-versions/azure/azure-services/dn528859(v=azure.100)?redirectedfrom=MSDN#optimize-congestion-control-settings-between-web-application-proxy-and-the-ad-fs-servers--optional-step

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6bdcea6-e429-95ce-0012-a30241941e36
* Version Independent ID: b37b7c92-12d0-9d03-c181-05b7cfcbe276
* Content: [Best Practices for securing AD FS and Web Application Proxy](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/best-practices-securing-ad-fs#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Best-Practices-Securing-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Best-Practices-Securing-AD-FS.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by RAJU2529** [comment]
@billmath . as user @paulrichwine  report, the below line 
**<congestionControl latencyThresholdInMSec="8000" minCongestionWindowSize="64" enabled="true" />’.**

is  not there in this article, so i try to add above line via  EDIT page , but i found 
**<congestionControl latencyThresholdInMSec="8000" minCongestionWindowSize="64" enabled="true" />’.**

is already added in this article, but the above line does not visible in main article page, so please fix soon. Thanks

**Comment by RAJU2529** [comment]
@billmath . I found the way to make visible in the article i adjusted it correctly. But i did not create PR. 
here is the screenshot 
![Capture02](https://user-images.githubusercontent.com/3296790/78234505-dd306500-74f4-11ea-8c15-a4a2fad05eb0.JPG)

**Comment by NomadRex** [comment]
Why hasn't this been fixed?

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @paulrichwine,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change was made, and this issue was not closed. Changes are live. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
