### ISSUE TITLE
Ummm...slightly unprofessional

### ISSUE THREAD

**Issue by alavrin** [MicrosoftDocs/windowsserverdocs#4104]
https://docs.microsoft.com/en-us/windows-server/storage/storage-migration-service/known-issues#data-does-not-transfer-user-renamed-when-migrating-to-or-from-a-domain-controller

Not sure if this is an attempt at humor or just poor editing, but the "loser" reference probably isn't necessary.

For any users returned with their original name, edit their "User Logon Name (pre-Windows 2000)" to remove the random character suffix added by Storage Migration Service, so that this loser can logon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f348eda3-6195-cd36-9bf9-769b6c37927b
* Version Independent ID: a2255385-394e-7ee0-a90d-dcaca017a3d4
* Content: [Storage Migration Service known issues](https://docs.microsoft.com/en-us/windows-server/storage/storage-migration-service/known-issues#data-does-not-transfer-user-renamed-when-migrating-to-or-from-a-domain-controller)
* Content Source: [WindowsServerDocs/storage/storage-migration-service/known-issues.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-migration-service/known-issues.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @nedpyle
* Microsoft Alias: **nedpyle**

**Comment by nedpyle** [comment]
We at Microsoft do not have a sense of humor that we are aware of. This is an autocorrect typo.

**Comment by alavrin** [comment]
Glad to hear humor is not allowed at Microsoft, but you just made me laugh. Consider yourself reprimanded! Have a nice day and be safe out there.


Thanks
--
Andy Lavrin
Systems Engineer
Information Technology - Server Engineering
Office: 301-985-7078
Cell: 301-641-0484
E-mail: andrew.lavrin@umuc.edu<mailto:andrew.lavrin@umuc.edu>
University of Maryland Global Campus

[cid:image001.jpg@01D6076F.1F7BF530]

**Comment by nedpyle** [comment]
:) Thanks for reporting, I've fixed it and it should hit your region within 24 hours. I hope you and your family stay safe.

**Comment by nedpyle** [comment]
It looks like someone up in in the private repo forgot to press publish after my PR, I am shaking trees. Thanks for alerting me.

I'll take a look at the profile too, thanks.

**Comment by nedpyle** [comment]
Ok now it's really, _really_ published. Look for it to appear soonish.

**Comment by illfated** [comment]
"Waiting with with bated breath" 😉 😜

**Comment by illfated** [comment]
Looks like it is fixed now:

> 2. For any users returned with their original name, edit their "User Logon Name (pre-Windows 2000)" to remove the random character suffix added by Storage Migration Service, so that this user can logon.

**Comment by illfated** [comment]
Commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/084f9dd733b2fa248491d867b3f100731f5b4aec has made it to the page & section 
- https://docs.microsoft.com/en-us/windows-server/storage/storage-migration-service/known-issues#data-does-not-transfer-user-renamed-when-migrating-to-or-from-a-domain-controller .

**Comment by illfated** [comment]
#please-close
