### ISSUE TITLE
Error Levels

### ISSUE THREAD

**Issue by creahard** [MicrosoftDocs/windowsserverdocs#4119]
Most programs report error levels with a value less than 1, so the note's IF script should only be

IF ERRORLEVEL 0 GOTO Okay

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c179cec0-fc0c-2f8e-8b15-cd23b46e58dd
* Version Independent ID: 7d9137c1-5db0-c8ec-419c-ac4540433438
* Content: [if](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/if)
* Content Source: [WindowsServerDocs/administration/windows-commands/if.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/if.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
I think the whole point of that last line is to demonstrate the use of "Less than or Equal to" (LEQ) in conjunction with `%errorlevel%` -- meaning that maybe someone would want to return the same result for both errorlevel 1 and errorlevel 0.

Of course, your suggestion would be useful in some (many) scenarios, but this Note example is probably not intended for simplicity, only to show the usage of arithmetic operators in combination with the errorlevel check.

**Comment by Xelu86** [comment]
Hey creahard,

Thanks again for contacting Microsoft. We value your feedback. 

The explanation given by the ghost account is accurate in what the example was conveying for the `if` command using `%errorlevel%`. As this is a non-documentation issue, we'll now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
