### ISSUE TITLE
title of this page  is too short

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windowsserverdocs#4120]
I request to author  to consider any of the below titles to change

**IF Commands**   
**Commands  for IF function**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c179cec0-fc0c-2f8e-8b15-cd23b46e58dd
* Version Independent ID: 7d9137c1-5db0-c8ec-419c-ac4540433438
* Content: [if](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/if#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/if.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/if.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
@RAJU2529 : Please notice that all of the Windows Commands pages (https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands#command-line-reference-a-z) use only the command name, without any direct reference to its parameters in the title.

The main reason for the short title is that the command in itself is so short — if — and the page contains both a short description of what the command is used for, as well as which parameters are available and what the parameters do.

Unless you want to suggest a precise new title format for 268 pages, I don't see a need for changing the title of this page (https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/if).

**Comment by illfated** [comment]
Additional note: Some of the commands are listed with the name of one of the parameters in the title as separate pages. This is mainly for special cases, where individual parameters are either meant to be used without any of the other parameters, or the parameter listed in the title needs extra documentation because of its usage or behaviour.

**Comment by RAJU2529** [comment]
@illfated . thanks . i am closing
