### ISSUE TITLE
Camera and Microphone Redirection?

### ISSUE THREAD

**Issue by GuyPaddock** [MicrosoftDocs/windowsserverdocs#4121]
I didn't see anything on this page about whether or not Mic and Camera redirection is supported, or how to configure it.

We have a user connecting from Mac OS who is using the latest release (10.3.8) of [the MRD app](https://apps.apple.com/us/app/microsoft-remote-desktop-10/id1295203466). They are connecting from Mac OS Sierra (10.12).

They are trying to use Microsoft Teams inside WVD, which I am able to do when connecting from Windows, but they don't have any option to use the camera or microphone inside the WVD environment. It seems as though microphone and camera redirection is not working.

Is Mic and Camera redirection supported in MRD for WVD? If so, does it require a newer version of Mac OS? Please add a note about this.

(As an aside: the link provided in the text about "please do NOT post a request for troubleshooting help by using the comment feature at the end of this article" points to forums that no longer accept posts).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0517ea6a-9417-31a8-39a5-f6128387fee5
* Version Independent ID: 7636ec70-e1dd-8c6b-516c-8af324d9f645
* Content: [Get started with the macOS client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-mac)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
Hello @GuyPaddock.  Thank you for your feedback about the forum. For your question, please open a support ticket or post your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html).
