### ISSUE TITLE
Can't logon with AAD user to windows 10 SSH server

### ISSUE THREAD

**Issue by scyto** [MicrosoftDocs/windowsserverdocs#4124]
I have a windows 10 AAD joined machine
i can logon with at winlogon with my AAD upn in format of username@mydomain.com
this user is in the ssh users group
however the password for this user is not accepted
is this supported user type for logon?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8ad5c9a-efb1-d994-0e3c-53c90096a245
* Version Independent ID: 5cb0ea97-4c3d-ffdf-b69c-8a717f9f9f3f
* Content: [OpenSSH Server Configuration for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_server_configuration)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Server_Configuration.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Server_Configuration.md)
* GitHub Login: @maertendMSFT

**Comment by illfated** [comment]
I could be mistaken, but I think sshd looks for a local password on the Windows SSH server.

**Comment by scyto** [comment]
> I could be mistaken, but I think sshd looks for a local password on the Windows SSH server.

Ok, we don’t allow use of local accounts. Never mind, so long as it gets clarified in doc.

**Comment by illfated** [comment]
https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_server_configuration#authenticationmethods :

### AuthenticationMethods

For Windows OpenSSH, the only available authentication methods are "password" and "publickey".

**Comment by scyto** [comment]
I am back.  This issue still occurs.

I have configured publickey for the user domain\username and still can't login.

I don't think the previous commenter quite understood the question.

This is a azure active directory domain user that can logon locally as the PC is AAD joined (not AAD DS joined or AD joined)

**Comment by scyto** [comment]
seems this is the issue and always has been https://github.com/PowerShell/Win32-OpenSSH/issues/1787

**Comment by robinharwood** [comment]
Hi @scyto,

Thanks for your dedication to our documentation. I have confirmed with our internal teams that Authentication using an Azure AD account for authentication in OpenSSH is not currently supported. I have shared your feedback with the team, and I can see you have already commented on the [feature request in the Win32-OpenSSH repo](https://github.com/PowerShell/Win32-OpenSSH/issues/1787), thank you. This is the right place to follow up on these types of requests.

As this does not require an update to the documentation, we are closing this pull request for now. #please-close

Thanks,
Robin

#please-close
