### ISSUE TITLE
Azure Hybrid Services Cluster vs Stand Alone

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/windowsserverdocs#4125]
If an Azure Stack HCI cluster is used to create VM's, I'd assume stand-alone hybrid services could apply to those VM's? Or is this stating that you're using an Azure Stack HCI cluster (e.g., 2 - 4 nodes) only Azure Monitor, Azure Site Recovery and Cloud Witness can be used from Windows Admin Center?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c8fa86e-65b1-d8d1-c1e6-d7ba721d7f75
* Version Independent ID: 714b296f-07d4-3e09-3928-483e9069d180
* Content: [Connecting Windows Server to Azure hybrid services](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/azure/#services-for-stand-alone-servers-and-vms)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/azure/index.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/azure/index.md)
* Product: **windows-server**
* Technology: **manage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
@jebalert : Sorry about the long delay without any reply. The Microsoft Docs Server team does not have the capacity to follow up on questions not related to correcting or improving the document articles, only when there are specific suggestions to improve the referenced article(s). That is also the intended usage of this repository.

Please, feel free to report back if you have found anything in the meanwhile worth correcting in the documentation pages.

**Comment by illfated** [comment]
I will go ahead and ask for this ticket to be closed. Even so, feel free to reopen this ticket, or create a new one, should your question be answered elsewhere in such a way that you would be able to recommend the new information to be added to the page.

**Comment by illfated** [comment]
#please-close
