### ISSUE TITLE
dual use branch cache hosted mode and distributed mode on clients

### ISSUE THREAD

**Issue by okanozcan** [MicrosoftDocs/windowsserverdocs#4126]
is it possible use of both  modes  (hosted nad distributed mode ) on client os in the same time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfc4e34c-6c6e-093d-2af9-af41d7edfb43
* Version Independent ID: 6a7a3dc7-6dcb-4084-ab65-df7e3d30cdd7
* Content: [Choosing a BranchCache Design](https://docs.microsoft.com/en-us/windows-server/networking/branchcache/plan/choosing-a-branchcache-design)
* Content Source: [WindowsServerDocs/networking/branchcache/plan/Choosing-a-BranchCache-Design.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/branchcache/plan/Choosing-a-BranchCache-Design.md)
* Product: **windows-server**
* Technology: **networking-bc**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by IngridAtMicrosoft** [comment]
Hello @okanozcan. GitHub issues for this repo are for reporting problems with our documentation.  Please open a support ticket or post your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html).
