### ISSUE TITLE
How to display exclamation marks?

### ISSUE THREAD

**Issue by abdekker** [MicrosoftDocs/windowsserverdocs#4128]
When "setlocal EnableDelayedExpansion" is defined, displaying exclamation marks doesn't work:

@echo off
setlocal EnableDelayedExpansion
echo hello!
[Output: hello]

A trick is to use "endlocal" just before you want to display the exclamation mark, but is there no escape character? Caret (^) does not work (Microsoft Windows [Version 10.0.14393]).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b73a4605-c4b3-46a8-ec4e-493751fff82b
* Version Independent ID: 2bcfea05-35c7-49cb-0570-a0d5a4957ca1
* Content: [echo](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/echo)
* Content Source: [WindowsServerDocs/administration/windows-commands/echo.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/echo.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
https://stackoverflow.com/ is great for this kind of material. I have used batch files since MS-DOS 3.30, but I still had to use Google to find some useful answers:
- https://stackoverflow.com/questions/3288552/how-can-i-escape-an-exclamation-mark-in-cmd-scripts

Long story short: Using only 1 caret ` ^ ` needs quotation marks around the text to work. Double the caret (use 2) and it should work.

(https://stackoverflow.com/questions/3288552/how-can-i-escape-an-exclamation-mark-in-cmd-scripts)

**Comment by illfated** [comment]
Please note: The Windows Commands sub-pages will be receiving some updates during the coming weeks, so I have postponed any updates to those pages until the internal work is completed.

Even so, I would like to know if you find this extra Windows batch scripting information added to the existing tables.

**Comment by abdekker** [comment]
Yes, I think so. Its only a small addition, but would save time and make the documentation more complete (an ommission can sometimes be an error).

Ideal would probably be a dedicated page (with a link) or a section & table (on that page) showing a more complete list of the characters which have a special meaning in command-line programming (<, >, |, !, % and so on) and how to escape them.

I note that you have made numerous contributions to MS technical documentation, yet live in Norway. Are you an employee of Microsoft? Can anyone be a contributor?

**Comment by illfated** [comment]
Thank you for having confidence in me as a potential Microsoft employee, but I am just a regular user. Being a so-called "highly functional" autistic, it feels good to be able to contribute by being overzealous regarding details and grammar. I do this only in my spare time, even though some of the knowledge comes from my previous jobs as a computer support agent in various workplaces.

**Comment by illfated** [comment]
Oh, right. I forgot to answer the last question in your comment. Anyone with a modicum of knowledge of how to write functionally, have good suggestions for improvements and adhere to the existing code style guides for the MicrosoftDocs repositories, are welcome to contribute to the English (en-us) pages. Some time in the future, it might become possible to contribute to localized pages, but the Microsoft teams are still testing out how it works to manage the en-us hierarchy of contributors first.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @abdekker, 

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made on how to display `!` in batch scripts and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
