### ISSUE TITLE
switched

### ISSUE THREAD

**Issue by alysdexia** [MicrosoftDocs/windowsserverdocs#4133]
R2R, R2L

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0003865-ce9a-117a-f2ff-7eeed387c213
* Version Independent ID: 4506e308-992a-237a-4ad6-5acc552a75fe
* Content: [Fsutil behavior](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil-behavior)
* Content Source: [WindowsServerDocs/administration/windows-commands/fsutil-behavior.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/fsutil-behavior.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @toklima
* Microsoft Alias: **toklima**

**Comment by illfated** [comment]
OK, I think I see what you mean:

|                 Parameter                  | Description |
| ------------------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
|    symlinkevaluation <SymbolicLinkType>    | Controls the kind of symbolic links that can be created on a computer. Valid choices are:<br /><br />1.  Local to local symbolic links, L2L:{0&#124;1}<br />2.  Local to remote symbolic links, L2R:{0&#124;1}<br />3.  Remote to local symbolic links, R2R:{0&#124;1}<br />4.  Remote to remote symbolic links, R2L:{0&#124;1} |

I will make a PR to have that corrected.

**Comment by illfated** [comment]
@alysdexia : The Windows Server Docs team has started some planned work to make an overall cleanup on all the neighbouring pages, including the page with your reported issue. My PR got closed to avoid merge conflicts due to this internal work process. Even so, I presume this ticket may stay open in the meanwhile. The internal work may take some time, so please be patient.

**Comment by illfated** [comment]
I hope this PR (#5001) will be more useful by not colliding with any other major projects in the MS Docs team's work schedule.
