### ISSUE TITLE
IAM for new Azure Migrate

### ISSUE THREAD

**Issue by gate502** [MicrosoftDocs/windowsserverdocs#4140]
The previous version of Azure Migrate the IAM blade was available - how do we grant access to users for the new Azure Migrate?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e37be4a-764f-21bd-32f4-f7f6dfa2c4a5
* Version Independent ID: ae59e355-fb1d-150c-1293-c95c48253d44
* Content: [Determining the Interval](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/determining-the-interval)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/Determining-the-Interval.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/Determining-the-Interval.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by IngridAtMicrosoft** [comment]
Question is out of scope for Windows Server documentation. Closing.
