### ISSUE TITLE
Get-WindowsFeature FS-SMB1 not recognized

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/windowsserverdocs#4142]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/windowsserverdocs.it-it/issues/5

@Enozagar commented 3 days ago — with docs.microsoft.com
Hi all,
as reported, I'd have liked to check SMB v1 on my PC. As reported below, the log shows that this command isn't recognized.

PS C:\WINDOWS\system32&gt; Get-WindowsFeature FS-SMB1
Get-WindowsFeature : Termine 'Get-WindowsFeature' non riconosciuto come nome di cmdlet, funzione, programma eseguibile
o file script. Controllare l'ortografia del nome o verificare che il percorso sia incluso e corretto, quindi riprovare.
In riga:1 car:1

    Get-WindowsFeature FS-SMB1

      + CategoryInfo          : ObjectNotFound: (Get-WindowsFeature:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a91db45-ca3c-7a2e-3f32-2f5b57837b03
* Version Independent ID: b83cbaab-c0df-d6e7-a67f-f4c99a46e30a
* Content: [How to detect, enable and disable SMBv1, SMBv2, and SMBv3 in Windows](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3#feedback)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md)
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by QuiGonJames** [comment]
Are you running this on Windows Server 2012 R2 or 2016? If not, it is not the correct command.
The section in MS Docs with that command specifies these OSes.

But you mentioned you were running it on your PC. Assuming Windows 10 or 8(.1), you need to run: **Get-WindowsOptionalFeature –Online –FeatureName SMB1Protocol**
This is specified in the section for these OSes:
[MS Docs Link](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3#windows-81-and-windows-10-powershell-method)

**Comment by illfated** [comment]
Same link as above, just made openly visible as plain text:
- https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3#windows-81-and-windows-10-powershell-method

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
Sorry for taking so long to point it out, but SMBv1 has been deprecated for a long time and is replaced with the default version SMBv2 in all supported versions of Windows.

**Comment by illfated** [comment]
#please-close
