### ISSUE TITLE
License upgradation

### ISSUE THREAD

**Issue by shahmanthan1209** [MicrosoftDocs/windowsserverdocs#4144]
I would like to extend the number of users of RDP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9d8e4f9-6717-41fb-cca8-64e936965cf0
* Version Independent ID: a208cb51-3070-9be2-f8e3-1b61ffaf8ade
* Content: [Remote Access](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/remote-access)
* Content Source: [WindowsServerDocs/remote/remote-access/Remote-Access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/Remote-Access.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by IngridAtMicrosoft** [comment]
Hello @shahmanthan1209. GitHub issues for this repo are for reporting problems with our documentation.  Please open a support ticket or post your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html).
