### ISSUE TITLE
dead link of Job Aids in the last section

### ISSUE THREAD

**Issue by inntran** [MicrosoftDocs/windowsserverdocs#4147]
The updated URL for "Job Aids for Windows Server 2003 Deployment Kit" is now at https://www.microsoft.com/en-us/download/details.aspx?id=9608

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83d759d6-1086-3c3c-a6fe-c5e6c3edbef2
* Version Independent ID: ae4cd61b-2fc0-fac3-d212-d5917fe4e37f
* Content: [Selecting the Forest Root Domain](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/selecting-the-forest-root-domain#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/Selecting-the-Forest-Root-Domain.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/Selecting-the-Forest-Root-Domain.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by illfated** [comment]
Good job, nice find. I have been curious about the whereabouts of that document for a while. I always got sidetracked before I managed to complete a full session of digging through all web search hits, so your feedback helps quite a bit. Thank you.

**Comment by illfated** [comment]
BTW, the old and non-functional link is as follows:
- https://go.microsoft.com/fwlink/?LinkID=102558
