### ISSUE TITLE
Does this apply to server 2019 as well?

### ISSUE THREAD

**Issue by jantoney** [MicrosoftDocs/windowsserverdocs#4148]
Does this line apply to server 2019 as well? if so, this may need to be updated or clarification so the text on the page doesn't become dated in the future. For example - "This does not apply to server 2019" or similar

Do not attempt to deploy Remote Access on a virtual machine (VM) in Microsoft Azure. Using Remote Access in Microsoft Azure is not supported. You cannot use Remote Access in an Azure VM to deploy VPN, DirectAccess, or any other Remote Access feature in Windows Server 2016 or earlier versions of Windows Server. For more information, see Microsoft server software support for Microsoft Azure virtual machines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa82e6ef-7f35-9672-2ca3-9006de31b2cf
* Version Independent ID: 1dca040b-d5ba-8449-627b-b3069bd9be0e
* Content: [DirectAccess](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/directaccess/directaccess)
* Content Source: [WindowsServerDocs/remote/remote-access/directaccess/DirectAccess.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/directaccess/DirectAccess.md)
* Product: **windows-server**
* Technology: **networking-da**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 4144 -b #assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by anaharris-ms** [comment]
#please-close
