### ISSUE TITLE
Feature to consider .gitignore in robocopy

### ISSUE THREAD

**Issue by CBenghi** [MicrosoftDocs/windowsserverdocs#4149]
Hello,
I'm not sure this is the right place to add a feature request for robocopy, if not please accept my apologies.

My suggestion is to include a flag to robocopy so that, when scanning folders, it picks up local  .gitignore files and then adopts those extra exclusion patterns in the scope of the folder.
This is different from excluding them from the command line because exclusion patterns could then change for different sub-directories of the same backup operation.

Thanks.
Claudio

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @CBenghi,

Thanks again for contacting Microsoft. We value your feedback. 

GitHub isn't quite the right location to make feature requests. If you'd like to submit a feature request, please refer to our [Microsoft Feedback Hub](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332#:~:text=1%20Select%20the%20Start%20button%2C%20and%20then%20open,at%20the%20far%20right%20of%20the%20search%20box.). Please submit your suggestions in this app. 

We will now be closing this. Thank you and have a most pleasant day. #please-close

**Comment by hasansezertasan** [comment]
Is this feature implemented?
