### ISSUE TITLE
Broken link to 159865

### ISSUE THREAD

**Issue by codaamok** [MicrosoftDocs/windowsserverdocs#4150]
Hello, the link to https://docs.microsoft.com/EN-US/help/159865 is broken. Under the "The Target Disk" heading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fa148d7-c2ce-dc38-8da3-957bafa62683
* Version Independent ID: 70e3cc32-72eb-524a-fb61-7f1b67eaa4db
* Content: [Troubleshoot the Event ID 50 Error Message](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/troubleshoot-event-id-50-error)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/troubleshoot-event-id-50-error.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/Troubleshoot/troubleshoot-event-id-50-error.md)
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by illfated** [comment]
Confirmed. The sad part is that the link in itself is not the culprit. At first, I thought it could be an issue that the link is language specific or that /en-us/ is entered in CAPS (/EN-US/). That is apparently not a problem. The target page is lost and gone), the page appears to have been removed, which makes it a distributed issue because the link exists in multiple pages around in the microsoft.com universe.

**Comment by illfated** [comment]
See also https://support.microsoft.com/help/159865/ (**Sorry, page not found**)

# 404

**Comment by illfated** [comment]
Browsing through some old Microsoft Forum pages, it appears the KB article must have dated back to 2007 (Windows Vista) or earlier, people have asked for Windows Vista and Windows 7 support related to KB 159865, but seemingly not received any. It is most likely removed, deleted and never again revived.

The best course of action here is to completely remove the sentence referring to it, and seek other venues of support for this type of issue, like PowerShell or WMI.

**Comment by illfated** [comment]
Search results limited to site:microsoft.com :
https://www.bing.com/search?q=%22How+to+Distinguish+a+Physical+Disk+Device+from+an+Event+Message%22+site%3Amicrosoft.com&qs=n&form=QBRE&sp=-1&pq=%22how+to+distinguish+a+physical+disk+device+from+an+event+message%22&sc=0-65&sk=&cvid=2CB38ADF89AC4EAF834998F940C0A21E

**Comment by illfated** [comment]
There you go. PR #4973 to remove the text and the broken link is now available for review, comments and suggestions.
