### ISSUE TITLE
upgrade-to-rds possible typo ?

### ISSUE THREAD

**Issue by jspcstl** [MicrosoftDocs/windowsserverdocs#4153]
https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/upgrade-to-rds

Looks like there is a typo there... We are seeking whether or not in-place upgrade from Server 2016 to Server 2019 would be a supported scenario.

Should the yellow highlighted be Windows Server 2019 ?

![image](https://user-images.githubusercontent.com/17784483/78830337-c63ab880-79b5-11ea-9fc2-5462ec6a1097.png)

**Comment by illfated** [comment]
At first, I would agree that it looks that the to upgrade from Windows Server 2016 to Windows Server 2016.
Then again, looking back at the Feedback section of the page (used for reporting issues) links issue ticket #3995:

## Upgrade path at the top of this article doesn't make sense #3995

More specifically, see my comment from April 8: https://github.com/MicrosoftDocs/windowsserverdocs/issues/3995#issuecomment-596246448

> Searching the web (via Bing), it looks like the sentence is missing a version description detail at the end, so maybe it should look similar to the same line in **Upgrading your Remote Desktop Session Host to Windows Server 2016** (https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/upgrade-to-rdsh):
>> ## Supported OS upgrades with RDS role installed
>> Upgrades to Windows Server 2016 are supported only from Windows Server 2012 R2 and Windows Server 2016 TP5.

**Comment by illfated** [comment]
Also, please note that the article itself is at least as old as 2018-03-20 (and maybe older), so even though the phrasing is confusing, it is less likely that it should talk about upgrading to Windows Server 2019 as early as 7 months before the release date of Windows Server 2019.

**Comment by jspcstl** [comment]
The fact that the article applies to section included Server 2019 must be where it is confusing me.

Also the article isn't mentioning from Server 2016 TP5 anymore compared to the other issue you linked.

From your answer should I understand that upgrade from 2016 to 2019 is not a supported scenario?

**Comment by illfated** [comment]
Sorry, I am not a Microsoft employee, developer or engineer. It may very well be that you are correct. I am simply trying to find out if there are other explanations or if the document needs to be corrected exactly as you have suggested.

**Comment by jspcstl** [comment]
Is there any escalation process with the product team or MS to get an official answer on the subject ?

**Comment by illfated** [comment]
Oh. You opened a ticket directly here on GitHub, not on the docs.microsoft.com page. This ticket is likely to lay around for weeks or months to find an answer, without a reference to any of the MS Docs team members. You may want to open a new ticket from the page you linked, unless you want to post in the existing ticket.

If you need faster follow-up than weeks or months, consider contacting your local Microsoft Support instance or ask in the Technet forum pages to get answers from other software engineers.

**Comment by jspcstl** [comment]
ok thanks, i will open for docs.microsoft.com, I was under the impression I was in the right repo.

**Comment by illfated** [comment]
The repository may be correct, but if you don't open it from the docs.microsoft.com page, it does not get any relevant information attached, and therefore even less attention than regular tickets.

**Comment by jspcstl** [comment]
thanks, I was wondering about not being on the "page" itself.

**Comment by illfated** [comment]
To be continued in issue ticket #3995, where the docs.microsoft.com page is referenced.

#please-close
