### ISSUE TITLE
Example .ps1 script does not work

### ISSUE THREAD

**Issue by Macel** [MicrosoftDocs/windowsserverdocs#4158]
When attempting to run the profile creation example script under the system context, I get the following error:

Unable to create <profile name> profile: A general error occurred that is not covered by a more specific error code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc584192-594f-3633-21e1-6881bf186c01
* Version Independent ID: 7ec2db2e-cb49-90e5-4d71-209e9754666c
* Content: [Configure the VPN device tunnel in Windows 10](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/vpn-device-tunnel-config)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/vpn-device-tunnel-config.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/vpn-device-tunnel-config.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by hiscorebob** [comment]
+1

**Comment by IngridAtMicrosoft** [comment]
GitHub issues for this repository are for reporting problems with documentation.  Please open a support ticket for your issue. #please-close
