### ISSUE TITLE
wusa command isn't complete

### ISSUE THREAD

**Issue by miketheitguy** [MicrosoftDocs/windowsserverdocs#4163]
wusa requires you to be console'd into the machine. When running over winrm, you first have to expand the .msu file and use Add-WindowsPackage to the extracted cab file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35b743aa-a61e-2ecb-ef34-2d6fd31c836b
* Version Independent ID: 6dcc4daa-056f-3d9a-8e7a-ba2f584a815b
* Content: [Patching Server Core](https://docs.microsoft.com/en-us/windows-server/administration/server-core/server-core-servicing)
* Content Source: [WindowsServerDocs/administration/server-core/server-core-servicing.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/server-core/server-core-servicing.md)
* Product: **windows-server**
* GitHub Login: @lizap

**Comment by robinharwood** [comment]
We hugely appreciate your contribution, feedback, and support to our technical documentation.

We’ve phased out GitHub Issues on this repository as the feedback mechanism for content and have replaced it with a new feedback system. For more information see, [Content User Feedback](https://aka.ms/ContentUserFeedback). As part of this rollout, we are migrating your issue where our team will use your comments to improve the documentation experience. Unfortunately, this does mean you won't be able to access this issue after the migration is complete.

All issues will be migrated by Thursday 29th August 2024.

Once again, thank you for your valuable feedback, we hope you’ll continue to contribute using our new feedback system.
