### ISSUE TITLE
Microsoft (R) Diagnostics Hub Standard Collector

### ISSUE THREAD

**Issue by rlappsupport** [MicrosoftDocs/windowsserverdocs#4164]
Service description for this service is actually service description for Local Session manager

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d867f27-5abb-be93-6bad-13eaa2e57ca6
* Version Independent ID: 8e8d603f-f93f-57f2-dec2-098433885624
* Content: [Security guidelines for system services in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server#feedback)
* Content Source: [WindowsServerDocs/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server.md)
* Product: **windows-server**
* Technology: **techgroup-security**
* GitHub Login: @nirb
* Microsoft Alias: **nirb**

**Comment by illfated** [comment]
Thank you for noticing and reporting this issue. That looks like a copy-paste mistake. I will look up what the actual description should be by logging in to the WS2016 server at my workplace and see if I can find it there, then create a PR to have that description corrected.

**Comment by illfated** [comment]
Found it. The correct description is as follows:
- Diagnostics Hub Standard Collector Service. When running, this service collects real time ETW events and processes them.

**Comment by rlappsupport** [comment]
Thank you – any update on the recommendation of whether this can be safely disabled or not per the theme of the original document?

**Comment by illfated** [comment]
Well, I can only reference what the Windows Server 2016 DC server setting is: Manual (not running). This is my workplace production AD DC, file & print server running our main MS SQL server database for 12 simultaneous DB login sessions (3rd party license limitation) within the Virtual Machine. The outer server (hardware-installed OS) also uses this setting, but I don't know enough about this specific service to know if it is safe to stop it while it is running.

Seeing that the service does not have any dependencies nor is dependent on any other services, it looks independent enough to try stopping, if you don't need it for troubleshooting any issues. I can only venture a guess that the Manual setting is recommended if you want to run any Microsoft diagnostic OS tools to troubleshoot any OS issues, but that might depend on your specific server configuration.

**Comment by illfated** [comment]
Minor correction: since the service is not running on either of my workplace server operating systems, I guess it is just a matter of checking whether you may want to run any Microsoft diagnostic tools at a later time, which could be one of the few reasons why it would be a good idea not to disable it. Then again, if you have access to 3rd party debugging tools or diagnostic tools (non-Microsoft), it is all up to you. You may also want to consider which type of support you have got available, as well as your server(s) role(s) and importance in production. Those evaluations are for you and your closest peers to consider.

**Comment by illfated** [comment]
BTW, I just noticed that the service Name is copy-pasted as well, showing "LSM" (same as Local Session Manager).
The actual name of this service is "diagnosticshub.standardcollector.service". I need to add that correction too in my PR.

**Comment by illfated** [comment]
... aaand I will change the Startup Type to be "Manual" as well, seeing that this is the default configuration on my workplace server(s).

**Comment by illfated** [comment]
There are a lot of changes in my PR, both regarding whitespace, layout and reordering of rows, as well as row name corrections to match the actual UI names.
