### ISSUE TITLE
Query policy proccessing schema

### ISSUE THREAD

**Issue by egozav** [MicrosoftDocs/windowsserverdocs#4166]
Query policy proccessing  schema is broken near the "Do not apply policy" block

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b951d0a2-1d11-00dc-cfd3-64dd31bbf377
* Version Independent ID: ab56539c-e788-9209-2d35-057fcacd972b
* Content: [DNS Policies Overview](https://docs.microsoft.com/en-us/windows-server/networking/dns/deploy/dns-policies-overview#feedback)
* Content Source: [WindowsServerDocs/networking/dns/deploy/DNS-Policies-Overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/dns/deploy/DNS-Policies-Overview.md)
* Product: **windows-server**
* Technology: **networking-dns**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 4161 -b #assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by robinharwood** [comment]
We hugely appreciate your contribution, feedback, and support to our technical documentation.

We’ve phased out GitHub Issues on this repository as the feedback mechanism for content and have replaced it with a new feedback system. For more information see, [Content User Feedback](https://aka.ms/ContentUserFeedback). As part of this rollout, we are migrating your issue where our team will use your comments to improve the documentation experience. Unfortunately, this does mean you won't be able to access this issue after the migration is complete.

All issues will be migrated by Thursday 29th August 2024.

Once again, thank you for your valuable feedback, we hope you’ll continue to contribute using our new feedback system.
