### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by YipYup** [MicrosoftDocs/windowsserverdocs#4170]
In the documentation, there is a technical error:

By default, a KMS host registers its SRV records in the DNS zone that corresponds to the domain of the KMS host computer. For example, assume that a KMS host joins the contoso.com domain. In this scenario, the KMS host registers its _vmlcs SRV record under the contoso.com DNS zone. Therefore, the record identifies the service as VLMCS._TCP.CONTOSO.COM.

Should be:

By default, a KMS host registers its SRV records in the DNS zone that corresponds to the domain of the KMS host computer. For example, assume that a KMS host joins the contoso.com domain. In this scenario, the KMS host registers its _vmlcs SRV record under the contoso.com DNS zone. Therefore, the record identifies the service as **_VLMCS._TCP.CONTOSO.COM**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08ba6d1a-0f8e-7796-073f-f431c4421f6c
* Version Independent ID: c88cc509-3ccc-dc6d-f0b2-098303d178c6
* Content: [Guidelines for troubleshooting DNS-related activation issues](https://docs.microsoft.com/en-us/windows-server/get-started/common-troubleshooting-procedures-kms-dns#feedback)
* Content Source: [WindowsServerDocs/get-started/common-troubleshooting-procedures-kms-dns.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/common-troubleshooting-procedures-kms-dns.md)
* Technology: **server-general**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by illfated** [comment]
(Ref. #4175 )

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
This issue ticket has been resolved by Pull Request #4175 - see linked PR icon above.

**Comment by illfated** [comment]
#sign-off

**Comment by illfated** [comment]
Ref. commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/7a6f5a884ff379c38bbe0eb9138180a5f4e662ae — Resolved.

**Comment by illfated** [comment]
#please-close
