### ISSUE TITLE
Graftabl not found though it is listed in the "help" command

### ISSUE THREAD

**Issue by d-c-d** [MicrosoftDocs/windowsserverdocs#4171]
[Enter feedback here]

( got to this page searching for "help graftabl"  )
The Help command indicates that help is available for  GRAFTABL

C:\Windows\system32>help | find "GRAF"
GRAFTABL       Enables Windows to display an extended character set in

C:\Windows\system32>graftabl /?
'graftabl' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\system32>ver

Microsoft Windows [Version 10.0.18362.720]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bcda751-29e6-5541-0bcd-7b3f7a5e9d94
* Version Independent ID: 24314f2c-5492-10da-deac-fc97f88dc671
* Content: [graftabl](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/graftabl)
* Content Source: [WindowsServerDocs/administration/windows-commands/graftabl.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/graftabl.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
I have not done enough research on this command yet, but it looks like this command is intended for use on Cathode-ray tube monitors (pre-LCD graphics monitors).

Some pages seem to suggest that the last time this command was available in Windows was with Windows XP, back when most of us end users still could not easily afford flat panel displays.

Some of the information around on various web pages also indicate that this command would mostly only be useful if you set up the OS to start with `CONFIG.SYS` and `AUTOEXEC.BAT` just like in the 1990s with Windows 3.1 and Windows 95.

I am tempted to believe that this command should be retired from the pages as a deprecated and removed command, maybe only useful up to and including Windows XP.

**Comment by illfated** [comment]
BTW, I can confirm that the name `GRAFTABL` and its description still exists in the extended text for the cmd Help command:
(relevant snippet)
```
GOTO           Directs the Windows command interpreter to a labeled line in
               a batch program.
GPRESULT       Displays Group Policy information for machine or user.
GRAFTABL       Enables Windows to display an extended character set in
               graphics mode.
HELP           Provides Help information for Windows commands.
ICACLS         Display, modify, backup, or restore ACLs for files and
               directories.
```
`Microsoft Windows [Version 10.0.18363.752]`

![image](https://user-images.githubusercontent.com/38162891/79385335-b2b8c000-7f68-11ea-967d-d426def25e77.png)

**Comment by osirisgothra** [comment]
This is a super-duper old command for super-duper old hardware, most of us weren't bothering with using it  even in the early 90s, though it still worked at that time (in DOS). Another example of documentation neglect despite the obscene budget and manpower they have for documentation updates. GRAFTABL was mainly needed for people who were not using plain-jane MSDOS (usually non-US, non-EU). Think of it as a (bad) attempt to solve certain problems before lo and behold Unicode (and later finally, UTF-8) came to be. Back then, locales and encoding was all over the place, in a manner of speaking.

 DOS constantly was trying to solve problems the Unix-like systems had already solved at the time, in their different "own" way. The need to be able to text documents from these other systems lead to stuff like GRAFTABL, ANSI.SYS and other such weird sometimes-works-sometimes-not drivers for locale/character support. It is nice they finally, in the end, realized that character sets, locales, and languages go hand-in-hand.  

But hey, they also thought 640k was more memory than anyone would ever need, too.  GRAFTABL was not used so much though, as it was an external file and programmers much preferred to change character sets as needed with their own proprietary code, internally (back then, such things could be done easily, not now though).                                                 

It is possible GRAFTABL is left alone for nostalgic reasons, however. You know programmers love their nostalgia.

**Comment by jsuelwald** [comment]
I'd like to re-open this issue because this is still the case in "Microsoft Windows [Version 10.0.19045.4046]"
