### ISSUE TITLE
typo in LogFileName

### ISSUE THREAD

**Issue by bimimicah** [MicrosoftDocs/windowsserverdocs#4173]
"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Safer\ CodeIdentifiers"

String Value: NameLogFile path to NameLogFile      &lt;----- *these should be LogFileName*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f04afba8-26a0-64ac-1e64-9f4e7db60857
* Version Independent ID: 41404a21-cc7e-eaea-86d6-107d221aa7cb
* Content: [Determine Allow-Deny List and Application Inventory for Software Restriction Policies](https://docs.microsoft.com/en-us/windows-server/identity/software-restriction-policies/determine-allow-deny-list-and-application-inventory-for-software-restriction-policies#feedback)
* Content Source: [WindowsServerDocs/identity/software-restriction-policies/determine-allow-deny-list-and-application-inventory-for-software-restriction-policies.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/software-restriction-policies/determine-allow-deny-list-and-application-inventory-for-software-restriction-policies.md)
* Product: **windows-server**
* Technology: **security-software-restriction-policies**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by bimimicah** [comment]
Also, the registry path should not contain a space next to CodeIdentifiers

**Comment by illfated** [comment]
(Ref. #4176 )

**Comment by bimimicah** [comment]
Seems to be fixed now, thanks :)
