### ISSUE TITLE
Not Work

### ISSUE THREAD

**Issue by SOACAt** [MicrosoftDocs/windowsserverdocs#4178]
This don't work
Grant-AdfsApplicationPermission -ClientRoleIdentifier "[Client ID from #3 above]" -ServerRoleIdentifier "[Identifier from #5 above]" -ScopeNames "allatclaims","openid"

Crashes store a client ID as GUID

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7537a789-92aa-2b04-30bf-028008948c62
* Version Independent ID: d07f261b-29af-74af-f5a6-b4f93aaf5bee
* Content: [Customize claims to be emitted in id_token when using OpenID Connect or OAuth with AD FS 2016 or later](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/custom-id-tokens-in-ad-fs#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/Custom-Id-Tokens-in-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/Custom-Id-Tokens-in-AD-FS.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @anandyadavMSFT
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Related issue: #4235 (E-mail and name claims not working / E-mail and name claims are still not received)

**Comment by illfated** [comment]
Hello again, @SOACAt . Did my changes to the document help you in any way? (mostly only formatting issues and renewing a link)

**Comment by IngridAtMicrosoft** [comment]
Issue seems to have been reopened via automation. Closing as there has been no response.
