### ISSUE TITLE
Broken link: Windows Server Insider Preview download page 

### ISSUE THREAD

**Issue by danblakely** [MicrosoftDocs/windowsserverdocs#4186]
https://www.microsoft.com/software-download/windowsinsiderpreviewserver 

"We are sorry, the page you requested cannot be found."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9561716a-21fa-fd7c-1807-300a0bc73869
* Version Independent ID: 7aed7f1a-3924-1bd2-6cd1-02a94382a392
* Content: [Use performance counters to diagnose application responsiveness problems on Remote Desktop Session Hosts](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-rdsh-performance-counters#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-rdsh-performance-counters.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-rdsh-performance-counters.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
Thank you for pointing out this issue. The correct link is https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewserver (note the locale /en-us/ part which is **unique** to most of the server OS download pages).

I will create a Pull Request to have this link corrected, as well as updating (in a proactive fashion) some outdated (but still working) links, to prevent those links from breaking in the future.
