### ISSUE TITLE
Wrong info about User Certificate

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windowsserverdocs#4188]
User certificate in Windows 10 1607+ doesn't support provider: Microsoft Platform Crypto Provider, autoenrolling will fail and manual request is going to show an error like CSP is not supported or valid. Windows 10 only supports Microsoft Software Key Storage Provider for IKEv2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76dd49bb-b86e-f5b7-35b9-a8d246d36fcb
* Version Independent ID: dedfa83f-36d6-f60b-e839-ba382c5a7372
* Content: [Configure the Server Infrastructure](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure#feedback)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by IngridAtMicrosoft** [comment]
GitHub issues for this repo are for reporting problems with documentation.  Please open a support ticket.
