### ISSUE TITLE
Device or Workstation certicate not mentioned

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windowsserverdocs#4189]
Principal requirement for IKEv2 is Device or Workstation Certificate, without it VPN doesn't connect. In RRAS to make IKEv2 connection works, option "Allow machine certificate for IKEv2" must be selected. Hint: NPS certificate template for Clients work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76dd49bb-b86e-f5b7-35b9-a8d246d36fcb
* Version Independent ID: dedfa83f-36d6-f60b-e839-ba382c5a7372
* Content: [Configure the Server Infrastructure](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure#feedback)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by IngridAtMicrosoft** [comment]
Contributor no longer account on GitHub to contact for clarification.
