### ISSUE TITLE
VPN Client error connecting, due to incomplete SAN in VPN Server certificate

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windowsserverdocs#4190]
Actually is a known issue, that if a client is showing errors about machine certificate, and client certificate is well configured, Alternative Names -&gt; DNS for VPN Server certificate must contain Public FQDN and even VPN Server internal IPs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76dd49bb-b86e-f5b7-35b9-a8d246d36fcb
* Version Independent ID: dedfa83f-36d6-f60b-e839-ba382c5a7372
* Content: [Configure the Server Infrastructure](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure#feedback)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by IngridAtMicrosoft** [comment]
Cannot contact ghost contributor about clarification.
