### ISSUE TITLE
Is LAN routing required for Static Address Pool in different subnet?

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windowsserverdocs#4193]
When Static Address Pool is configured in different subnet. Is there a need to enable LAN routing? or internal routing can be achieved by static routing. Please add info.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f49053-d4b0-03cd-2572-366af6d2b943
* Version Independent ID: 05ec3fce-bcc0-3833-82fd-96abc10b9dda
* Content: [Configure the Remote Access Server for Always On VPN](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-ras)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-ras.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-ras.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by IngridAtMicrosoft** [comment]
Ghost contributor.
