### ISSUE TITLE
I don't have a /s option for EFI. Why not?

### ISSUE THREAD

**Issue by BullShark** [MicrosoftDocs/windowsserverdocs#4196]
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mountvol

Looking at the link, I should have an /s option for EFI, but there is none.

```
Administrator@WIN8 MINGW64 ~
$ mountvol /?
Creates, deletes, or lists a volume mount point.

MOUNTVOL [drive:]path VolumeName
MOUNTVOL [drive:]path /D
MOUNTVOL [drive:]path /L
MOUNTVOL [drive:]path /P
MOUNTVOL /R
MOUNTVOL /N
MOUNTVOL /E

    path        Specifies the existing NTFS directory where the mount
                point will reside.
    VolumeName  Specifies the volume name that is the target of the mount
                point.
    /D          Removes the volume mount point from the specified directory.
    /L          Lists the mounted volume name for the specified directory.
    /P          Removes the volume mount point from the specified directory,
                dismounts the volume, and makes the volume not mountable.
                You can make the volume mountable again by creating a volume
                mount point.
    /R          Removes volume mount point directories and registry settings
                for volumes that are no longer in the system.
    /N          Disables automatic mounting of new volumes.
    /E          Re-enables automatic mounting of new volumes.

Possible values for VolumeName along with current mount points are:

    \\?\Volume{97a9b140-5847-11e2-be65-806e6f6e6963}\
        D:\

    \\?\Volume{97a9b13f-5847-11e2-be65-806e6f6e6963}\
        C:\

    \\?\Volume{dea31453-585d-11e2-be67-806e6f6e6963}\
        G:\
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ea142d6-a7d5-77e6-aaca-eebf0fe6dacc
* Version Independent ID: 80c0cd82-d0e8-3138-8bf8-54f4d8fb1467
* Content: [mountvol](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mountvol)
* Content Source: [WindowsServerDocs/administration/windows-commands/mountvol.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/mountvol.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
I just tested this on my Windows 10 Home (x64) Laptop PC, my workplace (via remote) Windows 10 Professional (x64) desktop PC and my company's Windows Server 2016 Standard (both VM and hardware OS login sessions).

Only my workplace server (HP ProLiant DL series) running Windows Server 2016 (both within the VM and on hardware) shows this option. None of the Windows 10 versions display this option.

My conclusion: it is probably not available unless you are using Server hardware and Server EFI/UEFI BIOS.

**Comment by illfated** [comment]
Correction: "/s should work when an ESP (EFI System Partition) exists. Not just Itanium Systems" (**Update mountvol.md - /s switch clarification**) #2820

**Comment by BullShark** [comment]
I forgot why I was even trying to use this command, sorry.

**Comment by illfated** [comment]
No worries, it is usually a result from creative thinking. Unfortunately, not all solutions work as we hoped they would. Then again, it is a fair opportunity to get a checkup for the topic detail itself.
