### ISSUE TITLE
How much maximum number of virtual processors?

### ISSUE THREAD

**Issue by 0xbadfca11** [MicrosoftDocs/windowsserverdocs#4197]
> Windows Server, version 1909
> **240** for generation 2; 64 for generation 1
> **Greater than 240 virtual processor support** requires Windows Server, version 1903 or later guest operating systems.

Maximum number of virtual processors in doc has not increased.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb311bf2-8548-000e-36a6-4ea4c01ac953
* Version Independent ID: d2966c17-b877-a879-bd7f-39c3758f0a77
* Content: [Supported Windows guest operating systems for Hyper-V on Windows Server](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-windows-guest-operating-systems-for-hyper-v-on-windows#feedback)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Supported-Windows-guest-operating-systems-for-Hyper-V-on-Windows.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/Supported-Windows-guest-operating-systems-for-Hyper-V-on-Windows.md)
* Product: **windows-server**
* Technology: **compute-hyper-v**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by craigcaseyMSFT** [comment]
Hello @0xbadfca11,

Thanks for contacting Microsoft. We value your feedback.

Documentation changes have been made to clarify and acknowledge this issue. The doc changes will be live after the next business day.

Thank you again and have a most pleasant day.
#please-close
