### ISSUE TITLE
Examples missing quotes

### ISSUE THREAD

**Issue by uecasm** [MicrosoftDocs/windowsserverdocs#4198]
The examples on this page do not actually work, as they are missing the required quotes around the /c parameter.
They also redundantly specify the default /m parameter (and there is a typo in the table above where the default for this parameter is mentioned).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b1a260b-a509-ffcd-1132-4c1fb7694e6e
* Version Independent ID: a14e97c6-be2f-3a3a-7452-3fcc734fa63d
* Content: [forfiles](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/forfiles)
* Content Source: [WindowsServerDocs/administration/windows-commands/forfiles.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/forfiles.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
(ref. #4310 )

**Comment by illfated** [comment]
From the ticket https://github.com/MicrosoftDocs/windowsserverdocs/issues/4310#issue-614944414 :

> If you copy the examples verbatim, forfiles will return the error "ERROR: Invalid syntax. '/c' option is not allowed more than '1' time(s)."
> 
> The forfiles command does not allow multiple "/c " parameters, yet all of your examples utilize "/c cmd /c"
> 
Note to self: **open a Pull Request to edit the affected command examples.**

**Comment by illfated** [comment]
By the way, I took the time to acquire the help text from a production Windows Server 2016 Standard, just to make sure my efforts will be compromised or polluted by Windows 10 changes to the command features and descriptions (quite a bit more extensive than the Server version of Forfiles). Attached file: "forfiles-help.txt" in link and view the "**Details**" below for the current help text content:

[forfiles-help.txt](https://github.com/MicrosoftDocs/windowsserverdocs/files/4653981/forfiles-help.txt)


<details>

```
FORFILES [/P pathname] [/M searchmask] [/S]
         [/C command] [/D [+ | -] {dd.MM.yyyy | dd}]

Description:
    Selects a file (or set of files) and executes a 
    command on that file. This is helpful for batch jobs.

Parameter List:
    /P    pathname      Indicates the path to start searching.
                        The default folder is the current working
                        directory (.).

    /M    searchmask    Searches files according to a searchmask.
                        The default searchmask is '*' .

    /S                  Instructs forfiles to recurse into
                        subdirectories. Like "DIR /S".

    /C    command       Indicates the command to execute for each file.
                        Command strings should be wrapped in double
                        quotes. 

                        The default command is "cmd /c echo @file".

                        The following variables can be used in the
                        command string:
                        @file    - returns the name of the file.
                        @fname   - returns the file name without
                                   extension.
                        @ext     - returns only the extension of the
                                   file.
                        @path    - returns the full path of the file.
                        @relpath - returns the relative path of the
                                   file.
                        @isdir   - returns "TRUE" if a file type is
                                   a directory, and "FALSE" for files.
                        @fsize   - returns the size of the file in
                                   bytes.
                        @fdate   - returns the last modified date of the
                                   file.
                        @ftime   - returns the last modified time of the
                                   file.

                        To include special characters in the command 
                        line, use the hexadecimal code for the character
                        in 0xHH format (ex. 0x09 for tab). Internal
                        CMD.exe commands should be preceded with
                        "cmd /c".

    /D    date          Selects files with a last modified date greater
                        than or equal to (+), or less than or equal to
                        (-), the specified date using the
                        "dd.MM.yyyy" format; or selects files with a
                        last modified date greater than or equal to (+)
                        the current date plus "dd" days, or less than or
                        equal to (-) the current date minus "dd" days. A
                        valid "dd" number of days can be any number in
                        the range of 0 - 32768.
                        "+" is taken as default sign if not specified.

    /?                  Displays this help message.

Examples:
    FORFILES /?
    FORFILES  
    FORFILES /P C:\WINDOWS /S /M DNS*.* 
    FORFILES /S /M *.txt /C "cmd /c type @file | more"
    FORFILES /P C:\ /S /M *.bat
    FORFILES /D -30 /M *.exe
             /C "cmd /c echo @path 0x09 was changed 30 days ago"
    FORFILES /D 01.01.2001
             /C "cmd /c echo @fname is new since Jan 1st 2001"
    FORFILES /D +20.5.2020 /C "cmd /c echo @fname is new today"
    FORFILES /M *.exe /D +1
    FORFILES /S /M *.doc /C "cmd /c echo @fsize" 
    FORFILES /M *.txt /C "cmd /c if @isdir==FALSE notepad.exe @file"
```

</details>

**Comment by illfated** [comment]
(also ref. https://github.com/MicrosoftDocs/windowsserverdocs.es-es/issues/3)

**Comment by illfated** [comment]
@uecasm : Feel free to follow and/or comment in the Pull Request #4374 , in case I have missed something in need of correction, based on your ticket report.
