### ISSUE TITLE
more info on -recoverypassword option

### ISSUE THREAD

**Issue by timrobinson33** [MicrosoftDocs/windowsserverdocs#4200]
For the -recoverypassword option, specify whether you need to type in the dashes or not

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a504df6-57a1-96a8-e00b-971fd9a3ed0b
* Version Independent ID: a9fe4704-fc82-2eca-cfc2-981e805e73a6
* Content: [manage-bde unlock](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/manage-bde-unlock)
* Content Source: [WindowsServerDocs/administration/windows-commands/manage-bde-unlock.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/manage-bde-unlock.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @timrobinson33,

We value your feedback. 

A documentation change has been made clarifying this in the description & an example at the bottom of the page. In short, yes, it is required. Changes will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. #please-close
