### ISSUE TITLE
misleading

### ISSUE THREAD

**Issue by tcsx** [MicrosoftDocs/windowsserverdocs#4202]
"You can use wildcard characters (* and ?) in either FileName parameter. Characters that are represented by wildcard characters in FileName2 will be identical to the corresponding characters in FileName1."

This is misleading.  "ren ab* d*" would just rename abc.txt to dbc.txt. It is counterintuitive and stupid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54d66847-a721-6cca-98c5-8e52499686af
* Version Independent ID: 87f1e6a4-dafa-11a8-ea95-806a33f65e4b
* Content: [ren](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/ren#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/ren.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/ren.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Confirmed. Using the Rename command, regardless of "run as Administrator" or regular user, only the same number of characters as specified in FileName2 will be replaced in FileName1.

This comment is based on simple preliminary testing. No further search for documentation to validate this has been performed so far.

**Comment by illfated** [comment]
Actually, there is a really interesting post on Stack Exchange/SuperUser:
- https://superuser.com/questions/475874/how-does-the-windows-rename-command-interpret-wildcards
(this post is quite useful for coders or batch script writers)

Based on reading that page, I find it fairly reasonable to state the following:
1. FileName1 = source mask. FileName1 (source mask) will only be used as a source to find the target files before renaming them.
2. FileName2 = target mask. FileName2 (target mask) will be the only parameter defining how many characters will be changed in the resulting file name.

There is also a special case mentioned in the linked post, where a rename happens twice. That paragraph is named: **Possible RENAME bug - a single command may rename the same file twice!**

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. A documentation change was made and is live. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
