### ISSUE TITLE
Focus

### ISSUE THREAD

**Issue by nicechocolate** [MicrosoftDocs/windowsserverdocs#4204]
Page tells us how to determine focus, but NOT how to set it.

So I just typed "list disk" and I have a list of the physical disks on my system and NONE has focus, no little "*" on any of them.  Is it select, set ID, assign, add or something that isn't here at all?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bca0f8f7-da0d-6340-bf63-f269be5f64d1
* Version Independent ID: 39758423-e92d-d2db-88f3-260dc5a1a26a
* Content: [DiskPart](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/diskpart#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/diskpart.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/diskpart.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Not sure if the page has changed anything since you posted this issue, but to me, it looks like you have to use the (diskpart) **select** command to set focus.

**Comment by illfated** [comment]
By the way, I am working on a plan to have the DiskPart links updated and grouped in the TOC (Table Of Contents) on the left hand side of the web page. Not sure how soon or how quick it will be realized, but it needs some love to be useful at all. Recommendations and suggestions are welcome!

**Comment by illfated** [comment]
Select. Select is the command you are looking for (in case you have not already found the answer).

**Comment by illfated** [comment]
#please-close
