### ISSUE TITLE
Smartcard logon support

### ISSUE THREAD

**Issue by paroola** [MicrosoftDocs/windowsserverdocs#4206]
Does this client support smartcard logon to remote servers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acc42a8f-2623-4352-7cc4-70f0f61e9d89
* Version Independent ID: 97d8b54b-5e7d-098b-4fb7-e8f6e0b30389
* Content: [Get started with the Windows Store client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windows)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windows.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windows.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
Hello @paroola. GitHub issues for this repo are for reporting problems with our documentation.  Please open a support ticket or post your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html).
