### ISSUE TITLE
Support of AlwaysOn VPN in a Cluster

### ISSUE THREAD

**Issue by nathanmaslin** [MicrosoftDocs/windowsserverdocs#4208]
Hi Team

This documentation seems to be specific for DirectAccess, if there similar documentation on how to do with for AlwaysOn VPN?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7588744-e1a1-7038-d9e1-da15da049176
* Version Independent ID: 41df6ff7-603e-3b37-e05a-fc79e9565a03
* Content: [Plan a Remote Access Cluster Deployment](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/ras/cluster/plan/plan-a-remote-access-cluster-deployment#feedback)
* Content Source: [WindowsServerDocs/remote/remote-access/ras/cluster/plan/Plan-a-Remote-Access-Cluster-Deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/ras/cluster/plan/Plan-a-Remote-Access-Cluster-Deployment.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by JLOPS** [comment]
Please see https://social.technet.microsoft.com/Forums/windowsserver/en-US/60346461-2c23-44e3-8204-228e85ddefdf/high-availability-for-always-on-vpn?forum=winserverNIS#9186e914-310b-4896-aa98-71040b7bde8a

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
Addressed in comments.
