### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Regen379** [MicrosoftDocs/windowsserverdocs#4214]
...the KMS host registers its _vmlcs SRV record...
should be
...the KMS host registers its _vlmcs SRV record...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08ba6d1a-0f8e-7796-073f-f431c4421f6c
* Version Independent ID: c88cc509-3ccc-dc6d-f0b2-098303d178c6
* Content: [Guidelines for troubleshooting DNS-related activation issues](https://docs.microsoft.com/en-us/windows-server/get-started/common-troubleshooting-procedures-kms-dns#feedback)
* Content Source: [WindowsServerDocs/get-started/common-troubleshooting-procedures-kms-dns.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/common-troubleshooting-procedures-kms-dns.md)
* Technology: **server-general**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by illfated** [comment]
Thank you for pointing out that typo. Sorry for the delay. I will open a PR to have that typo resolved.

**Comment by illfated** [comment]
There you go, PR #4481 is ready for review. Feel free to have a look.
