### ISSUE TITLE
server info

### ISSUE THREAD

**Issue by Anuya1** [MicrosoftDocs/windowsserverdocs#4215]
it is useful thanks for info

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a0806c0-628b-9769-c209-98dfd6373a49
* Version Independent ID: 5dd7c49f-ccf6-0e02-0c5f-88f74bf0a9f8
* Content: [Windows Server technical content for IT Administrators - Windows Server](https://docs.microsoft.com/en-us/windows-server/windows-server-versions#feedback)
* Content Source: [WindowsServerDocs/windows-server-versions.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/windows-server-versions.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
Thank you for the nice words. Duly noted.

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
