### ISSUE TITLE
info

### ISSUE THREAD

**Issue by Anuya1** [MicrosoftDocs/windowsserverdocs#4216]
thanks a lot. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 505fe07b-6fdd-4887-3c8b-15405c5d8308
* Version Independent ID: 25645df2-0ffb-4cc3-a8d2-5466edd309fb
* Content: [Overview about Windows Server upgrades](https://docs.microsoft.com/en-us/windows-server/upgrade/upgrade-overview)
* Content Source: [WindowsServerDocs/upgrade/upgrade-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/upgrade/upgrade-overview.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @RobHindman
* Microsoft Alias: **robhind**

**Comment by illfated** [comment]
On behalf of the MS Docs team (even though I am not one of them), you are welcome. Thank you for the nice remark.

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close

**Comment by Anuya1** [comment]
What is this

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by illfated** [comment]
@Anuya1 : That is only a notification about this ticket being closed (check your notification settings if you don't want emails).
