### ISSUE TITLE
Registry path incorrect

### ISSUE THREAD

**Issue by Regen379** [MicrosoftDocs/windowsserverdocs#4218]
Both the "**Verify the configuration of the KMS host**" and "**Configure the KMS host to publish in multiple DNS domains**" sections list the Registry path as "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SL", however in my testing (on Win2008R2 and Win2012R2) running "cscript slmgr.vbs /cdns" and "cscript slmgr.vbs /sdns" changes the value of DisableDnsPublishing in "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SoftwareProtectionPlatform". "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SL" does not exist in Win2008R2 and later.

https://docs.microsoft.com/en-us/previous-versions/tn-archive/ff793405(v=technet.10)?redirectedfrom=MSDN says that "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SL" was the location in Vista/2008. From Win7/2008R2 onward it is "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SoftwareProtectionPlatform". I have just verified this on a Win2008 and a Win2008R2 server.

Can we please update this documentation to show the different Registry paths for the different versions of Windows. For example:

**Verify the configuration of the KMS host**
2. Locate the HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SL subkey, and check the value of the DisableDnsPublishing entry. This entry has the following possible values:

could be changed to
2. Locate the following subkey:
Windows Vista/2008: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SL
Windows 7/2008R2 and later:  HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SoftwareProtectionPlatform
and check the value of the DisableDnsPublishing entry. This entry has the following possible values:

Likewise for the other section
**Configure the KMS host to publish in multiple DNS domains**
2. Locate and then select the HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SL subkey.

could be changed to
2. Locate and then select the following subkey:
Windows Vista/2008: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SL
Windows 7/2008R2 and later:  HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SoftwareProtectionPlatform

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08ba6d1a-0f8e-7796-073f-f431c4421f6c
* Version Independent ID: c88cc509-3ccc-dc6d-f0b2-098303d178c6
* Content: [Guidelines for troubleshooting DNS-related activation issues](https://docs.microsoft.com/en-us/windows-server/get-started/common-troubleshooting-procedures-kms-dns#feedback)
* Content Source: [WindowsServerDocs/get-started/common-troubleshooting-procedures-kms-dns.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/common-troubleshooting-procedures-kms-dns.md)
* Technology: **server-general**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by Regen379** [comment]
Update:
I've just discovered at https://docs.microsoft.com/en-us/previous-versions/tn-archive/ff793405(v=technet.10)?redirectedfrom=MSDN that "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SL" was the location in Vista/2008. From Win7/2008R2 onward it is "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SoftwareProtectionPlatform". I have just verified this on a Win2008 and a Win2008R2 server.

Based on this new information, I ask that this page be updated to show the different locations for the different versions of Windows.

As far as I can tell DisableDnsPublishing is a valid option in Win2008 (because slmgr /sdns and /cdns are valid options), so it is appropriate to list both Registry locations (for the different Windows versions) in the section "Verify the configuration of the KMS host".

However, as far as I can tell DnsDomainPublishList did not become a valid option until a version after Win2008R2, so it does not make sense to list the path "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SL" in the section "Configure the KMS host to publish in multiple DNS domains", only "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SoftwareProtectionPlatform" should be listed. I am not 100% certain about this, please verify.

**Comment by IngridAtMicrosoft** [comment]
#assign:dknappettmsft

**Comment by dknappettmsft** [comment]
Thanks for raising this one as well.  I've updated the registry key and a note for the previous versions, and it should be visible in a few hours.

#please-close
