### ISSUE TITLE
Ten Laws of Immutable Security Link does not work.

### ISSUE THREAD

**Issue by jonsabbs** [MicrosoftDocs/windowsserverdocs#4220]
This link no longer works.  I think the page has been removed - which is a shame, it was a great resource

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96a7fa52-cf7d-5e1f-deb6-bae5d9d3ddda
* Version Independent ID: b4043e84-61e0-23d1-6405-693b30367e65
* Content: [Implementing Least-Privilege Administrative Models](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/implementing-least-privilege-administrative-models#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Implementing-Least-Privilege-Administrative-Models.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Implementing-Least-Privilege-Administrative-Models.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by illfated** [comment]
Sorry for the long wait, would this be the page you are looking for?
- https://docs.microsoft.com/en-us/previous-versions//cc722488(v=technet.10)

**Comment by illfated** [comment]
There is also this similar page: https://docs.microsoft.com/en-us/previous-versions//cc722487(v=technet.10)
(Not sure how much difference there is between them, but maybe you will know more about it.)

**Comment by jonsabbs** [comment]
It is the second link that is the correct one - thanks!

**Comment by illfated** [comment]
Thank you for your positive reply. I will look into this later and see if I can post a pull request to have the page updated accordingly.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
