### ISSUE TITLE
Storage Migration Service Proxy not working on Windows Server 2019 Cluster

### ISSUE THREAD

**Issue by Sergong** [MicrosoftDocs/windowsserverdocs#4222]
Hi,
We are trying to plan a migration from a 3-node Windows Server 2008 R2 Cluster to a 3-node Windows Server 2019 (1809) Cluster with updates up to 2020-03. When setting up the Transfer stage and doing a validation we get the following 2 warning:
The credential has administrative privileges; Warning: Action isn't available remotely
The destination proxy is registered; Warning: The destination proxy wasn't found.

Why are we getting these warnings even though the Proxy service is installed running and registered on all nodes of the destination 2019 Cluster?

We did a transfer regardless of the warnings and it took over 8 hours for 1.4TB of data (16K files). My guess is that it took this long because it wasn't able to use the proxy service on the destination cluster?
There were 101 files that did not transfer but the error log has not details on the error that prevented the transfer. The state of transfer shows as "couldn't transfer some devices". What does devices actually refer to (Volumes, Shares)?

Thanks,
Serge

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f348eda3-6195-cd36-9bf9-769b6c37927b
* Version Independent ID: a2255385-394e-7ee0-a90d-dcaca017a3d4
* Content: [Storage Migration Service known issues](https://docs.microsoft.com/en-us/windows-server/storage/storage-migration-service/known-issues#feedback)
* Content Source: [WindowsServerDocs/storage/storage-migration-service/known-issues.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-migration-service/known-issues.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @nedpyle
* Microsoft Alias: **nedpyle**

**Comment by nedpyle** [comment]
Howdy. This would only be expected if you couldn't actually reach the SMS proxy service on the destination (firewall blocked, service off, etc.) or if they were version mismatched (ex: Orchestrator is fully patched and destination is a vanilla RTM WS2019 machine that was never patched). 

I'd recommend opening a support case here with MS Support to investigate if none of those things appear to be the problem. It's unexpected and proxy supports clusters just fine.

- Ned

**Comment by Sergong** [comment]
Hi,
Thanks for the pointers. We've changed the set up slightly and are now running the Storage Migration Services on the Destination Cluster (as opposed to the Orchestrator server we'd set up). Now when doing a transfer, the Proxy is recognised. This brought down the time to less than 3 hours! 
Thanks!
Serge

**Comment by nedpyle** [comment]
Awesome, thanks for the followup

**Comment by nedpyle** [comment]
@steved0x why was this reopened

**Comment by IngridAtMicrosoft** [comment]
@nedpyle I have noticed that a LOT of issues were closed and reopened on Oct 28th, 2020.  I suspect that it was a bulk exercise.  Closing.
#please-close
