### ISSUE TITLE
Service name has changed between Windows versions

### ISSUE THREAD

**Issue by Regen379** [MicrosoftDocs/windowsserverdocs#4224]
In the section "Configure the KMS host to publish in multiple DNS domains"
...restart the Software Licensing service...
In Vista/2008 the service was named Software Licensing.
In Win7/2008R2 and later (up until at least Win2016) it is named Software Protection.
Can this please be updated to show the different names for the service in the different Windows versions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08ba6d1a-0f8e-7796-073f-f431c4421f6c
* Version Independent ID: c88cc509-3ccc-dc6d-f0b2-098303d178c6
* Content: [Guidelines for troubleshooting DNS-related activation issues](https://docs.microsoft.com/en-us/windows-server/get-started/common-troubleshooting-procedures-kms-dns#configure-the-kms-host-to-publish-in-multiple-dns-domains)
* Content Source: [WindowsServerDocs/get-started/common-troubleshooting-procedures-kms-dns.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/common-troubleshooting-procedures-kms-dns.md)
* Technology: **server-general**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by IngridAtMicrosoft** [comment]
#assign:dknappettmsft

**Comment by dknappettmsft** [comment]
Thanks for the feedback This has been changed and should be visible in the next few hours.

#please-close
