### ISSUE TITLE
The netcfg option "-d" is not documented

### ISSUE THREAD

**Issue by Scherlac** [MicrosoftDocs/windowsserverdocs#4225]
Hi,

I found on many places the netcfg with option "-d" like here:

https://social.technet.microsoft.com/Forums/azure/en-US/53ab5cd6-3467-4c4b-bbba-5b8dd8c17c1e/network-failure-caused-by-array-ssl-vpn-and-hard-to-repair?forum=win10itpronetworking

https://social.technet.microsoft.com/Forums/en-US/f7e4af56-900e-4879-ab34-9d50f4e345a9/cant-create-any-virtual-switch-in-hyperv-failed-while-creating-virtual-ethernet-switch-0x800401f3?forum=win10itprovirt

We have the same issue like the second one, but we are working over corporate VPN and it is not easy to get into the office right now. 

Can you please tell us what exactly the "-d" option does and if it is safe with "Cisco Any Connect"?

Thanks!

**Comment by illfated** [comment]
Well, if you look at issue ticket #3990 (**/b option not documented**), I posted the following:

> Please note that running the `netcfg` command on Windows 10 version 1909 will list more options in the examples than those present on this page, as well as using a dash (`-`) character instead of the slash (`/`) as the indicating character for that parameter.

<details>

```
Microsoft Windows [Version 10.0.18363.693]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>netcfg /?
netcfg [-v] [-winpe] [-l <full-path-to-component-INF>] -c <p|s|c>
       -i <comp-id>

    -winpe installs TCP/IP, NetBIOS and Microsoft Client for Windows
           preinstallation environment
    -l     provides the location of INF
    -c     provides the class of the component to be installed (p == Protocol,
           s == Service, c == Client)
    -i     provides the component ID

    The arguments must be passed in the order shown.

    Examples:

    netcfg -l c:\oemdir\myprot.inf -c p -i myprot

        Installs protocol 'myprot' using c:\oemdir\myprot.inf

    netcfg -c s -i MS_Server

        Installs service 'MS_Server'

OR

netcfg [-v] -winpe

    Example:

    netcfg -v -winpe

        Installs TCP/IP, NetBIOS, and Microsoft Client for Windows
        preinstallation environment

OR

netcfg [-v] -q <comp-id>

    Example:

    netcfg -q MS_IPX

        Displays if component 'MS_IPX' is installed

OR

netcfg [-v] -u <comp-id>

    Example:

    netcfg -u MS_IPX

        Uninstalls component 'MS_IPX'

OR

netcfg [-v] -s <a|n>

    -s  provides the type of components to show (a == adapters,
        n == net components)

    Example:

    netcfg -s n

        Shows all installed net components

OR

netcfg [-v] -b <comp-id>

    Example:

    netcfg -b ms_tcpip

        Shows binding paths containing 'MS_TCPIP'

OR

netcfg [-v] -m

    Example:

    netcfg -m

        Outputs the binding map to NetworkBindingMap.txt in the current directory.
        -v will also display the binding map to the console.

OR

netcfg -d

    Example:

    netcfg -d

        Performs a cleanup on all networking devices.
                This will require a reboot.

OR

netcfg -x

    Example:

    netcfg -x

        Performs a cleanup on networking devices, skipping those without physical
        object names.
                This will require a reboot.

General Notes:
  -v    Run in verbose (detailed) mode
  -?    Displays this help information


C:\WINDOWS\system32>_
```

</details>

> Also, I don't know if this is indicative of this command being updated closer to what will be available on Windows Server 2019 (I don't have access to WS 2019 yet).

Based on what I posted in my previous ticket follow-up, I would like to show you this excerpt:

```
netcfg -d

    Example:

    netcfg -d

        Performs a cleanup on all networking devices.
                This will require a reboot.
```
My immediate thought is that you could use the mnemonic "delete" as a reminder of what the -d parameter does.

Unfortunately, I do not know the product Cisco AnyConnect at all, so I am unable to answer if the -d parameter is safe to use with Cisco AnyConnect. I can only suggest that you treat the -d parameter as a reset option to remove any settings you may have changed just to end up with a non-working scenario. Use commands like this with caution, as changes to a working production system can cause instability or a major malfunction, forcing you to reset what you did and start over again.

**Comment by illfated** [comment]
By the way, I presume you are referring to the following page:
- https://docs.microsoft.com/windows-server/administration/windows-commands/netcfg

**Comment by dknappettmsft** [comment]
Thanks for the feedback. I have added this parameter to the article. I can't answer about Cisco AnyConnect, my recommendation would be to ask Cisco.

#please-close
