### ISSUE TITLE
how to check which product I can use my KMS server to active

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/windowsserverdocs#4233]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/windowsserverdocs.zh-cn/issues/13

@VegetableBirdy commented 17 hours ago — with docs.microsoft.com
how to check which product I can use my KMS server to active.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc852932-b3f4-25ea-46b1-a9abb93fabac
* Version Independent ID: 5a03c0fc-a460-678d-c2ea-e9b8aeae6a75
* Content: [Guidelines for troubleshooting KMS](https://docs.microsoft.com/en-us/windows-server/get-started/activation-troubleshoot-kms-general#feedback)
* Content Source: [WindowsServerDocs/get-started/activation-troubleshoot-kms-general.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/activation-troubleshoot-kms-general.md)
* Technology: **server-general**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by IngridAtMicrosoft** [comment]
#assign:dknappettmsft

**Comment by dknappettmsft** [comment]
Hi @VegetableBirdy - there is a table on this page which provides the information you're after.

#please-close
