### ISSUE TITLE
complement a tree w/o overwriting; unclear terms

### ISSUE THREAD

**Issue by frandert** [MicrosoftDocs/windowsserverdocs#4234]
I am looking for a way to complement certain &lt;files&gt; (a list, possibly with wildcards, creating subdirectories where needed) in a &lt;destination&gt; path from a &lt;source&gt; path, not touching existing files within the &lt;destination&gt;. I have to admit, I'm bit lost.

One reason might be that this article uses numerous terms without further explaining them, e.g.

/xc: 'changed' 
/xx: 'extra'
/xl: "lonely"
/is: 'same'
/it: "tweaked" files.

The pure existence of the /is option creates an impression that the default behaviour might already be what I need, but I fear that's way too optimistic. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @frandert,

Thanks again for contacting Microsoft. We value your feedback. A documentation change was made and changes are live. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
