### ISSUE TITLE
E-mail and name claims not working

### ISSUE THREAD

**Issue by janouwehand** [MicrosoftDocs/windowsserverdocs#4235]
E-mail and name claims are still not received

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7537a789-92aa-2b04-30bf-028008948c62
* Version Independent ID: d07f261b-29af-74af-f5a6-b4f93aaf5bee
* Content: [Customize claims to be emitted in id_token when using OpenID Connect or OAuth with AD FS 2016 or later](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/custom-id-tokens-in-ad-fs#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/Custom-Id-Tokens-in-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/Custom-Id-Tokens-in-AD-FS.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @anandyadavMSFT
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Do you know what should be added to or changed on this page, to make the documentation more correct to avoid your issue happening again?

**Comment by illfated** [comment]
Related issue: #4178 (Not Work / This don't work)

**Comment by illfated** [comment]
@jansoftable : As you can see, my PR #4236 has now been merged and the changes are visible on the docs.microsoft.com page. Even though those changes are mostly only formatting issues and a renewed link, I don't know if this has been helpful to your issue, in any way. Would you be able to check the page again and see if any of those changes have been helpful to your issue?

**Comment by IngridAtMicrosoft** [comment]
Issue seems to have been reopened via automation.  Closing as there has been no response.
