### ISSUE TITLE
Windows server 2008 r2 upgrade

### ISSUE THREAD

**Issue by leowong1108** [MicrosoftDocs/windowsserverdocs#4238]
I have a license key of Windows server 2016, and I am using Windows server 2018 r2. When I upgrade to Windows server 2016, I need upgrade to 2012 first; Should I also have the Windows server 2012 license key for upgrade to 2016?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 465ee446-5e41-bd72-1305-976db9c3a4ec
* Version Independent ID: f7091237-826d-1e6e-d8f3-b688205f25fd
* Content: [Upgrade Windows Server 2012 to Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/upgrade/upgrade-2012-to-2016#feedback)
* Content Source: [WindowsServerDocs/upgrade/upgrade-2012-to-2016.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/upgrade/upgrade-2012-to-2016.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @RobHindman
* Microsoft Alias: **robhind**

**Comment by RobHindman** [comment]
I think that there is a typo in your question, perhaps?
The valid released versions of Windows Server are: 2003, 2003R2, 2008, 2008R2, 2012, 2012R2, 2016, and 2019. I think you are probably upgrading from 2012 to 2016, and want to know if you need a license key for 2012R2. The answer is that you do not. In the case of a single stand-alone server, you should be able to upgrade directly from 2012 to 2016 if you have the 2016 install media. I am assuming this is the case, and that you are not attempting to upgrade a failover cluster in-place. Please let me know if you have any additional questions.
-Rob.

**Comment by leowong1108** [comment]
My case is I would like to upgrade our server from Windows server 2008 R2 to 2016. I see the documents said it must be upgrade to 2012 R2 first. I want to confirm:

  1.  I need the license key of 2012 R2 for upgrade from 2008 R2 to 2012 R2?
  2.  Can I direct upgrade from 2008 R2 to 2012 R2?
  3.  After competed the upgrade from 2008 R2 to 2012 R2, no need to do any configuration then direct upgrade to 2016?
Regards,
Leo Wong
CLP Power
Technical Services Department/ Telecom Branch/ Telecom NMC
 CLASSIFICATION : PROPRIETARY

**Comment by RobHindman** [comment]
Hi Leo, if you are using Volume License (VL) media, then you do not need a key for 2012R2. If you are using regular media (not Volume License media), then you do need a key for 2012R2.
-Rob.

**Comment by leowong1108** [comment]
I am not using VL. But the objective is upgrade the Windows server from 2008 R2 to 2016, due to it could not direct upgrade from 2008 R2.
You means I need to buy a liense key of 2012 R2 for 2008 R2 upgrade to 2012 R2, then upgrade to 2016; even I have a liense key of 2016?
Regards,
Leo Wong
CLP Power
Technical Services Department/ Telecom Branch/ Telecom NMC
Office : (852) 2678 6796
Mobile: (852) 9884 7795
 CLASSIFICATION : PROPRIETARY

**Comment by leowong1108** [comment]
Hi, could you please update me any feedback, thanks.
Regards,
Leo Wong
CLP Power
Technical Services Department/ Telecom Branch/ Telecom NMC
Office : (852) 2678 6796
Mobile: (852) 9884 7795
 CLASSIFICATION : PROPRIETARY

From: Wong, Leo Wai Ho
Sent: Monday, April 27, 2020 3:43 PM
To: 'MicrosoftDocs/windowsserverdocs' <reply@reply.github.com>; MicrosoftDocs/windowsserverdocs <windowsserverdocs@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [MicrosoftDocs/windowsserverdocs] Windows server 2008 r2 upgrade (#4238)

I am not using VL. But the objective is upgrade the Windows server from 2008 R2 to 2016, due to it could not direct upgrade from 2008 R2.
You means I need to buy a liense key of 2012 R2 for 2008 R2 upgrade to 2012 R2, then upgrade to 2016; even I have a liense key of 2016?
Regards,
Leo Wong
CLP Power
Technical Services Department/ Telecom Branch/ Telecom NMC
Office : (852) 2678 6796
Mobile: (852) 9884 7795
 CLASSIFICATION : PROPRIETARY

**Comment by IngridAtMicrosoft** [comment]
Addressed. #please-close
