### ISSUE TITLE
Restrict Workstation Logon GPO

### ISSUE THREAD

**Issue by Frumpi** [MicrosoftDocs/windowsserverdocs#4240]
Currently, the Restrict Workstation Logon GPO lists "deny log on as a batch job", and "deny log on as a service".
It does not mention "deny log on locally". So these settings will not prevent privileged accounts from logging onto computers in the workstation ou.

The "deny log on locally" was correctly mention in the "Restrict Server Logon" GPO which leads me to believe it was accidently left out of the "Restrict Workstation Logon" GPO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1338ba44-301c-db33-d336-80dd50a77960
* Version Independent ID: 55abfb6d-3f63-9dce-1b70-36c6265fc37b
* Content: [Why Privileged Access Workstations can help secure your organization](https://docs.microsoft.com/en-us/windows-server/identity/securing-privileged-access/privileged-access-workstations#feedback)
* Content Source: [WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md)
* Product: **windows-server**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
