### ISSUE TITLE
Disable powershell logging

### ISSUE THREAD

**Issue by megatc101** [MicrosoftDocs/windowsserverdocs#4245]
Hi
The above example shows how to start windows PowerShell logging, and then says after the failure occurs "- Disable Windows Powershell logging. Collect the Event Trace Log file", but it is not clear how to actually do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43936fc2-1668-ab19-4310-16659b0bcc64
* Version Independent ID: 331225d9-d9e1-e0e5-0b71-3167a7ffeea9
* Content: [Troubleshooting DirectAccess](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/directaccess/troubleshooting-directaccess#feedback)
* Content Source: [WindowsServerDocs/remote/remote-access/directaccess/Troubleshooting-DirectAccess.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/directaccess/Troubleshooting-DirectAccess.md)
* Product: **windows-server**
* Technology: **networking-da**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by PRMerger19** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: ingridatmicrosoft 
gh issue comment 4208 -b ingridatmicrosoft

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by robinharwood** [comment]
We hugely appreciate your contribution, feedback, and support to our technical documentation.

We’ve phased out GitHub Issues on this repository as the feedback mechanism for content and have replaced it with a new feedback system. For more information see, [Content User Feedback](https://aka.ms/ContentUserFeedback). As part of this rollout, we are migrating your issue where our team will use your comments to improve the documentation experience. Unfortunately, this does mean you won't be able to access this issue after the migration is complete.

All issues will be migrated by Thursday 29th August 2024.

Once again, thank you for your valuable feedback, we hope you’ll continue to contribute using our new feedback system.
