### ISSUE TITLE
Missing character in words

### ISSUE THREAD

**Issue by caramel1995** [MicrosoftDocs/windowsserverdocs#4246]
Why are there missing character in words???

e.g

Cluster infras ruct re i prov ments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4150f10d-0ac3-0a70-8bcb-c7c2fa630f66
* Version Independent ID: 41670466-1fa8-d27c-965d-59e3ac362676
* Content: [What's new in Failover Clustering in Windows Server](https://docs.microsoft.com/en-us/windows-server/failover-clustering/whats-new-in-failover-clustering#feedback)
* Content Source: [WindowsServerDocs/failover-clustering/whats-new-in-failover-clustering.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/whats-new-in-failover-clustering.md)
* Product: **windows-server**
* Technology: **storage-failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Could you provide a screenshot of the issue you are seeing? I have tried searching for parts of the text you provided as an example, but I cannot find any of those issues.

The only line I could find resembling your example, is the following:
- **Cluster infrastructure improvements**

(below the first sub-heading)
(https://docs.microsoft.com/en-us/windows-server/failover-clustering/whats-new-in-failover-clustering#whats-new-in-windows-server-2019)

To me, it seems like you could have had a temporary browser refresh issue, showing local artifacts on your screen.

**Comment by caramel1995** [comment]
I just checked, it's fine now. Probably something to do with my browser.
