### ISSUE TITLE
Missing Permissions

### ISSUE THREAD

**Issue by vultureman** [MicrosoftDocs/windowsserverdocs#4249]
The permissions listed for "Folder Redirection Users" is missing 'Traverse Folder/Execute File'. Reference the ancient 2003 docs - https://support.microsoft.com/en-us/help/274443/how-to-dynamically-create-security-enhanced-redirected-folders-by-usin and just pretend that their overuse of Everyone is the same as "Folder Redirection Users" group in this writeup.

Without that permission, username folders and roaming folders are not automatically generated. Just confirmed that in my environment today when someone followed this document and I was unaware that helpdesk has been manually creating username folders for years.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3273d609-8cdb-19b8-6e72-e6c763904c47
* Version Independent ID: cf80c8f5-49f6-43a4-bb8e-b5849beb818b
* Content: [Deploy Folder Redirection with Offline FilesDeploy Folder Redirection with Offline Files](https://docs.microsoft.com/en-us/windows-server/storage/folder-redirection/deploy-folder-redirection#feedback)
* Content Source: [WindowsServerDocs/storage/folder-redirection/deploy-folder-redirection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/folder-redirection/deploy-folder-redirection.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by vultureman** [comment]
Hi, to be more clear on what I'm saying:

The old Server 2003 era KB article link I provided in the original post doesn't use a dedicated group for folder access, they just tell people to use "Everyone" instead. If you can replace their use of "Everyone" with "Security group of users needing to put data on share (Folder Redirection Users)" that you had in this newer documentation, you'd see that the missing security item is "Traverse Folder/Execute File (Apply onto: This Folder Only)" for the security group that gets folder redirection.

Let me know if you have any questions.

**Comment by illfated** [comment]
Fair point, your advice seems very practical and useful. I will look into this and see if I can make a Pull Request to suggest the necessary change.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub. I am just an external contributor.

**Comment by illfated** [comment]
By the way: I presume the reference section is as follows:
- https://docs.microsoft.com/en-us/troubleshoot/windows-server/user-profiles-and-logon/create-security-enhanced-redirected-folder#create-security-enhanced-redirected-folders

***

## Create security-enhanced redirected folders
To make sure that only the user and the domain administrators have permissions to open a particular redirected folder, do the following steps:

1. Select a central location in your environment where you would like to store Folder Redirection, and then share this folder. In this example, FLDREDIR, and HOMEDIR are used.

2. Set **Share Permissions** for the Everyone group to **Full Control**.

3. Use the following settings for NTFS Permissions:

- CREATOR OWNER - Full Control (Apply onto: Subfolders and Files Only)
- System - Full Control (Apply onto: This Folder, Subfolders, and Files)
- Domain Admins - Full Control (Apply onto: This Folder, Subfolders, and Files)
- Everyone - Create Folder/Append Data (Apply onto: This Folder Only)
- Everyone - List Folder/Read Data (Apply onto: This Folder Only)
- Everyone - Read Attributes (Apply onto: This Folder Only)
- Everyone - Traverse Folder/Execute File (Apply onto: This Folder Only)

4. Configure Folder Redirection Policy as outlined in Windows Help. Use a path similar to `\\server\FLDREDIR\%username%` to create a folder under the shared folder, FLDREDIR.

You can also configure a home folder "HOMEDIR" in a similar manner by copying a template user with a home folder like `\\server\HOMEDIR\%username%`, or create the user and folder with that name.

***

I also presume that the target section is as follows:
- https://docs.microsoft.com/en-us/windows-server/storage/folder-redirection/deploy-folder-redirection#required-permissions-for-the-file-share-hosting-redirected-folders

### Required permissions for the file share hosting redirected folders

| User Account  | Access  | Applies to  |
| --------- | --------- | --------- |
| System     | Full control        |    This folder, subfolders and files     |
| Administrators     | Full Control       | This folder only        |
| Creator/Owner     |   Full Control      |   Subfolders and files only      |
| Security group of users needing to put data on share (Folder Redirection Users)     |   List folder / read data *(Advanced permissions)* <p>Create folders / append data *(Advanced permissions)* <p>Read attributes *(Advanced permissions)* <p>Read extended attributes *(Advanced permissions)* <p>Read permissions *(Advanced permissions)*      |  This folder only       |
| Other groups and accounts     |  None (remove)       |         |

**Comment by vultureman** [comment]
Yes, I'm saying to add "Traverse Folder/Execute File" permission from the
reference section to the "Security group of users needing to put data on
share (Folder Redirection Users)" area in the target section. Without this
permission being applied to the security group for that folder
only, automatic user folder creation doesn't happen on first logon of a new
user.

**Comment by illfated** [comment]
Very good. I then presume it will be correct to add that permission in the same order as in the Troubleshooting document, perhaps something like the following (here on GitHub, but slightly converted to a more open table on docs.microsoft.com):

### Required permissions for the file share hosting redirected folders

| User Account  | Access  | Applies to  |
| --------- | --------- | --------- |
| System     | Full control        |    This folder, subfolders and files     |
| Administrators     | Full Control       | This folder only        |
| Creator/Owner     |   Full Control      |   Subfolders and files only      |
| Security group of users needing to put data on share (Folder Redirection Users)     |   List folder / read data *(Advanced permissions)* <p>Create folders / append data *(Advanced permissions)* <p>Read attributes *(Advanced permissions)* <p>Read extended attributes *(Advanced permissions)* <p>Read permissions *(Advanced permissions)* <p>Traverse Folder/Execute File *(Advanced permissions)*      |  This folder only       |
| Other groups and accounts     |  None (remove)       |         |

***

If you know a better way to sort this table, feel free to suggest your preferred view.

**Comment by vultureman** [comment]
Yes that is correct and formatted as I would have suggested. Thank you.

**Comment by illfated** [comment]
👍🏻 Thank you for confirming and for reporting the issue in the first place. That is the kind of contribution we need in this repository. 🙂

**Comment by illfated** [comment]
There you go. PR #5181 is now ready for review, comments, and improvement suggestions.
