### ISSUE TITLE
I am unable to Upgrade from 2016 to 2019

### ISSUE THREAD

**Issue by clgz2002** [MicrosoftDocs/windowsserverdocs#4250]
When I mount the iso and execute the setup I am unable to select the keep personal files and app option. It is grayed out.

This is the iso I am using for the 2019 Version:
en_windows_server_2019_updated_april_2020_x64_dvd_12d6dc63.iso

The Windows Server 2016 Version that is currently installed is: Windows Server 2016 Standard 10.0.14393 Build 14393 RETAIL Channel

**Comment by illfated** [comment]
Please close this ticket in favor of the correctly opened ticket #4251 (just copy this information over, if needed).

**Comment by illfated** [comment]
#please-close
