### ISSUE TITLE
I am unable to do an In Place Upgrade from 2016 to 2019

### ISSUE THREAD

**Issue by clgz2002** [MicrosoftDocs/windowsserverdocs#4251]
When I mount the iso and execute the setup I am unable to select the keep personal files and app option. It is grayed out.

This is the iso I am using for the 2019 Version:
en_windows_server_2019_updated_april_2020_x64_dvd_12d6dc63.iso

The Windows Server 2016 Version that is currently installed is: Windows Server 2016 Standard 10.0.14393 Build 14393 RETAIL Channel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 505fe07b-6fdd-4887-3c8b-15405c5d8308
* Version Independent ID: 25645df2-0ffb-4cc3-a8d2-5466edd309fb
* Content: [Overview about Windows Server upgrades](https://docs.microsoft.com/en-us/windows-server/upgrade/upgrade-overview#feedback)
* Content Source: [WindowsServerDocs/upgrade/upgrade-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/upgrade/upgrade-overview.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @RobHindman
* Microsoft Alias: **robhind**

**Comment by eliassal** [comment]
Me too, getting exactly the same thing

**Comment by ShadeByLesio** [comment]
I have the same issue. Have Windows 2016 Standard and with Windows 2019 Standard iso can't upgrade.

**Comment by IngridAtMicrosoft** [comment]
Thank you for your contribution to Windows Server documentation.  This appears to be a support request or can be address in our community forums.  #please-close

**Comment by IngridAtMicrosoft** [comment]
@clgz2002 Please open a support ticket.  GitHub issues for this repo are for reporting problems with our documentation. #please-close
