### ISSUE TITLE
Fsutil does not rely on WSL

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/windowsserverdocs#4254]
In the note at the top of this article, it states: "You have to enable Windows Subsystem for Linux before you can run Fsutil

On Server 2019, I see this:

```powershell
PS C:\Foo&gt; get-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
FeatureName      : Microsoft-Windows-Subsystem-Linux
DisplayName      : Windows Subsystem for Linux
Description      : Provides services and environments for running native user-mode Linux shells and tools on Windows.
RestartRequired  : Possible
State            : Disabled
CustomProperties :

PS C:\Foo&gt; fsutil
---- Commands Supported ----
8dot3name       8dot3name management
behavior        Control file system behavior
dax             Dax volume management
dirty           Manage volume dirty bit
file            File specific commands
fsInfo          File system information
hardlink        Hardlink management
objectID        Object ID management
quota           Quota management
repair          Self healing management
reparsePoint    Reparse point management
resource        Transactional Resource Manager management
sparse          Sparse file control
tiering         Storage tiering property management
transaction     Transaction management
usn             USN management
volume          Volume management
wim             Transparent wim hosting management
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18562b49-3654-a3ff-9617-3c59d50a7d1e
* Version Independent ID: 3e69bcb1-b1e6-f0ea-e861-5ced88fe6a24
* Content: [Fsutil](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/fsutil.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/fsutil.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @toklima
* Microsoft Alias: **toklima**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @doctordns,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made removing this from the note as WSL is not a dependancy for `fsutil` to run. Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
