### ISSUE TITLE
Grammar issues

### ISSUE THREAD

**Issue by tksh164** [MicrosoftDocs/windowsserverdocs#4255]
This issue come from the comments on my PR https://github.com/MicrosoftDocs/windowsserverdocs/pull/4132

----

> This fairly long sentence needs a tiny bit of grammar improvement, both for readability and logical understanding.
> 
> ```suggestion
> 8. To verify that the cluster set creation process created one SMB share (identified as Volume1 or > whatever the CSV folder is labeled with, the ScopeName being the Infrastructure File Server name and the path as both) on the Infrastructure SOFS for each cluster member's CSV volume:
> ```
> (this is just a minor adjustment, it is likely that this sentence could be improved upon even more)

_Originally posted by @illfated in https://github.com/MicrosoftDocs/windowsserverdocs/pull/4132#discussion_r417129732_

----

> ```suggestion
> 2. Once all the clusters have been created, use the following command to create the cluster set master:
> ```

_Originally posted by @illfated in https://github.com/MicrosoftDocs/windowsserverdocs/pull/4132#discussion_r417131486_

----

> ```suggestion
> 3. Use the command set below to add a Cluster Server to the cluster set:
> ```

_Originally posted by @illfated in https://github.com/MicrosoftDocs/windowsserverdocs/pull/4132#discussion_r417132551_

----

> ```suggestion
> 8. Cluster set debug logs can be collected for review.  Both the cluster set and cluster debug logs can be gathered for all members and the management cluster:
> ```

_Originally posted by @illfated in https://github.com/MicrosoftDocs/windowsserverdocs/pull/4132#discussion_r417133975_

----

> ```suggestion
> If you were to have not enough memory, CPU capacity, or disk space to add the virtual machine, you will receive the following error:
> ```

_Originally posted by @illfated in https://github.com/MicrosoftDocs/windowsserverdocs/pull/4132#discussion_r417134976_

----

> ```suggestion
> Once the virtual machine has been created, it will be displayed in Hyper-V manager on the specific node specified.  To add it as a cluster set virtual machine, and add it to the cluster, use the command below:
> ```

_Originally posted by @illfated in https://github.com/MicrosoftDocs/windowsserverdocs/pull/4132#discussion_r417135635_

----

> ```suggestion
> If you have added a cluster with existing virtual machines, the virtual machines will also need to be registered with Cluster sets. To register all those virtual machines at once, the command to use is:
> ```

_Originally posted by @illfated in https://github.com/MicrosoftDocs/windowsserverdocs/pull/4132#discussion_r417136546_

----

> ```suggestion
> However, the process is not yet complete, as the path to the virtual machine needs to be added to the cluster set namespace:
> ```

_Originally posted by @illfated in https://github.com/MicrosoftDocs/windowsserverdocs/pull/4132#discussion_r417136824_

----

> ```suggestion
> For example: An existing cluster is added and it has pre-configured virtual machines which reside on the local Cluster Shared Volume (CSV). The path for the VHDX would be something similar to "C:\ClusterStorage\Volume1\MYVM\Virtual Hard Disks\MYVM.vhdx".  A storage migration would need to be accomplished, as CSV paths are by design local to a single member cluster and will therefore not be accessible to the virtual machine once they are live migrated across member clusters. 
> ```
> 
> (mentally directed to the original text author:) One thing is to have problems writing in a easily readable style. It is something else entirely to explain scenarios in a cryptic way.

_Originally posted by @illfated in https://github.com/MicrosoftDocs/windowsserverdocs/pull/4132#discussion_r417140187_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cebe1cda-c758-b30b-bb43-161e1ca13b77
* Version Independent ID: 7fbdf25e-0ca7-f60d-8c0c-f12e18adafee
* Content: [Cluster Sets](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/cluster-sets)
* Content Source: [WindowsServerDocs/storage/storage-spaces/Cluster-Sets.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/Cluster-Sets.md)
* Product: **windows-server**
* Technology: **storage-spaces**
* GitHub Login: @JohnMarlin-MSFT
* Microsoft Alias: **johnmar**

**Comment by illfated** [comment]
Thank you very much for moving the grammar issues here. Well done, sir. 👍
