### ISSUE TITLE
Bug - Renewal of user certificate causes connection issue

### ISSUE THREAD

**Issue by endreigesund** [MicrosoftDocs/windowsserverdocs#4258]
By using this guide and the example config - evantually when the user certificate on the computer renews , further vpn connections will fail.
The user will get an error message saying: "There are no more files"

To fix the issue the user has to open properties of the vpn connection and press "Clear signin info". Then he can successfully connect again.

The error message is easy to reproduce - just manually renew the user certificate from mmc.exe - certificates.

After some investegation found this line in profile xml - as default in this guide:
&lt;RememberCredentials&gt;true&lt;/RememberCredentials&gt;

If i change this line in the profile to:
&lt;RememberCredentials&gt;false&lt;/RememberCredentials&gt;

The error won't reproduce, and connecting vpn works seamless after certificate renewal, as we would expect :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e14da1-102d-3ddf-e2a1-a20ce533b95a
* Version Independent ID: 374edc4c-f527-b7b7-c291-353928b97d8d
* Content: [Configure Windows 10 Client Always On VPN Connections](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections#feedback)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by IngridAtMicrosoft** [comment]
#assign:HeidiLohr

**Comment by anaharris-ms** [comment]
#please-close Fixed in: https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/3398
