### ISSUE TITLE
Converting evaluation to a current retail version works also when the server is a domain controller

### ISSUE THREAD

**Issue by tk-wfischer** [MicrosoftDocs/windowsserverdocs#426]
In the documentation file https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/Supported-Upgrade-Paths.md#converting-a-current-evaluation-version-to-a-current-retail-version there is the following text regarding converting an evaluation version to a retail version:

---
If the server is running an evaluation version of Windows Server 2016 Standard or Windows Server 2016 Datacenter, you can convert it to a retail version as follows:
1. If the server is a domain controller, you cannot convert it to a retail version. [...]
---

We have also documented it in this way in our wiki here https://www.thomas-krenn.com/de/wiki/Windows_Server_Evaluierungsversion_in_Vollversion_umwandeln

But meanwhile we got lots of feedback, that converting an Server (which is running an evaluation license and acting as a domain controller) to a retail version works. So I think that this restriction might not apply anymore.

Could you check this and update the doc in case that it is officially supported to convert an evaluation server (running as a domain controller) to a retail version?

Best regards,
Werner

**Comment by daveba** [comment]
Thanks for your feedback.  No, this is not supported.

**Comment by tk-wfischer** [comment]
Thank you for your feedback that this is not supported. I hereby close this issue as my question got answered and the doc does not need to be changed.
