### ISSUE TITLE
MRD: Please support Mac AppStore China region.

### ISSUE THREAD

**Issue by kzhui125** [MicrosoftDocs/windowsserverdocs#4260]
Please support Mac AppStore China region.

I can't download MRD in Mac AppStore using my account (region China). 

And Microsoft doesn't provide a dmg to download.

Please fix, thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0517ea6a-9417-31a8-39a5-f6128387fee5
* Version Independent ID: 7636ec70-e1dd-8c6b-516c-8af324d9f645
* Content: [Get started with the macOS client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-mac)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
Hello @kzhui125. GitHub issues for this repo are for reporting problems with our documentation.  Please open a support ticket or post your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html).
