### ISSUE TITLE
Suggested change to Title

### ISSUE THREAD

**Issue by cliffhobbs** [MicrosoftDocs/windowsserverdocs#4265]
[Enter feedback here]
Would it not be better to change the title to:

"Overview of Windows Server upgrades"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 505fe07b-6fdd-4887-3c8b-15405c5d8308
* Version Independent ID: 25645df2-0ffb-4cc3-a8d2-5466edd309fb
* Content: [Overview about Windows Server upgrades](https://docs.microsoft.com/en-us/windows-server/upgrade/upgrade-overview#feedback)
* Content Source: [WindowsServerDocs/upgrade/upgrade-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/upgrade/upgrade-overview.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @RobHindman
* Microsoft Alias: **robhind**

**Comment by illfated** [comment]
> [Enter feedback here]
> Would it not be better to change the title to:
> 
> "Overview of Windows Server upgrades"?
> 
Good point. "Overview about" is not good English, it sounds and reads mistranslated. I will make that suggestion by creating a PR to have it changed.

**Comment by illfated** [comment]
There you go. Feel free to comment, remark or suggest any changes you find necessary to add in my PR #4268 .
