### ISSUE TITLE
Syntax incorrect

### ISSUE THREAD

**Issue by mmmiller60** [MicrosoftDocs/windowsserverdocs#4267]
All examples showing Get-ItemProperty -Path HKLM:\Software\Microsoft\Windows NT\CurrentVersion are incorrect they must be corrected to Get-ItemProperty -Path "HKLM:\Software\Microsoft\Windows NT\CurrentVersion" without "" the commands do not work due to the empty space added to the path by -  Windows NT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd87c102-6f5d-376b-4665-98ff94b4ca41
* Version Independent ID: f6140fb6-30bc-e9e7-463a-bf5bfc926165
* Content: [Servicing Channels](https://docs.microsoft.com/en-us/windows-server/get-started-19/servicing-channels-19#feedback)
* Content Source: [WindowsServerDocs/get-started-19/servicing-channels-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/servicing-channels-19.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Thank you, well spotted. Good point. I will open a PR to have that fixed.

**Comment by illfated** [comment]
There you go. Thank you for pointing out the unparsable command parameters.
