### ISSUE TITLE
WS08 and WVista

### ISSUE THREAD

**Issue by v-radelg** [MicrosoftDocs/windowsserverdocs#4282]
@Linyixuan10 commented 2 days ago — with docs.microsoft.com

Since there is WindowsServer2008 here, you must write Windows Vista on it too!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5148ebad-44a0-b14a-d65c-e51650ce4197
* Version Independent ID: ceb3e4c3-ccc3-b75a-ccb1-235ad1a22469
* Content: [KMS client setup keys](https://docs.microsoft.com/en-us/windows-server/get-started/kmsclientkeys#feedback)
* Content Source: [WindowsServerDocs/get-started/KMSclientkeys.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/KMSclientkeys.md)
* Product: **windows-server**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @v-radelg,

The page in question has been moved to: 
[https://learn.microsoft.com/en-us/windows-server/get-started/kms-client-activation-keys](https://learn.microsoft.com/en-us/windows-server/get-started/kms-client-activation-keys). 

This article has been updated with several additions during the opening of this GitHub issue. 

I believe what you're looking for resides in our [Windows IT Pro KMS Clent Keys](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/jj612867(v=ws.11)) page. Vista keys will be added to the new page by end of the week. 

We will now be closing this thread. Thank you and have a most pleasant day. #please-close
