### ISSUE TITLE
Out of date information on server OS upgrade paths

### ISSUE THREAD

**Issue by MikeFarrington** [MicrosoftDocs/windowsserverdocs#4283]
https://docs.microsoft.com/en-us/windows-server/upgrade/upgrade-overview
links to the following page (for more information)
https://docs.microsoft.com/en-us/windows-server/get-started/supported-upgrade-paths

The tables on the latter page seem out of date compared to the graphical representation of upgrade paths on the former page.  One page has been updated much more recently than the other.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1b19ef8-a273-c1c8-18ff-7d29664bb9d2
* Version Independent ID: 8cf37a43-cff4-78de-0d66-2f482c022dc7
* Content: [Upgrade and Conversion Options for Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/get-started/supported-upgrade-paths)
* Content Source: [WindowsServerDocs/get-started/Supported-Upgrade-Paths.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/Supported-Upgrade-Paths.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@eross-msft

**Comment by robinharwood** [comment]
Hi @MikeFarrington 

Thanks for your dedication to our documentation.  I appreciate it is frustrating we haven’t been able to provide this information sooner, I apologise for the delayed response and thank you for your patience. We've submitted a documentation change based, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. If you need to follow up on this issue, leave us a comment with an @mention.

#assign:robinharwood
#please-close
