### ISSUE TITLE
Wrong GPO Path

### ISSUE THREAD

**Issue by matziq** [MicrosoftDocs/windowsserverdocs#4289]
Right below https://docs.microsoft.com/en-us/windows-server/security/tls/manage-tls#configuring-tls-cipher-suite-order-by-using-group-policy
From the Group Policy Management Console, go to Computer Configuration &gt; Administrative Templates &gt; Networks &gt; SSL Configuration Settings.

Should read From the Group Policy Management Console, go to Computer Configuration &gt; Administrative Templates &gt; Network &gt; SSL Configuration Settings.

i.e. remove the "s" from Networks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40eec07-5000-8af5-37f9-c2908bea3c67
* Version Independent ID: 4540c962-9294-e70d-de5b-8094e608768c
* Content: [Manage Transport Layer Security (TLS)](https://docs.microsoft.com/en-us/windows-server/security/tls/manage-tls#feedback)
* Content Source: [WindowsServerDocs/security/tls/manage-tls.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/manage-tls.md)
* Product: **windows-server**
* Technology: **security-tls-ssl**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by illfated** [comment]
👍 Thank you, good find. Pretty obvious typo, should be easy to correct. I will also take a quick look through the document and see if I find anything else worth correcting while I'm at it.

**Comment by illfated** [comment]
There you go, Pull Request #4291 is now available for review. Thank you for making me visit this document & find the other necessary stuff to fix in there. 🕺 🥳 🎉
