### ISSUE TITLE
License activation port

### ISSUE THREAD

**Issue by v-radelg** [MicrosoftDocs/windowsserverdocs#4294]
@dalianelanzarin commented 6 hours ago — with docs.microsoft.com

Good morning, I have a license server and I need 01 jump server to look for this license, I already pointed the IP in regedit, but I need to release the connection on the firewall, would you know what port it uses for this connection and license activation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4767a747-aab2-11eb-28fc-02652c3479ec
* Version Independent ID: c3245db3-8839-7b41-32a2-b4cf14bc5848
* Content: [Deploy your Remote Desktop environment](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-deploy-infrastructure#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-deploy-infrastructure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-deploy-infrastructure.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
Wish I had found this ticket earlier. This is usually TCP port 135, RPC Endpoint Mapper:


| Port # | Protocol | Name | Services using this port             |
| :----: | :------: | :--: | :----------------------------------- |
|  135   |    TCP   |  RPC | Message Queuing                      |
|  135   |    TCP   |  RPC | Remote Procedure Call                |
|  135   |    TCP   |  RPC | Exchange Server                      |
|  135   |    TCP   |  RPC | Certificate Services                 |
|  135   |    TCP   |  RPC | Cluster Service                      |
|  135   |    TCP   |  RPC | Distributed File System Namespaces   |
|  135   |    TCP   |  RPC | Distributed Link Tracking            |
|  135   |    TCP   |  RPC | Distributed Transaction Coordinator  |
|  135   |    TCP   |  RPC | Distributed File Replication Service |
|  135   |    TCP   |  RPC | Fax Service                          |
|  135   |    TCP   |  RPC | Microsoft Exchange Server            |
|  135   |    TCP   |  RPC | File Replication Service             |
|  135   |    TCP   |  RPC | Group Policy                         |
|  135   |    TCP   |  RPC | Local Security Authority             |
|  135   |    TCP   |  RPC | Remote Storage Notification          |
|  135   |    TCP   |  RPC | Remote Storage                       |
|  135   |    TCP   |  RPC | Systems Management Server 2.0        |
|  135   |    TCP   |  RPC | Terminal Services Licensing          |
|  135   |    TCP   |  RPC | Terminal Services Session Directory  |

**Comment by illfated** [comment]
- https://docs.microsoft.com/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements#ports-and-protocols

**Comment by illfated** [comment]
#please-close
