### ISSUE TITLE
Documentation for wmic needs to be more detailed

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/windowsserverdocs#4295]
Documentation for wmic needs to be more detailed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da66c962-ba67-2ed4-dd50-99142632a981
* Version Independent ID: 8d394b19-cbe3-42be-0f25-aebf2323b538
* Content: [wmic](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/wmic)
* Content Source: [WindowsServerDocs/administration/windows-commands/wmic.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/wmic.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Xelu86** [comment]
#assign:xelu86
