### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by mschrisran** [MicrosoftDocs/windowsserverdocs#4298]
This link is no longer working: https://blogs.technet.com/b/filecab/archive/2013/11/01/performance-considerations-for-large-scale-work-folders-deployments.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7074b89-8645-115d-bc9f-014d1812257c
* Version Independent ID: ca7910ae-ee68-fb02-9e0f-87c9d7151647
* Content: [Planning a Work Folders deployment](https://docs.microsoft.com/en-us/windows-server/storage/work-folders/plan-work-folders)
* Content Source: [WindowsServerDocs/storage/work-folders/plan-work-folders.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/work-folders/plan-work-folders.md)
* Product: **windows-server**
* Technology: **storage-work-folders**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Please check out these links and tell us if which one(s) we should use to cover your needs:
- https://techcommunity.microsoft.com/t5/storage-at-microsoft/performance-considerations-for-work-folders-deployments/ba-p/425037
- https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn265974(v=ws.11) (browse the page and TOC links for relevant info)
- https://techcommunity.microsoft.com/t5/storage-at-microsoft/bg-p/FileCAB (overview, please look for a relevant page if you can find one)

**Comment by illfated** [comment]
Already resolved in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/b679b452d9c3a2a38af885a356463fa77308beb8 .

 (See the very last file, https://github.com/MicrosoftDocs/windowsserverdocs/commit/b679b452d9c3a2a38af885a356463fa77308beb8#diff-e0136610a2480a95530e02d203313fb8 , for the specific changes.)

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
As noted in comment https://github.com/MicrosoftDocs/windowsserverdocs/issues/4298#issuecomment-703996422 :


> Already resolved in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/b679b452d9c3a2a38af885a356463fa77308beb8 .
> 
> (See the very last file, https://github.com/MicrosoftDocs/windowsserverdocs/commit/b679b452d9c3a2a38af885a356463fa77308beb8#diff-e0136610a2480a95530e02d203313fb8 , for the specific changes.)

**Comment by illfated** [comment]
#please-close
