### ISSUE TITLE
Had to restart in order for SSH agent to register with PowerShell

### ISSUE THREAD

**Issue by justincy** [MicrosoftDocs/windowsserverdocs#4299]
Installing SSH via the Settings -> Apps menu worked, but I also had to restart my machine in order for Powershell to detect it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Installation of OpenSSH For Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* GitHub Login: @maertendMSFT

**Comment by uafonseca** [comment]
my windows not show the ssh client/serer packages....help me please

**Comment by illfated** [comment]
> Installing SSH via the Settings -> Apps menu worked, but I also had to restart my machine in order for Powershell to detect it.
> 
Can happen sometimes when enabling and disabling OpenSSH via the PowerShell commands too, you intermittently need to restart Windows for the feature to be enabled or disabled.

> my windows not show the ssh client/serer packages....help me please

Try the steps from my comments in https://github.com/MicrosoftDocs/windowsserverdocs/issues/3970 and use PowerShell to install it.

**Comment by konstruktoid** [comment]
I believe this is a support question, and a stale issue, and can be closed.

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
