### ISSUE TITLE
Associate multiple Organizational Units to a network group

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/windowsserverdocs#4300]
The coments below were machine-translated

@juankiz123 commented 16 hours ago — with docs.microsoft.com
Is there the possibility of adding a single network group to several Organizational Units?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7b785b5-2b5f-9ec0-d429-49e01d45b35e
* Version Independent ID: 350db306-e299-1206-4d5b-f6e76da396af
* Content: [Reviewing OU Design Concepts](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/reviewing-ou-design-concepts#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/Reviewing-OU-Design-Concepts.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/Reviewing-OU-Design-Concepts.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by IngridAtMicrosoft** [comment]
Hi @CeciAc. GitHub issues are for identifying problems with our documentation. If you need assistance please either open a support ticket or post a question at [Microsoft Q & A](https://learn.microsoft.com/en-us/answers/questions/).
