### ISSUE TITLE
Please clarify is SRIOV is supported for use with SET host managementOS vNIC

### ISSUE THREAD

**Issue by mmmiller60** [MicrosoftDocs/windowsserverdocs#4302]
I have 2016 with an IOV enabled SET switch, IOV is working fine for VM vNICs BUT the host managementOS vNIC are missing IOV properties...

PS C:\Windows\system32&gt; Get-VMNetworkAdapter -ManagementOS -Name ExternalSwitch | fl

Name                           : ExternalSwitch
IsManagementOs                 : True
SwitchName                     : ExternalSwitch
Connected                      :
PoolName                       :
DynamicMacAddressEnabled       :
AllowPacketDirect              :
MacAddressSpoofing             : Off
AllowTeaming                   : Off
RouterGuard                    : Off
DhcpGuard                      : Off
StormLimit                     : 0
PortMirroringMode              : None
IeeePriorityTag                : On
VirtualSubnetId                : 0
DynamicIPAddressLimit          : 0
DeviceNaming                   :
VMQWeight                      : 100
VMQUsage                       : 1
PacketDirectNumProcs           :
PacketDirectModerationCount    :
PacketDirectModerationInterval :
VrssEnabledRequested           : True
VrssEnabled                    : True
VmmqEnabledRequested           : True
VmmqEnabled                    : True
VmmqQueuePairsRequested        : 16
VmmqQueuePairs                 : 4
IPsecOffloadMaxSA              : 512
IPsecOffloadSAUsage            : 0
VFDataPathActive               : False
MaximumBandwidth               :
MinimumBandwidthAbsolute       :
MinimumBandwidthWeight         :
BandwidthPercentage            : 0%
MandatoryFeatureId             :
MandatoryFeatureName           :
Status                         : {Ok}
IPAddresses                    :

PS C:\Windows\system32&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcdc6c48-ad04-d715-5e7b-03ba9c50a709
* Version Independent ID: 141be0cf-264f-f0d8-9fdd-937d45df45e1
* Content: [Remote Direct Memory Access (RDMA) and Switch Embedded Teaming (SET)](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v-virtual-switch/rdma-and-switch-embedded-teaming#bkmk_compat)
* Content Source: [WindowsServerDocs/virtualization/hyper-v-virtual-switch/RDMA-and-Switch-Embedded-Teaming.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v-virtual-switch/RDMA-and-Switch-Embedded-Teaming.md)
* Product: **windows-server**
* Technology: **networking-hv-switch**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 4275 -b #assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
Hello @mmmiller60 GitHub issues for this repo are for reporting problems with our documentation.  Please open a support ticket or post your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html).
