### ISSUE TITLE
Typo in "provides real-time tiaring"

### ISSUE THREAD

**Issue by nandak-msft** [MicrosoftDocs/windowsserverdocs#4304]
It should be "tiering"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 375ef18d-2d7f-fd6a-12ea-7a4d8d0a8c80
* Version Independent ID: fcaaf1af-4829-ac36-1617-e71dfd758208
* Content: [Storage Spaces Direct - Frequently asked questions](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/storage-spaces-direct-faq#feedback)
* Content Source: [WindowsServerDocs/storage/storage-spaces/storage-spaces-direct-faq.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/storage-spaces-direct-faq.md)
* Product: **windows-server**
* Technology: **storage-spaces**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **kaushik**

**Comment by illfated** [comment]
Thank you, good find. I wonder how long it has been that way, where most people hardly even notice that typo. I will open a PR to have that typo fixed.

**Comment by illfated** [comment]
There you go. Feel free to comment or suggest more improvements in my PR #4307 .
