### ISSUE TITLE
Missing information for validating SMB direct is working

### ISSUE THREAD

**Issue by mmmiller60** [MicrosoftDocs/windowsserverdocs#4308]
The article covers how to test the performance by disabling rdma and comparing but what if its similar, it is missing any info on how to confirm SMB direct is working at all, can we look at ports? can we look at connections? can we look at task manager? how do we even know if its working?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85ab8371-7782-ad6f-b564-5fd93b3b879a
* Version Independent ID: 5d91cde1-786d-6c7b-f8c3-9667f9df84d7
* Content: [Improve performance of a file server with SMB Direct](https://docs.microsoft.com/en-us/windows-server/storage/file-server/smb-direct)
* Content Source: [WindowsServerDocs/storage/file-server/smb-direct.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/smb-direct.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey mmmiller60,

We are making updates to this document and changes will be live by the next business day. Another way to test SMB Direct can be done by using the Performance Monitor tool and adding counters for RDMA.

```
Once the network adapter is verified RDMA-capable, perform the following test:

1. Disable RDMA on the network adapter.
2. Measure the amount of time taken to run a large file copy without using SMB Direct.
3. Re-enable RDMA on the network adapter, perform the same file copy, and then compare the two results.
4. To avoid the impact of caching, perform the following:
   a. Copy a large amount of data (more data than memory is capable of handling).
   b. Copy the data twice, with the first copy as practice and then timing the second copy.
   c. Restart both the server and the client before each test to ensure they operate under similar conditions.

Additionally, you can observe the performance counters during testing using the same scenario utilizing the Performance Monitor tool by performing the following:

1. Select **Start**, type **perfmon**, hit <kbd>Enter</kbd>.
2. In the left pane, under **Monitoring Tools** > select **Performance Monitor**.
3. In the right pane, select the green "**+**" icon to add a new counter.
4. In the **Add Counters** dialog box, expand **SMB Direct Connection**.
5. Select both **Bytes RDMA Read/sec** and **Bytes RDMA Written/sec**, select **Add**, then select **OK**.
```

Once you set up your environment, you can perform large file copies with SMB Direct enabled and then disabled to observe changes. Kindly remember to reboot the client and server when disabling and enabling during testing for better accuracy.

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
