### ISSUE TITLE
Examples are non-working

### ISSUE THREAD

**Issue by devcrowley** [MicrosoftDocs/windowsserverdocs#4310]
If you copy the examples verbatim, forfiles will return the error "ERROR: Invalid syntax. '/c' option is not allowed more than '1' time(s)."

The forfiles command does not allow multiple "/c " parameters, yet all of your examples utilize "/c cmd /c"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b1a260b-a509-ffcd-1132-4c1fb7694e6e
* Version Independent ID: a14e97c6-be2f-3a3a-7452-3fcc734fa63d
* Content: [forfiles](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/forfiles#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/forfiles.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/forfiles.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by devcrowley** [comment]
Closing issue as I realize it's a duplicate of another post

**Comment by illfated** [comment]
OK, fair enough. The original issue ticket reporting the same issue is the following: #4198
