### ISSUE TITLE
powerline

### ISSUE THREAD

**Issue by hazardland** [MicrosoftDocs/windowsserverdocs#4311]
can we get powerline already for git branch in cmd.exe?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a9e75b9-f667-9b12-eda1-94e44182135d
* Version Independent ID: 866008d5-06e9-0e2c-1813-3f9514c033d4
* Content: [prompt](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/prompt#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/prompt.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/prompt.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
I don't quite see the relevance between your question and the Cmd.exe command "prompt" document page. Could you provide more details for your question, so we may be able to address your question?

**Comment by hazardland** [comment]
There is no need I already made powerline using prompt command and bat files

![image](https://user-images.githubusercontent.com/2015121/87555636-c50cdc00-c6c6-11ea-994d-a912a9957634.png)

https://github.com/hazardland/powerline.bat

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. We are closing this as feedback is unspecified or unrelated to this documentation. #please-close
