### ISSUE TITLE
administrators_authorized_keys Permissions

### ISSUE THREAD

**Issue by ThomasMConnors** [MicrosoftDocs/windowsserverdocs#4315]
I found by trial and error that the option

   Match Group administrators
       AuthorizedKeysFile c:/ProgramData/ssh/administrators_authorized_keys

does not work out of the box when you create the administrators_authorized_keys file. You must REMOVE the Authenticated Users permissions from the file and it then works fine. (Presumably this is to protect the editing of the file by non-Admins trying to gain additiona prilivages when using SSH in-bound.

When I searched forums on this, I saw a lot of frustated Windows Pros trying to get this to work. It needs to be better documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8ad5c9a-efb1-d994-0e3c-53c90096a245
* Version Independent ID: 5cb0ea97-4c3d-ffdf-b69c-8a717f9f9f3f
* Content: [OpenSSH Server Configuration for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_server_configuration#feedback)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Server_Configuration.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Server_Configuration.md)
* GitHub Login: @maertendMSFT

**Comment by heaths** [comment]
Alternatively, comment out or delete that section and just set `AllowGroups "Group Name"`, where "Group Name" is whatever group you want to manage for user access. I called mine "SSH Users", and have only PubkeyAuthentication enabled.

**Comment by darren0h** [comment]
From https://github.com/PowerShell/Win32-OpenSSH/wiki/Security-protection-of-various-files-in-Win32-OpenSSH and https://serverfault.com/questions/873064/public-key-authentication-windows-port-of-openssh/957397 .
You can find out a solution:
(In powershell with administrator mode):
```powershell
icacls administrators_authorized_keys /inheritance:r
icacls administrators_authorized_keys /grant SYSTEM:`(F`)
icacls administrators_authorized_keys /grant BUILTIN\Administrators:`(F`)
```

Also, in https://serverfault.com/questions/1032713/public-key-authentication-not-work-on-windows-10-professional . You can find out another solution:
```powershell
$acl = Get-Acl C:\ProgramData\ssh\administrators_authorized_keys
$acl.SetAccessRuleProtection($true, $false)
$administratorsRule = New-Object system.security.accesscontrol.filesystemaccessrule("Administrators","FullControl","Allow")
$systemRule = New-Object system.security.accesscontrol.filesystemaccessrule("SYSTEM","FullControl","Allow")
$acl.SetAccessRule($administratorsRule)
$acl.SetAccessRule($systemRule)
$acl | Set-Acl
```

**Comment by robinharwood** [comment]
Hi @ThomasMConnors 

Thanks for your dedication to our documentation. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow.

Thanks

please-close
