### ISSUE TITLE
How do you configure dhcp server to match suboption 5?

### ISSUE THREAD

**Issue by anubisg1** [MicrosoftDocs/windowsserverdocs#4319]
In the dhcp relay is using option 82 suboption 5 link selection, how is a windows dhcp server configured to match on such suboption and then allocate the right ip to the client?

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. As your question isn't tied to any specific documentation, we are unable to assist. We're closing this issue but please feel free to reopen it and advise us which document is in reference to better support your needs. #please-close
