### ISSUE TITLE
Incorrect syntax

### ISSUE THREAD

**Issue by Famartincfm** [MicrosoftDocs/windowsserverdocs#4320]
Syntax seems to be incorrect when creating the SSL binding.

$sm.Sites[Default Web Site].Bindings.Add(*:443:, $hash, My, 0)    # My is the certificate store name  

And should be:
$sm.Sites["Default Web Site"].Bindings.Add("*:443:", $hash, "My", "0")
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3c543c0-4217-676c-4ae2-cd16e159e1f4
* Version Independent ID: 397e17c4-d59b-943a-0c99-eb8d05b04ebb
* Content: [IIS on Nano Server](https://docs.microsoft.com/en-us/windows-server/get-started/iis-on-nano-server)
* Content Source: [WindowsServerDocs/get-started/IIS-on-Nano-Server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/IIS-on-Nano-Server.md)
* Product: **windows-server**
* Technology: **server-nano**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by illfated** [comment]
Although this topic is not something I have personal experience from, I can understand that the text with spaces ("Default Web Site") needs quotation marks to be kept as 1 unit or parameter. Regarding the remaining arguments or parameters, is there a known reason why they need the quotes around them, e.g. to specify that they are text and not numeral values?

**Comment by jaimeo** [comment]
@eross-msft

**Comment by Famartincfm** [comment]
> Although this topic is not something I have personal experience from, I can understand that the text with spaces ("Default Web Site") needs quotation marks to be kept as 1 unit or parameter. Regarding the remaining arguments or parameters, is there a known reason why they need the quotes around them, e.g. to specify that they are text and not numeral values?
> 
> edit: Oh well, I suppose I should read up on PowerShell command syntax to learn more about this.

I've tried without on the others and it always fails. Checking also other link -> https://docs.microsoft.com/en-us/powershell/module/iisadministration/new-iissite?view=win10-ps 

New-IISSite -Name "TestSite" -BindingInformation "*:8080:" -PhysicalPath "$env:systemdrive\inetpub\testsite"

If we create a new Site the binding information is also set with quotas. I just followed that example and it worked fine to create the binding. I dont know what is the last parameter 0 or why need this to be in quotas :)

**Comment by eross-msft** [comment]
I'm speaking with the product team and they need more info before they can verify. Which version of Nano Server are you using? for which scenario? Thanks!!

**Comment by Famartincfm** [comment]
OS 2016. The scenario is using the NanoServer as a simple IIS server with a certificate binding because I need it to use https.

**Comment by eross-msft** [comment]
This has been validated by the product team. @Famartincfm or @illfated do you want to create the pull request with this change, so you get the credit for the effort?

**Comment by illfated** [comment]
I am quite ready to start making the changes, but I would very much enjoy seeing Fausto Martins (@Famartincfm) having a go at it, if he wants. Also because I believe in "credit where credit is due" and let the reporter get some local fame for making the correction. 😉

**Comment by eross-msft** [comment]
@Famartincfm @illfated  Does someone want to make this change and get the credit? If not, I can go ahead and make the update. I'd rather not sit with this when we know it's wrong....thanks!!

**Comment by illfated** [comment]
Thank you for reminding us. I was sort of hoping that @Famartincfm would like to participate in making this change, but maybe he is not familiar with the PR functionality of the Microsoft ServerDocs repository. Anyway, I will be providing the suggested PR shortly.
