### ISSUE TITLE
Refresh token issue

### ISSUE THREAD

**Issue by alsanma** [MicrosoftDocs/windowsserverdocs#4323]
This statement "ADFS issues a new refresh token only if the validity of the newer refresh token is longer than the previous token." should be cleared up. Tested in ADFS 2019 with a confidential client and registered devices, when using "grant_type=refresh_token" in authorization code grant flow, no new primary refresh token is issued. Only an access token and id_token.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bef1d22-1712-5da4-8f77-4071210ff67b
* Version Independent ID: 49c5d531-c7d0-4c14-e878-f8fa7f675c3a
* Content: [AD FS 2016 Single Sign On Settings](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/ad-fs-single-sign-on-settings#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/ad-fs-single-sign-on-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/ad-fs-single-sign-on-settings.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Question was asked at Microsoft Q & A and there was an answer.
https://learn.microsoft.com/en-us/answers/questions/1287360/refresh-token-issuance-for-ad-fs
