### ISSUE TITLE
Screenshot for Configuring WIA for Chrome

### ISSUE THREAD

**Issue by ixniz** [MicrosoftDocs/windowsserverdocs#4341]
The screenshot for Configuring WIA for Chrome does not appear to match what the configuration would be after running the commands to update the list of user agents. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abf9cb6e-38be-d28e-6ad3-1151b7e1a379
* Version Independent ID: 3eed2746-fc1e-b7c3-ea04-203291aec098
* Content: [Configuring intranet forms-based authentication for devices that do not support WIA](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-intranet-forms-based-authentication-for-devices-that-do-not-support-wia#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-intranet-forms-based-authentication-for-devices-that-do-not-support-WIA.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-intranet-forms-based-authentication-for-devices-that-do-not-support-WIA.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
From https://github.com/MicrosoftDocs/windowsserverdocs/issues/4409#issuecomment-635623882 :

> Please note: The actual issue is that the image needs to be replaced with a similar image showing the use of "Mozilla/5.0 (Windows NT)" as the User Agent string.
> 
> See commit [1d33634](https://github.com/MicrosoftDocs/windowsserverdocs/commit/1d33634de36c4966da5a1b2d69e32b0fe0708352) from 2019-07-26 and its Pull Request source **Recommendation for adding Chrome to WIASupportedUserAgents is too broad** **#2750** .
> 
> Note in particular the PR main comment, explaining the issue as follows:
> 
> > The current recommendation seems to suggest adding the “Chrome” string to WIASupportedUserAgents, but I think that is too broadly defined and could lead to a match when it probably should not because all Chrome user agent strings start with “Mozilla/5.0” followed by the platform. Adding "Chrome" by itself would lead to scenarios where WIA could incorrectly be attempted for devices such as Chrome for Android, which has a user agent string such as:
> > Mozilla/5.0 (Linux; ; ) AppleWebKit/ (KHTML, like Gecko) Chrome/ Mobile Safari/
> 
> So in fact, the text is correct, but the image is incorrect.
> 
> (I don't think I will be able to produce a working image on Windows 10 to replace the current one, but if you are able to create and use any ADFS Server VM, please post a replacement picture in a comment here with the same content as the existing image, except for the **Chrome** string being replaced by "Mozilla/5.0 (Windows NT)".)

**Comment by ixniz** [comment]
> Please note: The actual issue is that the image needs to be replaced with a similar image showing the use of "Mozilla/5.0 (Windows NT)" as the User Agent string.

Note that this should probably be: "Mozilla/5.0 (Windows NT" without the closing parenthesis after NT, since "NT" seems to always be directly followed by a version number.

**Comment by illfated** [comment]
Sure. I would have provided a screenshot of it, if I had access to a VM running an ADFS server where the response output would be similar to the existing image. I was considering editing the image, but I don't think it would be easy enough to modify the text correctly to be true to reality.

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 4330 -b #assign:IngridAtMicrosoft
