### ISSUE TITLE
Chrome User Agent

### ISSUE THREAD

**Issue by ixniz** [MicrosoftDocs/windowsserverdocs#4342]
Regarding the Chrome User Agent string, should it be "Mozilla/5.0 (Windows NT)") or "Mozilla/5.0 (Windows NT") without the parenthesis after NT? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abf9cb6e-38be-d28e-6ad3-1151b7e1a379
* Version Independent ID: 3eed2746-fc1e-b7c3-ea04-203291aec098
* Content: [Configuring intranet forms-based authentication for devices that do not support WIA](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-intranet-forms-based-authentication-for-devices-that-do-not-support-wia#configuring-wia-for-chrome)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-intranet-forms-based-authentication-for-devices-that-do-not-support-WIA.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-intranet-forms-based-authentication-for-devices-that-do-not-support-WIA.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
From https://github.com/MicrosoftDocs/windowsserverdocs/issues/3208#issue-480174107:
> > Current command is:
> Set-AdfsProperties -WIASupportedUserAgents ((Get-ADFSProperties | Select -ExpandProperty WIASupportedUserAgents) + "Mozilla/5.0 (Windows NT")
> 
> And has a typo at the end which leads to the user agent to go into ADFS incorrectly. Goes in as 'Mozilla/5.0 (Windows NT' & 'Mozilla/5.0 (Macintosh; Intel Mac OS X'
> 
> Command should be:
> Set-AdfsProperties -WIASupportedUserAgents ((Get-ADFSProperties | Select -ExpandProperty WIASupportedUserAgents) + "Mozilla/5.0 (Windows NT)"
> 
> Same problem for the Mac one where the quote is before the closing bracket.
> 
***
From https://github.com/MicrosoftDocs/windowsserverdocs/issues/3208#issuecomment-532225217:
> Yes, the second parenthesis is missed by intent – we need substring function used by ADFS to match any Windows version on NT kernel (Windows 2000 and later).
***
From https://github.com/MicrosoftDocs/windowsserverdocs/issues/3594#issue-533456323:
> Information in this article should also be included about Chrome... "Mozilla/5.0 (Windows NT") and "Mozilla/5.0 (Macintosh; Intel Mac OS X")
***
From https://github.com/MicrosoftDocs/windowsserverdocs/issues/3816#issue-557321513:
> this page doesn't show the new user agent string for Edge (Chromium) Edg/79.0.309.43 as described in this document
> [docs.microsoft.com/en-us/microsoft-edge/web-platform/user-agent-string](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/user-agent-string)
***
From https://github.com/MicrosoftDocs/windowsserverdocs/issues/3816#issuecomment-585907188:
> at this point, probably need to just put the more generic Edg/* as its already at 80.
> 
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36 Edg/80.0.361.48
> 
> I just noticed that the "Change WIASupportedUserAgent Settings" command line given has the description "The command above will ensure that AD FS only covers the following use cases for WIA:" meaning that it should include the updated Edg/79.0.309.43, but it doesnt. so if your going to update the Agent list, it should also be updated in the command line example.
***
From https://github.com/MicrosoftDocs/windowsserverdocs/issues/1545#issue-364819560:
> Hi,
> I tried the instructions above, but they didn't work. Using "Set-AdfsProperties -WIASupportedUserAgents ((Get-ADFSProperties | Select -ExpandProperty WIASupportedUserAgents) + “Chrome”)" to add Chrome to my existing list didn't provide SSO for Chrome. This resulted in the WIASupportedUserAgents being:
> 
> MSAuthHost/1.0/In-Domain
> MSIE 6.0
> MSIE 7.0
> MSIE 8.0
> MSIE 9.0
> MSIE 10.0
> Trident/7.0
> MSIPC
> Windows Rights Management Client
> Mozilla/5.0
> Edge/12
> Chrome
> 
> I then restarted ADFS services and tested, but no luck. The browser user agent string from Chrome reports as below from whoishostingthis. Does the entire string below need adding? If so, does it need updating for new Chrome versions?
> 
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36

**Comment by ixniz** [comment]
I'm not sure if my initial comment was clear enough. My question is shouldn't the User Agent string be entered as: 
Mozilla/5.0 (Windows NT
Instead of: 
Mozilla/5.0 (Windows NT)

The "NT" seems to always be followed by a version number, not an end parenthesis. If I'm not mistaken, this would evaluate to false "Mozilla/5.0 (Windows NT)" while this would succeed "Mozilla/5.0 (Windows NT".

**Comment by illfated** [comment]
OK, I was sort of hoping that one or more of the existing tickets would contain something about that. Sure, you do have a point regarding the string not ending with a parenthesis. When thinking about it now, I do remember a discussion I had about a year ago, but related to a Pull Request and not any open issue tickets. Unfortunately, I was unable to find that old and closed PR or the discussion I was involved in.

Please disregard my misunderstandings and unneeded issue ticket links.
I am sure we can follow up on your recommendations for what we should update/rewrite/correct 
in the existing documentation, based on the findings you have mentioned.

**Comment by illfated** [comment]
The closest thing I can get to an answer is by referring to issue ticket #3208 (the complete ticket content).
