### ISSUE TITLE
Accept SAM-account name as login format when Azure MFA is set as Primary Authentication

### ISSUE THREAD

**Issue by tnadolski1** [MicrosoftDocs/windowsserverdocs#4344]
As our organization moves towards Azure MFA, a hot topic has been passwordless sign-in. Is there an example of "Example 2: accept SAM-account name as a login format on an AD FS form-based sign-in page" that accommodates Azure MFA as a Primary Authentication Method?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 110e65f0-76bd-55d7-51b3-58149c8e0eb7
* Version Independent ID: 1184ab13-6803-236d-cc17-b08896cf1695
* Content: [Advanced Customization of AD FS Sign-in Pages](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/advanced-customization-of-ad-fs-sign-in-pages#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Advanced-Customization-of-AD-FS-Sign-in-Pages.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Advanced-Customization-of-AD-FS-Sign-in-Pages.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
