### ISSUE TITLE
OpenSSHUtils Not Needed

### ISSUE THREAD

**Issue by gynnantonix** [MicrosoftDocs/windowsserverdocs#4345]
OpenSSHUtils isn't necessary anymore.  Just enable the OpenSSH Authentication Agent service, as detailed here:
https://stackoverflow.com/questions/52113738/starting-ssh-agent-on-windows-10-fails-unable-to-start-ssh-agent-service-erro

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH Server Configuration for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement#feedback)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* GitHub Login: @maertendMSFT

**Comment by illfated** [comment]
( cf. #4598 & #3400 )

**Comment by illfated** [comment]
See Pull Request #4788 for a suggested improvement to this issue.
(The PR will close this issue ticket when it gets merged.)

**Comment by btipling** [comment]
I found these instructions useful on StackOverflow:

https://stackoverflow.com/questions/52113738/starting-ssh-agent-on-windows-10-fails-unable-to-start-ssh-agent-service-erro

The ssh-agent service was disabled which led me down the wrong path of trying to install an outdated package.

The correct solution was to enable the service in an admin terminal:

`Get-Service -Name ssh-agent | Set-Service -StartupType Manual`

Then ssh-agent worked as expected.

**Comment by illfated** [comment]
Fair enough, thanks for the useful feedback.

@konstruktoid : Do you think there is something provided by @btipling you can use in your PR, or is it covered somewhere else?

**Comment by konstruktoid** [comment]
I believe this is already documented in my PR.

```
To do that, start the ssh-agent service as Administrator and use ssh-add to store the private key.

# Make sure you're running as an Administrator
Start-Service ssh-agent

# This should return a status of Running
Get-Service ssh-agent

# Now load your key files into ssh-agent
ssh-add ~\.ssh\id_ed25519

After completing these steps, whenever a private key is needed for authentication from this client, ssh-agent will automatically retrieve the local private key and pass it to your SSH client.
```

**Comment by illfated** [comment]
List of related issue tickets:

- #2747 **A better explanation can be found here** (Open)
- #3400 **Can't install the "OpenSSHUtils"** (Closed)
- #3456 **Misleading title/summary causing search confusion** (Open)
- #3806 **OpenSSHUtils is deprecated** (Open)
- #3970 **OpenSSH installation** (Closed)
- #4518 **Unable to configure OpenSSH for public key auth following docs** (Open)
- #4598 **Instructions provided ends with an error** (Open)
- #4622 **Out-of-date - OpenSSHUtils no longer available.** (Open)
- #4634 **More documentation required** (Open)
- #4690 **OpenSSHUtils install reference no longer valid** (Open)
- #4702 **OpenSSHUtils got unlisted from the PowerShell gallery** (Open)
- #4743 **Nope. First example errors out.** (Open)
- #4770 **Error when following instructions to install OpenSSHUtils** (Open)
- #4787 **OpenSSHUtils module does not exist** (Open)
- #5000 **Clarification needed** (Open)
- #5138 **These instructions do not work on Windows 10 20h2** (Open)

**Comment by dknappettmsft** [comment]
Thanks for submitting this issue. I have reworked this document to remove or replace parts that are no longer relevant or correct based on this and several other issues raised for this page.

The changes should be visible in around 6-12 hours.

#please-close
