### ISSUE TITLE
System-Insights not working with Custom Perf Counters

### ISSUE THREAD

**Issue by NottyNerd** [MicrosoftDocs/windowsserverdocs#4357]
[Enter feedback here]

I currently can't add New Capabilities for my custom perf_counter. Details are shown below

Adding the Datasource below:

    DataSource perfCounter3 = new DataSource

    {

        SourceType = DataSourceType.PerfCounter,

        PerformanceCounter = new PerformanceCounterDataSource

        {

            CounterPath = "GGD",

            CounterName = "Bandwidth MB/sec",

            InstanceName = "*"                     // All instances

        },

        AggregationType = DataAggregationType.Sum,

        SeriesContext = "GGDPerfCounters"

    };
Getting the following error below when i add the custom DataSource above:

Update-InsightsCapability : System Insights failed to register one or more of data sources for capability 'GGD Capability'.
At line:1 char:1

Update-InsightsCapability -Name "GGD Capability" -Library "C:\GGdCapa ...

CategoryInfo : InvalidData: (GGD Capability:String) [Update-InsightsCapability], Exception

FullyQualifiedErrorId : SystemInsightsError,Microsoft.SystemInsights.Management.PowerShell.UpdateInsightsCapabilityCommand

Everything works fine if i remove this datasource and use one from PhysicalDisk.

Also after checking Event Viewer to check the error, I see the error below:

Failed to update capability 'GGd Capability'. Enable the Debug channel to see more details.

Unknown exception when adding or updating for capability GGd Capability. Exception type: System.ServiceModel.FaultException`1[Microsoft.SystemInsights.Management.SystemInsightsError]. Reason: The creator of this fault did not specify a Reason.

https://windowsserver.uservoice.com/forums/295047-general-feedback/suggestions/39375703-issue-with-creating-system-insights-capability-for

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 519a0668-fef9-674c-7f48-165ee9c9cbfc
* Version Independent ID: 3c30e45f-1416-87d9-cf60-c445987a54aa
* Content: [Adding and developing capabilities](https://docs.microsoft.com/en-us/windows-server/manage/system-insights/adding-and-developing-capabilities)
* Content Source: [WindowsServerDocs/manage/system-insights/adding-and-developing-capabilities.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/system-insights/adding-and-developing-capabilities.md)
* Product: **windows-server**
* Technology: **system-insights**
* GitHub Login: @gawatu
* Microsoft Alias: **gawatu**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @NottyNerd,

Thanks again for contacting Microsoft. We value your feedback.

As we understand it, you're describing a problem with the product itself and not with the product documentation. GitHub isn't quite the right location if searching for technical support or feature requests as it is completely outside our scope. If there are any issues within the content itself, please let us know.

To get assistance or support for your product issue, we recommend that you engage with the product community or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs). 

Additional support forums listed below:
- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
