### ISSUE TITLE
Note

### ISSUE THREAD

**Issue by D4-AzIdentity** [MicrosoftDocs/windowsserverdocs#4359]
I had to add the Server to the Group first before activating the server on step 4. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4767a747-aab2-11eb-28fc-02652c3479ec
* Version Independent ID: c3245db3-8839-7b41-32a2-b4cf14bc5848
* Content: [Deploy your Remote Desktop environment](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-deploy-infrastructure#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-deploy-infrastructure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-deploy-infrastructure.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
Just to make sure I have understood your scenario correctly: You say that you had to perform step 4.e. before you could perform step 4.a. Is that a correct interpretation?

By the way, if someone else wants to try to replicate this issue; which server types & versions are you using?

**Comment by illfated** [comment]
No reply or follow-up for 11 months now. Please create a new ticket with more information.

#please-close
