### ISSUE TITLE
How so you enter Ctrl Alt Delete on Remote Desktop on a MAC

### ISSUE THREAD

**Issue by steveu75** [MicrosoftDocs/windowsserverdocs#4360]
How do you send it to a PC while on a mac. How do you do an Alt Tab

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e3bc1ca-2fde-4a75-3583-fdb8ff2bf962
* Version Independent ID: 5cef2f0a-bed1-f05f-0f74-ba6f2808a714
* Content: [Remote Desktop clients FAQ](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-client-faq#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
From https://social.technet.microsoft.com/Forums/en-US/492352af-5a54-4ebf-b24e-210f26a7e17d/how-do-you-send-ctrlaltdelete-when-running-mrd-on-a-macbook-pro?forum=winRDc :
> Hi,
>
>If you are using Microsoft's Remote Desktop Connection to access a windows (virtual) machine, you should use the following keys: Fn + Ctrl + Opt + Delete
(function-control-option-delete), also as shown in the picture below:
>
> ![999744 1](https://user-images.githubusercontent.com/38162891/82141307-2b938c00-9835-11ea-82b0-8ecc4cdc992e.jpg)

***

From https://www.parallels.com/blogs/alt-key-on-a-mac/ :
>
> **Where is the Alt key on a Mac keyboard?**
>
> The PC-keyboard equivalent of Alt on a Mac is called the Option key, and you’ll find the Option Key on your Mac if you go two keys to the left of the spacebar. However, the option key on a Mac keyboard is used in a different way than the alt key on a Windows PC. In terms of functionality, the alt key in Windows is often more comparable with the Command key than with the Option key on a Mac. You might be also familiar with the Ctrl and Alt keys from your PC. On your Mac keyboard, you have Command (⌘ cmd), Control (ctrl), and Option (⌥  alt) keys.

**Comment by IngridAtMicrosoft** [comment]
Addressed in comments.
