### ISSUE TITLE
Can I use MSRDC instead of MSTSC?

### ISSUE THREAD

**Issue by xinkunZ** [MicrosoftDocs/windowsserverdocs#4364]
MSTSC has some DPI problem under 4k monitor， so I want to use MSRDC, but it seems like MSRDC is not for personal users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ab98fc-fea2-a11a-e5ca-de1430211d97
* Version Independent ID: 4d9943c3-fef7-ca86-bd03-1241a04b8135
* Content: [Get started with the Windows Desktop client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by RAJU2529** [comment]
@xinkunZ . Only Microsoft employees  will give solutions, so wait for the replies

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hello @xinkunZ,

Thanks again for contacting Microsoft. We value your feedback.

Per my understanding, the Windows Remote Desktop Client app only works with a work or school account for the time being. For personal use, the built-in Remote Desktop Connection is available. Granted that you won't receive the best DPI in 4k as this is also my case. 

If you'd like to submit a feature request, please utilize our Microsoft Feedback Hub which can be found by clicking Start and searching for "Feedback Hub". Alternatively, if the Windows Remote Desktop Client app is open, click on the "Feedback" button and it will also take you to the Feedback Hub.

![image](https://user-images.githubusercontent.com/103963494/188970230-4c99838b-b058-4a1c-bc56-a8f345694308.png)

We will now be closing this thread. Thank you and have a most pleasant day. #please-close
