### ISSUE TITLE
is We recommend the dimensions for the illustration to be 1420x1080 pixels @ 96 DPI with a file size of no greater than 200 KB.

### ISSUE THREAD

**Issue by DJHutchinson** [MicrosoftDocs/windowsserverdocs#4366]
Customer believes this should read 1920x1080 for the background illustration image size.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 879cdd90-da4c-fa30-49e0-2ddfccf74e03
* Version Independent ID: e2ac76f5-2ee5-147d-79b0-0834ee8076fd
* Content: [Change the illustration on the AD FS sign-in page](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/change-the-illustration-on-the-ad-fs-sign-in-page#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Change-the-illustration-on-the-AD-FS-sign-in-page.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Change-the-illustration-on-the-AD-FS-sign-in-page.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
It may very well look that way, but from what I can read in this page, the image is not supposed to cover the full width of the screen. I would go so far as to say that the example image is in fact far less than 1420 pixels wide, I would estimate 50% of the screen width (960x1080). Based on the recommended size 1420x1080 pixels, I presume there is a need for a remaining space of 500x1080 for the company information and the sign-in boxes, buttons, and so on. These are supposed to be placed in a part of of the screen separated from the image.

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 4363 -b #assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @DJHutchinson,

Thanks again for contacting Microsoft. We value your feedback. 

We have updated this to state:

> We recommend the dimensions for the illustration to be 1420x1080 pixels @ 96 DPI for displays with 1080p resolution in **jpg** or **png** format. A file size of no greater than 200 KB to 500 KB to improve load times. 

Depending on the illustration & max display resolution, this will need to be adjusted accordingly for anything above a max display of 1080p. Setting the image to 1920x1080p may cut a portion of the image.

Changes will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. #please-close
