### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by S-List** [MicrosoftDocs/windowsserverdocs#4383]
"This example all the non-empty directories, plus files whose name match the pattern given with the asterisk symbol."
The sentence appears to be missing a verb.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a1e859-b436-290e-69c0-810dd3a5ce90
* Version Independent ID: 10c81289-2bf7-40d9-39ea-e624cf92aa3e
* Content: [xcopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/xcopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/xcopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/xcopy.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
👍 Thank you for pointing that out. I will open a PR and start writing on something to get that text to make sense again. 😄

**Comment by illfated** [comment]
Sorry for the delay, I had a somewhat stressful week before I got around to creating the PR.

**Comment by illfated** [comment]
There you go. This issue ticket will close automatically when my PR gets merged into the `master` branch.
