### ISSUE TITLE
URL format is not clear

### ISSUE THREAD

**Issue by ottmihkel** [MicrosoftDocs/windowsserverdocs#4385]
Can you pls clarify the URL above: rdp://full%20address=s:mypc:3389&audiomode=i:2&disable%20themes=i:1? Perhaps some examples?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cd04fe0-b87d-9c35-638d-8d9971746097
* Version Independent ID: be3bf30a-de46-2b88-f829-f729ec49b0d8
* Content: [Remote Desktop clients URI scheme](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-uri#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-uri.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-uri.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
Many of the attributes have links to a description page.

| RDP attribute                                           | Android | Mac | iOS |
|---------------------------------------------------------|---------|-----|-----|
| [audiomode=i:&lt;0, 1, or 2&gt;](https://docs.microsoft.com/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/ff393707(v=ws.10)) | x | x | x |
| disable themes=i:&lt;0 or 1&gt;                         |    x    |  x  |  x  |
| [full address=s:&lt;string&gt;](https://docs.microsoft.com/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/ff393661(v=ws.10))  | x | x | x |

Some of the attributes are linked to a page where the details are explained. The non-linked attributes are presumed to be known Windows settings.

| RDP attribute                   | Description from linked page |
| ------------------------------- | ---------------------------- |
| audiomode=i:**0** | Play sounds on the local computer (this computer) |
| audiomode=i:**1** | Play sounds on the remote computer (remote PC) |
| audiomode=i:**2** | Do not play sounds (Do not play) |
| disable themes=i:**0** | No, do not disable themes (boolean false) |
| disable themes=i:**1** | Yes, disable themes (boolean true) |
| full address=s:&lt;**value**&gt;   | A valid computer name, IPv4 address, or IPv6 address |

A valid computer name is usually a reachable computer on the network, especially if it is a short name.
When a full URL host+domain address is specified, RDP searches DNS for the target computer.

**Comment by illfated** [comment]
See also https://docs.microsoft.com/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/ff393699(v=ws.10) for a comprehensive list of attributes.

BTW, regarding the `mypc:3389` part of the URI, 3389 is the default TCP Port responding to RDP access on the target Windows computer. **mypc** means any name given to the PC reachable on the local network. Maybe a better name could be **rdp-pc** -- but I doubt Microsoft would like to change that naming in these old (and soon outdated) document pages).

**Comment by ottmihkel** [comment]
Hello!

What I actually meant is that it’s a mess of attributes instead of simply

rdp://username@hostname:port

Also attribute types like i:, s: etc are not strictly necessary and not common in URLs.

But actually it’s even worse, URLs like described in https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-uri are not recognized on Mac OS 10.15.
Fore example, if I try to open:

rdp://full%20address=s:mic-netem-vm.westeurope.cloudapp.azure.com:40000&screen%20mode%20id:i:1&username=s:builder

in Safari, I get:




The message is technically incorrect, becuase macOS DOES recognize URLs starting with MRD is installed, eg if I try a simple URL:

rdp://mic-netem-vm.westeurope.cloudapp.azure.com:40000

Then it’s handed over to MRD which in turn complains that the URL is invalid.

I suppose Safari actually wants to say that it considers the URL itself invalid, probably because it cannot parse host fom it.

Altogether it means that RDP URLs are unusable on Mac OS 10.15 (Catalina). 

I wonder can you fix it, like supporting simple URL as above in MRD?

Best regards,
Mihkel Tammepuu
mitammep@microsoft.com

**Comment by illfated** [comment]
@ottmihkel : Thank you for posting and replying regarding your issue. You may want to contact the developers to get something done about this, by using the Feedback Hub.

Unless there are inaccuracies or blatant errors in the page which need to be corrected, based on test results / production environment facts contradicting the document information, there is precious little we can help you with here in the Microsoft Server Documentation issue ticket repository.

Whenever you are in contact with the Microsoft Developers about this issue, we are more than happy to receive feedback if you manage to get news back to us about stuff we need to look into or correct in the documentation.

Best of luck to you in your further endeavors.

#sign-off
