### ISSUE TITLE
Why the URL does not work on Windows?

### ISSUE THREAD

**Issue by ottmihkel** [MicrosoftDocs/windowsserverdocs#4387]
Cannot you fix the Windows MRD so that the URL is supported on Windows too?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cd04fe0-b87d-9c35-638d-8d9971746097
* Version Independent ID: be3bf30a-de46-2b88-f829-f729ec49b0d8
* Content: [Remote Desktop clients URI scheme](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-uri)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-uri.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-uri.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
Isn't it just as easy to use a shortcut to the Remote Desktop Client on any Windows client computer?


![Remote Desktop](https://winaero.com/blog/wp-content/uploads/2017/04/remote-desktop-rdp-mstsc-icon.png)

https://winaero.com/blog/remote-desktop-pc-shortcut-windows-10/

**Comment by cullub** [comment]
@illfated No, if you're trying to launch from another app, that doesn't help.

**Comment by illfated** [comment]
Thank you for the feedback. Sorry for not noticing the actual issue details. I will leave this to be answered by someone who may be affected by this kind of issue.

**Comment by IngridAtMicrosoft** [comment]
Hi @ottmihkel. GitHub issues for this repo are for reporting problems with our documentation.  Please open a support ticket or post your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html).
