### ISSUE TITLE
bowser

### ISSUE THREAD

**Issue by Curtmcgirt** [MicrosoftDocs/windowsserverdocs#4388]
the word "bowser" appears eight times on this page, and as a Mario fan, my gut tells me all of them are supposed to be"browser". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a91db45-ca3c-7a2e-3f32-2f5b57837b03
* Version Independent ID: b83cbaab-c0df-d6e7-a67f-f4c99a46e30a
* Content: [How to detect, enable and disable SMBv1, SMBv2, and SMBv3 in Windows](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md)
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by illfated** [comment]
Heh. Sure, it may look that way, but as a matter of fact, you will be surprised to see how much you can find, especially connected to the family name or surname "Bowser":

- https://en.wikipedia.org/wiki/Bowser
- https://www.bing.com/search?q=Bowser&form=QBLH&sp=-1&pq=bowser&sc=8-6&qs=n&sk=&cvid=C1E417F49CA445D485AAFF60CF4C62AF

Just to "throw my 2 cents in", Bowser (https://en.wikipedia.org/wiki/Bowser) could in theory be the project code name for SMB (Server Message Block), the same way as "Denali" (Mount Denali, formerly Mount McKinley, tallest mountain in Alaska) is the codename for the **SQL Server 2012** project. I still can't find any proof for this theory, though.

(See also https://en.wikipedia.org/wiki/List_of_Microsoft_codenames for other examples.)

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
By the way, for anyone visiting this page later and still thinking that the term 'bowser' needs to be changed to "browser", please read the history behind why that name was chosen. If the service named 'bowser' had been named "browser", it would have conflicted with the already existing Kernel Browser Service and made a much bigger mess than this odd name choice. Those events happened some 20 years ago, so if you want to change the name, please invent a time machine to go back and find a different name for 'bowser' used in parts of the SMB1 service.
