### ISSUE TITLE
Missing parameter setcatemplate

### ISSUE THREAD

**Issue by ztrhgf** [MicrosoftDocs/windowsserverdocs#4403]
On page is missing description for parameter setCAtemplates parameter.
It can be used to make template available for use on Enterprise CA (i.e. simulates Certificate Template to Issue)
certutil -setCAtemplates +"templateName" (for adding template)
certutil -setCAtemplates -"templateName" (for removing)

Strange is that parameter is missing also in command builtin help, but is working! :)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d238db2c-10e1-d418-e780-54b421779754
* Version Independent ID: d1313e31-d990-2f0b-3f70-ae0fcdb4ba5c
* Content: [certutil](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/certutil)
* Content Source: [WindowsServerDocs/administration/windows-commands/certutil.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/certutil.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by ztrhgf** [comment]
I found this information in pdf file " Windows Server 2008 - Active Directory Certificate Services Migration Guide"

**Comment by illfated** [comment]
Thank you for the practical and (hopefully) useful feedback.

I know, sometimes there are command parameters that don't appear in the documentation, although it happens less often in the built-in help function than in the online documentation.

I also notice that this page ( certutil ) is one of the longer pages in the Windows Commands hierarchy. Maybe that is one of the reasons for not including the parameter `-setcatemplate` in addition to evaluating if that parameter is used less often than the others.

Anyway, if you would like to reference the exact phrasing from your sources, or maybe point me to some online ones, I could make an attempt to write a suggestion to have that parameter added. Please note that the text will have to follow the same codestyle as the rest of the page.

**Comment by ztrhgf** [comment]
I don't know where I found that pdf but here https://www.sysadmins.lv/blog-en/microsoft-whitepapers-public-key-infrastructure-and-active-directory-certificate-services.aspx is link to docx document with almost same content https://www.sysadmins.lv/dl/43.aspx

Search it for "certutil –setcatemplates +templatelist"

**Comment by illfated** [comment]
OK, thanks for the feedback. I will have a look and see what I can do about it. This may take a while, due to other pending activities.

**Comment by Xelu86** [comment]
Hey ztrhgf,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding several missing parameters from the CertUtil doc and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
