### ISSUE TITLE
Domain joined devices, device tunnel and windows enterprise

### ISSUE THREAD

**Issue by OffColour** [MicrosoftDocs/windowsserverdocs#4411]
A couple of questions on this:

"Device Tunnel can only be configured on domain-joined devices running Windows 10 Enterprise or Education version 1709 or later"

1. If the machine is only Windows Enterprise after the user logs in (i.e. using a Microsoft 365 licence that dynamically changes to Enterprise based on the users licence) will the device tunnel still function when the user isn't logged in?

2. If the Device tunnel only works on domain joined machines then how are we supposed to join the machine to the domain when the VPN is the only way of getting to the domain controller?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3e10ece-cd5d-0080-a1d3-df64466d1a0b
* Version Independent ID: 5b0e8894-8d85-7d93-9dc7-d79fd15504d3
* Content: [Always On VPN features](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/vpn-map-da)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/vpn-map-da.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/vpn-map-da.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by IngridAtMicrosoft** [comment]
@OffColour Please ask your question at Microsoft Q & A. https://docs.microsoft.com/en-us/answers/products/
