### ISSUE TITLE
Duplicated header for table under "Required permissions for the file share hosting redirected folders" 

### ISSUE THREAD

**Issue by DrDrrae** [MicrosoftDocs/windowsserverdocs#4414]
The heading for the table under "Required permissions for the file share hosting redirected folders" is duplicated.

![image](https://user-images.githubusercontent.com/672350/83181320-b5274180-a0f2-11ea-8d2d-539080e0405a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3273d609-8cdb-19b8-6e72-e6c763904c47
* Version Independent ID: cf80c8f5-49f6-43a4-bb8e-b5849beb818b
* Content: [Deploy Folder Redirection with Offline FilesDeploy Folder Redirection with Offline Files](https://docs.microsoft.com/en-us/windows-server/storage/folder-redirection/deploy-folder-redirection)
* Content Source: [WindowsServerDocs/storage/folder-redirection/deploy-folder-redirection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/folder-redirection/deploy-folder-redirection.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Thank you for reporting this. Good find. I will make sure this gets resolved quite soon.
