### ISSUE TITLE
Example 3 is incorrect

### ISSUE THREAD

**Issue by Tsirke** [MicrosoftDocs/windowsserverdocs#4415]
One of the example pictures in this article is incorrect, Example 3 for the 24 cores scenario suggests that a customer may utilize a single 16 virtual core VM and 2 additional 2 virtual core VMs for a total of 3 separate instances of Windows Server in Azure, however, the Product Terms (page 55 in the May 2020 edition) does not allow the use of the product for 24 per core licenses in such a way in Azure. Each set of 16 core licenses permit the deployment of 2 or less base instances in Azure, each additional set of 8 licenses permit the deployment of **1**
 additional instance ie. the description of the picture is incorrect, the customer will not be able to use 2 further base instances with 2 virtual cores each and leave 4 per core licenses unused. Please correct the image as it may mislead customers. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90e335dd-0bc5-a7e3-650b-e3dd1823176b
* Version Independent ID: 18f34ef3-ff61-0473-a64b-ac5a64dbe1d7
* Content: [Azure Hybrid Benefit for Windows Server](https://docs.microsoft.com/en-us/windows-server/get-started/azure-hybrid-benefit)
* Content Source: [WindowsServerDocs/get-started/azure-hybrid-benefit.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/azure-hybrid-benefit.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @eross-msft
* Microsoft Alias: **chrisrin**

**Comment by illfated** [comment]
( also ref. issue ticket #488 from the same page )

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by dknappettmsft** [comment]
Thanks for the feedback. The image is incorrect and I have removed it as part of some wider changes to the article in favor of the Azure Hybrid Benefit Savings Calculator https://azure.microsoft.com/en-gb/pricing/hybrid-benefit/#calculator.  The changes should be visible later today.

#please-close
