### ISSUE TITLE
Ssh username@servername - how get username & servername?

### ISSUE THREAD

**Issue by sj2501** [MicrosoftDocs/windowsserverdocs#4418]
Thank you, information was useful. People like me who just need an SFTP for testing purpose might not know some basic things. How do i get the username , password and servername for testing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Installation of OpenSSH For Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* GitHub Login: @maertendMSFT

**Comment by illfated** [comment]
If you run the SSH server on your local machine, you are in control of the usernames and server names yourself. You may also use already existing Windows usernames (the lowercase username version without any spaces).

**Comment by illfated** [comment]
Please note that the Microsoft Docs repositories are is not support instances. They are intended for reporting docs pages in need of correction or improvement, as well as creating Pull Requests to improve the existing documentation. The MS Docs team will not have time to answer questions, so the only practical answers from them may be a suggestion where to look for support, when this issue ticket gets closed.

**Comment by illfated** [comment]
You may also want to have a look at my comments in issue ticket [**OpenSSH installation**](https://github.com/MicrosoftDocs/windowsserverdocs/issues/3970) **#3970**

**Comment by konstruktoid** [comment]
I believe this is a support question, and a stale issue, and can be closed.

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
