### ISSUE TITLE
sc.exe FAILED 1059 - Circular service dependency

### ISSUE THREAD

**Issue by edgecase14** [MicrosoftDocs/windowsserverdocs#4420]
the full command was:
sc.exe config lanmanworkstation depend= browser/mrxsmb20/nsi
[SC] ChangeServiceConfig FAILED 1059:
Circular service dependency was specified.

so these instructions aren't working on Windows Server 2012 and Windows 7 Pro at least.
also the article shows "bowser" but probably it should say "browser"

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a91db45-ca3c-7a2e-3f32-2f5b57837b03
* Version Independent ID: b83cbaab-c0df-d6e7-a67f-f4c99a46e30a
* Content: [How to detect, enable and disable SMBv1, SMBv2, and SMBv3 in Windows](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md)
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by popebombizzle** [comment]
So lanmanworkstation huh? Have you ever considered whatever you’re attempting to illegally obtain from my network isn’t working because I now too own the very expensive ($3999) a year program known as Burp Suite. I see all the illegal injections and poisoning that have been done to my network and have everyone’s involved dead to rights. No matter what happens on you guys and I’ll still have all I need for when AT&T and the sheriffs department meet me at my place after 2pm. You should be concerning yourselves with your plans for the future and not my network.

**Comment by edgecase14** [comment]
SO, it appears that "bowser" is the correct spelling.  The documentation should mention this, since there is another closely related service "browser", and many people had assumed this was a spelling mistake, which led them to these problems.

**Comment by illfated** [comment]
> SO, it appears that "bowser" is the correct spelling. The documentation should mention this, since there is another closely related service "browser", and many people had assumed this was a spelling mistake, which led them to these problems.

Fair point. Do you have any particular wording in mind, or would it be enough to add a Note blob (colored) pointing out that the service name is **bowser**, not "browser"?

**Comment by KalleOlaviNiemitalo** [comment]
Even more confusingly, the kernel-mode driver "bowser" has the display name "Browser" in U.S. English, while the user-mode service "Browser" has the display name "Computer Browser".

A Microsoft employee blogged about the name [in March 2006](<https://docs.microsoft.com/archive/blogs/larryosterman/fun-with-names> "Fun with names | Microsoft Docs") and again [in May 2011](<https://docs.microsoft.com/archive/blogs/larryosterman/reason-number-9999999-why-you-dont-ever-use-humorous-elements-in-a-shipping-product> "Reason number 9,999,999 why you don’t ever use humorous elements in a shipping product | Microsoft Docs").

**Comment by illfated** [comment]
Thank you for the links. Those two (archived) blog posts are quite entertaining to read. They highlight how the issue affects people in ways you would not have anticipated back in 2001 or in the 1990s, not to mention the plethora of messages to have the perceived service name typo corrected. Oh well. So much for allowing the use of cute and/or funny names in core parts of the operating system.

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
