### ISSUE TITLE
What's new in Windows Server, version 2004 page needs more detail.

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/windowsserverdocs#4424]
[Enter feedback here]

The what's new in Windows Server, version 2004 page needs to be updated with more details. Is there anything new other than Server Core container improvements ? If so, it should be stated.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 738d569b-2ab6-9681-b7b0-6af9040da16b
* Version Independent ID: abda3eec-da9f-1620-5e29-6c4e99a9e4d2
* Content: [What's New in Windows Server, version 2004](https://docs.microsoft.com/en-us/windows-server/get-started/whats-new-in-windows-server-2004)
* Content Source: [WindowsServerDocs/get-started/whats-new-in-windows-server-2004.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/whats-new-in-windows-server-2004.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by illfated** [comment]
GitHub page blame view: https://github.com/MicrosoftDocs/windowsserverdocs/blame/master/WindowsServerDocs/get-started/whats-new-in-windows-server-2004.md

Page created May 26, 2020, 12:47 PM PDT in PR #4407 (**From private repo**), commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/2477982bfd6dc42b0eefeb648c1adefdc8d485c3

Page updated by Heidilohr on Oct 13, 2020, 11:18 AM PDT, in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/30fb6ddc320291fb89cf2b93e44879d59f9de186

```diff
  @@ -1,18 +1,20 @@
  ---
- title: What's New in Windows Server, version 2004
- description: New features in Windows Server, version 2004
+ title: What's New in Windows Server, versions 2004 20H2
+ description: New features in Windows Server, version 2004 and 20H2.
  ms.topic: article
  author: Heidilohr
  ms.author: helohr
  ms.date: 05/27/2020
  ms.localizationpriority: high
  ---
  
- # What's new in Windows Server, version 2004
+ # What's new in Windows Server, version 2004 and 20H2
  
  >Applies to: Windows Server (Semi-Annual Channel)
- To learn about the latest features in Windows, see [What's New in Windows Server](whats-new-in-windows-server.md). This topic describes some of the new features in Windows Server, version 2004.
+ To learn about the latest features in Windows, see [What's New in Windows Server](whats-new-in-windows-server.md). This topic describes some of the new features in Windows Server, version 2004 and 20H2.
+ 
+ Windows Server, version 20H2 is the next Semi-Annual Channel release of Windows Server, version 2004. This version focuses on reliability, performance, and other general improvements, but has no new features. Like other Semi-Annual Channel releases, it’s supported for 18 months after its release. To learn more about the support dates for Semi-Annual Channel releases, see [Windows Server release info](windows-server-release-info.md).
  
  ## Server Core container improvements

```

***

<details>
<summary>Click to see image details.</summary>


![image](https://user-images.githubusercontent.com/38162891/100484519-127d6900-30fd-11eb-91ae-8492c2d0f9ce.png)

</details>

**Comment by illfated** [comment]
#please-close
