### ISSUE TITLE
Page needs to be updated for Windows Server, version 2004

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/windowsserverdocs#4425]
[Enter feedback here]

This page needs to be updated for Windows Server, version 2004
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbf74885-9525-9828-95c9-0ab9167b1f35
* Version Independent ID: f0a39382-120b-0cfa-692f-621124a23f37
* Content: [Windows Server release information](https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info)
* Content Source: [WindowsServerDocs/get-started/windows-server-release-info.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/windows-server-release-info.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Oct 13, 2020, 11:18 PDT, the following was added for 2004 and 20H2 in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/30fb6ddc320291fb89cf2b93e44879d59f9de186 (direct file link: https://github.com/MicrosoftDocs/windowsserverdocs/commit/30fb6ddc320291fb89cf2b93e44879d59f9de186#diff-c7e8f4154bb3aea37087cd2ca928c5e985d5b6946eae1d597f16dea29fa942eb) by Heidilohr :

**4** 📗📗📗🟥🔲 [WindowsServerDocs/get-started/windows-server-release-info.md](https://github.com/MicrosoftDocs/windowsserverdocs/commit/30fb6ddc320291fb89cf2b93e44879d59f9de186#diff-c7e8f4154bb3aea37087cd2ca928c5e985d5b6946eae1d597f16dea29fa942eb)
```diff
  @@ -2,7 +2,7 @@
  title: Windows Server release information
  description: Release information about Windows Server
  ms.topic: article
- ms.date: 04/14/2020
+ ms.date: 10/20/2020
  author: jasongerend
  ms.author: jgerend
  ms.localizationpriority: high
  @@ -17,6 +17,8 @@ The Semi-Annual Channel provides opportunity for customers who are innovating qu
  
  | Windows Server release | Version | OS Build | Availability | Mainstream support end date|Extended support end date |
  |----------------|---------|----------|----------|---------|----------|
+ | Windows Server, version 20H2 (Semi-Annual Channel) (Datacenter Core, Standard Core) | 20H2 | 19042.508.200927-1902 | 10/20/2020 | 05/10/2022 | Review note |
+ | Windows Server, version 2004 (Semi-Annual Channel) (Datacenter Core, Standard Core) | 2004 | 19041.264.200508-2205 | 05/27/20 | 12/14/2021 | Review note |
  | Windows Server, version 1909 (Semi-Annual Channel) (Datacenter Core, Standard Core) | 1909  | 18363.418.191007-0143 | 11/12/2019 | 05/11/2021 | Review note |
  | Windows Server, version 1903 (Semi-Annual Channel) (Datacenter Core, Standard Core) | 1903  | 18362.30.190401-1528 | 5/21/2019 | 12/08/2020 | Review note |
  |Windows Server 2019 (Long-Term Servicing Channel) (Datacenter, Essentials, Standard)|1809|17763.107.1010129-1455|11/13/2018|01/09/2024|01/09/2029|

```

**Comment by illfated** [comment]
#please-close
