### ISSUE TITLE
Not possible to get this error (?)

### ISSUE THREAD

**Issue by xXxOlivierxXx** [MicrosoftDocs/windowsserverdocs#4427]
Item 61 of "Promotion and demotion failure codes" shows "Not possible to get this error" as the suggested resolution. I just got this error during a DC Promotion... Now what?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8992fe44-ee47-e595-cd07-3944b1b01e7d
* Version Independent ID: 9dcafc3b-84ba-9b41-8b1d-03af40bb8c5f
* Content: [Troubleshooting Domain Controller Deployment](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/troubleshooting-domain-controller-deployment)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/Troubleshooting-Domain-Controller-Deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/Troubleshooting-Domain-Controller-Deployment.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by illfated** [comment]
Would you be able to post the contents of the error message or a screen shot of the error, possibly with some of the wording for it?

Would also be nice to know a bit about the details regarding your server version(s) and some of the scenario context.

**Comment by xXxOlivierxXx** [comment]
Fixed.
The error shows up if you attempt to execute the install-ADDSDomainController function with the "-InstallDns" parameter on Windows Server 2016, and the server already has the DNS role installed. The solution is to remove the -InstallDns parameter from your promotion PS script.

**Comment by illfated** [comment]
Error code 61 description: "You cannot install Active Directory Domain Services with DNS in an existing domain that does not already host DNS"

Based on your feedback, it seems that it includes the possibility that this can also happen when the role selected by the install parameter already exists on the server and cannot be reinstalled.
