### ISSUE TITLE
Windows 10 Always-VPN clients - must be Active Directory joined?

### ISSUE THREAD

**Issue by tfurstms** [MicrosoftDocs/windowsserverdocs#4434]
In the "Windows 10 VPN Clients" section on this page it states that: "The Windows 10 VPN clients must be domain-joined to your Active Directory domain."

However, I am working with Win10 1909 devices that are **only Azure AD joined** and Always-On VPN is working just fine.  Can you update the page if Always-On VPN is officially supported with AAD Joined devices - Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ecf5e50-aeae-4c29-dc40-e1222d17a4ed
* Version Independent ID: bb4d5a7f-7805-e8b9-7c27-a161f59f8061
* Content: [Always On VPN Technology Overview](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/always-on-vpn-technology-overview)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/always-on-vpn-technology-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/always-on-vpn-technology-overview.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by illfated** [comment]
@eross-msft : Even though the sentence could be interpreted as meaning that any Active Directory domain is a valid AD to be joined to, would it be practical to get this verified for Azure AD and update only that paragraph, or should we check for a planned general update for the whole document?

**Comment by eross-msft** [comment]
@illfated  We currently have no way to address GitHub issues (though I'm trying to figure out a plan), so if you want to create a PR to address this singular issue, I can certainly get that updated. Unfortunately, there is no one on point to review this content, so an overall review would be a tough promise.

**Comment by illfated** [comment]
Fair enough, thank you for the insight. I will dwell on these facts and consider the implications before I start writing something which might be useful enough for this specific case.

**Comment by illfated** [comment]
> [On Jun 1, 2020, 9:23 PM GMT+2](https://github.com/MicrosoftDocs/windowsserverdocs/issues/4434#issue-628668578), @tfurstms wrote:
>
> In the "Windows 10 VPN Clients" section on this page it states that: "The Windows 10 VPN clients must be domain-joined to your Active Directory domain."
> 
> However, I am working with Win10 1909 devices that are **only Azure AD joined** and Always-On VPN is working just fine. Can you update the page if Always-On VPN is officially supported with AAD Joined devices - Thanks!
> 

Could we have this confirmed, somehow, maybe from the dev team, that this document could benefit from an added statement that "only Azure AD joined an Always-On VPN" is a valid supported solution and useful part of the referenced document?

**Comment by IngridAtMicrosoft** [comment]
@tfurstms Please ask your question at Microsoft Q&A. https://docs.microsoft.com/en-us/answers/products/
