### ISSUE TITLE
'Set-Service' is not recognized

### ISSUE THREAD

**Issue by oktay454** [MicrosoftDocs/windowsserverdocs#4436]
[Enter feedback here]
Command:
`Set-Service -Name sshd -StartupType 'Automatic'`
Output:
```
'Set-Service' is not recognized as an internal or external command, 
operable program or batch file.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Installation of OpenSSH For Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* GitHub Login: @maertendMSFT

**Comment by illfated** [comment]
Please read the notes carefully.
1. That command is a PowerShell cmdlet and must be run in PowerShell.
2. You need to open PowerShell as Administrator to make the commands work.

Please read my log in https://github.com/MicrosoftDocs/windowsserverdocs/issues/3970#issuecomment-610078386

**Comment by illfated** [comment]
#please-close
