### ISSUE TITLE
Device level profiles

### ISSUE THREAD

**Issue by steve-prentice** [MicrosoftDocs/windowsserverdocs#4439]
MakeProfile.ps has been written for user based VPN profiles, where as we're now looking to deploy machine based VPN profiles. I've managed to modify the created VPN_Profile.ps1 to run in device context rather than user context by removing $options from $session.CreateInstance and running as SYSTEM, but I'm unsure if that's 100% correct.

Please could the script be updated to handle both user (EAP) and/or machine (Certificate) based profiles?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e14da1-102d-3ddf-e2a1-a20ce533b95a
* Version Independent ID: 374edc4c-f527-b7b7-c291-353928b97d8d
* Content: [Configure Windows 10 Client Always On VPN Connections](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections#makeprofileps1-full-script)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by IngridAtMicrosoft** [comment]
Related to #4380.

**Comment by anaharris-ms** [comment]
We're sorry that the docs team was unable to assist you in a timely fashion with your issue, but we appreciate your reaching out to us. The issue you are having isn't really a doc issue, but if you are still experiencing an issue, we encourage you to contact support.

#please-close
