### ISSUE TITLE
Event log docs gone from TechNet - Where to revive them?

### ISSUE THREAD

**Issue by softwarecraft** [MicrosoftDocs/windowsserverdocs#444]
TechNet used to have a nice listing and explanation of all the event log codes, eg [Event ID 6005](http://www.microsoft.com/technet/support/ee/transform.aspx?ProdName=Windows%20Operating%20System&ProdVer=5.2&EvtID=6005&EvtSrc=EventLog&LCID=1033).

In typical Microsoft fashion with the latest web content re-org all these URLs have disappeared although the content is still 100% valid so lots of HTML pages linking to these URLs are SooL, eg [Windows Server restart / shutdown history](https://serverfault.com/questions/702828/windows-server-restart-shutdown-history/702829) on serverfault.

Can someone suggest where in the new MicrosoftDocs universe we revive this content, re-writing it or pulling it from the Internet Archives?

**Comment by daveba** [comment]
If you are looking for previous versions of Windows Server content, please go here: https://docs.microsoft.com/en-us/previous-versions/.  We will now close this issue.

**Comment by softwarecraft** [comment]
> If you are looking for previous versions of Windows Server content, please go here: https://docs.microsoft.com/en-us/previous-versions/. We will now close this issue.

The suggested link does not contain the content I'm referring to, detailed listings and descriptions of Windows Server event log error codes. The development and IT Pro communities need this documentation which has disappeared from MS website. 

Let's find a suitable place to revive this content!

Please re-open this issue.

**Comment by countingpine** [comment]
@daveba can you explain how to find the Event ID pages starting from the link you've posted?
Thanks.
:-)

**Comment by softwarecraft** [comment]
> If you are looking for previous versions of Windows Server content, please go here: https://docs.microsoft.com/en-us/previous-versions/. We will now close this issue.

@daveba your reply didn't resolve this issue, please re-open this issue and review the two follow up comments. Thank you
