### ISSUE TITLE
Feature Request - SSHFS

### ISSUE THREAD

**Issue by breakpoint7** [MicrosoftDocs/windowsserverdocs#4440]
Are there an plans to support SSHFS or get a request in to make a feature request for SSHFS?

**Comment by illfated** [comment]
Disclaimer: I am not affiliated with Microsoft or Microsoft Docs.

I recommend using either the Feedback Hub to get in touch with the developers, or forums like the Microsoft Community (https://answers.microsoft.com) for discussing that topic.

This repository only handles issue reports for the documentation pages (factual errors, improvement suggestions, or requests for updates based on new versions).

**Comment by Xelu86** [comment]
Hey breakpoint7,

Thanks for contacting Microsoft. We value your feedback.

The user above is correct where GitHub issues in the Windows Server repo are monitored for content issues that we can address, such as broken links, grammar or wording, typos, updates, or incorrect code in examples. We offer other channels for engaging with us, whether you have a support question, product feedback, or other feedback. 

We cannot assist with the following as it's outside our scope of work:

- Support cases or support tickets
- [Bug submittal or Feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
- Extended troubleshooting, technical support, or product support

Instead, please use one or more of the following:

 - On a Windows OS, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with using our [Feedback Portal](https://feedbackportal.microsoft.com/feedback).
- Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
- Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

As this is a non-documentation issue, we’re closing this thread.

Thank you and have a most pleasant day. 
#please-close
