### ISSUE TITLE
Logic Error in License Calculator Spreadsheet

### ISSUE THREAD

**Issue by waclark57** [MicrosoftDocs/windowsserverdocs#4447]
There is a logic error in the spreadsheet calculator. The calculator does a simple calculation to determine the correct number of licenses needed for Azure AHUB benefits. I have an example in which I have a set of VMs that require 960 VM and 1808 cores. Your calculation does a simple division of the VMs and Cores based on 2 proc and 16 cores max and takes the larger of the 2. In this case that would be 480 VMs. However, when you look at the cores required 480, 16 core VMs will not suffice. This is because 6 of the 960 VMs require 16 cores total. If you deploy 480, 2 proc, 16 core max instances you will not have enough cores. 

First, you need 6 instances to support the single VM, 16 core requirements. That leaves 954 instances which have 8, 4 or 2 core requirements. You can satisfy that core count with 477, 2 proc, 16 core max instances. 477+6 is 483. Hence you need 483 licenses, not 480, to satisfy these requirements. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90e335dd-0bc5-a7e3-650b-e3dd1823176b
* Version Independent ID: 18f34ef3-ff61-0473-a64b-ac5a64dbe1d7
* Content: [Azure Hybrid Benefit for Windows Server](https://docs.microsoft.com/en-us/windows-server/get-started/azure-hybrid-benefit)
* Content Source: [WindowsServerDocs/get-started/azure-hybrid-benefit.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/azure-hybrid-benefit.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @eross-msft
* Microsoft Alias: **chrisrin**

**Comment by illfated** [comment]
( also ref. issue ticket #488 from the same page )

**Comment by dknappettmsft** [comment]
Thanks for the feedback. The spreadsheet has been retired in favor of the [Azure Hybrid Benefit Savings Calculator](https://azure.microsoft.com/en-gb/pricing/hybrid-benefit/#calculator). The changes to the original article should be visible later today.

#please-close
