### ISSUE TITLE
Link to announcement blog broken

### ISSUE THREAD

**Issue by troyphil** [MicrosoftDocs/windowsserverdocs#4449]
The article contains a link to https://blogs.technet.microsoft.com/networking/2018/07/18/top10-ws2019-hatime/ which redirects to the generic https://techcommunity.microsoft.com/t5/networking-blog/bg-p/NetworkingBlog and thus does not provide the information about the announcement. The content has been archived at https://web.archive.org/web/20180725221612/https://blogs.technet.microsoft.com/networking/2018/07/18/top10-ws2019-hatime/, but not sure what URL Microsoft now use for it.

Also Windows Server 2019 is no longer insider preview, so presumably title of article should change as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b7797e-f018-e538-1a51-dd6ca694b436
* Version Independent ID: ad75618a-360a-b81e-ffab-2a62155335bc
* Content: [Insider preview for Windows Time Service features in Windows Server 2019](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/insider-preview)
* Content Source: [WindowsServerDocs/networking/windows-time-service/insider-preview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/windows-time-service/insider-preview.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @dcuomo
* Microsoft Alias: **dacuo**

**Comment by illfated** [comment]
Thank you for pointing out the outdated link and its current broken redirect.

The correct URL to the blog page named **Top 10 Networking Features in Windows Server 2019: `#10` Accurate Network Time** is the following link:
- https://techcommunity.microsoft.com/t5/networking-blog/top-10-networking-features-in-windows-server-2019-10-accurate/ba-p/339739

To reduce the amount of inaccuracies left to resolve, I am going to create a PR to have the URL corrected.
