### ISSUE TITLE
Quotes usage in **-name** value of command "new-cluster"

### ISSUE THREAD

**Issue by HCaglar** [MicrosoftDocs/windowsserverdocs#4451]
If you receive an error with the command in W. Server 2019, please try again with quotes in **-name** value as:
`New-Cluster -Name "CN=MyCluster,OU=Cluster,DC=Contoso,DC=com" -Node Server1, Server2`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d947ba9b-b87a-867f-1f86-bba7fcfcc734
* Version Independent ID: 251fb0e6-79a8-a135-3ff3-f82a02cff4ab
* Content: [Create a failover cluster](https://docs.microsoft.com/en-us/windows-server/failover-clustering/create-failover-cluster#create-a-failover-cluster-by-using-windows-powershell)
* Content Source: [WindowsServerDocs/failover-clustering/create-failover-cluster.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/create-failover-cluster.md)
* Product: **windows-server**
* Technology: **storage-failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Thank you for the suggestion. It looks quite useful. Do you happen to have an official source page where this has been discussed and concluded?

**Comment by HCaglar** [comment]
Hi
No, I do not have.

I used the command as shown in the page, I had received an error.
When I used it within ("") quotes,  it was okay. Therefore; I shared it in case someone might need it.

**Comment by illfated** [comment]
@JasonGerend / @eross-msft : Do you think this practical feedback could be useful in the documentation, in case other users experience issues like the one referenced by the ticket author?

**Comment by illfated** [comment]
Hmm. Come to think of it, quite a lot of parameter values in PowerShell cmdlets need to be encapsulated in quotes to parse correctly. I wonder if this is more of a PowerShell question than Failover Cluster/ Windows Server 2019 issue.
