### ISSUE TITLE
Set-ClusterQuorum link is outdated

### ISSUE THREAD

**Issue by grayjeremy** [MicrosoftDocs/windowsserverdocs#4454]
The Set-ClusterQuorum link redirects to the Windows Server 2008 powershell in the "[Configuring Cloud Witness Using Powershell](https://docs.microsoft.com/en-us/windows-server/failover-clustering/deploy-cloud-witness#configuring-cloud-witness-using-powershell)" section, can we update it to the newer doc site?

Change [this](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/ee461013(v=technet.10)?redirectedfrom=MSDN) to [this](https://docs.microsoft.com/en-us/powershell/module/failoverclusters/set-clusterquorum?view=win10-ps) or update the [technet link](https://technet.microsoft.com/library/ee461013.aspx) on the page to be the newest version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e6da99e-a148-b5ea-224d-8a4c48604945
* Version Independent ID: a6a90a1f-870c-3501-ce6e-fbf52f802dfb
* Content: [Deploy a cloud witness for a Failover Cluster](https://docs.microsoft.com/en-us/windows-server/failover-clustering/deploy-cloud-witness#configure-cloud-witness-as-a-quorum-witness-for-your-cluster)
* Content Source: [WindowsServerDocs/failover-clustering/deploy-cloud-witness.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/deploy-cloud-witness.md)
* Product: **windows-server**
* Technology: **storage-failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Good point. I will open a PR to have that link updated.
Your link (https://docs.microsoft.com/powershell/module/failoverclusters/set-clusterquorum?view=win10-ps) looks like a very good candidate.

Any other issues on the same page, while we are at it?

**Comment by illfated** [comment]
There you go. PR #4459 is ready for review. Feel free to comment, approve and/or suggest further improvements.

**Comment by illfated** [comment]
Going to make a new PR to resolve the file conflict and build my changes on other events in this repository.

**Comment by illfated** [comment]
New attempt at resolving the issue of the outdated link. My PR #5144 is ready for review (might take until the start of January before it gets merged, due to the holidays).
