### ISSUE TITLE
Wrong name used for ODBC Driver

### ISSUE THREAD

**Issue by NickMRamirez** [MicrosoftDocs/windowsserverdocs#4455]
On the page, [Add the RD Connection Broker server to the deployment and configure high availability](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-connection-broker-cluster), an example connection string is given:

```
Driver={SQL Server Native Client 13.0};Server=tcp:cb-sqls1.database.windows.net,1433;Database=CB-DB1;Uid=sqladmin@contoso;Pwd={your_password_here};Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;
```

The ODBC driver must be installed on the connection broker server, and the page gives a link to that download: https://www.microsoft.com/en-us/download/confirmation.aspx?id=50420

However, whereas the example connection string uses **SQL Server Native Client 13.0** as the name of the driver, it is actually named **ODBC Driver 13 for SQL Server** when installed. This mismatch causes the connection to fail when setting up high availability of connection brokers.

The page should be updated with the correct name of the driver.

**Comment by illfated** [comment]
Thank you for being very precise about the details of this issue.
That resolves an unanswered question I had after looking at the same type of issue ticket in **Suggestion from customer on the Connection string** #4080

I will open a PR to get that string corrected, unless someone else has created a PR already.

**Comment by illfated** [comment]
(ref. #4080 and #4840 )

**Comment by illfated** [comment]
PR #4974 is now ready for review. Feel free to browse, comment, or suggest changes.
