### ISSUE TITLE
Documentation for the netdom command is missing

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/windowsserverdocs#4457]
[Enter feedback here]

Documentation for the netdom command is missing. Please add documentation for the netdom command to the command reference.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d382ca0-6538-5e1d-3e83-e31c9ab6a911
* Version Independent ID: 11eff296-6158-f89a-4941-8735529183e9
* Content: [Windows Commands](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands?source=docs)
* Content Source: [WindowsServerDocs/administration/windows-commands/windows-commands.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/windows-commands.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 4453 -b #assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @rossmpersonal, 

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding the **netdom** command and will be live after the next business day. We are aware that some Windows Commands no longer appear in this list in favor of their PowerShell counterparts found in our [Active Directory PowerShell Modules](https://docs.microsoft.com/en-us/powershell/module/activedirectory/?view=windowsserver2022-ps) reference article.

We are encouraging our users to adopt PowerShell in place of Windows Commands for these commands and potentially more in the future. We will be closing this as resolved. Thank you and have a most pleasant day.

#please-close
