### ISSUE TITLE
"break" command in cmd.exe does not enter a breakpoint

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/windowsserverdocs#4458]
> If command extensions are enabled and running on the Windows platform, inserting the **break** command into a batch file enters a hard-coded breakpoint if being debugged by a debugger.

On Windows 10 version 1909 (OS Build 18363.836), I started `cmd.exe` from within WinDbg and ran a batch file that contained the **break** command, but it did not enter a breakpoint.

Does "the Windows platform" refer only to the Windows 95/98/Me operating systems, as opposed to the NT platform? Such a distinction has existed in the past, e.g. in `VER_PLATFORM_WIN32_WINDOWS` vs. `VER_PLATFORM_WIN32_NT`. If so, I think the paragraph could be removed, because those operating systems are no longer supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc995a12-c47c-715c-9050-dd38bc621ec5
* Version Independent ID: e4f947c4-fa5d-5a4a-ee2b-7d008ebbc8d9
* Content: [break](https://docs.microsoft.com/fi-fi/windows-server/administration/windows-commands/break_1)
* Content Source: [WindowsServerDocs/administration/windows-commands/break_1.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/break_1.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
What about the [important] note on the top of the page, doesn't it explain why the command is unusable on modern files?

![image](https://user-images.githubusercontent.com/38162891/83950975-cbd64280-a82e-11ea-9fbc-7fa51daee12b.png)

**Comment by KalleOlaviNiemitalo** [comment]
The "enters a hard-coded breakpoint" functionality surely is not automatic, so I don't think the important note applies to that.

**Comment by illfated** [comment]
OK, well, then I suppose that page should be retired to the same archive as the retired (no longer supported) versions of Windows.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. A documentation change has been made and can be found in our [reference](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/break) section. Changes are live and we will be closing this thread. Thank you and have a most pleasant day. #please-close
