### ISSUE TITLE
https://docs.microsoft.com/en-us/windows-server/administration/manage-windows-server contains a dead link for Windows PowerShell

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/windowsserverdocs#4460]
https://docs.microsoft.com/en-us/windows-server/administration/manage-windows-server contains a dead link for Windows PowerShell

Steps to reproduce:

1. Go to https://docs.microsoft.com/en-us/windows-server/administration/manage-windows-server .
2. Click on Windows PowerShell.
3. Get a 404.

Please fix this.

**Comment by illfated** [comment]
OK, fair enough. I will see what I can do.

**Comment by illfated** [comment]
OK, so the following seems to be the case:
The page https://docs.microsoft.com/powershell/scripting/powershell-scripting?view=powershell-5.1 (broken, error 404)
moved to https://docs.microsoft.com/powershell/scripting/overview

This is what the original web page looked like, by way of the WayBack machine (Web Archives):
https://web.archive.org/web/20180221051851/https://docs.microsoft.com/en-us/powershell/scripting/powershell-scripting?view=powershell-6&viewFallbackFrom=powershell%3D5.1

Would you mind taking a look and see if the new page (https://docs.microsoft.com/powershell/scripting/overview) is an acceptable replacement?

There are 4 PowerShell versions to choose from, but they don't seem to affect the page much (as far as I can see):
- https://docs.microsoft.com/powershell/scripting/overview?view=powershell-5.1
- https://docs.microsoft.com/powershell/scripting/overview?view=powershell-6
- https://docs.microsoft.com/powershell/scripting/overview?view=powershell-7 (LTS)
- https://docs.microsoft.com/powershell/scripting/overview?view=powershell-7.1 (preview)

**Comment by illfated** [comment]
By the way, I will open a Pull Request (PR) to have the link replaced. Feel free to join in, once I have posted my PR with the link change.

**Comment by illfated** [comment]
Anyway, looking at the archived versions of the PowerShell Scripting page, the archive only contains cmdlet info for versions 3.0, 4.0, and 5.0. 

For version 5.1, we are forced to use the new page, https://docs.microsoft.com/powershell/scripting/overview .

**Comment by illfated** [comment]
Off topic: Would it be OK to ask you to add some minimalistic info to your GitHub profile page, like city/country and maybe full name? (Feel free to ignore this, if you are concerned about privacy.)

**Comment by illfated** [comment]
There you go. PR #4463 is now ready for review. Feel free to join in to comment, approve or suggest further improvement changes.
