### ISSUE TITLE
CoreInfo 3.5 Is An Unreliable/Unauthoritative Tool For Planning Upgrades To Server 2016 & 2019

### ISSUE THREAD

**Issue by OneVideo** [MicrosoftDocs/windowsserverdocs#4462]
Microsoft's <a href="https://docs.microsoft.com/en-us/sysinternals/downloads/coreinfo">CoreInfo v3.5</a> is promoted as an authoritative tool for establishing, in advance, that a particular server hardware platform satisfies the <a href="https://docs.microsoft.com/en-us/windows-server/get-started-19/sys-reqs-19">documented prerequisites necessary for the installation of current Windows Server 2019 packages</a>. 

However, experience shows that the two software products have not been qualified relative to one another.  And further, that there are material differences between the two that can result in large amounts of wasted direct and elapsed time on the part of Information Technology professionals participating in a migration of in-house computing platforms.

In one particular case, a currently out-of-production Dell Poweredge SC1425 with Intel Irwindale family Xeon CPUs (3.60GHz EM64T Family 15 Model 4 Stepping 10, Genuine Intel
Microcode signature: 00000002) is reported by CoreInfo64, in part, as PREFETCHW -	Supports PREFETCHW instruction.  Subsequent bare metal installation of the Server 2019 Standard package (en_windows_server_2019_updated_may_2020_x64_dvd_5651846f.iso) fails to progress past a report that the system's CPU is missing the PREFETCHW capability
  
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e689bd8-af18-5c68-8a10-70fe1837f30b
* Version Independent ID: 7922038d-9327-ac00-df6e-360d5c14de4d
* Content: [Windows Server 2019 System Requirements](https://docs.microsoft.com/en-us/windows-server/get-started-19/sys-reqs-19)
* Content Source: [WindowsServerDocs/get-started-19/sys-reqs-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/sys-reqs-19.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
From my experience installing previous versions of Windows Server on some older HP server models, I usually found it necessary to use HP tools to install Windows. Otherwise, the installation would fail, either at random points, or the install target storage would not show up within the Windows Server setup procedure.

Could this be the case for some Dell servers too, that either Dell software tools or specific BIOS boot procedures need to be started first, to initiate the hardware correctly?

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by robinharwood** [comment]
We hugely appreciate your contribution, feedback, and support to our technical documentation.

We’ve phased out GitHub Issues on this repository as the feedback mechanism for content and have replaced it with a new feedback system. For more information see, [Content User Feedback](https://aka.ms/ContentUserFeedback). As part of this rollout, we are migrating your issue where our team will use your comments to improve the documentation experience. Unfortunately, this does mean you won't be able to access this issue after the migration is complete.

All issues will be migrated by Thursday 29th August 2024.

Once again, thank you for your valuable feedback, we hope you’ll continue to contribute using our new feedback system.
