### ISSUE TITLE
Link to list of RSAT tools available via Features on Demand is dead

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/windowsserverdocs#4464]
[Enter feedback here]

The Link to list of RSAT tools available via Features on Demand is dead.

Also, there are so many dead links on docs.micrsoft.com that Microsoft needs to use an automated tool find all dead links.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdcb12f6-884e-2537-795d-540421900ab1
* Version Independent ID: 4853adc9-67c5-abf0-6c6c-178e8a4e126d
* Content: [Remote Server Administration Tools](https://docs.microsoft.com/en-us/windows-server/remote/remote-server-administration-tools)
* Content Source: [WindowsServerDocs/remote/remote-server-administration-tools.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-server-administration-tools.md)
* Product: **windows-server**
* Technology: **manage-rsat**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by exchange12rocks** [comment]
@rossmpersonal Could you please close this issue, since it seems to be resolved.
