### ISSUE TITLE
Windows Hello For Business Integration

### ISSUE THREAD

**Issue by Silencer0001** [MicrosoftDocs/windowsserverdocs#4465]
Hi,

As advanced feature the integration with "Windows Hello For Business" is highlighted. It also mentions that it's only supported when using **certificate-based authentication**.

Just to be sure: Does this mean that the "certificate trust deployment" needs to be used instead of the "key trust deployment" for Windows Hello For Business?

In the deployment guide of "Windows Hello For Business" it only mentions that authentication to RDP sessions is possible in the "certificate trust deployment", but it doesn't mention "Always-On VPN" capabilities which are dependant on the chosen deployment method.

I would be good to receive some information regarding these 2 Microsoft technologies and how they can integrate with each other. I would also advise to update docs of Windows Hello For Business if the chosen deployment methods results in not being able to use AO VPN integration.

Thanks in advance!

Regards,
Sven

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198d75d5-9988-5eaa-bd24-6f7b46ead75e
* Version Independent ID: d2fffeee-2788-90d5-0ccb-e0e92207997c
* Content: [Advanced Features of Always On VPN](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-adv-options)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-adv-options.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-adv-options.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by IngridAtMicrosoft** [comment]
Hi @Silencer0001.  Please post your question on Microsoft Q&A. https://docs.microsoft.com/en-us/answers/products/
