### ISSUE TITLE
attrib command reference is not up-to-date

### ISSUE THREAD

**Issue by AjayvFTC** [MicrosoftDocs/windowsserverdocs#4466]
We need to update https://docs.microsoft.com/windows-server/administration/windows-commands/attrib
because it is too old.
Recently we have File-On-Demand function in OneDrive, and we can control the file attributes such as &quot;online&quot;, &quot;off-line&quot; etc.
to use the command &quot;attrib&quot;; 
e.g. &quot;attrib +U -P /s&quot;.
But &quot;+U&quot; or &quot;-P&quot; options are not mentioned in the reference page;
https://docs.microsoft.com/windows-server/administration/windows-commands/attrib
Actually this page was updated on Oct-2017 (so old), and we need to update this page to include these new options.
We have many options for ATTRIB function;
ATTRIB 
[+R | -R] [+A | -A] [+S | -S] [+H | -H]
[+O | -O] [+I | -I] [+X | -X] [+P | -P] [+U | -U]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62650d46-4208-8880-2c41-1d7220bfdd89
* Version Independent ID: 9577a78a-7c08-0e57-d507-a7e96a335660
* Content: [attrib](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/attrib)
* Content Source: [WindowsServerDocs/administration/windows-commands/attrib.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/attrib.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Fair point. Lots of the Windows Commands pages could be updated to contain more precise and up to date information from the help text in the command itself.

Please note that it will be necessary to point out where any parameter or argument specific to online services or cloud solutions will be described, in contrast to local filesystem command usage.

Feel free to open a Pull Request for the changes you would like to see in the documentation page, or simply post a comment here containing the text & format of your suggested change.

**Comment by Xelu86** [comment]
Hey AjayvFTC,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation update has been made adding the missing parameters for `attrib` and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
