### ISSUE TITLE
typo error  in memory.hdmp 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/windowsserverdocs#4474]
I found one typo error, **memory.dump** is wrongly entered as **memory.hdmp**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69242460-9916-0cca-0858-a36f7f427991
* Version Independent ID: c154f1d7-ec73-2d8d-5fd8-7adf18b668a5
* Content: [Troubleshooting a Failover Cluster using Windows Error Reporting](https://docs.microsoft.com/en-us/windows-server/failover-clustering/troubleshooting-using-wer-reports)
* Content Source: [WindowsServerDocs/failover-clustering/troubleshooting-using-WER-reports.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/troubleshooting-using-WER-reports.md)
* Product: **windows-server**
* Technology: **storage-failover-clustering**
* GitHub Login: @dcuomo
* Microsoft Alias: **vpetter**

**Comment by illfated** [comment]
From https://github.com/MicrosoftDocs/windowsserverdocs/pull/4475#issuecomment-641529423
> Thank you for your efforts. This is where I have to correct myself and tell you that we were both wrong, in one way or another.
> 
> Modern versions of Windows (Windows 10, Windows Server 2016, Windows Server 2019 running WER (Windows Error Reporting) can produce 3 types of memory dumps:
> 
> 1. Minidump - `memory.mdmp`
> 2. Kernel dump - `memory.dmp`
> 3. Complete memory dump (Memory Heap dump) - `memory.hdmp`
> 
> This means that the text you suggest to change is actually supposed to be the way it is. Therefore, I recommend that you close this PR and issue #4474 .
> 
> Thank you for keeping up the good work, though. Good effort. 👍

#please-close

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
