### ISSUE TITLE
Demoting Secondary controller/s

### ISSUE THREAD

**Issue by elvirk** [MicrosoftDocs/windowsserverdocs#4484]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4db96074-3ebd-a88e-5d1c-fc8e8083c5c5
* Version Independent ID: 0b5d953b-8fce-410f-037e-e81dda94a477
* Content: [Demoting Domain Controllers and Domains (Level 200)](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/demoting-domain-controllers-and-domains--level-200-)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/Demoting-Domain-Controllers-and-Domains--Level-200-.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/Demoting-Domain-Controllers-and-Domains--Level-200-.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by IngridAtMicrosoft** [comment]
@elvirk My guess is that you have already found the answer to your question, but I have asked it over at Microsoft Q & A.  Here are the answers given.

https://learn.microsoft.com/en-us/answers/questions/1287325/demoting-secondary-controllers
