### ISSUE TITLE
Parameter Cannot be found that matches EnableSMB3Protocol

### ISSUE THREAD

**Issue by rawsGit** [MicrosoftDocs/windowsserverdocs#4490]
[Set-SmbServerConfiguration -EnableSMB3Protocol $true                                            Set-SmbServerConfiguration : A parameter cannot be found that matches parameter name 'EnableSMB3Protocol'.
At line:1 char:28
+ Set-SmbServerConfiguration -EnableSMB3Protocol $true
+                            ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-SmbServerConfiguration], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Set-SmbServerConfigurationEnter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a91db45-ca3c-7a2e-3f32-2f5b57837b03
* Version Independent ID: b83cbaab-c0df-d6e7-a67f-f4c99a46e30a
* Content: [How to detect, enable and disable SMBv1, SMBv2, and SMBv3 in Windows](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md)
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by rawsGit** [comment]
Additionally Info:
Version 10.0.18363 Build 18363 
Hardware Abstraction Layer Version = 10.0.18362.752
PS> Get-SmbServerConfiguration 
EnableSMB1Protocol              : False
EnableSMB2Protocol              : True
PS> Get-SmbServerConfiguration | Select EnableSmb3Protocol
EnableSmb3Protocol
------------------

**Comment by IngridAtMicrosoft** [comment]
Hi @rawsGit.   Thank you for your dedication to documentation! This issue seems to be a request for support and is therefore being closed.  If you still feel that the documentation needs to be updated, please clarify what needs to change in the document you are reporting and ask for the issue to be reopened. #please-close
