### ISSUE TITLE
Ubuntu 20.04 LTS?

### ISSUE THREAD

**Issue by joel0** [MicrosoftDocs/windowsserverdocs#4498]
On the page of supported Ubuntu guest OS versions, it would be good to mention Ubuntu 20.04 LTS.  If it's supported, I'd expect a column; if it's unsupported, a note making that clear would be good.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84d52296-198d-7c8a-db99-e8cb336e355f
* Version Independent ID: 77670399-109f-3233-0466-c13d84542039
* Content: [Supported Ubuntu virtual machines on Hyper-V](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-ubuntu-virtual-machines-on-hyper-v)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Supported-Ubuntu-virtual-machines-on-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/Supported-Ubuntu-virtual-machines-on-Hyper-V.md)
* Product: **windows-server**
* Technology: **compute-hyper-v**
* GitHub Login: @shirgall
* Microsoft Alias: **shirgall**

**Comment by konstruktoid** [comment]
Fixed by https://github.com/MicrosoftDocs/windowsserverdocs/commit/fb78b64c3a2ffc434c1e04d16cf7804e9c00df81?

**Comment by shirgall** [comment]
Fixed by https://github.com/MicrosoftDocs/windowsserverdocs/commit/fb78b64c3a2ffc434c1e04d16cf7804e9c00df81#diff-2c87b9243c51b6fdef6774ae8e77296f172eca2841618beee48d6e0430185e4b
