### ISSUE TITLE
Misleading Document

### ISSUE THREAD

**Issue by D4-AzIdentity** [MicrosoftDocs/windowsserverdocs#4499]
Hello Team,

I believe the following documentation is slightly misleading 
[https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/best-practices-securing-ad-fs#optional-min-set-of-endpoints-proxy-enabled-for-azure-ad--office-365]

/adfs/services/trust/2005/usernamemixed	Used for Exchange Online with Office clients older than Office 2013 May 2015 update. Later clients use the passive \adfs\ls endpoint.
/adfs/services/trust/13/usernamemixed	Used for Exchange Online with Office clients older than Office 2013 May 2015 update. Later clients use the passive \adfs\ls endpoint.

This may be leading Cx on modern versions of Office to disable these endpoints without thinking about other services such as device registration which use these endpoints. 

For example in Federated environments these endpoint are required for Hybrid Azure AD Join. 
[https://docs.microsoft.com/en-us/azure/active-directory/devices/hybrid-azuread-join-plan#federated-environment]

Please update the recommendation here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6bdcea6-e429-95ce-0012-a30241941e36
* Version Independent ID: b37b7c92-12d0-9d03-c181-05b7cfcbe276
* Content: [Best Practices for securing AD FS and Web Application Proxy](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/best-practices-securing-ad-fs#optional-min-set-of-endpoints-proxy-enabled-for-azure-ad--office-365)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Best-Practices-Securing-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Best-Practices-Securing-AD-FS.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
