### ISSUE TITLE
Managing SSL/TLS Protocols and Cipher Suites for AD FS

### ISSUE THREAD

**Issue by eLgRuNgE** [MicrosoftDocs/windowsserverdocs#4500]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f505619-9097-e736-4c6a-8ec57c631f7d
* Version Independent ID: 12dc28e7-d8bf-4cca-95e5-0547b4f46b08
* Content: [Managing SSL/TLS Protocols and Cipher Suites for AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/manage-ssl-protocols-in-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Manage-SSL-Protocols-in-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Manage-SSL-Protocols-in-AD-FS.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by kevin-tunge-spok** [comment]
How can we admins do this on a per RPT basis? I have some SP's that require TLS 1.2 and others that don't/can't support it.

**Comment by exchange12rocks** [comment]
@kevin-tunge-spok You can't - those settings are on the system level. Just enable both TLS 1.2 and TLS 1.1.

**Comment by exchange12rocks** [comment]
@eLgRuNgE What is your feedback about that page? You didn't provide any in your issue.

**Comment by kevin-tunge-spok** [comment]
> @kevin-tunge-spok You can't - those settings are on the system level. Just enable both TLS 1.2 and TLS 1.1.

Thank you @exchange12rocks, I suspected as much, just was looking to verify it with others who may have had the same issues. I appreciate the reply!

**Comment by illfated** [comment]
@exchange12rocks : The ticket looks like a test post by the ticket author, so we may have to close this, unless we hear from them again soon.

@eLgRuNgE : Unless you post a comment containing what you want to report as an issue with the page, we will have to conclude that this was just a test and close the ticket.

**Comment by PRMerger17** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: ingridatmicrosoft 
gh issue comment 4499 -b ingridatmicrosoft

**Comment by Xelu86** [comment]
#please-close
