### ISSUE TITLE
Support for 2016 RDSH environments that aren't Windows Virtual Desktop

### ISSUE THREAD

**Issue by itthing** [MicrosoftDocs/windowsserverdocs#4502]
The features I'm seeing in the MSRDC look phenomenal!  We run our Server 2016 environment in Azure, but it appears we cannot access it using MSRDC and are instead stuck with MSTSC.

Does the roadmap for MSRDC include adding the features supported by MSTSC?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ab98fc-fea2-a11a-e5ca-de1430211d97
* Version Independent ID: 4d9943c3-fef7-ca86-bd03-1241a04b8135
* Content: [Get started with the Windows Desktop client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by dknappettmsft** [comment]
Closing the loop on this - no the MSRDC app can't access RDS and isn't on the roadmap to do that.
