### ISSUE TITLE
Missing description of new /SJ switch

### ISSUE THREAD

**Issue by barry-luijten** [MicrosoftDocs/windowsserverdocs#4505]
I accidentally discovered the new /SJ switch in the Windows 10 2004 version of robocopy. This very useful switch copies JUNCTIONS as real junctions instead of directories (default behavior).
It would be nice to have this option documented ;)
Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @barry-luijten, 

Thanks again for contacting Microsoft. We value your feedback. A documentation change has been made for the /sj parameter and will be live after the next business day. 

We will be closing this as resolved. Thank you and have a most pleasant day. #please-close

**Comment by barry-luijten** [comment]
Thank you @Xelu86! :)
