### ISSUE TITLE
Redirection problem of this document for a German Language setting browser  

### ISSUE THREAD

**Issue by OrkunAKSU** [MicrosoftDocs/windowsserverdocs#4506]
Hi Dears , 

"NTFS - Delayed Write Host" rule fire alerts from the SCOM side and we can see  http://go.microsoft.com/fwlink/?LinkId=25977 at the knowledge tab of the rule to get more details which is totally redirect it to this URL which is https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/troubleshoot-event-id-50-error when used EN-US in the settings of the language of the Internet Options.
But when we set the language of the Internet Options as German then it tries to reach out to https://support.microsoft.com/?scid=kb;de-de;816004 and display nothing  even if it need to redirect to https://docs.microsoft.com/de-de/windows-server/storage/file-server/troubleshoot/troubleshoot-event-id-50-error for the German language settings.  We do not have any other similar issue with the other redirections and just this one having this proıblem so think that there is some redirection problem for the German language . Btw, I have tested with French , Spanish , And some other languages all is working very well . Can you please help us to handle this redirection issue ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fa148d7-c2ce-dc38-8da3-957bafa62683
* Version Independent ID: 70e3cc32-72eb-524a-fb61-7f1b67eaa4db
* Content: [Troubleshoot the Event ID 50 Error Message](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/troubleshoot-event-id-50-error)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/troubleshoot-event-id-50-error.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/Troubleshoot/troubleshoot-event-id-50-error.md)
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by illfated** [comment]
Thank you for reporting that odd /de-de/ (German) redirect issue. Am I understanding you correctly, that this happens in a Windows Server GUI or SCCM interface (Configuration Manager, previously known as "System Center Configuration Manager")?

I think perhaps it would be useful to report this to the developers via Feedback Hub, but I will chance pinging some team members to ask if this can be forwarded to the microsoft.com web management team, in case this needs to be handled directly in the www.microsoft.com domain.

@JasonGerend or @eross-msft - would you like to forward this report, in case it is an internal microsoft.com link redirect issue?

**Comment by eross-msft** [comment]
@illfated  @OrkunAKSU Thanks for sending this...it's definitely odd.  I'm forwarding this to our localization team to see if they have any insight into the issue. Thanks!!

**Comment by v-cakoll** [comment]
@OrkunAKSU Thank you for letting us know about this. Can you please send a screenshot of where this occurs?
