### ISSUE TITLE
What about Remote Desktop for Administration?

### ISSUE THREAD

**Issue by KitLemmonds** [MicrosoftDocs/windowsserverdocs#4508]
This page adds to confusion about Remote Desktop licensing.  According to this page, Remote Desktop for Administration doesn't even exist.  We have several admins who need to quickly remote into our Windows Server 2016 boxes in separate domains and start/restart a service, then log right back out again.  Why would a separate license be needed to administrate a server that's not included in the server's operating system license?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd015c0b-3360-88fd-86b1-08e8c0e8ec5e
* Version Independent ID: 0c3ddb09-23f3-68a3-e7a4-877951feb55b
* Content: [License your RDS deployment with client access licenses (CALs)](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-client-access-license)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-client-access-license.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-client-access-license.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
Hello @KitLemmonds. Please post your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html).

**Comment by ptrtech1** [comment]
Microsoft has no documentation anywhere on "Remote Desktop for Administration", so to the original poster's point, you draw great confusion with this article completely ignoring it.
