### ISSUE TITLE
IPv6 statement no longer true

### ISSUE THREAD

**Issue by aqasrawi** [MicrosoftDocs/windowsserverdocs#4512]
The statement "Because Azure virtual networks do not support IPv6" is no longer true as VNETs do now support IPv6.  In fact the link you have on the page gets directed to this page https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-faq#do-vnets-support-ipv6 where it's clearly stated it's now supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b0097c-668e-1d37-22b0-89d0bf649f8a
* Version Independent ID: 49ccfef6-05bb-9c93-5a05-a2e2fe632b3c
* Content: [Install Active Directory Domain Services on an Azure virtual machine](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm.md)
* Product: **windows-server**
* Technology: **identity-adds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by illfated** [comment]
Thank you for pointing out this change in support for IPv6 and the implication it has on this document page.

I will start a Pull Request to have those 2 paragraphs altered to remove the incorrect statement.

**Comment by illfated** [comment]
There you go. PR #4513 is ready for review, comments and suggestions.
