### ISSUE TITLE
It creates 9 groups - not 6

### ISSUE THREAD

**Issue by githubsteveb** [MicrosoftDocs/windowsserverdocs#4515]
The article says it creates 6 groups

```
Groups
Six new security-enabled global groups: Tier 0 Replication Maintenance; Tier 1 Server Maintenance; Service Desk Operators; Workstation Maintenance; PAW Users; PAW Maintenance.
```
however there is 9 groups (they are listed in the Group.csv)

1. Tier 0 Replication Maintenance
2. Tier 1 Server Maintenance
3. Service Desk Operators
4. Workstation Maintenance
5. Cloud Service Admins
6. PAW Users
7. PAW Maintenance
8. Tier 1 Admins
9. Tier 2 Admins

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae0917f-d36a-ab81-c41a-03eb25bcb5fd
* Version Independent ID: 8166929e-bf9b-512d-eab0-75851f599a7a
* Content: [Why Privileged Access Workstations can help secure your organization](https://docs.microsoft.com/en-gb/windows-server/identity/securing-privileged-access/privileged-access-workstations?redirectedfrom=MSDN#phase-1-immediate-deployment-for-active-directory-administrators)
* Content Source: [WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md)
* Product: **windows-server**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by illfated** [comment]
Good point. This is what the CSV file contains in the ZIP file script download:

| Name | samAccountName | GroupCategory | GroupScope | DisplayName | OU | Description | Membership |
| ---- | -------------- |:-------------:|:----------:| ----------- | -- | ----------- | ---------- |
| Tier 0 Replication Maintenance | Tier0ReplicationMaintenance | Security | Global | Tier 0 Replication Maintenance | "OU=Groups,OU=Tier 0,OU=Admin" | Members of this group are Tier 0 Replication Maintenance |
| Tier 1 Server Maintenance | Tier1ServerMaintenance | Security | Global | Tier 1 Server Maintenance | "OU=Groups,OU=Tier 1,OU=Admin" | Members of this group perform Tier 1 Server Maintenance |
| Service Desk Operators | ServiceDeskOperators | Security | Global | Service Desk Operators | "OU=Groups,OU=Tier 2,OU=Admin" | Members of this group are Service Desk Operators |
| Workstation Maintenance | WorkstationMaintenance | Security | Global | Workstation Maintenance | "OU=Groups,OU=Tier 2,OU=Admin" | Members of this group perform Workstation Maintenance |
| Cloud Service Admins | cloudadmins | Security | Global | Cloud Service Admins | "OU=Groups,OU=Tier 0,OU=Admin" | Members of this group are permitted to connect to pre-identified cloud services via Privileged Access Workstations |
| PAW Users | pawusers | Security | Global | PAW Users | "OU=Groups,OU=Tier 0,OU=Admin" | Members of this group are permitted to log onto Privileged Access Workstations |
| PAW Maintenance | pawmaint | Security | Global | PAW Maintenance | "OU=Groups,OU=Tier 0,OU=Admin" | Members of this group maintain and support Privileged Access Workstations |
| Tier 1 Admins | tier1admins | Security | Global | Tier 1 Admins | "OU=Groups,OU=Tier 1,OU=Admin" | Members of this group are Tier 1 Administrators |
| Tier 2 Admins | tier2admins | Security | Global | Tier 2 Admins | "OU=Groups,OU=Tier 2,OU=Admin" | Members of this group are Tier 2 Administrators |

(Apologies for the cramped view, to those of you who don't have a working Wide GitHub browser extension.)

**Comment by illfated** [comment]
Maybe an image is more useful, taken from Excel after converting the CSV to spreadsheet content:

![image](https://user-images.githubusercontent.com/38162891/85175720-5e87d000-b278-11ea-90ed-241a453bdf6e.png)

**Comment by illfated** [comment]
I am thinking about how to modify the page, so any help you could offer is appreciated to suggest the sections in need of change and how it could look with the correct number of groups in them.

I am thinking, among other things, that it is more useful to list those groups in a numbered list or at least a bullet point list.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
