### ISSUE TITLE
This page is BROKEN INCOMPLETE

### ISSUE THREAD

**Issue by agvardha** [MicrosoftDocs/windowsserverdocs#4516]
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/lodctr

What is the point in giving incomplete information. How much time is wasted by this half backed page.  Look at this page for full info:
https://ss64.com/nt/lodctr.html

Also when we do lodctr /? why does it not show all the options? What is the point in hiding it? Such  a waste of time!!!! 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4b3ac89-b24b-e0c9-3c32-6f341e99d256
* Version Independent ID: 5fbaecde-5418-5179-9690-17f87843a131
* Content: [lodctr](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/lodctr)
* Content Source: [WindowsServerDocs/administration/windows-commands/lodctr.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/lodctr.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Thank you for sharing your view on this topic, I don't know exactly why the page is short of information, but if I could make a guess, maybe it is to avoid showing options not available on all the listed server versions on the page? I notice that in Windows 10, version 2004 (OS build 19041.329), the command `lodctr /?` provides a lot more information, but I haven't researched if all of them are available on, for example, Windows Server 2016 Standard.

This repository is intended for reporting errors or requesting improvements or version updates, but it would also help a lot if you have got time to post a suggestion of what you think the page should contain (maybe even a draft for the content you want to see added) to help us all out in the process of improving this documentation.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

What I am willing to offer, is to create a Pull Request to have this page updated, if you would be so kind as to provide some information about what we can expect the command to support in the listed Server OS versions.

Looking forward to your reply.

**Comment by illfated** [comment]
Please, feel free to continue using the **ss64.com** site (https://ss64.com/nt/) for Desktop/Laptop use.
 
The main idea here in the Windows Server docs is to keep a simple, barebone reference level for Server use, not so much for client device use.

**Comment by illfated** [comment]
#please-close
