### ISSUE TITLE
Server 2004 Released but not this page

### ISSUE THREAD

**Issue by rmrosen** [MicrosoftDocs/windowsserverdocs#4517]
Please add Server 2004 here. Per Lifecycle, it released May 27, 2020:
https://support.microsoft.com/en-us/lifecycle/search?alpha=2004%20windows

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbf74885-9525-9828-95c9-0ab9167b1f35
* Version Independent ID: f0a39382-120b-0cfa-692f-621124a23f37
* Content: [Windows Server release information](https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info)
* Content Source: [WindowsServerDocs/get-started/windows-server-release-info.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/windows-server-release-info.md)
* Product: **windows-server**
* Technology: **server-general**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
We may need to get some required information to suggest the specific content update.
- https://docs.microsoft.com/windows-server/get-started/whats-new-in-windows-server-2004
- https://techcommunity.microsoft.com/t5/containers/windows-server-version-2004-now-available/ba-p/1419194

Unfortunately, those pages do not list the exact build number required in that table. Have you tried downloading an ISO with Docker and installed it to be able to list the OS build numbers?

**Comment by rmrosen** [comment]
@MicrosoftDocs/windowsservercontent still no entry for 2004? It has been out for over 3 months now.

**Comment by exchange12rocks** [comment]
I think it was fixed in 30fb6dd
@rmrosen could you please confirm?

**Comment by illfated** [comment]
(Direct file source change link: https://github.com/MicrosoftDocs/windowsserverdocs/commit/30fb6ddc320291fb89cf2b93e44879d59f9de186#diff-c7e8f4154bb3aea37087cd2ca928c5e985d5b6946eae1d597f16dea29fa942eb)

**Comment by illfated** [comment]
Looks resolved to me, but a confirmation from the ticket author is welcome.

**Comment by rmrosen** [comment]
Confirmed resolved with 20H2 publishing.

Thanks!

Ray Rosen
Senior Customer Success Account Manager | Microsoft
