### ISSUE TITLE
Update picture in a document

### ISSUE THREAD

**Issue by mihapihler** [MicrosoftDocs/windowsserverdocs#453]
The picture in the document https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/get-started/virtual-dc/virtualized-domain-controller-architecture is incorrect.

The picture URL is https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/get-started/virtual-dc/media/virtualized-domain-controller-architecture/adds_vdc_virtualizationsafeguardsduringsnapshotrestore.png

In the bottom right corner of the picture there is the following information

DC1(A)@USN = 200
DC1(A)@USN = 250

this should be

DC1(A)@USN = 200
DC1(B)@USN = 250

This is the old picture https://docs.microsoft.com/en-us/windows-server/identity/media/introduction-to-active-directory-domain-services--ad-ds--virtualization--level-100-/adds_vdc_exampleofhowsafeguardswork.gif and information in this picture is correct -- (A) and (B)

**Comment by mihapihler** [comment]
Update the picture in a document.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
