### ISSUE TITLE
duplicate information

### ISSUE THREAD

**Issue by thabaum** [MicrosoftDocs/windowsserverdocs#4573]
## Issue

I kept finding a lot of duplicate information so I cleaned up docs as it was just a lot to read over and over and over....

Maybe Mr. Bill can squeak out a night at one of his resorts for me during a slow season or a drink during happy hour.  AB is nice this time of the year ;) always a pleasure to help no worries life is short!

## The Final Report

I created a number of PR's as I found them... I should of created one but I was not working on this tonight, in fact this set me back a lot.  I visit this section a lot so it will save my eyes time down the road... time is money!

## MS Docs Bug

There must be a bug moving information to docs as I found this on Office 365 and Xbox docs...  this is fairly fresh stuff so the bug must still remain.

## Notes

The bug must be related to the links being created for the content.  It seems whenever a link was created when these docs had been merged with other docs I am guessing there was two links created doubling the content for those links. 

I kept these separate due to the fact some links start with `.../<section>/` and the others do not have that appended at the beginning of the links created.  I did not catch this until later on... when I was thinking about making one bigger PR, however documents sometimes are better to work on one page at a time.  There are misc issues I noted in some PR's.

My guess is the merge script used needs a tuning.

I went through this entire set of sections and sub sections... I will go over my PR's for duplicate file entries as I may have done some of those since this was not in one PR you can look at each file on it's own for other issues and to be sure the links created are properly created as desired.

https://docs.microsoft.com/en-us/windows-server-essentials/get-started/get-started

## P.S.
Sorry for so many PR's, but just think, if you have to read this once... think of all the others that had to put the time into this and possible confusion which I had.  

I am hoping this resolves the issues in these sections at least for people like me are already stressed enough trying to make things work ;)

On another note the docs are getting better, clearer and more precise!  Keep up the good work contributors we love it!

## Past Issue Details
https://github.com/MicrosoftDocs/windowsserverdocs/pull/4083

Looks like about 52 total files in this **Windows Server Docs** section had this issue.

May be worth investigating other sections.

**Comment by RAJU2529** [comment]
@StevenEk. Please assign the user to verify many PR . This user @thabaum  has created PR , so carefull verifications are needed before merging.

**Comment by thabaum** [comment]
@eross-msft Thank you for taking the time to merge all of these changes as always it was a pleasure to help!
