### ISSUE TITLE
Next Steps are outdated

### ISSUE THREAD

**Issue by davemct** [MicrosoftDocs/windowsserverdocs#4574]
Greetings,

I would love to be able to check and test my S2D setup.  You have, as part of the very end of this page, a link to NOT testing S2D but rather Storage Spaces on Windows Server 2012.

Do you have ANY documentation that either updates the referred page, or shows how to test S2D after setting it up? I would be most grateful for this!

Here's the text I am referring to:

**Next steps**
After deploying your clustered file server, we recommend testing the performance of your solution using synthetic workloads prior to bringing up any real workloads. This lets you confirm that the solution is performing properly and work out any lingering issues before adding the complexity of workloads. For more info, see [Test Storage Spaces Performance Using Synthetic Workloads.
](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn894707(v=ws.11))

Dave Franklyn, MCT, MVP
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af5d56ce-6ce8-772c-f1c5-c314b9f05dcd
* Version Independent ID: 2ca4d497-707f-4507-7431-ef3fdbb3ec7d
* Content: [Deploy Storage Spaces Direct](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/deploy-storage-spaces-direct)
* Content Source: [WindowsServerDocs/storage/storage-spaces/deploy-storage-spaces-direct.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/deploy-storage-spaces-direct.md)
* Product: **windows-server**
* Technology: **storage-spaces**
* GitHub Login: @StevenEk
* Microsoft Alias: **stevenek**

**Comment by IngridAtMicrosoft** [comment]
Addressed. #please-close
