### ISSUE TITLE
schtasks Documentation Error

### ISSUE THREAD

**Issue by paupal1** [MicrosoftDocs/windowsserverdocs#4578]
The documentation for: "To schedule a task that runs every time the system starts" gives the following command as an example. This command is incorrect - /sd should not be specified for ONSTART tasks.

```
schtasks /create /tn My App /tr c:\apps\myapp.exe /sc onstart /sd 03/15/2001

ERROR: The options /RI, /DU, /ST, /SD, /ET, /ED and /K  are not applicable for the scheduled types: ONSTART, ONLOGON, ONIDLE, ONEVENT.
Type "SCHTASKS /CREATE /?" for usage.
```

This is for Windows Server 2019 Datacenter
Build: 17763.1282

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 017089b7-e7fe-f1d8-854f-91d1619164b6
* Version Independent ID: 766063ce-6e31-fa5f-da41-27b75ecec05d
* Content: [schtasks](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/schtasks#BKMK_startup)
* Content Source: [WindowsServerDocs/administration/windows-commands/schtasks.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/schtasks.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. A documentation change has been made and will be live after the next business day. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
