### ISSUE TITLE
ReFS vs NTFS comparisons

### ISSUE THREAD

**Issue by scoobert** [MicrosoftDocs/windowsserverdocs#4579]
Isn't the ReFS file/path name limitation much greater than 255 unicode characters? The chart in the middle of the page shows it equal to NTFS, which is very confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1239e469-71b9-faa2-9e4c-2999bbb06e87
* Version Independent ID: 5461ce26-c20b-4a04-692f-1a3721bb96f5
* Content: [Resilient File System (ReFS) overview](https://docs.microsoft.com/en-us/windows-server/storage/refs/refs-overview)
* Content Source: [WindowsServerDocs/storage/refs/refs-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/refs/refs-overview.md)
* Product: **windows-server**
* Technology: **storage-file-systems**
* GitHub Login: @gawatu
* Microsoft Alias: **gawatu**

**Comment by wbsmolen** [comment]
Sorry for the late response @scoobert. Our team is working to better monitor doc feedback on GitHub.

The table is accurate - the limit is 255 characters for both file systems.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @scoobert,

Thanks again for contacting Microsoft. We value your feedback. 

It appears that @wbsmolen has provided us an answer that the current table does reflect correctly that the character limitation is 255 for both file systems. Thank you kindly @wbsmolen for providing clarity on this!

@scoobert, we will now be closing this thread. Thank you and we wish you a most pleasant day!

#please-close
