### ISSUE TITLE
REG_MULTI_SZ

### ISSUE THREAD

**Issue by markfilipak-windows** [MicrosoftDocs/windowsserverdocs#4583]
REG_MULTI_SZ needs an example that adds multiple string values and data, not a single string value (trivial case). Also, how does '/s <Separator>' fit into it?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd817f1d-e494-af38-4a10-86360d63c195
* Version Independent ID: 11fcbf91-6c28-9ae8-045a-35ea97444dfe
* Content: [reg add](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/reg-add)
* Content Source: [WindowsServerDocs/administration/windows-commands/reg-add.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/reg-add.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Well, the way I read it, there is at least one example of multiple strings added by the example command
```
REG ADD HKLM\Software\MyCo /v MRU /t REG_MULTI_SZ /d fax\0mail\0\0
```
Note in particular the table entry and description below:

|    Parameter   | Description |
| :------------: | :---------- |
| /s <Separator> | Specifies the character to be used to separate multiple instances of data when the REG_MULTI_SZ data type is specified and more than one entry needs to be listed. If not specified, **the default separator is \0**. |

This means that the command REG ADD HKLM\Software\MyCo /v MRU /t REG_MULTI_SZ /d **fax\0mail\0\0** adds the data set
```
fax
mail

```
to the value named "MRU" (Most Recently Used) inside the subkey HKLM\Software\MyCo .

Note in particular the extra blank line below the added data, which stems from the ending **\0** in the data set.

I do not see a specific explanation for the separator \0 on this page, but I am fairly sure that experienced registry maintainers are aware that the separator \0 translates as `<Enter>` or NewLine / Carriage Return.

**Comment by illfated** [comment]
By the way, if you want to use a different separator from the default NewLine / Carriage Return, you could possibly use comma or semicolon, if that makes more sense to your own data set. I have not yet found an easy way to search for the specifics regarding how to specify other separators than \0, but you could export a subkey or value containing the separators you want to duplicate, then look at the contents of the exported data set to find if the separators are encoded or shown in plain text.

**Comment by markfilipak-windows** [comment]
Thank you, Trond,
You are indeed correct. I was not paying sufficient attention. But I'm happy to explain one thing to you! '\0' is a binary zero (also known as 'null'), not a newline or carriage return. The strings are called "z-strings" because '\0' is the string terminator. Use of z-strings is common in the 'C' language. ...I guess this proves that two heads are better than one. Cheers!
