### ISSUE TITLE
Incorrect path

### ISSUE THREAD

**Issue by johnckirk** [MicrosoftDocs/windowsserverdocs#4584]
[Enter feedback here]
In the export section, step 3 refers to "%programfiles%\Active Directory Federation Services 2.0\Microsoft.IdentityServer.Servicehost.exe.config"
On my 2012 server, the correct path was "%windir%\ADFS\Microsoft.IdentityServer.Servicehost.exe.config"
I didn't change the default path when I added that role.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c9ee880-410e-baa6-c4b3-79796116d2b4
* Version Independent ID: ae800f9c-239b-4d9c-03bb-e8926ee148ec
* Content: [Migrate the AD FS 2.0 federation server](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/migrate-ad-fs-fed-server-r2)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/migrate-ad-fs-fed-server-r2.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/migrate-ad-fs-fed-server-r2.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
While searching the web for pages describing those location paths, I noticed a recurring difference between them.
Searching for "%windir%\ADFS\Microsoft.IdentityServer.Servicehost.exe.config" (more often than not) refers to **ADFS 3.0**, whereas search results for "%programfiles%\Active Directory Federation Services 2.0\Microsoft.IdentityServer.Servicehost.exe.config" frequently refers to **ADFS 2.0**. Could it be that the different versions use different location paths?

**Comment by johnckirk** [comment]
Checking my servers, Windows Server 2012 (ADFS 2.1) and Windows Server 2012 R2 (ADFS 3.0) both use %windir%. I haven't tried Windows Server 2008 R2 (ADFS 2.0), so it's possible that it uses %programfiles%.

**Comment by johnckirk** [comment]
Checking the original document again, I realise that this was a migration guide from ADFS 2.0 rather than 2.1. Sorry, my mistake!

**Comment by illfated** [comment]
Fair enough. Sharing a mistake is just as useful, especially seeing that it simplifies resolving the issue. Thank you.

**Comment by MAHEENKANNOOZ** [comment]
Done
