### ISSUE TITLE
Mangled Text Encoding

### ISSUE THREAD

**Issue by lmmarsano** [MicrosoftDocs/windowsserverdocs#459]
In [certreq -new](/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/certreq_1.md#certreq--new), the mangled text

```Markdown
“template�?
�?WebServer�?
```

appears.
Unfortunately, it's in critical sections regarding inf file syntax that make the correct syntax difficult to guess.
Please fix these text encoding issues?

**Comment by lizap** [comment]
I've updated the encoding. Thanks!
