### ISSUE TITLE
unable to create DnsServerQueryResolutionPolicy as example has it

### ISSUE THREAD

**Issue by raymondtant** [MicrosoftDocs/windowsserverdocs#4597]
I was only able to make this work by adding a criteria to the last cmdlet:
-FQDN "eq,www.contosogiftservices.com"

I am sure other criteria would have worked

I assume it was missing.

this is the replacement line: Add-DnsServerQueryResolutionPolicy -Name "AmericaPolicy" -Action ALLOW **-FQDN "eq,www.contosogiftservices.com"** -ZoneScope "SeattleZoneScope,2;ChicagoZoneScope,1;DallasZoneScope,1" -ZoneName "contosogiftservices.com"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bb1b428-6fe2-cde9-3c05-595676b26be7
* Version Independent ID: dd23fffe-6422-c22c-db4a-72da2f110941
* Content: [Use DNS Policy for Application Load Balancing](https://docs.microsoft.com/en-us/windows-server/networking/dns/deploy/app-lb)
* Content Source: [WindowsServerDocs/networking/dns/deploy/app-lb.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/dns/deploy/app-lb.md)
* Product: **windows-server**
* Technology: **networking-dns**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
Thank you for the constructive feedback. I take it you are referring to tests you have done, as a training exercise, to come up with that result.

Original command line:
```PowerShell
Add-DnsServerQueryResolutionPolicy -Name "AmericaPolicy" -Action ALLOW -ZoneScope "SeattleZoneScope,2;ChicagoZoneScope,1;DallasZoneScope,1" -ZoneName "contosogiftservices.com"
```

Proposed command line:
```PowerShell
Add-DnsServerQueryResolutionPolicy -Name "AmericaPolicy" -Action ALLOW -FQDN "eq,www.contosogiftservices.com" -ZoneScope "SeattleZoneScope,2;ChicagoZoneScope,1;DallasZoneScope,1" -ZoneName "contosogiftservices.com"
```
Is this a reasonably correct interpretation of your post?

**Comment by illfated** [comment]
BTW, I looked up the PowerShell page for the cmdlet,
- https://docs.microsoft.com/powershell/module/dnsserver/add-dnsserverqueryresolutionpolicy

and found the following:
- The operator is either EQ or NE. You can specify no more than one of each operator in a criterion.
- The common operator format is UPPERCASE, e.g. `-FQDN "EQ,career.contoso.com"`

Based on these findings, I have adjusted the proposed addition above accordingly.

**Comment by raymondtant** [comment]
yes - you decoded my ramble very well.

I was blindly following the copy and paste cmdlets - this just bugged me
enough I followed through.

but hey  - thanks for the quick response!

Sincerely,
Ray

**Comment by illfated** [comment]
Thank you for the positive feedback. I will go ahead and create a Pull Request (PR) to suggest your improvement to the page. It should not take long, but we may have to be patient with when it gets approved and merged into the master branch.
