### ISSUE TITLE
Instructions provided ends with an error

### ISSUE THREAD

**Issue by jyavenard** [MicrosoftDocs/windowsserverdocs#4598]
[Enter feedback here]

You get the error:
Repair-AuthorizedKeyPermission : The term 'Repair-AuthorizedKeyPermission' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:30
+ $ConfirmPreference = 'None'; Repair-AuthorizedKeyPermission C:\Users\ ...
+                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Repair-AuthorizedKeyPermission:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH Server Configuration for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* GitHub Login: @maertendMSFT

**Comment by jyavenard** [comment]
This is likely related that the instructions to install OpenSSHUtils also failed

> Install-Module -Force OpenSSHUtils -Scope AllUsers
PackageManagement\Install-Package : No match was found for the specified search criteria and module name
'OpenSSHUtils'. Try Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex
   ception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by illfated** [comment]
https://github.com/MicrosoftDocs/windowsserverdocs/search?q=OpenSSHutils&unscoped_q=OpenSSHutils&type=Issues :
- [**Unable to configure OpenSSH for public key auth following docs**](https://github.com/MicrosoftDocs/windowsserverdocs/issues/4518) (#4518) (jaraco opened 8 days ago)
- [**OpenSSHUtils Not Needed**](https://github.com/MicrosoftDocs/windowsserverdocs/issues/4345) (#4345) (gynnantonix opened on 14 May)
- [**Outdated instructions?**](https://github.com/MicrosoftDocs/windowsserverdocs/issues/4023) (#4023) (RussKeldorph opened on 16 Mar)
- [**OpenSSH installation**](https://github.com/MicrosoftDocs/windowsserverdocs/issues/3970) (#3970) (DavidA2014 opened on 2 Mar)
- [**OpenSSHUtils is deprecated**](https://github.com/MicrosoftDocs/windowsserverdocs/issues/3806) (#3806) (FizzBuzz791 opened on 28 Jan)
- [**Misleading title/summary causing search confusion**](https://github.com/MicrosoftDocs/windowsserverdocs/issues/3456) (#3456) (ChrisDodd opened on 30 Oct 2019)
- [**Can't install the "OpenSSHUtils"**](https://github.com/MicrosoftDocs/windowsserverdocs/issues/3400) (#3400) (kljkyzsl opened on 14 Oct 2019)
- [**A better explanation can be found here**](https://github.com/MicrosoftDocs/windowsserverdocs/issues/2747) (#2747) (ElimAdmin opened on 23 Apr 2019)

**Comment by illfated** [comment]
You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by jyavenard** [comment]
The documentation is obsolete; from further search OpenSSHUtils was deprecated by Microsoft. And yet they still document that this is the way to go.

So if that's not a documentation error, what is ?

**Comment by illfated** [comment]
Thanks, that is obviously a suggestion to remove parts of the existing documentation. Sorry for being so general in my replies. I just did not have the capacity to evaluate the full scope of your issue.

Would you be able to suggest which parts to remove and which parts of the documentation to keep, maybe start working on a Pull Request to have these documents improved?

**Comment by konstruktoid** [comment]
Seems all documentation related to `OpenSSHUtils` needs to be updated, https://github.com/MicrosoftDocs/windowsserverdocs/issues/4345

**Comment by therealkenc** [comment]
I used the blog post [here](https://www.concurrency.com/blog/may-2019/key-based-authentication-for-openssh-on-windows) which worked for me. I couldn't find anything on the interwebs describing how to use Windows `ssh-agent` with a user in group Administrator. Absent a `Repair-AuthorizedKeyPermission`, any new documentation to cover the Admin case would need a lot of ink.

**Comment by illfated** [comment]
See Pull Request #4788 for a suggested improvement to this issue.
(The PR will close this issue ticket when it gets merged.)

**Comment by therealkenc** [comment]
The proposed changes will result in countless developers who have Admin accounts and are trying to ssh from their VM to windows to waste at least an hour (and perhaps more) of their lives (which they will never get back) finding out how to get their remote authorized_keys working.

All the PR does is remove the reference to now defunct OpenSSHUtils. The changes as proposed do not work for any user with Administrators group; which, to a first order, is most developers.

**Comment by illfated** [comment]
Thank you for your feedback. May I ask of you to edit the issue ticket title, to add "SSH: " in the title, something like this?

**OpenSSH Server Configuration: instructions provided ends with an error**

I believe this will make it more clear what this ticket is about, in the issue tickets list, so others may see what this ticket is about before opening it to read the details.

**Comment by illfated** [comment]
Also, feel free to comment in the linked PR to follow up on what you would prefer to see changed to make the end result more useful in the scenario you have described.

**Comment by illfated** [comment]
List of related issue tickets:

- #2747 **A better explanation can be found here** (Open)
- #3400 **Can't install the "OpenSSHUtils"** (Closed)
- #3456 **Misleading title/summary causing search confusion** (Open)
- #3806 **OpenSSHUtils is deprecated** (Open)
- #3970 **OpenSSH installation** (Closed)
- #4345 **OpenSSHUtils Not Needed** (Open)
- #4518 **Unable to configure OpenSSH for public key auth following docs** (Open)
- #4622 **Out-of-date - OpenSSHUtils no longer available.** (Open)
- #4634 **More documentation required** (Open)
- #4690 **OpenSSHUtils install reference no longer valid** (Open)
- #4702 **OpenSSHUtils got unlisted from the PowerShell gallery** (Open)
- #4743 **Nope. First example errors out.** (Open)
- #4770 **Error when following instructions to install OpenSSHUtils** (Open)
- #4787 **OpenSSHUtils module does not exist** (Open)
- #5000 **Clarification needed** (Open)
- #5138 **These instructions do not work on Windows 10 20h2** (Open)

**Comment by farcaller** [comment]
for anyone landing here after spending non trivial time trying to set up ssh pubkey auth to your win10 machine, as of early 2021 [this is still a functional fix](https://stackoverflow.com/questions/16212816/setting-up-openssh-for-windows-using-public-key-authentication/50502015#50502015): specifically you need to both update the `authorized_keys` permissions and clean up the sshd_config.

**Comment by G3NSVRV** [comment]
> for anyone landing here after spending non trivial time trying to set up ssh pubkey auth to your win10 machine, as of early 2021 [this is still a functional fix](https://stackoverflow.com/questions/16212816/setting-up-openssh-for-windows-using-public-key-authentication/50502015#50502015): specifically you need to both update the `authorized_keys` permissions and clean up the sshd_config.

Thanks m8, you saved me 30 minutes of hitting my head against the table

**Comment by dknappettmsft** [comment]
Thanks for submitting this issue. I have reworked this document to remove or replace parts that are no longer relevant or correct based on this and several other issues raised for this page.

The changes should be visible in around 6-12 hours.

#please-close

**Comment by therealkenc** [comment]
> I have reworked this document to remove or replace parts that are no longer relevant or correct based on this and several other issues raised for this page.

The proposed changes will result in countless developers who have Admin accounts and are trying to ssh from their VM to windows to waste at least an hour (and perhaps more) of their lives (which they will never get back) finding out how to get their remote authorized_keys working.

All the PR does is remove the reference to now defunct OpenSSHUtils. The changes as proposed do not work for any user with Administrators group; which, to a first order, is most developers.

**Comment by dknappettmsft** [comment]
There was a PR a few days earlier that didn't include the changes I was referring to, but the article has many more changes, including a section for administrative users. The commit is https://github.com/MicrosoftDocs/windowsserverdocs/commit/46199a470234d64dab8be910894c8442878306e1.

Thanks.
