### ISSUE TITLE
Static IP Injection - accurate?

### ISSUE THREAD

**Issue by sqlsolver** [MicrosoftDocs/windowsserverdocs#4600]
Can you be more specific about why 'static IP injection may not work' when using NetworkManager? I almost unrolled my whole NM installation on Ubuntu 20.04 and reverted to the previous stack because of this until I did some testing to discover that it is fine as long as the adapter MAC addresses match and you have added the static IP you want to the list of IPs on your NIC. If this is going to be flagged there should be context given as to how it causes a problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84d52296-198d-7c8a-db99-e8cb336e355f
* Version Independent ID: 77670399-109f-3233-0466-c13d84542039
* Content: [Supported Ubuntu virtual machines on Hyper-V](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-ubuntu-virtual-machines-on-hyper-v)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Supported-Ubuntu-virtual-machines-on-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/Supported-Ubuntu-virtual-machines-on-Hyper-V.md)
* Product: **windows-server**
* Technology: **compute-hyper-v**
* GitHub Login: @shirgall
* Microsoft Alias: **shirgall**

**Comment by Xelu86** [comment]
Hey sqlsolver,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made clarifying this to state:

> Static IP injection may not work if **NetworkManager** has been configured for a given Hyper-V-specific network adapter on the virtual machine as it can override static IP settings that have been manually configured. 

Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
