### ISSUE TITLE
Incorrect max value for parameter /l

### ISSUE THREAD

**Issue by Kamiclausy** [MicrosoftDocs/windowsserverdocs#4608]
[Enter feedback here]
Microsoft Docs states that that the ping /l <size> parameter has a maximum value of 65527. When trying this in Windows 10 Command Prompt, the actual maximum value is 65500:
"Bad value for option /l, valid range is from 0 to 65500."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecb04dc8-7ab3-71e9-9773-41c080b40109
* Version Independent ID: 435a4517-0c3f-6af6-d75d-faed7282c86a
* Content: [ping](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/ping)
* Content Source: [WindowsServerDocs/administration/windows-commands/ping.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/ping.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Confirmed, both on Windows 10 Version 2004 and on Windows Server 2016 Version 1607.

Verification images from Windows Server 2016:

![image](https://user-images.githubusercontent.com/38162891/86343487-5442da00-bc59-11ea-8ff7-b9cfcf29cf44.png)

![WinVerWS2016](https://user-images.githubusercontent.com/38162891/86344367-7d179f00-bc5a-11ea-994c-28312922ee29.png)

**Comment by dksimpson** [comment]
Hi @Kamiclausy,
Thanks for contacting Microsoft. We value your feedback. 
We've updated the ping /l max value in the article to reflect the correct value.
Thank you for your continued support.
#please-close
