### ISSUE TITLE
broken links in troubleshoot-windows-server-software-defined-networking-stack.md

### ISSUE THREAD

**Issue by xdrus** [MicrosoftDocs/windowsserverdocs#461]
Hello,

There are two links in [troubleshoot-windows-server-software-defined-networking-stack.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/sdn/troubleshoot/troubleshoot-windows-server-software-defined-networking-stack.md) to detailed description of "NetworkControllerDiagnostics" and "hnvdiagnostics" modules and both are broken:
* [Network Controller Diagnostics Cmdlet Topic](https://technet.microsoft.com/library/mt490456.aspx)
* [Hyper-V Network Virtualization (HNV) Diagnostics Cmdlet Topic](https://technet.microsoft.com/library/mt490472.aspx)

Best,
Ruslan.

**Comment by lizap** [comment]
Thanks, Ruslan!

@shortpatti - Hey, can you take a look at these broken links? Thanks!

**Comment by shortpatti** [comment]
Links are fixed.
