### ISSUE TITLE
Some input examples are always appreciated but rarely present in these docs.

### ISSUE THREAD

**Issue by ddineen** [MicrosoftDocs/windowsserverdocs#4619]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c3e19b-dd81-20a2-f797-9590d37cb84e
* Version Independent ID: f3d14a6d-f4fb-971f-c648-d69439e1b81e
* Content: [whoami](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/whoami)
* Content Source: [WindowsServerDocs/administration/windows-commands/whoami.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/whoami.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by craigcaseyMSFT** [comment]
Hello @ddineen,

Thanks for contacting Microsoft. We value your feedback.

Documentation changes have been made to clarify and acknowledge this issue. The doc changes will be live after the next business day.

Thank you again and have a most pleasant day.
#please-close

**Comment by ddineen** [comment]
Thank you!
