### ISSUE TITLE
In Address (IP or DNS), enter the NAS IP address or FQDN.

### ISSUE THREAD

**Issue by GammaProtocol** [MicrosoftDocs/windowsserverdocs#4626]
"In Address (IP or DNS), enter the RAS IP address or FQDN."?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52077540-dca2-7972-17ee-12659c4983a6
* Version Independent ID: 2da3938f-0fda-c05f-776a-97a39191ca88
* Content: [Install and Configure the NPS Server](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-nps)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-nps.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-nps.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by illfated** [comment]
Not sure what you are asking. Could you provide more details for your question, to explain what you want to know, or if this is about some kind of issue with the document page?

**Comment by GammaProtocol** [comment]
Apologies, I was thinking that NAS should have been RAS.  More than likely
just me not fully grasping aovpn still.

**Comment by illfated** [comment]
Thank you, I missed that detail in between the ticket title and the posted comment. Maybe you are correct, I don't know yet.

**Comment by IngridAtMicrosoft** [comment]
Addressed.
