### ISSUE TITLE
DTLS 1.1 (not a thing)

### ISSUE THREAD

**Issue by Conan1989** [MicrosoftDocs/windowsserverdocs#4627]
Hi,
under the DTLS 1.2 heading, it refers to "DTLS 1.1"
Reasonably sure DTLS 1.1 isn't a thing. Should be 1.0 1.2 or 1.3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd180142-4c19-8abc-ecce-e4c7e5ac8951
* Version Independent ID: fc5bba87-afad-1729-8f7e-333c73188b73
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server**
* Technology: **security-tls-ssl**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by RAJU2529** [comment]
@Conan1989 , I Also  DTLS 1.2 is correct.  But last screenshot is showing for DTLS 1.1

![DTLS1 2-](https://user-images.githubusercontent.com/3296790/87178429-c15e0b80-c2fa-11ea-992f-b94402bfc003.JPG)

**Comment by illfated** [comment]
(ref. #4632 and #4737 )

**Comment by illfated** [comment]
There you go. PR #4988 is available for viewing, comments and suggestions. Take care of yourself and those near you.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. A documentation change was made and changes are live. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
