### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Rvvhub** [MicrosoftDocs/windowsserverdocs#4629]
Last link on the page is broken.

Note all content on MSAs appears to have been removed...
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 344b210a-650f-4f12-dd1c-4a20f6cf46eb
* Version Independent ID: 176eade9-04bd-a656-fc2c-ba04c1c0aab2
* Content: [What's New for Managed Service Accounts](https://docs.microsoft.com/en-us/windows-server/security/group-managed-service-accounts/what-s-new-for-managed-service-accounts)
* Content Source: [WindowsServerDocs/security/group-managed-service-accounts/what-s-new-for-managed-service-accounts.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/group-managed-service-accounts/what-s-new-for-managed-service-accounts.md)
* Product: **windows-server**
* Technology: **security-gmsa**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by RAJU2529** [comment]
@coreyp-at-msft , Issue is conformed by me also, after the link.

So i will create PR now

**Comment by illfated** [comment]
#closed-by #4630

**Comment by dknappettmsft** [comment]
I've checked the links in the live page, and they all work as expected now.

#please-close
