### ISSUE TITLE
Merge conflict

### ISSUE THREAD

**Issue by andrevdl** [MicrosoftDocs/windowsserverdocs#463]
It's seems that this document has a merge conflict.
In the section "Related topics"

![image](https://user-images.githubusercontent.com/3393539/37407823-f31c0dfa-279a-11e8-91fa-4cbf6f4257a3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5be3773d-783c-115d-4945-9ec79b407877
* Version Independent ID: 3993b5ed-9b01-4759-6083-1586c8cf7fdd
* Content: [Virtual Private Networking (VPN) | Microsoft Docs](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/vpn-top#)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/vpn-top.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/vpn-top.md)
* Service: **unspecified**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
Resolved
