### ISSUE TITLE
VPN Server Group Membership

### ISSUE THREAD

**Issue by hexmike** [MicrosoftDocs/windowsserverdocs#464]
In the guide above it indicates that an AD group should be used to grant access to the certificate templates which issue certificates to the VPN servers. This would seem to suggest that the VPN servers should be Domain Joined - however I have always thought that machines in a DMZ should not be joined to the Domain. Is it no longer best practice for DMZ / Perimeter machines to be non domain joined?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e886cf2-b2cc-1942-2e93-b83ba3f5c81a
* Version Independent ID: 14185f76-c920-66a5-9d3b-51ddc4845ee8
* Content: [Configure the Always On VPN Server Infrastructure | Microsoft Docs](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure#create-the-vpn-users-vpn-servers-and-nps-servers-groups)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md)
* Service: **unspecified**
* GitHub Login: @jamesmci
* Microsoft Alias: **jamesmci**

**Comment by shortpatti** [comment]
It’s certainly recommended that VPN Servers which are placed in the DMZ/Perimeter are not domain joined. However some customers prefer to have the VPN Servers domain joined for better manageability (Group Policies, Backup/Monitoring agent, no local users to manage etc).  To do this, add an AD group to the VPN Server certificate template, which is only required when the VPN Servers are domain joined.

**Comment by shortpatti** [comment]
Closed

**Comment by mghrivera** [comment]
Having a trouble following this documentation on configuring the RAS server non-domain joined configuration. 
This article needs rework. To many information tips not documented correctly. 
ex. On the RRAS server, generate a file called VPNGateway.inf based upon the example certificate policy request provided in Appendix A (section 0) and customize the following entries.
Where is Appendix A (section 0)?

another one is:
You can find a copy of the VPNGateway.inf script in the VPN Offering IP Kit under the Certificate Request Policies folder. Only update the 'Subject' and '_continue_' with customer specific values.
Where is the VPN Offering IP Kit under the Certificate Request Policies folder?
