### ISSUE TITLE
Windows Time Service unavailable in Windows Server 2008 R2

### ISSUE THREAD

**Issue by patiljayesh040** [MicrosoftDocs/windowsserverdocs#4641]
Hello Team,

Please help me to restore Windows Time Service in Windows 2008 R2. We are facing an issue where Windows Time Service is not present. I have tried to look for it in services.msc also tried to look for the status via cmd (Attached the screenshot with error).
I have checked in registry and found few parts missing (Attached screenshots for the same for all directories in registry.

<img width="431" alt="WindowsTimeServices_Registry05" src="https://user-images.githubusercontent.com/68346067/87576565-3791b200-c6ef-11ea-93ee-bbdd42b11a61.png">
<img width="364" alt="WindowsTimeServices_Registry04" src="https://user-images.githubusercontent.com/68346067/87576575-39f40c00-c6ef-11ea-8760-6ce775542b61.png">
<img width="467" alt="WindowsTimeServices_Registry03" src="https://user-images.githubusercontent.com/68346067/87576578-3b253900-c6ef-11ea-800a-e640fbfd05ae.png">
<img width="408" alt="WindowsTimeServices_Registry02" src="https://user-images.githubusercontent.com/68346067/87576585-3c566600-c6ef-11ea-8e0b-3ff3f83311ac.png">
<img width="393" alt="WindowsTimeServices_Registry01" src="https://user-images.githubusercontent.com/68346067/87576588-3ceefc80-c6ef-11ea-8823-7f8838e1ecdd.png">
<img width="281" alt="WindowsTimeServices_Error" src="https://user-images.githubusercontent.com/68346067/87576592-3e202980-c6ef-11ea-9f06-a3dfe6658779.png">
<img width="467" alt="WindowsTimeServices_Registry03" src="https://user-images.githubusercontent.com/68346067/87576669-585a0780-c6ef-11ea-971e-1dfda18831ab.png">
<img width="408" alt="WindowsTimeServices_Registry02" src="https://user-images.githubusercontent.com/68346067/87576677-5abc6180-c6ef-11ea-95cf-018642d40a2f.png">
<img width="393" alt="WindowsTimeServices_Registry01" src="https://user-images.githubusercontent.com/68346067/87576685-5bed8e80-c6ef-11ea-9bb1-446cb5a355ff.png">
<img width="281" alt="WindowsTimeServices_Error" src="https://user-images.githubusercontent.com/68346067/87576687-5d1ebb80-c6ef-11ea-891f-4e45710967f2.png">
<img width="431" alt="WindowsTimeServices_Registry05" src="https://user-images.githubusercontent.com/68346067/87576694-5e4fe880-c6ef-11ea-80e1-d41c46383224.png">
<img width="364" alt="WindowsTimeServices_Registry04" src="https://user-images.githubusercontent.com/68346067/87576697-6019ac00-c6ef-11ea-9980-7da90590b062.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d09b16e-4bbb-91fa-3d84-e7623ec4dc07
* Version Independent ID: b6eadad5-0167-34b6-ed3a-16fa7ee83c60
* Content: [Windows Time service tools and settings](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings)
* Content Source: [WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by RAJU2529** [comment]
@patiljayesh040 . Check windows time Service executable file exists in System32 folder or not.

**Comment by patiljayesh040** [comment]
@RAJU2529 , Yes w32 executable does exist in system32 folder.

**Comment by patiljayesh040** [comment]
@RAJU2529 , Yee w32tm executable does exist in system32 folder*

**Comment by RAJU2529** [comment]
@patiljayesh040 . Then export that particular service registry settings from known good compuer and  then merge in your computer

**Comment by patiljayesh040** [comment]
@RAJU2529 , like export the w32time registry directory from regedit and import in the server with issue right ?

Also could you please help me with any documentation for the same ?

This is production server because. It would be great if you could help me with Microsoft Document. Thank You !

**Comment by illfated** [comment]
There is a documentation page, https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings , but this presumes that you already have got the service w32time running already. I presume you are looking for a way to add w32time / w32tm to your current configuration.

**Comment by illfated** [comment]
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/ff799054(v=ws.11)

Applies To: Windows Server 2003, Windows SBS 2003, Windows Vista, Windows XP, Windows Home Server 2011, Windows HPC Server 2008 R2, Windows Server 2008, Windows 7, Windows Server 2003 R2, Windows Server 2008 R2, Windows Essential Business Server, Windows Server 2008 Foundation, Windows SBS 2008, Windows Server 2008 R2 Foundation, Windows Home Server, Windows Server 2012, Windows HPC Server 2008, Windows 8

**Comment by illfated** [comment]
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/ff799054(v=ws.11)#examples

**Examples**
If you want to set the local Windows Time client to point to two different time servers, one named ntpserver.contoso.com and another named clock.adatum.com, type the following command at the command line, and then press ENTER:
```
w32tm /config /manualpeerlist:"ntpserver.contoso.com clock.adatum.com" /syncfromflags:manual /update
```
For a list of valid NTP servers that are available on the Internet for external time synchronization, see [article 262680](https://go.microsoft.com/fwlink/?linkid=60401) in the Microsoft Knowledge Base (https://go.microsoft.com/fwlink/?LinkID=60401).

**Comment by patiljayesh040** [comment]
No @illfated there is w32tm executable in system32 folder. I tried to run it but still Windows Time Service in services.msc is not present. I did checked the registry for the same. But the registry seems to be missing some for folders and values from the W32Time in registry. You can see the attached screenshots for the same.

**Comment by illfated** [comment]
OK, I see. So you basically need to save a w32time registry backup from a working 2008 Server with w32time running and run that .reg file on your production server.

**Comment by patiljayesh040** [comment]
Okay @illfated , Can you please help me with the Microsoft documentation if there is any ?  
Also the server is domain joined.

**Comment by illfated** [comment]
Looking around now, trying to find out where it says how to install Windows Time service, but I am also checking in on my workplace production server (2016) to see if that would be of any help.

**Comment by patiljayesh040** [comment]
Okay Thank You @illfated . I'll be waiting for your response. I have tried to run the w32tm executable but no luck. I have captured the video for the same and tried to do slomo. I'm attaching in here if it can help you to get about all the troubleshooting I have tried till now.

**Comment by patiljayesh040** [comment]
Okay Thank You @illfated . I'll be waiting for your response. I have tried to run the w32tm executable but no luck. I have captured a screenshot of the come pop-up which occurs after the executable was runned. Attached it to give you an gist about the troubleshooting done so far.
![Screenshot_2020-07-16-01-41-17-887_org videolan vlc](https://user-images.githubusercontent.com/68346067/87591328-c7425b00-c705-11ea-8c5b-021f6c7062ee.jpg)

**Comment by illfated** [comment]
2 things I have looked at so far:

1. Windows Server 2016 W32Time / NTP configuration in the Registry:

<details>

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time]
"Start"=dword:00000002
"DisplayName"="Windows Time"
"ErrorControl"=dword:00000001
"ImagePath"=hex(2):25,00,53,00,79,00,73,00,74,00,65,00,6d,00,52,00,6f,00,6f,00,\
  74,00,25,00,5c,00,73,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,00,5c,00,73,\
  00,76,00,63,00,68,00,6f,00,73,00,74,00,2e,00,65,00,78,00,65,00,20,00,2d,00,\
  6b,00,20,00,4c,00,6f,00,63,00,61,00,6c,00,53,00,65,00,72,00,76,00,69,00,63,\
  00,65,00,00,00
"Type"=dword:00000020
"Description"="@%SystemRoot%\\system32\\w32time.dll,-201"
"ObjectName"="NT AUTHORITY\\LocalService"
"ServiceSidType"=dword:00000001
"RequiredPrivileges"=hex(7):53,00,65,00,41,00,75,00,64,00,69,00,74,00,50,00,72,\
  00,69,00,76,00,69,00,6c,00,65,00,67,00,65,00,00,00,53,00,65,00,43,00,68,00,\
  61,00,6e,00,67,00,65,00,4e,00,6f,00,74,00,69,00,66,00,79,00,50,00,72,00,69,\
  00,76,00,69,00,6c,00,65,00,67,00,65,00,00,00,53,00,65,00,43,00,72,00,65,00,\
  61,00,74,00,65,00,47,00,6c,00,6f,00,62,00,61,00,6c,00,50,00,72,00,69,00,76,\
  00,69,00,6c,00,65,00,67,00,65,00,00,00,53,00,65,00,53,00,79,00,73,00,74,00,\
  65,00,6d,00,54,00,69,00,6d,00,65,00,50,00,72,00,69,00,76,00,69,00,6c,00,65,\
  00,67,00,65,00,00,00,00,00
"FailureActions"=hex:80,51,01,00,00,00,00,00,00,00,00,00,03,00,00,00,14,00,00,\
  00,01,00,00,00,60,ea,00,00,01,00,00,00,c0,d4,01,00,00,00,00,00,00,00,00,00
"DelayedAutostart"=dword:00000001

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\Config]
"AnnounceFlags"=dword:0000000a
"EventLogFlags"=dword:00000002
"FrequencyCorrectRate"=dword:00000004
"HoldPeriod"=dword:00000005
"LargePhaseOffset"=dword:02faf080
"LastKnownGoodTime"=hex(b):0e,20,d5,fa,c4,d3,d5,01
"LocalClockDispersion"=dword:0000000a
"MaxAllowedPhaseOffset"=dword:00000001
"MaxNegPhaseCorrection"=dword:0000d2f0
"MaxPollInterval"=dword:0000000a
"MaxPosPhaseCorrection"=dword:0000d2f0
"MinPollInterval"=dword:00000006
"PhaseCorrectRate"=dword:00000001
"PollAdjustFactor"=dword:00000005
"SpikeWatchPeriod"=dword:00000384
"TimeJumpAuditOffset"=dword:00007080
"UpdateInterval"=dword:00000064
"UtilizeSslTimeData"=dword:00000001
"LastClockRate"=dword:0002625b

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\Parameters]
"NtpServer"="ntp.online.no,0x9"
"ServiceDll"=hex(2):25,00,73,00,79,00,73,00,74,00,65,00,6d,00,72,00,6f,00,6f,\
  00,74,00,25,00,5c,00,73,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,00,5c,00,\
  77,00,33,00,32,00,74,00,69,00,6d,00,65,00,2e,00,64,00,6c,00,6c,00,00,00
"ServiceDllUnloadOnStop"=dword:00000001
"ServiceMain"="SvchostEntry_W32Time"
"Type"="NTP"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\SecureTimeLimits]
"SecureTimeEstimated"=hex(b):a4,69,87,c0,e3,5a,d6,01
"SecureTimeHigh"=hex(b):a4,d1,4b,22,ec,5a,d6,01
"SecureTimeLow"=hex(b):a4,01,c3,5e,db,5a,d6,01

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\SecureTimeLimits\RunTime]
"SecureTimeTickCount"=hex(b):8a,f2,63,a4,00,00,00,00
"SecureTimeConfidence"=dword:00000008

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\Security]
"Security"=hex:01,00,04,80,98,00,00,00,a4,00,00,00,00,00,00,00,14,00,00,00,02,\
  00,84,00,06,00,00,00,00,00,14,00,fd,01,02,00,01,01,00,00,00,00,00,05,12,00,\
  00,00,00,00,18,00,ff,01,0f,00,01,02,00,00,00,00,00,05,20,00,00,00,20,02,00,\
  00,00,00,14,00,8d,01,02,00,01,01,00,00,00,00,00,05,04,00,00,00,00,00,14,00,\
  8d,01,02,00,01,01,00,00,00,00,00,05,06,00,00,00,00,00,14,00,9d,01,02,00,01,\
  01,00,00,00,00,00,05,13,00,00,00,00,00,14,00,a9,00,02,00,01,01,00,00,00,00,\
  00,05,13,00,00,00,01,01,00,00,00,00,00,05,12,00,00,00,01,01,00,00,00,00,00,\
  05,12,00,00,00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\TimeProviders]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\TimeProviders\NtpClient]
"AllowNonstandardModeCombinations"=dword:00000001
"CompatibilityFlags"=dword:80000000
"CrossSiteSyncFlags"=dword:00000002
"DllName"=hex(2):25,00,73,00,79,00,73,00,74,00,65,00,6d,00,72,00,6f,00,6f,00,\
  74,00,25,00,5c,00,73,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,00,5c,00,77,\
  00,33,00,32,00,74,00,69,00,6d,00,65,00,2e,00,64,00,6c,00,6c,00,00,00
"Enabled"=dword:00000001
"EventLogFlags"=dword:00000001
"InputProvider"=dword:00000001
"LargeSampleSkew"=dword:00000003
"ResolvePeerBackoffMaxTimes"=dword:00000007
"ResolvePeerBackoffMinutes"=dword:0000000f
"SignatureAuthAllowed"=dword:00000001
"SpecialPollInterval"=dword:00015180
"SpecialPollTimeRemaining"=hex(7):6e,00,74,00,70,00,2e,00,6f,00,6e,00,6c,00,69,\
  00,6e,00,65,00,2e,00,6e,00,6f,00,2c,00,37,00,65,00,31,00,65,00,32,00,65,00,\
  38,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,\
  00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\TimeProviders\NtpServer]
"AllowNonstandardModeCombinations"=dword:00000001
"ChainDisable"=dword:00000000
"ChainEntryTimeout"=dword:00000010
"ChainLoggingRate"=dword:0000001e
"ChainMaxEntries"=dword:00000080
"ChainMaxHostEntries"=dword:00000004
"DllName"=hex(2):25,00,73,00,79,00,73,00,74,00,65,00,6d,00,72,00,6f,00,6f,00,\
  74,00,25,00,5c,00,73,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,00,5c,00,77,\
  00,33,00,32,00,74,00,69,00,6d,00,65,00,2e,00,64,00,6c,00,6c,00,00,00
"Enabled"=dword:00000000
"EventLogFlags"=dword:00000000
"InputProvider"=dword:00000000
"RequireSecureTimeSyncRequests"=dword:00000000

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\TimeProviders\VMICTimeProvider]
"DllName"=hex(2):25,00,53,00,79,00,73,00,74,00,65,00,6d,00,52,00,6f,00,6f,00,\
  74,00,25,00,5c,00,53,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,00,5c,00,76,\
  00,6d,00,69,00,63,00,74,00,69,00,6d,00,65,00,70,00,72,00,6f,00,76,00,69,00,\
  64,00,65,00,72,00,2e,00,64,00,6c,00,6c,00,00,00
"Enabled"=dword:00000001
"InputProvider"=dword:00000001

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\TimeProviders\VMICTimeProvider\Parameters]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\TriggerInfo]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\TriggerInfo\0]
"Type"=dword:00000003
"Action"=dword:00000001
"GUID"=hex:ba,0a,e2,1c,51,98,21,44,94,30,1d,de,b7,66,e8,09

```
</details>

2. social.technet.microsoft.com posting of how to start non-running w32time service:
https://social.technet.microsoft.com/Forums/office/en-US/8df6cfee-8cd3-4440-ad67-bc732d4f74fc/w32time-service-missing?forum=winservergen

**Comment by illfated** [comment]
Please note: Windows Server 2016 introduced 2 new things not present in earlier versions of Windows Server:
1. High security access control to the time service and its sources
2. High precision (accuracy down to less than milliseconds)

I do not know enough about the registry content to know exactly which parts are the new ones and which ones are the original core components.

**Comment by illfated** [comment]
https://blogs.msmvps.com/mweber/2010/06/27/time-configuration-in-a-windows-domain/

**Comment by illfated** [comment]
https://community.spiceworks.com/topic/2180667-windows-time-service-missing

**Comment by illfated** [comment]
You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by RAJU2529** [comment]
@patiljayesh040 . You need same server v Registry settings

**Comment by illfated** [comment]
> Okay Thank You @illfated . I'll be waiting for your response. I have tried to run the w32tm executable but no luck. I have captured a screenshot of the come pop-up which occurs after the executable was run.
>

Please note carefully: w32tm.exe is **not** a GUI program. You need to open a **CMD**.exe window **as an Administrator** and run the command from there.

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
