### ISSUE TITLE
Update attrib commands to include +p, -p, +u

### ISSUE THREAD

**Issue by hdonaldMSFT** [MicrosoftDocs/windowsserverdocs#4642]
Can we please add the attrib commands: +p, -p, +u?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62650d46-4208-8880-2c41-1d7220bfdd89
* Version Independent ID: 9577a78a-7c08-0e57-d507-a7e96a335660
* Content: [attrib](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/attrib)
* Content Source: [WindowsServerDocs/administration/windows-commands/attrib.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/attrib.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Xelu86** [comment]
Hey hdonaldMSFT,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation update has been made adding the missing parameters for `attrib` and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
