### ISSUE TITLE
Instructions for AOVPN include depricated call in the powershell

### ISSUE THREAD

**Issue by obprg** [MicrosoftDocs/windowsserverdocs#4643]
The instructions in the documentation specifies using Gwmi which is not available in pwsh 7.  It has been changed to Get-CimInstance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e14da1-102d-3ddf-e2a1-a20ce533b95a
* Version Independent ID: 374edc4c-f527-b7b7-c291-353928b97d8d
* Content: [Configure Windows 10 Client Always On VPN Connections](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by anaharris-ms** [comment]
#please-close Fixed in: https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/3398
