### ISSUE TITLE
Incorrect key?

### ISSUE THREAD

**Issue by PaulBol** [MicrosoftDocs/windowsserverdocs#4644]
This part doesn't seem to be correct:

> Navigate to the following registry subkey: HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\PortNumber

I think one needs to open the key *HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp* and then edit the *value PortNumber*.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13054e70-b770-f803-4596-6d0ab3fe865c
* Version Independent ID: 3e474a79-1129-fdf6-bbd4-a12e0e7ebe27
* Content: [Change the listening port in Remote Desktop](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/change-listening-port)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/change-listening-port.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/change-listening-port.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by RAJU2529** [comment]
@PaulBol .  Below steps are fine according to you?

Navigate to the following registry subkey: HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
Find  PortNumber
Edit > Modify and then click Decimal
Type the new port number, and then click OK.
Close the registry editor, and restart your computer.

**Comment by illfated** [comment]
(Ref. #4646 )

**Comment by PaulBol** [comment]
Sorry, only saw your comment now. The change makes sense to me.
