### ISSUE TITLE
Content mistype and missing content?

### ISSUE THREAD

**Issue by dimagohere** [MicrosoftDocs/windowsserverdocs#4649]
Hello there!!

Reading this page I noticed there is a mistype here: "When issuing a token from WS-Federaion relying parties that token request comes across with URL query string parameters." The Federation word is missing the "t".

I'm in my mobile using Safari to read but looks like when you got in the end of the current content is seems missing information or links? It says about a troubleshooter tool but stops right there without more details. It could be because I'm in my mobile but other pages worked just fine.

Well that's all! I hope someone can check this and thanks for all good documentation you guys have been providing, very helpful!

Diego

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 643b3e65-fdac-926d-a62a-0ede3c06f4d0
* Version Independent ID: ac4d10da-4fd3-4a6b-a95e-fccd4a5eb07e
* Content: [AD FS Troubleshooting - Claims Issuance](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-claims-issuance)
* Content Source: [WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-claims-issuance.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-claims-issuance.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by RAJU2529** [comment]
@billmath , i also  checked  this article , i conformed  four topics without links

**Comment by illfated** [comment]
Well, the main issue is that this page is unfinished and it seems to have been like this since its creation, 2018-04-13.

It is completely without content underneath 3 of the paragraphs, as well as containing unfinished text content for the **Token Request** paragraph.

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
