### ISSUE TITLE
Article is largely incorrect

### ISSUE THREAD

**Issue by revjonnyflash** [MicrosoftDocs/windowsserverdocs#465]
I was plagued with issues during setup. Even after 2 weeks with support there was no progress being made. I ended up finding a 3rd party guide and found that much of this article is out of order and inaccurate. The biggest example I have is that it first has you create app registrations and then the native app and two app proxies. The way it is actually done is you create the app proxies, then you open those proxies in app registration and set the URIs to the addresses in the app registration steps. These steps result in 5 total app or registrations where there should only be 3. 

This article resulted in about 3 weeks of  frustration only to find the official documentation was wrong and missing massive important steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21d1d072-911f-92c0-248a-9e44efbff42d
* Version Independent ID: 0fdb921d-d97d-5b12-ae28-286216e130df
* Content: [Deploy Windows Server Hybrid Cloud Print | Microsoft Docs](https://docs.microsoft.com/en-us/windows-server/administration/hybrid-cloud-print/hybrid-cloud-print-deploy)
* Content Source: [WindowsServerDocs/administration/hybrid-cloud-print/hybrid-cloud-print-deploy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/hybrid-cloud-print/hybrid-cloud-print-deploy.md)
* Service: **unspecified**
* GitHub Login: @msjimwu
* Microsoft Alias: **coreyp**

**Comment by lizap** [comment]
Thanks for this feedback. You're absolutely correct that this article needs update. I'm sorry about the time lost because of that. We will fix it.

**Comment by andrieskuipers** [comment]
I'm struggling to get this working too. Is there any timeframe known in which we can expect working documentation?

**Comment by NiklasJern** [comment]
@jleger88: Can you please share the 3rd party guide you mentioned?

**Comment by lizap** [comment]
We published an update to this article, so I'm going to close the issue for now. Please feel free to re-open if necessary. Thanks!

**Comment by pyoungberg** [comment]
This article has been pretty painful to read through. Should I be using three app registrations or five? The guide as written has me setup 5, and I'm still unsure what the value for https://<services-machine-endpoint>/RedirectUrl is supposed to be. Would recommend rewriting to remove any steps where the word 'repeat steps' are used, and being detailed as possible assuming the user knows nothing. Maybe creating a table at the beginning a user can fill in for variables. The article is also vague when referring to the Mopria Cloud Service. Is it a Discovery Service or no?

**Comment by pyoungberg** [comment]
Had to copy the sqlite3.exe to the directory referenced in step 2.7. Just kind of guessed the instructions there.

**Comment by pyoungberg** [comment]
Step 4 CloudPrinterDiscoveryEndPoint doen't even make sense. External URL of the Mopria Discovery Service Azure Application Proxy created in Step 3.3 (must be exactly the same but without the trailing /) refers to a step where you setup an SPN, not an App Proxy App.

**Comment by pyoungberg** [comment]
Maybe instead of telling users to 'use any name' when creating an App Registration / Proxy you could provide an example name for clarity? The instructions make it very easy to confuse these 5 when you refer to them all as "Mopria Discovery Service Azure Application Proxy"

**Comment by pyoungberg** [comment]
Stepp 2.8.D contains random slashes where they shouldn't be 
ms-appx-web://Microsoft.AAD.BrokerPlugin/\<NativeClientAppID\>
Should be:
ms-appx-web://Microsoft.AAD.BrokerPlugin/<NativeClientAppID>
