### ISSUE TITLE
Cannot found option "Use all monitors" in "Windows Store Client"

### ISSUE THREAD

**Issue by PlusoneWang** [MicrosoftDocs/windowsserverdocs#4652]
As described on the page:
>#### How do I use all of my monitors?
>To use two or more screens, do the following:
>1. Right-click the remote desktop that you want to enable multiple screens for, and then click Edit.
>2. Enable Use all monitors and Full screen.

The above step not working on "Windows Store Client". Nothing happens when I right-click on the remote desktop.
And I cannot found the option "Use all monitors" in this application.
How could I enable multiple monitors support in "Windows Store Client"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e3bc1ca-2fde-4a75-3583-fdb8ff2bf962
* Version Independent ID: 5cef2f0a-bed1-f05f-0f74-ba6f2808a714
* Content: [Remote Desktop clients FAQ](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-client-faq#monitors-audio-and-mouse)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
Addressed in comments.
