### ISSUE TITLE
Backtick character is incorrectly show as single-quote (which breaks the examples, as they are not the same character)

### ISSUE THREAD

**Issue by m0mk** [MicrosoftDocs/windowsserverdocs#4655]
The example with the backtick at the end of the page actually uses a single quote ('), instead of a real backtick (`), which end up being very confusing for people reading the page and trying to follow that example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 362d60c8-8d69-6016-10bd-0f81114ec228
* Version Independent ID: 76d9a719-f621-f716-4987-68acb1501c63
* Content: [for](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/for)
* Content Source: [WindowsServerDocs/administration/windows-commands/for.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/for.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Are you referring to the last example line, as copied here?

```
for /f usebackq delims== %i in ('set') do @echo %i
```
By the way, I have not tested this myself, but are you using CMD or PowerShell to test this?
I can't remember seeing back ticks used much in old-school CMD scripts or batch files.

**Comment by Xelu86** [comment]
Hey m0mk,

Thanks for contacting Microsoft. We value your feedback.

This was corrected with changes being live and this thread was not closed. We're now closing this thread.

Thank you and have a most pleasant day.
#please-close
