### ISSUE TITLE
Needs to include information for Windows Server 2012 R2

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/windowsserverdocs#4660]
[Enter feedback here]

This page needs instructions about how to manually install disk cleanup for Windows Server 2012 R2 without installing Desktop Experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7226c88e-03b8-b123-e257-171dd4cb03ba
* Version Independent ID: 973ec668-3612-887a-a254-67e34bf70f04
* Content: [Using Disk Cleanup on Windows Server](https://docs.microsoft.com/en-us/windows-server/storage/file-server/disk-cleanup)
* Content Source: [WindowsServerDocs/storage/file-server/disk-cleanup.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/disk-cleanup.md)
* Product: **windows-server**
* Technology: **storage-spaces**
* GitHub Login: @iangpgh
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Looks like that is present to me in the last section of the page:
- https://docs.microsoft.com/en-us/windows-server/storage/file-server/disk-cleanup#manually-add-disk-cleanup-to-an-earlier-version-of-windows-server

***

## Manually add Disk Cleanup to an earlier version of Windows Server

The Disk Cleanup tool (cleanmgr.exe) isn't present on Windows Server 2012 R2 or earlier unless you have the Desktop Experience feature installed.

To use cleanmgr.exe, install the Desktop Experience as described earlier, or copy two files that are already present on the server, cleanmgr.exe and cleanmgr.exe.mui. Use the following table to locate the files for your operating system.

| Operating System  | Architecture  | File Location  |
| ----------------- | -------------- | --------------- |
| Windows Server 2008 R2 | 64-bit | C:\Windows\winsxs\amd64_microsoft-windows-cleanmgr_31bf3856ad364e35_6.1.7600.16385_none_c9392808773cd7da\cleanmgr.exe 
| Windows Server 2008 R2 | 64-bit | C:\Windows\winsxs\amd64_microsoft-windows-cleanmgr.resources_31bf3856ad364e35_6.1.7600.16385_en-us_b9cb6194b257cc63\cleanmgr.exe.mui |

Locate cleanmgr.exe and move the file to **%systemroot%\System32**.

Locate cleanmgr.exe.mui and move the files to **%systemroot%\System32\en-US**.

You can now launch the Disk cleanup tool by running Cleanmgr.exe from Command Prompt, or by clicking **Start** and typing **Cleanmgr** into the search bar.

To have Disk Cleanup button appear on a disk's Properties dialog, you will also need to install the Desktop Experience feature.

## Additional references

[Free up drive space in Windows 10](https://support.microsoft.com/help/12425/windows-10-free-up-drive-space)

[cleanmgr](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/cleanmgr.md)

**Comment by rossmpersonal** [comment]
I completely disagree. The table at the bottom of the page lists what files need to copied for Windows Server 2008 R2 but does not list what files need to be copied for Windows Server 2012 R2. Rows in that table need to be added for Windows Server 2012 R2. Please let me know if you have further questions.

**Comment by illfated** [comment]
OK, so you are looking for something like https://serverfault.com/questions/580751/cleanmgr-can-nolonger-be-installed-on-server-2012-r2

Which sections from that page would you recommend adding to this page?

Would you also recommend sectioning out parts of the existing section as a "2008 only" section to avoid confusion?

**Comment by rossmpersonal** [comment]
If the only way to install Disk Cleanup in Server 2012 R2 is to install Desktop Experience, that should be documented and the section "Manually add Disk Cleanup to an earlier version of Windows Server" should be updated to clarify that it does not apply to Server 2012 R2. If it is possible to install cleanmgr in Server 2012 R2 without installing Desktop Experience, such as copying files, that should be documented.

**Comment by illfated** [comment]
Thank you very much. That is fair and square. From what I could deduce after reading the related pages, Desktop Experience needs to be installed, either on the target server or on a "throwaway" server to be able to get a working, functional 64-bit copy of the 2 required files.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

I will start authoring a Pull Request for this page, to make it distinguish this fact a lot better, maybe as soon as the coming weekend.

**Comment by iangpgh** [comment]
I no longer work on this team (v-iap)

**Comment by Xelu86** [comment]
Hey rossmpersonal,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made clarifying:

- For versions of Windows Server prior to 2016, the Desktop Experience feature is required to use cleanmgr.exe
- Cleanmgr.exe can be manually installed for WS2008 R2

Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
