### ISSUE TITLE
missing reference

### ISSUE THREAD

**Issue by dhummel77** [MicrosoftDocs/windowsserverdocs#4662]
The referenceto the b log post "to scale out or not to scale out" does not take you to that blog post.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07d7bf3d-4ab7-3f11-acb2-840d86090042
* Version Independent ID: ba1dc68b-297a-3c2f-2e99-4f42367e89f7
* Content: [Scale-Out File Server for application data overview](https://docs.microsoft.com/en-us/windows-server/failover-clustering/sofs-overview)
* Content Source: [WindowsServerDocs/failover-clustering/sofs-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/sofs-overview.md)
* Product: **windows-server**
* Technology: **storage-failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Yes, even though this broken URL does not trigger a 404 error, it is only able to take you to

- https://techcommunity.microsoft.com/t5/storage-at-microsoft/bg-p/FileCAB

in the new site home for TechNet:

- https://techcommunity.microsoft.com/

There is a search function on the page, in the top right corner, which enables us to search for page titles quite easily. (I don't know what is wrong with my Microsoft Edge chromium browser, but I have to activate the search box several times to be able to paste and edit the search text properly, but anyway) Here is the final result:

- https://techcommunity.microsoft.com/t5/storage-at-microsoft/to-scale-out-or-not-to-scale-out-that-is-the-question/ba-p/425080

**Comment by illfated** [comment]
Feel free to create a Pull Request to have this URL updated to the correct working page.

**Comment by dhummel77** [comment]
If I knew the correct and working page I wouldn’t have pointed out it was missing.  I was hoping to be directed t the correct and working page.

 

Thank you

 

David Hummel

561-635-6999

**Comment by dhummel77** [comment]
Please disregard my previous message.  I read you responses out of order and did not see you had pointed me to the right place.  Thank you.

 

David Hummel

561-635-6999

**Comment by illfated** [comment]
Fair enough, it happens to the best of us some times.

Are you familiar with GitHub, enough to create a Pull Request for the correction of this link?

**Comment by dhummel77** [comment]
No definitely not.  But it is something I should become familiar with so I will give it a look see.  GitHub seems to be the way of things now.

 

Thank you,

 

David Hummel

561-635-6999

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @dhummel77,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting the blog post hyperlink and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
