### ISSUE TITLE
Step 2 under "To enable and view the trace log" is wrong

### ISSUE THREAD

**Issue by ThomasRapidis** [MicrosoftDocs/windowsserverdocs#4665]
Just try it...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 073ab477-ac4c-9951-9d50-9d979176cff1
* Version Independent ID: 384cd6f7-2249-3f33-9b9e-1c6abeae69cb
* Content: [AD FS Troubleshooting - Auditing Events and Logging](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-logging)
* Content Source: [WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-logging.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-logging.md)
* Product: **windows-server**
* Technology: **identity-adfs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @ThomasRapidis,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made to better reflect the steps for the mentioned section and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
