### ISSUE TITLE
Several parts of GPO linking needs correction and updating

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/windowsserverdocs#4667]
In the [Move Tier 1 Objects to the Appropriate OUs](https://docs.microsoft.com/en-us/windows-server/identity/securing-privileged-access/privileged-access-workstations#move-tier-1-objects-to-the-appropriate-ous) section, under step 5., b., ii., there are several issues.

- GPO names need to be updated.  The SCM is no longer used.  All GPO names are named MSFT Windows 10 1909 and Server 1909, etc.
- There are User GPOs linked to the Devices OUs for each tier.  The User OUs should be linked to the Accounts OU instead.
- Earlier on in the article, it mentioned linking the RestrictedAdmin Required - Computer GPO to the Tier 0 devices OU has no added security benefit so why link it there now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1338ba44-301c-db33-d336-80dd50a77960
* Version Independent ID: 55abfb6d-3f63-9dce-1b70-36c6265fc37b
* Content: [Why Privileged Access Workstations can help secure your organization](https://docs.microsoft.com/en-us/windows-server/identity/securing-privileged-access/privileged-access-workstations#move-tier-1-objects-to-the-appropriate-ous)
* Content Source: [WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md)
* Product: **windows-server**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by illfated** [comment]
Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub. I am merely an external contributor familiar with the use of git, GitHub functionality and English grammar, in addition to general IT tech support on a small business level.

I am not entirely familiar with this topic, but I would like to offer my assistance in creating a Pull Request to have the content updated and corrected. During the last 15 minutes, I have found that this table is referenced in your first bullet point in your list of what needs to be reviewed:

***

 **Policies:**

|||
|-|-|
|CM Windows 10 - Domain Security|N/A - Do Not Link Now|
|SCM Windows 10 TH2 - Computer|Admin\Tier 0\Devices|
||Admin\Tier 1\Devices|
||Admin\Tier 2\Devices|
|SCM Windows 10 TH2- BitLocker|Admin\Tier 0\Devices|
||Admin\Tier 1\Devices|
||Admin\Tier 2\Devices|
|SCM Windows 10 - Credential Guard|Admin\Tier 0\Devices|
||Admin\Tier 1\Devices|
||Admin\Tier 2\Devices|
|SCM Internet Explorer - Computer|Admin\Tier 0\Devices|
||Admin\Tier 1\Devices|
||Admin\Tier 2\Devices|
|PAW Configuration - Computer|Admin\Tier 0\Devices (Existing)|
||Admin\Tier 1\Devices (New Link)|
||Admin\Tier 2\Devices (New Link)|
|RestrictedAdmin Required - Computer|Admin\Tier 0\Devices|
||Admin\Tier 1\Devices|
||Admin\Tier 2\Devices|
|SCM Windows 10 - User|Admin\Tier 0\Devices|
||Admin\Tier 1\Devices|
||Admin\Tier 2\Devices|
|SCM Internet Explorer - User|Admin\Tier 0\Devices|
||Admin\Tier 1\Devices|
||Admin\Tier 2\Devices|
|PAW Configuration - User|Admin\Tier 0\Devices (Existing)|
||Admin\Tier 1\Devices (New Link)|
||Admin\Tier 2\Devices (New Link)|

> [!NOTE]
> The "SCM Windows 10 - Domain Security" GPO may be linked to the domain independently of PAW, but will affect the entire domain.

***

I also notice that the first table entry "CM Windows 10 - Domain Security" contains a typo, missing an S (confirmed in the Note blob below the table), but that is a moot point if all the SCM entries need to be changed.

I was just about to ask if it would be enough to replace "SCM" with MSFT in that table, but now I think the entries need to be identified as Version specific entries as well as replacing the initials SCM.

Could you offer some insight into how you visualize the changes for this section?

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
