### ISSUE TITLE
Typo in Platform Support

### ISSUE THREAD

**Issue by tvilo** [MicrosoftDocs/windowsserverdocs#4672]
Platform support | AAlways On VPN supports domain-joined, nondomain-joined (workgroup), or Azure AD–joined devices to allow for both enterprises and bring your own device (BYOD) scenarios. Also, Always On VPN is available in all Windows editions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8009edd9-f014-f54d-b473-d3c7319c5bf0
* Version Independent ID: 6786c3dc-85ee-c283-fcdf-e1b6bfe0af79
* Content: [Always On VPN enhancements](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/always-on-vpn-enhancements)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/always-on-vpn-enhancements.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/always-on-vpn-enhancements.md)
* Product: **windows-server**
* Technology: **networking-ras**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by tvilo** [comment]
Fixed the typo

**Comment by illfated** [comment]
(ref. PR #4673 -- typo correction)
