### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by andrewatfornax** [MicrosoftDocs/windowsserverdocs#468]
In the text "For a detailed list of Active Directory concepts, see Understanding Active Directory.", the Understanding Active Directory link is broken, and goes to a retired content download page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94251036-29c8-87b0-eb8f-2516600d4aac
* Version Independent ID: f5309f09-ad43-619b-c23c-269f37177d2c
* Content: [Active Directory Domain Services Overview | Microsoft Docs](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/get-started/virtual-dc/active-directory-domain-services-overview)
* Content Source: [WindowsServerDocs/identity/ad-ds/get-started/virtual-dc/Active-Directory-Domain-Services-Overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/get-started/virtual-dc/Active-Directory-Domain-Services-Overview.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by lizap** [comment]
Hi, Andrew - can you try the link again? Between when you opened this issue and now we've published the article in question to docs.microsoft.com. The link's working for me, but can you confirm it is for you as well? If it is, I'll close the issue. Thanks!

**Comment by andrewatfornax** [comment]
Confirmed as fixed, thanks.
