### ISSUE TITLE
Syntax of -backupTarget example incorrect.

### ISSUE THREAD

**Issue by DJ-1701** [MicrosoftDocs/windowsserverdocs#4682]
On testing, the syntax for the argument -backupTarget should be `-backupTarget:f:\` and not `-backupTarget:f` as displayed in the example.

Using just the letter returns:
ERROR - The specified backup location could not be found or is not a supported backup storage location.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d61fe7f-1576-54f9-cfd8-2c065cf4353a
* Version Independent ID: 879f4d16-4fab-7cb6-c84d-53ac717c7e1e
* Content: [wbadmin delete systemstatebackup](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/wbadmin-delete-systemstatebackup)
* Content Source: [WindowsServerDocs/administration/windows-commands/wbadmin-delete-systemstatebackup.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/wbadmin-delete-systemstatebackup.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
At first, I thought this was an issue with missing escape character for the backslash, but those are obviously code blocks, so that is a pure typo. Should be pretty easy to fix.

**Comment by DJ-1701** [comment]
Yes it should, just a matter of adding a colon and a backslash and that save the documentation... might even get away with just a colon and saving. Just an easy fix to the documentation to save error and confusion. :)

**Comment by illfated** [comment]
Thanks for the reminder. I made a "quick-and-lazy" PR to correct the typo issue, as well as removing some whitespace redundancy. PR #4707 is ready for review.
