### ISSUE TITLE
Example is wrong

### ISSUE THREAD

**Issue by calvinhsia** [MicrosoftDocs/windowsserverdocs#4683]
[Enter feedback here]
the example is wrong. It should be "lodctr /s:backup1.txt"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4b3ac89-b24b-e0c9-3c32-6f341e99d256
* Version Independent ID: 5fbaecde-5418-5179-9690-17f87843a131
* Content: [lodctr](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/lodctr)
* Content Source: [WindowsServerDocs/administration/windows-commands/lodctr.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/lodctr.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
The issue dates back to when the surrounding quotation marks were incorrectly removed in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/ad297d36711efc8984d6e6daac7b62fb71d49ab9 :
- https://github.com/MicrosoftDocs/windowsserverdocs/commit/ad297d36711efc8984d6e6daac7b62fb71d49ab9#diff-78c54f3e5f9c4c5aaf24987650ee0134L42

I believe we should revert that change to get the documented quotation marks back:

#### Remarks

- If the information that you supply contains spaces, use quotation marks around the text (for example, "file name 1").

### Examples

```diff
- To save the current performance registry settings and explanatory text to file *perf backup1.txt*, type:
+ To save the current performance registry settings and explanatory text to file *"perf backup1.txt"*, type:

- lodctr /s:perf backup1.txt
+ lodctr /s:"perf backup1.txt"
```

If that change is not acceptable, we should split the difference and make the Remarks section suggest that a gap should always be replaced by a dash or underscore character, as well as adding said character to the file name to get rid of the space in the filename.

**Comment by calvinhsia** [comment]
yes, using quotes will be fine.

**Comment by illfated** [comment]
There you go. PR #4684 is ready for review.

**Comment by illfated** [comment]
#sign-off
