### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by VorbeckGV** [MicrosoftDocs/windowsserverdocs#4685]
In the sentence "Windows has two command shells: The Command shell and PowerShell.", the link for PowerShell is broken.
Thank you!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d382ca0-6538-5e1d-3e83-e31c9ab6a911
* Version Independent ID: 11eff296-6158-f89a-4941-8735529183e9
* Content: [Windows commands](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands)
* Content Source: [WindowsServerDocs/administration/windows-commands/windows-commands.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/windows-commands.md)
* Product: **windows-server**
* Technology: **manage-windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
OK, I think I see what is going on. The 404 URL is this one:
- https://docs.microsoft.com/en-us/powershell/scripting/powershell-scripting

What it should look like instead:
- https://docs.microsoft.com/en-us/powershell/scripting/overview

I removed the `?view=powershell-6` and `?view=powershell-7` parts of the URL because it might be dynamic, depending on the OS & browser of the visiting user, just like I will remove the /en-us/ part for localization purposes.

**Comment by illfated** [comment]
BTW, I presume the 404 error may have been caused by changes in the PowerShell pages hierarchy, while not noticing other pages linking to the original (now removed) pages.

**Comment by illfated** [comment]
Also: There are more than one outdated link in this page, so my changes might take a little while to complete, before I can post my PR to suggest a solution to this issue.

**Comment by illfated** [comment]
There is also the unspoken question whether the link should point to
* the index page https://docs.microsoft.com/powershell/ 

instead of my first suggestion,
* https://docs.microsoft.com/powershell/scripting/overview

**Comment by illfated** [comment]
Never mind, the second PowerShell URL is not broken or causing any 404 error, so I will make only 1 change to speed up the review & merge process. I will add my question about what counts as the actual PowerShell index page for the link, in my PR, in case the MS Docs reviewer wants to consider that question.

**Comment by illfated** [comment]
There you go. PR #4687 is ready for review & merge.
