### ISSUE TITLE
"Configure DNS and Firewall Settings for Always On VPN" URL doesn't work

### ISSUE THREAD

**Issue by lukenie** [MicrosoftDocs/windowsserverdocs#469]
"Configure DNS and Firewall Settings for Always On VPN" URL doesn't work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ae99a07-be14-63a1-d5bb-1e92f9cde0b7
* Version Independent ID: ed219e40-9a0e-794b-110d-d82418d456e7
* Content: [Remote Access Always On VPN Deployment | Microsoft Docs](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-deployment#configure-dns-and-firewall-settings-for-always-on-vpnvpn-deploy-dns-firewallmd)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-deployment.md)
* Service: **unspecified**
* GitHub Login: @jamesmci
* Microsoft Alias: **jamesmci**

**Comment by lizap** [comment]
Hi - can you check the link again? When I click on the heading you mention, I get to this page: https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-dns-firewall

**Comment by lukenie** [comment]
Yes, it's working now.

Thank you.

From Android

________________________________
