### ISSUE TITLE
OpenSSHUtils install reference no longer valid

### ISSUE THREAD

**Issue by wrjohnson** [MicrosoftDocs/windowsserverdocs#4690]
[Enter feedback here]
The required command...
   - Install-Module -Force OpenasSSHUtils -Scope AllUsers

...fails reporting:
   - PackageManagmenet\Install-Package : No match was found for the specified search criteria and module name

Please provide a link for resolving this common error and/or superseding documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH key management for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* GitHub Login: @maertendMSFT

**Comment by illfated** [comment]
For reference; See also the list of following related issues:

- **Can't install the "OpenSSHUtils"** (#3400)
kljkyzsl opened on 14 October 2019, 7 comments

- **OpenSSHUtils is deprecated** (#3806)
FizzBuzz791 opened on 28 January, 1 comment

- **Instructions provided ends with an error** (#4598)
jyavenard opened on 28 June, 5 comments

- **More documentation required** (#4634)
garylawuk opened on 11 July 2020

- **Outdated instructions?** (#4023)
RussKeldorph opened on 16 March 2020, 6 comments

- **OpenSSH installation** (#3970)
DavidA2014 opened on 2 March 2020, 4 comments

- **Misleading title/summary causing search confusion** (#3456)
ChrisDodd opened on 30 October 2019, 7 comments

- **Unable to configure OpenSSH for public key auth following docs** (#4518)
jaraco opened on 20 June1 2020

- **A better explanation can be found here** (#2747)
ElimAdmin opened on 23 Apr 2019, 2 comments

**Comment by illfated** [comment]
See Pull Request #4788 for a suggested improvement to this issue.
(The PR will close this issue ticket when it gets merged.)

**Comment by illfated** [comment]
List of related issue tickets:

- #2747 **A better explanation can be found here** (Open)
- #3400 **Can't install the "OpenSSHUtils"** (Closed)
- #3456 **Misleading title/summary causing search confusion** (Open)
- #3806 **OpenSSHUtils is deprecated** (Open)
- #3970 **OpenSSH installation** (Closed)
- #4345 **OpenSSHUtils Not Needed** (Open)
- #4518 **Unable to configure OpenSSH for public key auth following docs** (Open)
- #4598 **Instructions provided ends with an error** (Open)
- #4622 **Out-of-date - OpenSSHUtils no longer available.** (Open)
- #4634 **More documentation required** (Open)
- #4702 **OpenSSHUtils got unlisted from the PowerShell gallery** (Open)
- #4743 **Nope. First example errors out.** (Open)
- #4770 **Error when following instructions to install OpenSSHUtils** (Open)
- #4787 **OpenSSHUtils module does not exist** (Open)
- #5000 **Clarification needed** (Open)
- #5138 **These instructions do not work on Windows 10 20h2** (Open)

**Comment by dknappettmsft** [comment]
Thanks for submitting this issue. I have reworked this document to remove or replace parts that are no longer relevant or correct based on this and several other issues raised for this page.

The changes should be visible in around 6-12 hours.

#please-close
