### ISSUE TITLE
Active Directory on Windows Server 2019 Core

### ISSUE THREAD

**Issue by pisees** [MicrosoftDocs/windowsserverdocs#4691]
Can you install Active Directory Domain Services on Windows Server 2019 Core? I don't see in the list of Roles/Features on my VM but not sure if was removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 216d2c6e-b4ea-c927-0c99-bf35366529f0
* Version Independent ID: 9fa31ffc-3465-a8f6-7426-7c4d76f3cc85
* Content: [What is Server Core?](https://docs.microsoft.com/en-us/windows-server/administration/server-core/what-is-server-core)
* Content Source: [WindowsServerDocs/administration/server-core/what-is-server-core.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/server-core/what-is-server-core.md)
* Product: **windows-server**
* GitHub Login: @lizap

**Comment by illfated** [comment]
You need to install the role manually, it is in the list of roles not installed by default:
- https://docs.microsoft.com/en-us/windows-server/administration/server-core/server-core-roles-and-services#roles-included-in-server-core
(notice in particular the last column on the right hand side, "**Installed by default?**")

**Comment by dksimpson** [comment]
Hello @pisees,

As correctly noted by ghost, the Active Directory Domain Services role is not installed by default, but can be installed manually. Here's the list of roles available to install in the Windows Server Core: https://learn.microsoft.com/windows-server/administration/server-core/server-core-roles-and-services#roles-included-in-server-core. 

If you need more information, you can also try engaging with one or more of these forums:
  - From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback).
 - Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
 - Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

Thanks for contacting Microsoft; we value your feedback. It appears that this issue has been addressed. 
If you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.

#please-close
