### ISSUE TITLE
issue in command

### ISSUE THREAD

**Issue by Egyptionl** [MicrosoftDocs/windowsserverdocs#470]
i have did all that and my printer driver fine and print test page good. it's USB printer>and printer say currently being printed > and do nothing when run from cmd

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab4325a5-e272-9360-32ca-acd01a75a883
* Version Independent ID: a839fd55-3997-e5e7-b43f-c30cbec39c94
* Content: [print | Microsoft Docs](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/print#BKMK_examples)
* Content Source: [WindowsServerDocs/administration/windows-commands/print.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/print.md)
* Service: **unspecified**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by coreyp-at-msft** [comment]
Hi @Egyptionl ,

The **Print** command does not work with USB printers. The printer must be connected through a serial or parallel port.

Thanks,
Corey
