### ISSUE TITLE
Where is ssh.exe?

### ISSUE THREAD

**Issue by Daniel15** [MicrosoftDocs/windowsserverdocs#4700]
After installing the OpenSSH Client, where is the .exe file located?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Installation of OpenSSH For Windows Server](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* GitHub Login: @maertendMSFT

**Comment by RAJU2529** [comment]
@Daniel15. SSH  means    Secure SHell  . in windows 10 v2004, location of  ssh.exe  is  **C:\Windows\System32\OpenSSH\**


![ssh](https://user-images.githubusercontent.com/3296790/89443847-7f47ae80-d76e-11ea-9104-214dec86d2ed.JPG)

**Comment by Daniel15** [comment]
Thanks!
