### ISSUE TITLE
Typo in example code for creating subnets

### ISSUE THREAD

**Issue by vstepic** [MicrosoftDocs/windowsserverdocs#4701]
Hi,

There is a typo in example code for creating subnets:

Add-DnsServerClientSubnet -Name "AmericaSubnet" -IPv4Subnet "192.0.0.0/24, 182.0.0.0/24"  
  
Add-DnsServerClientSubnet -Name "EuropeSubnet" -IPv4Subnet "141.1.0.0/24, 151.1.0.0/24"

it should be 

Add-DnsServerClientSubnet -Name "AmericaSubnet" -IPv4Subnet "192.0.0.0/24" , "182.0.0.0/24"  
  
Add-DnsServerClientSubnet -Name "EuropeSubnet" -IPv4Subnet "141.1.0.0/24", "151.1.0.0/24"

BR,
VS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df0c3c0b-d980-b4fb-b12a-72827f2410e2
* Version Independent ID: cd10eb85-9e2b-e937-45f3-8e5c1e2bcef7
* Content: [Use DNS Policy for Intelligent DNS Responses Based on the Time of Day](https://docs.microsoft.com/en-us/windows-server/networking/dns/deploy/dns-tod-intelligent)
* Content Source: [WindowsServerDocs/networking/dns/deploy/dns-tod-intelligent.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/dns/deploy/dns-tod-intelligent.md)
* Product: **windows-server**
* Technology: **networking-dns**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
@vstepic : Thank you for creating a ticket to report your findings. What is the result if you try to use the existing format command?

I thought that the existing `IPv4Subnet` values are supposed to be added on 2 separate lines, or at least added in succession, due to the existing comma between the IP ranges.

Unfortunately, I don't have a test environment to check if I can reproduce your issue, only a production environment which would not support this kind of change.

**Comment by vstepic** [comment]
Hi,

The error message that is generated when running the example code
Add-DnsServerClientSubnet
-Name "AmericaSubnet" -IPv4Subnet "192.0.0.0/24, 182.0.0.0/24" is

Add-DnsServerClientSubnet : The client subnet information provided is not
in CIDR notation.

Which is expected, because the parameter ipv4subnet is expecting string[]
as input. When the command is run with ipv4subnet formated as string
array  "192.0.0.0/24" , "182.0.0.0/24", the command is running as expected,
and both subnets are added.

BR,

Vladimir Stepic
MCT,MCSE,MCSA,MCITP,MCTS

http://vstepic.net

[image: Follow me on twitter] <https://twitter.com/vstepic>
<https://mk.linkedin.com/in/vstepic/>

**Comment by illfated** [comment]
There you go. PR #4712 is ready for review.
