### ISSUE TITLE
What eventlog?

### ISSUE THREAD

**Issue by MeanDoubleStain** [MicrosoftDocs/windowsserverdocs#4705]
[Enter feedback here]
What eventlog are you referencing here? Where is EventID 1135 logged?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2144e7f4-708a-c9c9-04e9-48631a8448d3
* Version Independent ID: 7acefe4f-73d9-95d1-d2ed-67b96d509355
* Content: [Troubleshooting cluster issue with Event ID 1135](https://docs.microsoft.com/en-us/windows-server/troubleshoot/troubleshooting-cluster-event-id-1135)
* Content Source: [WindowsServerDocs/troubleshoot/troubleshooting-cluster-event-id-1135.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/troubleshoot/troubleshooting-cluster-event-id-1135.md)
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by exchange12rocks** [comment]
Most likely it will be in the "System" event log.

**Comment by illfated** [comment]
Good point. Also indicated in https://docs.microsoft.com/en-us/windows-server/troubleshoot/troubleshooting-cluster-event-id-1135#several-scenarios-of-event-id-1135

## Several scenarios of Event ID 1135

We want you to take a closer look on at the **System Event logs** on all the nodes of your cluster. Review the Event ID 1135 that you are seeing on the nodes and copy all the instances of this event. This will make it convenient for you to look at them and review.

```console
Event ID 1135
Cluster node ' **NODE A** ' was removed from the active failover cluster membership.
The Cluster service on this node may have stopped.
This could also be due to the node having lost communication with other active nodes in the failover cluster.
Run the Validate a Configuration wizard to check your network configuration.
If the condition persists, check for hardware or software errors related to the network adapters on this node.
Also check for failures in any other network components to which the node is connected such as hubs, switches, or bridges.
```

**Comment by illfated** [comment]
#please-close
