### ISSUE TITLE
Cloud Share Witness configuration fails if you have existing witness configured

### ISSUE THREAD

**Issue by kalalvishal** [MicrosoftDocs/windowsserverdocs#4706]
If you have already configured a witness (FileShare or any other) and if you like to change the Witness to Cloud Share Witness, its failing with error "Please check your storage account name, endpoint, and access key and HTTPS connection". To resolve this, simply remove existing witness and then try to add the Cloud share witness. More Information:  https://social.technet.microsoft.com/Forums/en-US/72eca634-5d45-4eef-8bff-de6bf84f828a/cannot-create-cloud-witness-quorum-disk-in-azure-file-storage?forum=windowsazuredata

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e6da99e-a148-b5ea-224d-8a4c48604945
* Version Independent ID: a6a90a1f-870c-3501-ce6e-fbf52f802dfb
* Content: [Deploy a cloud witness for a Failover Cluster](https://docs.microsoft.com/en-us/windows-server/failover-clustering/deploy-cloud-witness)
* Content Source: [WindowsServerDocs/failover-clustering/deploy-cloud-witness.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/deploy-cloud-witness.md)
* Product: **windows-server**
* Technology: **storage-failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by robinharwood** [comment]
We hugely appreciate your contribution, feedback, and support to our technical documentation.

We’ve phased out GitHub Issues on this repository as the feedback mechanism for content and have replaced it with a new feedback system. For more information see, [Content User Feedback](https://aka.ms/ContentUserFeedback). As part of this rollout, we are migrating your issue where our team will use your comments to improve the documentation experience. Unfortunately, this does mean you won't be able to access this issue after the migration is complete.

All issues will be migrated by Thursday 29th August 2024.

Once again, thank you for your valuable feedback, we hope you’ll continue to contribute using our new feedback system.
