### ISSUE TITLE
Any additional network configuration required for this?

### ISSUE THREAD

**Issue by stoff75** [MicrosoftDocs/windowsserverdocs#471]
We have a ADFS2016 farm which is used by 4 different domains (DomA, DomB, DomC and DomD). Whenever I enable "extranet lockout" it works fine for DomA, DomB and DomC but not dor DomD, those users can't be authenticated.
We have upgraded fo ADFS2016 ("farm behavior level 3") because we thought the requirement for PDC was the issue but it is still not working. Is there some additional firewall requirement that is needed for this to work? We can authenticate fine to the PDC's in DomD and everything works normally, but when we enable extranetlockout the authentication fails but only for DomD. The only thing we have been able to find when comparing this with the other 3 domains that this works for is that we cannot access the AD Web Services (TCP port 9389?) in DomD's domain controllers but I can't see any note that this feature would require additional ports?
Regards // Kristoffer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25643e14-4b84-c492-a60b-eacef63a491d
* Version Independent ID: 93348a46-9024-6798-8356-be09f482e0b1
* Content: [Configure AD FS Extranet Lockout Protection | Microsoft Docs](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-extranet-lockout-protection#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Lockout-Protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Lockout-Protection.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Page has moved since this ticket was created, likely due to a site section overhaul. May as well close this ticket due to missing reference.

**Comment by illfated** [comment]
#please-close
