### ISSUE TITLE
Possible outdated content

### ISSUE THREAD

**Issue by jks05c** [MicrosoftDocs/windowsserverdocs#4713]
Hello, customer noticed that this referenced procs as well as the use of the deprecated AzureRm module and was wondering if this content is still accurate? They were using the Azure Hybrid Benefit WS SA Count Tool as well. Hoping to verify whether or not that still works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90e335dd-0bc5-a7e3-650b-e3dd1823176b
* Version Independent ID: 18f34ef3-ff61-0473-a64b-ac5a64dbe1d7
* Content: [Azure Hybrid Benefit for Windows Server](https://docs.microsoft.com/en-us/windows-server/get-started/azure-hybrid-benefit#how-to-maintain-compliance)
* Content Source: [WindowsServerDocs/get-started/azure-hybrid-benefit.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/azure-hybrid-benefit.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @eross-msft
* Microsoft Alias: **chrisrin**

**Comment by illfated** [comment]
( also ref. issue ticket #488 from the same page )

**Comment by dknappettmsft** [comment]
Thanks for the feedback. The article no longer references processors or the AzureRm PowerShell module.  The changes should be visible later today.

#please-close
