### ISSUE TITLE
Operating Systems Applied To Confusion

### ISSUE THREAD

**Issue by matziq** [MicrosoftDocs/windowsserverdocs#4716]
The article says at the top:
Applies To: Windows Server 2016, Windows Server 2012 R2, Windows Server 2012, Windows 10, Windows 8.1, Windows 7

No mention of Server 2008.

However, in the body of the article it says:
Recommended Audit Policies by Operating System
This section contains tables that list the audit setting recommendations that apply to the following operating systems:
Windows Server 2016
Windows Server 2012
Windows Server 2012 R2
**Windows Server 2008**
Windows 10
Windows 8.1
Windows 7

Does the article apply to Windows Server 2008? Also, where is 2008 R2?
Thanks!
John

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ba42209-cc0a-d257-5566-a101d91b89ea
* Version Independent ID: 7973c0ca-3afd-619f-a08e-43873f2e8dbf
* Content: [Audit Policy Recommendations](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/audit-policy-recommendations)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Audit-Policy-Recommendations.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Audit-Policy-Recommendations.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
Yes same recommendations for 2008R2

**Comment by MicrosoftGuyJFlo** [comment]
#please-close

**Comment by illfated** [comment]
Conclusion: The entirety of the article applies to supported versions of Windows client and server OS versions.

The individual audit setting recommendation tables also apply to the unsupported OS version 2008, but only for reference and because the settings are the same.

**Comment by illfated** [comment]
#please-close
