### ISSUE TITLE
Update "Generate a certificate for Azure MFA on each AD FS server" section

### ISSUE THREAD

**Issue by osbistonium** [MicrosoftDocs/windowsserverdocs#4717]
I just tried to generate a certificate using the "New-AdfsAzureMfaTenantCertificate" and specifying TenantId as my tenant domain, similar to specified in this documentation, but that did not work, I had to use the full TenantId instead, which can be found looking up the ObjectId of your VerifiedDomain using "Get-AzureADTenantDetail".

I suggest updating the documentation to reflect this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f333e8cb-c046-ee06-d33d-d7dc8e8af695
* Version Independent ID: 10838695-f60e-42a7-b0e8-eed7820fd333
* Content: [Configure AD FS 2016 and Azure MFA](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
