### ISSUE TITLE
Is max volume size (still) correct?

### ISSUE THREAD

**Issue by pkar70** [MicrosoftDocs/windowsserverdocs#4718]
[Enter feedback here]
As https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-fsa/4e3695bd-7574-4f24-a223-b4679c065b63?redirectedfrom=MSDN#Appendix_A_1 says in note 1, NTFS max cluster size is 2 MB on Windows 10 v1709 operating system and Windows Server 2019 and later. As NTFS has max cluster number 2^32, then max volume size should be about 8 PB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ede5970f-3974-f410-2d00-d99ae6177e9e
* Version Independent ID: 835f76fc-f470-d52e-50e8-880f7986a65c
* Content: [NTFS overview](https://docs.microsoft.com/en-us/windows-server/storage/file-server/ntfs-overview)
* Content Source: [WindowsServerDocs/storage/file-server/ntfs-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/ntfs-overview.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @pkar70,

Thanks again for contacting Microsoft. We value your feedback. 

It appears that the [max volume size table](https://learn.microsoft.com/en-us/windows-server/storage/file-server/ntfs-overview#support-for-large-volumes) in this documentation was updated to reflect the latest changes and this thread was not closed:

Cluster size | Largest volume and file
-- | --
4 KB (default size) | 16 TB
8 KB | 32 TB
16 KB | 64 TB
32 KB | 128 TB
64 KB (earlier max) | 256 TB
128 KB | 512 TB
256 KB | 1 PB
512 KB | 2 PB
1024 KB | 4 PB
2048 KB (max size) | 8 PB

We will now be closing this thread. Thank you and have a most pleasant day. #please-close
