### ISSUE TITLE
What is expected "CurrentFamBehavior" after upgrade?

### ISSUE THREAD

**Issue by stoff75** [MicrosoftDocs/windowsserverdocs#472]
This document was clearly written for the pre-release version of the upgrade. But now that it is release, could you please update the screenshot at the end that is the final confirmation that the upgrade went through, the one with "CurrentFarmBehavior"? For us it's 3 which jives with every other blog out there that that is indeed correct for ADFS2016, but it does create confusion as this document says "Threshold" and the version of ADFS in Windows 2012 R2 is referred to as _version_ 3!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebfd725f-1b77-751c-1948-f8f88d26a9bc
* Version Independent ID: 7d9c78d9-7736-8f0a-9636-269125a10d6f
* Content: [Upgrading to AD FS in Windows Server 2016 | Microsoft Docs](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by thibaultchatiron** [comment]
Before upgrade the Farm Behavior Level, the "CurrentFarmBehavior" is equal to 1, then after the upgrade, the version is 3

**Comment by bencorley** [comment]
Wait, Version 3 for 2016, version 4 for 2019, why isn't this specified ?
