### ISSUE TITLE
Examples on page for Shutdown options do not show required quotes on comment parameter /c 

### ISSUE THREAD

**Issue by RodneySandwith** [MicrosoftDocs/windowsserverdocs#4725]
shutdown /r /m \\servername /t 60 /c Reconfiguring myapp.exe /f /d p:4:1
should be
shutdown /r /m \\servername /t 60 /c "Reconfiguring myapp.exe" /f /d p:4:1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2770335e-d15c-6389-36b9-d687b7794b92
* Version Independent ID: 319c885a-1c12-595f-8018-c563945afe93
* Content: [shutdown](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/shutdown)
* Content Source: [WindowsServerDocs/administration/windows-commands/shutdown.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/shutdown.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Thank you for reporting the issue with missing required quotes on comment parameter /c .
The solution provided in Pull Request #4789 should close this ticket when merged.
