### ISSUE TITLE
How can admins enable TLS 1.2 on a per- RPT basis? I have some SP's that are not supporting TLS 1.2 and others that require it

### ISSUE THREAD

**Issue by kevin-tunge-spok** [MicrosoftDocs/windowsserverdocs#4728]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f505619-9097-e736-4c6a-8ec57c631f7d
* Version Independent ID: 12dc28e7-d8bf-4cca-95e5-0547b4f46b08
* Content: [Managing SSL/TLS Protocols and Cipher Suites for AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/manage-ssl-protocols-in-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Manage-SSL-Protocols-in-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Manage-SSL-Protocols-in-AD-FS.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Sorry for taking so long to respond to your ticket and question. I notice that you asked the same question in comment https://github.com/MicrosoftDocs/windowsserverdocs/issues/4500#issuecomment-675507400 and have received a reply from @exchange12rocks . 

Do you consider your question to be answered, or do you find a need for the page to be updated/improved in any way?

**Comment by billmath** [comment]
No reply.

#please-close
