### ISSUE TITLE
ssh-agent service not installed upon installation of OpenSSH Server or Client

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [MicrosoftDocs/windowsserverdocs#4729]
After installing the optional features noted in [Installation of OpenSSH For Windows Server 2019 and Windows 10](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse), the command `Start-Service ssh-agent` errors with:
```
Start-Service : Cannot find any service with service name 'ssh-agent'.
```

Running `Get-Service ssh-agent` produces the same error.

Are there extra steps needed to add the service? If so, these should be added to docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH key management for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT

**Comment by illfated** [comment]
Install OpenSSH as described here:
- https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse

Check also if you need any of the information on the following page:
- https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_server_configuration

Those are prerequisites for managing OpenSSH on your Windows computer.

**Comment by illfated** [comment]
You may need to reboot your computer after some (or all) of the install procedures have finished, before you can manage the software as described.

Please also browse through the following list of related issue tickets for previously posted questions & answers:
- https://github.com/MicrosoftDocs/windowsserverdocs/search?q=ssh-agent&state=open&type=Issues
