### ISSUE TITLE
Invalid DTLS 1.1 references

### ISSUE THREAD

**Issue by ixtlanian** [MicrosoftDocs/windowsserverdocs#4731]
DTLS 1.2 version section (https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings#dtls-12) contains references to DTLS 1.1 in the example - both text and the screenshot show DTLS 1.1

There is no such thing as DTLS 1.1.
Please correct the example text and the screenshot to show DTLS 1.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd180142-4c19-8abc-ecce-e4c7e5ac8951
* Version Independent ID: fc5bba87-afad-1729-8f7e-333c73188b73
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by RAJU2529** [comment]
@ixtlanian , thanks for reporting, i create PR to change the screenshot.
![dls1 2](https://user-images.githubusercontent.com/3296790/90767572-108c5880-e30b-11ea-84bc-55d522e0da7d.JPG)
![dls1 2](https://user-images.githubusercontent.com/3296790/90767581-14b87600-e30b-11ea-87ed-1f2d41968c0e.PNG)

**Comment by ixtlanian** [comment]
Please also do not forget to change the sentence above the screenshot in the article - it also references 1.1

**Comment by illfated** [comment]
(ref. #4632 and #4737 )

**Comment by illfated** [comment]
There you go. PR #4988 is available for viewing, comments and suggestions. Take care of yourself and those near you.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. A documentation change was made and changes are live. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
