### ISSUE TITLE
Missing double quotes

### ISSUE THREAD

**Issue by arturohernandez10** [MicrosoftDocs/windowsserverdocs#4733]
λ dir c:\ /s /b | find CPU
FIND: Parameter format not correct

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53026067-c2f4-c930-ecf8-f483a0aecf54
* Version Independent ID: 4fff263a-28b2-7896-0712-0ef70a713629
* Content: [find](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/find)
* Content Source: [WindowsServerDocs/administration/windows-commands/find.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/find.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Looks like the description for `<string>` is way too vague to make all readers understand that the quotation marks are _required_ and not just suggested.

Also, as you have pointed out, all and any of the strings in the examples should be enclosed in proper quotation marks ` " " ` for the **find** command to work as intended.

From the Help text in Windows 10 (Home x64) Version 2004 (OS Build 19041.388) :
```
C:\>find /?
Searches for a text string in a file or files.

FIND [/V] [/C] [/N] [/I] [/OFF[LINE]] "string" [[drive:][path]filename[ ...]]

  /V         Displays all lines NOT containing the specified string.
  /C         Displays only the count of lines containing the string.
  /N         Displays line numbers with the displayed lines.
  /I         Ignores the case of characters when searching for the string.
  /OFF[LINE] Do not skip files with offline attribute set.
  "string"   Specifies the text string to find.
  [drive:][path]filename
             Specifies a file or files to search.

If a path is not specified, FIND searches the text typed at the prompt
or piped from another command.

C:\>_
```

**Comment by illfated** [comment]
I will get back to this issue in a day or two. Have to get some sleep now.

**Comment by dknappettmsft** [comment]
Fixed the example for CPU to include the quotation marks.

#please-close

**Comment by illfated** [comment]
Thank you very much. Sorry for forgetting about this in August 2020.
