### ISSUE TITLE
Is this nested virtualization?

### ISSUE THREAD

**Issue by LijuV-MSFT** [MicrosoftDocs/windowsserverdocs#4740]
A secure variant of the administrative VM model is to use **_shielded virtual machines to host one or more admin VMs_** alongside a user VM. Does it mean:
- Hyper-V (guarded) hosts running shielded VMs. These shielded VMs are used as PAWs.
  OR
- Hyper-V (guarded) hosts running shielded VMs. These shielded VMs in turn host an admin VM and a user VM. (so nested virtualization?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1338ba44-301c-db33-d336-80dd50a77960
* Version Independent ID: 55abfb6d-3f63-9dce-1b70-36c6265fc37b
* Content: [Why Privileged Access Workstations can help secure your organization](https://docs.microsoft.com/en-us/windows-server/identity/securing-privileged-access/privileged-access-workstations)
* Content Source: [WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
Content updates in progress #please-close
