### ISSUE TITLE
Cannot Deny Log on Locally to Administrators

### ISSUE THREAD

**Issue by LijuV-MSFT** [MicrosoftDocs/windowsserverdocs#4741]
Attempting to assign the Deny log on locally right to Administrators throws the error "You cannot deny all users or administrator(s) from logging on locally"

![image](https://user-images.githubusercontent.com/47825646/90920975-3bcc8180-e3b7-11ea-9504-cbe40e623669.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1338ba44-301c-db33-d336-80dd50a77960
* Version Independent ID: 55abfb6d-3f63-9dce-1b70-36c6265fc37b
* Content: [Why Privileged Access Workstations can help secure your organization](https://docs.microsoft.com/en-us/windows-server/identity/securing-privileged-access/privileged-access-workstations)
* Content Source: [WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
