### ISSUE TITLE
Not able to install RDS CALs Per User License in Azure Windows 2019 VM

### ISSUE THREAD

**Issue by AgassiJoeLVedala89** [MicrosoftDocs/windowsserverdocs#4742]
[Enter feedback here]

I am stuck with installing RDS CALs per user license. I am in a windows server 2019 VM and allowed 3 users to login and access the concurrently, this is happening but when I am trying to activate the server and install the license it is not happening. I also made this VM as a DC but still getting the same error. I am following all the steps which is Microsoft documentation but why I am still not able to achieve this? am I wrong or the documentation is missing steps? Please I need help I have to deliver this to the customer. Please provide me a solution. 
![ss](https://user-images.githubusercontent.com/32320522/90958998-508f3f00-e4b5-11ea-80d3-ae766990f267.png) 

![error](https://user-images.githubusercontent.com/32320522/90958995-4cfbb800-e4b5-11ea-8216-8589e508782e.png)
![RDP not configured](https://user-images.githubusercontent.com/32320522/90958996-4e2ce500-e4b5-11ea-8efb-87180013bc91.png)
![rds error](https://user-images.githubusercontent.com/32320522/90958997-4ff6a880-e4b5-11ea-88ff-66e8ac002fbe.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a02d662-56db-4efc-52d4-61689541f632
* Version Independent ID: f8692043-d888-09d3-1bf3-bff51ae20e34
* Content: [Install RDS client access licenses](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-install-cals)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-install-cals.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-install-cals.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
Hello @AgassiJoeLVedala89. GitHub issues for this repo are for reporting problems with our documentation.  Please open a support ticket or post your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html).
