### ISSUE TITLE
Wrong Link?

### ISSUE THREAD

**Issue by Theragus** [MicrosoftDocs/windowsserverdocs#4749]
[Enter feedback here]

Azure Extended Network Link shows the same site again.
Should it follow to this site?: https://docs.microsoft.com/de-de/azure/virtual-network/subnet-extension

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c8fa86e-65b1-d8d1-c1e6-d7ba721d7f75
* Version Independent ID: 714b296f-07d4-3e09-3928-483e9069d180
* Content: [Connecting Windows Server to Azure hybrid services](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/azure/)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/azure/index.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/azure/index.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Thank you for pointing out that link URL issue. Curiously enough, the link URL occurs 3 times on the same page as well.

It feels a bit like reading the phrase "Recursive -- see **Recursive**."

The current URL in all 3 places is this one: https://go.microsoft.com/fwlink/?linkid=2109517&clcid=0x409

**Comment by illfated** [comment]
But yes, I think you are pretty close to right answer, or at least as correct as we can be, given that we don't know the author's exact intentions.

To me, it could be to skip directly to the section https://docs.microsoft.com/azure/virtual-network/subnet-extension#extend-your-subnet-to-azure
Although I suppose we need to use the overarching page URL as the suggested correction.

Anyway, a Pull Request to suggest this correction will be available shortly.

**Comment by illfated** [comment]
Just to see if I was able to find something useful or interesting in the page history, I visited the web archives (WayBack Machine), but the only single history entry was from November 9, 2019:
- https://web.archive.org/web/20191109121926/https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/azure/

That page only refers to using **Azure Network Adapter**, which I suppose is an outdated solution. The link also leads to a TechNet blog, which is a repost of a 2018 blog post.

**Comment by illfated** [comment]
Oh my. I just checked to see if it is possible to use some of the local relative links to keep the document browsable in the GitHub version of the page as well. It seems to be adapted to the docs.microsoft.com directory structure, not the github.com directory structure -- `*sigh*` -- that is a rabbit-hole I am not prepared to deal with at the moment. I will post my PR with the suggestion to use the full URL (although language agnostic), but I won't try to adapt it to using https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/virtual-network/subnet-extension.md unless recommended by the team members.

**Comment by illfated** [comment]
There you go. PR #4752 is available for review.

**Comment by illfated** [comment]
(ref. #3958 )
