### ISSUE TITLE
Specify Scope

### ISSUE THREAD

**Issue by mytee306** [MicrosoftDocs/windowsserverdocs#475]
How do I specify whether I want the changes to apply to the user or group?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce055b59-7d93-7c0c-6373-109b53f31119
* Version Independent ID: fc5ac67c-1db4-bfca-a71a-bb1f2c4296df
* Content: [attrib | Microsoft Docs](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/attrib)
* Content Source: [WindowsServerDocs/administration/windows-commands/attrib.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/attrib.md)
* Service: **unspecified**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by lizap** [comment]
You can use this command for files or groups of files, but not for users. Thanks.
