### ISSUE TITLE
Broken Link - Create the JEA Role File

### ISSUE THREAD

**Issue by JoelCBennett** [MicrosoftDocs/windowsserverdocs#4750]
Broken link under Create the JEA Role File in the link "JRE Role Capabilities".  It links to https://docs.microsoft.com/en-us/powershell/jea/role-capabilities, which is invalid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2dd1426-8251-d4a1-1082-286e0cc78b45
* Version Independent ID: b205687f-f9f9-a3f5-772f-3fad427bf828
* Content: [Delegate AD FS Powershell Commandlet Access to Non-Admin Users](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/delegate-ad-fs-pshell-access)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/delegate-ad-fs-pshell-access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/delegate-ad-fs-pshell-access.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
OK, so the invalid link URL is this: https://docs.microsoft.com/powershell/jea/role-capabilities

Suggestion for a working URL: https://docs.microsoft.com/powershell/scripting/learn/remoting/jea/role-capabilities

**Comment by illfated** [comment]
I will open a Pull Request to have that link corrected. The PR should be available shortly.

**Comment by illfated** [comment]
Hmm, there are several other broken URLs in the same page. Not sure if we should take the time to look up all of them right now, or just fix 1 URL at a time.

**Comment by illfated** [comment]
There you go. PR #4753 is available for review. Feel free to comment or post suggestions for further edits.
