### ISSUE TITLE
Applicable to server 2019?

### ISSUE THREAD

**Issue by davidwhitenz** [MicrosoftDocs/windowsserverdocs#4755]
Could you please advise or update the page if this is applicable for Server 2019? Currently the article suggests up to 2016.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e057092d-9ac5-4b9a-7f28-b5c83a3239cc
* Version Independent ID: e5743fda-f4a5-5a4c-fce0-4b5ef541c739
* Content: [Appendix F - Securing Domain Admins Groups in Active Directory](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/appendix-f--securing-domain-admins-groups-in-active-directory)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-F--Securing-Domain-Admins-Groups-in-Active-Directory.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-F--Securing-Domain-Admins-Groups-in-Active-Directory.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by iainfoulds** [comment]
@davidwhitenz Yes, this guidance should still apply for Windows Server 2019. Sorry for any confusion.

I'm working on broader doc updates to indicate support. Most of the existing content applies to Windows Server 2019.

#please-close

**Comment by davidwhitenz** [comment]
Thanks Iain! All good, will close off this issue. Appreciate the quick response also.
