### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by kuglidani** [MicrosoftDocs/windowsserverdocs#4756]
According to documentation: "The VPN client then sends the certificate issues by Azure AD to the VPN for credential validation. "
I think it should be "issued by" and not "issues by".
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5821032c-238b-624e-8f97-728845660380
* Version Independent ID: 8418cae3-e7fd-aa7c-1bd9-04b0fd3a534b
* Content: [Create root certificates for VPN authentication with Azure AD](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/vpn-create-root-cert-for-vpn-auth-azure-ad)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/vpn-create-root-cert-for-vpn-auth-azure-ad.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/vpn-create-root-cert-for-vpn-auth-azure-ad.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by illfated** [comment]
Nice catch, good call. I will open a Pull Request to have that typo corrected.
