### ISSUE TITLE
Provide Detail for All Valid Sections, Keys, and Values

### ISSUE THREAD

**Issue by JrAsparagus** [MicrosoftDocs/windowsserverdocs#476]
Similar to the following link with any addition information for the current version of ADCS.
https://blogs.technet.microsoft.com/askds/2009/10/15/windows-server-2008-r2-capolicy-inf-syntax/
or
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc737264(v=ws.10)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8ffdaef-7179-7cfc-ceb3-7443fe3e9476
* Version Independent ID: e5c1e3a8-9b73-d314-df06-c6da3a3adf67
* Content: [Prepare the CAPolicy.inf File | Microsoft Docs](https://docs.microsoft.com/en-us/windows-server/networking/core-network-guide/cncg/server-certs/prepare-the-capolicy-inf-file)
* Content Source: [WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Prepare-the-CAPolicy-inf-File.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Prepare-the-CAPolicy-inf-File.md)
* Service: **unspecified**
* GitHub Login: @jamesmci
* Microsoft Alias: **jamesmci**

**Comment by shortpatti** [comment]
@JrAsparagus -- Thank you for providing the extra detail.  I'll the changes made.

**Comment by shortpatti** [comment]
Changes have been made.
