### ISSUE TITLE
The commands are wrong in the documentation

### ISSUE THREAD

**Issue by mattdreher** [MicrosoftDocs/windowsserverdocs#4762]
The /e command was specified with an incorrect description:

/s | Copies subdirectories. This option automatically excludes empty directories.
/e | Copies subdirectories. This option automatically excludes empty directories.

It should be 

/s | Copies subdirectories. This option automatically excludes empty directories.
/e | Copies subdirectories. This option copy subdirectories, including Empty ones.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Closed in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/bbd9904c2b6a53f4543fdd1fc5fd50acd4a4fed9 . See also issue ticket #4759 for duplicate issue report.

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
