### ISSUE TITLE
Wrong term used

### ISSUE THREAD

**Issue by z7x** [MicrosoftDocs/windowsserverdocs#4764]
Under https://docs.microsoft.com/en-us/windows-server/upgrade/upgrade-2016-to-2019#to-perform-the-upgrade we are asked to check the **BuildLabEx** value but it should say **ProductName**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26a28fb3-5359-dcd1-7361-64deec4f1fd5
* Version Independent ID: fd95c553-bd8d-f060-5bfe-ad5b69ab1216
* Content: [Upgrade Windows Server 2016 to Windows Server 2019](https://docs.microsoft.com/en-us/windows-server/upgrade/upgrade-2016-to-2019)
* Content Source: [WindowsServerDocs/upgrade/upgrade-2016-to-2019.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/upgrade/upgrade-2016-to-2019.md)
* Product: **windows-server**
* Technology: **upgrade**
* GitHub Login: @RobHindman
* Microsoft Alias: **robhind**

**Comment by illfated** [comment]
Fair enough, that much is true when upgrading a production server. A quick search shows me 4 results for "**BuildLabEx**":

https://docs.microsoft.com/en-us/search/?terms=BuildLabEx

- **[Upgrade Windows Server 2012 R2 to Windows Server 2019](https://docs.microsoft.com/en-us/windows-server/upgrade/upgrade-2012r2-to-2019)**
- **[Upgrade Windows Server 2008 R2 to Windows Server 2012 R2](https://docs.microsoft.com/en-us/windows-server/upgrade/upgrade-2008r2-to-2012r2)**
- **[Upgrade Windows Server 2016 to Windows Server 2019](https://docs.microsoft.com/en-us/windows-server/upgrade/upgrade-2016-to-2019)**
- **[Upgrade Windows Server 2012 to Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/upgrade/upgrade-2012-to-2016)**

Oddly enough, I can't find the variable **BuildLabEx** in other documents when searching the entire Docs site. I thought that it would be part of a lab tutorial in the Docs.

**Comment by IngridAtMicrosoft** [comment]
#label: "triaged"

**Comment by IngridAtMicrosoft** [comment]
Addressed. #please-close
