### ISSUE TITLE
[Query] What should I put as my user name and password?

### ISSUE THREAD

**Issue by Vivraan** [MicrosoftDocs/windowsserverdocs#4768]
Unlike in Linux, the Windows user name and password to use for connecting to SSH aren't clearly stated, while I'd use `localhost` for the server name. Please advise on what these values should be.

I have tried:
- Using my PC's name and Windows Hello PIN.
- Using my PC's name and my Microsoft Account Password.
- Using the user name that appears under the `Users/` directory and the PIN.
- Using the user name that appears under the `Users/` directory and the Password.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Installation of OpenSSH For Windows Server](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT

**Comment by illfated** [comment]
(from #3970 :)

```powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\WINDOWS\system32> Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'

Name  : OpenSSH.Client~~~~0.0.1.0
State : NotPresent

Name  : OpenSSH.Server~~~~0.0.1.0
State : NotPresent

PS C:\WINDOWS\system32> # Install the OpenSSH Client
PS C:\WINDOWS\system32> Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0

Path          :
Online        : True
RestartNeeded : False

PS C:\WINDOWS\system32> # Install the OpenSSH Server
PS C:\WINDOWS\system32> Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0

Path          :
Online        : True
RestartNeeded : False

PS C:\WINDOWS\system32> # Install the OpenSSH Server
PS C:\WINDOWS\system32> Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0

Path          :
Online        : True
RestartNeeded : False

PS C:\WINDOWS\system32> Start-Service sshd
PS C:\WINDOWS\system32> # OPTIONAL but recommended:
PS C:\WINDOWS\system32> Set-Service -Name sshd -StartupType 'Automatic'
PS C:\WINDOWS\system32> # Confirm the Firewall rule is configured. It should be created automatically by setup.
PS C:\WINDOWS\system32> Get-NetFirewallRule -Name *ssh*

Name                  : OpenSSH-Server-In-TCP
DisplayName           : OpenSSH SSH Server (sshd)
Description           : Inbound rule for OpenSSH SSH Server (sshd)
DisplayGroup          : OpenSSH Server
Group                 : OpenSSH Server
Enabled               : True
Profile               : Any
Platform              : {}
Direction             : Inbound
Action                : Allow
EdgeTraversalPolicy   : Block
LooseSourceMapping    : False
LocalOnlyMapping      : False
Owner                 :
PrimaryStatus         : OK
Status                : The rule was parsed successfully from the store. (65536)
EnforcementStatus     : NotApplicable
PolicyStoreSource     : PersistentStore
PolicyStoreSourceType : Local

PS C:\WINDOWS\system32> # There should be a firewall rule named "OpenSSH-Server-In-TCP", which should be enabled
PS C:\WINDOWS\system32> # If the firewall does not exist, create one
PS C:\WINDOWS\system32> New-NetFirewallRule -Name sshd -DisplayName 'OpenSSH Server (sshd)' -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22

Name                  : sshd
DisplayName           : OpenSSH Server (sshd)
Description           :
DisplayGroup          :
Group                 :
Enabled               : True
Profile               : Any
Platform              : {}
Direction             : Inbound
Action                : Allow
EdgeTraversalPolicy   : Block
LooseSourceMapping    : False
LocalOnlyMapping      : False
Owner                 :
PrimaryStatus         : OK
Status                : The rule was parsed successfully from the store. (65536)
EnforcementStatus     : NotApplicable
PolicyStoreSource     : PersistentStore
PolicyStoreSourceType : Local

PS C:\WINDOWS\system32> Ssh illfated@VPCSE2N1E
The authenticity of host 'vpcse2n1e (fe80::c97c:af76:7a45:f78b%18)' can't be established.

ECDSA key fingerprint is SHA256:YFo7UR/MvjSaY7JFXeOZrnX71y9gceX7F9wUZwnpiBw.
Are you sure you want to continue connecting (yes/no)? _

Warning: Permanently added 'vpcse2n1e,fe80::c97c:af76:7a45:f78b%18' (ECDSA) to the list of known hosts.
illfated@vpcse2n1e's password: _

Microsoft Windows [Version 10.0.18363.752]
(c) 2019 Microsoft Corporation. All rights reserved.

illfated@VPCSE2N1E C:\Users\illfated>_
```

**Comment by illfated** [comment]
The login I found to be working for me in my testing is the following local information (on the same computer): `%USERNAME%@%USERDOMAIN%`

**Comment by konstruktoid** [comment]
I believe this is a support question and can be closed.

**Comment by illfated** [comment]
#please-close

**Comment by Vivraan** [comment]
> The login I found to be working for me in my testing is the following local information (on the same computer): `%USERNAME%@%USERDOMAIN%`

Or `$env:USERNAME`:`$env:USERDOMAIN`, I suppose.

This did not work in my case, I think.

**Comment by illfated** [comment]
The login method depends very much on the OS you are trying to log in from.
This question is still a support question, so my request to close this ticket still stands.

**Comment by illfated** [comment]
#please-close

**Comment by Vivraan** [comment]
Where should I pose support questions for documentation without someone trying to request its closure?

**Comment by illfated** [comment]
You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.
The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by Vivraan** [comment]
However I'd usually expect to land in a query page instead of an actual issue-and-feedback place. What you said makes sense but the redirect for getting assistance is misleading.

**Comment by Vivraan** [comment]
I'll close it myself.

**Comment by Morgan-6Freedom** [comment]
The documentation is not clear enough when it says we should use username@servername.

if 
- I login to my windows using john.doe@hotmail.com 
- my User folder name is John.
- my server ip is 192.168.1.42
- I typed `Set-Service -Name sshd -StartupType 'Automatic'` in the server initialization

Should I put

1. john.doe@hotmail.com@192.168.1.42 ?
2. John@192.168.1.42 ?
3. john@192.168.1.42 ?
4. john.doe@hotmail.com@sshd ?
5. John@sshd  ?
6. john@sshd  ?

I think an example should be useful inside [this part](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse#initial-use-of-ssh)

**Comment by konstruktoid** [comment]
Hi @Morgan-6Freedom, run `whoami` in PowerShell on the host that you will be connecting to in order to see the format and username.

**Comment by illfated** [comment]
From my experience, running sshd on Windows 10 and connecting from Windows 10, it works with both of these methods:
```powershell
ssh illfated@VPCSE2N1E

ssh VPCSE2N1E\illfated
```

I don't have enough recent experience with using ssh in other OS environments, so "your mileage may vary" and you should follow the advice above.
