### ISSUE TITLE
Import does what you need

### ISSUE THREAD

**Issue by whatdoctor** [MicrosoftDocs/windowsserverdocs#4769]
I just had the same issue as the original post and decided the instructions were a little more than I was willing to try.
I just did an import in place instead and it just worked perfectly.  It may be that Hyper-V has been upgraded since this article was written.  I was using Hyper-V manager 10.0.19041.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acc00093-1f29-7e3b-ab30-9e6966598390
* Version Independent ID: bd281aaf-4e09-73a4-95a0-873ab4cc5de2
* Content: [Export and import virtual machines](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/deploy/export-and-import-virtual-machines)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/deploy/Export-and-import-virtual-machines.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/deploy/Export-and-import-virtual-machines.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by illfated** [comment]
When you say "had the same issue as the original post", are you referring to issue ticket #3848 (**What happens when it won't find the files?**) ?

**Comment by whatdoctor** [comment]
Sorry - my first time posting here.  Attempted to reply to a post about adding a virtual machine to a different computer after the first one died (not the link you found).  Someone had found a really complicated way to do it but I found the import function worked fine.  My new computer is faster with a better cpu butt he VM is still on an external SSD.

**Comment by illfated** [comment]
Fair enough. Interesting scenario. Would you say, based on your findings, that the document can be improved upon, or is this mostly a technical discussion?

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. As your comment doesn't seem to be tied to any specific issue(s) within this documentation, we will be closing this thread. Please feel free to reopen this if changes do need to be made in order to better support your needs. #please-close
