### ISSUE TITLE
There is a note that says there used to be a recommendation to disable the Administrator account, however there are still references in this doc that say to check that the account is disabled.

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/windowsserverdocs#4771]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a861650d-0499-c46b-7ca8-d1fb04546192
* Version Independent ID: 3967b664-f419-6e8e-5ad8-f98cdcb21733
* Content: [Appendix D - Securing Built-In Administrator Accounts in Active Directory](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/appendix-d--securing-built-in-administrator-accounts-in-active-directory)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-D--Securing-Built-In-Administrator-Accounts-in-Active-Directory.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-D--Securing-Built-In-Administrator-Accounts-in-Active-Directory.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by PatAltimore** [comment]
I removed the disabled account references. The update will publish soon. 

Closing issue. #please-close.

Pat
