### ISSUE TITLE
Lots of duplicated code and several typos.

### ISSUE THREAD

**Issue by themattman18** [MicrosoftDocs/windowsserverdocs#4772]
Lots of duplicated code and several typos. The gac commands have random periods in them and the code for the c# library has duplicated sections.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 432d0552-7fd9-7220-c5b2-3dd726ce54fa
* Version Independent ID: fa375dbe-43da-abcc-bc52-87f48b3d0b0c
* Content: [Build a Custom Authentication Method for AD FS in Windows Server](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/ad-fs-build-custom-auth-method)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/ad-fs-build-custom-auth-method.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/ad-fs-build-custom-auth-method.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
I am not a real coder, but I get what you are talking about (e.g. DRY coding).

Would you like to create a Pull Request to have the offending code improved, or only add comments here about what needs to be changed?

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 4748 -b #assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. A documentation change has been made and will be live after the next business day. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
