### ISSUE TITLE
10

### ISSUE THREAD

**Issue by glcnmami** [MicrosoftDocs/windowsserverdocs#4775]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45b9a61b-38a5-151e-376c-ea2786acf8dd
* Version Independent ID: dd7a38cb-2485-0d03-8441-aa4cca2899cd
* Content: [Command-line syntax key](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/command-line-syntax-key)
* Content Source: [WindowsServerDocs/administration/windows-commands/command-line-syntax-key.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/command-line-syntax-key.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
