### ISSUE TITLE
Broken link in https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/walkthrough--workplace-join-with-an-ios-device

### ISSUE THREAD

**Issue by bshashik** [MicrosoftDocs/windowsserverdocs#478]
The following hyper-text leads to a broken link in this page:
 Create an application access policy and custom access denied message

https://docs.microsoft.com/en-us/azure/active-directory/active-directory-conditional-access-on-premises-setup - 404 not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccb8fc7d-0c10-c860-5826-4716961fc875
* Version Independent ID: 5e4135f6-3289-10ea-6dd5-7a3862f32e05
* Content: [Walkthrough - Workplace Join with an iOS Device](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/walkthrough--workplace-join-with-an-ios-device)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Walkthrough--Workplace-Join-with-an-iOS-Device.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Walkthrough--Workplace-Join-with-an-iOS-Device.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by lizap** [comment]
Thanks for pointing this out. It looks like one of our redirects isn't working. I've updated the article to point to "Create an application access policy and custom access-denied message" (at https://docs.microsoft.com/en-us/azure/active-directory/active-directory-device-registration-on-premises-setup#create-an-application-access-policy-and-custom-access-denied-message). Change will be live on 4/3/2018, by 4 PM.
