### ISSUE TITLE
Please update for new functionality

### ISSUE THREAD

**Issue by adilapi** [MicrosoftDocs/windowsserverdocs#4780]
KB4571748 indicates "new functionality" has recently been added to the robocopy command but I cannot find any information on this.  Please consider updating this article with relevant details.

[August 20, 2020—KB4571748 (OS Build 17763.1432) Preview](https://support.microsoft.com/en-us/help/4571748)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @steved0x,

Thanks again for contacting Microsoft. We value your feedback. 

Doing some digging, I found one of our [blog articles](https://blogs.windows.com/windowsexperience/2020/09/02/announcing-windows-server-vnext-preview-build-20206/) related to [KB4571748](https://support.microsoft.com/en-us/topic/august-20-2020-kb4571748-os-build-17763-1432-preview-fa1db909-8923-e70f-9aef-ba09edaee6f0). It appears that the new robocopy functionality (and xcopy) is one new parameter, "**/compress**". The documentation has been updated to reflect this new parameter.

We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
