### ISSUE TITLE
Can't do in-place upgrade like it says

### ISSUE THREAD

**Issue by ArranTuna** [MicrosoftDocs/windowsserverdocs#4781]
Can't do in-place upgrade like it says as I am using "Windows Server 2012 R2 Standard" and in the server 2019 installer I am getting this which shows I can't do in-place upgrade:

![image](https://user-images.githubusercontent.com/253404/92154734-2c6d1f80-ee1e-11ea-8f4b-826731907b56.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82772fa0-1642-4481-dff0-ebf83270db4d
* Version Independent ID: e5d451c4-2ee0-9461-c19b-19d0cb199b42
* Content: [Upgrade Windows Server 2012 R2 to Windows Server 2019](https://docs.microsoft.com/en-us/windows-server/upgrade/upgrade-2012r2-to-2019)
* Content Source: [WindowsServerDocs/upgrade/upgrade-2012r2-to-2019.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/upgrade/upgrade-2012r2-to-2019.md)
* Product: **windows-server**
* Technology: **upgrade**
* GitHub Login: @RobHindman
* Microsoft Alias: **robhind**

**Comment by ArranTuna** [comment]
At least in the guide tell us how we can figure out what reason the installer has decided to block the in-place upgrade. I have tried looking in the installer log file and there is nothing about it being blocked in the hundreds of log lines it makes.

**Comment by networld-its** [comment]
i have the same exact issue, trying to upgrade windows server 2012 r2 standard to windows server 2019 standard.
doesnt allow me to keep my files and apps.

**Comment by illfated** [comment]
I haven't tested this myself, but if I were to troubleshoot your issues, I would have started looking at the Microsoft Update / Windows Update status of your servers, then checked the list of installed programs to see if any of those are either not supported on Server 2019 or not updated to its newest status.

I could be wrong, of course. There are several unanswered questions and I don't know half of them. Have you tried contacting your nearest Microsoft Support department?

**Comment by IngridAtMicrosoft** [comment]
#label:"triaged"

**Comment by IngridAtMicrosoft** [comment]
@ArranTuna Please open a support ticket, as GitHub issues for this repo are for reporting problems with our documentation.  #please-close
