### ISSUE TITLE
Outdated page/tools/docs need to be removed.

### ISSUE THREAD

**Issue by andreiztm** [MicrosoftDocs/windowsserverdocs#4782]
Hi,

the tools mentioned in this article are no longer available (error 404 on download) and no longer maintained. Could you please help remove this page? As some customers are asking about the broken downloads. There is an internal thread on this with WSUS PM Paul Reed.

An alternative would be:
The alternative is to use the WSUS API and build customer reports yourself:

https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc720459(v=ws.10)?redirectedfrom=MSDN#use-wsus-apis-to-create-custom-reports

Thanks,
Andrei

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa21e853-8fa2-24d0-9806-75345cc12fd3
* Version Independent ID: 5397b0db-f1b5-fa63-df9c-112fb9672833
* Content: [Windows Server Update Services tools and utilities](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/manage/wsus-tools?source=docs)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/manage/wsus-tools.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/manage/wsus-tools.md)
* Product: **windows-server**
* Technology: **wsus**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by vpaulreed** [comment]
Please remove this page as the tools on the page are no longer available.

**Comment by illfated** [comment]
Could you please provide more details? All links seem to work for me, so I don't know which ones you are talking about.

Please provide text, paragraphs or screen shots of what does not work for you any more.

**Comment by vpaulreed** [comment]
@illfated - The page loads, but yeah you get the 404 error when you click on the link "WSUS Reporting Rollup Sample Tool" and "Client Diagnostics Tool."  The downloads are no longer available.  So yea, the page is useless now.

**Comment by illfated** [comment]
OK, we agree that the page needs to be removed. The remaining uncertainty for me is whether we ignore any pages linking to this one, or if you have got any practical methods to traceback pages pointing to this one.

**Comment by vpaulreed** [comment]
@illfated - I've tried going through WSUS pages on docs.microsoft.com, and cannot find a reference.  I've also tried bing and google.  However I am sure other people have linked to it.  I'm not sure how much work it is, but could we add a banner at the top saying that the "WSUS Reporting Rollup Sample Tool" and "Client Diagnostics Tool" are no long available and let folks know the page would be taken down in 30 days?

**Comment by illfated** [comment]
Thank you for the useful feedback. I think that sounds like a good idea. I was pondering the implications of removing the page altogether, but your suggestion makes sense. To be honest, I think the page should be moved to the archives, unless any of the MS Docs team members know that the tools will be made available again.

**Comment by illfated** [comment]
(ref. #4957 )

**Comment by illfated** [comment]
(also ref. #5105 )
