### ISSUE TITLE
Command-line examples don't work

### ISSUE THREAD

**Issue by djmitchella** [MicrosoftDocs/windowsserverdocs#4783]
The command-line examples don't work, for a couple of reasons.

First, everything after the '/d' should be in quotes; it looks like they were copied from https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-xp/bb490899(v=technet.10)?redirectedfrom=MSDN, but didn't quite come across properly.

Second, even fixing that, some of them just don't work anyway. (on windows 10, at least). After adding the missing quotes:

`eventcreate /t information /id 1000 /so winmgmt /d "Create event in WinMgmt source"`
fails with "ERROR: Source parameter is used to identify custom applications/scripts only (not installed applications)."

`eventcreate /t error /id 2001 /so winword /l application /d "new src Winword in application log"`
 fails with "ERROR: EventID must be in the range of 1 - 1000."

(I haven't tried the log-to-remote-server ones)

 The examples that `eventcreate /?` gives do work, though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6ca4c13-d0f1-560d-9b23-13001949b78f
* Version Independent ID: edc21998-3980-2518-8725-21b0dd54a345
* Content: [eventcreate](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/eventcreate)
* Content Source: [WindowsServerDocs/administration/windows-commands/eventcreate.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/eventcreate.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
@eross-msft : is there any internal PR in the pipelines for this ticket issue?

**Comment by illfated** [comment]
Output from `eventcreate /?` in Windows 10 :

```
Microsoft Windows [Version 10.0.19041.388]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\illfated>eventcreate /?

EVENTCREATE [/S system [/U username [/P [password]]]] /ID eventid
            [/L logname] [/SO srcname] /T type /D description

Description:
    This command line tool enables an administrator to create
    a custom event ID and message in a specified event log.

Parameter List:
    /S    system           Specifies the remote system to connect to.

    /U    [domain\]user    Specifies the user context under which
                           the command should execute.

    /P    [password]       Specifies the password for the given
                           user context. Prompts for input if omitted.

    /L    logname          Specifies the event log to create
                           an event in.

    /T    type             Specifies the type of event to create.
                           Valid types: SUCCESS, ERROR, WARNING, INFORMATION.

    /SO   source           Specifies the source to use for the
                           event (if not specified, source will default
                           to 'eventcreate'). A valid source can be any
                           string and should represent the application
                           or component that is generating the event.

    /ID   id               Specifies the event ID for the event. A
                           valid custom message ID is in the range
                           of 1 - 1000.

    /D    description      Specifies the description text for the new event.

    /?                     Displays this help message.


Examples:
    EVENTCREATE /T ERROR /ID 1000
        /L APPLICATION /D "My custom error event for the application log"

    EVENTCREATE /T ERROR /ID 999 /L APPLICATION
        /SO WinWord /D "Winword event 999 happened due to low diskspace"

    EVENTCREATE /S system /T ERROR /ID 100
        /L APPLICATION /D "Custom job failed to install"

    EVENTCREATE /S system /U user /P password /ID 1 /T ERROR
        /L APPLICATION /D "User access failed due to invalid user credentials"

C:\Users\illfated>_
```

**Comment by eross-msft** [comment]
@illfated  Nope, not that I know of. If you want to do the PR for it, go for it! Thanks!!!
