### ISSUE TITLE
Start cmd no longer working as it used to

### ISSUE THREAD

**Issue by WanaGo** [MicrosoftDocs/windowsserverdocs#4784]
You seem to have to specify a 'Window Name' now, which you never use to have to do. Which breaks documentation we have had for years using this Start command.

start [<Title>] [/d <Path>] [/i] [{/min | /max}] [{/separate | /shared}] [{/low | /normal | /high | /realtime | /abovenormal | belownormal}] [/affinity <HexAffinity>] [/wait] [/elevate] [/b] [<Command> [<Parameter>... ] | <Program> [<Parameter>... ]]

is wrong, should be

start <Title> [/d <Path>] [/i] [{/min | /max}] [{/separate | /shared}] [{/low | /normal | /high | /realtime | /abovenormal | belownormal}] [/affinity <HexAffinity>] [/wait] [/elevate] [/b] [<Command> [<Parameter>... ] | <Program> [<Parameter>... ]]

However the fact you need a Window Name is very annoying.

Typically we have used:
start /w "c:\path_name_here\filename.ext"
But all this does now is open another cmd prompt window with "c:\path_name_here\filename.ext" as it's title.

As a minimum, what is now required is this:
start "" /w "c:\path_name_here\filename.ext"

Why did this change??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a52b78b6-e846-0b32-25c0-f9aab145b112
* Version Independent ID: 0c56bb98-4f1f-dd55-63ae-8bb18535cee1
* Content: [start](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start)
* Content Source: [WindowsServerDocs/administration/windows-commands/start.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/start.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Good question, especially when it does not seem to be obvious from just reading the help text.

I doubt that anyone who knows why that change was made will be available to answer your question, I think that would be something more likely to be shared in a developer forum like MSDN or similar.

Knowing that this repository is intended for reporting issues in the Microsoft Documentation, it looks like what we need to focus on here is to consider removing the optional brackets around the **"title"** keyword in the documentation page.

We can always open a Pull Request to do so, even though I keep second-guessing myself on the difference between the OS help files and this documentation page.
