### ISSUE TITLE
Translate into spanish

### ISSUE THREAD

**Issue by yScQ** [MicrosoftDocs/windowsserverdocs#4785]
It would be great if you translated this article into Spanish. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b73a4605-c4b3-46a8-ec4e-493751fff82b
* Version Independent ID: 2bcfea05-35c7-49cb-0570-a0d5a4957ca1
* Content: [echo](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/echo#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/echo.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/echo.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Ya Hecho -- Already Done:

https://docs.microsoft.com/es-es/windows-server/administration/windows-commands/echo

Asegúrese de configurar su navegador para usar español si desea mostrar páginas en ese idioma.

(Make sure you set your browser to use Espanol if you want to display pages in that language.)

**Comment by illfated** [comment]
Partes de este tema pueden estar traducidos automáticamente.
- https://docs.microsoft.com/es-es/windows-server/administration/windows-commands/echo

**Comment by illfated** [comment]
Para la mayoría de las páginas del repositorio de Microsoft Docs (docs.microsoft.com), puede hacer lo siguiente para que se muestre en español: Asegúrese de agregar el siguiente texto como parte de la URL: en lugar de / en-us / (Inglés - Estados Unidos) en la URL, escriba / es-es / (Español - España) para obtener la mayor traducción posible al español.

**Comment by illfated** [comment]
#please-close
