### ISSUE TITLE
Points to use /adfs/probe on HTTP against the web application proxy, but the WAP doesn't have HTTP enabled

### ISSUE THREAD

**Issue by pauska** [MicrosoftDocs/windowsserverdocs#4786]
The document says that it's recommended to use the HTTP probe /adfs/probe - but the Web Application Proxy does not have this endpoint after a fresh install on Windows Server 2019. The Windows Firewall on the WAP servers doesn't have port 80 opened up either, and it doesn't help to manually add a rule to allow port 80.

Note that the endpoint does exist on our ADFS servers, like the document describes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fc58b9-7063-5107-5f65-c77694b33c7e
* Version Independent ID: a541e745-1505-696d-2adf-c578e1f54b4c
* Content: [AD FS 2016 Requirements](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-requirements)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/ad-fs-requirements.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/ad-fs-requirements.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
