### ISSUE TITLE
Multiple incorrect and missing requirement descriptions

### ISSUE THREAD

**Issue by tandasat** [MicrosoftDocs/windowsserverdocs#4790]
Those should be corrected:
- The virtual machine generation must be 9.1 or higher. Otherwise, `Set-VMProcessor` command fails with the below message
```
Cannot modify processor setting 'EnablePerfmonIpt' without first upgrading the virtual machine version.
(Current version: 9.0. Needs version: 9.1).
```
- `An Intel processor that supports IPT and the PT2GPA feature.` needs clarification or can even be incorrect. 

PT2GPA is not a term used in the Intel Software Developers Manual, and needs clarification. I doubt this is incorrect information, as I was able to enable PT for a VM running on Coffee Lake processors. 

- PT cannot be enabled alone, and the description should clarify this

The below example gives and impression that PT can be enabled without enabling other performance monitoring features. 
`Set-VMProcessor MyVMName -Perfmon @("ipt")` 

This fails like this
```
> Set-VMProcessor "Win10 20H1" -Perfmon @("ipt")
Set-VMProcessor : Failed to modify device 'Processor'.
'Win10 20H1' failed to modify device 'Processor'. (Virtual machine ID
085DFF33-5CC4-4CB9-9681-4C28C8A44A79)
```

Instead, the page should instruct to run `Set-VMProcessor MyVMName -Perfmon @("pmu", "lbr", "pebs", "ipt")`  to enable PT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d511241-f09a-63d9-e95b-99a52d93a14c
* Version Independent ID: c5897e9d-b827-04be-f894-59acf1474cf7
* Content: [Enable Intel Performance Monitoring Hardware in a Hyper-V Virtual Machine](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/performance-monitoring-hardware)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/Performance-Monitoring-Hardware.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/Performance-Monitoring-Hardware.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @ifeomaufondu-ms
* Microsoft Alias: **ifufondu**

**Comment by illfated** [comment]
Seeing that the PR #4825 got closed automatically by one of the MS Docs PR merger bots, due to the MS Docs team member author, I decided to create one myself (PR #4984), since the document has not been updated since commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/20603c7c4aeee121614725b2d2cd513f9c909767 of August 7.

Feel free to view, comment and suggest any further improvements in my PR.
