### ISSUE TITLE
Link to Windows PowerShell in left navigation pane is dead

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/windowsserverdocs#4792]
At https://docs.microsoft.com/en-us/windows-server/administration/manage-windows-server , in the left navigation pane, the link to Automate Windows Server management > Windows PowerShell scripting is dead. This needs to be fixed.

**Comment by illfated** [comment]
Well, we probably need to look up the new page within the PowerShell Documentation page overview: https://docs.microsoft.com/en-us/powershell/

I was thinking maybe we could use https://docs.microsoft.com/en-us/powershell/scripting/overview?view=powershell-7 , but there might be a more exact page beneath it, or parallel to the "[**What is PowerShell?**](https://docs.microsoft.com/en-us/powershell/scripting/overview?view=powershell-7)" page.

Suggestions and/or recommendations are more than welcome.

**Comment by illfated** [comment]
Looks like you fixed this issue on Oct 16, 2020, 12:47 PM PDT, in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/68e512d7a026babde93ec35ded2e8ae2b4b6b4b1 (file link https://github.com/MicrosoftDocs/windowsserverdocs/commit/68e512d7a026babde93ec35ded2e8ae2b4b6b4b1#diff-31c178ae9b889549cf45ec64aebdf5f46b48bb139348dbeebc99b698958eee72)

https://github.com/MicrosoftDocs/windowsserverdocs/commit/68e512d7a026babde93ec35ded2e8ae2b4b6b4b1#diff-31c178ae9b889549cf45ec64aebdf5f46b48bb139348dbeebc99b698958eee72L62-L72

```diff
  @@ -62,11 +62,11 @@
  #### [Manage User Access Logging](user-access-logging/manage-user-access-logging.md)
  
  ## Tune your Windows Server performance
- ### [Performance Tuning Guidelines](performance-tuning/index.md) 
+ ### [Performance Tuning Guidelines](performance-tuning/index.md)
  ### [Microsoft Server Performance Advisor](server-performance-advisor/microsoft-server-performance-advisor.md)
  #### [Server Performance Advisor User's Guide](server-performance-advisor/server-performance-advisor-users-guide.md)
  #### [Server Performance Advisor Pack Development Guide](server-performance-advisor/server-performance-advisor-pack-development-guide.md)
  
  ## Automate Windows Server management
- ### [Windows PowerShell scripting](/powershell/scripting/powershell-scripting?view=powershell-5.1)
+ ### [Windows PowerShell scripting](/powershell/scripting/overview)
  ### [Windows Commands](windows-commands/windows-commands.md)
```
https://github.com/MicrosoftDocs/windowsserverdocs/blame/master/WindowsServerDocs/administration/TOC.md#L71

**Comment by illfated** [comment]
#please-close
