### ISSUE TITLE
pktmon command is not documented

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/windowsserverdocs#4793]
[Enter feedback here]

The pktmon command is not documented. It needs to be documented. Please document it.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d382ca0-6538-5e1d-3e83-e31c9ab6a911
* Version Independent ID: 11eff296-6158-f89a-4941-8735529183e9
* Content: [Windows commands](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands)
* Content Source: [WindowsServerDocs/administration/windows-commands/windows-commands.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/windows-commands.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. A documentation change has been made and will be live after the next business day. You can view more about the pktmon cmdlet [here](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/pktmon).

We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
