### ISSUE TITLE
Poor page information

### ISSUE THREAD

**Issue by Kotensu** [MicrosoftDocs/windowsserverdocs#4794]
Page in question offers no instruction or assistance towards the page title.
Page indicates it's a How article, not a Who article. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b278b39-8437-1886-ab8e-264370673776
* Version Independent ID: 10a3d7bb-4673-c53d-1310-55204018af60
* Content: [Assigning the DNS for AD DS Owner Role](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/assigning-the-dns-for-ad-ds-owner-role)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/Assigning-the-DNS-for-AD-DS-Owner-Role.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/Assigning-the-DNS-for-AD-DS-Owner-Role.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by PatAltimore** [comment]
Hi @Kotensu,

Thanks for the feedback. I changed the title to match the intent of the article. The change will publish today. 

Thanks,
Pat 

#please-close
