### ISSUE TITLE
User CALs require AD for Server 2019?

### ISSUE THREAD

**Issue by VGSandz** [MicrosoftDocs/windowsserverdocs#4795]
Does Server 2019 need AD available to install user CALs? and throws the following error?

"There is a problem with your Remote Desktop license, and your session will be disconnected in 60 minutes. Contact your system administrator to fix this problem."

what about standalone servers? i mean what logic exists. This multiple sessions technically should be free, but it's paid. now its a pain for server 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd015c0b-3360-88fd-86b1-08e8c0e8ec5e
* Version Independent ID: 0c3ddb09-23f3-68a3-e7a4-877951feb55b
* Content: [License your RDS deployment with client access licenses (CALs)](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-client-access-license)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-client-access-license.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-client-access-license.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
Hello @VGSandz. GitHub issues for this repo are for reporting problems with our documentation.  Please open a support ticket or post your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html).
