### ISSUE TITLE
Typo in Repair Options/Syntax/Parameters

### ISSUE THREAD

**Issue by nshallred** [MicrosoftDocs/windowsserverdocs#4797]
`

/fc | Runs from source and re-caches the local package.
-- | --

`
Should be: -
`

/fv | Runs from source and re-caches the local package.
-- | --

`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a2e3005-0d38-154e-560e-0f25d4892810
* Version Independent ID: 11dcf68e-545e-8e9d-3df0-645a9ae9b6fc
* Content: [msiexec](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/msiexec)
* Content Source: [WindowsServerDocs/administration/windows-commands/msiexec.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/msiexec.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
Good point. The list is sorted alphabetically too, so it should be pretty obvious that this typo is a copy-paste from a few lines above and should be **/fv** as you said.

**Comment by eross-msft** [comment]
@illfated @RAJU2529  Fixed in current pull request. This should be live in the next few days.

**Comment by illfated** [comment]
#please-close
