### ISSUE TITLE
"Storage" section is confusing

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/windowsserverdocs#480]
implies that, for example, that you must have exclusively 2016 guests to use Storage Spaces Direct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 135138ec-af8e-3ce7-bcc9-b2c972eac54a
* Version Independent ID: bcce95fd-7533-9661-8778-de026461e4a3
* Content: [Hyper-V feature compatibility by generation and guest](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/hyper-v-feature-compatibility-by-generation-and-guest)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Hyper-V-feature-compatibility-by-generation-and-guest.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/Hyper-V-feature-compatibility-by-generation-and-guest.md)
* Service: **na**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by TBBle** [comment]
The Storage Spaces Direct documentation at https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/storage-spaces-direct-overview also implies you need a Windows Server 2016 to use it.

**Comment by fowl2** [comment]
@TBBle you do. Any even Standard is not enough - Enterprise Edition is required. https://docs.microsoft.com/en-us/windows-server/get-started/2016-edition-comparison

**Comment by TiloGit** [comment]
Please add info of hot add disk (SCSI adapter disk); seems to work on Win guest but not on Linux

**Comment by fowl2** [comment]
@daveba was this resolved?

**Comment by TBBle** [comment]
Looking at this a year later, I don't see the confusion. The table says that only Gen 2 Windows Server 2016 guests can use Storage spaces direct, but I don't see the implication that you cannot have other guests present at all.

What's not clear to me is whether this is actually Hyper-V relevant. Looking at https://techcommunity.microsoft.com/t5/Failover-Clustering/Storage-Spaces-Direct-using-Windows-Server-2016-virtual-machines/ba-p/372018, it seems that Hyper-V and the host aren't actually involved when a guest is using Storage Spaces Direct, it's entirely up to the guest's OS. That example can use 2012 R2 VM hosts, even though the guests need to be Server 2016 Datacenter.

**Comment by fowl2** [comment]
Ahh well it's not clear rather than confusing then ;)

It's possible that S2D in guests is only supported on 2016+ hosts, but I don't think this table is the best way of expressing that as every other item is describing host features not guest.
