### ISSUE TITLE
Dead Links

### ISSUE THREAD

**Issue by EQ5** [MicrosoftDocs/windowsserverdocs#4801]
[Enter feedback here]
Dead Links at the End of the Page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1999621a-92cd-28d0-88e0-c504d409afa5
* Version Independent ID: a9c96c5f-b03d-1805-fd7d-29853d33d03c
* Content: [Migrate SYSVOL replication to DFS Replication](https://docs.microsoft.com/en-us/windows-server/storage/dfs-replication/migrate-sysvol-to-dfsr)
* Content Source: [WindowsServerDocs/storage/dfs-replication/migrate-sysvol-to-dfsr.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/dfs-replication/migrate-sysvol-to-dfsr.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
I think it will be useful to point out which ones and how many links are broken (404):

The 5 broken links can be found underneath https://docs.microsoft.com/en-us/windows-server/storage/dfs-replication/migrate-sysvol-to-dfsr#additional-references (see copy below):

## Additional references

[SYSVOL Migration Series: Part 1—Introduction to the SYSVOL migration process](https://go.microsoft.com/fwlink/?linkid=121756) **(404 Web Site not found.)**

[SYSVOL Migration Series: Part 2—Dfsrmig.exe: The SYSVOL migration tool](https://go.microsoft.com/fwlink/?linkid=121757) **(404 Web Site not found.)**

[SYSVOL Migration Series: Part 3—Migrating to the 'PREPARED' state](https://go.microsoft.com/fwlink/?linkid=121758) **(404 Web Site not found.)**

[SYSVOL Migration Series: Part 4—Migrating to the 'REDIRECTED' state](https://go.microsoft.com/fwlink/?linkid=121759) **(404 Web Site not found.)**

[SYSVOL Migration Series: Part 5—Migrating to the 'ELIMINATED' state](https://go.microsoft.com/fwlink/?linkid=121760) **(404 Web Site not found.)**

[Step-by-Step Guide for Distributed File Systems in Windows Server 2008](https://go.microsoft.com/fwlink/?linkid=85231)

[FRS Technical Reference](https://go.microsoft.com/fwlink/?linkid=121764)

***

Most Technet pages have migrated to a differently named domain, so we may be able to find working URLs, even if archived.

**Comment by RAJU2529** [comment]
I am fixing invalid links now.

**Comment by illfated** [comment]
Looks good @RAJU2529 - I just added some suggestions for cosmetic text adjustment, but if you think it is unnecessary, that is OK too.
(ref. Pull Request #4803 .)

**Comment by illfated** [comment]
This issue was resolved 3 weeks ago. Thank you all for participating. 👍 🙂

**Comment by illfated** [comment]
#please-close
