### ISSUE TITLE
Undefined Acronym LUN

### ISSUE THREAD

**Issue by jlroynet** [MicrosoftDocs/windowsserverdocs#4804]
LUN did not immediately come to mind when reading this article where it is used 43 times.  It would help to say Logical Unit Number (LUN) the first time it is used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d7bd11a-e693-26a0-d374-5cfb1d2335d3
* Version Independent ID: bc9a2fb3-fa85-4ec0-8e0f-6e7c4906262b
* Content: [Volume Shadow Copy Service](https://docs.microsoft.com/en-us/windows-server/storage/file-server/volume-shadow-copy-service)
* Content Source: [WindowsServerDocs/storage/file-server/volume-shadow-copy-service.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/volume-shadow-copy-service.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Fair point, the text "a Logical Unit Number (LUN)" in 12 other pages, but none of them underneath the Storage section/chapters.

Then again, I was wondering how common a problem it is for IT personnel to get as far as the Storage documentation section without ever having seen the acronym LUN before in relation to computer (server) storage.

**Comment by illfated** [comment]
There you go. Sorry for the delay. PR #4952 is ready for review and comments.
