### ISSUE TITLE
Quotation marks are required for timezone identifiers

### ISSUE THREAD

**Issue by jschlackman** [MicrosoftDocs/windowsserverdocs#4805]
### Both examples for the /s switch are wrong, as quotation marks are required for timezone identifiers
The examples listed for the `/s` switch are wrong and do no match the correct examples given by running `tzutil /?`

Current examples on page:

`tzutil /s Pacific Standard time`
and
`tzutil /s Pacific Standard time_dstoff`

Correct syntax must include quotation marks around the TZ identifier, e.g.
`tzutil /s "Pacific Standard Time"`
and
`tzutil /s "Pacific Standard Time_dstoff"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1c0add1-f2b7-9eb9-5f16-350e94a191e4
* Version Independent ID: 19261da7-d370-e21d-dccb-6608f60338f2
* Content: [tzutil](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/tzutil)
* Content Source: [WindowsServerDocs/administration/windows-commands/tzutil.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/tzutil.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
Thanks, good point. I will open a Pull Request to have that issue resolved.
Anything else on the same page, while I suggest your changes?

**Comment by eross-msft** [comment]
@illfated @jschlackman  I've actually already made the change in my current pull request. This should be published in the next few days and you should see the update.

**Comment by illfated** [comment]
Thanks. Good work, thank you for noticing and posting. 😺

**Comment by illfated** [comment]
```
Microsoft Windows [Version 10.0.19041.388]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\illfated>tzutil /?
Windows Time Zone Utility

Usage:
TZUTIL </? | /g | /s TimeZoneID[_dstoff] | /l>

Parameters:
    /? Displays usage information.

    /g Displays the current time zone ID.

    /s TimeZoneID[_dstoff]
       Sets the current time zone using the specified time zone ID.
       The _dstoff suffix disables Daylight Saving Time adjustments
       for the time zone (where applicable).

    /l Lists all valid time zone IDs and display names. The output will
       be:
           <display name>
           <time zone ID>

Examples:
    TZUTIL /g
    TZUTIL /s "Pacific Standard Time"
    TZUTIL /s "Pacific Standard Time_dstoff"

Remarks:
    An exit code of 0 indicates the command completed successfully.

C:\Users\illfated>_
```

**Comment by illfated** [comment]
#please-close
