### ISSUE TITLE
Max SAGESET value is 9999 not 65535

### ISSUE THREAD

**Issue by sqlposh** [MicrosoftDocs/windowsserverdocs#4806]
FYI, tested this on both Server 2016 (1607) and Win10 (1909)

The documentation says the max /sageset:x value is 65535.  This is not true based on the way the registry value is created.  It appears that it creates a "StateFlagsXXXX" value where only the first 4 digits are used in the name so the largest value that should be used is 9999.

cleanmgr /D C /sageset:9999
cleanmgr /D C /sageset:10000
cleanmgr /D C /sageset:65535

produces registry values named:

StateFlags9999
StateFlags1000
StateFlags6553

Therefore, I believe the instructions should show that the maximum value for /SAGESET: and /SAGERUN: is 9999

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 768ab539-031f-b493-edc9-2958ced20fc2
* Version Independent ID: cab3aa07-fc05-1a74-875b-fd37983593d4
* Content: [cleanmgr](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cleanmgr)
* Content Source: [WindowsServerDocs/administration/windows-commands/cleanmgr.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/cleanmgr.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @iangpgh
* Microsoft Alias: **jgerend**

**Comment by RAJU2529** [comment]
i will create one more PR to add further topics with explanations, for this purpose I am collecting information.

**Comment by RAJU2529** [comment]
@iangpgh , i collected information today, so I am ready to create PR with extra topics. Can I create now?

**Comment by iangpgh** [comment]
I no longer work on this team (v-iap)

**Comment by illfated** [comment]
Thanks. Creating a PR to change author name based on your feedback.
