### ISSUE TITLE
enable secondary right-click on a MacBook

### ISSUE THREAD

**Issue by casagordita** [MicrosoftDocs/windowsserverdocs#4807]
You advised going into System Preferences, clicking Mouse, and then enabling Secondary click there.  On a MacBook without a mouse, the Mouse settings don't offer that option--they just tell you "No mouse found."  You have to click Trackpad--that's where you'll find the setting to enable Secondary click.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e3bc1ca-2fde-4a75-3583-fdb8ff2bf962
* Version Independent ID: 5cef2f0a-bed1-f05f-0f74-ba6f2808a714
* Content: [Remote Desktop clients FAQ](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-client-faq#mac-client---hardware-questions)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
Very well. So this is only a 1 word correction? Or would you like to recommend additional changes?

**Comment by casagordita** [comment]
Nope, just the one word…which will make all the difference to a few people who can’t figure it out for themselves.

And you’re welcome.

------------

Mary McGhee
marymc@casagordita.com

“Espresso est, ergo cogito."

**Comment by illfated** [comment]
Thanks, both for the textual correction report and for the additional confirmation. 👍
