### ISSUE TITLE
Allow easy switching to english version

### ISSUE THREAD

**Issue by spawnia** [MicrosoftDocs/windowsserverdocs#481]
I landed on your machine-translated german docs page. I could not find an easy option of simply displaying the article in english without switching the language of the whole page. The mouse-hover feature is just distracting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3824263-5c49-03e9-9063-b44b1c636540
* Version Independent ID: 31684400-9100-b442-8957-c1300ad35cb8
* Content: [AD FS Scenarios for Developers](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-scenarios-for-developers#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/AD-FS-Scenarios-for-Developers.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/AD-FS-Scenarios-for-Developers.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by lizap** [comment]
Thanks for the comment - to make sure the right people see it, can you open it as feedback against the docs.microsoft.com site? Here's where you can do that: https://aka.ms/sitefeedback
