### ISSUE TITLE
Is there a flag that will show hidden files in the tree?

### ISSUE THREAD

**Issue by Josias-Cruz** [MicrosoftDocs/windowsserverdocs#4812]
[Enter feedback here]
are the /a /f flags the only ones available to the tree command? is there a way to get the hidden files listed in the tree too?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a3647fd-2127-f673-618e-9842d3e8202c
* Version Independent ID: 00e69fb8-23b3-eb08-47fb-adf04f46fbf1
* Content: [tree](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/tree)
* Content Source: [WindowsServerDocs/administration/windows-commands/tree.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/tree.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by RAJU2529** [comment]
@Josias-Cruz , you can use the **ATTRIB**  command to see  hidden files to make visible.

moreover  /A  works with  attrib command , no /f

**Comment by illfated** [comment]
```
Microsoft Windows [Version 10.0.19041.388]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>tree /?
Graphically displays the folder structure of a drive or path.

TREE [drive:][path] [/F] [/A]

   /F   Display the names of the files in each folder.
   /A   Use ASCII instead of extended characters.


C:\WINDOWS\system32>_
```

**Comment by illfated** [comment]
> are the /a /f flags the only ones available to the tree command? is there a way to get the hidden files listed in the tree too?
> 

Those 2 "flags" appear to be the only available parameters to the command.
*
If you need to look for hidden files, you need to use the DIR command with switches, like `DIR /AH` to see only hidden files or `DIR /A` to list all files regardless of attributes.
*
If you need to see which files has got which attributes, use the ATTRIB command, as needed.

**Comment by IngridAtMicrosoft** [comment]
Addressed in comments.
