### ISSUE TITLE
Steps "To create an Azure storage account" confusing

### ISSUE THREAD

**Issue by Schutzhund3** [MicrosoftDocs/windowsserverdocs#4817]
In Step 3, ii. For Account kind, select general purpose.  "You can't use a Blob storage account for a Cloud Witness."

but then in "View and copy endpoint URL Links" it says: "… Cloud Witness always uses Blob as the the storage type."

**Comment by RAJU2529** [comment]
@Schutzhund3. Which article are you referring ?

**Comment by Schutzhund3** [comment]
https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/deploy-cloud-witness.md

**Comment by RAJU2529** [comment]
@thanks for reply. I dont have knowledge about Azure , so wait for few days to get answers from azure experienced users
