### ISSUE TITLE
MicrosoftDocs

### ISSUE THREAD

**Issue by bhargavgb** [MicrosoftDocs/windowsserverdocs#4818]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e4c63a8-69a4-da31-a805-54f5a4eba11d
* Version Independent ID: c1af9748-e90c-9521-7ea8-017ad238faa0
* Content: [Remote Desktop - Allow access to your PC](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-allow-access)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-allow-access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-allow-access.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
This looks more like a test of the reporting feature than an actual report.

@bhargavgb : Did you intend to report any issue with the referenced page?

**Comment by illfated** [comment]
#please-close
