### ISSUE TITLE
SCM is now retired

### ISSUE THREAD

**Issue by TrixM** [MicrosoftDocs/windowsserverdocs#482]
Should now state Security Compliance Toolkit is recommended for 2016/Windows 10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4762d9fe-e510-df71-a718-aa0d018db38f
* Version Independent ID: fc2f30ef-e71d-5167-6d41-7abadbc2892a
* Content: [Securing Domain Controllers Against Attack](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/securing-domain-controllers-against-attack)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Securing-Domain-Controllers-Against-Attack.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Securing-Domain-Controllers-Against-Attack.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by MicrosoftGuyJFlo** [comment]
Resolving in private repo branch GitHubIssues072018

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
