### ISSUE TITLE
Hyper-V enhanced mode grey out

### ISSUE THREAD

**Issue by MelissaPang** [MicrosoftDocs/windowsserverdocs#4821]
[Enter feedback here]
 I have turn it on in the Server setting "Enhanced Session Mode Policy" and User setting "Enhanced Session Mode" and checked the VM setting -> Integration Services -> Guest services. And restart the laptop and VM a couple times to make sure these configurations are applied. But the enhanced mode is still grey out. Why is that and how to fix? I have a Windows 10 Pro for the service and ubuntu 20 (the most recent one) for the the VM. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55dae836-2730-7a91-b162-cd154557d0fd
* Version Independent ID: 69c4c00c-f3e6-9710-28fe-6ecdc7731c65
* Content: [Use local resources on Hyper-V virtual machine with VMConnect](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/learn-more/use-local-resources-on-hyper-v-virtual-machine-with-vmconnect)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/learn-more/Use-local-resources-on-Hyper-V-virtual-machine-with-VMConnect.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/learn-more/Use-local-resources-on-Hyper-V-virtual-machine-with-VMConnect.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by Xelu86** [comment]
Hey MelissaPang,

Thanks again for contacting Microsoft. We value your feedback.

What you're describing is discussed in a different article found at:

- https://learn.microsoft.com/en-us/virtualization/community/team-blog/2018/20180228-sneak-peek-taking-a-spin-with-enhanced-linux-vms
- https://github.com/Microsoft/linux-vm-tools/wiki/Onboarding:-Ubuntu

In another repo, there is an article that describes the "**Quick Create**" feature in Hyper-V:

- https://learn.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/custom-gallery

The Quick Create feature should have a custom LIS and XRDP built-in for an Enhanced Session with the latest 22.04:

![image](https://github.com/MicrosoftDocs/windowsserverdocs/assets/103963494/33d8b355-f0e8-4fa8-9a68-a06a39b67a3d)

Once you complete the OS installation and reboot the system, XRDP should engage, and Enhanced Session should be enabled.

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
