### ISSUE TITLE
Security Configuration Wizard removed from server 2016

### ISSUE THREAD

**Issue by jmadunleavy** [MicrosoftDocs/windowsserverdocs#4822]
[Enter feedback here]
Security Configuration Wizard was removed from Server 2016 according to this document.  
https://docs.microsoft.com/en-us/windows-server/get-started/deprecated-features

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca929d6b-746d-f20a-8902-4e93a69ab8d8
* Version Independent ID: 88e13a93-f80b-d07b-cfaa-ab38205148e0
* Content: [Securing Domain Controllers Against Attack](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/securing-domain-controllers-against-attack#physical-domain-controllers)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Securing-Domain-Controllers-Against-Attack.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Securing-Domain-Controllers-Against-Attack.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by PatAltimore** [comment]
Hi @jmadunleavy,

Thanks for the feedback. I removed the Security Configuration Wizard reference. The change will publish soon.

Thanks,
Pat

#please-close
