### ISSUE TITLE
Typo - Toogle -> Toggle

### ISSUE THREAD

**Issue by meverettglobal9287497** [MicrosoftDocs/windowsserverdocs#4826]
Under the section titled "Managed Deployment using Intune"  Step 4 has a typo of "toogle" that should be the word "toggle".

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfa69a96-b69c-4175-80b5-b5ca227a7b86
* Version Independent ID: be5e50f6-d123-5fe3-5d88-f28f9fc2beb1
* Content: [Create OMA-DM based VPNv2 Profiles to Windows 10 devices](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/vpn-create-oma-dm-based-vpnv2-profiles)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/vpn-create-oma-dm-based-vpnv2-profiles.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/vpn-create-oma-dm-based-vpnv2-profiles.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by illfated** [comment]
Nice catch, thanks. Will fix.

**Comment by illfated** [comment]
By the way, have you noticed anything else on the page in need of fixing or simply adjusting to look more correct?

**Comment by meverettglobal9287497** [comment]
All I saw was that typo.  The rest is fine and is in line with all the other articles in that area.  Just figured I would send in a note about the typo.


Matthew Everett  |  Senior Network Technician  |  Global Aerospace Inc.
One Sylvan Way, Parsippany, NJ, 07054
+1 (973) 490 8673 (w)  |  +1 (973) 997-6232 (m)   |  www.global-aero.com

Follow us on:    LinkedIn <https://www.linkedin.com/company/global-aerospace?trk=company_logo>   |  Twitter <https://twitter.com/GlobalAerospace>

Latest News: Get the tools and insights you need for professional development through the SM4 Online Learning Management System - Learn More<https://sm4.global-aero.com/community-of-excellence/level-2-lms/>

**Comment by illfated** [comment]
Thank you for the useful feedback and your initial report post.

The issue will be resolved by the Pull Request #4828 , which will also close this ticket automatically.
