### ISSUE TITLE
This Was Not A Permanent Fix

### ISSUE THREAD

**Issue by KIRKULEES** [MicrosoftDocs/windowsserverdocs#4829]
I followed the directions outlined in this article and it does work to change the command processor window, but when I closed it down and opened it back up it was back to baby blue (the original color I wanted to change).  My real problem is that I changed the color to baby blue awhile back and forgot how I did it.  I never planned to leave it that way, it was just something I learned to do one day and was playing around with.

Anyway, everywhere I searched I found the same solution that you have outlined here.  I tried both properties and Default but always had the same result.  When I shut it down and re-opened it, it was always back to baby blue.  Then on How-to-Geek's page about changing cmd colors, I actually read what it said inside their example picture of Command Processor.  There, for the first time, I seen the words "DefaultColor registry" and that lead me to my breakthrough. 

-	I GOOGLED “CHANGE DEFAULT COLOR REGISTERY VALUE”.  (I SPELLED REGISTRY WRONG)

**That took me to this page:**
 https://www.google.com/search?client=opera-gx&q=CHANGE+DEFAULT+COLOR+REGISTERY+VALUE&sourceid=opera&ie=UTF-8&oe=UTF-8

Web results
Showing results for CHANGE DEFAULT COLOR REGISTRY VALUE
Search instead for CHANGE DEFAULT COLOR REGISTERY VALUE

-	I SELECT THE FIRST CHOICE ON THIS PAGE:

**That took me to this page:**
https://www2.isye.gatech.edu/~mgoetsch/cali/Windows%20Configuration/Windows%20Configuration%20Html/SettingtheDefaultColorfortheCommandProcessor_WindowsNTonly_.htm

Setting the Default Color for the Command Processor ...
Setting the Default Color for the Command Processor (Windows NT only) ... the default colors in the command processor windows by editing the Registry directly ...

WHICH IS THE PAGE WHERE I LEARNED HOW TO FIX THE COLOR OF MY CMD WINDOW PERMANENTLY.
 
THIS INFORMATION WAS SO PERFECT I WANTED TO SEE WHAT ELSE I COULD LEARN BUT THERE WAS ONLY 3 SMALL ICONS IN THE TOP LEFT.  ONE TOOK ME TO A CONTENTS PAGE THE OTHER TWO WERE FORWARD AND BACK ARROWS.  BY THE LOOK OF THE CONTENTS PAGE I CAN LEARN A GREAT DEAL FROM THIS INFORMATION WHEREVER IT CAME FROM.  I ONLY WISH I COULD THANK THE PUBLISHER.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 959d4b23-8fd3-0404-f2b3-9397fbe9dce2
* Version Independent ID: e860e4fa-0075-7df0-0780-cb4f2c86ced3
* Content: [color](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/color)
* Content Source: [WindowsServerDocs/administration/windows-commands/color.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/color.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
Please note that CMD windows have 2 sets of properties:
- **Defaults**
- **Properties**

***

![image](https://user-images.githubusercontent.com/38162891/93587959-fa75c480-f9aa-11ea-905a-993771a3fc9a.png)

***

![image](https://user-images.githubusercontent.com/38162891/93588158-458fd780-f9ab-11ea-8183-7001668b847a.png)

***

![image](https://user-images.githubusercontent.com/38162891/93588234-66582d00-f9ab-11ea-838f-8c7a5e514ab3.png)

**Comment by illfated** [comment]
1. You did not spell "registry" wrong. The person responsible for that page you found to be most helpful to you does probably not have English as their native language, making it more likely that typos and misspellings happen more frequently on non-official pages than official pages (I know, official pages get misspellings too, although a bit less frequent).

2. Microsoft Docs is not going to adapt material from the outside, unless the source belongs to a well-known Microsoft Partner or affiliated organization.

3. Please don't use ALL CAPS when posting friendly information. It tends to come across as less friendly or shouting.

4. Unless you can point to some factual errors on the page, it is highly unlikely that your research to solve a singular issue for yourself can be used as basis for documentation change. Most IT Pro admins are fully aware of how to solve this issue. This documentation site is also intended for IT Pros, not so much for the general public non-professional internet audience as such.

**Comment by illfated** [comment]
#please-close

**Comment by KIRKULEES** [comment]
I apologize for the all caps.  I am dyslexia and it helps me to read what I
type, which is also why I've made a habit of taking the blame when it comes
to spelling discrepancies.  I had also tried both of these, "Default" and
"Properties" but still when I re-opened cmd the color reverted to baby blue
with black text.  This is a lovely point for point outline of how I somehow
was out of my league when I posted a solution that worked, but my question
is this.  If you are all so intelligent that this is something you all
automatically know how to do, why did I need to go to another website to
find a solution that worked for me?  I won't bother your website ever
again.  I prefer to stick to sites that have solutions to problems, not
just the ones that tell me how a computer is supposed to work.  Thanks for
telling me how smart you are though.  Here's a video you should check out.
https://www.youtube.com/watch?v=GJz66wm95-M
