### ISSUE TITLE
Broken link in "See Also" section

### ISSUE THREAD

**Issue by jrochet** [MicrosoftDocs/windowsserverdocs#483]
This link - "Configure a federation server with Device Registration Service" - is broken.  It points to - "assetid:///007016d9-b1c9-4ee1-a30f-13865f784c80" - and that seems to go nowhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2646147-59ef-ae02-9923-742f1fd58508
* Version Independent ID: bba6f1ff-468f-f23c-f419-eba95096e131
* Content: [Join to Workplace from Any Device for SSO and Seamless Second Factor Authentication Across Company Applications](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/join-to-workplace-from-any-device-for-sso-and-seamless-second-factor-authentication-across-company-applications)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Join-to-Workplace-from-Any-Device-for-SSO-and-Seamless-Second-Factor-Authentication-Across-Company-Applications.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Join-to-Workplace-from-Any-Device-for-SSO-and-Seamless-Second-Factor-Authentication-Across-Company-Applications.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by lizap** [comment]
Goo d catch - thanks! I've updated the source - you should see the fix by tomorrow morning, at which time I'll close this issue.
