### ISSUE TITLE
Not able to download 1.2.1275

### ISSUE THREAD

**Issue by wimkestens** [MicrosoftDocs/windowsserverdocs#4831]
Links doesn't work, other versions are ok.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f43e914-5ede-6f18-2fbc-165f3386f7cb
* Version Independent ID: a9489295-572d-ff60-6bff-a44390ac4031
* Content: [What's new in the Windows Desktop client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop-whatsnew)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop-whatsnew.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop-whatsnew.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by illfated** [comment]
(ref. duplicate ticket #4830 (to be closed))

**Comment by illfated** [comment]
The reported defective links can be found in this section:

***

## Updates for version 1.2.1275

*Date published: 08/25/2020*

Download: [Windows 64-bit](https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE4FpYR), [Windows 32-bit](https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE4FpYS), [Windows ARM64](https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE4Fg3H)

- Added functionality to auto-detect sovereign clouds from the user’s identity.
- Added functionality to enable custom URL subscriptions for all users.
- Fixed an issue with app pinning on the feed taskbar.
- Fixed a crash when subscribing with URL.
- Improved experience when dragging remote app windows with touch or pen.
- Fixed an issue with localization.

***

Uncommon links:
- https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE4FpYR (Windows 64-bit)
- https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE4FpYS (Windows 32-bit)
- https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE4Fg3H (Windows ARM64)

Output from trying to access the current links:

{"Code":"DocumentNotFound","Message":"StorageDocumentNotFoundException : Could not find document with id 'RE4FpYR', tenant 'am'. ","Resource":null}
{"Code":"DocumentNotFound","Message":"StorageDocumentNotFoundException : Could not find document with id 'RE4FpYS', tenant 'am'. ","Resource":null}
{"Code":"DocumentNotFound","Message":"StorageDocumentNotFoundException : Could not find document with id 'RE4Fg3H', tenant 'am'. ","Resource":null}

***

Latest changes to those links were made in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/ba6a485975fdff647505f633542f390163078a85 by @Heidilohr .

The links from before the change are still working:

**Download:**
- https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE4D7LK (Windows 64-bit)
- https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE4D5aF (Windows 32-bit)
- https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE4Dan3 (Windows ARM64)

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey wimkestens,

Thanks for contacting Microsoft. We value your feedback.

Based on the time this issue was generated, the link was updated and this issue was not closed. Verified download link to latest version 1.2.4487 is functional. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
