### ISSUE TITLE
Missing email

### ISSUE THREAD

**Issue by MarineM310** [MicrosoftDocs/windowsserverdocs#4833]
the email address of "sdn_feedback@microsoft.com" was not found, when sending a message the email route

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b581b541-9b0b-06e2-fb89-7af5f7a7d800
* Version Independent ID: 3ac4461b-b5f3-477a-f0d1-612bf142168a
* Content: [Contact the Datacenter and Cloud Networking Team](https://docs.microsoft.com/en-us/windows-server/networking/sdn/contact-sdn-team)
* Content Source: [WindowsServerDocs/networking/sdn/contact-sdn-team.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/sdn/contact-sdn-team.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @AnirbanPaul
* Microsoft Alias: **anpaul**

**Comment by doctordns** [comment]
I can verify that this email addresses bounces as so very similar addresses. For what it's worth, I tweeted to the team and got a response that by filing this issue, someone at the team would see it.  Eventually. I'll re-ping the team with this URL and hopefully, someone will action this issue.

**Comment by AnirbanPaul** [comment]
I have created another alias with the same name. Should get created in a day.

**Comment by doctordns** [comment]
The email address now works - this issue can be closed!

Thanks!

**Comment by illfated** [comment]
Very well, thank you for confirming that it has been resolved. 👍

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
