### ISSUE TITLE
KB4490481 in cumulative update

### ISSUE THREAD

**Issue by senravh** [MicrosoftDocs/windowsserverdocs#4835]
Are all the KB references in the "know issues" section inlcuded in the lastest cumulative update KB4577069? spesifically interested in KB4490481 that is related to backup priviliges
Migratting from a Win2003 to a win2019 fileserver and I am not able to sync files where the NTFS rights are tight(SYSTEM=full controll, User1 or group1=full controll, Owner=unknown).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f348eda3-6195-cd36-9bf9-769b6c37927b
* Version Independent ID: a2255385-394e-7ee0-a90d-dcaca017a3d4
* Content: [Storage Migration Service known issues](https://docs.microsoft.com/en-us/windows-server/storage/storage-migration-service/known-issues)
* Content Source: [WindowsServerDocs/storage/storage-migration-service/known-issues.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-migration-service/known-issues.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @nedpyle
* Microsoft Alias: **nedpyle**

**Comment by nedpyle** [comment]
Hi. Yes, that KB rolls up anything previous and we haven't heard of your issue. I recommend opening a support case to investigate - if it turns out to be a bug, there will be no charge for the case.

**Comment by senravh** [comment]
Thx for feedback. Will investigate the configuration and see if I have missed something before reporting a bug.

**Comment by sanglyb** [comment]
We have the same issue, installed all updates to our 2019 servers and files cannot be copied if there are no permittions for file...
