### ISSUE TITLE
wevtutil documentation does not list /rf and /mf and /pf parameters

### ISSUE THREAD

**Issue by adamwalling** [MicrosoftDocs/windowsserverdocs#4836]
wevtutil documentation does not list /rf and /mf and /pf parameters which are in wevtutil im /?

Options:

You can use either the short (for example, /rf) or long (for example,
/resourceFilePath) version of the option names. Options and their values are not
case-sensitive.

/{rf | resourceFilePath}:VALUE
ResourceFileName attribute of the Provider Element in the manifest to be
replaced.
The VALUE should be the full path to the resource file.

/{mf | messageFilePath}:VALUE
MessageFileName attribute of the Provider Element in the manifest to be replaced.
The VALUE should be the full path to the message file.

/{pf | parameterFilePath}:VALUE
ParameterFileName attribute of the Provider Element in the manifest to be replaced.
The VALUE should be the full path to the parameter file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac36ce81-c27b-9390-0046-40fce407d810
* Version Independent ID: 654871b9-01cf-f163-e03b-c1361609713f
* Content: [wevtutil](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/wevtutil)
* Content Source: [WindowsServerDocs/administration/windows-commands/wevtutil.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/wevtutil.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @adamwalling,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding the 3 sub-parameters for the `/im` switch and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
