### ISSUE TITLE
Where are the images that supposed to be within this article?

### ISSUE THREAD

**Issue by muhsashi** [MicrosoftDocs/windowsserverdocs#4837]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94dc8d96-147f-27ea-2ba8-9a346fa63d55
* Version Independent ID: ac53f9d9-629b-9a95-6fd9-790b9fa9572f
* Content: [Plan Your WSUS Deployment](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/plan/plan-your-wsus-deployment)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/plan/plan-your-wsus-deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/plan/plan-your-wsus-deployment.md)
* Product: **windows-server**
* Technology: **wsus**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by eross-msft** [comment]
@muhsashi  Thank you for taking the time to add this item. I'm hoping you can clarify. This isn't actually my article, but doing a quick pass of both the online and the underlying markdown text, I'm not seeing any broken image links. In fact, I'm not seeing calls to any images at all. Can you tell me where the missing images are located in the content? Thanks!!

**Comment by illfated** [comment]
I believe the OP is referring to at least these 2 sections/paragraphs, where both of them end with a sentence like the following:

> **The following image shows how you might deploy** [ ... ]

#### Autonomous mode
The Autonomous mode, also called distributed administration, is the default installation option for WSUS. In Autonomous mode, an upstream WSUS server shares updates with downstream servers during synchronization. Downstream WSUS servers are administered separately, and they do not receive update approval status or computer group information from the upstream server. By using the distributed management model, each WSUS server administrator selects update languages, creates computer groups, assigns computers to groups, tests and approves updates, and makes sure that the correct updates are installed to the appropriate computer groups. The following image shows how you might deploy autonomous WSUS servers in a branch office environment:

#### Replica mode
The Replica mode, also called centralized administration, works by having an upstream WSUS server that shares updates, approval status, and computer groups with downstream servers. Replica servers inherit update approvals and are not administered separately from the upstream WSUS server. The following image shows how you might deploy replica WSUS servers in a branch office environment.

***

I tried searching for the words "figure" and "graph" as well, just in case, but could not find anything obvious to point out.

**Comment by illfated** [comment]
Curiously enough, there is no folder named /images/ (or /media/ for that matter) , neither in the same folder as the referenced document, nor the parent folder, nor any of the parallel folders. There is a media folder named https://github.com/MicrosoftDocs/windowsserverdocs/tree/master/WindowsServerDocs/administration/media/wsus , but that one contains only 3 not quite related icons.

**Comment by eross-msft** [comment]
@illfated @muhsashi  I now see where you're talking about in the text, thank you for pointing that out. It doesn't appear that any images were ever removed...I'm guessing that the original writer had plans to add images and then got sidetracked before they actually did it. To avoid future confusion, I'm going to pull out those sentences.

**Comment by illfated** [comment]
Thank you for the informative feedback. Yes, it does look like there was an intention to add images, but that never happened. Oh well. For all I know, adding images to this article might end up being so late that the WSUS documentation becomes close to obsolete.

**Comment by muhsashi** [comment]
Hai, thank you for resolving this.

Greetz
Matthijs Vossen.

Op wo 23 sep. 2020 18:17 schreef Trond B. Krokli <notifications@github.com>:
