### ISSUE TITLE
THis information is not working on 2019 version

### ISSUE THREAD

**Issue by olgabeat** [MicrosoftDocs/windowsserverdocs#4840]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5238c11b-240b-ff1c-42f1-8381048912f9
* Version Independent ID: 98ec3637-8be0-5500-8b8d-cf1062c3271d
* Content: [Add an RD Connection Broker server to configure high availability in RDS](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-connection-broker-cluster)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-connection-broker-cluster.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-connection-broker-cluster.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
@olgabeat : Thank you for your feedback. Could you add some more information, so we know what kind of issues to look for in this article?

**Comment by illfated** [comment]
This attempt to report an issue in the referenced article page, [Add an RD Connection Broker server to configure high availability in RDS](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-connection-broker-cluster), seems to be related to 2 other tickets:
- https://github.com/MicrosoftDocs/windowsserverdocs/issues/4080 (**Suggestion from customer on the Connection string**)
- https://github.com/MicrosoftDocs/windowsserverdocs/issues/4455 (**Wrong name used for ODBC Driver**)

To resolve this issue ticket along with the other two, we need to make a Pull Request to ask for the change suggested in ticket #4455 .

**Comment by illfated** [comment]
PR #4974 is now ready for review. Feel free to browse, comment, or suggest changes.
