### ISSUE TITLE
TLS Registry Keys and Example

### ISSUE THREAD

**Issue by 1spgardiner** [MicrosoftDocs/windowsserverdocs#4846]
You mention to disable the keys set to 0 (diagrams) for TLS 1.1 and 1.2, yet the notes say set to 0 for Default and Disabledbydesign to 1.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd180142-4c19-8abc-ecce-e4c7e5ac8951
* Version Independent ID: fc5bba87-afad-1729-8f7e-333c73188b73
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @1spgardiner,

Thanks again for contacting Microsoft. We value your feedback. A documentation change has been made surrounding the image examples and will be live after the next business day. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
