### ISSUE TITLE
Needs to address remote access to a home computer

### ISSUE THREAD

**Issue by Greengecko19** [MicrosoftDocs/windowsserverdocs#485]
This article is linked from a Windows 10 Settings dialog box, where it says, "Why allow connections only with Network Level Access?".  So it should include an explanation that this option should not be checked for a computer on home network, if the person wants to connect remotely from a location outside of their home (and off their home network).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71cfbf1a-c5b7-df0f-8194-6ebc03afcc7d
* Version Independent ID: f36b567f-aa48-2c8f-4908-b1fe18cd2842
* Content: [Remote Desktop - Allow access to your PC](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-allow-access#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-allow-access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-allow-access.md)
* Service: **unspecified**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by hoangzaza11** [comment]
i love PC

**Comment by lizap** [comment]
Hi, the article's been updated to be more clear, using the specific example you called out. Thanks for your help!

**Comment by ahumeniy** [comment]
Am I missing something here? I have connected to my computers at home for years over the Internet having the NLA option enabled (because it's the default) without any issues except maybe the fact that I needed to setup a Remote Desktop Gateway to connect from corporate networks blocking RDP connections
