### ISSUE TITLE
Add Server 2019 to Supported Benefit

### ISSUE THREAD

**Issue by cconrado** [MicrosoftDocs/windowsserverdocs#4852]
Hi There,
Just checking that isn't Server 2019 supposed to be included in this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90e335dd-0bc5-a7e3-650b-e3dd1823176b
* Version Independent ID: 18f34ef3-ff61-0473-a64b-ac5a64dbe1d7
* Content: [Azure Hybrid Benefit for Windows Server](https://docs.microsoft.com/en-us/windows-server/get-started/azure-hybrid-benefit)
* Content Source: [WindowsServerDocs/get-started/azure-hybrid-benefit.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/azure-hybrid-benefit.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @eross-msft
* Microsoft Alias: **chrisrin**

**Comment by dknappettmsft** [comment]
Thanks for the feedback. The article has been updated to remove listed versions.

#please-close
