### ISSUE TITLE
Does not explain how to ensure keys get reloaded to agent on boot

### ISSUE THREAD

**Issue by g24swint** [MicrosoftDocs/windowsserverdocs#4858]
What is missing from this page is how to set it up so that keys automatically get loaded when the machine boots. Also, it would be good to explain how this ssh-agent interacts with any ssh-agents running in a WSL instance
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH key management for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by robinharwood** [comment]
Hi @g24swint 

Thanks for your dedication to our documentation. We've submitted a documentation change to update the code examples, setting the ssh-agent to automatic based on your suggestion, the updated article should be live by tomorrow.

With regard to WSL, WSL can be side-by-side but each environment would be separate from each other as they are separate instances.

#please-close
