### ISSUE TITLE
Event Viewer Path Incorrect

### ISSUE THREAD

**Issue by jakemm** [MicrosoftDocs/windowsserverdocs#486]
Path in the document 'Applications and Services Logs\Microsoft\Windows\Microsoft\Authentication'
Actual path 'Applications and Services Logs\Microsoft\Windows\Authentication'

**Comment by illfated** [comment]
Using the GitHub search feature, I can confirm that are no documents belonging to this repository containing the reported incorrect path, only the correct path.

I believe this issue has been resolved via a different ticket.

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
