### ISSUE TITLE
Ubuntu 20.04 should be Focal not Disco

### ISSUE THREAD

**Issue by fgggid** [MicrosoftDocs/windowsserverdocs#4866]
Is it right? In the page, it says 'Ubuntu 20.04 (Disco)'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25943cc5-9927-5ca7-b9db-4c1d398726c5
* Version Independent ID: ae5bf48b-26cf-b5c8-22c8-68fa9a70258f
* Content: [Linux Software Repository for Microsoft Products](https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software)
* Content Source: [WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @victorcheng7
* Microsoft Alias: **vichen**

**Comment by illfated** [comment]
That looks like a misunderstanding, muddle-up or copy-paste typo.

Ubuntu 20.04.1 LTS (Focal Fossa):
- http://releases.ubuntu.com/focal/
- https://wiki.ubuntu.com/FocalFossa/

Ubuntu 19.04 (Disco Dingo):
- http://old-releases.ubuntu.com/releases/disco/
- https://wiki.ubuntu.com/DiscoDingo

I will open a Pull Request to have a correction merged into the article.
