### ISSUE TITLE
Wrong UA string information for Microsoft Edge

### ISSUE THREAD

**Issue by apmpinho** [MicrosoftDocs/windowsserverdocs#4867]
[Enter feedback here]

Hi there,

I'm an escalation engineer in the CSS Browsers team and we keep see cases related with this article, namely that the new Edge browser is not authenticating properly with ADFS. This article contains wrong information:

- We shouldn't need to specify actual browser version, like, _Edg/79.0.309.43_, since Microsoft Edge is not OS-version dependent
- This is not correct, as it will not catch Microsoft Edge's UA string

![image](https://user-images.githubusercontent.com/72249906/94902377-f8723200-048f-11eb-953c-1b6ea6404578.png)

This is a classic Edge UA string for your review:

User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 **_Edg/85.0.564.63_**

Let me know if you need more details or if I'm not seeing this correctly.
Thanks!

António

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd7eb3f6-c00a-453f-a596-6f8bde452cb7
* Version Independent ID: 3250a24b-8e71-a36c-a9a0-7c46bc36acd4
* Content: [Configure browsers to use Windows Integrated Authentication (WIA) with AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-browser-wia#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Browser-WIA.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Browser-WIA.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by apmpinho** [comment]
Any updates here? Is there a better way to have this content reviewed and updated?

**Comment by illfated** [comment]
Thank you for your report. This will be looked into. Please be patient with the process.

If this information is shown to be incorrect elsewhere, like if there are other pages (preferably other Microsoft sites), please also provide the links. I will do my best to find the information, but every extra piece of information to prove this document incorrect is appreciated.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub. I don't know the topic well enough to know that your information is correct.

**Comment by illfated** [comment]
Ref. official **Release notes for Microsoft Edge Stable Channel**:
- https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel

Looking at the table in https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-browser-wia#change-wiasupporteduseragent-settings , how can we use this information?

**Comment by illfated** [comment]
Maybe we could find something useful within these search results:
- https://www.bing.com/search?q=%22Set-AdfsProperties+-WIASupportedUserAgents%22+site%3Amicrosoft.com

**Comment by illfated** [comment]
See also:
- https://social.technet.microsoft.com/Forums/en-US/016ef05d-de46-4588-9de2-e634c205af0b/newer-version-of-chrome-not-working-for-ssoadfs-30?forum=ADFS
- https://www.whatismybrowser.com/detect/what-is-my-user-agent
- https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes
- https://developers.whatismybrowser.com/useragents/explore/

**Comment by illfated** [comment]
(ref. PR #5098 )

**Comment by rotraves-microsoft** [comment]
Thanks for reporting this Pinho. I just submitted a change on the document correcting the command line.

**Comment by apmpinho** [comment]
Thanks Rodrigo, appreciate that 👍

**Comment by illfated** [comment]
Can we conclude that the issue is resolved now, via referenced PR #5098 ?

**Comment by illfated** [comment]
#please-close
