### ISSUE TITLE
Where to place a Federation Service - Best Practive description is confusing 

### ISSUE THREAD

**Issue by rhmeyering-vw** [MicrosoftDocs/windowsserverdocs#4868]
[Enter feedback here]
https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/design/plan-your-ad-fs-deployment-topology 
As a security best practice, place AD FS federation servers **in front of a firewall** and connect them to your corporate network to prevent exposure from the Internet.

I think you mean behind a Corporate Firewall!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edc29383-bec8-c02f-3b53-06e1ee07ffd2
* Version Independent ID: 0d50c96d-faaf-b4dd-cae2-dc32d1e5fcad
* Content: [Plan Your AD FS Deployment Topology](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/design/plan-your-ad-fs-deployment-topology)
* Content Source: [WindowsServerDocs/identity/ad-fs/design/Plan-Your-AD-FS-Deployment-Topology.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/design/Plan-Your-AD-FS-Deployment-Topology.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @rhmeyering-vw,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting this and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
