### ISSUE TITLE
Private keys from the ssh-agent can be accessed

### ISSUE THREAD

**Issue by stefanfritsch** [MicrosoftDocs/windowsserverdocs#4871]
Hi,

I believe the article contains false information:

> It is strongly recommended that you back up your private key to a secure location, then delete it from the local system, after adding it to ssh-agent. **The private key cannot be retrieved from the agent.** If you lose access to the private key, you would have to create a new key pair and update the public key on all systems you interact with.

[This](https://blog.ropnop.com/extracting-ssh-private-keys-from-windows-10-ssh-agent/) link shows that any process running as your user can access the private key and actually retrieve it unencrypted.

Feel free to correct me, if I'm wrong.

Regards,
Stefan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH key management for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by dknappettmsft** [comment]
Thanks for submitting this issue @stefanfritsch. I have clarified the part you highlighted and alluded to it earlier on in the article too.

The link you provided is valid for keys using the RSA algorithm that are no higher than 2048-bit. The example in the document refers to Ed25519 for which your link doesn't work. However the ssh-keygen command as presented did not use Ed25519, so I've updated the article to reflect that.

The changes should be visible in a few hours.

#please-close
