### ISSUE TITLE
Formatting issue for the JBOD example.

### ISSUE THREAD

**Issue by Absoblogginlutely** [MicrosoftDocs/windowsserverdocs#4873]
The formatting for the jbod enclosure "To determine whether the JBOD enclosure supports enclosure and slot identification, run the following Windows PowerShell cmdlet:" shows the backslash that is being used to escape the pipe symbol which is required for the markdown page however also gets rendered on the docs.microsoft.com site. However attempting to edit the document in Github, removing the backslashes  and viewing the example preview shows the text showing in the next table field.
I'm not familiar enough with markdown to edit the document correctly so the powershell code shows up properly. Using the powershell code from the other examples makes it show up on a new line breaking the table as in the screenshot below.
![Screenshot - 20201002-071517](https://user-images.githubusercontent.com/21364480/94990051-19498e80-0547-11eb-869c-00963bd38321.png)
 Any ideas?
--
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5eff1fc-f935-23b3-6165-914061f81334
* Version Independent ID: 6689ae37-f31e-ec5d-f964-5695a5a6dc14
* Content: [Deploy Storage Spaces on a stand-alone server](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/deploy-standalone-storage-spaces)
* Content Source: [WindowsServerDocs/storage/storage-spaces/deploy-standalone-storage-spaces.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/deploy-standalone-storage-spaces.md)
* Product: **windows-server**
* Technology: **storage-spaces**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Fair question. I usually encapsulate commands using MarkDown backticks **``** (1 before and 1 after the code in question) to avoid the issue of having to use any escape characters for special characters like vertical pipe, Greater Than, and Less Than characters, as well as asterisks (wildcards).

Looking at the page in question, I notice that the cmdlet seems to be encapsulated in backticks already, so I will have a look at the GitHub version of the page and see if it is only a question of removing the unneeded escape characters.

**Comment by illfated** [comment]
By the way: I am not very familiar with the topic, at least not using this information on a daily basis, so I would think that the last sentence in that cell could fit better in the directly following **Notes** cell instead:

"If the **EnclosureNumber** and **SlotNumber** fields contain values, then the enclosure supports these features."

Do you agree, or do you find that it belongs where it currently is placed?

**Comment by illfated** [comment]
Funny thing is, the rich diff view here on GitHub seems to hide the escape character, but fortunately not in the raw view:
- https://raw.githubusercontent.com/MicrosoftDocs/windowsserverdocs/master/WindowsServerDocs/storage/storage-spaces/deploy-standalone-storage-spaces.md
