### ISSUE TITLE
Channels Chart

### ISSUE THREAD

**Issue by mslicensing** [MicrosoftDocs/windowsserverdocs#488]
The chart could be confusing because the # of devices row is not a very adaptable metric and this will result in strange outcomes. It appears to be using the number of desktop devices, since the 500 in the EA column is the minimum for an EA. But someone looking at this chart, which is, after all about servers, not desktops, may conclude that the hybrid use benefit isn't economical in an EA until you have 500 Servers. And it would really weird for someone to buy 250 Windows Servers with SA in Open. For example, I could buy fewer than 10 Windows server licenses with SA in the MPSA if I paid LSA all up front to get the 500 points I need for an A discount. Your number of 250 would nearly get me a C discount in the MPSA, way below the open price.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64ecde30-6c97-9426-978c-df2f018a88b8
* Version Independent ID: 46c06b02-9514-d7e4-90a1-3f2c8cae481f
* Content: [Azure Hybrid Benefit for Windows Server](https://docs.microsoft.com/en-us/windows-server/get-started/azure-hybrid-benefit)
* Content Source: [WindowsServerDocs/get-started/azure-hybrid-benefit.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/azure-hybrid-benefit.md)
* Service: **unspecified**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by illfated** [comment]
Other tickets originating from the same page:

***

**Possible outdated content**
#4713 opened on Aug 10 by jks05c

**Logic Error in License Calculator Spreadsheet**
#4447 opened on Jun 4 by waclark57

**Example 3 is incorrect**
#4415 opened on May 28 by Tsirke

**Wrong values**
#3981 opened on Mar 5 by MiguelCaldasMS

**Updates to Server Versions**
#3926 opened on Feb 20 by jantoney

***

Could be useful to know, in case any of those other tickets touch upon closely related material in the doc page.

**Comment by IngridAtMicrosoft** [comment]
#please-close
