### ISSUE TITLE
Windows 10 Build 1809 Automatic Updates GPO ignored

### ISSUE THREAD

**Issue by deucalion** [MicrosoftDocs/windowsserverdocs#4883]
Please update your documentation accordingly: on Windows 10 build 1809 the setting "Automatic Updates - deactivated" is ignored. Updates are downloaded anyway, despite the documentation suggesting otherwise. (At the moment, the documentation misleads the reader to think this setting overrides any other settings for automatic update installation. Which appears to be WRONG.)

Its mitigation caused a significant strain and workload in my department, which given current times is less than welcome.

Please fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d9a7aaf-447d-a2dd-d7f6-828f277a00ea
* Version Independent ID: c3dd7389-454f-870d-5502-46544d6336dc
* Content: [Step 4 - Configure Group Policy Settings for Automatic Updates](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/deploy/4-configure-group-policy-settings-for-automatic-updates#configure-automatic-updates)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/deploy/4-configure-group-policy-settings-for-automatic-updates.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/deploy/4-configure-group-policy-settings-for-automatic-updates.md)
* Product: **windows-server**
* Technology: **wsus**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by deucalion** [comment]
... and it appears that the documentation clearly states "Applies to: Windows Server*" and not Windows Desktop/client.

Oh well. Please re-target my (mis-filed) suggestion to add to this page instead: https://docs.microsoft.com/en-us/windows/deployment/update/waas-wu-settings#configure-automatic-updates

My apologies for the sleep-deprived feedback.

**Comment by eross-msft** [comment]
@deucalion  Happens to the best of us...thank you for taking the time to comment :) I'm going to go ahead and close this.
