### ISSUE TITLE
2016 Schema Required? 

### ISSUE THREAD

**Issue by Muleguy** [MicrosoftDocs/windowsserverdocs#489]
Under Schema requirements "New installations of AD FS 2016 require the Active Directory 2016 schema (minimum version 85)." does this imply that only new installations require the 2016 schema and that in place upgrades do not? It seems that this is an odd requirement if the Domain could still be a 2003 or 2008 functional level. If you could clarify it would be appreciated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68bac2aa-024c-a014-eeaf-f28a44b31c5e
* Version Independent ID: 86c83819-91d6-c990-16f1-d05ebdf07b58
* Content: [AD FS 2016 Requirements](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-requirements)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/ad-fs-requirements.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/ad-fs-requirements.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by thibaultchatiron** [comment]
The upgrade of ADFS also needs to have an AD 2016 schema. It is necessary during the step for raising the AD FS farm behavior level (FBL)
For the domain functionnal level, 2003 is the miminum and 2008 in somes cases for compatibility with user certificate

**Comment by ImNotSerious** [comment]
This should be updates to reflect that having a 2016 DC isn’t enough, that you must make a 2016 server the PDC Emulator FSMO holder. That stumped me on why the Key Admins groups weren’t  created. I finally found the answer here:
https://secureidentity.se/adprep-bug-in-windows-server-2016
