### ISSUE TITLE
Screenshot and Registry value are inconsistent

### ISSUE THREAD

**Issue by hkawano** [MicrosoftDocs/windowsserverdocs#4891]
[Enter feedback here] Screenshot and Registry value are inconsistent
text and screenshot provided by MS is conflicting here, right?
 

 
To disable SSL 2.0 by default, create a DisabledByDefault entry and change the DWORD value to 1. If an SSPI app explcitly requests to use SSL 2.0, it may be negotiated.

The following example shows SSL 2.0 disabled in the registry..the example shows value of 0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd180142-4c19-8abc-ecce-e4c7e5ac8951
* Version Independent ID: fc5bba87-afad-1729-8f7e-333c73188b73
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by illfated** [comment]
Maybe you could edit the document directly to change the text to say something similar to

**The following example shows you where to disable SSL 2.0 in the registry.**

**Comment by illfated** [comment]
Oh. Now I see. Please note the following, you need to read the text as follows:

> To disable SSL 2.0 _**by default**_ , create a DisabledByDefault entry and change the DWORD value to 1.

Please Note that "Disabled **By Default**" is not the same as Disabled / Enabled on their own.

**Comment by illfated** [comment]
Notice also the following:

The following example shows SSL 2.0 **disabled** in the registry.

This is not the same as **Disabled By Default** .

**Comment by illfated** [comment]
#please-close
