### ISSUE TITLE
Map empty

### ISSUE THREAD

**Issue by SoftwaregeekNL** [MicrosoftDocs/windowsserverdocs#4892]
[Voer hier feedback in]

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 09ab98fc-fea2-a11a-e5ca-de1430211d97
* Version Independent ID: 4d9943c3-fef7-ca86-bd03-1241a04b8135
* Content: [Get started with the Windows Desktop client](https://docs.microsoft.com/nl-nl/windows-server/remote/remote-desktop-services/clients/windowsdesktop)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by illfated** [comment]
Could you please add some more details about the issue? "Map empty" does not give us enough details to work out what needs to be changed.

**Comment by illfated** [comment]
No reply after more than a month. I consider this a test ticket and choose to close it. Feel free to open a new ticket if you find that there still is a legitimate issue in the referenced document.

**Comment by illfated** [comment]
#please-close
