### ISSUE TITLE
mis-spelled "passwords" in first paragraph

### ISSUE THREAD

**Issue by snotty** [MicrosoftDocs/windowsserverdocs#4897]
mis-spelled "passwords" in first paragraph

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH key management for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by illfated** [comment]
A pair consists of 2 elements: 1 + 1 (or A + B) in their single form, making a pair of 2. This is also valid for English grammar.

Maybe you are thinking of the combined word "credentials"?

I know, it may seem weird, but some American English (en-us) grammatical forms might be different to what is expected in British English documents.

There are a few variants when it comes to presenting the phrase "username and password" in writing:
- Username and password pair
- Username/password pair
- Username + password pair
- Username & password pair
- Username - password pair

If I have misunderstood anything, please advise or specify what you mean.

**Comment by illfated** [comment]
Oh. Sorry. The typo is in the **second** paragraph, not the first. Now I see it. It is misspelled as "passowrds". 😄

Thank you for reporting the typo. I will make sure to have it corrected.

**Comment by illfated** [comment]
There you go. PR #4901 is ready for review. I noticed that I have been through that document several times before, strange that I haven't noticed it. Oh well, "water under the bridge" as they say. 😉

**Comment by illfated** [comment]
Typo source: **Update OpenSSH_KeyManagement.md** #4878 (commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/4802475b9bed46dc891aeecfdf76cc4c5c913a16)
