### ISSUE TITLE
Power Shell Requirements Details

### ISSUE THREAD

**Issue by RandyInMarin** [MicrosoftDocs/windowsserverdocs#4899]
Nothing is said about Power Shell 7, just PowerShell 5.1 or higher.  Does this include PowerShell 7?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a65d64c7-5f3f-e516-c9c9-0f0cebe100fe
* Version Independent ID: 0bff8d8c-c692-b862-a906-483d7430415d
* Content: [Prepare your environment for Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/prepare-environment)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/deploy/prepare-environment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/deploy/prepare-environment.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by robinharwood** [comment]
We hugely appreciate your contribution, feedback, and support to our technical documentation.

We’ve phased out GitHub Issues on this repository as the feedback mechanism for content and have replaced it with a new feedback system. For more information see, [Content User Feedback](https://aka.ms/ContentUserFeedback). As part of this rollout, we are migrating your issue where our team will use your comments to improve the documentation experience. Unfortunately, this does mean you won't be able to access this issue after the migration is complete.

All issues will be migrated by Thursday 29th August 2024.

Once again, thank you for your valuable feedback, we hope you’ll continue to contribute using our new feedback system.
