### ISSUE TITLE
See also links do not works

### ISSUE THREAD

**Issue by Keeper306** [MicrosoftDocs/windowsserverdocs#490]
Hyper-V Network Virtualization Overview
Hyper-V Network Virtualization technical details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8734ca48-427b-c3db-55eb-eed73e3619a5
* Version Independent ID: b33a1045-8334-e2af-7045-0c6ebd7cea92
* Content: [What's New in Hyper-V Network Virtualization in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/networking/sdn/technologies/hyper-v-network-virtualization/whats-new-hyperv-network-virtualization-windows-server#see-also)
* Content Source: [WindowsServerDocs/networking/sdn/technologies/hyper-v-network-virtualization/whats-new-hyperv-network-virtualization-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/sdn/technologies/hyper-v-network-virtualization/whats-new-hyperv-network-virtualization-windows-server.md)
* Service: **unspecified**
* GitHub Login: @jamesmci
* Microsoft Alias: **jamesmci**

**Comment by lizap** [comment]
Thanks for letting us know! I've just fixed the links in the source - you should see them fixed this afternoon, at which point I'll close this issue. THANKS!
