### ISSUE TITLE
Refresh needed

### ISSUE THREAD

**Issue by cchapin2020** [MicrosoftDocs/windowsserverdocs#4906]
[Enter feedback here]
This page should be updated to include Server 2019, and references to 2008r2/2012 should be updated to reflect the current OS versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca929d6b-746d-f20a-8902-4e93a69ab8d8
* Version Independent ID: 88e13a93-f80b-d07b-cfaa-ab38205148e0
* Content: [Securing Domain Controllers Against Attack](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/securing-domain-controllers-against-attack)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Securing-Domain-Controllers-Against-Attack.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Securing-Domain-Controllers-Against-Attack.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by IngridAtMicrosoft** [comment]
#assign:pataltimore

**Comment by PatAltimore** [comment]
Hi @cchapin2020,

Thanks for the feedback. We made an update to remove version specific references. The change publishes today.

Thanks,
Pat

**Comment by PatAltimore** [comment]
Hi @cchapin2020,

Thanks for the feedback. We made an update to remove version specific references. The change publishes today.

**Comment by PatAltimore** [comment]
#please-close
