### ISSUE TITLE
update "Upgrade Domain Controllers to Windows Server 2016" for 2019

### ISSUE THREAD

**Issue by Conan1989** [MicrosoftDocs/windowsserverdocs#4907]
Hi,
Think this should be updated for Server 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 666fb8cb-b1e5-c7b6-6326-cd172a2bf4b2
* Version Independent ID: 3d899ddb-c33f-28e6-3154-af039e28521a
* Content: [Upgrade Domain Controllers to Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/upgrade-domain-controllers)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/upgrade-domain-controllers.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/upgrade-domain-controllers.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by PatAltimore** [comment]
Hi @Conan1989,

Thanks for the feedback. We updated the article to remove future version specifics. The change will publish today.

Thanks,
Pat

#please-close
