### ISSUE TITLE
Your on-premises environment is federated with Azure AD.

### ISSUE THREAD

**Issue by JulienFloris** [MicrosoftDocs/windowsserverdocs#4908]
The _**"Pre-Requisites"**_ state that you need to be **_Federated_** for Azure MFA to work with ADFS. 
But if you Follow all the Step in an Non-Federated(Managed) environment this also works.
Is the Documentation wrong or are there situations that this is Not-supported or functionality would not work?

If this is unsupported it might be an reason for us to move to federated from an managed state. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f333e8cb-c046-ee06-d33d-d7dc8e8af695
* Version Independent ID: 10838695-f60e-42a7-b0e8-eed7820fd333
* Content: [Configure AD FS 2016 and Azure MFA](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by JulienFloris** [comment]
Asked Premier support to follow up on this feedback and the answer is that it is supported in both states (Managed and federated). 
Could the documentation be updated? 
TicketId: 120101322003189

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
