### ISSUE TITLE
Figure 9 image is too tiny.

### ISSUE THREAD

**Issue by Keeper306** [MicrosoftDocs/windowsserverdocs#491]
Figure 9 image is too tiny. Plz upload image with good quality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 219cb131-c2ad-51b2-0bb8-678c1b1b308b
* Version Independent ID: 7726d8df-f346-37cc-306e-8a0c71ca44c3
* Content: [Hyper-V Network Virtualization Technical Details in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/networking/sdn/technologies/hyper-v-network-virtualization/hyperv-network-virtualization-technical-details-windows-server#feedback)
* Content Source: [WindowsServerDocs/networking/sdn/technologies/hyper-v-network-virtualization/hyperv-network-virtualization-technical-details-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/sdn/technologies/hyper-v-network-virtualization/hyperv-network-virtualization-technical-details-windows-server.md)
* Service: **virtual-network**
* GitHub Login: @jamesmci
* Microsoft Alias: **jamesmci**

**Comment by shortpatti** [comment]
@Keeper306 -- I've found the image you mentioned and, you are correct, the image is hard to read.  I am redoing the image and it should be added soon.  👍
