### ISSUE TITLE
Clarify what versions of windows server

### ISSUE THREAD

**Issue by alexknab** [MicrosoftDocs/windowsserverdocs#4910]
What versions of Windows Server does this apply to?   Server 2008 R2 is still in extended support, but I was under the impression that you used dcpromo.exe, vice server manager to decom DCs.    I am not suggesting you update this page for 2008R2 just update what versions these steps apply to.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4db96074-3ebd-a88e-5d1c-fc8e8083c5c5
* Version Independent ID: 0b5d953b-8fce-410f-037e-e81dda94a477
* Content: [Demoting Domain Controllers and Domains (Level 200)](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/demoting-domain-controllers-and-domains--level-200-)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/Demoting-Domain-Controllers-and-Domains--Level-200-.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/Demoting-Domain-Controllers-and-Domains--Level-200-.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by steved0x** [comment]
Closing and reopening as a test of PRMerger automation

**Comment by PatAltimore** [comment]
Hi @alexknab,

Thanks for the feedback. Several articles including this one were updated with *applies to* in this commit: https://github.com/MicrosoftDocs/windowsserverdocs/commit/e057d07062045e3a97715861a3a762434ce23dd9.

I'm going to request closing the issue. #please-close.

Thanks again,
Pat
