### ISSUE TITLE
CA Configuration for non-domain joined computers

### ISSUE THREAD

**Issue by csando** [MicrosoftDocs/windowsserverdocs#4916]
In the first step:

1. On the RRAS server, generate a file called VPNGateway.inf based upon the example certificate policy request provided in Appendix A (section 0) and customize the following entries:

There is no link to Appendix A (section 0) nor any decent way of finding out where that is exactly.

Could use a hyperlink embedded there or some way to find out where Appendix A (section 0) is

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76dd49bb-b86e-f5b7-35b9-a8d246d36fcb
* Version Independent ID: dedfa83f-36d6-f60b-e839-ba382c5a7372
* Content: [Configure the Server Infrastructure](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure#feedback)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by illfated** [comment]
The question about **Appendix A (section 0)** has been raised before, but in a closed issue ticket: #464

There is no such Appendix in the online documentation (or at least not searchable). Other server docs appendices start from the letter B.

**Comment by illfated** [comment]
🤔 https://www.bing.com/search?q=%22Appendix+A+(section+0)%22 (17 Results) 😞

**Comment by csando** [comment]
Hah. The info in question (inf file example) is right below the section I mentioned, it's just not labelled as an appendix so I think a lot of people get confused there. Its comforting to know I'm not the only person who got confused :)

**Comment by illfated** [comment]
😄 👍 Very good, thank you for pointing out that important detail.

Do you have a suggestion for improvement, like an improved phrasing or rewrite of the section in question, so we may resolve the issue for good this time?

**Comment by csando** [comment]
Maybe just replace the text about the appendix to "the example below" or something like that

**Comment by shieldsmicah** [comment]
Seconding this. just spent 10 minutes looking for Appendix A (section 0) until I came across csando's comment above

**Comment by IngridAtMicrosoft** [comment]
Fixed.
