### ISSUE TITLE
Configure DNS before configuring the second domain controller

### ISSUE THREAD

**Issue by K-Dela-R** [MicrosoftDocs/windowsserverdocs#4917]
I just tried this procedure. When promoting the second server, it fails with error message "an active directory domain controller for the domain <testdomain.com> could not be contacted".

The fix is to configure the DNS on the VNet first before configuring the second server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b0097c-668e-1d37-22b0-89d0bf649f8a
* Version Independent ID: 49ccfef6-05bb-9c93-5a05-a2e2fe632b3c
* Content: [Install Active Directory Domain Services on an Azure virtual machine](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by illfated** [comment]
@K-Dela-R : Do you suggest to simply move the [**Configure DNS**](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm#configure-dns) section up before the [**Configure the second Domain Controller**](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm#configure-the-second-domain-controller) section? (see suggestion below)

### Configure DNS

After promoting the new domain controllers in Azure, they will need to be set to the primary and secondary DNS Servers for the virtual network, and any on-premises DNS Servers would be demoted to tertiary and beyond. More information on changing DNS Servers can be found in the article [Create, change, or delete a virtual network](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/azure/virtual-network/manage-virtual-network#change-dns-servers).

### Configure the second Domain Controller

Connect to AZDC02 using the credentials you provided in the script.
.
.
.

**Comment by K-Dela-R** [comment]
That will do. I also suggest to rephrase "After promoting the new domain controllers in Azure..." to say "after promoting the first server..."

**Comment by illfated** [comment]
Looks good. Unless you want to edit the page yourself, I am prepared to do so and create a pull request with the suggested improvement.

**Comment by K-Dela-R** [comment]
Please do so. I have yet to learn how to go about GitHub. Thanks!
