### ISSUE TITLE
Is this document for storage spaces?

### ISSUE THREAD

**Issue by mattu0119** [MicrosoftDocs/windowsserverdocs#492]
I was looking for S2D documentation, but this document explains "Health and operational states" on Storage Spaces .
I would like to konw where this document for S2D is?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a9251ff-772a-a74b-bdf0-81f958b81460
* Version Independent ID: bcf33868-0d5a-8f69-a0f5-03e829289ecc
* Content: [Storage Spaces health and operational states](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/storage-spaces-states)
* Content Source: [WindowsServerDocs/storage/storage-spaces/storage-spaces-states.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/storage-spaces-states.md)
* Service: **unspecified**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by lizap** [comment]
It's for both Storage Spaces Direct and Storage Spaces. Thanks!
