### ISSUE TITLE
SPN: host or http

### ISSUE THREAD

**Issue by aferrillo** [MicrosoftDocs/windowsserverdocs#4922]
Hi,
 when checking my AD FS environment (AD FS 2016) I can only see the **host** SPN. See below:

`PS C:\Users\XXXXXXX> setspn -L ferrillo\adfs_svc`
`Registered ServicePrincipalNames for CN=ADFS_SVC,CN=Users,DC=XXXXXXX,DC=LOCAL:`
`host/sts.XXXXXXX.cloud`
`host/sts.XXXXXXX.local`

 When should I expect to have the **http** and when the **host**?
 Thanks and bye
 alferr@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cae6d9d8-4a22-f41e-a43f-b88816ae4519
* Version Independent ID: aad0e220-49d9-b9bc-10b7-ea0155af1d96
* Content: [AD FS Troubleshooting - Integrated Windows Authentication](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-iwa)
* Content Source: [WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-iwa.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-iwa.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Not sure if I understand your issue completely, but have you browsed other sites to see if your problem has been discussed already?

Example:
- https://social.technet.microsoft.com/Forums/ie/en-US/c51a4b53-80b3-4992-96a0-650e7dfec83b/adfs-configuration-wizard-the-spn-required-for-this-federation-service-is-already-set-on-another?forum=ADFS

**Comment by exchange12rocks** [comment]
@illfated They say that the page [WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-iwa.md](../blob/master/WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-iwa.md) specifies the "http" service class for AD FS SPN, while all other docs everywhere say that the SPN should start with "host".
Maybe that ad-fs-tshoot-iwa should be corrected

**Comment by illfated** [comment]
> Maybe that ad-fs-tshoot-iwa should be corrected

Fair point. Do we have enough evidence to say that "host" is the correct term, not http, and that http should be replaced with "host" in that page?

**Comment by illfated** [comment]
OK, I just noticed that the same issue has been reported in ticket #5039 as well. I guess this suggests that I get a grip on myself and start modifying the page as suggested.

**Comment by illfated** [comment]
Hmm. I was hoping for text content to edit, but this is images only, no text.

I don't have access to any AD FS server, but maybe the correct images exist elsewhere on the internet already?

**Comment by exchange12rocks** [comment]
@illfated The screenshot with the SPN in the article is from ADSI Edit, not from the AD FS console. So if you have an access to a domain controller, you are good

**Comment by illfated** [comment]
@aferrillo : Just to check before I dig too deep down into this rabbit hole of finding the correct images, would you happen to have any good screenshot images to replace the ones in the article, making it easier to update the images to show the correct words ("host" instead of "http")?

**Comment by exchange12rocks** [comment]
@illfated That's not a property of ADFS, you'll find it in AD DS. Just use ADSI Edit, for example: create a test account, assign SPNs to it, make a screenshot for documentation, delete the account =)

**Comment by exchange12rocks** [comment]
I also found where we can see what classes the "host" class represents: take a look at the `sPNMappings` attribute at the `CN=Directory Service,CN=Windows NT,CN=Services,CN=Configuration,DC=<your context here>`

**Comment by illfated** [comment]
Thank you for the information. I am currently on sick leave, but I may be able to test this if it is safe to do remotely on a production server.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @aferrillo,

Thanks again for contacting Microsoft. We value your feedback.

As we understand it, you're describing something about the product compared to an issue with the documentation. GitHub isn't quite the right location if searching for technical support, deeper specifics of the product or feature requests as it is completely outside our scope. If there are any issues within the content itself, please let us know.

To get assistance or support for your product, we recommend that you engage with the product community or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs). 

Additional support forums listed below:
- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Hopefully one of the community experts may be able to better assist. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
