### ISSUE TITLE
DisabledByDefault Descrepancy

### ISSUE THREAD

**Issue by Kiwifulla** [MicrosoftDocs/windowsserverdocs#4926]
All through this article, there are comments around the DisabledByDefault setting which says to set to 1 to disable the protocol by default, yet the screenshots show it set to 0 but the description immediate preceding these pictures say "The following example shows TLS xxx disabled in the registry".

e.g. "To disable TLS 1.0 by default, create a DisabledByDefault entry and change the DWORD value to 1. If an SSPI app explicitly requests to use TLS 1.0, it may be negotiated.  The following example shows TLS 1.0 disabled in the registry" - but then it shows it set to 0!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd180142-4c19-8abc-ecce-e4c7e5ac8951
* Version Independent ID: fc5bba87-afad-1729-8f7e-333c73188b73
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by illfated** [comment]
OK. There are 2 options to choose from here (both involving that you make a Pull Request to change the incorrect information):
- Create your own image (or edit the current image) and upload the new one to your own PR branch.
- Start editing the text in the document, create a PR from that, where you suggest the image description to something like this:
"**The following example shows you where to disable TLS 1.0 in the registry.**"

Feel free to inform us when you have started working on your Pull Request and ask for help whenever you need to add information in the PR.

**Comment by illfated** [comment]
You are misreading the text and image content. The image shows the setting as "Disabled" because **Enabled = 0** in the image.

This is NOT the same as **Disabled By Default**.

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
By the way, when I said "You are misreading the text and image content.", I meant to say that you are jumping to conclusions. It is necessary to read the statements separately and with individual meanings.

**Comment by Kiwifulla** [comment]
Wow you sure have a blunt way of letting me know what you mean!

Ok I wouldn’t say “jumping to conclusions” but more like you have worded it right before showing a picture that has it set the opposite way!

I do see what you mean now though, but because perhaps the statements about DisabledByDefault shouldn’t be right before the screenshots then, and instead should be after?

I am having a similar discussion with a SCOM Management Pack author (see below) who thinks your page is saying to set DisabledByDefault to 0 to disable it and has written his monitors to expect it to be 0 to be considered Healthy, therefore his monitors generate alerts when set to 1 as he thinks 0 is DisabledByDefault.

https://monitoringguys.com/2020/07/13/tls-compliance-monitoring/



Sent from my iPhone

On 8/11/2020, at 8:40 AM, Trond B. Krokli <notifications@github.com> wrote:

﻿

By the way, when I said "You are misreading the text and image content.", I meant to say that you are jumping to conclusions. It is necessary to read the statements separately and with individual meanings.

**Comment by Kiwifulla** [comment]
To add to this, why has each picture got the red box around both settings when making that statement - this is where the confusion got me too?!

The DisabledByDefault setting shouldn’t be included in the red box when set to 0, following the example statements around this is the protocol showing as disabled. This is very misleading (yes the protocol is disabled but not by default too) and is no doubt why they wrote their monitors to look for that combination as the best practice.

Kevin Holman’s SCOM TLS script sets DisabledByDefault to 1 as best practice, and the Monitoring Guys have it as 0, as they too misinterpreted your site.


Sent from my iPhone

On 8/11/2020, at 9:44 AM, Steve Cahill <Steve.Cahill@kiwibank.co.nz> wrote:

﻿ Wow you sure have a blunt way of letting me know what you mean!

Ok I wouldn’t say “jumping to conclusions” but more like you have worded it right before showing a picture that has it set the opposite way!

I do see what you mean now though, but because perhaps the statements about DisabledByDefault shouldn’t be right before the screenshots then, and instead should be after?

I am having a similar discussion with a SCOM Management Pack author (see below) who thinks your page is saying to set DisabledByDefault to 0 to disable it and has written his monitors to expect it to be 0 to be considered Healthy, therefore his monitors generate alerts when set to 1 as he thinks 0 is DisabledByDefault.

https://monitoringguys.com/2020/07/13/tls-compliance-monitoring/



Sent from my iPhone

On 8/11/2020, at 8:40 AM, Trond B. Krokli <notifications@github.com> wrote:

﻿

By the way, when I said "You are misreading the text and image content.", I meant to say that you are jumping to conclusions. It is necessary to read the statements separately and with individual meanings.

**Comment by illfated** [comment]
Sorry for appearing to be blunt, I did not intend to make that impression.

I was tired and wanted to complete my task of sorting out which tickets were related to the DTLS 1.1 / DTLS 1.2 image issue, for which I made a PR to resolve the fact that DTLS 1.1 is not an existing protocol.

Anyway, maybe you are correct, but would you be able to suggest a better way to clear up that confusion, so we can work on some material to add in a new PR to clean up the mess you are seing?

**Comment by Kiwifulla** [comment]
No problem, I guess I just want to understand if the article needs updating to better explain the end goal of disabling each protocol by default and in general.  In my opinion to reduce confusion, each protocol explanation should be similar to this (or show a screenshot for each setting right after it is explained on what it should be set to for it to be disabled).

I also wasn’t 100% sure if it needs the statement updated when you have it set as per my screenshot that it will be denied even when an SSPI app explicitly requests to use TLS 1.1 IF Enabled = 0 and DisabledByDefault = 1 – is that the case?  I have highlighted my text around that too…

….
To disable TLS 1.1 for client or server, change the DWORD value to 0. If an SSPI app requests to use TLS 1.1, it will be denied.
To disable TLS 1.1 by default, create a DisabledByDefault entry and change the DWORD value to 1. If an SSPI app explicitly requests to use TLS 1.1, it may be negotiated (unless Enabled = 0 and DisabledByDefault = 1, then it will be denied).
The following example shows TLS 1.1 disabled (Enabled = 0) and TLS 1.1 by default being disabled also (DisabledByDefault = 1) in the registry:
[cid:image003.png@01D6B68B.266F0E10]

**Comment by illfated** [comment]
Just to quote someone more knowledgeable than me in this topic, here is an explanation from https://github.com/MicrosoftDocs/windowsserverdocs/pull/4988#issuecomment-723637268:

> > By the way, I have answered a handful of tickets where other users have claimed that the images do not show the correct state of the services being disabled, because they (in my opinion) claim that the Registry key **`DisabledByDefault`** should have the value 1 instead of 0, whereas I find that the images seem to be correct by showing the key **`Enabled = 0`**. Do you have any views on that detail?
> 
> Well, this is a standard case where Microsoft makes things difficult with double negation and further complicates it with dual flags overriding each other. So let's break it down.
> 
> * DisabledByDefault and Enabled control different things, but we can think of DisabledByDefault as a subset of Enabled=1 setting.
> * When Enabled flag is set to 0, the respective protocol version is disabled and cannot be negotiated no matter what the value of DisabledByDefault flag is. In this cases the value of DisabledByDefault is essentially ignored.
> * If Enabled=1 AND DisabledByDefault=1 the respective protocol is not advertised, but it can still be explicitly requested through SSPI.
> * If Enabled=1 AND DisabledByDefault=0 the respective protocol is available and advertised.
> * In short, DisabledByDefault flag is somewhat useless and confusing because no matter what the value is here, it does not really disable the protocol.
> 
> So, back to your question, while the clean settings for a completely disabled protocol are:
> 
> * DisabledByDefault=1 (Disabled by Default)
> * Enabled=0 (Disabled)
> 
> in reality, the following combination also completely disables the protocol:
> 
> * DisabledByDefault=0 (Enabled by Default)
> * Enabled=0 (Disabled)

**Comment by Kiwifulla** [comment]
Thanks for the information – the fact that multiple people are querying this and that some are taking DisabledByDefault=0 as gospel over DisabledByDefault=1 highlights my confusion also.

But yes, I do understand it now in that DisabledByDefault is a subset of Enabled, so if Enabled=0 then it doesn’t really matter what DisabledByDefault is set to…but as mentioned by your guru, DisabledByDefault=1 is the “clean” way of setting it.

I have let the SCOM Management Pack company know this too, as currently when his monitor sees DisabledByDefault=1, it fires SCOM alerts to say this is not set as best practice when disabling these protocol, and his monitor expects this to be 0.
https://monitoringguys.com/2020/07/13/tls-compliance-monitoring/#comment-102

Thanks again

**Comment by illfated** [comment]
Very well, good follow-up and feedback. Would you also like to offer some form of document improvement to reduce the confusion, based on the available information?

**Comment by Kiwifulla** [comment]
I would say the document could be improved by reiterating what @ixtlanian<https://github.com/ixtlanian> wrote on https://github.com/MicrosoftDocs/windowsserverdocs/pull/4988#issuecomment-723637268 - to cleanly disable the protocol by setting it as not available and not advertised (by default) then to set Enabled to 0 and DisabledByDefault to 1.

He has summed up what needs to be highlighted – also with his comments around thinking of DisabledByDefault as a subset of Enabled, and that when Enabled is set to 0 this essentially ignores the value of DisabledByDefault.

**Comment by illfated** [comment]
Good call. I will do my best to find a way to place it within the existing document, but it might take a week for me to finish it (got more than enough to do at work. I am also going to ask for this ticket to be reopened, just to make it easier for myself to follow up on this ticket.

Feel free to add anything that might be helpful regarding the placement and so on.

**Comment by illfated** [comment]
#please-reopen

**Comment by illfated** [comment]
#please-open

**Comment by Kiwifulla** [comment]
Hi there - this doesn't appear to have been reopened yet as per the comments made 28 days ago?

**Comment by illfated** [comment]
I tried both here and somewhere else with no success, so I don't know if the scripted bots are able to reopen tickets at all or if they have got any respond codes to do so.

**Comment by Kiwifulla** [comment]
OK thanks - so how can we progress with you being able to update the documentation?

**Comment by illfated** [comment]
Sorry, I have had some rough times lately. I misjudged how sleepy the medicine I take makes me. Would it be OK if we continue this discussion in my PR #4988 ?

**Comment by Kiwifulla** [comment]
Ah sorry to hear that. No problem using that one, thanks
