### ISSUE TITLE
No description about "Open Source Shielded VM"

### ISSUE THREAD

**Issue by k-takai** [MicrosoftDocs/windowsserverdocs#493]
The description about "Open Source Shielded VM" is missing.
Please add the description about "Open Source Shielded VM" to the section of "Secure Boot setting in Hyper-V Manager".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2854f1b3-5af8-fea5-c0be-ea95033065ed
* Version Independent ID: 68acd194-7f2b-ec0b-b862-6a33b356c9bc
* Content: [Generation 2 virtual machine security settings for Hyper-V](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/learn-more/generation-2-virtual-machine-security-settings-for-hyper-v#feedback)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/learn-more/Generation-2-virtual-machine-security-settings-for-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/learn-more/Generation-2-virtual-machine-security-settings-for-Hyper-V.md)
* Service: **na**
* GitHub Login: @larsiwer
* Microsoft Alias: **kathydav**

**Comment by larsiwer** [comment]
Sorry that this took so long. I've created [PR 1781](https://github.com/MicrosoftDocs/windowsserverdocs/pull/1781) to include some information on the template

**Comment by larsiwer** [comment]
@k-takai @lizap with the documentation changes being live: is it ok to close this issue?
