### ISSUE TITLE
Feedback on findstr documentation

### ISSUE THREAD

**Issue by bjordan2010** [MicrosoftDocs/windowsserverdocs#4930]
This does not work you get cannot open there.  The documentation is misleading.  
findstr /c:hello there C:\blah\blah\*.*  

This works.
findstr "hello there" C:\blah\blah\*.*

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b90f482-f48a-7d60-7ba9-bb5a1e837989
* Version Independent ID: 5a8e1ac5-3f4d-4da9-67c3-15a08d9a1b61
* Content: [findstr](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/findstr)
* Content Source: [WindowsServerDocs/administration/windows-commands/findstr.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/findstr.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @bjordan2010,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change was made surrounding this example, and changes are live. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close

**Comment by apompeia** [comment]
Trying to find open G:  on all .frm files I used findstr /s /i "open G" *.frm |more
This command do not work. 
If I use findstr /s /i "open" *.frm |more is ok it works
[findstr problem.txt](https://github.com/MicrosoftDocs/windowsserverdocs/files/11783907/findstr.problem.txt)
