### ISSUE TITLE
Need to provide official way of fixing the issue 

### ISSUE THREAD

**Issue by PradeepKommaraju** [MicrosoftDocs/windowsserverdocs#4932]
In case as per the attached screen-shot ,
 
![image](https://user-images.githubusercontent.com/70923691/96757017-b7cc5100-1389-11eb-83eb-ed3b48f196f2.png)

Since its a system volume which is blocking the expand C; drive operation , We should have an official way to fix the issue rather than telling customer to use third party tools like Ghost etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2beddb54-a9ed-b53e-c8e1-152069c2c5c4
* Version Independent ID: 8aa0fe83-1e7f-3636-2122-477afd35a657
* Content: [Extend a basic volume](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/extend-a-basic-volume)
* Content Source: [WindowsServerDocs/storage/disk-management/extend-a-basic-volume.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/extend-a-basic-volume.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @PradeepKommaraju,

Thanks again for contacting Microsoft. We value your feedback. 

Going over the documentation, point number 2 states the following if the **Extend Volume** option is greyed out:

- Disk Management or Computer Management was opened with administrator permissions.
- There is unallocated space directly after (to the right) of the volume, as shown in the graphic above. If there's another volume in-between the unallocated space and the volume you want to extend, you can either delete the in-between volume and all files on it (make sure to back up or move any important files first!), use a non-Microsoft disk partitioning app that can move volumes without destroying data, or skip extending the volume and instead create a separate volume in the unallocated space.
- The volume is formatted with the NTFS or ReFS file system. Other file systems can't be extended, so you'd have to move or back up the files on the volume and then format the volume with the NTFS or ReFS file system.
- If the disk is larger than 2 TB, make sure that it's using the GPT partitioning scheme. To use more than 2 TB on a disk, it must be initialized using the GPT partitioning scheme. To convert to GPT, see [Change an MBR disk into a GPT disk](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/change-an-mbr-disk-into-a-gpt-disk).

If you're still experiencing issue's after going through the potential issue's above, we recommend that you engage with the product community or open a ticket with Microsoft Support. For more information, please see [Contact Microsoft Support](https://support.microsoft.com/ContactUs).

We will be closing this thread. Thank you and have a most pleasant day. 
#please-close
