### ISSUE TITLE
"Brandcache Overview" link not working.

### ISSUE THREAD

**Issue by jrochet** [MicrosoftDocs/windowsserverdocs#494]
It leads to page not found error at the following URL:
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh831696(v=ws.11)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e75c29a6-08f9-3c3e-2379-fd8e6e501a50
* Version Independent ID: 28be067a-f8bb-c3a6-5ce3-91d620d2f263
* Content: [Work Folders overview](https://docs.microsoft.com/en-us/windows-server/storage/work-folders/work-folders-overview)
* Content Source: [WindowsServerDocs/storage/work-folders/work-folders-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/work-folders/work-folders-overview.md)
* Service: **unspecified**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by lizap** [comment]
We had some issues with some of our Windows Server 2012 content, but you should see it now. Thanks!
