### ISSUE TITLE
Video Link to Channel 9 does not work.

### ISSUE THREAD

**Issue by HelderN** [MicrosoftDocs/windowsserverdocs#4941]
Video Link to Channel 9 does not work.

**Comment by eross-msft** [comment]
@HelderN  Thanks for the feedback. What page is the broken link on? There's no information with this issue beyond your text, so I don't know where the problematic link is located.

**Comment by HelderN** [comment]
Refused to display 'https://channel9.msdn.com/Shows/Mechanics/Introduction-to-Shielded-Virtual-Machines-in-Windows-Server-2016?nocookie=true' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Comment by eross-msft** [comment]
@HelderN  Thank you for this. It looks like the video is working and the link is right (https://channel9.msdn.com/Shows/Mechanics/Introduction-to-Shielded-Virtual-Machines-in-Windows-Server-2016), but that it's not displaying properly from GitHub. I will have to look into this and see if we can figure out why it's not showing properly.

**Comment by eross-msft** [comment]
@HelderN  Figured out the issue, the full link needs to be: https://channel9.msdn.com/Shows/Mechanics/Introduction-to-Shielded-Virtual-Machines-in-Windows-Server-2016/player. This will be fixed with our publish at the end of the week.
