### ISSUE TITLE
Does ssh-agent on windows have persistent storage of ssh keys?

### ISSUE THREAD

**Issue by zaaj** [MicrosoftDocs/windowsserverdocs#4946]
[Enter feedback here]

This article seems to suggest deleting ssh private keys after adding them to ssh-agent with ssh-add and backing them up to a secure storage medium.  I've only ever seen ssh-agent store keys for a single session of the OS running, so a reboot clears them all out and they have to be re- ssh-add'ed every reboot.

Did Microsoft alter ssh-agent to have persistent storage of added keys?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH key management for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by eross-msft** [comment]
Closing and re-opening to test labeling automation so this can be addressed.

**Comment by robinharwood** [comment]
Hi @zaaj 

Thanks for your dedication to our documentation. In our examples the service was set to manual which required the service to be started at each reboot, although the keys were already persistent. We've submitted a documentation change to update the code examples, setting the ssh-agent to automatic, the updated article should be live by tomorrow. If you have an more queries about the ssh-agent design, please use the (Win32-OpenSSH issues)[https://github.com/PowerShell/Win32-OpenSSH/issues]

#please-close
