### ISSUE TITLE
Embedded Script doesnt work on copy paste due to syntax error.

### ISSUE THREAD

**Issue by asengutt** [MicrosoftDocs/windowsserverdocs#4947]
In link https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/deploy-storage-spaces-direct#step-4-deploy-scale-out-file-server-for-converged-solutions
Under Step 4.2: Create file shares
Bullet 3, Open a Windows PowerShell session with Administrator credentials 
There is embedded script to FileShareSetup.ps1

Get-ClusterSharedVolume -Cluster $StorageClusterName | ForEach-Object
**{**
should change to 
Get-ClusterSharedVolume -Cluster $StorageClusterName | ForEach-Object **{**

If not, we will fail due to below error.
![bug](https://user-images.githubusercontent.com/73563414/97372438-072ee780-188a-11eb-9b5f-1cd7fe8cc21a.png)

However running from a script file, might not have any issues. Most users run from PS prompt.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af5d56ce-6ce8-772c-f1c5-c314b9f05dcd
* Version Independent ID: 2ca4d497-707f-4507-7431-ef3fdbb3ec7d
* Content: [Deploy Storage Spaces Direct](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/deploy-storage-spaces-direct#step-4-deploy-scale-out-file-server-for-converged-solutions)
* Content Source: [WindowsServerDocs/storage/storage-spaces/deploy-storage-spaces-direct.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/deploy-storage-spaces-direct.md)
* Product: **windows-server**
* Technology: **storage-spaces**
* GitHub Login: @StevenEk
* Microsoft Alias: **stevenek**

**Comment by IngridAtMicrosoft** [comment]
#assign:dknappett

**Comment by PRMerger12** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: dknappett

**Comment by IngridAtMicrosoft** [comment]
#assign:dknappettmsft

**Comment by dknappettmsft** [comment]
Thanks for the feedback. I have corrected the PowerShell, which should be visible later today.

#please-close
