### ISSUE TITLE
Wrong PowerShell Commands for Removing Certificates

### ISSUE THREAD

**Issue by matziq** [MicrosoftDocs/windowsserverdocs#4956]
Site lists the following commands:
Get-DHASInactiveSigningCertificates
Remove-DHASInactiveSigningCertificates
Get-DHASInactiveEncryptionCertificates
Remove-DHASInactiveEncryptionCertificates

Commands should be (no "s" at the end):
Get-DHASInactiveSigningCertificate
Remove-DHASInactiveSigningCertificate
Get-DHASInactiveEncryptionCertificate
Remove-DHASInactiveEncryptionCertificate

Thanks!
John
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c83a63b4-fc94-5218-3b1a-0083d0fe0f47
* Version Independent ID: 6d2687b7-9b35-5d76-31b1-39ac86af7b6c
* Content: [Device Health Attestation](https://docs.microsoft.com/en-us/windows-server/security/device-health-attestation#install-and-configure-the-dha-service-on-windows-server-2016)
* Content Source: [WindowsServerDocs/security/device-health-attestation.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/device-health-attestation.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. A documentation change has been made and will be live after the next business day. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
