### ISSUE TITLE
WSUS client diagnostic tools links to Forbidden page.

### ISSUE THREAD

**Issue by JeroenTuinstra** [MicrosoftDocs/windowsserverdocs#4957]
Page links to broken pages. ClientDiag.exe is nowhere to be found anymore.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa21e853-8fa2-24d0-9806-75345cc12fd3
* Version Independent ID: 5397b0db-f1b5-fa63-df9c-112fb9672833
* Content: [Windows Server Update Services tools and utilities](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/manage/wsus-tools)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/manage/wsus-tools.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/manage/wsus-tools.md)
* Product: **windows-server**
* Technology: **wsus**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
See also issue ticket #4782 for a discussion on this topic and maybe how to resolve it.

**Comment by illfated** [comment]
(also ref. #5105 )
