### ISSUE TITLE
doesn't support architecture 'i386'

### ISSUE THREAD

**Issue by UsielAmaral** [MicrosoftDocs/windowsserverdocs#4967]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25943cc5-9927-5ca7-b9db-4c1d398726c5
* Version Independent ID: ae5bf48b-26cf-b5c8-22c8-68fa9a70258f
* Content: [Linux Software Repository for Microsoft Products](https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software)
* Content Source: [WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @victorcheng7
* Microsoft Alias: **vichen**

**Comment by konstruktoid** [comment]
That is correct, and most possibly due to the fact most Linux distribution has dropped, or is dropping, support for i386.

```sh
~$ curl https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/main/binary-amd64/Release
Origin: microsoft-ubuntu-focal-prod focal
Label: microsoft-ubuntu-focal-prod focal
Archive: focal
Architecture: amd64
Component: main
```

**Comment by illfated** [comment]
@konstruktoid : Thank you for the perfectly good answer. It is true, more and more software solutions are going in the direction of supplying 64-bit versions only, especially for IT Pro and Server usage.

@UsielAmaral : Is it fair to say that your question has been answered, so we can go ahead and close this ticket?
