### ISSUE TITLE
User Certificate should not include Secure Email or Encrypted File System EKU

### ISSUE THREAD

**Issue by NeoZer01** [MicrosoftDocs/windowsserverdocs#4971]
Hello this is Wes Hammond (Sr. PFE) PKI SME ( alias: weham )

The User Certificate for Auto VPN should not include Secure Email or Encrypted File System EKU as it may not be intended they use the certificate for this purpose.

Please add a note to go to the extensions tab and remove these EKU's only leaving client authentication.

Thanks!

-Wes
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76dd49bb-b86e-f5b7-35b9-a8d246d36fcb
* Version Independent ID: dedfa83f-36d6-f60b-e839-ba382c5a7372
* Content: [Configure the Server Infrastructure](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by anaharris-ms** [comment]
#please-close Fixed in: https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/3398

**Comment by NeoZer01** [comment]
> #please-close Fixed in: https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/3398

I believe the link for this is broken.

**Comment by anaharris-ms** [comment]
Hi @NeoZer01,

My apologies. The link can only be asked by MSFT internal. You'll have to check out the live document here: https://learn.microsoft.com/windows-server/remote/remote-access/tutorial-aovpn-deploy-create-certificates

Let me know if you still have issues!
