### ISSUE TITLE
How to use Windows Admin Center Links

### ISSUE THREAD

**Issue by mdmaguire** [MicrosoftDocs/windowsserverdocs#4975]
The links to the Ignite 2019 Videos showing how to use Windows Admin Center are dead as the videos are gone.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd448b3c-456e-bd11-efb5-278296801fc0
* Version Independent ID: f82f9906-69aa-fc5b-e479-84b42b6c716f
* Content: [Windows Admin Center Overview](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/overview#video-based-learning)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/overview.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by Xelu86** [comment]
Hey @mdmaguire,

Thanks again for contacting Microsoft. We value your feedback. 

The video has been updated in this documentation and directs to the correct location. This change is live. We will be closing this as resolved. 

Thank you and have a most pleasant day. #please-close
