### ISSUE TITLE
Incorrect column heading

### ISSUE THREAD

**Issue by foobird13** [MicrosoftDocs/windowsserverdocs#4976]
Under the section "SendTrustedIssuerList" there is a table with the title "Default Send Trusted Issuer List behavior".  The second column currently has a header of "Time", which does not apply to the values listed (i.e. TRUE, FALSE).  It's more likely this header should be something like "Default value", or "Default Behavior".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd180142-4c19-8abc-ecce-e4c7e5ac8951
* Version Independent ID: fc5bba87-afad-1729-8f7e-333c73188b73
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by illfated** [comment]
Fair point. That column title is more than a little bit confusing. I think maybe it should be something like "**Default behavior**", based on the following:
- https://support.microsoft.com/en-us/help/933430/clients-cannot-make-connections-if-you-require-client-certificates-on

### Method 3: Configure Schannel to no longer send the list of trusted root certificate authorities during the TLS/SSL handshake process
Warning: Serious problems might occur if you modify the registry incorrectly by using Registry Editor or by using another method. These problems might require that you reinstall the operating system. Microsoft cannot guarantee that these problems can be solved. Modify the registry at your own risk.

On the server that is running IIS or on the IAS server on which you experience this problem, set the following registry entry to false:

**HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL**

    Value name: SendTrustedIssuerList
    Value type: REG_DWORD
    Value data: 0 (False)

By default, this entry is not listed in the registry. By default, this value is 1 (True). This registry entry controls the flag that controls whether the server sends a list of trusted certificate authorities to the client. When you set this registry entry to False, the server does not send a list of trusted certificate authorities to the client. This behavior may affect how the client responds to a request for a certificate. For example, if Internet Explorer receives a request for client authentication, Internet Explorer displays only the client certificates that appear in the chain of one of the certification authorities that are in the list from the server. However, if the server does not send a list of trusted certificate authorities, Internet Explorer displays all the client certificates that are installed on the client computer.

To set this registry entry, follow these steps:
1. Click **Start**, click **Run**, type regedit, and then click **OK**.
2. Locate and then click the following registry subkey:

**HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL**

3. On the Edit menu, point to New, and then click DWORD Value.
4. Type SendTrustedIssuerList, and then press ENTER to name the registry entry.
5. Right-click SendTrustedIssuerList, and then click Modify.
6. In the Value data box, type 0 if that value is not already displayed, and then click OK.
7. Exit Registry Editor.

**Comment by illfated** [comment]
There you go. PR #4988 is available for viewing, comments and suggestions. Take care of yourself and those near you.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. A documentation change was made and changes are live. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
