### ISSUE TITLE
Missing Windows 10 Pro for Workstations / Enterprise capabilities description

### ISSUE THREAD

**Issue by i3v** [MicrosoftDocs/windowsserverdocs#4980]
In 2017, Microsoft announced "Windows 10 Pro for Workstations", that includes some SMB Direct capabilities [[1](https://www.microsoft.com/en-us/microsoft-365/blog/2017/08/10/microsoft-announces-windows-10-pro-workstations/#:~:text=Users%20will%20now%20be%20able,(today%20limited%20to%202TB).),[2](https://www.microsoft.com/en-us/microsoft-365/blog/2017/12/15/windows-10-pro-workstations-power-advanced-workloads/)]. Also, it was mentioned that Enterprise versions are getting the same capabilities. Nevertheless, this article still does not mention any of that.
For example, personally, I'm still puzzled about whether  "Windows 10 Pro for Workstations" and "Windows 10 Enterprise" are providing both SMB-Direct server and SMB-Direct client capabilities, or "client only". But it would make sense to mention all other possible nuances too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85ab8371-7782-ad6f-b564-5fd93b3b879a
* Version Independent ID: 5d91cde1-786d-6c7b-f8c3-9667f9df84d7
* Content: [Improve performance of a file server with SMB Direct](https://docs.microsoft.com/en-us/windows-server/storage/file-server/smb-direct)
* Content Source: [WindowsServerDocs/storage/file-server/smb-direct.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/smb-direct.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey i3v,

Thanks again for contacting Microsoft. We value your feedback. 

Not everything that is found in blog posts or similar pages will make it into the documentation page of a specific product or service. Other times I have seen it where the blog is launched before the product is released to let users know that something new is coming, like a sneak peek or a preview/demo.

In regards to: 

> whether "Windows 10 Pro for Workstations" and "Windows 10 Enterprise" are providing both SMB-Direct server and SMB-Direct client capabilities, or "client only"

It is to our understanding that the features/capabilities of SMB Direct are shared between both server-side & client-side with the exception that any non-Server OS (strictly client-only) are restricted. Meaning that Windows 10/11 family Operating Systems can only run as a client, it cannot perform any of the capabilities that you can perform in Windows Server in setting up this environment.

We have updated this page to reflect this along with minor updates. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
