### ISSUE TITLE
Update supported TFS / DevOps Servers versions on Windows Server 2019

### ISSUE THREAD

**Issue by shunkino** [MicrosoftDocs/windowsserverdocs#4986]
This document contains table that suggest TFS 2017 and TFS 2018 is supported on Windows Server 2019.
But, according the issue bellow, it seems they are not supported on Windows Server 2019.
https://github.com/MicrosoftDocs/azure-devops-docs/issues/3368

This conflict between Windows Server 2019 doc and TFS / DevOps doc is quite confusing for users who are considering on-premise ALM environment. I think it's better to add Windows Server 2019 and Azure DevOps Server 2020 instead of TFS 2017/2018 as documented in the following doc. 
https://docs.microsoft.com/en-us/azure/devops/server/requirements?view=azure-devops-2020#server-operating-systems

Please let me know if I should write PR for this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 511301d9-f9cb-bad2-993f-d45c3b17b1b0
* Version Independent ID: 3f1d3506-849e-5dde-de07-edfc99b333f8
* Content: [Windows Server 2019 and Microsoft Server application compatibility](https://docs.microsoft.com/en-us/windows-server/get-started-19/app-compat-19)
* Content Source: [WindowsServerDocs/get-started-19/app-compat-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/app-compat-19.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by rikat-ms** [comment]
See this issue which talked that TFS2017/TFS2018 is **NOT** supported on Windows Server 2019.
https://github.com/MicrosoftDocs/azure-devops-server-docs/issues/115

**Comment by illfated** [comment]
@shunkino : Feel free to start a PR to suggest removing Team Foundation Server 2017 & 2018, in addition to adding Azure DevOps Server 2019 / 2020 for the table in this document.

**Comment by shunkino** [comment]
@illfated Thanks for your response! I will write PR.

**Comment by shunkino** [comment]
I have wrote PR and the doc page is updated as suggested. Closing this issue.

**Comment by illfated** [comment]
Nice. Good job. Thank you for following up on this.

**Comment by EDToft** [comment]
And what of the people who relied on that, now changed, documentation as the basis for moving to Windows Server 2019; Thinking that they'd be able to move their TFS 2017/2018 over. Oh...yeah...tough luck buddy. :)

Why is this the case. Is it a matter of some features of TFS 2017 not working with Windows Server 2019? Or will it not work...period? As you may have guessed...I'm in this situation and budgets are constrained.

**Comment by EDToft** [comment]
As of 9/9/2020...when management was buying Windows Server 2019, all looked well.

Now that we are actually needing to move TFS2017 from an old server on to a 2019 server...we get stuck holding the bag.

![tfs20172018](https://user-images.githubusercontent.com/12531984/108899131-af0cb580-75dd-11eb-970e-9e5689ca35d3.png)

**Comment by EDToft** [comment]
Will TFS 2017 not work at all on Windows Server 2019? Or is it just parts of it that don't work? Will the installation just fail outright? 

I thing Microsoft owes a bit toward explaining this better, since decisions were made based on the "latest documentation" (at the time) for moving to Windows Server 2019. What is our recourse?
