### ISSUE TITLE
The link in step 3D for the update-clusterfunctionallevel command gives a 404 error.

### ISSUE THREAD

**Issue by kelemvor33** [MicrosoftDocs/windowsserverdocs#499]
The URL links to here:
https://technet.microsoft.com/library/mt589702.aspx
And then I end up here:
https://docs.microsoft.com/en-us/powershell/module/failover-clusters/update-clusterfunctionallevel
With a giant 404 on the screen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60832ce0-4687-b723-afd3-0fba3fec54d7
* Version Independent ID: 28ce8f7a-0280-65e3-3fe5-d07cdfd6405f
* Content: [Cluster Operating System Rolling Upgrade](https://docs.microsoft.com/en-us/windows-server/failover-clustering/cluster-operating-system-rolling-upgrade)
* Content Source: [WindowsServerDocs/failover-clustering/Cluster-Operating-System-Rolling-Upgrade.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/Cluster-Operating-System-Rolling-Upgrade.md)
* Service: **unspecified**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by lizap** [comment]
Thanks for catching that. I've updated that link - you should see the fix live on 3/27/18.
