### ISSUE TITLE
How to Create a Custom Primary Authenticator?

### ISSUE THREAD

**Issue by kabronkline** [MicrosoftDocs/windowsserverdocs#4998]
Is there any documentation available that describes the steps for developing and registering a custom primary authenticator in ADFS 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1c6f3c5-3b46-0c95-5293-802819ac729d
* Version Independent ID: c881178b-868a-a9a4-834e-c30e010e7dcc
* Content: [Additional authentication methods in AD FS 2019](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/additional-authentication-methods-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Additional-Authentication-Methods-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Additional-Authentication-Methods-AD-FS.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @kabronkline,

I did find  "[Build a Custom Authentication Method for AD FS in Windows Server](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/development/ad-fs-build-custom-auth-method)" page. Hopefully this is able to provide you an answer.

For additional support outside of the Docs page, please check our additional forums or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs). 

Additional support forums listed below:
- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
