### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by conyg** [MicrosoftDocs/windowsserverdocs#5000]
The documentation should be more clear on what need to be installed on the server and what needs to be installed on the client
Ex: **OpenSSHUtils** should be installed only on the server (helpful to repair permissions)
while **ssh-agent** should be installed  / started only on the client (to store keys that will be used to connect to the server)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH key management for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by illfated** [comment]
@konstruktoid : Would this be related to your PR and your proposed changes to the referenced page?

**Comment by konstruktoid** [comment]
Yeah, https://github.com/MicrosoftDocs/windowsserverdocs/pull/4788

@conyg Are you sure about `OpenSSHUtils` most issues mentions its deprecated?

**Comment by conyg** [comment]
When OpenSSH is installed (at least on Windows Server) `OpenSSHUtils` is missing.
I had to configure OpenSSH today and definitely this tool is needed.

People were downloading it from a different source (ex [PowerShell gallery](https://www.powershellgallery.com/packages/OpenSSHUtils/1.0.0.1)). This is now deprecated and I don't know where the most recent version is.

I think everybody is expecting this to be part of OpenSSH installation package on windows

**Comment by konstruktoid** [comment]
`OpenSSH_KeyManagement.md` is about key management after the service has been installed. 
I believe you should be following https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md before reading the content source mentioned in this issue.

**Comment by conyg** [comment]
My comment is related to [this page](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement).  When I clicked the link to give Feedback about that page I was sent here.

You are right: It is about key management and this is a quote from the page that I am referring to:

> `# Install the OpenSSHUtils module to the server. This will be valuable when deploying user keys.`
Install-Module -Force OpenSSHUtils -Scope AllUsers
>
>`# By default the ssh-agent service is disabled. Allow it to be manually started for the next step to work.`
Get-Service -Name ssh-agent | Set-Service -StartupType Manual
>
>`# Start the ssh-agent service to preserve the server keys`
Start-Service ssh-agent
>
>`# Now start the sshd service`
Start-Service sshd

As I said: `OpenSSHUtils `should be installed only on the server and `ssh-agent` should be used only on the client.
The way it is written wright now, may have people think they need to use also the `ssh-agent` on the server. 

This is not true unless you need to do connect from the server to another server and in that case we are talking about the client settings on the server.

**Comment by konstruktoid** [comment]
That page, https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement, is getting rewritten by #4788

**Comment by illfated** [comment]
List of related issue tickets:

- #2747 **A better explanation can be found here** (Open)
- #3400 **Can't install the "OpenSSHUtils"** (Closed)
- #3456 **Misleading title/summary causing search confusion** (Open)
- #3806 **OpenSSHUtils is deprecated** (Open)
- #3970 **OpenSSH installation** (Closed)
- #4345 **OpenSSHUtils Not Needed** (Open)
- #4518 **Unable to configure OpenSSH for public key auth following docs** (Open)
- #4598 **Instructions provided ends with an error** (Open)
- #4622 **Out-of-date - OpenSSHUtils no longer available.** (Open)
- #4634 **More documentation required** (Open)
- #4690 **OpenSSHUtils install reference no longer valid** (Open)
- #4702 **OpenSSHUtils got unlisted from the PowerShell gallery** (Open)
- #4743 **Nope. First example errors out.** (Open)
- #4770 **Error when following instructions to install OpenSSHUtils** (Open)
- #4787 **OpenSSHUtils module does not exist** (Open)
- #5138 **These instructions do not work on Windows 10 20h2** (Open)

**Comment by dknappettmsft** [comment]
Thanks for submitting this issue @conyg. I made a change to the ssh-agent reference you mentioned in your original post (it missed the boat for the other changes made to this article that are now visible).

The changes should be visible in around 6-12 hours.

#please-close
