### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by adrianhale** [MicrosoftDocs/windowsserverdocs#5002]
Add "a" and "."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f43fec44-fdc4-3f92-291e-a46c10cd4aee
* Version Independent ID: 0ed1458c-2026-696f-a7d1-f964137e1377
* Content: [Securing privileged access](https://docs.microsoft.com/en-us/windows-server/identity/securing-privileged-access/securing-privileged-access)
* Content Source: [WindowsServerDocs/identity/securing-privileged-access/securing-privileged-access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/securing-privileged-access/securing-privileged-access.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by illfated** [comment]
@adrianhale : Could you reference which sentence this is about, to make it easier for someone like me to write a correction PR to the document?

**Comment by adrianhale** [comment]
Yes sorry. I got a error from GitHub but this still submitted somehow.

https://docs.microsoft.com/en-us/windows-server/identity/securing-privileged-access/securing-privileged-access#1-require-windows-hello-for-business-and-mfa

Administrators can benefit from the ease of use associated with Windows Hello for Business. Admins can replace their complex passwords with strong two-factor authentication on their PCs. An attacker must have both the device and the biometric info or PIN, it's much more difficult to gain access without the employee's knowledge. More details about Windows Hello for Business and the path to roll out can be found in the article Windows Hello for Business Overview**.**

Enable multi-factor authentication (MFA) for your administrator accounts in Azure AD using Azure MFA. At **a** minimum enable the baseline protection conditional access policy**.** **M**ore information about Azure Multi-Factor Authentication can be found in the article Deploy cloud-based Azure Multi-Factor Authentication**.**

**Comment by illfated** [comment]
Thank you very much. From what I can remember, I view you as a reliable source for valid feedback and assumed that something unexpected could have happened. Fair enough. I can implement your suggested change, as well as adding some missing commas for readability.

Feel free to add anything else in need of improvement you find on the page, so I can add that to the list of changes. 🙂

**Comment by illfated** [comment]
There you go. PR #5003 is ready for review. Feel free to browse, review, comment or suggest more improvements.
