### ISSUE TITLE
Very good page

### ISSUE THREAD

**Issue by GetFitgardenercom** [MicrosoftDocs/windowsserverdocs#5018]
"https://docs.microsoft.com/en-us/windows-server/storage/disk-management/change-a-gpt-disk-into-an-mbr-disk" is a solid page that provided perfect information. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 188314c1-f9b8-c4b5-61d7-dc726cc4a3e1
* Version Independent ID: a7420741-a2d7-f0a0-2df4-e66a6c382bef
* Content: [Change a GUID Partition Table (GPT) disk into a Master Boot Record (MBR) disk](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/change-a-gpt-disk-into-an-mbr-disk)
* Content Source: [WindowsServerDocs/storage/disk-management/change-a-gpt-disk-into-an-mbr-disk.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/change-a-gpt-disk-into-an-mbr-disk.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
@GetFitgardenercom : Thank you for the nice feedback. Is there anything else you would like to share, before we close this ticket?

Please note: This page will still be searchable after closing, by using the search feature, or by clicking the link at the bottom of the page:
- :octocat: [View all page feedback](https://github.com/MicrosoftDocs/windowsserverdocs/issues?utf8=%E2%9C%93&q=%22a7420741-a2d7-f0a0-2df4-e66a6c382bef%22&in=body)

**Comment by illfated** [comment]
#please-close
