### ISSUE TITLE
ipconfig

### ISSUE THREAD

**Issue by yaxye8123** [MicrosoftDocs/windowsserverdocs#5019]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d472fa7d-c960-de56-f804-a93e117b8fb3
* Version Independent ID: c8c28e1d-6555-59b5-24e4-69ec11a420ef
* Content: [macfile](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/macfile)
* Content Source: [WindowsServerDocs/administration/windows-commands/macfile.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/macfile.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
@yaxye8123 : Thank you for taking your time to check out the Feedback feature.

Please make sure to include a description when posting an issue ticket.

Feel free to open a new ticket when you have got a practical issue to report.

**Comment by illfated** [comment]
#please-close
