### ISSUE TITLE
need to say how to uninstall too

### ISSUE THREAD

**Issue by ladylazy9x** [MicrosoftDocs/windowsserverdocs#5023]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25943cc5-9927-5ca7-b9db-4c1d398726c5
* Version Independent ID: ae5bf48b-26cf-b5c8-22c8-68fa9a70258f
* Content: [Linux Software Repository for Microsoft Products](https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software)
* Content Source: [WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @victorcheng7
* Microsoft Alias: **vichen**

**Comment by illfated** [comment]
# [Frequently Asked Questions about Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/faq#how-do-i-uninstall-a-wsl-distribution)


## How do I uninstall a WSL Distribution?

On builds prior to 1709 (16299) open a command prompt and run:

  ```batchfile
  lxrun /uninstall /full
  ```
  
WSL distributions installed **from the Store** can be uninstalled **like any other Windows app**, by right-clicking on the app tile and clicking **Uninstall**, or via **PowerShell** using the [`Remove-AppxPackage` cmdlet](https://docs.microsoft.com/powershell/module/appx/remove-appxpackage#example-1--remove-an-app-package).

***

**Comment by illfated** [comment]
Thank you for the feedback and for contributing to make the MS Docs better!

**Comment by illfated** [comment]
Please also note that I am making another PR to (hopefully) close this ticket. I am adding a "See Also" section to the page referenced in this ticket.

**Comment by illfated** [comment]
There you go. PR #5148 is ready for review, comments, and suggestions.
