### ISSUE TITLE
See slso => See also

### ISSUE THREAD

**Issue by mehmetberber** [MicrosoftDocs/windowsserverdocs#5024]
Hi there,

The section at the very bottom of the page should be titled "See **a**lso" instead of "See **s**lso"

Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2beddb54-a9ed-b53e-c8e1-152069c2c5c4
* Version Independent ID: 8aa0fe83-1e7f-3636-2122-477afd35a657
* Content: [Extend a basic volume](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/extend-a-basic-volume)
* Content Source: [WindowsServerDocs/storage/disk-management/extend-a-basic-volume.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/extend-a-basic-volume.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Good point, well spotted. Thanks! 🙂
