### ISSUE TITLE
Automatic Refresh Error

### ISSUE THREAD

**Issue by StevenHardware** [MicrosoftDocs/windowsserverdocs#503]
Just to note on the install. If you get an error in Server Manager for Automatic refresh and it failed to installed WSUS, this is the WID install part of the WSUS install. In this case, it was because in the Default domain policy, logon as a service was not setup correctly as explained in the below article.

https://social.technet.microsoft.com/Forums/windowsserver/en-US/ae88de7d-f69f-4cb1-877f-379151d01899/can-not-install-windows-internal-database-wid-windows-server-2012?forum=winserver8gen

As we have this already set up on our domain to run as a service for our software, i just added the "NETWORK, NETWORK SERVICE, SERVICE" to the "Define these policy settings" and then forced a gpupdate on the WSUS server. It now worked and installed without error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2a2bd78-4375-2b03-244a-fb83a25d94cd
* Version Independent ID: 6384256d-5048-be30-ffe2-86ff61862226
* Content: [Step 1 - Install the WSUS Server Role](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/deploy/1-install-the-wsus-server-role)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/deploy/1-install-the-wsus-server-role.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/deploy/1-install-the-wsus-server-role.md)
* Service: **unspecified**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
@StevenHardware : Thank you for your feedback & solution suggestion. This ticket should remain searchable even after closing. 
Please post again if you believe your feedback should be part of the documentation.

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
