### ISSUE TITLE
SMB2 Not Listed In Windows Features

### ISSUE THREAD

**Issue by KellisR** [MicrosoftDocs/windowsserverdocs#5030]
I'm going crazy. Only SMB1 is listed. How can I force Windows to get SMB2 and SMB3 from "someplace"???????
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6efee75e-7541-0166-76ac-81ecbe4cb022
* Version Independent ID: 35b346a7-ea72-325e-81c9-a1056dca72f4
* Content: [SMBv1 is not installed by default in Windows 10 version 1709, Windows Server version 1709 and later versions](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/smbv1-not-installed-by-default-in-windows)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/smbv1-not-installed-by-default-in-windows.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/Troubleshoot/smbv1-not-installed-by-default-in-windows.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by RAJU2529** [comment]
@KellisR . You can use powershell command to enable SMB2 and SMB3

**Comment by KellisR** [comment]
Thanks, I appreciate the response. I "assumed" like SMB1 it would show in windows Features for me to check. So I kept looking for an indication it was truly enabled. Finely dawned on me it was on by default and not listed.  Hence the need for PowerShell.

**Comment by illfated** [comment]
@KellisR : Thank you for the discussion. I hope you found this useful. It appears that your issue has been resolved via the answer from @RAJU2529 .

I will proceed to close this ticket, but feel free to open a new ticket if you have got suggestions for improving the MS Docs document pages.

**Comment by illfated** [comment]
#please-close
