### ISSUE TITLE
Web Client's About page and Feedback link are not correct

### ISSUE THREAD

**Issue by Jahn08** [MicrosoftDocs/windowsserverdocs#5032]
The last section **Get help with the web client** mentions: 

> you can get help with the web client by emailing the address on the web client's About page

However, it seems irrelevant since there is no email on the web client's About panel.

![WEB_CLIENT_ABOUT](https://user-images.githubusercontent.com/23010028/99518575-cc5c3300-29a1-11eb-95d9-6af9cbb397ce.png)

On top of that, its Feedback link leads to a [non-working address](https://remotedesktop.uservoice.com/forums/911494-remote-desktop-web-client).

So, is there any other way to share all the pain I suffer from while working through the Web Client (being compelled to do so in the absence of a free desktop client for Linux and my company's corporate policies)? If there is such a way then please update this section of the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58c2644e-6037-8b15-10e6-e77392cff23a
* Version Independent ID: 1307699a-e45f-0f84-9563-73270bae1a76
* Content: [Get started with the web client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by RAJU2529** [comment]
@Jahn08 . Which article are you referring to

**Comment by Jahn08** [comment]
@RAJU2529, I added a link to the article in my question it's called [Get started with the web client](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client.md)

**Comment by illfated** [comment]
This is what the ticket could have looked like, if it had been opened via the button "This page":

![image](https://user-images.githubusercontent.com/38162891/99753228-27973e00-2ae6-11eb-9dd0-c27f23ae50e1.png)

***

(Your comment here)
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58c2644e-6037-8b15-10e6-e77392cff23a
* Version Independent ID: 1307699a-e45f-0f84-9563-73270bae1a76
* Content: [Get started with the web client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by illfated** [comment]
> The last section **Get help with the web client** of a document [Get started with the web client](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client.md?rgh-link-date=2020-11-18T11%3A45%3A33Z) mentions:
> 
> > you can get help with the web client by emailing the address on the web client's About page
> 
> However, it seems irrelevant since there is no email on the web client's About panel.
> 
 
Disclaimer: I am not affiliated with Microsoft nor the Microsoft Docs teams here on GitHub. I may not know the topic well enough to give correct feedback on the topic.

Please also note: I have not used or tested this web app, it sounds a bit like there would be a company-designed About page with a contact address for the person or department responsible for the web-based remote desktop client access. Then again, I could be wrong, not having seen the inner workings of this app.


> On top of that, its Feedback link leads to a [non-working address] (https://remotedesktop.uservoice.com/forums/911494-remote-desktop-web-client).
> 
> So, is there any other way to share all the pain I suffer from while working through the Web Client (being compelled to do so in the absence of a free desktop client for Linux and my company's corporate policies)? If there is such a way then please update this section of the documentation.

Not sure if this is because of your browser, your OS or your internet connection, but the link works fine for me:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/38162891/99754073-e99b1980-2ae7-11eb-9ecd-ca1790fac295.png)

</details>

***

The main site link also works for me, https://remotedesktop.uservoice.com/ :

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/38162891/99754135-0df6f600-2ae8-11eb-8890-14b37ba05568.png)

</details>

**Comment by illfated** [comment]
Looking closer at your image, it seems you don't have Telemetry, which seems to be required for support.

![image](https://user-images.githubusercontent.com/38162891/99754342-7f36a900-2ae8-11eb-9203-06582ef81b05.png)

( I could easily be wrong, I have not tested it. Although if I had, I would have tested this from a Windows computer.)

**Comment by Jahn08** [comment]
@illfated thank you for your help! Since I've stumbled upon this document on GitHhub, there was no such a button to create a well formatted issue! I've edited my initial comment.

If it's telemetry to blame, perhaps, it should be mentioned in that document too.

**Comment by Jahn08** [comment]
@illfated both links are still unresponsive for me: I've tried to open them in Chrome and Mozilla. It's hardly possible that my OS is responsible for rendering web pages.

**Comment by illfated** [comment]
Hmm, that is a weird browser issue. I have tested that web page only from a Windows 10 Home (x64) laptop, using Google Chrome, Version 86.0.4240.198 (Official Build) (64-bit), Mozilla Firefox 82.0.3 (64-bit) & 83.0 (64-bit), and Microsoft Edge (chromium-based) Version 86.0.622.69 (Official build) (64-bit) &  87.0.664.41 (Official build) (64-bit). All of them show the web page as expected & intended.

I am not sure what could be causing the page not to render on your computer. Would it be possible for you to create a VM running Windows 10 and using a Windows-based browser somehow, just for testing purposes? If that is not an option, maybe you could use some form of remote connect to a Windows computer?

**Comment by RAJU2529** [comment]
@illfated . could you tell me, which website you tried to open, paste the website link here .

**Comment by Jahn08** [comment]
@illfated, I've just tried opening it on Windows 10 being connected to my work computer by the web client with the same unsatisfying result for both Edge (86.0.622.69) and Chrome (86.0.4240.111).

**Comment by illfated** [comment]
@RAJU2529 : These 2 links are the ones I manage to get working from my computer, but @Jahn08 seems to be blocked from reaching:
- https://remotedesktop.uservoice.com/forums/911494-remote-desktop-web-client
- https://remotedesktop.uservoice.com/

I checked the pages again, just now, to see if I was logged in with my Microsoft account, but not in that site. So I don't know exactly why other users can't reach that site.

**Comment by RAJU2529** [comment]
@illfated . Just now I checked on Android 10 based smartphone, both the links are opened without problems.
on chrome v87.0.4280.66
on edge browser v45.10.24.5088

i am in college now, I will check in laptop once I reach to my home and then I update the status

**Comment by illfated** [comment]
Thank you for testing those links from other operating systems than Windows, that helps us narrow down the amount of possible suspects.

@Jahn08 : Could it be some form of geo-location issue, that your Linux computer might have some rigorous security, or that some form of firewall is blocking your access to those pages? I don't know, but it feels a little bit like if your scenario could be compared to "the Great Firewall of China", blocking some sites which have not been whitelisted by your government (or something similar causing the same results).

**Comment by Jahn08** [comment]
@illfated, I don’t think that this particular site is among prohibited in Russia, where I’m from. We don’t have a whole nation wide firewall here. However, it occurred to me that it’s Microsoft that might restrict the access for some countries, is it possible?

**Comment by illfated** [comment]
Thank you for the reply. Well, then I don't know what is causing the issue. Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub. Hence I don't know whether Microsoft uses any geo-location or not.

**Comment by Jahn08** [comment]
@illfated, thank you for your responsiveness. It would be great if someone official from Microsoft could unravel the mystery. Though as far as I understand, they haven’t replied yet.

**Comment by illfated** [comment]
Well, this repository (and its parallel MicrosoftDocs repositories) are intended to be used to report issues with the documentation and suggestions for improvements to the documentation. In this ticket, it is about the page [Get started with the web client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client) and what should be done to improve any errors or missing information in that page.

Problems and errors during use of the documentation should be directed to the Microsoft forums, where the users and managers are prepared to answer questions and suggest troubleshooting steps. Here is a short list I have collected earlier:

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

We other users try our best to find any clear steps we can take to suggest improvements by creating Pull Requests to add information or modifying the existing information.

**Comment by illfated** [comment]
Knowing that this repository is intended for direct improvement of the documentation by reporting issues in the document pages, and not so much about reporting issues in the software itself, do you know if there is anything we can do to improve the related document page(s), or is this almost exclusively about the software contents?

**Comment by illfated** [comment]
Also: Please consider using the general Feedback feature in Windows to report issues with the software. 
That is the common suggestion in most of the Microsoft Docs documentation repositories.

**Comment by illfated** [comment]
To report a bug, you can use the Windows 10 Feedback Hub: https://aka.ms/AA160kq

**Comment by Jahn08** [comment]
I've finally managed to try opening the links again after returning back to my country, and it seems that they are indeed somehow blocked for Russia: they don't work from any of my devices. @illfated, I'll report this behaviour through the links you've provided. Thank you for your help!

As for improvements to the documentation, perhaps, it would be better to mention what particular conditions should be met to get that support mail address on the About page of the Web Client. If it's about Telemetry then it would be great to highlight this fact and provide a link to an article explaining how to turn it on.

**Comment by illfated** [comment]
Thank you again for the feedback. I see what you are saying, but from my experience with this repository, it is often difficult to verify changes like that without involving MS technical employees and developers, which often takes a lot of time to complete. It is usually more effective to report issues like this to the developers via either local Microsoft support or Feedback Hub, then wait for the developers to request changes in the documentation based on their findings.

Sure, we can leave this ticket open for now, but without any other reports to other departments, it may take a very long time before anything can be done to change the documentation.

**Comment by Jahn08** [comment]
I've asked questions regarding the trouble on the [Microsoft Q&A portal](https://docs.microsoft.com/en-us/answers/questions/187092/web-client39s-about-page-and-feedback-link-are-not.html). I reckon, it makes sense to close this issue and reopen it later as long as there are relevant answers or comments, clarifying how the documentation should be amended.
