### ISSUE TITLE
How to configure DNS on the DC's

### ISSUE THREAD

**Issue by gerrynicol** [MicrosoftDocs/windowsserverdocs#5033]
Please can you provide more information on how DNS should be set up on Domain controllers in Azure. If you have 2 domain controllers in a vnet and set the DNS to custom on the VNET (Using the two IP's of the DC's\DNS servers), what should the settings be in DNS within the TCP\IP properties of the nic in the VM. If you set it to 'Obtain DNS server address automatically' then both domain controllers will point to the IP address that is top of the list on the custom DNS servers on the vnet. Is this the correct way of configuring this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b0097c-668e-1d37-22b0-89d0bf649f8a
* Version Independent ID: 49ccfef6-05bb-9c93-5a05-a2e2fe632b3c
* Content: [Install Active Directory Domain Services on an Azure virtual machine](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by gerrynicol** [comment]
Hi @iainfoulds.  Is there any update on the issue I raised? I can't see this documented anywhere by MS.

**Comment by PatAltimore** [comment]
Hi @gerrynicol,

Thanks for the feedback. It's not clear in the article the VM requires restart for the change. It's covered in the "for more information" reference https://docs.microsoft.com/en-us/azure/virtual-network/manage-virtual-network#change-dns-servers. I added a line of text to the section that the VM requires restart. 

Thanks for the feedback. I'll close the issue. #please-close

Pat
