### ISSUE TITLE
dash missing in command-line command for manage-bde pause

### ISSUE THREAD

**Issue by neil007m** [MicrosoftDocs/windowsserverdocs#5037]
[Enter feedback here]
change
`manage-bde pause C:`
to 
`manage-bde -pause C:`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a26f7d30-dde1-aed4-c476-cdb2e6629495
* Version Independent ID: aea33249-0859-932a-d556-390efe1b5a47
* Content: [manage-bde pause](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/manage-bde-pause)
* Content Source: [WindowsServerDocs/administration/windows-commands/manage-bde-pause.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/manage-bde-pause.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
@neil007m : Thank you for noticing and reporting that example typo. I will open a Pull Request to have that typo corrected.

**Comment by illfated** [comment]
There you go. PR #5038 is now ready for review, browsing, commenting & suggestions.
