### ISSUE TITLE
Windows Remote Management for Server Core 2019

### ISSUE THREAD

**Issue by MrPeppah** [MicrosoftDocs/windowsserverdocs#5040]
For Server 2019,

This article should be updated to remove the reference:
Enable-NetFirewallRule -DisplayGroup "Remote Administration" and then replace it with:
Enable-NetFirewallRule -DisplayGroup "Windows Remote Management"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcb12aed-dce1-d2e8-c5bd-da2c2fec5bc9
* Version Independent ID: 2b215377-7c67-9012-8ad2-889483380b5d
* Content: [Manage Server Core](https://docs.microsoft.com/en-us/windows-server/administration/server-core/server-core-manage)
* Content Source: [WindowsServerDocs/administration/server-core/server-core-manage.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/server-core/server-core-manage.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @pronichkin
* Microsoft Alias: **artemp**

**Comment by MrPeppah** [comment]
`PS C:\Users\user> Enable-NetFirewallRule -DisplayGroup "Remote Administration"
Enable-NetFirewallRule : No MSFT_NetFirewallRule objects found with property 'DisplayGroup' equal to 'Remote
Administration'.  Verify the value of the property and retry.
At line:1 char:1
+ Enable-NetFirewallRule -DisplayGroup "Remote Administration"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Remote Administration:String) [Enable-NetFirewallRule], CimJobException
    + FullyQualifiedErrorId : CmdletizationQuery_NotFound_DisplayGroup,Enable-NetFirewallRule

PS C:\Users\user> Enable-NetFirewallRule -DisplayGroup "Windows Remote Management"`

**Comment by RAJU2529** [comment]
@MrPeppah , What you  said is  correct, thanks for pointingout. I am fixing the error now.
![Capture1](https://user-images.githubusercontent.com/3296790/99892995-43930f00-2ca1-11eb-8cd3-475028e7fe79.JPG)

**Comment by illfated** [comment]
Resolved in PR #5046 .

#please-close

**Comment by illfated** [comment]
(also ref. #821 )
