### ISSUE TITLE
Need to shown an example of a key with spaces

### ISSUE THREAD

**Issue by verakot** [MicrosoftDocs/windowsserverdocs#5041]
For example HKLM\SOFTWARE\Microsoft\Windows Script Host\

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd817f1d-e494-af38-4a10-86360d63c195
* Version Independent ID: 11fcbf91-6c28-9ae8-045a-35ea97444dfe
* Content: [reg add](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/reg-add)
* Content Source: [WindowsServerDocs/administration/windows-commands/reg-add.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/reg-add.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by PRMerger12** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: ingridatmicrosoft 
gh issue comment 5034 -b ingridatmicrosoft

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86
