### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by msft-jasonparker** [MicrosoftDocs/windowsserverdocs#5043]
Broken link:  To learn more about this feature, check out https://aka.ms/paa-sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0517ea6a-9417-31a8-39a5-f6128387fee5
* Version Independent ID: 7636ec70-e1dd-8c6b-516c-8af324d9f645
* Content: [Get started with the macOS client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-mac)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
Resolves to https://docs.microsoft.com/samples/browse/?redirectedfrom=MSDN-samples

Going to open a PR and suggest changes, to get rid of old technet & MSDN links by replacing them with docs.microsoft.com URLs (if available).

**Comment by illfated** [comment]
Also: ref. recent commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/b813b5c92b6ddb6b55a66bbf568d5f7fca80d148 (direct file link https://github.com/MicrosoftDocs/windowsserverdocs/commit/b813b5c92b6ddb6b55a66bbf568d5f7fca80d148#diff-afc375680b97586e90c2d96617d9d4ced5204505ef8ed947d60fdc1ba39ac08c).

**Comment by illfated** [comment]
There you go, PR #5044 is ready for review, comments and suggestions.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. A documentation change has been made and will be live after the next business day. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
