### ISSUE TITLE
Donel Adams/ Donadamassociates

### ISSUE THREAD

**Issue by donadam2015** [MicrosoftDocs/windowsserverdocs#5047]
Fostering business development through my associate networks to maximize any platforms growth potential utilizing ai and cloud
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa82e6ef-7f35-9672-2ca3-9006de31b2cf
* Version Independent ID: 1dca040b-d5ba-8449-627b-b3069bd9be0e
* Content: [DirectAccess](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/directaccess/directaccess?ranMID=24542&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-elxANRvQbJCgbpT3vaLQCw&epi=je6NUbpObpQ-elxANRvQbJCgbpT3vaLQCw&irgwc=1&OCID=AID2000142_aff_7593_1243925&tduid=%28ir__oweodkpgbkkfqmt0kk0sohzgc32xsswv2uvtqydp00%29%287593%29%281243925%29%28je6NUbpObpQ-elxANRvQbJCgbpT3vaLQCw%29%28%29&irclickid=_oweodkpgbkkfqmt0kk0sohzgc32xsswv2uvtqydp00)
* Content Source: [WindowsServerDocs/remote/remote-access/directaccess/DirectAccess.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/directaccess/DirectAccess.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
#please-close (unrelated to the referenced documentation page)
