### ISSUE TITLE
Is "Windows Server 2019” also included in Azure Hybrid Benefit?

### ISSUE THREAD

**Issue by SnoWolfT** [MicrosoftDocs/windowsserverdocs#5049]
The last update of this document is 11/10/2017. Customer wants to double confirm whether "Windows Server 2019” is also included in Azure Hybrid Benefit?

Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90e335dd-0bc5-a7e3-650b-e3dd1823176b
* Version Independent ID: 18f34ef3-ff61-0473-a64b-ac5a64dbe1d7
* Content: [Azure Hybrid Benefit for Windows Server](https://docs.microsoft.com/en-us/windows-server/get-started/azure-hybrid-benefit)
* Content Source: [WindowsServerDocs/get-started/azure-hybrid-benefit.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/azure-hybrid-benefit.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @eross-msft
* Microsoft Alias: **chrisrin**

**Comment by SnoWolfT** [comment]
Hi Team, do we have any update on this?
In additional, I use my subscription to create 2 Win2019 VM with and without AHB. Then I use the Cost analysis to check and find the cost of both VM are the same... Would you please have a check of that? I suppose the cost of the VM with AHB should be lower.
![image](https://user-images.githubusercontent.com/20415080/100684972-623a8980-33b6-11eb-8390-9c2f21c777b7.png)

**Comment by eross-msft** [comment]
@SnoWolfT I will try to get a response from the product group about whether this is supported on WS2019.

As for your other questions, this feedback area is only intended to address documentation-related issues. It's currently not possible for us to follow up on support-related questions. To ask for product assistance, you can go our new Windows on Q&A site, https://docs.microsoft.com/en-us/answers/products/windows#windows-server-for-it-pros or to the Microsoft Tech Community Windows Server forum, https://techcommunity.microsoft.com/t5/windows-server/ct-p/Windows-Server to ask your questions. You may also want to contact your local Microsoft Support representative to see if they can help.

**Comment by eross-msft** [comment]
@SnoWolfT  The product team confirmed it includes WS 2019. I will update the article to add that. Thanks!
