### ISSUE TITLE
Missing IIS folder "MopriaCloudService\bin" after installing "CloudPrintDeploy.ps1"

### ISSUE THREAD

**Issue by jleger88** [MicrosoftDocs/windowsserverdocs#505]
After running Step 2 - 2, I noticed that IIS was missing folder "MopriaCloudService\bin" for the Webapp:(C:\inetpub\wwwroot\MopriaCloudService\bin) does not exists.

Is this a common occurrence? What can I try next?
OS Build 14393.2068

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21d1d072-911f-92c0-248a-9e44efbff42d
* Version Independent ID: 0fdb921d-d97d-5b12-ae28-286216e130df
* Content: [Deploy Windows Server Hybrid Cloud Print](https://docs.microsoft.com/en-us/windows-server/administration/hybrid-cloud-print/hybrid-cloud-print-deploy#feedback)
* Content Source: [WindowsServerDocs/administration/hybrid-cloud-print/hybrid-cloud-print-deploy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/hybrid-cloud-print/hybrid-cloud-print-deploy.md)
* Service: **unspecified**
* GitHub Login: @msjimwu
* Microsoft Alias: **coreyp**

**Comment by jleger88** [comment]
Could not find a part of the path
'C:\inetpub\wwwroot\EnterpriseCloudPrint'
""
'C:\inetpub\wwwroot\MopriaCloudService'

**Comment by msjimwu** [comment]
Please take a look at the "CloudPrintDeploy.log" in "\Program Files\WindowsPowerShell\Modules\PublishCloudPrinter\1.0.0.0" directory.  You can also file a feedback through "Feedback Hub" application and attach the log file.

Was IIS already installed on the machine under a different directory structure?

**Comment by jleger88** [comment]
Look's like IIS may have already been installed, when I added the print service a few weeks ago I added "Internet Printing" which installs the old IIS IPP webpage. I'm hoping that's the main culprit. I'll see if I can remove that role and reset IIS.

**Comment by jleger88** [comment]
I just tried on a newly created VM, IIS was never installed until I ran CloudPrntDeploy.ps1. I am still getting the same error with the path for ECP and MCS not being created under 'C:\inetpub\wwwroot '.

Here's the log:

** Installing IIS

Deployment Image Servicing and Management tool
Version: 10.0.14393.0

Image Version: 10.0.14393.0

Enabling feature(s)

[                           0.1%                           ] 

[                           1.1%                           ] 

[=                          2.1%                           ] 

[=                          3.1%                           ] 

[==                         4.1%                           ] 

[==                         5.1%                           ] 

[===                        6.1%                           ] 

[====                       7.1%                           ] 

[====                       8.1%                           ] 

[=====                      9.1%                           ] 

[=====                      10.0%                          ] 

[=====                      10.0%                          ] 

[=====                      10.0%                          ] 

[=====                      10.0%                          ] 

[=====                      10.0%                          ] 

[=====                      10.0%                          ] 

[======                     11.0%                          ] 

[======                     12.0%                          ] 

[=======                    13.0%                          ] 

[========                   14.0%                          ] 

[========                   15.0%                          ] 

[=========                  16.0%                          ] 

[=========                  17.0%                          ] 

[==========                 18.0%                          ] 

[===========                19.0%                          ] 

[===========                20.0%                          ] 

[============               21.0%                          ] 

[============               22.0%                          ] 

[=============              23.0%                          ] 

[=============              24.0%                          ] 

[==============             25.0%                          ] 

[===============            26.0%                          ] 

[===============            27.0%                          ] 

[================           28.0%                          ] 

[================           29.0%                          ] 

[=================          30.0%                          ] 

[=================          30.0%                          ] 

[=================          31.0%                          ] 

[==================         31.4%                          ] 

[==================         32.4%                          ] 

[===================        33.4%                          ] 

[===================        33.4%                          ] 

[===================        33.4%                          ] 

[===================        34.4%                          ] 

[====================       35.4%                          ] 

[=====================      36.4%                          ] 

[=====================      37.4%                          ] 

[======================     38.4%                          ] 

[======================     39.4%                          ] 

[=======================    40.4%                          ] 

[========================   41.4%                          ] 

[========================   42.4%                          ] 

[=========================  43.4%                          ] 

[=========================  44.4%                          ] 

[========================== 45.4%                          ] 

[========================== 46.4%                          ] 

[===========================47.4%                          ] 

[===========================48.4%                          ] 

[===========================49.4%                          ] 

[===========================50.4%                          ] 

[===========================51.4%                          ] 

[===========================52.4%                          ] 

[===========================53.4%                          ] 

[===========================54.4%                          ] 

[===========================55.4%                          ] 

[===========================55.5%                          ] 

[===========================55.6%                          ] 

[===========================55.7%                          ] 

[===========================56.7%                          ] 

[===========================57.7%=                         ] 

[===========================58.7%==                        ] 

[===========================59.7%==                        ] 

[===========================60.7%===                       ] 

[===========================61.7%===                       ] 

[===========================62.7%====                      ] 

[===========================63.7%====                      ] 

[===========================64.3%=====                     ] 

[===========================65.3%=====                     ] 

[===========================66.1%======                    ] 

[===========================67.1%======                    ] 

[===========================68.1%=======                   ] 

[===========================69.1%========                  ] 

[===========================70.1%========                  ] 

[===========================71.1%=========                 ] 

[===========================71.3%=========                 ] 

[===========================72.3%=========                 ] 

[===========================73.1%==========                ] 

[===========================74.1%==========                ] 

[===========================81.7%===============           ] 

[===========================82.7%===============           ] 

[===========================83.7%================          ] 

[===========================84.7%=================         ] 

[===========================85.7%=================         ] 

[===========================86.7%==================        ] 

[===========================87.7%==================        ] 

[===========================88.7%===================       ] 

[===========================89.7%====================      ] 

[===========================90.7%====================      ] 

[===========================91.5%=====================     ] 

[===========================91.8%=====================     ] 

[===========================92.5%=====================     ] 

[===========================93.0%=====================     ] 

[===========================93.4%======================    ] 

[===========================93.7%======================    ] 

[===========================94.7%======================    ] 

[===========================94.9%=======================   ] 

[===========================95.0%=======================   ] 

[===========================95.3%=======================   ] 

[===========================95.6%=======================   ] 

[===========================96.0%=======================   ] 

[===========================96.1%=======================   ] 

[===========================96.2%=======================   ] 

[===========================96.4%=======================   ] 

[===========================96.5%=======================   ] 

[===========================96.7%========================  ] 

[===========================96.8%========================  ] 

[===========================96.9%========================  ] 

[===========================96.9%========================  ] 

[===========================97.0%========================  ] 

[===========================97.1%========================  ] 

[===========================97.2%========================  ] 

[===========================97.3%========================  ] 

[===========================97.5%========================  ] 

[===========================97.8%========================  ] 

[===========================98.0%========================  ] 

[===========================98.4%========================= ] 

[===========================98.7%========================= ] 

[===========================99.0%========================= ] 

[==========================100.0%==========================] 
The operation completed successfully.
** Stopping WWW service
The World Wide Web Publishing Service service is stopping.
The World Wide Web Publishing Service service was stopped successfully.

** Installing Enterprise Cloud Print binaries

Deployment Image Servicing and Management tool
Version: 10.0.14393.0

Image Version: 10.0.14393.0


Error: 87

No Windows features were specified on the command line.
Use the /Get-Features option to find the name of the feature in the image and try the command again.

The DISM log file can be found at C:\Windows\Logs\DISM\dism.log
** Installing Mopria Discovery Service binaries

Deployment Image Servicing and Management tool
Version: 10.0.14393.0

Image Version: 10.0.14393.0


Error: 87

No Windows features were specified on the command line.
Use the /Get-Features option to find the name of the feature in the image and try the command again.

The DISM log file can be found at C:\Windows\Logs\DISM\dism.log
** Adding WebServices
APPPOOL object "ECPAppPool" added
Applied configuration changes to section "system.applicationHost/applicationPools" for "MACHINE/WEBROOT/APPHOST" at configuration commit path "MACHINE/WEBROOT/APPHOST"
SITE object "Default Web Site" changed
APP object "Default Web Site/ecp" added
VDIR object "Default Web Site/ecp" added
APP object "Default Web Site/ecp" changed
APP object "Default Web Site/mcs" added
VDIR object "Default Web Site/mcs" added
APP object "Default Web Site/mcs" changed
** Enabling Windows Authentication for AAD PreAuth
Unlocked section "system.webServer/security/authentication/anonymousAuthentication" at configuration path "MACHINE/WEBROOT/APPHOST".
Applied configuration changes to section "system.webServer/security/authentication/anonymousAuthentication" for "MACHINE/WEBROOT/APPHOST/Default Web Site" at configuration commit path "MACHINE/WEBROOT/APPHOST/Default Web Site"
Unlocked section "system.webServer/security/authentication/windowsAuthentication" at configuration path "MACHINE/WEBROOT/APPHOST".
Applied configuration changes to section "system.webServer/security/authentication/windowsAuthentication" for "MACHINE/WEBROOT/APPHOST/Default Web Site" at configuration commit path "MACHINE/WEBROOT/APPHOST/Default Web Site"
** Opening SSL firewall port
Ok.

** Updating registry
The operation completed successfully.

The operation completed successfully.

The operation completed successfully.

The operation completed successfully.

The operation completed successfully.

The operation completed successfully.

The operation completed successfully.

The operation completed successfully.

The operation completed successfully.

The operation completed successfully.

The operation completed successfully.

** Restarting IIS

Attempting stop...

Internet services successfully stopped

Attempting start...

Internet services successfully restarted

** Creating EcpPrintTest virtual printer


    Directory: C:\


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----        3/29/2018   2:33 PM                EcpTestOutput                                                         


** Done

**Comment by jleger88** [comment]
The install was directly from an Azure Marketplace Compute, Windows Server 2016 Datacenter. Version 1607, OS Build 14393.2155. Should I be trying on Windows Server version 1709? Out of curiosity is there any plans or roadmap to make Hybrid Cloud Print a direct drag and drop PAAS solution in Azure?

**Comment by msjimwu** [comment]
Thanks for the info.  I have the same Azure Compute VM running with build 14393.2007 and the feature on demand package installed fine.  We'll keep looking at what may be causing the issue you've hit.

**Comment by ec-alm** [comment]
Did anyone ever find a solution for this? I'm struggling to find any resource on how this has been fixed. I see @lizap closed the issue, but would be interesting in knowing how to resolve it.
Thanks in advance.
