### ISSUE TITLE
Key not recognized in Focal Fossa

### ISSUE THREAD

**Issue by lucaberti** [MicrosoftDocs/windowsserverdocs#5053]
The procedure to add the repo-key in Ubuntu seems not to work on Focal Fossa: 
curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
gpg: invalid key resource URL '/tmp/apt-key-gpghome.6Jpcq7bemm/home:manuelschneid3r.asc.gpg'
gpg: keyblock resource '(null)': Errore generale
gpg: key 1488EB46E192A257: 1 signature not checked due to a missing key
gpg: key 1488EB46E192A257: 1 signature not checked due to a missing key
gpg: key E6D4736255751E5D: 1 signature not checked due to a missing key
gpg: key 3B4FE6ACC0B21F32: 3 signatures not checked due to missing keys
gpg: key D94AA3F0EFE21092: 3 signatures not checked due to missing keys
gpg: key 871920D1991BC93C: 1 signature not checked due to a missing key
gpg: Numero totale esaminato: 8
gpg:       nuove chiavi saltate: 8

Sorry, it is in Italian, but I guess you can figure it out.
Best, 
Luca

**Comment by illfated** [comment]
@konstruktoid : Sorry to bother you again, but is this something we need to look into or fix in the existing Microsoft Docs pages?

**Comment by konstruktoid** [comment]
Hi @lucaberti, I don't believe this is an issue with `microsoft.asc` being faulty.

There seems to be couple issues mentioning issues with the `manuelschneid3r.asc.gpg` key (https://askubuntu.com/questions/1246031/gpg-invalid-key-resource-url-following-docker-official-guide, https://github.com/RadeonOpenCompute/ROCm/issues/1254) and other issues mentioning `gpg: invalid key resource URL` (https://serverfault.com/questions/1022078/ubuntu-add-repo-app-key-fails, https://www.linuxliteos.com/forums/other/update-error-lite-welcome/).

My suggestion is that you remove the `manuelschneid3r` key and try again.

```
$ curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -v -
gpg: armor header: Version: GnuPG v1.4.7 (GNU/Linux)
gpg: pub  rsa2048/EB3E94ADBE1229CF 2015-10-28  Microsoft (Release signing) <gpgsecurity@microsoft.com>
gpg: no running gpg-agent - starting '/usr/bin/gpg-agent'
gpg: waiting for the agent to come up ... (5s)
gpg: connection to agent established
OK
$ sudo apt-key list EB3E94ADBE1229CF
pub   rsa2048 2015-10-28 [SC]
      BC52 8686 B50D 79E3 39D3  721C EB3E 94AD BE12 29CF
uid           [ unknown] Microsoft (Release signing) <gpgsecurity@microsoft.com>
```

**Comment by lucaberti** [comment]
Hello, 
You are quote correct: the problem has been solved  by removing manuelschneid3r.gpg key. I find nevetheless somehow strange that everything worked before installing MS Keys and after removing them.

> Hi @lucaberti, I don't believe this is an issue with `microsoft.asc` being faulty.
> 
> There seems to be couple issues mentioning issues with the `manuelschneid3r.asc.gpg` key (https://askubuntu.com/questions/1246031/gpg-invalid-key-resource-url-following-docker-official-guide, https://github.com/RadeonOpenCompute/ROCm/issues/1254) and other issues mentioning `gpg: invalid key resource URL` (https://serverfault.com/questions/1022078/ubuntu-add-repo-app-key-fails, https://www.linuxliteos.com/forums/other/update-error-lite-welcome/).
> 
> My suggestion is that you remove the `manuelschneid3r` key and try again.
> 
> ```
> $ curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -v -
> gpg: armor header: Version: GnuPG v1.4.7 (GNU/Linux)
> gpg: pub  rsa2048/EB3E94ADBE1229CF 2015-10-28  Microsoft (Release signing) <gpgsecurity@microsoft.com>
> gpg: no running gpg-agent - starting '/usr/bin/gpg-agent'
> gpg: waiting for the agent to come up ... (5s)
> gpg: connection to agent established
> OK
> $ sudo apt-key list EB3E94ADBE1229CF
> pub   rsa2048 2015-10-28 [SC]
>       BC52 8686 B50D 79E3 39D3  721C EB3E 94AD BE12 29CF
> uid           [ unknown] Microsoft (Release signing) <gpgsecurity@microsoft.com>
> ```

**Comment by illfated** [comment]
@lucaberti : Thank you for the nice and quick feedback. Do you consider your issue resolved, that we may close this ticket?

**Comment by lucaberti** [comment]
@illfated Hello, I do think so. I will continue to monitor the situation, though, since the conseuqences of deleting another key could become evident in the future. I that case, I will get back to you.
Best

**Comment by illfated** [comment]
Thanks a lot. Wishing you the best of luck with solving any problems and issues. This ticket will remain searchable after closing, it just appears to be resolved in terms of no longer being an unanswered ticket for the MS Docs team members to respond to. (There is a slight feeling that some team members may have taken time off for the holidays in the U.S. for the time being, it has been a little bit quieter lately around here, so I do my best to see what I can do to offer help when I can.)

Anyway, feel free to return to this ticket even after it has been closed, in case you come across some new information which might be useful to the documentation.

**Comment by illfated** [comment]
#please-close
