### ISSUE TITLE
Images are not examples of descriptions. Incorrect DWORD values for DisabledByDefault

### ISSUE THREAD

**Issue by Emredrum** [MicrosoftDocs/windowsserverdocs#5054]
[Enter feedback here]

Each image used in this document is incorrect.

Before each image it says "The following example shows XXX disabled in the registry:"

However, the images have 2 DWORDS shown with values of 0. This is not an example of disable.

DisabledByDefault value needs to be 1
Enabled values needs to be 0

I would also strongly suggest that the Client key is also added with identical values.

This article was excellent in providing PowerShell Scripts to make this whole thing simple.
https://www.jorgebernhardt.com/disable-ssl-and-tls-on-winserv/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd180142-4c19-8abc-ecce-e4c7e5ac8951
* Version Independent ID: fc5bba87-afad-1729-8f7e-333c73188b73
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @Emredrum, 

Thanks again for contacting Microsoft. We value your feedback. A documentation change has been made surrounding the image examples and will be live after the next business day. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
