### ISSUE TITLE
ADFS Config file

### ISSUE THREAD

**Issue by cloidl** [MicrosoftDocs/windowsserverdocs#5055]
The page references an ADFS Config file, but doesn't specify the path or file name (Microsoft.IdentityServer.Servicehost.exe.config in C:\Windows\ADFS" by default).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cdd5a14-4ae6-fc74-21fa-2e6d2c84eff5
* Version Independent ID: 442f2a9e-7ece-8491-cea0-7c5ae94e4b01
* Content: [Fine Tuning SQL and Addressing Latency Issues with AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/adfs-sql-latency#multiple-artifact-db-support-across-datacenters)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/adfs-sql-latency.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/adfs-sql-latency.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by cloidl** [comment]
Done, Sorry about that. Still trying to get used to GitHub

**Comment by illfated** [comment]
🙂 Fair enough. We have all been there. Thank you for following up and making the ticket overview better. 👍🏻

**Comment by illfated** [comment]
OK, so based on your experience, where would it be reasonably good to add the file information, in your opinion?

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 5028 -b #assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @cloidl,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made with the default path to the config file and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
