### ISSUE TITLE
You need to talk about "slab consolidation" error & "space efficiency" in Optimizer.

### ISSUE THREAD

**Issue by Ergonomicmike** [MicrosoftDocs/windowsserverdocs#5058]
Win10 Home. I have two spinning drivers mirrored in Storage Spaces. (Which report as "thin provisioned space.") 

I was noodling around in Storage Spaces the other day and noticed a Warning about needing to optimize the mirror.

When I run Optimize (a.k.a. defrag") I get an error in Event Viewer that "The storage optimizer couldn't complete slab consolidation on [foo](G:) because: The slab consolidation operation was aborted because an insufficient number of slabs could be reclaimed (based on the limits specified in the registry). (0x89000028)"

I cannot find anything on the Internet about "insufficient number of slabs." 

I can kinda "see" when the error is generated. Optimizer will chunk along at 2 to 3 percent intervals until it gets to about 95%. At which point Optimizer suddenly "completes" (more like fails and stops), jumping to 100% complete.

FWIW, I deleted a bunch of files on the mirror (like, 50% capacity) and I still get this error. (Since I know that conventional degrag needs a certain amount of free space in which to work.)

So now, after Optimizer finishes, it shows me "94% space efficiency." Whereas it used to show 100%

I presume that 94% is not as good as 100%. 

I've seen documentation here saying that "efficiency" for two mirrored drives is 50%. But I don't think this is the same efficiency that Optimize is referring to. Is it?

Also FWIW, I built this mirror in Win 10 Home 1903. Then I did a Refresh update to 1909 and am now at 2004. I offer this because I read that there is a known bug with Storage Spaces and 2004. (Although, fortunately for me, I am still about to use the mirror.)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 375ef18d-2d7f-fd6a-12ea-7a4d8d0a8c80
* Version Independent ID: fcaaf1af-4829-ac36-1617-e71dfd758208
* Content: [Storage Spaces Direct - Frequently asked questions](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/storage-spaces-direct-faq)
* Content Source: [WindowsServerDocs/storage/storage-spaces/storage-spaces-direct-faq.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/storage-spaces-direct-faq.md)
* Product: **windows-server**
* Technology: **storage-spaces**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **kaushik**

**Comment by IngridAtMicrosoft** [comment]
@Ergonomicmike GitHub issues for this repo are for reporting problems with documentation.  For your questions please see https://support.microsoft.com/en-us/windows/storage-spaces-in-windows-b6c8b540-b8d8-fb8a-e7ab-4a75ba11f9f2#WindowsVersion=Windows_10

and for any further questions try https://answers.microsoft.com/en-us/windows/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by no-identd** [comment]
@IngridAtMicrosoft

Technically speaking @Ergonomicmike DID report a documentation issue and requested remediation of it, he 'just' reported it against the wrong documentation, and phrased it in a way where it easily can get misunderstood as a support request. I suspect the correct page against which this should have gotten reported may consist of https://learn.microsoft.com/en-us/windows/compatibility/new-api-allows-apps-to-send-trim-and-unmap-hints, and/or of https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/hh831391(v=ws.11) (and/or the equivalent for client  windows, since Storage Spaces was originally a server-only feature and later added to client OS)
