### ISSUE TITLE
yazılım edl

### ISSUE THREAD

**Issue by karakartal1881** [MicrosoftDocs/windowsserverdocs#5062]
[Geri bildiriminizi buraya girin]

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: d3d97834-a7a2-2e9b-f9fd-1025e038388e
* Version Independent ID: dbf305e8-49e1-c8be-f4fb-d056912c76b9
* Content: [Guarded fabric and shielded VMs](https://docs.microsoft.com/tr-tr/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-and-shielded-vms-top-node)
* Content Source: [WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-and-shielded-vms-top-node.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-and-shielded-vms-top-node.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @rpsqrd
* Microsoft Alias: **ryanpu**

**Comment by illfated** [comment]
"yazılım edl" translates (from Turkish) to "software edl" which I don't quite see what means in this context.

@karakartal1881 : Do you have something specific to report from the document, or is this just a test?

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. As your question isn't tied to any errors within this documentation, we are unable to assist. We're closing this issue but please feel free to reopen it and advise us if any changes are needed to better support your needs. #please-close
