### ISSUE TITLE
Headings with long registry paths don't wrap

### ISSUE THREAD

**Issue by the-ress** [MicrosoftDocs/windowsserverdocs#5064]
Long registry paths in headings don't wrap and there's no horizontal scrollbar.

Example:
![image](https://user-images.githubusercontent.com/1612377/100609911-184a9880-330f-11eb-845e-b3ddc3831393.png)
(The heading should say *"HKLM\SYSTEM\CurrentControlSet\Services\W32Time\TimeProviders\NtpClient" subkey entries*)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d09b16e-4bbb-91fa-3d84-e7623ec4dc07
* Version Independent ID: b6eadad5-0167-34b6-ed3a-16fa7ee83c60
* Content: [Windows Time service tools and settings](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings)
* Content Source: [WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by illfated** [comment]
Thank you for reporting. I noticed that too. On my 24" screen (1920x1200), with the browser maximized, it does not become apparent until I scroll down to the next 2 registry titles:
- **"HKLM\SYSTEM\CurrentControlSet\Services\W32Time\TimeProviders\NtpClient"**
https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings#ntpclient
- **"HKLM\SYSTEM\CurrentControlSet\Services\W32Time\TimeProviders\NtpServer"**
https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings#ntpserver

On my screen, though, it does not disappear as such, but the last key in the registry path submerges under the links in the right-hand section "**In this article**".

My first thought would be to separate the full registry path to a subheading, 1 level below the H3 heading format applied to those titles, leaving only the key names "**TimeProviders\NtpClient**" / "**TimeProviders\NtpServer**" in the H3 heading, but adding the full registry path in the subheading.

Example:

***

### <a id="ntpclient"></a>TimeProviders\NtpClient subkey entries

#### HKLM\SYSTEM\CurrentControlSet\Services\W32Time\TimeProviders\NtpClient

***

### <a id="ntpserver"></a>TimeProviders\NtpServer subkey entries

#### <a id="ntpserver"></a>"HKLM\SYSTEM\CurrentControlSet\Services\W32Time\TimeProviders\NtpServer"

***

Then again, noticing that HTML linking is used for those titles, maybe the existing links can be reduced down from heading format size H3 to H4 ?

@Teresa-Motiv : Any thoughts on this, seeing that the current title size is impractical for full registry paths?

**Comment by Teresa-Motiv** [comment]
This issue should be reassigned--the article is currently being rewritten by another team, and that may resolve this issue.
PR for rewrite is MicrosoftDocs/windowsserverdocs-pr#1751

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. A documentation change was made and changes are live. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
