### ISSUE TITLE
Email discovery obsolete?

### ISSUE THREAD

**Issue by jflieben** [MicrosoftDocs/windowsserverdocs#5067]
It seems this article is now obsolete, as a WVD client sign in now automatically detects what WVD resources I have access to.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca8081a3-ec92-8aa5-2a51-1c10a298fdd1
* Version Independent ID: 6c33184e-2ef8-0b7c-8666-50d4c4b16c7e
* Content: [Set up email discovery to subscribe to your RDS feed](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-email-discovery)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-email-discovery.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-email-discovery.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @ChristianMontoya
* Microsoft Alias: **chrimo**

**Comment by davidbel** [comment]
This article is used for both WVD and RDS. For RDS this still applies. Also, even for WVD it still applies for the non-Windows clients and even on the Windows client, there is an option to subscribe with URL which supports email discovery.

**Comment by illfated** [comment]
@jflieben : Thank you for reporting and suggesting improvements to the documentation.

Does the comment above answer your question?

Please remember, even if an article seems obsolete in your scenario, it may not be obsolete for others.

**Comment by jflieben** [comment]
Yes it does, i thought it was closed already. It could use some clarification in the text though

**Comment by illfated** [comment]
> Yes it does, i thought it was closed already. It could use some clarification in the text though

Thank you for the feedback. Feel free to open a new ticket if you happen to find out how that could be done, suggesting a text or phrasing used elsewhere, so we can update the document. We are always glad to have more feedback from users, especially if it helps us improve the documentation.
