### ISSUE TITLE
Get-NetAdapter

### ISSUE THREAD

**Issue by O365scripts** [MicrosoftDocs/windowsserverdocs#5072]
The link to the Get-NetAdapter is incorrect and should be adjusted in this section:

"Find existing network adapters by running the Get-NetAdapter cmdlet. Make a note of the network adapter name that you want to use for the virtual switch."

https://technet.microsoft.com/library/jj130867.aspx > https://docs.microsoft.com/en-us/powershell/module/network-adapter/get-netadapter (404)

Correct path should be:
https://docs.microsoft.com/en-us/powershell/module/netadapter/get-netadapter?view=win10-ps

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e6f2ad2-2525-dd4f-3e58-3afdf032fd47
* Version Independent ID: 71ba6edc-2be3-ce8f-2930-afa5bf5d61e9
* Content: [Create a virtual switch for Hyper-V virtual machines](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/get-started/create-a-virtual-switch-for-hyper-v-virtual-machines)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/get-started/Create-a-virtual-switch-for-Hyper-V-virtual-machines.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/get-started/Create-a-virtual-switch-for-Hyper-V-virtual-machines.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by illfated** [comment]
Aha, thank you. Good job, nice find. Thank you for providing the solution in addition to reporting the issue.

**Comment by exchange12rocks** [comment]
I think that while it makes sense to replace the link in the documentation, the TechNet Library link should be corrected as well. Because it might be used somewhere else as well

**Comment by illfated** [comment]
Good call. I will make the necessary changes. Thank you for the tip.

**Comment by illfated** [comment]
@exchange12rocks : By the way, are you suggesting to look for the same link in the other Docs pages as well, and correct as many of them as possible, adding those pages to the same PR? From what I can see, the TechNet Library link correction for this specific page is already suggested in the main ticket comment.

**Comment by illfated** [comment]
There you go. PR #5117 is ready for review, comments, and suggestions.

**Comment by exchange12rocks** [comment]
What I am saying that this ticket should not be closed just when the link on Create-a-virtual-switch-for-Hyper-V-virtual-machines.md is corrected, but only when the TechNet link is corrected as well.

**Comment by illfated** [comment]
Aha. Thank you. Very well, then. I will remove the "Closes" comment in my PR, then.

**Comment by exchange12rocks** [comment]
Thank you @illfated!

**Comment by illfated** [comment]
No problem. I guess I am just slow to draw conclusions some times, but that is part of how high functional autism works.

**Comment by illfated** [comment]
Oh man. I forgot that the commit text inside the PR would work the same way as the PR comment text.

Oh well. I was thinking about making a wider search for technet links anyway from inside my cloned copy on my computer and see how many files I can fit into a PR before it becomes unmanageable.

@exchange12rocks : Any thoughts on how many separate pages to include in a PR to fix old TechNet links and still keep it reasonably manageable?

**Comment by exchange12rocks** [comment]
@illfated I would use one page per PR, because different page might require different reviewers. If the pages are about the same technology and have the same author, then putting them in the same PR shouldn't cause any inconveniences.

**Comment by illfated** [comment]
Thanks. Good advice.
