### ISSUE TITLE
Missing image from this page

### ISSUE THREAD

**Issue by csf6gom** [MicrosoftDocs/windowsserverdocs#5075]
This page states "**The following image illustrates the various layers and their elements**.", but there is no image supporting the text provided.  Please can the intended image be added to this please?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 674208bc-fe92-8cc3-1161-4b03dbc413c8
* Version Independent ID: fea49931-618b-cd10-0b8e-69de1ed330d6
* Content: [Transport Layer Security protocol](https://docs.microsoft.com/en-us/windows-server/security/tls/transport-layer-security-protocol)
* Content Source: [WindowsServerDocs/security/tls/transport-layer-security-protocol.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/transport-layer-security-protocol.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by illfated** [comment]
Hmm. That is a challenging request, although we might be able to dig up a Microsoft-owned image from somewhere.

I just checked the page document history here on GitHub, and it has never contained an image during its ≤ 5 years here with us. I can only assume that the original document author thought to themselves something like "Going to add the image as soon as I have added this next paragraph." and then forgot all about it.

**Comment by illfated** [comment]
Any chance one of the images in this bing.com search result would match the intended "various layers and their elements" in the page text?
- https://www.bing.com/images/search?q=transport-layer-security-protocol+site%3amicrosoft.com&form=HDRSC2&first=1&tsc=ImageBasicHover

**Comment by illfated** [comment]
There are also alternate views to look for specific images, like "**Transport Layer Diagram site:microsoft.com**":
- https://www.bing.com/images/search?q=Transport%20Layer%20Diagram%20site%3Amicrosoft.com&qs=n&form=QBIR&sp=-1&pq=transport%20layer%20diagram%20site%3Amicrosoft.com&sc=0-42&cvid=653E8A28C05B47DE9C9EF31A22CCAB19&ajf=60&first=1&tsc=ImageBasicHover

"**Transport Layer OSI Model site:microsoft.com**":
- https://www.bing.com/images/search?q=Transport+Layer+OSI+Model+site%3Amicrosoft.com&qs=n&form=QBIR&sp=-1&pq=transport+layer+osi+model+site%3Amicrosoft.com&sc=0-44&cvid=6729BC697C2A40B0A67F23EF1290EE5C&first=1&tsc=ImageBasicHover

**Comment by IngridAtMicrosoft** [comment]
Addressed with another issue and PR.
