### ISSUE TITLE
Documentation for nltest command is missing

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/windowsserverdocs#5077]
Expected behavior: Page has link to documentation for nltest command.
Observed behavior: Page does not have link to documentation for nltest command.
Fix needed: Add link to documentation for nltest command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d382ca0-6538-5e1d-3e83-e31c9ab6a911
* Version Independent ID: 11eff296-6158-f89a-4941-8735529183e9
* Content: [Windows commands](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands)
* Content Source: [WindowsServerDocs/administration/windows-commands/windows-commands.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/windows-commands.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
&#9432; We're no longer updating this content regularly. Check the [Microsoft Product Lifecycle](https://docs.microsoft.com/en-us/lifecycle/products) for information about how this product, service, technology, or API is supported.

## Nltest

Applies To: Windows Server 2003, Windows Server 2008, Windows Server 2003 R2, Windows Server 2008 R2, Windows Server 2012, Windows Server 2003 with SP1, Windows 8

- https://docs.microsoft.com/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc731935(v=ws.11)

**Comment by rossmpersonal** [comment]
This ticket is about https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands and not https://docs.microsoft.com/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc731935(v=ws.11) . You are correct that https://docs.microsoft.com/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc731935(v=ws.11) is no longer being updated per the Microsoft Product Lifecycle. However, this ticket is not about https://docs.microsoft.com/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc731935(v=ws.11) and https://docs.microsoft.com/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc731935(v=ws.11) is not relevant to this ticket.

nltest is a command in Windows Server 2016 and possibly later versions. Documentation for Windows Server 2016 is still supported and is still being updated regularly per the Microsoft Product Lifecycle. Therefore, documentation for nltest should exist at https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands but is missing. This needs to be fixed.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @rossmpersonal, 

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding the **nltest** command and will be live after the next business day. We are aware that some Windows Commands no longer appear in this list in favor of their PowerShell counterparts found in our [Active Directory PowerShell Modules](https://docs.microsoft.com/en-us/powershell/module/activedirectory/?view=windowsserver2022-ps) reference article. 

We are encouraging our users to adopt PowerShell in place of Windows Commands for these commands and potentially more in the future. We will be closing this as resolved. Thank you and have a most pleasant day. 

#please-close
