### ISSUE TITLE
Ubuntu 20.10 apt-key is deprecated AND does not work

### ISSUE THREAD

**Issue by tgmoo** [MicrosoftDocs/windowsserverdocs#5078]
[The instructions cannot be followed on  Ubuntu 20.10 (GNU/Linux 5.8.0-1006-raspi aarch64) as the apt-get commands do not work.  Some earlier reports online suggested that the deprecation was just a warning and that the command worked.  It is not working on this version of Ubuntu.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25943cc5-9927-5ca7-b9db-4c1d398726c5
* Version Independent ID: ae5bf48b-26cf-b5c8-22c8-68fa9a70258f
* Content: [Linux Software Repository for Microsoft Products](https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software)
* Content Source: [WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @victorcheng7
* Microsoft Alias: **vichen**

**Comment by illfated** [comment]
@konstruktoid : This looks like something you would know more about than me. 
Is this something we could check out to improve the document?

**Comment by konstruktoid** [comment]
Hi @tgmoo, are you perhaps running a Raspberry Pi (`GNU/Linux 5.8.0-1006-raspi aarch64`)?
If so, ARM isn't supported.
If you're not running on ARM, please provide information on which platform and distribution version.

**Comment by illfated** [comment]
Thanks a lot. I was unaware of those options (although when I look at the Linux version string now, it does look like it refers to Raspberry Pi.

Possibly lost cause, I assume.

**Comment by IngridAtMicrosoft** [comment]
#please-close
