### ISSUE TITLE
Update suggestion of OpenSSHUtils

### ISSUE THREAD

**Issue by aamir0** [MicrosoftDocs/windowsserverdocs#5080]
This page mentions installing OpenSSHUtils, which [appears to be deprecated](https://github.com/MicrosoftDocs/windowsserverdocs/issues/3806).

I'm also unable to install it from an elevated command prompt, which may or may not be related:

```
➜  ~ Install-Module -Force OpenSSHUtils -Scope AllUsers
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'OpenSSHUtils'. Try Get-PSRepository to see all available registered module repositories.
At C:\program files\powershell\6\Modules\PowerShellGet\PSModule.psm1:9508 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Microsoft.PowerShel\u2026lets.InstallPackage:InstallPackage) [Install-Package], Exception
+ FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

```
➜  ~ Get-PSRepository

Name                      InstallationPolicy   SourceLocation
----                      ------------------   --------------
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH key management for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by aamir0** [comment]
Never mind, I see this is a duplicate

**Comment by illfated** [comment]
Fair point. Thanks for checking and closing.
- https://github.com/MicrosoftDocs/windowsserverdocs/issues?utf8=%E2%9C%93&q=%221e4b742e-d999-2c1e-a396-dc149f7ac76b%22&in=body
