### ISSUE TITLE
Wrong parameter in w32tm example configuration command line

### ISSUE THREAD

**Issue by lupo49** [MicrosoftDocs/windowsserverdocs#5083]
The example line 
`w32tm /config /manualpeerlist:"ntpserver.contoso.com,0x8 clock.adatum.com,0xa" /syncfromflags:manual /update`
shows a paramter "0xa". According to the parameter list it should be "0x02" (UseAsFallbackOnly)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d09b16e-4bbb-91fa-3d84-e7623ec4dc07
* Version Independent ID: b6eadad5-0167-34b6-ed3a-16fa7ee83c60
* Content: [Windows Time service tools and settings](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings#using-group-policy-to-configure-the-windows-time-service)
* Content Source: [WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by lupo49** [comment]
My issue. 0xa is the combination of the flags "0x2" (UseAsFallbackOnly) and "0x8" (Client)

**Comment by illfated** [comment]
Thank you for the feedback and for closing with an explanation. Nicely done.
