### ISSUE TITLE
missing important parameter on Initialize-Cluster powershell command for installing to existing forest

### ISSUE THREAD

**Issue by k3for** [MicrosoftDocs/windowsserverdocs#5099]
The PowerShell for the Initialize-Cluster command IS MISSING AN IMPORTANT PARAMETER:
-ClusterName "MyHGSClusterName"

without this, a random cluster name (number suffix) is inserted, and you will get a cluster operation terminated / error occured.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ae25db7-fa78-b9bd-463c-a6debe7387f9
* Version Independent ID: 9384ad42-9e6a-ecd6-b07f-7baf55cbe4eb
* Content: [Initialize the HGS cluster using TPM mode in a bastion forest](https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-initialize-hgs-tpm-mode-bastion)
* Content Source: [WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-initialize-hgs-tpm-mode-bastion.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-initialize-hgs-tpm-mode-bastion.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @rpsqrd
* Microsoft Alias: **ryanpu**

**Comment by illfated** [comment]
Thank you for noticing and reporting that critical detail. I will open a pull request to have that parameter added.

BTW, is the order of appearance important for any of the parameters? 
Or is it up to the admins to order the parameters (along with their values) in any order they choose?

**Comment by illfated** [comment]
Also ref. https://docs.microsoft.com/powershell/module/hgsserver/initialize-hgsserver

**Comment by illfated** [comment]
Never mind. I will add it as first parameter, just to make it obvious to the current page author (owner), to get feedback in the PR in case it matters at all.

**Comment by illfated** [comment]
There you go. PR #5108 is ready for review, comments, etc. This ticket will close automatically upon PR merge.

**Comment by k3for** [comment]
parameter order not important

**Comment by illfated** [comment]
Thanks. Duly noted. Feel free to comment in the PR if you like.

**Comment by illfated** [comment]
New year, new attempt. Taking the chance that it will be more stable this time.

**Comment by illfated** [comment]
There you go. PR #5163 is ready for review, comments, and suggestions.

**Comment by k3for** [comment]
I don't know what happened here - it didn't get fixed - will resubmit.
