### ISSUE TITLE
Spacer images visible in "Dark" theme

### ISSUE THREAD

**Issue by chrisbrownie** [MicrosoftDocs/windowsserverdocs#511]
When using the "Dark" docs theme, the `spacer1.png` images are visible. 

![image](https://user-images.githubusercontent.com/5036744/37751114-920d2f08-2de4-11e8-9f80-dbbf395f332f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0af97c26-de04-babc-589e-d9b2978db231
* Version Independent ID: 6c6290e1-0a76-8566-7304-a60b6c38f728
* Content: [Microsoft Project Honolulu](https://docs.microsoft.com/en-us/windows-server/manage/honolulu/honolulu#feedback)
* Content Source: [WindowsServerDocs/manage/honolulu/honolulu.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/honolulu/honolulu.md)
* Service: **unspecified**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Page has changed because Project Honolulu is now known as **Windows Admin Center**. Images have changed too, so the reported issue is no longer part of the page.

**Comment by illfated** [comment]
#please-close
