### ISSUE TITLE
Wsusutil configuresslcertificateName

### ISSUE THREAD

**Issue by matziq** [MicrosoftDocs/windowsserverdocs#5113]
https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/deploy/2-configure-wsus#to-configure-ssl-on-the-wsus-root-server

Wsusutil configuresslcertificateName

needs a space between configuressl and certificatename

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85eb6a21-2659-019a-71ab-66f2e3a7f474
* Version Independent ID: ee2ab576-3c19-15a5-8c41-29a00275614b
* Content: [Step 2 - Configure WSUS](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/deploy/2-configure-wsus)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/deploy/2-configure-wsus.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/deploy/2-configure-wsus.md)
* Product: **windows-server**
* Technology: **wsus**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
Thank you for noticing and reporting.

Fun fact: MS Docs pages containing odd and weird typos ( like this one ) are easy to trace to other sites, just because the typos don't occur in any other documents.

**Comment by illfated** [comment]
OK, I will go ahead and make a PR to correct that typo, as well as looking for other improvement details.

**Comment by illfated** [comment]
There you go. PR #5114 is ready for review, comments, and suggestions. Welcome.
