### ISSUE TITLE
Please remove trailing slash

### ISSUE THREAD

**Issue by yutopio** [MicrosoftDocs/windowsserverdocs#5122]
On line 35, please remove the trailing slash from the text, "To wipe the free space on drive C, type:\" because this causes localization error in other language version. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3812dfb-f308-4556-c90c-856a77e9b1ae
* Version Independent ID: c1d1c8d4-ec53-8463-e24d-c7258e2d4a58
* Content: [manage-bde wipefreespace](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/manage-bde-wipefreespace#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/manage-bde-wipefreespace.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/manage-bde-wipefreespace.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by eross-msft** [comment]
@yutopio  I've corrected this file and it will go live with tomorrow morning's publish. Thank you for catching it!
