### ISSUE TITLE
Important flash is not there 

### ISSUE THREAD

**Issue by babulfir** [MicrosoftDocs/windowsserverdocs#5123]
<outputvolumeorimage> | Identifies the drive on which to store the content of the repaired drive. All information on the output drive will be overwritten.
-- | --

recently we follow the document to perform the repair-bde, and we did not know that this process will overwrite the data. even though you mentioned in your article but some how i missed watching this and eventually we lost the data. later referred from another article the statement was very clear. can you update this information in a blue box so that we can avoid data loss in the future. I mean others will not do the same mistake

source: https://www.eightforums.com/threads/bitlocker-repair-tool-recover-drive-in-windows-7-and-8.21714/?__cf_chl_jschl_tk__=0304ea5eecc9b48f517a4dab46e635ca1b301c8d-1608016033-0-ARnwZ2xbXbvWQkhvAlmj0ugvbyCiC91l_bEEPYdjBJnGt_E1F0sSlGnMEZnBfvgxHHAb3oQewzhWT5aEW1BipApNrbmAU9bcZmXscR628cVEodkIE0HJKwr_xsUeyJdB9JyME9OXJ4Heg-Di1H7R6GRQd7Ta4fbJhWu6TJuxZHUGKnhxhHdlmRunh_DVc0ZD0aCIPZvhbgu4HUYehhbfDqcuoa3c_7Bmj8Lv55GMLk2WF0iZtQPXFkhpn8guDqDfwEp9Bg-TtXJvSU8TtkW7llQpqyV9JavgNGTKmPNaeHMMyBVYBW8RhB3O4xa-Cy1t_eiOeCguS5JeJwNvuQoIO6wuPFMoCG8RVrCMm6jpbQekS8I1Ob6P3czxVdtuMLgFihxPdWzPthVsj7bi8fBTURM 

**You will need to have an empty output volume (drive) of equal or larger size than the damaged BitLocker encrypted drive.** The contents of the output volume will be completely deleted and overwritten by the decrypted contents of the damaged BitLocker drive.r feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4006b303-a81e-8de3-e75e-23dd7d097111
* Version Independent ID: af6d19cc-90f1-38e8-60cd-03b64a97f532
* Content: [repair-bde](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/repair-bde)
* Content Source: [WindowsServerDocs/administration/windows-commands/repair-bde.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/repair-bde.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
Seems like a fair point to make. I will create a suggestion and a Pull Request to have it added to the page.

By the way, I think the message deserves its own Important blob between the Syntax paragraph and the Parameters table.

**Comment by illfated** [comment]
There you go. PR #5126 is ready for review, comments, suggestions etc.
