### ISSUE TITLE
Documentation page about using command redirection operators should be added referenced from main page about Windows Commands

### ISSUE THREAD

**Issue by A-Mofi** [MicrosoftDocs/windowsserverdocs#5127]
The command redirection operators `<`, `>`, `>>`, `>&`, `<&` and `|` are used very often on using Windows commands in command shell or in batch files. But there is no page which describes them in this repository of documentations about the Windows commands.

There is the Microsoft documentation page [Using command redirection operators](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-xp/bb490982(v=technet.10)) in the documentations repository of Windows XP which was created from a former TechNet article. Everything described on this old page is still valid for newer versions of Windows.

I think, it would be good to add here a documentation page which explains the usage of the command redirection operators (contents copy of Windows XP documentation page) and reference it from the main page about the Windows commands somewhere above the list of the commands.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d382ca0-6538-5e1d-3e83-e31c9ab6a911
* Version Independent ID: 11eff296-6158-f89a-4941-8735529183e9
* Content: [Windows commands](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands)
* Content Source: [WindowsServerDocs/administration/windows-commands/windows-commands.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/windows-commands.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Thank you for this recommendation. I will see what I can do to make a PR to have that added in some form like you described.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @A-Mofi,

Thanks again for contacting Microsoft. We value your feedback.

A documentation change has been made surrounding the command redirection operators and will be live after the next business day. We will be closing this as resolved. Thank you and have a most pleasant day.

#please-close
