### ISSUE TITLE
Debian repository not supplied.

### ISSUE THREAD

**Issue by meoso** [MicrosoftDocs/windowsserverdocs#5134]
Debian repository instructions not supplied on 
  https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software
 but the product exists in https://packages.microsoft.com/debian/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25943cc5-9927-5ca7-b9db-4c1d398726c5
* Version Independent ID: ae5bf48b-26cf-b5c8-22c8-68fa9a70258f
* Content: [Linux Software Repository for Microsoft Products](https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software)
* Content Source: [WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @victorcheng7
* Microsoft Alias: **vichen**

**Comment by illfated** [comment]
@konstruktoid : Would you like to verify this statement?

**Comment by konstruktoid** [comment]
Yeah, that's correct. Not all distributions available in the repo (https://packages.microsoft.com/config/) are shown with examples on the page.
I don't know if it would help if we showed _all_ examples, perhaps an instruction about the availability of other distros would be enough.

**Comment by illfated** [comment]
I also think it will be necessary to add some text saying whether the additional distros are supported or not.

**Comment by konstruktoid** [comment]
Related: #3635

**Comment by illfated** [comment]
(ref. #5169 )

**Comment by sethmanheim** [comment]
Closing per #5169
