### ISSUE TITLE
sshd fails to start

### ISSUE THREAD

**Issue by brucejo75** [MicrosoftDocs/windowsserverdocs#5135]
I have `OpenSSH.Server` installed, but `sshd` fails to start.

-`Powershell` is running as administrator.

## Repro steps
```powershell
PS D:\Software> Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'


Name  : OpenSSH.Client~~~~0.0.1.0
State : Installed

Name  : OpenSSH.Server~~~~0.0.1.0
State : Installed

PS D:\Software> Start-service sshd
Start-service : Failed to start service 'OpenSSH SSH Server (sshd)'.
At line:1 char:1
+ Start-service sshd
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand
```

## System Event Log:
`The OpenSSH SSH Server service terminated unexpectedly.`

## Firewall Settings look odd:
![SSHD FireWall Settings](https://user-images.githubusercontent.com/14342237/102535856-a5a32200-405d-11eb-9626-703878709cb2.jpg)

As a test I disabled all rules except for 1 of the private `sshd` rules.  Still failed.

Any help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Installation of OpenSSH For Windows Server](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by illfated** [comment]
@konstruktoid : Do you have any ideas about this? Or should we refer to some support instance?

**Comment by brucejo75** [comment]
I have no idea, I guess I need support.  thanks!

**Comment by konstruktoid** [comment]
Without any error logs I can't really assist. Anything in EventViewer?

**Comment by brucejo75** [comment]
yes, from my original [comment](https://github.com/MicrosoftDocs/windowsserverdocs/issues/5135#issue-770322212):

> The OpenSSH SSH Server service terminated unexpectedly.

Can I turn on other logging?

**Comment by illfated** [comment]
```PowerShell
PS C:\WINDOWS\system32> Get-Service sshd

Status   Name               DisplayName
------   ----               -----------
Stopped  sshd               OpenSSH SSH Server


PS C:\WINDOWS\system32> sshd --help
unknown option -- -

OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
usage: sshd [-46DdeiqTt] [-C connection_spec] [-c host_cert_file]
            [-E log_file] [-f config_file] [-g login_grace_time]
            [-h host_key_file] [-o option] [-p port] [-u len]

PS C:\WINDOWS\system32>_

**Comment by konstruktoid** [comment]
`The OpenSSH SSH Server service terminated unexpectedly.` won't tell us about the root cause, and I don't know enough about logging on Windows on how to turn that into a useful message.

**Comment by brucejo75** [comment]
Hi,

Thanks for your comments!

I think I found the relevant event logs with more useful information.
Under `Applications and Services Logs -> OpenSSH -> Admin`.

I get the following errors sequentially:
1. `sshd: error: Bind to port 22 on :: failed: Permission denied.`
2. `sshd: error: Bind to port 22 on 0.0.0.0 failed: Permission denied.`
3. `sshd: fatal: Cannot bind any address.`

**Note**: I run my powershell window as administrator.

This is my hosts file  at `C:\Windows\System32\drivers\etc\hosts` (dunno if it helps):
```
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#       127.0.0.1       localhost
#       ::1             localhost
127.0.0.1 blocked-your-system-61.gq
192.168.1.99 MEDIA mpc
172.18.168.97 vm.lcl
192.168.1.112 mac
192.168.1.100 devpc.ip
```

**Comment by konstruktoid** [comment]
Thanks @brucejo75, can you verify you user with `whoami` before starting `sshd`?
If you are a system user, could you please step through https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting-Steps?

**Comment by brucejo75** [comment]
Could this have anything to do with the multitude of inbound rules I have for sshd & OpenSSH?

- Configured the `sshd_config` file, added:
```
SyslogFacility LOCAL0
LogLevel DEBUG
```

Here is the result of running the commands:
```powershell
PS C:\ProgramData\ssh> whoami
devpc\admin
PS C:\ProgramData\ssh> Stop-Service sshd
PS C:\ProgramData\ssh> psexec -s sshd.exe -d

PsExec v2.2 - Execute processes remotely
Copyright (C) 2001-2016 Mark Russinovich
Sysinternals - www.sysinternals.com


debug1: sshd version OpenSSH_for_Windows_7.7, LibreSSL 2.6.5
debug1: private host key #0: ssh-rsa SHA256:hXx1JyZ5YwFXwYkMLJ1R0CT2mBF4jACpu82Ime81bOg
debug1: private host key #1: ecdsa-sha2-nistp256 SHA256:oSfbiqRznCHFPCdW+g5uSY3Jxd9V8EgqOgNtU0hxM9E
debug1: private host key #2: ssh-ed25519 SHA256:b3xydKOH5a8eZ+dnpWL5uK2c41BLb859snWDv+PTDNE
debug1: rexec_argv[0]='sshd.exe'
debug1: rexec_argv[1]='-d'
debug1: Bind to port 22 on ::.
Bind to port 22 on :: failed: Permission denied.
debug1: Bind to port 22 on 0.0.0.0.
Bind to port 22 on 0.0.0.0 failed: Permission denied.
Cannot bind any address.
sshd.exe exited on DEVPC with error code 255.
```

No log files are output.

Should I move my issue over here: https://github.com/powershell/Win32-OpenSSH/issues?

**Comment by illfated** [comment]
> Could this have anything to do with the multitude of inbound rules I have for sshd & OpenSSH?

Possibly. Maybe there are some recommended ways to set specific rules for its use. Myself, I don't have the required experience to know the answer.

(part of the log omitted)

> ```PowerShell
> debug1: Bind to port 22 on ::.
> Bind to port 22 on :: failed: Permission denied.
> debug1: Bind to port 22 on 0.0.0.0.
> Bind to port 22 on 0.0.0.0 failed: Permission denied.
> Cannot bind any address.
> sshd.exe exited on DEVPC with error code 255.
> ```
> 
> No log files are output.
> 
> Should I move my issue over here: [powershell/Win32-OpenSSH/issues](https://github.com/powershell/Win32-OpenSSH/issues)?

Looks like a good idea to me. I am hopeful that they may have more experience with proper usage and setup of OpenSSH in a Windows environment.

**Comment by brucejo75** [comment]
Closing...
