### ISSUE TITLE
Compact documentation out of date/incomplete

### ISSUE THREAD

**Issue by Archov** [MicrosoftDocs/windowsserverdocs#5139]
the page listing info on Compact doesn't show all of the arguments possible, you get more complete information by typing "compact /?" in CMD. Would be great if it was updated as complete.

![image](https://user-images.githubusercontent.com/21347464/102701927-01b6a380-4222-11eb-8a4b-d27eed4b0508.png)
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eaddfdd0-36f0-5188-4ccc-534227c91149
* Version Independent ID: 9a9901e1-9c4c-c623-936d-e55de1c22dbe
* Content: [compact](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/compact)
* Content Source: [WindowsServerDocs/administration/windows-commands/compact.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/compact.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
Output from the command `compact /?` on a Windows Server 2016 Standard, production server:
```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Administrator>compact /?
Displays or alters the compression of files on NTFS partitions.

COMPACT [/C | /U] [/S[:dir]] [/A] [/I] [/F] [/Q] [/EXE[:algorithm]]
        [/CompactOs[:option] [/WinDir:dir]] [filename [...]]

  /C         Compresses the specified files.  Directories will be marked
             so that files added afterward will be compressed unless /EXE
             is specified.
  /U         Uncompresses the specified files.  Directories will be marked
             so that files added afterward will not be compressed.  If
             /EXE is specified, only files compressed as executables will
             be uncompressed; if this is omitted, only NTFS compressed
             files will be uncompressed.
  /S         Performs the specified operation on files in the given
             directory and all subdirectories.  Default "dir" is the
             current directory.
  /A         Displays files with the hidden or system attributes.  These
             files are omitted by default.
  /I         Continues performing the specified operation even after errors
             have occurred.  By default, COMPACT stops when an error is
             encountered.
  /F         Forces the compress operation on all specified files, even
             those which are already compressed.  Already-compressed files
             are skipped by default.
  /Q         Reports only the most essential information.
  /EXE       Use compression optimized for executable files which are read
             frequently and not modified.  Supported algorithms are:
             XPRESS4K  (fastest) (default)
             XPRESS8K
             XPRESS16K
             LZX       (most compact)
  /CompactOs Set or query the system's compression state.  Supported options are:
             query  - Query the system's Compact state.
             always - Compress all OS binaries and set the system state to Compact
                      which remains unless administrator changes it.
             never  - Uncompress all OS binaries and set the system state to non
                      Compact which remains unless administrator changes it.
  /WinDir    Used with /CompactOs:query, when querying the offline OS. Specifies
             the directory where Windows is installed.
  filename   Specifies a pattern, file, or directory.

  Used without parameters, COMPACT displays the compression state of
  the current directory and any files it contains. You may use multiple
  filenames and wildcards.  You must put spaces between multiple
  parameters.

C:\Users\Administrator>_
```
While I agree that the **Windows Server > Windows Commands > Commands by Server Role** section could be useful to have updated content to match the supported versions and their help texts, I also see that the current content is inherited from way older Windows Server versions (Windows 2000 or Windows NT 4) as well as being written to contain a bare minimum only to be used for simple reference, not for comprehensive help documentation use.

**Comment by eross-msft** [comment]
@Archov @illfated  I can update the compact options and text, based on what you have above. It won't be for a few days, but I'll get to it as soon as I can. Thank you for including the text here, it's much appreciated.

With that being said, this reference content is slow to update since there are no actual owners of the articles. Because of that, we always recommend looking at the command line help included with the option, it will almost always be more complete and current.

**Comment by eross-msft** [comment]
Closing since it will be addressed this week.  #please-close
