### ISSUE TITLE
WSL for fsutil?

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/windowsserverdocs#5143]
"You must enable Windows Subsystem for Linux before you can run fsutil."

I don't have WSL but I do have fsutil.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18562b49-3654-a3ff-9617-3c59d50a7d1e
* Version Independent ID: 3e69bcb1-b1e6-f0ea-e861-5ced88fe6a24
* Content: [fsutil](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil)
* Content Source: [WindowsServerDocs/administration/windows-commands/fsutil.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/fsutil.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @toklima
* Microsoft Alias: **toklima**

**Comment by illfated** [comment]
> "You must enable Windows Subsystem for Linux before you can run fsutil."
> 
> I don't have WSL but I do have fsutil.

You are probably correct, I haven't had the pleasure of using `fsutil` myself. Have you tried using it to perform any tasks, like using any of the parameters or any specific structured `fsutil` command to achieve something practical, without having WSL installed? (You might be able to, I don't know.)

BTW, I am mostly answering here now because I know that it may take quite some time before someone follows up tickets not directly stating what should be corrected in the MS Server Docs, unless there is a good reference to correct information, preferably MS sources.

**Comment by BR77BE** [comment]
@illfated 

Thanks for the response.

Yes, I can perform fsutil functions without WSL.

What should be corrected is the deletion of the following, as it is evidently untrue:

> "You must enable Windows Subsystem for Linux before you can run fsutil. Run the following command as Administrator in PowerShell to enable this optional feature:
> 
> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
> 
> You'll be prompted to restart your computer once it's installed. After your computer restarts, you'll be able to run Fsutil as an administrator."

**Comment by illfated** [comment]
I am thinking much of the same, especially when looking at other references like stackoverflow.com, ss64.com and other places, it is often not referred to using a Linux subsystem at all to run `fsutil`:
- https://stackoverflow.com/questions/1893200/why-fsutil-exe-takes-less-time-to-write-a-huge-file-into-disk-than-programmatica
- https://ss64.com/nt/fsutil.html

Still, it feels like there should be some form of text describing when you need WSL and when you don't need it. I admit that I don't have the required experience myself, yet.

Even on Windows 10 Home x64, Version 20H2 (OS Build 19042.685):
```
Microsoft Windows [Version 10.0.19042.685]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\illfated>fsutil
---- Commands Supported ----

8dot3name         8dot3name management
behavior          Control file system behavior
dax               Dax volume management
dirty             Manage volume dirty bit
file              File specific commands
fsInfo            File system information
hardlink          Hardlink management
objectID          Object ID management
quota             Quota management
repair            Self healing management
reparsePoint      Reparse point management
storageReserve    Storage Reserve management
resource          Transactional Resource Manager management
sparse            Sparse file control
tiering           Storage tiering property management
transaction       Transaction management
usn               USN management
volume            Volume management
wim               Transparent wim hosting management

C:\Users\illfated>_
```

**Comment by illfated** [comment]
Would be very interesting to see if any complex `fsutil` commands are not available on Windows without WSL, only being member of the Windows Administrators group.

**Comment by illfated** [comment]
Just for your information (FYI): The holiday season may delay any feedback from the MS Docs team members and document authors.

**Comment by Xelu86** [comment]
Hey @BR77BE,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made removing this from the note as WSL is not a dependancy for `fsutil` to run. Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
