### ISSUE TITLE
Hyper-v2019 vm nic objects limit is 8, not 64!

### ISSUE THREAD

**Issue by ilRobbi** [MicrosoftDocs/windowsserverdocs#5147]
Hello,

I've a lab env. hyper-v 2019 and I need to add 16 nic (external) to a vm that acts as a firewall; after the eighth nic a message displays that I've reached the maximum number of network adapter object.

The docs says 64 nic, that is not true.

Regards,
Roberto.

![Immagine](https://user-images.githubusercontent.com/76570731/103105985-fc969180-4631-11eb-93ab-23e13433bdf4.png)

![Immagine](https://user-images.githubusercontent.com/76570731/103105997-2354c800-4632-11eb-9ebb-b4ce7d9e2961.png)

![Immagine](https://user-images.githubusercontent.com/76570731/103105933-724e2d80-4631-11eb-8c40-ffdd774e7daa.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51695048-f8f8-c2c1-89ff-dc3614f9d3d8
* Version Independent ID: 372b149c-9a75-7db5-f8fd-4820e7b05b35
* Content: [Plan for Hyper-V scalability in Windows Server 2016 and Windows Server 2019](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/plan/plan-hyper-v-scalability-in-windows-server)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/plan/plan-hyper-v-scalability-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/plan/plan-hyper-v-scalability-in-windows-server.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by ilRobbi** [comment]
Hello again!

Issue can be closed, after a windows updates os's build has changed to:

![image](https://user-images.githubusercontent.com/76570731/106215310-f1a2c400-61d0-11eb-8b56-8bafa07c92fa.png)

now I can add more than 16 nic objects! Haven't check the limit, but I think that the guide IS CORRECT!

My mistake, forgive me!
Roberto

**Comment by illfated** [comment]
OK, thank you for the update & feedback.

**Comment by ilRobbi** [comment]
Just for who has the same problem, the discriminating factor isn't the os build, but the "hw generation" of vm!
Gen 1 support "only" 8 nic... in my case Checkpoint's virtual appliances (also on latest R81 version) doesn't support Gen 2 hw vm.
Maybe it would be appropriate to highlight  this difference between gen 1 and gen 2 in the documentation.
Bye,
Roberto

**Comment by illfated** [comment]
Fair point. We may need an open ticket for that addition, though (feel free to reopen this ticket if you find it is needed, or open a new one). Feel free to suggest the phrasing we could use in a style consistent with the document (I could use some help with the phrasing, since this topic is outside of the extent of my experience).
