### ISSUE TITLE
Change in xcopy beavior after 20H2 Win10Pro update

### ISSUE THREAD

**Issue by jada4p** [MicrosoftDocs/windowsserverdocs#5149]
To back my data I created simple script (bat file), part of which is:

set Anc=ancestry\save
xcopy C:\%Anc% %BackupTarget%%BackupDate%\%Anc% %Flags%

Running this script above lines translate into (user name changed -;)

set Anc=Ancestry\save
C:\Users\xxxxxx\Desktop>xcopy E:\Ancestry\save F:\backups\magrata\20201208\Ancestry\save /I /F /H /K /Y /C /D /R

The xcopy command creates Ancestry directory, but did’nt copy the save subdirectory, even though it is not empty

E:\>dir Ancestry\save /s
Volume in drive E is Pracovni2qitek
Volume Serial Number is C812-E3FB

Directory of E:\Ancestry\save

04.11.2020 12:36 <DIR> .
04.11.2020 12:36 <DIR> ..
27.02.2016 16:20 55 074 rKV.jpg
27.02.2016 16:21 1 727 rKV.rodz
2 File(s) 56 801 bytes

Thus listing of backup structure is:

F:\backups\magrata\20201208>dir Ancestry /s
Volume in drive F is ZalohyMagrataDocs
Volume Serial Number is 0046-4A76

Directory of F:\backups\magrata\20201208\Ancestry

08.12.2020 17:33 <DIR> .
08.12.2020 17:33 <DIR> ..
0 File(s) 0 bytes

Whereas simmilar structure created on 20201018 shows

F:\backups\magrata\20201018>dir Ancestry /s
Volume in drive F is ZalohyMagrataDocs
Volume Serial Number is 0046-4A76

Directory of F:\backups\magrata\20201018\Ancestry

18.10.2020 11:21 <DIR> .
18.10.2020 11:21 <DIR> ..
18.10.2020 11:21 <DIR> save
0 File(s) 0 bytes

Directory of F:\backups\magrata\20201018\Ancestry\save

18.10.2020 11:21 <DIR> .
18.10.2020 11:21 <DIR> ..
27.02.2016 16:20 55 074 rKV.jpg
27.02.2016 16:21 1 727 rKV.rodz
2 File(s) 56 801 bytes

Where could the problem be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a1e859-b436-290e-69c0-810dd3a5ce90
* Version Independent ID: 10c81289-2bf7-40d9-39ea-e624cf92aa3e
* Content: [xcopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/xcopy#examples)
* Content Source: [WindowsServerDocs/administration/windows-commands/xcopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/xcopy.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
Parameters used in your example: `/I /F /H /K /Y /C /D /R`

Those parameters from the MS Docs reference page:

| Parameter | Description |
| :-------: | :---------- |
| /i | If Source is a directory or contains wildcards and Destination does not exist, xcopy assumes Destination specifies a directory name and creates a new directory. Then, xcopy copies all specified files into the new directory. By default, xcopy prompts you to specify whether Destination is a file or a directory. |
| /f | Displays source and destination file names while copying. |
| /h | Copies files with hidden and system file attributes. By default, xcopy does not copy hidden or system files |
| /k | Copies files and retains the read-only attribute on Destination files if present on the Source files. By default, xcopy removes the read-only attribute. |
| /y | Suppresses prompting to confirm that you want to overwrite an existing destination file. |
| /c | Ignores errors. |
| /d [:MM-DD-YYYY] | Copies source files changed on or after the specified date only. If you do not include a MM-DD-YYYY value, xcopy copies all Source files that are newer than existing Destination files. This command-line option allows you to update files that have changed. |
| /r | Copies read-only files. |

<details>
<summary>Output from xcopy /? Windows 10 Version 20H2 (OS Build 19042.685) (click anywhere on this line to view the collapsed content)</summary>

```
Microsoft Windows [Version 10.0.19042.685]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\illfated>xcopy /?
Copies files and directory trees.

XCOPY source [destination] [/A | /M] [/D[:date]] [/P] [/S [/E]] [/V] [/W]
                           [/C] [/I] [/Q] [/F] [/L] [/G] [/H] [/R] [/T] [/U]
                           [/K] [/N] [/O] [/X] [/Y] [/-Y] [/Z] [/B] [/J]
                           [/EXCLUDE:file1[+file2][+file3]...] [/COMPRESS]

  source       Specifies the file(s) to copy.
  destination  Specifies the location and/or name of new files.
  /A           Copies only files with the archive attribute set,
               doesn't change the attribute.
  /M           Copies only files with the archive attribute set,
               turns off the archive attribute.
  /D:m-d-y     Copies files changed on or after the specified date.
               If no date is given, copies only those files whose
               source time is newer than the destination time.
  /EXCLUDE:file1[+file2][+file3]...
               Specifies a list of files containing strings.  Each string
               should be in a separate line in the files.  When any of the
               strings match any part of the absolute path of the file to be
               copied, that file will be excluded from being copied.  For
               example, specifying a string like \obj\ or .obj will exclude
               all files underneath the directory obj or all files with the
               .obj extension respectively.
  /P           Prompts you before creating each destination file.
  /S           Copies directories and subdirectories except empty ones.
  /E           Copies directories and subdirectories, including empty ones.
               Same as /S /E. May be used to modify /T.
  /V           Verifies the size of each new file.
  /W           Prompts you to press a key before copying.
  /C           Continues copying even if errors occur.
  /I           If destination does not exist and copying more than one file,
               assumes that destination must be a directory.
  /Q           Does not display file names while copying.
  /F           Displays full source and destination file names while copying.
  /L           Displays files that would be copied.
  /G           Allows the copying of encrypted files to destination that does
               not support encryption.
  /H           Copies hidden and system files also.
  /R           Overwrites read-only files.
  /T           Creates directory structure, but does not copy files. Does not
               include empty directories or subdirectories. /T /E includes
               empty directories and subdirectories.
  /U           Copies only files that already exist in destination.
  /K           Copies attributes. Normal Xcopy will reset read-only attributes.
  /N           Copies using the generated short names.
  /O           Copies file ownership and ACL information.
  /X           Copies file audit settings (implies /O).
  /Y           Suppresses prompting to confirm you want to overwrite an
               existing destination file.
  /-Y          Causes prompting to confirm you want to overwrite an
               existing destination file.
  /Z           Copies networked files in restartable mode.
  /B           Copies the Symbolic Link itself versus the target of the link.
  /J           Copies using unbuffered I/O. Recommended for very large files.
  /COMPRESS    Request network compression during file transfer where
               applicable.

The switch /Y may be preset in the COPYCMD environment variable.
This may be overridden with /-Y on the command line.

C:\Users\illfated>_
```

</details>

Shortened list, to include only those parameters you used in your examples:

```
  /I           If destination does not exist and copying more than one file,
               assumes that destination must be a directory.
  /F           Displays full source and destination file names while copying.
  /H           Copies hidden and system files also.
  /K           Copies attributes. Normal Xcopy will reset read-only attributes.
  /Y           Suppresses prompting to confirm you want to overwrite an
               existing destination file.
  /C           Continues copying even if errors occur.
  /D:m-d-y     Copies files changed on or after the specified date.
               If no date is given, copies only those files whose
               source time is newer than the destination time.
  /R           Overwrites read-only files.
```

**Comment by illfated** [comment]
Hang on. I think I see where you went wrong. You did not include either `/E` or `/S` in your parameter list. That is a user error.


Do yourself a favor and use both `/S` and `/E` at the same time, so you don't forget to include any of them.
I also recommend that you use `/V` to verify that the file copying process ended 100% successfully, even if it takes a bit more time.

See also the ss64.com page for more details regarding the default use of `xcopy` :
- https://ss64.com/nt/xcopy.html

To be perfectly honest, this is something you should have posted in a forum and not in the MS Docs documentation improvement site, unless you wanted to inform the MS Docs team that you have confirmed and verified that there is something wrong in the documentation. Whenever you do have facts showing that the documentation is incorrect or missing important information related to normal or critical use of the documentation, do not hesitate to create a new issue ticket about that document page on MS Docs (docs.microsoft.com).

Allow me to share some information I have collected during my time here on MS Docs on GitHub:

***

Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Other than that, I also suggest that you contact Microsoft Support if you can't find help in the forums, to the extent you have access to Microsoft Support via your Windows 10 licenses.

**Comment by illfated** [comment]
Thank you for checking in with Microsoft Docs to contribute. You are very welcome, just keep in mind the intended functionality of these pages.

In any future contributions, you may also want to learn more about MarkDown and "GitHub Flavored MarkDown" to improve the readability of your tickets.

#sign-off

#please-close

**Comment by illfated** [comment]
#please-close

**Comment by jada4p** [comment]
First of all I apologize to place my question/problem in inappropriate
place... and thanks a lot for your help. I tried to ask on AskWoody forum,
unfortunately up to now there was no real help.

But, unfortunately, it didn't change the situation. Even adding values of
"/S /E" to flags (which I thought are not needed, for I wanted to copy only
this one folder), nothing changed, selected folder (and its content) was
not copied.

Some more explanation. About month ago I replaced my old PC (HP workstation
xw6200, Win 10 Pro 32bit) with new one (HP EliteDesk 705 G4. Win 10 Pro
64bit). I used to back my data, among others, by script (which I tested
until it worked properly) to external 2TB WD disk. After testing there were
no problems, all needed files and folders were backed up OK.

After putting new PC in use I copied old user files/folders to an external
HDD which I later installed in new PC disk cage. Thus all my data are now
accessible from internal HDD, to which, I, as user, have full access (i.e.
I changed properties of drive/folder/files to allow me full access). In
similar way I have full access to backup HDD.

I modified script, which I used before to back my data, to smaller one,
backing only some of them to smaller external disk. It was part of this
script, which I presented as part of my question.

If you are interested in following the problem, I'm enclosing both scripts
(modified to translate comments to english and removing some inappropriate
ones) . NB both Ancestry and Docs folders were not backed :-( by
ZalohaDocsSeagate6GB.bat script.

Moreover. I think something has been really changed... e.g. I used line
   for /F "tokens=2" %%D in ("%DATE%") do set BackupDate=%%D
to get backup date from system, which I had to change to
   for /F "tokens=1" %%D in ("%DATE%") do set BackupDate=%%D
to be able to get it ;-)

Best regards and thanks a lot for all your help! Have a wonderful new year!
Jaromir Pavlinec

On Mon, Dec 28, 2020 at 1:52 AM Trond B. Krokli <notifications@github.com>
wrote:
>
> Hang on. I think I see where you went wrong. You did not include either
/E or /S in your parameter list. That is a user error.
>
> Do yourself a favor and use both /S and /E at the same time, so you don't
forget to include any of them.
> I also recommend that you use /V to verify that the file copying process
ended 100% successfully, even if it takes a bit more time.
>
> See also the ss64.com page for more details regarding the default use of
xcopy :
>
> https://ss64.com/nt/xcopy.html
>
> To be perfectly honest, this is something you should have posted in a
forum and not in the MS Docs documentation improvement site, unless you
wanted to inform the MS Docs team that you have confirmed and verified that
there is something wrong in the documentation. Whenever you do have facts
showing that the documentation is incorrect or missing important
information related to normal or critical use of the documentation, do not
hesitate to create a new issue ticket about that document page on MS Docs (
docs.microsoft.com).
>
> Allow me to share some information I have collected during my time here
on MS Docs on GitHub:
>
> ________________________________
>
> Wish I could help, but this repository is not intended for regular
support issues, support requests or support questions.
>
> You may want to look elsewhere for answers, unless you have suggestions
for improving one or more specific pages in the MS Docs repository.
>
> Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs
teams here on GitHub.
>
> The intention of this repository is to improve on the existing
documentation by providing the users a way to report factual errors,
improvement suggestions and request updates for new versions.
>
> The MS Docs team members might not have time to answer your question,
both due to the small size of the team and the big workload.
>
> Try the following resources to get in touch with users who may be able to
help you:
>
> TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
> MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
> Microsoft Community: https://answers.microsoft.com/
>
> Other than that, I also suggest that you contact Microsoft Support if you
can't find help in the forums, to the extent you have access to Microsoft
Support via your Windows 10 licenses.

**Comment by illfated** [comment]
Fair enough, thanks for the feedback. Likewise, have a very good new year. 🥳

Just a last suggestion: Even if you keep looking for a solution to using your script (which worked on the old computer, but not the new), consider the possibility that the new computer might use more modern data stream handling for faster communication and that a fast scripted backup method could (in theory) be mishandled in some way to cause the process to end in a different way than on an older computer/older OS. You may want to turn on debugging measures, like all verbose output and any logging options.

There is also the faint possibility that you may have to change to a GUI backup method, or a trusted backup script from somewhere else, to get your desired results.
