### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by barsv** [MicrosoftDocs/windowsserverdocs#515]
link for 'Deploy an Active Directory Detached Cluster' leads to 'Install and Configure High Availability Printing'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaf1bffb-8b1e-50d5-84d6-394218757167
* Version Independent ID: a88884da-ad0a-0c71-183e-7fafc8e8e722
* Content: [Failover Clustering](https://docs.microsoft.com/en-us/windows-server/failover-clustering/failover-clustering-overview#deployment)
* Content Source: [WindowsServerDocs/failover-clustering/failover-clustering-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/failover-clustering-overview.md)
* Service: **unspecified**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by lizap** [comment]
Thanks for catching this. I've updated the link - you should see the fix live on the page later on 3/27/18.
