### ISSUE TITLE
Disk Management CPL app removed from WIndows 10 - this page needs updating

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/windowsserverdocs#5155]
This page is no longer accurate - this wizard has been removed.

And so far as I can tell, there is no no GUI way to change drive letters either

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35f8441a-d145-c5ce-36ee-49058d0c09b4
* Version Independent ID: 49a7f4be-4d96-8b7b-537d-3a758d0a4beb
* Content: [Change a drive letter](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/change-a-drive-letter)
* Content Source: [WindowsServerDocs/storage/disk-management/change-a-drive-letter.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/change-a-drive-letter.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Do you have documentation or proof for your statement being the case? It works on my Windows 10 20H2 computer.

![image](https://user-images.githubusercontent.com/38162891/103256956-7f4f8180-498f-11eb-9fa6-619dfeedb51d.png)


![image](https://user-images.githubusercontent.com/38162891/103256998-aefe8980-498f-11eb-9115-24b16e7020e4.png) ![image](https://user-images.githubusercontent.com/38162891/103257337-123ceb80-4991-11eb-80ea-8b5128244d75.png)  ![image](https://user-images.githubusercontent.com/38162891/103257192-83c86a00-4990-11eb-8087-041bbc815ac3.png)


![image](https://user-images.githubusercontent.com/38162891/103258221-99d82980-4994-11eb-9218-4b5fb6c0911e.png)  ![image](https://user-images.githubusercontent.com/38162891/103258185-77461080-4994-11eb-9174-60dbf023fa85.png)


Please note: I am not affiliated with Microsoft or the MS Docs team, although I spend some time contributing.
I just found it hard to be sure that what you are saying is a fact, when I have not noticed it happening.

**Comment by doctordns** [comment]
Thanks for that comment.

**Comment by doctordns** [comment]
It was an mac,not a cpl app. My bad. That being said, the new did management settings app does change things. But once that app is working, this page can be updated. 

Closed.

**Comment by illfated** [comment]
Thank you for the feedback.
