### ISSUE TITLE
"mail filter" wording is not correct here.. its causing confusion

### ISSUE THREAD

**Issue by kekici** [MicrosoftDocs/windowsserverdocs#5158]
[Enter feedback here]

Document including below lines;

"This issue may occur if the packets are dropped during high traffic bursts. Ensure that there is no traffic filtering occurring (for example, with a mail filter). After eliminating this possibility, gradually increase the number of buffers in the guest operating system and verify."

Here we are telling that; MAIL FILTER can cause a package DISCARDs on network layer. This is not technically possible. On network layer a package is just a package never a SMTP nor HTTP package. It's low level thing yet and SMTP/MAIL filtering software's does not understand package meaning. Also mail filtering software's does not work on network layer, they works on application layer and look at traffic as SMTP protocol traffic. So please update above lines like below;

"This issue may occur if the packets are dropped during high traffic bursts. Ensure that there is no traffic filtering occurring (for example, with a package filter). After eliminating this possibility, gradually increase the number of buffers in the guest operating system and verify."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2144e7f4-708a-c9c9-04e9-48631a8448d3
* Version Independent ID: 7acefe4f-73d9-95d1-d2ed-67b96d509355
* Content: [Troubleshooting cluster issue with Event ID 1135](https://docs.microsoft.com/en-us/windows-server/troubleshoot/troubleshooting-cluster-event-id-1135)
* Content Source: [WindowsServerDocs/troubleshoot/troubleshooting-cluster-event-id-1135.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/troubleshoot/troubleshooting-cluster-event-id-1135.md)
* Product: **windows-server**
* Technology: **troubleshoot**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by illfated** [comment]
> So please update above lines like below;
> 
> "This issue may occur if the packets are dropped during high traffic bursts. Ensure that there is no traffic filtering occurring (for example, with a **package** filter). After eliminating this possibility, gradually increase the number of buffers in the guest operating system and verify."

Fair point. I will open a Pull Request to ask for this correction to be made. Thank you for contributing.

**Comment by illfated** [comment]
For other contributors who want to go directly to the referenced paragraph, here is the anchor link:
- https://docs.microsoft.com/en-us/windows-server/troubleshoot/troubleshooting-cluster-event-id-1135#cluster-installed-in-the-vmware-virtualization-platform

**Comment by illfated** [comment]
Derp. I was a bit trigger-happy there and pushed my first commit before checking that all my documented changes were present. Found at least one missing, so I start again with a new commit. BRB.

**Comment by illfated** [comment]
Anyway, at this point in time, I am more than tired of finding issues to fix in that document. Some of them I can't even fix myself.

So here I go again on my own ...  🎵 🎵 🎶 🎵 🎵

**Comment by illfated** [comment]
There you go. PR #5159 is now open for review, comments, and suggestions.
