### ISSUE TITLE
Not being updated?

### ISSUE THREAD

**Issue by CarlFink** [MicrosoftDocs/windowsserverdocs#5164]
Looks as if this has not been updated for the current Ubuntu. Deliberate choice?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25943cc5-9927-5ca7-b9db-4c1d398726c5
* Version Independent ID: ae5bf48b-26cf-b5c8-22c8-68fa9a70258f
* Content: [Linux Software Repository for Microsoft Products](https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software)
* Content Source: [WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/Linux-Package-Repository-for-Microsoft-Software.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @victorcheng7
* Microsoft Alias: **vichen**

**Comment by illfated** [comment]
@CarlFink : Things Take Time. That is true also for this documentation. Unless something is really factually broken, it won't have much priority to be updated.

Do you have suggestions for how the page document can be improved?

**Comment by CarlFink** [comment]
@illfated, the page itself is fine. it's that the repositories haven't been updated that seems odd to me.

**Comment by illfated** [comment]
Very well. Maybe you have got a point. I am not familiar enough with Linux to tell if it is important or not.

@konstruktoid : Can I ask you to comment on this question and the page content?

**Comment by konstruktoid** [comment]
Which version of Ubuntu are you referring to @CarlFink? https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software contains the three latest LTS releases.

**Comment by CarlFink** [comment]
LTS releases, yes. Most desktop users don't appear to use LTS, and 20.10 is very widely used.

If the policy is LTS only, then that's reasonable, and I just didn't realize it.

**Comment by illfated** [comment]
Thank you for the feedback, both of you. Good to get feedback from real users of the software involved.


> If the policy is LTS only, then that's reasonable, and I just didn't realize it.

While I don't know if it is a fact, it is a probable reason. Knowing that the content is for IT Pros and users who often need to use stable long-time solutions, I find it very likely. I guess it would take someone like an influential Microsoft solution user in a sizeable scenario to ask for a useful change to that content. I could be wrong, though.

**Comment by konstruktoid** [comment]
Continuing with what @illfated said; the pages also states that `The Production sub-repository is designated for packages intended for use in production` and in many cases only LTS server releases as classified as such.
Even though the page only lists LTS releases, there are more available at https://packages.microsoft.com/ubuntu

Related issue: https://github.com/MicrosoftDocs/windowsserverdocs/issues/5134

**Comment by konstruktoid** [comment]
Related: #3635

**Comment by sethmanheim** [comment]
Closing per #5169
