### ISSUE TITLE
FoD Offline ISO not available on the Evaluation Site

### ISSUE THREAD

**Issue by tomohulk** [MicrosoftDocs/windowsserverdocs#5165]
Page states that the offline ISO can be downloaded via the Evaluation Center page, I cannot find the ISO anywhere if this is true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0017894c-49f1-6114-28cf-9e27411ee9d8
* Version Independent ID: d871e63a-6ad0-fbda-757f-95baef0301a8
* Content: [Server Core App Compatibility Feature on Demand (FOD)](https://docs.microsoft.com/en-us/windows-server/get-started-19/install-fod-19)
* Content Source: [WindowsServerDocs/get-started-19/install-fod-19.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/install-fod-19.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Maybe it has changed to be available only from the VLSC page or with a Microsoft authenticated customer login. I can only confirm that the Evaluation Center only lists the default server downloads for 180 day trial or purchase.

**Comment by tomohulk** [comment]
fair enough, but the doc should be updated to reflect that, I wasted a bit of time searching round the eval site for content that doesn't exist.

**Comment by illfated** [comment]
True, I also searched a little bit, but could only find reddit.com pages and Microsoft Answers/MSDN/TechNet pages dated a year or more back. I guess this page should be changed to not have Evaluation Center suggested, or prefaced with a limitation of availability only to Enterprise customers.

**Comment by dknappettmsft** [comment]
Hi, the link is in the top paragraph for the relevant server release. For instance, for Windows Server 2022:

![image](https://user-images.githubusercontent.com/49432665/152332347-b5239bdf-3e2e-4926-8e92-97cee25388ff.png)

I hope that helps.

#please-close
