### ISSUE TITLE
Steps 19, 20, and 21 wrong. 

### ISSUE THREAD

**Issue by Kilo1977** [MicrosoftDocs/windowsserverdocs#5167]
Hi,

The steps regarding SSTP, L2TP and PPTP are wrong and needs to be exact opposite of what they are.
L2TP and PPTP are obsolete protocols and especially SSTP needs to be enabled as SSTP Fallback for IKEv2 VPN is the standard for AlwaysON VPN now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f49053-d4b0-03cd-2572-366af6d2b943
* Version Independent ID: 05ec3fce-bcc0-3833-82fd-96abc10b9dda
* Content: [Configure the Remote Access Server for Always On VPN](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-ras)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-ras.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-ras.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by illfated** [comment]
> The steps regarding SSTP, L2TP and PPTP are wrong and needs to be exact opposite of what they are.
> L2TP and PPTP are obsolete protocols and especially SSTP needs to be enabled as SSTP Fallback for IKEv2 VPN is the standard for AlwaysON VPN now.

Is this true only for Windows Server 2019, or are the earlier supported versions of Windows Server also affected?

**Comment by illfated** [comment]
Note to self: When following up on this ticket, we may also want to combine it with the content 
reported in ticket #4191 (**Missing config: Allow machine certificate authetication for IKEv2**).

**Comment by Kilo1977** [comment]
> Note to self: When following up on this ticket, we may also want to combine it with the content
> reported in ticket #4191 (**Missing config: Allow machine certificate authetication for IKEv2**).

I agree. This should be somewhere between step 13 and 14

**Comment by Kilo1977** [comment]
> > The steps regarding SSTP, L2TP and PPTP are wrong and needs to be exact opposite of what they are.
> > L2TP and PPTP are obsolete protocols and especially SSTP needs to be enabled as SSTP Fallback for IKEv2 VPN is the standard for AlwaysON VPN now.
> 
> Is this true only for Windows Server 2019, or are the earlier supported versions of Windows Server also affected?

Well, as I gather AlwaysOn VPN is for Windows 10 only and User Tunneling utilizes IKEv2 with SSTP fallback  and  Device Tunneling utilizes IKEv2 only (Hopefully MS will soon include SSTP as fallback for Device Tunnelling as well as AlwaysON VPN would be the most powerfull VPN solution for Windows then!), I really don't see the need to include configuring ports for SSTP or L2TP for any reason.

**Comment by Teresa-Motiv** [comment]
There have been a number of issues reported for this article and several related articles. However, I'm not actually the owner of these docs and I'm not sure how I ended up listed as such. I've contacted someone to try to find the correct owner.

**Comment by anaharris-ms** [comment]
#please-close Fixed in: https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/3398

**Comment by Kilo1977** [comment]
> #please-close Fixed in: https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/3398

Yet, the link provided is dead :(

**Comment by Kilo1977** [comment]
Thanks alot 👌
________________________________
