### ISSUE TITLE
Incorrect information regarding "Multiple token signing certs"

### ISSUE THREAD

**Issue by luisfeliz79** [MicrosoftDocs/windowsserverdocs#5168]
https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/design/token-signing-certificates#deployment-considerations-for-token-signing-certificates

This page indicates that you can have multiple token signing certificates per AD FS server.

I don't believe this is correct.   You can only have one global token signing cert set as Primary and must be installed to all AD FS 
servers.

>>>> incorrect paragraph <<<<

There is a unique token-signing certificate for each federation server in a farm.

When you use multiple, unique certificates throughout your farm, each server in that farm signs tokens with its own unique private key.

As shown in the following illustration, you can obtain a separate token-signing certificate for every single federation server in the farm. This option is more expensive if you plan to obtain your token-signing certificates from a public CA.

>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f61f784-56a5-d760-8917-9e7de66a83ba
* Version Independent ID: 79eb458d-c2ca-7898-47ed-57c6df038d09
* Content: [Token-Signing Certificates](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/design/token-signing-certificates#deployment-considerations-for-token-signing-certificates)
* Content Source: [WindowsServerDocs/identity/ad-fs/design/Token-Signing-Certificates.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/design/Token-Signing-Certificates.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
I don't quite get your issue.
I seem to be reading that document section with a completely different understanding from yours.

I read the quoted paragraphs to mean the following:
1. Each server has **a unique token-signing certificate**.
2. Each server **in a farm** signs different tokens with **its own unique private key**.
3. You can obtain **a separate token-signing certificate** for _every single federation server in the farm_. (This is more expensive if you obtain your token-signing certificates from a public CA.)

To me, all of this still means that 1 server has got 1, and only 1, token-signing certificate.

**Comment by illfated** [comment]
## Deployment considerations for token\-signing certificates

When you deploy the first federation server in a new AD FS installation, you must obtain a token\-signing certificate and install it in the local computer personal certificate store on that federation server. You can obtain a token\-signing certificate by requesting one from an enterprise CA or a public CA or by creating a self\-signed certificate.

When you deploy an AD FS farm, token\-signing certificates are installed differently, depending on how you create the server farm.

There are two server farm options that you can consider when you obtain token\-signing certificates for your deployment:

- A private key from one token\-signing certificate is shared among all the federation servers in a farm.

  In a federation server farm environment, we recommend that all federation servers share \(or reuse\) the same token\-signing certificate. You can install a single token\-signing certificate from a CA on a federation server and then export the private key, as long as the issued certificate is marked as exportable.

  As shown in the following illustration, the private key from a single token\-signing certificate can be shared to all the federation servers in a farm. This option—compared to the following "unique token\-signing certificate" option—reduces costs if you plan to obtain a token\-signing certificate from a public CA.

  ![Illustration that shows the private key from a single token\-signing certificate can be shared to all the federation servers in a farm.](https://github.com/MicrosoftDocs/windowsserverdocs/raw/master/WindowsServerDocs/identity/ad-fs/design/media/adfs2_fedserver_certstory_3.gif)

- There is a unique token\-signing certificate for each federation server in a farm.

  When you use multiple, unique certificates throughout your farm, each server in that farm signs tokens with its own unique private key.

  As shown in the following illustration, you can obtain a separate token\-signing certificate for every single federation server in the farm. This option is more expensive if you plan to obtain your token\-signing certificates from a public CA.

  ![token signing](https://github.com/MicrosoftDocs/windowsserverdocs/raw/master/WindowsServerDocs/identity/ad-fs/design/media/adfs2_fedserver_certstory_4.gif)

For information about installing a certificate when you use Microsoft Certificate Services as your enterprise CA, see [IIS 7.0: Create a Domain Server Certificate in IIS 7.0](https://go.microsoft.com/fwlink/?LinkId=108548).

For information about installing a certificate from a public CA, see [IIS 7.0: Request an Internet Server Certificate](https://go.microsoft.com/fwlink/?LinkId=108549).

For information about installing a self\-signed certificate, see [IIS 7.0: Create a Self\-Signed Server Certificate in IIS 7.0](https://go.microsoft.com/fwlink/?LinkID=108271).

**Comment by illfated** [comment]
Feel free to point out any mistakes or misunderstandings I have made in my understanding/interpretation of the document section.

**Comment by luisfeliz79** [comment]
Hi Trond, Point #3 is incorrect.  All servers in a farm use the same token signing cert and private key. There is no option to have a token signing cert per server.

An ADFS farm can only have 1 primary token signing cert, and that cert will be the same on every server on that farm.







~ Luis

Please note my new email address luis@felizmail.com


________________________________

**Comment by illfated** [comment]
> Hi Trond, Point #3 is incorrect. All servers in a farm use the same token signing cert and private key. There is no option to have a token signing cert per server. An ADFS farm can only have 1 primary token signing cert, and that cert will be the same on every server on that farm.

Thank you for pointing out precisely what you find to be incorrect in the documentation. I see what you mean now.

Do you know of some form of official documentation elsewhere to reference if I start working on making a Pull Request to have the document corrected?

(Without an official reference showing that your point is the correct one, it might look like I am only taking your word for it. Someone might even go so far as to suggest that maybe that scenario is the only practical and cost-effective one, and that is the only prevailing scenario in most, if not all, server farms today.)

**Comment by luisfeliz79** [comment]
Hi, I completely understand.  I think is best if we bring in the PG for validation.  I will get an email out Monday morning with the appropriate team and include you.

**Comment by luisfeliz79** [comment]
I'm reached out to the PG about this and they agree this is not correct.  They are going to handle internally and get it removed.  Thanks!

**Comment by illfated** [comment]
OK, fair enough. Thank you for the insight & feedback.
