### ISSUE TITLE
Recommended dimensions typo (350 should be 35 (I think))

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/windowsserverdocs#517]
This line:
"Important

We recommend the dimensions for the logo to be 260x350 @ 96 dpi with a file size of no greater than 10 KB."

I think it means to say 260x35.  I could be wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26b30a8b-731c-a11f-a666-83e25eef75ad
* Version Independent ID: 2f45486d-f1d0-bf45-3790-fedc30f5a658
* Content: [Changing the company logo on the AD FS sign-in page](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/change-the-company-logo-on-the-ad-fs-sign-in-page)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Change-the-company-logo-on-the-AD-FS-sign-in-page.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Change-the-company-logo-on-the-AD-FS-sign-in-page.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Markus-Hanisch** [comment]
I agree. Annoying.
Correct value is stated here: Customizing the AD FS Sign-in Pages
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn280950(v=ws.11)

**Comment by doctordns** [comment]
As this has been addressed and a fix merged, can this issue be closed?

**Comment by JeremyTBradshaw** [comment]
@doctordns Certainly!  Haha if the question is for me:).

Thanks very much!

**Comment by illfated** [comment]
(ref. #929 (**Error in instructions?**) )
