### ISSUE TITLE
Uninstall Microsoft.WindowsStore_8wekyb3d8bbwe not supported

### ISSUE THREAD

**Issue by severrol-msft** [MicrosoftDocs/windowsserverdocs#5170]
Hello team,

In step "Step 7: Optionally specify a Start layout for Windows 10 PCs  /  point 6).
Uninstalling the Windows Store Apps is not supported.

https://docs.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/cannot-remove-uninstall-or-reinstall-microsoft-store-app

So I think we need to remove the line : Microsoft.WindowsStore_8wekyb3d8bbwe
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32c24e82-8047-12d6-877a-8ee1ad7d259c
* Version Independent ID: 021dac4b-8b4c-0fad-85fb-f89231fe8afa
* Content: [Deploying Roaming User Profiles](https://docs.microsoft.com/en-us/windows-server/storage/folder-redirection/deploy-roaming-user-profiles?source=docs)
* Content Source: [WindowsServerDocs/storage/folder-redirection/deploy-roaming-user-profiles.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/folder-redirection/deploy-roaming-user-profiles.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Fair point, but I have a minor doubt about the intended reach for the troubleshooting document you linked above (Removing, uninstalling, or reinstalling Microsoft Store app is not supported).

That article document is located in the [**Windows client troubleshooting**](https://docs.microsoft.com/troubleshoot/windows-client/welcome-windows-client) site category, so it looks to me as if that document targets individual Windows 10 client computer troubleshooting.

I also suspect that working on Windows 10 deployment images could be outside the scope of that article, but I may very well be mistaken about it.

@JasonGerend : Any chance we could have this question clarified, if the statement from the ticket author is correct, valid, and needs to be reacted to?

**Comment by RAJU2529** [comment]
If Microsoft store is reinstalled by windows reset , then my question, there is cmd file which contains path of the  file which belongs Microsoft store.

so we have to found where is the location.

**Comment by illfated** [comment]
Fair enough, that is a troubleshooting detail as part of verifying the ticket issue.

I am more uncertain about whether it is actually valid to remove Microsoft Store in a Deployment image to be installed on multiple empty computers. (I could be wrong, of course.)

**Comment by illfated** [comment]
By the way, @severrol-msft , are you a Microsoft employee with access to documentation and lab tests to confirm and verify that it is not supported to create Deployment images without including `Microsoft.WindowsStore_8wekyb3d8bbwe` ? Or is this based only on the documentation in the Windows 10 client support page https://docs.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/cannot-remove-uninstall-or-reinstall-microsoft-store-app ?

Please note that I have made a PR to update the following section:
- https://docs.microsoft.com/en-us/windows-server/storage/folder-redirection/deploy-roaming-user-profiles?source=docs#required-permissions-for-the-file-share-hosting-roaming-user-profiles

***

### Required permissions for the file share hosting roaming user profiles

| User Account | Access | Applies to |
|   -   |   -   |   -   |
|   System    |  Full control     |  This folder, subfolders and files     |
|  Administrators     |  Full Control     |  This folder only     |
|  Creator/Owner     |  Full Control     |  Subfolders and files only     |
| Security group of users needing to put data on share (Roaming User Profiles Users and Computers)      |  List folder / read data  *(Advanced permissions)* <br />Create folders / append data *(Advanced permissions)* |  This folder only     |
| Other groups and accounts   |  None (remove)     |       |

***
See my PR #5181 to resolve issue ticket #4249 and (hopefully) bring a conclusion to the old PR #2158 regarding the missing folder permission `Traverse Folder/Execute File` *(Advanced permissions)* to make Roaming User Profile file share folder access and deployment work as intended and expected.

**Comment by severrol-msft** [comment]
Hello,

My remark is based on the documentation :

 Important
·       Uninstalling the Microsoft Store app is not supported, and uninstalling it may cause unintended consequences.
·       There is no supported workaround to uninstall or reinstall Microsoft Store.

Cordialement,

﻿[Microsoft]
Sébastien VERROLLE
Sr. Customer Engineer
Modern Workplace
Office: +33157753611
Mobile: +33699145673
sebastien.verrolle@microsoft.com<mailto:sebastien.verrolle@microsoft.com>

De : Trond B. Krokli <notifications@github.com>
Envoyé : dimanche 10 janvier 2021 07:18
À : MicrosoftDocs/windowsserverdocs <windowsserverdocs@noreply.github.com>
Cc : Sébastien Verrolle <Sebastien.Verrolle@microsoft.com>; Mention <mention@noreply.github.com>
Objet : Re: [MicrosoftDocs/windowsserverdocs] Uninstall Microsoft.WindowsStore_8wekyb3d8bbwe not supported (#5170)


By the way, @severrol-msft<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fseverrol-msft&data=04%7C01%7CSebastien.Verrolle%40microsoft.com%7Cbdf9c426b28845298f0008d8b52f694e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637458562545952698%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kT0WveuViWab2ue4YOynCTKs2QikiG0Td1kiVbHJQug%3D&reserved=0> , are you a Microsoft employee with access to documentation and lab tests to confirm and verify that it is not supported to create Deployment images without including Microsoft.WindowsStore_8wekyb3d8bbwe ? Or is this based only on the documentation in the Windows 10 client support page https://docs.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/cannot-remove-uninstall-or-reinstall-microsoft-store-app<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Ftroubleshoot%2Fwindows-client%2Fshell-experience%2Fcannot-remove-uninstall-or-reinstall-microsoft-store-app&data=04%7C01%7CSebastien.Verrolle%40microsoft.com%7Cbdf9c426b28845298f0008d8b52f694e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637458562545952698%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NcQ%2BFKCw2rtETjDUbcaqBz1O%2FJs3EhN54o6%2BhomfUdE%3D&reserved=0> ?

Please note that I have made a PR to update the following section:

  *   https://docs.microsoft.com/en-us/windows-server/storage/folder-redirection/deploy-roaming-user-profiles?source=docs#required-permissions-for-the-file-share-hosting-roaming-user-profiles<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fwindows-server%2Fstorage%2Ffolder-redirection%2Fdeploy-roaming-user-profiles%3Fsource%3Ddocs%23required-permissions-for-the-file-share-hosting-roaming-user-profiles&data=04%7C01%7CSebastien.Verrolle%40microsoft.com%7Cbdf9c426b28845298f0008d8b52f694e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637458562545962653%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Gp5yR93O8Wqk3seLWQJWZKnGLTELMGHLnWQ19d9LoNw%3D&reserved=0>

________________________________
Required permissions for the file share hosting roaming user profiles
User Account
Access
Applies to
System
Full control
This folder, subfolders and files
Administrators
Full Control
This folder only
Creator/Owner
Full Control
Subfolders and files only
Security group of users needing to put data on share (Roaming User Profiles Users and Computers)
List folder / read data (Advanced permissions)
Create folders / append data (Advanced permissions)
This folder only
Other groups and accounts
None (remove)
________________________________

See my PR #5181<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fwindowsserverdocs%2Fpull%2F5181&data=04%7C01%7CSebastien.Verrolle%40microsoft.com%7Cbdf9c426b28845298f0008d8b52f694e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637458562545962653%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Lgnc3gPrf4giDEWVWXIqnAOmDwZLgFCJcazjcXgE%2BwM%3D&reserved=0> to resolve issue ticket #4249<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fwindowsserverdocs%2Fissues%2F4249&data=04%7C01%7CSebastien.Verrolle%40microsoft.com%7Cbdf9c426b28845298f0008d8b52f694e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637458562545972612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WcvYHz5KVsZdAbrI3e%2B3C79zitncGb1W5c5um2EQpU4%3D&reserved=0> and (hopefully) bring a conclusion to the old PR #2158<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fwindowsserverdocs%2Fpull%2F2158&data=04%7C01%7CSebastien.Verrolle%40microsoft.com%7Cbdf9c426b28845298f0008d8b52f694e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637458562545972612%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=M49S5QNK0kE%2FgUUTrh%2FQu2josXCVdxiimLsspCMGJS8%3D&reserved=0> regarding the missing folder permission Traverse Folder/Execute File (Advanced permissions) to make Roaming User Profile file share folder access and deployment work as intended and expected.

**Comment by illfated** [comment]
Fair enough. I think we need a verification from one of the MS Docs tech writers to confirm if this should be reflected in the Server docs even if the caveat is specifically targeting the Windows 10 client computers.

@MaratMussabekov & @joinimran : Is this something you can verify and confirm as needed in the Server docs, even if it seems to be more specific for standalone Windows 10 clients?

**Comment by severrol-msft** [comment]
Hello,

The article still contains this error.

Here we are talking about an optmisation for Roaming User Profiles.

The information below is about Windows 10 (Client).

Uninstalling the Store under Windows 10 is not supported :
More information

This behavior is by design.

If you uninstalled Microsoft Store by any means and want to reinstall it, the only Microsoft-supported method is to reset or reinstall the operating system. It will reinstall Microsoft Store.

 Important
·       Uninstalling the Microsoft Store app is not supported, and uninstalling it may cause unintended consequences.
·       There is no supported workaround to uninstall or reinstall Microsoft Store.

Can't remove, uninstall, or reinstall Microsoft Store app - Windows Client | Microsoft Docs<https://docs.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/cannot-remove-uninstall-or-reinstall-microsoft-store-app>

Is there a reason not to correct the article ?

(Optional) Further decrease sign-in times by removing unnecessary apps from the Windows 10 base image you use to deploy client PCs. Windows Server 2019 and Windows Server 2016 don't have any pre-provisioned apps, so you can skip this step on server images.
·       To remove apps, use the Remove-AppxProvisionedPackage<https://docs.microsoft.com/en-us/powershell/module/dism/remove-appxprovisionedpackage> cmdlet in Windows PowerShell to uninstall the following applications. If your PCs are already deployed you can script the removal of these apps using the Remove-AppxPackage<https://docs.microsoft.com/en-us/powershell/module/appx/remove-appxpackage>.
o   Microsoft.windowscommunicationsapps_8wekyb3d8bbwe
o   Microsoft.BingWeather_8wekyb3d8bbwe
o   Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
o   Microsoft.Getstarted_8wekyb3d8bbwe
o   Microsoft.Windows.Photos_8wekyb3d8bbwe
o   Microsoft.WindowsCamera_8wekyb3d8bbwe
o   Microsoft.WindowsFeedbackHub_8wekyb3d8bbwe
o   Microsoft.WindowsStore_8wekyb3d8bbwe
o   Microsoft.XboxApp_8wekyb3d8bbwe
o   Microsoft.XboxIdentityProvider_8wekyb3d8bbwe
o   Microsoft.ZuneMusic_8wekyb3d8bbwe

My customer considers that he can uninstall the awning with this item when it is not supported !

Best regards,

﻿[Microsoft]
Sébastien VERROLLE
Sr. Customer Engineer
Modern Workplace
Office: +33157753611
Mobile: +33699145673
sebastien.verrolle@microsoft.com<mailto:sebastien.verrolle@microsoft.com>

De : Trond B. Krokli <notifications@github.com>
Envoyé : lundi 11 janvier 2021 22:25
À : MicrosoftDocs/windowsserverdocs <windowsserverdocs@noreply.github.com>
Cc : Sébastien Verrolle <Sebastien.Verrolle@microsoft.com>; Mention <mention@noreply.github.com>
Objet : Re: [MicrosoftDocs/windowsserverdocs] Uninstall Microsoft.WindowsStore_8wekyb3d8bbwe not supported (#5170)


Fair enough. I think we need a verification from one of the MS Docs tech writers to confirm if this should be reflected in the Server docs even if the caveat is specifically targeting the Windows 10 client computers.

@MaratMussabekov<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMaratMussabekov&data=04%7C01%7CSebastien.Verrolle%40microsoft.com%7C91f49fa046b4419c213208d8b6775a36%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637459971027772590%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=s0I3ZGsCczaSrCjodke9CNztoSQZ2S519bnOpnWbH%2Fs%3D&reserved=0> & @joinimran<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjoinimran&data=04%7C01%7CSebastien.Verrolle%40microsoft.com%7C91f49fa046b4419c213208d8b6775a36%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637459971027782545%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vDyU%2BXeza7mptnq6mo8gLu8i9pdVzZKB4x2qOV6dJI8%3D&reserved=0> : Is this something you can verify and confirm as needed in the Server docs, even if it seems to be more specific for standalone Windows 10 clients?

**Comment by severrol-msft** [comment]
Sébastien Verrolle souhaite rappeler le message « [MicrosoftDocs/windowsserverdocs] Uninstall Microsoft.WindowsStore_8wekyb3d8bbwe not supported (#5170) ».

**Comment by severrol-msft** [comment]
Hello,

The article still contains this error.

Here we are talking about an optmisation for Roaming User Profiles.

The information below is about Windows 10 (Client).

Uninstalling the Store under Windows 10 is not supported :
More information

This behavior is by design.

If you uninstalled Microsoft Store by any means and want to reinstall it, the only Microsoft-supported method is to reset or reinstall the operating system. It will reinstall Microsoft Store.

 Important
·       Uninstalling the Microsoft Store app is not supported, and uninstalling it may cause unintended consequences.
·       There is no supported workaround to uninstall or reinstall Microsoft Store.

Can't remove, uninstall, or reinstall Microsoft Store app - Windows Client | Microsoft Docs<https://docs.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/cannot-remove-uninstall-or-reinstall-microsoft-store-app>

Is there a reason not to correct the article ?

(Optional) Further decrease sign-in times by removing unnecessary apps from the Windows 10 base image you use to deploy client PCs. Windows Server 2019 and Windows Server 2016 don't have any pre-provisioned apps, so you can skip this step on server images.
·       To remove apps, use the Remove-AppxProvisionedPackage<https://docs.microsoft.com/en-us/powershell/module/dism/remove-appxprovisionedpackage> cmdlet in Windows PowerShell to uninstall the following applications. If your PCs are already deployed you can script the removal of these apps using the Remove-AppxPackage<https://docs.microsoft.com/en-us/powershell/module/appx/remove-appxpackage>.
o   Microsoft.windowscommunicationsapps_8wekyb3d8bbwe
o   Microsoft.BingWeather_8wekyb3d8bbwe
o   Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
o   Microsoft.Getstarted_8wekyb3d8bbwe
o   Microsoft.Windows.Photos_8wekyb3d8bbwe
o   Microsoft.WindowsCamera_8wekyb3d8bbwe
o   Microsoft.WindowsFeedbackHub_8wekyb3d8bbwe
o   Microsoft.WindowsStore_8wekyb3d8bbwe
o   Microsoft.XboxApp_8wekyb3d8bbwe
o   Microsoft.XboxIdentityProvider_8wekyb3d8bbwe
o   Microsoft.ZuneMusic_8wekyb3d8bbwe

My customer considers that he can uninstall the application with this item when it is not supported !

Best regards,

﻿[Microsoft]
Sébastien VERROLLE
Sr. Customer Engineer
Modern Workplace
Office: +33157753611
Mobile: +33699145673
sebastien.verrolle@microsoft.com<mailto:sebastien.verrolle@microsoft.com>

De : Trond B. Krokli <notifications@github.com>
Envoyé : lundi 11 janvier 2021 22:25
À : MicrosoftDocs/windowsserverdocs <windowsserverdocs@noreply.github.com>
Cc : Sébastien Verrolle <Sebastien.Verrolle@microsoft.com>; Mention <mention@noreply.github.com>
Objet : Re: [MicrosoftDocs/windowsserverdocs] Uninstall Microsoft.WindowsStore_8wekyb3d8bbwe not supported (#5170)


Fair enough. I think we need a verification from one of the MS Docs tech writers to confirm if this should be reflected in the Server docs even if the caveat is specifically targeting the Windows 10 client computers.

@MaratMussabekov<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMaratMussabekov&data=04%7C01%7CSebastien.Verrolle%40microsoft.com%7C91f49fa046b4419c213208d8b6775a36%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637459971027772590%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=s0I3ZGsCczaSrCjodke9CNztoSQZ2S519bnOpnWbH%2Fs%3D&reserved=0> & @joinimran<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjoinimran&data=04%7C01%7CSebastien.Verrolle%40microsoft.com%7C91f49fa046b4419c213208d8b6775a36%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637459971027782545%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vDyU%2BXeza7mptnq6mo8gLu8i9pdVzZKB4x2qOV6dJI8%3D&reserved=0> : Is this something you can verify and confirm as needed in the Server docs, even if it seems to be more specific for standalone Windows 10 clients?

**Comment by illfated** [comment]
@MicrosoftGuyJFlo , @brianlic-msft : Please forgive me for pinging you, but it seems like @JasonGerend is not available for comment. Do you agree that the information provided above is valid and that we need to change the document as suggested above, by making a PR to update the document accordingly? I am prepared to create a PR to suggest the change, but it would be nice to have this verified by any of you team members before I start working on a PR to provide the suggestion.
