### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by WillyMoselhy** [MicrosoftDocs/windowsserverdocs#5183]
Line 117, Gran**d** should be Gran**t**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bdc0597-e371-3404-95b8-3cb6879048e8
* Version Independent ID: 0c03b7ab-64cb-e25a-41f2-4a8bf3859ea7
* Content: [Deploy Windows Server Hybrid Cloud Print](https://docs.microsoft.com/en-us/windows-server/administration/hybrid-cloud-print/hybrid-cloud-print-deploy)
* Content Source: [WindowsServerDocs/administration/hybrid-cloud-print/hybrid-cloud-print-deploy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/hybrid-cloud-print/hybrid-cloud-print-deploy.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @msjimwu
* Microsoft Alias: **jimwu**

**Comment by illfated** [comment]
Thank you for the typo report.

Given a fair amount of goodwill, that typo makes the line look a bit like it could be talking about a "Grand Admiral" or something like that. 😄

**Comment by illfated** [comment]
(also ref. PR #5184 for the correction)

**Comment by illfated** [comment]
Closing this ticket as it appears to be corrected in PR #5184 .

#please-close
