### ISSUE TITLE
Screenshots don't match text

### ISSUE THREAD

**Issue by hunkydoryrepair** [MicrosoftDocs/windowsserverdocs#5190]
[Enter feedback here]
For TLS 1.0 and TLS 1.1, the text reads
"To disable TLS 1.0 by default, create a DisabledByDefault entry and change the DWORD value to 1"

and the screenshot description reads "The following example shows TLS 1.0 disabled in the registry:"

However, in the screenshot, `DisabledByDefault` is set to 0x00000000

Same for TLS 1.1 and possibly others. The difference being "1", is not the same as 0, which is in the screenshot. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd180142-4c19-8abc-ecce-e4c7e5ac8951
* Version Independent ID: fc5bba87-afad-1729-8f7e-333c73188b73
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by RAJU2529** [comment]
@hunkydoryrepair, Thanks for pointing out. I am using server OS , so wait for a few server os experts will fix this issue.

**Comment by illfated** [comment]
Please also note the amount of tickets opened about this same issue:
- https://github.com/MicrosoftDocs/windowsserverdocs/issues?utf8=%E2%9C%93&q=%22fc5bba87-afad-1729-8f7e-333c73188b73%22&in=body

Please also note my PR #4988 regarding some of those issue tickets, please check if it covers this ticket too.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. A documentation change was made and changes are live. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
