### ISSUE TITLE
findstr example incorrect

### ISSUE THREAD

**Issue by jay** [MicrosoftDocs/windowsserverdocs#5192]
One of the findstr examples is incorrect. It says:

> To search for _hello there_ in file x.y, type:
> findstr /c:hello there x.y

It needs to be quoted
```
C:\Temp>echo hello there>x.y

C:\Temp>findstr /c:hello there x.y
FINDSTR: Cannot open there
x.y:hello there

C:\Temp>findstr "/c:hello there" x.y
hello there

```

Also it's not documented how to allow for a space in regex search strings, it seems to still be a delimiter separating the strings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b90f482-f48a-7d60-7ba9-bb5a1e837989
* Version Independent ID: 5a8e1ac5-3f4d-4da9-67c3-15a08d9a1b61
* Content: [findstr](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/findstr)
* Content Source: [WindowsServerDocs/administration/windows-commands/findstr.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/findstr.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by jay** [comment]
Also I can't reference examples directly, the fragment is removed when the page is loaded rather than going to the section.

For example 
`https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/findstr#code-try-1`
the fragment is removed in both Firefox and Chrome:
`https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/findstr`

**Comment by RAJU2529** [comment]
@jay , i tried the following way

**Findstr /c:"hello there" C:\writing.log >"%userprofile%\Desktop\result.txt"** 

i make sure hello there words must be written in writing.log  file
above command worked fine

**Comment by jay** [comment]
> above command worked fine

The example doesn't have quotes. View the page and see for yourself.

![Capture](https://user-images.githubusercontent.com/965580/104507182-63b1c100-55b4-11eb-959d-94070e100f6e.PNG)

**Comment by atamasco** [comment]
Why was this closed as "completed"? The example is still wrong! The two search strings have to be quoted, otherwise the 2nd search string is considered to be a filename.

Contento of file 'x.y':
```
hello
there
what is wrong with some people?
hello there?
```

Testing the 1st example on Microsoft Windows 11 Enterprise v10.0.22631 Build 22631 gives:
```
D:\>findstr hello there x.y
FINDSTR: Cannot open there
x.y:hello
x.y:hello there?
```

_"...FINDSTR: Cannot open there..."_ Obviously the 1st example on https://learn.microsoft.com/de-de/windows-server/administration/windows-commands/findstr#examples has not been corrected!
