### ISSUE TITLE
Provided script Deploy-WACAzVM.ps1 returns error

### ISSUE THREAD

**Issue by iwalker200** [MicrosoftDocs/windowsserverdocs#5195]
PS /home/igor/Deploy-WACAzVM> ./strat-deploy-WACAzVM.ps1

PowerShell credential request
Enter your credentials.
User: myadminname
Password for user myadminname: *************

Creating virtual machine vm-srv01-WAC in resource group rg-WACPoC-neu
Enabling PowerShell Remoting on virtual machine vm-srv01-WAC
The MSI will generate the self-signed certificate.
OpenError: /usr/local/share/powershell/Modules/PSCloudShellUtility/PSCloudShellUtility.psm1:1112Line |1112 |          Invoke-Command @invokeCommandParams -ErrorAction Stop     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     | [vm-srv01-wac-2d9d3f.uaenorth.cloudapp.azure.com] Connecting to remote server vm-srv01-wac-2d9d3f.uaenorth.cloudapp.azure.com failed with the following error message : error:1416F086:SSL     | routines:tls_process_server_certificate:certificate verify failed For more information, see the about_Remote_Troubleshooting Help topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e98e7f06-59d2-01bf-4fbb-779204194f8e
* Version Independent ID: 5b2c311e-69ee-7e2f-5ca3-696c9f9369f5
* Content: [Deploy a Windows Admin Center gateway in Azure](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/azure/deploy-wac-in-azure)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/azure/deploy-wac-in-azure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/azure/deploy-wac-in-azure.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @jwwool
* Microsoft Alias: **jeffrew**

**Comment by illfated** [comment]
I have no idea what the output is supposed to look like, but I have taken the liberty to add a liberal amount of NewLine/ Line Breaks in it.

I have also added a GitHub Flavored MarkDown syntax highlighted code block to use a monospaced font.

```PowerShell
PS /home/igor/Deploy-WACAzVM> ./strat-deploy-WACAzVM.ps1

PowerShell credential request
Enter your credentials.
User: myadminname
Password for user myadminname: *************

Creating virtual machine vm-srv01-WAC in resource group rg-WACPoC-neu

Enabling PowerShell Remoting on virtual machine vm-srv01-WAC

The MSI will generate the self-signed certificate.

OpenError: /usr/local/share/powershell/Modules/PSCloudShellUtility/PSCloudShellUtility.psm1:1112

Line |
1112 |
 Invoke-Command @invokeCommandParams -ErrorAction Stop |
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ |
 [vm-srv01-wac-2d9d3f.uaenorth.cloudapp.azure.com]

 Connecting to remote server vm-srv01-wac-2d9d3f.uaenorth.cloudapp.azure.com failed with the following error message :

 error:1416F086:SSL |

 routines:tls_process_server_certificate:certificate verify failed

 For more information, see the about_Remote_Troubleshooting Help topic.
```

Please be aware that this repository does not provide troubleshooting support, as it is intended for Microsoft Docs documentation improvement.

On the other hand, if you know what needs to be improved in the linked documentation, please tell us about it.

**Comment by illfated** [comment]
Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.

You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

The intention of this repository is to improve on the existing documentation by providing the users a way to report factual errors, improvement suggestions and request updates for new versions.

The MS Docs team members might not have time to answer your question, both due to the small size of the team and the big workload.

Try the following resources to get in touch with users who may be able to help you:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

**Comment by iwalker200** [comment]
> Wish I could help, but this repository is not intended for regular support issues, support requests or support questions.
> 
> You may want to look elsewhere for answers, unless you have suggestions for improving one or more specific pages in the MS Docs repository.
> 

Unfortunately there any no any answers around about this error on this script :( Will try to open case to Microsoft Azure support

**Comment by illfated** [comment]
> Unfortunately there any no any answers around about this error on this script :( Will try to open case to Microsoft Azure support

Very well, thank you for your reply. My best wishes for a productive response from the support department. Feel free to post feedback here, in case your support ticket reveals a need for documentation improvements in the linked page.

**Comment by IngridAtMicrosoft** [comment]
Suppport ticket opened. #please-close
