### ISSUE TITLE
Incorrect displaygroup name

### ISSUE THREAD

**Issue by Magrene** [MicrosoftDocs/windowsserverdocs#5204]
This document has listed "Windows Firewall Remote Management" the correct display group is "Windows Defender Firewall Remote Management"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcb12aed-dce1-d2e8-c5bd-da2c2fec5bc9
* Version Independent ID: 2b215377-7c67-9012-8ad2-889483380b5d
* Content: [Manage Server Core](https://docs.microsoft.com/en-us/windows-server/administration/server-core/server-core-manage#managing-with-microsoft-management-console)
* Content Source: [WindowsServerDocs/administration/server-core/server-core-manage.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/server-core/server-core-manage.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @pronichkin
* Microsoft Alias: **artemp**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey Magrene,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made updating the product name in the table and changes are live. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
