### ISSUE TITLE
Remove is mispelled as "Remote"

### ISSUE THREAD

**Issue by shabiel** [MicrosoftDocs/windowsserverdocs#521]
Click Add and enter the user or group that you want to have access to the collection. You can also remove users and groups from this window by selecting the user or group you want to remove, and then clicking Remote. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce20f03f-95d6-7896-8481-432ced40009b
* Version Independent ID: a0a1c419-caf1-6e3a-f4f0-4d7c1fa5ae35
* Content: [Manage users in your RDS collection](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-user-management)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-user-management.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-user-management.md)
* Service: **unspecified**
* GitHub Login: @ChristianMontoya
* Microsoft Alias: **chrimo**

**Comment by lizap** [comment]
Thanks for catching this. I've updated the article - you should see the fix live this afternoon (3/27/18).
