### ISSUE TITLE
Mistakes in endpoints addresses 

### ISSUE THREAD

**Issue by MJLpl** [MicrosoftDocs/windowsserverdocs#5219]
This part:

/adfs/ls/federationmetadata/2007-06/federationmetadata.xml | Requirement for any passive flows; and used by Office 365 / Azure AD to check AD FS certificates.
-- | --

Should be:

/federationmetadata/2007-06/federationmetadata.xml | Requirement for any passive flows; and used by Office 365 / Azure AD to check AD FS certificates.
-- | --

there is no /adfs/ls/federationmetadata endpoint.

Also the names of the /adfs/ls/ and /adfs/oauth2/ should end with a trailing slash.

Best Regards
Mike

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6bdcea6-e429-95ce-0012-a30241941e36
* Version Independent ID: b37b7c92-12d0-9d03-c181-05b7cfcbe276
* Content: [Best Practices for securing AD FS and Web Application Proxy](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/best-practices-securing-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Best-Practices-Securing-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Best-Practices-Securing-AD-FS.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
Hey @MJLpl,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation update has been made and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
