### ISSUE TITLE
Meeting Latest Release Notes

### ISSUE THREAD

**Issue by noahtk1** [MicrosoftDocs/windowsserverdocs#5223]
This page is missing the latest release notes for the past two versions.  The latest being version 10.2.1701.0 at the time of writing this post.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67b7b5a4-647e-fee3-6533-6ed88ae45bfa
* Version Independent ID: d9102859-0147-346f-8268-6e2a75c8b0b7
* Content: [What's new in the Microsoft Store Client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windows-whatsnew#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windows-whatsnew.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windows-whatsnew.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by illfated** [comment]
Speaking as an external contributor to this repository, do you know if the release notes are available elsewhere, so they could be easily contributed in a Pull Request?

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @noahtk1,

Thanks again for contacting Microsoft. We value your feedback. 

The documentation in question has been updated to reflect the most current changes to RDS as of this date & time. 

- [RDS - Windows Store Version Updates](https://learn.microsoft.com/en-us/Windows-Server/remote/remote-desktop-services/clients/windows-whatsnew)
- [RDS - Windows Stand-alone Version Updates](https://learn.microsoft.com/en-us/azure/virtual-desktop/whats-new-client-windows?toc=%2Fazure%2Fvirtual-desktop%2Fusers%2Ftoc.json)

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
