### ISSUE TITLE
In first step of the upgrade process, you reference to the BuildLabEx (version) key and verify its value matches the Server version as it is mentioned in the ProductName key, not the BuildLabEx (version)

### ISSUE THREAD

**Issue by Gert-Vangeel** [MicrosoftDocs/windowsserverdocs#5224]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82772fa0-1642-4481-dff0-ebf83270db4d
* Version Independent ID: e5d451c4-2ee0-9461-c19b-19d0cb199b42
* Content: [Upgrade Windows Server 2012 R2 to Windows Server 2019](https://docs.microsoft.com/en-us/windows-server/upgrade/upgrade-2012r2-to-2019)
* Content Source: [WindowsServerDocs/upgrade/upgrade-2012r2-to-2019.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/upgrade/upgrade-2012r2-to-2019.md)
* Product: **windows-server**
* Technology: **upgrade**
* GitHub Login: @RobHindman
* Microsoft Alias: **robhind**

**Comment by IngridAtMicrosoft** [comment]
#label:"triaged"

**Comment by IngridAtMicrosoft** [comment]
Addressed. #please-close
