### ISSUE TITLE
iOS Mobile App certificate based Auth on ADFS

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/windowsserverdocs#5226]
Are there any material available to setup iOS Mobile App certificate based Auth on ADFS?
E.g. What are some architectural consideration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7cc47f3-30fe-1a90-ac1f-6ddfe842ace8
* Version Independent ID: ed59c2d1-48f2-5b15-1b10-826e7d66f210
* Content: [Configure AD FS support for user certificate authentication](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-user-certificate-authentication)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-User-Certificate-Authentication.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-User-Certificate-Authentication.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @jenfieldmsft
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @Anand-Moghe,

Thanks again for contacting Microsoft. We value your feedback. 

Looking through some docs, I did find this:

> - Azure AD CBA - [Azure Active Directory certificate-based authentication on iOS](https://learn.microsoft.com/en-us/azure/active-directory/authentication/concept-certificate-based-authentication-mobile-ios). 
>
> - Federated CBA with Azure AD - [Get started with certificate-based authentication in Azure Active Directory with federation](https://learn.microsoft.com/en-us/azure/active-directory/authentication/active-directory-certificate-based-authentication-get-started).
> - Link 2 leads to the [Azure Active Directory certificate-based authentication with federation on iOS](https://learn.microsoft.com/en-us/azure/active-directory/authentication/active-directory-certificate-based-authentication-ios) article.

This may not be as relevant, [Walkthrough: Workplace Join with an iOS Device](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/operations/walkthrough--workplace-join-with-an-ios-device).

Please let us know if any of this is of help.
