### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by alexaguilar89** [MicrosoftDocs/windowsserverdocs#5227]
no se que hacer 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb08c5b-865d-26b5-0867-de14e87a205c
* Version Independent ID: 5eacc1db-a948-722b-d3d5-ae0f281e9e30
* Content: [System requirements for Hyper-V on Windows Server](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/system-requirements-for-hyper-v-on-windows)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/System-requirements-for-Hyper-V-on-Windows.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/System-requirements-for-Hyper-V-on-Windows.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by illfated** [comment]
#please-close
