### ISSUE TITLE
Info not detailed enough for W2K16 (LTSC)

### ISSUE THREAD

**Issue by WernerXXL** [MicrosoftDocs/windowsserverdocs#5234]
Hi Team,

in my point of view it's a good article but the third bullet point is not detailed enough or wrong:
Window Server 2016 in the LTSC version from 15.10.2016 RTM (Version 1607 OS Build 14393) has still SMBv1 enabled by default! !

There is a SAC version of Windows Server Build 1709, there SMBv1 is disabled but it's not the same as Window Server 2016 (LTSC).

Can you give some more information about the SMBv1 future or roadmap for the following years in Window server products.
Even in Windows Server 2019 (LTSC) in an install and enable SMBv1 in the roles and features section. Does it mean you support, patch and maintain the SMBv1 until end of extended support for Windows Server 2019 on 9th January 2029?

We have some secured and isolated environments with old WinCE devices and there are a SMBv1 connection required so we need more information about the SMBv1 future in the Microsoft server products. 

I also opened a SR 121012125003226 and try to get this information. (still ongoing)

Have a good day!
Werner

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6efee75e-7541-0166-76ac-81ecbe4cb022
* Version Independent ID: 35b346a7-ea72-325e-81c9-a1056dca72f4
* Content: [SMBv1 is not installed by default in Windows 10 version 1709, Windows Server version 1709 and later versions](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/smbv1-not-installed-by-default-in-windows)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/smbv1-not-installed-by-default-in-windows.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/Troubleshoot/smbv1-not-installed-by-default-in-windows.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by doctordns** [comment]
Looking at the page, you ask "Can you give some more information about the SMBv1 future?"

There is no future for SMB1. You should remove it from all clients/servers, and ensure you are running supported versions of the OS that all work fine without SMB1.  

That said, from what I can see, Windows Server 2019, and Server 2022  all have SMB1 features (``FS-SMB1``, ``FS-SMB1-CLIENT``, and ``FS-SMB1-SERVER.``  Using Get-WindowsFeature says these features are available but not installed. And looking at the very latest WIn10 Insiders build (21301), those features exist but are disabled by default. I note that the feature names are different between Windows 10 and Windows Server but I guess that is not important. 

In both cases, these features are they are available but installed. So I agree that that third bullet point is incorrect. 

From what I understand, SMB1 is there if you want to use it.  But definitely not recommended.

**Comment by IngridAtMicrosoft** [comment]
"I also opened a SR 121012125003226 and try to get this information. (still ongoing)"
Contributor opened support ticket.  #please-close
