### ISSUE TITLE
A little confusing

### ISSUE THREAD

**Issue by john-roa** [MicrosoftDocs/windowsserverdocs#5239]
In the section about disabling TLS 1.0, you say to disable, put an entry DisableByDefault and set it to 1 but in the picture, you have it set to 0.  The same for TLS 1.1.  Which is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd180142-4c19-8abc-ecce-e4c7e5ac8951
* Version Independent ID: fc5bba87-afad-1729-8f7e-333c73188b73
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. A documentation change was made and changes are live. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close

**Comment by Xelu86** [comment]
@john-roa, 

The "DisabledByDefault" is just to override any system default settings. For "DisabledByDefault" to be enabled, the value must be set to 1, which will disable TLS on the client/server. Alternatively, you can set "Enabled" to 0 and "DisabledByDefault" to 0 for the same effect.
