### ISSUE TITLE
Wrong link to Routing and Remote Access Error Codes

### ISSUE THREAD

**Issue by J0sn** [MicrosoftDocs/windowsserverdocs#5243]
Hello,
link "Routing and Remote Access Error Codes" in "https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-troubleshooting#application-logs"
 is pointing to wrong page. Specificaly to "Enabling remote access with Windows Hello for Business in Windows 10" instead of "Routing and Remote Access Error Codes".

BR Josef

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5b7b963-8942-b367-857e-c538e6e2aa8d
* Version Independent ID: 69a13db8-25a2-d389-420e-b61e9bb214b4
* Content: [Troubleshoot Always On VPN](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-troubleshooting)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-troubleshooting.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-troubleshooting.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by illfated** [comment]
Thank you for reporting and pointing out that outdated and incorrectly labeled link.

I wonder if it will be OK to link to a page in a different repository, Win32 instead of Windows Server, for this information:
- https://docs.microsoft.com/windows/win32/rras/routing-and-remote-access-error-codes

**Comment by J0sn** [comment]
Yes - this https://docs.microsoft.com/windows/win32/rras/routing-and-remote-access-error-codes will be much better than previus link unless there si another page describinng Always on VPN client return codes.

**Comment by J0sn** [comment]
Link was not updated...

**Comment by illfated** [comment]
Sorry for the delay, I must have forgotten about this ticket somehow. I will put it back on a list of things to follow up.

**Comment by illfated** [comment]
There you go. PR #5499 is now ready for review, comments, and suggestions. Better late than never, I hope.

**Comment by IngridAtMicrosoft** [comment]
Addressed.
