### ISSUE TITLE
Confusing article 

### ISSUE THREAD

**Issue by JeromeMom** [MicrosoftDocs/windowsserverdocs#5244]
Hi

This article is really confusing:
- "24 cores" scenario does not provide information on the licenses which are needed for the 24 cores. It should be 2 x 16 core licenses or 16 x 2 core pack licenses per my knowledge.

-  "Each additional set of 8 core licenses with SA/Subscription entitles use on up to 8 virtual cores and one Base Instance (VM)."
It is incorrect. It should be 8*2 core pack licenses or 16 core licenses. You cannot split the rights under 16 cores per my knowledge and the licensing documentation as we can stack but it still requires 16 core licenses to get additional core.

Thanks,

Jerome

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90e335dd-0bc5-a7e3-650b-e3dd1823176b
* Version Independent ID: 18f34ef3-ff61-0473-a64b-ac5a64dbe1d7
* Content: [Azure Hybrid Benefit for Windows Server](https://docs.microsoft.com/en-us/windows-server/get-started/azure-hybrid-benefit)
* Content Source: [WindowsServerDocs/get-started/azure-hybrid-benefit.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/azure-hybrid-benefit.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @eross-msft
* Microsoft Alias: **chrisrin**

**Comment by PRMerger9** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: ingridatmicrosoft 
gh issue comment 5209 -b ingridatmicrosoft

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by dknappettmsft** [comment]
Hi @JeromeMom, thanks for the feedback. 16-cores is the minimum requirement to start using Azure Hybrid Benefit. After that you can buy as many licenses as you need in either 2-core or 16-core packs, but every Azure VM must have a minimum of 8-cores. This is listed in the Commercial Licensing Terms, where you can find this by visiting https://www.microsoft.com/licensing/terms/productoffering/MicrosoftAzure/all, selecting the Program, and seeing the section Azure Hybrid Benefit. That wording "Each additional set of 8 core Licenses with SA entitles use on up to 8 Virtual Cores on one Base Instance" comes directly from the Commercial Licensing Terms.  The key word there is 'additional', meaning once you're already using AHB. I appreciate it's a bit of a minefield, but I've reworded the article to hopefully make things a bit clearer. The changes should be visible later today.

#please-close
