### ISSUE TITLE
No email address as stated

### ISSUE THREAD

**Issue by TomHickling** [MicrosoftDocs/windowsserverdocs#5246]
In this section: https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client#get-help-with-the-web-client

"Get help with the web client
If you've encountered an issue that can't be solved by the information in this article, you can get help with the web client by emailing the address on the web client's About page."

There is no email address on the web clients About Page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58c2644e-6037-8b15-10e6-e77392cff23a
* Version Independent ID: 1307699a-e45f-0f84-9563-73270bae1a76
* Content: [Get started with the web client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
Hey TomHickling,

Thanks again for contacting Microsoft. We value your feedback. 

Wording in this documentation has changed and a new feedback system was incorporated:

![image](https://github.com/MicrosoftDocs/windowsserverdocs/assets/103963494/64b1ed59-e172-44b6-8f84-db1724d9542f)

Other ways to provide feedback are as follows:

- https://feedbackportal.microsoft.com/
- [Feedback Hub app](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332) (if you're running a Windows 10/11 OS)

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close

**Comment by Xelu86** [comment]
#assign:xelu86
