### ISSUE TITLE
Missing definitions within the Windows Server 2016 Licensing Guide.

### ISSUE THREAD

**Issue by mc1903** [MicrosoftDocs/windowsserverdocs#525]
This feedback is not directly related to this page, but rather the Commercial Licensing Reference Guide for Windows Server 2016 which provides a number of Licensing Definitions (towards the end of the document) however there is no definition for a 'cluster'. 

There are several references to 'cluster' through the document in different contexts (HPC, DR, etc).

Please can you include a definition in a future edition of this document?

http://download.microsoft.com/download/e/6/4/e64f72bf-55e9-4d85-9efe-39605d7ce272/windowsserver2016-licensing-guide.pdf

Thanks.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0230423b-be6b-c5b3-7c69-d99b0a0f79aa
* Version Independent ID: 825d1114-1fa8-5e9b-a0d1-478ac15d7626
* Content: [Windows Server](https://docs.microsoft.com/en-gb/windows-server/windows-server#windows-server-editions)
* Content Source: [WindowsServerDocs/Windows-Server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/Windows-Server.md)
* Service: **unspecified**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
Great point. I'll investigate and try to get some Licensing SMEs to give us some clarifications.
