### ISSUE TITLE
There is a mistake in the document AFAIK

### ISSUE THREAD

**Issue by bekirdur** [MicrosoftDocs/windowsserverdocs#5252]
There is a mistake in the document if I am not mistaken. We see an example SAN called certauth.contoso.com but this is not correct, it should be certauth.adfs.contoso.com as far as I know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7cc47f3-30fe-1a90-ac1f-6ddfe842ace8
* Version Independent ID: ed59c2d1-48f2-5b15-1b10-826e7d66f210
* Content: [Configure AD FS support for user certificate authentication](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-user-certificate-authentication)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-User-Certificate-Authentication.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-User-Certificate-Authentication.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @jenfieldmsft
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Ref. https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/ad-fs-support-for-alternate-hostname-binding-for-certificate-authentication :

> With AD FS in Windows Server 2016 this can be accomplished.
> 
> In AD FS on Windows Server 2016 this has changed. Now we support two modes, the first uses the same host (i.e. adfs.contoso.com) with different ports (443, 49443). The second used different hosts (**adfs.contoso.com and certauth.adfs.contoso.com**) with the same port (443). This will require an SSL certificate to support "certauth." as an alternate subject name. This can be done at the time of the farm creation or later via PowerShell.

Note: my emphasis added in the quoted text for (**adfs.contoso.com and certauth.adfs.contoso.com**).

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @bekirdur,

Thanks again for contacting Microsoft. We value your feedback.

The response given by Illfated is indeed correct where more than one hostname can be used. We have updated this documentation to state this for more clarity and changes should be live by the next business day.

We will now be closing this thread. Thank you and have a most pleasant day. #please-close
