### ISSUE TITLE
GMSA - missing information?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/windowsserverdocs#5255]
Basically I miss the complete installation instructions for CEP / CES. Information I can find is fragmented and sometimes outdated.

In the section Configuration is stated "You can also configure any user service account, MSA, or GMSA for CES to work."
We can get it to work with a service account, but of course we prefer a GMSA and then we get stuck with WS_E_ENDPOINT_ACCESS_DENIED .
1. Can GMSA also be used for CEP, or only for CES?
2. What extra configuration would be necessary (like logon as a batchjob/logon as a service/NTFS permissions etc)?

Also, the refences to the two basic installation articles (Certificate Enrollment Policy Web Service Guidance and 
Certificate Enrollment Web Service Guidance) are helpful, but these are with a note "We're no longer updating this content regularly.". Unfortunately, the author has passed away and the feedback links on this page point to another dead end.

Any help greatly appreciated!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a15cfbb-d54a-0533-edde-464554b94b7f
* Version Independent ID: 4d47d383-956e-e580-505b-21ec55278984
* Content: [Configuring Certificate Enrollment Web Service for certificate key-based renewal on a custom port](https://docs.microsoft.com/en-us/windows-server/identity/solution-guides/certificate-enrollment-certificate-key-based-renewal)
* Content Source: [WindowsServerDocs/identity/solution-guides/certificate-enrollment-certificate-key-based-renewal.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/solution-guides/certificate-enrollment-certificate-key-based-renewal.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by Deland-Han** [comment]
Hi, our engineer points out that the access denied error can be caused by various reasons like authentication failure. Please contact an expert or our support for help. 

Please note as mentioned in the article, this setup is created for a specific requirement and has limited supportability.

#please-close

**Comment by andrePKI** [comment]
Ok, thanks. We solved this with help from MS support. Still, information present at [docs.]microsoft.com is fragmented and incomplete, making it hard to implement this without help.
