### ISSUE TITLE
Invalid Examples link

### ISSUE THREAD

**Issue by aydeisen** [MicrosoftDocs/windowsserverdocs#526]
The link in the Examples subsection to the 'Windows Hardware Developer Center Web site' returns a Microsoft page that says "We are sorry, the page you requested cannot be found."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24be43d1-3341-8a45-b240-cf31a8588f37
* Version Independent ID: 8e4c4165-266d-4c2b-640a-8305aaa4b59c
* Content: [bcdedit](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/bcdedit)
* Content Source: [WindowsServerDocs/administration/windows-commands/bcdedit.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/bcdedit.md)
* Service: **unspecified**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by lizap** [comment]
Thanks for catching this. I've updated the link - you should see the change on the page later today (3/27/18).
