### ISSUE TITLE
WS Standard usage

### ISSUE THREAD

**Issue by DavidD-SE** [MicrosoftDocs/windowsserverdocs#5263]
Hi,

I need some clarification.
The table states:

License with SA/Subscription | VMs and cores granted | **How they can be used**
WS Datacenter (16 cores or a 2-proc L) | Up to two VMs and up to 16 cores | Run virtual machines both on premises and in Azure
**WS Standard** (16 cores or a 2-proc L) | Up to two VMs and up to 16 cores | **Run virtual machines either on premises or in Azure**

My question is:
when having the proper amount of Windows Server Standard licenses with Software Assurance enabled, can I use Windows Server Datacenter license in Azure or do I need to deploy Windows Server Standard Edition in Azure?

Thank you!

Best regards, David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90e335dd-0bc5-a7e3-650b-e3dd1823176b
* Version Independent ID: 18f34ef3-ff61-0473-a64b-ac5a64dbe1d7
* Content: [Azure Hybrid Benefit for Windows Server](https://docs.microsoft.com/en-us/windows-server/get-started/azure-hybrid-benefit)
* Content Source: [WindowsServerDocs/get-started/azure-hybrid-benefit.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/azure-hybrid-benefit.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @eross-msft
* Microsoft Alias: **chrisrin**

**Comment by DavidD-SE** [comment]
Hi, any update on this?

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by dknappettmsft** [comment]
Hi @DavidD-SE - if you have Standard edition licenses with active Software Assurance on a relevant agreement, you can use either Standard or Datacenter in Azure VMs. In the Commercial Licensing Terms you can find this by visiting https://www.microsoft.com/licensing/terms/productoffering/MicrosoftAzure/all, selecting the Program, and under the section Azure Hybrid Benefit it states "Customer may use Standard or Datacenter software". I have added that to the article as part of some wider changes, which should be visible later today.

#please-close
