### ISSUE TITLE
Consider adding/moving Windows 10 information into appropriate sections

### ISSUE THREAD

**Issue by davidpaMSFT** [MicrosoftDocs/windowsserverdocs#5265]
Windows 10 is mentioned only in section "How to remove SMB v1". Consider moving the subsection that explains how to detect, enable and disable SMB protocols on Windows 10 into the appropriate section, i.e. move it to "How to detect status, enable, and disable SMB protocols on the SMB Server" section. Also, add Windows 10 information to "How to detect status, enable, and disable SMB protocols on the SMB Client".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a91db45-ca3c-7a2e-3f32-2f5b57837b03
* Version Independent ID: b83cbaab-c0df-d6e7-a67f-f4c99a46e30a
* Content: [How to detect, enable and disable SMBv1, SMBv2, and SMBv3 in Windows](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Deland-Han** [comment]
This issue is addressed in PR https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/2405
@IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
Addressed. #please-close
