### ISSUE TITLE
Consider clarifying applicability of group policy methods for disabling SMBv1 client/server

### ISSUE THREAD

**Issue by davidpaMSFT** [MicrosoftDocs/windowsserverdocs#5266]
It is not clear what versions of Windows are sections on using group policy to disable SMBv1 client/server applicable to, i.e. is using group policy to disable SMBv1 client/server supported on Windows 10?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a91db45-ca3c-7a2e-3f32-2f5b57837b03
* Version Independent ID: b83cbaab-c0df-d6e7-a67f-f4c99a46e30a
* Content: [How to detect, enable and disable SMBv1, SMBv2, and SMBv3 in Windows](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3#how-to-detect-status-enable-and-disable-smb-protocols-on-the-smb-client)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by Deland-Han** [comment]
This issue is addressed in PR https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/2405
@IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
Addressed. #please-close
