### ISSUE TITLE
Documentation around Authentication Silos and Service Accounts is unclear

### ISSUE THREAD

**Issue by CXMelga** [MicrosoftDocs/windowsserverdocs#5269]
Hello the Document states the following

Service

Standalone managed service accounts, group managed service accounts, or a custom account object that is derived from these two types of service accounts are used. Policies can set a device's access control conditions, which are used to restrict managed service account credentials to specific devices with an Active Directory identity. **Services should never be members of the Protected Users security group because all incoming authentication will fail.**

However, the part I marked in bold above is not clear, do you mean

1) MSA/GMSA
2) standard Service Accounts (e.g. those based on a standard AD user object) 
3) Both of the above

When said they should never be members of the Protected Users group?

Please clarity
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a45dbca-c152-ecc3-e21c-cf3f5694c366
* Version Independent ID: 018190db-c9cc-3ae2-1903-49257966560c
* Content: [Authentication Policies and Authentication Policy Silos](https://docs.microsoft.com/en-us/windows-server/security/credentials-protection-and-management/authentication-policies-and-authentication-policy-silos)
* Content Source: [WindowsServerDocs/security/credentials-protection-and-management/authentication-policies-and-authentication-policy-silos.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/credentials-protection-and-management/authentication-policies-and-authentication-policy-silos.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by MicrosoftGuyJFlo** [comment]
#reassign @MicrosoftGuyJFlo

**Comment by MicrosoftGuyJFlo** [comment]
@CXMelga I dont know how that paragraph can be any clearer. It breaks down what a service account is and says that should never be in the Protected Users security group. 

If you are looking for what protections can be offered to a service, look at the next article in the series (linked in the introduction and the next steps sections of the doc) [How to Configure Protected Accounts](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/how-to-configure-protected-accounts#BKMK_ProvidePUdcProtections) it talks about how to provide DC-side protections for services and computers.

**Comment by illfated** [comment]
Maybe I am misunderstanding or misinterpreting the ticket description, but to me it looks like **CXMelga** states that the term "Protected Users security group" is unclear, or is asking for more specific information for the "Protected Users security group".

**Comment by CXMelga** [comment]
Hello CXMelga here
I think I have now, when you state 'Service Accounts' should never be members of the Protected Users group, you are referring, 'only' to MSA/GMSA (which are tired to computer objects in AD), and 'not' referring to the classic Service Account which are using prior to MSA/GSMA which was basically a standard user account, 

It the above correct?
Thanks

CXMelga

**Comment by MicrosoftGuyJFlo** [comment]
Service = Standalone managed service accounts, group managed service accounts, or a custom account object that is derived from these two types of service accounts.

Services should never be members of the Protected Users security group because all incoming authentication will fail.

#please-close
