### ISSUE TITLE
Links to referenced documents don't work

### ISSUE THREAD

**Issue by mrghostwalker** [MicrosoftDocs/windowsserverdocs#5270]
Various links to documents referenced within the page take the form of assetid:///6cbee1b5-f6f6-443f-8fa9-31cc5c05a0ee which are not resolvable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcb3f5fb-6a88-cb57-78c0-963c78a394ca
* Version Independent ID: 55d980df-e89d-615c-d1d3-d4ac2c0589fa
* Content: [Steps for Configuring the Test Lab](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/directaccess/tlg-multisite/steps-for-configuring-the-test-lab-4)
* Content Source: [WindowsServerDocs/remote/remote-access/directaccess/tlg-multisite/Steps-for-Configuring-the-Test-Lab-4.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/directaccess/tlg-multisite/Steps-for-Configuring-the-Test-Lab-4.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
Hmm. Those assetid:/// links look like remnants from the old pre-GitHub Microsoft Docs platform. We should replace them with the current document filename links (note the Step 1 — 14 pages in the TOC list to the left of the page).

**Comment by illfated** [comment]
By the way, thank you for pointing out that issue. 👍🏻
