### ISSUE TITLE
Get all ciphers

### ISSUE THREAD

**Issue by JoeBrunsTR** [MicrosoftDocs/windowsserverdocs#5272]
How can one tell what ciphers are enabled and disabled?

Get-TlsCipherSuite does not say.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd180142-4c19-8abc-ecce-e4c7e5ac8951
* Version Independent ID: fc5bba87-afad-1729-8f7e-333c73188b73
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings?source=docs)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by IngridAtMicrosoft** [comment]
@JoeBrunsTR Please post your question at [Microsoft Q & A](https://docs.microsoft.com/en-us/answers/index.html).
