### ISSUE TITLE
Documentation should describe what the options mean or do.

### ISSUE THREAD

**Issue by billev** [MicrosoftDocs/windowsserverdocs#5276]
It's great that you document what all of the options are, however many of them need further explanation. Just a few examples of options that need more:

       /b  Copies files in Backup mode.
What does "backup mode" mean? Does it affect the destination file? The source file? Selection of files? I could construct a scenario for any of those.

      /xc  Excludes changed files.
Changed? Compared to what? Which file? How is "changed" different from "modified" (as in "/it")?

      /is    Includes the same files.
What the heck does that mean at all? The same files? Which same files?

I'm sure you get the picture.

As an example of good file copy utility documentation, please check out the online help for rsync. I understand that robocopy is intended to be simple and easy to use, but it still needs to be completely and unambiguously documented.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 5263 -b #assign:IngridAtMicrosoft

**Comment by PRMerger20** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: ingridatmicrosoft 
gh issue comment 5263 -b ingridatmicrosoft

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @billev,

Thanks again for contacting Microsoft. We value your feedback. A documentation change has been made and will be live after the next business day. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
