### ISSUE TITLE
Need to mention that parsing keywords must be double-quoted; broken example commands

### ISSUE THREAD

**Issue by mklement0** [MicrosoftDocs/windowsserverdocs#5279]
The so-called parsing keywords (called options by `help for`) must be specified _as a single, double-quoted_ string.

Not only is this not mentioned, the sample commands are broken too.

E.g., the following sample command is broken in two respects:

```
for /f usebackq delims== %i in ('set') do @echo %i
```

* The lack of enclosing `usebackq delims==` in `"..."` causes a syntax error.
* Since `usebackq` is specified, the command to execute must be enclosed in `` `...` ``, not `'...'`

The correct form of this command is:

```
for /f "usebackq delims==" %i in (`set`) do @echo %i
````

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 362d60c8-8d69-6016-10bd-0f81114ec228
* Version Independent ID: 76d9a719-f621-f716-4987-68acb1501c63
* Content: [for](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/for)
* Content Source: [WindowsServerDocs/administration/windows-commands/for.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/for.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 5264 -b #assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. A documentation change has been made and will be live after the next business day. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
