### ISSUE TITLE
can ti check this?

### ISSUE THREAD

**Issue by alexaguilar89** [MicrosoftDocs/windowsserverdocs#5280]
[Enter feedback here]
<herlp to fix that pfroblem  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ee6351-fff8-19bd-93bc-842da70262f3
* Version Independent ID: 49d05de6-45b8-16ea-de91-e53e7ea4b1b2
* Content: [Upgrading your Remote Desktop Virtualization Host to Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/upgrade-to-rdvh)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/upgrade-to-rdvh.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/upgrade-to-rdvh.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @spatnaik
* Microsoft Alias: **spatnaik**

**Comment by spatnaik** [comment]
I've moved teams. Someone on Remote Desktop team should look in to this. Contact: KamV (alias)

**Comment by IngridAtMicrosoft** [comment]
#please-close
