### ISSUE TITLE
Assignment rather than assignation

### ISSUE THREAD

**Issue by pierrebestwork** [MicrosoftDocs/windowsserverdocs#5281]
[Enter feedback here]
"removes the drive-letter assignation" should probably be "removes the drive-letter assignment"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8476ea49-b196-7010-88f1-0c199b7cec41
* Version Independent ID: 320776d9-13d3-a1af-12b9-5066535e6871
* Content: [pushd](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/pushd)
* Content Source: [WindowsServerDocs/administration/windows-commands/pushd.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/pushd.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by RAJU2529** [comment]
@PRMerger8 , assign user to verify this PR #5289 
**https://github.com/MicrosoftDocs/windowsserverdocs/pull/5289**

**Comment by illfated** [comment]
@pierrebestwork : PR #5289 has now been merged and the changes are available live in the document https://docs.microsoft.com/windows-server/administration/windows-commands/pushd

Feel free to close this issue ticket if you agree that the issue has been resolved.

**Comment by illfated** [comment]
#please-close
