### ISSUE TITLE
Typo "fie" instead of "file"

### ISSUE THREAD

**Issue by guyrleech** [MicrosoftDocs/windowsserverdocs#5284]
On this line:

Using certreq -policy without any additional parameter opens a dialog window, allowing you to select the requested fie 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 912a2faa-63c4-43c7-056b-16f5a5c71038
* Version Independent ID: cbec348f-53ad-a5b7-5a6e-f1cc5540d212
* Content: [certreq](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/certreq_1)
* Content Source: [WindowsServerDocs/administration/windows-commands/certreq_1.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/certreq_1.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by IngridAtMicrosoft** [comment]
#please-close
