### ISSUE TITLE
Scoping in ADFS 2016 is mentioned as a new feature, but how to use it?

### ISSUE THREAD

**Issue by riesm** [MicrosoftDocs/windowsserverdocs#5290]
The documentation for ADFS 2016 specifically mentions this:

> Additionally, AD FS 2016 has support for the scoping parameter as described in the SAML Core specification, section 3.4.1.2. This element allows relying parties to specify one or more identity providers for an authentication request.

However, there is no mention on how to do this and I couldn't find this anywhere. Any tips/tricks or extra documentation on how to do this?

Our scenario would be that we would like to use scoping to our IdP (CPT) so that the IdP knows which authentication provider would be used. The SAML would look something like this:

`<samlp:Scoping xmlns:samlp=”urn:oasis:names:tc:SAML:2.0:protocol”>
  <samlp:IDPList>
    <samlp:IDPEntry ProviderID=”urn:etoegang:HM:0000000XXXXXXXX:entities:XXXX″/>
    <samlp:IDPEntry ProviderID=”urn:etoegang:EB:00000000XXXXXXXX:entities:XXXX″/>
  </samlp:IDPList>
</samlp:Scoping>
`

How could we send this to our CPT using ADFS 2016?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae507a19-3f9e-56be-609e-de0428f89c56
* Version Independent ID: 35f3b756-467d-587a-fee6-c225d4fa8a3f
* Content: [Improved interoperability with SAML 2.0](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/improved-interoperability-with-saml-2.0)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Improved-interoperability-with-SAML-2.0.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Improved-interoperability-with-SAML-2.0.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Hi @riesm. GitHub issues are for reporting problems with the documentation. For assistance with your implementation, please open a support ticket or post your question at [Microsoft Q & A](https://learn.microsoft.com/en-us/answers/questions/).
