### ISSUE TITLE
CLaimTypes incorrectly referencing HTTPs prefix instead of HTTP prefix

### ISSUE THREAD

**Issue by ChristianWeisse** [MicrosoftDocs/windowsserverdocs#5293]
in Reference: Complete list of user certificate claim types and example values
the Claim Description list is incorrectly using HTTPS prefixes and is not in line with the actuall ADFS Claims Descriptions 
which do not use the HTTPS but HTTP prefix

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7cc47f3-30fe-1a90-ac1f-6ddfe842ace8
* Version Independent ID: ed59c2d1-48f2-5b15-1b10-826e7d66f210
* Content: [Configure AD FS support for user certificate authentication](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-user-certificate-authentication)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-User-Certificate-Authentication.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-User-Certificate-Authentication.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @jenfieldmsft
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @ChristianWeisse,

Claim types prefix have been corrected in [PR #3383](https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/3383). We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
