### ISSUE TITLE
Remove Applies to:HCI in all the pages below

### ISSUE THREAD

**Issue by carlosmayol** [MicrosoftDocs/windowsserverdocs#5296]
The sentence: Applies to: Azure Stack HCI, Windows Server 2019, Windows Server 2016 is misleading. 

@khdownie  We already spoke about this recently. @cosmosdarwin  is supporting this as per HCI DL alias thread:

From: Cosmos Darwin <cosdar@microsoft.com> 
Sent: Tuesday, February 9, 2021 12:49 AM
To: Joachim Gomard <jgomard@microsoft.com>; Azure Stack HCI Discussion (FTE Only) <hcitalk@microsoft.com>; Jason Gerend <jgerend@microsoft.com>
Subject: RE: HCI 20H2 - Support for converged deployment?

Thanks Joachim. This is a good catch.

**@Jason Gerend can your team make the change so our docs don’t inadvertently imply support for disaggregated (aka “converged”) on the new Azure Stack HCI 20H2 OS?
Thanks!**

Cosmos

From: Joachim Gomard <jgomard@microsoft.com> 
Sent: Monday, February 8, 2021 9:25 PM
To: Azure Stack HCI Discussion (FTE Only) <hcitalk@microsoft.com>
Subject: HCI 20H2 - Support for converged deployment?

Hi All,

I’m working with Dell on an Azure Stack HCI opportunity in Algeria.
For unknown reasons, the customer plans to deploy a Converged cluster based on S2D.

In our public documentation about Storage Space Direct : Storage Spaces Direct overview that applies to Azure Stack HCI, WS 2019 and WS 2016 : 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 072d78ce-5d31-cea0-ef9f-0c5328e4b505
* Version Independent ID: e31b2c93-f040-8f71-b5b6-1f615b992de6
* Content: [Storage Spaces Direct overview](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/storage-spaces-direct-overview)
* Content Source: [WindowsServerDocs/storage/storage-spaces/storage-spaces-direct-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/storage-spaces-direct-overview.md)
* Product: **windows-server**
* Technology: **storage-spaces**
* GitHub Login: @cosmosdarwin
* Microsoft Alias: **cosdar**

**Comment by khdownie** [comment]
Hi @carlosmayol - so you are saying that this page should not mention Azure Stack HCI: https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/storage-spaces-direct-overview

**Comment by carlosmayol** [comment]
> Hi @carlosmayol - so you are saying that this page should not mention Azure Stack HCI: https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/storage-spaces-direct-overview

Correct! we have specific HCI documentation where we should cover any similarity and differences with Windows Server.
HCI is a new OS code branch and should be a New Doc branch with no cross-references that confuses our customers.

Thanks Sir.

**Comment by khdownie** [comment]
@carlosmayol I can't promise zero cross references because sometimes they are needed, but I get your point here. This issue is fixed and can be closed: https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/storage-spaces-direct-overview

**Comment by carlosmayol** [comment]
Awesome, thanks!
