### ISSUE TITLE
cmd

### ISSUE THREAD

**Issue by reza44** [MicrosoftDocs/windowsserverdocs#5301]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69b5a02c-32fd-3064-b368-20c67b13ba27
* Version Independent ID: d010fb83-9073-639b-a9ae-aa75d3cbfd44
* Content: [Commands by Server role](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/commands-by-server-role)
* Content Source: [WindowsServerDocs/administration/windows-commands/commands-by-server-role.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/commands-by-server-role.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
Looks like a test ticket, no information provided to act upon.

#please-close
