### ISSUE TITLE
Updated Azure ADFS Github reference

### ISSUE THREAD

**Issue by artro03** [MicrosoftDocs/windowsserverdocs#5302]
[Enter feedback here]
Hello
Is there a newer GitHub repo for deploying ADFS to Azure?  The one in this page hasn't been updated in over 5 years.  Wanted to ask for a customer who is deploying it with Server 2019 and ARM templates and newer VMs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ac8cd29-26cd-47da-5b3e-d58ba7c4a20c
* Version Independent ID: ae9587c8-0822-f5af-98ef-5386c4f17e58
* Content: [Active Directory Federation Services in Azure](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/how-to-connect-fed-azure-adfs)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/how-to-connect-fed-azure-adfs.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/how-to-connect-fed-azure-adfs.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by PRMerger19** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: ingridatmicrosoft 
gh issue comment 5294 -b ingridatmicrosoft

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
@artro03 Thank you for your input. We apologize for the delay in our response. I am sure you have found the Azure AD FS documentation by now.  This document was last updated in 2023.
https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/how-to-connect-fed-azure-adfs
