### ISSUE TITLE
Vertical bar not included in the list of special characters

### ISSUE THREAD

**Issue by hollasch** [MicrosoftDocs/windowsserverdocs#5303]
Near the bottom of this page is the following bullet point:

> • You must use quotation marks around the following special characters: & < > [ ] { } ^ = ; ! ' + , ` ~ [white space].

This list should also include the vertical bar.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0df94452-999b-43a0-be42-722fbabedaf3
* Version Independent ID: 84206d79-507f-b562-9d3f-cc3683b7abe6
* Content: [cmd](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cmd)
* Content Source: [WindowsServerDocs/administration/windows-commands/cmd.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/cmd.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by RAJU2529** [comment]
@hollasch . Thanks for pointing out. I am adding that character

**Comment by eross-msft** [comment]
Fixed.
#please-close
