### ISSUE TITLE
Please update table

### ISSUE THREAD

**Issue by jackvdbuk** [MicrosoftDocs/windowsserverdocs#5304]
Since version 1.0.24 web client now supports mic redirection.

Please amend 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7697c05-dd66-0803-cd60-c79ea972acf7
* Version Independent ID: 9c8e11b5-ed31-15af-4918-d9c66337bb1a
* Content: [Remote Desktop - compare the client apps redirections](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-app-compare)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-app-compare.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-app-compare.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
#assign:xelu86
