### ISSUE TITLE
Fall back flag confusion in example provided

### ISSUE THREAD

**Issue by BWMerlin** [MicrosoftDocs/windowsserverdocs#5306]
For the example given for "If you have only two time servers, you should specify the UseAsFallbackOnly flag (0x2) to de-prioritize one of them." the example is 
`w32tm /config /manualpeerlist:"ntpserver.contoso.com,0x8 clock.adatum.com,0xa" /syncfromflags:manual /update` but this example list "0xa" so is the "0xa" correct or a typo as the details for registry key entries found [here ](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings#parameters) list it as "0x02" while the text mentions "0x2".  So is the 0xa wrong and should be 0x2?  Is 0xa and 0x2 wrong and it should be 0x02?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d09b16e-4bbb-91fa-3d84-e7623ec4dc07
* Version Independent ID: b6eadad5-0167-34b6-ed3a-16fa7ee83c60
* Content: [Windows Time service tools and settings](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings)
* Content Source: [WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by Teresa-Motiv** [comment]
This issue should be reassigned--the article is currently being rewritten by another team, and that may resolve this issue.
PR for rewrite is MicrosoftDocs/windowsserverdocs-pr#1751

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @BWMerlin,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made concerning the example used and will be live after the next business day. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close

**Comment by BWMerlin** [comment]
The two documents https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings and https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings#parameters still have conflicting information.

One lists 0x2 as the fall-back while the other lists 0x02.  Which one is correct or are they both correct?

**Comment by Xelu86** [comment]
Hey @BWMerlin,

Thank you for this update. Both links provided are from the same article. We have updated it to reflect the correct registry settings to use:

- 0x1
- 0x2
- 0x4
- 0x8

The updated information will be live after the next business day. Have a great day!
