### ISSUE TITLE
Invalid email address specified

### ISSUE THREAD

**Issue by mfleisz** [MicrosoftDocs/windowsserverdocs#5308]
I tried to reach out to the email address specified in https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/removed-features-1903.md (rdsdev@microsoft.com).
However the address is non functional (returns SMTP error 550 - recipient address rejected).
Could you please provide the right mail address to contact the RDS dev team to acquire information for Remote Display IDD?

**Comment by illfated** [comment]
Link to the same document in the published docs.microsoft.com pages:
- https://docs.microsoft.com/windows-server/get-started-19/removed-features-1903

**Comment by illfated** [comment]
@daveba : The e-mail address referred to in the issue ticket post can be found in the second row of the table:

|                         Feature                         |                                                                                                                                                                                                                                                                                                                                                                                                                           Instead you can use                                                                                                                                                                                                                                                                                                                                                                                                                            |
|---------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|              Hyper-V vSwitch on LBFO                |                                                                                                                                                                  In a future release, the Hyper-V vSwitch will no longer have the capability to be bound to an LBFO team. Instead, it must be bound via [Switch Embedded Teaming (SET)](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v-virtual-switch/RDMA-and-Switch-Embedded-Teaming.md#switch-embedded-teaming-set).                                                                                                                                                                    |
|       XDDM-based remote display driver (**new**)        |                                                                                                                                          Starting with this release the Remote Desktop Services uses a Windows Display Driver Model (WDDM) based Indirect Display Driver (IDD) for a single session remote desktop. The support for Windows 2000 Display Driver Model (XDDM) based remote display drivers will be removed in a future release. Independent Software Vendors that use XDDM-based remote display driver should plan a migration to the WDDM driver model. For more information on implementing remote display indirect display driver ISVs can reach out to [rdsdev@microsoft.com](mailto:rdsdev@microsoft.com).                                                                                                                                           |

**Comment by illfated** [comment]
@mfleisz : I tested sending an email to the address rdsdev@microsoft.com right now, using my Microsoft account e-mail address, from https://outlook.live.com/ and it did not return to me, at least not immediately. I will keep my outlook.live.com mailbox open for a few hours to check if anything happens. I would expect the message to get kicked back very soon if the target address is invalid or unreachable.

**Comment by mfleisz** [comment]
@illfated I just tried again and this is the reply I get (it's the same as before):

> This message was created automatically by mail delivery software.
> 
> A message that you sent could not be delivered to one or more of its recipients. This is a permanent error. The following address(es) failed:
>
>  rdsdev@microsoft.com
>    host microsoft-com.mail.protection.outlook.com [104.47.54.36]
>    SMTP error from remote mail server after RCPT TO:<rdsdev@microsoft.com>:
>    550 5.4.1 Recipient address rejected: Access denied. AS(201806281) [DM3NAM06FT010.Eop-nam06.prod.protection.outlook.com]
>
> Reporting-MTA: dns; mail.thincast.com
> 
> Action: failed
> Final-Recipient: rfc822;rdsdev@microsoft.com
> Status: 5.0.0
> Remote-MTA: dns; microsoft-com.mail.protection.outlook.com
> Diagnostic-Code: smtp; 550 5.4.1 Recipient address rejected: Access denied. AS(201806281) [DM3NAM06FT012.Eop-nam06.prod.protection.outlook.com]

I am using my company's mail account (which is also registered as a Microsoft account).

**Comment by illfated** [comment]
Thank you for posting again and replying to my comment. That is odd, I still have not received any return mail or anything indicating that my message failed like yours did. I can post the content I sent, just to let you know:

From: Trond Børge Krokli
Sent: lørdag 20. februar 2021 23:00
To: rdsdev@microsoft.com <rdsdev@microsoft.com>
Subject: Feedback from docs.microsoft.com - is this address correct?
 
Ref. https://github.com/MicrosoftDocs/windowsserverdocs/issues/5308

On February 19, 2021, 11:48 AM GMT+1, Martin Fleisz (@mfleisz) wrote:
> I tried to reach out to the email address specified in
> https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started-19/removed-features-1903.md 
> (rdsdev@microsoft.com).
>
> However the address is non functional (returns SMTP error 550 - recipient address rejected).
> Could you please provide the right mail address to contact the RDS dev team to acquire information for Remote Display IDD?

Is this a correct obeservation, or is the published address shielded to only provide access for privileged users?

Feel free to post in the GitHub issue ticket in case the address needs changing in the documentation.

---------------
Best regards,
Trond B. Krokli
(@illfated on GitHub - https://github.com/illfated)


outlook.live.com also took a small preview of my GitHub account image along with some text underneath my signature, based on the link in my signature:

|   |    |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/38162891/108762846-e2edc980-7550-11eb-8e6d-3765fed3d9aa.png) | illfated (Trond B. Krokli) · GitHub
Computer support & general IT technician. illfated has 7 repositories available. Follow their code on GitHub / github.com |

(The image & text has much smoother formatting in the HTML format used on outlook.live.com, but that is only a cosmetic detail, should not have any bearing on this issue.)

**Comment by mfleisz** [comment]
@illfated I tried again from 2 of my private mail address and again - each time I receive SMTP 550:

> <rdsdev@microsoft.com>: host
>    microsoft-com.mail.protection.outlook.com[104.47.53.36] said: 550 5.4.1
>    Recipient address rejected: Access denied. AS(201806281)
>    [BL2NAM06FT008.Eop-nam06.prod.protection.outlook.com] (in reply to RCPT TO
>    command)

Additionally Google Mail i.e. says that my mail was "blocked" so I guess your suspicion of the address being shielded is quite possible ...

**Comment by illfated** [comment]
OK. Thank you for keeping me updated. Maybe test it from a new outlook.com email address, in case Microsoft-friendly sources are preferred.

**Comment by mfleisz** [comment]
@illfated just tried with an Outlook.com mail account but it is still erroring:


> Undeliverable: Remote Display Indirect Display Driver
> DM3NAM06FT006.mail.protection.outlook.com rejected your message to the following email addresses:
>
> rdsdev@microsoft.com (rdsdev@microsoft.com)
> Your message was rejected by the recipient's domain because the recipient's email address isn't listed in the domain's directory. It might be misspelled or it might not exist. Try to fix the problem by doing one or more of the following:
> 
> * Send the message again - delete and retype the address before resending. If your email program automatically suggests an address to use, don't select it - type the complete email address.
> * Clear the recipient Auto-Complete List in your email program by following the steps in this article. Then resend the message.
>
> For Email Administrators
> Directory based edge blocking is enabled for the recipient's organization and the recipient wasn't found in their directory. If the sender is using the correct address but continues to experience the problem, contact the recipient's email admin and tell them about the problem. To fix this they should resynchronize their on-premises and cloud directories.

It looks like nobody outside of Microsoft is able to contact this mail address. Can you ask them if they can have a look at their configuration or if they can get in touch with me? We eagerly need Information from them so any help will be appreciated!

**Comment by illfated** [comment]
Sorry for the delay, my office work time has been tough lately, but I will send a new email to the address, asking them (as you suggested) to get in touch with you (and maybe even inform you of which limitations they have set for their address. (Need to sleep a lot more these days, hence the delay.)

**Comment by mfleisz** [comment]
@illfated sorry as well for the late reply but I was on vacation and just got back to the office so - no worries ;-) Thanks for reaching out to the RDS dev team - just hope they will get in touch soon (so far no news yet).

**Comment by illfated** [comment]
Thank you for the update, fair enough. I have got enough on my plate these days, as well as being tired of a long winter with all the lockdowns and restrictions.

**Comment by illfated** [comment]
I sent another e-mail to the address rdsdev@microsoft.com just to remind them, and in case my messages end up in a spam filter at the other end (no idea). My tiny hope is that the message could encourage them to visit this page.

**Comment by mfleisz** [comment]
@illfated thanks a lot for your help! Highly appreciated!

**Comment by doctordns** [comment]
We have seen this issue before with email addresses in docs not being correctly or correctly handled. This can happen when a manager leaves and the alias is no longer used. In general, the best way forward would be for someone inside MSFT to reach out to the team to get clarification.. After all, it is in the team's best interest that mail addresses like this are accurate and allow customers to communicate back to the team.

**Comment by illfated** [comment]
@mfleisz : Today, after taking a deep dive in my spam folder, I found that my messages have been rejected due to the following reason:

> BL2NAM06FT010.mail.protection.outlook.com rejected the message you sent to the following email address:
>
> rdsdev@microsoft.com (rdsdev@microsoft.com)
> The message was rejected by the recipient's domain because the recipient's email address is not listed in the domain's directory. Your email address may be misspelled or may not exist.

This indicates that the email address rdsdev@microsoft.com may be deleted, or could be completely blocked from receiving any email messages by public Microsoft mail hosts.

**Comment by mfleisz** [comment]
@illfated after posting over at Microsoft Q&A the mail address is now working again (https://docs.microsoft.com/answers/answers/301721/view.html). Thanks a lot for your help! I guess this can be closed now.

**Comment by illfated** [comment]
Wow, that is very nice to read, I am so happy on your behalf. I am also relieved that spending time on this issue was not a total loss. Good job, thank you for the good news.

**Comment by illfated** [comment]
#please-close
