### ISSUE TITLE
$PSVersionTable.BuildVersion

### ISSUE THREAD

**Issue by tommymaynard** [MicrosoftDocs/windowsserverdocs#5310]
The BuildVersion property of `$PSVersionTable` was a _Windows_ PowerShell-only property. You may want to use the word "Windows" as a modifier for PowerShell on this page. Additionally, perhaps this page should include the property name for PowerShell -- the non-Windows PowerShell, PowerShell. The best property for the job for PowerShell appears to be `$PSVersionTable.OS`.

**Windows PowerShell**
```
[WPS5.1] C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.610
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.610
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

[WPS5.1] C:\> $PSVersionTable.BuildVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      19041  610
```
**PowerShell**
```
[PS7.1.0] C:\> $PSVersionTable.OS
Microsoft Windows 10.0.19042
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ec5477-2ed5-373e-417d-98536e0a52c5
* Version Independent ID: d352661a-2f30-07b9-b1c9-029483faedfc
* Content: [ver](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/ver)
* Content Source: [WindowsServerDocs/administration/windows-commands/ver.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/ver.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
Looks like a good suggestion. Feel free to create a Pull Request to have this change added to the document page.

**Comment by PRMerger8** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: ingridatmicrosoft 
gh issue comment 5299 -b ingridatmicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @tommymaynard,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made to reflect both PS versions and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
