### ISSUE TITLE
Error while execute Register-PSSessionConfiguration

### ISSUE THREAD

**Issue by marcinfaza** [MicrosoftDocs/windowsserverdocs#5315]
This procedure doesn't work for me, once I'm trying to execute Register-PSSessionConfiguration
following error is thrown:
Register-PSSessionConfiguration : The trust relationship between the primary domain and the trusted domain failed.
It doesn't make any sense for me. don't even what trust it is about, I've single domain AD here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2dd1426-8251-d4a1-1082-286e0cc78b45
* Version Independent ID: b205687f-f9f9-a3f5-772f-3fad427bf828
* Content: [Delegate AD FS Powershell Commandlet Access to Non-Admin Users](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/delegate-ad-fs-pshell-access)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/delegate-ad-fs-pshell-access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/delegate-ad-fs-pshell-access.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
@marcinfaza Thanks for your contribution to Microsoft Docs! The GitHub issues for this repo are for issues with the documentation. If you haven't resolved the result of using the procedure on this page, please open a support ticket or post to our community forum on Technet.  If you have found that the documentation is incorrect, please let us know and ask for this issue to be reopened.

#please-close
