### ISSUE TITLE
missing latest update version

### ISSUE THREAD

**Issue by cshea-msft** [MicrosoftDocs/windowsserverdocs#5317]
[Enter feedback here]
A customer mentioned they downloaded 1.2.1755.0 version today and but the doc says the latest version is 1.2.1750.0. Can someone add the update for the 1.2.1755.0 on the doc and what is coming with that update. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f43e914-5ede-6f18-2fbc-165f3386f7cb
* Version Independent ID: a9489295-572d-ff60-6bff-a44390ac4031
* Content: [What's new in the Windows Desktop client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop-whatsnew)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop-whatsnew.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop-whatsnew.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey cshea-msft,

Thanks again for contacting Microsoft, we value your feedback. 

Based on the time this issue was created, a documentation update was made, and this issue was not closed. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
