### ISSUE TITLE
Wrong Title of content. It is NOT about Store Client but about Remote desktop Client.

### ISSUE THREAD

**Issue by TheNightmanX** [MicrosoftDocs/windowsserverdocs#5320]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67b7b5a4-647e-fee3-6533-6ed88ae45bfa
* Version Independent ID: d9102859-0147-346f-8268-6e2a75c8b0b7
* Content: [What's new in the Microsoft Store Client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windows-whatsnew)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windows-whatsnew.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windows-whatsnew.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by RAJU2529** [comment]
@TheNightmanX . Thanks for reporting. I am going to fix it now.

**Comment by TheNightmanX** [comment]
It seems that the Title reflects, that it is regarding the Microsoft Store Version of The Remote Desktop Client.

**Comment by RAJU2529** [comment]
@TheNightmanX ,  i try to change like below 
**What's new in the Microsoft Remote Desktop Store Client**
is  above title  is  good

**Comment by illfated** [comment]
@TheNightmanX : Please keep this ticket open until the page has been updated by creating a PR linked to this ticket, and the same PR being merged to add the change to the page reported in this ticket.

**Comment by illfated** [comment]
Thank you. 👍🏻
