### ISSUE TITLE
How to redirect output to NUL

### ISSUE THREAD

**Issue by andrisi** [MicrosoftDocs/windowsserverdocs#5321]
[Enter feedback here]

Please add an example of how to start a command and redirect it's output to NUL. I'm trying to start WinAppDriver and it's output is just slowing it down considerably sometimes. Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a52b78b6-e846-0b32-25c0-f9aab145b112
* Version Independent ID: 0c56bb98-4f1f-dd55-63ae-8bb18535cee1
* Content: [start](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start)
* Content Source: [WindowsServerDocs/administration/windows-commands/start.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/start.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
Read these pages, they should cover the case of getting STDERR to redirect to NUL :
- https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-xp/bb490982(v=technet.10)
- https://stackoverflow.com/questions/4507312/how-to-redirect-stderr-to-null-in-cmd-exe

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
Hey andrisi,

Thanks again for contacting Microsoft, we value your feedback. 

The documentation for command redirection is found at: https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/cpp/language-compilers/redirecting-error-command-prompt

Per the issue you're having, please see the [GitHub content feedback guidelines](https://github.com/MicrosoftDocs/windowsserverdocs#github-content-feedback-guidelines)

As this is a non-documentation issue, we'll be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
