### ISSUE TITLE
Topology Diagrammer no longer available

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/windowsserverdocs#5323]
Apparently you guys have removed the AD Topology Diagrammer tool from public downloads.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b94f000b-e4bb-1d71-7940-4972466d77aa
* Version Independent ID: f95232f6-5567-ba82-361a-32f4fb6961b0
* Content: [AD Forest Recovery - Devising an AD Forest Recovery Plan](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/ad-forest-recovery-devising-a-plan)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/AD-Forest-Recovery-Devising-a-Plan.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/manage/AD-Forest-Recovery-Devising-a-Plan.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by RAJU2529** [comment]
@PRMerger18 . I also confirmed that the link belongs to ** AD Topology Diagrammer tool** is broken

**Comment by dknappettmsft** [comment]
Link removed as it's no longer available - PR: https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/1811

#please-close
