### ISSUE TITLE
The link to Netsh Technical Reference at the end of the page is broken

### ISSUE THREAD

**Issue by Veverke** [MicrosoftDocs/windowsserverdocs#5325]
[Enter feedback here]
The link to Netsh Technical Reference at the end of the page is broken (under Content Availability)
https://docs.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdf15d6d-c63e-6ec4-d1c0-bb800eec7f12
* Version Independent ID: 595b6b57-f169-e38d-35d7-91eaa3b33610
* Content: [Network Shell (Netsh)](https://docs.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh)
* Content Source: [WindowsServerDocs/networking/technologies/netsh/netsh.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/netsh/netsh.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by illfated** [comment]
Right. That link points to the retired TechNet Gallery pages, but I will see if the content has been migrated to the new TechNet pages.

**Comment by illfated** [comment]
Looks like only the Server 2008 version is available (for now, at least):
- https://docs.microsoft.com/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc725935(v=ws.10)

**Comment by illfated** [comment]
Looks like the Windows Help file format download has been removed, leaving the end section dangling in empty space:

***

### Content availability

The Network Shell Technical Reference is available for download in Windows Help \(*.chm\) format from TechNet Gallery: [Netsh Technical Reference](https://gallery.technet.microsoft.com/Netsh-Technical-Reference-c46523dc)

***

Looks like we should replace the text reference and link 
to the 2008/2008 R2/Windows 7 pages. Also, maybe move the 
blue **Important** note about **PowerShell** being 
preferred over Netsh on Windows 10/Server 2016 and newer, 
down to right before the **Content availability** section.

**Suggested solution:**

***

## Network Shell (Netsh) Technical Reference

The Netsh Technical Reference provides a comprehensive netsh command reference, including syntax, parameters, and examples for netsh commands. You can use the Netsh Technical Reference to build scripts and batch files by using netsh commands for local or remote management of network technologies on computers running Windows Server 2016 and Windows 10.

> [!IMPORTANT]
> It is recommended that you use Windows PowerShell to manage networking technologies in [Windows Server 2016 and Windows 10](/powershell/windows/get-started) rather than Network Shell. Network Shell is included for compatibility with your scripts, however, and its use is supported.

### Content availability

- Available in the Windows Server 2008 R2 and Windows Server 2008 archive: https://docs.microsoft.com/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc725935(v=ws.10)

**Comment by Xelu86** [comment]
Hey @Veverke, 

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made to redirect users to our [netsh command reference](https://learn.microsoft.com/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc754516(v=ws.10)) as the other resource is no longer available. Changes will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
