### ISSUE TITLE
Feature Request:  Basic Logging

### ISSUE THREAD

**Issue by mpearon** [MicrosoftDocs/windowsserverdocs#533]
Maybe I've just not run across them yet, but I think it would be handy to have a basic audit log for Honolulu.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 786aeae9-05e3-50e3-4d33-46c5a8174576
* Version Independent ID: b5f7ee33-6b8e-005a-f8de-fb57aa2841e2
* Content: [Microsoft Project Honolulu Frequently Asked Questions](https://docs.microsoft.com/en-us/windows-server/manage/honolulu/honolulu-faq)
* Content Source: [WindowsServerDocs/manage/honolulu/honolulu-faq.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/honolulu/honolulu-faq.md)
* Service: **unspecified**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by lizap** [comment]
HI, Matthew (again :) ) - best bet is to go to http://aka.ms/HonoluluFeedback to request basic logging capability. The team is currently working on improvements to Honolulu. Thanks!
