### ISSUE TITLE
Dnscache service can't be stopped or modified due to restrictive security permissions

### ISSUE THREAD

**Issue by AndisGrossteins** [MicrosoftDocs/windowsserverdocs#5332]
It is not possible to stop or disable the Dnscache service on Windows 10 (10.0.19042.844) because security permissions don't allow the Administrators group or even the `SYSTEM` account to stop the service or modify its configuration.

It seems that the permissions of many services have changed in recent versions of Windows 10 but the documentation doesn't reflect those changes.

For example, in an elevated command prompt:
```cmd
> sc stop dnscache
[SC] OpenService FAILED 5:

Access is denied.
```
Same result when running the command as the `NT AUTHORITY\SYSTEM` account.

For now, the only option to disable the service is by modifying the `Start` type parameter in the service registry entry `HKLM\SYSTEM\CurrentControlSet\Services\Dnscache`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a78b6afe-349f-9bf7-60bd-00d8953f8ab7
* Version Independent ID: f99a1fb5-a1a6-9d3e-2cc5-f8bcd442ad88
* Content: [Disable DNS client-side caching on DNS clients](https://docs.microsoft.com/en-us/windows-server/networking/dns/troubleshoot/disable-dns-client-side-caching)
* Content Source: [WindowsServerDocs/networking/dns/troubleshoot/disable-dns-client-side-caching.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/dns/troubleshoot/disable-dns-client-side-caching.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by IngridAtMicrosoft** [comment]
Addressed. #please-close
