### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by TrixM** [MicrosoftDocs/windowsserverdocs#5337]
Continuing the trend of recent changes breaking links to core documentation, this link is no longer functional: https://go.microsoft.com/fwlink/?linkID=28523

It may have pointed to the Server 2003 Reskit tools formerly at http://www.microsoft.com/download/en/details.aspx?id=17657

This are no longer available anywhere.

Since the tool no longer exists, removing all mention of it is probably best. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47705e9-bd32-04e8-9647-3ff6c6b373a3
* Version Independent ID: 80eec322-c2b0-7d71-2171-b6342f888013
* Content: [Active Directory Replication Concepts](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/get-started/replication/active-directory-replication-concepts)
* Content Source: [WindowsServerDocs/identity/ad-ds/get-started/replication/Active-Directory-Replication-Concepts.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/get-started/replication/Active-Directory-Replication-Concepts.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by illfated** [comment]
Seems like a correct observation, the link no longer points to any available download, it simply resolves to the general non-specific download page.

Removing the paragraph would be a useful solution. Going to suggest that in a PR later.

**Comment by dknappettmsft** [comment]
Link and reference removed as it's no longer available.

#please-close

**Comment by illfated** [comment]
@dknappettmsft : Thank you for following up on this. Very good.
