### ISSUE TITLE
Feature Request:  Disable Extension Manager

### ISSUE THREAD

**Issue by mpearon** [MicrosoftDocs/windowsserverdocs#534]
The ability to disable user's ability to add extension at a global level would be a nice feature.

**Comment by lizap** [comment]
Hi, Matthew - probably your best bet is to submit this same feedback in the Windows Server User Voice forum: https://windowsserver.uservoice.com/forums/295047-general-feedback

This channel is for feedback on the content. While we love to see feature requests, we don't have a way to track and submit them through this channel. As such I'm going to close this request, but seriously, please do submit this suggestion to User Voice. Thanks!
