### ISSUE TITLE
wrong path

### ISSUE THREAD

**Issue by welsen1** [MicrosoftDocs/windowsserverdocs#535]
sqlcmd -S \\.\pipe\Microsoft\#\#WID\tsql\query use master
should be 
sqlcmd -S \\.\pipe\Microsoft##WID\tsql\query use master

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e2a5a31-29b9-5599-2f14-bc244c5da034
* Version Independent ID: 393db29c-0866-46f4-9ee6-7ae82e8cb29f
* Content: [Migrating the WSUS Database from (Windows Internal Database) WID to SQL](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/manage/wid-to-sql-migration)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/manage/wid-to-sql-migration.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/manage/wid-to-sql-migration.md)
* Service: **unspecified**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by aydeisen** [comment]
@welsen1: a correction I submitted for the document, which included the sqlcmd code, was published yesterday.  Does the update resolve this issue?
