### ISSUE TITLE
NFS Client v4.1 support in Windows Server 2016/2019?

### ISSUE THREAD

**Issue by pconijn** [MicrosoftDocs/windowsserverdocs#5350]
Has Microsoft planned or has plans to support NFS client v4.1 in Windows Server 2016/2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20741e00-6d40-c122-88b2-562b38d39b1e
* Version Independent ID: e556fb83-dc86-94ed-d0e0-616a6499c1e8
* Content: [Network File System overview](https://docs.microsoft.com/en-us/windows-server/storage/nfs/nfs-overview?source=docs)
* Content Source: [WindowsServerDocs/storage/nfs/nfs-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/nfs/nfs-overview.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @pconijn,

Thanks again for contacting Microsoft. We value your feedback. 

At this current moment in time, NFS _Client_ v4.1 is not supported in any of the operating system versions in the documented list. This is not to say that it may or may or may not be in future works, but I cannot speak on this. 

We will now be closing this thread. Thank you and have a most pleasant day. #please-close
