### ISSUE TITLE
NPS not explained

### ISSUE THREAD

**Issue by Mcafee123** [MicrosoftDocs/windowsserverdocs#5355]
i do not understand the term "NPS". can you please explain?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52c36415-d21e-cc3b-44f4-4626e0053029
* Version Independent ID: 4d23b36a-6d3b-be93-dd70-49caae51e199
* Content: [Refresh Group Policy](https://docs.microsoft.com/en-us/windows-server/networking/core-network-guide/cncg/server-certs/refresh-group-policy)
* Content Source: [WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Refresh-Group-Policy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Refresh-Group-Policy.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
https://docs.microsoft.com/en-us/windows-server/networking/technologies/nps/nps-top

## Network Policy Server (NPS)

>Applies to: Windows Server (Semi-Annual Channel), Windows Server 2016, Windows Server 2019
You can use this topic for an overview of Network Policy Server in Windows Server 2016 and Windows Server 2019. NPS is installed when you install the Network Policy and Access Services (NPAS) feature in Windows Server 2016 and Server 2019.

***

(The link to the NPS pages can be found further down in the page tree hierarchy on the left hand side of the original document.)

***

![image](https://user-images.githubusercontent.com/38162891/110552163-1b87c880-8137-11eb-8648-ef3eda6634af.png)

**Comment by Mcafee123** [comment]
Thank you. I propose to add a link on the Term NPS to the page you mentioned, for a better understanding.

**Comment by illfated** [comment]
Fair enough. Please be aware that the general MS Docs codestyle recommends using the full name, followed by the acronym, the first time it is used.

Later on, the acronym can be used more freely, alternatively reversed with the acronym before the full name in parentheses, if the name and acronym is very new and not before described topic.

**Comment by illfated** [comment]
Just as an example, improving the issue could be done like this:
***

## Network Policy Server (NPS)

> Applies to: Windows Server (Semi-Annual Channel), Windows Server 2016, Windows Server 2019

You can use this topic for an overview of Network Policy Server in Windows Server 2016 and Windows Server 2019. **Network Policy Server (NPS)** is installed when you install the Network Policy and Access Services (NPAS) feature in Windows Server 2016 and Server 2019.

**Comment by RAJU2529** [comment]
I am adding NPS link into this  article.

**Comment by illfated** [comment]
Good suggestion. PR #5361 is ready for review, comments and further suggestions.

**Comment by craigcaseyMSFT** [comment]
Hello @Mcafee123,

Thanks for contacting Microsoft. We value your feedback.

Documentation changes have been made to clarify and acknowledge this issue. The doc changes are now live.

Thank you again and have a most pleasant day.
#please-close
