### ISSUE TITLE
Link to Data Classification Toolkit

### ISSUE THREAD

**Issue by Snozzberries** [MicrosoftDocs/windowsserverdocs#5356]
Microsoft Data Classification Toolkit link does not work within §Simplifying Security for End Users

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4475bd58-e078-6883-2fd5-0fb176b58ca6
* Version Independent ID: 9a42f3a6-33b8-5ec5-b136-ff34ff43ab13
* Content: [Planning for Compromise](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/planning-for-compromise)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Planning-for-Compromise.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Planning-for-Compromise.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by dknappettmsft** [comment]
Link and reference removed as it's no longer available.

#please-close
