### ISSUE TITLE
Can you please include a link to the Visio diagram for this one ? 

### ISSUE THREAD

**Issue by dmali777** [MicrosoftDocs/windowsserverdocs#5360]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200b266e-1c8e-63ef-3853-de91aebd8d04
* Version Independent ID: 8884c7fe-32c7-5f10-3fb4-308b951b6b6d
* Content: [Remote Desktop Services architecture](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/desktop-hosting-logical-architecture)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/Desktop-hosting-logical-architecture.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/Desktop-hosting-logical-architecture.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
@dmali777 I'm sorry but we don't offer Visio diagrams on the Docs site.
