### ISSUE TITLE
Typo in WVD classic discovery URL

### ISSUE THREAD

**Issue by rpstester** [MicrosoftDocs/windowsserverdocs#5363]
The "Windows Virtual Desktop (classic)" discovery URL is misspelled.  It says "webfedd" instead of "webfeed". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca8081a3-ec92-8aa5-2a51-1c10a298fdd1
* Version Independent ID: 6c33184e-2ef8-0b7c-8666-50d4c4b16c7e
* Content: [Set up email discovery to subscribe to your RDS feed](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-email-discovery)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-email-discovery.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-email-discovery.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @ChristianMontoya
* Microsoft Alias: **chrimo**

**Comment by RAJU2529** [comment]
@rpstester https://rdweb.wvd.microsoft.com/api/feeddiscovery/webfeeddiscovery.aspx

https://rdweb.wvd.microsoft.com/api/arm/feeddiscovery 

not miss spelled

**Comment by illfated** [comment]
The link was corrected in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/5f9957172568e0b443c785638da8ff0815a25a12 yesterday (March 12, 2021, at 03:03 AM GMT+1), and this ticket was opened on March 11, 2021 at 09:44 PM GMT+1, 5 hours and 19 minutes earlier. 

It looks like this ticket could have been a source for the typo being corrected.

**Comment by rick-man** [comment]
That's correct. Thanks for reporting this typo.

#please-close
