### ISSUE TITLE
Wrong options for /bootmode

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/windowsserverdocs#5369]
My system (Microsoft Windows 10.0.21337) has different options for `/bootmode`:

```text
    /bootmode
        Specifies the Driver Verifier boot mode. This option requires system
        reboot to take effect.

          persistent        Ensures that Driver Verifier settings are
                            persistent across reboots. This is the default
                            value.
          resetonbootfail   Disables Driver Verifier for subsequent reboots
                            if the system failed to start.
          resetonunusualshutdown
                            Driver Verifier persists until unusual shutdown
                            happens. Its abbrevation, 'rous', can be used.
          oneboot           Enables Driver Verifier only for the next boot.
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5828ff59-dddb-9bdb-7f9d-7fa8b8e5a02c
* Version Independent ID: b244e83a-8e49-4f45-0201-cfa4849cea8a
* Content: [verifier](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/verifier)
* Content Source: [WindowsServerDocs/administration/windows-commands/verifier.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/verifier.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by RAJU2529** [comment]
@paulomorgado , On windows 10 64bit v21H1, the same options are shown according to your post is correct.  but  we need to check in windows server OS after that only we can conclude and if need, i will change those options in the article

**Comment by paulomorgado** [comment]
Which build build, @RAJU2529?

**Comment by RAJU2529** [comment]
@paulomorgado . windows 10  build   19043.867

![Capture](https://user-images.githubusercontent.com/3296790/111350654-585c3e00-86a8-11eb-90e0-080cfd4374d4.JPG)

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @paulomorgado,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting the table to display this information and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
