### ISSUE TITLE
Issue With Per-User CALs

### ISSUE THREAD

**Issue by dennisbaker** [MicrosoftDocs/windowsserverdocs#537]
I am attempting to deploy this in my environment and I've run into an issue. When running the Publish-RDWebClientPackage cmdlet I am receiving an error that per-device CALs are not supported. However, my enviroment is configured with Per-User CALs. I have verified this in the deployment properties in Server Manager. Any suggestions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Service: **unspecified**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by dennisbaker** [comment]
Apparently I am concerned about nothing as that was just a warning. You may want to consider suppressing that warning if it isn't relevant.

**Comment by lizap** [comment]
Thanks, Dennis - while we're not suppressing the warning, we have added a note to this article to explain why you see it. That note will be live probably on 3/29. Thanks!

**Comment by lizap** [comment]
The note re: this issue is now live in the article, so I'm going to close this issue. Thanks for raising the issue, Dennis!
