### ISSUE TITLE
microsoftDocs

### ISSUE THREAD

**Issue by Dithn** [MicrosoftDocs/windowsserverdocs#5371]
[ป้อนคำติชมที่นี่]

---
#### รายละเอียดเอกสาร

⚠ *อย่าแก้ไขส่วนนี้ กำหนดให้ต้องจัดทำ docs.microsoft.com ➟ การเชื่อมโยงปัญหา GitHub*

* ID: 28e747b1-411e-7f53-69d5-69c3730bf223
* Version Independent ID: d8da91d3-7b35-5a49-e484-e16fc31011ef
* Content: [Change a Master Boot Record (MBR) into a GUID partition table (GPT) disk](https://docs.microsoft.com/th-th/windows-server/storage/disk-management/change-an-mbr-disk-into-a-gpt-disk)
* Content Source: [WindowsServerDocs/storage/disk-management/change-an-mbr-disk-into-a-gpt-disk.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/change-an-mbr-disk-into-a-gpt-disk.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
No valid content found in the issue ticket, only [Enter your feedback here] (in Thai).

#please-close
