### ISSUE TITLE
Very nice document

### ISSUE THREAD

**Issue by SixSigmaGuy** [MicrosoftDocs/windowsserverdocs#5379]
After reading through tons of documents today about managing servers, it was so nice to get to this one that was so concise and complete.  I was really confused on what ssh was before this.  But this document cleared up my confusion by not complicating it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89f816fb-37f4-ce80-1723-783f534acaf7
* Version Independent ID: 817a16e8-741f-0f38-cee3-ae4a36e6e83e
* Content: [Overview about OpenSSH for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_overview)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Overview.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by RAJU2529** [comment]
@SixSigmaGuy. Thanks for your valuable feedback. From your post I understand that you liked this article. . Authors will be happy if they see your feedback. 
keep reading all our Microsoft documents and article.
