### ISSUE TITLE
OpenSSH documentation incorrectly categorizes StrictModes as not supported

### ISSUE THREAD

**Issue by alvinzhengq** [MicrosoftDocs/windowsserverdocs#5388]
OpenSSH Server Configuration Documentation incorrectly categorizes StrictModes as a not supported setting. 

While testing OpenSSH configurations on a Window Server 2019 machine, I noticed that the StrictMode setting in C:\ProgramData\ssh\sshd_config did have an effect on SSH authentication. When the setting is set to `on` and I attempt to authenticate with the OpenSSH Server using public key authentication it returns a User Authentication Error, but when the setting is set to `off` the authentication works successfully.

This indicates that the StrictMode setting does indeed check for local folder permissions on Windows and is in fact supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8ad5c9a-efb1-d994-0e3c-53c90096a245
* Version Independent ID: 5cb0ea97-4c3d-ffdf-b69c-8a717f9f9f3f
* Content: [OpenSSH Server Configuration for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_server_configuration)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Server_Configuration.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Server_Configuration.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by robinharwood** [comment]
Hi @alvinzhengq ,


Thanks for your dedication to our documentation. I have shared your feedback with the team and have confirmed that although StrictModes may work it is not currently supported and remains in the currently published list. You can of course raise an issue in the [engineering repository](https://github.com/PowerShell/Win32-OpenSSH/issues) for this functionality.

As this does not require an update to the documentation, we are closing this pull request for now.

Thanks,
Robin

#please-close
