### ISSUE TITLE
Out of date - Repair-AuthorizedKeyPermission

### ISSUE THREAD

**Issue by nekdima** [MicrosoftDocs/windowsserverdocs#5395]
[Enter feedback here]

Module **Repair-AuthorizedKeyPermission** can't be installed since it's out of date. Please update the documentation.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH key management for Windows](https://docs.microsoft.com/en-gb/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by RAJU2529** [comment]
@maertendMSFT , Can i add a reference link to this article 
**https://techcommunity.microsoft.com/t5/itops-talk-blog/installing-and-configuring-openssh-on-windows-server-2019/ba-p/309540**

**Comment by nekdima** [comment]
> @maertendMSFT , Can i add a reference link to this article
> **https://techcommunity.microsoft.com/t5/itops-talk-blog/installing-and-configuring-openssh-on-windows-server-2019/ba-p/309540**

This article is on the same level as official documentation and promotes the usage of **OpenSSHUtils** module which is no longer available.

**Comment by dknappettmsft** [comment]
Thanks for submitting this issue. I have reworked this document to remove or replace parts that are no longer relevant or correct based on this and several other issues raised for this page.

The changes should be visible in around 6-12 hours.

#please-close
