### ISSUE TITLE
Format parameter link to wrong page

### ISSUE THREAD

**Issue by pamf** [MicrosoftDocs/windowsserverdocs#5396]
Hello,

When we click on the format parameter, we go to the **format CMD line command** and we should go to the **diskpart format** parameter reference.

Thank you.

Paulo Mesquita

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bca0f8f7-da0d-6340-bf63-f269be5f64d1
* Version Independent ID: 39758423-e92d-d2db-88f3-260dc5a1a26a
* Content: [diskpart](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/diskpart)
* Content Source: [WindowsServerDocs/administration/windows-commands/diskpart.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/diskpart.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by RAJU2529** [comment]
@pamf . Format linked page is correct only.
Format commands work only under diskpart parameters.

at first , you need to go to diskpart and type  format  commands

**Comment by illfated** [comment]
@pamf : You need to read the Previous Versions Documentation to find the information you are looking for:

- Windows Server 2008 R2 and Windows Server 2008 (https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-r2-and-2008/dd349801(v=ws.10))
- Windows Server Commands, References, and Tools (https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-r2-and-2008/dd560674(v=ws.10))
- Command-Line Reference (https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-r2-and-2008/cc754340(v=ws.10))
- **A-Z List** (https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-r2-and-2008/cc772390(v=ws.10))
- **DiskPart Commands** (https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-r2-and-2008/cc770877(v=ws.10))
- **DiskPart Commands Format** (https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-r2-and-2008/cc753770(v=ws.10))

Please note that in future versions of DiskPart, only the "/script" option will be shown in the help text.

**Comment by PRMerger16** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: ingridatmicrosoft 
gh issue comment 5391 -b ingridatmicrosoft

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @pamf 

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change was made to redirect users to the "[Diskpart Commands format parameter](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc753770(v=ws.11))" page and will be live after the next business day. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
