### ISSUE TITLE
Web Client on 2016 Essentials feature?

### ISSUE THREAD

**Issue by Wimmel24** [MicrosoftDocs/windowsserverdocs#540]
Is it possible to configure the Web Client on a 2016 essentials server? At this moment when I try to run Import-RDWebClientBrokerCert I get the message:
RD Web Access does not appear to be installed on the system.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Service: **unspecified**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by lizap** [comment]
Are you trying to install the **support** for the Web Client on your Essentials box? That needs to be installed on the Connection Broker - and you must have already installed the RD Web Access role. Is your Essentials box also your CB?
