### ISSUE TITLE
galkan cowbar

### ISSUE THREAD

**Issue by jolyjoly** [MicrosoftDocs/windowsserverdocs#5404]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3bb627d-9eb9-6335-57d2-f26ca1fb89be
* Version Independent ID: 460b5aa1-7984-ed94-d79b-09846580cbeb
* Content: [begin backup](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/begin-backup)
* Content Source: [WindowsServerDocs/administration/windows-commands/begin-backup.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/begin-backup.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
No valid issue content. This looks more like a test posting.

#please-close
