### ISSUE TITLE
Resolving credentials issues.

### ISSUE THREAD

**Issue by whitekn3** [MicrosoftDocs/windowsserverdocs#541]
If you attempted to use a user that is not an Enterprise or Schema admin, then add the memberships to the needed groups AFTER the wizard has started and/or reported the error in the prerequisites checks it will not refresh the credentials.  After trying many things, I ended up entering an invalid name, reran the prerequisites check, got a different error, then used <Previous to go back and enter the original user.  Then I could proceed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fdfba58-60f3-7d3f-7a2c-07caad3a254c
* Version Independent ID: 1c299ca2-4455-3ae0-6a01-c2c29e1d1abe
* Content: [Install a Replica Windows Server 2012 Domain Controller in an Existing Domain (Level 200)](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/install-a-replica-windows-server-2012-domain-controller-in-an-existing-domain--level-200-)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/Install-a-Replica-Windows-Server-2012-Domain-Controller-in-an-Existing-Domain--Level-200-.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/Install-a-Replica-Windows-Server-2012-Domain-Controller-in-an-Existing-Domain--Level-200-.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by MicrosoftGuyJFlo** [comment]
Sounds like you were able to figure out the issue with group membership. #please-close
