### ISSUE TITLE
Calculation Error in Azure Hybrid (Use) Benefit Calculator

### ISSUE THREAD

**Issue by ChJohnso3075** [MicrosoftDocs/windowsserverdocs#5415]
There appears to be a small error in the Windows Server SA requirement based on the Azure Hybrid Use (AHB) calculator:

A D15v2 (20 Cores) is flagged as requiring 20 Cores of Windows Server with active Software Assurance for the purposes of using AHB. However, per the Microsoft Product Terms, Windows Server Core licenses for the purposes of adding AHB savings must be assigned in groups of 8:

"Each two-processor license or each set of of 16-Core licenses, either Datacenter or Standard editions, are entitled to two instances of up to 8 cores, or one instance of up to 16 Cores"

This is further validated through “Get Licensing Ready”:

"A minimum of 8 Core licenses must be assigned to an Azure Virtual Machine, and further groups of 8 Core licenses may be assigned to larger virtual machines"

Because of this, it is not possible to assign only 20 Cores with ASA to this particular VM. The correct number of Cores required for AHB would be 24. As this VM series is the only model that isn’t deployed in a multiple of 8 (e.g. 8, 16, 24 etc.) this is the only SKU impacted.

**Comment by dknappettmsft** [comment]
Thanks for the feedback. It is possible to do assign 20 cores to a 20-core VM - an Azure VM requires a minimum of 8-cores, regardless of the size, and then you can stack 2-core packs on top up to the value needed.  They do not have to be allocated in blocks of 8-cores, only 8-cores as a minimum initially. I appreciate this can be a bit of a minefield, so I hope that clears it up. I have reworded the section to hopefully make this clearer. I appreciate it is a bit of a minefield.  The changes should be visible later today.

#please-close

**Comment by ChJohnso3075** [comment]
Hello!

Thank you for your feedback. Based on this, can you please provide documentation where it is noted that you can assign 2-Core packs of Windows Server licenses for the purposes of AHB?

While Windows Server on prem licensing allows you to assign 2-Core pack licenses, there is still a minimum requirement of 8 Cores per Proc and a minimum requirement of 2 procs. Once that threshold is reached, you can continue to assign licenses in increments of 2-Core Packs until the minimum requirement is met. The one caveat is when you’re stacking Standard licenses for the purposes of licensing additional VMs in which case the minimum requirement needs to be met for every 2 VMs on a single Hypervisor.

Specific to AHB, please note the following:

Microsoft Windows Server | Microsoft Licensing Resources<https://www.microsoft.com/en-us/licensing/product-licensing/windows-server>

***@***.***

https://www.microsoft.com/licensing/terms/en-US/productoffering/MicrosoftAzure/EAEAS

[Text  Description automatically generated]

In both sections, a minimum of 8 is called out. Specific to the former, “Customers can add virtual cores (up to 8) to an existing or new virtual machine with incremental sets of eight licenses. Each incremental set of eight licenses must be allocated to a single virtual machine”. Per your response, adding 4 licenses to hit the threshold of 20 vCPUs for AHB would contradict the above because you need to assign them in sets of 8 and each set can only be applied to a single VM. You cannot “split” 8 to cover 4 and 4 on two VMs. Oddly enough, only 20 vCPU profiles fall under this specific situation.

If you’re able to provide documentation where it’s noted that the above statements are incorrect, I’d greatly appreciate it.

Thanks!
Chris Johnson
C 425.359.1751 | 425.702.8175 x1105
***@***.******@***.***>
***@***.***<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.invisocorp.com%2F&data=02%7C01%7Crbrown1%40Trueblue.com%7Cd3212ddcbef84a38109108d57d6d461e%7Cc2c09bd09a1a4ab184471a37d3917683%7C0%7C0%7C636552830676584545&sdata=KTjJEEXyc2LTm4SPnVgfYGZzm4lr2NOMvic%2Bxuty%2Bl8%3D&reserved=0>     ***@***.*** <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Finviso&data=02%7C01%7Crbrown1%40Trueblue.com%7Cd3212ddcbef84a38109108d57d6d461e%7Cc2c09bd09a1a4ab184471a37d3917683%7C0%7C0%7C636552830676584545&sdata=BEKohKANYfZgttCUf3CzgPZ2YAmlDq%2Br3HkVaOdDJ%2BU%3D&reserved=0>   ***@***.*** <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2Fpages%2FInviso-Corp%2F55078292953&data=02%7C01%7Crbrown1%40Trueblue.com%7Cd3212ddcbef84a38109108d57d6d461e%7Cc2c09bd09a1a4ab184471a37d3917683%7C0%7C0%7C636552830676584545&sdata=v8FadrV6semSdiRLe9kKMRNo8RH9rOgERXFaoGu29LA%3D&reserved=0>
***@***.***

**Comment by PRMerger5** [comment]
Only Microsoft employees can close issues or pull requests via commenting in this repo.
