### ISSUE TITLE
Oops, we couldn't connect

### ISSUE THREAD

**Issue by ErwinVreys** [MicrosoftDocs/windowsserverdocs#542]
The publishing went fine but when I click on any published application I always end up with the message "The connection to the remote PC was lost". I can't seem to find the reason nor can I find any error. Opening the published application the old way works fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Service: **unspecified**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by reluctantflux** [comment]
Same issue.  Make sure that you're using the FQDN for the RD Gateway in the Deployment Properties.  I was just testing internally before putting it into the DMZ, and changing my dns entry for that to point to my correct server resolved the issue.

**Comment by fate0521** [comment]
I got the same title message except it the body for me says "Your session ended because of an error."  I am also to open it fine through regular RDWeb, we are not using a Gateway in our deployment.

**Comment by githubths** [comment]
Same problem. Based on a fiddler trace we see a GET request to the server URL that comes back with HTTP 500. The server URLs are https://%TSG ServerName%/remoteDesktopGateway?...
But this URL "/remoteDesktopGateway" is not documented?

**Comment by dchild198** [comment]
Same error. I was looking through the Event Viewer but did not see an indication of an error. Any help would be appreciated. We are interested in testing this preview.

**Comment by stanthewizzard** [comment]
Same for me

**Comment by davidbel** [comment]
@fate0521 @githubths @dchild198 @stanthewizzard  Hi folks, as a general statement, during the public preview, if you encounter technical difficulties, it's recommended to send mail to the Support email address found in the about page so we can further investigate. Whenever possible, also include some of the debug information from the browser debug console.
You do need a gateway in your environment. The web client will not work without this.

**Comment by lizap** [comment]
HI, all - to David's point above, we include the RD Gateway config item as one of the things to check for connection issues here, in the troubleshooting section: https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin#what-to-do-if-the-user-cant-connect-to-a-resource-with-the-web-client-even-though-they-can-see-the-items-under-all-resources

Because of that, I'm going to close this issue for now. Please continue to report technical difficulties, but through the channel David describes (using the Support email address on the About page). Thanks!

**Comment by leonmeijer** [comment]
Fixed this by disabling HTTP/2 in IIS under the bindings. Also make sure the Gateway service is running (under Windows services). Found Firefox more verbose around websocket errors (in console and network tabs) than Chrome and Edge.
