### ISSUE TITLE
No WIF SDK available

### ISSUE THREAD

**Issue by himanshur17** [MicrosoftDocs/windowsserverdocs#5420]
[Enter feedback here]
The link of WIF SDK given in this article for sample claim aware application is not working. It seems WIF 3.5 is obsolete and removed from the download link. Can we have another sample claim aware application instead?
https://www.microsoft.com/en-ca/download/details.aspx?id=4451 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f333201e-8d13-c621-6eac-f3ca7b2dcdc0
* Version Independent ID: 07d1fd0e-6988-a6d5-c586-7de810bc0906
* Content: [Set up the lab environment for AD FS in Windows Server 2012 R2](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/set-up-the-lab-environment-for-ad-fs-in-windows-server-2012-r2#BKMK_5)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Set-up-the-lab-environment-for-AD-FS-in-Windows-Server-2012-R2.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Set-up-the-lab-environment-for-AD-FS-in-Windows-Server-2012-R2.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
#label:"doc-bug"
