### ISSUE TITLE
Wrong version

### ISSUE THREAD

**Issue by RonGlo** [MicrosoftDocs/windowsserverdocs#5431]
Hi,

There is a mistake of the version of Windows 10 client in the Microsoft Store.
It's written 1.2.1810 instead of 10.2.1810.

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f7187f-7e2e-da7f-6f46-46568be43db7
* Version Independent ID: 49714e7e-ecfb-dba3-f43a-17b6ca677fa6
* Content: [Remote Desktop clients](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-clients)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @RonGlo,

Thanks again for contacting Microsoft. We value your feedback. 

This issue may or may not have been corrected with the latest update to `10.2.3000.0`. The authors on GH also do not have the ability to correct any issue's or verbiage within the application itself. 

If something like this does arise with any future developing apps, we recommend you use the Feedback hub to report these issues. If you're using Windows as your main OS, click **Start** > type '**Feedback Hub**' > and provide the data.

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
