### ISSUE TITLE
Maximum size switch requires documentation update.

### ISSUE THREAD

**Issue by vLGrok** [MicrosoftDocs/windowsserverdocs#5434]
Documentation for /l switch requires update.
On Windows Server 2019, attempting /l 65527, reply indicates:
Bad value for option /l, valid range is from 0 to 65500.

Best Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecb04dc8-7ab3-71e9-9773-41c080b40109
* Version Independent ID: 435a4517-0c3f-6af6-d75d-faed7282c86a
* Content: [ping](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/ping)
* Content Source: [WindowsServerDocs/administration/windows-commands/ping.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/ping.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by dksimpson** [comment]
Hi @vLGrok,
Thanks for contacting Microsoft. We value your feedback.
We've updated the ping /l max value in the article to reflect the correct value.
Thank you for your continued support.
#please-close
