### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by rvahaver** [MicrosoftDocs/windowsserverdocs#5435]
Most of the links to the video training are not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd448b3c-456e-bd11-efb5-278296801fc0
* Version Independent ID: f82f9906-69aa-fc5b-e479-84b42b6c716f
* Content: [Windows Admin Center Overview](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/overview)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/overview.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by DarwinChanaba** [comment]
I visited the site and tried video-based learning 
https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/overview#video-based-learning

Links are not working:
Windows Admin Center: Unlock Azure Hybrid value
Windows Admin Center: What’s new and what’s next
Automatically monitor, secure and update your on-premises servers from Azure with Windows Admin Center
Get more done with Windows Admin Center third-party extensions
Be a Windows Admin Center expert: Best practices for deployment, configuration, and security
Windows Admin Center: Better together with System Center and Microsoft Azure
How to use Microsoft Azure hybrid services together with Windows Admin Center and Windows Server
Live Q&A: Manage your hybrid server environment with Windows Admin Center

Any update to this issue?

**Comment by IngridAtMicrosoft** [comment]
@DarwinChanaba Thank you for bringing this to our attention.

**Comment by IngridAtMicrosoft** [comment]
@rvahaver It appears that the videos are no longer available.  We will be removing the links.

**Comment by IngridAtMicrosoft** [comment]
#please-close
