### ISSUE TITLE
RD Web Access - access to published remote app on Azure virtual machine from external client PC

### ISSUE THREAD

**Issue by MisbahMHasan** [MicrosoftDocs/windowsserverdocs#5440]
I followed the steps mentioned in the documentation. Deployed the environment with self-signed certificate to test RD Web Access. I can see the published apps icons, but I get error "**The connection to the remote PC was lost. This might be because of a network connection problem.**", 
<img width="449" alt="Cannot connect to remote app" src="https://user-images.githubusercontent.com/82229723/114212843-3168f300-995a-11eb-940c-08f9c2701704.png">
when I click on an app icon to access it. The client computer is on external network and trying to access a published app on Azure virtual machine. Not sure, if this would work with self-signed certificate. Any advise would be greatly appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4767a747-aab2-11eb-28fc-02652c3479ec
* Version Independent ID: c3245db3-8839-7b41-32a2-b4cf14bc5848
* Content: [Deploy your Remote Desktop environment](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-deploy-infrastructure)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-deploy-infrastructure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-deploy-infrastructure.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
Hi @MisbahMHasan. GitHub issues for this repo are for reporting problems with our documentation.  Please open a support ticket or post your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html).
