### ISSUE TITLE
broken example code

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/windowsserverdocs#5448]
The powershell snippets are surrounded in backtick characters.  This makes them not work.  The first and last backtick characters should be removed from these examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a09965e-bb25-dbd2-18b7-4550b1bedefd
* Version Independent ID: dc776e65-60eb-c04b-8994-7b7df8ab2af2
* Content: [Walkthrough Guide - Manage Risk with Conditional Access Control](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/walkthrough-guide--manage-risk-with-conditional-access-control)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Walkthrough-Guide--Manage-Risk-with-Conditional-Access-Control.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Walkthrough-Guide--Manage-Risk-with-Conditional-Access-Control.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Thank you for noticing and reporting this issue. It looks to me as if there has been a conversion mishap, forgetting to remove the back ticks at the start and end of the lines when adding MarkDown code fence boxes around the examples. Feel free to create a PR for the necessary change, or I can do it if you decide not to.

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 5445 -b #assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @jordanmills,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change was made a while back correcting this and this issue wasn't closed. Changes are live. We will now be closing this thread. Thank you and have a most pleasant day. #please-close
