### ISSUE TITLE
SSH to windows using key does not allow to connect with domain controller.

### ISSUE THREAD

**Issue by nippyin** [MicrosoftDocs/windowsserverdocs#5451]
[Enter feedback here]

When I ssh to windows server using key and then try to run get-aduser -identity username. I get following message.
Get-ADUser : Unable to contact the server. This may be because this server does not exist, it is currently down, or it does not have the Active Directory Web Services running.
At line:1 char:1
+ Get-ADUser username
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (ssharma:ADUser) [Get-ADUser], ADServerDownException
    + FullyQualifiedErrorId : ActiveDirectoryServer:0,Microsoft.ActiveDirectory.Management.Commands.GetADUser

However, if I ssh to same VM using Username & Password I am able to get ad user details. can you fix it or help me sort this out if this is ssh_config issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8ad5c9a-efb1-d994-0e3c-53c90096a245
* Version Independent ID: 5cb0ea97-4c3d-ffdf-b69c-8a717f9f9f3f
* Content: [OpenSSH Server Configuration for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_server_configuration)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Server_Configuration.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Server_Configuration.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by illfated** [comment]
@konstruktoid : Is this something you would be able to answer, or maybe point to a suitable support site, like a forum page for this type of issue?

**Comment by konstruktoid** [comment]
What I've noticed is that the AD requires a password, this seems to be bypassed when using only a key file (since that is a local check on the server).
One solution is to use both a password and key file authentication.

**Comment by nippyin** [comment]
That is true, is there a way instead of passing a credential file with clear ad password we pass in hash or something. The goal is to make this auth process more secure while keeping no user interactive.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by konstruktoid** [comment]
I'm not aware of any solution that would achieve that, but I haven't really looked either to be honest.

**Comment by nippyin** [comment]
Oh, is this something you can take a look at when you get a moment.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by konstruktoid** [comment]
I'm not going to spend much time looking into that, no.
A quick search turned up https://blog.ndk.name/linux-ssh-authentication-against-active-directory-without-joining-the-domain/ but I haven't tested it in any way, but OpenSSH certificates are probably the way to go.

**Comment by jborean93** [comment]
This issue is related to the double hop/credential delegation problem. When you authenticate with SSH public keys the logon session that is created doesn't have your credentials to re-authenticate with any downstream servers, domain controllers, file shares, etc. When you authenticate with password auth the username and password are sent to the host so it's able to create a logon session with your credentials for further authentication. A similar thing exists with WinRM where you need to set up Kerberos delegation or use CredSSP (analogue to password auth here) to deal with stuff like that.

**Comment by nippyin** [comment]
Absolutely, do we have anything in ssh to delegate or to fix it ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jborean93** [comment]
The closest thing you can do is GSSAPI/Kerberos delegation I've talked about in https://github.com/MicrosoftDocs/windowsserverdocs/issues/4669. I think the version of OpenSSH on newer Windows builds have finally been updated to support this, if not then the GitHub release (not builtin) will work.

Essentially you use your current user's logon session to authenticate with the remote server but also grant the ability for that remote session to use that same token. It may require some settings to be enabled in the service principal (remote host) in AD to allow delegation whether it be unconstrained (allow all) or constrained (allow specific).

**Comment by robinharwood** [comment]
Hi @nippyin 

Thank you for your dedication to our documentation. I can confirm this is the expected bevahiour, which is documented in our (Win32-OpenSSH Wiki)[https://github.com/PowerShell/Win32-OpenSSH/wiki/SSH-remote-sessions-on-Windows]. I appreciate how frustrating it can be to have documentation fragmented like this. So, based on your feedback I have updated the (OpenSSH key management)[https://docs.microsoft.com/windows-server/administration/openssh/openssh_keymanagement] article on our Microsoft Docs site to include this point. 

I also realise this doesn't solve your issue with running remote commands such as `Get-ADUser`, which rely on your associated user credentials. I was able to successful recreate your issue and find an alternative method. Commands like `Get-ADUser` allow you to user the **Credential** parameter to specify credentials. You can't just run `Get-Credential` however, as using a remote PowerShell session via OpenSSH doesn't allow for the interactive prompt. You can however run `Get-Credential` without prompting the user by following (Example 4 in the Get-Credential reference)[https://docs.microsoft.com/powershell/module/microsoft.powershell.security/get-credential#example-4].

The worked example would look like the below PowerShell example.

```powershell
$User = "Domain01\User01"
$PWord = ConvertTo-SecureString -String "P@sSwOrd" -AsPlainText -Force
$Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $User, $PWord

Get-ADUSer <username> -Credential $Credential 

```

Thanks for your feedback once again,

Robin

#please-close
