### ISSUE TITLE
Missing restart requirement for SMBv1 removal

### ISSUE THREAD

**Issue by msangster** [MicrosoftDocs/windowsserverdocs#5452]
The section "SMB v1 (client and server)" doesn't indicate the restart requirement (whereas other sections do).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a91db45-ca3c-7a2e-3f32-2f5b57837b03
* Version Independent ID: b83cbaab-c0df-d6e7-a67f-f4c99a46e30a
* Content: [How to detect, enable and disable SMBv1, SMBv2, and SMBv3 in Windows](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by Deland-Han** [comment]
@IngridAtMicrosoft I tested and confirmed that computer will restart after running the PowerShell commands to enable/disable SMBv1. I have submitted a [PR2395](https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/2395) to fix it.
