### ISSUE TITLE
Small Typo

### ISSUE THREAD

**Issue by Bryan-Streber** [MicrosoftDocs/windowsserverdocs#5455]
[Enter feedback here]

"If you use an email address, enter your email address. Entering your email address tells the client ot search for a URL associated with your email address if your admin configured the server that way."

Should be  to not ot 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d21e96b-c8a6-7f9f-76e1-62ee4fbde62b
* Version Independent ID: 5530201e-2ff5-19de-5990-1a996cf5ef2e
* Content: [Get started with the iOS client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-ios)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-ios.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-ios.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by illfated** [comment]
Thank you for noticing and reporting the typo. I will open a Pull Request to have that typo corrected (unless you want to do so yourself, of course).

**Comment by illfated** [comment]
( ref. #5457 )
