### ISSUE TITLE
Commands and Output missing the tilde "~" symbols

### ISSUE THREAD

**Issue by walchst** [MicrosoftDocs/windowsserverdocs#5458]
Minor issue but the PowerShell commands/output are missing the tilde symbols:

<img width="599" alt="Screengrab_2021-Apr-17_09-44-46" src="https://user-images.githubusercontent.com/10477121/115094627-95df1000-9f61-11eb-8e6c-2485d81c6a44.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Install OpenSSH](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by illfated** [comment]
Please note: Those tilde characters used to be present in the document article, but were removed on April 8, 2021 (9 days ago as of this comment) in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/1edf6dd35ae418216f5200dbd9deb0726f466ed6 by @v-dasis .

From a practical point of view, it is slightly unfortunate that the change was added without a public PR explaining the reasoning for this change.

Nevertheless, the change has been made by one of the MS Docs team members and therefore seems to be validated.

**Comment by walchst** [comment]
I can't say for certain but my guess is they thought the tildes were formatting anomalies and removed them however they are required or else the commands will fail and need to be reinstated.

**Comment by illfated** [comment]
> I can't say for certain but my guess is they thought the tildes were formatting anomalies and removed them however they are required or else the commands will fail and need to be reinstated.

Fair point, I was a little bit uncertain about why the tilde characters were removed. Do you want to make a PR to recommend adding them back, or do you prefer that I do so?

**Comment by v-dasis** [comment]
Tildes have been added back - changes go live later this morning. My apologies...

**Comment by illfated** [comment]
> Tildes have been added back - changes go live later this morning. My apologies...

Thank you for confirming the change. Good to know. 👍🏻

**Comment by robinharwood** [comment]
@walchst - Thanks for your dedication to our documentation. We sincerely apologize for the delayed response. The requested updates have already been made. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
