### ISSUE TITLE
Typo: DFSRMIG not DSFRMIG

### ISSUE THREAD

**Issue by WhetDawg** [MicrosoftDocs/windowsserverdocs#5459]
Typo:
The output of dsfrmig /getmigrationstate...
s/b
The output of dfsrmig /getmigrationstate...

DFS not DSF
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b39d577-4c79-3dbd-bf5e-4b1bf551f73e
* Version Independent ID: 4bead400-5af7-bd08-5bfe-8297cbc8dd85
* Content: [dfsrmig](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/dfsrmig)
* Content Source: [WindowsServerDocs/administration/windows-commands/dfsrmig.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/dfsrmig.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Thanks, good catch. I will create a PR to have that typo corrected.

**Comment by illfated** [comment]
( ref. #5460 )

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 5454 -b #assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @WhetDawg, 

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting this typo and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
