### ISSUE TITLE
Issues in openSUSE Leap 42.3

### ISSUE THREAD

**Issue by bmo6** [MicrosoftDocs/windowsserverdocs#546]
When a user connected through Chrome in openSUSE Leap 42.3 to a DDA Nvidia M10 powered RDSH, he experienced a pink graphical distortion covering the entire RDP session.

The issue didn’t repeat itself in Firefox, however he reported that the cursor movement was slow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Service: **unspecified**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by davidbel** [comment]
Hi bmo6, if you are still seeing this issue, please send mail to the Support Email found on the about page so we can investigate. Thank you.
