### ISSUE TITLE
Product version mismatch

### ISSUE THREAD

**Issue by humanascode** [MicrosoftDocs/windowsserverdocs#5461]
The "Applies to" section mentions Windows Server 2016 and Windows Server SAC.

Just bellow it Says:

"This topic for the IT professional describes NTLM, any changes in functionality, and provides links to technical resources to Windows Authentication and NTLM for **Windows Server 2012 and previous versions**."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a7ee325-0910-830e-3992-79d7ddf317e6
* Version Independent ID: 6d8d74ea-201c-4827-3898-a22024fbe640
* Content: [NTLM Overview](https://docs.microsoft.com/en-us/windows-server/security/kerberos/ntlm-overview)
* Content Source: [WindowsServerDocs/security/kerberos/ntlm-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/kerberos/ntlm-overview.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Well, those lines mean separate things.

***

This paragraph refers to the currently supported Windows Server versions:
> Applies To: Windows Server (Semi-Annual Channel), Windows Server 2016

***

The next paragraph tells us that content in this document talks about, and may lead you to, documentation concerning previous versions of Windows Server, like 2012 or older:

"This topic for the IT professional describes NTLM, any changes in functionality, and provides links to technical resources to Windows Authentication and NTLM for Windows Server 2012 and previous versions."

***

**Comment by dksimpson** [comment]
Hi @humanascode,

Thanks for contacting Microsoft; we value your feedback. This issue has been addressed.
If you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.

#please-close
