### ISSUE TITLE
Typo on command Get-SyncProperties

### ISSUE THREAD

**Issue by imartinez2** [MicrosoftDocs/windowsserverdocs#547]
The command to validate the rol of the server had a typo, must be Get-AdfsSyncProperties

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a58b49ca-ae39-132e-adbd-6766a8019a89
* Version Independent ID: fdf31266-bc9e-8880-0073-00cf1cad2897
* Content: [AD FS Rapid Restore Tool](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/ad-fs-rapid-restore-tool)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/AD-FS-Rapid-Restore-Tool.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/AD-FS-Rapid-Restore-Tool.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by MicrosoftGuyJFlo** [comment]
Looks like this has been resolved #please-close
