### ISSUE TITLE
instructions need work

### ISSUE THREAD

**Issue by ericreiss** [MicrosoftDocs/windowsserverdocs#5471]
In step 9 it says select one of, then in step 15 it says select the other.  This is a poor explanation.

Either say select the first, then later say select the second or when you say select one of, later say select the other that was not previously selected.

But the language should be improved.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49d6fd82-29a9-ed74-00be-1576e5266bb8
* Version Independent ID: 33578f4a-5fcc-bf56-92a8-c51e4f259328
* Content: [Create a new NIC Team on a host computer or VM](https://docs.microsoft.com/en-us/windows-server/networking/technologies/nic-teaming/create-a-new-nic-team-on-a-host-computer-or-vm)
* Content Source: [WindowsServerDocs/networking/technologies/nic-teaming/Create-a-New-NIC-Team-on-a-Host-Computer-or-VM.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/nic-teaming/Create-a-New-NIC-Team-on-a-Host-Computer-or-VM.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Linked issue: #5472 (see https://github.com/MicrosoftDocs/windowsserverdocs/issues?utf8=%E2%9C%93&q=%2233578f4a-5fcc-bf56-92a8-c51e4f259328%22&in=body for reference)

**Comment by dknappettmsft** [comment]
Linked to resolution in #5472.

#please-close
