### ISSUE TITLE
Mention the limitation that you can't convert evaluation datacenter to retail standard edition without reinstalling

### ISSUE THREAD

**Issue by ElizabethGreene** [MicrosoftDocs/windowsserverdocs#5474]
It might be worthwhile to mention here that you can't convert datacenter editions to standard editions without reinstalling.  That limitation is documented elsewhere, but it came up as a question for a customer that wanted to flip their Server 2019 Datacenter Eval to Server 2019 Standard Retail. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1b19ef8-a273-c1c8-18ff-7d29664bb9d2
* Version Independent ID: 8cf37a43-cff4-78de-0d66-2f482c022dc7
* Content: [Upgrade and Conversion Options for Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/get-started/supported-upgrade-paths)
* Content Source: [WindowsServerDocs/get-started/Supported-Upgrade-Paths.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/Supported-Upgrade-Paths.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
Author metadata is out of date. @JasonGerend

**Comment by ElizabethGreene** [comment]
There has been some additional discussion on this in the internal Server 2019 DL.  It appears that all 2019 Eval to Retail conversions require a reinstall and that will also be the case for the next version of windows server as well. (per the Sr. PM)  The new ask is to update the documentation to indicate that all  2019+ server eval conversions will require an in place upgrade.

**Comment by jaimeo** [comment]
@JasonGerend

**Comment by illfated** [comment]
It has been quite a while since I have seen anything posted by @JasonGerend, I wonder if he is too occupied elsewhere, e.g. with the undocumented conversion to Azure.

**Comment by ElizabethGreene** [comment]
I'm looking for an opportunity to create some impact; if you'd like I can submit a pull request to handle this.  It'll be my first time though; do I need to do anything special for i18n?

**Comment by illfated** [comment]
Everyone is welcome to contribute, be it via issue tickets or pull requests. Unless you want to use your own local flavor of Git tools on your own computer, you should be good to go with the web based tools to edit the page in question and open a new pull request with your suggested changes.

Feel free to ask for help too, we are here to help if we can.

**Comment by robinharwood** [comment]
Hi @ElizabethGreene,

Thanks for the feedback and your dedication to our documentation. I have reviewed you comment and believe this has already been address by the article updates on the 25th November 2021. The last bullet in the [Upgrading licensed versions of Windows Server section](https://docs.microsoft.com/en-us/windows-server/get-started/upgrade-conversion-options#upgrading-licensed-versions-of-windows-server) now reflects your comment.

With regard to creating some impact, this is great to hear. We have a [Microsoft Docs contributor guide](https://docs.microsoft.com/contribute/) that you can review.

To follow up on this issue, leave us a comment with an @mention.

Thanks,

Robin

#please-close
