### ISSUE TITLE
Typo on page

### ISSUE THREAD

**Issue by saurabh500** [MicrosoftDocs/windowsserverdocs#5475]
[Enter feedback here]
Typo in `Support` for the heading

`Suppport for building modern line-of-business`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bd4457e-c29d-d174-f88f-6eedfc7e7db6
* Version Independent ID: bb86780a-ac42-97bc-9d38-acb019437f76
* Content: [What's new in Active Directory Federation Services for Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Nice, well spotted. I can create a Pull Request to have that typo corrected (unless you want to do it yourself, of course).

**Comment by dknappettmsft** [comment]
This has been corrected and should be visible in a few hours.

#please-close
