### ISSUE TITLE
Detect of SMBv1 Command must be ran with Admin privs.  Alternate command doesn't need admin privs.

### ISSUE THREAD

**Issue by toddalbers** [MicrosoftDocs/windowsserverdocs#5477]
The PS command given under "**_Powershell methods SMB v1 (client and server)- Detect:_**" does not work in PS on Win 10 box unless you run elevated.  The command listed is:  
Get-WindowsOptionalFeature -Online -FeatureName smb1protocol   
This gives error message if you are not running PS as an admin.

What does seem to work with and without admin privs is the following PS command:  Get-SmbServerConfiguration | Format-List EnableSMB1Protocol

This is for "Detect" only at this time.  The page should probably be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a91db45-ca3c-7a2e-3f32-2f5b57837b03
* Version Independent ID: b83cbaab-c0df-d6e7-a67f-f4c99a46e30a
* Content: [How to detect, enable and disable SMBv1, SMBv2, and SMBv3 in Windows](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by illfated** [comment]
(https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3#how-to-remove-smb-v1)
(https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3#powershell-methods)
(https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3#smb-v1-client-and-server)

**Comment by illfated** [comment]
Maybe it should be added as an extra note at the top, reminding users to _**always**_ run PowerShell as local administrator on Windows 10. (Then again, I thought most administrators knew this already.)

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @toddalbers, 

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made to include your PS cmdlet contribution, among other tweaks, and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
