### ISSUE TITLE
Computers not Reporting Status but Have Last Contact

### ISSUE THREAD

**Issue by mwisniewski9** [MicrosoftDocs/windowsserverdocs#548]
We have many computers in our environment that do not show the last status report but have last contact times in the WSUS console. Is there a recommended process to troubleshoot this issue. I'm looking for steps to follow such as stopping/starting the wuaserv service, deleting the software distribution folder on the client side especially for WIndows 10 Build 1709. 
![imgpsh_mobile_save](https://user-images.githubusercontent.com/6878905/38148057-ab3e4568-3409-11e8-9397-e9f34d33f7e8.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ac4f254-d166-06ce-ea0d-7d954f6469fa
* Version Independent ID: ecd627b0-1984-e75b-561f-3a33d2effba7
* Content: [WSUS Messages and Troubleshooting Tips](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/manage/wsus-messages-and-troubleshooting-tips)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/manage/wsus-messages-and-troubleshooting-tips.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/manage/wsus-messages-and-troubleshooting-tips.md)
* Service: **unspecified**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by rm304** [comment]
STEPS to take on Client PC having issues:
1) Stop Windows Update service
2) Delete everything in "C:\Windows\SoftwareDistribution" ,  *** not the SoftwareDistribution folder itself ***
3) Start Windows Update service
4) Open command prompt and run command at a time
- wuauclt.exe /resetauthorization
- wuauclt.exe /r /detectnow
- wuauclt.exe /reportnow

Give it about 2 minutes and then refresh the WSUS console window to see if it connects. This is the usual method to get Clients connected. However, I have one Windows 10 PC that is connecting but not reporting same as you.  I have done this steps numerous times and just not reporting.  I can verify it is querying the server for updates, as the event logs showing grabbed updates and applied this morning.  I have deleted form the console and run the commands again only to have it show up and state it has not reported yet.

**Comment by goldaurora** [comment]
Thank you rm304. Your steps worked perfectly for me. Win 10 PC and Windows Server 2016 WSUS.

**Comment by stevenahmet** [comment]
The wuauclt commands have been deprecated on Windows 10 and have no effect.
Normally you would try using "usoclient startscan"

**Comment by ngoccac96** [comment]
Many thanks, it worked for my client 94 days no report
