### ISSUE TITLE
icacls: Explain what "(I)" means in the output

### ISSUE THREAD

**Issue by smcpeak** [MicrosoftDocs/windowsserverdocs#5481]
The [documentation for icacls](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/icacls) explains the meaning of inheritance rights like "(OI)", but does not explain what the single letter "(I)" means in the output.  Please add that.

According the [this SU answer](https://superuser.com/a/322431) it means the permissions that appear afterward were inherited from the parent container.

And on this topic, while rights like "(OI)" have short descriptions (like "Object inherit"), that same answer gives better explanations of their meaning (e.g., "This ACE will be inherited by objects placed in this container.") that could be incorporated to further improve the article.

Finally, the acronym "ACE" appears around 10 times on the page, but its definition is buried under /verify ("ACE (access control entry)").  The definition should be in a more prominent location so readers do not have to resort to browser text search to find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5906879b-e678-e3da-c404-07a437b42cc2
* Version Independent ID: 0779c597-9e20-38e0-3ae7-40126f5c2bcb
* Content: [icacls](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/icacls)
* Content Source: [WindowsServerDocs/administration/windows-commands/icacls.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/icacls.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @smcpeak,

Thanks again for contacting Microsoft. We value your feedback. 

Mentioned concerns within this documentation were corrected a while ago and this issue was not closed. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
