### ISSUE TITLE
The wording of the below statement is confusing

### ISSUE THREAD

**Issue by Sephanyah** [MicrosoftDocs/windowsserverdocs#5485]
[Hi Team, the wording of this statements ("_We don't support extensions to Windows Admin Center in the Azure portal at this time. If you manually installed Windows Admin Center in the VM to manage multiple systems, installing this VM extension reduces the functionality to managing just the VM in which the extension is installed. Uninstall the extension to get back full functionality._") makes it hard for the reader to fully understand what is being said.

Is there a better way in which this can be worded?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0af46722-5b7c-eb50-f6fe-ba7ce4552f85
* Version Independent ID: b2710445-053e-14fd-1cf9-813cdc628d06
* Content: [Use Windows Admin Center in the Azure portal to manage a Windows Server VM](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/azure/manage-vm)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/azure/manage-vm.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/azure/manage-vm.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Fair question, interesting problem as well, at least from a logical and linguistical viewpoint. I will start making some notes here, in case I can come up with some valid phrasing to simplify the text, while still keeping the intended meaning. (https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/azure/manage-vm#overview-of-functionality)

***

> Extensions to Windows Admin Center are currently not supported in the Azure portal.
>
> If you installed Windows Admin Center on the virtual machine to manage multiple systems, the functionality of this VM extension will be reduced to managing single VMs only where the extension is installed. Remove the extension to restore your intended functionality.

***

(Yes, I know, it does not look like it changed much. I translated it to my own language, Norwegian, to see how much I could boil the text down, then translated it back again to English, but it did not make a lot of difference.)

**Comment by Sephanyah** [comment]
Hello,

I greatly appreciate you taking the time to understand my feedback and the work you are putting out to make these documents even better (I give you great credit for being a non native English speaker and working on documentation as these).

The changes you’ve made so far are a lot clearer and I do look forward to what more can be done to have the documents be as precise as they can be.


Best Regards,
Sephanyah Peters

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dknappettmsft** [comment]
Thanks for the feedback.  I have changed the text to read: "If you manually installed Windows Admin Center in the VM to manage multiple systems, installing this VM extension reduces the functionality to managing just this VM only. Uninstall the extension to get back full functionality."

The change should be visible in a few hours.  If there is any further clarification required, please let me know.

#please-close
