### ISSUE TITLE
Enterprise PRT deprecated by New Edge

### ISSUE THREAD

**Issue by dbona75** [MicrosoftDocs/windowsserverdocs#5486]
[Enter feedback here]

Hello Guys, 

I think this document should be updated. Indeed today is no more possible to use device conditional access policies, device compliance policies, etc with ADFS  onprem federated applications because the new Edge browser doesn't support the enterprise prt token.

This document remains  true only for Internet Explorer.

Thanks

dabona@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4ead20d-8590-f267-506b-59f3fce14bbb
* Version Independent ID: 20871f1c-eed9-0117-f479-c4e77a022c99
* Content: [Plan Device-based Conditional Access on-Premises](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/plan-device-based-conditional-access-on-premises)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Plan-Device-based-Conditional-Access-on-Premises.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Plan-Device-based-Conditional-Access-on-Premises.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Identical ticket content to, but different page from, issue ticket #5487 (for reference).

**Comment by dbona75** [comment]
Hello , yes but must be corrected both pages !!!!

Scarica Outlook<https://aka.ms/qtex0l> per iOS
________________________________
Da: Trond B. Krokli ***@***.***>
Inviato: Saturday, May 1, 2021 2:01:21 PM
A: MicrosoftDocs/windowsserverdocs ***@***.***>
Cc: Daniele Bona ***@***.***>; Author ***@***.***>
Oggetto: Re: [MicrosoftDocs/windowsserverdocs] Enterprise PRT deprecated by New Edge (#5486)


Identical ticket content to, but different page from, issue ticket #5487<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fwindowsserverdocs%2Fissues%2F5487&data=04%7C01%7Cdaniele.bona%40microsoft.com%7Cbd64f961eed143d1447708d90c98d644%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637554672905610336%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MVRx11sKpEhEcPwM5zkOR4vaBSqOneynYHHsV2DIG7A%3D&reserved=0> (for reference).

**Comment by illfated** [comment]
Sure, that is why I included " **but different page from,** ", but I guess what I wrote is not clear enough.

I will edit the comment to say only "ref."

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
