### ISSUE TITLE
Enterprise PRT deprecated by New Edge

### ISSUE THREAD

**Issue by dbona75** [MicrosoftDocs/windowsserverdocs#5487]
[Enter feedback here]

Hello Guys,

I think this document should be updated. Indeed today is no more possible to use device conditional access policies, device compliance policies, etc with ADFS onprem federated applications because the new Edge browser doesn't support the enterprise prt token.

This document remains true only for Internet Explorer.

Thanks

dabona@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74d09c81-d205-dbd0-ea6a-aaf469eadf5c
* Version Independent ID: 458db848-1b30-1115-8814-3a639a57c70b
* Content: [Configure Device-based Conditional Access on-Premises](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-device-based-conditional-access-on-premises)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-Device-Based-Conditional-Access-on-Premises.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-Device-Based-Conditional-Access-on-Premises.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Identical ticket content to, but different page from, issue ticket #5486 (for reference).

**Comment by illfated** [comment]
> Identical ticket content to, but different page from, issue ticket #5486 (for reference).

This sentence seems to be unclear, so I will replace it with only the word "ref.".
