### ISSUE TITLE
Configure a Remote Access Cluster in a VPN only deployment

### ISSUE THREAD

**Issue by pulse717** [MicrosoftDocs/windowsserverdocs#549]
Can this be updated to include configuring a Remote Access Cluster in a VPN only deployment with server 1709 nodes. This documentation focuses on DirectAccess. Microsoft has been actively encouraging organizations who are considering a DirectAccess solution to instead implement AlwaysOn VPN. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 850c01ae-4168-d0be-a80e-43ab921a31c8
* Version Independent ID: e3112370-7fc2-1872-9461-0519d7ef41e8
* Content: [Configure a Remote Access Cluster](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/ras/cluster/configure/configure-a-remote-access-cluster)
* Content Source: [WindowsServerDocs/remote/remote-access/ras/cluster/configure/Configure-a-Remote-Access-Cluster.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/ras/cluster/configure/Configure-a-Remote-Access-Cluster.md)
* Service: **unspecified**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@pulse717, thank you. I will update the documentation to reflect Always On VPN.

**Comment by shortpatti** [comment]
@pulse717, I apologize for the delay, I have the engineering team working on providing more details.

**Comment by pulse717** [comment]
Thanks for the update Patti.

**Comment by shortpatti** [comment]
Hi @hitchb52, I'm updating the content now.  The content should be done next week to wrap up the questions that are still being answered.

**Comment by hitchb52** [comment]
Thanks @shortpatti, this AOV clustering\High Availability is mind boggling

**Comment by pulse717** [comment]
Thanks for the update

**Comment by shortpatti** [comment]
@pulse717, I am working with the engineering team to rework this topic since DirectAccess is being phased out.

**Comment by shortpatti** [comment]
@MihaiSP, can you take a look at this and update the content?
