### ISSUE TITLE
Windows interface

### ISSUE THREAD

**Issue by Erik-code** [MicrosoftDocs/windowsserverdocs#5490]
what exactly is the Windows interface?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28e747b1-411e-7f53-69d5-69c3730bf223
* Version Independent ID: d8da91d3-7b35-5a49-e484-e16fc31011ef
* Content: [Change a Master Boot Record (MBR) into a GUID partition table (GPT) disk](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/change-an-mbr-disk-into-a-gpt-disk#converting-using-the-windows-interface)
* Content Source: [WindowsServerDocs/storage/disk-management/change-an-mbr-disk-into-a-gpt-disk.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/change-an-mbr-disk-into-a-gpt-disk.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
According to the description, it appears to be the Graphical User Interface (GUI), where you use a mouse pointer to click or right-click to perform actions, in contrast to the command-line interface used in CMD or PowerShell, where you could perform the actions via text commands, cmdlets or scripts.

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
assign:xelu86

**Comment by Xelu86** [comment]
Hey @Erik-code,

Thanks again for contacting Microsoft. We value your feedback. 

Per this documentation, the **Windows interface** in this article is referencing the Graphical User Interface (GUI) for the Disk Management utility:

![image](https://user-images.githubusercontent.com/103963494/186552081-fe676ce2-599f-4f50-9dc8-37cb6cf9b8d1.png)

I have attached a virtual drive to my VM to perform the example given under the **Windows interface** section of this article (my drive was already set as MBR):

![image](https://user-images.githubusercontent.com/103963494/186553069-cc9c2a01-d772-42d2-b793-7ca350580ee5.png)

We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
