### ISSUE TITLE
OpenSSH Server config doc missing vital info

### ISSUE THREAD

**Issue by LarryBrasfield** [MicrosoftDocs/windowsserverdocs#5491]
The article should mention the necessity of certain permissions on a user's .ssh/authorized_keys file for public key authentication to succeed.  In particular: (1) the file should not inherit permission; (2) the user should not appear on the ACL; (3) BUILTIN\Administrators should have R or RX permission; and (4) NT AUTHORITY\SYSTEM should have R or RX permission.

Without this information, very few people will get public key authentication to work without recourse to outside sources of this information. In my opinion, Microsoft Docs should be the primary, go-to source, and that is why the article needs this improvement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8ad5c9a-efb1-d994-0e3c-53c90096a245
* Version Independent ID: 5cb0ea97-4c3d-ffdf-b69c-8a717f9f9f3f
* Content: [OpenSSH Server Configuration for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_server_configuration)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Server_Configuration.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Server_Configuration.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by illfated** [comment]
Related issue tickets:

- #5451 **SSH to windows using key does not allow to connect with domain controller.**
opened 15 days ago by @nippyin

- #5388 **OpenSSH documentation incorrectly categorizes StrictModes as not supported**
opened on Mar 21 by @alvinzhengq

- #4669 **GSSAPIAuthentication for OpenSSH**
opened on Jul 27, 2020 by @jborean93

- #4315 **administrators_authorized_keys Permissions**
opened on May 9, 2020 by @ThomasMConnors

- #4253 **Further caveat on administrators and authorised keys**
opened on Apr 29, 2020 by @pjt33

- #4124 **Can't logon with AAD user to windows 10 SSH server**
opened on Apr 3, 2020 by @scyto

**Comment by tgauth** [comment]
> In particular: (1) the file should not inherit permission; (2) the user should not appear on the ACL; (3) BUILTIN\Administrators should have R or RX permission; and (4) NT AUTHORITY\SYSTEM should have R or RX permission.

The file permission requirements for an authorized_keys file are the following: 
1) NT AUTHORITY\SYSTEM is **required** to have _FullControl_ File System Rights
2) The user (who has the authorized_keys file in their .ssh folder) & BUILTIN\Administrators are **permitted** to have _any_ File System Rights
4) Everyone else is **permitted** to have _Read_ File System Rights

There are various scenarios that would fulfill these requirements.

An easy way to do so is to use the ACL of the user's public key file, as long as it was generated using ssh-keygen, like so:
`get-acl "$env:systemdrive\users\<user>\.ssh\id_rsa.pub" | set-acl "$env:systemdrive\users\<user>\.ssh\authorized_keys"`

**Comment by robinharwood** [comment]
@tgauth - Thanks for providing this detailed response.

@LarryBrasfield - Thanks for your dedication to our documentation. We've submitted a documentation change based on the discussion above, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

#please-close
