### ISSUE TITLE
Supported Windows Version missing

### ISSUE THREAD

**Issue by boyracer2014** [MicrosoftDocs/windowsserverdocs#5493]
this cmdlet only applies to Windows 10 / Server 2019 and later

**Comment by illfated** [comment]
There appears to be some missing information. Would you like to try again, or are you able to point back to where you were before you commented here?

![image](https://user-images.githubusercontent.com/38162891/116582319-88d50000-a915-11eb-90d0-bcd4a4d31bbd.png)

**Comment by boyracer2014** [comment]
hello, i am referring to this document : https://docs.microsoft.com/en-us/windows-server/networking/technologies/hpn/hpn-nic-advanced-properties - however it does not work prior to 10/2019 it seems. would be nice to mention this.

**Comment by illfated** [comment]
Thank you. This is the accompanying text that would have appeared in the ticket comment:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c413342-d217-523a-e425-9c7e6e5da850
* Version Independent ID: 46894097-547f-35c2-f693-3363fa3d1474
* Content: [NIC advanced properties](https://docs.microsoft.com/en-us/windows-server/networking/technologies/hpn/hpn-nic-advanced-properties)
* Content Source: [WindowsServerDocs/networking/technologies/hpn/hpn-nic-advanced-properties.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/hpn/hpn-nic-advanced-properties.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

***

Going to look into this issue later, as soon as I get the phrasing right. (Others are encouraged to contribute as well, maybe even creating a Pull Request (PR) to add corrections, if you have good ideas for how the content should be written.)

**Comment by dknappettmsft** [comment]
The cmdlet was wrong in the text and didn't match what is in the screenshots.  I've updated this to Get‑NetAdapterAdvancedProperty, which works on both Windows Server 2016 and 2019.

#please-close
