### ISSUE TITLE
Broken link to KB

### ISSUE THREAD

**Issue by ElizabethGreene** [MicrosoftDocs/windowsserverdocs#5497]
There is a broken link to a KB that no longer exists.

 Microsoft Knowledge Base article 902229 linked via https://go.microsoft.com/fwlink/?LinkId=186066 to https://support.microsoft.com/en-us/help/902229 which returns a 404 error.  The original KB was for server 2003, so no big shock that it's been removed.  
 
 Here is what that page used to look like per the internet archive:
 https://web.archive.org/web/20190110172734/https://support.microsoft.com/en-us/help/902229/preset-values-for-the-windows-time-service-group-policy-settings-are-d
 
 I don't believe that usefully adds to this in any way, so the broken link can probably be removed.   Thanks!  <egreene@microsoft.com>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4d52178-35e4-18fa-4e0d-3d983278664d
* Version Independent ID: b2ef1ce4-2d5f-f4c9-9cd2-577866c30a4d
* Content: [How the Windows Time Service Works](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/how-the-windows-time-service-works)
* Content Source: [WindowsServerDocs/networking/windows-time-service/How-the-Windows-Time-Service-Works.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/windows-time-service/How-the-Windows-Time-Service-Works.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @dahavey
* Microsoft Alias: **dahavey**

**Comment by ElizabethGreene** [comment]
The same broken link is on page https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tech-ref

**Comment by illfated** [comment]
Both documents are in the same folder/directory, so it should be OK to create a PR to fix both pages using the same solution. Thank you for pointing out the issue and the relation between those 2 pages.

**Comment by illfated** [comment]
I also notice that there is some kind of formatting issue in the **See Also** section, so that bit would be nice to get cleaned up as well.
- https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/how-the-windows-time-service-works#see-also

I will suggest copying the **Related topics** section from the other page, updated to link the other page instead of itself.

**Comment by illfated** [comment]
There you go. PR #5498 is now ready for review, comments, and suggestions. ( I had to get my night sleep mid-way through my editing of the PR content. 😉 )

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Linked to similar issue that was previously resolved #6445.
#please-close
