### ISSUE TITLE
Network Monitor Install link is dead

### ISSUE THREAD

**Issue by ato2** [MicrosoftDocs/windowsserverdocs#5501]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e28e601d-3a48-36cc-c1f1-6638c9ca38d1
* Version Independent ID: b54244fc-4ff7-6ebf-bc51-b880a3ae8ade
* Content: [Pktmon support for Microsoft Network Monitor (Netmon)](https://docs.microsoft.com/en-us/windows-server/networking/technologies/pktmon/pktmon-netmon-support)
* Content Source: [WindowsServerDocs/networking/technologies/pktmon/pktmon-netmon-support.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/pktmon/pktmon-netmon-support.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @khdownie
* Microsoft Alias: **v-kedow**

**Comment by illfated** [comment]
Fair point. For a document updated as recently as 5 months ago, you would think that the only visible link on the page would be a working one.

![image](https://user-images.githubusercontent.com/38162891/116963496-4579e900-aca9-11eb-898a-70393315776e.png)

***

Follow these steps to install and configure Netmon to parse Packet Monitor-generated ETL files:

   1. [Install Network Monitor 3.4](/download/4865).

```
Follow these steps to install and configure Netmon to parse Packet Monitor-generated ETL files:

   1. [Install Network Monitor 3.4](/download/4865).
```

***

Then again, in hindsight, it appears that Microsoft Network Monitor 3.4 is an old and archived tool, so the link needs to be changed to point to the archives.

**Comment by illfated** [comment]
https://en.wikipedia.org/wiki/Microsoft_Network_Monitor :

## Microsoft Network Monitor
From Wikipedia, the free encyclopedia

Microsoft Network Monitor is a deprecated packet analyzer. It enables capturing, viewing, and analyzing network data and deciphering network protocols. It can be used to troubleshoot network problems and applications on the network. Microsoft Network Monitor 1.0 (codenamed Bloodhound) was originally designed and developed by Raymond Patch, a transport protocol and network adapter device driver engineer on the Microsoft LAN Manager development team.

Network Monitor was replaced by Microsoft Message Analyzer (MMA was discontinued in 2019[1]).

**Comment by illfated** [comment]
Working download link:

### https://www.microsoft.com/en-us/download/details.aspx?id=4865

![image](https://user-images.githubusercontent.com/38162891/116963902-67c03680-acaa-11eb-9fd9-38488d66ce18.png)

**Comment by khdownie** [comment]
Thanks @ato2 and @illfated - I fixed this one. Will try to work through others as I get time. You can close this PR now.

**Comment by pintail120** [comment]
where can I find a link like that for PKTMON ?
