### ISSUE TITLE
Duplicate step in Create the VPN Server Authentication template section

### ISSUE THREAD

**Issue by ryandengstrom** [MicrosoftDocs/windowsserverdocs#5502]
In the 'Create the VPN Server Authentication template' section of the instructions, step 11 looks to be duplicated with step 13.  It should be removed, as the step should be done after the certsrv service is restarted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76dd49bb-b86e-f5b7-35b9-a8d246d36fcb
* Version Independent ID: dedfa83f-36d6-f60b-e839-ba382c5a7372
* Content: [Configure the Server Infrastructure](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by illfated** [comment]
https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure#create-the-vpn-server-authentication-template

Good point, step 11 seems very much out of place, and should not be a step to be performed right before a system restart.

***

10. Close the Certificate Templates console.

11. In the navigation pane of the Certification Authority snap-in, right-click **Certificate Templates**, click **New** and then click **Certificate Template to Issue**.

12. Restart the Certificate Authority services.(*)

13. In the navigation pane of the Certification Authority snap-in, right-click **Certificate Templates**, select **New** and then select **Certificate Template to Issue**.

14. Select the name you chose in step 4 above, and click **OK**.

15. Close the Certification Authority snap-in.

**Comment by dknappettmsft** [comment]
Thanks for raising this issue.  Step 11 has been removed and the changes should be visible in a few hours.

#please-close
