### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by elljay23** [MicrosoftDocs/windowsserverdocs#5504]
Typo (Too many zeros in "10,0000") in "To get the SystemClockRate value, you can use the following command and convert it from seconds to clock ticks by using the formula of (seconds × 1,000 × 10,0000):"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d09b16e-4bbb-91fa-3d84-e7623ec4dc07
* Version Independent ID: b6eadad5-0167-34b6-ed3a-16fa7ee83c60
* Content: [Windows Time service tools and settings](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings)
* Content Source: [WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by illfated** [comment]
Good point. We should be using the ISO system, not reference numbers read in groups of myriads (10,000s) (https://en.wikipedia.org/wiki/Myriad) or Kharab (10,00,00,00,00,000).

**Comment by illfated** [comment]
There you go. PR #5536 is now ready for review, comments, and suggestions.

**Comment by IngridAtMicrosoft** [comment]
Addressed.
