### ISSUE TITLE
One P too much

### ISSUE THREAD

**Issue by stiftung-battenberg** [MicrosoftDocs/windowsserverdocs#5506]
Suppport for building modern line-of-business apps

One p too much in Su(p)pport, spelling mistake

;)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bd4457e-c29d-d174-f88f-6eedfc7e7db6
* Version Independent ID: bb86780a-ac42-97bc-9d38-acb019437f76
* Content: [What's new in Active Directory Federation Services for Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/overview/whats-new-active-directory-federation-services-windows-server.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Thank you for reminding me of this. I had forgotten about it for a while.

I was going to fix it 10 days ago by opening a Pull Request to have it updated, 
but I never got any reply from @saurabh500 (opened issue ticket #5475 **Typo on page**).

**Comment by dknappettmsft** [comment]
This has been corrected and should be visible in a few hours.

#please-close
