### ISSUE TITLE
Link not going to right page.

### ISSUE THREAD

**Issue by breento** [MicrosoftDocs/windowsserverdocs#5507]
[Enter feedback here]
This link https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v-virtual-switch/rdma-and-switch-embedded-teaming  was going to the right page last week, now it's going to an Azure HCI doc page which is not containing the information that was on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61dec703-ec84-c4fc-ab45-83decde810f2
* Version Independent ID: 2b0ebf31-825f-39cd-d7c8-8e207344252e
* Content: [Configure and View VLAN Settings on Hyper-V Virtual Switch Ports](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v-virtual-switch/configure-and-view-vlan-settings-on-hyper-v-virtual-switch-ports)
* Content Source: [WindowsServerDocs/virtualization/hyper-v-virtual-switch/Configure-and-View-VLAN-Settings-on-Hyper-V-Virtual-Switch-Ports.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v-virtual-switch/Configure-and-View-VLAN-Settings-on-Hyper-V-Virtual-Switch-Ports.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
On which page did you find that link, and what is the description text for that link?

**Comment by illfated** [comment]
Also: You may want to check out the **Q & A page** https://docs.microsoft.com/en-us/answers/topics/windows-server-hyper-v.html to see if this is something you can get answers to quicker than the weeks it takes before someone posts back here with a useful answer.

**Comment by breento** [comment]
> 
> 
> On which page did you find that link, and what is the description text for that link?
> 
> edit:
> I just thought it would be useful to see what the latest changes on that page would be, in case the author of the latest update knows anything about this issue. Was trying to look for where your link is located, but web searches were not too helpful this time.

On this page for example:
https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v-virtual-switch/configure-and-view-vlan-settings-on-hyper-v-virtual-switch-ports
In the main menu there is a link "Remote Direct Memory Access (RDMA) and Switch Embedded Teaming (SET)" going to: https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v-virtual-switch/rdma-and-switch-embedded-teaming  this is the right link and last week was going to the right page. Now this link is going to https://docs.microsoft.com/en-us/azure-stack/hci/concepts/host-network-requirements  which is about Host network requirements for Azure Stack HCI instead of RDMA and Switch Embedded Teaming.

**Comment by illfated** [comment]
@JasonGerend : Do you have any connection to the technicians who seem to be working on redirection for some of the web pages? Or is there some kind of general work going on to move everything over to Azure instead of the existing pages?
