### ISSUE TITLE
Server 2022 Keys Reversed.

### ISSUE THREAD

**Issue by sluhn-klepeib** [MicrosoftDocs/windowsserverdocs#5514]
Windows Server 2022 Standard and Datacenter keys are reversed, they need to be corrected.  The one listed "Datacenter" is actually Standard, and vice versa.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5148ebad-44a0-b14a-d65c-e51650ce4197
* Version Independent ID: ceb3e4c3-ccc3-b75a-ccb1-235ad1a22469
* Content: [KMS client setup keys](https://docs.microsoft.com/en-us/windows-server/get-started/kmsclientkeys)
* Content Source: [WindowsServerDocs/get-started/KMSclientkeys.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/KMSclientkeys.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by dknappettmsft** [comment]
Thanks for flagging this.  This has been fixed and will be visible in the next few hours.

#please-close
