### ISSUE TITLE
Link to Register-CauPlugin doc is broken

### ISSUE THREAD

**Issue by danupton** [MicrosoftDocs/windowsserverdocs#5515]
The link to  Register-CauPlugin on the below page leads to a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25605c2e-831a-5a24-0b3e-3cf7a9279a85
* Version Independent ID: f1af6d9d-1589-e104-2d14-0cb5d2cbade2
* Content: [How Cluster-Aware Updating plug-ins work](https://docs.microsoft.com/en-us/windows-server/failover-clustering/cluster-aware-updating-plug-ins#:~:text=Using%20the%20Microsoft.WindowsUpdatePlugin%201%20Requirements.%20The%20failover%20cluster,Configure%20the%20Windows%20Update%20Agent%20query%20string.%20)
* Content Source: [WindowsServerDocs/failover-clustering/cluster-aware-updating-plug-ins.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/cluster-aware-updating-plug-ins.md)
* Product: **windows-server**
* Technology: **failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by dknappettmsft** [comment]
Thanks for flagging this - I have updated the link and the changes should be visible later today.

#please-close
