### ISSUE TITLE
Very usefull document. thanks

### ISSUE THREAD

**Issue by YokiXml** [MicrosoftDocs/windowsserverdocs#5517]
[Enter feedback here]
Fantastic con. Very usefull

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 385c3c9e-8a25-237b-eb1f-c10569d2fc0d
* Version Independent ID: 1f128afc-b017-4b84-7a9a-f84471baffab
* Content: [Upgrade virtual machine version in Hyper-V on Windows 10 or Windows Server](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/deploy/upgrade-virtual-machine-version-in-hyper-v-on-windows-or-windows-server)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/deploy/Upgrade-virtual-machine-version-in-Hyper-V-on-Windows-or-Windows-Server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/deploy/Upgrade-virtual-machine-version-in-Hyper-V-on-Windows-or-Windows-Server.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by dknappettmsft** [comment]
Thank you for the feedback :)

#please-close
