### ISSUE TITLE
ip-adress.eu 

### ISSUE THREAD

**Issue by akvalibra** [MicrosoftDocs/windowsserverdocs#552]
https not working. http://www.ip-adress.eu/ is fine

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f03c4904-9756-3fcf-17ee-05a2e5717dc9
* Version Independent ID: ec3b6a31-7d65-5ab1-2721-40401a9b3b7f
* Content: [Remote Desktop - Allow access to your PC from outside your network](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-allow-outside-access#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-allow-outside-access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-allow-outside-access.md)
* Service: **unspecified**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **elizapo**

**Comment by lizap** [comment]
You're right - it throws a "this site is not secure" warning. Instead of using the http: address, I'm replacing it with instructions on how to find the IP address. You'll see the changes this afternoon (4/2/18). Thanks for your comment!
