### ISSUE TITLE
Formatting Error DHCP (Dynamic Host Configuration Protocol) Basics

### ISSUE THREAD

**Issue by Maraudier** [MicrosoftDocs/windowsserverdocs#5520]
[Enter feedback here]
Proposed new line break or bullet point:

Current:
Default GatewayOther information can be provided as well, such as Domain Name Service (DNS) server addresses and Windows Internet Name Service (WINS) server addresses. The system administrator configures the DHCP server with the options that are parsed out to the client.

Proposed:

Default Gateway
Other information can be provided as well, such as Domain Name Service (DNS) server addresses and Windows Internet Name Service (WINS) server addresses. The system administrator configures the DHCP server with the options that are parsed out to the client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73153ab0-ccc2-a270-ffe4-783aaf40455c
* Version Independent ID: 1e12552d-7c40-8e02-03a0-4abb785e536f
* Content: [DHCP (Dynamic Host Configuration Protocol) Basics](https://docs.microsoft.com/en-US/windows-server/troubleshoot/dynamic-host-configuration-protocol-basics)
* Content Source: [WindowsServerDocs/troubleshoot/dynamic-host-configuration-protocol-basics.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/troubleshoot/dynamic-host-configuration-protocol-basics.md)
* Product: **windows-server**
* Technology: **troubleshoot**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by illfated** [comment]
Thank you for reporting this issue, it is quite obvious that the text needs to be updated to correct the missing NewLine break. I can easily create a Pull Request to have that part updated. For the other suggestion, I would like to see a suggestion from the article document author to know what needs to be added.

**Comment by craigcaseyMSFT** [comment]
Hello @Maraudier,

Thanks for contacting Microsoft. We value your feedback.

Documentation changes have been made to clarify and acknowledge this issue. The doc changes are now live.

Thank you again and have a most pleasant day.
#please-close
