### ISSUE TITLE
Inaccurate Powershell Command

### ISSUE THREAD

**Issue by ctsaylorsr** [MicrosoftDocs/windowsserverdocs#5523]
This page states that you can backup all active bitlocker protectors for a volume to AD by running manage-bde -protectors -adbackup C:.  This is inaccurate and returns a result of  "ERROR: Specifying the parameter '-ID' is required to back up recovery
information."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82ef6d71-4070-a941-ccc2-868e435e7c18
* Version Independent ID: 1a9eac49-6fd4-de12-9c8a-452ee31f6bc7
* Content: [manage-bde protectors](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/manage-bde-protectors)
* Content Source: [WindowsServerDocs/administration/windows-commands/manage-bde-protectors.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/manage-bde-protectors.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Thank you for pointing out the inaccuracy and error in the documentation.

Would you be able to provide the correct command to replace the incorrect one?

**Comment by illfated** [comment]
(Just as a formality, this is the current Windows 10 help output for the command `manage-bde -protectors -adbackup`)

```
C:\WINDOWS\system32>manage-bde -protectors -adbackup /?
BitLocker Drive Encryption: Configuration Tool version 10.0.19041
Copyright (C) 2013 Microsoft Corporation. All rights reserved.

manage-bde -protectors -adbackup Volume
                       -ID KeyProtectorID
                       [{-ComputerName|-cn} ComputerName]
                       [{-?|/?}] [{-Help|-h}]

Description:
    Backs up recovery information for the drive.

Parameter List:
    Volume      A drive letter followed by a colon, a volume GUID path or
                a mounted volume. Example: "C:",
                \\?\Volume{26a21bda-a627-11d7-9931-806e6f6e6963}\ or
                "C:\MountVolume"
    -id         Backs up the key protector with a certain identifier.
    -ComputerName or -cn
                Runs on another computer. Examples: "ComputerX", "127.0.0.1"
    -? or /?    Displays brief help. Example: "-ParameterSet -?"
    -Help or -h Displays complete help. Example: "-ParameterSet -h"

Examples:
    manage-bde -protectors -adbackup C: -id {84E151C1...7A62067A512}

C:\WINDOWS\system32>_
```

**Comment by illfated** [comment]
Looking back at the output now, it seems obvious that the output example is closer to the answer than what appears on the page. I wonder if the command has changed sometime between Windows Server 2000 and now, that the `-id` parameter might have been added at a later time.

**Comment by dknappettmsft** [comment]
Thanks for raising this issue.  I have made change to update the description for both adbackup and aadbackup parameters to note that ID is required.  The change should be visible in a few hours.

#please-close
