### ISSUE TITLE
Add instructions to start service

### ISSUE THREAD

**Issue by edbird** [MicrosoftDocs/windowsserverdocs#5527]
see:

https://www.youtube.com/watch?v=KLN2bY0dTtQ

service start is required before this will work - no note of this in the instructions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Install OpenSSH](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by dknappettmsft** [comment]
Hi @edbird, this step is covered on the page you linked in the section 'Start and configure SSH Server', with the first two steps being to start the service and make it start automatically. Note that the heading for this is not a sub-heading of 'Install OpenSSH using PowerShell', so it needs to be performed regardless of the installation method. The video showed it through the Services console, but it achieves the same thing.

I hope that clarifies it.

**Comment by dknappettmsft** [comment]
#please-close
