### ISSUE TITLE
MAK activation for Server 2019 is not addressed

### ISSUE THREAD

**Issue by SL-motis** [MicrosoftDocs/windowsserverdocs#5528]
We have several servers in an isolated mode and the MAK key activation is required.  
Please detail the function of MAK licensing for Windows Server 2019 where Internet access is unavailable.

**Comment by dknappettmsft** [comment]
Hi @SL-motis, an alternative option is to activate MAK clients using the telephone. The information on that can be found here https://docs.microsoft.com/en-us/previous-versions/tn-archive/ff793438%28v=technet.10%29#activating-mak-clients-using-the-telephone

I hope that helps.

**Comment by dknappettmsft** [comment]
#please-close

**Comment by SL-motis** [comment]
Hi @dknappettmsft, thanks for the note and using slui.exe 4 allowed me to perform the activation.  However the documentation for server 2019 has not been fixed.  The link you sent was last updated in 2010 and I had not found it despite spending a good amount of time searching.  Surely if we have up-to-date documentation for Server 2019, it should mention MAK activation with a link to more detailed reference material?
