### ISSUE TITLE
Why dont you address the most basic mind numbing problem

### ISSUE THREAD

**Issue by heschelpop** [MicrosoftDocs/windowsserverdocs#553]
2 pc's, joined to same AAD, user is global admin, remote access enabled on both.  NLA is checked on remote pc.  You can log in.  pull hair out. wash rinse repeat.  Please tell us what we need to do for this scenario that applies to majority of small businesses.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5581a04a-e204-4a19-3eba-0852d2eb5d8e
* Version Independent ID: 820c77b6-2182-7e92-bbe6-0819f727d207
* Content: [Remote Desktop clients FAQ](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-client-faq#connection-gateway-and-networks)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.md)
* Service: **unspecified**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
Troubleshooting issue, likely outdated too (page has been updated quite a lot since this ticket).

**Comment by illfated** [comment]
#please-close
