### ISSUE TITLE
Crying

### ISSUE THREAD

**Issue by bchristen** [MicrosoftDocs/windowsserverdocs#5531]
I am not so sure this should actually be a recommendation and in fact the VPN section should be the recommended option. shodan.io will find them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb3496f-9df6-8859-4569-ea033daed5ac
* Version Independent ID: 9f762b67-575d-ea11-08d5-edbab9a21f15
* Content: [Remote Desktop - Allow access to your PC from outside your network](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-allow-outside-access)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-allow-outside-access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-allow-outside-access.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **elizapo**

**Comment by dknappettmsft** [comment]
Thanks for raising this. I've updated the warning text to say it's not recommended and that it's preferable to use a VPN.  The change should be visible in a few hours.

#please-close
