### ISSUE TITLE
NLA

### ISSUE THREAD

**Issue by heschelpop** [MicrosoftDocs/windowsserverdocs#554]
how does anyone reviewing this documentation feel this is appropriate:

"The remote PC might only allow PCs to connect that have Network Level Authentication set up. "

gee, since windows 10 defaults to this setting and tell us its for our own good, then you should sure as h** have detailed, step by step, idiot proof procedures as to how to make this work because I cant - and if they do exist, then I look forward to the link, but they are woefully buried.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5581a04a-e204-4a19-3eba-0852d2eb5d8e
* Version Independent ID: 820c77b6-2182-7e92-bbe6-0819f727d207
* Content: [Remote Desktop clients FAQ](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-client-faq#connection-gateway-and-networks)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.md)
* Service: **unspecified**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by weaslevdmd** [comment]
See issue https://github.com/MicrosoftDocs/windowsserverdocs/issues/2931

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by IngridAtMicrosoft** [comment]
#please-close
