### ISSUE TITLE
"Step 2 - Install Application Proxy", link returns 404

### ISSUE THREAD

**Issue by CloudViking86** [MicrosoftDocs/windowsserverdocs#5543]
Hello,

This link under "[Step 2 - Install Application Proxy](https://docs.microsoft.com/en-us/windows-server/administration/hybrid-cloud-print/hybrid-cloud-print-deploy#step-2---install-application-proxy)":
[Tutorial: Add an on-premises application for remote access through Application Proxy in Azure Active Directory.](https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/application-proxy-add-on-premises-application) returns a 404.

I guess the correct link would be this?
https://docs.microsoft.com/en-us/azure/active-directory/app-proxy/application-proxy-add-on-premises-application

Best Regards - Karl

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bdc0597-e371-3404-95b8-3cb6879048e8
* Version Independent ID: 0c03b7ab-64cb-e25a-41f2-4a8bf3859ea7
* Content: [Deploy Windows Server Hybrid Cloud Print](https://docs.microsoft.com/en-us/windows-server/administration/hybrid-cloud-print/hybrid-cloud-print-deploy)
* Content Source: [WindowsServerDocs/administration/hybrid-cloud-print/hybrid-cloud-print-deploy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/hybrid-cloud-print/hybrid-cloud-print-deploy.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @msjimwu
* Microsoft Alias: **jimwu**

**Comment by illfated** [comment]
Confirmed, the link does indeed cause a 404 error for this link: https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/application-proxy-add-on-premises-application

Also, it looks quite correct to substitute the current bad link with the suggested link https://docs.microsoft.com/azure/active-directory/app-proxy/application-proxy-add-on-premises-application .

Would you like to create a Pull Request to replace the broken link with the suggested one?

(Link to the editing page: https://github.com/MicrosoftDocs/windowsserverdocs/edit/master/WindowsServerDocs/administration/hybrid-cloud-print/hybrid-cloud-print-deploy.md)

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
The article hybrid-cloud-print-deploy.md may have been moved, renamed, or absorbed into another article. Unable to make any changes. 

Verified https://learn.microsoft.com/en-us/azure/active-directory/app-proxy/application-proxy-add-on-premises-application link is active w/o issue. 

Closing thread. #please-close
