### ISSUE TITLE
Page needs to be updated with what's new in Windows Server 21H1

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/windowsserverdocs#5546]
[Enter feedback here]
Expected behavior: Page documents what is new with all versions of Windows Server, SAC.
Actual behavior: Page documents what is new wall with versions of Windows Server, SAC through 20H2.
Steps to reproduce:
1. Go to page.
2. Observe that it does not have a link to what's new in Windows Server SAC 21H1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 511845b3-0a7a-1820-c501-dbbf70c46f20
* Version Independent ID: 9352e65e-eb25-6fe4-16f3-7b4511bf9d14
* Content: [What's New in Windows Server](https://docs.microsoft.com/en-us/windows-server/get-started/whats-new-in-windows-server)
* Content Source: [WindowsServerDocs/get-started/whats-new-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/whats-new-in-windows-server.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 5542 -b #assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#6625 sign:xelu86

**Comment by Xelu86** [comment]
Hey @rossmpersonal,

Thanks again for contacting Microsoft. We value your feedback. 

Looking further into this, I came across [this page](https://learn.microsoft.com/en-us/windows-server/get-started/servicing-channels-comparison#semi-annual-channel) with the following notes:

> There will be no future Semi-Annual Channel releases of Windows Server. Customers using the SAC should move to [Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/) where the same release cadence and rapid innovation continues with features such as [Azure Kubernetes Service on Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/aks-hci/). Alternatively, use the Long-Term Servicing Channel of Windows Server.

and

> The current Semi-Annual Channel release is Windows Server, version 20H2. If you want to put servers in this channel, you should install Windows Server, version 20H2, which can be installed in Server Core mode or as Nano Server run in a container. In-place upgrades from a Long-Term Servicing Channel release aren't supported because they are in different release channels. This applies vice versa. You cannot upgrade or change from Semi-Annual Channel to Long-Term Servicing Channel without a clean installation.
>
> A Semi-Annual Channel release isn't an update – it's the next Windows Server release in the Semi-Annual Channel. In-place upgrades from one Semi-Annual Channel release to a later Semi-Annual Channel release are possible. This makes it easier to keep up with the relatively short release cadence.
 
More information on this is that [Windows Server, version 20H2](https://learn.microsoft.com/en-us/lifecycle/products/windows-server) will reach the end of servicing on August 9, 2022. This will also be the retirement of Windows Server Semi-Annual Channel (SAC). [There will be no future SAC releases of Windows Server](https://learn.microsoft.com/en-us/windows-server/get-started/servicing-channels-comparison#semi-annual-channel), and this product will no longer receive security updates after August 9, 2022.

Windows Server is moving to the Long-Term Servicing Channel (LTSC) as the primary release channel.
 Customers using Windows Server SAC should move to [Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/). Alternatively, customers may use the Long-Term Servicing Channel of Windows Server. More can be read at our [Windows Server Release](https://learn.microsoft.com/en-us/windows-server/get-started/windows-server-release-info) page if interested.

We hope that this addresses your concern for the missing content. We will now be closing this thread. 

We do wish that you have a most pleasant day!
#please-close
