### ISSUE TITLE
OpenSSHUtils Module not found

### ISSUE THREAD

**Issue by reuvygroovy** [MicrosoftDocs/windowsserverdocs#5548]
[Enter feedback here]

When trying to import this module I got the following error:
PS C:\Windows\System32> Install-Module -Force OpenSSHUtils -Scope AllUsers
Install-Package: C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1:9711
Line |
9711 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No match was found for the specified search criteria and module name 'OpenSSHUtils'. Try
     | Get-PSRepository to see all available registered module repositories.

PS C:\Windows\System32>

And then I found the following link which states that the module is depreciated: https://stackoverflow.com/questions/62873521/powershell-opensshutils

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH key management for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by illfated** [comment]
(ref. https://github.com/MicrosoftDocs/windowsserverdocs/issues?utf8=%E2%9C%93&q=%221e4b742e-d999-2c1e-a396-dc149f7ac76b%22&in=body)

**Comment by dknappettmsft** [comment]
Thanks for submitting this issue. I have reworked this document to remove or replace parts that are no longer relevant or correct based on this and several other issues raised for this page.

The changes should be visible in around 6-12 hours.

#please-close
