### ISSUE TITLE
Which label?

### ISSUE THREAD

**Issue by bobcruz** [MicrosoftDocs/windowsserverdocs#555]
Your documentation neglects to mention what will happen if two identical labels exists within a batch file.  When a GOTO to that label name is issued, does the interpreter begin its scan from the top of the program, or from the next line?  Or from the next logical line within an expanded multiple command?  If it starts from the next physical line, does it stop at the last line of the program, or wrap around to the first line of the program and continue the scan until it reaches its starting point?

Consider use case 1:
REM start program
ECHO One
:my_label
ECHO Two
GOTO my_label
ECHO  Three
:my_label
ECHO Four
REM EOF

Should I expect One, Two, Four (stop) or One, Two, One, Two, One, Two... ?

Use Case 2 (multiple commands on one physical line)
REM start program
ECHO One
(GOTO my_label &:my_label &ECHO Two)
ECHO  Three
:my_label
ECHO Four
REM EOF

Should I expect One, Two, Three, Four; or One, Three, Four?

This is more than a thought exercise, as the answer comes into play if I copy an internal subroutine into a program without making its labels unique:

REM First line
ECHO One
CALL :Sub
ECHO Two
GOTO my_label
ECHO Three
:my_label
ECHO Four
GOTO :EOF

:Sub
ECHO Sub1
GOTO my_label
ECHO Sub2
:my_label
ECHO Sub3
GOTO :EOF

Will the GOTO in the internal subroutine transfer control to the second my_label ("within" the subroutine) or to the first my_label ("within" the calling program)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc5f4b1-c41e-73f7-21b5-d817c6655973
* Version Independent ID: 92746b15-0718-c72d-eea0-66b98e6bec9b
* Content: [goto](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/goto)
* Content Source: [WindowsServerDocs/administration/windows-commands/goto.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/goto.md)
* Service: **unspecified**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
@bobcruz : I really hope you have found an answer to your question above by now.

If not, if you are still looking for an answer to your question, I do recommend using the forum pages instead.

Here is a handful of forums I hope can be useful to you in your search for answers:
- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Disclaimer: I am not affiliated with Microsoft or the Microsoft Docs teams here on GitHub.

**Comment by illfated** [comment]
If you by random chance come across a solution to your issue and find that the solution fits within the existing documentation, feel free to suggest improvements to the page.

Otherwise, ...

**Comment by illfated** [comment]
#please-close
