### ISSUE TITLE
Please clarify access level needed for this service account.

### ISSUE THREAD

**Issue by richard-artes** [MicrosoftDocs/windowsserverdocs#5550]
[Enter feedback here]
Please clarify access level needed for this service account.
Does this service account need to be Domain Admin account? Or can it just be a domain user account?
Thanks
Richard Artes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dde1639a-439a-a95e-028f-62fbbee058ec
* Version Independent ID: 357a5c2e-c4f8-d618-1740-5235d9a26a2a
* Content: [Manually Configure a Service Account for a Federation Server Farm](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/manually-configure-a-service-account-for-a-federation-server-farm)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Manually-Configure-a-Service-Account-for-a-Federation-Server-Farm.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Manually-Configure-a-Service-Account-for-a-Federation-Server-Farm.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Answser from Dave Patrick. 

Any standard domain account can be used as a service account for AD FS. Group Managed Service accounts are also supported. The permissions required at runtime will be added automatically when you configure AD FS.

See [AD FS requirements](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-requirements#BKMK_4)
