### ISSUE TITLE
Download link doesn't work

### ISSUE THREAD

**Issue by nalinabey** [MicrosoftDocs/windowsserverdocs#5551]
[Enter feedback here]

Below SPA download link doesn't work.Please help to find the link

Microsoft Server Performance Advisor 3.1 (32-bit)
http://download.microsoft.com/download/0/3/D/03D07D11-18D4-4160-B4AC-915061B85669/SPAPlus_x86.cab

Microsoft Server Performance Advisor 3.1 (64-bit)
http://download.microsoft.com/download/0/3/D/03D07D11-18D4-4160-B4AC-915061B85669/SPAPlus_amd64.cab

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 697b9e0a-e082-cadd-3c08-ffb54f640e45
* Version Independent ID: 45250bd4-d7e9-6e79-a6d4-80d169cb5ac7
* Content: [Microsoft Server Performance Advisor](https://docs.microsoft.com/en-us/windows-server/administration/server-performance-advisor/microsoft-server-performance-advisor)
* Content Source: [WindowsServerDocs/administration/server-performance-advisor/microsoft-server-performance-advisor.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/server-performance-advisor/microsoft-server-performance-advisor.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
From https://github.com/MicrosoftDocs/windowsserverdocs/issues?utf8=%E2%9C%93&q=%2245250bd4-d7e9-6e79-a6d4-80d169cb5ac7%22&in=body :

#4905 **Server Performance Advisor download link does not work**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 5550 -b #assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
The microsoft-server-performance-advisor.md article has either been deprecated or absorbed into another article. Closing threads #4905 & #5551 as updates cannot be made.
#please-close
