### ISSUE TITLE
Missing OpenSSHUtils

### ISSUE THREAD

**Issue by DiskCrasher** [MicrosoftDocs/windowsserverdocs#5553]
This command does not work:
Install-Module -Force OpenSSHUtils -Scope AllUsers

Says no match for package was found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH key management for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by illfated** [comment]
See also the following issues from https://github.com/MicrosoftDocs/windowsserverdocs/issues?utf8=%E2%9C%93&q=%221e4b742e-d999-2c1e-a396-dc149f7ac76b%22&in=body

- #5552 **Instructions to install deprecated OpenSshUtils module**
  opened 5 hours ago by zack-at-ds2

- #5548 **OpenSSHUtils Module not found**
  opened 14 hours ago by reuvygroovy

- #5538 Outdated documentation
  opened 3 days ago by aperally

- #5408 **Error: No match was found for the specified search criteria and module name 'OpenSSHUtils'**
  opened on Mar 26 by JoshSnider

- #5395 **Out of date - Repair-AuthorizedKeyPermission**
  opened on Mar 23 by nekdima

- #5138 **These instructions do not work on Windows 10 20h2**
  opened on Dec 19, 2020 by mihai-preda

- #5000 **Clarification needed**
  opened on Nov 10, 2020 by conyg

- #4948 **OpenSSHTools doesn't exist anymore on powershell gallery**
  opened on Oct 28, 2020 by JustinGrote

- #4893 **Install-Module OpenSSHUtils failure**
  opened on Oct 8, 2020 by LeeJenkins

- #4787 **OpenSSHUtils module does not exist**
  opened on Sep 4, 2020 by oliversalzburg

- #4770 **Error when following instructions to install OpenSSHUtils**
  opened on Aug 31, 2020 by c0f

- #4743 **Nope. First example errors out.**
  opened on Aug 22, 2020 by boomalator

- #4702 **OpenSSHUtils got unlisted from the PowerShell gallery**
  opened on Aug 5, 2020 by jagraveldinger

- #4690 **OpenSSHUtils install reference no longer valid**
  opened on Aug 1, 2020 by wrjohnson

- #4634 **More documentation required**
  opened on Jul 11, 2020 by garylawuk

- #4622 **Out-of-date - OpenSSHUtils no longer available.**
  opened on Jul 8, 2020 by Jammrock

- #4598 **Instructions provided ends with an error**
  opened on Jun 28, 2020 by jyavenard

- #4345 **OpenSSHUtils Not Needed**
  opened on May 14, 2020 by gynnantonix

- #3806 **OpenSSHUtils is deprecated**
  opened on Jan 28, 2020 by FizzBuzz791

**Comment by dknappettmsft** [comment]
Thanks for submitting this issue. I have reworked this document to remove or replace parts that are no longer relevant or correct based on this and several other issues raised for this page.

The changes should be visible in around 6-12 hours.

#please-close
