### ISSUE TITLE
Options described do not exist on screen

### ISSUE THREAD

**Issue by FerrousJack** [MicrosoftDocs/windowsserverdocs#5558]
The options described do not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3331f737-d4d5-8b05-e5e2-57ba67903f6b
* Version Independent ID: 33e0848c-3070-2367-8d21-28f3e05f5850
* Content: [Join a Computer to a Domain](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/join-a-computer-to-a-domain)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Join-a-Computer-to-a-Domain.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Join-a-Computer-to-a-Domain.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @FerrousJack,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made to reflect how to join a computer and a server to a domain and will be live after the next business day. We will be closing this as resolved. 

Thank you and have a most pleasant day. #please-close
