### ISSUE TITLE
eol of wsus 3.0 sp2

### ISSUE THREAD

**Issue by NCBrady** [MicrosoftDocs/windowsserverdocs#5562]
I think you should not be quoting wsus 3.0 sp2 when it's eol - see https://techcommunity.microsoft.com/t5/windows-it-pro-blog/end-of-synchronization-for-wsus-3-0-sp2/ba-p/2371993

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94dc8d96-147f-27ea-2ba8-9a346fa63d55
* Version Independent ID: ac53f9d9-629b-9a95-6fd9-790b9fa9572f
* Content: [Plan Your WSUS Deployment](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/plan/plan-your-wsus-deployment)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/plan/plan-your-wsus-deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/plan/plan-your-wsus-deployment.md)
* Product: **windows-server**
* Technology: **wsus**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 5561 -b #assign:IngridAtMicrosoft

**Comment by v-thepet** [comment]
Hi @NCBrady,

Thanks for contacting Microsoft. We appreciate your feedback.
A documentation change has been made to update this link and will go live the next business day. 
We're now closing this issue. Thanks again for your input, and have a most pleasant day.

#please-close
