### ISSUE TITLE
Typo in doc page for bcdedit

### ISSUE THREAD

**Issue by fpl9000** [MicrosoftDocs/windowsserverdocs#5566]
This page has a typo in this sentence in the debugging section:

> This command does not enablepose.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cb98e1d-8a4e-b087-b9f0-3f98862f3347
* Version Independent ID: 2e8ca9f3-b293-8677-b379-0d2f3b204857
* Content: [bcdedit](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/bcdedit)
* Content Source: [WindowsServerDocs/administration/windows-commands/bcdedit.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/bcdedit.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Well spotted. Thank you for reporting this typo.

**Comment by illfated** [comment]
Hmm, while I was looking for how on earth this sentence would become coherent, just by adding a space between the two words, I found that this "typo" covers a much more important issue entirely. Much of the actual sentence has gone missing:

**Current content:**

| Parameter | Description |
| ------ | :---------- |
| /dbgsettings | Specifies or displays the global debugger settings for the system. This command does not enablepose. To set an individual global debugger setting, use the **bcdedit /set** `<dbgsettings> <type> <value>` command. |

**Original content:**

|Parameter|Description|
|---------|-----------|
|/dbgsettings|Specifies or displays the global debugger settings for the system. This command does not enable or disable the kernel debugger; use the **/debug** option for that purpose. To set an individual global debugger setting, use the **bcdedit /set** \<dbgsettings> <type> <value> command.|

**Comment by illfated** [comment]
I had to go back to commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/d092cf3f8c05745aaecceddf708f5898054ca5f4 (March 31, 2020) to find the original version of the document, to be able to get the sentence to make sense, both logically and grammatically.

The unwanted change seems to have happened in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/a56d40f989ceaec5a55f804b0bbaf07f91f1b8d9 (April 3, 2020) (https://github.com/MicrosoftDocs/windowsserverdocs/commit/a56d40f989ceaec5a55f804b0bbaf07f91f1b8d9#diff-254cc20d67a6fe78c74ff11398f3eb795b7c80b7d296a56675bf7cdb7c30474a), so I guess we need to revert that unwanted sentence change (not sure if something in the edit broke during preparation of that commit).

**Comment by illfated** [comment]
There you go. PR #5567 is now ready for review, comments, and suggestions. Please note that I have not spent any time making any other improvements to this article, in order to make sure the sentence gets restored individually and without any other changes (which could potentially be reverted at a later date).
