### ISSUE TITLE
Dead Link to Windows Defender Application Control (WDAC) Deployment Guide

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/windowsserverdocs#5568]
The Windows Server Security documentation page at https://docs.microsoft.com/en-us/windows-server/security/security-and-assurance has a dead link to the Windows Defender Application Control (WDAC) Deployment Guide. Please fix this.

Steps to reproduce.
1. Go to https://docs.microsoft.com/en-us/windows-server/security/security-and-assurance .
2. Click on link to Windows Defender Application Control (WDAC) Deployment Guide under the Hardening the OS and applications box.
3. Get a 404.

Expected results: Arrive at the Windows Defender Application Control (WDAC) Deployment Guide  page.
Actual results: Get a 404.

**Comment by illfated** [comment]
Thank you for the report, I have confirmed the 404 issue.

Will look into creating a Pull Request to correct the link as you suggested, as soon as I get time to do so.

**Comment by illfated** [comment]
Preliminary search results:
- dead (404) link:
  https://docs.microsoft.com/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-contro
- working link:
  https://docs.microsoft.com/windows/security/threat-protection/windows-defender-application-control/windows-defender-application-control-deployment-guide

Looks like there could have been a change in the URL length management, or creation of a new page URL. Need to inspect some commits to find out what happened.

**Comment by illfated** [comment]
Not that it matters much now, but it looks like the link was broken in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/f281ba060b1767b4f5e35c5cbade3f0c32dd490d while converting the old HTML-based file WindowsServerDocs/security/security-and-assurance.md to the current YML format in [WindowsServerDocs/security/security-and-assurance.yml](https://github.com/MicrosoftDocs/windowsserverdocs/commit/f281ba060b1767b4f5e35c5cbade3f0c32dd490d#diff-a833e56e44ffdc56cda7d8949668e8dc82feca7683a28c7073a1e517d96a21da) .

(See https://github.com/MicrosoftDocs/windowsserverdocs/commit/f281ba060b1767b4f5e35c5cbade3f0c32dd490d#diff-a833e56e44ffdc56cda7d8949668e8dc82feca7683a28c7073a1e517d96a21daR63 for details.)

**Comment by illfated** [comment]
There you go, PR #5572 is now ready for review, comments, and suggestions.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @rossmpersonal,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change was made correcting the link in question a while back and this issue was not closed. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
