### ISSUE TITLE
Event ID 1201 info incorrect

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/windowsserverdocs#5570]
The events table says:

1201 | This event is written each time a user is locked out.Activity ID: %1XML: %2

This is incorrect.  Event 1201 is "The Federation Service failed to issue a valid token"  Maybe it was supposed to be for event 1210.

ref: https://adfshelp.microsoft.com/AdfsEventViewer/GetAdfsEventList

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0238d6f-4073-172e-de62-e2d973d993b7
* Version Independent ID: 3789bcce-bebd-8a9d-c814-45ce6c1bfe47
* Content: [Configure AD FS Extranet Smart Lockout Protection](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-extranet-smart-lockout-protection)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by robinharwood** [comment]
#assign:robinharwood

Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made, although there have been further updates with subsequent releases which supersede the updates in your issue. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
