### ISSUE TITLE
Powershell snippet at the bottom of this page does not add rule for RDP UDP protocol

### ISSUE THREAD

**Issue by IonutDanNica** [MicrosoftDocs/windowsserverdocs#5580]
Ideally the snippet for enabling RDP on a custom port should include the UDP in rule, just like the default windows rule set.

```
$portvalue = 3390
Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "PortNumber" -Value $portvalue 
New-NetFirewallRule -DisplayName 'RDPPORTLatest-TCP-In' -Profile 'Public' -Direction Inbound -Action Allow -Protocol TCP -LocalPort $portvalue 

New-NetFirewallRule -DisplayName 'RDPPORTLatest-UDP-In' -Profile 'Public' -Direction Inbound -Action Allow -Protocol UDP -LocalPort $portvalue 

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13054e70-b770-f803-4596-6d0ab3fe865c
* Version Independent ID: 3e474a79-1129-fdf6-bbd4-a12e0e7ebe27
* Content: [Change the listening port in Remote Desktop](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/change-listening-port)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/change-listening-port.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/change-listening-port.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by illfated** [comment]
Fair point. Would you like to create a Pull Request to add your suggested addition to the code?

**Comment by illfated** [comment]
( ref. #5581 )
