### ISSUE TITLE
OpenSSH key instructions

### ISSUE THREAD

**Issue by Dmole** [MicrosoftDocs/windowsserverdocs#5586]
[Enter feedback here]
"The term 'Repair-AuthorizedKeyPermission' is not recognized as the 
name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if 
a path was included, verify that the path is correct and try again."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH key management for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by illfated** [comment]
Please browse this list of open issue tickets to find similar tickets which might contain some answers to your questions.

I am aware that this OpenSSH key management issue (OpenSSHTools / OpenSSHUtils) is still an unsolved issue in need of being addressed properly. Maybe there is some Win32 OpenSSHUtils development going on, I am uncertain. Feel free to search more for the details, both here on GitHub and elsewhere.

**Comment by Dmole** [comment]
The correct instructions should be 

$acl = Get-Acl C:\ProgramData\ssh\administrators_authorized_keys
$acl.SetAccessRuleProtection($true, $false)
$administratorsRule = New-Object system.security.accesscontrol.filesystemaccessrule("Administrators","FullControl","Allow")
$systemRule = New-Object system.security.accesscontrol.filesystemaccessrule("SYSTEM","FullControl","Allow")
$acl.SetAccessRule($administratorsRule)
$acl.SetAccessRule($systemRule)
$acl | Set-Acl

**Comment by illfated** [comment]
@konstruktoid : Since you know a lot more than me about this topic, may I ask you to take a look and suggest how we should move forward with this ticket?

**Comment by konstruktoid** [comment]
That's a document generating alot of comments, see https://github.com/MicrosoftDocs/windowsserverdocs/pull/4788.
And the above solution using  `Get-Acl` et al was mentioned as a comment here: https://github.com/MicrosoftDocs/windowsserverdocs/pull/4788#issuecomment-687662994

**Comment by illfated** [comment]
Thanks a lot, I have had so much on my mind lately, I almost forgot about your PR and your helpful comments in a lot of the other tickets.

Thank you for taking your time to drop in and leave a comment. I hope and wish that the MS Docs server team will follow up on your PR soon, because that PR may very well close 25 open issue tickets.

Then again, I have no idea what their schedules and priority lists look like.

**Comment by dknappettmsft** [comment]
Thanks for submitting this issue. I have reworked this document to remove or replace parts that are no longer relevant or correct based on this and several other issues raised for this page.

The changes should be visible in around 6-12 hours.

#please-close

**Comment by Dmole** [comment]
@dknappettmsft 

commit

> 409d9dccc8acd7c87774948904cf95b933dceeee

still has

> Repair-AuthorizedKeyPermission

purportedly from 

> OpenSSHUtils

but is it not mentioned

> in the instructions above

as claimed.

#please-open

**Comment by dknappettmsft** [comment]
Hi @Dmole,

That commit was from a couple of days ago (and went live a couple of days ago too) and not what I was referencing above.  Your latest comment was still before the timeframe I gave was up for it being visible - if you happen to refresh the page it's there now :)

**Comment by Dmole** [comment]
Thanks @dknappettmsft ,
maybe next time mention the commit id, or close after push so there is no confusion.
