### ISSUE TITLE
Problem when restoring AD FS Backup

### ISSUE THREAD

**Issue by andrefonsecadeoliveira** [MicrosoftDocs/windowsserverdocs#559]
When trying to restore a backup I run into the folowing error:

**Restore-ADFS : The process cannot access the file 'C:\Windows\ADFS\Microsoft.IdentityServer.Servicehost.exe.config' because it is being used by another process.**

Already tried using ProcessMonitor to see if there was another process using de file but it seems like activity is being generated only by the Restore Script.

Backup is made by the following script:

_$StoragePath = "C:\BACKUP_ADFS\DATA"
$EncryptionPassword = "*************"
$mycreds = New-Object System.Management.Automation.PSCredential ("CGU\app_adfs$")
Import-Module 'C:\Program Files (x86)\ADFS Rapid Recreation Tool\ADFSRapidRecreationTool.dll'
Backup-ADFS -StorageType "FileSystem" -StoragePath $StoragePath -EncryptionPassword $EncryptionPassword -ServiceAccountCredential $mycreds_

_Get-ChildItem $StoragePath | Where-Object {$_.CreationTime -le (Get-Date).AddDays(-35)} | Foreach-Object { Remove-Item $_.FullName -Recurse -Verbose -Force}_

Restore is being attempted by the following commands:

_import-module 'C:\Program Files (x86)\ADFS Rapid Recreation Tool\ADFSRapidRecreationTool.dll'
Restore-ADFS -StorageType "FileSystem" -StoragePath "C:\Temp\Backup" -DecryptionPassword "********" -GroupServiceAccountIdentifier "cgu\app_adfs$" -DBConnectionString "WID" -Force_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a58b49ca-ae39-132e-adbd-6766a8019a89
* Version Independent ID: fdf31266-bc9e-8880-0073-00cf1cad2897
* Content: [AD FS Rapid Restore Tool](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/ad-fs-rapid-restore-tool)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/AD-FS-Rapid-Restore-Tool.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/AD-FS-Rapid-Restore-Tool.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by gregdod** [comment]
Having the exact same issue, I see that it's caused by the ADFS service starting before the file is edited.  We tried stopping the service and disabling it, but it still keeps starting prematurely.  If anyone has a fix for this it would be appreciated.

**Comment by Ramses26** [comment]
Anyone come up with a fix?

**Comment by andrefonsecadeoliveira** [comment]
Thanks!!! After installing the new version the restore was successful!
