### ISSUE TITLE
ObjectNotFound: (Repair-AuthorizedKeyPermission:String) [], CommandNotFoundException

### ISSUE THREAD

**Issue by fanlessfan** [MicrosoftDocs/windowsserverdocs#5591]
[Enter feedback here]
admin@VM2-WINX C:\Users\admin>powershell -c $ConfirmPreference = 'None'; Repair-AuthorizedKeyPermission C:\Users\user1\.ssh\authorized_keys
Repair-AuthorizedKeyPermission : The term 'Repair-AuthorizedKeyPermission' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:30                                                                                                 
+ $ConfirmPreference = 'None'; Repair-AuthorizedKeyPermission C:\Users\ ...                                       
+                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                     
    + CategoryInfo          : ObjectNotFound: (Repair-AuthorizedKeyPermission:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH key management for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by illfated** [comment]
Please see the following pages for related and already discussed OpenSSH issues:
- https://github.com/MicrosoftDocs/windowsserverdocs/issues?q=%221e4b742e-d999-2c1e-a396-dc149f7ac76b%22+is%3Aopen
- #4788 (update OpenSSH key management)

***

- #2747 **A better explanation can be found here**
- #3456 **Misleading title/summary causing search confusion**
- #3806 **OpenSSHUtils is deprecated**
- #4345 **OpenSSHUtils Not Needed**
- #4518 **Unable to configure OpenSSH for public key auth following docs**
- #4598 **Instructions provided ends with an error**
- #4622 **Out-of-date - OpenSSHUtils no longer available.**
- #4634 **More documentation required**
- #4690 **OpenSSHUtils install reference no longer valid**
- #4702 **OpenSSHUtils got unlisted from the PowerShell gallery**
- #4743 **Nope. First example errors out.**
- #4770 **Error when following instructions to install OpenSSHUtils**
- #5000 **Clarification needed**
- #5138 **These instructions do not work on Windows 10 20h2**

**Comment by dknappettmsft** [comment]
Thanks for submitting this issue. I have reworked this document to remove or replace parts that are no longer relevant or correct based on this and several other issues raised for this page.

The changes should be visible in around 6-12 hours.

#please-close
