### ISSUE TITLE
Duplicate reg key

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/windowsserverdocs#5592]
Why does the document say to add the same registry key 3 times? It's in the docs for both 2004 and 1909.
```
add "HKLM\Temp\Software\Microsoft\Windows\CurrentVersion\UserProfileEngagement" /v ScoobeSystemSettingEnabled /t REG_DWORD /d 0 /f
add "HKLM\Temp\Software\Microsoft\Windows\CurrentVersion\UserProfileEngagement" /v ScoobeSystemSettingEnabled /t REG_DWORD /d 0 /f
add "HKLM\Temp\Software\Microsoft\Windows\CurrentVersion\UserProfileEngagement" /v ScoobeSystemSettingEnabled /t REG_DWORD /d 0 /f
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e1dd70b-7121-aba0-9277-dc981f5ccc3e
* Version Independent ID: ea47f1b9-d29a-cc8c-d84d-b37df76ee05f
* Content: [Optimizing Windows 10, Build 2004, for a Virtual Desktop role](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-vdi-recommendations-2004)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-vdi-recommendations-2004.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-vdi-recommendations-2004.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by RAJU2529** [comment]
After merging this PR #5594 , i will edit further to add word , to work commands correctly, because **reg** is missing

**Comment by RAJU2529** [comment]
@Heidilohr , Please look in this PR #5897 . i added  word reg

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @jonwbstr,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change was made a while ago correcting the duplicate entries and this issue was not closed. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
