### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by cdestratis** [MicrosoftDocs/windowsserverdocs#5593]
_To operating Windows Admin Center:_

Should be:

**To operate Windows Admin Center:**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84be3ac8-1a9e-bb18-1070-ad161642890f
* Version Independent ID: e5552651-0676-fce6-b0b5-36be6df9ae64
* Content: [What type of installation is right for you](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/plan/installation-options#installation-supported-operating-systems)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/plan/installation-options.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/plan/installation-options.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by dknappettmsft** [comment]
Hi @cdestratis, thanks for flagging this.  The change has been made and should be visible later today.

#please-close
