### ISSUE TITLE
Possibly wrong description for /P

### ISSUE THREAD

**Issue by karniemi** [MicrosoftDocs/windowsserverdocs#5596]
[Enter feedback here]
The internet(Tm) tells that the /P-option of format works like this: "
Zero every sector on the volume.  After that, the volume will be
                   overwritten "count" times using a different random number each time.
                   If "count" is zero, no additional overwrites are made after 
                   zeroing every sector."

Either the ms doc is wrong or the internet(Tm) is wrong.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9fbdba6-cfee-e68d-e1a9-e97d09f0cfad
* Version Independent ID: 26f12948-5d6d-41c2-21ac-538da6e25f7a
* Content: [format](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/format)
* Content Source: [WindowsServerDocs/administration/windows-commands/format.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/format.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by dknappettmsft** [comment]
Hi @karniemi, thanks for raising this issue. I have updated the description for that parameter and also added a few missing parameters that are newer. The PR should be merged soon and the changes visible later today.

Thanks.

#please-close
