### ISSUE TITLE
Windows commands

### ISSUE THREAD

**Issue by imostafizur** [MicrosoftDocs/windowsserverdocs#5597]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d382ca0-6538-5e1d-3e83-e31c9ab6a911
* Version Independent ID: 11eff296-6158-f89a-4941-8735529183e9
* Content: [Windows commands](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands)
* Content Source: [WindowsServerDocs/administration/windows-commands/windows-commands.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/windows-commands.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by illfated** [comment]
Anything particular you wanted to report regarding this documentation page? Your comment does not contain any text and your ticket title is the same as the page.

Maybe this is just a test from your side, that this ticket could be closed as a test comment?

**Comment by dknappettmsft** [comment]
Hi, I'm changing this to a #pri3 while there isn't any extra info. Thanks.

**Comment by dknappettmsft** [comment]
#reassign:dknappettmsft
