### ISSUE TITLE
Bad

### ISSUE THREAD

**Issue by Karr** [MicrosoftDocs/windowsserverdocs#560]
Does anyone verify what someone writes?  This is all wrong and would only cause frustration.  DO NOT install the AD FS role.  Install the REMOTE ACCESS Role and chose Web Application Proxy option.  Bad author!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51d2d175-77c7-f326-820a-cf1d348b07a7
* Version Independent ID: 4db77ba4-8d91-2510-8ea6-a658c1a0352d
* Content: [Install the Federation Service Proxy Role Service](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/install-the-federation-service-proxy-role-service)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Install-the-Federation-Service-Proxy-Role-Service.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Install-the-Federation-Service-Proxy-Role-Service.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by lizap** [comment]
You are absolutely correct! We've just updated the article - you'll see the corrected steps by end of day 6/19/18. Thanks for raising this issue.
