### ISSUE TITLE
Claim types

### ISSUE THREAD

**Issue by D4-AzIdentity** [MicrosoftDocs/windowsserverdocs#5600]
The claim types here are written with https and should be http.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecd05228-38b5-0e37-8eef-b2f2d801f0f3
* Version Independent ID: 94163f6d-4010-e679-81ef-a33a8397348a
* Content: [Client access claim types in AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/ad-fs-claims-types)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/AD-FS-Claims-Types.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/AD-FS-Claims-Types.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by dknappettmsft** [comment]
Hi, thanks for flagging this.  The claim types were http on this Microsoft blog post too (https://techcommunity.microsoft.com/t5/ask-the-directory-services-team/an-adfs-claims-rules-adventure/ba-p/400036), so I have corrected them in this article. The changes should be visible in the next few hours.

#please-close
