### ISSUE TITLE
Diagnostics folder goes to 404 page in github link

### ISSUE THREAD

**Issue by msuddon** [MicrosoftDocs/windowsserverdocs#5602]
Diagnostics folder goes to 404 page in github link

GitHub
The Microsoft/SDN GitHub Repo has a number of sample scripts and workflows which build on top of these in-box cmdlets. In particular, diagnostic scripts can be found in the **Diagnostics** folder. Please help us contribute to these scripts by submitting Pull Requests.

I believe the link should be: https://github.com/microsoft/SDN/tree/master/Diagnostics

it is currently: https://github.com/Microsoft/sdn/diagnostics

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfbbfba4-3c8c-80ac-c95e-ccb513dee009
* Version Independent ID: 8d1f3a7d-b844-5894-9c44-c878b3b46843
* Content: [Troubleshoot the Windows Server Software Defined Networking Stack](https://docs.microsoft.com/en-us/windows-server/networking/sdn/troubleshoot/troubleshoot-windows-server-software-defined-networking-stack)
* Content Source: [WindowsServerDocs/networking/sdn/troubleshoot/troubleshoot-windows-server-software-defined-networking-stack.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/sdn/troubleshoot/troubleshoot-windows-server-software-defined-networking-stack.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @AnirbanPaul
* Microsoft Alias: **anpaul**

**Comment by dknappettmsft** [comment]
Hi @msuddon, thanks for logging this.  I've changed the URL and the change should be live in a couple of hours.

#please-close
