### ISSUE TITLE
NET Framework 4.8 or a later update is already installed on this computer

### ISSUE THREAD

**Issue by NandC** [MicrosoftDocs/windowsserverdocs#5603]
On Windows Server 2012 R2 Standard Edition

While installing .NET Framework 4.8 Setup
gives error - NET Framework 4.8 or a later update is already installed on this computer

Last framework installed was 4.5, and we are trying to install Runtime 4.8 on top of it

**Comment by YoXpertguyZ** [comment]
I also need help with this please

**Comment by NandC** [comment]
Workaround is to install dev-pak/sdk

**Comment by YoXpertguyZ** [comment]
Can you please send a link thank you

**Comment by NandC** [comment]
Link for Dev-pack
https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-developer-pack-offline-installer
