### ISSUE TITLE
I just got this from chkdsk on Win 10 as Admin in  a cold boot into WinRE:: "Failed to transfer logged messages to the event log with status 6."

### ISSUE THREAD

**Issue by dbreed53** [MicrosoftDocs/windowsserverdocs#5606]
It is not something I am motivated to figure out, because all the onscreen reports show NO ISSUES.
Although the webpage does all the other details about chkdsk that I've known since it was introduced, this is the first time I ever got a report like that ends with a Status #.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e39de773-2483-f94c-45aa-32b6af9775a1
* Version Independent ID: 03ba7ec3-9c97-5572-3e41-9ffd0ce916f0
* Content: [chkdsk](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/chkdsk)
* Content Source: [WindowsServerDocs/administration/windows-commands/chkdsk.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/chkdsk.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @dbreed53,

Thanks again for contacting Microsoft. We value your feedback.

As we understand it, you're describing a problem with the product itself and not with the product documentation. If there are any issue(s) within the content, please let us know.

To get assistance or support for your product issue, we recommend that you engage with the product community or open a ticket with Microsoft Support. For more information, see [Contact Microsoft Support](https://support.microsoft.com/ContactUs).

We will now be closing this. Thank you and have a most pleasant day. #please-close
