### ISSUE TITLE
"<command1>&&<command2>&&<command3>"

### ISSUE THREAD

**Issue by dev-hari** [MicrosoftDocs/windowsserverdocs#5607]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0df94452-999b-43a0-be42-722fbabedaf3
* Version Independent ID: 84206d79-507f-b562-9d3f-cc3683b7abe6
* Content: [cmd](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cmd)
* Content Source: [WindowsServerDocs/administration/windows-commands/cmd.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/cmd.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by dknappettmsft** [comment]
Hi, please can you add a comment what it is about this page that you would like to provide feedback on? In the meantime, I'll change this to a #pri3. Thanks.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @dev-hari,

Thanks again for contacting Microsoft. We value your feedback. A documentation change has been made providing an example on multiple command usage. Changes will be live after the next business day, and we'll will be closing this as resolved. Thank you and have a most pleasant day. #please-close
