### ISSUE TITLE
no match with code 

### ISSUE THREAD

**Issue by jnneelesh** [MicrosoftDocs/windowsserverdocs#5608]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4866bff-5947-4b24-7958-94a8164b814a
* Version Independent ID: 3d5611d1-df23-90de-cc1b-81862d2f39e4
* Content: [Build a web application using OpenID Connect with AD FS 2016 and later](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/enabling-openid-connect-with-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/enabling-openId-connect-with-ad-fs.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/enabling-openId-connect-with-ad-fs.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Mentioned article has been either renamed, moved, or absorbed into another article. Unable to verify or make any changes. Closing thread.
#please-close
