### ISSUE TITLE
documentation and code is different altogether 

### ISSUE THREAD

**Issue by jnneelesh** [MicrosoftDocs/windowsserverdocs#5609]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7537a789-92aa-2b04-30bf-028008948c62
* Version Independent ID: d07f261b-29af-74af-f5a6-b4f93aaf5bee
* Content: [Customize claims to be emitted in id_token when using OpenID Connect or OAuth with AD FS 2016 or later](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/custom-id-tokens-in-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/Custom-Id-Tokens-in-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/Custom-Id-Tokens-in-AD-FS.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @anandyadavMSFT
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Mentioned article has been either renamed, moved, or absorbed into another article. Unable to verify or make any changes. Closing thread.
#please-close
