### ISSUE TITLE
Document content and accuracy is... A bit rubbish, really.

### ISSUE THREAD

**Issue by Cottroad** [MicrosoftDocs/windowsserverdocs#5610]
[Enter feedback here]

This doc says it's relevant to Server 2019... I tried using it to install RDS and activate a Licensing feature on a Server 2019...

The section of this document pertaining to describing how to install Remote Desktop Services is thoroughly flawed from the second bullet point (the one after "log into your server") - there is no such thing as "Roles Summary" in Server Manager. Clicking on Manage then "Add Roles and Features" opens what I expect to be the same wizard, but the instructions diverge very quickly from what is available on a server in this wizard. 

All in all, this article gets zero stars out of, well, whatever the scale is because it's utterly useless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2499f6d6-b28d-d46b-ea9d-3c9dd54fee7c
* Version Independent ID: cd210491-0f3a-1b60-c739-f74bd58daae4
* Content: [Activate the Remote Desktop Services license server](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-activate-license-server)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-activate-license-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-activate-license-server.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
#assign:HeidiLohr

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey Cottroad,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made updating the steps outlined and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
