### ISSUE TITLE
Check the permissions of the MachineKeys folder: Can't reset permissions

### ISSUE THREAD

**Issue by L1ttl3J1m** [MicrosoftDocs/windowsserverdocs#5614]
Attempting to modify the permissions on this folder gives a series of about 20 errors;

"An error occurred while applying security information to
     ..\LongStringOfHex...
Failed to enumerate objects in the container. Access is denied."

So this step does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 420f2431-a31d-c952-eec9-47399399e151
* Version Independent ID: c00b4f63-1ddf-27b5-835b-35f7d6d80484
* Content: [General Remote Desktop connection troubleshooting](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/troubleshoot/rdp-error-general-troubleshooting)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/troubleshoot/rdp-error-general-troubleshooting.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/troubleshoot/rdp-error-general-troubleshooting.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **delhan**

**Comment by IngridAtMicrosoft** [comment]
Question has been routed to Q&A. Please track it there. 
https://docs.microsoft.com/en-us/answers/questions/621142/check-the-permissions-of-the-machinekeys-folder-ca.html
#please-close

**Comment by L1ttl3J1m** [comment]
It was a statement, not a question.

**Comment by IngridAtMicrosoft** [comment]
@L1ttl3J1m Thank you.  I have reopened the issue.
