### ISSUE TITLE
Microsoft Platform Crypto Provider

### ISSUE THREAD

**Issue by anspa** [MicrosoftDocs/windowsserverdocs#5622]
Configure the server certificate with the required cryptography setting:

Open Certificate Templates.
In the details pane, right-click the certificate template that you want to change, and then click Properties.
Click the Cryptography tab and make sure to configure the following:
**Provider Category: Key Storage Provider**
Algorithm Name: RSA
**Providers: Microsoft Platform Crypto Provider**
Minimum key size: 2048
Hash Algorithm: SHA2
Click Next.

Using Microsoft Platform Crypto Provider requires TPM by default. Is this really the minimun requirement for the server certificate when EAP-TLS is implemented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2237d85b-4b60-02bf-0ce2-09d803a75186
* Version Independent ID: ff569ede-822d-1d39-b233-a66a3541d32a
* Content: [Configure Certificate Templates for PEAP and EAP Requirements](https://docs.microsoft.com/en-us/windows-server/networking/technologies/nps/nps-manage-cert-requirements)
* Content Source: [WindowsServerDocs/networking/technologies/nps/nps-manage-cert-requirements.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/nps/nps-manage-cert-requirements.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey anspa,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change was made correcting that section and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
