### ISSUE TITLE
Incorrect WID federation server number limitation

### ISSUE THREAD

**Issue by RamblingPSTech** [MicrosoftDocs/windowsserverdocs#5623]
The line: 
`A WID farm has a limit of five federation servers. For more information, see AD FS Deployment Topology Considerations.`

should read as
`A WID farm has a limit of 30 federation servers. For more information, see AD FS Deployment Topology Considerations.`

---

Ref: [AD FS Deployment Topology Considerations](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/design/ad-fs-deployment-topology-considerations)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db66dfd7-8981-bad9-ebdd-24edd18f1de5
* Version Independent ID: dfd3d9fa-c827-a301-6818-7f5f812cbf39
* Content: [AD FS Federation Server Farm Using WID](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/design/federation-server-farm-using-wid-2012)
* Content Source: [WindowsServerDocs/identity/ad-fs/design/Federation-Server-Farm-Using-WID-2012.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/design/Federation-Server-Farm-Using-WID-2012.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @RamblingPSTech,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation update has been made and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
