### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by cmaneiro** [MicrosoftDocs/windowsserverdocs#5624]
the link in 

You can also access the information on all services detailed in this article by viewing the attached Microsoft Excel spreadsheet: **Guidance on Disabling System Services on Windows Server 2016 with Desktop Experience)**

is broken for the article 

https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server.md

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey cmaneiro,

Thanks again for contacting Microsoft. We value your feedback. 

Verified link is active --> [Guidance on disabling system services on Windows Server 2016 with Desktop Experience](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server.md).

- Excel spreadsheet link was removed from current documentation. 
- Excel spreadsheet link was removed from [Tech Community post 701058](https://techcommunity.microsoft.com/t5/microsoft-security-baselines/guidance-on-disabling-system-services-on-windows-server-2016/ba-p/701058).
  - Source location for spreadsheet is the same for both articles and this resource is unavailable.

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
