### ISSUE TITLE
Missing - Updates for version 1.2.1953

### ISSUE THREAD

**Issue by DavidTaig** [MicrosoftDocs/windowsserverdocs#5630]
As MSRDC 1.2.1953 is already installed in customers environments, Whatsnew can't disappear. Please add back.

![image](https://user-images.githubusercontent.com/38142528/122479196-04962380-d00e-11eb-8776-8eb739d8be07.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f43e914-5ede-6f18-2fbc-165f3386f7cb
* Version Independent ID: a9489295-572d-ff60-6bff-a44390ac4031
* Content: [What's new in the Windows Desktop client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop-whatsnew)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop-whatsnew.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop-whatsnew.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey DavidTaig,

Windows stand-alone client release 1.2.1953 updates can be found in its new location at:

- https://learn.microsoft.com/en-us/azure/virtual-desktop/whats-new-client-windows

Microsoft Store version updates can be found at:

- https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windows-whatsnew

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
