### ISSUE TITLE
Wrong details yet again...  

### ISSUE THREAD

**Issue by kolonuk** [MicrosoftDocs/windowsserverdocs#5640]
Is it surprising that these instructions for adding a computer to a domain no longer apply, because Microsoft have yet again moved shit around?  If Microsoft didn't keep changing things to the ludicrous "Settings", life would be sooo much simpler for tech support.

Just, "why?".  Thats all we want to know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3331f737-d4d5-8b05-e5e2-57ba67903f6b
* Version Independent ID: 33e0848c-3070-2367-8d21-28f3e05f5850
* Content: [Join a Computer to a Domain](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/join-a-computer-to-a-domain)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Join-a-Computer-to-a-Domain.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Join-a-Computer-to-a-Domain.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Karl-WE** [comment]
@kolonuk the reason is simple. Because they did not manage to have it consistent over all versions and SKU.
Windows Server 2022 LTSC does not have the same options in settings to join a computer as a Windows 10 client has.

to ease things I use Add-Computer PowerShell to add computers to a domain.

**Comment by Xelu86** [comment]
Hey @kolonuk,

Thanks again for contacting Microsoft. We value your feedback.

A documentation change has been made to reflect how to join a standard computer to a domain along with the subtle change on how this can be performed when joining a server to a domain. These changes will be live after the next business day. 

As our products and services continuously improve, features may be added, removed, upgraded, or shifted to different locations based on technological advancements and user feedback. Some may not enjoy the outcome as to why the developers made certain decisions, but in fairness, this can also be said about several non-Microsoft products and services.

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
