### ISSUE TITLE
Missing `wevtutil im` options

### ISSUE THREAD

**Issue by zooba** [MicrosoftDocs/windowsserverdocs#5642]
This page is missing the options and description of the `wevtutil im` command (which is arguably the most important, as this is the main way used to install new event manifests).

From running `wevtutil im /?`:

```
Install event publishers and logs from manifest.

Usage:

wevtutil { im | install-manifest  } <MANIFEST> [/OPTION:VALUE [/OPTION:VALUE] ...]

<MANIFEST>
File path to an event manifest. All publishers and logs defined in the manifest
will be installed. To learn more about event manifests and using this option,
consult the Windows Eventing SDK on Microsoft Developers Network (MSDN) at
http://msdn.microsoft.com.

Options:

You can use either the short (for example, /rf) or long (for example,
/resourceFilePath) version of the option names. Options and their values are not
case-sensitive.

/{rf | resourceFilePath}:VALUE
ResourceFileName attribute of the Provider Element in the manifest to be
replaced.
The VALUE should be the full path to the resource file.

/{mf | messageFilePath}:VALUE
MessageFileName attribute of the Provider Element in the manifest to be replaced.
The VALUE should be the full path to the message file.

/{pf | parameterFilePath}:VALUE
ParameterFileName attribute of the Provider Element in the manifest to be replaced.
The VALUE should be the full path to the parameter file.

Example:

The following example installs publishers and logs from the myManifest.man
manifest file.

wevtutil im myManifest.man /rf:^%systemroot^%/System32/wevtutil.exe
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac36ce81-c27b-9390-0046-40fce407d810
* Version Independent ID: 654871b9-01cf-f163-e03b-c1361609713f
* Content: [wevtutil](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/wevtutil)
* Content Source: [WindowsServerDocs/administration/windows-commands/wevtutil.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/wevtutil.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @zooba,

Thanks again for contacting Microsoft. We value your feedback.

A documentation change was recently made adding the 3 sub-parameters for the `/im` switch and will be live after the next business day. We will now be closing this thread.

Thank you and have a most pleasant day. #please-close
