### ISSUE TITLE
Document `copy` command exit codes

### ISSUE THREAD

**Issue by Eli-Black-Work** [MicrosoftDocs/windowsserverdocs#5645]
I think it would be nice to document the exit codes for the `copy` command, like is already done with [xcopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/xcopy#:~:text=exit%20codes%20for%20xcopy) and [robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy#exit-return-codes) 🙂

In particular, I had to do some experimenting to see if `copy` would return an error code if it didn't find any files to copy. (e.g. `copy *.nonexistant C:\example\`)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff097c0e-ea9f-9d7c-7900-d8c0be602d5d
* Version Independent ID: 8b17895a-ddd8-1737-9e7d-8deaa69d5b0f
* Content: [copy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/copy)
* Content Source: [WindowsServerDocs/administration/windows-commands/copy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/copy.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Bosch-Eli-Black** [comment]
Just following up on this 🙂

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey Eli-Black-Work,

Having the return codes for the `copy` command into this document wouldn't add much value as its operations are quite basic:

- **0:** Copy completed successfully
- **1:** Copy didn't complete successfully

There is no indication/reason of _why_ it fails with **1** as any failure of _any_ kind throws a **1**. Comparing to `xcopy` or `robocopy` return codes, they are more detailed in indicating reasons for failure. We encourage you to use either `xcopy` or `robocopy` for these operations if failures are occurring to identify them.

At this time, we are not going to update this documentation. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
