### ISSUE TITLE
netsh portproxy reset description possibly incorrect

### ISSUE THREAD

**Issue by wilsonzlin** [MicrosoftDocs/windowsserverdocs#5651]
The description for the [netsh interface portproxy reset](https://docs.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh-interface-portproxy#reset) command appears to be incorrect, and appears to refer to another command, possibly `netsh interface ipv6 reset`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3b40a3-1d83-9dab-d06b-784944580ddb
* Version Independent ID: 0be7bac0-6fc9-ce45-92dc-81d612ae8204
* Content: [Netsh commands for interface portproxy](https://docs.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh-interface-portproxy#reset)
* Content Source: [WindowsServerDocs/networking/technologies/netsh/netsh-interface-portproxy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/netsh/netsh-interface-portproxy.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by craigcaseyMSFT** [comment]
Hello @wilsonzlin,

Thanks for contacting Microsoft. We value your feedback.

Documentation changes have been made to clarify and acknowledge this issue. The doc changes will be live after the next business day.

Thank you again and have a most pleasant day.
#please-close
