### ISSUE TITLE
na update windows 10 diversen programma's automatisch verijderd. hoe kan dit?

### ISSUE THREAD

**Issue by aad23** [MicrosoftDocs/windowsserverdocs#5652]
[Voer hier feedback in]

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 9acf4b99-84e9-0f78-6e26-16c9721bf927
* Version Independent ID: 3b9ba790-adbd-68c8-726b-033cb7a4a019
* Content: [Resolve Windows activation error codes](https://docs.microsoft.com/nl-nl/windows-server/get-started/activation-error-codes)
* Content Source: [WindowsServerDocs/get-started/activation-error-codes.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/activation-error-codes.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **kaushika**

**Comment by IngridAtMicrosoft** [comment]
GitHub issues for this repo are for reporting problems with documentation.  Please open a support ticket. #please-close
