### ISSUE TITLE
Error in the article please fix

### ISSUE THREAD

**Issue by bencorley** [MicrosoftDocs/windowsserverdocs#5659]
The following sentence is wrong:
Members of this group can **administer domain servers**.

Should be **Administer Domain Controllers**. I double checked this one. 

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1329c1d1-c6bd-6005-39e3-f04763735ae4
* Version Independent ID: 0915e4bb-7383-b971-9f9b-7aba95ab501c
* Content: [Appendix B - Privileged Accounts and Groups in Active Directory](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/appendix-b--privileged-accounts-and-groups-in-active-directory)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-B--Privileged-Accounts-and-Groups-in-Active-Directory.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-B--Privileged-Accounts-and-Groups-in-Active-Directory.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by craigcaseyMSFT** [comment]
Hello @bencorley,

Thanks for contacting Microsoft. We value your feedback.

Documentation changes have been made to clarify and acknowledge this issue. The doc changes will be live after the next business day.

Thank you again and have a most pleasant day.
#please-close
