### ISSUE TITLE
Additions to the Doc

### ISSUE THREAD

**Issue by Omzig** [MicrosoftDocs/windowsserverdocs#566]
It would be helpful if there were PowerShell commands listed out that sets the values to disabled so that we can disable everything but TLS 1.2 quickly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38fcd9dd-91c8-e79b-5f4d-28a435a8ada8
* Version Independent ID: 0d79a0c8-0b73-c783-4d5c-b107d24acf55
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Service: **unspecified**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by PastaManana** [comment]
You need Server 2016 or later to be able to do much with the TLS PowerShell module.

**Comment by PastaManana** [comment]
In the current "applies to" list, I do not see Server 2012 nor Server 2012 R2 and it would seem that they should be included in the list as well.

**Comment by Justinha** [comment]
@PastaManana Thanks for pointing out that omission. The Applies to values are actually intended to only list the current release. Then inline within the text, I added which release introduced the setting.
