### ISSUE TITLE
Incorrect command for adding REG_MULTI_SZ 

### ISSUE THREAD

**Issue by SaurabhGautam** [MicrosoftDocs/windowsserverdocs#5661]
The correct example to add REG_MULTI_SZ  is 
`reg add HKLM\Software\MyCo /v MRU /t REG_MULTI_SZ /d fax\0mail\0`

instead of 

`reg add HKLM\Software\MyCo /v MRU /t REG_MULTI_SZ /d fax\0mail\0\0`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd817f1d-e494-af38-4a10-86360d63c195
* Version Independent ID: 11fcbf91-6c28-9ae8-045a-35ea97444dfe
* Content: [reg add](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/reg-add)
* Content Source: [WindowsServerDocs/administration/windows-commands/reg-add.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/reg-add.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @SaurabhGautam,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting this issue and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
