### ISSUE TITLE
How to troubleshoot when export virtual machine fails

### ISSUE THREAD

**Issue by jeffsilverm** [MicrosoftDocs/windowsserverdocs#5663]
[Enter feedback here]
Insofar as I can tell, I am following instructions to export a virtual machine.  I went through the process as described here with the VM running, with the VM stopped.  In all cases, I get the following error: "Export failed for virtual machine 'jeffs_VM1'".  When I ask for more details, I get the message "Export failed for virtual machine 'jeffs_VM1' {A GUID} with error 'The system cannot find the file specified.' (0x80070002)".

How do I troubleshoot this problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acc00093-1f29-7e3b-ab30-9e6966598390
* Version Independent ID: bd281aaf-4e09-73a4-95a0-873ab4cc5de2
* Content: [Export and import virtual machines](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/deploy/export-and-import-virtual-machines)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/deploy/Export-and-import-virtual-machines.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/deploy/Export-and-import-virtual-machines.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by jeffsilverm** [comment]
The way I (partly) solved the problem was to search the entire file system for any files named "*jeff_VM1*".  I found the files.  I still haven't quite figured out how to export them.

**Comment by Xelu86** [comment]
#assign:xelu86
