### ISSUE TITLE
Excel file link is broken on the link

### ISSUE THREAD

**Issue by elcorewin** [MicrosoftDocs/windowsserverdocs#5664]
Unable to download the excel file on the page, could this be fixed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d867f27-5abb-be93-6bad-13eaa2e57ca6
* Version Independent ID: 8e8d603f-f93f-57f2-dec2-098433885624
* Content: [Security guidelines for system services in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server)
* Content Source: [WindowsServerDocs/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @nirb
* Microsoft Alias: **nirb**

**Comment by An-dir** [comment]
I guess the link was removed so... no broken link anymore :D 
the missing excel file is still a problem, but you may use powershell to parse the data to a object and then export a csv

```
$fields = "ServiceTitle","ServiceName","Description","Installation","StartupType","Recommendation","Comments"
$RequestData = Invoke-WebRequest -UseBasicParsing -Uri https://raw.githubusercontent.com/MicrosoftDocs/windowsserverdocs/main/WindowsServerDocs/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server.md
$regexString = '(?m)^##\s(?<ServiceTitle>.*)$(?s).*?\*\*Service name\*\* \| (?<ServiceName>.*?(?=\s+\|)).*?\*\*Description\*\* \| (?<Description>.*?(?=\s+\|)).*?\*\*Installation\*\* \| (?<Installation>.*?(?=\s+\|)).*?\*\*Startup type\*\* \| (?<StartupType>.*?(?=\s+\|)).*?\*\*Recommendation\*\* \| (?<Recommendation>.*?(?=\s+\|)).*?\*\*Comments\*\* \| (?<Comments>.*?(?=\s+\|))'
$out = $RequestData.Content |
    Select-String -Pattern $regexString -AllMatches |
        Foreach-Object { $_.Matches | Foreach-Object {
            $hash = [ordered]@{}
            foreach ($field in $fields) {
                $hash.$field = $_.Groups.where{$_.Name -eq $field}.Value}
                [pscustomobject]$hash
            }
        };
$out | Export-Csv -Path file.csv -Delimiter ";" -NoTypeInformation
 .\file.csv
```
This PowerShell code generates an object with all the services in the GitHub version of the Microsoft website and then exports and opens a CSV in excel if it is installed

any other useful (integrated / automated) export of data would be appreciated

thanks to AdminOfThings at https://stackoverflow.com/questions/70696733/can-someone-optimize-my-net-regex-for-powershell-parsing-a-table-with-errors

**Comment by dksimpson** [comment]
Hello @elcorewin,

Thanks for contacting Microsoft; we value your feedback. It appears that this issue has been addressed.
If you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.

#please-close
