### ISSUE TITLE
Update-AdfsArtifactDatabasePermission not available with Server 2019

### ISSUE THREAD

**Issue by ThomasKoflerSOS** [MicrosoftDocs/windowsserverdocs#5665]
The cmdlet is not available with ADFS 2019: Update-AdfsArtifactDatabasePermission
and probably not needed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0238d6f-4073-172e-de62-e2d973d993b7
* Version Independent ID: 3789bcce-bebd-8a9d-c814-45ce6c1bfe47
* Content: [Configure AD FS Extranet Smart Lockout Protection](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-extranet-smart-lockout-protection#additional-features-in-ad-fs-2019)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Extranet-Smart-Lockout-Protection.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by robinharwood** [comment]
#assign:robinharwood

Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. The requested updates have not been made, although there have been further updates with subsequent releases which supersede the updates in your issue. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
