### ISSUE TITLE
[Data Deduplication interoperability] Uservoice links no longer work

### ISSUE THREAD

**Issue by 0x53A** [MicrosoftDocs/windowsserverdocs#5667]
Under the section [Unsupported](https://docs.microsoft.com/en-us/windows-server/storage/data-deduplication/interop#unsupported) there are two uservoice links, neither works ``This site is not currently active``.

For what it's worth, I am struggling with duplicated build artefacts on my developer machine, and having NTFS deduplication on the client os would solve a lot of my issues. Which is why I wanted to "upvote" this request.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbca43fe-2459-af79-0ab0-6c598217239f
* Version Independent ID: 7e824aea-3911-d256-4002-d62711005efd
* Content: [Data Deduplication interoperability](https://docs.microsoft.com/en-us/windows-server/storage/data-deduplication/interop)
* Content Source: [WindowsServerDocs/storage/data-deduplication/interop.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/data-deduplication/interop.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @wmgries
* Microsoft Alias: **wgries**

**Comment by Joachim-Otahal** [comment]
There is no (official) deduplication for the client OS. Some fans "steal" that feature from the current server build to the same client build, but it may break with the next upgrade or at any time between. So you either use Server 2019 / 2022 locally on your machine, or you set up a Server 2012 R2/2016/2019/2022, store your data there and deduplicate there. Whether you use normal file share access or the iSCSI method to connect the server data is up to you. The former is easier to set up, the latter might allow higher compression but requires the "VDS" deduplication template and it behaves like a local disk.
IF you have enough RAM you can run that deduplicating server locally as VM :).

**Comment by IngridAtMicrosoft** [comment]
Addressed. #please-close
