### ISSUE TITLE
Make the string administrators_authorized_keys bold

### ISSUE THREAD

**Issue by Charlweed** [MicrosoftDocs/windowsserverdocs#5672]
[Enter feedback here]

Make the string administrators_authorized_keys bold, and explicitly point out that it does not have the same name as the per-user file authorized_keys.
It is easy to miss the fact that users must NOT name the file authorized_keys. And openssh's failure to authorize is silent.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH key management for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by robinharwood** [comment]
Hi @Charlweed,

Thanks for your dedication to our documentation. With regard to the formatting style, the current article conforms to our style guides and voice principles, so we make a change to this. However, we have updated the article to address multiple GitHub issues. This update should help with the clarity in the wording used, specifically in the note box. The updated article should be live by tomorrow. 

Thanks

#please-close
