### ISSUE TITLE
How do i set the ChrootDirectory for a user from Active Directory

### ISSUE THREAD

**Issue by tvikram1258** [MicrosoftDocs/windowsserverdocs#5675]
HI Team,
Windows 2016 (SFTP configured)
Windows 2008 R2 (Active directory)

1. I have configure the Open ssh on windows 2016 server
2. its added to Domain control peon.com
3. SFTP is the main folder, in NTFS permissions i have given Users group from local where i have integrated the Domain users of AD to access
4. Inside this SFTP folder i have created the sub folders with DEV, Prod, Test... directory.
5. i removed the disabled the inheritance on them and add the Devuser to DEV folder and soon.
6.Now i am able to connect to the dev folder 
BUT
when is login to SFTP with devuser i am not able to login to that particular folder instead of it i need to use cd devuser then i am able to copy or paste.
Can you help me in this .

Subsystem   sftp  sftp-server.exe "c:\SFTP"

Match Group users
ChrootDirectory "c:\SFTP"
AllowTcpForwarding  no
ForceCommand internal-sftp
![SFTP to directory](https://user-images.githubusercontent.com/16240698/124360852-a5f5ba00-dc49-11eb-9f38-df3fe78baf0e.PNG)

**Comment by Joachim-Otahal** [comment]
Wrong place to ask. This is only for windowsserverdocs. Your case requires someone to check directly on your machine what is going on or what is wrong since a lot of details are missing.

**Comment by tvikram1258** [comment]
Thanks For The Update

**Comment by robinharwood** [comment]
Hi @tvikram1258
