### ISSUE TITLE
Unsure about the method used to enable TLS

### ISSUE THREAD

**Issue by Tarjei-stavanger** [MicrosoftDocs/windowsserverdocs#5677]
It looks like you are both enabling and disabling the protocols in the examples. That is the example is setting both the Enabled and DisabledByDefault keys for a protocol.

I have used IISCrypto 3.2 (https://www.nartac.com/Products/IISCrypto) to disable and enable protocols and it does not disable a protocol that is enabled. In other words, it does what I expect it to do.

If I was writing this documentation, I would create a text which could be saved into a .reg file to provide the best practice setting. That is : Disable TLS 1.0 and TLS 1.1 while enabling TLS 1.2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd180142-4c19-8abc-ecce-e4c7e5ac8951
* Version Independent ID: fc5bba87-afad-1729-8f7e-333c73188b73
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by RAJU2529** [comment]
@Tarjei-stavanger . best way is to create text file  save as  .reg .

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @Tarjei-stavanger,

Thanks again for contacting Microsoft. We value your feedback. 

We will consider the addition of `.reg` files for the examples in this documentation as it has already gone through several updates. This thread will now be closed. Thank you and have a most pleasant day. #please-close
