### ISSUE TITLE
Correction needed to: Azure Virtual Desktop has been renamed to Azure Virtual Desktop

### ISSUE THREAD

**Issue by neilslater123** [MicrosoftDocs/windowsserverdocs#5679]
The page says "Azure Virtual Desktop has been renamed to Azure Virtual Desktop"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f43e914-5ede-6f18-2fbc-165f3386f7cb
* Version Independent ID: a9489295-572d-ff60-6bff-a44390ac4031
* Content: [What's new in the Windows Desktop client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop-whatsnew)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop-whatsnew.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop-whatsnew.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey neilslater123,

Thanks again for contacting Microsoft. We value your feedback. 

We're closing this thread as the 'What's New?' pages for RDS have been moved to:

- https://learn.microsoft.com/en-us/azure/virtual-desktop/whats-new-client-windows (Standalone).
- https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windows-whatsnew (Windows Store).

The new doc set has been updated to reflect the most current changes as of this date & time.

Thank you and have a most pleasant day. 
#please-close
