### ISSUE TITLE
Please more Information on "Storage bus cache is now available for standalone servers"

### ISSUE THREAD

**Issue by Joachim-Otahal** [MicrosoftDocs/windowsserverdocs#5680]
Hello Microsoft,

there is absolutely no information about how to use the cmdlets of
Get-Command -Module StorageBusCache
Some of those listed there already exist in Server 2019, like Get-StorageBusDisk
I would love to test the Storage Bus Cache, but even when related to StorageSpacesDirect for Server 2019/2016, the documentation is not enough.

How can it be used? The first test would be the usual 2 SSD (or mediatype SCM) + 2 HDD,

kind regards,

Joachim Otahal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e65f261-8e8d-ddb6-02e5-0c24d0d835fc
* Version Independent ID: 46099ff5-4b3c-8097-e7e0-b2bdb79a38ff
* Content: [What's new in Windows Server 2022](https://docs.microsoft.com/en-us/windows-server/windows-server-2022/get-started/whats-new?source=docs#)
* Content Source: [WindowsServerDocs/windows-server-2022/get-started/whats-new.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/windows-server-2022/get-started/whats-new.md)
* Product: **windows-server**
* GitHub Login: @dknappettmsft
* Microsoft Alias: **daknappe**

**Comment by dknappettmsft** [comment]
Hi @Joachim-Otahal, there is an article coming for this soon, please bear with us.

**Comment by dknappettmsft** [comment]
#pri3

**Comment by Joachim-Otahal** [comment]
Thank you for that fast reply!

**Comment by Joachim-Otahal** [comment]
BTW: I am hoping that it would REALLY use a given part of the SSD / SCM (aka NVME) as cache. Since this Server 2019 line (real world example 2* 1 TB SSD + 2 * 16 TB HDD) does not actually use 150 GB of SSD as cache as it looks like on the command line.
`New-VirtualDisk -FriendlyName Tiered-Vdisk-D -StoragePoolFriendlyName "Pool-D" -StorageTiers (Get-StorageTier -FriendlyName SSDTier-D),(Get-StorageTier -FriendlyName HDDTier-D) -StorageTierSizes 627GB,14900GB -WriteCacheSize 150GB`
So when the new option is available I am among the first to test this virtual and then in real. In the ideal world it would use the existing Stoage Space and apply the cachesize as given above, but in reality I expect I have to build a new vdisk, maybe even an new pool. Which is fine by me as long as it works.

**Comment by dknappettmsft** [comment]
Hi @Joachim-Otahal, this article has now been published.

#please-close

**Comment by Joachim-Otahal** [comment]
Link: https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/storage-spaces-storage-bus-cache

**Comment by Joachim-Otahal** [comment]
Does not seem to work in a virtual test environment, see here:
https://github.com/MicrosoftDocs/windowsserverdocs/issues/5761
