### ISSUE TITLE
UserVoice links lead to 404 not found errors

### ISSUE THREAD

**Issue by yllekz** [MicrosoftDocs/windowsserverdocs#5686]
Many dead links on this page leading to now-defunct UserVoice feedback sites.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40cb194b-0a55-714a-96ba-c28287e6e18c
* Version Independent ID: 44a152a9-63b7-3d29-03c5-4af03950c1ff
* Content: [Manage Servers with Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/manage-servers)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/use/manage-servers.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/use/manage-servers.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by Xelu86** [comment]
#assign:xelu86
