### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by kilasuit** [MicrosoftDocs/windowsserverdocs#5689]
the link -https://technet.microsoft.com/library/mt589702.aspx - is a dead link
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 284d419d-f0b5-cfa0-8509-0dfc93fb37b6
* Version Independent ID: d3e5b827-3071-3df7-cdb4-1b3275c3fb92
* Content: [Cluster Operating System Rolling Upgrade](https://docs.microsoft.com/en-us/windows-server/failover-clustering/Cluster-Operating-System-Rolling-Upgrade)
* Content Source: [WindowsServerDocs/failover-clustering/Cluster-Operating-System-Rolling-Upgrade.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/Cluster-Operating-System-Rolling-Upgrade.md)
* Product: **windows-server**
* Technology: **failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by ejsiron** [comment]
submitted pr to fix: https://github.com/MicrosoftDocs/windowsserverdocs/pull/5690

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Closing GH issue as link was fixed in [#5690](https://github.com/MicrosoftDocs/windowsserverdocs/pull/5690).
#please-close
