### ISSUE TITLE
Hi, the link to the "Service-management-WS2016.xlsx" file is no more valid. Where can I find this file?

### ISSUE THREAD

**Issue by LucaAnsa** [MicrosoftDocs/windowsserverdocs#5692]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d867f27-5abb-be93-6bad-13eaa2e57ca6
* Version Independent ID: 8e8d603f-f93f-57f2-dec2-098433885624
* Content: [Security guidelines for system services in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server)
* Content Source: [WindowsServerDocs/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @nirb
* Microsoft Alias: **nirb**

**Comment by dksimpson** [comment]
Hello @LucaAnsa,

Thanks for contacting Microsoft; we value your feedback. It appears that this issue has been addressed.
If you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.

#please-close
