### ISSUE TITLE
Detailed descriptions for robocopy "xn" and "xo" flags (exclude new and exclude old) appear to be reversed

### ISSUE THREAD

**Issue by JimNim** [MicrosoftDocs/windowsserverdocs#5697]
[Enter feedback here]

Detailed descriptions for robocopy "xn" and "xo" flags (exclude new and exclude old) appear to be reversed:

<html>
<body>

/xn | Excludes existing files newer than the copy in the source directory.
-- | --
/xo | Excludes existing files older than the copy in the source directory.

</body>
</html>

Natural interpretation of this language:
 - XN: excludes [destination] files [that are] newer than the copy in the source directory
 - XO: excludes [destination] files [that are] older than the copy in the source directory

Actual functionality: 
 - XN: robocopy excludes source directory files newer than the destination files
 - XO: robocopy excludes source directory files older than the destination files

The descriptions sound like the "oldness" or "newness" of the destination file is what determines exclusion, when in fact it is the oldness of the SOURCE file which causes /xo to exclude it, and the newness of a source file which causes /xn to exclude it.

Tested with W10 20H2 19042.1052 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
@assign:xelu86

**Comment by Xelu86** [comment]
Hey @JimNim, 

Thanks again for contacting Microsoft. We value your feedback. A documentation change has been made for both **/xn** and **/xo** parameters and will be live after the next business day. 

We will be closing this as resolved. Thank you and have a most pleasant day. #please-close

**Comment by JimNim** [comment]
Bravo - a small detail, but the fix is appreciated!
