### ISSUE TITLE
Which type of Logon triggers an update of the LastLogonTimestamp for an AD user (skew accepted)

### ISSUE THREAD

**Issue by CXMelga** [MicrosoftDocs/windowsserverdocs#5702]
[Enter feedback here]

I understand not 'all' logon types update the above, what I would like to know please is which logon type does 'not' update the 
 LastLogonTimestamp for an AD user (forgetting about the 9 to 14 day skew rule).

I have some service type accounts which according to LastLogonDate have not logged on for years, but a small number of owners of these accounts sometimes say they are still used (with little information). Therefore I want to know which logon type the account might be using and escape detection

Thanks very much in advance
CXMegla 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45afe575-a51d-94ce-d81e-092768a67518
* Version Independent ID: 13d4632e-9671-41e8-24cf-0301aa503d56
* Content: [Administrative tools and logon types reference - Windows Server](https://docs.microsoft.com/en-us/windows-server/identity/securing-privileged-access/reference-tools-logon-types)
* Content Source: [WindowsServerDocs/identity/securing-privileged-access/reference-tools-logon-types.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/securing-privileged-access/reference-tools-logon-types.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
Unfortunately, the answer really is "it depends..." to get a better answer we recommend opening a support case so an engineer can ask some follow up questions and understand your environment. #please-close
