### ISSUE TITLE
CSV file headers are case-sensitive.

### ISSUE THREAD

**Issue by robharman** [MicrosoftDocs/windowsserverdocs#5708]
[Enter feedback here]

The CSV file is selectively case sensitive, as is the 'global' groupId. If 'global' is 'Global' the following error is thrown when importing:

Error: User is not authorized to modify this connection. Only gateway administrators can modify shared connections with groupId "global"

Capitalization in other fields doesn't seem to matter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6eeacf83-f081-d3ac-2d08-60bf6acde0a4
* Version Independent ID: 20153ee2-be3c-5a77-3fba-0b5bfe763bec
* Content: [Get started with Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/get-started#csv-file-format-for-importing-connections)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/use/get-started.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/use/get-started.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by v-thepet** [comment]
Hi @robharman,

Thank you for contacting Microsoft. We appreciate your feedback.

A documentation update has been made to stipulate that this CSV file is case-sensitive, and will be live with the next business day. In my testing I found that all the field headers were case sensitive, as well as values in the type and groupId fields. 

We'll now be closing this issue. Thanks again for your feedback, and have a most pleasant day.

#please-close

**Comment by Xelu86** [comment]
#assign:xelu86
