### ISSUE TITLE
HP

### ISSUE THREAD

**Issue by sulevtael** [MicrosoftDocs/windowsserverdocs#571]
Vebinar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588d12d1-fdd1-892a-eb5e-9e2d86302368
* Version Independent ID: 5eceac91-1d90-a663-2856-19e13da59351
* Content: [Remote Desktop clients](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-clients)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md)
* Service: **unspecified**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by chengchengLe** [comment]
看不懂，能不能翻译成中文。
Don't understand, can you translate into Chinese.

**Comment by lizap** [comment]
Hi - is there an issue here? I'm not sure what you mean by "vebinar"? Thanks!
