### ISSUE TITLE
universal remote destop app changes hwid between sessions - impact on per device CALs

### ISSUE THREAD

**Issue by be-puzzle-it** [MicrosoftDocs/windowsserverdocs#5711]
Hello,

We are using the universal remote desktop app (v10.2.1810)  from the store to connect to a Windows Server 2016 RDS Farm.
The setup has been done with per device CALs.

We noticed that the Remote Desktop app somehow generates its own hwids (starting with ff).  They change from time to time which results in client computers that claim multiple per device CALs.
The hardware ID stored in the registry isn't being used.

Is there anything we can do (configuration?) that allows us to continue to use the app and somehow ensure that it will send the same hwid all the time?

Thanks,
Bob

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acc42a8f-2623-4352-7cc4-70f0f61e9d89
* Version Independent ID: 97d8b54b-5e7d-098b-4fb7-e8f6e0b30389
* Content: [Get started with the Microsoft Store Client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windows)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windows.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windows.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
Hi @be-puzzle-it.  GitHub issues for this repo are for reporting problems with our documentation.  Please open a support ticket or post your question on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html).
