### ISSUE TITLE
Unable to Connect to Remote Host as Non-Administrator

### ISSUE THREAD

**Issue by daveinci** [MicrosoftDocs/windowsserverdocs#5713]
According to the docs I should be able to remotely connect to the hyper-v host if I am a member of the Hyper-V Administrators group OR the Administrators group. However, this doesn't seem to work for me unless I am a member of both Hyper-V Administrators AND Administrators. Is this a bug or error in documentation?

"Connect to a Windows Server 2016 or Windows 10 remote host as a different user
This lets you connect to the Hyper-V host when you're not running on the local computer as a user that's a member of either the Hyper-V Administrators group or the Administrators group on the Hyper-V host. To do this:

In the left pane, right-click Hyper-V Manager.
Click Connect to Server.
Select Connect as another user in the Select Computer dialogue box.
Select Set User.
 Note

This will only work for Windows Server 2016 or Windows 10 remote hosts."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4cb8cb4-b3d3-3833-c72a-b100d5078966
* Version Independent ID: 438b5485-1c26-b95b-11b1-b592dfc0117f
* Content: [Remotely manage Hyper-V hosts](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/remotely-manage-hyper-v-hosts)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/Remotely-manage-Hyper-V-hosts.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/manage/Remotely-manage-Hyper-V-hosts.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey daveinci,

Thanks again for contacting Microsoft. We value your feedback. 

Being a member of either the Hyper-V Admins or Admins group would suffice. If you're still experiencing an issue with Hyper-V in this regard, we encourage you to visit our community forums for advice:

- Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).
- Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).

We'll now be closing this thread. Thank you and have a most pleasant day. 
#please-close
