### ISSUE TITLE
"Only Windows Message Analyzer can check SMB3" but Windows Message Analyzer downloads are not available

### ISSUE THREAD

**Issue by humandevs** [MicrosoftDocs/windowsserverdocs#5714]
Please update Windows Message Analyzer to support SMB 3.1. Even the official documentation here says only Windows Message Analyzer can analyze SMB3 messages, but the downloads to this tool have been deleted and it hasn't been updated since 2016. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 643788d4-ceda-1f1d-a36f-916d207068e7
* Version Independent ID: 9ac5db6c-9619-b699-aabf-1c51faa22c2b
* Content: [Advanced Troubleshooting Server Message Block (SMB)](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/troubleshooting-smb)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/troubleshooting-smb.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/Troubleshoot/troubleshooting-smb.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @humandevs,

Thanks again for contacting Microsoft. We value your feedback. 

We have recently updated this documentation to reflect that the Message Analyzer (MA) tool has been [retired](https://learn.microsoft.com/openspecs/blog/ms-winintbloglp/dd98b93c-0a75-4eb0-b92e-e760c502394f) including removal of download packages from our download center on November 25, 2019. 

At this time, we have a reference page for those who are still using this tool, but we recommend that all our customers refer to [Wireshark](https://www.wireshark.org/index.html#download) for their network analysis tool as it also includes support for SMBv3 with the capability to read ETL files. 

These changes will take affect by the next business day. We will now be closing this thread.

Thank you and have a most pleasant day.
#please-close
