### ISSUE TITLE
broken uservoice links

### ISSUE THREAD

**Issue by charltonstanley** [MicrosoftDocs/windowsserverdocs#5716]
There are two broken uservoice links on this page. Below is the quoted text where both links are used.  I assume that this is due to MS moving away from uservoice (sadly).

> Vote for this item for Windows 10 vNext on the Windows Server Storage UserVoice.

and

> Vote for this item for Windows Server vNext on the Windows Server Storage UserVoice.

As a side question: is there a uservoice where we can submit feedback about MS moving away from uservoice?....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbca43fe-2459-af79-0ab0-6c598217239f
* Version Independent ID: 7e824aea-3911-d256-4002-d62711005efd
* Content: [Data Deduplication interoperability](https://docs.microsoft.com/en-us/windows-server/storage/data-deduplication/interop)
* Content Source: [WindowsServerDocs/storage/data-deduplication/interop.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/data-deduplication/interop.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @wmgries
* Microsoft Alias: **wgries**

**Comment by IngridAtMicrosoft** [comment]
Addressed. #please-close
