### ISSUE TITLE
start command needs more documentation

### ISSUE THREAD

**Issue by jredfox** [MicrosoftDocs/windowsserverdocs#5719]
[Enter feedback here]
so I am trying to figure out how to launch a command prompt in a new windows with a command. Once it's done executing the exit code is always 0 even if the process has failed. `start "my app" java -jar myapp.jar`  for example. The goal was to make an exit code of `4097` and reboot it if that has occurred. I just don't see a way of doing this. the `/wait` flag was very helpful it helped me to keep the program open while the process was running. it's not just you guys though. apple and linux will have the same issues. is there any documentation on how to get a child process on windows from the start command so I can get the real process? I don't know I think the best thing for my app would be to have process to process communication which I haven't seen a good way of doing yet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a52b78b6-e846-0b32-25c0-f9aab145b112
* Version Independent ID: 0c56bb98-4f1f-dd55-63ae-8bb18535cee1
* Content: [start](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start)
* Content Source: [WindowsServerDocs/administration/windows-commands/start.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/start.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey @jredfox,

Thanks again for contacting Microsoft. We value your feedback.

As we understand it, you may be describing a problem with the product itself and not with the product documentation. GitHub isn't quite the right location if searching for technical support or feature requests as it is completely outside our scope. It is mainly for documentation updates, improvement, and clarity. If there are any issues within the content itself, please let us know.

To get assistance or support for your product issue, we recommend that you engage with the product community or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs). 

Additional support forums listed below:
- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

We hope that one of the experts in those communities can better assist. We will now be closing this thread. We do wish that you have a most pleasant day!
#please-close
