### ISSUE TITLE
Don't understand

### ISSUE THREAD

**Issue by chengchengLe** [MicrosoftDocs/windowsserverdocs#572]
看不懂，能不能翻译成中文。
Don't understand, can you translate into Chinese.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 588d12d1-fdd1-892a-eb5e-9e2d86302368
* Version Independent ID: 5eceac91-1d90-a663-2856-19e13da59351
* Content: [Remote Desktop clients](https://docs.microsoft.com/zh-cn/windows-server/remote/remote-desktop-services/clients/remote-desktop-clients)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md)
* Service: **unspecified**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by lizap** [comment]
@chengchengLe - Hi! I'm submitting your ask to have this article translated. It will take a while to work through the system. Thanks for highlighting this issue - Liza

**Comment by craigskeat** [comment]
虽然简体中文翻译版本稍后可能会上线，但我还是会选择阅读英文文档。
Although Simplified Chinese translation would go online, I still prefered the docs in its original langauge.
