### ISSUE TITLE
Copy files from Mac to remote Windows server

### ISSUE THREAD

**Issue by mariflax** [MicrosoftDocs/windowsserverdocs#5720]
Hi,

I'm using the Microsoft Remote Desktop to connect from my Mac laptop to an AWS Windows instance. I want to transfer files from my Mac laptop to my Windows instance, but I don't see the options for this. Could you help me, please?

Thanks,
Marilyn Flax

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0517ea6a-9417-31a8-39a5-f6128387fee5
* Version Independent ID: 7636ec70-e1dd-8c6b-516c-8af324d9f645
* Content: [Get started with the macOS client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-mac)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by mariflax** [comment]
Hi again,
Just following up...
Thanks,
Marilyn

**Comment by IngridAtMicrosoft** [comment]
Hi @mariflax. GitHub issues for this repo are for reporting problems with our documentation.  Please open a support ticket or post your question at [Microsoft Q & A.](https://docs.microsoft.com/en-us/answers/index.html).
