### ISSUE TITLE
Build a Customer Auth Method with Azure AD ?

### ISSUE THREAD

**Issue by sydneystone59** [MicrosoftDocs/windowsserverdocs#5724]
Hi,

I did not try all of it, but this "Build a Custom Authentication Method for AD FS in Windows" procedure looks like a very good help.
Do you have the same for an Azure AD ?

Kind regards,

Sydney

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 432d0552-7fd9-7220-c5b2-3dd726ce54fa
* Version Independent ID: fa375dbe-43da-abcc-bc52-87f48b3d0b0c
* Content: [Build a Custom Authentication Method for AD FS in Windows Server](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/ad-fs-build-custom-auth-method)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/ad-fs-build-custom-auth-method.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/ad-fs-build-custom-auth-method.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @sydneystone59,

Thanks again for contacting Microsoft. We value your feedback. 

Looking into our Azure Docs, I did come across the following:

- [Authorization with Azure AD](https://learn.microsoft.com/en-us/azure/architecture/framework/security/design-identity-authorization)
- [Azure AD Connect and Federation](https://learn.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-whatis)
- [Deploying Active Directory Federation Services in Azure](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/how-to-connect-fed-azure-adfs)
- [Configure your App Service or Azure Functions app to use Azure AD login](https://learn.microsoft.com/en-us/azure/app-service/configure-authentication-provider-aad)
- [Choose the right authentication method for your Azure Active Directory hybrid identity solution](https://learn.microsoft.com/en-us/azure/active-directory/hybrid/choose-ad-authn)
- [Custom authentication in Azure Static Web Apps](https://learn.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad)
- [Custom controls (preview) in Azure AD](https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/controls)
- [Conditional Access authentication strength (preview)](https://learn.microsoft.com/en-us/azure/active-directory/authentication/concept-authentication-strengths)

We also have this resource below to assist with some AD FS issues:
- [AD FS Help](https://adfshelp.microsoft.com/) 

Do please let us know if this is helpful so we can close this issue.

**Comment by Xelu86** [comment]
Hey @sydneystone59,

We will now be closing this thread due to no response. Thank you and have a most pleasant day. #please-close
