### ISSUE TITLE
Semantic errors

### ISSUE THREAD

**Issue by Dweeberly** [MicrosoftDocs/windowsserverdocs#5727]
In the description it says "Specifies the full path of the subkey or entry to be added".  This is the "reg **delete**", so it should read deleted, not added.

Description of the /va option is unclear, poorly worded.  Perhaps it should be "All non-subkey items under the given subkey are deleted.

BTW: I just realized the page has an edit button <doh> sry  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2a03b57-702b-7270-deac-e12d055bf1ad
* Version Independent ID: d76457f5-2bee-4600-8f2d-6c7166b9de1f
* Content: [reg delete](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/reg-delete)
* Content Source: [WindowsServerDocs/administration/windows-commands/reg-delete.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/reg-delete.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86
