### ISSUE TITLE
robocopy braking behaviour change

### ISSUE THREAD

**Issue by rs38** [MicrosoftDocs/windowsserverdocs#5729]
We experience issues with robocopy Version from Windows Server 2019 copying files where a destination file to overwrite (.dll) can be locked. 

Versions of Robocopy from Server 2016 and older are working as expected by defining some retries and waits:
Options : *.* /V /S /E /DCOPY:DA /COPY:DAT /R:100 /W:10

Version 2019 is somehow not trying to retry, it proceeds with not showing any error in the per-file details but results summary is stating a FAILED copy as well as finishing with result code 10 or 11:

```
12:56:51   Info     |                    Total    Copied   Skipped  Mismatch    FAILED    Extras
12:56:51   Info     |       Dirs :         41         0        41         0         0         0
12:56:51   Info     |       Files :        74        59        14         0         1         1
12:56:51   Info     |       Bytes :   22.13 m    8.92 m   12.66 m         0   562.0 k     7.0 k
12:56:51   Info     |       Times :   0:00:40   0:00:23                       0:00:00   0:00:17
12:56:51   Info     |       Speed :              396600 Bytes/sec.
12:56:51   Info     |       Speed :              22.693 MegaBytes/min.
12:56:51   Info     |       Ended : 21 July 2021 10:56:46
12:56:51   Info     |       Exit code: 11
```
so if a job is expecting the copy operation to be successful by only accepting resultcodes < 8 it fails and you are not able to find any error in the verbose log.

Workaround: replacing robocopy.exe from Server 2016 or older works fine.

Are there any undocumented changes? any new options?

![image](https://user-images.githubusercontent.com/12622612/126612835-34a3d1e8-859e-40c1-8604-a80bc4e5ef49.png)
![image](https://user-images.githubusercontent.com/12622612/126612906-b7069c74-dc48-4dfb-8f63-6a74467be2e6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @rs38,

Thanks again for contacting Microsoft. We value your feedback. 

As we understand it, you're describing a problem with the product itself and not with the product documentation. If there are any issue(s) within the content, please let us know. 

To get assistance or support for your product issue, we recommend that you engage with the product community or open a ticket with Microsoft Support. For more information, see [Contact Microsoft Support](https://support.microsoft.com/ContactUs).

We will now be closing this. Thank you and have a most pleasant day. #please-close
