### ISSUE TITLE
Conflicting Edge (Chromium) information

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/windowsserverdocs#5730]
In the PowerShell code, the user agent matching string for Edge (Chromium) is different:

|PowerShel|Table|
|-|-|
|`=~Windows\s*NT.*Edg.*`|=~Windows\s*NT.Edg.|

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd7eb3f6-c00a-453f-a596-6f8bde452cb7
* Version Independent ID: 3250a24b-8e71-a36c-a9a0-7c46bc36acd4
* Content: [Configure browsers to use Windows Integrated Authentication (WIA) with AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-browser-wia)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Browser-WIA.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-Browser-WIA.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @paulomorgado,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting the table and will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. #please-close
