### ISSUE TITLE
page contains a typo

### ISSUE THREAD

**Issue by tdoan1** [MicrosoftDocs/windowsserverdocs#5731]
The PowerShell section of the page contains a typo under the section entitled Unconstrained Delegation/Trust This Computer for Delegation to any service. 

The first line of code reads:
-ADAccountControl -Identity TestgMSA$ ...

Instead it should read:
Set-ADAccountControl -Identity TestgMSA$ ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be58b4ad-e1e8-3eeb-6196-cd1c7d16a3b0
* Version Independent ID: 45556b26-7376-db10-4f14-c5571813ae3b
* Content: [Configuring Kerberos delegation for group Managed Service Accounts](https://docs.microsoft.com/en-us/windows-server/security/group-managed-service-accounts/configure-kerberos-delegation-group-managed-service-accounts)
* Content Source: [WindowsServerDocs/security/group-managed-service-accounts/configure-kerberos-delegation-group-managed-service-accounts.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/group-managed-service-accounts/configure-kerberos-delegation-group-managed-service-accounts.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @SumanBhowmik
* Microsoft Alias: **justinha**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We've submitted a documentation change based on your suggestion. Changes will be live after the next business day. This issue has been resolved. #please-close
