### ISSUE TITLE
A few cases of lack of clarity

### ISSUE THREAD

**Issue by DaPadrePedro** [MicrosoftDocs/windowsserverdocs#5733]
Hi,

Great Microsoft Docs page, but IMHO there a few cases of lack of clarity:
1) "Windows Server 2019" is mentioned, where I suspect "Windows server, version 1709" is meant (bullet 3 of the 1st bullet list)?
2) Bullet 6 in the 1st bullet list: I suppose this text should be interpreted as client and server are each evaluated (and possibly uninstalled) separately? The text is not 100% clear on this one.
3) Bullet 8 in the 1st bullet list: is it really literally a one-time operation? Or gets the automatic removal disabled after an explicit action (which makes the removal typically indeed a one-time operation, though not always!). Examples:
a) What if the SMB 1 client is uninstalled explicitly by an admin and afterwards installed explicitly again by an admin, while an automatic client removal has never occurred on the system in the past (so the one-time operation hasn't been executed yet, but an admin has installed the SMB 1 client on-demand)?
b) What if the SMB 1 server is installed explicitly by an admin (e.g. after a default installation which doesn't include this server), while an automatic server removal has never occurred on the system in the past (so the one-time operation hasn't been executed yet, but an admin has installed the SMB 1 server on-demand)?
Will the automatic removal mechanism will still be active in these cases?
4) Bullet 1 of the 2nd bullet list: I suppose this doesn't count for Insider builds (like on other editions since Version 1709)? The text is not clear on that?
5) Bullet 2 of the 2nd bullet list: what exactly is divergent from Version 1709? At first the text seems to insinuate everything, but then it seems that only 2 scenarios for the automatic removal mechanism are divergent. I suppose it's only the latter?
6) Bullet 2 of the 2nd bullet list - the 2 scenarios: I suppose this is also valid for Insider builds?
7) The 6 different error messages: I suppose these appear in Windows events?

Thank you very much in advance for clarifying! Do I get notified if changes are made?

With kind regards,

Padre Pedro (Christophe Heereman)
From WinDoh, Belgium

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6efee75e-7541-0166-76ac-81ecbe4cb022
* Version Independent ID: 35b346a7-ea72-325e-81c9-a1056dca72f4
* Content: [SMBv1 is not installed by default in Windows 10 version 1709, Windows Server version 1709 and later versions](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/smbv1-not-installed-by-default-in-windows)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/smbv1-not-installed-by-default-in-windows.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/Troubleshoot/smbv1-not-installed-by-default-in-windows.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
#label:"in-progress"

**Comment by Deland-Han** [comment]
We have modified the article with [PR2384](https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/2384). The issues should be addressed.

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by DaPadrePedro** [comment]
Hi, is there an update "pending" concerning points 1, 3, 4, 6 and 7 (the others seem to be dealt with; thanks!)? If it's not completely clear what exactly I mean, I'm certainly prepared to elucidate my questions/thoughts.

Regards,
Pedro

**Comment by IngridAtMicrosoft** [comment]
@DaPadrePedro Thanks as always for your dedication to docs.  Please open a new issue to address the rest of your thoughts.

**Comment by DaPadrePedro** [comment]
Hi @IngridAtMicrosoft 
I've just opened issue #6045.
Thanks!

Pedro
