### ISSUE TITLE
How many maximum number of GPUs we can pass-through to one virtual machine ? 

### ISSUE THREAD

**Issue by sandipt** [MicrosoftDocs/windowsserverdocs#5736]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5810b968-e5fb-ee1d-5313-a27906ecb6a1
* Version Independent ID: df579f96-62f1-ffe0-bc45-48c336a32ff2
* Content: [Plan for GPU acceleration in Windows Server](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/plan/plan-for-gpu-acceleration-in-windows-server)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/plan/plan-for-gpu-acceleration-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/plan/plan-for-gpu-acceleration-in-windows-server.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @rick-man
* Microsoft Alias: **rickman**

**Comment by sandipt** [comment]
Any updates? Maximum number of NVIDIA GPUs can we pass-through to one virtual machine in Hyper-V DDA?

**Comment by sandipt** [comment]
@PRMerger16 Any updates? 

Thanks,
Sandip

**Comment by IngridAtMicrosoft** [comment]
Hi @sandipt The GitHub issues here are for reporting problems with our documentation.  Please contact customer support for your question. #please-close
