### ISSUE TITLE
Feedback button not working for Android Remote Desktop app help page

### ISSUE THREAD

**Issue by henno** [MicrosoftDocs/windowsserverdocs#5739]
Pressing the Feedback button says that User voice no longer works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e9e26ca-6ca8-4f7f-b033-2398576369af
* Version Independent ID: b5b50e01-baf9-c2fe-7a1e-6f04a276e1fc
* Content: [Get started with the Android client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-android)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-android.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-android.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by nfedera** [comment]
Also when sending feedback to the developer email address listed in the playstore description rdandr@microsoft.com the email comes back with the following content:

> From: Microsoft Remote Desktop for Android <rdandr@microsoft.com>
> 
> We appreciate your feedback, but you have posted it in a channel that we don't monitor. 
> Please submit your feedback via UserVoice [https://aka.ms/rdandfbk](https://aka.ms/rdandfbk) to ensure we see it.

And that again leads to the closed instance: 
![image](https://user-images.githubusercontent.com/670606/143601970-96105715-d1ad-4597-a9c9-b43100f2fa69.png)

**Comment by lesca** [comment]
Me too. No place to feedback.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey henmo, nfedera, and lesca,

Thanks again for contacting Microsoft. We value your feedback. 

All instances of providing feedback to the Android Remote Desktop App has been removed from this document. Feedback can still be provided by visiting one of the following:

- https://aka.ms/avdandroidclientfeedback (for this app specifically)
- https://feedbackportal.microsoft.com/
- [Feedback Hub app](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332) (if you're running a Windows 10/11 OS)

The last section also includes a way to provide feedback:

![image](https://github.com/MicrosoftDocs/windowsserverdocs/assets/103963494/f3df68db-0435-4a30-8ce5-c9691e571f39)

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
