### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by MC2001** [MicrosoftDocs/windowsserverdocs#5742]
In the last paragraph states the minimum times to set, one line says to set the min time to no less than 60 seconds and the next line says to set the minimum time to no less than 10 minutes.  is the second statement supposed to be no longer than 10 minutes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49c82bcb-c188-c1b3-953c-60f699cc5813
* Version Independent ID: ef57a40d-0ea2-9911-bb54-0a3d0c88a591
* Content: [Plan NPS as a RADIUS server](https://docs.microsoft.com/en-us/windows-server/networking/technologies/nps/nps-plan-server)
* Content Source: [WindowsServerDocs/networking/technologies/nps/nps-plan-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/nps/nps-plan-server.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
assign:xelu86

**Comment by Xelu86** [comment]
Hey MC2001,

Thanks again for contacting Microsoft. We value your feedback. 

In short, "_well no, but actually yes_".

Looking at the reference document [RFC 2869](https://datatracker.ietf.org/doc/html/rfc2869), it states:

![image](https://github.com/MicrosoftDocs/windowsserverdocs/assets/103963494/ce634ea3-c9fc-4d03-9d7a-0c5a7fcd4f32)

Between 1 and 10 minutes appears to be the recommended length of time (you can reach a max of 86,400 seconds (24 hours) but this is highly not recommended). Increasing the value of the "Acct-Interim-Interval" attribute will cause the NAS to send interim updates less frequently. This will reduce the amount of network traffic generated by the NAS, but will also reduce the frequency of accounting updates received by the RADIUS server. Depending on your specific use case, this may or may not be desirable. It is recommended that you carefully consider the impact on network traffic before changing this value.

A documentation change has been made to bring more clarity:

> According to RFC 2869, the value of the Acct-Interim-Interval attribute must not be smaller than 60 seconds (1 minute), and should not be smaller than 600 seconds (10 minutes), meaning that values over 600 seconds will reduce the frequency of updates received by the RADIUS server.

Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
