### ISSUE TITLE
SC.exe description incomplete

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/windowsserverdocs#5743]
The `sc` commands described in the section containing below mentioned page (`sc config`, `sc create`, `sc delete`, `sc query`) are far less than the ones described here: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc754599(v=ws.11). However, they show more options.

Please update the docs to describe all `sc` commands to their full extend.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 582a188c-bf96-b9c5-50fc-2dacade5fba0
* Version Independent ID: 2f25595f-9d0e-a533-2dac-7c6495c94511
* Content: [sc.exe create](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/sc-create)
* Content Source: [WindowsServerDocs/administration/windows-commands/sc-create.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/sc-create.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @SetTrend, 

Thanks again for contacting Microsoft. We value your feedback. 

This article is to serve as a very basic reference to the `sc.exe` command. As we already have a repository from IT Pros going into greater depth on the `sc.exe` command, a hyperlink has been added to refer everyone to that page to learn more. 

Changes has been made correcting the table to display the information correctly and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
