### ISSUE TITLE
Not working for Windows 11

### ISSUE THREAD

**Issue by MalavVyas** [MicrosoftDocs/windowsserverdocs#5744]
[Enter feedback here]
Not working for Windows 11

```The command  you selected is not available with this version of windows```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebe4d9a1-5861-da8b-24c3-94b0a0102d8d
* Version Independent ID: c7b6adee-5a8b-c154-6d3b-e4a54ef6297d
* Content: [add](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/add)
* Content Source: [WindowsServerDocs/administration/windows-commands/add.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/add.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey MalavVyas,

Thanks again for contacting Microsoft, we value your feedback. 

The `add` command for diskshadow is a server-only command. It won't function in Windows Client. As this is a non-documentation issue, we’ll now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
