### ISSUE TITLE
SR-IOV

### ISSUE THREAD

**Issue by MaddDogg98** [MicrosoftDocs/windowsserverdocs#5746]
Please let the users know that if SR-IOV is not enabled/supported this may not work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd3f9056-fa1c-5f71-e7ff-538829bf6f2f
* Version Independent ID: 2613fd35-4215-9b6c-0c25-19638049e61f
* Content: [Deploy graphics devices using Discrete Device Assignment](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/deploy/deploying-graphics-devices-using-dda)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/deploy/Deploying-graphics-devices-using-dda.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/deploy/Deploying-graphics-devices-using-dda.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by craigcaseyMSFT** [comment]
Hello @MaddDogg98,

Thanks for contacting Microsoft. We value your feedback.

Documentation changes have been made to clarify and acknowledge this issue. The doc changes are live now.

Thank you again and have a most pleasant day.
#please-close
