### ISSUE TITLE
Clarify the /l switch

### ISSUE THREAD

**Issue by sken130** [MicrosoftDocs/windowsserverdocs#5747]
<html>
<body>

/l | Displays a list of files that are to be copied.
-- | --

</body>
</html>
[Enter feedback here]

I suggest to stress that the /l switch will make xcopy not to do any real copying.

I suggest to change this line:

`/l | Displays a list of files that are to be copied.`

to

`/l | Displays a list of files that are to be copied, without actually doing any copy.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a1e859-b436-290e-69c0-810dd3a5ce90
* Version Independent ID: 10c81289-2bf7-40d9-39ea-e624cf92aa3e
* Content: [xcopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/xcopy#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/xcopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/xcopy.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @sken130,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made concerning the "**/l**" parameter and will be live after the next business day. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
