### ISSUE TITLE
I've to enter my credentials twice

### ISSUE THREAD

**Issue by ferronsw** [MicrosoftDocs/windowsserverdocs#575]
When I go to the new webclient url I have to authenticate. When I click on a remote app I'm asked to enter my credentials again. Is this on purpose or is something going wrong? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Service: **unspecified**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by torivara** [comment]
Same here. Had to enter my creds twice.

**Comment by kometkamerat** [comment]
Same, multiple times if you have multiple Collections.

**Comment by fate0521** [comment]
Please vote on this feature: https://remotedesktop.uservoice.com/forums/911494-remote-desktop-web-client/suggestions/33788413-enable-sso-in-rd-web-client

**Comment by Heidilohr** [comment]
The web client doesn't support SSO at this time, so you'll have to enter your credentials whenever you open an app in the client. I've updated this article and the "Access the Remote Desktop web client" article for users with notes clarifying this.
