### ISSUE TITLE
Device Tunnel - NRPT Table

### ISSUE THREAD

**Issue by donky-bison** [MicrosoftDocs/windowsserverdocs#576]
Is it possible to use the nrpt DNS table with device tunnel vpn profile. I can configure it, but it doesn't work. can you give me an example or an advice. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7453068-95eb-2a42-fd0b-553ae593adb0
* Version Independent ID: b39b2cb7-25b1-2af3-4954-dbcc04c836e9
* Content: [Configure Windows 10 Client Always On VPN Connections](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections#feedback)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md)
* Service: **unspecified**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@donky-bison, can you provide more details as to what you are doing?  What is the high-level scenario?

**Comment by donky-bison** [comment]
We have an onprem Skype for Business (SFB) deployment. The SFB client has to connect over the Internet to the SFB Edge Server and not over the VPN Tunnel to get connected to the sfb pool. To reach this Goal, we have to disable the dns Resolution for the internal SFB Servers. 
We have now implemented the dns role on the vpn Server, which forwards the sfB Client query for the internal sfb servers to nowhere.  The VPN Clients uses the VPN Servers as DN Server. 
If we could control the dns behavior for certain FQDN with NRPT, this would be nice. We could then configure nrpt to resolve the dns Names for our internal SFB Servers by a public DNS.

**Comment by shortpatti** [comment]
@donky-bison, I apologize for the delay, I have the engineering team working on providing more details.

**Comment by shortpatti** [comment]
Hi @donky-bison, I believe you can use NRPT dns table.  Let me verify with a couple of engineers.

**Comment by shortpatti** [comment]
@MihaiSP, can you take a look at this issue?
