### ISSUE TITLE
Can FSRM File Management Tasks be automated using PowerShell?

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/windowsserverdocs#5763]
This page describes how to create FSRM tasks using the FSRM Manager. 

Can these tasks be created and managed using a PowerShell cmdlet or is this a GUI only operation?

If the former, we should update the page to say how. If the later, how about updating the page to say this is a GUI only operation.

Happy to do the updates either way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05c61c2d-8734-4af9-1601-12e69d2c51a5
* Version Independent ID: 4dca62e7-807c-a03d-ae12-a44e3557293b
* Content: [Create a File Expiration Task](https://docs.microsoft.com/en-us/windows-server/storage/fsrm/create-file-expiration-task)
* Content Source: [WindowsServerDocs/storage/fsrm/create-file-expiration-task.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/fsrm/create-file-expiration-task.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @doctordns,

Thanks again for contacting Microsoft. We value your feedback.

Looking through this document, all the instructions are meant to be performed in the GUI itself as PowerShell is not mentioned.

Going through our PowerShell repo, I did come across [cmdlets for FSRM](https://learn.microsoft.com/en-us/powershell/module/fileserverresourcemanager/?view=windowsserver2022-ps). Taking a quick gander, it looks like the cmdlets below may be the ones that provides the same result as the example in this document:

[Get-FsrmFileManagementJob](https://learn.microsoft.com/en-us/powershell/module/fileserverresourcemanager/get-fsrmfilemanagementjob?view=windowsserver2022-ps)
[New-FsrmFileManagementJob](https://learn.microsoft.com/en-us/powershell/module/fileserverresourcemanager/new-fsrmfilemanagementjob?view=windowsserver2022-ps)
[Remove-FsrmFileManagementJob](https://learn.microsoft.com/en-us/powershell/module/fileserverresourcemanager/remove-fsrmfilemanagementjob?view=windowsserver2022-ps)
[Set-FsrmFileManagementJob](https://learn.microsoft.com/en-us/powershell/module/fileserverresourcemanager/set-fsrmfilemanagementjob?view=windowsserver2022-ps)
[Start-FsrmFileManagementJob](https://learn.microsoft.com/en-us/powershell/module/fileserverresourcemanager/start-fsrmfilemanagementjob?view=windowsserver2022-ps)
[Stop-FsrmFileManagementJob](https://learn.microsoft.com/en-us/powershell/module/fileserverresourcemanager/stop-fsrmfilemanagementjob?view=windowsserver2022-ps) 
[Wait-FsrmFileManagementJob](https://learn.microsoft.com/en-us/powershell/module/fileserverresourcemanager/wait-fsrmfilemanagementjob?view=windowsserver2022-ps) 

Hopefully this resource helps in automating certain tasks. We will now be closing this thread. Thank you and we wish you a most pleasant day. #please-close
