### ISSUE TITLE
fsutil does not require Windows Subsystem for Linux

### ISSUE THREAD

**Issue by YerCodeSmellsFunny** [MicrosoftDocs/windowsserverdocs#5765]
[Enter feedback here]

Its mentioned that to use fsutil, WSL  (windows subsystem for linux) is required.  This is not actually true, as far as I can tell.  I can hardlink files with fsutil no problem, and never enabled WSL.  

Oh, and if you get around to it- it would be nice if opening a folder with the File Explorer would remember where its window was last placed/sized by the user.  I've been waiting for that since Windows 3.0- I'm guessing your AIs are smart enough to handle it now. Thanks for reading this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18562b49-3654-a3ff-9617-3c59d50a7d1e
* Version Independent ID: 3e69bcb1-b1e6-f0ea-e861-5ced88fe6a24
* Content: [fsutil](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil)
* Content Source: [WindowsServerDocs/administration/windows-commands/fsutil.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/fsutil.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @toklima
* Microsoft Alias: **toklima**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @YerCodeSmellsFunny,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made removing this from the note as WSL is not a dependancy for `fsutil` to run. Changes will be live after the next business day. 

As per your feature request for file explorer, I don't know if this has been requested prior but hopefully this is in the works. Please use the Feedback Hub that's built into Windows and suggest a feature change:

![image](https://user-images.githubusercontent.com/103963494/199571268-1c1aeaf3-84d2-4789-865a-7f27ebcf5bb2.png)
 
We will now be closing this thread. Thank you and have a most pleasant day. #please-close
