### ISSUE TITLE
Checklist item #10 wrong link. Must be "Create a Claims Provider Trust"

### ISSUE THREAD

**Issue by janis-veinbergs** [MicrosoftDocs/windowsserverdocs#577]
Checklist item #10 reads: "create a claims provider trust relationship by using the AD FS Management snap-in", but the link leads to article that shows how to create relying party trust.  I think it should link to "Create a Claims Provider Trust": https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/create-a-claims-provider-trust

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6bc8336-382f-bd3e-0d5e-0ec19128cae9
* Version Independent ID: 138957a3-79b0-24e6-333c-446ef40fb8ed
* Content: [Checklist - Configuring the Resource Partner Organization](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/checklist--configuring-the-resource-partner-organization)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Checklist--Configuring-the-Resource-Partner-Organization.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Checklist--Configuring-the-Resource-Partner-Organization.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Thank you for reporting that issue and the suggested correction. I agree. Sorry for taking so long to find this ticket and replying to it.

**Comment by illfated** [comment]
It has been a long time, I know. I hope this material will still be useful for someone. Pull Request #4879 is ready for review.
