### ISSUE TITLE
Minor improvement to greatly improve clarity

### ISSUE THREAD

**Issue by cedwards-telis** [MicrosoftDocs/windowsserverdocs#5773]
The first sentence below reads to me as an "if and only if", although that isn't its grammatical sense or the intention.  Or maybe I can't read properly you decide.

> If your system does not require resiliency or has external backups, the storage bus cache will support both read and write caching. For resilient systems, the storage bus cache will only serve as a read cache and it is recommended to pick ReFS Mirror-accelerated parity as the volume resiliency. This combination improves random read performance as data is read from the parity tier and cached on the faster mirror tier. The mirror tier also provides write caching capabilities if the Provision Mode is set to Shared (default).

Change to:-

> If your system does not require resiliency or has external backups, the storage bus cache will **_always_** support both read and write caching.
> 
> For resilient systems, the storage bus cache will **_by default_** only serve as a read cache.  It is recommended to pick ReFS Mirror-accelerated parity as the volume resiliency since this combination improves random read performance as data is read from the parity tier and cached on the faster mirror tier. In this scenario the mirror tier also provides write caching capabilities if the Provision Mode is set to Shared (default).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38dc8bb9-ed5d-935c-2509-21871bed0749
* Version Independent ID: a17de18e-0ed2-68c1-5729-d76f493dbfea
* Content: [Storage bus cache on Storage Spaces](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/storage-spaces-storage-bus-cache)
* Content Source: [WindowsServerDocs/storage/storage-spaces/storage-spaces-storage-bus-cache.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/storage-spaces-storage-bus-cache.md)
* Product: **windows-server**
* Technology: **storage-spaces**
* GitHub Login: @TinaWu-Msft
* Microsoft Alias: **tinawu**

**Comment by TinaWu-Msft** [comment]
Hi, 
At this time, the storage bus cache can only serve as a read cache for systems that require resiliency. This is something that we hope to improve in the future.  

Best, 
Tina

**Comment by cedwards-telis** [comment]
@TinaWu-Msft Well in that case you should remove the following statement:-

> "The mirror tier also provides write caching capabilities if the Provision Mode is set to Shared (default)."

**Comment by TinaWu-Msft** [comment]
This is a functionality specific to mirror accelerated parity volumes as opposed to the storage bus cache. The mirror tier is on the faster media type and hence can act as a write cache. Using the storage bus cache together with mirror accelerated parity volumes provide read and write caching.

**Comment by IngridAtMicrosoft** [comment]
Addressed. #please-close
