### ISSUE TITLE
128 MB increments is ambiguous 

### ISSUE THREAD

**Issue by Zixradoom** [MicrosoftDocs/windowsserverdocs#5774]
[Enter feedback here]

128 MB increments is ambiguous, does it mean [MiB ](https://en.wikipedia.org/wiki/Binary_prefix)(134,217,728) or MB (128000000), the proper unit for computer memory is MiB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84d52296-198d-7c8a-db99-e8cb336e355f
* Version Independent ID: 77670399-109f-3233-0466-c13d84542039
* Content: [Supported Ubuntu virtual machines on Hyper-V](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-ubuntu-virtual-machines-on-hyper-v)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Supported-Ubuntu-virtual-machines-on-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/Supported-Ubuntu-virtual-machines-on-Hyper-V.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by Joachim-Otahal** [comment]
Microsft uses 1MB = 2^20 = 1048576, or in this case 2^27, 134217728 Bytes.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey Zixradoom,

Thanks again for contacting Microsoft. We value your feedback. 

The Windows OS displays storage capacity and file sizes using the decimal prefix KB, MB, GB, etc. but still calculates this as KiB, MiB, etc.

As this is a non-documentation issue, we'll be closing this thread.

Thank you and have a most pleasant day. 
#please-close
