### ISSUE TITLE
typo in `tree c:\ /f  prn` ? it replies with `Too many parameters - prn`

### ISSUE THREAD

**Issue by juwens** [MicrosoftDocs/windowsserverdocs#5778]
Did you mean something like `tree c:\ /f | print` ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a3647fd-2127-f673-618e-9842d3e8202c
* Version Independent ID: 00e69fb8-23b3-eb08-47fb-adf04f46fbf1
* Content: [tree](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/tree)
* Content Source: [WindowsServerDocs/administration/windows-commands/tree.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/tree.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
@juwens Thank you for catching that!

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @juwens,

Thanks again for contacting Microsoft. We value your feedback. 

The example used in this documentation has been updated to print the output into a file that can later be sent to a printer. 

The new example is:
`tree c:\ /f > <driveletter>:\<filepath>\filename.txt`.

So this can be `tree c:\ /f > C:\Users\UserName\Desktop\Output.txt`.

This change will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
