### ISSUE TITLE
mention testing if directory exists using   if exist directoryName\nul

### ISSUE THREAD

**Issue by MikeLippUnity** [MicrosoftDocs/windowsserverdocs#5787]
Please add to doc how to use the "if exist" to determine if directory exists. Typically this would be by using syntax like
   if exist directoryName\nul

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c179cec0-fc0c-2f8e-8b15-cd23b46e58dd
* Version Independent ID: 7d9137c1-5db0-c8ec-419c-ac4540433438
* Content: [if](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/if)
* Content Source: [WindowsServerDocs/administration/windows-commands/if.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/if.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey MikeLippUnity,

Thanks again for contacting Microsoft. We value your feedback. 

The `if` document already has an `if exist` example checking if a file exists (and deleting it) which can also be used for checking directories in the same fashion:

> IF EXIST Product.dat (del Product.dat) ELSE (echo The Product.dat file is missing.) 
>
> IF EXIST "ServerLogDir" (echo Directory exists!) ELSE (echo Directory is missing!) 

At this time, we will not be making an update to this document. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
