### ISSUE TITLE
Regex character missing

### ISSUE THREAD

**Issue by tribut** [MicrosoftDocs/windowsserverdocs#5791]
The section "Connect to these servers" says:

> [...] you must use at least one "" in the string specified. For example, you can specify nps.example.com to specify the RADIUS server nps1.example.com or nps2.example.com.

It is not clear what the magic character is that would trigger "matching as regex" and the example obviously does not match the intended host names.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac9de730-f6cf-01b1-d32a-b502283789c0
* Version Independent ID: 2e1c9ff2-4181-f459-ad44-c010530d50be
* Content: [Extensible Authentication Protocol (EAP) for network access](https://docs.microsoft.com/en-us/windows-server/networking/technologies/extensible-authentication-protocol/network-access#connect-to-these-servers)
* Content Source: [WindowsServerDocs/networking/technologies/extensible-authentication-protocol/network-access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/extensible-authentication-protocol/network-access.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @khdownie
* Microsoft Alias: **v-kedow**

**Comment by Xelu86** [comment]
Hey tribut,

Thanks again for contacting Microsoft. We value your feedback. 

Documentation changes have been applied addressing this issue and more updates to come. Changes are live. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
