### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by halajamal-ms** [MicrosoftDocs/windowsserverdocs#5797]
the "Securing network traffic in Azure" link is broken (404- content not found) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b0097c-668e-1d37-22b0-89d0bf649f8a
* Version Independent ID: 49ccfef6-05bb-9c93-5a05-a2e2fe632b3c
* Content: [Install Active Directory Domain Services on an Azure virtual machine](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm?source=docs)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/virtual-dc/adds-on-azure-vm.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by IngridAtMicrosoft** [comment]
Issue was addressed.
