### ISSUE TITLE
Cannot provision Always On VPN profile to non-admin using Powershell

### ISSUE THREAD

**Issue by S-dn-Y** [MicrosoftDocs/windowsserverdocs#580]
Hi,

I'm currently testing out the Always On VPN functionality. It works well, but I'm only able to deploy the VPN profile via Powershell to users that have got administrative permissions. 
I did some research on the CSP and the WMI Bridge provider and as expected one would need administrative permission to use the WMI Bridge Provider to set the CSP, so it make sense the command only works on administrative users.
To be able to set the required settings (on the CSP) for non-administrative users, it seems the script invokes a cim-session with some custom options containing the SID of the user to configure;

----
$session = New-CimSession
$options = New-Object Microsoft.Management.Infrastructure.Options.CimOperationOptions
$options.SetCustomOption('PolicyPlatformContext_PrincipalContext_Type', 'PolicyPlatform_UserContext', $false)
$options.SetCustomOption('PolicyPlatformContext_PrincipalContext_Id', "$SidValue", $false)

and using the options again to set the user settings
$session.CreateInstance($namespaceName, $newInstance, $options)

----

However If I run the provided powershell script with administrative permissions, it configures the VPN profiles on the profile of my administrative user, instead of the user to which to SID belongs to.
When I make the user member of the local adminstrators group, the script runs in context of the user itself and it works, but I'm testing this out to deploy this in our organization so it needs to work on non-admins also (in a logon script or something, I will sort this out when this is working).

I cannot seem to find any clear documentation about the custom options used here, so I find it rather hard to troubleshoot why this isn't working for me.

I'm using the latest version of Windows 10 in my test environment. All servers 2016.

I'm hoping someone can clear this up for me! :-)
Thanks!

Best Regards,
Sidney

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7453068-95eb-2a42-fd0b-553ae593adb0
* Version Independent ID: b39b2cb7-25b1-2af3-4954-dbcc04c836e9
* Content: [Configure Windows 10 Client Always On VPN Connections](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md)
* Service: **unspecified**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@S-dn-Y, as per the SME, WMI-to-CSP bridge requires local admin rights, by design - to deploy per user VPN profiles they should be using SCCM or MDM.

**Comment by plekkenpol** [comment]
I find it strange that there would even be a write up that is for Administrative users only.  Also, suggesting the only way to fix is pay for Intune or SCCM isn't a very thoughtful approach.  How about add the user temporarily as a local admin, run the script, then remove user from local admins.  Seems to work fine.  While this may be a bit time consuming, it's sufficient for a small user base.  

I'm sure if someone takes it a step further, the script can automate the addition and removal of the current user to/from the local admins group considering PowerShell has to be run as administrator anyway.

**Comment by S-dn-Y** [comment]
Hey plekkenpol,

I actually did find a way to automate it.
I'm not using it in production though, but liked the challenge ;).

So, the custom CIM options shown below that are being used to set the VPN CSP in regards of another user need to be run in local system context. If you try to run it with administrative permissions, it will ignore the custom options silenty (as it seems).

**_$options.SetCustomOption('PolicyPlatformContext_PrincipalContext_Type', 'PolicyPlatform_UserContext', $false)
$options.SetCustomOption('PolicyPlatformContext_PrincipalContext_Id', "$SidValue", $false)_**

Now I was able to work around this by using a scheduled task that runs only one time in a Group Policy Object. You can make the scheduled task run in the context as local system and make it call the Powershell script and pass the SID of the current logged on user  into $SidValue to feed to the custom CIM options. The script will give a user that is logged in the Always On VPN profile.

You can try to tweak things further (I haven't, cause haven't implemented it (yet)). Anyhow, the key here is that it needs to run as local system and a scheduled task let you implement this fairly easy :)

 Best regards,
Sidney

**Comment by efbertos** [comment]
> Hey plekkenpol,
> 
> I actually did find a way to automate it.
> I'm not using it in production though, but liked the challenge ;).
> 
> So, the custom CIM options shown below that are being used to set the VPN CSP in regards of another user need to be run in local system context. If you try to run it with administrative permissions, it will ignore the custom options silenty (as it seems).
> 
> **_$options.SetCustomOption('PolicyPlatformContext_PrincipalContext_Type', 'PolicyPlatform_UserContext', $false) $options.SetCustomOption('PolicyPlatformContext_PrincipalContext_Id', "$SidValue", $false)_**
> 
> Now I was able to work around this by using a scheduled task that runs only one time in a Group Policy Object. You can make the scheduled task run in the context as local system and make it call the Powershell script and pass the SID of the current logged on user into $SidValue to feed to the custom CIM options. The script will give a user that is logged in the Always On VPN profile.
> 
> You can try to tweak things further (I haven't, cause haven't implemented it (yet)). Anyhow, the key here is that it needs to run as local system and a scheduled task let you implement this fairly easy :)
> 
> Best regards,
> Sidney

Doesn't the script already gather the currently logged in user via the following?

$username = Gwmi -Class Win32_ComputerSystem | select username

Thanks,
