### ISSUE TITLE
Modify existing ADFS Application

### ISSUE THREAD

**Issue by CMDRVyborg** [MicrosoftDocs/windowsserverdocs#5810]
This document explains how to create an application pool in ADFS. Then it shows how to modify a separate project to add additional token ID types. However, it does not show you how to edit the application you built in part one of the document. I have a working application pool, I just need to modify it to allow different token ID types. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4866bff-5947-4b24-7958-94a8164b814a
* Version Independent ID: 3d5611d1-df23-90de-cc1b-81862d2f39e4
* Content: [Build a web application using OpenID Connect with AD FS 2016 and later](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/enabling-openid-connect-with-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/enabling-openId-connect-with-ad-fs.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/enabling-openId-connect-with-ad-fs.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
