### ISSUE TITLE
Link points to archived GitHub repo

### ISSUE THREAD

**Issue by dcrreynolds** [MicrosoftDocs/windowsserverdocs#5813]
The doc page "Build a single page web application using OAuth and ADAL.JS with AD FS 2016 or later" points to sample GitHub repo Azure-Samples/active-directory-angularjs-singlepageapp which has been archived. The link (and likely the docs) should be revamped to point to a current repo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 564391c0-ad11-762f-41c9-cc898c7b3a46
* Version Independent ID: 04020c6c-d236-3dcb-5be2-f444d05d214e
* Content: [Build a single page web application using OAuth and ADAL.JS with AD FS 2016 or later](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/single-page-application-with-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/Single-Page-Application-with-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/Single-Page-Application-with-AD-FS.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
#label: "doc-bug"

**Comment by IngridAtMicrosoft** [comment]
Referenced Windows Server page no longer exists. Keeping open as the Azure page is already assigned to content developer.

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
