### ISSUE TITLE
Add documentation for Windows Server 2022

### ISSUE THREAD

**Issue by Lefty4444** [MicrosoftDocs/windowsserverdocs#5819]
Please update page with requirements for Windows Server 2022.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 418dc0a0-0312-9d6f-b2dc-2eb4841285ba
* Version Independent ID: 600b0469-3c96-5737-c39b-2ce9021b0f5a
* Content: [Windows Server 2016 Functional Levels](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/active-directory-functional-levels)
* Content Source: [WindowsServerDocs/identity/ad-ds/active-directory-functional-levels.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/active-directory-functional-levels.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by IngridAtMicrosoft** [comment]
#assign:dknappettmsft

**Comment by dknappettmsft** [comment]
This article has been updated for Windows Server 2022 and the changes should be visible later today.

#please-close
