### ISSUE TITLE
Link to the Microsoft Windows Security Resource Kit in this document is dead

### ISSUE THREAD

**Issue by longman391** [MicrosoftDocs/windowsserverdocs#582]
The link to the Microsoft Windows Security Resource Kit in this document is dead: https://www.microsoft.com/learning/en/us/book.aspx?ID=6815&locale=en-us

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19620533-3f60-a1cb-a679-ff6ff5dde2bc
* Version Independent ID: 54583dac-de23-b64c-3396-fac964724595
* Content: [Implementing Least-Privilege Administrative Models](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/implementing-least-privilege-administrative-models#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Implementing-Least-Privilege-Administrative-Models.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Implementing-Least-Privilege-Administrative-Models.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by mokeshsingh-yahoo-com** [comment]
I spotted that too.
You can find it here: https://www.microsoftpressstore.com/store/microsoft-windows-security-resource-kit-9780735621749

**Comment by shortpatti** [comment]
Updated dead link with the correct link.
