### ISSUE TITLE
TLS 1.3 support unclear

### ISSUE THREAD

**Issue by ruffy91** [MicrosoftDocs/windowsserverdocs#5821]
Please clarify which features support TLS 1.3.
For example my tests indicate that LDAPS on a Server 2022 machine does not support TLS 1.3 (only TLS 1.2), however ADFS does support TLS 1.3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e900bb3-e55a-2175-818b-79bee86bd8d2
* Version Independent ID: 78f66ffe-6ee1-5adc-34f7-c36ef717d392
* Content: [What's new in Windows Server 2022](https://docs.microsoft.com/en-us/windows-server/get-started/whats-new-in-windows-server-2022)
* Content Source: [WindowsServerDocs/get-started/whats-new-in-windows-server-2022.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/whats-new-in-windows-server-2022.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @dknappettmsft
* Microsoft Alias: **daknappe**

**Comment by dknappettmsft** [comment]
Thank you for the feedback. This article only covers that TLS 1.3 is in the protocol layer is now enabled by default in Windows Server 2022. However, the higher layer components need to also make some changes to use it. That support is to be documented by those first and third applications and services that support it as it becomes available.

I have added some clarification and a link to a Microsoft Security blog article around some of the technicalities, which I hope helps.  That should be visible later today

I will close this issue as this article only covers the fact that TLS 1.3 is now available to be used in the operating system.

#please-close
