### ISSUE TITLE
windows server

### ISSUE THREAD

**Issue by ijlal12345** [MicrosoftDocs/windowsserverdocs#5822]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b79ce4d-52b9-5193-df08-c40fa663da58
* Version Independent ID: a5215c06-f761-3141-4eb4-71ae00b2c8aa
* Content: [Get started with Windows Server Update Services (WSUS)](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/get-started/windows-server-update-services-wsus)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/get-started/windows-server-update-services-wsus.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/get-started/windows-server-update-services-wsus.md)
* Product: **windows-server**
* Technology: **wsus**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#please-close no feedback given
