### ISSUE TITLE
OpenID Connect is an authentication protocol, not an authorization protocol

### ISSUE THREAD

**Issue by amirabr** [MicrosoftDocs/windowsserverdocs#5828]
Regarding this line: "openid - Allows application to request use of the OpenID Connect authorization protocol."
OpenID Connect is an authentication protocol, not an authorization protocol.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 305d0726-a212-975f-822e-9a23af6e7ccb
* Version Independent ID: b88a9450-4376-2fd2-aaaa-3b2d086dd266
* Content: [AD FS OpenID Connect/OAuth Concepts](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/ad-fs-openid-connect-oauth-concepts)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/ad-fs-openid-connect-oauth-concepts.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/ad-fs-openid-connect-oauth-concepts.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by Xelu86** [comment]
Hey @amirabr,
 
Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting this and will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. #please-close
