### ISSUE TITLE
Outdated Content

### ISSUE THREAD

**Issue by mr-fujnz** [MicrosoftDocs/windowsserverdocs#5829]
Hello

Network load balancer deployment guide leads here:
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc754833(v=ws.10)

Which then leads to what looks like it might have been a design guide for NLB on server 2003?
https://technet2.microsoft.com/windowsserver/en/library/4d24fdac-edf3-4ac5-937a-273867f46fcf1033.mspx?mfr=true

Any updated design guides available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62f953b5-5ea4-4435-37b9-53484f75b316
* Version Independent ID: 6394da95-c5cb-2e17-2ae7-82e203b16c9e
* Content: [Network Load Balancing](https://docs.microsoft.com/en-us/windows-server/networking/technologies/network-load-balancing)
* Content Source: [WindowsServerDocs/networking/technologies/Network-Load-Balancing.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/Network-Load-Balancing.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by v-thepet** [comment]
Hello @mr-fujnz, 

We'd like to express our gratitude for your commitment to our documentation. Support for Windows Server 2008 and 2012 has ended, and we don't update documentation for those previous versions, so all the linked pages in that table are unsupported and are for historical purposes only. Unfortunately, we don't have an updated "Deployment Guide" per se for NLB. 

For updated information, you could consult the [Load Balancer Documentation](https://learn.microsoft.com/azure/load-balancer/), or the [Q&A Page for Load Balancer](https://learn.microsoft.com/answers/tags/230/azure-load-balancer).

Here are some other channels for engaging with Microsoft for support questions, product feedback, or other feedback:

- [Bug submittal or feature requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide) 
 - From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback). 
- Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs). 
- Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home). 
- Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home). 
- Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

We offer our apologies for any inconvenience we’ve caused, and welcome any further suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support. 

#please-close
