### ISSUE TITLE
2019?

### ISSUE THREAD

**Issue by JoeBrunsTR** [MicrosoftDocs/windowsserverdocs#5838]
Shouldn't step 1 be talking about upgrading to windows server 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e46c4f0-4f70-47bf-d786-dd27c3a39692
* Version Independent ID: 00460a88-799c-3a42-898a-e6db893eaad0
* Content: [Upgrading Failover Clusters Using the Same Hardware](https://docs.microsoft.com/en-us/windows-server/failover-clustering/upgrade-option-same-hardware?source=docs)
* Content Source: [WindowsServerDocs/failover-clustering/Upgrade-Option-Same-Hardware.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/Upgrade-Option-Same-Hardware.md)
* Product: **windows-server**
* Technology: **failover-clustering**
* GitHub Login: @JohnMarlin-MSFT
* Microsoft Alias: **johnmar**

**Comment by IngridAtMicrosoft** [comment]
#assign:dknappettmsft

**Comment by dknappettmsft** [comment]
Hi @JoeBrunsTR, the steps in this article are an example of going from a Windows Server 2012 failover cluster server to Windows Server 2019. Upgrading the operating system on an existing failover cluster is only supported when going from Windows Server 2016 to Windows 2019, so step 1 goes to Windows Server 2016 first as it is necessary temporarily to get to Windows Server 2019.  I hope that clears it up.

#please-close
