### ISSUE TITLE
 Trusted Platform Module (TPM) w wersji 2.0

### ISSUE THREAD

**Issue by jerzy0612** [MicrosoftDocs/windowsserverdocs#5839]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51a46bd6-3e72-17c1-be81-3876b4be3ca1
* Version Independent ID: c54cac12-2b73-96ab-7be8-61c077377fed
* Content: [Deploy guarded hosts](https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-configure-hgs-with-authorized-hyper-v-hosts)
* Content Source: [WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-configure-hgs-with-authorized-hyper-v-hosts.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-configure-hgs-with-authorized-hyper-v-hosts.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @rpsqrd
* Microsoft Alias: **ryanpu**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Closing as this is a non-document issue. #please-close
