### ISSUE TITLE
Hash Algorithm: SHA2??

### ISSUE THREAD

**Issue by dm3942** [MicrosoftDocs/windowsserverdocs#5841]
[Enter feedback here]

Please confirm that the following is not a typo when creating the certificate template? 
Hash Algorithm: SHA2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2237d85b-4b60-02bf-0ce2-09d803a75186
* Version Independent ID: ff569ede-822d-1d39-b233-a66a3541d32a
* Content: [Configure Certificate Templates for PEAP and EAP Requirements](https://docs.microsoft.com/en-us/windows-server/networking/technologies/nps/nps-manage-cert-requirements)
* Content Source: [WindowsServerDocs/networking/technologies/nps/nps-manage-cert-requirements.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/nps/nps-manage-cert-requirements.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey dm3942,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change was made correcting that section and will be live after the next business day. We will now be closing this thread.

Thank you and have a most pleasant day. 
#please-close
