### ISSUE TITLE
TLS 1.2 issue

### ISSUE THREAD

**Issue by jeffjcom** [MicrosoftDocs/windowsserverdocs#5847]
[Enter feedback here]
Got errors running:  Install-Module -Name PowerShellGet -Force

After following notice from here on TLS 1.2 it worked.

https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-7.1

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71daf1a3-fdf6-de26-836e-badff4b8b869
* Version Independent ID: 4631dad7-30cc-f162-7e4f-4d461981c45a
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey jeffjcom,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding this into a note under the "[How to publish the Remote Desktop web client](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin#how-to-publish-the-remote-desktop-web-client)" section and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
