### ISSUE TITLE
What is "Disable U/P endpoint in ADFS"

### ISSUE THREAD

**Issue by Kofl** [MicrosoftDocs/windowsserverdocs#5848]
Hi,

documentation states:

Disable U/P endpoint in ADFS 

Please clarify, what the U/P endpoint in ADFS is, so customers are able to disable them.

B

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be1bc207-a870-6819-f24b-03643b78bf60
* Version Independent ID: b6a2fc36-63cd-fa78-af34-52b8bb53cf55
* Content: [AD FS Password Attack protection](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/technical-reference/ad-fs-password-protection)
* Content Source: [WindowsServerDocs/identity/ad-fs/technical-reference/ad-fs-password-protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/technical-reference/ad-fs-password-protection.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#label:"question"

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @Kofl,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made to clarify the verbiage being used. 

To answer your question directly, the author meant that _**"Admins need to disable the username & password endpoints in their AD FS server for increased security if under an active attack"**_. Hopefully this addresses your concern. Changes will be live either end of this week or beginning of next. 

We will now be closing this thread. Thank you and have a most pleasant day. #please-close
