### ISSUE TITLE
Linux and Windows instructions?

### ISSUE THREAD

**Issue by marcnoon** [MicrosoftDocs/windowsserverdocs#5850]
Is their instruction for doing the same thing in Linux or a Linux shell in Windows?  I want to send a Linux customer or a Windows customer instructions from a reputable source.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH key management for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement#feedback)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by robinharwood** [comment]
Hi @marcnoon,

Thanks for your feedback and dedication to our documentation. 

These steps are specific to OpenSSH in Windows. Additional detailed documentation for common OpenSSH features is available online at [OpenSSH.com](https://www.openssh.com/manual.html).

The master [OpenSSH open source project](https://www.openssh.com/) is managed by developers at the OpenBSD Project. The Microsoft fork of this project is in [GitHub](https://github.com/PowerShell/openssh-portable). Feedback on Windows OpenSSH is welcomed and can be provided by creating GitHub issues in our [OpenSSH GitHub repo](https://github.com/PowerShell/openssh-portable).

 To follow up on this issue, leave us a comment with an @mention.

#please-close
