### ISSUE TITLE
Windows 2022

### ISSUE THREAD

**Issue by reuvygroovy** [MicrosoftDocs/windowsserverdocs#5851]
[Enter feedback here]

Windows 2022 was just released but there is no information if 2022 is supported and under what configurations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb311bf2-8548-000e-36a6-4ea4c01ac953
* Version Independent ID: d2966c17-b877-a879-bd7f-39c3758f0a77
* Content: [Supported Windows guest operating systems for Hyper-V on Windows Server](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-windows-guest-operating-systems-for-hyper-v-on-windows)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Supported-Windows-guest-operating-systems-for-Hyper-V-on-Windows.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/Supported-Windows-guest-operating-systems-for-Hyper-V-on-Windows.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by IngridAtMicrosoft** [comment]
#assign:dknappettmsft

**Comment by dknappettmsft** [comment]
Thanks for the feedback. Windows Server 2022 was added to this page near the end of September in the first table: Supported Windows Server guest operating systems. In the Notes column it says, "Hosted on Windows Server 2019 or above, Azure Stack HCI, version 20H2 or above.".

#please-close
