### ISSUE TITLE
https://github.com/mhmood2021/Windows2019RDP-US.git

### ISSUE THREAD

**Issue by mhmood2021** [MicrosoftDocs/windowsserverdocs#5855]
[اكتب ملاحظاتك هنا]

---
#### تفاصيل المستند

⚠ *تجنب تحرير هذا القسم. مطلوب لـ docs.microsoft.com ➟ ربط مشكلة GitHub.*

* ID: 9dfc391b-ab1f-523f-6b04-0076af58af7f
* Version Independent ID: 46d3c36b-7cd8-dffe-dd6b-0be74aff31dd
* Content: [Privacy settings for managed apps and desktops](https://docs.microsoft.com/ar-sa/windows-server/remote/remote-desktop-services/clients/remote-privacy-settings)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-privacy-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-privacy-settings.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @davidbel
* Microsoft Alias: **davidbel**

**Comment by Xelu86** [comment]
Hey mhmood2021,

Thanks again for contacting Microsoft. We value your feedback. 

We're unable to determine what the intent of your question is. If there are any errors or areas of improvement with said documentation, please let us know so we may better assist.

We're closing this issue but please feel free to reopen it and advise us what revisions may be needed. Thank you and have a most pleasant day. #please-close
