### ISSUE TITLE
Windows Server 2022 Support

### ISSUE THREAD

**Issue by ThatWindowsGuy** [MicrosoftDocs/windowsserverdocs#5857]
Windows Server 2022 supported Windows editions activated by KMS host are not included on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3b24b69-ab33-c1b1-b8e2-51c23bbba31d
* Version Independent ID: ebc3123c-57f7-0d2c-f875-9b6ac6c7a319
* Content: [Key Management Services (KMS) activation planning](https://docs.microsoft.com/en-us/windows-server/get-started/kms-activation-planning)
* Content Source: [WindowsServerDocs/get-started/kms-activation-planning.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/kms-activation-planning.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#assign:dknappettmsft

**Comment by dknappettmsft** [comment]
Thanks for the feedback. This information was added in September and is in the table 'Activation versions'.

#please-close
