### ISSUE TITLE
lines before and after 

### ISSUE THREAD

**Issue by tgelliott196** [MicrosoftDocs/windowsserverdocs#5860]
[is there a way to or can you add the ability to findstr to see X number of lines before and after?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b90f482-f48a-7d60-7ba9-bb5a1e837989
* Version Independent ID: 5a8e1ac5-3f4d-4da9-67c3-15a08d9a1b61
* Content: [findstr](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/findstr)
* Content Source: [WindowsServerDocs/administration/windows-commands/findstr.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/findstr.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @tgelliott196,

Thanks again for contacting Microsoft. We value your feedback. 

The ```findstr``` command does not have the ability to view a designated number of lines. It will continue its process on locating certain patterns in text until complete. There aren't any parameters designed that allow for showing only "x" lines/patterns before or after at a time.

Alternatively, you can use PowerShell to perform this action. Running the following in this example will show the first 5 lines of the Fruits.txt file:

```powershell
Get-Content C:\Users\Administrator\Desktop\Fruits.txt | Select -First 5
```
![image](https://user-images.githubusercontent.com/103963494/188777164-1d34ad08-f733-4bb2-903f-25a9915829d6.png)

The same can be done to see the last 10 lines in the same file:

```powershell
Get-Content C:\Users\Administrator\Desktop\Fruits.txt | Select -Last 10
```
![image](https://user-images.githubusercontent.com/103963494/188777412-e96fc84d-91b6-43ef-99d8-e0ce1aa29f7a.png)

You can also search for patterns in PowerShell similarly to ```findtr```, such as finding all the "apples" in the text file:

```powershell
Get-Content C:\Users\Administrator\Desktop\Fruits.txt | Select-String -Pattern "apple"
```
![image](https://user-images.githubusercontent.com/103963494/188778382-6b2e07ee-6b79-4158-a31e-d8179ee5f6a1.png)

Lastly, you can combine both examples above to search for the first 4 lines that contain "apple":
```powershell
Get-Content C:\Users\Administrator\Desktop\Fruits.txt | Select -First 4 | Select-String -Pattern "apple"
```
![image](https://user-images.githubusercontent.com/103963494/188778624-52662d50-acf3-42f1-8fbb-d88d1c5ebed3.png)

PowerShell is a much more versatile tool based on what you'd like to accomplish. If you'd like to submit a feature request in the future, please refer to our [Microsoft Feedback Hub](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332) which can be accessed by searching for "Feedback Hub" in the Start menu. We hope that the above examples are helpful.

We will be closing this thread. Thank you and have a most pleasant day. #please-close

**Comment by mspaansen** [comment]
Unsubscribe

Op wo 7 sep. 2022 04:17 schreef Xelu86 ***@***.***>:
