### ISSUE TITLE
Permissions of C:\Users\username\.ssh\authorized_keys

### ISSUE THREAD

**Issue by DavidA2014** [MicrosoftDocs/windowsserverdocs#5864]
In section: https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement#standard-user

I found that the permission settings of C:\Users\username\.ssh\authorized_keys are critical. 

See step 'Setup permissions properly (important!!!)' of https://stackoverflow.com/a/50502015/4940771

The instructions need this information. Authentication didn't work for me without making these permission settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH key management for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement#standard-user)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by robinharwood** [comment]
Hi @DavidA2014 ,

Thanks for the feedback and dedication to our documentation.

Whilst I do agree the permissions for `_C:\Users\username\.ssh\authorized_keys_ are important, the default permissions for a user profile in Windows is NT AUTHORITY\SYSTEM - full control, BUILTIN\Administrators - full control, and the user also has full control. Validating using the defaults, I was able to successfully able to deploy the standard user's public key. Please make sure you have the latest Windows updates. In the meantime, I am marking this documentation issue has been resolved and we are closing the issue. #please-close

To follow up on this documentation issue, leave us a comment with an @mention. To get assistance or support for your product issue, we recommend that you engage with the product community or open a ticket with Microsoft Support. For more information, see [Contact Microsoft Support](https://support.microsoft.com/ContactUs)

Thanks,

Robin
