### ISSUE TITLE
click "This Product" at page bottom

### ISSUE THREAD

**Issue by DSPatrick** [MicrosoftDocs/windowsserverdocs#5866]
[Enter feedback here]
clicking "This Product" navigates to
https://windowsserver.uservoice.com/forums/295047-general-feedback
which gives us
![image](https://user-images.githubusercontent.com/37478978/132715184-c2d63f8e-18b9-43bd-85d9-808a1d614d34.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 418dc0a0-0312-9d6f-b2dc-2eb4841285ba
* Version Independent ID: 600b0469-3c96-5737-c39b-2ce9021b0f5a
* Content: [Windows Server 2016 Functional Levels](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/active-directory-functional-levels)
* Content Source: [WindowsServerDocs/identity/ad-ds/active-directory-functional-levels.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/active-directory-functional-levels.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by Xelu86** [comment]
Hey DSPatrick,

Thanks again for contacting Microsoft. We value your feedback. 

This issue was corrected several months ago, and this thread was not closed. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
