### ISSUE TITLE
Parameter names getting auto translated

### ISSUE THREAD

**Issue by tylerschmidtjp** [MicrosoftDocs/windowsserverdocs#5868]
Hi, I noticed on the certreq page that the parameter names are getting auto translated into japanese.

![image](https://user-images.githubusercontent.com/90454989/132847806-6752d315-f7f9-4930-ae04-f0814c088994.png)

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey tylerschmidtjp,

Thanks again for contacting Microsoft, we value your feedback. 

A documentation correction was made a while ago and this issue was not closed. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
