### ISSUE TITLE
Missing link to Schema docs

### ISSUE THREAD

**Issue by Mr-M33533K5** [MicrosoftDocs/windowsserverdocs#5869]
In the first point of the "Active Directory also includes:" section there is a reference to docs about "Schema" but there is no link.

The link that should be there is:
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc756876(v=ws.10)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bb772ec-10a8-1c86-8af7-5e1d51912866
* Version Independent ID: 743875a3-e418-d81f-1a70-474a3471bfcb
* Content: [Active Directory Domain Services Overview](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/get-started/virtual-dc/active-directory-domain-services-overview)
* Content Source: [WindowsServerDocs/identity/ad-ds/get-started/virtual-dc/Active-Directory-Domain-Services-Overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/get-started/virtual-dc/Active-Directory-Domain-Services-Overview.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by Xelu86** [comment]
#assign:xelu86
