### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by 4C3T** [MicrosoftDocs/windowsserverdocs#5872]
[Enter feedback here]
Neither of the top two commands had any affect:
PS C:\Users\xxxx> Get-WindowsFeature HostGuardian
Get-WindowsFeature : The term 'Get-WindowsFeature' is not recognized as the name of a cmdlet, function, script file, or
 operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try a
gain.
At line:1 char:1
+ Get-WindowsFeature HostGuardian
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-WindowsFeature:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\xxxx> Install-WindowsFeature HostGuardian -Restart
Install-WindowsFeature : The term 'Install-WindowsFeature' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct a
nd try again.
At line:1 char:1
+ Install-WindowsFeature HostGuardian -Restart
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Install-WindowsFeature:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

---

I'm running Windows 10 Enterprise, version 21H1, OS version 19043.1165 with Windows Feature Experience Pack 120.2212.3530.0. Swedish, also x64-bit.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e5237ef-7c83-f3cc-ab0e-90acc4e3fdac
* Version Independent ID: fb5b347f-f70b-305f-2cd2-5b0a0501042d
* Content: [Troubleshooting Guarded Hosts](https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-troubleshoot-hosts)
* Content Source: [WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-troubleshoot-hosts.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-troubleshoot-hosts.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @rpsqrd
* Microsoft Alias: **ryanpu**

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. 

The documentation and commands in question apply only to Windows Server 2016+ as it is part of RSAT (Remote Server Administration Tool). This is the only environment where the `Get-WindowsFeature` will function:

![image](https://user-images.githubusercontent.com/103963494/198423536-7d272f80-2542-478f-b9ed-d537f6591647.png)

If you're running Windows Server natively or in a VM, you can learn more about this cmdlet [here](https://learn.microsoft.com/en-us/powershell/module/servermanager/get-windowsfeature?view=windowsserver2022-ps).

Doing some digging, it appears that for non-Server instances, the command to perform the same action is `Enable-WindowsOptionalFeature -Online -FeatureName "HostGuardian" -All`:

![image](https://user-images.githubusercontent.com/103963494/198438431-0ea4c39f-9549-4100-a864-4ee2efd12ccb.png)

You can learn more about the `Enable-WindowsOptionalFeature` cmdlet [here](https://learn.microsoft.com/en-us/powershell/module/dism/enable-windowsoptionalfeature?view=winserver2012-ps&redirectedfrom=MSDN).

We hope this clarifies your concern. We will now be closing this thread. We do wish that you have a most pleasant day!
