### ISSUE TITLE
Admin rights

### ISSUE THREAD

**Issue by julianddavidson** [MicrosoftDocs/windowsserverdocs#5873]
The 64bit Windows download requires admin rights to install, even though the documentation says it doesn't require admin rights for a user to install it into their own context. They do. Version 1.2.23220.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ab98fc-fea2-a11a-e5ca-de1430211d97
* Version Independent ID: 4d9943c3-fef7-ca86-bd03-1241a04b8135
* Content: [Get started with the Windows Desktop client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop#install-the-client)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by davidbordenwi** [comment]
When will this be fixed.  This client is updated constantly.  We need a way to install in user context via INTUNE. The switches that are supposed to do that do not work and it installs in admin context regardless.

**Comment by dknappettmsft** [comment]
Closing the loop on this - this is fixed in the client and it can be installed without admin rights.

#please-close
