### ISSUE TITLE
netsh routing

### ISSUE THREAD

**Issue by CarlWebster** [MicrosoftDocs/windowsserverdocs#5875]
Subcontexts
Netsh contexts can contain both commands and additional contexts, called subcontexts. For example, within the Routing context, you can change to the IP and IPv6 subcontexts.

To display a list of commands and subcontexts that you can use within a context, at the netsh prompt, type the context name, and then type either /? or help. For example, to display a list of subcontexts and commands that you can use in the Routing context, at the netsh prompt (that is, netsh>), type one of the following:

routing /?

routing help

This is what I get on Windows Server 2019:

netsh>routing /?
The following command was not found: routing /?.
netsh>routing help
The following command was not found: routing help.
netsh>routing
The following command was not found: routing.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 018d29d0-d1e2-09bb-57a6-7cad7361f80a
* Version Independent ID: 58af419b-3d83-573f-bf54-07a5e37cb5a0
* Content: [Netsh Command Syntax, Contexts, and Formatting](https://docs.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh-contexts)
* Content Source: [WindowsServerDocs/networking/technologies/netsh/netsh-contexts.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/netsh/netsh-contexts.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey CarlWebster,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made updating the examples and text for `netsh`. The initial example was supposed to reflect `netsh interface ipv4 add route help`. Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
