### ISSUE TITLE
Collecting performance Data

### ISSUE THREAD

**Issue by jasawan** [MicrosoftDocs/windowsserverdocs#5881]
## Download Windows Admin Center 
[After Installing Windows Admin Center ([use this link to download](https://www.microsoft.com/en-us/evalcenter/evaluate-windows-admin-center)) were we can collected Performance Profile on setting  Development click [advance](https://minint:8081/settings/) ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6eeacf83-f081-d3ac-2d08-60bf6acde0a4
* Version Independent ID: 20153ee2-be3c-5a77-3fba-0b5bfe763bec
* Content: [Get started with Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/get-started#view-powershell-scripts-used-in-windows-admin-center)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/use/get-started.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/use/get-started.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by trungtran-msft** [comment]
Hey @jasawan, 

If I understand your statement correctly, you want to collect the performance data. 

If you go to Settings > Performance Profile > Toggle button on. Then you should be able to collect the performance data. 

![image](https://user-images.githubusercontent.com/79549145/140423913-f02b462e-bff4-4b50-ac32-2bc8ee09280f.png)

**Comment by craigcaseyMSFT** [comment]
Hello @jasawan,

Thanks for contacting Microsoft. We value your feedback.

We have tested the problem as described in this issue and either couldn't replicate the stated result or have verified that no documentation change is required.

As a result, we’re closing this thread.

Thank you again and have a most pleasant day.
#please-close
