### ISSUE TITLE
Azure AD Registered device 

### ISSUE THREAD

**Issue by rufioIK708** [MicrosoftDocs/windowsserverdocs#5882]
[Enter feedback here]

This document's last update is from 2017.  It looks like there are more fields than when it was written and some may have changed to different names.  I'm guessing "Last Updated" refers to the current "Activity" field, but it would be nice if the doc was up to date.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 459ecaec-8f09-2b0b-b6ed-daa2b8f29ef5
* Version Independent ID: 3dcfa55d-2778-e8b9-acc5-c29bdc9394e4
* Content: [Device Registration Technical Reference](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/technical-reference/device-registration-technical-reference#registered-devices)
* Content Source: [WindowsServerDocs/identity/ad-fs/technical-reference/Device-Registration-Technical-Reference.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/technical-reference/Device-Registration-Technical-Reference.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
This is documentation for on-premises Active Directory, not Azure Active Directory. Closing.
