### ISSUE TITLE
incorrect command

### ISSUE THREAD

**Issue by NickEales** [MicrosoftDocs/windowsserverdocs#5884]
`Start-Service sshd`

should read

`Start-Service ssh-agent`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH key management for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by robinharwood** [comment]
Hi @NickEales, are you able to clarify which section you are referencing?

Thanks,

Robin

**Comment by NickEales** [comment]
Looks like this was already addressed in a different way in change: #5722

https://github.com/MicrosoftDocs/windowsserverdocs/pull/5722/files

**Comment by robinharwood** [comment]
Thanks for you dedication to our documentation and for confirming @NickEales.

#please-close
