### ISSUE TITLE
Missing  v10.6.8 release notes.

### ISSUE THREAD

**Issue by flemingm** [MicrosoftDocs/windowsserverdocs#5885]
Was looking for latest release notes for current version of MacOS RDP desktop client.

Missing latest release notes for v10.6.8

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5982a31b-7825-9dde-8173-4bbb7cdb159b
* Version Independent ID: a3d6fba1-4a23-6f0b-5bad-d7b7862126d9
* Content: [What's new in the macOS client](https://docs.microsoft.com/en-ca/windows-server/remote/remote-desktop-services/clients/mac-whatsnew#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/mac-whatsnew.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/mac-whatsnew.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey flemingm,

Thanks again for contacting Microsoft, we value your feedback. 

A documentation change was made with this information and this issue was not closed. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
