### ISSUE TITLE
Doc Improvement: Renewal Instructions

### ISSUE THREAD

**Issue by jamesaepp** [MicrosoftDocs/windowsserverdocs#5890]
Doc should include what steps (if any) are required if the cert is renewed, particularly for a non-ADCS acquired certificate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64dadae1-7656-54e0-099d-620229836135
* Version Independent ID: 8f86a34d-ce81-d571-e118-29169a2c0df3
* Content: [SMB over QUIC](https://docs.microsoft.com/en-us/windows-server/storage/file-server/smb-over-quic)
* Content Source: [WindowsServerDocs/storage/file-server/smb-over-quic.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/smb-over-quic.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @nedpyle
* Microsoft Alias: **inhenkel**

**Comment by nedpyle** [comment]
I concur, will be adding this by GA.

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by jamesaepp** [comment]
I reviewed the document linked in the original issue report and found nothing which addresses the cert renewal issue. Is this coming shortly or is it being documented elsewhere?

**Comment by nedpyle** [comment]
> I reviewed the document linked in the original issue report and found nothing which addresses the cert renewal issue. Is this coming shortly or is it being documented elsewhere?

Fix finally coming, thanks, James

**Comment by dknappettmsft** [comment]
Hi @jamesaepp, the changes have been made and they should be visible later today. Thanks for your patience.

**Comment by jamesaepp** [comment]
@dknappettmsft doc improvement looks good to me and addresses the reason I opened the ticket.

From the point of view of the product itself though, has this functionality been tested in a lab with a true expiration/renewal lapse to see what happens? This is probably best for the SMBoQUIC product group/engineers themselves, but I'll continue:

My experience with ADCS is limited, but I have seen certificates renew before their actual expiration. So for example, I've seen certificates get to about 42 days remaining before expiration, and then they'll immediately auto renew to a whole new 365 day period. This makes things less than predictable from a product perspective.

I'm not sure how the certificate rotation works exactly. I'm now starting to wonder if the first certificate remains on the system or if it is replaced by the renewed one. If the old certificate remains, then there's no problem. But if the old certificate is deleted from the store....that could be a problem when auto-renewals happen.

**Comment by nedpyle** [comment]
Hiya.
> My experience with ADCS is limited, but I have seen certificates renew before their actual expiration. So for example, I've seen certificates get to about 42 days remaining before expiration, and then they'll immediately auto renew to a whole new 365 day period. This makes things less than predictable from a product perspective.
> 
> I'm not sure how the certificate rotation works exactly. I'm now starting to wonder if the first certificate remains on the system or if it is replaced by the renewed one. If the old certificate remains, then there's no problem. But if the old certificate is deleted from the store....that could be a problem when auto-renewals happen.

The default autorenewal attempt is when you're down to 20% of the remaining certificate lifetime. But the old issued certificate is not deleted unless you intentionally set that flag on your template when you are creating it, so the old cert will exist even past its renewal and expiration. You can also add a Purpose (EKU) to your template of "Encryption" in addition to the "Server Authentication" EKU we require, which will override any autorenewal deletion flags on the template. It's not something we require. I can make a note of all this in the article.
