### ISSUE TITLE
The Support button goes to a closed User Voice page.

### ISSUE THREAD

**Issue by Johns-305** [MicrosoftDocs/windowsserverdocs#5898]
Title says it all.  Shouldn't there be a robot that checks thest things?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f7187f-7e2e-da7f-6f46-46568be43db7
* Version Independent ID: 49714e7e-ecfb-dba3-f43a-17b6ca677fa6
* Content: [Remote Desktop clients](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-clients)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey Johns-305,

Thanks again for contacting Microsoft. We value your feedback.

Feedback for this product can still be provided by visiting one of the following:

- https://feedbackportal.microsoft.com/
- [Feedback Hub app](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332) (if you're running a Windows 10/11 OS)

The last section of this page also includes a way to provide feedback:

![image](https://github.com/MicrosoftDocs/windowsserverdocs/assets/103963494/54336d69-474a-422f-9e13-f9db71ed1084)

We will now be closing this thread. Thank you and have a most pleasant day.
#please-close
