### ISSUE TITLE
Feature Request: When using the Remote Desktop iOS app it adheres to the Mouse settings for my host device. Unfortunately I have switched right-click and left-click so the iOS app is now registering single tap as left-click. I would like this mouse input swap to only occur on my host OS and not also be present when using the iOS app.

### ISSUE THREAD

**Issue by zgoldin** [MicrosoftDocs/windowsserverdocs#5899]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d21e96b-c8a6-7f9f-76e1-62ee4fbde62b
* Version Independent ID: 5530201e-2ff5-19de-5990-1a996cf5ef2e
* Content: [Get started with the iOS client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-ios)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-ios.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-ios.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
#assign:xelu86
