### ISSUE TITLE
Grammatical mistake

### ISSUE THREAD

**Issue by karim-buzdar** [MicrosoftDocs/windowsserverdocs#59]
Change the following sentence under minimum processor requirements

Coreinfo is a tool you can use to confirm which of these capabilities you CPU has.

to 

Coreinfo is a tool you can use to confirm which of these capabilities *your* CPU has.

**Comment by lizap** [comment]
Hi, Karim - can you either send the name of the article this is in or, if you're willing, make the change yourself? (In the article, click Edit to get to the source.)

Thanks!
