### ISSUE TITLE
Cannot connect if RD Gateway HTTPS is not using port 443

### ISSUE THREAD

**Issue by ongpok** [MicrosoftDocs/windowsserverdocs#590]
I noticed that if we are not using HTTPS port 443 for RD Gateway, it will have the issue of "Oops, we couldn't connect to xxx" when connecting to the app. While checking browser console, the error is showing WebSocketTransport is trying to connect wss://xxxxxx:443, which it doesn't follow our custom port defined in RD Gateway.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Service: **unspecified**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by leftfire** [comment]
i hava find the same problem- -!

**Comment by davidbel** [comment]
@ongpok / @leftfire : If you are still having the same issue, please send mail to the address on the about page so we can investigate further. Thank you.
