### ISSUE TITLE
Microsoft has remained **steadfast against**?

### ISSUE THREAD

**Issue by olumideo** [MicrosoftDocs/windowsserverdocs#5901]
Hi,
I think you have an important text that indicates the opposite of what you meant to write.

In the line 
"Microsoft has remained **steadfast against** these principles ..."

Did you mean to write that:
"Microsoft has remained **steadfast about** (or **for**) these principles ..."

Best regards,
Olumide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f791f7df-719f-781c-2d4c-21a9770de5e2
* Version Independent ID: 9bb48040-94c7-7286-9e36-0a2a81973e4a
* Content: [Beginning your General Data Protection Regulation (GDPR) journey for Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/security/gdpr/gdpr-winserver-whitepaper)
* Content Source: [WindowsServerDocs/security/gdpr/gdpr-winserver-whitepaper.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/gdpr/gdpr-winserver-whitepaper.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @nirb-ms
* Microsoft Alias: **nirb**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
@olumideo Thank you for your feedback.  This issue has been addressed.
