### ISSUE TITLE
Change all instances to AD FS

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/windowsserverdocs#5902]
Hi folks,

Can we correct the docs so that "ADFS" is NOT used.  Change to "AD FS".  This article for example is inconsistent, and the title is correct, but the body content is not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2dd1426-8251-d4a1-1082-286e0cc78b45
* Version Independent ID: b205687f-f9f9-a3f5-772f-3fad427bf828
* Content: [Delegate AD FS Powershell Commandlet Access to Non-Admin Users](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/delegate-ad-fs-pshell-access)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/delegate-ad-fs-pshell-access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/delegate-ad-fs-pshell-access.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by dknappettmsft** [comment]
Thanks @r-milne for raising this, I've corrected around 200 occurrences across the repo (apart from URIs, PowerShell cmdlets, etc.). The changes should be made live in a few hours.

#please-close
