### ISSUE TITLE
Job file syntax needs to be documented

### ISSUE THREAD

**Issue by jgriffitts** [MicrosoftDocs/windowsserverdocs#5910]
I just wasted some time trying to figure out job files, specifically the syntax for /XF. It is not mentioned at all  that the file names need to be listed on lines _after_ the /XF line. Trying to put them on the same line as /XF, with a colon or a space separator, results in:
```
ERROR : Invalid Parameter #1 : "/JOB:j"
```
Not helpful at all. A simple example of a job file with /XD or /XF would have made it immediately clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @jgriffitts,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made and will be live after the next business day. Additional clarity has been added into the job options parameter. We're taking your feedback into consideration regarding command reference examples.

We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
