### ISSUE TITLE
What's New Updates out of date!

### ISSUE THREAD

**Issue by JCoreMS** [MicrosoftDocs/windowsserverdocs#5917]
I had a customer advise me of a recent change that incorporated a critical feature added as preview for Teams Optimizations.  My first stop was this document which is dated July 2021 but clearly there is a list of updates and fixes in the Apple Store. 

Would it be better to simply add a link to the Apple Store's app with the latest updates here?

https://apps.apple.com/app/microsoft-remote-desktop/id1295203466?mt=12 

IF YES, I will gladly update the overall document with a PR.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0517ea6a-9417-31a8-39a5-f6128387fee5
* Version Independent ID: 7636ec70-e1dd-8c6b-516c-8af324d9f645
* Content: [Get started with the macOS client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-mac)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made updating the details for the following releases:

- 10.6.8
- 10.7.1
- 10.9.1 

Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
