### ISSUE TITLE
Windows 10 Disk Manager handles Dynamic to Basic easily via shrinking then converting

### ISSUE THREAD

**Issue by VinceS2** [MicrosoftDocs/windowsserverdocs#5926]
I have just performed this operation on a pair of 2TB SSD's, forming a 4TB dynamic disk. Due to a mobo change I want to unpick this. First was to get down to around 1.5TB stored. Then use Windows Disk Manager (put diskmgmt in search bar) to shrink the Volume (Drive D for me), which it did to the default allowed amount. That showed disk 2 100% unallocated and disk 1 with about 30% unallocated. With no input from me, the shrink process relocated files as it needed to, so defragmenting was NOT needed. It did take about 10 minutes to do. Next right click disc 2 and select 'Convert to Basic'. Then right click the now blank disc 2 and put a partition on it in the normal way, leaving at least 6% for overprovisioning. Simple. Gotta love that!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 722fedef-d6a4-5ed6-526b-d6dd1a4d0642
* Version Independent ID: 10f9b44a-5a88-cb84-293f-1baf62359299
* Content: [Change a dynamic disk back to a basic disk](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/change-a-dynamic-disk-back-to-a-basic-disk)
* Content Source: [WindowsServerDocs/storage/disk-management/change-a-dynamic-disk-back-to-a-basic-disk.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/change-a-dynamic-disk-back-to-a-basic-disk.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
assign:xelu86

**Comment by Xelu86** [comment]
Hey @VinceS2,

Thanks again for contacting Microsoft. We value your feedback. We're glad to hear that you're enjoying a feature in our product! If there are any errors or areas of improvement with said documentation that needs to be addressed, please let us know. We will be closing this. Thank you and have a most pleasant day. 

#please-close
