### ISSUE TITLE
Old content

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windowsserverdocs#5935]
How come this does not include the newer server operating systems? If there is another version of this for them, please add a link
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c1a07a2-6191-0e09-748d-c3f526e0ed00
* Version Independent ID: 636f4465-11b0-5a12-2f12-0d05f6b05b86
* Content: [Best Practices for Securing Active Directory](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/best-practices-for-securing-active-directory)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Best-Practices-for-Securing-Active-Directory.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Best-Practices-for-Securing-Active-Directory.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by IngridAtMicrosoft** [comment]
The document states the operating systems that it applies to with this line:
Applies to: Windows Server 2022, Windows Server 2019, Windows Server 2016, Windows Server 2012 R2, Windows Server 2012

If you have further questions, please open a new GitHub issue.
