### ISSUE TITLE
Duplicate SPN found, aborting operation

### ISSUE THREAD

**Issue by MooreSys** [MicrosoftDocs/windowsserverdocs#5940]
Duplicate SPN found, aborting operation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dde1639a-439a-a95e-028f-62fbbee058ec
* Version Independent ID: 357a5c2e-c4f8-d618-1740-5235d9a26a2a
* Content: [Manually Configure a Service Account for a Federation Server Farm](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/manually-configure-a-service-account-for-a-federation-server-farm)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Manually-Configure-a-Service-Account-for-a-Federation-Server-Farm.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Manually-Configure-a-Service-Account-for-a-Federation-Server-Farm.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by cmcclister** [comment]
#label:"doc-bug"

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @MooreSys,

Thanks again for contacting Microsoft. We value your feedback.

As we understand it, you're describing an issue with the product compared to an issue with the documentation. GitHub isn't quite the right location or channel if searching for technical support, deeper specifics of the product or feature requests as it is completely outside our scope. If there are any issues within the content itself, such as incorrect code, verbiage, etc., please let us know.

I did find this article on [Duplicate SPN](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc733945(v=ws.10)?redirectedfrom=MSDN#resolve) (don't know if this is the fix you need) along with the [SPN Overview](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc731241(v=ws.10)?redirectedfrom=MSDN).

As the error you're receiving is quite specific, we recommend that you engage with the product community or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).

Additional support forums listed below:
- TechNet: https://social.technet.microsoft.com/Forums/windowsserver/en-US/home?category=&forum=&filter=&sort=relevancedesc&brandIgnore=true&searchTerm=Duplicate+SPN+found%2C+aborting+operation%21
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Hopefully one of the community experts may be able to better assist. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
