### ISSUE TITLE
Deploy Certificates

### ISSUE THREAD

**Issue by gerrynicol** [MicrosoftDocs/windowsserverdocs#5942]
A couple of points which I don't think are clear here.

Does the certificate need to be deployed to Active Directory only if the VPN server is domain joined? 
For a VPN server that is not domain joined what is the manual installation process described here? Is it just a certificate import into the computer trusted root certificate store?

"For environments where the VPN server is not joined to the Active Directory domain, the cloud root certificates must be added to the Trusted Root Certification Authorities store manually."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e575e6c6-ee12-fee9-fa27-f88f56643325
* Version Independent ID: fe0b17a1-4f40-3a9e-1be1-6d36eb870293
* Content: [Deploy Conditional Access root certificates to on-premises AD](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/vpn-deploy-cond-access-root-cert-to-on-premise-ad)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/vpn-deploy-cond-access-root-cert-to-on-premise-ad.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/vpn-deploy-cond-access-root-cert-to-on-premise-ad.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by anaharris-ms** [comment]
#please-close Fixed in: https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/3398
