### ISSUE TITLE
Incorrect or Incomplete Step: Settings Tab

### ISSUE THREAD

**Issue by Maraudier** [MicrosoftDocs/windowsserverdocs#5944]
[Enter feedback here]
(Optional) Select the Settings tab, and in the Policy Removal section, select Redirect the folder back to the local userprofile location when the policy is removed (this setting can help make Folder Redirection behave more predictably for administrators and users).

The settings tab does not have configurable and only shows the setting that has been selected for the GPO. Unless there is another settings tab. If there is the location of that tab should be identified in the step.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3273d609-8cdb-19b8-6e72-e6c763904c47
* Version Independent ID: cf80c8f5-49f6-43a4-bb8e-b5849beb818b
* Content: [Deploy Folder Redirection with Offline FilesDeploy Folder Redirection with Offline Files](https://docs.microsoft.com/en-us/windows-server/storage/folder-redirection/deploy-folder-redirection)
* Content Source: [WindowsServerDocs/storage/folder-redirection/deploy-folder-redirection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/folder-redirection/deploy-folder-redirection.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by cmcclister** [comment]
#label:"doc-bug"

**Comment by craigcaseyMSFT** [comment]
Hello @Maraudier,

Thanks for contacting Microsoft. We value your feedback.

Documentation changes have been made to clarify and acknowledge this issue. The doc changes will be live after the next business day.

Thank you again and have a most pleasant day.
#please-close
