### ISSUE TITLE
Remote Desktop Virtualization Host role needs Desktop Experience, why?

### ISSUE THREAD

**Issue by FaberfoX** [MicrosoftDocs/windowsserverdocs#5946]
Who was the genius that decided that you need desktop experience to be a remote desktop virtualization host? I now need this feature on a cluster that's been running for a couple of years, trying to install it fails without providing any meaningful errors, searching for the error mentions remote management or firewall issues, and only after searching for hours I found a mention of it being a deprecated feature. HSMH (Heavily Shaking My Head) in disbelief.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5a5e3d9-5583-c54f-374e-2dd4241e40d5
* Version Independent ID: 037b56ff-aec2-6238-c8c4-caa107655332
* Content: [Features removed or no longer developed starting with Windows Server 2019](https://docs.microsoft.com/en-us/windows-server/get-started/removed-deprecated-features-windows-server-2019)
* Content Source: [WindowsServerDocs/get-started/removed-deprecated-features-windows-server-2019.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/removed-deprecated-features-windows-server-2019.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by cmcclister** [comment]
#label:"question"

**Comment by cmcclister** [comment]
#label:"product-feedback"

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @FaberfoX,

Thanks again for contacting Microsoft. We value your feedback.

We apologize for the negative impact that you're experiencing with one of our products. As we understand it, you may be describing a problem with the product and not with the documentation. GitHub is not quite the right location if searching for technical support or feature requests as it is completely outside our scope. It is mainly for documentation updates, improvement, and clarity. If there are any issues within the content itself, please let us know.

We do recommend that you engage with the product community or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs) to see if one of our community experts may be able to better assist with your experience. 

Additional support forums listed below:
- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Thank you again for reaching out as we consider all user feedback. As we cannot assist in this manner, we will be closing this thread. We do wish you a most pleasant day! 
#please-close
