### ISSUE TITLE
Server 2022 content

### ISSUE THREAD

**Issue by DSPatrick** [MicrosoftDocs/windowsserverdocs#5948]
[Enter feedback here]
please add relevant info about an in-place upgrade to Server 2022

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 505fe07b-6fdd-4887-3c8b-15405c5d8308
* Version Independent ID: 25645df2-0ffb-4cc3-a8d2-5466edd309fb
* Content: [Overview of Windows Server upgrades](https://docs.microsoft.com/en-us/windows-server/upgrade/upgrade-overview)
* Content Source: [WindowsServerDocs/upgrade/upgrade-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/upgrade/upgrade-overview.md)
* Product: **windows-server**
* Technology: **upgrade**
* GitHub Login: @RobHindman
* Microsoft Alias: **robhind**

**Comment by DSPatrick** [comment]
well it should be more than a request, when a new OS RTMs at least a minimum of documentation should be available

**Comment by cmcclister** [comment]
#label:"docs-enhancement"

**Comment by robinharwood** [comment]
Hi @DSPatrick 

Thanks for your dedication to our documentation.  I appreciate it is frustrating we haven’t been able to provide this information sooner, I apologise for the delayed response and thank you for your patience. We've submitted a documentation change based, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. If you need to follow up on this issue, leave us a comment with an @mention.

#assign:robinharwood
#please-close
