### ISSUE TITLE
Great documentation!

### ISSUE THREAD

**Issue by Kamex009** [MicrosoftDocs/windowsserverdocs#5954]
Thank you for the info!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fed146e-5363-f935-8b4a-895dc13030b4
* Version Independent ID: 27158ca2-510f-9f60-9df5-3a38630c228c
* Content: [Manage Azure IaaS virtual machines](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/azure/manage-azure-vms)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/azure/manage-azure-vms.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/azure/manage-azure-vms.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by dknappettmsft** [comment]
Thank you!

#please-close
