### ISSUE TITLE
Windows 11 Support

### ISSUE THREAD

**Issue by reschrei** [MicrosoftDocs/windowsserverdocs#5956]
Could we get this page updated with activation support for Windows 11? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3b24b69-ab33-c1b1-b8e2-51c23bbba31d
* Version Independent ID: ebc3123c-57f7-0d2c-f875-9b6ac6c7a319
* Content: [Key Management Services (KMS) activation planning for Windows Server](https://docs.microsoft.com/en-us/windows-server/get-started/kms-activation-planning)
* Content Source: [WindowsServerDocs/get-started/kms-activation-planning.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/kms-activation-planning.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @dknappettmsft
* Microsoft Alias: **daknappe**

**Comment by dknappettmsft** [comment]
Thanks for the feedback. This article has been updated for Windows 11 and the changes should be visible later today.

#please-close
