### ISSUE TITLE
VPN_Profile.ps1 not working on Windows 11

### ISSUE THREAD

**Issue by wander1992** [MicrosoftDocs/windowsserverdocs#5963]
Hi Team,

Since Windows 11 the detection and deletion of existing VPN’s with the same same doesn’t work anymore. The error message is:

User SID is S-X-XX-1-XXXXXXXXXXX
Unable to remove existing outdated instance(s) of Info Support profile: A general error occurred that is not covered by a more specific error code.

Specifically those methods don’t work anymore:

$session.EnumerateInstances
$session.DeleteInstance

Therefore we can’t update our existing VPN’s. Do you have any idea how we can solve this?

Best regards,

Wander

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e14da1-102d-3ddf-e2a1-a20ce533b95a
* Version Independent ID: 374edc4c-f527-b7b7-c291-353928b97d8d
* Content: [Configure Windows 10 Client Always On VPN Connections](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by cmcclister** [comment]
#label:"doc-bug"

**Comment by anaharris-ms** [comment]
#please-close Fixed in: https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/3398
