### ISSUE TITLE
Why are we recommending to remove ciphers and modify the default cipher location in public AD FS documentation?

### ISSUE THREAD

**Issue by ToddMaxey** [MicrosoftDocs/windowsserverdocs#5966]
Why are we recommending to remove ciphers and modify the default cipher location in public AD FS documentation???
https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/manage-ssl-protocols-in-ad-fs#enabling-or-disabling-additional-cipher-suites

We should be indicating that –
There are two Microsoft supported methods of configuring cipher suites:
Via GP: https://msdn.microsoft.com/en-us/library/windows/desktop/bb870930(v=vs.85).aspx      
Via cmdlets: https://technet.microsoft.com/en-us/library/dn296632.aspx

Is there some AD FS needful that needs to have the value as REG_MULTI_SZ
As opposed to the GP location which is REG_SZ?

**Comment by cmcclister** [comment]
#label:"doc-enhancement"
