### ISSUE TITLE
Windows 11 GVLK Clarification

### ISSUE THREAD

**Issue by blakebourgeois** [MicrosoftDocs/windowsserverdocs#5967]
The document was updated to include information on Windows Server 2022 but does not currently have any information regarding configuring a GVLK for Windows 11.

It appears that the Windows 10 keys work for Windows 11 when utilizing a KMS. If this is true/intended, could this document be updated to confirm that this is the correct route to go, or publish new Windows 11 GVLKs if distinct? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 666e84fa-56d3-9cfb-58a6-8dd1b86b74cb
* Version Independent ID: 6c6de03f-8da2-0fee-8e0e-0e98c31855d9
* Content: [Key Management Services (KMS) client activation and product keys for Windows Server and Windows](https://docs.microsoft.com/en-us/windows-server/get-started/kms-client-activation-keys)
* Content Source: [WindowsServerDocs/get-started/kms-client-activation-keys.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/kms-client-activation-keys.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @dknappettmsft
* Microsoft Alias: **daknappe**

**Comment by dknappettmsft** [comment]
Thanks for raising this issue.  The documentation has been updated to reflect this.

#please-close
