### ISSUE TITLE
Text correction

### ISSUE THREAD

**Issue by mikaelcavrak** [MicrosoftDocs/windowsserverdocs#597]
Hi,
The text "If your organization is federated with Azure AD, you can use Azure Multi-Factor Authentication to secure AD FS resources, both on-premises and in the cloud. "  Is it not misguiding? What about the the following Scenario.. I'm switching to PTA for everything that has to do with Azure AD, but I still keep my onprem AD FS for other relying partys. According to the intro text, I will not be able to utilize  Azure MFA with AD FS to secure resources.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae96cfcf-0a50-7e13-30c8-43e3730e184f
* Version Independent ID: 9d8ed7b7-eec6-1b95-40b8-24a13361f66d
* Content: [Configure AD FS 2016 and Azure MFA](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by MicrosoftGuyJFlo** [comment]
You can still use your ADFS servers but pass the MFA responsibilities to Azure MFA.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
