### ISSUE TITLE
Example code resulted in error.

### ISSUE THREAD

**Issue by stephenregisterTJT** [MicrosoftDocs/windowsserverdocs#5976]
[Enter feedback here]
**When entering the 'Set-AdfsSslCertificate -thumbprint []' command an error is returned: errorcode 0x80090322 'while using Negotiate authentication: an unknown security error occurred.'

This is while running elevated PS as admin user and attempting to update our ADFS server as localhost. 
Is there a step missing from the instructions?

-Stephen**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8733a32-8eef-bdb8-673f-065e8a5f1e0f
* Version Independent ID: f111b377-0dce-d7a6-9483-8830533cacba
* Content: [Managing SSL Certificates in AD FS and WAP in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/manage-ssl-certificates-ad-fs-wap)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/manage-ssl-certificates-ad-fs-wap.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/manage-ssl-certificates-ad-fs-wap.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @jenfieldmsft
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @stephenregisterTJT,

Thanks again for contacting Microsoft. We value your feedback. 

As we understand it, you're describing an issue with the product compared to an issue with the documentation. GitHub isn't quite the right location if searching for technical support, deeper specifics of the product or feature requests as it is completely outside our scope. If there are any issues within the content itself, please let us know.

Looking into our tech forums, other users experienced the same error but there could be several factors as to why:

- The user name or password specified are invalid.
- Kerberos is used when no authentication method and no user name are specified.
- Kerberos accepts domain user names, but not local user names.
- The Service Principal Name (SPN) for the remote computer name and port does not exist.
   - setspn -D HTTP/SERVERNAME `<domain account>`
   - setspn -D HTTP/SERVERNAME.DOMAINAME.COM `<domain account>`
- The client and remote computers are in different domains and there is no trust between the two domains.
- Check the Event Viewer for events related to authentication.
- Change the authentication method; add the destination computer to the WinRM TrustedHosts configuration setting or use HTTPS transport.
- Note that computers in the TrustedHosts list might not be authenticated. 

Also came across this:
> Installation of "Microsoft BitLocker Administration and Monitoring" has broken PS Remoting.
> 
> Solution: https://social.technet.microsoft.com/Forums/en-US/cb71e431-5c4d-4597-b035-2380580a1a95/mbam-25-spn-issue-with-dns-alias-and-reporting?forum=mdopmbam -> Created a DNS Alias for MBAM
> 
> Reason for the problem:
> 
> SPN has been registered to the user from th MBAM Application Pool:
setspn -l DOMAIN\USER
> 
> ->http/myserver
> ->http/myserver.mydomain.ch

We recommend that you engage with the product community or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs) as not every producible error will be documented in this page. 

If the mentioned above does not work, we have additional support forums below:
- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Hopefully one of the community experts may be able to better assist. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
