### ISSUE TITLE
msol cmdlets do not need to be run on every server

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/windowsserverdocs#5977]
Azure AD requires the base64 cert for each farm member, but you do NOT need to run the  New-MsolServicePrincipalCredential from the server itself. Simply take the base64 certs to an administrative workstation and register them.

for example, if you had previously exported them to csv:
```
    
    $CertificatesCSV = Import-Csv 'c:\AAdfsAzureCertificates.csv'
    $CertificatesCSV | ForEach-Object {
        New-MsolServicePrincipalCredential -AppPrincipalId '981f26a1-7f43-403b-a875-f8b09b8cd720' -Type asymmetric -Usage verify -Value $_.CertInBase64
    }


```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f333e8cb-c046-ee06-d33d-d7dc8e8af695
* Version Independent ID: 10838695-f60e-42a7-b0e8-eed7820fd333
* Content: [Configure AD FS 2016 and Azure MFA](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
Thank you for submitting this issue.  Unfortunately, due to high volumes I was unable to respond to this in a timely manner.  At this point, I am going to close this due to it's age and the possibility that it may have been addressed.  If this is still a problem, please consider submitting a new issue.  Thank you.

#please-close
