### ISSUE TITLE
Should make it clearer that the destination folder must exist

### ISSUE THREAD

**Issue by LordZoltan** [MicrosoftDocs/windowsserverdocs#5979]
A critical part of the behaviour isn't covered.

When expanding a multi-file source cab, if  -r isn't used, then the destination must be a folder that **_exists_**, otherwise you'll get the '_Destination directory required for a multi-file CAB_' error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d352c588-1b3d-dd0d-0d8b-b7761eae861f
* Version Independent ID: a2e41711-2938-19a5-8bee-34ff2081b17c
* Content: [expand](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/expand)
* Content Source: [WindowsServerDocs/administration/windows-commands/expand.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/expand.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @LordZoltan, 

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made to state the `<destination>` must exist if `-r` is used along with correcting the syntax. Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
