### ISSUE TITLE
Can't follow directions on thispage

### ISSUE THREAD

**Issue by mihart** [MicrosoftDocs/windowsserverdocs#5982]
"From the Connection Center, tap the overflow menu (...) on the command bar at the top of the client."
Where is the Connection center?  What does it look like?  I don't see (...).  I'm stuck.  Please update instructions with screenshots.  Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ab98fc-fea2-a11a-e5ca-de1430211d97
* Version Independent ID: 4d9943c3-fef7-ca86-bd03-1241a04b8135
* Content: [Get started with the Windows Desktop client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop#install-the-client)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @mihart, 

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made and will be live after the next business day. 3 new images were added to address concerns. For your ask specifically, once you open the Windows Remote Desktop Client app, go to the far right of the app and click on the **"..."** to see the additional options in the drop-down menu. Please note that you will receive different options if you click on **"..."** in the Connection Bar and the **"..."** for your workspace:

![windows-remote-desktop-client-1](https://user-images.githubusercontent.com/103963494/189235299-86665a9b-d3b3-496b-ab46-6448fc6c3216.png)
![windows-remote-desktop-client-2](https://user-images.githubusercontent.com/103963494/189235302-c5d8022f-2c75-4577-b916-104554e4704d.png)

We hope this addresses your concerns. We will now be closing this thread. Thank you and have a most pleasant day. #please-close
