### ISSUE TITLE
What happened to the documentation on the schtasks create /NP option?

### ISSUE THREAD

**Issue by caderoux** [MicrosoftDocs/windowsserverdocs#5985]
It is still documented on this page: https://docs.microsoft.com/en-us/windows/win32/taskschd/schtasks

> /NP
> 
> A value that indicates that no password is stored. The task does not run interactively as the given user. Only local resources are available.
> 
> 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0feda591-bda7-75e4-3eee-f38ec06f6f17
* Version Independent ID: f9f5b2ca-d26f-dd8a-70d1-0c07b94a4dd6
* Content: [schtasks create](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/schtasks-create#feedback)
* Content Source: [WindowsServerDocs/administration/windows-commands/schtasks-create.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/schtasks-create.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @caderoux,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding the `/np` parameter and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
