### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by michael-mcvicker** [MicrosoftDocs/windowsserverdocs#5988]
Seems like there is a broken link 

from https://docs.microsoft.com/en-us/windows-server/administration/hybrid-cloud-print/hybrid-cloud-print-deploy

to this page for a tutorial: https://docs.microsoft.com/en-us/azure/active-directory/app-proxy/application-proxy-add-on-premises-application#feedback

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bdc0597-e371-3404-95b8-3cb6879048e8
* Version Independent ID: 0c03b7ab-64cb-e25a-41f2-4a8bf3859ea7
* Content: [Deploy Windows Server Hybrid Cloud Print](https://docs.microsoft.com/en-us/windows-server/administration/hybrid-cloud-print/hybrid-cloud-print-deploy)
* Content Source: [WindowsServerDocs/administration/hybrid-cloud-print/hybrid-cloud-print-deploy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/hybrid-cloud-print/hybrid-cloud-print-deploy.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @msjimwu
* Microsoft Alias: **jimwu**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey michael-mcvicker,

Thanks again for contacting Microsoft, we value your feedback. 

During the time this issue was created, the source page in question no longer exists. We'll now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
