### ISSUE TITLE
Azure AD as a prerequisite?

### ISSUE THREAD

**Issue by johnharvieux** [MicrosoftDocs/windowsserverdocs#599]
The prerequisites list an Azure AD subscription.  Why is this necessary for ADFS authentication?

**Comment by thibaultchatiron** [comment]
This is not necessary. Maybe a mistake because the given example is based on the Azure AD Sample...

**Comment by lizap** [comment]
This issue is a duplicate of https://github.com/MicrosoftDocs/windowsserverdocs/issues/600, so I'm going to close this one. Thanks!
