### ISSUE TITLE
Typo in the CSP Response headers default value

### ISSUE THREAD

**Issue by mitsuker** [MicrosoftDocs/windowsserverdocs#5999]
Content-Security-Policy: default-src ‘self' ‘unsafe-inline' ‘'unsafe-eval'; img-src ‘self' data:;

there is an extra ‘ before unsafe-eval, copying these as is to reset to the default values makes the ADFS unresponsive to requests

**Comment by Xelu86** [comment]
Hey mitsuker,

Thanks again for contacting Microsoft, we value your feedback. 

At the time this issue was created, a documentation change was made correcting this issue and was not closed. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
