### ISSUE TITLE
Grammar issue

### ISSUE THREAD

**Issue by ivandretvic** [MicrosoftDocs/windowsserverdocs#60]
- PAWs should be used for managing the operating system and applications that provide Directory Synchronization and Identify Federation for cloud ....

Should read

- PAWs should be used for managing the operating system and applications that provide Directory Synchronization and **Identity** Federation for cloud ...

**Comment by lizap** [comment]
Thanks, Ivan - I'll pass this along to the writer who owns this content.

**Comment by RavuAlHemio** [comment]
Fixed in 5529499.
