### ISSUE TITLE
Azure AD as pre-req?

### ISSUE THREAD

**Issue by johnharvieux** [MicrosoftDocs/windowsserverdocs#600]
I don't think an Azure AD subscription is required for ADFS authentication.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 473bc6ea-017f-52f3-7e58-81ecf58d2db8
* Version Independent ID: 20965612-d6a9-35ea-c030-91c09372962e
* Content: [Build a web application using OpenID Connect with AD FS 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/enabling-openid-connect-with-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/enabling-openId-connect-with-ad-fs.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/enabling-openId-connect-with-ad-fs.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by thibaultchatiron** [comment]
You totally right! This is not necessary. Maybe a mistake because the given example for OpenID is based on the Azure AD Sample...

**Comment by MicrosoftGuyJFlo** [comment]
@CelesteDG Can you take a look at this?

**Comment by CelesteDG** [comment]
In https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-scenarios-for-developers#how-it-works-the-basics, we specify that the IDP and auth server is AD FS and not Azure AD. I didn't see anything in the procedures that would require Azure AD or going to the Azure portal (to register an app, for example) so it should be okay to omit Azure AD as a prerequisite.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close

**Comment by johnharvieux** [comment]
It's still listed as a pre-req:
"Pre-requisites
The following are a list of pre-requisites that are required prior to completing this document. This document assumes that AD FS has been installed and an AD FS farm has been created. 
**An Azure AD subscription (a free trial is fine)** 
GitHub client tools 
AD FS in Windows Server 2016 TP4 or later 
Visual Studio 2013 or later. "

**Comment by MicrosoftGuyJFlo** [comment]
Yes It is being updated via a PR against our private repo. Will publish later today.
