### ISSUE TITLE
Missing Server 2022 info

### ISSUE THREAD

**Issue by gdukevt** [MicrosoftDocs/windowsserverdocs#6006]
This page does not mention compatibility with Windows Server 2022. Jeff Woolsey mentioned the Storage Migration Service in the Server 2022 launch event, so I _presume_ that it's compatible, but I hope you'll clarify.

Many thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 293dff88-4f13-d13a-bf54-4166598e0b81
* Version Independent ID: 58d2fc54-4f15-a67b-94f3-197e2dac7bc7
* Content: [Storage Migration Service overview](https://docs.microsoft.com/en-us/windows-server/storage/storage-migration-service/overview)
* Content Source: [WindowsServerDocs/storage/storage-migration-service/overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-migration-service/overview.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by craigcaseyMSFT** [comment]
Compatibility with Windows Server 2022 now documented.

#please-close
