### ISSUE TITLE
incomplete Applicable list

### ISSUE THREAD

**Issue by indiano78** [MicrosoftDocs/windowsserverdocs#6007]
[Enter feedback here]
Hello, 
Applicable list of operating systems seems not complete on the top of document.
Windows 2008 to 2012 R2 are missing, but documentation talks about them.
and reaching information about this operations, almost of internet indexer returns results for Windows 2003, 

i advise you about it, because i got a lot of engeeners, and some from microsoft, thas miss understand or dont know this article.
you know, almost make quick and dirty, then they brokes servers...

best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd180142-4c19-8abc-ecce-e4c7e5ac8951
* Version Independent ID: fc5bba87-afad-1729-8f7e-333c73188b73
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by PatAltimore** [comment]
Hi @indiano78,

Thanks for the feedback. The versions / SKUs were removed from the applies list because they are now out of support. Since the article talks about older versions, I added *and earlier versions as noted* in the applies to list.

The change should go live in a day or so.

Thanks,
Pat

#please-close
