### ISSUE TITLE
Now it also works while logged in trough RDP

### ISSUE THREAD

**Issue by wander1992** [MicrosoftDocs/windowsserverdocs#6008]
Maybe this will help some people.

`try
{
    $WmiLoggedOnUsers = (Get-WmiObject Win32_LoggedOnUser).Antecedent 
    If($WmiLoggedOnUsers.Count -gt 1) {
        $WmiLoggedOnUsers = $WmiLoggedOnUsers -match "Domain=`"DOMAIN`""
    }
    $WmiUserValid = ($WmiLoggedOnUsers | Select-Object -Unique -First 1) -match 'Domain="([^"]+)",Name="([^"]+)"'
    If(-not $WmiUserValid){
        Throw "Returned object is not a valid WMI string"
    }
    $UserName = "$($Matches[1])\$($Matches[2])"
    $ObjUser = New-Object System.Security.Principal.NTAccount($UserName)
    $Sid = $ObjUser.Translate([System.Security.Principal.SecurityIdentifier])
    $SidValue = $Sid.Value
    $Message = "User SID is $SidValue."
    Write-Host "$Message"
}
catch [Exception]
{
    $Message = "Unable to get user SID. $_"
    Write-Host "$Message"
    exit
}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e14da1-102d-3ddf-e2a1-a20ce533b95a
* Version Independent ID: 374edc4c-f527-b7b7-c291-353928b97d8d
* Content: [Configure Windows 10 Client Always On VPN Connections](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
#assign:HeidiLohr
