### ISSUE TITLE
Spelling mistake on service reference 'Bowser'

### ISSUE THREAD

**Issue by microtactical** [MicrosoftDocs/windowsserverdocs#6013]
[Enter feedback here]
There is a spelling mistake near the bottom when referencing "Browser" as a service that depends on LanmanWorkstation. It is spelled *Bowser* in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a91db45-ca3c-7a2e-3f32-2f5b57837b03
* Version Independent ID: b83cbaab-c0df-d6e7-a67f-f4c99a46e30a
* Content: [How to detect, enable and disable SMBv1, SMBv2, and SMBv3 in Windows](https://docs.microsoft.com/en-US/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
#label:"typo"

**Comment by MarkusNemesis** [comment]
FYI, OP, Bowser is actually a legitimate microsoft service, and does relate to SMB1, thus Bowser is actually correct. Browser relates to network discovery from the days of Server 2003.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @microtactical,

Thanks again for contacting Microsoft. We value your feedback. 

@MarkusNemesis did provide a nutshell version surrounding the bowser service in Windows released back in the Windows NT days and is correct. 

This is a legacy Windows network service that does have a display name as "Computer Browser" in the local Services GUI but not in the same as a browser used in a traditional sense to surf the web. This service was used for network discoverable resources which has been replaced by Microsoft Active Directory services about 2 decades ago. It is mentioned in this documentation to provide backwards compatibility with client devices running much older version of Windows.

We hope this clarifies the bowser service. We'll now be closing this thread. Thank you and have a most pleasant day. 
#please-close
