### ISSUE TITLE
Need updated documentation that Win11 keys are the same as Win10

### ISSUE THREAD

**Issue by andreiztm** [MicrosoftDocs/windowsserverdocs#6019]
Hi,

could you please update the docs to mention that Win10 keys are also the keys for Win11? Win11 has been out for a bit of time, but we still don't have updated docs which mention this. 

Thank you,
Andrei

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 666e84fa-56d3-9cfb-58a6-8dd1b86b74cb
* Version Independent ID: 6c6de03f-8da2-0fee-8e0e-0e98c31855d9
* Content: [Key Management Services (KMS) client activation and product keys for Windows Server and Windows](https://docs.microsoft.com/en-us/windows-server/get-started/kms-client-activation-keys)
* Content Source: [WindowsServerDocs/get-started/kms-client-activation-keys.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/kms-client-activation-keys.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @dknappettmsft
* Microsoft Alias: **daknappe**

**Comment by dknappettmsft** [comment]
Thanks for the feedback. This article has been updated now.

#please-close
