### ISSUE TITLE
Storage types

### ISSUE THREAD

**Issue by JazzyWagdaddy** [MicrosoftDocs/windowsserverdocs#602]
Is there a reason why we can't use GRS storage?  Is the recommendation LRS only?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 706b2e1a-e90e-d70e-431f-5476b0ca52c1
* Version Independent ID: 70721d4c-642c-61f8-6c61-84b1dd1ae96c
* Content: [Deploy a two-node Storage Spaces Direct SOFS for UPD storage in Azure](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-storage-spaces-direct-deployment)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-storage-spaces-direct-deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-storage-spaces-direct-deployment.md)
* Service: **unspecified**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by rawi-saas** [comment]
Premium Storage is LRS only.
