### ISSUE TITLE
AVHDX

### ISSUE THREAD

**Issue by tmcmi** [MicrosoftDocs/windowsserverdocs#6020]
You need to address the AVHDX hell here. By default Hyper-V creates them, and exporting just exports the resulting mess, which cannot be usefully imported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acc00093-1f29-7e3b-ab30-9e6966598390
* Version Independent ID: bd281aaf-4e09-73a4-95a0-873ab4cc5de2
* Content: [Export and import virtual machines](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/deploy/export-and-import-virtual-machines)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/deploy/Export-and-import-virtual-machines.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/deploy/Export-and-import-virtual-machines.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by dknappettmsft** [comment]
Hi @tmcmi, please could you elaborate? Exporting and then importing virtual machines that have checkpoints (AVHDX) is supported. By default, Hyper-V in Windows Server doesn't create automatic checkpoints, but you can enable this on a per-VM basis that will automatically create a checkpoint when that VM powers on, which is then removed when that VM powers off.

#assign:dknappettmsft

**Comment by dknappettmsft** [comment]
#pri3

**Comment by dknappettmsft** [comment]
Closing this as there is no reply.  This can be re-opened if it's replied to.

#please-close
