### ISSUE TITLE
Remove Azure Stack HCI from the "Applies to"

### ISSUE THREAD

**Issue by Mihaly7** [MicrosoftDocs/windowsserverdocs#6022]
Please remove Azure Stack HCI OS from applies to section as SOFS is not supported:
Applies to: Windows Server 2022, Windows Server 2019, Windows Server 2016, Windows Server 2012 R2, Windows Server 2012, **Azure Stack HCI, versions 21H2 and 20H2**
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07d7bf3d-4ab7-3f11-acb2-840d86090042
* Version Independent ID: ba1dc68b-297a-3c2f-2e99-4f42367e89f7
* Content: [Scale-Out File Server for application data overview](https://docs.microsoft.com/en-us/windows-server/failover-clustering/sofs-overview)
* Content Source: [WindowsServerDocs/failover-clustering/sofs-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/sofs-overview.md)
* Product: **windows-server**
* Technology: **failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
Addressed.
