### ISSUE TITLE
No Examples, syntax layout help

### ISSUE THREAD

**Issue by vordesigns** [MicrosoftDocs/windowsserverdocs#6024]
Where are the examples, why do I have to go somewhere else?

Dispart <paramater> is useless, why bother putting it there? I would not enter a command like that not knowing which drive it was going to impact.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bca0f8f7-da0d-6340-bf63-f269be5f64d1
* Version Independent ID: 39758423-e92d-d2db-88f3-260dc5a1a26a
* Content: [diskpart](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/diskpart)
* Content Source: [WindowsServerDocs/administration/windows-commands/diskpart.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/diskpart.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @vordesigns,

Thanks again for contacting Microsoft. We value your feedback. 

Can you please let us know which example(s) for which command(s) are in question in order for us to update this content with more clarity?

**Comment by vordesigns** [comment]
Here is a fair example;
https://www.thewindowsclub.com/list-of-diskpart-commands-windows

Tim Andaya
System Consultant
Vortex Designs, LTD.
310-391-4672 / ***@***.***



Vortex Designs, LTD. Disclaimer

NOTICE: This message is for the use of the addressee only. It may contain
proprietary, confidential and/or legally privileged information. No
confidentiality or privilege is waived or lost by transmission to an
unintended party.  If you are not the intended recipient, you must not,
directly or indirectly, use, disclose, distribute, print or copy any part
of this message. If you believe you have received this message in error,
please delete it and all copies of it from your system and notify the
sender immediately by e-mail.  Vortex Designs, LTD. attempts to scan e-mail
for viruses, however, it does not guarantee that this message is virus-free
and accepts no liability for any damage sustained as a result its
transmission.
