### ISSUE TITLE
Wrong registry key

### ISSUE THREAD

**Issue by engineererr** [MicrosoftDocs/windowsserverdocs#6029]
The registry key on Win10 20H2 (OS Build 19042.867) is stored under HKEY_LOCAL_MACHINE\SYSTEM\CurrentContolSet\Control\Lsa\Kerberos\HostToRealm. The key is stated without "Control"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e21a29b-ad56-2f49-c190-afb45c7e4a6a
* Version Independent ID: 2ec7fcfb-0504-d331-005b-acb2b14cbacd
* Content: [ksetup addhosttorealmmap](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/ksetup-addhosttorealmmap)
* Content Source: [WindowsServerDocs/administration/windows-commands/ksetup-addhosttorealmmap.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/ksetup-addhosttorealmmap.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by dknappettmsft** [comment]
#assign:dknappettmsft

**Comment by dknappettmsft** [comment]
Thanks @engineererr for raising this, I have made the correction (and the same error in another ksetup article) and the changes should be live in a few hours.

#please-close
