### ISSUE TITLE
STeps are not in order

### ISSUE THREAD

**Issue by JazzyWagdaddy** [MicrosoftDocs/windowsserverdocs#603]
If you complete step 4A, you need to update the document to say skip steps 4b & 4c and start with step 5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 706b2e1a-e90e-d70e-431f-5476b0ca52c1
* Version Independent ID: 70721d4c-642c-61f8-6c61-84b1dd1ae96c
* Content: [Deploy a two-node Storage Spaces Direct SOFS for UPD storage in Azure](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-storage-spaces-direct-deployment)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-storage-spaces-direct-deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-storage-spaces-direct-deployment.md)
* Service: **unspecified**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by rawi-saas** [comment]
Step 4 states "by doing one of the following", therefore you should choose between options a, b, and c.

**Comment by lizap** [comment]
I'll update it to be a bulleted lists, instead of numbered. I definitely see that the numbers make it look like you're supposed to do all of the steps. Thanks! I'll come back and close this issue once I push the change.

**Comment by lizap** [comment]
I changed the steps to a bulleted list and tried to clarify the introductory language in the step. Please let me know if that's not enough. Thanks!
