### ISSUE TITLE
idpinitiatedsignon.aspx does not show correct message after login successfully

### ISSUE THREAD

**Issue by koonsang** [MicrosoftDocs/windowsserverdocs#6032]
When I tried to login via idpinitiatedsignon.aspx, using the correct credential, I keep seeing the same login page which says "Sign in with your organizational account" and the "Sign In" button, instead of a page saying "You are signed in" with the "Sign Out" button.  I know the login is successful, because if the login fails, I will see an error message saying "Incorrect user ID or password. Type the correct user ID and password, and try again." and also can see the failed login attempt in Windows Event log.  I tried re-install and re-configure ADFS a few times but am still not able to get the correct successful login behaviour.  Can you advise what could the cause be?  Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17b38f1d-31ff-81bb-b850-2d86a6ae9ba7
* Version Independent ID: fc89f75a-b53f-ac96-c9c3-60dbea6ff19d
* Content: [AD FS Troubleshooting - Idp-Initiated Sign On](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-initiatedsignon)
* Content Source: [WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-initiatedsignon.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-initiatedsignon.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by dknappettmsft** [comment]
Hi @koonsang, unfortunately this isn't a place for product support, only changes that need to be made to articles.  If you could please get in touch with Microsoft Support they are best placed to help you, and if there are any changes that need to be made to the article as a result, we will work with them to improve it.

#please-close
