### ISSUE TITLE
Provide feedback section still references UserVoice

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/windowsserverdocs#6038]
There is still a link to UserVoice in the Providing Feedback section which no longer exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f168bf93-cc54-2a7e-2c1c-7c649a8458d2
* Version Independent ID: 0edf20e5-268c-b5df-93a6-85186eb4ba86
* Content: [Windows Admin Center Common Troubleshooting Steps](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/support/troubleshooting)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/support/troubleshooting.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/support/troubleshooting.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @jwwool
* Microsoft Alias: **jeffrew**

**Comment by dknappettmsft** [comment]
Thanks @MarcLaf, I've updated the link to the new location and the change should be visible in the article in a few hours.

#please-close
