### ISSUE TITLE
Multiple Monitors

### ISSUE THREAD

**Issue by dodge1350-frp** [MicrosoftDocs/windowsserverdocs#6042]
[Enter feedback here]
Don't you think it would be important to identify on this page if the Microsoft Store Client supports multiple monitors and if so, how to go about configuring that?  I don't see any mention of it anywhere, and I would think most folks that use this would want to know about that.  Please update to include this incredibly important information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acc42a8f-2623-4352-7cc4-70f0f61e9d89
* Version Independent ID: 97d8b54b-5e7d-098b-4fb7-e8f6e0b30389
* Content: [Get started with the Microsoft Store Client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windows)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windows.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windows.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by IngridAtMicrosoft** [comment]
#assign:HeidiLohr

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @dodge1350-frp,

Thanks again for contacting Microsoft. We value your feedback.

Looking at the very top of this documentation displays the following:

> You can use the Remote Desktop client for Windows to work with Windows apps and PCs remotely from a different Windows device. Use the following information to get started. Be sure to check out the [FAQ](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.yml) if you have any questions.

Within the [FAQ](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.yml) itself, there is a section surrounding multiple monitor setup under "[Monitors, Audio, and Mouse](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-client-faq#monitors,-audio,-and-mouse)" with instructions how to perform this task:

> **How do I use all of my monitors?**
>To use two or more screens, do the following:
>
> 1. Right-click the remote desktop that you want to enable multiple screens for, and then click **Edit**.
> 2. Enable **Use all monitors** and **Full screen**.

We hope this helps. This thread will now be closed. Thank you and have a most pleasant day. 
#please-close

**Comment by dodge1350-frp** [comment]
Sorry, this does not 'cure' the problem I have been having with multiple monitors.  I have the correct version of Remote Desktop as well as many others on my computer and the option for multiple monitors either don't exist or don't work.  I have attached images of the number of Microsoft Remote Desktop apps installed on my computer, which includes a Remote Desktop Web Client, as well as the app versions below.  Also attached is the error that I receive when attempting to log into version 1.2.3401.0.  Please advise.  This has not been addressed by anyone from Microsoft or the community in nearly a year and closing the issue with a blurb about how it is supposed to work is not helpful.  Please advise.

Microsoft Remote Desktop
Version 1.2.3401.0
(Fails to log in - see attached image)

Microsoft Remote Desktop
Version 10.2.3000.0
(No multiple monitor option)

Microsoft Remote Desktop
Version 1.0.27.51
(Does not have multiple monitor option)


![version-recommended-fails-to-login](https://user-images.githubusercontent.com/61803431/187677439-688e01fd-c6ab-4179-9aa8-7a5c74fdedeb.png)
![remote-desktop-versions](https://user-images.githubusercontent.com/61803431/187677490-064ec2f5-4f95-44d7-9a10-0bbd1fecb41e.png)
