### ISSUE TITLE
Events, powershell and RDP don't work through Azure Application Proxy

### ISSUE THREAD

**Issue by ClumsyNavigator** [MicrosoftDocs/windowsserverdocs#6043]
When registering Windows Admin center inside Azure you get an app registration, from here you can jump to the enterprise application and setup the Azure Application Proxy to the connector group you want.

This works like a charm and also very fast, yet the support for Events, RDP and Powershell is not there.
This has to do with the fact that WebSockets are not supported and stil in preview (since 2018?).

What is the current status of this and will it ever get supported?

**Comment by IngridAtMicrosoft** [comment]
GitHub issues for this repo are for reporting problems with Windows Server documentation.  Please post to a community forum or open a support request. #please-close

**Comment by ClumsyNavigator** [comment]
I understand that, yet the documentation doesn't state anything on this except "Known Issue". I thought this is something that should be added so we know what to expect.
