### ISSUE TITLE
Remove Reference to "One Identity | Starling 2FA AD FS | Starling 2FA AD FS Adapter"

### ISSUE THREAD

**Issue by seanstark** [MicrosoftDocs/windowsserverdocs#6048]
[Enter feedback here]

Requesting the below be removed from the docs section "Microsoft and third-party additional authentication methods" as this is now end of life from One Identity. You can reference https://support.oneidentity.com/starling-two-factor-authentication/hosted#ProductLifeCycleTable indicating this is EOL

Please remove:

One Identity | Starling 2FA AD FS | Starling 2FA AD FS Adapter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9067120-9721-1333-384b-d0c322f3ba35
* Version Independent ID: e58479e3-8137-6de4-d095-7b1b47839b91
* Content: [Configure Additional Authentication Methods for AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-additional-authentication-methods-for-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-Additional-Authentication-Methods-for-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-Additional-Authentication-Methods-for-AD-FS.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Addressed.
