### ISSUE TITLE
Expand automount

### ISSUE THREAD

**Issue by chadsters88** [MicrosoftDocs/windowsserverdocs#6051]
Respectfully requesting that automount is expanded with options/flags to enable or disable automount for specific drives by guid, or possibly even by port. This would enable a much higher degree of safety when keeping drives with other filesystems, such as ext* or btrfs, plugged in as permanent fixtures of our hardware. This would help dual-booting scenarios. However, my use case is that of portable systems, such as vm's and Puppy Linux, being kept on a usb drive. My intention is to keep it plugged into my fastest usb port (usb 3.1, part of the rear io) for quick access at all times, while I can always remove it if I have to move my workflow to another station. Every time Windows boots or I insert the drive, Windows inspects the drive and asks if I want to format the drive; each time this happens there is a risk of wiping my drive by user error, and technically even a risk of Windows corrupting the drive in the event of some grave failure. I hope you'll consider this and that the implementation is relatively straightforward.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0a74de9-f1e4-5155-1f15-a032791a2794
* Version Independent ID: 37116043-c59b-78ad-fef4-038ff4141940
* Content: [automount](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/automount)
* Content Source: [WindowsServerDocs/administration/windows-commands/automount.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/automount.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by IngridAtMicrosoft** [comment]
@chadsters88 Thank you for your product feedback. It has been forwarded to the engineering team.
