### ISSUE TITLE
ADFS oauth2 Single log-out not redirect.

### ISSUE THREAD

**Issue by KuSai18** [MicrosoftDocs/windowsserverdocs#6059]
Dear Sir/Madam, 

When sign out from web portal and successful cleared cookies during ADFS oauth Single log-out, but the redirect still keep at AD FS Single log-out page and not redirect that after gived parameter id_token_hint and post_logout_redirect_uri (before added LogoutUri), May i know any wrong step during the single log-out that discontinue process or the step is just over?

Document from below link:
[(https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/ad-fs-logout-openid-connect)
](url)

P.S Using Mircorsoft server 2019 ADFS 4.0.

Regards,
KuSai

**Comment by IngridAtMicrosoft** [comment]
@KuSai18 Please ask your question at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/). The GitHub issues for this repo are for reporting problems with our documentation.
