### ISSUE TITLE
Windows server 2022 forest level

### ISSUE THREAD

**Issue by Tarjei-stavanger** [MicrosoftDocs/windowsserverdocs#6061]
The article says at the top  "Applies to: Windows Server 2022, Windows Server 2019, Windows Server", but there is no mention of Windows Server 2022 further down in the article.

This is particularly disconcerting to those of use who have Windows Server 2008 forest level and wonder if it is supported by a Windows Server 2022 DC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 418dc0a0-0312-9d6f-b2dc-2eb4841285ba
* Version Independent ID: 600b0469-3c96-5737-c39b-2ce9021b0f5a
* Content: [Windows Server 2016 Functional Levels](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/active-directory-functional-levels)
* Content Source: [WindowsServerDocs/identity/ad-ds/active-directory-functional-levels.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/active-directory-functional-levels.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by IngridAtMicrosoft** [comment]
#assign:dknappettmsft

**Comment by danielniccoli** [comment]
https://github.com/MicrosoftDocs/windowsserverdocs/pull/6087

**Comment by dknappettmsft** [comment]
#label:"duplicate" of #5819 where it is already being tracked.

#please-close
