### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by thomaskennedy1066** [MicrosoftDocs/windowsserverdocs#6063]
This "To use telnet to connect to the computer running the telnet Server Service at telnet.microsoft.com on TCP port 44 and ro log the session activity in a local file called telnetlog.txt, type:"

Should be "To use telnet to connect to the computer running the telnet Server Service at telnet.microsoft.com on TCP port 44 and **to** log the session activity in a local file called telnetlog.txt, type:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3233a31-8788-33ca-a734-c486dafb544d
* Version Independent ID: b0e761ac-472c-73b9-a656-dced985750ff
* Content: [telnet](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/telnet)
* Content Source: [WindowsServerDocs/administration/windows-commands/telnet.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/telnet.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by RAJU2529** [comment]
@thomaskennedy1066 . Thanks for the report. Tomorrow I will correct typo error.

**Comment by Xelu86** [comment]
#assign:Xelu86
