### ISSUE TITLE
Updating OS versions

### ISSUE THREAD

**Issue by zjorz** [MicrosoftDocs/windowsserverdocs#6065]
[Enter feedback here]
IS NOW: These steps apply to DCs that run Microsoft® Windows Server 2016, 2012 R2, 2012, 2008 R2, 2008, and 2003 operating system

SHOULD BE: These steps apply to DCs that run Microsoft® Windows Server 2022, 2019, 2016, 2012 R2, 2012, 2008 R2, 2008, and 2003 operating system

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c013b1cb-de4b-c979-ab59-afe923287b3d
* Version Independent ID: 7836e716-0752-820f-0e64-8e58f8a06e70
* Content: [Active Directory Forest Recovery Guide](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/ad-forest-recovery-guide)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/AD-Forest-Recovery-Guide.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/manage/AD-Forest-Recovery-Guide.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by RAJU2529** [comment]
@zjorz . Thanks for the information, tomorrow I will add the OS versions.

**Comment by RAJU2529** [comment]
@zjorz Windows Server 2019 is added

**Comment by zjorz** [comment]
Not windows server 2022?


Met Vriendelijke Groeten / Kind Regards,



[IAMTEC | Identity And Security Services]

Jorge de Almeida Pinto


Lead Identity/Security Architect

MVP Enterprise Mobility & Security

Microsoft Certified



Mobile: +31-(0)6-26.26.62.80

E-mail: ***@***.******@***.***>



KvK/CoC (NL): 78.70.27.20

BTW/VAT: NL002970959B74

[MVP Profile]<http://tiny.cc/JorgeMVPDS> [Blog] <http://tiny.cc/JQFKblog>  [Website] <http://www.iamtec.eu/>

[LinkedIn]<http://tiny.cc/JorgeLinkedIn> [Facebook] <http://tiny.cc/JQFKfacebook>  [Twitter] <http://tiny.cc/JQFKtwitter>





________________________________

**Comment by IngridAtMicrosoft** [comment]
All server versions are in the document.
