### ISSUE TITLE
Brilliant thank you!!

### ISSUE THREAD

**Issue by sarahmcm** [MicrosoftDocs/windowsserverdocs#6067]
[Enter feedback here]
oh thank you at last Microsoft producing _good_ documentation!! Easy to follow! in logical order! clear, concise and complete!!  fabulous - OMG after all these years of agony, what a change. THANK YOU!!! (now please go teach all the rest of Microsoft dev teams documenters to do this :-) )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32c24e82-8047-12d6-877a-8ee1ad7d259c
* Version Independent ID: 021dac4b-8b4c-0fad-85fb-f89231fe8afa
* Content: [Deploying Roaming User Profiles](https://docs.microsoft.com/en-us/windows-server/storage/folder-redirection/deploy-roaming-user-profiles)
* Content Source: [WindowsServerDocs/storage/folder-redirection/deploy-roaming-user-profiles.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/folder-redirection/deploy-roaming-user-profiles.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by RAJU2529** [comment]
@sarahmcm . Thanks for your feedback .All documents or articles  authors are Dedicated their free time to write these type of articles for all enterprise users, all system administrators and  normal users.
We are happy to see your feedback.

**Comment by dknappettmsft** [comment]
Thanks for the positive feedback. There are dedicated teams at Microsoft whose role it is to produce and update great documentation. We also appreciate the contributions from the community to help us with our efforts updating and fixing issues where things aren't quite right.

#please-close
