### ISSUE TITLE
Oops, we couldn't connect to

### ISSUE THREAD

**Issue by robcwaldron** [MicrosoftDocs/windowsserverdocs#607]
Hi, I have a freshly installed windows server 2016 installed that is completed patched up to date. I can get to the webclient screen and see the apps, but when i click through to one, it states: "Your session has ended because of an error".

Also, when i try and run the KB update, it won't allow it, but my assumption is that because i've installed up to CU 2018-04, that it should be included anyway.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Service: **unspecified**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by dgnice** [comment]
Hello , i had the same message OUPS... send to administator , have you an idea ? thanks 
( all application work nice, with remoteapp web )

**Comment by dgnice** [comment]
sorry oops ,we couldn't connect to

**Comment by davidbel** [comment]
@robcwaldron Yes, the KB specified was the minimum one that has the necessary fix for the gateway. Subsequent updates will also include the fix.

Assuming you have an RD Gateway setup with the proper certificate, you could look in the browser console log to see what error you are seeing when you hit the problem.

If this is still an issue, please send mail to the address found on the About page of the client. @dgnice FYI.
