### ISSUE TITLE
Add Windows 10 LTSC 2021 KMS keys

### ISSUE THREAD

**Issue by tavrez** [MicrosoftDocs/windowsserverdocs#6076]
I've heard that it shares the same GVLK key with LTSC 2019, but it's not mentioned in documents.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 666e84fa-56d3-9cfb-58a6-8dd1b86b74cb
* Version Independent ID: 6c6de03f-8da2-0fee-8e0e-0e98c31855d9
* Content: [Key Management Services (KMS) client activation and product keys for Windows Server and Windows](https://docs.microsoft.com/en-us/windows-server/get-started/kms-client-activation-keys)
* Content Source: [WindowsServerDocs/get-started/kms-client-activation-keys.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/kms-client-activation-keys.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @dknappettmsft
* Microsoft Alias: **daknappe**

**Comment by dknappettmsft** [comment]
Thanks for the feedback.  It does share the same GVLK and I've updated the article, which should be visible later today.

#please-close
