### ISSUE TITLE
FoD on 2022 causes RDP to not work

### ISSUE THREAD

**Issue by TayschrennSedai** [MicrosoftDocs/windowsserverdocs#6077]
Microsoft has not responded to the ["Feedback Hub" post](https://aka.ms/AAe0l37) on this, but in all tests it appears certain that installing this in 2022 is breaking the ability to remote desktop into the servers.

This entire document should be excluded from the 2022 material until Microsoft has resolved this, or until such time as there is an applicable patch/workaround/etc.  Alternatively, a note should be added that it does not work with 2022.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42e7fb95-09a6-1dec-859a-08261408b289
* Version Independent ID: 823213b4-7445-da48-fb1f-82c5e74dc1af
* Content: [Server Core App Compatibility Feature on Demand (FOD) in Windows Server](https://docs.microsoft.com/en-us/windows-server/get-started/server-core-app-compatibility-feature-on-demand)
* Content Source: [WindowsServerDocs/get-started/server-core-app-compatibility-feature-on-demand.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/server-core-app-compatibility-feature-on-demand.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @dknappettmsft
* Microsoft Alias: **daknappe**

**Comment by dknappettmsft** [comment]
Hi @TayschrennSedai. thanks for the feedback. This is a known issue that is being worked on and will be fixed in a Cumulative Update.  As suggested, I have added a note to the article for this, which should be visible later today.

#please-close

**Comment by dmutsaers** [comment]
Is there an Estimated Time of Arrival for the fix for the known issue with App Compatibility FOD for Windows Server 2022 and RDP connections?

**Comment by TheBigBear** [comment]
Why is this marked as CLOSED? it has not been fixed or patched - as yet? Or has it?

**Comment by dknappettmsft** [comment]
GitHub issues in this repo are for issues with the documentation, not support for the product itself. The original request here was to make sure the document calls out this issue, which it does and is why this issue has been closed here. I do not have an update for the product issue, please contact Microsoft Support.
