### ISSUE TITLE
Dead link for the powershell cmdlets

### ISSUE THREAD

**Issue by vtsingaras** [MicrosoftDocs/windowsserverdocs#608]
IP Address Management (IPAM) Server Cmdlets in Windows PowerShell (https://technet.microsoft.com/library/jj553807.aspx) 404's.
Additionally I came to that page from https://social.technet.microsoft.com/Forums/windowsserver/en-US/15fa4b35-d1eb-4801-b792-7b101310b3d8/how-to-run-ipam-powershell-commands-remotely?forum=winserveripamdhcpdns
looking for info on running the IPAM cmdlets remotely (from a workstation).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab5ad1ab-fd26-a345-1734-07d0181ac11a
* Version Independent ID: 8224fe1d-0d39-e7b7-b96d-70932ca3797a
* Content: [IP Address Management (IPAM)](https://docs.microsoft.com/en-us/windows-server/networking/technologies/ipam/ipam-top#feedback)
* Content Source: [WindowsServerDocs/networking/technologies/ipam/ipam-top.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/technologies/ipam/ipam-top.md)
* Service: **unspecified**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by lizap** [comment]
We'll get the link fixed. I think this is where you need to go: https://docs.microsoft.com/en-us/powershell/module/ipamserver/?view=win10-ps

**Comment by shortpatti** [comment]
fixed

**Comment by Verox-** [comment]
Link (https://technet.microsoft.com/library/jj553807.aspx) is dead again, going 404.
