### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by gerbermarco** [MicrosoftDocs/windowsserverdocs#6080]
At Event 13006, the error cause description:
"When the error code is 0x80072ee7, the failurrre is caused by"

should be:
"When the error code is 0x80072ee7, the failure is caused by"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d126ae85-fc95-be1c-faeb-90b9279f734a
* Version Independent ID: 167f764c-bc47-25a7-b31b-7fdf18c81749
* Content: [Troubleshooting Web Application Proxy](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/web-application-proxy/troubleshooting-web-application-proxy)
* Content Source: [WindowsServerDocs/remote/remote-access/web-application-proxy/Troubleshooting-Web-Application-Proxy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/web-application-proxy/Troubleshooting-Web-Application-Proxy.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @JasonGerend
* Microsoft Alias: **kgremban**

**Comment by Xelu86** [comment]
#assign-xelu86

**Comment by PRMerger7** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: -xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. The change to this documentation has been resolved. #please-close
