### ISSUE TITLE
Possible wrong error code shown in Symptoms

### ISSUE THREAD

**Issue by archeon1004** [MicrosoftDocs/windowsserverdocs#6081]
Hi,

In section symptoms there are two WinError error codes:
8467 or 8468
there is table under which states:
<html>
<body>

8467 | 21C7 | ERROR_DS_SPN_VALUE_NOT_UNIQUE_IN_FOREST | The operation failed because SPN value provided for addition/modification is not unique forest-wide.
-- | -- | -- | --
8648 | 21C8 | ERROR_DS_UPN_VALUE_NOT_UNIQUE_IN_FOREST | The operation failed because UPN value provided for addition/modification is not unique forest-wide.

</body>
</html>

The error codes should be:
8647 for ERROR_DS_SPN_VALUE_NOT_UNIQUE_IN_FOREST and 8648 for ERROR_DS_UPN_VALUE_NOT_UNIQUE_IN_FOREST.
In the table the second one is correct but the SPN value mismatch error code is wrong. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4936a6c-23d8-fee8-4c3c-7913419d67e9
* Version Independent ID: 240f2bff-801c-8310-33fc-28980813fcc6
* Content: [SPN and UPN uniqueness](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/component-updates/spn-and-upn-uniqueness)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/component-updates/SPN-and-UPN-uniqueness.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/manage/component-updates/SPN-and-UPN-uniqueness.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by archeon1004** [comment]
opened PR #6170 to fix

**Comment by IngridAtMicrosoft** [comment]
Error corrected.
