### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by MrZepto** [MicrosoftDocs/windowsserverdocs#6082]
There is a typo in this:

Create VPN_Profile.xml and VPN_Proflie.ps1

should be:

Create VPN_Profile.xml and VPN_Profile.ps

Cheers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e14da1-102d-3ddf-e2a1-a20ce533b95a
* Version Independent ID: 374edc4c-f527-b7b7-c291-353928b97d8d
* Content: [Configure Windows 10 Client Always On VPN Connections](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by dknappettmsft** [comment]
Hi @MrZepto, please could you elaborate on why this should be changed to .ps?  The file extension for a PowerShell script is .ps1, so this should be correct already: 

"A script is nothing more than the same or similar commands that you would run interactively in the PowerShell console, except they're saved as a .PS1 file."

 (https://docs.microsoft.com/en-us/powershell/scripting/learn/ps101/06-flow-control?view=powershell-7.2#scripting)

**Comment by dknappettmsft** [comment]
#assign:@dknappettmsft

**Comment by dknappettmsft** [comment]
#please-close

**Comment by MrZepto** [comment]
Sorry I made a typo to. Should be ps1 of course.

The typo is this:

Proflie
should be Profile

**Comment by dknappettmsft** [comment]
Ah, got it! I've fixed that typo and the change should be visible later today. Thanks for flagging it.
