### ISSUE TITLE
Missing 2022 Info

### ISSUE THREAD

**Issue by NickDorak** [MicrosoftDocs/windowsserverdocs#6091]
The "applies to" section of the page shows that it applies to Windows 2022, but contents don't show any 2022 information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd015c0b-3360-88fd-86b1-08e8c0e8ec5e
* Version Independent ID: 0c3ddb09-23f3-68a3-e7a4-877951feb55b
* Content: [License your RDS deployment with client access licenses (CALs)](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-client-access-license)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-client-access-license.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-client-access-license.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by RAJU2529** [comment]
@lizap  I can tabular column but I have doubt what should like No or Yes

**Comment by v-thepet** [comment]
Hi @NickDorak,

Thank you for contacting Microsoft. We value your feedback.

Sorry for the tardy issue response. The documentation was updated in Feb. 2022 to include this information, so we will now be closing this issue.

Thanks again and have a very pleasant day.
#please-close
