### ISSUE TITLE
OpenSSH ssh-agent service - Automatic startup

### ISSUE THREAD

**Issue by UserJHansen** [MicrosoftDocs/windowsserverdocs#6094]
The recomended action is to have the ssh-agent on manual start but if the user does not start the service then they cannot access the keys. This forces it to default to password authentication. If it was automatic then they would not have to worry about that.

Something like:
`Get-Service ssh-agent | Set-Service -StartupType Automatic`
at [User Key Generation](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md#user-key-generation)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH key management for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by robinharwood** [comment]
Hi @UserJHansen 

Thanks for your dedication to our documentation. We've submitted a documentation change to update the code examples, setting the ssh-agent to automatic, the updated article should be live by tomorrow.

Thanks

#please-close
