### ISSUE TITLE
Typo's /Grammar cleanup

### ISSUE THREAD

**Issue by doah78** [MicrosoftDocs/windowsserverdocs#6095]
A good sample web app is available here. This app is a simple web app that echoes back the claims that it receives from the relying party. In order to use this you need to edit the web.config app by:

    changing https://app1.contoso.com/sampapp to the URL the you will be using for hosting the sample app
    changing all instances of sts.contoso.com to point you AD FS federation server
    Replacing the thumbprint with your thumbprint

Would work better like this

A good sample web app is available here. This app is a simple web app that echoes back the claims that it receives from the relying party. In order to use this you need to edit the web.config app by:

    changing https://app1.contoso.com/sampapp to the URL you will be using for hosting the sample app
    changing all instances of sts.contoso.com to point your AD FS federation server
    Replacing the thumbprint with your thumbprint

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f7b34d-aead-7d39-208b-9a32fe38e1dc
* Version Independent ID: 9a04307d-5e57-cfe4-993c-54231b242bd9
* Content: [AD FS Troubleshooting - Claims Rules](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-claims-rules)
* Content Source: [WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-claims-rules.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-claims-rules.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @doah78,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting the grammar and will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. #please-close
