### ISSUE TITLE
Missing parameter - /l

### ISSUE THREAD

**Issue by officedrone** [MicrosoftDocs/windowsserverdocs#6096]
[Enter feedback here]
The article is missing a parameter - /l . The command 'mstsc /l' (without the quotes), displays a list of monitors and their arrangement (offset from the center). This information is needed if a user wants to create a custom RDP file which uses more than one monitor, but not all monitors off the system (e.g not the full-screen option).

Output of the command from a sample machine with 3 monitors attached:
![image](https://user-images.githubusercontent.com/67024372/144174497-aad6c8f6-212b-4c44-9a78-621f82cc0e25.png)

Tested on Windows Server 2019, Windows 10 and 11.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eddd1822-7939-85d7-d010-25963b182434
* Version Independent ID: 8597bd89-e0f0-1f73-8c3c-7215bbf8c0e8
* Content: [mstsc](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mstsc)
* Content Source: [WindowsServerDocs/administration/windows-commands/mstsc.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/mstsc.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey @officedrone,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding the remaining parameters for `mstsc` and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
