### ISSUE TITLE
Can not install MSRDC without admin rights

### ISSUE THREAD

**Issue by damienvanrobaeys** [MicrosoftDocs/windowsserverdocs#6097]
On the doc you mentioned that msi can be installed without admin rights.
As you can see on the picture, it seems not true

![image](https://user-images.githubusercontent.com/8832278/144213151-6edd0994-a280-4881-a292-7c6a2cceb533.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ab98fc-fea2-a11a-e5ca-de1430211d97
* Version Independent ID: 4d9943c3-fef7-ca86-bd03-1241a04b8135
* Content: [Get started with the Windows Desktop client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop#install-the-client)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by jtonzi** [comment]
Is there any update on this one? Having the same issue here. It appears to be keeping MSRDC from properly auto-updating now.

**Comment by davidbordenwi** [comment]
When will this be fixed.  This client is updated constantly.  We need a way to install in user context via INTUNE. The switches that are supposed to do that do not work and it installs in admin context regardless.

**Comment by dknappettmsft** [comment]
Closing the loop on this - this is fixed in the client and it can be installed without admin rights.

@davidbordenwi - we have recently published an article how to do this with Intune: https://learn.microsoft.com/en-us/azure/virtual-desktop/install-client-per-user?tabs=intune

#please-close
