### ISSUE TITLE
Version not updated

### ISSUE THREAD

**Issue by AndreasRogge** [MicrosoftDocs/windowsserverdocs#6099]
Hello,
unfortunately the page seems to be not updated. I have version 1.2.2687.0 on my system.
![image](https://user-images.githubusercontent.com/2961807/144441194-82a139cf-b14e-459e-8046-6c11d708d517.png)

Best regards
Andreas Rogge

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f43e914-5ede-6f18-2fbc-165f3386f7cb
* Version Independent ID: a9489295-572d-ff60-6bff-a44390ac4031
* Content: [What's new in the Windows Desktop client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop-whatsnew)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop-whatsnew.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop-whatsnew.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
Hey AndreasRogge,

Thanks again for contacting Microsoft, we value your feedback. 

Based on the time this issue was created, a documentation update was made and this issue was not closed. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
