### ISSUE TITLE
Anuraaaag

### ISSUE THREAD

**Issue by KGNBAAGI5** [MicrosoftDocs/windowsserverdocs#6103]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b57c088-dd94-0e40-5202-130927d9f23c
* Version Independent ID: 0f4862b3-1bf7-e886-b425-cc003613766f
* Content: [Remote Desktop Services - Connect from any device](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-plan-connect-from-any-device)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-plan-connect-from-any-device.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-plan-connect-from-any-device.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **spatnaik**

**Comment by dknappettmsft** [comment]
#please-close
