### ISSUE TITLE
Access to Local Files

### ISSUE THREAD

**Issue by smfchavez** [MicrosoftDocs/windowsserverdocs#6105]
Windows Cloud Pc (Web Client) No longer shows an option to access local files on my computer. Please Help.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58c2644e-6037-8b15-10e6-e77392cff23a
* Version Independent ID: 1307699a-e45f-0f84-9563-73270bae1a76
* Content: [Get started with the web client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by IngridAtMicrosoft** [comment]
Hi @smfchavez. The GitHub issues on this repo are for reporting problems with documentation.  Please open a support incident for your issue with Windows.
