### ISSUE TITLE
No release information history table (OS Builds) available for Server 2022

### ISSUE THREAD

**Issue by AshleyHow** [MicrosoftDocs/windowsserverdocs#6107]
Windows Server release information at https://docs.microsoft.com/en-us/windows/release-health/windows-server-release-info should have a release history table like windows 10 and 11 showing a history of all released builds for Server 2022. Wouldn't harm to add other server releases too when time allows.

Until the new release of Server 2022 this was not required as previous windows server releases shared the same OS Build (2016 and 2019) with the windows 10 client release and thus shared the same release history present on the windows 10 page - https://docs.microsoft.com/en-us/windows/release-health/release-information

Now that is not the case anymore so this information (not in table format) is only available on https://support.microsoft.com/en-gb/topic/windows-server-2022-update-history-e1caa597-00c5-4ab9-9f3e-8212fe80b2ee but the link to this main page is dead at the moment.

```
Sorry, the page you’re looking for can’t be found.
You may have clicked an old link or the page may have moved.
Please try browsing from our main page .

Request ID: e907187d9561fe4b
```

Even Azure HCI has this and there is a release based on the same OS Build as 2022 - https://docs.microsoft.com/en-us/azure-stack/hci/release-information

Any chance that the following can be sorted please?

1) Link is fixed
2) A release history table for server 2022 added so we have parity as per other server releases and clients.

Thanks

**Comment by IngridAtMicrosoft** [comment]
#assign:dknappettmsft

**Comment by dknappettmsft** [comment]
Hi @AshleyHow, I think what might be going on here is the difference between the fixed lifecycle (long term servicing channel (LTSC)) vs modern lifecycle (semi-annual channel (SAC)).  With Windows Server 2016, 2019 and 2022 they are LTSC releases, so there is only one release, and therefore only one entry in the table on the Windows Server release information page.

Windows 10 has both LTSC releases every 2-3 years and SAC releases roughly every 6 months (historically). Windows 11 has SAC releases only currently.

There have been a number of Windows Server SAC releases, which are not 2016, 2019 or 2022, however there won't be any more of these (https://docs.microsoft.com/en-us/windows-server/get-started/servicing-channels-comparison#semi-annual-channel). The table on the Windows Server release information page contains all of the Windows Server releases - there aren't any missing.

The other link (that's currently not working) looks to be for Windows Updates history.  These are not listed in the release information page as they're not new version releases.  I can't personally fix the broken link, but I will notify the team.

Does that help clear things up?

**Comment by AshleyHow** [comment]
@dknappettmsft 

Thank you for the response. It's not that any releases are missing. What I mean by release history table is the OS build history which is normally updated upon the release of a new cumulative.

For example to obtain Server 2019 OS build history table you used Windows 10 1909 table [here](https://docs.microsoft.com/en-gb/windows/release-health/release-information)

The results of which are 

```
Servicing option	Availability date	Build	KB article
Semi-Annual Channel	2021-11-09	18363.1916	KB5007189
Semi-Annual Channel	2021-10-12	18363.1854	KB5006667
Semi-Annual Channel	2021-09-21	18363.1832	KB5005624
Semi-Annual Channel	2021-09-14	18363.1801	KB5005566
Semi-Annual Channel	2021-08-26	18363.1766	KB5005103
Semi-Annual Channel	2021-08-10	18363.1734	KB5005031
Semi-Annual Channel	2021-07-29	18363.1714	KB5004293
Semi-Annual Channel	2021-07-13	18363.1679	KB5004245
Semi-Annual Channel	2021-07-06	18363.1646	KB5004946
Semi-Annual Channel	2021-06-15	18363.1645	KB5003698
Semi-Annual Channel	2021-06-08	18363.1621	KB5003635
Semi-Annual Channel	2021-05-20	18363.1593	KB5003212
Semi-Annual Channel	2021-05-11	18363.1556	KB5003169
Semi-Annual Channel	2021-04-22	18363.1533	KB5001396
Semi-Annual Channel	2021-04-13	18363.1500	KB5001337
Semi-Annual Channel	2021-03-25	18363.1474	KB5000850
Semi-Annual Channel	2021-03-18	18363.1443	KB5001648
Semi-Annual Channel	2021-03-15	18363.1441	KB5001566
Semi-Annual Channel	2021-03-09	18363.1440	KB5000808
Semi-Annual Channel	2021-02-16	18363.1411	KB4601380
Semi-Annual Channel	2021-02-11	18363.1379	KB5001028
Semi-Annual Channel	2021-02-09	18363.1377	KB4601315
Semi-Annual Channel	2021-01-21	18363.1350	KB4598298
Semi-Annual Channel	2021-01-12	18363.1316	KB4598229
Semi-Annual Channel	2020-12-08	18363.1256	KB4592449
Semi-Annual Channel	2020-11-19	18363.1237	KB4586819
Semi-Annual Channel	2020-11-19	18363.1199	KB4594443
Semi-Annual Channel	2020-11-10	18363.1198	KB4586786
Semi-Annual Channel	2020-10-20	18363.1171	KB4580386
Semi-Annual Channel	2020-10-13	18363.1139	KB4577671
Semi-Annual Channel	2020-09-16	18363.1110	KB4577062
Semi-Annual Channel	2020-09-08	18363.1082	KB4574727
Semi-Annual Channel	2020-08-20	18363.1049	KB4566116
Semi-Annual Channel	2020-08-11	18363.1016	KB4565351
Semi-Annual Channel	2020-07-21	18363.997	KB4559004
Semi-Annual Channel	2020-07-14	18363.959	KB4565483
Semi-Annual Channel	2020-06-16	18363.904	KB4567512
Semi-Annual Channel	2020-06-09	18363.900	KB4560960
Semi-Annual Channel	2020-05-12	18363.836	KB4556799
Semi-Annual Channel	2020-04-21	18363.815	KB4550945
Semi-Annual Channel	2020-04-14	18363.778	KB4549951
Semi-Annual Channel	2020-03-30	18363.753	KB4554364
Semi-Annual Channel	2020-03-24	18363.752	KB4541335
Semi-Annual Channel	2020-03-12	18363.720	KB4551762
Semi-Annual Channel	2020-03-10	18363.719	KB4540673
Semi-Annual Channel	2020-02-27	18363.693	KB4535996
Semi-Annual Channel	2020-02-11	18363.657	KB4532693
Semi-Annual Channel	2020-01-28	18363.628	KB4532695
Semi-Annual Channel	2020-01-14	18363.592	KB4528760
Semi-Annual Channel	2019-12-10	18363.535	KB4530684
Semi-Annual Channel	2019-11-12	18363.476	KB4524570
```

What I would like to see is table for Server 2022 which contains the below :

```
Servicing option	Availability date	Build	        KB article
LTSC	                2021-11-22	        20348.380	KB5007254
LTSC	                2021-11-09	        20348.350	KB5007205
LTSC	                2021-10-26	        20348.320	KB5006745
LTSC	                2021-10-12	        20348.288	KB5006699
LTSC	                2021-09-27	        20348.261	KB5005619
LTSC	                2021-09-14	        20348.230	KB5005575
```

**Comment by dknappettmsft** [comment]
Ok, I follow, it's the terminology that can get a bit confusing. It's the same team I mentioned previously that also deal with this, so I will pass on this feedback and hope we can get this article updated soon.  Thanks!

**Comment by AshleyHow** [comment]
@dknappettmsft 

Thank you, it is appreciated!

**Comment by dknappettmsft** [comment]
#label:doc-enhancement

**Comment by dknappettmsft** [comment]
Hi @AshleyHow, the broken link looks to be fixed now, so you can now get information on Windows Server 2022 updates.  The other request has been logged, but has missed this planning cycle, so it will be a number of months unfortunately.

**Comment by dknappettmsft** [comment]
#please-close
