### ISSUE TITLE
Server 2022 update history went missing

### ISSUE THREAD

**Issue by DSPatrick** [MicrosoftDocs/windowsserverdocs#6108]
https://support.microsoft.com/en-gb/topic/windows-server-2022-update-history-e1caa597-00c5-4ab9-9f3e-8212fe80b2ee
Sorry, the page you’re looking for can’t be found.
You may have clicked an old link or the page may have moved.
Please try browsing from our main page .

Request ID: 8af604e8f9c48048

**Comment by RAJU2529** [comment]
@DSPatrick which article are you referring

**Comment by DSPatrick** [comment]
Its this page here
https://support.microsoft.com/en-gb/topic/windows-server-2022-update-history-e1caa597-00c5-4ab9-9f3e-8212fe80b2ee

**Comment by dknappettmsft** [comment]
This is a duplicate of part of #6107 and the team are investigating. I will close this as it's a duplicate, information will be updated in #6107. Thank you!

#please-close
