### ISSUE TITLE
Desktop Settings - Desktop Resource Settings?

### ISSUE THREAD

**Issue by dodge1350-frp** [MicrosoftDocs/windowsserverdocs#6109]
**Desktop settings**

"You can configure some of the settings for desktop resources to ensure the experience meets your needs. To access the list of available settings right-click on the desktop resource and select Settings"

How about some images of what it is you are describing here?  No idea at all where the "settings for desktop resources" is located.  Not able to find it anywhere.  Those words do not exist within the app.  Really getting tired of having to try and decipher what you mean when all you have to do is show it with screen shots.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ab98fc-fea2-a11a-e5ca-de1430211d97
* Version Independent ID: 4d9943c3-fef7-ca86-bd03-1241a04b8135
* Content: [Get started with the Windows Desktop client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @dodge1350-frp, 

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made and will be live after the next business day. 3 new images were added to address concerns. For your ask specifically, once you open the Windows Remote Desktop Client app, hover over the PC icon in your workspace and right-click on it to get the "Settings" menu:

![windows-remote-desktop-client-3](https://user-images.githubusercontent.com/103963494/189234654-b61135d6-344c-4f59-8c61-267f5a04bb53.png)

We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
