### ISSUE TITLE
Thumbprint format

### ISSUE THREAD

**Issue by jrg-jeff** [MicrosoftDocs/windowsserverdocs#611]
In what format does the installer need the certificate?  Copying and pasting doesn't work.  It gives and error about a known issue, but the window size is too small that it cuts off the error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe84fb4b-3420-bc1e-6a1d-b64ecc56fc5e
* Version Independent ID: f089767e-4613-d595-a0ee-0dab012724a1
* Content: [Install Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/install#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/deploy/install.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/deploy/install.md)
* Service: **unspecified**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by AndresPae** [comment]
remove spaces and make sure not start/end spaces are selected when copying.

**Comment by AndresPae** [comment]
found this also - https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/known-issues#installer

**Comment by badcowlee** [comment]
About the installation of "Windows Admin Centre", does it support to create the container image by using windows container ?

Actually, I tried but failed at the end . Please refer the the error log for the reference.

MSI (s) (78:90) [02:57:46:092]: Running as a service.
MSI (s) (78:90) [02:57:46:094]: Hello, I'm your 32bit Elevated Non-remapped custom action server.
ExecFirewallExceptions: Installing firewall exception2 SmeInboundOpenException on port 443, protocol 6
ExecFirewallExceptions: Error 0x800706d9: failed trying to find existing port rule
ExecFirewallExceptions: Error 0x800706d9: failed to add/update port exception for name 'SmeInboundOpenException' on port 443, protocol 6

**Comment by vidmaster2000** [comment]
Is there an option to skip trying to add a rule to the firewall?  I'm seeing this error when using an existing certificate, but the self generated one works fine:

1: Unhandled Exception: Microsoft.Deployment.WindowsInstaller.InstallerException Failed to reserve port: 443

**Comment by jones85** [comment]
Hi I'm getting the exact error when installing WAC on WS 2016 core but the certificate was requested from my server locally to my CA using certreq.  The private key is exportable too.  Are there any spacific requirments for the certificate that you know of?

**Comment by vidmaster2000** [comment]
It just needs to be a "Web Server" certificate. Are you using AD Certificate Services as your CA?

**Comment by jones85** [comment]
Yes but I've created a new certificate template copying the Web Server template but allowing the P/keys to be exportable.  I found an old blog stating that the keys needed to be exportable (http://bit.ly/2EOsyVy). Does WAC need to have the P/keys exportable or did you simply use the built-in Web Server template?

**Comment by jones85** [comment]
OK, so it would appear that the installation completed successfully when using the WebServer template but, there is nothing on the server listening on 443? (Netstat -a confirmed).  The service is running, I've rebooted the server and disabled the firewall to be sure.

WAC installation log can be found here (http://bit.ly/2qza4nV)
(Apologies if I'm now getting "off topic")

**Comment by vidmaster2000** [comment]
I generated the cert request using the built in Web Server template.  The CSR was generated based on the blog entry in my first comment. I can look at it again when I get back into town tomorrow night.

**Comment by jones85** [comment]
My issue has been opened under a new bug report. #645

**Comment by mioiox** [comment]
There is extra space at the beginning of the thumbprint line - it's practically invisible. Just paste the thumbprint in Notepad and remove anything before the first symbol and you'll be good to go.
Ref - https://support.microsoft.com/en-us/help/2023835/certificate-thumbprint-displayed-in-mmc-certificate-snap-in-has-extra
