### ISSUE TITLE
Wrong wording for location of AD FS federation server

### ISSUE THREAD

**Issue by akasparas** [MicrosoftDocs/windowsserverdocs#6112]
In the section **Where to place a federation server**
first sentence IMHO should read
As a security best practice, place AD FS federation servers _behind_ firewall 
instead of
As a security best practice, place AD FS federation servers _in front of_ a firewall 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edc29383-bec8-c02f-3b53-06e1ee07ffd2
* Version Independent ID: 0d50c96d-faaf-b4dd-cae2-dc32d1e5fcad
* Content: [Plan Your AD FS Deployment Topology](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/design/plan-your-ad-fs-deployment-topology)
* Content Source: [WindowsServerDocs/identity/ad-fs/design/Plan-Your-AD-FS-Deployment-Topology.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/design/Plan-Your-AD-FS-Deployment-Topology.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @akasparas,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting this and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
