### ISSUE TITLE
/dl does not work if printer name contains special characters

### ISSUE THREAD

**Issue by sean-sauve** [MicrosoftDocs/windowsserverdocs#6113]
/dl does not work if printer name contains special characters
Tested with a printer name 'Fax Test Printer With Really Long Name [Special]' and command:
 rundll32 printui.dll PrintUIEntry /dl "Fax Test Printer With Really Long Name [Special]"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d54fe360-2048-e164-75dd-647979679b80
* Version Independent ID: d55477bf-f3c3-0d02-a7ab-c1db032b0a10
* Content: [rundll32 printui.dll,PrintUIEntry](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/rundll32-printui)
* Content Source: [WindowsServerDocs/administration/windows-commands/rundll32-printui.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/rundll32-printui.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @sean-sauve,

Thanks again for contacting Microsoft. We value your feedback. 

Per the documentation, you're missing a modification parameter that follows your base parameter after `/dl`. Using the simplest syntax & printer name:

`rundll32 printui PrintUIEntry /dl /n <"PrinterName">` 

Example:
![image](https://user-images.githubusercontent.com/103963494/198167531-17477e75-d4f0-4c64-996c-53fca09d69ff.png)

Then
![image](https://user-images.githubusercontent.com/103963494/198167811-ed3c0aae-ca28-4f44-9946-c4cfad601076.png)

Using your example:
![image](https://user-images.githubusercontent.com/103963494/198168140-3b9d1564-1b88-419b-b2ee-85a128f36726.png)
![image](https://user-images.githubusercontent.com/103963494/198168189-5d1eed5b-f9c7-4cf8-b939-834f40b452a8.png)

We hope that this addresses your concerns. We will now be closing this thread. 

Thank you and have a most pleasant day! #please-close
