### ISSUE TITLE
OpenId support

### ISSUE THREAD

**Issue by daphneSot** [MicrosoftDocs/windowsserverdocs#6114]
Hello,

It is mentioned that saml artifact flow will not work. Does the same apply for Open ID Connect flow? Since during authentication_code flow, we retrieve a token through the backchannel using the code. If we send the code to the other server in the ADFS farm, it will throw MSIS9252 error. Is this documented somewhere?

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c9dcead-8883-6e08-b630-40d676ef8f7f
* Version Independent ID: 7307ed8f-6f58-7dbf-50d9-53e10c79c010
* Content: [AD FS Deployment Topology Considerations](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/design/ad-fs-deployment-topology-considerations)
* Content Source: [WindowsServerDocs/identity/ad-fs/design/AD-FS-Deployment-Topology-Considerations.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/design/AD-FS-Deployment-Topology-Considerations.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @daphneSot,

Thanks again for contacting Microsoft. We value your feedback.

As we understand it, you're describing a problem with the product itself and not with the product documentation. GitHub isn't quite the right location if searching for technical support as it is completely outside our scope. If there are any issues within the content itself, please let us know.

To get assistance or support for your product issue, as it is quite specific, we recommend you engage with the product community or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs). 

Additional support forums listed below:
- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Hopefully one of our community experts will be able to assist. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
