### ISSUE TITLE
oh no

### ISSUE THREAD

**Issue by DingoCC** [MicrosoftDocs/windowsserverdocs#6115]
the most evil  command in the history of languages.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd43ce44-5d30-7425-336b-58a7fc731c3f
* Version Independent ID: 68adad7a-0a26-2fad-d7c1-d9df45311ebd
* Content: [goto](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/goto)
* Content Source: [WindowsServerDocs/administration/windows-commands/goto.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/goto.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by dknappettmsft** [comment]
#please-close
