### ISSUE TITLE
WAC: Windows Admin Center with Failovercluster / HyperV: Performance Charts / Virtual Disks

### ISSUE THREAD

**Issue by kasimovv** [MicrosoftDocs/windowsserverdocs#6116]
Hello all,

 

I am using Windows Admin Center Version 2110 Build 1.3.2111.01001 with a 4 node FailoverCluster based on Server 2019. I am using the Cluster for HyperV. 

I am not using S2D, I have 4 CSV publsihed from a shared storage.

Both nodes have the latest windows updates.

When I am configuring a VM, the performance charts are not available. In addition and way more critical, the vhd´s are not showing up.

Follwing the errors I encountered:

Notification details

Error

Couldn't get the live performance data
9:54:39 AM
SourceGo to Virtual machines.
Type

Error
Message

There was an error getting the performance live chart data for ITIMRELAY01. Error: RemoteException: Failed Activity ID: {20aa0f8a-e39f-0015-5a2b-aa209fe3d701}

Notification details

Error

Couldn't get the virtual disks.
9:54:34 AM
SourceGo to Virtual machines.
Type

Error
Message

There was an error loading the virtual disks of virtual machine 'ITIMRELAY01'. Error: RemoteException: Failed to find SDDC Management resource, reason : No more data is available.

![изображение](https://user-images.githubusercontent.com/20535897/145765548-4ec82412-c31e-4d3e-9d63-0bb393ad9a03.png)

I checked on the S2D cluster there are no such errors.

**Comment by chips2014** [comment]
Do you have a microsoft account logged in or an azure id logged in? I think that would work.

**Comment by kasimovv** [comment]
> Do you have a microsoft account logged in or an azure id logged in? I think that would work.

Hi.

I checked on the S2D cluster there are no such errors. This situation is related to FailoverCluster.

**Comment by chips2014** [comment]
@kasimovv Since there are no errors. Can we close?
 (I AM NOT THE PERSON TO CLOSE THIS THOUGH)

**Comment by kasimovv** [comment]
> @kasimovv Since there are no errors. Can we close? (I AM NOT THE PERSON TO CLOSE THIS THOUGH)

Hi. Why close? The problem is present, and it is reproduced on FailoverCluster, if connect an s2d cluster for example, then it will not be reproduced on it. In both situations, the same account is used. Found same problem: [https://techcommunity.microsoft.com/t5/windows-admin-center/admin-center-with-failovercluster-hyperv-performance-charts/m-p/686776](url)

**Comment by chips2014** [comment]
?close aft 2MSREPRESENTIVE.rspnded/suc\USR: @chips2014(OWNER), @kasimovv(USER)

**Comment by chips2014** [comment]
Can I have your email so I can add you to a ticket?? It was raised by another member in my org. (I AM THE FOUNDER).

**Comment by chips2014** [comment]
ONLY GMAIL WORKS

**Comment by kasimovv** [comment]
> Can I have your email so I can add you to a ticket?? It was raised by another member in my org. (I AM THE FOUNDER).

Sure. - vik2kg@gmail.com

**Comment by IngridAtMicrosoft** [comment]
Thank you for contacting Microsoft. GitHub issues on this repo are for reporting problems with Windows Server documentation.  Please open a support ticket to get assistance.
