### ISSUE TITLE
Documentation is missing important parameters

### ISSUE THREAD

**Issue by danielniccoli** [MicrosoftDocs/windowsserverdocs#6117]
The -key -delkey and -csp parameters are missing entirely in these docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d238db2c-10e1-d418-e780-54b421779754
* Version Independent ID: d1313e31-d990-2f0b-3f70-ae0fcdb4ba5c
* Content: [certutil](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/certutil)
* Content Source: [WindowsServerDocs/administration/windows-commands/certutil.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/certutil.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey danielniccoli,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding several missing parameters from the CertUtil doc and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
