### ISSUE TITLE
Missing Parenthesis

### ISSUE THREAD

**Issue by jwmoss** [MicrosoftDocs/windowsserverdocs#6119]
One of the scriptblocks are missing parenthesis, I submitted #6118 to fix it.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fddc3bb1-c473-300c-9826-7aaa61e257ef
* Version Independent ID: 1cb03710-5f57-dade-0e74-a19c3aeabc54
* Content: [Scripting with Storage Spaces Direct performance history](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/performance-history-scripting)
* Content Source: [WindowsServerDocs/storage/storage-spaces/performance-history-scripting.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/performance-history-scripting.md)
* Product: **windows-server**
* Technology: **storage-spaces**
* GitHub Login: @cosmosdarwin
* Microsoft Alias: **cosdar**

**Comment by Xelu86** [comment]
Hey jwmoss,

Thanks again for contacting Microsoft, we value your feedback. 

We have merged your contribution into this documentation page. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
