### ISSUE TITLE
Networking Parameters are missing from the Install instructions

### ISSUE THREAD

**Issue by SqlTechMike** [MicrosoftDocs/windowsserverdocs#612]
The -staticAddress and -ignoreNetwork parameters are missing from the description of the install script

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32deb7a0-4ea0-caf1-0777-580539173e44
* Version Independent ID: a6ee1f9d-b316-c69d-fa9d-2a1556454868
* Content: [Deploy Windows Admin Center with High Availability](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/high-availability)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/deploy/high-availability.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/deploy/high-availability.md)
* Service: **unspecified**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by Haley-Rowland** [comment]
Thanks for catching the -staticAddress omission! I'll add that in. There is no parameter for -ignoreNetwork in the script.

**Comment by SqlTechMike** [comment]
Please see the error message that I encountered below.  I believe the -IgnoreNetwork parameter belongs to the Add-ClusterGenericServiceRole cmdlet, which I would expect the -StaticAddress parameter is being passed to

"Add-ClusterGenericServiceRole : Static network xxx.xxx.xxx.0/24 was not configured. Please use -StaticAddress to use this network or use -IgnoreNetwork to ignore it."

**Comment by dchina** [comment]
Add-ClusterGenericServiceRole : Static network 172.16.103.0/24 was not configured. Please use -StaticAddress to use thi
s network or use -IgnoreNetwork to ignore it.
At C:\R930\Install-WindowsAdminCenterHA.ps1:529 char:17
+ ...     $role = Add-ClusterGenericServiceRole -ServiceName ServerManageme ...
