### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by MichaelHall001** [MicrosoftDocs/windowsserverdocs#6121]
[Enter feedback here]
 You have a typo.  It says browse r 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cae6d9d8-4a22-f41e-a43f-b88816ae4519
* Version Independent ID: aad0e220-49d9-b9bc-10b7-ea0155af1d96
* Content: [AD FS Troubleshooting - Integrated Windows Authentication](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-iwa)
* Content Source: [WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-iwa.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-iwa.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We've submitted a documentation change based on your suggestion. Changes will be live after the next business day. This issue has been resolved and we are closing the issue. #please-close

**Comment by Xelu86** [comment]
#assign:xelu86
