### ISSUE TITLE
7 = Notify for install and notify for restart

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/windowsserverdocs#6128]
I believe there should be an option "7 = Notify for install and notify for restart" under "Configure Automatic Updates" for Windows Server.
I can only find 3rd party sources like this one, but this seems to have been added nearly two years ago.
https://www.vacuumbreather.com/index.php/blog/item/93-group-policy-changes-in-windows-10-20h1-preview

The Azure Automation doc here is pointing to the doc I am submitting feedback on and saying to choose value 7, so it would be very helpful to have that setting documented here.
https://docs.microsoft.com/en-us/azure/automation/update-management/configure-wuagent#pre-download-updates

You can reach me internally at v-dibr if you need more context, thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d9a7aaf-447d-a2dd-d7f6-828f277a00ea
* Version Independent ID: c3dd7389-454f-870d-5502-46544d6336dc
* Content: [Step 4 - Configure Group Policy Settings for Automatic Updates](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/deploy/4-configure-group-policy-settings-for-automatic-updates#configure-automatic-updates)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/deploy/4-configure-group-policy-settings-for-automatic-updates.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/deploy/4-configure-group-policy-settings-for-automatic-updates.md)
* Product: **windows-server**
* Technology: **wsus**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by v-thepet** [comment]
Hello @dcbrown16, and @IanJDan,

Thanks for contacting Microsoft. We value your feedback.

Documentation changes have been made to address this and other issues and are now live.

Thank you again and have a most pleasant day.
#please-close
