### ISSUE TITLE
Links are broken or pointing to old data

### ISSUE THREAD

**Issue by mattdreher** [MicrosoftDocs/windowsserverdocs#6131]
The links under the line no longer work correctly.

Go to GitHub, and download the tss_tools.zip file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70ed7e4c-0e62-887f-e3aa-db50bcb9d2b9
* Version Independent ID: 4d40f939-2773-a34b-ff7b-4f9d8e29878b
* Content: [Troubleshoot problems on the DHCP server](https://docs.microsoft.com/en-us/windows-server/troubleshoot/troubleshoot-problems-on-dhcp-server)
* Content Source: [WindowsServerDocs/troubleshoot/troubleshoot-problems-on-dhcp-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/troubleshoot/troubleshoot-problems-on-dhcp-server.md)
* Product: **windows-server**
* Technology: **troubleshoot**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by RAJU2529** [comment]
@Deland-Han , Sir please verify this PR #6132, and merge if correct.

**Comment by Deland-Han** [comment]
The change looks good to me but I don't have the permission to merge the PR.

**Comment by v-thepet** [comment]
Hi @mattdreher,

Thanks again for contacting Microsoft. We value your feedback.

A documentation change has been made with an updated link and instructions for the TSS tools and will be live after the next business day. We will now be closing this thread.

Thank you and have a most pleasant day.
#please-close
