### ISSUE TITLE
Total solution. It Works!

### ISSUE THREAD

**Issue by Tolga83** [MicrosoftDocs/windowsserverdocs#6133]
Thanks for the detailed solutoin, this is really hard to find solution via internet, thanks!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a91db45-ca3c-7a2e-3f32-2f5b57837b03
* Version Independent ID: b83cbaab-c0df-d6e7-a67f-f4c99a46e30a
* Content: [How to detect, enable and disable SMBv1, SMBv2, and SMBv3 in Windows](https://docs.microsoft.com/en-au/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3#for-windows-7-windows-server-2008-r2-windows-vista-and-windows-server-2008)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by RAJU2529** [comment]
@Tolga83 . I am very happy to hear the solutions mentioned in this article worked for you. Thanks for your feedback and conformation

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @Tolga83,

Thanks again for contacting Microsoft. We value your feedback. 

We're glad this documentation was able to provide a solution to a potential issue. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
