### ISSUE TITLE
Dllcache doesn’t exist anymore

### ISSUE THREAD

**Issue by garegin16** [MicrosoftDocs/windowsserverdocs#6134]
“If this command discovers that a protected file has been overwritten, it retrieves the correct version of the file from the systemroot\system32\dllcache folder, and then replaces the incorrect file.“

In Vista and above, Windows doesn’t have the dllcache folder.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d979606-3b11-34e5-70db-88d90855cf5c
* Version Independent ID: d2358e0b-7688-ac7f-0f08-fc198b6a57a9
* Content: [sfc](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/sfc)
* Content Source: [WindowsServerDocs/administration/windows-commands/sfc.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/sfc.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey @garegin16,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
