### ISSUE TITLE
Imported VM types

### ISSUE THREAD

**Issue by lkordos** [MicrosoftDocs/windowsserverdocs#6136]
It is not clear which VM types are supported for import. For example, can I directly import OVA VMs from VirtualBox? etc...
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acc00093-1f29-7e3b-ab30-9e6966598390
* Version Independent ID: bd281aaf-4e09-73a4-95a0-873ab4cc5de2
* Content: [Export and import virtual machines](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/deploy/export-and-import-virtual-machines#import-types)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/deploy/Export-and-import-virtual-machines.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/deploy/Export-and-import-virtual-machines.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by Xelu86** [comment]
Hey ikordos,

Thanks again for contacting Microsoft, we value your feedback. 

This document, steps discussed, and examples all surround our Hyper-V technology for importing/exporting VMs. Both the PowerShell modules, [Import-VM](https://learn.microsoft.com/en-us/powershell/module/hyper-v/import-vm?view=windowsserver2022-ps) & [Export-VM](https://learn.microsoft.com/en-us/powershell/module/hyper-v/emport-vm?view=windowsserver2022-ps) belong to Hyper-V. 

This document is not meant for importing/exporting third-party VMs.

As this is a non-documentation issue, we'll now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
