### ISSUE TITLE
.\toc*.yml REPLACE .\*\toc.yml in 2 place

### ISSUE THREAD

**Issue by Andre-w** [MicrosoftDocs/windowsserverdocs#6137]
9. This example copies all the non-empty directories, plus files whose name match the pattern given with the asterisk symbol.

xcopy .\toc*.yml ..\..\Copy-To\ /S /Y (***REPLACE xcopy .\*\toc.yml ..\..\Copy-To\ /S /Y)

rem Output example.
rem  .\d1\toc.yml
rem  .\d1\d12\toc.yml
rem  .\d2\toc.yml
rem  3 File(s) copied

In the preceding example, this particular source parameter value .\toc*.yml (***REPLACE .\*\toc.yml) copies the same 3 files even if its two path characters .\ were removed. However, no files would be copied if the asterisk wildcard was removed from the source parameter, making it just .\toc.yml.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a1e859-b436-290e-69c0-810dd3a5ce90
* Version Independent ID: 10c81289-2bf7-40d9-39ea-e624cf92aa3e
* Content: [xcopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/xcopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/xcopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/xcopy.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @Andre-w,
 
Thanks again for contacting Microsoft. We value your feedback. 

Running the example you have provided, moving the asterisk from `xcopy .\toc\*.yml` to `xcopy .*\toc.yml` will yield the following result:

![image](https://user-images.githubusercontent.com/103963494/186299215-e67d93d0-d13d-484e-92ae-daf0c765c262.png)

Running a similar example in the article yielded the following:
 
![image](https://user-images.githubusercontent.com/103963494/186300499-27b71948-b3c8-4aa6-a278-ccb740be4575.png)

The reason why the asterisk is placed before the file extension is to copy all files with the referenced extension, in this case, "**.yml**". Minor revisions have been made to this article and will be live after the next business day.

We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
