### ISSUE TITLE
Example command is incorrect

### ISSUE THREAD

**Issue by PJMarcum** [MicrosoftDocs/windowsserverdocs#6139]
The example command "manage-bde -protectors -adbackup C:" is incorrect. This doc also states that "the -id parameter is required" when using -adbackup or -aadbackup  however it does not explain what the ID is nor how to get the id.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82ef6d71-4070-a941-ccc2-868e435e7c18
* Version Independent ID: 1a9eac49-6fd4-de12-9c8a-452ee31f6bc7
* Content: [manage-bde protectors](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/manage-bde-protectors)
* Content Source: [WindowsServerDocs/administration/windows-commands/manage-bde-protectors.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/manage-bde-protectors.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey PJMarcum,

Thanks again for contacting Microsoft. We value your feedback. 

Looking into this, the `-get` parameter in the table explains that the ID is associated to the protector and retrieves it:

|Parameter | Description|
|-- | --|
|-get | Displays all the key protection methods enabled on the drive and provides their type and identifier (ID).|

So running `manage-bde -protectors -get DriveLetter:` will provide the ID.

The example used to back up the recovery password for a BitLocker-protected drive to Active Directory is correct. It would look similar to:  

`manage-bde -protectors -adbackup C: -id {12345678-ABCD-ABCD-ABCD-123456789012}`

You should replace "{12345678-ABCD-ABCD-ABCD-123456789012}" with the actual ID of the protector that you want to back up.

As there isn't a documentation issue, we'll be closing this thread.

Thank you and have a most pleasant day. 
#please-close
