### ISSUE TITLE
Possible to test on Win10?

### ISSUE THREAD

**Issue by forderud** [MicrosoftDocs/windowsserverdocs#614]
Is it possible to activate the RDP web client also on Windows 10 professional, or is Windows server strictly needed also for test purposes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin#troubleshooting)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Service: **unspecified**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by davidbel** [comment]
@forderud For the current web client, it is only supported as part of an RDS 2016 or 2019 deployment. We are looking for additional scenarios to enable in the future.
