### ISSUE TITLE
Recommending AD FS & AD DS on same server instance

### ISSUE THREAD

**Issue by Snozzberries** [MicrosoftDocs/windowsserverdocs#6141]
This may be a questionable good practice.

> DC/AD FS Servers: If you have fewer than 1,000 users you can simply install AD FS role on your domain controllers. If you do not want any performance impact on the domain controllers or if you have more than 1,000 users, then deploy AD FS on separate servers.

https://twitter.com/adfskitteh/status/1473705151231836164

https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/how-to-connect-fed-azure-adfs#:~:text=DC/AD%20FS%20Servers%3A%20If%20you%20have%20fewer%20than%201%2C000%20users%20you%20can%20simply%20install%20AD%20FS%20role%20on%20your%20domain%20controllers.%20If%20you%20do%20not%20want%20any%20performance%20impact%20on%20the%20domain%20controllers%20or%20if%20you%20have%20more%20than%201%2C000%20users%2C%20then%20deploy%20AD%20FS%20on%20separate%20servers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ac8cd29-26cd-47da-5b3e-d58ba7c4a20c
* Version Independent ID: ae9587c8-0822-f5af-98ef-5386c4f17e58
* Content: [Active Directory Federation Services in Azure](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/how-to-connect-fed-azure-adfs)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/how-to-connect-fed-azure-adfs.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/how-to-connect-fed-azure-adfs.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Heidilohr** [comment]
We recently updated this article to clarify the wording. I'm going to close this issue now.
