### ISSUE TITLE
Missing /

### ISSUE THREAD

**Issue by EthanHermsey** [MicrosoftDocs/windowsserverdocs#6142]
From deduction I think I can make up that there's a / missing before belownormal on this part:
{/low | /normal | /high | /realtime | /abovenormal | belownormal}

You'll find it in two places with ctrl+f. 

Kind regards,
Ethan Hermsey

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a52b78b6-e846-0b32-25c0-f9aab145b112
* Version Independent ID: 0c56bb98-4f1f-dd55-63ae-8bb18535cee1
* Content: [start](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start)
* Content Source: [WindowsServerDocs/administration/windows-commands/start.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/start.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @EthanHermsey, 

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made reflecting new updates and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
