### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by sbjornda** [MicrosoftDocs/windowsserverdocs#6146]
The link to NTbackup.exe download is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fee80a6-7593-5d46-00d0-3b99e40513bd
* Version Independent ID: 7a0a3ae2-e349-740f-013a-b7846fb1533f
* Content: [ntbackup](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/ntbackup)
* Content Source: [WindowsServerDocs/administration/windows-commands/ntbackup.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/ntbackup.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @sbjornda,

Thanks again for contacting Microsoft. We value your feedback. 

The NTBackup utility is no longer provided as a downloadable file via our Docs page in favor of wbadmin. We apologize for this in convenience. We recommend that you open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs) to see if they're able to provide you this tool. This is out of scope for us as of now.

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
