### ISSUE TITLE
Are there any performance/latency trade-offs?

### ISSUE THREAD

**Issue by forderud** [MicrosoftDocs/windowsserverdocs#615]
Can you please document the performance characteristics of the RDP web client, compared to the RDP desktop application? In particular, does it perform any server-side re-encoding of the RDP stream that affects latency?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin#troubleshooting)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Service: **unspecified**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by davidbel** [comment]
@forderud The Remote Desktop web client does not any server side re-encoding and has an RDP connection all the way from the web client to the end-point. It leverages the same codecs as the native clients and will generally perform with similar results.

**Comment by forderud** [comment]
Thank you for the reassuring explanation @davidbel . This was the answer I was hoping for.
