### ISSUE TITLE
Follow Along Silently As I Read Aloud:   Did You Test This Documented Procedure?   Windows 2019 Server

### ISSUE THREAD

**Issue by 5U8cVs** [MicrosoftDocs/windowsserverdocs#6156]
Install-WindowsFeature DirectAccess-VPN -IncludeManagementTools

Install-WindowsFeature : The term 'Install-WindowsFeature' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f49053-d4b0-03cd-2572-366af6d2b943
* Version Independent ID: 05ec3fce-bcc0-3833-82fd-96abc10b9dda
* Content: [Configure the Remote Access Server for Always On VPN](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-ras)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-ras.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-ras.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **inhenkel**

**Comment by anaharris-ms** [comment]
@5U8cVs Sorry for the late reply to this issue. Have you been able to find a resolution? If not, can you supply more details about the scenario. Are you using the x86 version of PowerShell? I assume you are running Windows Server 2019. Any other info would be helpful!

Thank you!

**Comment by anaharris-ms** [comment]
#please-close no customer response.
