### ISSUE TITLE
What Registry key does `cleanmgr` create with the `/sageset:n` option?

### ISSUE THREAD

**Issue by astrohart** [MicrosoftDocs/windowsserverdocs#6157]
Hello,

It would help to use this document, about the `cleanmgr` utility in Windows, if it were a bit more specific.

For example, the document says that the `/sageset:n` option:

"Displays the Disk Cleanup Settings dialog box and also **creates a registry key to store the settings that you select**. The n value, which is stored in the registry, allows you to specify tasks for Disk Cleanup to run. The n value can be any integer value from 0 to 9999." (emphasis mine)

WHAT Registry key does it create?  Do not know, because the document does not say, ever.

I would like to humbly suggest that the specific Registry key (or the pattern of the key name, if there are variables involved) that gets created when `cleanmgr` is launched with the `/sageset:n` switch applied, be listed somewhere in this document.

You can tell me what the key is in response to this issue, here, but I would not consider this issue to be in `Resolved` status until the source document -- referenced below -- is updated.

Thank you for considering this suggestion.

Brian Hart

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 768ab539-031f-b493-edc9-2958ced20fc2
* Version Independent ID: cab3aa07-fc05-1a74-875b-fd37983593d4
* Content: [cleanmgr](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cleanmgr)
* Content Source: [WindowsServerDocs/administration/windows-commands/cleanmgr.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/cleanmgr.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by craigcaseyMSFT** [comment]
Hello @astrohart,

Thanks for contacting Microsoft. We value your feedback.

Documentation changes have been made to clarify and acknowledge this issue. The doc changes will be live after the next business day.

Thank you again and have a most pleasant day.
#please-close
