### ISSUE TITLE
This page does not actually explain how Kerberos works in AD, the title says "Kerberos Authentication Overview" which is very misleading. Please either explain how Kerberos Authentication works or change the title. 

### ISSUE THREAD

**Issue by gary-RR** [MicrosoftDocs/windowsserverdocs#6158]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a5145ff-059a-67db-0c24-34f8b63fda6a
* Version Independent ID: af9468c7-e7f1-a22a-4b99-1acad8c8de62
* Content: [Kerberos Authentication Overview](https://docs.microsoft.com/en-us/windows-server/security/kerberos/kerberos-authentication-overview)
* Content Source: [WindowsServerDocs/security/kerberos/kerberos-authentication-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/kerberos/kerberos-authentication-overview.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by gary-RR** [comment]
The title ": Kerberos Authentication Overview" is very misleading because the page does not actually explain how Kerberos authentication works specially in AD.

**Comment by dksimpson** [comment]
Hi @gary-RR,

This article is going away soon and its information will be consolidated in other articles. For info about Kerberos authentication, please see [Windows Authentication Overview](https://learn.microsoft.com/windows-server/security/windows-authentication/windows-authentication-overview#related-resources).

#please-close
