### ISSUE TITLE
ServiceAccountCredential should not be mandatory if run with ServiceAccountCredential

### ISSUE THREAD

**Issue by Ramexises** [MicrosoftDocs/windowsserverdocs#617]
Not all ADFS intallations use a gMSA (I agree this would be best or at least better practice).
We do not and therefore cannot use a schedule Task to run the backups without putting the creds in the Powershell script that are easily recoverable.
Any options on this?
Regards
Keith

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a58b49ca-ae39-132e-adbd-6766a8019a89
* Version Independent ID: fdf31266-bc9e-8880-0073-00cf1cad2897
* Content: [AD FS Rapid Restore Tool](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/ad-fs-rapid-restore-tool)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/AD-FS-Rapid-Restore-Tool.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/AD-FS-Rapid-Restore-Tool.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by jodyhendrix** [comment]
I recently checked in a change to fix this behavior.  As long as the RunAs account has permissions to ADFS and the DKM container, it will perform the backup without requiring either DA or explicit credentials.  This fixes this problem as well as removes the DA requirement for gMSA.

We'll be publishing a new version, which includes these changes, later this week.

**Comment by jodyhendrix** [comment]
We published build 1.0.75.0 which fixes this problem.  Let us know if you run into any issues.
