### ISSUE TITLE
On User Environment Variables

### ISSUE THREAD

**Issue by NeapolitanSuitcase** [MicrosoftDocs/windowsserverdocs#6184]
[Enter feedback here]
Is there a way to view the PATH for user environment variables seperately?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b20eed0-caa5-60b4-5212-bfd0cde965cc
* Version Independent ID: a8cddc32-9e0a-9102-3a55-86b16fe6fdd6
* Content: [path](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/path)
* Content Source: [WindowsServerDocs/administration/windows-commands/path.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/path.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @NeapolitanSuitcase,

Thanks again for contacting Microsoft. We value your feedback. 

To view user variables can be done in CMD:

- `echo %path%`
- `reg query "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" /v path` (you can also follow this in the registry for GUI representation).
-- Both above output the same information differently

Running `set` in CMD will output all the variables and not just the user.

You can also do this in PowerShell:

- `Get-ChildItem env: | Format-List` for all variables
- `Get-ChildItem env:path | Format-List` for current user

GitHub may not be the best place looking for an answer that is outside the product documentation. It would be best to inquire via our support forums listed below:

- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/
- You could also open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs). 

Hopefully this is the answer you were looking for(?) and if not, one of the community experts will be able to better assist. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
