### ISSUE TITLE
Incorrect validity of Temporary RDS CALs

### ISSUE THREAD

**Issue by tusharchandwani** [MicrosoftDocs/windowsserverdocs#6186]
Temporary RDS CALs validity is incorrectly mentioned as 52–89 days. 
Temporary RDS CALs are valid for upto 90 days, whereas permanent RDS CALs (once upgraded from permanent CALs) are valid for a random period between 52-89 days.

Ref.:
https://social.technet.microsoft.com/wiki/contents/articles/21180.remote-desktop-licensing-demystified.aspx
https://techcommunity.microsoft.com/t5/ask-the-performance-team/multiple-per-device-rds-cals-are-issued-the-same-device-issue/ba-p/375639 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd015c0b-3360-88fd-86b1-08e8c0e8ec5e
* Version Independent ID: 0c3ddb09-23f3-68a3-e7a4-877951feb55b
* Content: [License your RDS deployment with client access licenses (CALs)](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-client-access-license#rds-cal-version-compatibility)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-client-access-license.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-client-access-license.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by v-thepet** [comment]
Hello @tusharchandwani,

Thank you for contacting Microsoft. We appreciate your feedback.

Documentation changes have been made to correct this issue and provide more information. The changes will be live after the next business day. We will now be closing this thread.

Thank you and have a most pleasant day.
#please-close
