### ISSUE TITLE
NFS Support for Windows 11?

### ISSUE THREAD

**Issue by bretter** [MicrosoftDocs/windowsserverdocs#6192]
This page addresses versions of NFS supported by other versions of Windows but makes no mention of Windows 11

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20741e00-6d40-c122-88b2-562b38d39b1e
* Version Independent ID: e556fb83-dc86-94ed-d0e0-616a6499c1e8
* Content: [Network File System overview](https://docs.microsoft.com/en-us/windows-server/storage/nfs/nfs-overview)
* Content Source: [WindowsServerDocs/storage/nfs/nfs-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/nfs/nfs-overview.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86
