### ISSUE TITLE
WSRM on Windows 2016?!

### ISSUE THREAD

**Issue by knut1er** [MicrosoftDocs/windowsserverdocs#6197]
Hello, Windows System Resource Manager is mentionned for Win2016/19/22. Does it exists really?
Isnt'it a mistake?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc70a4f8-73ca-941a-d0a5-9be63265bf03
* Version Independent ID: c8b45148-0319-c05e-773d-a4d4b66e6c9c
* Content: [Comparison of Standard and Datacenter editions Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/get-started/editions-comparison-windows-server-2016)
* Content Source: [WindowsServerDocs/get-started/editions-comparison-windows-server-2016.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/editions-comparison-windows-server-2016.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by dknappettmsft** [comment]
Thanks for flagging this, not sure what it was doing there since it was deprecated in Windows Server 2012. I have removed the entries and the changes should be visible later today.

#please-close
