### ISSUE TITLE
AdminSDHolder members Windows Server 2019 and Windows Server 2022

### ISSUE THREAD

**Issue by morph707** [MicrosoftDocs/windowsserverdocs#6199]
What about AdminSDHolder members for Windows Server 2019 and Windows Server 2022?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d03c8028-a0b9-f28a-c795-85f03563b549
* Version Independent ID: c1c8c10b-12e1-74fb-d824-10eeb924e73e
* Content: [Appendix C - Protected Accounts and Groups in Active Directory](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/appendix-c--protected-accounts-and-groups-in-active-directory)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-C--Protected-Accounts-and-Groups-in-Active-Directory.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-C--Protected-Accounts-and-Groups-in-Active-Directory.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by IngridAtMicrosoft** [comment]
AdminSDHolder content exists in document and applies to line has been updated.
