### ISSUE TITLE
How to I use this feature once installed?

### ISSUE THREAD

**Issue by MFaklis** [MicrosoftDocs/windowsserverdocs#6200]
I did the feature install on my hyper-v server 2016, so now how do I use it.  This page says to mount the ISO, but no ISO was installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42e7fb95-09a6-1dec-859a-08261408b289
* Version Independent ID: 823213b4-7445-da48-fb1f-82c5e74dc1af
* Content: [Server Core App Compatibility Feature on Demand (FOD) in Windows Server](https://docs.microsoft.com/en-us/windows-server/get-started/server-core-app-compatibility-feature-on-demand)
* Content Source: [WindowsServerDocs/get-started/server-core-app-compatibility-feature-on-demand.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/server-core-app-compatibility-feature-on-demand.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @dknappettmsft
* Microsoft Alias: **daknappe**

**Comment by dknappettmsft** [comment]
Hi @MFaklis, I don't quite follow - App Compatibility FOD adds some extra components to a Server Core installation of Windows Server to help with administration, or increase the compatibility of other apps, all without adding the full graphical interface.  It's not an application itself that you can run. For example, it adds Event Viewer, so you can run eventvwr.msc from a command line or PowerShell prompt.  This is detailed in the article.

An ISO doesn't get installed, all you're trying to do here is mount it so you can run commands from that location. Could you provide more detail about where in the article you're blocked?  You can mount the ISO using any method you like.

GitHub issues in this repo are for the contents of the article, which I can change if there's something that's incorrect or needs updating, but if you need product support, please contact Microsoft Support (https://support.microsoft.com/contactus).

**Comment by dknappettmsft** [comment]
#assign:dknappettmsft

**Comment by MFaklis** [comment]
I'll attempt to clarify my question.
**Background:**  I am running Win10 Pro x64 at the current release.  I have some hyper-v machines running on that.  I brought up another machine, with the same configuration, with the intent of migrating some of my virtual machines over to it.  I installed Hype-V Server 2016 the 2nd machine.  I found I couldn't configure that 2nd machine from my Win 10 Pro machine using the RSAT tool set I'm familiar with, at least configure to the extent I wish to.  
**Problem:**  Most  RSAT tools, other than the event viewer, do not allow me to connect to another machine (i.e., my Hyper-V Server 2016).  Those which do have the capability to connect to another machine, don't work as I tend to get a message like "RPC is unavailable".  The services.msc does work and does confirm that RPC and remote registry services are running on the Hyper-v server 2016.  I thought it might be a firewall problem, but the firewall app has no capability to connect to a remote machine.  Obviously I was missing some elementary step in installing Hyper-v server 2016, as references to that server describe that it is to be administered remotely, but how?
I was searching for documentation on how to manage Hyper-V Server 2016 from my Windows 10 machine, by my searches kept returning how to manage Hyper-V on Win 10 or on server 2016.  From a doc on managing server 2016, there was a reference to Server Core App Compatibility Feature on Demand (FOD)  https://docs.microsoft.com/en-us/windows-server/get-started/server-core-app-compatibility-feature-on-demand .  The components shown for the FOD are already included with Win 10 Pro, so doing the Add-WindowsCapability -Online -Name ServerCore.AppCompatibility~~~~0.0.1.0 comannd on my Win 1- machine seemed useless, so I believed it meant for me to execute that command on my Hyper-V server 2016 machine, so I did so.  Afterwards, I still couldn't execute the *.msc apps on the Hyper-V Server 2016.  Reading further, it says ti mount  the FOD ISO.  I can find no such ISO.  I went back and attempted to do the add-windowscapabilkity on my win 10 machine, but no ISO was installed.  The existing RSAT apps remained unchanged.  I tried to download the FOD ISO from the Microsoft.com, but I can't find it there.
**How to proceed?:** 
I can connect to my remote Hyper-v server 2016 with Remote Desktop Connection.  I can run commands with the SysInternals psexec.exe.  I cannot find any documentation on how to fully administer a Hyper-V server OS with only command line apps.  I want to administer; the firewall, disk management, the control panel System app to I can configure the path and page file, and most importantly, I need to be able to setup and manage the server backup wbadmin.  I thought the Server Core App FOD would help, but and couldn't get past the add-windowscapability step.

**Comment by dknappettmsft** [comment]
Hi, Server Core App Compatibility Feature on Demand isn't for Windows 10 or Hyper-V Server, it's for Windows Server when installed as a Server Core installation.  We have an article on [how to remotely manager Hyper-V hosts](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/remotely-manage-hyper-v-hosts).

GitHub issues in this repo are for article issues, updates, etc. and not for product support. Your question is best directed to [Microsoft Support](https://support.microsoft.com/contactus) or one of the TechCommunity forums, either for [Windows](https://techcommunity.microsoft.com/t5/windows/ct-p/Windows10) or [Windows Server](https://techcommunity.microsoft.com/t5/windows-server/ct-p/Windows-Server).

I hope that helps.

#please-close
