### ISSUE TITLE
True: is the key value 1 or 0xFFFFFFFF?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/windowsserverdocs#6203]
There is confusion about value '1' versus non-zero. This article still mentions non-zero, while others are modified to explicitly state '1'.
I have had issues solved by changing 0xFFFFFFFF to 1 wikth the help of MS Premier support who stated clearly "it must be 1".
Please fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd180142-4c19-8abc-ecce-e4c7e5ac8951
* Version Independent ID: fc5bba87-afad-1729-8f7e-333c73188b73
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @andrePKI,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made surrounding the terminology used and will be live after the next business day. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
