### ISSUE TITLE
Step 6. refers to server 2016 - should reflect 2019 

### ISSUE THREAD

**Issue by RobertGendreau** [MicrosoftDocs/windowsserverdocs#6207]
In step 6, it should says: "Now on the Windows Server 2016 federation server open AD FS Management. Note that now all of the admin capabilities appear because the primary role has been transferred to this server."

Should be: "Now on the Windows Server 2019 federation server open AD FS Management. Note that now all of the admin capabilities appear because the primary role has been transferred to this server."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5a924c8-8933-cb05-d4d1-8ac3cf64d1a9
* Version Independent ID: 15f1d47c-f8ec-7b76-7dbd-9bae4de99125
* Content: [Upgrading to AD FS in Windows Server 2016 and 2019](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @RobertGendreau,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change was made, and this issue was not closed. Changes are live. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
