### ISSUE TITLE
Ports list

### ISSUE THREAD

**Issue by AndresPae** [MicrosoftDocs/windowsserverdocs#621]
Even we know that Gateway uses RemotePowershell and WMI over WinRM for communication to target systems maybe it is better to list ports required for functioning. Also what enable in Windows local FW and how to make it secure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0a80173-16ed-bc1f-d257-199bf7fed581
* Version Independent ID: 00efc9b1-752b-94ad-c875-a8bcf59b12af
* Content: [Prepare your environment for Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/prepare-environment#prepare-windows-server-2012-and-2012-r2)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/deploy/prepare-environment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/deploy/prepare-environment.md)
* Service: **unspecified**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by noz482** [comment]
Yes please, this.

**Comment by Geogboe** [comment]
A port list for *any* application would be awesome!

**Comment by carllennon** [comment]
Any update on an actual port list?

**Comment by jwwool** [comment]
Windows Admin Center uses WinRM on port 5985 to communicate between the gateway and the managed node. If you are using RDP, you will also need 3389 open between the gateway and managed node.

The port for the Windows Admin Center UI is configurable in the installer, it defaults to 443.

Those are the only ports required for Windows Admin Center.
