### ISSUE TITLE
Where is pwsh.exe when installed from Microsoft Store

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/windowsserverdocs#6217]
When having PowerShell 7 installed from Microsoft store, where is pwsh.exe and which path (example) should be used to configure sshd_config ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Get started with OpenSSH](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by robinharwood** [comment]
Hi @hkusulja - Thanks for your feedback and dedication to our documentation. The article already explains where to find the OpenSSH configuration files in this respective section, [direct link](https://docs.microsoft.com/windows-server/administration/openssh/openssh_install_firstuse#openssh-configuration-files) and extract below. Please let me know if this doesn't resolve your issue.

_By launching ssh.exe with the -F parameter, specifying a path to a configuration file and an entry name from that file.
A user's configuration file at %userprofile%\.ssh\config.
The system-wide configuration file at %programdata%\ssh\ssh_config._

With regard to where pwsh.exe is, I believe this has already been answered in MicrosoftDocs/PowerShell-Docs#8516.

Thanks for providing feedback that helps improve our documentation. This issue has been resolved and we are closing the issue. #please-close
