### ISSUE TITLE
Which username to use when Azure AD joined?

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/windowsserverdocs#6218]
Hello, my Windows 10 / 11 is Azure AD Joined, and which username should be specified to login using ssh via username/password?
I have tried.
ssh -l azuread\myusername@domain.com is not working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Get started with OpenSSH](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by robinharwood** [comment]
Hi @hkusulja ,

Thanks for your dedication to our documentation. I have shared your feedback with the team and have confirmed that Authentication using an Azure AD account for authentication in OpenSSH is not currently supported. There is a [feature request in the Win32-OpenSSH repo](https://github.com/PowerShell/Win32-OpenSSH/issues/1787) already open for this functionality, where you can follow up.

As this does not require an update to the documentation, we are closing this pull request for now. #please-close

Thanks,
Robin

#please-close
