### ISSUE TITLE
Windows container 

### ISSUE THREAD

**Issue by badcowlee** [MicrosoftDocs/windowsserverdocs#622]
About the installation of "Windows Admin Centre", does it support to create the container image by using windows container ?

Actually, I tried but failed at the end . Please refer the the error log for the reference.

MSI (s) (78:90) [02:57:46:092]: Running as a service.
MSI (s) (78:90) [02:57:46:094]: Hello, I'm your 32bit Elevated Non-remapped custom action server.
ExecFirewallExceptions:  Installing firewall exception2 SmeInboundOpenException on port 443, protocol 6
ExecFirewallExceptions:  Error 0x800706d9: failed trying to find existing port rule
ExecFirewallExceptions:  Error 0x800706d9: failed to add/update port exception for name 'SmeInboundOpenException' on port 443, protocol 6

**Comment by StefanKert** [comment]
Ran into the same issue. I am curious if the container version of windows server core is actually supported? Would be really great to get up and running with this within a container :)

**Comment by jwwool** [comment]
Running in a container is not currently supported, but on the roadmap. You can add votes to [this request](https://windowsserver.uservoice.com/forums/295071/suggestions/32408029) to influence the priority.
