### ISSUE TITLE
How to extend a volume with unallocated space that is not immediately after the volume

### ISSUE THREAD

**Issue by Benmuiruri** [MicrosoftDocs/windowsserverdocs#6222]
[Is it possible to extend a volume to an allocated space that does not come immediately after the volume I want to extend? There are  other volumes in-between]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2beddb54-a9ed-b53e-c8e1-152069c2c5c4
* Version Independent ID: 8aa0fe83-1e7f-3636-2122-477afd35a657
* Content: [Extend a basic volume](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/extend-a-basic-volume)
* Content Source: [WindowsServerDocs/storage/disk-management/extend-a-basic-volume.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/extend-a-basic-volume.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @Benmuiruri,

Thanks again for contacting Microsoft. We value your feedback. 

Short answer to your question, no, this is not possible to perform with the built-in Disk Management utility in Windows. Looking at the documentation under "[To extend a volume by using Disk Management](https://learn.microsoft.com/en-us/windows-server/storage/disk-management/extend-a-basic-volume#to-extend-a-volume-by-using-disk-management)" part 2, bullet 2:

>There is unallocated space directly after (to the right) of the volume, as shown in the graphic above. **If there's another volume in-between the unallocated space and the volume you want to extend, you can either delete the in-between volume and all files on it (make sure to back up or move any important files first!) or use a non-Microsoft disk partitioning app that can move volumes without destroying data, or skip extending the volume and instead create a separate volume in the unallocated space.**

I have attempted this and confirmed it cannot be accomplished in Disk Management with any volumes to the _left_ or _in between_. Any attempts to do so doesn't provide the "Extend Volume" option. Checking our [Tech Support Forum](https://answers.microsoft.com/en-us/windows/forum/all/extend-volume-greyed-out/b028d127-f86c-48ee-961c-2e17ec376efd
) also states it is not possible.

![image](https://user-images.githubusercontent.com/103963494/191345844-f4d6177c-e755-4c4f-b47a-ea59d03656bf.png)

If data loss is a concern for your volume(s), it is recommended to either backup your data on that volume, delete it, then extend it.

> _or_

You can use a third-party disk management utility that does provide the functionality that Disk Management does not support at this time. Listed some below (we do not provide any support for non-Microsoft products and any risk of their use falls under the user):

- https://www.aomeitech.com/aomei-partition-assistant.html
- https://www.partitionwizard.com/
- https://www.diskgenius.com/
- More can be found using your favorite search engine

In the future, for technical assistance with our products, we recommend that if you engage with the product community or open a ticket with Microsoft Support. For more information, see [Contact Microsoft Support](https://support.microsoft.com/ContactUs).

Additional tech support forums:

- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
