### ISSUE TITLE
Wrong Image in ADFS oidc Docs

### ISSUE THREAD

**Issue by HendrikFW** [MicrosoftDocs/windowsserverdocs#623]
Hey, 
i just read the [docs ](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/enabling-openid-connect-with-ad-fs) about to how build an web application using Open ID Connect on ADFS and there is a wrong screenshot at "*11. On the Configure Web API screen, enter the following..*".   
This Image belongs to "*13. On the Configure Application Permissions screen*". The image for step 11 is missing.

**Comment by illfated** [comment]
Resolved in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/4ae84fe54041184ad3006ad369e785dd84d5e8cf ( PR #662 **Update enabling-openId-connect-with-ad-fs.md** ).

But the page has also changed a lot since that correction, so this ticket is definitely outdated.

**Comment by illfated** [comment]
#please-close
