### ISSUE TITLE
One or some Arguments aren't listed

### ISSUE THREAD

**Issue by Rand-Random** [MicrosoftDocs/windowsserverdocs#6231]
`multimon` argument is missing.
Finally found the argument here: 
https://support.steadfast.net/knowledgebase/article/View/107/3/using-multiple-monitors-with-windows-remote-desktop

and it works.

Maybe more arguments are missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eddd1822-7939-85d7-d010-25963b182434
* Version Independent ID: 8597bd89-e0f0-1f73-8c3c-7215bbf8c0e8
* Content: [mstsc](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mstsc)
* Content Source: [WindowsServerDocs/administration/windows-commands/mstsc.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/mstsc.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @Rand-Random,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding the remaining parameters for `mstsc` and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
