### ISSUE TITLE
Empty section

### ISSUE THREAD

**Issue by sergiomarotco** [MicrosoftDocs/windowsserverdocs#6232]
The section does not contain the video in question, it is proposed to delete the section:

https://docs.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-and-shielded-vms#video-introduction-to-shielded-virtual-machines

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @sergiomarotco,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made where the video is now available. Changes will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
