### ISSUE TITLE
Websocket compatibility when using a proxy service.

### ISSUE THREAD

**Issue by furyritchie** [MicrosoftDocs/windowsserverdocs#624]
Is there an ETA on the resolution for this? It makes it impossible to use RDP, PowerShell when 443 is directed at your IIS server and your organisation blocks non 80/443 traffic. I'm using a reverse proxy to point 443 towards 6516 and all other features work but these are ones that I was especially interested in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1c16ba9-2fc0-4c4e-8e98-71fa6149224c
* Version Independent ID: 95a061bd-a176-1ec3-259d-2a3925ca279e
* Content: [Windows Admin Center Known Issues](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/known-issues)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/use/known-issues.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/use/known-issues.md)
* Service: **unspecified**
* GitHub Login: @jwwool
* Microsoft Alias: **jeffrew**

**Comment by RamblingGeekUK** [comment]
This is my office desktop, fully up to date. :-(

**Comment by ClumsyNavigator** [comment]
Is there any update on the support of WebSockets for Windows Admin Center?
It is still a known issue that Events, Powershell and RDP don't work through the application proxy as it seems.

**Comment by IngridAtMicrosoft** [comment]
GitHub issues for this repo are for reporting problems with the documentation. Please contact support.

#please-close
