### ISSUE TITLE
Bot found on link "Download as PDF"

### ISSUE THREAD

**Issue by shoootyou** [MicrosoftDocs/windowsserverdocs#6241]
Hello,

The link on "Download as PDF" shows as not found. The link is wrong.

- Actual Link: https://github.com/MicrosoftDocs/windowsserverdocs/raw/master/WindowsServerDocs/manage/windows-admin-center/media/WindowsAdminCenter1910Poster.pdf
- Must be changed by: https://github.com/MicrosoftDocs/windowsserverdocs/raw/main/WindowsServerDocs/manage/windows-admin-center/media/WindowsAdminCenter1910Poster.pdf

Have a good day!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd448b3c-456e-bd11-efb5-278296801fc0
* Version Independent ID: f82f9906-69aa-fc5b-e479-84b42b6c716f
* Content: [Windows Admin Center Overview](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/overview)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/manage/windows-admin-center/overview.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @shoootyou,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change was made for the PDF link, and changes are live. We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
