### ISSUE TITLE
Please help update the key for Server 2022 Datacenter Azure Edition

### ISSUE THREAD

**Issue by i4leader** [MicrosoftDocs/windowsserverdocs#6243]
[Enter feedback here]
The KMS client product key for Server 2022 Datacenter WX4NM-KYWYW-QJJR4-XV3QB-6VM33 is not working on Azure Edition.
Please help update the key for Server 2022 Datacenter Azure Edition in this article. The key for Azure Edition should be NTBV8-9K7Q8-V27C6-M2BTV-KHMXV.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5148ebad-44a0-b14a-d65c-e51650ce4197
* Version Independent ID: ceb3e4c3-ccc3-b75a-ccb1-235ad1a22469
* C
![MicrosoftTeams-image](https://user-images.githubusercontent.com/11024002/151920682-0a3461da-5f6d-4706-838a-7bf291824afc.png)
ontent: [Key Management Services (KMS) client activation and product keys for Windows Server and Windows](https://docs.microsoft.com/en-us/windows-server/get-started/kms-client-activation-keys)
* Content Source: [WindowsServerDocs/get-started/kms-client-activation-keys.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/kms-client-activation-keys.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @dknappettmsft
* Microsoft Alias: **daknappe**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @i4leader, 

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding the Azure Edition and Key. Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
