### ISSUE TITLE
Windows 11 compatibility for makeprofile.ps1 script

### ISSUE THREAD

**Issue by Eds1989** [MicrosoftDocs/windowsserverdocs#6245]
Please add a note to advise that the powershell script to deploy the VPN profile fails by default on Windows 11.
This is during the part where it tries to remove existing instances of the profile.

I had to comment out the EXIT code on the try/catch block to allow the script to deploy the profile.
Searching online, it seems this is because of a bug in Windows 11 that remains to be fixed.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e14da1-102d-3ddf-e2a1-a20ce533b95a
* Version Independent ID: 374edc4c-f527-b7b7-c291-353928b97d8d
* Content: [Configure Windows 10 Client Always On VPN Connections](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by anaharris-ms** [comment]
From https://github.com/MicrosoftDocs/windowsserverdocs/issues/6823

Seems there is another issue reporting the same here:

In the MakeProfile.ps1 script, where it tries to enumerate and delete old VPNs via this:

$InstanceId = $deleteInstance.InstanceID

That doesn't work in Windows 11 - "A general error occurred that is not covered by a more specific error code"... which appears to be a WMI/CIM bug with the class.

It would seem sensible for MS to review and update the script to make it Windows 11 friendly?

**Comment by anaharris-ms** [comment]
#please-close Fixed in: https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/3398
