### ISSUE TITLE
Cross premises delegation

### ISSUE THREAD

**Issue by kellybos** [MicrosoftDocs/windowsserverdocs#625]
Hi, 

Cross premises delegation is now supported in a hybrid environment - 
https://technet.microsoft.com/en-us/library/58b46b2c-a6b2-424a-8fc2-0f1fe1ad8e18(v=exchg.150)#DelegatedMbxPerms
https://technet.microsoft.com/en-us/library/jj200581(v=exchg.150)#considerations

I have worked with several customers that have Alt ID configured and this functionality works as expected with Outlook for Windows.  It would be great if this section of this article could be updated to reference the hybrid delegation documentation instead of saying it is not supported.

Thanks,
Kelly

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02d8b61-29e8-c0a7-b3b2-79be7212a91c
* Version Independent ID: b4346d87-0727-c7fe-7896-7fd79098825c
* Content: [Configuring Alternate Login ID](https://docs.microsoft.com/en-ca/windows-server/identity/ad-fs/operations/configuring-alternate-login-id#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configuring-Alternate-Login-ID.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configuring-Alternate-Login-ID.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Resolved in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/60b7e505e0580ba8eeff6ee96c9172e8c42ed630 (direct file link https://github.com/MicrosoftDocs/windowsserverdocs/commit/60b7e505e0580ba8eeff6ee96c9172e8c42ed630#diff-2b4fbd9f50a26328bc643a32d342e886) by David Coulter.

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
