### ISSUE TITLE
Small typo error.

### ISSUE THREAD

**Issue by Raziel-SSJ** [MicrosoftDocs/windowsserverdocs#6259]
The set command assigns everything that follows the equal sign (=) to the value of the variable. Therefore, if you type set testVar=test^1, you'll get the following result, testVar=**test1**. _(and not "**test^1**")_

_There are also mismatches between uppercase and lowercase in all the examples that I find confusing but..._ ¯\_(ツ)_/¯

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beaee6aa-060a-58d2-a474-b47b3ac89f9e
* Version Independent ID: bae22319-b13a-63f8-6da4-6411fece9f91
* Content: [set](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/set_1#examples)
* Content Source: [WindowsServerDocs/administration/windows-commands/set_1.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/set_1.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey Raziel-SSJ,

Thanks again for contacting Microsoft. We value your feedback. 

The testVar issue was corrected in a previous document update. The examples section has been updated for more clarity and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
