### ISSUE TITLE
Samba 4 AD

### ISSUE THREAD

**Issue by lfdominguez** [MicrosoftDocs/windowsserverdocs#626]
This work with samba 4 AD???

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 9d5d4a9c-11eb-3b85-91dd-cdbb0625db5a
* Version Independent ID: 01dad638-f8fb-61ff-4952-e3b25007a234
* Content: [Windows Admin Center](https://docs.microsoft.com/es-es/windows-server/manage/windows-admin-center/understand/windows-admin-center)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/understand/windows-admin-center.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/understand/windows-admin-center.md)
* Service: **unspecified**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by jwwool** [comment]
AD management tools of any kind are not yet in Windows Admin Center.
