### ISSUE TITLE
Config entry AnnounceFlags does not document setting for 10 (0x0a) even though it is the default

### ISSUE THREAD

**Issue by gchancellor** [MicrosoftDocs/windowsserverdocs#6273]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d09b16e-4bbb-91fa-3d84-e7623ec4dc07
* Version Independent ID: b6eadad5-0167-34b6-ed3a-16fa7ee83c60
* Content: [Windows Time service tools and settings](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings)
* Content Source: [WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @v-tappelgate
* Microsoft Alias: **v-tappelgate**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @gchancellor,

Thanks again for contacting Microsoft. We value your feedback. A documentation change has been made under the ["Config entries"](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings#config) section and is live. 

We will be closing this as resolved. Thank you and have a most pleasant day. #please-close
