### ISSUE TITLE
Example error

### ISSUE THREAD

**Issue by Raziel-SSJ** [MicrosoftDocs/windowsserverdocs#6280]
In the third (last) example, the code suggested to be typed is actually the output of the supposedly typed command.

> To display the current system date, followed by a prompt to enter a new date, type:
> ```
> The current date is: Mon 04/02/2007
> Enter the new date: (mm-dd-yyyy)
> ```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf5bf65b-0725-ce75-22a3-1b902008187e
* Version Independent ID: fc6b8570-983c-b25d-a8fd-29685bc17153
* Content: [date](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/date)
* Content Source: [WindowsServerDocs/administration/windows-commands/date.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/date.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @Raziel-SSJ,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting this and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
