### ISSUE TITLE
URL does not open

### ISSUE THREAD

**Issue by AndrejsSo** [MicrosoftDocs/windowsserverdocs#6282]
Hello,

In this paragraph:
https://docs.microsoft.com/en-us/windows-server/identity/solution-guides/scenario--implement-retention-of-information-on-file-servers#BKMK_OVER

in sentence:
You can find planning information for configuring retention in [Plan for Retention of Information on File Servers](assetid:///edf13190-7077-455a-ac01-f534064a9e0c).

this URL does not work. Pressing on - [Plan for Retention of Information on File Servers](assetid:///edf13190-7077-455a-ac01-f534064a9e0c). - gives nothing. Please kindly check/fix URL.

Thanks! :)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1fa042f-0954-baa9-7344-d6d53db5c035
* Version Independent ID: 2abf0802-16c8-a10a-dc01-3d3bf8086367
* Content: [Scenario Implement Retention of Information on File Servers](https://docs.microsoft.com/en-us/windows-server/identity/solution-guides/scenario--implement-retention-of-information-on-file-servers)
* Content Source: [WindowsServerDocs/identity/solution-guides/Scenario--Implement-Retention-of-Information-on-File-Servers.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/solution-guides/Scenario--Implement-Retention-of-Information-on-File-Servers.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by robinharwood** [comment]
Thanks for your feedback. We have fixed the URL for this article, the change should be visible in the next few hours.

#please-close
