### ISSUE TITLE
Missing documentation for djoin

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/windowsserverdocs#6286]
Steps to reproduce:
1. Go to https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands .
2. Try to find a link to the djoin command
3. Observe that a link for the djoin command does not exist.

Expected behavior: A link for the djoin command exists.

Actual behavior: A link for the djoin command does not exist.

Recommend way to fix: Add documentation for the djoin command.

General description: Documentation for the djoin command does not exist and needs to be added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d382ca0-6538-5e1d-3e83-e31c9ab6a911
* Version Independent ID: 11eff296-6158-f89a-4941-8735529183e9
* Content: [Windows commands](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands)
* Content Source: [WindowsServerDocs/administration/windows-commands/windows-commands.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/windows-commands.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @rossmpersonal, 

Thanks again for contacting Microsoft. We value your feedback.

We are aware that some Windows Commands no longer appear in this list, such as **djoin** in favor of their PowerShell counterparts found in our [Active Directory PowerShell Modules](https://docs.microsoft.com/en-us/powershell/module/activedirectory/?view=windowsserver2022-ps) reference article. There may be about an additional 20+ Server commands that have PowerShell cmdlets. If still interested in the Windows Command version for **djoin**, it can be found in our [command-line reference](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/hh831799(v=ws.11)) article

We are encouraging our users to adopt PowerShell in place of Windows Commands for these commands and potentially more in the future. We will be closing this as resolved. Thank you and have a most pleasant day.

#please-close
