### ISSUE TITLE
Fault Domain Video Doesn't Play

### ISSUE THREAD

**Issue by zps77** [MicrosoftDocs/windowsserverdocs#6287]
[Enter feedback here]

The video about the fault domain doesn't work.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a03180ce-ce5e-a242-534e-a6d2a71fddc3
* Version Independent ID: 009bf11f-5419-1da4-36eb-89f16bf82ca2
* Content: [Fault domain awareness](https://docs.microsoft.com/en-us/windows-server/failover-clustering/fault-domains)
* Content Source: [WindowsServerDocs/failover-clustering/fault-domains.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/failover-clustering/fault-domains.md)
* Product: **windows-server**
* Technology: **failover-clustering**
* GitHub Login: @cosmosdarwin
* Microsoft Alias: **cosdar**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @zps77,

A documentation change has been made updating the links to these videos and will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day.
#please-close
