### ISSUE TITLE
Incorrect Information on the AuthorizedKeysFile for OpenSSH Server

### ISSUE THREAD

**Issue by fkoch-tgm** [MicrosoftDocs/windowsserverdocs#6293]
There are two issues with the documentation for [OpenSSH Server configuration for Windows Server and Windows](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/OpenSSH/OpenSSH_Server_Configuration.md) that I noticed while setting up a SSH server:

First, the documentation states:
> The default is ".ssh/authorized_keys .ssh/authorized_keys2". 

My installation (via `Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0`) came with the Option `AuthorizedKeysFile	.ssh/authorized_keys` set by default.

Secondly, it would be helpful to tell readers that the permissions on the file have to be set manually: [StackOverflow-Answer by n0rd](https://stackoverflow.com/a/50502015)

Without setting the permissions only to SYSTEM and my user, the SSH server wouldn't recognize the file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8ad5c9a-efb1-d994-0e3c-53c90096a245
* Version Independent ID: 5cb0ea97-4c3d-ffdf-b69c-8a717f9f9f3f
* Content: [OpenSSH Server configuration for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_server_configuration)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Server_Configuration.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/OpenSSH/OpenSSH_Server_Configuration.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by robinharwood** [comment]
Hi @fkoch-tgm

Thanks for your dedication to our documentation. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow.

Thanks

#please-close
