### ISSUE TITLE
Typo: Formatting code displayed as text

### ISSUE THREAD

**Issue by 1Dimitri** [MicrosoftDocs/windowsserverdocs#6296]
Technical formatting code displayed 
`Table SEQ Table \* ARABIC 17: Backup and Restore Windows PowerShell Cmdlets`
before the Backup-CARoleService header

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a200a93-59b1-9db1-ed61-8441dd7bb8f1
* Version Independent ID: f3edf34c-5a58-6c4d-e037-51384f7bf7fb
* Content: [CA Backup and Restore Windows PowerShell cmdlets](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/component-updates/ca-backup-and-restore-windows-powershell-cmdlets)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/component-updates/CA-Backup-and-Restore-Windows-PowerShell-cmdlets.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-ds/manage/component-updates/CA-Backup-and-Restore-Windows-PowerShell-cmdlets.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We've submitted a documentation change based on your suggestion. Changes will be live after the next business day. This issue has been resolved. #please-close
