### ISSUE TITLE
Specifying Subject Alternative Names and Extensions

### ISSUE THREAD

**Issue by MatBerg2** [MicrosoftDocs/windowsserverdocs#6297]
The document does not explain how to specify Subject Alternative Names. "SubjectAltName" is mentioned once in a note, but no syntax information is provided.

Also, specifying extensions as is shown in the example does not work. certreq says:

"Certificate Request Processor: The parameter is incorrect. 0x80070057 (WIN32: 87 ERROR_INVALID_PARAMETER)
/path/to/.inf
[Extensions] OID ="

Maybe the information is outdated, or unclear so I do not get how to do it. Even if I use the exmple inf exactly as specified (replacing the "<FQDN of computer you are creating the certificate>", our course) I get this error.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 912a2faa-63c4-43c7-056b-16f5a5c71038
* Version Independent ID: cbec348f-53ad-a5b7-5a6e-f1cc5540d212
* Content: [certreq](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/certreq_1)
* Content Source: [WindowsServerDocs/administration/windows-commands/certreq_1.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/certreq_1.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by craigcaseyMSFT** [comment]
Hello @MatBerg2,

Thanks for contacting Microsoft. We value your feedback.

Documentation changes have been made to clarify and acknowledge this issue. The doc changes will be live after the next business day.

Thank you again and have a most pleasant day.
#please-close
