### ISSUE TITLE
Question about internal users in the cross-region adfs deployment.

### ISSUE THREAD

**Issue by DufferFromParis** [MicrosoftDocs/windowsserverdocs#6298]
I understand the value of this architecture regarding external users that will use the traffic manager. My concern is about internal users. Internal users are supposed to be redirected to an adfs server when trying to access the sts right ? So how do you deal with dns resolution of the sts for internal users in such a deployment ? Are you supposed to use some kind of HLB on-prem? a DNS policy ? or do you consider that all users (external and internal) will go through the traffic manager ?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2427554b-3bca-1b79-c037-97bdce61e093
* Version Independent ID: 56f5a1ef-9c76-ca18-dbe4-d285bc36d967
* Content: [High availability cross-geographic AD FS deployment in Azure with Azure Traffic Manager](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/active-directory-adfs-in-azure-with-azure-traffic-manager)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/active-directory-adfs-in-azure-with-azure-traffic-manager.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/deployment/active-directory-adfs-in-azure-with-azure-traffic-manager.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @anandyadavMSFT
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Hello @DufferFromParis. GitHub issues are for letting us know that are there are problems with the documentation. For questions about your implementation, please contact support or post a question at [MS Q & A](https://learn.microsoft.com/en-us/answers/questions/).
