### ISSUE TITLE
Won't install on Server 2012 R2

### ISSUE THREAD

**Issue by mozzis** [MicrosoftDocs/windowsserverdocs#630]
Windows Server 2012 R2 all updates applied.
All steps on this page followed.
Running WindowsAdminCenter1804.msi results in message:
"This software is not supported on this operating system"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe84fb4b-3420-bc1e-6a1d-b64ecc56fc5e
* Version Independent ID: f089767e-4613-d595-a0ee-0dab012724a1
* Content: [Install Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/install#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/deploy/install.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/deploy/install.md)
* Service: **unspecified**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by dweeban** [comment]
+1 same exact setup & error message.

**Comment by mozzis** [comment]
I did not read the docs carefully enough. You can only install on Windows 10 or Server 2016. You can manage Server 2012 or 2012 R2 right enough. but most likely you will do that from a Windows 10 client if you don't have any newer server isntalled.
