### ISSUE TITLE
Error in powershell command

### ISSUE THREAD

**Issue by misterraj7** [MicrosoftDocs/windowsserverdocs#6300]
The following command is wrong.
Add-windowsfeature AD-Domain Services 

instead, it should have been like this :

Add-windowsfeature AD-Domain-Services

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1931a904-7043-c896-3e51-ca63cb4aced3
* Version Independent ID: 3df0ea5b-be28-abe5-e9f3-36e9a17fc1b5
* Content: [Install a New Windows Server 2012 Active Directory Forest (Level 200)](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/install-a-new-windows-server-2012-active-directory-forest--level-200-)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/Install-a-New-Windows-Server-2012-Active-Directory-Forest--Level-200-.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-ds/deploy/Install-a-New-Windows-Server-2012-Active-Directory-Forest--Level-200-.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by Xelu86** [comment]
#assign:xelu86
