### ISSUE TITLE
So is 2019 & 2022 supported for DA or not?

### ISSUE THREAD

**Issue by J-Fedor** [MicrosoftDocs/windowsserverdocs#6304]
The page says that it applies to Server 2022, 2019 & 2016.
But then further down, you're stating that DA is only supported on server 2016.  No mention of 2019 or 2022.
I know we have server 2019 deployed as DA server, the code is still there and works, etc.  So confused by the documentation vs reality, etc.
And what about Windows 11 for client access?  I know at least 1 of our machines is on Win 11 and using DA just fine.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa82e6ef-7f35-9672-2ca3-9006de31b2cf
* Version Independent ID: 1dca040b-d5ba-8449-627b-b3069bd9be0e
* Content: [DirectAccess](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/directaccess/directaccess)
* Content Source: [WindowsServerDocs/remote/remote-access/directaccess/DirectAccess.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-access/directaccess/DirectAccess.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by craigcaseyMSFT** [comment]
Hello @J-Fedor,

Thanks for contacting Microsoft. We value your feedback.

We have tested the problem as described in this issue and either couldn't replicate the stated result or have verified that no documentation change is required.

As a result, we’re closing this thread.

Thank you again and have a most pleasant day.
#please-close
