### ISSUE TITLE
Link to streamlined FRS to DFS-R instructions is broken

### ISSUE THREAD

**Issue by mnooseman** [MicrosoftDocs/windowsserverdocs#6305]
The link in the document goes to a TechNet blog that no longer exists

https://blogs.technet.com/b/filecab/archive/2014/06/25/streamlined-migration-of-frs-to-dfsr-sysvol.aspx

should be replaced with

https://techcommunity.microsoft.com/t5/storage-at-microsoft/streamlined-migration-of-frs-to-dfsr-sysvol/ba-p/425405

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 418dc0a0-0312-9d6f-b2dc-2eb4841285ba
* Version Independent ID: 600b0469-3c96-5737-c39b-2ce9021b0f5a
* Content: [Active Directory Domain Services Functional Levels in Windows Server](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/active-directory-functional-levels)
* Content Source: [WindowsServerDocs/identity/ad-ds/active-directory-functional-levels.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-ds/active-directory-functional-levels.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @dknappettmsft
* Microsoft Alias: **daveba**

**Comment by Xelu86** [comment]
Hey mnooseman,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made in updating the blog link post and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
