### ISSUE TITLE
OpenSSH PS script does not work on PS 7.2.1

### ISSUE THREAD

**Issue by jgwinner** [MicrosoftDocs/windowsserverdocs#6306]
The step in the article to install OpenSSH does not work on Windows 10 or Windows 11.

I don't use PowerShell much, as I use TCC's replacement shell, so maybe there's some component that it needs, that isn't installed and not checked for.

```
PS C:\Windows\System32> Get-WindowsCapability -Online | Where-Object Name -like 'OpenSSH*'
Get-WindowsCapability: Class not registered
```

My current Win10 particulars:

```
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
If I run an older powershell, it does work, however.

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\WINDOWS\system32> Get-WindowsCapability -Online | Where-Object Name -like 'OpenSSH*'


Name  : OpenSSH.Client~~~~0.0.1.0
State : Installed

Name  : OpenSSH.Server~~~~0.0.1.0
State : NotPresent



PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Get started with OpenSSH](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by jgwinner** [comment]
This is why MS is going down :( the basics don't work and no one pays attention because "Triage".

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. I went through the documentation outlined and was unable to reproduce the error "Get-WindowsCapability: Class not registered". This was tested on Windows 10 Pro 21H1 & Windows 11 22H2 in a VM and non-VM environment.

PowerShell 5.1
![image](https://user-images.githubusercontent.com/103963494/176062223-41c9e300-adcd-4439-bb64-fc6d42e02561.png)

PowerShell 7.2
![image](https://user-images.githubusercontent.com/103963494/176062342-b461dd91-6ee7-4032-99cd-b9df80685734.png)

The [Get-WindowsCapability](https://docs.microsoft.com/en-us/powershell/module/dism/get-windowscapability?view=windowsserver2022-ps) command belongs to the [DISM](https://docs.microsoft.com/en-us/powershell/module/dism/?view=windowsserver2022-ps) module. A list of associated DISM commands can be found by running: Import-module DISM -Verbose

The error encountered, "Class not registered", can be a software or hardware issue where the hard drive may potentially be unhealthy, or the OS is missing specific dll files or even corrupted. Generally, the following can be ran in the Windows Command Prompt to check for OS corruption:

1] DISM /Online /Cleanup-Image /ScanHealth (wait for this to complete).
2] DISM /Online /Cleanup-Image /RestoreHealth (once complete, reboot).
3] Once back in the command prompt, run: sfc /scannow.

There are several potential fixes to this issue depending on what is causing it. If you Google or Bing "Get-WindowsCapability: Class not registered error" you will find different remedies to this issue.

Thank you.

**Comment by Xelu86** [comment]
#please-close

**Comment by jgwinner** [comment]
THIS IS NOT A HARD DRIVE PROBLEM.

This is a "different versions of Windows have different base DLL's". It's well documented that this error occurs.

MS can't even fix their own O/S
