### ISSUE TITLE
Update title in table of contents / index

### ISSUE THREAD

**Issue by Orin-Thomas** [MicrosoftDocs/windowsserverdocs#6308]
The article title is correctly "Upgrade domain controllers to a newer version of Windows Server" and applies to 2016, 2019 and 2022, the title in the table of contents/index is Upgrade Domain Controllers to Windows Server 2016. Not sure how to fix this myself so submitting an issue - though now that Ingrid is no longer working on this stuff, I'm happy to talk to anyone about how I can help out as I somewhat live in the Windows Server docs.

https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/upgrade-domain-controllers
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 666fb8cb-b1e5-c7b6-6326-cd172a2bf4b2
* Version Independent ID: 3d899ddb-c33f-28e6-3154-af039e28521a
* Content: [Upgrade domain controllers to a newer version of Windows Server](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/upgrade-domain-controllers?WT.mc_id=modinfra-0000-orthomas)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/upgrade-domain-controllers.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-ds/deploy/upgrade-domain-controllers.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @PatAltimore
* Microsoft Alias: **daveba**

**Comment by IngridAtMicrosoft** [comment]
Hello Orin! Thanks for the head up. I will take care of this. Easy fix.
