### ISSUE TITLE
Add the remaining SQLCMD commands

### ISSUE THREAD

**Issue by aydeisen** [MicrosoftDocs/windowsserverdocs#631]
Can this document be augment to include the SQLCMD commands used to attach SUSDB and validate the permissions for the NT AUTHORITY\NETWORK SERVICE account?

Additionally, can the SQLCMD commands be separated into their own section, the same way newer documentation is being written?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e2a5a31-29b9-5599-2f14-bc244c5da034
* Version Independent ID: 393db29c-0866-46f4-9ee6-7ae82e8cb29f
* Content: [Migrating the WSUS Database from (Windows Internal Database) WID to SQL](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/manage/wid-to-sql-migration)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/manage/wid-to-sql-migration.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/manage/wid-to-sql-migration.md)
* Service: **unspecified**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Page edit History:
- https://github.com/MicrosoftDocs/windowsserverdocs/commits/master/WindowsServerDocs/administration/windows-server-update-services/manage/wid-to-sql-migration.md

Seems to be resolved. If not resolved, please open a new ticket, mentioning exactly which changes are needed.

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
