### ISSUE TITLE
Installation of DFS tools does not work on client PC

### ISSUE THREAD

**Issue by Tarjei-stavanger** [MicrosoftDocs/windowsserverdocs#6317]
See error message below.
I have also tried to find the name of the installation kit with the following command :
   Get-WindowsCapability -Name 'RSAT*' -Online |    Sort-Object State, Name |   Format-Table Name, State, DisplayName -AutoSize

It didn't work either.

![image](https://user-images.githubusercontent.com/82510602/156536860-602e92c0-4d06-4dff-a0d8-4644d4efe6ff.png)

So, it appears that you need to document a way of installing the software on a client PC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea517059-9b5a-bc03-b1f6-f4b8f8871090
* Version Independent ID: d6c91daf-152c-ab4e-c446-ec2fee710184
* Content: [DFS Namespaces overview](https://docs.microsoft.com/en-us/windows-server/storage/dfs-namespaces/dfs-overview)
* Content Source: [WindowsServerDocs/storage/dfs-namespaces/dfs-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/dfs-namespaces/dfs-overview.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @Tarjei-stavanger,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding the PS cmdlet to install DFS on a client device:

```
Add-WindowsCapability -Name Rsat.FileServices.Tools~~~~0.0.1.0 -Online
```

Changes will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. #please-close
