### ISSUE TITLE
https://zaochnik1.com/client_v2/order-new

### ISSUE THREAD

**Issue by Goodliv** [MicrosoftDocs/windowsserverdocs#6318]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 073ab477-ac4c-9951-9d50-9d979176cff1
* Version Independent ID: 384cd6f7-2249-3f33-9b9e-1c6abeae69cb
* Content: [AD FS Troubleshooting - Auditing Events and Logging](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-logging)
* Content Source: [WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-logging.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-logging.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Closing GitHub issue as user feedback is unspecified. #please-close.
