### ISSUE TITLE
Videos don't work

### ISSUE THREAD

**Issue by jaymichaud** [MicrosoftDocs/windowsserverdocs#6321]
There are several video clips allegedly embedded into this page, but none of them play. They seem to just be images and not actually embedded videos or links.
Browser: Edge 98.0.1108.56

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a03180ce-ce5e-a242-534e-a6d2a71fddc3
* Version Independent ID: 009bf11f-5419-1da4-36eb-89f16bf82ca2
* Content: [Fault domain awareness](https://docs.microsoft.com/en-us/windows-server/failover-clustering/fault-domains)
* Content Source: [WindowsServerDocs/failover-clustering/fault-domains.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/failover-clustering/fault-domains.md)
* Product: **windows-server**
* Technology: **failover-clustering**
* GitHub Login: @cosmosdarwin
* Microsoft Alias: **cosdar**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @jaymichaud,

A documentation change has been made updating the links to these videos and will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day.
#please-close
