### ISSUE TITLE
typo in title "More inforamtion"

### ISSUE THREAD

**Issue by brunogonzalez** [MicrosoftDocs/windowsserverdocs#6324]
Typo in title:
https://docs.microsoft.com/en-us/windows-server/troubleshoot/understanding-the-lack-of-distributed-file-locking-in-dfsr#more-inforamtion

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c321e85a-93bd-31d4-97ea-21596f73da6b
* Version Independent ID: 75009676-6682-6746-2da2-eb97455e0b3b
* Content: [Understanding (the Lack of) Distributed File Locking in DFSR](https://docs.microsoft.com/en-us/windows-server/troubleshoot/understanding-the-lack-of-distributed-file-locking-in-dfsr)
* Content Source: [WindowsServerDocs/troubleshoot/understanding-the-lack-of-distributed-file-locking-in-dfsr.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/troubleshoot/understanding-the-lack-of-distributed-file-locking-in-dfsr.md)
* Product: **windows-server**
* Technology: **troubleshoot**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We've submitted a documentation change based on your suggestion. This issue has been resolved and we are closing the issue. #please-close #assign:xelu86
