### ISSUE TITLE
Re-phrase VHDX recommendations

### ISSUE THREAD

**Issue by mattboothman** [MicrosoftDocs/windowsserverdocs#6331]
> - We don't support or recommend that you create a VHDX file that is bootable to both generation 1 and generation 2 virtual machines.

Sounds like bootable VHDX files are not supported in either generation, or that bootable VHDX is not supported at all.

Maybe something like:

> - Creation of VHDX files that are bootable on both generation 1 and generation 2 virtual machines is not supported or recommended. Only create bootable VHDX files that target generation 1 _or_ generation 2 virtual machines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90b81010-acd8-231f-852b-7a9edfa4bd50
* Version Independent ID: 871c5a14-9f83-71b6-67b8-8ca33eb91651
* Content: [Should I create a generation 1 or 2 virtual machine in Hyper-V?](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/plan/should-i-create-a-generation-1-or-2-virtual-machine-in-hyper-v)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/plan/Should-I-create-a-generation-1-or-2-virtual-machine-in-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/virtualization/hyper-v/plan/Should-I-create-a-generation-1-or-2-virtual-machine-in-Hyper-V.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by Xelu86** [comment]
Hey mattboothman,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made clarifying the wording for Gen 1 & Gen 2 VHDKs and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
