### ISSUE TITLE
Command mentioned should be specified correctly with : or under "" 

### ISSUE THREAD

**Issue by saahilverma** [MicrosoftDocs/windowsserverdocs#6336]
[Enter feedback here]

auditpol.exe /set /subcategory:"Application Generated" /failure:enable /success:enable
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 073ab477-ac4c-9951-9d50-9d979176cff1
* Version Independent ID: 384cd6f7-2249-3f33-9b9e-1c6abeae69cb
* Content: [AD FS Troubleshooting - Auditing Events and Logging](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-logging)
* Content Source: [WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-logging.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-logging.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. Reviewed the documentation and verified that the command syntax is correct and was updated. #please-close
