### ISSUE TITLE
Hyperlink broken

### ISSUE THREAD

**Issue by ranjnagemini** [MicrosoftDocs/windowsserverdocs#6338]
In this article, the below Hyperlink is broken.
For more information, see [Add-DnsServerQueryResolutionPolicy]
(https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/powershell/module/dnsserver/add-dnsserverqueryresolutionpolicy).
Can some one update as it gives the 404 error.
![image](https://user-images.githubusercontent.com/68504325/157652662-d5881cde-e564-4526-9b81-da5f5f4081b1.png)

**Comment by Xelu86** [comment]
Hey ranjnagemini,

We would like to express our gratitude for your commitment to our documentation. We regret to inform you that we have fallen short of our usual standards in addressing documentation concerns in a timely manner, and we offer our apologies for any inconvenience this may have caused. 

Unfortunately, we regret to inform you that we’re closing this request, but we encourage you to open a new GitHub issue if you still believe it’s a valid documentation concern. If the forementioned documentation issue has already been addressed, this thread will also be closed. We welcome and take into consideration additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thank you for your understanding and continued support.

#please-close
