### ISSUE TITLE
missing key info

### ISSUE THREAD

**Issue by ketchup201** [MicrosoftDocs/windowsserverdocs#6348]
fails to describe limits of ntfs, such as max files per folder
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ede5970f-3974-f410-2d00-d99ae6177e9e
* Version Independent ID: 835f76fc-f470-d52e-50e8-880f7986a65c
* Content: [NTFS overview](https://docs.microsoft.com/en-us/windows-server/storage/file-server/ntfs-overview)
* Content Source: [WindowsServerDocs/storage/file-server/ntfs-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/file-server/ntfs-overview.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @ketchup201,

Thanks again for contacting Microsoft. We value your feedback. 

The information in question can be found in our [Working with File Systems](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-xp/bb457112(v=technet.10)?redirectedfrom=MSDN) documentation, more specifically under the "[Maximum Sizes on NTFS Volumes](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-xp/bb457112(v=technet.10)?redirectedfrom=MSDN#maximum-sizes-on-ntfs-volumes)" section with the maximum being `4,294,967,295`.

We will now be closing this thread. Thank you and have a most pleasant day. #please-close

**Comment by ketchup201** [comment]
An NTFS overview should contain basic information about NTFS, and I think it's reasonable to assume that an overview will have a table showing maximum characters in a filename, maximum number of files in a directory, maximum number of folders and/or files at the root, etc.. 

Thank you for the link, however, as it's valuable information.
