### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by HairInId** [MicrosoftDocs/windowsserverdocs#6359]
Typo in this sentence "This command uses the current default server to look up the information about the specified DSN domain." It should be DNS, not DSN.
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/nslookup-server

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8646f52-b3af-dbc4-2a56-5024a34073c2
* Version Independent ID: f1bdbf55-8801-1bd3-3a7a-d5d94c548429
* Content: [nslookup server](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/nslookup-server)
* Content Source: [WindowsServerDocs/administration/windows-commands/nslookup-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/nslookup-server.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by robinharwood** [comment]
#assign:robinharwood

Thanks for providing feedback that helps improve our documentation. This issue has been resolved and we are closing the issue. #please-close

Fixed by #6381
