### ISSUE TITLE
Windows Admin Center

### ISSUE THREAD

**Issue by jack19095** [MicrosoftDocs/windowsserverdocs#636]
Windows Admin Center

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5d4a9c-11eb-3b85-91dd-cdbb0625db5a
* Version Independent ID: 01dad638-f8fb-61ff-4952-e3b25007a234
* Content: [Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/understand/windows-admin-center)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/understand/windows-admin-center.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/understand/windows-admin-center.md)
* Service: **unspecified**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by lizap** [comment]
Hi, did you have feedback on this topic, or a question about Windows Admin Center? If so, please reopen this issue with more information. Thanks!
