### ISSUE TITLE
WIA supported user agents

### ISSUE THREAD

**Issue by MichaelHall001** [MicrosoftDocs/windowsserverdocs#6365]
I'm on the ADFS team at Microsoft.  I get these calls all the time.  In my opinion, we should have something in this article about adding Chrome to the WIA supported user agents list in ADFS.  That would of saved me 2 hours today.  It was working in IE the whole time.  The customer kept testing with Chrome. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cae6d9d8-4a22-f41e-a43f-b88816ae4519
* Version Independent ID: aad0e220-49d9-b9bc-10b7-ea0155af1d96
* Content: [AD FS Troubleshooting - Integrated Windows Authentication](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-iwa)
* Content Source: [WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-iwa.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-iwa.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Hi @MichaelHall001,
Please send an internal email to the Windows Server Content Team and reference this GH issue. 
Thanks,
Ingrid
