### ISSUE TITLE
Upgrade path from Honolulu?

### ISSUE THREAD

**Issue by jefmes** [MicrosoftDocs/windowsserverdocs#637]
I'm going to assume you guys want us to do fresh installs of Admin Center, but in case there is an upgrade path...should it be added here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe84fb4b-3420-bc1e-6a1d-b64ecc56fc5e
* Version Independent ID: f089767e-4613-d595-a0ee-0dab012724a1
* Content: [Install Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/install#install-on-server-core)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/deploy/install.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/deploy/install.md)
* Service: **unspecified**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by jwwool** [comment]
This is great feedback, thanks! Upgrade is supported. We will update the docs.
