### ISSUE TITLE
No longer supports Windows Server 2012 R2

### ISSUE THREAD

**Issue by andrewwillett** [MicrosoftDocs/windowsserverdocs#6378]
The fix for "Added support for CNG based certificates" (1.0.82.3) has either broken or dropped support for legacy Crypto API-based certificates. When restoring a backup from Windows Server 2012 R2, this exception is raised from a call to Microsoft.ADFSRapidRecreationTool.Crypto.X509KeyManagement.AddAclCngKey

System.Security.Cryptography.CryptographicException: Key not valid for use in specified state

This is only form that Windows Server 2012 R2-based farms support, therefore support for this version should be dropped from the documentation unless or until the Crypto API handling is resolved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f625ecc8-248e-e357-425b-dbd8234eb43f
* Version Independent ID: 383a61c4-2e82-4958-98b4-a0e8c124badb
* Content: [AD FS Rapid Restore Tool](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/ad-fs-rapid-restore-tool#how-to-use-the-tool)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/AD-FS-Rapid-Restore-Tool.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/operations/AD-FS-Rapid-Restore-Tool.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
Issue addressed by PR https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/3827
