### ISSUE TITLE
install LIS 4.2 response "Unsupported kernel version"

### ISSUE THREAD

**Issue by zwq000** [MicrosoftDocs/windowsserverdocs#638]
CentOs version CentOS Linux release 7.4.1708 (Core)
kernal version 3.10.0-693.21.1.el7.x86_64
but install lis v4.2  response "Unsupported kernel version"

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7575f3e6-af25-1cfd-8784-96c72bd94516
* Version Independent ID: 59ea80f9-dbce-1404-ab36-a301175a8c85
* Content: [Supported CentOS and Red Hat Enterprise Linux virtual machines on Hyper-V](https://docs.microsoft.com/zh-cn/windows-server/virtualization/hyper-v/supported-centos-and-red-hat-enterprise-linux-virtual-machines-on-hyper-v)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Supported-CentOS-and-Red-Hat-Enterprise-Linux-virtual-machines-on-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/Supported-CentOS-and-Red-Hat-Enterprise-Linux-virtual-machines-on-Hyper-V.md)
* Service: **na**
* GitHub Login: @DaniHalfin
* Microsoft Alias: **daniha**

**Comment by pseud0nym5** [comment]
Current version: 4.2.4-1 adds support for latest 7.4 kernels and installs for me on 3.10.0-693.21.1.el7.x86_64

**Comment by etfong** [comment]
I have the same issue with LIS 4.2.7 

Centos version CentOS Linux release 7.6.1810
kernel version 3.10.0-957.1.3.el7.x86_64
but install lis v4.2 response "Unsupported kernel version"

**Comment by pseud0nym5** [comment]
That's expected as /latestsupportedkernel in the 4.2.7 ISO contains

RHEL5:2.6.18-419.x86_64
RHEL6:2.6.32-754.3.5.el6.x86_64
RHEL7:3.10.0-862.11.6.el7.x86_64

I suspect 4.2.7 was already in the QA pipeline when 3.10.0-957.1.3.el7.x86_64 was released (26 Nov 2018). No doubt support will be coming soon in 4.2.7-1.

**Comment by lionzhou1981** [comment]
Is any news for CentOS 3.10.0-957.el7.x86_64 ?

**Comment by illfated** [comment]
If you believe the version information is incorrect and should be changed, please report this on the /en-us/ version of the same page:
- https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-centos-and-red-hat-enterprise-linux-virtual-machines-on-hyper-v

That is the only way we are able to make corrections to the source for the localized pages.

The localized pages (/zh-cn/ in this case) are mainly intended for reporting translation errors made by the Machine Translation.

**Comment by illfated** [comment]
@konstruktoid : if you look at the /en-us/ version of the page (link above), do you notice any obvious Linux version issues?

**Comment by konstruktoid** [comment]
```
Because of potential conflicts between the built-in LIS support and the downloadable LIS support when you upgrade the kernel, disable automatic updates, uninstall the LIS downloadable packages, update the kernel, reboot, and then install the latest LIS release, and reboot again.
```

The pages just mentions CentOS releases so I assume the `LiS` build process just haven't kept up with the kernel versions.

**Comment by illfated** [comment]
> > Because of potential conflicts between the built-in LIS support and the downloadable LIS support when you upgrade the kernel, disable automatic updates, uninstall the LIS downloadable packages, update the kernel, reboot, and then install the latest LIS release, and reboot again.
> 
> The pages just mentions CentOS releases so I assume the `LiS` build process just haven't kept up with the kernel versions.

Thanks for the feedback, I needed a view from someone in the know. 😉

**Comment by illfated** [comment]
If this issue still exists and cannot be resolved by the following suggested procedure;
1. disabling automatic updates,
2. uninstalling the LIS downloadable packages,
3. updating the kernel,
4. rebooting,
5.  installing the latest LIS release,
6. rebooting again,

please open a new ticket from the /en-us/ page (https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-centos-and-red-hat-enterprise-linux-virtual-machines-on-hyper-v) to report any potential issue with the information in this page and hopefully suggest / propose specific improvements to the page.

**Comment by illfated** [comment]
#please-close

**Comment by MironAtHome** [comment]
CentOS-8.4.2105-x86_64-dvd1.iso
Install ok.
LinuxIC-4.3.5.x86_64.iso failing to install with error "unsupported kernel version"
