### ISSUE TITLE
Cmd

### ISSUE THREAD

**Issue by Alexdraa** [MicrosoftDocs/windowsserverdocs#6386]
[Enter feedback here]

**
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0df94452-999b-43a0-be42-722fbabedaf3
* Version Independent ID: 84206d79-507f-b562-9d3f-cc3683b7abe6
* Content: [cmd](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cmd)
* Content Source: [WindowsServerDocs/administration/windows-commands/cmd.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/cmd.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Closing public GitHub issue as user feedback is unspecified. #please-close
