### ISSUE TITLE
Mismatch between written and picture for SMB detect-enable-and-disable-smbv1-v2-v3 

### ISSUE THREAD

**Issue by umeshnegi85** [MicrosoftDocs/windowsserverdocs#6389]
[SMB related URL 

https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3 

In the above URL, Section 'Disable SMBv1 by using Group Policy'

Disable SMBv1 server - Its mention Action is "Update" where as in the example picture it is "create". 

Could you please create this ?
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a91db45-ca3c-7a2e-3f32-2f5b57837b03
* Version Independent ID: b83cbaab-c0df-d6e7-a67f-f4c99a46e30a
* Content: [How to detect, enable and disable SMBv1, SMBv2, and SMBv3 in Windows](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @umeshnegi85,

Thanks again for contacting Microsoft. We value your feedback. 

We've updated the documentation so that the screenshot in question reflects the wording. Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
