### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by danieljloughlin** [MicrosoftDocs/windowsserverdocs#639]
The Windows Admin Center web UI doesn't appear to work over IPv6.  (netsh http show ssl, and netstat show no bindings to IPv6 addresses, only IPv4).  This appears to be the case on Windows 10 and Windows Server 2016

You can manage IPv6 only servers with it though, if you can connect to the web interface over IPv4.

Is IPv6 support planned?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe84fb4b-3420-bc1e-6a1d-b64ecc56fc5e
* Version Independent ID: f089767e-4613-d595-a0ee-0dab012724a1
* Content: [Install Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/install)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/deploy/install.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/deploy/install.md)
* Service: **unspecified**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by jwwool** [comment]
Binding the web UI to IPv6 is not currently on the roadmap. If you'd like, please [create a suggestion](http://aka.ms/wacfeedback) for this to be tracked!
