### ISSUE TITLE
64 Bit download link is not correct?

### ISSUE THREAD

**Issue by boymen35** [MicrosoftDocs/windowsserverdocs#6390]
It looks like the download link for the 64 bit version is not correct. When you press the link, it downloads the file, but without the .msi extension. The 32bit and 64arm version are working well. When you put .msi behind the 64 version, it works normal again, but that's not really handy :).

Tested it on 2 devices, and got the same result on both devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ab98fc-fea2-a11a-e5ca-de1430211d97
* Version Independent ID: 4d9943c3-fef7-ca86-bd03-1241a04b8135
* Content: [Get started with the Windows Desktop client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop#install-the-client)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by rtebrake** [comment]
I opened a Premier support case to get this fixed, it's working now (but might require clearing the cache of the browser)

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We have verified that the download links for the 32-bit, 64-bit, and ARM64 client installer have been corrected. #please-close
