### ISSUE TITLE
Error in documentation?

### ISSUE THREAD

**Issue by mattguelde** [MicrosoftDocs/windowsserverdocs#6395]
The example in the documentation for running a repair on an msi package can be done using the command msiexec.exe /fa {product code}, but I've found that it only works if the product code is enclosed in quotation marks: msiexec.exe /fa "{product code}"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a2e3005-0d38-154e-560e-0f25d4892810
* Version Independent ID: 11dcf68e-545e-8e9d-3df0-645a9ae9b6fc
* Content: [msiexec](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/msiexec)
* Content Source: [WindowsServerDocs/administration/windows-commands/msiexec.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/msiexec.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. Reviewing this documentation and your inquiry, no errors were found when running "msiexec.exe /fa {product code}".

Running the following command in PowerShell will display a list of msi installer applications on your current machine where IdentifyingNumber is your product_code:

get-wmiobject Win32_Product | Sort-Object Name | Format-Table Name, IdentifyingNumber -AutoSize

In the example below, the command in question works successfully with and without double quotes:

![image](https://user-images.githubusercontent.com/103963494/175427637-08a0b45c-0c50-4643-9958-ab9bbf327ac4.png)

Thank you.

**Comment by Xelu86** [comment]
#please-close
