### ISSUE TITLE
My experience with directions on this page

### ISSUE THREAD

**Issue by shane128** [MicrosoftDocs/windowsserverdocs#6398]
[Enter feedback here]

Hello,

     Just a couple of things I discovered while trying to implement sftp server on windows.  

1.  When I tired to install the latest version from Github, I could make putty connections, but not sftp nor scp.  The error was something to the effect that no protocol was recognized, is the server running.  Thinking that maybe the github version and the client installed from the Microsoft additional options are conflicting, I uninstalled the github version.
2.   Installing the github version installed it's version of ssh-agent for authentication.  (overwriting the Microsoft one).  Problem being, after I uninstalled, it removed this service which was there previously.  
3.   Installing the Microsoft version from windows optional features was problem some due to our enterprise using WSUS.  I had to create a policy to negate the enterprise settings thus, allowing me to install ssh-server via option features.  This did not re-create the ssh-agent service that was deleted from my github install.  I had to re-create the ssh authentication service manually.
4.   The syntax for adding user / group permissions to the sshd_config are vague.  I found (from linux forums) that the allow users supersedes the allow groups.  Its one or the other, not both.  The example on this page is confusing on this.  For my use, I just used the allowusers and that worked.  Also, there was no clear syntax on the use of allowed users.  There should be a space between users as "allowusers user1 user2@localhost user3@remotehost"
5.   There is no mention of how to lock down sshd to use just sftp.  In our case, we did not want users to have console access to our server.  So I found this command on other forums that allowed me to turn this functionality off.   "ForceCommand internal-sftp"

Thank you,
Shane Van Loenen
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8ad5c9a-efb1-d994-0e3c-53c90096a245
* Version Independent ID: 5cb0ea97-4c3d-ffdf-b69c-8a717f9f9f3f
* Content: [OpenSSH Server configuration for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_server_configuration)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Server_Configuration.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/OpenSSH/OpenSSH_Server_Configuration.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by robinharwood** [comment]
Hi @shane128 ,

Thanks for your dedication to our documentation. Firstly, just for clarity the GitHub verion of OpenSSH for Windows is a beta. Our recommendation is to the built-in version of OpenSSH, unless you are specifically testing the beta. Any issues or requests related to the beta should be raised as an issue in the [Win32-OpenSSH repo](https://github.com/PowerShell/Win32-OpenSSH/issues), where you can follow up there. To get assistance or support for the built-in version, we recommend that you engage with the product community or open a ticket with Microsoft Support. For more information, see [Contact Microsoft Support](https://support.microsoft.com/ContactUs).

With regard to the product document you mention in point 4. We've submitted a documentation change based on your suggestion, and the updated article went live last week.

With regard to point 5, this isn't so much a Windows specific setting an OpenSSH configuration setting. With that in mind please refer to the OpenSSH documentation managed by developers at the OpenBSD Project [OpenSSH open source project](https://www.openssh.com), which is strive not to duplicate. I was able to find a few community examples like this one [How to Allow SFTP and disallow SSH? - Techglimpse](https://techglimpse.com/allow-sftp-disallow-ssh-ubuntu), however we haven't tested this.

Thanks,
Robin

#please-close
