### ISSUE TITLE
Keyboard shortcut redirection

### ISSUE THREAD

**Issue by MichiZubi** [MicrosoftDocs/windowsserverdocs#640]
Is there a plan to allow keyboard shortcut redirection, for example Windows Key + R?
I tested the webclient with a published mstsc and it worked so far.

A second issue: When setting webclient to fullscreen mode there are scrollbars. If I just set the browser itself to fullscreen it works.

**Comment by illfated** [comment]
Troubleshooting issue, and related page is not referenced.

**Comment by illfated** [comment]
#please-close
