### ISSUE TITLE
RODC recommendation goes against autopilot hybrid azure ad

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/windowsserverdocs#6411]
I have made dozen of Windows Autopilot project ms involving hybrid azure ad join. One thing I learned is RODCs are a complete mess and break the process. Please mention it at least before telling organizations to install RODCs on Vms where it is no big deal to install a read/write dc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca929d6b-746d-f20a-8902-4e93a69ab8d8
* Version Independent ID: 88e13a93-f80b-d07b-cfaa-ab38205148e0
* Content: [Securing Domain Controllers Against Attack](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/securing-domain-controllers-against-attack#blocking-internet-access-for-domain-controllers)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Securing-Domain-Controllers-Against-Attack.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Securing-Domain-Controllers-Against-Attack.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
#please-close

**Comment by MicrosoftGuyJFlo** [comment]
This has been addressed in the content.
