### ISSUE TITLE
Download Link Returns 404

### ISSUE THREAD

**Issue by CorvusCallosum** [MicrosoftDocs/windowsserverdocs#6415]
[this](https://www.microsoft.com/download/details.aspx?id=34821) is dead.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. As the dead link in question isn't tied to specific documentation, we cannot provide an update. Please feel free to reopen this GitHub issue so we can further assist. #please-close
