### ISSUE TITLE
Switching identity providers

### ISSUE THREAD

**Issue by chrisrendall** [MicrosoftDocs/windowsserverdocs#642]
If I setup Windows Admin Center to use Active Directory, is it possible to switch to Azure Active Directory?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6273f49-fe06-5a18-80e3-863bd3a0cf4e
* Version Independent ID: 4ed5bf3d-0c2a-a80e-5bd9-0e858dd8749b
* Content: [Configuring user access control and permissions](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/configure/user-access-control)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/configure/user-access-control.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/configure/user-access-control.md)
* Service: **unspecified**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by jwwool** [comment]
Yes, Gateway administrators can [change the identity provider](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/configure/user-access-control#choose-the-identity-provider) at any time.

**Comment by jwwool** [comment]
@chrisrendall I hope this answers your question.

@TitianRob thanks for creating a new issue #679

**Comment by chrisrendall** [comment]
@jwwool Yes, Thanks!
