### ISSUE TITLE
Server OS description for Set-SMBServerConfiguration

### ISSUE THREAD

**Issue by sakura0518** [MicrosoftDocs/windowsserverdocs#6421]
As for following section, it should include "Windows server 2016". is there any reason that this section does not include 2016 though it include 2012, 2012R2 and 2019.
>How to detect status, enable, and disable SMB protocols on the SMB Server
>For Windows 8.1, Windows Server 2012, Windows Server 2012 R2, Windows 10, and Windows Server 2019
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a91db45-ca3c-7a2e-3f32-2f5b57837b03
* Version Independent ID: b83cbaab-c0df-d6e7-a67f-f4c99a46e30a
* Content: [How to detect, enable and disable SMBv1, SMBv2, and SMBv3 in Windows](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @sakura0518, 

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made to better clarify said content and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
