### ISSUE TITLE
Missing W in www

### ISSUE THREAD

**Issue by Karr** [MicrosoftDocs/windowsserverdocs#6422]
The first two lines of the script create client subnet objects for North America and Europe. The two lines after that create a zone scope within the contoso.com domain, one for each region. The two lines after that create a record in each zone that associates ww.contoso.com to different IP address, one for Europe, another one for North America. Finally, the last lines of the script create two DNS Query Resolution Policies, one to be applied to the North America subnet, another to the Europe subnet.

UNDER TRAFFIC MANAGMENT.  Please note that a "w" is missing from www.contoso.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b951d0a2-1d11-00dc-cfd3-64dd31bbf377
* Version Independent ID: ab56539c-e788-9209-2d35-057fcacd972b
* Content: [DNS Policies Overview](https://docs.microsoft.com/en-us/windows-server/networking/dns/deploy/dns-policies-overview)
* Content Source: [WindowsServerDocs/networking/dns/deploy/DNS-Policies-Overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/networking/dns/deploy/DNS-Policies-Overview.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We've submitted a documentation change based on your suggestion. Changes will be live after the next business day. #please-close
