### ISSUE TITLE
show only differences

### ISSUE THREAD

**Issue by yomoenco** [MicrosoftDocs/windowsserverdocs#6424]
[Enter feedback here]
ADD an option to show only differences as this is a Huge list and only 2 options differ
regards
Andre

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e477d8d-7469-cd57-29a9-13135b164311
* Version Independent ID: 73fb5866-3a3e-8cde-f39f-c2677de6d326
* Content: [Comparison of Standard and Datacenter editions Windows Server 2019](https://docs.microsoft.com/en-us/windows-server/get-started/editions-comparison-windows-server-2019)
* Content Source: [WindowsServerDocs/get-started/editions-comparison-windows-server-2019.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/editions-comparison-windows-server-2019.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey @yomoenco,

Thanks again for contacting Microsoft. We value your feedback. 

Looking at this documentation, it contains more than 2 differences for each section in their respective categories. A documentation change has been made for Server 2016, 2019, and 2022 to easily distinguish these differences and should be live. 

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
