### ISSUE TITLE
Link in Document points to no relevant content

### ISSUE THREAD

**Issue by Ekaitz22** [MicrosoftDocs/windowsserverdocs#6426]
Link in doc **Active Directory in Networks Segmented by Firewalls** points to a landing page that indicates that it will no longer be updated or article has not been written.  

Assume article was from TechNet or another Microsoft website that is no longer available.  It should then be removed or updated to proper content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 028cd4f3-4e39-9b7e-5dc8-33dbd8e7b3ca
* Version Independent ID: d6a1ec63-dc3c-ff96-5597-ed6ee0e4e73e
* Content: [Creating a Site Link Bridge Design](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/creating-a-site-link-bridge-design)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/Creating-a-Site-Link-Bridge-Design.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-ds/plan/Creating-a-Site-Link-Bridge-Design.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @Ekaitz22,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made removing the last sentence as the reference content pertains to _very_ old material. Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
