### ISSUE TITLE
Get-WMIObject is deprecated

### ISSUE THREAD

**Issue by tazmologist** [MicrosoftDocs/windowsserverdocs#6431]
Get-WMIObject is deprecated.  What is the get-cimclass equivalent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5b7b963-8942-b367-857e-c538e6e2aa8d
* Version Independent ID: 69a13db8-25a2-d389-420e-b61e9bb214b4
* Content: [Troubleshoot Always On VPN](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-troubleshooting)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-troubleshooting.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-troubleshooting.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **inhenkel**

**Comment by anaharris-ms** [comment]
Fixed in: https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/3398

#please-close
