### ISSUE TITLE
Little correctrion about product name

### ISSUE THREAD

**Issue by mmoioli** [MicrosoftDocs/windowsserverdocs#6432]
[Enter feedback here]
In the page I read the phrase "**Azure** Defender for Servers." but the correct name of the product is "Microsoft Defender for Servers" 
https://docs.microsoft.com/en-us/azure/defender-for-cloud/defender-for-servers-introduction#:~:text=Microsoft%20Defender%20for%20Servers%20is%20one%20of%20the,running%20in%20Azure%2C%20AWS%2C%20GCP%2C%20and%20on-premises%20environment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca929d6b-746d-f20a-8902-4e93a69ab8d8
* Version Independent ID: 88e13a93-f80b-d07b-cfaa-ab38205148e0
* Content: [Securing Domain Controllers Against Attack](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/securing-domain-controllers-against-attack#blocking-internet-access-for-domain-controllers)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Securing-Domain-Controllers-Against-Attack.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Securing-Domain-Controllers-Against-Attack.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by Xelu86** [comment]
#assign:xelu86
