### ISSUE TITLE
Update TLS certs ADFS alternative method

### ISSUE THREAD

**Issue by gbarceloPIB** [MicrosoftDocs/windowsserverdocs#6433]
Is there an alternative method in azure-docs? [](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-ssl-update)
If PowerShell and Azure AD Connect steps work for both TLS binding modes, Azure AD Connect should be mentioned?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8733a32-8eef-bdb8-673f-065e8a5f1e0f
* Version Independent ID: f111b377-0dce-d7a6-9483-8830533cacba
* Content: [Managing SSL Certificates in AD FS and WAP in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/manage-ssl-certificates-ad-fs-wap)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/manage-ssl-certificates-ad-fs-wap.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/operations/manage-ssl-certificates-ad-fs-wap.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @jenfieldmsft
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
This is not Azure AD documentation. For Azure AD documentation please see https://learn.microsoft.com/en-us/azure/active-directory/

#please-close
