### ISSUE TITLE
Bad instructions seemingly everywhere

### ISSUE THREAD

**Issue by RavenWing71** [MicrosoftDocs/windowsserverdocs#6435]
Under "**To allow a virtual machine to use a VLAN**"

Step 2: "In the results pane, under Virtual Machines, select the appropriate virtual machine and then right-click Settings."
- Hyper-V Manager does not have a results pane as it does not have any search.  I believe you mean the Virtual Machines pane.
- You can not right-click on settings, it does nothing.  Perhaps you mean, "in the right hand column click settings?"

Step 3: "Under Hardware, select an virtual switch that's set up with a VLAN."
- There are no virtual switches under hardware.  There are Network Adapters.
- The whole point of this exercise was to set up a VLAN for a VM Guest.
- This step is beyond help, completely rewrite it.

Get someone to follow your instructions before you post them.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96354f2e-e4eb-5efb-84e1-c1328e891ef6
* Version Independent ID: 2d8b614b-868a-4462-4815-213e7d84a5c5
* Content: [Configure virtual local area networks for Hyper-V](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/deploy/configure-virtual-local-areal-networks-for-hyper-v)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/deploy/configure-virtual-local-areal-networks-for-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/virtualization/hyper-v/deploy/configure-virtual-local-areal-networks-for-Hyper-V.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by v-thepet** [comment]
Hi @RavenWing71,

Thank you for contacting Microsoft. We appreciate your feedback.

A documentation change has been made to correct this procedure and will go live in the next business day. 

We'll now be closing this thread. Thank you again for your feedback, and have a most pleasant day.

#please-close
