### ISSUE TITLE
Not possible to add VPN server to AD group when not domain joined!

### ISSUE THREAD

**Issue by HomeJeroen** [MicrosoftDocs/windowsserverdocs#6436]
This page clearly states the following:

`Since the RRAS server is not domain joined, ...`

So the "Always On VPN" server is **not** joined to the Domain. Yet it expects the following: 

```
Configure the VPN Servers and NPS Servers groups

    On a domain controller, open Active Directory Users and Computers.

    Right-click a container or organizational unit, select New, then select Group.

    In Group name, enter VPN Servers, then select OK.

    Right-click VPN Servers and select Properties.

    On the Members tab of the VPN Servers Properties dialog box, select Add.

    select Object Types, select the Computers check box, then select OK.

    In Enter the object names to select, enter the names of your VPN servers, then select OK.

    Select OK to close the VPN Servers Properties dialog box.

    Repeat the previous steps for the NPS Servers group.

    Close Active Directory Users and Computers.

```

So how can we add VPN-servers the AD group, when they are not domain-joined?
Should the RRAS VPN server be domain joined or not? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76dd49bb-b86e-f5b7-35b9-a8d246d36fcb
* Version Independent ID: dedfa83f-36d6-f60b-e839-ba382c5a7372
* Content: [Configure the Server Infrastructure](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-server-infrastructure.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by anaharris-ms** [comment]
#please-close Fixed in: https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/3398
