### ISSUE TITLE
Little TYPO, within the page  ::  schtasks-create

### ISSUE THREAD

**Issue by forands** [MicrosoftDocs/windowsserverdocs#6437]
[Enter feedback here]
Within the section  /mo   there is a little error.
Where you can read "ONLOGON - Specifies that the task runs when the user specified by the /u parameter logs on."
       --> where we see  "/u" -->   should be  --> "/ru"

Best regards'
Stephane Forand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0feda591-bda7-75e4-3eee-f38ec06f6f17
* Version Independent ID: f9f5b2ca-d26f-dd8a-70d1-0c07b94a4dd6
* Content: [schtasks create](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/schtasks-create)
* Content Source: [WindowsServerDocs/administration/windows-commands/schtasks-create.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/schtasks-create.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @forands, 

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting `/u` > `/ru` and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
