### ISSUE TITLE
Link mis-configured

### ISSUE THREAD

**Issue by mwtrigg** [MicrosoftDocs/windowsserverdocs#644]
Two "See also" links are mis-configured. First, the link titled "Planning to Publish Applications Using Web Application Proxy" has a URL of format "assetid://<assetGUID>", I believe the correct URL should be "https://technet.microsoft.com/library/dn383650.aspx"  And second, "Web Application Proxy Walkthrough Guide" has an invalid URL of format"assetid://<assetGUID>".  I believe this URL should point to "https://technet.microsoft.com/library/dn280944.aspx"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6eab4e1f-d36f-3af5-a470-748544db10c6
* Version Independent ID: 507b5d01-0566-2459-a9c4-006ce7681a54
* Content: [Publishing Applications with SharePoint, Exchange and RDG](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/web-application-proxy/publishing-applications-with-sharepoint%2c-exchange-and-rdg)
* Content Source: [WindowsServerDocs/remote/remote-access/web-application-proxy/Publishing-Applications-with-SharePoint,-Exchange-and-RDG.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/web-application-proxy/Publishing-Applications-with-SharePoint,-Exchange-and-RDG.md)
* Service: **unspecified**
* GitHub Login: @kgremban

**Comment by MicrosoftGuyJFlo** [comment]
Resolving in private repo branch GitHubIssues072018

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
