### ISSUE TITLE
The option /RL is not described on this page about creation of a scheduled task with schtasks

### ISSUE THREAD

**Issue by A-Mofi** [MicrosoftDocs/windowsserverdocs#6442]
The usage help output on running `schtasks /create /?` in a Windows command prompt window lists also the option `/RL` as follows:

```
    /RL   level        Sets the Run Level for the job. Valid values are
                       LIMITED and HIGHEST. The default is LIMITED.
```

The option `/RL` with its description is missing on this documentation page.

The option `/RL` is described on the documentation page [Schtasks.exe](https://docs.microsoft.com/en-us/windows/win32/taskschd/schtasks) for creating a task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0feda591-bda7-75e4-3eee-f38ec06f6f17
* Version Independent ID: f9f5b2ca-d26f-dd8a-70d1-0c07b94a4dd6
* Content: [schtasks create](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/schtasks-create)
* Content Source: [WindowsServerDocs/administration/windows-commands/schtasks-create.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/schtasks-create.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. A documentation change has been made and will be live after the next business day. #please-close
