### ISSUE TITLE
The option /RL is not described on this page about change of a scheduled task with schtasks

### ISSUE THREAD

**Issue by A-Mofi** [MicrosoftDocs/windowsserverdocs#6443]
The usage help output on running `schtasks /change /?` in a Windows command prompt window lists also the option `/RL` as follows:

```
    /RL      level       Sets the Run Level for the job. Valid values are
                         LIMITED and HIGHEST. The default is to not change it.
```

The option `/RL` with its description is missing on this documentation page.

The option `/RL` is described on the documentation page [Schtasks.exe](https://docs.microsoft.com/en-us/windows/win32/taskschd/schtasks) for changing a task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28c3149e-b28d-0152-a86c-62be53ae361b
* Version Independent ID: 86c11506-0c13-6ce9-d27a-14b60e037f7a
* Content: [schtasks change](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/schtasks-change)
* Content Source: [WindowsServerDocs/administration/windows-commands/schtasks-change.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/schtasks-change.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. A documentation change has been made and will be live after the next business day. #please-close
