### ISSUE TITLE
Broken Link on Page

### ISSUE THREAD

**Issue by mlibenocg** [MicrosoftDocs/windowsserverdocs#6445]
The link, [Microsoft Knowledge Base article 902229](https://go.microsoft.com/fwlink/?LinkId=186066) returns a 404 error. Is should be corrected or removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4d52178-35e4-18fa-4e0d-3d983278664d
* Version Independent ID: b2ef1ce4-2d5f-f4c9-9cd2-577866c30a4d
* Content: [How the Windows Time Service Works](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/how-the-windows-time-service-works)
* Content Source: [WindowsServerDocs/networking/windows-time-service/How-the-Windows-Time-Service-Works.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/networking/windows-time-service/How-the-Windows-Time-Service-Works.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @dahavey
* Microsoft Alias: **dahavey**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. A correction to this documentation has been made. Changes will be live after the next business day. #please-close
