### ISSUE TITLE
netsh command when using interface that starts with #

### ISSUE THREAD

**Issue by L30N1D45-5P15L4** [MicrosoftDocs/windowsserverdocs#6447]
There is the following information about netsh command: 

_Throughout the Netsh command reference there are commands that contain parameters for which a string value is required.

In the case where a string value contains spaces between characters, such as string values that consist of more than one word, it is required that you enclose the string value in quotation marks. For example, for a parameter named interface with a string value of Wireless Network Connection, use quotation marks around the string value:

interface="Wireless Network Connection"_

I had an issue with this command because the name of the interface of my computer was #Private and the command didn't work. I was receiving ERRORLEVEL=1 and after lots of tries to figure out the escape character I found the asterisk "*".
  
I suggest adding a complement to use the escape character (maybe escape character is not the right term) "*" when the interface starts with #.

e.g. interface="*#Private"

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 018d29d0-d1e2-09bb-57a6-7cad7361f80a
* Version Independent ID: 58af419b-3d83-573f-bf54-07a5e37cb5a0
* Content: [Netsh Command Syntax, Contexts, and Formatting](https://docs.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh-contexts)
* Content Source: [WindowsServerDocs/networking/technologies/netsh/netsh-contexts.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/networking/technologies/netsh/netsh-contexts.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey L30N1D45-5P15L4,

Thanks again for contacting Microsoft. We value your feedback. 

Additional document updates have been along with string values for network interfaces where either the interface name or index# can be used for `netsh`. Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
