### ISSUE TITLE
Missing information for open ssh and certificates.

### ISSUE THREAD

**Issue by queglay** [MicrosoftDocs/windowsserverdocs#6449]
[Enter feedback here]
It would be helpful to see documentation for using SSH certificates.   I thought these were now best practice.  Is it available?

In open SSH on linux when configuring SSH certificates, there are two important paths needed to configure a known hosts CA (when sshing into another host, avoiding TOFU warnings), and trusted user CA keys (allowing other hosts with signed certs to ssh into the current machine).  

There isn't any documentaton on this page ( https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement ) discussing how to configure a CA for a domain or any mention of the windows equivalent paths for configuring a CA -
"/etc/ssh/trusted-user-ca-keys.pem"
"/etc/ssh/ssh_known_hosts"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [OpenSSH key management for Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by robinharwood** [comment]
Hi @queglay,

Thanks for your dedication to our documentation. We've submitted an item to our backlog based on your suggestion. I am not sure what the timeline will be, so I am going to close this for now. But once I have an update I will drop it in here and let you know. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

Thanks,
Robin

#please-close
