### ISSUE TITLE
Can not open the Page

### ISSUE THREAD

**Issue by mkruiss** [MicrosoftDocs/windowsserverdocs#645]
After my Admin Center Installation, on a Server 2016 with GUI and Server 1709 Core i get on both Server the same error wen i will open the Website "Page can not be displayed" Also wenn ich oben die Admin Center on the Server. What is the problem now? BR

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe84fb4b-3420-bc1e-6a1d-b64ecc56fc5e
* Version Independent ID: f089767e-4613-d595-a0ee-0dab012724a1
* Content: [Install Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/install)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/deploy/install.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/deploy/install.md)
* Service: **unspecified**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by jones85** [comment]
Hi, I'm having the issue too.  My setup is a single Windows Server 1709 install with a self-signed cert from my internal CA.  The installation completed successfully (install log here bit.ly/2qza4nV).  After the install, I can see the WAC service running but get no response when accessing the site.  I ran 'netstat -a' shows there is nothing listening on TCP:443 (specified during the install).

Any ideas?

**Comment by migo99** [comment]
Same issue here. Installing WAC on a Windows 10 client works like a charm. However, running it on a server 2016 (latest updates installed) does not work. Identical behavior as jones85.

**Comment by davista2** [comment]
Same issue here but on Win10 LTSB.  Honolulu 1802 works fine.  Install WAC and there is no popup or anything to choose the certificate as indicated in the installer.  Site can't be reached with the following error:  The webpage at https://localhost:6516/ might be temporarily down or it may have moved permanently to a new web address.
ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY

**Comment by Techsteps** [comment]
Leave out the port number. Just use https://localhost.

**Comment by davista2** [comment]
leaving out the port number gets "ERR_CONNECTION_REFUSED"

**Comment by jones85** [comment]
Still no response, as in there is nothing listening on port 443 at all.  I've tried https://<hostname>, https://<FQDN> and https://<IP Address>. NETSTAT -a shows nothing listening on port 443 but the service is running.

**Microsoft! can you give us a clue?**

**Comment by julienrudolph** [comment]
Does your machine has internet connection. 

If not look at the Microsoft-ServerManagementExperience. If there is an error with "Signature verificate failed" see https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/known-issues

**Comment by jones85** [comment]
Ohh? no, they don't.  On either of my environments (security policy).  Good shout julienrudolph!   But as I'm using an internal CA (and my root CA is not globally signed) wouldn't the signature verification still fail?

**Comment by julienrudolph** [comment]
It seems to be not the signature of your certificate. Windows tries to check the signature of the files installed with admin center.

**Comment by jones85** [comment]
ok, I have now allowed internet access to the server but it has mad no difference.  I've restarted the service and performed an uninstall/reinstall but no joy.  I'll continue to monitor the event logs...

**Comment by jones85** [comment]
So, I've had some success. I've followed the exact same setup as before except I've downloaded Windows Server 2019 TP (10.0.17639.1000).  First I ran the install with no internet access and again, no admin centre listening on TCP:443.  I gave the server internet access and ran an uninstall/reinstall... Voilà!  TCP:443 and WAC is now working... (Thanks @julienrudolph )  

But why can't a get the same result when running Windows Server 2016?

**Comment by kgranson** [comment]
@jones85 I am having the same problem.  Honolulu was working fine, an install of Windows Server Manager on the same server is having the exact same reaction as yours.  I did the same as you, gave the server access to the internet and then did a full reinstall, same results, no joy.  I am hoping for a solution to this soon because we are in the middle of testing a plugin for a 3rd party and they'd like to see some results.

**Comment by kgranson** [comment]
@jones85, I just figured it out on 2016.  When I configured the proxy, I configured it as me.  The installer runs as "administrator" due to UAC.  I had to globally set the proxy connection on the server, once I did that, I restarted the service and I am now able to connect!  

The command to do this is:
netsh winhttp set proxy <your proxy server>:<port> 

Once I did that, it seems happy!

Thank you @julienrudolph for setting me down the right path!

**Comment by jones85** [comment]
Good find @davista2 but we have no proxy in our environment and therefore my proxy settings do look as you have described.  Glad to hear that you have had some success mind.

**Comment by jones85** [comment]
So I performed another install using Server 2019 today.  Initially, I left the server with no internet access and ran the installer.  Result? The installer completed successfully but there was nothing listening on TCP:443 again.  I then gave the server internet access and restarted it but asked our networking analyst to log the traffic that originates from the VM... 
![3f4eeb3d](https://user-images.githubusercontent.com/32510981/39150159-4f28ee84-4739-11e8-9efc-77979e5f2b1d.PNG)
Once the server had spoken to the services at the end of that DNS/IP, WAC worked okay

**Comment by davista2** [comment]
@nwashburn-ms...how about the rest of us that have no restrictions on internet but still can't access WAC?  See my above comments where reinstalling 1802 works like it always did, but 1804 you can't access because the certificate selection never comes up per the installer instructions.  1802/1804 are installed on my Win10 computer...so no issues with internet.  Thanks.

**Comment by jwwool** [comment]
Hi @davista2, We haven't been able to reproduce this ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY error, but I have heard it from another customer.

Please try the following workaround, which worked for him:

Add the following two keys to the registry under HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Http\Parameters

```EnableHttp2Cleartext=dword:00000000```

```EnableHttp2Tls=dword:00000000```

**Comment by davista2** [comment]
@jwwool - THANK YOU!!!  That worked!  After I made that change and rebooted, I was able to select the certificate and am able to use WAC.  Thanks again!

**Comment by jwwool** [comment]
Thanks for confirming @davista2! I'll add this to our [troubleshooting guide.](http://aka.ms/wactroubleshoot)

While reviewing the thread, I saw you mention earlier that you were on W10 LTSB. Is this still the case?

**Comment by davista2** [comment]
@jwwool Correct...WAC is installed on my Win10 LTSB (1607) computer

**Comment by davista2** [comment]
@jwwool One question...aren't these two settings bad for production environments?  Shutting those two down should not be considered in production
