### ISSUE TITLE
Change URL

### ISSUE THREAD

**Issue by gdgriffiths** [MicrosoftDocs/windowsserverdocs#646]
I have installed admin center with our wildcard SSL certificate with the plan to be able to access it using a subdomain.certifcateddomain.org.uk address but i cannot find anywhere to actually manage the site bindings as it doesn't seem to use IIS.

Is there any config to change this?

**Comment by jwwool** [comment]
The web server binds to the machine name or FQDN. There is no mechanism to change this currently, if you'd like please [create a suggestion](http://aka.ms/wacfeedback) for this to be tracked!
