### ISSUE TITLE
Local printing using Remote Desktop app URDC

### ISSUE THREAD

**Issue by timcu** [MicrosoftDocs/windowsserverdocs#6462]
Please explain how to print to a local printer when using this product.

If local printing is not possible, please say this explicitly, and whether or not it is a planned future feature.

If I need to use the older product "Remote Desktop Connection" to local print, please explain how to connect "Remote Desktop Connection" to an Azure Virtual Desktop. (This should probably be on the RDC page, but a link from this page to the RDC page would help).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ab98fc-fea2-a11a-e5ca-de1430211d97
* Version Independent ID: 4d9943c3-fef7-ca86-bd03-1241a04b8135
* Content: [Get started with the Windows Desktop client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by dknappettmsft** [comment]
The client for the page linked here does support printer redirection - we call out that printer redirection needs to be configured by an admin:

- https://learn.microsoft.com/en-us/azure/virtual-desktop/configure-device-redirections#printer-redirection 
- https://learn.microsoft.com/en-us/azure/virtual-desktop/users/client-features-windows?toc=%2Fazure%2Fvirtual-desktop%2Ftoc.json#redirect-devices-audio-and-clipboard
- https://learn.microsoft.com/en-us/universal-print/fundamentals/universal-print-avd?toc=%2Fazure%2Fvirtual-desktop%2Ftoc.json

For the Microsoft Store client (URDC) doesn't support printer redirection. We can't add possible future plans to product docs. Here is a table that compares each client and the features supported:

- https://learn.microsoft.com/en-us/azure/virtual-desktop/compare-remote-desktop-clients#other-redirection-devices-etc

Finally, for Remote Desktop Connection - it's not supported for Azure Virtual Desktop.
