### ISSUE TITLE
Unusable docs for SMB settings

### ISSUE THREAD

**Issue by gwideman** [MicrosoftDocs/windowsserverdocs#6466]
[Enter feedback here]
It is hard to comprehend what a shambles this page is. It mixes together Server and Client docs, and a confusing array of methods just to find out or set what &^%$# SMB version(s) Windows is capable of.

An infuriating example is the section on determining whether SMBv1, v2 and/or v3 is enabled for the Client, titled: "SMBv2/v3 on SMB Client"

It shows the command:  sc.exe qc lanmanworkstation

... but then give no idea how to interpret the mumbo jumbo that command returns.  Which looks like this:
`C:\WINDOWS\system32>sc.exe qc lanmanworkstation
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: lanmanworkstation
        TYPE               : 20  WIN32_SHARE_PROCESS
        START_TYPE         : 2   AUTO_START
        ERROR_CONTROL      : 1   NORMAL
        BINARY_PATH_NAME   : C:\WINDOWS\System32\svchost.exe -k NetworkService -p
        LOAD_ORDER_GROUP   : NetworkProvider
        TAG                : 0
        DISPLAY_NAME       : Workstation
        DEPENDENCIES       : Bowser
                           : MRxSmb20
                           : NSI
        SERVICE_START_NAME : NT AUTHORITY\NetworkService
`
What on earth is that supposed to tell you?  Come on Microsoft -- ever more people are trying to connect their PCs to file servers of different types, and as the servers, and Windows updates elevate the security hurdles, it's a travesty that this is the interface to making things work, and the completely obtuse docs that are supposed to explain it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a91db45-ca3c-7a2e-3f32-2f5b57837b03
* Version Independent ID: b83cbaab-c0df-d6e7-a67f-f4c99a46e30a
* Content: [How to detect, enable and disable SMBv1, SMBv2, and SMBv3 in Windows](https://docs.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/detect-enable-and-disable-smbv1-v2-v3)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/file-server/Troubleshoot/detect-enable-and-disable-smbv1-v2-v3.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by RAJU2529** [comment]
I also found that, the following windows OS versions are mentioned in two  categories 
1.  How to detect status, enable, and disable SMB protocols on the SMB Server
2.  How to detect status, enable, and disable SMB protocols on the SMB Client

 **Windows 10, Windows Server 2019, Windows 8.1,Windows Server 2012 R2, and Windows Server 2012**

From my basic knowledge , the following windows OS comes under in Windows Client
**Windows Vista
Windows 7
Windows 8
Windows 8.1 
Windows 10
Windows 11**

From my basic knowledge, the following windows OS comes under in Windows Server
**Windows Server 2008
Windows Server 2008 R2
Windows Server 2012
Windows Server 2012 R2
Windows Server 2016
Windows Server 2019 
Windows Server 2022**

Which service is used to disable  **SMB v1, SMBv2** on windows client os
**LanmanServer  or LanmanWorkStation**

Which service is used to disable  **SMB v1, SMBv2** on windows Server os
**LanmanServer  or LanmanWorkStation**

**Comment by Xelu86** [comment]
Hey @gwideman, 

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made to better clarify our content by separating Server & Client functionalities. Changes will be live after the next business day. 

To address the "mumbo jumbo", please look at [sc.exe config](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/sc-config) documentation which provides more insight to the output in question. 

We also have additional support forums listed below if looking for more technical aid into what you're trying to achieve which may not be found in our doc set:
- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

We will now be closing this thread. Thank you and have a most pleasant day. #please-close

**Comment by gwideman** [comment]
@Xelu86 :
I just checked the page, now dated 12/13/2022, presumably the revised one, and so far as I can tell, it still doesn't address my issue report.

Under "How to detect status, enable, and disable SMB protocols", the C;ient tab still says to use:

`sc.exe qc lanmanworkstation`

and still doesn't show sample results or say how to interpret the results.

And your suggestion to interpret the results by looking at the docs for "sc.exe config" doesn't make any sense, as that's a different command.

I am simply looking for a straightforward, authoritative, no-runaround, unambiguous way to get Windows (10 in my case) to tell me which SMB protocols it is capable of engaging in, as a client.  Why is this so difficult?
