### ISSUE TITLE
The repo behind the link from the article is missing.

### ISSUE THREAD

**Issue by lmakar** [MicrosoftDocs/windowsserverdocs#6468]
the link from the doc mentioned "here" is pointing to
the: https://github.com/microsoft/adfs-sample-msal-dotnet-webapp-to-webapi
But the GitHub can't find any repo behind it.

It feels extremely upsetting for people that are new to AFDS since there are no details on the Auth pipeline configuration in the article itself, and the only link is broken.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1023d1b4-ba6b-32ab-7e9c-7cfb7a4b07dd
* Version Independent ID: 876ffb88-2999-179c-aab8-a7db6e773011
* Content: [AD FS MSAL Web app (server app) calling web APIs](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/msal/adfs-msal-web-app-web-api)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/msal/adfs-msal-web-app-web-api.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/development/msal/adfs-msal-web-app-web-api.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
The repo exists but is archived. No further changes to the content in the repo will be accepted, but the repo can still be cloned.
