### ISSUE TITLE
GitHub issue linking

### ISSUE THREAD

**Issue by louislu007** [MicrosoftDocs/windowsserverdocs#6469]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1023d1b4-ba6b-32ab-7e9c-7cfb7a4b07dd
* Version Independent ID: 876ffb88-2999-179c-aab8-a7db6e773011
* Content: [AD FS MSAL Web app (server app) calling web APIs](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/msal/adfs-msal-web-app-web-api)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/msal/adfs-msal-web-app-web-api.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/development/msal/adfs-msal-web-app-web-api.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
Closing GitHub issue as user feedback is unspecified. #please-close
