### ISSUE TITLE
AVD RemoteDesktop Client - RemoteApp not visible on taskbar

### ISSUE THREAD

**Issue by dgiesselbach** [MicrosoftDocs/windowsserverdocs#6472]
Hello,

we have a RemoteApp on AVD (W10 multisession build 20H2) that shows up for 1 second on the taskbar. After 1 second its gone. If you minimized and maximized the app window again, then it will be visible on the taskbar. But when you logout and logon again, the app is not visible... Its really strange...

The app is accessable via UNC path and we created a shortucut on SessionHost to start it. We have 3 more apps that working fine with this solution!

Other applications like Word / Outlook... are visible all the time on the taskbar.

Maybe a Bug from the RemoteDesktop Client? We have the last one 1.2.3130.0 (x64).

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @dgiesselbach,

Thanks again for contacting Microsoft. We value your feedback.

As we understand it, you're describing an issue with the product compared to an issue with the documentation. GitHub isn't quite the right location or channel if searching for technical support, deeper specifics of the product or feature requests as it is completely outside our scope. If there are any issues within the content itself, such as incorrect code, verbiage, etc., please let us know.

As the issue you're experiencing is quite specific, we recommend that you engage with the product community or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).

Additional support forums listed below:
- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Hopefully one of the community experts may be able to better assist. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
