### ISSUE TITLE
Any intention for 2012 R2 gateway support

### ISSUE THREAD

**Issue by JamesEdmonds89** [MicrosoftDocs/windowsserverdocs#648]
Any intention to bring gateway support for this to 2012 R2, considering it worked perfectly well in preview?

Our entire estate is 2012 R2, and we aren't interested in 2016 yet, but would like to make use of WAC.
Shame that this scenario's support has been removed!

**Comment by jwwool** [comment]
Our plan is to eventually take dependencies on features that did not exist prior to 2016. We are tracking interest on installing on 2012 R2 [here](https://windowsserver.uservoice.com/forums/295071/suggestions/33946567). Please add your vote!
