### ISSUE TITLE
Missing forward slash in docs & examples

### ISSUE THREAD

**Issue by cscholefield** [MicrosoftDocs/windowsserverdocs#6483]
imageFile & imageType parameters require forwardslash in Windows Server 2022

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d597eca3-40f7-6c36-b683-8de4822836f6
* Version Independent ID: 0ae91c11-1a15-3226-87eb-fe993be88a8d
* Content: [wdsutil add-image](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/wdsutil-add-image)
* Content Source: [WindowsServerDocs/administration/windows-commands/wdsutil-add-image.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/wdsutil-add-image.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. A documentation change has been made and will be live after the next business day. #please-close
