### ISSUE TITLE
Windows Desktop client & Web client (remoteapp) VB6 application no more refresh on maximized state

### ISSUE THREAD

**Issue by alexandretuee** [MicrosoftDocs/windowsserverdocs#6484]
Hi,

Since this weekend, our VB6 Application with MDI form stop refresh the form if maximized but only for certain user not all. Must depends on the user resolution of their screen. Before that, everything was running good.

Also, when a modal form open in the application, the application task bar icon disappears..
Exactly the same issue as this one - > https://github.com/MicrosoftDocs/windowsserverdocs/issues/6472

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @alexandretuee,

Thanks again for contacting Microsoft. We value your feedback.

As we understand it, you're describing an issue with the product compared to an issue with the documentation. GitHub isn't quite the right location or channel if searching for technical support, deeper specifics of the product or feature requests as it is completely outside our scope. If there are any issues within the content itself, such as incorrect code, verbiage, etc., please let us know.

As the issue you're experiencing is quite specific, we recommend that you engage with the product community or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).

Additional support forums listed below:
- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Hopefully one of the community experts may be able to better assist. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
