### ISSUE TITLE
Dando erro

### ISSUE THREAD

**Issue by Viniciustt** [MicrosoftDocs/windowsserverdocs#6491]
![Screenshot_20220528-042512_Microsoft Remote Desktop](https://user-images.githubusercontent.com/106451421/170842217-c12e70ce-d63b-4e6b-ab16-8cf8df1f9ffc.jpg)

[Enter feedback here]
Erroo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e9e26ca-6ca8-4f7f-b033-2398576369af
* Version Independent ID: b5b50e01-baf9-c2fe-7a1e-6f04a276e1fc
* Content: [Get started with the Android client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-android)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-android.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-android.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @Viniciustt,

Thanks again for contacting Microsoft. We value your feedback.

As we understand it, you're describing an issue with the product compared to an issue with the documentation. GitHub isn't quite the right location or channel if searching for technical support, deeper specifics of the product or feature requests as it is completely outside our scope. If there are any issues within the content itself, such as incorrect code, verbiage, etc., please let us know.

As the error you're receiving is quite specific, we recommend that you engage with the product community or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).

Looking into our support forums may provide details as to why you may be receiving this error. Please see this search on [RDP Client 0x204](https://answers.microsoft.com/en-us/search/search?SearchTerm=0x204&tab=&status=all&advFil=&IsSuggestedTerm=false&isFilterExpanded=undefined&CurrentScope.ForumName=windows&CurrentScope.Filter=windows_10&ContentTypeScope=&page=1&sort=Relevance&dir=Desc&from=threadpagesearchbar) error.

Additional support forums listed below:
- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Hopefully one of the community experts may be able to better assist. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
