### ISSUE TITLE
Batch: "del" command being used with spaces in a folder name of a directory

### ISSUE THREAD

**Issue by FunXTime** [MicrosoftDocs/windowsserverdocs#6494]
Hello, this is a question regarding Batch.
How do we delete (`del`) a file using a **directory containing spaces**?
What I mean is that if I have written (for example):
`del C:\an example\folder\file.txt`
But then the computer will think it has to delete:
`C:\an`
`example\folder\file.txt`

How will we let the computer know about the spaces in a folder name of a directory?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e809f83e-26b1-52b5-a663-e2d3705e7cdc
* Version Independent ID: b968d3d3-1ba0-65a8-524e-3c5e4118209f
* Content: [del](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/del)
* Content Source: [WindowsServerDocs/administration/windows-commands/del.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/del.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We've submitted a documentation change based on your suggestion. Changes will be live after the next business day. 

To delete a file or all files in a folder where the folder has a space in its name, the full path needs to be wrapped in double quotes.

Per your example: del "C:\an example\folder\file.txt"
