### ISSUE TITLE
reg query: missing documentation for /reg:32 and /reg:64 switches

### ISSUE THREAD

**Issue by kevinushey** [MicrosoftDocs/windowsserverdocs#6500]
What it says on the tin. On my Windows machine, I see:

```
C:\Users\kevin>reg query /?

REG QUERY KeyName [/v [ValueName] | /ve] [/s]
          [/f Data [/k] [/d] [/c] [/e]] [/t Type] [/z] [/se Separator]
          [/reg:32 | /reg:64]
```

However, the `/reg:32` and `/reg:64` keys are not documented on the associated Microsoft Docs page.

For posterity, the command line also mentions:

```
  /reg:32  Specifies the key should be accessed using the 32-bit registry view.

  /reg:64  Specifies the key should be accessed using the 64-bit registry view.
```

but some extra documentation on different registry views would be helpful here (especially since, as I understand it, there might be some extra consideration for Windows on ARM)

(Perhaps also worth noting that Windows provides multiple copies of `regedit.exe`, and some online documentation suggests that different versions should be used depending on which registry view one wants to check?)

```
C:\Users\kevin>where /R C:\Windows regedit.exe
C:\Windows\regedit.exe
C:\Windows\SysWOW64\regedit.exe
< ... >
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b712cc31-d8c9-7694-01b8-a85cda240f7f
* Version Independent ID: 9c95c177-9bef-03ec-5774-f92b7ea42c9e
* Content: [reg query](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/reg-query)
* Content Source: [WindowsServerDocs/administration/windows-commands/reg-query.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/reg-query.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @kevinushey,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding these parameters and will be live after the next business day.  Concerning more depth into this article, the main intent is to provide it solely as a reference with a few examples of its use. We do have more articles that go into depth that can be found at [Source 1](https://learn.microsoft.com/en-US/troubleshoot/windows-client/deployment/view-system-registry-with-64-bit-windows) & [Source 2](https://learn.microsoft.com/en-us/troubleshoot/windows-server/performance/windows-registry-advanced-users). Going through it, I did see this in the first paragraph:

> There are no differences in the way you perform tasks between the 32-bit version of Registry Editor and the 64-bit version of Registry Editor.

I did not go through the whole article myself but wanted to procure some other references. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
