### ISSUE TITLE
Thanks%

### ISSUE THREAD

**Issue by Dominik192** [MicrosoftDocs/windowsserverdocs#6504]
This is the reason 
@echo off
Set X=0
Set Y=0
:restart
If %X% == 10 goto :Yp
If %Y% == 10 goto :stop
Set %X%%Y%=%X%%Y%
Set /a X=%X%+1
goto :restart
:Yp
Set /a Y=%Y%+1
Set X=0
goto :restart

:stop
echo.%00% %10% %20% %30% %40% %50% %60% %70% %80% %90%
echo.%01% %11% %21% %31% %41% %51% %61% %71% %81% %91%
echo.%02% %12% %22% %32% %42% %52% %62% %72% %82% %92%
echo.%03% %13% %23% %33% %43% %53% %63% %73% %83% %93%
echo.%04% %14% %24% %34% %44% %54% %64% %74% %84% %94%
echo.%05% %15% %25% %35% %45% %55% %65% %75% %85% %95%
echo.%06% %16% %26% %36% %46% %56% %66% %76% %86% %96%
echo.%07% %17% %27% %37% %47% %57% %67% %77% %87% %97%
echo.%08% %18% %28% %38% %48% %58% %68% %78% %88% %98%
echo.%09% %19% %29% %39% %49% %59% %69% %79% %89% %99%
pause >nul
goto: stop

didn't work!
Thank you for making this place!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 362d60c8-8d69-6016-10bd-0f81114ec228
* Version Independent ID: 76d9a719-f621-f716-4987-68acb1501c63
* Content: [for](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/for)
* Content Source: [WindowsServerDocs/administration/windows-commands/for.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/for.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. As there are no issues with the document in question, we will be closing this issue. #please-close
