### ISSUE TITLE
Forest and Domain Prep??

### ISSUE THREAD

**Issue by pmcdonn1** [MicrosoftDocs/windowsserverdocs#651]
If the Forest is already at 2016 and the domain is already at 2012, would we still need to run these steps? I cannot upgrade my domain functional level to 2016 just yet but my schema is already at 2016.  I don't want run the upgrade if it is going to break something.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebfd725f-1b77-751c-1948-f8f88d26a9bc
* Version Independent ID: 7d9c78d9-7736-8f0a-9636-269125a10d6f
* Content: [Upgrading to AD FS in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by thibaultchatiron** [comment]
If your schema is 2016, it's ok then. That is the prerequisite. For the prerequisite about domain functional level, 2003 is the minimum and 2008 if you use client certificate authentication
