### ISSUE TITLE
windows admin center configure

### ISSUE THREAD

**Issue by jereytucker** [MicrosoftDocs/windowsserverdocs#6510]
######
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d18b413e-74c7-9d71-63c6-360c0bcba261
* Version Independent ID: 546104d1-d9de-94f7-2183-8552832a0769
* Content: [Settings](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/configure/settings)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/configure/settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/manage/windows-admin-center/configure/settings.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **wscontent**

**Comment by Xelu86** [comment]
#assign:xelu86
