### ISSUE TITLE
Possible typo?

### ISSUE THREAD

**Issue by td48260** [MicrosoftDocs/windowsserverdocs#6511]
The page says:
To perform the upgrade
1. Make sure the BuildLabEx value says you're running Windows Server 2012.

My BuildLabEx is "9200.23711.amd64fre.win8_ldr_escrow.220427-1731". Should step 1 say "ProductName" instead of "BuildLabEx"?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 465ee446-5e41-bd72-1305-976db9c3a4ec
* Version Independent ID: f7091237-826d-1e6e-d8f3-b688205f25fd
* Content: [Upgrade Windows Server 2012 to Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/get-started/upgrade-2012-to-2016)
* Content Source: [WindowsServerDocs/get-started/upgrade-2012-to-2016.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/upgrade-2012-to-2016.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @RobHindman
* Microsoft Alias: **robhind**

**Comment by robinharwood** [comment]
Hi @td48260 

Thanks for your dedication to our documentation. We've submitted some documentation changes to the upgrade pages, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. If you need to follow up on this issue, leave us a comment with an @mention.

#assign:robinharwood
#please-close
