### ISSUE TITLE
Broken link -- System Restore

### ISSUE THREAD

**Issue by BR77BE** [MicrosoftDocs/windowsserverdocs#6516]
"System Restore" link is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d7bd11a-e693-26a0-d374-5cfb1d2335d3
* Version Independent ID: bc9a2fb3-fa85-4ec0-8e0f-6e7c4906262b
* Content: [Volume Shadow Copy Service](https://docs.microsoft.com/en-us/windows-server/storage/file-server/volume-shadow-copy-service)
* Content Source: [WindowsServerDocs/storage/file-server/volume-shadow-copy-service.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/file-server/volume-shadow-copy-service.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @BR77BE,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made updating the broken link in question and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
