### ISSUE TITLE
/TIME parameter description is incorrect

### ISSUE THREAD

**Issue by alex47** [MicrosoftDocs/windowsserverdocs#6518]
This is what the /time parameter description says:

> Specifies the amount of time that the message you sent is displayed on the user's screen. After the time limit is reached, the message disappears. If no time limit is set, the message remains on the user's screen until the user sees the message and clicks OK.

This is false. 
When the time parameter is omitted the timeout is 60 seconds.

You can try this in powershell:
`Measure-Command { MSG /W * "Test" }`

Result:
```
Days              : 0
Hours             : 0
Minutes           : 1
Seconds           : 0
Milliseconds      : 56
Ticks             : 600562197
TotalDays         : 0.000695095135416667
TotalHours        : 0.01668228325
TotalMinutes      : 1.000936995
TotalSeconds      : 60.0562197
TotalMilliseconds : 60056.2197
```

You can find some technical details here: https://stackoverflow.com/a/40461255/3420775

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83436a0e-9eb4-23f5-16ed-1badecb22f48
* Version Independent ID: 757738ea-6b32-fa58-0d76-12ada0fbd535
* Content: [msg](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/msg)
* Content Source: [WindowsServerDocs/administration/windows-commands/msg.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/msg.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @alex47,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made surrounding the `/time` parameter and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
