### ISSUE TITLE
Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'

### ISSUE THREAD

**Issue by onknows** [MicrosoftDocs/windowsserverdocs#6519]
It is in fact not possible to install OpenSSH using command given because per recommendation that wil be prevented with message 

> The requested operation requires elevation  

As shown below. There is a lot of documentation on this error message. I think in excess of 100.000 pages on the internet try to address this issue but this won't be resolved really until MS fixes it. Currently there is no clear supported way to fix this issue. Most of recommendations won't work depending on the situation.

```
PS C:\Windows\system32> Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'
Get-WindowsCapability : The requested operation requires elevation.
At line:1 char:1
+ Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WindowsCapability], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsCapabilityCommand

PS C:\Windows\system32>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Get started with OpenSSH](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by robinharwood** [comment]
Hi @onknows,

Thanks for the feedback and dedication to our documentation.

I see this message you are receiving means you are either running this as a standard user or without an administrative context. The article does state to install OpenSSH using PowerShell, run PowerShell as an Administrator. This can be done by right clicking the PowerShell shortcut and selecting **Run as administrator** or by right clicking the Start button and selecting **Windows PowerShell (Admin)**.

In addition, I will look at the current article to see if this should be made clearer. In the meantime, I am marking this documentation issue has been resolved and we are closing the issue. #please-close

To follow up on this documentation issue, leave us a comment with an @mention. To get assistance or support for your product issue, we recommend that you engage with the product community or open a ticket with Microsoft Support. For more information, see [Contact Microsoft Support](https://support.microsoft.com/ContactUs)

Thanks,

Robin
