### ISSUE TITLE
Installing Windows Admin Center.............

### ISSUE THREAD

**Issue by gabrielluizbh** [MicrosoftDocs/windowsserverdocs#652]
What is the average installation time?

You have a few minutes, which is on the installation screen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32deb7a0-4ea0-caf1-0777-580539173e44
* Version Independent ID: a6ee1f9d-b316-c69d-fa9d-2a1556454868
* Content: [Deploy Windows Admin Center with High Availability](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/high-availability)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/deploy/high-availability.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/deploy/high-availability.md)
* Service: **unspecified**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by gabrielluizbh** [comment]
I checked here, the error was the name of the cluster, after the fix worked perfectly.

**Comment by jwwool** [comment]
@gabrielluizbh Thanks for confirming that your issue was resolved! 
Did the script just hand with the incorrect cluster name, or did it throw an error? If we can improve the error handling, we will.

**Comment by gabrielluizbh** [comment]
After several attempts to try to run the script, we find that we must first execute script unlock on all nodes in the cluster.

I ran the following commands on all nodes in the cluster.

Get-ExecutionPolicy -List
Get-ExecutionPolicy -ScopeMachine
Set-ExecutionPolicy Unrestricted -Scope LocalMachine


More information:

https://technet.microsoft.com/en-us/library/hh847748.aspx

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/get-executionpolicy?view=powershell-6

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-6

**Comment by gabrielluizbh** [comment]
Today repeat the same procedure of executing scipt but unfortunately, again the script does not perform correct form. Please Jeff Woolslayer take away my doubt about what can be running because one hour the script performs correctly another time does not run.

**Comment by RocknRolla101** [comment]
for those where the Installation just gets stuck, it's because of the following line:
$process = [System.Diagnostics.Process]::Start($processSInput)
change it to:
$process = Start-Process msiexec.exe -ArgumentList ('/I ' + $processSInput.FileName + ' ' +  $processSInput.Arguments).ToString() -Wait -NoNewWindow -Passthru

Somehow the script is not able sometimes to find the MS Installer.
Also make sure you enable Script execution as mentioned above (if it still doesnt work):
Set-ExecutionPolicy Unrestricted -Scope LocalMachine
Set-ExecutionPolicy Unrestricted -Scope Process
