### ISSUE TITLE
SQL 2017

### ISSUE THREAD

**Issue by agressiv** [MicrosoftDocs/windowsserverdocs#653]
Is SQL 2017 supported for WSUS yet?  If not, is there an ETA?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa4be2a-4045-4135-353a-ed882ada9402
* Version Independent ID: c43f3896-9f9b-2754-9b5d-d73f9650592b
* Content: [Plan Your WSUS Deployment](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/plan/plan-your-wsus-deployment)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/plan/plan-your-wsus-deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/plan/plan-your-wsus-deployment.md)
* Service: **unspecified**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Ref. #3984 & commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/a9fbb9880f83834baeef7855ddc28e965dabd9a9 - this issue ticket can be closed.

**Comment by illfated** [comment]
#please-close
