### ISSUE TITLE
missing double-quote

### ISSUE THREAD

**Issue by farismalaeb** [MicrosoftDocs/windowsserverdocs#6556]
The PowerShell line is not correct as the "" are missing.
``` where {$_.Severity -eq Information}``` should be  where ```{$_.Severity -eq "Information"}```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60f64dda-00e0-473d-31ee-019dfde9770a
* Version Independent ID: 163b79d0-138a-7d42-ccf9-eeae66879d6d
* Content: [Run Best Practices Analyzer Scans and Manage Scan Results_1](https://docs.microsoft.com/en-us/windows-server/administration/server-manager/run-best-practices-analyzer-scans-and-manage-scan-results)
* Content Source: [WindowsServerDocs/administration/server-manager/run-best-practices-analyzer-scans-and-manage-scan-results.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/server-manager/run-best-practices-analyzer-scans-and-manage-scan-results.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey @farismalaeb,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting all PS cmdlet instances where double quotes are needed. Changes will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
