### ISSUE TITLE
Looking for information on keys that drive TLS/SSL renegotiation behavior in Schannel

### ISSUE THREAD

**Issue by mscottmueller** [MicrosoftDocs/windowsserverdocs#6558]
In troubleshooting some schannel issues with channel renegotiation, I've come across a few registry keys:

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL]
"AllowInsecureRenegoClients"=dword
"AllowInsecureRenegoServers"=dword
"DisableRenegoOnServer"=dword

The first two only seem to be documented in MS10-049, and only there, but I can't find any information on DisableRenegoOnServer. Searches for this information point to the MS10-049 advisory containing this registry value as well as "DisableRenegoOnServer" in 2010.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd180142-4c19-8abc-ecce-e4c7e5ac8951
* Version Independent ID: fc5bba87-afad-1729-8f7e-333c73188b73
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by Xelu86** [comment]
Hey mscottmueller,

Thanks again for contacting Microsoft. We value your feedback. 

Conversing with the TLS team on this, I was given the following response:

> "There are several registry values that can be used to change schannel behavior and a lot of settings are implemented internally. Authors/Contributors are under no obligation to document every single setting. Configuring them without deep understanding will generate more support cases. We actively discourage customers from using some of schannel settings for this reason."

I did go into our tech community and did find some links that may potentially assist you:

- https://social.msdn.microsoft.com/Forums/en-US/8f5907de-0458-4740-8d8a-fd74042aeb8e/how-do-you-enable-quotsecure-renegotiationquot-in-iis-on-windows-2012-r2?forum=iissecurity
- https://social.msdn.microsoft.com/Forums/en-US/d80517da-ab45-40d3-b9b6-6b275dd01b7a/disable-renegotiation?forum=iissecurity
- https://social.msdn.microsoft.com/Forums/en-US/3f69a42b-b62d-4a4a-81aa-f93d6d4883de/client-certificate-selection?forum=iissecurity

Here are our additional support forums:
- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Hopefully one of our community experts can assist you better. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
