### ISSUE TITLE
Wrong info

### ISSUE THREAD

**Issue by KillerMZE** [MicrosoftDocs/windowsserverdocs#6559]
Information for `netmask` is just a copy of the `destination` info

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5298689-e441-3788-b31d-967dbce4f735
* Version Independent ID: 5b078c74-5b82-3b35-5842-8ce6142b2152
* Content: [route](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/route_ws2008)
* Content Source: [WindowsServerDocs/administration/windows-commands/route_ws2008.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/route_ws2008.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hy @KillerMZE,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made surrounding the mask/netmask descriptions and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
