### ISSUE TITLE
Still no Server 2022 added to in-place upgrade support

### ISSUE THREAD

**Issue by stupots** [MicrosoftDocs/windowsserverdocs#6563]
[Enter feedback here]
Hi, I see this page has been upgraded recently, but there is still no Server 2022 added to this page 10 months after it's release. I cannot find and "Microsoft" documentation that says it even supports an upgrade from 2019. We would very much like to upgrade our DCs to server 2022 and some of them are physical machines, so would like to perform in-place upgrades on those (I've cloned them to a VM and done upgrade testing)

Our management are very much "Only do it if Microsoft support it" so it doesn't matter how much testing I do and how flawless the results are, until Microsoft add it to the in-place support matrix I have to do fresh rebuilds on everything.

Thanks

Stuart
(working as a system admin at a UK University)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 505fe07b-6fdd-4887-3c8b-15405c5d8308
* Version Independent ID: 25645df2-0ffb-4cc3-a8d2-5466edd309fb
* Content: [Overview of Windows Server upgrades](https://docs.microsoft.com/en-us/windows-server/get-started/upgrade-overview)
* Content Source: [WindowsServerDocs/get-started/upgrade-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/upgrade-overview.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @RobHindman
* Microsoft Alias: **robhind**

**Comment by robinharwood** [comment]
Hi @stupots 

Thanks for your dedication to our documentation.  I appreciate it is frustrating we haven’t been able to provide this information in a timely response, I apologise for the delayed response and thank you for your patience. We've submitted a documentation change based on your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. If you need to follow up on this issue, leave us a comment with an @mention.

#assign:robinharwood
#please-close
