### ISSUE TITLE
Typing Error?

### ISSUE THREAD

**Issue by LarsVonZipper** [MicrosoftDocs/windowsserverdocs#6564]
Should step 6 under the section "To upgrade your AD FS farm to Windows Server 2019 Farm Behavior Level" say '2019' and NOT '2016'

rgds
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5a924c8-8933-cb05-d4d1-8ac3cf64d1a9
* Version Independent ID: 15f1d47c-f8ec-7b76-7dbd-9bae4de99125
* Content: [Upgrading to AD FS in Windows Server 2016 and 2019](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
#assign:xelu86
