### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by Beaudge** [MicrosoftDocs/windowsserverdocs#6566]
[Enter feedback here]

This link is dead - https://docs.microsoft.com/en-us/windows/threat-protection/windows-defender-antivirus/windows-defender-antivirus-on-windows-server-2016

Can it be updated to the current location?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfee81e6-dba5-cbd6-4190-3b3aa3fd5f94
* Version Independent ID: ad63832b-7b61-01c2-83f8-11a446ddfbb7
* Content: [Windows Defender Overview for Windows Server](https://docs.microsoft.com/en-us/windows-server/security/windows-defender/windows-defender-overview-windows-server)
* Content Source: [WindowsServerDocs/security/windows-defender/windows-defender-overview-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/security/windows-defender/windows-defender-overview-windows-server.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We've submitted a documentation change based on your feedback. Changes will be live after the next business day. #please-close
