### ISSUE TITLE
wrong registy hive/key name 

### ISSUE THREAD

**Issue by Uchiko** [MicrosoftDocs/windowsserverdocs#6568]
[Enter feedback here]
bad:  HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsNT\CurrentVersion
correct  HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion
   space missing between 'Windows' and 'NT' (2 times)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82772fa0-1642-4481-dff0-ebf83270db4d
* Version Independent ID: e5d451c4-2ee0-9461-c19b-19d0cb199b42
* Content: [Upgrade Windows Server 2012 R2 to Windows Server 2019](https://docs.microsoft.com/en-us/windows-server/get-started/upgrade-2012r2-to-2019)
* Content Source: [WindowsServerDocs/get-started/upgrade-2012r2-to-2019.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/upgrade-2012r2-to-2019.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @RobHindman
* Microsoft Alias: **inhenkel**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We've submitted a documentation change based on your suggestion. Changes will be live after the next business day. #please-close
