### ISSUE TITLE
clarifying windows core licenses vs virtual cores

### ISSUE THREAD

**Issue by aipsychnerd** [MicrosoftDocs/windowsserverdocs#6572]
Sales resources have raised issues born of confusion on wording of "Rules and use cases" section where MSFT states: 

" After that, a minimum of eight additional core licenses with active Software Assurance entitles use on up to eight virtual cores and one Azure VM, where core licenses are sold in two-core packs and 16-core packs. " 

We should clarify WINDOWS core licenses in this sentence, so that users might more easily read the distinction between "windows core" and "virtual cores". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90e335dd-0bc5-a7e3-650b-e3dd1823176b
* Version Independent ID: 18f34ef3-ff61-0473-a64b-ac5a64dbe1d7
* Content: [Azure Hybrid Benefit for Windows Server](https://docs.microsoft.com/en-us/windows-server/get-started/azure-hybrid-benefit#rules-and-use-cases)
* Content Source: [WindowsServerDocs/get-started/azure-hybrid-benefit.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/azure-hybrid-benefit.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @dknappettmsft
* Microsoft Alias: **daknappe**

**Comment by dknappettmsft** [comment]
#assign:@robinharwood

**Comment by aipsychnerd** [comment]
Continuing conversation with field - they also contested the second paragraph in "ruse and use cases" section which conflicts with messaging from MS licensing specialists who advised that a user with 24 Windows core licenses could apply these to 4 1vCore VMs + 1 20vCore VMs =, whereas docs wording implies a user with 24 Windows core licenses can have up to 4 VMs but all VMs must have a minimum of 8 virtual cores. 

"An Azure VM must be licensed with a minimum of eight cores, regardless of the size, then you can stack additional core licenses on top to the number you need."

**Comment by dknappettmsft** [comment]
Hi @aipsychnerd, thanks for the feedback. In the Azure product licensing terms (https://www.microsoft.com/licensing/terms/productoffering/MicrosoftAzure/EAEAS), there is a section for AHUB which states:

"...each Windows Server processor License with SA, and each set of 16 Windows Server core [Licenses](https://www.microsoft.com/licensing/terms/product/Glossary/all) with SA, entitles Customer to use Windows Server on Microsoft Azure on up to 16 [Virtual Cores](https://www.microsoft.com/licensing/terms/product/Glossary/all) **allocated across two or fewer Azure Base Instances**. Each additional set of 8 core [Licenses](https://www.microsoft.com/licensing/terms/product/Glossary/all) with SA entitles use on up to 8 [Virtual Cores](https://www.microsoft.com/licensing/terms/product/Glossary/all) **on one Base Instance**."

The last part is specific about 1 base instance (VM) per 8 core pack, not 8 x 1 core VMs.  It's probably best if you can set up a call internally to discuss.  Adding @robinharwood.

**Comment by aipsychnerd** [comment]
Hey - yea I can setup an internal call, Looks like Robin isn't back for a couple weeks. We did review the licensing pages (it looks like there's a couple typos there as well), and understand that the total number of VMs cannot exceed [[#core windows licenses] / 8] - however there's still confusion if each VM / "base instance" must have a minimum of 8 virtual cores. 

Apologies - in the example above I meant to stay within the 4 VM limit - let's change it to 2 1vCore VMs + 1v22Core VM.

**Comment by v-thepet** [comment]
Hi @aipsychnerd,

Thanks for contacting Microsoft. We value your feedback.

This article underwent quite a few revisions in 2022 after this issue was filed, and the specific content discussed in this thread is no longer present. The language regarding core licenses and virtual cores has been clarified and no longer seems of concern. A documentation update has been made primarily to clarify the licensing requirements for Azure Hybrid Benefit for Azure Stack HCI.

We'll now be closing this issue. However, if you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your continued support.

#please-close
