### ISSUE TITLE
PowerShell command to start vmms service is incorrect.

### ISSUE THREAD

**Issue by phollyni** [MicrosoftDocs/windowsserverdocs#6577]
the command "sc start vmms" does not start the vmms service when run from PowerShell. By default sc is an alias for the set-content PowerShell command. To execute the command correctly in PowerShell you need to use "sc.exe start vmms".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97843995-fb91-967c-6c44-1d5ae0f7b83a
* Version Independent ID: a6ccec18-1c4d-3d0a-d564-8d2ed7409c2f
* Content: [The Hyper-V Virtual Machine Management service must be running](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/best-practices-analyzer/the-hyper-v-virtual-machine-management-service-must-be-running)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/best-practices-analyzer/The-Hyper-V-Virtual-Machine-Management-service-must-be-running.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/virtualization/hyper-v/best-practices-analyzer/The-Hyper-V-Virtual-Machine-Management-service-must-be-running.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. A documentation change has been made based on your suggestion. Changes will be live after the next business day. #please-close
