### ISSUE TITLE
Teams optimization for AVD is supported for our macOS client too

### ISSUE THREAD

**Issue by RobVyK** [MicrosoftDocs/windowsserverdocs#6579]
According to https://docs.microsoft.com/en-us/azure/virtual-desktop/teams-on-avd :

_Media optimization for Microsoft Teams is only available for the following two clients:
- Windows Desktop client for Windows 10 or 11 machines, version 1.2.1026.0 or later.
- **macOS Remote Desktop client, version 10.7.7 or later.**_

Can we update the table on https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-features#client-features to reflect that "Teams optimization for Azure Virtual Desktop" is available also for macOS?

Thanks,
Robert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d746fc6-0121-c9dc-f552-2d53a902922f
* Version Independent ID: a7508e87-b2ac-c474-f168-5af94c250332
* Content: [Remote Desktop clients feature comparison](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-features)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-features.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-features.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by craigcaseyMSFT** [comment]
Hello @RobVyK,

Thanks for contacting Microsoft. We value your feedback.

We have tested the problem as described in this issue and either couldn't replicate the stated result or have verified that no documentation change is required.

As a result, we’re closing this thread.

Thank you again and have a most pleasant day.
#please-close
