### ISSUE TITLE
the Replacing the SSL certificate for the Web Application Proxy PS missing agurment

### ISSUE THREAD

**Issue by freddylao** [MicrosoftDocs/windowsserverdocs#658]
correct one: Set-WebApplicationProxySslCertificate -Thumbprint '<thumbprint of new cert>'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d10177c6-b241-0a3e-d6ba-3619c094812a
* Version Independent ID: 7a42691f-7f28-eee2-0c69-294e24cccdbe
* Content: [Managing SSL Certificates in AD FS and WAP in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/manage-ssl-certificates-ad-fs-wap#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/manage-ssl-certificates-ad-fs-wap.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/manage-ssl-certificates-ad-fs-wap.md)
* Service: **unspecified**
* GitHub Login: @jenfieldmsft
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Resolved in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/9622422acc1b6f4bf134b1c8793c248198961f58 (Pull Request #2800 **The "Thumbprint" parameter is required for Set-WebApplicationProxySsl…**)

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
