### ISSUE TITLE
missing key for Windows Server 2022 Datacenter Azure Edition (21H2)

### ISSUE THREAD

**Issue by dnevelos** [MicrosoftDocs/windowsserverdocs#6589]
[Enter feedback here]
Please add the Generic key for Windows Server 2022 Datacenter Azure Edition (21H2)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5148ebad-44a0-b14a-d65c-e51650ce4197
* Version Independent ID: ceb3e4c3-ccc3-b75a-ccb1-235ad1a22469
* Content: [Key Management Services (KMS) client activation and product keys for Windows Server and Windows](https://docs.microsoft.com/en-us/windows-server/get-started/kms-client-activation-keys)
* Content Source: [WindowsServerDocs/get-started/kms-client-activation-keys.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/kms-client-activation-keys.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @dknappettmsft
* Microsoft Alias: **daknappe**

**Comment by MatthewBrown0** [comment]
Hello - What is the status of this request?

**Comment by Xelu86** [comment]
Hey dnevelos,

Thanks again for contacting Microsoft. We value your feedback. 

This key was added to this page and this thread was not closed. 

> | Windows Server 2022 Datacenter Azure Edition | NTBV8-9K7Q8-V27C6-M2BTV-KHMXV |

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
