### ISSUE TITLE
Oops, we couldn't connect to 

### ISSUE THREAD

**Issue by dgnice** [MicrosoftDocs/windowsserverdocs#659]
Oops, we couldn't connect to
When i launch remoteApps application ...
Have you an idea ? ( no errors for log )
thanks for your reply !
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Service: **unspecified**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by davidbel** [comment]
@dgnice If you are still seeing some connection issues, you can first take a look at the browser console to see if the error indicates where the problem might be. If not, please reach out using the email address found on the About page of the client.
