### ISSUE TITLE
How to create Task under Specific Folder?

### ISSUE THREAD

**Issue by msgoussi** [MicrosoftDocs/windowsserverdocs#6591]
If I want to create a folder "Test" under Task Scheduler Library then create a task inside that folder. The link "https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/schtasks-create" does not show how to do so.

![image](https://user-images.githubusercontent.com/18138496/177933687-cb26c844-dbb9-4c95-bc72-0d188bcb3189.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45b9a61b-38a5-151e-376c-ea2786acf8dd
* Version Independent ID: dd7a38cb-2485-0d03-8441-aa4cca2899cd
* Content: [Command-line syntax key](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/command-line-syntax-key)
* Content Source: [WindowsServerDocs/administration/windows-commands/command-line-syntax-key.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/command-line-syntax-key.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#6625 sign:xelu86

**Comment by Xelu86** [comment]
Hey @msgoussi,



Assuming you want to do this via command-line and not in the GUI as seen below with the example "SCHTASKS /CREATE /SC DAILY /TN "_**BrandNewFolder**_\NotAsFancyTask" /TR "C:\Windows\System32\notepad.exe" /ST 11:50"

![image](https://user-images.githubusercontent.com/103963494/190552863-fc6051b6-5a95-4550-ae6f-b2ed6d677084.png)

When you run the **/tn** switch, place the name of the folder you want to create followed by the task name: /TN "Folder Name\Task Name". This will allow you to separate your own tasks from the built-in system tasks or those created by certain software.

A documentation change has been made to reflect this under the **/tn** switch and will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. 

#please-close
