### ISSUE TITLE
It is not in the PATH so ssh command doesn't work

### ISSUE THREAD

**Issue by bsielski** [MicrosoftDocs/windowsserverdocs#6595]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Get started with OpenSSH](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by robinharwood** [comment]
Hi @bsielski 

Are you able to provide some more detail? SSH should be in the PATH variable if it was installed following our documentation.

Thanks

#assign:robinharwood

**Comment by robinharwood** [comment]
Hi @bsielski,

Just to follow up on this, if this is a documentation issue, leave us a comment with an @mention. To get assistance or support for your product issue, we recommend that you engage with the product community or open a ticket with Microsoft Support. For more information, see [Contact Microsoft Support](https://support.microsoft.com/ContactUs). Closing this issue in the meantime.

Thanks,

Robin
#please-close
