### ISSUE TITLE
Documentation for -exportPFX verb missing?

### ISSUE THREAD

**Issue by cloudgreen** [MicrosoftDocs/windowsserverdocs#6596]
There seems to be no documentation for the **-exportPFX** verb and all its options? It's something I would find useful! :)

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d238db2c-10e1-d418-e780-54b421779754
* Version Independent ID: d1313e31-d990-2f0b-3f70-ae0fcdb4ba5c
* Content: [certutil](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/certutil)
* Content Source: [WindowsServerDocs/administration/windows-commands/certutil.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/certutil.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey cloudgreen,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding several missing parameters from the CertUtil doc and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
