### ISSUE TITLE
Parameter missing

### ISSUE THREAD

**Issue by ahdung** [MicrosoftDocs/windowsserverdocs#6599]
Parameter `/reg:64|32` missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6472b04a-6012-bb34-1d0e-c03fc4504f19
* Version Independent ID: 00f23c12-7136-078f-8708-47380f9872a2
* Content: [reg import](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/reg-import)
* Content Source: [WindowsServerDocs/administration/windows-commands/reg-import.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/reg-import.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @ahdung,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding the missing parameters and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
