### ISSUE TITLE
Memory\Available Mbytes is low

### ISSUE THREAD

**Issue by reuvygroovy** [MicrosoftDocs/windowsserverdocs#6600]
Hi

I don't believe there is a counter called "Memory\Available Mbytes **is low**", but rather just "Memory\Available Mbytes"

![image](https://user-images.githubusercontent.com/1325158/178651671-be1f6660-dd89-4a4d-9ae2-83f53811fbd6.png)

I think the "is low" is a mistake, possibly added because of the next section explaining to look for low values.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fe81add-b285-ff8e-f383-2df80332e722
* Version Independent ID: 4e96ec10-8088-0d77-bc8b-d2197aebf9d9
* Content: [Troubleshoot Cache and Memory Manager Performance Issues](https://docs.microsoft.com/en-us/windows-server/administration/performance-tuning/subsystem/cache-memory-management/troubleshoot)
* Content Source: [WindowsServerDocs/administration/performance-tuning/subsystem/cache-memory-management/troubleshoot.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/performance-tuning/subsystem/cache-memory-management/troubleshoot.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @phstee
* Microsoft Alias: **pavel**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @reuvygroovy,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made, removing this mistype, and will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
