### ISSUE TITLE
Integration System Service Should Running On Hyper-V Host Or Not? Need Clarification.

### ISSUE THREAD

**Issue by Phyktion** [MicrosoftDocs/windowsserverdocs#6604]
[Enter feedback here]
The notation here:

Each service you want to use must be enabled in both the host and guest in order to function. All integration services except Hyper-V Guest Service Interface are on by default on Windows guest operating systems. The services can be turned on and off individually. The next sections show you how.

Does this mean that the System Service should be "Running" on the Hyper-V host?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf5eedca-3535-d00e-98ab-9e25496a30a7
* Version Independent ID: 797c37a7-ccd5-ed59-2dc3-5cf3892bbf3b
* Content: [Manage Hyper-V Integration Services](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/manage-hyper-v-integration-services)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/manage/Manage-Hyper-V-integration-services.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/virtualization/hyper-v/manage/Manage-Hyper-V-integration-services.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by craigcaseyMSFT** [comment]
Hello @Phyktion,

Thanks for contacting Microsoft. We value your feedback.

Documentation changes have been made to clarify and acknowledge this issue. The doc changes will be live after the next business day.

Thank you again and have a most pleasant day.
#please-close
