### ISSUE TITLE
tracert document page should explain the *output* of the command

### ISSUE THREAD

**Issue by heikki-heikkila** [MicrosoftDocs/windowsserverdocs#6605]
The manual page for tracert explains what input the command expects.  However, it does not explain how the user should interpret the output. Conside this example (inside a private corporate network):
```
Tracing route to 172.19.219.42 over a maximum of 9 hops

  1     2 ms     *        2 ms  10.15.8.1
  2     1 ms     1 ms     1 ms  10.15.0.1
  3    18 ms     *        9 ms  10.14.1.33
  4     6 ms     7 ms     6 ms  10.14.1.84
  5     9 ms     9 ms     9 ms  172.19.254.86
  6     6 ms     6 ms     6 ms  172.19.254.66
  7     9 ms     9 ms     9 ms  172.19.219.42

Trace complete.
```
There are several columns.  What do all these columns mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6444fdcc-eab2-9bb3-1b94-34914af628c9
* Version Independent ID: 31345b9a-df7a-8403-7fda-86784646d2c6
* Content: [tracert](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/tracert)
* Content Source: [WindowsServerDocs/administration/windows-commands/tracert.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/tracert.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey heikki-heikkila,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change was made explaining the columns for the `tracert` output and changes are live. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
