### ISSUE TITLE
[BUG] ajax error 400

### ISSUE THREAD

**Issue by gittihub123** [MicrosoftDocs/windowsserverdocs#6607]
Get error code: ajax error 400 when browsing in Windows admin center and making changes in Powershell.

**To Reproduce**
1. Surf to Windows admin center and go to virtual machines.
2. Stay on the site
3. Start doing some virtual machines changes on powershell, for example set-VMMemory and change processor from 2 to 4.

Screenshot 
![image](https://user-images.githubusercontent.com/80075118/178967831-d0f821b3-23dc-481c-afce-5fe25a89be44.png)

![image](https://user-images.githubusercontent.com/80075118/179018461-1e0fdfe0-00bb-460e-b3ea-c16cd36ceba0.png)

**Expected behavior**
Be able to use Windows admin center without getting ajax error 400 when changing the environment in powershell.
Happens about 4-5 times /day.

**Environment (please complete the following information):**
- OS: Azure Stack HCI
- Browser: Edge 
- Version 103.0.1264.49 (Official build) (64-bit)
- Azure stack HCI version 2009 10.0.20348.558

Any inputs regarding this behaviour?

**Comment by gittihub123** [comment]
![image](https://user-images.githubusercontent.com/80075118/179182614-5fae7376-6c21-4dab-8f29-25f60e334db3.png)
Other ajax 400 error.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @gittihub123,

Thanks again for contacting Microsoft. We value your feedback.

As we understand it, you're describing an issue with the product compared to an issue with our documentation. GitHub isn't quite the right location or channel if searching for technical support, deeper specifics of the product or feature requests as it is completely outside our scope. If there are any issues within the content itself, such as incorrect code, verbiage, etc., please let us know.

As the error you're receiving is quite specific, we recommend that you engage with the product community or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).

Additional support forums listed below:
- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Hopefully one of the community experts may be able to better assist. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
