### ISSUE TITLE
Features table does not show Teams optimizations for Mac

### ISSUE THREAD

**Issue by cmcapellan** [MicrosoftDocs/windowsserverdocs#6611]
https://techcommunity.microsoft.com/t5/windows-365/microsoft-teams-media-optimizations-is-now-generally-available/m-p/3563129

Per this announcement, Teams optimizations is now GA for the MacOS client, the Features table needs to be updated please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d746fc6-0121-c9dc-f552-2d53a902922f
* Version Independent ID: a7508e87-b2ac-c474-f168-5af94c250332
* Content: [Remote Desktop clients feature comparison](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-features)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-features.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-features.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by craigcaseyMSFT** [comment]
Hello @cmcapellan,

Thanks for contacting Microsoft. We value your feedback.

We have tested the problem as described in this issue and either couldn't replicate the stated result or have verified that no documentation change is required.

As a result, we’re closing this thread.

Thank you again and have a most pleasant day.
#please-close
