### ISSUE TITLE
Installing OpenSSH needs slightly update for Windows 11

### ISSUE THREAD

**Issue by dmorse76** [MicrosoftDocs/windowsserverdocs#6618]
These instructions currently read:
"Both OpenSSH components can be installed using Windows Settings on Windows Server 2019 and Windows 10 devices.

To install the OpenSSH components:

1.   Open Settings, select Apps > Apps & Features, then select Optional Features."

For Windows 11, this needs to be modified to:

"Both OpenSSH components can be installed using Windows Settings on Windows Server 2019, Windows 10, and Windows 11 devices.

To install the OpenSSH components:

1a.   For Windows 10: Open Settings, select Apps > Apps & Features, then select Optional Features.
1b.   For Windows 11: Open Settings, select Apps, then select Optional Features."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Get started with OpenSSH](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by robinharwood** [comment]
Hi @dmorse76,

Thanks for providing feedback that helps improve our documentation. This issue has been resolved as part of an update on the 29th of July, we are closing the issue. 

Thanks,
Robin

#please-close
