### ISSUE TITLE
Install the Client - Windows64-bit link directs to a file with no extension

### ISSUE THREAD

**Issue by PlottingPanthera** [MicrosoftDocs/windowsserverdocs#6621]
When downloading the Windows 64-bit client via the link on this page, it downloads a file with no extension. The correct extension should be a .MSI. It also downloads with the name "RE518ld", which is unrecognizable.

The link goes to "https://go.microsoft.com/fwlink/?linkid=2068602" which hosts the file - so this may be just an issue with the hosted installer.

Windows 32-bit and Windows ARM64 link with the appropriate extension and properly named installer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ab98fc-fea2-a11a-e5ca-de1430211d97
* Version Independent ID: 4d9943c3-fef7-ca86-bd03-1241a04b8135
* Content: [Get started with the Windows Desktop client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by reeseste** [comment]
To fix this issue, just add ".msi" to the resulting file download. After doing that, I was able to run the file and install the client without any issues.

**Comment by PlottingPanthera** [comment]
> To fix this issue, just add ".msi" to the resulting file download. After doing that, I was able to run the file and install the client without any issues.

Right, so that is a workaround but that is not what this post is for. The installer needs to be corrected so it can be accurately identified and downloaded without the additional modification after download. The other links do not have this issue.  

The fix should be to correct the hosted file with the appropriate File Name and extension - or provide a different software repository that has the appropriately named file.

**Comment by reeseste** [comment]
> > To fix this issue, just add ".msi" to the resulting file download. After doing that, I was able to run the file and install the client without any issues.
> 
> Right, so that is a workaround but that is not what this post is for. The installer needs to be corrected so it can be accurately identified and downloaded without the additional modification after download. The other links do not have this issue.
> 
> The fix should be to correct the hosted file with the appropriate File Name and extension - or provide a different software repository that has the appropriately named file.

I understand this is a workaround. 
Based on other posts with the same issue, Microsoft took some time to fix the problem on the site, so I figured I would recommend a temporary solution so you're able to install the client while waiting on Microsoft to fix this on their end.

**Comment by PlottingPanthera** [comment]
> > > To fix this issue, just add ".msi" to the resulting file download. After doing that, I was able to run the file and install the client without any issues.
> > 
> > 
> > Right, so that is a workaround but that is not what this post is for. The installer needs to be corrected so it can be accurately identified and downloaded without the additional modification after download. The other links do not have this issue.
> > The fix should be to correct the hosted file with the appropriate File Name and extension - or provide a different software repository that has the appropriately named file.
> 
> I understand this is a workaround. Based on other posts with the same issue, Microsoft took some time to fix the problem on the site, so I figured I would recommend a temporary solution so you're able to install the client while waiting on Microsoft to fix this on their end.

Of course, perfectly fine and thank you for that. Until then, we need to ensure that this gets the required attention.

**Comment by Xelu86** [comment]
Hey @PlottingPanthera,

Thanks again for contacting Microsoft. We value your feedback. We'd also like to thank @reeseste for the temporary workaround whilst the team updated this documentation for better accuracy.

The hyperlink to the 64-bit client has been updated to reflect the correct changes and is live. We will be closing this thread as resolved. Thank you and have a most pleasant day. #please-close
