### ISSUE TITLE
Download Link for Remote Desktop Client 64-Bit is not functioning properly

### ISSUE THREAD

**Issue by RyanHuber75214** [MicrosoftDocs/windowsserverdocs#6626]
The download link for Remote Desktop Client 64-Bit just downloads a file called "RES518Id" with no extension. The file appears to be a binary. The link displayed is:
https://go.microsoft.com/fwlink/?linkid=2068602

Thanks!
Ryan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ab98fc-fea2-a11a-e5ca-de1430211d97
* Version Independent ID: 4d9943c3-fef7-ca86-bd03-1241a04b8135
* Content: [Get started with the Windows Desktop client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by reeseste** [comment]
To fix this issue, just add ".msi" to the resulting file download. After doing that, I was able to run the file and install the client without any issues.

**Comment by RyanHuber75214** [comment]
> 

Thanks, reeseste! That worked for me!

Ryan

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @RyanHuber75214, 

Thanks again for contacting Microsoft. We value your feedback. We'd also like to thank @reeseste for providing a temporary workaround whilst the team worked on updating this documentation.

The hyperlink to the 64-bit client has been updated to reflect the correct changes and is live. We will be closing this thread as resolved. Thank you and have a most pleasant day. #please-close
