### ISSUE TITLE
Netsh Technical Reference link is broken

### ISSUE THREAD

**Issue by voidbar** [MicrosoftDocs/windowsserverdocs#6629]
[Enter feedback here]

The link in the bottom of the page to [Netsh Technical Reference](https://gallery.technet.microsoft.com/Netsh-Technical-Reference-c46523dc) is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdf15d6d-c63e-6ec4-d1c0-bb800eec7f12
* Version Independent ID: 595b6b57-f169-e38d-35d7-91eaa3b33610
* Content: [Network Shell (Netsh)](https://docs.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh)
* Content Source: [WindowsServerDocs/networking/technologies/netsh/netsh.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/networking/technologies/netsh/netsh.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @voidbar,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made to redirect users to our [netsh command reference](https://learn.microsoft.com/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc754516(v=ws.10)) as the other resource is no longer available. Changes will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
