### ISSUE TITLE
64 bit installer does not download properly

### ISSUE THREAD

**Issue by nckelwd** [MicrosoftDocs/windowsserverdocs#6630]
The link for the 64 bit installer does not route correctly, and only downloads a "file" called RE518ld
32 bit installer correctly downloads msi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ab98fc-fea2-a11a-e5ca-de1430211d97
* Version Independent ID: 4d9943c3-fef7-ca86-bd03-1241a04b8135
* Content: [Get started with the Windows Desktop client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @nckelwd,

Thanks again for contacting Microsoft. We value your feedback. The hyperlink to the 64-bit client has been updated to reflect the correct changes and is live. We will be closing this thread as resolved. Thank you and have a most pleasant day. #please-close
