### ISSUE TITLE
Does Windows Admin Center support Windows Server 2012 R2 ?

### ISSUE THREAD

**Issue by yoshihirok** [MicrosoftDocs/windowsserverdocs#664]
How can I install the Windows Admin Center to Windows Server 2012 R2 ?
Now, Installer show that it does not support on my server.
PowerShell version is 5.1 on my server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe84fb4b-3420-bc1e-6a1d-b64ecc56fc5e
* Version Independent ID: f089767e-4613-d595-a0ee-0dab012724a1
* Content: [Install Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/install#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/deploy/install.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/deploy/install.md)
* Service: **unspecified**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by lizap** [comment]
You can manage WS 2012R2 using Windows Admin Center, but no, you can't install WAC on WS2012R2. If you want to manage WS2012R2, you have to add WMF 5.1, as described here: https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/prepare-environment#prepare-windows-server-2012-and-2012-r2

**Comment by yoshihirok** [comment]
$PSVersiontable off PowerShell is 5.1, on my Windows Server 2012 R2 server.

```
Name                           Value                                                                                                          
----                           -----                                                                                                          
PSVersion                      5.1.14409.1012                                                                                                 
PSEdition                      Desktop                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                        
BuildVersion                   10.0.14409.1012                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                
WSManStackVersion              3.0                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                            
SerializationVersion           1.1.0.1   
```

**Comment by salroyal** [comment]
When will Windows Admin Center work with 1803?

**Comment by 101script** [comment]
Developers in Microsoft, does not know if Windows Admin Center can be installed on server 2008 or 2012, he write text like monkeys :), so official documentation wrote with errors, and some time is not fully, or updated! i tried to install and cannot, install wac,,i have latest version of ps (5.1)
