### ISSUE TITLE
The "NTPServer entries" under "Windows registry reference" are wrong

### ISSUE THREAD

**Issue by occasionallydennis** [MicrosoftDocs/windowsserverdocs#6646]
All the descriptions and values look like they are copies from the "NTPClient entries", nothing like the default keys should be:
![image](https://user-images.githubusercontent.com/50244937/183951129-d13782f3-8ffc-4753-84a1-8494b8e5c5ed.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d09b16e-4bbb-91fa-3d84-e7623ec4dc07
* Version Independent ID: b6eadad5-0167-34b6-ed3a-16fa7ee83c60
* Content: [Windows Time service tools and settings](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings)
* Content Source: [WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @v-tappelgate
* Microsoft Alias: **v-tappelgate**

**Comment by Xelu86** [comment]
Hey occasionallydennis,

Thanks again for contacting Microsoft. We value your feedback. 

The W32Time doc is going through an update, including the 4 sections surrounding the registry entries. Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
