### ISSUE TITLE
Why are /autocleanstoragesense /autoclean options not explained?

### ISSUE THREAD

**Issue by Joachim-Otahal** [MicrosoftDocs/windowsserverdocs#6648]
The page is incomplete. Folling options are not explained:
/autocleanstoragesense
/autoclean

BTW: /autoclean is undocumented since Vista! I want the MS-DOS 5.0 level of documentation back. That book was over 700 pages and indeed was worth to be called "documentation".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 768ab539-031f-b493-edc9-2958ced20fc2
* Version Independent ID: cab3aa07-fc05-1a74-875b-fd37983593d4
* Content: [cleanmgr](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cleanmgr)
* Content Source: [WindowsServerDocs/administration/windows-commands/cleanmgr.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/cleanmgr.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by craigcaseyMSFT** [comment]
Hello @Joachim-Otahal,

Thanks for contacting Microsoft. We value your feedback.

Documentation changes have been made to clarify and acknowledge this issue. The doc changes will be live after the next business day.

Thank you again and have a most pleasant day.
#please-close
