### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by ppfortes** [MicrosoftDocs/windowsserverdocs#665]
Hi, in the example URI, I see "mypc:3389". Is mypc the name of the connection in the app (using mac os x)? Is 3389 the connection port?
I'm able to connect but the machine refuses the connection. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9effefa0-ac98-1fdd-6174-f06d524622f5
* Version Independent ID: 5d405e1c-d2eb-9c72-3cf6-817930cad4f6
* Content: [Remote Desktop clients URI scheme](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-uri#feedback)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-uri.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-uri.md)
* Service: **unspecified**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by lizap** [comment]
In that example, "mypc" is the name of the computer you want to connect to. I'll update the example to make that more clear. And yes, 3389 is the port to use.

**Comment by ppfortes** [comment]
Any ideas on the reason why I'm able to connect through the app but not using the URI whilst it looks I'm reaching the machine and it later refuses the connection?

**Comment by lizap** [comment]
Are you trying to connect to a Windows machine, by any chance?

**Comment by lizap** [comment]
You can only use the URI with Mac, iOS, and Android clients.
