### ISSUE TITLE
Where?

### ISSUE THREAD

**Issue by MikeWise2718** [MicrosoftDocs/windowsserverdocs#6651]
So where is the windows drive in Ubuntu? Seems to be missing from this article, and it is fairly useless withouth knowing that. I looked under /mnt and saw nothing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55dae836-2730-7a91-b162-cd154557d0fd
* Version Independent ID: 69c4c00c-f3e6-9710-28fe-6ecdc7731c65
* Content: [Use local resources on Hyper-V virtual machine with VMConnect](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/learn-more/use-local-resources-on-hyper-v-virtual-machine-with-vmconnect)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/learn-more/Use-local-resources-on-Hyper-V-virtual-machine-with-VMConnect.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/virtualization/hyper-v/learn-more/Use-local-resources-on-Hyper-V-virtual-machine-with-VMConnect.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @MikeWise2718,

Thanks again for contacting Microsoft. We value your feedback. 

If **Enhanced Session** is enabled in your Hyper-V instance, the locally shared drive path is **/home/shared-drives**.

Please see my VM session below:

![image](https://user-images.githubusercontent.com/103963494/219506864-452f0482-3d87-4344-beec-6f56b23c1c7c.png)

![image](https://user-images.githubusercontent.com/103963494/219506940-3015a722-0348-4b54-8c3f-999211c09ce3.png)

![image](https://user-images.githubusercontent.com/103963494/219507213-b1d2a8dc-966b-4d92-a717-f783193e86da.png)

A documentation change has been made addressing the shared drive location in the VM environment and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
