### ISSUE TITLE
Help meta thrive

### ISSUE THREAD

**Issue by ItsKylieCyrus** [MicrosoftDocs/windowsserverdocs#6653]

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @ItsKylieCyrus, 

Thanks again for contacting Microsoft. We value your feedback. 

We're unable to determine what the intent of your question is. If there are any errors or areas of improvement with said documentation, please let us know so we may better assist.

We're closing this issue but please feel free to reopen it and advise us what revisions may be needed. Thank you and have a most pleasant day. #please-close
