### ISSUE TITLE
Bad link to 10 Immutable Laws of Security

### ISSUE THREAD

**Issue by JimSycurity** [MicrosoftDocs/windowsserverdocs#6659]
The link after Law Number Three that is intended to direct to the Ten Immutable Laws of Security (Version 2.0) is a bad link that ends up just going to MSRC.  I believe the 10 Immutable Laws of Security blog post was an old TechNet post and has been archived somewhere?  I'm sad and maybe even a little big angry at how so many TechNet posts got archived and lost their perma-links, but holy smokes the 10 Immutable Laws of Security post should have stayed up at an immutable permalink for crying out loud!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca929d6b-746d-f20a-8902-4e93a69ab8d8
* Version Independent ID: 88e13a93-f80b-d07b-cfaa-ab38205148e0
* Content: [Securing Domain Controllers Against Attack](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/securing-domain-controllers-against-attack)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Securing-Domain-Controllers-Against-Attack.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Securing-Domain-Controllers-Against-Attack.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
Thanks @JimSycurity 

I have sent a note out to see if we can find a good place to publish/update the info. 

#please-close
