### ISSUE TITLE
Incorrect statement

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/windowsserverdocs#666]
The statement that reads as follows: "Preferably, this is the password of the built-in Administrator account, which must not be disabled." is not correct.  Please read this document https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/implementing-least-privilege-administrative-models
and look for the sentences that reads as follows: "If the Administrator account is not already disabled, disable it when you have completed configuration of the account's properties. This prevents the account from being used for any purpose unless it is first enabled. In a disaster recovery scenario in which no accounts are available to perform repairs of the AD DS environment, you can boot a domain controller into safe mode, log on locally with the built-in Administrator account (which is never blocked from local logon), and enable the domain's Administrator account, if necessary."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0588c9d4-0323-08a7-5bd0-cf0143e8cee5
* Version Independent ID: 5e206583-e925-75b5-f93f-e24ab8ac8789
* Content: [AD Forest Recovery - Determine how to recover the forest](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/ad-forest-recovery-determine-how-to-recover)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/AD-Forest-Recovery-Determine-how-to-Recover.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/manage/AD-Forest-Recovery-Determine-how-to-Recover.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Justinha** [comment]
@poortom1004 Thanks for the feedback. Could just be me, but the way I read it, they are saying the same thing. The forest recovery doc is saying you will need a Domain Admin account in each domain you want to recover, and to get that you will need to enable the Built-in Administrator account (if it's been disabled). Would it help if we changed "which must not be disabled" to "which you may need to enable"?

**Comment by poortom1004** [comment]
Yep that would make sense

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Justinha** [comment]
And thanks for the link to the sec guide. Maybe this would be more consistent with the sec guide if we just remove it? I submitted a commit for that. We also encourage pull requests for revisions. Thanks for improving the docs.
