### ISSUE TITLE
Windows 11 NFS client versions

### ISSUE THREAD

**Issue by qysnn** [MicrosoftDocs/windowsserverdocs#6661]
In current "Network File System overview", there is no information about Windows 11 NFS client versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20741e00-6d40-c122-88b2-562b38d39b1e
* Version Independent ID: e556fb83-dc86-94ed-d0e0-616a6499c1e8
* Content: [Network File System overview](https://docs.microsoft.com/en-us/windows-server/storage/nfs/nfs-overview)
* Content Source: [WindowsServerDocs/storage/nfs/nfs-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/nfs/nfs-overview.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @qysnn,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding Win 11 to the supported OS list and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
