### ISSUE TITLE
Robocopy page NOTE should change to equal to or greater than 8

### ISSUE THREAD

**Issue by clairestreb** [MicrosoftDocs/windowsserverdocs#6662]
The lowest table on the page contains: 8   |  Several files did not copy.
So 8 means there was an error.
Therefore, the NOTE under the table that says: Any value greater than 8 indicates that there was at least one failure during the copy operation.
should be changed to: Any value equal to or greater than 8 indicates that there was at least one failure during the copy operation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @clairestreb,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made surrounding the note field for better accuracy and will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. 

#please-close
