### ISSUE TITLE
Current store app version is 10.2.3000.0 but most recent update is 10.2.1810

### ISSUE THREAD

**Issue by marknoble** [MicrosoftDocs/windowsserverdocs#6665]
Could someone update this page with a summary of fixes and enhancements since 10.2.1810?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67b7b5a4-647e-fee3-6533-6ed88ae45bfa
* Version Independent ID: d9102859-0147-346f-8268-6e2a75c8b0b7
* Content: [What's new in the Microsoft Store client](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windows-whatsnew)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windows-whatsnew.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/windows-whatsnew.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by tamoanxx** [comment]
This is an issue for me as well.

**Comment by Xelu86** [comment]
Hey marknoble,

Thanks again for contacting Microsoft, we value your feedback. 

Based on the time this issue was created, a documentation update was made, and this issue was not closed. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
