### ISSUE TITLE
support dates do not agree

### ISSUE THREAD

**Issue by maynard517** [MicrosoftDocs/windowsserverdocs#6666]
The end of extended support for Windows Server 2008 and 2008 R2 are reported as both January 2020 and January 2023.  The extended support dates for Windows 2012 have similar issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23b0ff5c-e77e-6cf1-5a0e-86a62908d73d
* Version Independent ID: e58c39e4-dc33-3639-14e7-a970a214b0ed
* Content: [Overview of Extended Security Updates for Windows Server 2008, 2008 R2, 2012, and 2012 R2](https://docs.microsoft.com/en-us/windows-server/get-started/extended-security-updates-overview)
* Content Source: [WindowsServerDocs/get-started/extended-security-updates-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/extended-security-updates-overview.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @dknappettmsft
* Microsoft Alias: **daknappe**

**Comment by Xelu86** [comment]
Hey maynard517,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change was made correcting the dates in question and this issue was not closed. Changes have been live. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
