### ISSUE TITLE
Explain what "LIS" is.

### ISSUE THREAD

**Issue by debuglevel** [MicrosoftDocs/windowsserverdocs#6669]
The page states "LIS" several times without explaining what this is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84d52296-198d-7c8a-db99-e8cb336e355f
* Version Independent ID: 77670399-109f-3233-0466-c13d84542039
* Content: [Supported Ubuntu virtual machines on Hyper-V](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-ubuntu-virtual-machines-on-hyper-v)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Supported-Ubuntu-virtual-machines-on-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/virtualization/hyper-v/Supported-Ubuntu-virtual-machines-on-Hyper-V.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by Xelu86** [comment]
Hey @debuglevel,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made in expanding the LIS (Linux Integration Services) acronym and will be live after the next business day. Certain information on our products have their own dedicated page so If you'd like to learn more about what hardware services can be virtualized for Hyper-V. please see our [Hyper-V Integration Services](https://learn.microsoft.com/en-us/virtualization/hyper-v-on-windows/reference/integration-services) page. 

We also have these resources:
- [Which Linux Integration Services should I use in my Linux VMs?](https://techcommunity.microsoft.com/t5/virtualization/which-linux-integration-services-should-i-use-in-my-linux-vms/ba-p/382304)
- [Linux Integration Services 4.1](https://learn.microsoft.com/en-us/virtualization/community/team-blog/2016/20160321-linux-integration-services-4-1) (a quick read in case you wanted more information)

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
