### ISSUE TITLE
Add information on Ubuntu 22.04

### ISSUE THREAD

**Issue by debuglevel** [MicrosoftDocs/windowsserverdocs#6670]
The table lacks information on Ubuntu 22.04 LTS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84d52296-198d-7c8a-db99-e8cb336e355f
* Version Independent ID: 77670399-109f-3233-0466-c13d84542039
* Content: [Supported Ubuntu virtual machines on Hyper-V](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-ubuntu-virtual-machines-on-hyper-v)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Supported-Ubuntu-virtual-machines-on-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/virtualization/hyper-v/Supported-Ubuntu-virtual-machines-on-Hyper-V.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by Xelu86** [comment]
Hey debuglevel,

Thanks again for contacting Microsoft. We value your feedback. 

Ubuntu 22.04 LTS was added into the table to this documentation a while ago and this issue was left open. We're now closing this thread. 

Thank you and have a most pleasant day. 
#please-close
