### ISSUE TITLE
Boot mode for authorative restaore

### ISSUE THREAD

**Issue by ngoug** [MicrosoftDocs/windowsserverdocs#6674]
[Hello,

Is the server need to start in DSRM to perform this change attribute?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b32b0d7e-d4e1-1314-dda9-1231519bfbd7
* Version Independent ID: 91ccaa87-c3ef-2a38-1417-de11583cdbc5
* Content: [AD Forest Recovery - Authoritative sync of SYSVOL](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/ad-forest-recovery-authoritative-recovery-sysvol)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/AD-Forest-Recovery-Authoritative-Recovery-SYSVOL.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-ds/manage/AD-Forest-Recovery-Authoritative-Recovery-SYSVOL.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by IngridAtMicrosoft** [comment]
Hello @ngoug,
The answer to your question is no.
