### ISSUE TITLE
Bullet point links are broken.

### ISSUE THREAD

**Issue by BlakeMsft** [MicrosoftDocs/windowsserverdocs#6679]
The bullet point links are all broken.  Please fix this as we in CSS use these as reference and provide to our customers.

[Enable the interface](https://docs.microsoft.com/en-us/windows/threat-protection/windows-defender-antivirus/windows-defender-antivirus-on-windows-server-2016#BKMK_UsingDef)

[Verify Windows Defender AV is running](https://docs.microsoft.com/en-us/windows/threat-protection/windows-defender-antivirus/windows-defender-antivirus-on-windows-server-2016#BKMK_DefRun)

[Update antimalware definitions](https://docs.microsoft.com/en-us/windows/threat-protection/windows-defender-antivirus/windows-defender-antivirus-on-windows-server-2016#BKMK_UpdateDef)

[Submit Samples](https://docs.microsoft.com/en-us/windows/threat-protection/windows-defender-antivirus/windows-defender-antivirus-on-windows-server-2016#BKMK_DefSamples)

[Configure automatic exclusions](https://docs.microsoft.com/en-us/windows/threat-protection/windows-defender-antivirus/windows-defender-antivirus-on-windows-server-2016#BKMK_DefExclusions)

Thank you,
Blakemo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfee81e6-dba5-cbd6-4190-3b3aa3fd5f94
* Version Independent ID: ad63832b-7b61-01c2-83f8-11a446ddfbb7
* Content: [Windows Defender Overview for Windows Server](https://docs.microsoft.com/en-us/windows-server/security/windows-defender/windows-defender-overview-windows-server)
* Content Source: [WindowsServerDocs/security/windows-defender/windows-defender-overview-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/security/windows-defender/windows-defender-overview-windows-server.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @BlakeMsft,


All hyperlinks have been updated with new content to better serve our customer needs. The following link encompasses the 5 previous hyperlinks into 1 article:

https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-on-windows-server

Changes to the main article will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
