### ISSUE TITLE
Unable to get VPN_PROFILE.PS1 to generate VPN

### ISSUE THREAD

**Issue by DiPersiaTech** [MicrosoftDocs/windowsserverdocs#668]
This is on version 1709 using user authentication. Made our template VPN, which connects fine. Ran MakeProfile.ps1 fine and it generated the VPN_Profile.XML and PS1 files. We're use Powershell; VPN_Profile.PS1 looks fine to this untrained eye.

When we run it, locally, as an admin of the machine, running Powershell as admin with execution policy set to bypass, we get this error from the script -

"Unable to create AlwaysOn VPN profile: A general error occurred that is not covered by a more specific error code."

I commented out all of the error catching and found the error is the following line -
 $session.CreateInstance($namespaceName, $newInstance, $options)

I looked at each of the variables being passed to the createinstance and all seem fine. I'm attached their output here in vars.txt.

I've also attached the vpn_profile.ps1 (as a text file.)

Any thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7453068-95eb-2a42-fd0b-553ae593adb0
* Version Independent ID: b39b2cb7-25b1-2af3-4954-dbcc04c836e9
* Content: [Configure Windows 10 Client Always On VPN Connections](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md)
* Service: **unspecified**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by DiPersiaTech** [comment]
[Vars.txt](https://github.com/MicrosoftDocs/windowsserverdocs/files/1932701/Vars.txt)
[VPN_Profile.txt](https://github.com/MicrosoftDocs/windowsserverdocs/files/1932702/VPN_Profile.txt)

**Comment by shortpatti** [comment]
@DiPersiaTech, I'll consult with the main engineer on this and will let you know of the outcome :)

**Comment by shortpatti** [comment]
@DiPersiaTech, I have the engineering team working on providing more details. :)

**Comment by shortpatti** [comment]
@DiPersiaTech, Sorry for the delay. 

The problem is that AlwaysOn tag needs to be set to True, with a capital T.

<AlwaysOn>True</AlwaysOn>

Let me know if that works :)

**Comment by scerazy** [comment]
NOT a solution, bit T little t, none makes ANY difference at all!
Have situation same like here - https://www.hayesjupe.com/always-on-vpn-technical-follow-up/

**Comment by bryhall** [comment]
I have AlwaysOn set to **true** (lowercase) and it does work.  However I have other issues such as:

- Neither user nor device tunnel register the tunnel IP addresses, they only register the physical NIC's address.  I've tried both <RegisterDNS>true</RegisterDNS> and the capital True.  So, DNS registration is obviously working, but it's the wrong IP address.
- AlwaysOn does not always connect/reconnect automatically.  It sometimes requires that the user initiate the tunnel.

This occurs for us on 1709 and 1803

**Comment by frasercarter** [comment]
Great going guys, seriously no update to this? why bother rolling out an enterprise feature if it's not able to be deployed to the enterprise...
