### ISSUE TITLE
No domain join button on Windows 10 Pro

### ISSUE THREAD

**Issue by spyderdyne** [MicrosoftDocs/windowsserverdocs#6693]
Edition	Windows 10 Pro
Version	21H2
Installed on	‎8/‎25/‎2022
OS build	19044.1889
Experience	Windows Feature Experience Pack 120.2212.4180.0

AzureVM cannot join the domain because there is nowhere to add it to one.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3331f737-d4d5-8b05-e5e2-57ba67903f6b
* Version Independent ID: 33e0848c-3070-2367-8d21-28f3e05f5850
* Content: [Join a Computer to a Domain](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/join-a-computer-to-a-domain)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Join-a-Computer-to-a-Domain.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/deployment/Join-a-Computer-to-a-Domain.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @spyderdyne,

Thanks again for contacting Microsoft. We value your feedback.

We do have this resource surrounding how to join Azure VMs to a domain in our Azure documentation below:
[https://learn.microsoft.com/en-us/azure/active-directory-domain-services/join-windows-vm](https://learn.microsoft.com/en-us/azure/active-directory-domain-services/join-windows-vm)

If you're experiencing any issue with the documentation above to where it does not lead you to a solution, we recommend that you engage with the product community or open a ticket with Microsoft Support. For more information, see [Contact Microsoft Support](https://support.microsoft.com/ContactUs).

Additional Tech Support forums below:

- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/ 

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
