### ISSUE TITLE
shutdown: Possible wrong description of /h

### ISSUE THREAD

**Issue by DazzyWalkman** [MicrosoftDocs/windowsserverdocs#6695]
The description: 

You can use /h **only** with /f.

The behavior and help option output of shutdown command suggest it shoud be:

Can be used with the /f option.

Tested on Windows Server 2008 R2 and Windows Server 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2770335e-d15c-6389-36b9-d687b7794b92
* Version Independent ID: 319c885a-1c12-595f-8018-c563945afe93
* Content: [shutdown](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/shutdown)
* Content Source: [WindowsServerDocs/administration/windows-commands/shutdown.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/shutdown.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @DazzyWalkman,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made surrounding the **/h** switch and will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. 

#please-close
