### ISSUE TITLE
Can you define what Password is the command asking for?

### ISSUE THREAD

**Issue by info-vemanti** [MicrosoftDocs/windowsserverdocs#6699]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a504df6-57a1-96a8-e00b-971fd9a3ed0b
* Version Independent ID: a9fe4704-fc82-2eca-cfc2-981e805e73a6
* Content: [manage-bde unlock](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/manage-bde-unlock)
* Content Source: [WindowsServerDocs/administration/windows-commands/manage-bde-unlock.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/manage-bde-unlock.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @info-vemanti, 

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made clarifying this in the description & an example at the bottom of the page. This is the password that you yourself or an admin has set to any of the drives where encryption is needed:

![image](https://user-images.githubusercontent.com/103963494/196545329-fb311759-eb7b-4903-b075-5fcb6b38d8b1.png)

![image](https://user-images.githubusercontent.com/103963494/196545513-9147de86-712c-4915-88dc-ea70b5a3c7a6.png)

Changes will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. #please-close
