### ISSUE TITLE
Delete second deleted in description of "dfsrmig /deleterontfrsmember contoso-dc2"

### ISSUE THREAD

**Issue by rcbro** [MicrosoftDocs/windowsserverdocs#6700]
To delete the global AD DS settings for FRS replication for a read-only domain controller named contoso-dc2 if those settings were not deleted automatically deleted by the migration process, type:

should be 

To delete the global AD DS settings for FRS replication for a read-only domain controller named contoso-dc2 if those settings were not deleted automatically by the migration process, type:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b39d577-4c79-3dbd-bf5e-4b1bf551f73e
* Version Independent ID: 4bead400-5af7-bd08-5bfe-8297cbc8dd85
* Content: [dfsrmig](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/dfsrmig)
* Content Source: [WindowsServerDocs/administration/windows-commands/dfsrmig.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/dfsrmig.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @rcbro, 

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made removing the duplicate wording and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
