### ISSUE TITLE
extra "S"

### ISSUE THREAD

**Issue by fedesoundsystem** [MicrosoftDocs/windowsserverdocs#6704]
[Enter feedback here]
There's an extra "S" on the sentence Use the following steps to add another RD Sesssion Host to your deployment:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc57542-d28d-f0f5-8baa-bf439c8a1b04
* Version Independent ID: 36a9dd84-5284-5cfd-2366-546c978b1852
* Content: [Scale out your RDS deployment by adding an RD Session Host farm](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-scale-rdsh-farm)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-scale-rdsh-farm.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/rds-scale-rdsh-farm.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by Xelu86** [comment]
#assing:xelu86

**Comment by Xelu86** [comment]
Hey @fedesoundsystem,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting grammar issues within and changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
