### ISSUE TITLE
Administrator 

### ISSUE THREAD

**Issue by ajsjhddj** [MicrosoftDocs/windowsserverdocs#6705]
I net a free rdp
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a02d662-56db-4efc-52d4-61689541f632
* Version Independent ID: f8692043-d888-09d3-1bf3-bff51ae20e34
* Content: [Install RDS client access licenses](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-install-cals?source=recommendations)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-install-cals.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/rds-install-cals.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by Xelu86** [comment]
User feedback is undeterminable. Closing thread.
#please-close

**Comment by Xelu86** [comment]
#assign:xelu86
