### ISSUE TITLE
Page is missing the ECDH registry settings

### ISSUE THREAD

**Issue by ToddMaxey** [MicrosoftDocs/windowsserverdocs#6717]
**Page is missing the ECDH registry settings for enabling the key exchange and setting the key exchange bit length.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd180142-4c19-8abc-ecce-e4c7e5ac8951
* Version Independent ID: fc5bba87-afad-1729-8f7e-333c73188b73
* Content: [Transport Layer Security (TLS) registry settings](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by PatAltimore** [comment]
#assign:Xelu86 I don't know if you can help with this.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @ToddMaxey,

Thanks again for contacting Microsoft. We value your feedback. 

Looking at the documentation, ECDH registry settings are covered under the [KeyExchangeAlgorithm - Diffie-Hellman key sizes](https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings#keyexchangealgorithm---diffie-hellman-key-sizes) section with minimum and maximum bit lengths used.

Is this what you're referring to?

**Comment by ToddMaxey** [comment]
Here is what is missing.... (From my personal OneNote)

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\KeyExchangeAlgorithms\**ECDH**]
"Enabled "=dword:ffffffff
"ClientMinKeyBitLength"=dword:[00000800][00000C00][00001000] <Choose one of the three assure the Diffie-Hellman, ECDH and RSA key length is the same for consistency>
"ServerMinKeyBitLength"=dword:[00000800][00000C00][00001000] <Choose one of the three assure the Diffie-Hellman, ECDH and RSA key length is the same for consistency>

**Comment by ToddMaxey** [comment]
Greeting @Xelu86 
BTW, I do not see the ECDH registry settings in the document you referenced. I see Diffie-Hellman but not ECDH. These are not the same. ECDH is a difference implementation of DH and has separate registry settings.

**Comment by Xelu86** [comment]
Hey @ToddMaxey,

Will be updating this documentation this week and provide an update once changes are made.

**Comment by Xelu86** [comment]
Hey @ToddMaxey,

All additions to this documentation have been updated per our conversation and should be live by the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
