### ISSUE TITLE
what

### ISSUE THREAD

**Issue by wawanwanta** [MicrosoftDocs/windowsserverdocs#6718]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf5bf65b-0725-ce75-22a3-1b902008187e
* Version Independent ID: fc6b8570-983c-b25d-a8fd-29685bc17153
* Content: [date](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/date)
* Content Source: [WindowsServerDocs/administration/windows-commands/date.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/date.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
User feedback is undeterminable. Closing thread.
#please-close
