### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by churstz** [MicrosoftDocs/windowsserverdocs#672]
The text "Replace both occurrences" needs to be reworded as the two changes are independently identified.
The text "Uri redirectUri = new Uri(Request.Url.GetLeftPart(UriPartial.Authority.ToString());" should instead be "Uri redirectUri = new Uri(Request.Url.GetLeftPart(UriPartial.Authority).ToString());"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29422078-e443-7a9a-7342-ca6915e4ffaa
* Version Independent ID: f19ea02c-4bbc-7b65-78c3-b8613a8154e5
* Content: [Build a server side application using OAuth confidential clients with AD FS 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/enabling-oauth-confidential-clients-with-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/enabling-oauth-confidential-clients-with-ad-fs.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/enabling-oauth-confidential-clients-with-ad-fs.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Already resolved in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/a3327343c37abb70e5f68d31fc3c2c0d65aa59cb (first file).

**Comment by illfated** [comment]
#please-close
