### ISSUE TITLE
Missing /reg parameter over the entire Reg documentation

### ISSUE THREAD

**Issue by julianxhokaxhiu** [MicrosoftDocs/windowsserverdocs#6721]
I was reading this page for documentation purposes and I found out all commands are missing the `/reg` parameter description which is very important if you want to edit 32 bit registry keys on 64 bit machines.

Docs:
![image](https://user-images.githubusercontent.com/1237070/189524926-a8fb8dc9-9526-45f8-b656-4bfa05286c63.png)

CLI:
![image](https://user-images.githubusercontent.com/1237070/189524930-e3347508-c42c-4fd4-a153-a494e4cc97e4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd817f1d-e494-af38-4a10-86360d63c195
* Version Independent ID: 11fcbf91-6c28-9ae8-045a-35ea97444dfe
* Content: [reg add](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/reg-add)
* Content Source: [WindowsServerDocs/administration/windows-commands/reg-add.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/reg-add.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by JavierSan9** [comment]
#5640

**Comment by Xelu86** [comment]
Hey julianxhokaxhiu,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding both `/reg:32` & `/reg:64` parameters and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
