### ISSUE TITLE
WAC installation error (with Spanish language)

### ISSUE THREAD

**Issue by ramonromancastro** [MicrosoftDocs/windowsserverdocs#6722]
When i try to install WAC on Windows systems with Spanish language, next error message is showed:

"Error applying transforms. Verify that the specified transform paths are valid."

WindowsAdminCenter2110.2.msi /log debug.log returns:

```
DEBUG:_ Error 2203:  Database: 3082. Cannot open database file. System error -2147287038
1: 2203 2: 3082 3: -2147287038 
Error al aplicar las transformaciones. Compruebe que las rutas de las transformaciones especificadas son válidas.
3082
MSI (c) (74:C0) [13:14:46:464]: Product: Windows Admin Center -- Installation failed.

MSI (c) (74:C0) [13:14:46:464]: Windows Installer installed the product. Product Name: Windows Admin Center. Product Version: 1.3.53858.0. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 1624.
```

On Windows systems with English language, installation is ok.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @ramonromancastro,

Thanks again for contacting Microsoft. We value your feedback.

As we understand it, you're describing an issue with a product compared to an issue with our documentation. GitHub isn't quite the right location or channel if searching for technical support, deeper specifics of the product or feature requests as it is completely outside our scope. If there are any issues within the content itself, such as incorrect code, verbiage, etc., please let us know.

As the error you're receiving is quite specific, we recommend that you engage with the product community or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).

Additional support forums listed below:
- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Hopefully one of the community experts may be able to better assist. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
