### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by JDCNS** [MicrosoftDocs/windowsserverdocs#6723]
[Enter feedback here]
Entering the query command as listed results in:

schtasks : ERROR: Invalid argument/option - 'query'.
    + CategoryInfo          : NotSpecified: (ERROR: Invalid ...tion - 'query'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Type "SCHTASKS /QUERY /?" for usage.

From the above, you will note the '/' before 'query'. The correct command is
schtasks /query

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 017089b7-e7fe-f1d8-854f-91d1619164b6
* Version Independent ID: 766063ce-6e31-fa5f-da41-27b75ecec05d
* Content: [schtasks commands](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/schtasks)
* Content Source: [WindowsServerDocs/administration/windows-commands/schtasks.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/schtasks.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey @JDCNS,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting the syntax on this page and will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
