### ISSUE TITLE
Microsoft remote desktop fails where old mstsc works fine

### ISSUE THREAD

**Issue by raikoug** [MicrosoftDocs/windowsserverdocs#6726]
I'm trying to migrate my remote connections to the new Microsoft Remote Desktop App from MS Store.  

My RDP connections works perfectly with the mstsc client, but fails with the new APP.  
I've some VM on vmware, attached to a HostOnly network (the default VMnet1, with network address in 192.168.72.0/24), I have a virtual NIC with 192.168.72.1 that let me connect to these machines. As I said, _I can connect to them, ping them, use the services running on each of them_.  
The result of Test-NetConnection:
```
Test-NetConnection -ComputerName "192.168.72.100" -CommonTCPPort "RDP" -InformationLevel "Detailed"

ComputerName            : 192.168.72.100
RemoteAddress           : 192.168.72.100
RemotePort              : 3389
NameResolutionResults   : 192.168.72.100
MatchingIPsecRules      :
NetworkIsolationContext : Internet
InterfaceAlias          : VMware Network Adapter VMnet1
SourceAddress           : 192.168.72.1
NetRoute (NextHop)      : 0.0.0.0
TcpTestSucceeded        : True
```

On the Remote Desktop APP, simply adding the new VM and trying to connect I receive an instantaneous error:
```
Error code: 0x4 
Extended error code: 0x0 
Activity ID: {9078ef5c-661c-48f0-b401-1c48db150000}
```
I tried adding a Gateway (and, please, what should be the account for the gateway?) and used the ip of the Virtual NIC (192.168.72.1) as in the Test NetConnection result. In this case the connections fails after a bit of thinking:
```
Error code: 0x50331742 
Extended error code: 0x0 
Activity ID: {c47b8ffd-4d20-412f-bee1-e6165cd10000}
```

Am I missing something?

**Comment by Rehbluth** [comment]
Same Issue here. Any Solution or Ideas?

**Comment by raikoug** [comment]
I never found a way, and rollbacked to old good rpd.

**Comment by avibrazil** [comment]
Same issue here on W11 and RDP app version 10.2.3012.0.
On the remote server I can see on logs that this client doesn't even try to reach it over the network.

**Comment by Xelu86** [comment]
Hey raikoug,

Thanks again for contacting Microsoft, we value your feedback. 

You have described an issue with a product or service rather than our documentation. Please see our [GitHub content feedback guidelines]( https://github.com/MicrosoftDocs/windowsserverdocs/tree/main#github-content-feedback-guidelines). As this is a non-documentation issue, we’ll now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
