### ISSUE TITLE
Screenshots On Portal

### ISSUE THREAD

**Issue by bhaimicrosoft** [MicrosoftDocs/windowsserverdocs#6727]
Please update the screenshots in the article as none of them are relevant anymore. All the options on the Azure portal have also changed. So, kindly keep the articles updated for the public to view and follow.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ac8cd29-26cd-47da-5b3e-d58ba7c4a20c
* Version Independent ID: ae9587c8-0822-f5af-98ef-5386c4f17e58
* Content: [Active Directory Federation Services in Azure](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/how-to-connect-fed-azure-adfs)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/how-to-connect-fed-azure-adfs.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/deployment/how-to-connect-fed-azure-adfs.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Heidilohr** [comment]
Thank you for bringing this to our attention. The appearance of the UI has changed, but the process described in the article hasn't, so the screenshots are still relevant. However, we can add updating the screenshots to our current backlog.
