### ISSUE TITLE
Add Examples

### ISSUE THREAD

**Issue by andyorszula** [MicrosoftDocs/windowsserverdocs#6728]
Can you add some examples at the bottom?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57c9b953-a63d-e238-9318-8363698a0de6
* Version Independent ID: 366abac3-f803-f0c6-48e0-cd2f867d95fb
* Content: [manage-bde](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/manage-bde)
* Content Source: [WindowsServerDocs/administration/windows-commands/manage-bde.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/manage-bde.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @andyorszula,

Thanks again for contacting Microsoft. We value your feedback. 

Examples on how to use `manage-bde` can be found depending on the parameter(s) used. Each one should have 1 or more examples on their use in their own respective page. Please select one of the parameters from this main page to learn more.

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
