### ISSUE TITLE
Install error on Windows Server 2012 R2

### ISSUE THREAD

**Issue by chall3ng3r** [MicrosoftDocs/windowsserverdocs#673]
I am getting "This software is not supported on this operating system" error. Tried it on dedicated Windows Server 2012 R2 Standard, and VPS Windows Server 2012 R2 Datacenter editions. Same error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5d4a9c-11eb-3b85-91dd-cdbb0625db5a
* Version Independent ID: 01dad638-f8fb-61ff-4952-e3b25007a234
* Content: [Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/understand/windows-admin-center)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/understand/windows-admin-center.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/understand/windows-admin-center.md)
* Service: **unspecified**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by Haley-Rowland** [comment]
You can use Windows Admin Center to remotely manage Windows Server 2012 R2, but Windows Admin Center does not support installation on Windows Server 2012 R2. You can learn more about supported OSes for installation and management at [What type of installation is right for you?](https://docs.microsoft.com/windows-server/manage/windows-admin-center/plan/installation-options)

**Comment by chall3ng3r** [comment]
Thank you!

I think it is described a bit confusing over there. I installed WMF5.1 on server, and thought it would install fine after that.

**Comment by lizap** [comment]
Thanks for the feedback! We'll review with this in mind.

**Comment by AmonM15** [comment]
> You can use Windows Admin Center to remotely manage Windows Server 2012 R2, but Windows Admin Center does not support installation on Windows Server 2012 R2. You can learn more about supported OSes for installation and management at [What type of installation is right for you?](https://docs.microsoft.com/windows-server/manage/windows-admin-center/plan/installation-options)

Thanks for the link.
