### ISSUE TITLE
No output exmaple

### ISSUE THREAD

**Issue by Diramu** [MicrosoftDocs/windowsserverdocs#6731]
There no example with output and an explaining what it means . 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6444fdcc-eab2-9bb3-1b94-34914af628c9
* Version Independent ID: 31345b9a-df7a-8403-7fda-86784646d2c6
* Content: [tracert](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/tracert)
* Content Source: [WindowsServerDocs/administration/windows-commands/tracert.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/tracert.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey Diramu,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding a `tracert` output example with included description of what each column represents. Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
