### ISSUE TITLE
Server Core

### ISSUE THREAD

**Issue by jamesaepp** [MicrosoftDocs/windowsserverdocs#6733]
The document assumes the use of server with desktop experience. Please update article with steps for a CLI (core) windows server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7226c88e-03b8-b123-e257-171dd4cb03ba
* Version Independent ID: 973ec668-3612-887a-a254-67e34bf70f04
* Content: [Using Disk Cleanup on Windows Server](https://docs.microsoft.com/en-us/windows-server/storage/file-server/disk-cleanup)
* Content Source: [WindowsServerDocs/storage/file-server/disk-cleanup.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/file-server/disk-cleanup.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @iangpgh
* Microsoft Alias: **jgerend**

**Comment by craigcaseyMSFT** [comment]
Hello @jamesaepp,

Thanks for contacting Microsoft. We value your feedback.

A documentation change was made with a link pointing to the cleanmgr command, which you can run from the CLI.  The doc change is now live.

Thank you again and have a most pleasant day.
#please-close
