### ISSUE TITLE
Missing the word "Permissions" following the third "Read"

### ISSUE THREAD

**Issue by yedinakd** [MicrosoftDocs/windowsserverdocs#6734]
[Enter feedback here]
In the step "Permissions for file servers without Remote Desktop Services" the third "Read" permissions for the "Security group of users who need to put data on the share (Folder Redirection Users)" the third "Read" in the Permissions column is missing the word "Permissions."
The first two are "Read attributes" and "Read extended attributes." 
"Read" by itself is not a permission that can be applied in the "Advanced Permissions."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3273d609-8cdb-19b8-6e72-e6c763904c47
* Version Independent ID: cf80c8f5-49f6-43a4-bb8e-b5849beb818b
* Content: [Deploy Folder Redirection with Offline FilesDeploy Folder Redirection with Offline Files](https://docs.microsoft.com/en-us/windows-server/storage/folder-redirection/deploy-folder-redirection)
* Content Source: [WindowsServerDocs/storage/folder-redirection/deploy-folder-redirection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/folder-redirection/deploy-folder-redirection.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @yedinakd,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made surrounding the verbiage to display "Read permissions" in the designated location and will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day.
#please-close
