### ISSUE TITLE
Command "certutil -setreg chain\ChainCacheResyncFiletime @now" doesn't work for Windows 2022

### ISSUE THREAD

**Issue by Yan-Son** [MicrosoftDocs/windowsserverdocs#6736]
Command "certutil -setreg chain\ChainCacheResyncFiletime @now" doesn't work for Windows 2022 Datacenter

Reply:
PowerShell:
PS C:\Users\Administrator\Documents> certutil -setreg chain\ChainCacheResyncFiletime @now
Expected at least 2 args, received 1
CertUtil: Missing argument

CMD:
C:\Users\Administrator>certutil -setreg chain\ChainCacheResyncFiletime @now
HKEY_LOCAL_MACHINE\Software\Microsoft\Cryptography\OID\EncodingType 0\CertDllCreateCertificateChainEngine\Config\ChainCacheResyncFiletime:

Old Value:
  ChainCacheResyncFiletime REG_SZ = \@now
CertUtil: -setreg command FAILED: 0x8007000d (WIN32: 13 ERROR_INVALID_DATA)
CertUtil: The data is invalid.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198d75d5-9988-5eaa-bd24-6f7b46ead75e
* Version Independent ID: d2fffeee-2788-90d5-0ccb-e0e92207997c
* Content: [Advanced Features of Always On VPN](https://learn.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-adv-options#blocking-vpn-clients-that-use-revoked-certificates)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-adv-options.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-adv-options.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **wscontent**

**Comment by Yan-Son** [comment]
![image](https://github.com/MicrosoftDocs/windowsserverdocs/assets/65586173/d24b07c0-d182-45a0-abf1-d1f858296c59)
Still doesn't work

Windows Server 2022 Updated
![image](https://github.com/MicrosoftDocs/windowsserverdocs/assets/65586173/3e6e947e-71a8-4de4-a6dc-e112dee3bc46)

**Comment by anaharris-ms** [comment]
#reassign @robinharwood

**Comment by Yan-Son** [comment]
Please check https://github.com/MicrosoftDocs/windowsserverdocs/issues/7574
