### ISSUE TITLE
Feature "Blocking VPN Clients that Use Revoked Certificates" doesn't work for Windows 2022 dataccenter

### ISSUE THREAD

**Issue by Yan-Son** [MicrosoftDocs/windowsserverdocs#6737]
Feature "Blocking VPN Clients that Use Revoked Certificates" doesn't work for Windows 2022 datacenter.

Remote Access Server (installed on Windows 2022 DC), for IKEv2 connections checks CRL against own VPN certificate only and allows any "UserAuthProtocolAccepted Certificate" signed certificate to create connection. It do not check device certificated used for connection. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198d75d5-9988-5eaa-bd24-6f7b46ead75e
* Version Independent ID: d2fffeee-2788-90d5-0ccb-e0e92207997c
* Content: [Advanced Features of Always On VPN](https://learn.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-adv-options#blocking-vpn-clients-that-use-revoked-certificates)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-adv-options.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-adv-options.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **wscontent**

**Comment by anaharris-ms** [comment]
This has been fixed #please-close
