### ISSUE TITLE
Broken Link - Azure Active Directory Device Registration Service Overview

### ISSUE THREAD

**Issue by kicka5h** [MicrosoftDocs/windowsserverdocs#674]
Link - "Azure Active Directory Device Registration Service Overview". Points here: https://msdn.microsoft.com/6a14cb1f-a058-4453-8ede-d9f4a66a7073.aspx

Error 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2646147-59ef-ae02-9923-742f1fd58508
* Version Independent ID: bba6f1ff-468f-f23c-f419-eba95096e131
* Content: [Join to Workplace from Any Device for SSO and Seamless Second Factor Authentication Across Company Applications](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/join-to-workplace-from-any-device-for-sso-and-seamless-second-factor-authentication-across-company-applications)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Join-to-Workplace-from-Any-Device-for-SSO-and-Seamless-Second-Factor-Authentication-Across-Company-Applications.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Join-to-Workplace-from-Any-Device-for-SSO-and-Seamless-Second-Factor-Authentication-Across-Company-Applications.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by MicrosoftGuyJFlo** [comment]
looks like this link has been removed

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
