### ISSUE TITLE
Step 7 not clear enough

### ISSUE THREAD

**Issue by yusidd** [MicrosoftDocs/windowsserverdocs#6740]
On Step 7, we need more direction about what Microsoft recommends for the Hyper-V options.  Not just "select the appropriate options."  Most users may not understand what these things are.  Maybe include a link to a page with further explanation, if such a page exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c26eae-f46d-707a-f092-0c3d66b22912
* Version Independent ID: c4f0453e-2904-864f-fcfe-d7a2555f5732
* Content: [Install the Hyper-V role on Windows Server](https://learn.microsoft.com/en-us/windows-server/virtualization/hyper-v/get-started/install-the-hyper-v-role-on-windows-server)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/get-started/Install-the-Hyper-V-role-on-Windows-Server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/virtualization/hyper-v/get-started/Install-the-Hyper-V-role-on-Windows-Server.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by dksimpson** [comment]
Hi @yusidd,

Thanks for contacting Microsoft; we value your feedback. We've addressed this issue and updated the procedure steps.

#please-close
