### ISSUE TITLE
Federation Server farm limit is 5 or 30?

### ISSUE THREAD

**Issue by nicolgit** [MicrosoftDocs/windowsserverdocs#6742]
on this page I see a limit of 5 federation servers per Farm using WID

https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/design/federation-server-farm-using-wid-2012

here you talk about 30 federation servers per Farm using WID. Which is the correct number?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62721bd3-925d-08eb-a27c-49cbcbb4a253
* Version Independent ID: d03cfee1-ac41-0c24-f96b-cd60d1897983
* Content: [Determine Your AD FS Deployment Topology](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/design/determine-your-ad-fs-deployment-topology)
* Content Source: [WindowsServerDocs/identity/ad-fs/design/Determine-Your-AD-FS-Deployment-Topology.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/design/Determine-Your-AD-FS-Deployment-Topology.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @nicolgit,

Thanks again for contacting Microsoft. We value your feedback. 

We recently updated our AD FS documentation to reflect the limit of 30 for WID farms. 

- https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/design/federation-server-farm-using-wid-2012
- https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/design/AD-FS-Deployment-Topology-Considerations
- https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/design/federation-server-farm-using-wid

Changes are live. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
