### ISSUE TITLE
Incorrect Equation

### ISSUE THREAD

**Issue by EunJK** [MicrosoftDocs/windowsserverdocs#675]
2,400,000,000 / (30000*1) equals to 100,000? Please review that equation part.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bc978a2-5a8b-c6af-0c56-f762ea9edf16
* Version Independent ID: 33693e91-d1a2-10c0-0dd7-43167114868a
* Content: [Windows Time Service Tools and Settings](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings)
* Content Source: [WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by MicrosoftGuyJFlo** [comment]
Resolving in private repo branch GitHubIssues072018

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
