### ISSUE TITLE
DIR response has changed in Win 11

### ISSUE THREAD

**Issue by Mysteron347** [MicrosoftDocs/windowsserverdocs#6751]
Up to windows 11, a "dir" listing showed "directories" '.' and '..'.

Under windows 11, on the first directory level below root, such as the directory listing of "C:\temp" used as an example, there is no listing of '..'. 

This does not appear to be the case for subdirectories below the first level.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8095c8a1-5049-2eb1-2041-6392f2025cfa
* Version Independent ID: 6e63df5e-a455-33c7-22db-36f44121a2c0
* Content: [dir](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/dir)
* Content Source: [WindowsServerDocs/administration/windows-commands/dir.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/dir.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @Mysteron347,

Thanks again for contacting Microsoft. We value your feedback. 

We're unable to determine what the intent of your question is or if there's an issue with this documentation. If there are any errors or areas of improvement, please let us know so we may revise for better clarity. 

This repository is for Windows Server where both the "**.**" and "**..**" for directory levels still apply:

![image](https://user-images.githubusercontent.com/103963494/193954849-b33b227f-64af-4ffb-93a3-d9a0253aed4a.png)

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close

**Comment by Mysteron347** [comment]
I'll repeat : **first directory level below root, such as the directory listing of "C:\temp" used as an example,** there is no listing of '..'.

**This does not appear to be the case for subdirectories below the first level.**

So - your observations about "C:\Users\Administrator", being the **SECOND** level below root confirm my second point.

Try the **FIRST** level, such as "C:\Users" or "C:\temp" as exempliified in the original article.

![Clipboard03](https://user-images.githubusercontent.com/47810334/193994345-80734dc9-5ce0-43e1-acf7-3a1a257c9fa5.jpg)
