### ISSUE TITLE
Logging examples needed

### ISSUE THREAD

**Issue by robsmi-msfte** [MicrosoftDocs/windowsserverdocs#6752]
In the logging section, there are examples of how to open the logs.  But there are no examples of what tools are good at viewing the logs, and there are no examples.  That section would have much more value if there were examples of a problem, and what it looks like in the trace.  Better yet, several problems and follow along trace reviews.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09ab98fc-fea2-a11a-e5ca-de1430211d97
* Version Independent ID: 4d9943c3-fef7-ca86-bd03-1241a04b8135
* Content: [Get started with the Windows Desktop client](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
Hey @robsmi-msfte,

Thanks again for contacting Microsoft. We value your feedback.

Looking over this documentation under the [Access client logs](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/windowsdesktop.md#access-client-logs) section, the tool used to read the logs for the Windows Remote Desktop client is the built-in **Event Viewer**. 

As logs stored in **Event Viewer** may not look too user-friendly (data in the details box is either blank or very minimal): 

![image](https://user-images.githubusercontent.com/103963494/193960385-eec7a261-613f-4b3c-8b4a-23ab80880cfe.png)

We've added a way to convert it from the **etl** format to both **csv** and **xml**. This example is of **etl** > **xml** already filtered for **Error**, **EventTrace**, and **SummaryTracer**:

![image](https://user-images.githubusercontent.com/103963494/193959572-cf5eb2c4-8d88-4ae0-8b41-e89a9c15a358.png)

In both instances, not much data can be pulled to better understand an issue if one to occur.

We do have 2 sections for issues under [Remote Desktop client FAQ](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-client-faq) along with [General Troubleshooting](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/troubleshoot/rdp-error-general-troubleshooting) (under the collective Known issues) but neither of them go into depth as to what you may encounter viewing the logs for errors with solutions as this is outside the scope of GitHub.

A more appropriate forum for this would be to reach out to our product experts in the communities below:

- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/
- Microsoft Support: https://support.microsoft.com/ContactUs

We will consider an addition of an example for future upkeep of this documentation. In the meanwhile, we will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
