### ISSUE TITLE
How to activate RDS Licensing server and allocate CAL license by using powershell.

### ISSUE THREAD

**Issue by jameswsp** [MicrosoftDocs/windowsserverdocs#6755]
How to activate RDS Licensing server and allocate CAL license by using powershell.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2499f6d6-b28d-d46b-ea9d-3c9dd54fee7c
* Version Independent ID: cd210491-0f3a-1b60-c739-f74bd58daae4
* Content: [Activate the Remote Desktop Services license server](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-activate-license-server?source=recommendations)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-activate-license-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/rds-activate-license-server.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by craigcaseyMSFT** [comment]
Hi there,

We don't offer PowerShell instructions for most of the articles in this section of the documentation. But here are a couple links to hopefully help with your request:
https://learn.microsoft.com/en-us/troubleshoot/windows-server/remote/troubleshoot-rds-licensing-guidance#rdls-stops-responding-on-windows-server-2016-when-windows-server-2019-cals-are-requested

https://learn.microsoft.com/en-us/powershell/module/remotedesktop/set-rdlicenseconfiguration?view=windowsserver2016-ps

You can also check out our user forum for help:
https://techcommunity.microsoft.com/t5/windows-server/ct-p/Windows-Server

 We will now be closing this thread. Thank you.

#please-close
