### ISSUE TITLE
What is the difference between a desktop client and the one in Microsoft Store?

### ISSUE THREAD

**Issue by vickliew** [MicrosoftDocs/windowsserverdocs#6756]
What is the difference between a desktop client and the one in Microsoft Store?

The category and type are rather confusing as it does not clearly spell out which devices are for which OS etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: acc42a8f-2623-4352-7cc4-70f0f61e9d89
* Version Independent ID: 97d8b54b-5e7d-098b-4fb7-e8f6e0b30389
* Content: [Get started with the Microsoft Store Client](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windows)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windows.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/windows.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by Xelu86** [comment]
Hey vickliew,

Thanks again for contacting Microsoft. We value your feedback. 

We do have this document, [Compare the features of the Remote Desktop clients](https://learn.microsoft.com/en-us/azure/virtual-desktop/compare-remote-desktop-clients?toc=%2Fazure%2Fvirtual-desktop%2Fusers%2Ftoc.json), that hopefully answers this question.

There is also the "What's new for Remote Desktop clients" page for each one: https://learn.microsoft.com/en-us/azure/virtual-desktop/whats-new-client-windows?toc=%2Fazure%2Fvirtual-desktop%2Fusers%2Ftoc.json. Use the TOC on the left to navigate to which client you're using for changes applied to each.

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
