### ISSUE TITLE
Location of Chkdsk results

### ISSUE THREAD

**Issue by ClaraPotato** [MicrosoftDocs/windowsserverdocs#6758]
[Enter feedback here]

I feel this article could be improved by including information on where to find ChkDsk logs in Windows.

As of my recent testing the results will be in the Event Viewer and located under 'Application logs' with either the source "Wininit" or "ChkDsk"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e39de773-2483-f94c-45aa-32b6af9775a1
* Version Independent ID: 03ba7ec3-9c97-5572-3e41-9ffd0ce916f0
* Content: [chkdsk](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/chkdsk)
* Content Source: [WindowsServerDocs/administration/windows-commands/chkdsk.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/chkdsk.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @ClaraPotato,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made demonstrating how to retrieve chkdsk log files via **Event Viewer** and **PowerShell**. Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
