### ISSUE TITLE
Missing capitalisation in DACLs acronym expansion

### ISSUE THREAD

**Issue by Tx0actical** [MicrosoftDocs/windowsserverdocs#6759]
It's just a minor problem but for attention-to-detail purposes, I thought it would be right to create an issue.

Under the "Security Groups" heading, the documentation refers to Discretionary Access Control Lists (DACLs). It appears that the first letters are not capitalised as should have been the case while writing an acronym.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3489e3cf-5323-1d4d-9250-081af0abb2f7
* Version Independent ID: 3489e3cf-5323-1d4d-9250-081af0abb2f7
* Content: [Active Directory security groups](https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/understand-security-groups)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/understand-security-groups.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-ds/manage/understand-security-groups.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @Tx0actical,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made capitalizing the acronym expansion and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
