### ISSUE TITLE
WAC first login after installation

### ISSUE THREAD

**Issue by MiF-7** [MicrosoftDocs/windowsserverdocs#676]
After upgrade from Honolulu I cann't start the WAC in Edge Browser - after choosing the WAC Certificate  I get the following error: 
"Cant connect securely to this page
This might be because the site uses outdated or unsafe TLS security settings. If this keeps happening try contacting the website's owner."
It's Windows 10 Ent. (1709). Honolulu works here fine, but WAC does not want. It does not matter if upgrade from Honolulu or clean install of WAC first uninstall Honolulu - I get the same error :-(
Any idea?

Thanks in advance.
Michael

**Comment by jwwool** [comment]
This is the exact error that we see on [Windows Insider Preview versions](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/known-issues#insider-preview-windows-10--window-server-2019-rs5)
Will you please confirm the exact version in ```winver```?

**Comment by jwwool** [comment]
That's for the additional info! 

If you would be comfortable and are able, it would help us a lot if you could try to add a registry key as described in the **Easy Fix** section of [this page.](https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in)

We will be changing the product to use TLS 2.0 exclusively in the next release, which will eliminate the need for this workaround.

**Comment by MiF-7** [comment]
Thank you for Infos, Jeff!
But that does not work... The article discussed not the Windows 10 OS, and **Easy Fix** will not run too. Even though I do the settings manually - there are no changes, I get the same error.
BUT!
I have seen, the registry settings, discussed in link you provide, deal with enabling TLS 1.0/1.1/1.2. But it looks like WAC just wants TLS 2.0, and nothing else ;-) And in my registry there are TLS 2.0 not enabled by default, whatever the reason, I definitely did not do it.
After setting following registry values and reboot the WAC has started to work!

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Client]
"DisabledByDefault"=dword:**00000000**
"Enabled"=dword:**00000001**
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\WinHttp]
"DefaultSecureProtocols"=dword:**00000aa8**
[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Internet Settings\WinHttp]
"DefaultSecureProtocols"=dword:**00000aa8**
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings]
"SecureProtocols"=dword:**00000aa8**
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings]
"SecureProtocols"=dword:**00000aa8**

It may be that one or the other setting is unnecessary, but it works and I do not want to continue experimenting now to find the right one.
That should be able to tell us the Microsoft, but does not do that... :-(
