### ISSUE TITLE
Missing hyphen in cmdlet name

### ISSUE THREAD

**Issue by tmolenh** [MicrosoftDocs/windowsserverdocs#6763]
Both instances of "Get VMNetworkAdapterVlan" should be "Get-VMNetworkAdapterVlan"
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61dec703-ec84-c4fc-ab45-83decde810f2
* Version Independent ID: 2b0ebf31-825f-39cd-d7c8-8e207344252e
* Content: [Configure and View VLAN Settings on Hyper-V Virtual Switch Ports](https://learn.microsoft.com/en-us/windows-server/virtualization/hyper-v-virtual-switch/configure-and-view-vlan-settings-on-hyper-v-virtual-switch-ports)
* Content Source: [WindowsServerDocs/virtualization/hyper-v-virtual-switch/Configure-and-View-VLAN-Settings-on-Hyper-V-Virtual-Switch-Ports.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/virtualization/hyper-v-virtual-switch/Configure-and-View-VLAN-Settings-on-Hyper-V-Virtual-Switch-Ports.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @tmolenh, 

Thanks again for contacting Microsoft. We value your feedback. 

Nice catch! A documentation change has been made correcting the cmdlet in both instances and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
