### ISSUE TITLE
Adjust Transfer Settings page doesn't work.

### ISSUE THREAD

**Issue by dir-it** [MicrosoftDocs/windowsserverdocs#6764]
Hello,

We've got Windows Admin Center (version 2110.2 build 1.3.2204.19002) installed on a VM with Windows Server 2022 Standard 21H2 OS build 20348.1006 with the Storage Migration Service extension 2.24.0 installed. 

We're able to create a job, add servers to the job, define credentials and so on without issue. However we've got an issue under the Transfer Data section > Adjust Settings page. This page in particular does not proceed when pressing next, any edits to settings on this page are not respected during the rest of the process. We can bypass this page by clicking Install required features in the side navigation but are still unable to adjust any of the settings defined on this page, the defaults are OK but we'd like to ability to adjust these if needed. No error messages show, simply nothing happens when pressing next. Save and exit also fails to save any settings adjustments.

We've attempted to uninstall and reinstall the SMS extension without luck. Is this just a bug? Let me know if there are any log files I can produce to assist.
![adjust_settings_page](https://user-images.githubusercontent.com/45499074/192791697-d9973f12-e817-43fb-81b1-2ba9546fb204.jpg)

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @dir-it,

Thanks again for contacting Microsoft. We value your feedback.

As we understand it, you're describing a problem with the product itself and not with the product documentation. If there are any issue(s) within the content, please let us know so revisions can be made for more clarity.

GitHub isn't quite the right location for technical support. To get assistance or support for your product issue, we recommend that you engage with the product community or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).

Additional support forums:

- TechNet forums: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

We hope that that a resolution to this issue will be solved by our product experts. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
