### ISSUE TITLE
Sample command should use AuditLevel instead of LogLevel

### ISSUE THREAD

**Issue by NomadRex** [MicrosoftDocs/windowsserverdocs#6765]
<html>
<body>

Audit Level | PowerShell syntax | Description
-- | -- | --
None | **Set-AdfsProperties -LogLevel None** | Auditing is disabled and no events will be logged.
Basic (Default) | **Set-AdfsProperties -LogLevel Basic** | No more than 5 events will be logged for a single request
Verbose | **Set-AdfsProperties -LogLevel Verbose** | All events will be logged. This will log a significant amount of information per request.

</body>
</html>

The sample PowerShell commands should be replaced with:

Set-AdfsProperties -LogLevel None
Set-AdfsProperties -LogLevel Basic
Set-AdfsProperties -LogLevel Verbose

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 073ab477-ac4c-9951-9d50-9d979176cff1
* Version Independent ID: 384cd6f7-2249-3f33-9b9e-1c6abeae69cb
* Content: [AD FS Troubleshooting - Auditing Events and Logging](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-logging?source=docs#event-auditing-information-for-ad-fs-on-windows-server-2016)
* Content Source: [WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-logging.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/troubleshooting/ad-fs-tshoot-logging.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by NomadRex** [comment]
Correction:
Set-AdfsProperties -AuditLevel None
Set-AdfsProperties -AuditLevel  Basic
Set-AdfsProperties -AuditLevel Verbose

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @NomadRex,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting this issue and will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. #please-close
