### ISSUE TITLE
123

### ISSUE THREAD

**Issue by willstev321** [MicrosoftDocs/windowsserverdocs#6772]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Get started with OpenSSH for Windows](https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse?source=recommendations&tabs=gui)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @robinharwood
* Microsoft Alias: **roharwoo**

**Comment by robinharwood** [comment]
Hi @willstev321,

The feedback for this issue appears to be empty. I'm closing for the moment but please reply with an @ mention if you meant to add the details.

Thanks

#please-close
