### ISSUE TITLE
Blank Zip File

### ISSUE THREAD

**Issue by TitianRob** [MicrosoftDocs/windowsserverdocs#679]
Using the following PowerShell provides me with a blank Zip file - any thoughts on resolving this? I changed the WindowsAdminCenterGateway variable to match my own Admin Center address.
$WindowsAdminCenterGateway = 'https://windowsadmincenter.contoso.com:6516'
Invoke-RestMethod -Uri "$WindowsAdminCenterGateway/api/nodes/all/features/jea/endpoint/export" -Method POST -UseDefaultCredentials -OutFile "~\Desktop\WindowsAdminCenter_RBAC.zip"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6273f49-fe06-5a18-80e3-863bd3a0cf4e
* Version Independent ID: 4ed5bf3d-0c2a-a80e-5bd9-0e858dd8749b
* Content: [Configuring user access control and permissions](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/configure/user-access-control)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/configure/user-access-control.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/configure/user-access-control.md)
* Service: **unspecified**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by jwwool** [comment]
Specifying port 6516 is a bug in our documentation. It should be the port you specified when installing the gateway (default 443)
$WindowsAdminCenterGateway = 'https://windowsadmincenter.contoso.com:443'

**Comment by TitianRob** [comment]
Thanks! I did try that, but I'm still running into the same issue...
$WindowsAdminCenterGateway = 'https://company-wac.company.co.uk:443'
PowerShell just flashes as if it attempts to create the zip file, but when trying to open it I receive the error: 
"The compressed (zipped) folder is invalid".

**Comment by rpsqrd** [comment]
Hmm, that's not good. Could you give us some more information about your setup?

- Is the gateway domain joined?
- Did you run the command on the gateway or another computer?
- If another computer, was that computer domain joined and were you signed in with a domain account?
- Have you tried the single node deployment option? Did that work?

**Comment by TitianRob** [comment]
Sure; please see below: 

- Yes, the gateway is joined to the domain.
- I've tried running the command on both the gateway, and my own PC (the gateway is a Server 2016 VM). Both are joined to the domain.
- Single node option? I can't seem to find that on this page.

**Comment by TitianRob** [comment]
Actually, this is my own stupidity showing once again. Turn off Azure AD and this works perfectly fine. Thanks for the help!

**Comment by rpsqrd** [comment]
I’m glad to hear you got it working! I’ll see if we can figure out a more reliable command that works whether you’ve added an AAD account or not and update the doc.

_____________________________
