### ISSUE TITLE
Providing full ReFS+mirror benefits to Hyper-V guests

### ISSUE THREAD

**Issue by MikeLabatt** [MicrosoftDocs/windowsserverdocs#6792]
Would be nice if someone could address this topic (same question asked in 2012, 2014, 2022, never answered):

[https://learn.microsoft.com/en-us/answers/questions/1029203/storage-pool-disappeared-from-guest-appeared-on-ho.html](https://learn.microsoft.com/en-us/answers/questions/1029203/storage-pool-disappeared-from-guest-appeared-on-ho.html)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa4f8adc-7422-04df-56a8-3b16f73a5e2d
* Version Independent ID: a5b7899f-d1f1-3e58-01c4-858291128be7
* Content: [ReFS integrity streams](https://learn.microsoft.com/en-us/windows-server/storage/refs/integrity-streams)
* Content Source: [WindowsServerDocs/storage/refs/integrity-streams.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/refs/integrity-streams.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @gawatu
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey MikeLabatt,

Thanks again for contacting Microsoft. We value your feedback.

As we understand it, you're describing an issue with the product/service compared to an issue with the documentation itself.

For the Windows Server Repo in GitHub, here is what we're able to assist with that is in our direct scope:

- Content Issues
   - Broken Links, Grammar, Incorrect Code, Typos, Updates, Verbiage (general documentation issues)

GitHub is _not_ the right location/channel if searching for:

- Support Case or Support Tickets
   - We cannot action such items, nor are we a liaison between support teams.
- [Bug Submittal/Feature Requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
   - If on a Windows OS, click [here](https://aka.ms/WIPFeedbackHub) or perform `Windows Key + F` [Only on Win10 Build 14367+] ( this captures & attaches a screenshot).
   - Feedback can also be provided via our [Feedback Form](https://feedbackportal.microsoft.com/feedback).
- Extended Troubleshooting, Technical/Product Support, Vast specifics/functions of a product
   - Please utilize one or more of the following: 
     - Engage with the product community or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
     - TechNet: https://social.technet.microsoft.com/Forums/en-US/home.
     - MSDN: https://social.msdn.microsoft.com/Forums/en-US/home.
     - Microsoft Community: https://answers.microsoft.com/.

For all non-documentation issues, hopefully one of the community experts may be able to better assist. We will now be closing this thread.

Thank you and have a most pleasant day.
#please-close
