### ISSUE TITLE
No powershell for enable ?

### ISSUE THREAD

**Issue by gstevens-kyriba** [MicrosoftDocs/windowsserverdocs#6794]
It would be nice if there were a Powershell snipped to ENABLE TLS 1.2,  All the others have a script, including a disable script for TLS 1.2.  Don't 90% of people want to enable TLS 1.2 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8f505619-9097-e736-4c6a-8ec57c631f7d
* Version Independent ID: 12dc28e7-d8bf-4cca-95e5-0547b4f46b08
* Content: [Managing SSL/TLS Protocols and Cipher Suites for AD FS](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/operations/manage-ssl-protocols-in-ad-fs#enable-and-disable-tls-12)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Manage-SSL-Protocols-in-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/operations/Manage-SSL-Protocols-in-AD-FS.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @gstevens-kyriba,

Thanks again for contacting Microsoft. We value your feedback. 

As the documentation already has a code snippet to disable TLS 1.2, you can **enable** it by reversing the value from **off** to **on**:

```powershell
New-Item HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server' -Force | Out-Null

New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server' -name 'Enabled' -value '1' -PropertyType 'DWord' -Force | Out-Null

New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server' -name 'DisabledByDefault' -value '0' -PropertyType 'DWord' -Force | Out-Null

New-Item 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client' -Force | Out-Null

New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client' -name 'Enabled' -value '1' -PropertyType 'DWord' -Force | Out-Null

New-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client' -name 'DisabledByDefault' -value '0' -PropertyType 'DWord' -Force | Out-Null Write-Host 'TLS 1.2 has been enabled.'
```
We will now be closing this thread. Thank you and have a most pleasant day. #please-close
