### ISSUE TITLE
Windows server 

### ISSUE THREAD

**Issue by Jester112604** [MicrosoftDocs/windowsserverdocs#6796]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa6fb030-d76e-69a6-a764-c7cd7665ed79
* Version Independent ID: 307ff62c-f28f-4262-c812-b126799507d2
* Content: [Get started with Windows Server](https://learn.microsoft.com/en-us/windows-server/get-started/get-started-with-windows-server)
* Content Source: [WindowsServerDocs/get-started/get-started-with-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/get-started-with-windows-server.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @dknappettmsft
* Microsoft Alias: **daknappe**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
User feedback is unspecified/unrelated to documentation. Closing thread.
#please-close
