### ISSUE TITLE
References To Disabled Account

### ISSUE THREAD

**Issue by aakash-shah** [MicrosoftDocs/windowsserverdocs#681]
Under the section "Configure Auditing of Administrator Accounts", it suggests monitoring for if the account is enabled.  Based on the first Note where it indicates that this account should no longer be disabled, I believe this section needs to be updated?

Also, under the section "Verify "Account is disabled" Account Option", I believe that this section should also be removed since it is no longer recommended that this account be disabled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8499f8c0-64c7-2b6e-9022-115ed3d69904
* Version Independent ID: 9bf515dd-a4e4-baf2-8c18-0d0d76dd5eb0
* Content: [Appendix D - Securing Built-In Administrator Accounts in Active Directory](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/appendix-d--securing-built-in-administrator-accounts-in-active-directory#feedback)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-D--Securing-Built-In-Administrator-Accounts-in-Active-Directory.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Appendix-D--Securing-Built-In-Administrator-Accounts-in-Active-Directory.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by MicrosoftGuyJFlo** [comment]
Many still choose to disable these accounts. If you do this is saying you need to monitor and test.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
