### ISSUE TITLE
Referenced PowerShell script no longer available.

### ISSUE THREAD

**Issue by BestBackwards** [MicrosoftDocs/windowsserverdocs#6813]
> [KRBTGT Account Password Reset Scripts now available for customers](https://blogs.microsoft.com/cybertrust/2015/02/11/krbtgt-account-password-reset-scripts-now-available-for-customers/).

The script is no longer available at the page linked. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d0664917-1dbe-3018-7234-e64d86969376
* Version Independent ID: d0664917-1dbe-3018-7234-e64d86969376
* Content: [Active Directory Accounts](https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/understand-default-user-accounts#sec-krbtgt)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/understand-default-user-accounts.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-ds/manage/understand-default-user-accounts.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by IngridAtMicrosoft** [comment]
Link removed.
