### ISSUE TITLE
Remarks - to use ampersand (&) when  using echo, you also need caret (^) immediately before the ampersand 

### ISSUE THREAD

**Issue by rafamarrara** [MicrosoftDocs/windowsserverdocs#6814]
On last item of "Remarks" we should add ampersand (&) on the list of characters to escape with caret (^).

without **^**
```
C:\>echo foo & bar
foo
'bar' is not recognized as an internal or external command,
operable program or batch file.
```

with **^**
```
C:\>echo foo ^& bar
foo & bar
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b73a4605-c4b3-46a8-ec4e-493751fff82b
* Version Independent ID: 2bcfea05-35c7-49cb-0570-a0d5a4957ca1
* Content: [echo](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/echo)
* Content Source: [WindowsServerDocs/administration/windows-commands/echo.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/echo.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @rafamarrara,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made including the ampersand symbol (`&`) and will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
