### ISSUE TITLE
Add Documation n how to properly mount NFS share on Windows clients

### ISSUE THREAD

**Issue by swinster** [MicrosoftDocs/windowsserverdocs#6827]
I have been struggling to find decent and consistent documentation on how a Windows client should be configured to mount and access an NFS share. There are a number of articles out on the Internet, although they seem to suggest Registry edits and the use of the old `mount` command via `Cmd.exe`. It would be good for Microsoft to document how this can be achieved in various OS. 

Further, on this page, you make reference to the client and server versions supported (https://learn.microsoft.com/en-us/windows-server/storage/nfs/nfs-overview?source=recommendations#windows-and-windows-server-versions). There is no reference of a Windows 11 client and the NFS version supported. It seems odd that Windows Servers back to 2012 supported service NFS v4.1, but the clients on all Windows OS only support up to v3. Is this correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20741e00-6d40-c122-88b2-562b38d39b1e
* Version Independent ID: e556fb83-dc86-94ed-d0e0-616a6499c1e8
* Content: [Network File System overview](https://learn.microsoft.com/en-us/windows-server/storage/nfs/nfs-overview?source=recommendations)
* Content Source: [WindowsServerDocs/storage/nfs/nfs-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/nfs/nfs-overview.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @swinster,

Thanks again for contacting Microsoft. We value your feedback. 

-This article was recently updated to include Windows 11 as a supported OS. 
-Yes, NFSv3 is still the latest version for all clients on Windows OS.

We do have an article on [Mounting NFS](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-r2-and-2008/cc754350(v=ws.10)) and it is suggested to use the command line to perform certain actions (mount/unmount). Depending on the action needed, it can be performed using the native interface and not the CLI. The TOC to the left has more articles surrounding NFS that may be beneficial depending on your needs. Hopefully this helps. 

We will now be closing this thread. Thank you and have a most pleasant day. #please-close
