### ISSUE TITLE
It seems a typo?

### ISSUE THREAD

**Issue by zhqnbq** [MicrosoftDocs/windowsserverdocs#6832]
![image](https://user-images.githubusercontent.com/101001142/198012063-3560f762-acf4-4a9e-a999-9f7f07f1ee06.png)
I found two Windows 7 Ultimate in this page.I found the problem in not only the en-us page but also the zh-cn page.(I have never check this page in other languages, but I guess it also exists in others.
Hope to get an reply.Thanks.
Have a good day.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9cc647b1-b2a7-7b60-8c34-1718bad72dd0
* Version Independent ID: 73630a01-0734-1d15-dc40-1bde7a34ca4f
* Content: [Remote Desktop client - supported configuration](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-supported-config)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-supported-config.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-supported-config.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @zhqnbq,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made removing the duplicate `Windows 7 Ultimate` OS entry and will be live after the next business day. This change will affect all languages. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
