### ISSUE TITLE
Connect to these servers section unclear on regular expressions

### ISSUE THREAD

**Issue by trs80** [MicrosoftDocs/windowsserverdocs#6834]
The Connect to these servers section has this:

> The complete syntax of the regular expression can be used to specify the server name, but to differentiate a regular expression with the literal string, you must use at least one "" in the string specified. For example, you can specify nps.example.com to specify the RADIUS server nps1.example.com or nps2.example.com.

Which seems to be missing some characters, in the "" and nps.example.com. I looked in the Markdown source but there's nothing extra there either.

Also, could the document be updated to cover Windows 11, which in testing has even stricter requirements - matches are sensitive to upper/lower case, and wildcards don't work, both of which are different to Windows 10 behaviour.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ac9de730-f6cf-01b1-d32a-b502283789c0
* Version Independent ID: 2e1c9ff2-4181-f459-ad44-c010530d50be
* Content: [Extensible Authentication Protocol (EAP) for network access](https://learn.microsoft.com/en-us/windows-server/networking/technologies/extensible-authentication-protocol/network-access)
* Content Source: [WindowsServerDocs/networking/technologies/extensible-authentication-protocol/network-access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/networking/technologies/extensible-authentication-protocol/network-access.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @khdownie
* Microsoft Alias: **wscontent**

**Comment by khdownie** [comment]
@trs80 thanks for this. I worked on this page a couple of years ago when I was a vendor for Microsoft, but I'm on a different team now and probably shouldn't be listed as the author. Adding @JasonGerend who might know who owns this topic now.

**Comment by Xelu86** [comment]
Hey trs80,

Thanks again for contacting Microsoft. We value your feedback. 

Documentation changes have been applied addressing this issue and more updates to come. Changes are live. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
