### ISSUE TITLE
broken link to source code from MSAL tutorial

### ISSUE THREAD

**Issue by mlidal** [MicrosoftDocs/windowsserverdocs#6836]
I'm trying to follow this guide to set up authentication to ADFS, but the link to the code is broken. Has the code been removed or can the link be updated. Current link is https://github.com/microsoft/adfs-sample-msal-dotnet-webapp-to-webapi which returns 404

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1023d1b4-ba6b-32ab-7e9c-7cfb7a4b07dd
* Version Independent ID: 876ffb88-2999-179c-aab8-a7db6e773011
* Content: [AD FS MSAL Web app (server app) calling web APIs](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/development/msal/adfs-msal-web-app-web-api)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/msal/adfs-msal-web-app-web-api.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/development/msal/adfs-msal-web-app-web-api.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
The repo exists but is archived. No further changes to the content in the repo will be accepted, but the repo can still be cloned.
