### ISSUE TITLE
Text mistake

### ISSUE THREAD

**Issue by iarua** [MicrosoftDocs/windowsserverdocs#6840]
At the bottom of the page I found a mistake. There must be "Wininit"
![Screenshot 2022-10-29 012635](https://user-images.githubusercontent.com/24230723/198743788-d0fd026b-06e2-4a8d-83ae-a4aee74178b0.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e39de773-2483-f94c-45aa-32b6af9775a1
* Version Independent ID: 03ba7ec3-9c97-5572-3e41-9ffd0ce916f0
* Content: [chkdsk](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/chkdsk?tabs=event-viewer)
* Content Source: [WindowsServerDocs/administration/windows-commands/chkdsk.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/chkdsk.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **alalve**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @iarua, 

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting `winnit` > `wininit` through its entirety. Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
