### ISSUE TITLE
Specified registry path is wrong

### ISSUE THREAD

**Issue by ackh** [MicrosoftDocs/windowsserverdocs#6841]
The documentation of the command `fsutil 8dot3name set` specifies that the registry key `HKLM\System\CurrentControlSet\Control\FileSystem\NtfsDisable8dot3NameCreationNtfsDisable8dot3NameCreationNtfsDisable8dot3NameCreation` is changed. That registry key does not exist and I assume it should be `HKLM\System\CurrentControlSet\Control\FileSystem\NtfsDisable8dot3NameCreation`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f366fe77-febb-cb4b-54f4-8ee1610e1293
* Version Independent ID: 23861f16-2542-95b7-e5d6-9f0afaaa3de8
* Content: [fsutil 8dot3name](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil-8dot3name)
* Content Source: [WindowsServerDocs/administration/windows-commands/fsutil-8dot3name.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/fsutil-8dot3name.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @toklima
* Microsoft Alias: **toklima**

**Comment by Xelu86** [comment]
Hey @ackh, 

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting how the table is displayed and the registry file path for `NtfsDisable8dot3NameCreation`. Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
