### ISSUE TITLE
Explain in detail, the application and mode of operation of active directory in the system administration of an enterprise infrastructure, using any case study approach

### ISSUE THREAD

**Issue by MCKhabo** [MicrosoftDocs/windowsserverdocs#6844]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9bb772ec-10a8-1c86-8af7-5e1d51912866
* Version Independent ID: 743875a3-e418-d81f-1a70-474a3471bfcb
* Content: [Active Directory Domain Services Overview](https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/get-started/virtual-dc/active-directory-domain-services-overview)
* Content Source: [WindowsServerDocs/identity/ad-ds/get-started/virtual-dc/Active-Directory-Domain-Services-Overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-ds/get-started/virtual-dc/Active-Directory-Domain-Services-Overview.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by IngridAtMicrosoft** [comment]
Issue appears to be an exam essay question, and not an issue with the documentation. Closing.
