### ISSUE TITLE
non-zero value is incorrect

### ISSUE THREAD

**Issue by ssmiller60** [MicrosoftDocs/windowsserverdocs#6845]
[Enter feedback here]

In this section: https://learn.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings?tabs=diffie-hellman#tls-dtls-and-ssl-protocol-version-settings

this is incorrect:
In order to override a system default and set a supported (D)TLS or SSL protocol version to the Enabled state, create a DWORD registry value named "Enabled" with a non-zero value

Should not be "non-zero value".  Should be "value of 1" as is shown in the multiple pictures/examples on the same page

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dd180142-4c19-8abc-ecce-e4c7e5ac8951
* Version Independent ID: fc5bba87-afad-1729-8f7e-333c73188b73
* Content: [Transport Layer Security (TLS) registry settings](https://learn.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings?tabs=diffie-hellman)
* Content Source: [WindowsServerDocs/security/tls/tls-registry-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/security/tls/tls-registry-settings.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @PatAltimore
* Microsoft Alias: **alalve**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @ssmiller60,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made removing further instances of `non-zero value` with valid registry value entries and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. #please-close
