### ISSUE TITLE
Update to avoid confusion

### ISSUE THREAD

**Issue by bellnaf** [MicrosoftDocs/windowsserverdocs#6847]
This article describes how to deploy a new SSL certificate to your AD FS and WAP servers.
Note
The AD FS SSL certificate is not the same as the AD FS Service communications certificate found in the AD FS Management snap-in. To change the AD FS SSL certificate, you will need to use PowerShell.

Replacing the SSL certificate for AD FS
Note: 
First, determine which certificate binding mode your AD FS servers are running default certificate authentication binding, or alternate client TLS binding mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d8733a32-8eef-bdb8-673f-065e8a5f1e0f
* Version Independent ID: f111b377-0dce-d7a6-9483-8830533cacba
* Content: [Managing SSL Certificates in AD FS and WAP in Windows Server 2016](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/operations/manage-ssl-certificates-ad-fs-wap)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/manage-ssl-certificates-ad-fs-wap.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/operations/manage-ssl-certificates-ad-fs-wap.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @jenfieldmsft
* Microsoft Alias: **billmath**

**Comment by craigcaseyMSFT** [comment]
Hello @bellnaf,

Thanks for contacting Microsoft. We value your feedback.

Documentation changes have been made to clarify and acknowledge this issue. The doc changes are now live.

Thank you again and have a most pleasant day.
#please-close
