### ISSUE TITLE
New feature - extend search to other tables in other model driven apps

### ISSUE THREAD

**Issue by cizquierdo73** [MicrosoftDocs/windowsserverdocs#6848]
[Enter feedback here]
My customer is disappoi8nted with dataverse search as they cannot extend the search to tables in another model driven app. IS this a feature that can be added?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23b0ff5c-e77e-6cf1-5a0e-86a62908d73d
* Version Independent ID: e58c39e4-dc33-3639-14e7-a970a214b0ed
* Content: [Overview of Extended Security Updates for Windows Server 2008, 2008 R2, 2012, and 2012 R2](https://learn.microsoft.com/en-us/windows-server/get-started/extended-security-updates-overview#what-are-extended-security-updates)
* Content Source: [WindowsServerDocs/get-started/extended-security-updates-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/extended-security-updates-overview.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @dknappettmsft
* Microsoft Alias: **daknappe**

**Comment by dknappettmsft** [comment]
Hi, GitHub issues in this repo are not for product feature requests and are for Windows Server, not Power Platform (which Dataverse search is). As this is not related to the article, I'll close it.

#please-close
