### ISSUE TITLE
WAC - Incorrectly reports Remote Desktop status

### ISSUE THREAD

**Issue by JamesEdmonds89** [MicrosoftDocs/windowsserverdocs#685]
I have WAC installed on my local Win 10 workstation, and when I click on one of the server connections I have, and then go to remote desktop, it says connections are not allowed to this computer.

If I go to settings, it reports remote desktop is not enable, but I know for a fact it is as I am logged onto the server remotely using RDC.

**Comment by jwwool** [comment]
We aren't able to reproduce this issue. Please [create a bug](https://windowsserver.uservoice.com/forums/295071/category/319162?query=%5BBug%5D) so we can identify other users that may be effected.

Please include the following:

* Platform where Windows Admin Center is **installed** (Windows 10 or Windows Server):
    * If installed on Server, are you using:
        * A self-signed certificate created by the installer?
        * Your own certificate?
            * If you are using your own certificate, does the subject name match the machine?
            * If you are using your own certificate, does it specify an alternate subject name?
* Did you install with the default port setting?
    * If not, which port did you specify?
* Is the machine where Windows Admin Center is **installed** joined to a domain?
* Windows version where Windows Admin Center is **installed**:
* Is the machine that you are **trying to manage** joined to a domain?
* Windows version of the machine that you are **trying to manage**:
* What browser are you using?
    * If you are using Google Chrome, what is the version? (Help > About Google Chrome)

**Comment by JamesEdmonds89** [comment]
Looks like someone else has had the issue:
https://windowsserver.uservoice.com/forums/295071-management-tools/suggestions/33940756-unable-to-use-remote-desktop

Should I create my own bug or just add my details to their entry?

**Comment by jwwool** [comment]
Please add to the existing entry, thanks!

**Comment by JamesEdmonds89** [comment]
Have commented on his raised bug.
