### ISSUE TITLE
564

### ISSUE THREAD

**Issue by Zaooa** [MicrosoftDocs/windowsserverdocs#6855]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d83b6fc-d8bf-0c5e-de23-85a22ee90947
* Version Independent ID: 108708f2-24d1-3a92-4a92-08686a2ed32f
* Content: [What's new in Windows Server 2016](https://learn.microsoft.com/en-us/windows-server/get-started/whats-new-in-windows-server-2016)
* Content Source: [WindowsServerDocs/get-started/whats-new-in-windows-server-2016.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/whats-new-in-windows-server-2016.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
User feedback is unspecified. Closing thread.
#please-close
