### ISSUE TITLE
Linked Videos are Screenshots only

### ISSUE THREAD

**Issue by thomas-kringel** [MicrosoftDocs/windowsserverdocs#6856]
Hi team,

all linked videos are screenshots only, can you pls check and link the videos?

Best,
Thomas

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a03180ce-ce5e-a242-534e-a6d2a71fddc3
* Version Independent ID: 009bf11f-5419-1da4-36eb-89f16bf82ca2
* Content: [Fault domain awareness](https://learn.microsoft.com/en-us/windows-server/failover-clustering/fault-domains)
* Content Source: [WindowsServerDocs/failover-clustering/fault-domains.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/failover-clustering/fault-domains.md)
* Product: **windows-server**
* Technology: **failover-clustering**
* GitHub Login: @cosmosdarwin
* Microsoft Alias: **cosdar**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @thomas-kringel,

A documentation change has been made updating the links to these videos and will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
