### ISSUE TITLE
Fantastic article

### ISSUE THREAD

**Issue by TomShinder** [MicrosoftDocs/windowsserverdocs#686]
Thank you for taking the time to write this, this is truly Golden Knowledge.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19620533-3f60-a1cb-a679-ff6ff5dde2bc
* Version Independent ID: 54583dac-de23-b64c-3396-fac964724595
* Content: [Implementing Least-Privilege Administrative Models](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/implementing-least-privilege-administrative-models)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Implementing-Least-Privilege-Administrative-Models.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Implementing-Least-Privilege-Administrative-Models.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by lizap** [comment]
Thanks, Tom! @billmath - just want to make sure you see this kudos.
