### ISSUE TITLE
Where are the latest update for Microsoft Remote Desktop Client? Latest version is 10.2.3000.0

### ISSUE THREAD

**Issue by tamoanxx** [MicrosoftDocs/windowsserverdocs#6865]
Where are the latest update for Microsoft Remote Desktop Client? Latest version is 10.2.3000.0

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67b7b5a4-647e-fee3-6533-6ed88ae45bfa
* Version Independent ID: d9102859-0147-346f-8268-6e2a75c8b0b7
* Content: [What's new in the Microsoft Store client](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windows-whatsnew)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windows-whatsnew.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/windows-whatsnew.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @tamoanxx,

Thanks again for contacting Microsoft. We value your feedback.

I think you may be referring to our "[What's new in the Remote Desktop Client](https://learn.microsoft.com/en-us/azure/virtual-desktop/whats-new-client-windows)" page with the latest version being 1.2.3770 for the Window client itself. As this is a cross-platform product, please refer to the TOC on the left and select the page for the platform you're currently using:

![image](https://user-images.githubusercontent.com/103963494/213003318-978f6b2c-83ea-4f90-a4aa-f0debfa19607.png)
 
We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
