### ISSUE TITLE
Missing repo

### ISSUE THREAD

**Issue by mercer-michael-c** [MicrosoftDocs/windowsserverdocs#6866]
I can't find the fedora 37 repo.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @mercer-michael-c,

Thanks again for contacting Microsoft. We value your feedback. 

As the repo in question is not a Microsoft product or service, this is out of our scope in terms of our ability to assist. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close

**Comment by mercer-michael-c** [comment]
> Hey @mercer-michael-c,
> 
> 
> 
> Thanks again for contacting Microsoft. We value your feedback. 
> 
> 
> 
> As the repo in question is not a Microsoft product or service, this is out of our scope in terms of our ability to assist. We will now be closing this thread. Thank you and have a most pleasant day. 
> 
> #please-close

How is packages.microsoft.com not a Microsoft product?

I saw the repos for many other distros including fedora 36 but fedora 37 was not available. I wanted to test something with intune
