### ISSUE TITLE
Where is Summary of Best Practice Recommendations

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windowsserverdocs#6870]
The text states that there is  a Summary of Best Practice Recommendations section but I don't see this on the left side navigation or in the listing at the bottom of the page, where is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c76843e-4f42-c311-7aa0-c743ce763188
* Version Independent ID: 71457c14-0691-337d-9c8f-3a1dcc329c06
* Content: [Introduction](https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/component-updates/introduction)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/component-updates/Introduction.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-ds/manage/component-updates/Introduction.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by IngridAtMicrosoft** [comment]
It is located here:
https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/component-updates/introduction#summary-of-best-practice-recommendations
