### ISSUE TITLE
Broken links in Networking Documentation

### ISSUE THREAD

**Issue by measin** [MicrosoftDocs/windowsserverdocs#6871]
[Enter feedback here]
https://learn.microsoft.com/en-us/windows-server/networking/core-network-guide/cncg/wireless/a-deploy-8021x-wireless-access#network-and-domain-environment-dependencies

In this section there's a link to a word doc supposedly, the link is broken as it points to a location on technet. Please update to reflect new location, if possible, else remove links and reference.

Best regards
Alf Morten

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e47cd8e-249a-1f45-031d-041a5697bb16
* Version Independent ID: 7197b09e-2d8a-326b-c13b-4b388b438ff1
* Content: [Deploy Password-Based 802.1X Authenticated Wireless Access](https://learn.microsoft.com/en-us/windows-server/networking/core-network-guide/cncg/wireless/a-deploy-8021x-wireless-access#network-and-domain-environment-dependencies)
* Content Source: [WindowsServerDocs/networking/core-network-guide/cncg/wireless/a-deploy-8021X-wireless-access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/networking/core-network-guide/cncg/wireless/a-deploy-8021X-wireless-access.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @measin,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made removing the link to the unavailable Word doc resource, including said link from related docs, and will be live after the next business day. 

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
