### ISSUE TITLE
Hack download 

### ISSUE THREAD

**Issue by munsihprajapat** [MicrosoftDocs/windowsserverdocs#6872]
Sushil 
[Enter feedback here]

---
#### Document  gjhbin 

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b79ce4d-52b9-5193-df08-c40fa663da58
* Version Independent ID: a5215c06-f761-3141-4eb4-71ae00b2c8aa
* Content: [Get started with Windows Server Update Services (WSUS)](https://learn.microsoft.com/en-us/windows-server/administration/windows-server-update-services/get-started/windows-server-update-services-wsus)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/get-started/windows-server-update-services-wsus.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-server-update-services/get-started/windows-server-update-services-wsus.md)
* Product: **windows-server**
* Technology: **wsus**
* GitHub Login: @JasonGerend
* Microsoft Alias:  show k. E U ke us.

**Comment by munsihprajapat** [comment]
Sir U. D

**Comment by munsihprajapat** [comment]
W uxeif I fe j uge n

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
User feedback is unspecified. Closing thread.
#please-close
