### ISSUE TITLE
Msi will not install.

### ISSUE THREAD

**Issue by pathfinderNE** [MicrosoftDocs/windowsserverdocs#6874]
Great solved my problem with msi failing to install

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2a2e3005-0d38-154e-560e-0f25d4892810
* Version Independent ID: 11dcf68e-545e-8e9d-3df0-645a9ae9b6fc
* Content: [msiexec](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/msiexec)
* Content Source: [WindowsServerDocs/administration/windows-commands/msiexec.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/msiexec.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @pathfinderNE, 

Thanks again for contacting Microsoft. We value your feedback.

We're glad to hear our documentation assisted you in your endeavors. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
