### ISSUE TITLE
Wrong dash character (U+2013) used in the copyable examples makes the examples fail

### ISSUE THREAD

**Issue by viorel-m** [MicrosoftDocs/windowsserverdocs#6876]
[Enter feedback here]
The copyable examples on this page have the wrong dash sign in front of the -unlock arguments. They are supposed to be U+002D but they are U+2013 (EN DASH). If the reader uses the Copy button and paste in a terminal window they'll get strange errors like:

manage-bde –unlock E: -password

ERROR: Invalid Syntax.
"–unlock" was not understood.

Type "manage-bde -?" for usage.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a504df6-57a1-96a8-e00b-971fd9a3ed0b
* Version Independent ID: a9fe4704-fc82-2eca-cfc2-981e805e73a6
* Content: [manage-bde unlock](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/manage-bde-unlock)
* Content Source: [WindowsServerDocs/administration/windows-commands/manage-bde-unlock.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/manage-bde-unlock.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **alalve**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @viorel-m,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting the dashes used so that the code snippet will copy/paste correctly. Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
