### ISSUE TITLE
ağ ayaraları

### ISSUE THREAD

**Issue by huseyinkyz7** [MicrosoftDocs/windowsserverdocs#6884]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 801f55b2-1a96-6661-b07e-33fcd3b6d50d
* Version Independent ID: 7d7178c4-d679-eb13-39ea-82fd1fa8a2bd
* Content: [High-performance networking (HPN)](https://learn.microsoft.com/en-us/windows-server/networking/technologies/hpn/hpn-top?source=recommendations)
* Content Source: [WindowsServerDocs/networking/technologies/hpn/hpn-top.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/networking/technologies/hpn/hpn-top.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. 

We're unable to determine what the intent of your question is. If there are any errors or areas of improvement with said documentation, please let us know so we may better assist.

We're closing this issue but please feel free to reopen it and advise us what revisions may be needed. Thank you and have a most pleasant day. #please-close
