### ISSUE TITLE
Kalenex tool 

### ISSUE THREAD

**Issue by Kmhububjbgg** [MicrosoftDocs/windowsserverdocs#6886]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69b5a02c-32fd-3064-b368-20c67b13ba27
* Version Independent ID: d010fb83-9073-639b-a9ae-aa75d3cbfd44
* Content: [Commands by Server role](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/commands-by-server-role)
* Content Source: [WindowsServerDocs/administration/windows-commands/commands-by-server-role.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/commands-by-server-role.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. 

We're unable to determine what the intent of your question is. If there are any errors or areas of improvement with said documentation, please let us know so we may better assist.

We're closing this issue but please feel free to reopen it and advise us what revisions may be needed. Thank you and have a most pleasant day. #please-close
