### ISSUE TITLE
Typo of AD FS Requirement

### ISSUE THREAD

**Issue by whlearn00** [MicrosoftDocs/windowsserverdocs#6888]
Title of AD FS is incorrectly written as AD DS
(https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-requirements#BKMK_4)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81fc58b9-7063-5107-5f65-c77694b33c7e
* Version Independent ID: a541e745-1505-696d-2adf-c578e1f54b4c
* Content: [AD FS 2016 Requirements](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-requirements)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/ad-fs-requirements.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/overview/ad-fs-requirements.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @whlearn00,

Thanks again for contacting Microsoft. We value your feedback. 

This is not a typo as a necessary component for AD FS is AD DS that has its own requirements. We have another article that discusses this, also titled "[AD FS Requirements](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn554247(v=ws.11)?redirectedfrom=MSDN)", which includes a bit more information surrounding this topic when planning your deployment topology. 

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
