### ISSUE TITLE
recursion option needs more explanation

### ISSUE THREAD

**Issue by MarkAWalters** [MicrosoftDocs/windowsserverdocs#6889]
Tried using the recursion option, but although my command looks right, it **yields no results**.  As far as I can see my command follows the model and explanations given, see below:

      For /r ("d:\my dir\") %A in (*.*) do Echo %~ftzA

On the other hand, **this works**, but only within the directory specified, whereas I also want files in subdirectories as well

     For %A in ("d:\my dir\*") do Echo %~ftzA

I've tried playing around with it, and looking on the internet for more info, but no joy.  Perhaps you can expand the explanation further and/or **add examples** of the recursion syntax, as there are none.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 362d60c8-8d69-6016-10bd-0f81114ec228
* Version Independent ID: 76d9a719-f621-f716-4987-68acb1501c63
* Content: [for](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/for?source=recommendations)
* Content Source: [WindowsServerDocs/administration/windows-commands/for.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/for.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey MarkAWalters, 

Thanks again for contacting Microsoft. We value your feedback. 

You may need to remove the parenthesis surrounding your directory to run the command as desired:

> for /r "c:\my dir\" %A in (*.*) do echo %~ftzA

![image](https://github.com/MicrosoftDocs/windowsserverdocs/assets/103963494/70ca1eb0-adbf-4bbd-aa13-c50d3fcbf640)

A documentation change has been made adding this example and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
