### ISSUE TITLE
Where is the documentation on how to configure the DnsCache?

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/windowsserverdocs#689]
The DnsCache has several registry setting, where are the documentation for those?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae9078ba-b4ed-c780-d0ab-97c1f7472ab1
* Version Independent ID: 3a211d30-cc8f-5fbc-f37a-0c460652a4b2
* Content: [What's New in DNS Client in Windows Server](https://docs.microsoft.com/en-us/windows-server/networking/dns/what-s-new-in-dns-client)
* Content Source: [WindowsServerDocs/networking/dns/What-s-New-in-DNS-Client.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/dns/What-s-New-in-DNS-Client.md)
* Service: **unspecified**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@Bartolomeus-649, here is link to dnscache registry settings.  I am working with engineering to update this content.

https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/cc959517(v%3dtechnet.10)

**Comment by Bartolomeus-649** [comment]
The one with this header?
![image](https://user-images.githubusercontent.com/7513795/39219435-bf9b33f6-482a-11e8-8a40-9bad78efb0f0.png)

**Comment by shortpatti** [comment]
We moved all previous versions (Windows Server 2008 or earlier, and Windows 8.1 or earlier) to a different location.  The engineer is working on updating the dnscache information.

**Comment by shortpatti** [comment]
The documentation can be found [here](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-r2-and-2008/dd197418(v%3dws.10)#dnscacheparameters).  Closing
