### ISSUE TITLE
Missing some Well-known SIDs

### ISSUE THREAD

**Issue by MichaelGrafnetter** [MicrosoftDocs/windowsserverdocs#6903]
The **Well-known SIDs** section does not contain several well-known SIDs introduced in Windows Server 2012 and newer, including Key Admins (S-1-5-domain-526), Enterprise Key Admins (S-1-5-root domain-527), Protected Users (S-1-5-domain-525), Read-only Domain Controllers (S-1-5-domain-521), and Cloneable Domain Controllers (S-1-5-domain-522).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f38b3e17-9e4b-958b-5b4c-87f230f43254
* Version Independent ID: f38b3e17-9e4b-958b-5b4c-87f230f43254
* Content: [Security identifiers](https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/understand-security-identifiers)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/understand-security-identifiers.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-ds/manage/understand-security-identifiers.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by Xelu86** [comment]
Hey MichaelGrafnetter,

Thanks again for contacting Microsoft. We value your feedback. 

Good catch, missing SIDs are being added and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
