### ISSUE TITLE
Typo in the note

### ISSUE THREAD

**Issue by OursonBleu** [MicrosoftDocs/windowsserverdocs#6906]
Note

Windows Admin Center as an application depends on the operating system and infrastructure for security. Windows Admin Center does not implement, **moitor**, or enforce a security boundary.

Just a typo in the note.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: acae660a-58ce-fa6c-4b39-1ef467d21b1d
* Version Independent ID: eeabb63a-ced9-02a2-3b8e-858e5488c4b5
* Content: [User access options with Windows Admin Center](https://learn.microsoft.com/en-us/windows-server/manage/windows-admin-center/plan/user-access-options)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/plan/user-access-options.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/manage/windows-admin-center/plan/user-access-options.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **wscontent**

**Comment by Xelu86** [comment]
#assign:xelu86
