### ISSUE TITLE
hash marks mistaken for real numbers

### ISSUE THREAD

**Issue by great-danezzz13** [MicrosoftDocs/windowsserverdocs#6909]
![Screenshot_20221208_180959_Software Update.jpg](https://user-images.githubusercontent.com/97160836/206592939-c9461aa9-994b-42b1-82d6-09a68bcf0704.jpg)#772-6*

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. 

We're unable to determine what the intent of your question is. If there are any errors or areas of improvement with our documentation, please let us know so we may better assist.

We're closing this issue but please feel free to reopen it and advise us what revisions may be needed for the specific document in question. Thank you and have a most pleasant day. #please-close
