### ISSUE TITLE
PTP client settings and configuration is not documented

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/windowsserverdocs#6910]
Expected: Windows PTP client thoroughly documented.
Found: Windows PTP client not documented.
Suggested fix: Document Windows PTP client including all settings and registry entries.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d09b16e-4bbb-91fa-3d84-e7623ec4dc07
* Version Independent ID: b6eadad5-0167-34b6-ed3a-16fa7ee83c60
* Content: [Windows Time service tools and settings](https://learn.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-time-service-tools-and-settings)
* Content Source: [WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/networking/windows-time-service/Windows-Time-Service-Tools-and-Settings.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @v-tappelgate
* Microsoft Alias: **v-tappelgate**

**Comment by Xelu86** [comment]
Hey rossmpersonal,

Thanks again for contacting Microsoft. We value your feedback. 

The W32Time doc is going through an update, including the 4 sections surrounding the registry entries. Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close

**Comment by rossmpersonal** [comment]
Ticket needs to be reopened. While the page has been updated (thank goodness), it still does not include PTP client settings.

**Comment by Xelu86** [comment]
Hey rossmpersonal,

We have engaged with the W32Time team and are waiting for their response whether they will decide to include PTP settings in this doc or have separate content available for PTP. Once we hear back, we will apply necessary changes.

Thank you.

**Comment by Xelu86** [comment]
Hey rossmpersonal, 

While waiting for a response, I did find this doc [PTP Validation](https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fraw.githubusercontent.com%2FMicrosoft%2FW32Time%2Fmaster%2FPrecision%2520Time%2520Protocol%2Fdocs%2FValidation%2520Guide%2520-%2520Precision%2520Time%2520Protocol.docx&wdOrigin=BROWSELINK).
