### ISSUE TITLE
Standard edition to standard edition upgrade support clarity.

### ISSUE THREAD

**Issue by nascar3000** [MicrosoftDocs/windowsserverdocs#6912]
The Topic,  "Upgrading licensed versions of Windows Server" confuses customers who in-place upgrading Standard to Standard edition without license upgrade to Datacenter.
First sentence says; 
"Below are general guidelines for in-place upgrade paths where Windows Server is already licensed (that is, not evaluation):"
And last one says ;
"You can only change from Standard edition to Datacenter edition when upgrading. Changing from Datacenter edition to Standard edition is not supported."

misleading customers to wrong idea Standard to Standard in-place upgrade not supported.

Need more clarity to Standard to Standard in-place is supported and it is not license conversion.

Thanks 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1b19ef8-a273-c1c8-18ff-7d29664bb9d2
* Version Independent ID: 8cf37a43-cff4-78de-0d66-2f482c022dc7
* Content: [Upgrade and conversion options for Windows Server](https://learn.microsoft.com/en-us/windows-server/get-started/upgrade-conversion-options)
* Content Source: [WindowsServerDocs/get-started/upgrade-conversion-options.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/upgrade-conversion-options.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @dknappettmsft
* Microsoft Alias: **daknappe**

**Comment by v-thepet** [comment]
Hello @nascar3000,

Thanks for contacting Microsoft. We value your feedback.

Documentation changes have been made to clarify this issue and will be live after the next business day.

Thank you again and have a most pleasant day.

#please-close
