### ISSUE TITLE
Missing /e "Reason" examples and parameter options.

### ISSUE THREAD

**Issue by JourneyInAntiquity** [MicrosoftDocs/windowsserverdocs#6915]
Please provide more information on how to properly use the "/e" command switch to provide a Reason.  The Reason Options as well as an example usage would be greatly appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2770335e-d15c-6389-36b9-d687b7794b92
* Version Independent ID: 319c885a-1c12-595f-8018-c563945afe93
* Content: [shutdown](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/shutdown)
* Content Source: [WindowsServerDocs/administration/windows-commands/shutdown.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/shutdown.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **alalve**

**Comment by Xelu86** [comment]
Hey JourneyInAntiquity,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding an example on how to use `/e` parameter. Note that the reason will be tracked into the [shutdown event tracker](https://learn.microsoft.com/en-us/troubleshoot/windows-server/application-management/description-shutdown-event-tracker). Changes will be live after the next business day. 

> To restart the remote computer *myremoteserver* in 5 minutes due to a security update and include this reason in the shutdown event tracker, type:
>
> ```
> shutdown /r /t 300 /e /c "Security Update" /m \\myremoteserver
> ```

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
