### ISSUE TITLE
"Next Steps" links are broken

### ISSUE THREAD

**Issue by jonaslewin** [MicrosoftDocs/windowsserverdocs#6923]
The links to
[Prepare your environment](https://learn.microsoft.com/en-us/deploy/prepare-environment.md)
[Install Windows Admin Center](https://learn.microsoft.com/en-us/deploy/install.md)
are broken, since they link to md files in the wrong path.
I guess they should be

[Prepare your environment](prepare-environment)
[Install Windows Admin Center](install)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d81cd846-91e6-dc59-57cc-c0a25ffe9a92
* Version Independent ID: d81cd846-91e6-dc59-57cc-c0a25ffe9a92
* Content: [Windows Admin Center network requirements](https://learn.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/network-requirements)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/deploy/network-requirements.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/manage/windows-admin-center/deploy/network-requirements.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @prasidharora
* Microsoft Alias: **praror**
*

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @jonaslewin

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting the 'Next Steps' links and will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day.
#please-close
