### ISSUE TITLE
"All releases of Windows Server since Windows Server 2016 are 64-bit only."

### ISSUE THREAD

**Issue by 29039** [MicrosoftDocs/windowsserverdocs#6930]
The page:
https://learn.microsoft.com/en-us/windows-server/get-started/upgrade-conversion-options

Says:
All releases of Windows Server since Windows Server 2016 are 64-bit only.

However, all releases of Windows Server since Windows Server **2008 R2** have been 64-bit only

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1b19ef8-a273-c1c8-18ff-7d29664bb9d2
* Version Independent ID: 8cf37a43-cff4-78de-0d66-2f482c022dc7
* Content: [Upgrade and conversion options for Windows Server](https://learn.microsoft.com/en-us/windows-server/get-started/upgrade-conversion-options)
* Content Source: [WindowsServerDocs/get-started/upgrade-conversion-options.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/upgrade-conversion-options.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @dknappettmsft
* Microsoft Alias: **daknappe**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @29039,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting the Windows Server edition where 64-bit only architectures became the mainstream. Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
