### ISSUE TITLE
It's so helpful.

### ISSUE THREAD

**Issue by nasir-dpi** [MicrosoftDocs/windowsserverdocs#6935]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa3950f2-42d8-a9e0-1fa3-92031db3c136
* Version Independent ID: 00967574-af37-27d8-e680-93ce3384bc62
* Content: [Plan for Hyper-V networking in Windows Server](https://learn.microsoft.com/en-us/windows-server/virtualization/hyper-v/plan/plan-hyper-v-networking-in-windows-server)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/plan/plan-hyper-v-networking-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/virtualization/hyper-v/plan/plan-hyper-v-networking-in-windows-server.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @robinharwood
* Microsoft Alias: **roharwoo**

**Comment by robinharwood** [comment]
Thanks for the lovely feedback @nasir-dpi.

#please-close
