### ISSUE TITLE
Link to Remote Desktop client for Windows does not work

### ISSUE THREAD

**Issue by DownBackDad** [MicrosoftDocs/windowsserverdocs#6940]
In the following section, the "Remote Desktop client for Windows" link does not work (takes you to a 404 error page).

====================
Important

We're no longer updating the Microsoft Store client with new features.

If you're connecting to Azure Virtual Desktop, for the best experience that includes the latest features and fixes, we recommend you download the [Remote Desktop client for Windows](https://learn.microsoft.com/en-us/azure/virtual-desktop/users/connect-windows.md) instead.
====================

The issue seems to be due to the ".md" at the end of the URL, if I remove that it goes to the appropriate page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: acc42a8f-2623-4352-7cc4-70f0f61e9d89
* Version Independent ID: 97d8b54b-5e7d-098b-4fb7-e8f6e0b30389
* Content: [Get started with the Microsoft Store Client](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windows)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windows.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/windows.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @DownBackDad,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting the link in question and will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close

**Comment by DownBackDad** [comment]
Thanks for the fix @Xelu86!
