### ISSUE TITLE
Server with no internet connection

### ISSUE THREAD

**Issue by jashamra** [MicrosoftDocs/windowsserverdocs#695]
Can I download the RDWebClient package and install this on a server which is not connected to internet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Service: **unspecified**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by davidbel** [comment]
@jashamra, in theory this should work although it's not a scenario we have tested yet. If you are interested, I'd say give it a try and send feedback to the email address found on the About page of the client.

You may need to ensure your DNS and certificates are setup appropriately.

**Comment by Kirbogd** [comment]
If it is regarding an ability to get module into isolated box - https://www.powershellgallery.com/packages/RDWebClientManagement/1.0.0 you can download module using PS> Save-Module -Name RDWebClientManagement -Path <path>
