### ISSUE TITLE
Netsh technical reference missing

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [MicrosoftDocs/windowsserverdocs#6951]
The link to the [Netsh Technical Reference](https://gallery.technet.microsoft.com/Netsh-Technical-Reference-c46523dc) is dead:
> ### Content availability
> 
> The Network Shell Technical Reference is available for download in Windows Help (*.chm) format from TechNet Gallery: [Netsh Technical Reference](https://gallery.technet.microsoft.com/Netsh-Technical-Reference-c46523dc)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cdf15d6d-c63e-6ec4-d1c0-bb800eec7f12
* Version Independent ID: 595b6b57-f169-e38d-35d7-91eaa3b33610
* Content: [Network Shell (Netsh)](https://learn.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh)
* Content Source: [WindowsServerDocs/networking/technologies/netsh/netsh.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/networking/technologies/netsh/netsh.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @DimitriPapadopoulos,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made to redirect users to our [netsh command reference](https://learn.microsoft.com/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc754516(v=ws.10)) as the other resource is no longer available. Changes will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close

**Comment by DimitriPapadopoulos** [comment]
The [netsh command reference](https://learn.microsoft.com/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc754516(v=ws.10)) you are referring to is obsolete (Windows 7, Windows Server 2008, Windows Server 2008 R2, Windows Vista) and is not consistent with current version of netsh. Please re-consider.
