### ISSUE TITLE
[FUNCTION REQUEST] Add customization key mapping for Remote Desktop Client for MacOS

### ISSUE THREAD

**Issue by wlyan** [MicrosoftDocs/windowsserverdocs#6953]
I want to map the CMD key to output a CTRL key on my Mac only when accessing the Microsoft Remote Desktop Connection for Mac application.

I know RDP client has remap some hotkeys like  CMD+C, CMD+V, and CMD+F，but other hotkeys like CMD+W still work unexpected, it will close RDP Client windows instead of close some app tab in RDP Client remote OS.

some extral link: https://learn.microsoft.com/en-us/answers/questions/447782/remote-desktop-connection-for-macos-how-to-remap-c.html

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @wlyan,

Thanks again for contacting Microsoft. We value your feedback.

GitHub isn't quite the right location or channel for feature requests. If you're running a Windows OS, we encourage you to use the [Feedback Hub](https://learn.microsoft.com/en-us/windows-insider/feedback-hub/feedback-hub-app). This can be accessed by going to: 

Start > _type_ Feedback Hub > Suggest a feature > provide your feedback.

You can also provide any feedback/suggestions for this product specifically by visiting our [AVD Feedback](https://techcommunity.microsoft.com/t5/azure-virtual-desktop-feedback/idb-p/AzureVirtualDesktop) page.

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
