### ISSUE TITLE
Typo - 3.1.1 instead of 3.11?

### ISSUE THREAD

**Issue by aakash-shah** [MicrosoftDocs/windowsserverdocs#6959]
Hello! I believe there is a typo at https://learn.microsoft.com/en-us/windows-server/storage/file-server/file-server-smb-overview#features-added-in-smb-311-with-windows-server-2016-and-windows-10-version-1607 where I believe it should state 3.1.1 and not 3.11 (based on the references to 3.1.1 under this item?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dca900b3-d060-8342-c545-a610d23157ef
* Version Independent ID: ab1fc94a-0c56-8fc7-9875-4cc119438512
* Content: [Overview of file sharing using the SMB 3 protocol in Windows Server](https://learn.microsoft.com/en-us/windows-server/storage/file-server/file-server-smb-overview)
* Content Source: [WindowsServerDocs/storage/file-server/file-server-smb-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/file-server/file-server-smb-overview.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @aakash-shah,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting this typo and changes will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
