### ISSUE TITLE
Windows Server 2022 / Ubuntu 20.04 and 22.04 / Processor compatibility mode/ "can't allocate initrd"

### ISSUE THREAD

**Issue by viceice** [MicrosoftDocs/windowsserverdocs#6964]
When running Ubuntu 20.04 or 22.04 on Windows Server 2022 with `Processor compatibility mode`[^1] enabled the Gen v2 VM won't boot and stops with "can't allocate initrd"[^2] error.

Even the normal `generic` kernel don't work. Using a Gen v1 VM works fine.

Opened this issue to get more attention because without enable `Processor compatibility mode` you can't do live migration to different servers. 😕 So this blocks me from upgrading my 2019 servers to 2022

[^1]: https://learn.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/processor-compatibility-mode-hyper-v
[^2]: https://techcommunity.microsoft.com/t5/windows-server-for-it-pro/server-2022-ubuntu-20-04-quot-can-t-allocate-initrd-quot/m-p/3116902
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84d52296-198d-7c8a-db99-e8cb336e355f
* Version Independent ID: 77670399-109f-3233-0466-c13d84542039
* Content: [Supported Ubuntu virtual machines on Hyper-V](https://learn.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-ubuntu-virtual-machines-on-hyper-v)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Supported-Ubuntu-virtual-machines-on-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/virtualization/hyper-v/Supported-Ubuntu-virtual-machines-on-Hyper-V.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @kkkashan
* Microsoft Alias: **kkashanjat**

**Comment by Xelu86** [comment]
Hey viceice,

Thanks for contacting Microsoft. We value your feedback.

We have made a documentation change to state the following:

> 12. In order to perform live migrations for VMs that are Generation 2 configured, the **Migrate to a physical computer with a different processor version** option must be enabled under *Processor* > *Compatibility* in your VM settings. To learn more, see [Processor compatibility mode in Hyper-V](../hyper-v/manage/processor-compatibility-mode-hyper-v.md).

Changes will be live after the next business day. We'll now be closing this thread, 

Thank you and have a most pleasant day. 
#please-close

**Comment by viceice** [comment]
this doesn't solve the problem, because when enable the migration feature the gen 2 VM won't boot at all (kernel panic).
