### ISSUE TITLE
Need Windows Desktop RDC

### ISSUE THREAD

**Issue by brmcmill** [MicrosoftDocs/windowsserverdocs#6965]
For some reason, the links/references to the Windows Desktop RDC is no longer referenced.  Should it be referenced back to here or at least it's own sub-page?

https://learn.microsoft.com/en-us/azure/virtual-desktop/whats-new-client-windows

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86f7187f-7e2e-da7f-6f46-46568be43db7
* Version Independent ID: 49714e7e-ecfb-dba3-f43a-17b6ca677fa6
* Content: [Remote Desktop clients for Remote Desktop Services and remote PCs - Windows Server](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-clients)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
Hey brmcmill,

Thanks for contacting Microsoft. We value your feedback.

The table has been updated to better clarify the Windows Store version of RDC. The link you're referencing is already part of the green "Tip" block taking users to the Windows Desktop version (which has moved to the Azure repo). 

Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
