### ISSUE TITLE
Bad Translation in windows-server/virtualization/hyper-v/hyper-v-technology-overview

### ISSUE THREAD

**Issue by PhilippRenner** [MicrosoftDocs/windowsserverdocs#6966]
Hi,

I found a bad translation in https://learn.microsoft.com/de-de/windows-server/virtualization/hyper-v/hyper-v-technology-overview
The original document is fine but the german document has some pointless things because of poor translation. How could I improve and correct these translations mistakes?

**Comment by Xelu86** [comment]
Hey @PhilippRenner,

Thanks again for contacting Microsoft. We value your feedback. 

From my understanding, any change we make to these documents will also change it for all available languages once published. Depending on the way the sentences are written, it may translate correctly or may need to be rewritten to make more sense in another language.

If you would like to propose a change, this can be performed via a pull request. Please see our [Contributor's Guide](https://learn.microsoft.com/en-us/contribute/#quick-edits-to-documentation) on how to contribute. If this is the method you'd like to use, please propose the change(s) needed and reply to this thread including your pull request #.

You can also let us know what area(s) could be improved for more clarity and how what is currently provided may not convey the intended information.

Thank you.

**Comment by Xelu86** [comment]
Hey @PhilippRenner,

Hope you're doing well. Kindly following up with you on issue #6966. Please let us know how we can further assist. 

Thank you.

**Comment by Xelu86** [comment]
Due to no response, we’ll now be closing this thread. If a documentation issue is still present, please consider opening a new issue. #please-close
