### ISSUE TITLE
Please correct point no 5. Its very misleading.

### ISSUE THREAD

**Issue by baghijee** [MicrosoftDocs/windowsserverdocs#6974]

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @baghijee, 

Thanks again for contacting Microsoft. We value your feedback. 

We're unable to determine what the intent of your question is as it isn't targeted towards any of our documents. If there are any errors or areas of improvement with our documentation, please let us know so we may better assist.

We're closing this issue but please feel free to reopen it and advise us what revisions may be needed. Thank you and have a most pleasant day. #please-close
