### ISSUE TITLE
Exact duplicate notes exist in this document

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/windowsserverdocs#6975]
![image](https://user-images.githubusercontent.com/118815227/213286359-36d74802-2187-40e2-a2dc-e8f372fc1cc4.png)

This part is unnecessarily repeated twice:

> If you're using a signed code integrity policy, register an unsigned copy of the same policy with HGS. The signature on code integrity policies is used to control updates to the policy, but is not measured into the host TPM and therefore cannot be attested to by HGS.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b0c7529a-9b0d-7cbc-0318-b6a542e934e5
* Version Independent ID: ecfa7f6f-df4b-7dfc-368c-d6cf1197d5fa
* Content: [Capture TPM-mode information required by HGS](https://learn.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-tpm-trusted-attestation-capturing-hardware#versioned-attestation-policies)
* Content Source: [WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-tpm-trusted-attestation-capturing-hardware.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/security/guarded-fabric-shielded-vm/guarded-fabric-tpm-trusted-attestation-capturing-hardware.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @HotCakeX,
 
Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made removing this duplicate note and will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close

**Comment by HotCakeX** [comment]
@Xelu86 Anytime, and you as well!
