### ISSUE TITLE
IF condition in second example is wrong as @isdir has never string value true

### ISSUE THREAD

**Issue by A-Mofi** [MicrosoftDocs/windowsserverdocs#698]
The **Examples** section contains as second example:

`forfiles /p c:\ /s /m *.* /c "cmd /c if @isdir==true echo @file is a directory"`

The case-sensitive **if** condition in this command line is never true because of **@isdir** has either string value **TRUE** or **FALSE**, but never _true_ or _false_. The value _true_ in this command line example should be corrected to **TRUE**. Alternatively it is possible to insert **/I** after **if** to do the string comparison case-insensitive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ebfe8b1-07af-a46f-d839-4ee4b15f55d1
* Version Independent ID: f96a4e35-724e-1bb0-1f6d-7c67ca500313
* Content: [forfiles](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/forfiles)
* Content Source: [WindowsServerDocs/administration/windows-commands/forfiles.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/forfiles.md)
* Service: **unspecified**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by lizap** [comment]
Thanks for the feedback - I've updated the article.
