### ISSUE TITLE
folder has disappeared

### ISSUE THREAD

**Issue by SairOOs** [MicrosoftDocs/windowsserverdocs#6988]
i use this code for Coping folders without files but when i press start, destination's folder has disappeared. I can find it by file explorer's address bar but can't see main folder and "Hidden item" is on.

`robocopy S:\  C:\Users\SairO\Desktop\P /E /DCOPY:DAT /R:10 /W:3 /ia:S`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **alalve**

**Comment by Xelu86** [comment]
Hey @SairOOs,

Thanks again for contacting Microsoft. We value your feedback.

As we understand it, you're describing an issue with the product compared to an issue with the documentation. GitHub isn't quite the right location or channel if searching for technical support, deeper specifics of the product or feature requests as it is completely outside our scope. If there are any issues within the content itself, such as incorrect code, verbiage, etc., please let us know.

Looking into our Technet forum, there is a post "[ROBOCOPY hides destination Directory](https://social.technet.microsoft.com/Forums/ie/en-US/8dcb6432-6ae0-4816-92e8-2599e5e638f5/robocopy-hides-destination-directory)".

In short, if you are to copy anything from the _root_ directory of a source folder (`S:\`), this causes the destination folder to have the "Hidden" attribute applied to it once it copies the content. I have tested several of the parameters, with changes, and the output is consistent in the destination folder becoming hidden. Copying data from the source folder not from the root of the device does not adopt the hidden attribute (`S:\SourceDirectory`) vs (`S:\`).

Below you'll find our support forums:
- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Something that you can do after running your command:
```
robocopy S:\ C:\Users\SairO\Desktop\P /E /DCOPY:DAT /R:10 /W:3 /ia:S
```
Is to run the following:
```
attrib -s -h C:\Users\SairO\Desktop\P
```
Or you can combine them both:
```
robocopy S:\ C:\Users\SairO\Desktop\P /E /DCOPY:DAT /R:10 /W:3 /ia:S & attrib -s -h C:\Users\SairO\Desktop\P
```

We're adding a note to this document to reflect the issue with copying from the _root_ device. We will also engage with the appropriate team to see if this is a bug.
 
This document has been updated and the changes will be live by the next business day. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
