### ISSUE TITLE
An error in the example

### ISSUE THREAD

**Issue by tomaszdubiel18** [MicrosoftDocs/windowsserverdocs#6998]
robocopy c:\reports '\\marketing\videos' yearly-report.mov /mt /z
When I try this on Windows 11, I get error with wrong formatted paths. There should be "\\marketing\videos", not '\\marketing\videos'

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **alalve**

**Comment by Xelu86** [comment]
#assign:xelu86
