### ISSUE TITLE
FAQ for Remote Desktop "Your connection was lost" (repeated) 

### ISSUE THREAD

**Issue by jeffblackadar** [MicrosoftDocs/windowsserverdocs#7001]
[Enter feedback here]
I request a FAQ to solve Remote Desktop "Your connection was lost" (repeated) please
Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3e3bc1ca-2fde-4a75-3583-fdb8ff2bf962
* Version Independent ID: 5cef2f0a-bed1-f05f-0f74-ba6f2808a714
* Content: [Remote Desktop clients FAQ](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-client-faq?source=recommendations)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.yml](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-client-faq.yml)
* Product: **windows-server**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by dksimpson** [comment]
Hi jeffblackadar,

Thanks for contacting Microsoft. We value your feedback. This issue appears to be already addressed in the documentation. 
However, if you believe there’s still a documentation concern, you're encouraged to open a new GitHub issue. We welcome any additional suggestions for improving our documentation to provide a more satisfactory experience in the future. Thanks for your understanding and continued support.

#please-close
