### ISSUE TITLE
Robocopy /DCOPY now has E and X flags - please include in doco

### ISSUE THREAD

**Issue by LUatWork** [MicrosoftDocs/windowsserverdocs#7004]
Robocopy /? has this:

> /DCOPY:copyflag[s] :: what to COPY for directories (default is /DCOPY:DA).
>                       (copyflags : D=Data, A=Attributes, T=Timestamps, **E**=EAs, **X**=Skip alt data streams).

Those 'E' and 'X' flags look new - please document them properly in this reference page?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **alalve**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @LUatWork,

Thanks again for contacting Microsoft. We value your feedback. 

This robocopy documentation already has these flags for **/DCOPY**. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
