### ISSUE TITLE
SCHTASKS documentation missing the 'OnEvent' schedule type

### ISSUE THREAD

**Issue by whoisrich** [MicrosoftDocs/windowsserverdocs#7005]
SCHTASKS /Create /?

SCHTASKS /Create /SC ONEVENT is an option not listed in this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0feda591-bda7-75e4-3eee-f38ec06f6f17
* Version Independent ID: f9f5b2ca-d26f-dd8a-70d1-0c07b94a4dd6
* Content: [schtasks create](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/schtasks-create)
* Content Source: [WindowsServerDocs/administration/windows-commands/schtasks-create.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/schtasks-create.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **alalve**

**Comment by Xelu86** [comment]
Hey whoisrich,

Thanks again for contacting Microsoft, we value your feedback. 

A documentation change has been made adding the ONEVENT schedule type and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
