### ISSUE TITLE
The link to the VLSC resources are dead.

### ISSUE THREAD

**Issue by jvanduvel** [MicrosoftDocs/windowsserverdocs#7014]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9acf4b99-84e9-0f78-6e26-16c9721bf927
* Version Independent ID: 3b9ba790-adbd-68c8-726b-033cb7a4a019
* Content: [Resolve Windows activation error codes](https://learn.microsoft.com/en-us/windows-server/get-started/activation-error-codes#0xc004c008-the-activation-server-determined-that-the-specified-product-key-could-not-be-used)
* Content Source: [WindowsServerDocs/get-started/activation-error-codes.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/activation-error-codes.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **kaushika**

**Comment by Xelu86** [comment]
Hey @jvanduvel,

Hope you're well. Wondering if this is a potential duplicate issue for the activation center by phone as found in #7015? Please let us know when possible. Thank you.

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by jvanduvel** [comment]
It's indeed a similar issue; however at a different page

**Comment by Xelu86** [comment]
Hey @jvanduvel,

Is the issue with the current page, https://learn.microsoft.com/en-us/Windows-Server/get-started/activation-error-codes ? I just finished going through all the hyperlinks on this page to make sure they're working.

If there is an issue with a different article that is not referenced in this page, please open a new GitHub issue for that page specifically. 

We await your response. Thank you.

**Comment by Xelu86** [comment]
Hey @jvanduvel,

We are closing this issue as we see no issue with the referenced page. Thank you and have a most pleasant day. 
#please-close
