### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by jvanduvel** [MicrosoftDocs/windowsserverdocs#7015]
[Enter feedback here]
https://www.microsoft.com/Licensing/existing-customer/activation-centers

these links are no longer valid and run dead

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9acf4b99-84e9-0f78-6e26-16c9721bf927
* Version Independent ID: 3b9ba790-adbd-68c8-726b-033cb7a4a019
* Content: [Resolve Windows activation error codes](https://learn.microsoft.com/en-us/windows-server/get-started/activation-error-codes#0xc004c008-the-activation-server-determined-that-the-specified-product-key-could-not-be-used)
* Content Source: [WindowsServerDocs/get-started/activation-error-codes.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/activation-error-codes.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @kaushika-msft
* Microsoft Alias: **kaushika**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @jvanduvel 

Thanks again for contacting Microsoft. We value your feedback. 

Looking over the documentation, all instances for the [Activation Centers](https://www.microsoft.com/Licensing/existing-customer/activation-centers) by phone is functional and the page is up:

![image](https://user-images.githubusercontent.com/103963494/217387098-0394086f-cc1b-4855-99e2-761a2a6c4123.png)

Verified that the remaining hyperlinks do redirect to the correct locations. As we do not see an issue with these current links, we will be closing this thread. Thank you and have a most pleasant day. 
#please-close
