### ISSUE TITLE
COLOR command explanations and actual behavior inconsistencies

### ISSUE THREAD

**Issue by Raziel-SSJ** [MicrosoftDocs/windowsserverdocs#7016]
Hello.
There are two inconsistencies with the actual behavior of my W11 CMD console.

> If` used without parameters, color restores the default Command Prompt window foreground and background colors.

- Using COLOR without parameters **don't** restore the default Command Prompt colors (which is unfortunate) **and** set ERRORLEVEL to 1

> If `<b>` and `<f>` are the same color value, the ERRORLEVEL is set to 1, and no change is made to either the foreground or the background color.

- Using the same color values **don't** set ERRORLEVEL to 1

Best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 959d4b23-8fd3-0404-f2b3-9397fbe9dce2
* Version Independent ID: e860e4fa-0075-7df0-0780-cb4f2c86ced3
* Content: [color](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/color)
* Content Source: [WindowsServerDocs/administration/windows-commands/color.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/color.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by craigcaseyMSFT** [comment]
Hello @Raziel-SSJ,

Thanks for contacting Microsoft. We value your feedback.

Though we couldn't replicate your issue, we saw some updating was necessary and documentation changes have been made to clarify and acknowledge this issue. The doc changes will be live after the next business day.

Thank you again and have a most pleasant day.
#please-close
