### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by FC-EricWeller** [MicrosoftDocs/windowsserverdocs#7018]
[The "See Also" content described as "Performance Considerations for Work Folders Deployments" provides a link only to the Storage at Microsoft blog (https://techcommunity.microsoft.com/t5/storage-at-microsoft/bg-p/FileCAB)]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d4132d5c-20d3-6ba3-3558-34c379c35229
* Version Independent ID: 3ac614ac-d52a-9c4e-4ac5-05ceafcd7a31
* Content: [Work Folders overview](https://learn.microsoft.com/en-us/windows-server/storage/work-folders/work-folders-overview)
* Content Source: [WindowsServerDocs/storage/work-folders/work-folders-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/work-folders/work-folders-overview.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @FC-EricWeller,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made concerning all affected links in the "See also" section and redirects will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
