### ISSUE TITLE
Majority of the links don't work

### ISSUE THREAD

**Issue by AlexcFrench** [MicrosoftDocs/windowsserverdocs#7019]
[Enter feedback here]
Hi, the majority of the links on this page take me to an RDS CALs page : 

(https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd851844(v=ws.11))

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 76fafc23-53f0-92a2-93e0-cbf721f4e6f9
* Version Independent ID: badf2f99-70a0-cb44-4717-c0659b8c0b8d
* Content: [BGP Windows PowerShell Command Reference](https://learn.microsoft.com/en-us/windows-server/remote/remote-access/bgp/bgp-windows-powershell-command-reference)
* Content Source: [WindowsServerDocs/remote/remote-access/bgp/BGP-Windows-PowerShell-Command-Reference.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-access/bgp/BGP-Windows-PowerShell-Command-Reference.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @AlexcFrench,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made updating all links to redirect to the correct PS cmdlets and will be live after the next business day. All cmdlets for BGP can be found in our PS repo for [Remote Access](https://learn.microsoft.com/en-us/powershell/module/remoteaccess/?view=windowsserver2022-ps). We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
