### ISSUE TITLE
Any update for Supported Windows guest operating systems for Hyper-V on Windows Server 2016?

### ISSUE THREAD

**Issue by comhlp** [MicrosoftDocs/windowsserverdocs#702]
As this document updated at last year, I am not sure that Windows Server 1709 is/isn't an Supported Windows guest operating systems for Hyper-V on Windows Server 2016. Please clarify & mention in this document. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db545402-d0df-dbfc-311a-b7b2f0cdbb2a
* Version Independent ID: 8255de57-a41a-0dbd-7197-3915ebb32ed2
* Content: [Supported Windows guest operating systems for Hyper-V on Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-windows-guest-operating-systems-for-hyper-v-on-windows#how-microsoft-provides-support-for-guest-operating-systems)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Supported-Windows-guest-operating-systems-for-Hyper-V-on-Windows.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/Supported-Windows-guest-operating-systems-for-Hyper-V-on-Windows.md)
* Service: **na**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by doctordns** [comment]
Any updates on this issue?

**Comment by cwilhit** [comment]
Hey there, docs have been amended to call out the SAC versions of Windows Server as supported guests. Since 1709 reached end of life back in April of this year, it's no longer supported. But you'll find Windows Server, version 1803 and Windows Server, version 1903 in the table, for example.
