### ISSUE TITLE
List of Commands for Windows Powershell

### ISSUE THREAD

**Issue by joepbord** [MicrosoftDocs/windowsserverdocs#7020]
I tried to find a list of Windows commands for the PowerShell but everytime I come on this website that is for Windows Server. This is what anyway is written in the first lines. I work with Window 11.
It seems as if MS don't want me to find or use the commands.
regards Joep
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6d382ca0-6538-5e1d-3e83-e31c9ab6a911
* Version Independent ID: 11eff296-6158-f89a-4941-8735529183e9
* Content: [Windows commands](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands#c)
* Content Source: [WindowsServerDocs/administration/windows-commands/windows-commands.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/windows-commands.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey @joepbord, 

Thanks again for contacting Microsoft. We value your feedback. 

On this page you're referencing:

**Command-line shells**
"Windows has two command-line shells: the Command shell and [PowerShell](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/powershell/scripting/overview)."

Once you click the "[PowerShell](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/powershell/scripting/overview)" hyperlink, it will take you out of the Windows Server repository to our PowerShell repository starting with the Overview. On the left side of the page, we have our TOC. If you expand the "Reference" tab at the bottom on the TOC, it will provide you the PS commands grouped per module type:

![image](https://user-images.githubusercontent.com/103963494/231845815-34045514-e0d6-4cdc-b949-fa2d1822f383.png)

If you go to the top of the TOC, "Version", and change it to 5.1, it will provide you with some additional commands for that version:

![image](https://user-images.githubusercontent.com/103963494/231848907-c931e3cb-dfba-4c99-8f17-4220fa1246cc.png)

We also have [Azure PowerShell](https://learn.microsoft.com/en-us/powershell/azure/?view=azps-9.6.0) documentation in the same style with commands found in the "Reference" tab as mentioned.

Learning modules for PowerShell can be found [here ](https://learn.microsoft.com/en-us/training/browse/?terms=Powershell) for your convenience.

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
