### ISSUE TITLE
Config for LSA in Endpoint Manager / Intune?

### ISSUE THREAD

**Issue by nb-ofs** [MicrosoftDocs/windowsserverdocs#7026]
Config for doing it in Endpoint Manager / Intune is missing
tried this - https://www.petervanderwoude.nl/post/easier-configuring-additional-lsa-protection/ and its not worked

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b04bc4d-9435-cdbc-429f-2433ada7bd37
* Version Independent ID: 5c902397-b2e7-4435-2b37-a57919434c9e
* Content: [Configuring Additional LSA Protection](https://learn.microsoft.com/en-us/windows-server/security/credentials-protection-and-management/configuring-additional-lsa-protection)
* Content Source: [WindowsServerDocs/security/credentials-protection-and-management/configuring-additional-lsa-protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/security/credentials-protection-and-management/configuring-additional-lsa-protection.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by stcs2309** [comment]
Does this only work on Win 11 22H2?
And why is the Integer set to 2 when in Peter's guide it's set to 1?

**Comment by stcs2309** [comment]
Nevermind, I see that 2 means without UEFI lock

**Comment by v-thepet** [comment]
Hello @nb-ofs,

Thank you for contacting Microsoft. We value your feedback.

We've updated the documentation to add this Intune admin center-based procedure for configuring LSA protection. The update will be live after the next business day.

We'll now be closing this thread. Thank you again for your contribution, and have a most pleasant day.

#please-close
