### ISSUE TITLE
Diskpart Shrink documentation is wrong

### ISSUE THREAD

**Issue by AH-SWG** [MicrosoftDocs/windowsserverdocs#7029]
[Enter feedback here]

Documentation says:

> Shrinks the selected volume to **_desiredsize_**

THIS IS WRONG!
The shrink command shrinks the volume **BY** **_desiredsize_**.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f91258c0-7929-4d60-3f88-e67c957584c6
* Version Independent ID: d952a74b-1f86-de68-df1e-1956ac045fc7
* Content: [Shrink a basic volume](https://learn.microsoft.com/en-us/windows-server/storage/disk-management/shrink-a-basic-volume)
* Content Source: [WindowsServerDocs/storage/disk-management/shrink-a-basic-volume.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/disk-management/shrink-a-basic-volume.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by v-thepet** [comment]
Hi @AH-SWG - Thanks for contacting Microsoft and for your valuable feedback.

A documentation change has been made implementing your corrections and will be live after the next business day. We will now be closing this thread.

Thank you and have a most pleasant day.
#please-close
