### ISSUE TITLE
Windows admin center

### ISSUE THREAD

**Issue by vileforte** [MicrosoftDocs/windowsserverdocs#703]
Olá instalei o windows admin center e quando abro o gerenciamento de cluster e tento visualizar os eventos de uma VM tenho o seguinte erro: websocket/powershell não conectado ou não configurado.

Alguém, poderia ajudar?

**Comment by jwwool** [comment]
Websockets can be broken by anything that routes or filters TCP traffic. Unfortunately due to this complexity, we cannot help troubleshoot WebSocket support in your environment.
