### ISSUE TITLE
it took a long time to convert windows server 2016 standard into windows server datacenter

### ISSUE THREAD

**Issue by heryhs** [MicrosoftDocs/windowsserverdocs#7035]
Hi

I'm converting a standard Windows Server 2016 license to a datacenter license on a virtual server with specifications 4 CPUs and 4 Memories and running on Red Hat OpenStack and this is a testing server, there is no data other than the default windows package but It took a long time to convert windows server 2016 standard into windows server datacenter. I have done this several times, it takes about 2 hours to finish.
Does it really take that long or is there something that makes the process longer?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1b19ef8-a273-c1c8-18ff-7d29664bb9d2
* Version Independent ID: 8cf37a43-cff4-78de-0d66-2f482c022dc7
* Content: [Upgrade and conversion options for Windows Server](https://learn.microsoft.com/en-us/windows-server/get-started/upgrade-conversion-options)
* Content Source: [WindowsServerDocs/get-started/upgrade-conversion-options.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/upgrade-conversion-options.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @dknappettmsft
* Microsoft Alias: **daknappe**

**Comment by Xelu86** [comment]
Hey heryhs,

Thanks again for contacting Microsoft. We value your feedback. 

License conversion times isn't something we can address or document given the numerous scenarios per user case. Every scenario would yield completely different results given the following:

- CPU type, speed, amount, cores & threads
- RAM type, speed, amount
- Storage type & speed
- The physical hardware health
- Physical vs Virtual environments

Looking into our own forums and several external forums, users have stated that the conversion process for the majority took 1 - 4 hours (no percentage given). As we don't have hard data into each setup environment, this information isn't documented as it can greatly vary. Your scenario falls into the majority timeframe.

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
