### ISSUE TITLE
Defrag.exe /b

### ISSUE THREAD

**Issue by AlexeyKhrenov** [MicrosoftDocs/windowsserverdocs#7037]
As for the docs for **Defrag.exe**
_WindowsServerDocs/administration/windows-commands/defrag.md_
we have some legacy project that passes **/b** parameter to the executable, which is undocumented. Is it some obsolete feature? There's no info on the net anymore

**Comment by Xelu86** [comment]
Hey AlexeyKhrenov,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding the `/b` parameter and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
