### ISSUE TITLE
Typo in Question 3

### ISSUE THREAD

**Issue by MSFT-davidgregory** [MicrosoftDocs/windowsserverdocs#7038]
Question 3 has a typo:

Incorrect: I’m registering Hybrid AADJ devices using AD FS device claims. How do I allow devices to continue to complete their hybrid aadj process with AD FS?

Correct: I’m registering Hybrid Azure AD Join devices using AD FS device claims. How do I allow devices to continue to complete their Hybrid Azure AD Join process **without** AD FS?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 967cf275-c5f8-b0f2-b17a-66bc137dcf98
* Version Independent ID: 967cf275-c5f8-b0f2-b17a-66bc137dcf98
* Content: [AD FS to Azure AD FAQ](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/decommission/ad-fs-to-azure-ad-faq?source=docs)
* Content Source: [WindowsServerDocs/identity/ad-fs/decommission/ad-fs-to-azure-ad-faq.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/decommission/ad-fs-to-azure-ad-faq.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @MSFT-davidgregory,

A documentation change has been made expanding the AADJ acronym for more clarity. Alternate product names are as follows:

- AADJ
- Azure AD Joined
- Aure Active Directory Joined

Changes will be live after the next business day. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
