### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by TXbluzmn** [MicrosoftDocs/windowsserverdocs#705]
The link at the top of this article for "plan to move your virtual machine to Azure" that points here: 
https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-questions/ 
gives a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f754d56c-0290-d582-ba2c-b3f0dcc13866
* Version Independent ID: f3062eb0-c4d0-a637-675e-f867ea934877
* Content: [Should I create a generation 1 or 2 virtual machine in Hyper-V?](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/plan/should-i-create-a-generation-1-or-2-virtual-machine-in-hyper-v)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/plan/Should-I-create-a-generation-1-or-2-virtual-machine-in-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/plan/Should-I-create-a-generation-1-or-2-virtual-machine-in-Hyper-V.md)
* Service: **na**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by illfated** [comment]
Resolved in commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/5f8470ee6f04ab62cdecbb860b39b1edc0a8b4e1 (https://github.com/MicrosoftDocs/windowsserverdocs/commit/5f8470ee6f04ab62cdecbb860b39b1edc0a8b4e1#diff-b098257b8a1a5d5165066e59cceb19cd) via PrivateRepo #876 .

**Comment by illfated** [comment]
#please-close
