### ISSUE TITLE
Feedback: Add a page for the Windows Desktop RDC

### ISSUE THREAD

**Issue by brmcmill** [MicrosoftDocs/windowsserverdocs#7052]
Hello!  I think it will help if this docs area also includes the Windows Desktop RDC.  The Windows Store client, while functional, does not have a lot of the same features that the Windows Desktop RDC has.  The addition could be similar to the one under the AVD Docs:

[Connect to Azure Virtual Desktop with the Remote Desktop client for Windows](https://learn.microsoft.com/en-us/azure/virtual-desktop/users/connect-windows?tabs=subscribe)

Also this page referencing the AVD client on the Store site is invalid:
[What's new in the Remote Desktop Microsoft Store client](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windows-whatsnew)

![image](https://user-images.githubusercontent.com/26752719/229307643-14b76a40-cb97-40be-9070-a294e8a62c1e.png)

Should be updated with the one above.

Thanks!

- Brandon

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86f7187f-7e2e-da7f-6f46-46568be43db7
* Version Independent ID: 49714e7e-ecfb-dba3-f43a-17b6ca677fa6
* Content: [Remote Desktop clients for Remote Desktop Services and remote PCs - Windows Server](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-clients)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
Hey brmcmill,

Thanks again for contacting Microsoft. We value your feedback. 

This doc page looked quite different at the time this issue was generated. We have updated the broken links on this page and it should direct users to the proper pages per the link you provided. Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
