### ISSUE TITLE
"Domain Guests" is not protected by AdminSDHolder

### ISSUE THREAD

**Issue by JimSycurity** [MicrosoftDocs/windowsserverdocs#7056]
This document incorrectly states that the well-known security group "Domain Guests" is Protected by AdminSDHolder.  It's not and never has been.

Domain Guests portion:
https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/understand-security-groups#domain-guests

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3489e3cf-5323-1d4d-9250-081af0abb2f7
* Version Independent ID: 3489e3cf-5323-1d4d-9250-081af0abb2f7
* Content: [Active Directory security groups](https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/understand-security-groups)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/understand-security-groups.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-ds/manage/understand-security-groups.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @Dansimp
* Microsoft Alias: **alalve**

**Comment by Xelu86** [comment]
Hey @JimSycurity,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting this and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
