### ISSUE TITLE
Page lacks necessary information to configure

### ISSUE THREAD

**Issue by tobyhorton** [MicrosoftDocs/windowsserverdocs#7057]
There's no mention at all about the redirect URI for this to enable authorization of the app.

It appears impossible to use this documentation to configure the feature without some significant deeper knowledge that's not covered here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d25e426f-b6ed-c9db-1b8f-4c755789e0a6
* Version Independent ID: d25e426f-b6ed-c9db-1b8f-4c755789e0a6
* Content: [Get started with Windows LAPS and Azure Active Directory](https://learn.microsoft.com/en-us/windows-server/identity/laps/laps-scenarios-azure-active-directory)
* Content Source: [WindowsServerDocs/identity/laps/laps-scenarios-azure-active-directory.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/laps/laps-scenarios-azure-active-directory.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @jay98014
* Microsoft Alias: **jsimmons**

**Comment by jay98014** [comment]
Hi @tobyhorton  - for Powershell-based authentication, which is what the Get-LapsAADPassword cmdlet requires, you should not specify a Redirect uri.

**Comment by IT-Daniel** [comment]
Hi @tobyhorton I just managed to get It work. Just go to the App > Authentication > Add a platform > Mobile and desktop applications > https://login.microsoftonline.com/common/oauth2/nativeclient

It should work with it.
