### ISSUE TITLE
help.coinbase.com

### ISSUE THREAD

**Issue by mspaansen** [MicrosoftDocs/windowsserverdocs#7058]
https://m.youtube.com/watch?ref=S7REL07T&utm_source=BinanceInstagram&utm_medium=GlobalSocial&utm_campaign=GlobalSocial&fbclid=PAAaZLtyWO6we8UyTTb52svbLtVUmYw9u9uWTvM7V0nuaKhxAcsJAOVQsxa-o&v=Z8whvrnEtbo&feature=youtu.be#dialog

**Comment by InitialSupport** [comment]
We'd be happy to look into this for you.
Kindly file a support ticket here
https://forms.gle/xABEcR5MwDBJAm1c6

**Comment by CustomerTeam001** [comment]
@mspaansen We'd be happy to look into this for you 
Kindly file a support ticket below 
https://forms.gle/VcaSaDQysAwZBQp77

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
#please-close
