### ISSUE TITLE
Typo in the Doc

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/windowsserverdocs#7061]
...Similarly, because **"installdns** has a default value of $False if you install a domain controller in an environment...

it's missing a closing double quotes.

![image](https://user-images.githubusercontent.com/118815227/219682535-13156587-8c4d-4372-95f5-9fafae9e5df7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3514f314-5a3b-df0a-2841-3639f54d1990
* Version Independent ID: 64ffa657-61ee-ad60-614c-278cfcec0b84
* Content: [Install Active Directory Domain Services (Level 100)](https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/install-active-directory-domain-services--level-100-)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/Install-Active-Directory-Domain-Services--Level-100-.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-ds/deploy/Install-Active-Directory-Domain-Services--Level-100-.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by Xelu86** [comment]
#assign:xelu86

**Comment by Xelu86** [comment]
Hey @HotCakeX,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made removing the quote and placing the hyphen for the cmdlet in question along with correcting the verbiage to maintain consistency. Changes will be live after the next business day. 

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
