### ISSUE TITLE
TCP Connection Limit missing

### ISSUE THREAD

**Issue by dhenson02** [MicrosoftDocs/windowsserverdocs#7062]
Been looking everywhere for TCP connection limit numbers and the only one I've found is for Windows 10 Pro with 20 connections (from a forum post's multiple replies).  After using Server 2019 Standard, I've notice the same indications of this limitation, but would very much like to confirm with official documentation.  Does this information no longer exist?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e477d8d-7469-cd57-29a9-13135b164311
* Version Independent ID: 73fb5866-3a3e-8cde-f39f-c2677de6d326
* Content: [Comparison of Standard and Datacenter editions Windows Server 2019](https://learn.microsoft.com/en-us/windows-server/get-started/editions-comparison-windows-server-2019?source=recommendations&tabs=full-comparison)
* Content Source: [WindowsServerDocs/get-started/editions-comparison-windows-server-2019.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/editions-comparison-windows-server-2019.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @JasonGerend
* Microsoft Alias: **alalve**

**Comment by Xelu86** [comment]
Hey dhenson02,

Thanks again for contacting Microsoft. We value your feedback. 

TCP connection limit is not an item to be included into this page. There are some parameters and factors that can influence the maximum number of TCP connections that Windows Server can support, such as:

- **TcpNumConnections** - a registry value that limits the maximum number of connections that TCP may have open simultaneously. Default value of this parameter is 16,777,214 (0x00fffffe), which is quite generous and unlikely to be reached.
- **Maximum Transmission Unit (MTU)** - the maximum size of a packet that can be transmitted over a network without fragmentation which depends on the lower layers of the network (Ethernet) which have their own limitations.
- **TCP congestion control** - the mechanism that adjusts the rate of data transmission based on the network conditions, such as bandwidth, latency, and packet loss. TCP congestion control aims to avoid overloading the network and causing congestion collapse.

To learn more about the modifying registry settings for TCP, please see https://learn.microsoft.com/en-us/troubleshoot/windows-client/networking/tcpip-and-nbt-configuration-parameters (these also relates to current versions).

If you're experiencing a TCP connection issue, that is outside our scope to assist, we kindly ask that you use one of the following:

- Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
- Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

Hopefully a community expert can provide additional support.

**Comment by v-thepet** [comment]
#please-close
