### ISSUE TITLE
Examples would be nice - I would look at them first and ignore everything else

### ISSUE THREAD

**Issue by dlwiii** [MicrosoftDocs/windowsserverdocs#7069]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **alalve**

**Comment by Xelu86** [comment]
Hey dlwiii,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding several examples and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
