### ISSUE TITLE
Bug or need for escaping in UserContainer

### ISSUE THREAD

**Issue by mbaladi** [MicrosoftDocs/windowsserverdocs#708]
In the above example for Add-AdfsLocalClaimsProviderTrust, the UserContainer parameter is set to "CN=VendorsContainer...". In my existing production directory (AD DS), I have existing users in an OU with a space in the name such as "OU=Vendors Container,....". In ADFS trace I can see that ADFS translates this to "OU=Vendors%20Container" in the LDAP query and the LDAP server can't find a result. AFAIK, only leading/trailing spaces should be escaped in LDAP so I think this is a bug in ADFS. In the ADFS event log I get errors with event id 342 and 364, both with an LDAP error "Microsoft.IdentityServer.ClaimsPolicy.Engine.AttributeStore.Ldap.LdapServerOperationException: The object does not exist. Error code: NoSuchObject Server response message: 0000208D: NameErr: DSID-03100213, problem 2001 (NO_OBJECT), data 0". If I create a new OU without space and move a user, all works as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce6494d8-d525-8961-8dff-c5ee55a18849
* Version Independent ID: a3608a5f-26ed-1a93-2cd2-2fe2e5238248
* Content: [Configure AD FS to authenticate users stored in LDAP directories](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-to-authenticate-users-stored-in-ldap-directories#feedback)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-to-authenticate-users-stored-in-LDAP-directories.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Configure-AD-FS-to-authenticate-users-stored-in-LDAP-directories.md)
* Service: **unspecified**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by fish30** [comment]
Was there any update to the space in a LDAP organization or ou sent as %20 in the LDAP query?  I too have the same issue and removing the space isn't an option at this time.

**Comment by mbaladi** [comment]
Microsoft acknowledged that this is a bug in in ADFSv4 and decided **not** to fix this in Windows Server 2016, but maybe in a future release. We ended up changing all customer's app configurations and user management utils to point to a container without a space in the name. I  have not yet tested if this is fixed in new ADFS (Windows Server 2019).
