### ISSUE TITLE
Remove "PowerShell 5.1 or later" from Prerequisites

### ISSUE THREAD

**Issue by ajf8729** [MicrosoftDocs/windowsserverdocs#7088]
PowerShell 5.1 is listed as a prereq for upgrading Windows Server, however, there is a known issue when upgrading 2012 R2 with WMF 5.1 installed that causes WMI migration to fail, which can cause serious issues if ConfigMgr is installed. Also, WMF 5.1 is already present on 2016+, so it is no longer needed to check there anyway.

Docs stating to uninstall WMF 5.1 on 2012 R2 pre-upgrade: https://learn.microsoft.com/en-us/mem/configmgr/core/servers/manage/upgrade-on-premises-infrastructure#before-upgrade

The specific WMI issue caused by having WMF 5.1 present during upgrade: https://learn.microsoft.com/en-us/troubleshoot/mem/configmgr/os-deployment/task-sequence-stops-after-in-place-upgrade

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26a28fb3-5359-dcd1-7361-64deec4f1fd5
* Version Independent ID: fd95c553-bd8d-f060-5bfe-ad5b69ab1216
* Content: [Perform an in-place upgrade of Windows Server](https://learn.microsoft.com/en-us/windows-server/get-started/perform-in-place-upgrade#prerequisites)
* Content Source: [WindowsServerDocs/get-started/perform-in-place-upgrade.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/perform-in-place-upgrade.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @robinharwood
* Microsoft Alias: **roharwoo**

**Comment by v-thepet** [comment]
Hi @ajf8729, 

Thanks for contacting Microsoft. We value your feedback.

Documentation changes have been made to address this issue and are now live. We will now be closing this thread.

Thank you and have a most pleasant day.
#please-close
