### ISSUE TITLE
Issues with Pushing Custom Role Based Access Control to systems remotely 

### ISSUE THREAD

**Issue by jsims-af247** [MicrosoftDocs/windowsserverdocs#709]
When attempting to push a custom Role Based Access control to other systems in the domain as suggested [here](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/configure/using-extensions) the Script fails to generate the InstalJeaFeature directory and files required to push the DSC configuration. However when running the same script from the console it deploys without issue. Scripts are listed below for reference.

<details><summary>InstallJeaFeature.ps1</summary>
<code>Configuration InstallJeaFeature
{
    Import-DscResource -ModuleName PSDesiredStateConfiguration, JustEnoughAdministration

    File MicrosoftSMECertificateManager-Module 
    {
        SourcePath = Join-Path $ConfigurationData.ModuleBasePath.Source "Microsoft.SME.CertificateManager"
        DestinationPath = Join-Path $ConfigurationData.ModuleBasePath.Destination "Microsoft.SME.CertificateManager"
        Checksum = "SHA-1"
        Ensure = "Present"
        Force = $true
        Type = "Directory"
        Recurse = $true
    }

    File MicrosoftSMEDeviceManager-Module
    {
        SourcePath = Join-Path $ConfigurationData.ModuleBasePath.Source "Microsoft.SME.DeviceManager"
        DestinationPath = Join-Path $ConfigurationData.ModuleBasePath.Destination "Microsoft.SME.DeviceManager"
        Checksum = "SHA-1"
        Ensure = "Present"
        Force = $true
        Type = "Directory"
        Recurse = $true
    }

    File MicrosoftSMEEventViewer-Module
    {
        SourcePath = Join-Path $ConfigurationData.ModuleBasePath.Source "Microsoft.SME.EventViewer"
        DestinationPath = Join-Path $ConfigurationData.ModuleBasePath.Destination "Microsoft.SME.EventViewer"
        Checksum = "SHA-1"
        Ensure = "Present"
        Force = $true
        Type = "Directory"
        Recurse = $true
    }

    File MicrosoftSMEFailoverCluster-Module
    {
        SourcePath = Join-Path $ConfigurationData.ModuleBasePath.Source "Microsoft.SME.FailoverCluster"
        DestinationPath = Join-Path $ConfigurationData.ModuleBasePath.Destination "Microsoft.SME.FailoverCluster"
        Checksum = "SHA-1"
        Ensure = "Present"
        Force = $true
        Type = "Directory"
        Recurse = $true
    }

    File MicrosoftSMEFileExplorer-Module
    {
        SourcePath = Join-Path $ConfigurationData.ModuleBasePath.Source "Microsoft.SME.FileExplorer"
        DestinationPath = Join-Path $ConfigurationData.ModuleBasePath.Destination "Microsoft.SME.FileExplorer"
        Checksum = "SHA-1"
        Ensure = "Present"
        Force = $true
        Type = "Directory"
        Recurse = $true
    }

    File MicrosoftSMEFirewall-Module
    {
        SourcePath = Join-Path $ConfigurationData.ModuleBasePath.Source "Microsoft.SME.Firewall"
        DestinationPath = Join-Path $ConfigurationData.ModuleBasePath.Destination "Microsoft.SME.Firewall"
        Checksum = "SHA-1"
        Ensure = "Present"
        Force = $true
        Type = "Directory"
        Recurse = $true
    }

    File MicrosoftSMEHyperV-Module
    {
        SourcePath = Join-Path $ConfigurationData.ModuleBasePath.Source "Microsoft.SME.HyperV"
        DestinationPath = Join-Path $ConfigurationData.ModuleBasePath.Destination "Microsoft.SME.HyperV"
        Checksum = "SHA-1"
        Ensure = "Present"
        Force = $true
        Type = "Directory"
        Recurse = $true
    }

    File MicrosoftSMELocalUsersGroups-Module
    {
        SourcePath = Join-Path $ConfigurationData.ModuleBasePath.Source "Microsoft.SME.LocalUsersGroups"
        DestinationPath = Join-Path $ConfigurationData.ModuleBasePath.Destination "Microsoft.SME.LocalUsersGroups"
        Checksum = "SHA-1"
        Ensure = "Present"
        Force = $true
        Type = "Directory"
        Recurse = $true
    }

    File MicrosoftSMENetworkSettings-Module
    {
        SourcePath = Join-Path $ConfigurationData.ModuleBasePath.Source "Microsoft.SME.NetworkSettings"
        DestinationPath = Join-Path $ConfigurationData.ModuleBasePath.Destination "Microsoft.SME.NetworkSettings"
        Checksum = "SHA-1"
        Ensure = "Present"
        Force = $true
        Type = "Directory"
        Recurse = $true
    }

    File MicrosoftSMEProcessViewer-Module
    {
        SourcePath = Join-Path $ConfigurationData.ModuleBasePath.Source "Microsoft.SME.ProcessViewer"
        DestinationPath = Join-Path $ConfigurationData.ModuleBasePath.Destination "Microsoft.SME.ProcessViewer"
        Checksum = "SHA-1"
        Ensure = "Present"
        Force = $true
        Type = "Directory"
        Recurse = $true
    }

    File MicrosoftSMERegistryEditor-Module
    {
        SourcePath = Join-Path $ConfigurationData.ModuleBasePath.Source "Microsoft.SME.RegistryEditor"
        DestinationPath = Join-Path $ConfigurationData.ModuleBasePath.Destination "Microsoft.SME.RegistryEditor"
        Checksum = "SHA-1"
        Ensure = "Present"
        Force = $true
        Type = "Directory"
        Recurse = $true
    }

    File MicrosoftSMERolesFeatures-Module
    {
        SourcePath = Join-Path $ConfigurationData.ModuleBasePath.Source "Microsoft.SME.RolesFeatures"
        DestinationPath = Join-Path $ConfigurationData.ModuleBasePath.Destination "Microsoft.SME.RolesFeatures"
        Checksum = "SHA-1"
        Ensure = "Present"
        Force = $true
        Type = "Directory"
        Recurse = $true
    }

    File MicrosoftSMEServerManager-Module
    {
        SourcePath = Join-Path $ConfigurationData.ModuleBasePath.Source "Microsoft.SME.ServerManager"
        DestinationPath = Join-Path $ConfigurationData.ModuleBasePath.Destination "Microsoft.SME.ServerManager"
        Checksum = "SHA-1"
        Ensure = "Present"
        Force = $true
        Type = "Directory"
        Recurse = $true
    }

    File MicrosoftSMEServiceViewer-Module
    {
        SourcePath = Join-Path $ConfigurationData.ModuleBasePath.Source "Microsoft.SME.ServiceViewer"
        DestinationPath = Join-Path $ConfigurationData.ModuleBasePath.Destination "Microsoft.SME.ServiceViewer"
        Checksum = "SHA-1"
        Ensure = "Present"
        Force = $true
        Type = "Directory"
        Recurse = $true
    }

    File MicrosoftSMEStorage-Module
    {
        SourcePath = Join-Path $ConfigurationData.ModuleBasePath.Source "Microsoft.SME.Storage"
        DestinationPath = Join-Path $ConfigurationData.ModuleBasePath.Destination "Microsoft.SME.Storage"
        Checksum = "SHA-1"
        Ensure = "Present"
        Force = $true
        Type = "Directory"
        Recurse = $true
    }

    File MicrosoftSMEWindowsUpdate-Module
    {
        SourcePath = Join-Path $ConfigurationData.ModuleBasePath.Source "Microsoft.SME.WindowsUpdate"
        DestinationPath = Join-Path $ConfigurationData.ModuleBasePath.Destination "Microsoft.SME.WindowsUpdate"
        Checksum = "SHA-1"
        Ensure = "Present"
        Force = $true
        Type = "Directory"
        Recurse = $true
    }

    File MicrosoftSMEShell-Module
    {
        SourcePath = Join-Path $ConfigurationData.ModuleBasePath.Source "Microsoft.SME.Shell"
        DestinationPath = Join-Path $ConfigurationData.ModuleBasePath.Destination "Microsoft.SME.Shell"
        Checksum = "SHA-1"
        Ensure = "Present"
        Force = $true
        Type = "Directory"
        Recurse = $true
    }

    File MS-RoleCapabilities-Module
    {
        SourcePath = Join-Path $ConfigurationData.ModuleBasePath.Source "WindowsAdminCenter.Jea"
        DestinationPath = Join-Path $ConfigurationData.ModuleBasePath.Destination "WindowsAdminCenter.Jea"
        Checksum = "SHA-1"
        Ensure = "Present"
        Force = $true
        Type = "Directory"
        Recurse = $true
    }

    JeaEndpoint Endpoint
    {
        Ensure = "Present"
        EndpointName = "Microsoft.Sme.PowerShell"
        RoleDefinitions = "@{ '$env:Domain\WAC Admins' = @{ RoleCapabilities = 'MS-Administrators', 'MS-Hyper-V-Administrators', 'MS-Readers' }; '$env:Domain\WAC Hyper-V Admins' = @{ RoleCapabilities = 'MS-Hyper-V-Administrators', 'MS-Readers' }; '$env:Domain\WAC Viewers' = @{ RoleCapabilities = 'MS-Readers' } }"
        DependsOn = "[File]MicrosoftSMECertificateManager-Module", "[File]MicrosoftSMEDeviceManager-Module", "[File]MicrosoftSMEEventViewer-Module", "[File]MicrosoftSMEFailoverCluster-Module", "[File]MicrosoftSMEFileExplorer-Module", "[File]MicrosoftSMEFirewall-Module", "[File]MicrosoftSMEHyperV-Module", "[File]MicrosoftSMELocalUsersGroups-Module", "[File]MicrosoftSMENetworkSettings-Module", "[File]MicrosoftSMEProcessViewer-Module", "[File]MicrosoftSMERegistryEditor-Module", "[File]MicrosoftSMERolesFeatures-Module", "[File]MicrosoftSMEServerManager-Module", "[File]MicrosoftSMEServiceViewer-Module", "[File]MicrosoftSMEStorage-Module", "[File]MicrosoftSMEWindowsUpdate-Module", "[File]MicrosoftSMEShell-Module", "[File]MS-RoleCapabilities-Module"
    }
}

Copy-Item "$PSScriptRoot\JustEnoughAdministration" "$env:ProgramFiles\WindowsPowerShell\Modules" -Recurse -Force

$ConfigData = @{
    AllNodes = @()
    ModuleBasePath = @{
        Source = "$PSScriptRoot\Modules"
        Destination = "$env:ProgramFiles\WindowsPowerShell\Modules"
    }
}

InstallJeaFeature -ConfigurationData $ConfigData | Out-Null
Start-DscConfiguration -Path "$PSScriptRoot\InstallJeaFeature" -JobName "Installing JEA for Windows Admin Center" -Force</code>
</details>
<p></p>
<details><summary>Push-InstallJeaFeature.ps1</summary>
<code>
$ComputersToConfigure = Get-ADComputer -Filter * -SearchBase 'OU=Servers,DC=DOMAIN,DC=COM' -SearchScope Subtree | select-object -expandproperty name

$ComputersToConfigure | ForEach-Object {
    $session = New-PSSession -ComputerName $_ -ErrorAction Stop
    Copy-Item -Path "~\Desktop\WindowsAdminCenter_RBAC\JustEnoughAdministration\" -Destination "$env:ProgramFiles\WindowsPowerShell\Modules\" -ToSession $session -Recurse -Force
    Copy-Item -Path "~\Desktop\WindowsAdminCenter_RBAC" -Destination "$env:TEMP\WindowsAdminCenter_RBAC" -ToSession $session -Recurse -Force
    Invoke-Command -Session $session -ScriptBlock { Import-Module JustEnoughAdministration; & "$env:TEMP\WindowsAdminCenter_RBAC\InstallJeaFeature.ps1" } -AsJob -Verbose
    Disconnect-PSSession $session
}</code>
</details>

**Comment by jwwool** [comment]
@rpsqrd can you please take a look?

**Comment by rpsqrd** [comment]
Hey James,

Sorry to hear you're having trouble with this. Just to clarify, you're doing an enterprise wide deployment right? Is the script that had issues the one on our website, or the one that comes from the package you download from Windows Admin Center?

Ryan

**Comment by jsims-af247** [comment]
Yes this would be deployed across out environment. The Script was downloaded from the Windows Admin Center Gateway and Modified as specified in the Role Based Access Control [Link](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/configure/using-extensions).

**Comment by jsims-af247** [comment]
Is there any additional information I can provide to you on this?

**Comment by rpsqrd** [comment]
Do you see an error when it fails to generate the DSC configuration or does it just fail silently? You've also copied the JustEnoughAdministration PowerShell module onto the remote machines, correct?
