### ISSUE TITLE
Wrong parameter in PS command?

### ISSUE THREAD

**Issue by runemy** [MicrosoftDocs/windowsserverdocs#71]
Hi

In: https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v-virtual-switch/RDMA-and-Switch-Embedded-Teaming.md#changing-the-load-distribution-algorithm-for-a-set-team

It's written `Set-VMSwitchTeam -Name TeamedvSwitch -VMSwitchLoadBalancingAlgorithm Dynamic`

I cannot find the parameter `VMSwitchLoadBalancingAlgorithm` in Set-VMSwitchTeam, but I can find `LoadBalancingAlgorithm`

**Comment by lizap** [comment]
Thanks for pointing this out - I'll research and update the article.

Liza
