### ISSUE TITLE
no examples ?!

### ISSUE THREAD

**Issue by JossBoulement** [MicrosoftDocs/windowsserverdocs#7114]
examples whould be very helpfull !!!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d98186ad-af7e-d25d-2135-f0c65ffd5288
* Version Independent ID: 55c29643-935f-7eab-6a3a-8814f96e8669
* Content: [mount](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/mount)
* Content Source: [WindowsServerDocs/administration/windows-commands/mount.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/mount.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey JossBoulement,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding examples for the `mount` command and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
