### ISSUE TITLE
Incomplete descriptions are useless

### ISSUE THREAD

**Issue by ZBB-XD** [MicrosoftDocs/windowsserverdocs#7116]
Most of the parameter descriptions are incomplete, and thus they are useless. the description of /s essentially means nothing, for we don't know _how_ the string is modified by the command. The same for the pipe/to file commands. Please write more exhaustive descriptions, or at least provide a link to a website who has done the work already (I haven't been able to find one, which is why I am writing to you now).

Thank you and have a good day!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0df94452-999b-43a0-be42-722fbabedaf3
* Version Independent ID: 84206d79-507f-b562-9d3f-cc3683b7abe6
* Content: [cmd](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/cmd)
* Content Source: [WindowsServerDocs/administration/windows-commands/cmd.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/cmd.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by v-thepet** [comment]
Hello @ZBB-XD,

Thanks for contacting Microsoft. We value your feedback.

Documentation changes have been made to clarify the Parameters and Remarks and will be live after the next business day. We will now be closing this thread.

Thank you and have a most pleasant day.
#please-close
