### ISSUE TITLE
Missing "GET" environment variable.  Demonstrates how to set the variables, no mention of GET.  I'm lost.

### ISSUE THREAD

**Issue by DrStein99** [MicrosoftDocs/windowsserverdocs#7121]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: beaee6aa-060a-58d2-a474-b47b3ac89f9e
* Version Independent ID: bae22319-b13a-63f8-6da4-6411fece9f91
* Content: [set](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/set_1#examples)
* Content Source: [WindowsServerDocs/administration/windows-commands/set_1.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/set_1.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey DrStein99,

Thanks again for contacting Microsoft. We value your feedback. 

The command you're thinking of is `set`. If you run `set`, it will display all the environment variables on the current device:

![image](https://github.com/MicrosoftDocs/windowsserverdocs/assets/103963494/f83e575e-a49f-422c-9b95-e7b896690363)

We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
