### ISSUE TITLE
Incorrect Link

### ISSUE THREAD

**Issue by stryqx** [MicrosoftDocs/windowsserverdocs#7153]
The link to the 10 Immutable Laws of Security (v2.0) isn't correct, it should be:
[https://learn.microsoft.com/en-us/security/zero-trust/ten-laws-of-security#immutable-laws-of-security-v2](url)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ca929d6b-746d-f20a-8902-4e93a69ab8d8
* Version Independent ID: 88e13a93-f80b-d07b-cfaa-ab38205148e0
* Content: [Securing Domain Controllers Against Attack](https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/securing-domain-controllers-against-attack)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Securing-Domain-Controllers-Against-Attack.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Securing-Domain-Controllers-Against-Attack.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by Xelu86** [comment]
Hey @stryqx,

Thanks again for contacting Microsoft. We value your feedback.

A documentation change has been made correcting the link in question and will be live after the next business day. We will now be closing this thread.

Thank you and have a most pleasant day.
#please-close
