### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by StegemannDominik** [MicrosoftDocs/windowsserverdocs#7155]
[Enter feedback here]
Hi everyone

`nslookup -type=all _vlmcs._tcp>kms.txt`
does not work, use `nslookup -type=all _vlmcs._tcp > kms.txt` instead.

Best regards
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 08ba6d1a-0f8e-7796-073f-f431c4421f6c
* Version Independent ID: c88cc509-3ccc-dc6d-f0b2-098303d178c6
* Content: [Guidelines for troubleshooting DNS-related activation issues](https://learn.microsoft.com/en-us/windows-server/get-started/common-troubleshooting-procedures-kms-dns)
* Content Source: [WindowsServerDocs/get-started/common-troubleshooting-procedures-kms-dns.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/common-troubleshooting-procedures-kms-dns.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **wscontent**

**Comment by craigcaseyMSFT** [comment]
Hello @StegemannDominik,

Thanks for contacting Microsoft. We value your feedback.

We have tested the problem as described in this issue and either couldn't replicate the stated result or have verified that no documentation change is required.

As a result, we’re closing this thread.

Thank you again and have a most pleasant day.
#please-close
