### ISSUE TITLE
The 30 day grace period information doesn't apply to Windows 10

### ISSUE THREAD

**Issue by vascograca80** [MicrosoftDocs/windowsserverdocs#7157]
The 30 day grace period information doesn't apply to Windows 10

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cc852932-b3f4-25ea-46b1-a9abb93fabac
* Version Independent ID: 5a03c0fc-a460-678d-c2ea-e9b8aeae6a75
* Content: [Guidelines for troubleshooting KMS](https://learn.microsoft.com/en-us/windows-server/get-started/activation-troubleshoot-kms-general)
* Content Source: [WindowsServerDocs/get-started/activation-troubleshoot-kms-general.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/activation-troubleshoot-kms-general.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **wscontent**

**Comment by Xelu86** [comment]
Hey vascograce80,

Thanks again for contacting Microsoft. We value your feedback.

We're closing this thread as it's a non-documentation issue.
#please-close
