### ISSUE TITLE
Update due

### ISSUE THREAD

**Issue by lythix** [MicrosoftDocs/windowsserverdocs#716]
Would like to see an update for new version Ubuntu 18.04 LTS.
Also some instructions on how to get Enhanced Session working so connecting to guest machine will automatically change resolution to full screen, like how Windows VM's work, if possible. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52db1d76-fb68-c44f-1162-3e30e8c2b793
* Version Independent ID: 696aa3ee-bd95-2acf-9021-ef4b67663f1a
* Content: [Supported Ubuntu virtual machines on Hyper-V](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-ubuntu-virtual-machines-on-hyper-v)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/Supported-Ubuntu-virtual-machines-on-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/Supported-Ubuntu-virtual-machines-on-Hyper-V.md)
* Service: **na**
* GitHub Login: @shirgall
* Microsoft Alias: **kathydav**

**Comment by evancox10** [comment]
Hi lythix, there is some information (here)[https://community.ubuntu.com/t/enhanced-ubuntu-vm-in-hyper-v/4363/9] on the Enhanced Session. But I too would like some information on the 18.04 LTS integration packages. pinging @shirgall

**Comment by DiApostola** [comment]
So it appears they may have solved the vast majority of the Step #12 headaches with 18.04. Install 18.04 as you will, and run this: "apt-get install linux-image-virtual linux-tools-virtual linux-cloud-tools-virtual" - power off, and when you copy the template image it doesn't create the issues it did in previous versions.

**Comment by BarnumD** [comment]
I also came here looking for updates and recommendations for Ubuntu 18 on Hyper-V.  I'm trying to use a Gen2 machine with a dynamic 128GB disk, and the Ubuntu 18 installer is reporting it as 1TB.  I know this is not the place for that issue, but it would be helpful to get some updated best practices.

**Comment by jcpro** [comment]
So whats the final consensus on Ubuntu 18.04 LTS support in SCVMM 2016?  Will there be an update for the s/w soon adding official support for this OS?

**Comment by dutcherm** [comment]
Please update with 18.04 LTS.

**Comment by lythix** [comment]
Good news that the Quickstart Ubuntu 18.04.1 image linux vm tools installed but make sure you turn Autologon OFF. There is currently a bug which stops the xrdp session from working. In my opinion it's a bug not a feature as it seems to be the default setting. There is an option to turn off the Autologon when you are creating your account, but if you don't know about this bug you may well give up trying to get it to work in Fullscreen. Issue is here: https://github.com/Microsoft/linux-vm-tools/issues/22

**Comment by BarnumD** [comment]
The old directions can't be correct.  For instance, there is no `linux-virtual-lts-bionic`. `linux-tools-virtual-lts-bionic`, or `linux-cloud-tools-virtual-lts-bionic`.  There also doesn't seem to be a `hyperv-daemons` package in the default repo either.

**Comment by shirgall** [comment]
I haven't had the time to update the Windows Server pages in a while, but I am working with the docs team to queue up some help. 18.04 is supported. So is 18.10. The recommended kernel to use is "linux-azure".

**Comment by BarnumD** [comment]
Thanks for that.  Looking forward to the update.

**Comment by larsiwer** [comment]
This should be addressed by #1958 -- the updated document is live.
@lizap @BarnumD Ok to close this issue?

**Comment by BarnumD** [comment]
Yes, thanks for the new recommendations.

**Comment by jcpro** [comment]
@shirgall Why is the recommended kernel to use linux-azure?  Are there any benefits to be had with this kernel?

**Comment by thomasbohan** [comment]
What about support for Ubuntu 18.04 within SCVMM 2012 R2 (Hyper-V Server 2012 R2 ).
Will Ubuntu 18 be added to the list of Guest OS Profiles as it currently only goes as far as 16.04.
