### ISSUE TITLE
I believe this page should say 10 HOURS... not 10 DAYS.

### ISSUE THREAD

**Issue by GreysonMitchem** [MicrosoftDocs/windowsserverdocs#7191]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5d689602-4103-4688-0ca4-dadd3069e3ea
* Version Independent ID: 7402857f-bbf0-008e-ceaa-9fd879d95770
* Content: [Create the Key Distribution Services KDS Root Key](https://learn.microsoft.com/en-us/windows-server/security/group-managed-service-accounts/create-the-key-distribution-services-kds-root-key)
* Content Source: [WindowsServerDocs/security/group-managed-service-accounts/create-the-key-distribution-services-kds-root-key.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/security/group-managed-service-accounts/create-the-key-distribution-services-kds-root-key.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey @GreysonMitchem,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting the length of time and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
