### ISSUE TITLE
add info about Azure AD Connect server

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windowsserverdocs#7207]
I have seen other guidance that states the AAD Connect server should be protected in the same manner as the DCs. I think that it would be helpful to explicitly state this in this documentation to help remind people how important it is to secure that server also. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ca929d6b-746d-f20a-8902-4e93a69ab8d8
* Version Independent ID: 88e13a93-f80b-d07b-cfaa-ab38205148e0
* Content: [Securing Domain Controllers Against Attack](https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/securing-domain-controllers-against-attack#blocking-internet-access-for-domain-controllers)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Securing-Domain-Controllers-Against-Attack.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Securing-Domain-Controllers-Against-Attack.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by IngridAtMicrosoft** [comment]
Azure Active Directory content is out of scope for Windows Server Active Directory content. 

More security information about Azure Active Directory can be found here. https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-whatis

**Comment by DeanGross** [comment]
I don't understand why the AAD connect server is out of scope, it is just a valuable a target as DC. I would like to suggest that you reconsider the scope of this guidance and expand to include resources that are similar risks and value to an attacker. You should be making it easier for your clients to secure the systems they have purchased and not forcing us to look at many different best practice guides.
