### ISSUE TITLE
PowerShell module information

### ISSUE THREAD

**Issue by Apoc70** [MicrosoftDocs/windowsserverdocs#721]
The documentation should provide some information on which PowerShell module contains the *ADFS* and *WebApplicationProxy* cmdlets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d10177c6-b241-0a3e-d6ba-3619c094812a
* Version Independent ID: 7a42691f-7f28-eee2-0c69-294e24cccdbe
* Content: [Managing SSL Certificates in AD FS and WAP in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/manage-ssl-certificates-ad-fs-wap#replacing-the-ssl-certificate-for-the-web-application-proxy)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/manage-ssl-certificates-ad-fs-wap.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/manage-ssl-certificates-ad-fs-wap.md)
* Service: **unspecified**
* GitHub Login: @jenfieldmsft
* Microsoft Alias: **billmath**

**Comment by gjonespf** [comment]
Had same issue while trying to debug SSL certs expired.

```powershell
Get-Command Get-WebApplicationProxySslCertificate | Select -ExpandProperty Source
# WebApplicationProxy
Get-Module WebApplicationProxy | select -ExpandProperty Path
# C:\Windows\system32\WindowsPowerShell\v1.0\Modules\WebApplicationProxy\WebApplicationProxy.psm1
```
Guessing this module is installed by default when WAP is installed, as it's not on the ADFS box.
ADFS is here:
```powershell
# And ADFS is here:
Get-Command Get-ADFSProperties | Select -ExpandProperty Source
# ADFS
Get-Module ADFS | select -ExpandProperty Path
```

**Comment by jaxidian** [comment]
I'm struggling with this as well, only on my server there seems to be **no** WebApplicationProxy module around.

`Get-Module WebApplicationProxy | select -ExpandProperty Path` returns nothing and there is no "WebApplicationProxy" folder in my Modules folder. I'm not sure when/what/where but I do not believe the module was even installed. So now I'm struggling to find where I can get it from so I can actually run these commands!

**Comment by rodgerkeesee** [comment]
Same here. Replacing an expired certificate requires these commands, but they aren't present. Running 
`Add-WindowsFeature web-application proxy` fails with "has a conflict with ADFS". Now I need to call MS Enterprise support to simply replace an expired SSL cert. So lame.

**Comment by IngridAtMicrosoft** [comment]
#please-close
