### ISSUE TITLE
when performing 'Configure Remote Access as a VPN Server' steps, the wizard attempts to add the server to the 'RAS and IAS Servers' group - either add in advance, or make sure you have permissions

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/windowsserverdocs#7212]
When performing...
https://learn.microsoft.com/en-us/windows-server/remote/remote-access/get-started-install-ras-as-vpn?tabs=powershell#configure-remote-access-as-a-vpn-server

> Right-click the VPN server, and then select Configure and Enable Routing and Remote Access to open the Routing and Remote Access Server Setup Wizard.

at the end, if the server isn't already in the 'RAS and IAS Servers' group, and the server administrator isn't a domain administrator, it fails with... 

> Windows was unable to add this computer to the list of valid remote access servers in the Active Directory. Before you can use this computer as a remote access server, the domain administrator must complete this task.

The server object in AD DS must be added to the standard | built in 'RAS and IAS Servers' group in AD DS.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 525fb6b7-96b4-191e-044b-9d38b9ba633d
* Version Independent ID: 525fb6b7-96b4-191e-044b-9d38b9ba633d
* Content: [How to install and configure Remote Access (RAS) as a VPN server](https://learn.microsoft.com/en-us/windows-server/remote/remote-access/get-started-install-ras-as-vpn?tabs=powershell)
* Content Source: [WindowsServerDocs/remote/remote-access/get-started-install-ras-as-vpn.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-access/get-started-install-ras-as-vpn.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @anaharris-ms
* Microsoft Alias: **anaharris**

**Comment by anaharris-ms** [comment]
#please-close

**Comment by anwarmahmood1** [comment]
@anaharris-ms why have you just closed this issue, with no feedback or edits to the main document?

**Comment by anaharris-ms** [comment]
Sorry for the confusion. I should have left an explanation. There is a link to the fix that has added prerequisites to complete this how-to. The document takes a few hours or more to publish. Thanks for your patience.
________________________________
