### ISSUE TITLE
Laps Attributes list the same settings on each one

### ISSUE THREAD

**Issue by DustyStudy** [MicrosoftDocs/windowsserverdocs#7214]
It appears that there was a copy/paste issue here for the following attributes:

ms-LAPS-EncryptedPassword
msLAPS-EncryptedPasswordHistory
msLAPS-EncryptedDSRMPassword

Those 3 all list the same settings as the ms-LAPS-EncryptedPassword settings as pasted below:

Name: ms-LAPS-EncryptedPassword
LDAP display name: msLAPS-EncryptedPassword
OID: 1.2.840.113556.1.6.44.1.3
Syntax: 2.5.5.10
OmSyntax: 4
IsSingleValued: True
IsMemberOfPartialAttributeSet: False
SearchFlags: 904
AttributeSecurityGuid: f3531ec6-6330-4f8e-8d39-7a671fbac605 (ms-LAPS-Encrypted-Password-Attributes)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d6c8d4c0-26b0-52da-1183-5039578c97cf
* Version Independent ID: d6c8d4c0-26b0-52da-1183-5039578c97cf
* Content: [Windows LAPS schema and rights extensions for Windows Server Active Directory](https://learn.microsoft.com/en-gb/windows-server/identity/laps/laps-technical-reference#windows-laps-schema-vs-legacy-microsoft-laps-schema)
* Content Source: [WindowsServerDocs/identity/laps/laps-technical-reference.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/laps/laps-technical-reference.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @jay98014
* Microsoft Alias: **jsimmons**

**Comment by jay98014** [comment]
Thank you @DustyStudy I will look at this.

**Comment by jay98014** [comment]
@DustyStudy - thanks again for pointing this.  I think the only discrepancy was in the attribute names which yes I did have a cut-and-paste bug on.   I have committed a [PR](https://github.com/MicrosoftDocs/windowsserverdocs-pr/pull/3769) to fix the problem - fix should go live later this afternoon.

**Comment by jay98014** [comment]
#sign-off

**Comment by jay98014** [comment]
#please-close
