### ISSUE TITLE
Section titled "PDF download" links to a .doc file

### ISSUE THREAD

**Issue by TheWaterbug** [MicrosoftDocs/windowsserverdocs#7217]
This page has a section titled, "PDF download," but when clicked, the link downloads a .doc file.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1999621a-92cd-28d0-88e0-c504d409afa5
* Version Independent ID: a9c96c5f-b03d-1805-fd7d-29853d33d03c
* Content: [Migrate SYSVOL replication to DFS Replication](https://learn.microsoft.com/en-us/windows-server/storage/dfs-replication/migrate-sysvol-to-dfsr?source=recommendations)
* Content Source: [WindowsServerDocs/storage/dfs-replication/migrate-sysvol-to-dfsr.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/dfs-replication/migrate-sysvol-to-dfsr.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey @TheWaterbug,

Thanks again for contacting Microsoft. We value your feedback. 

The verbiage has been updated. The option to print this .doc to .pdf is available in the top-right of the page if so desired. Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
