### ISSUE TITLE
Credential Guard replace de LSA protection?

### ISSUE THREAD

**Issue by ingd** [MicrosoftDocs/windowsserverdocs#7219]
It was not clear if Credential Guard replaces de LSA protection in a better way or if both can be used to operate to mitigate different flaws.

Someone could please clarify my question?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b04bc4d-9435-cdbc-429f-2433ada7bd37
* Version Independent ID: 5c902397-b2e7-4435-2b37-a57919434c9e
* Content: [Configuring Additional LSA Protection](https://learn.microsoft.com/en-us/windows-server/security/credentials-protection-and-management/configuring-additional-lsa-protection?toc=%2Fwindows%2Fsecurity%2Ftoc.json&bc=%2Fwindows%2Fsecurity%2Fbreadcrumb%2Ftoc.json)
* Content Source: [WindowsServerDocs/security/credentials-protection-and-management/configuring-additional-lsa-protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/security/credentials-protection-and-management/configuring-additional-lsa-protection.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by v-thepet** [comment]
Hello @ingd,

Thank you for contacting Microsoft. We value your feedback.

We've updated the documentation to clarify that both LSA protection and CG can be enabled on systems that support them. They are complementary. The update will be live after the next business day.

We'll now be closing this thread. Thank you again for your feedback, and have a most pleasant day.

#please-close

**Comment by ingd** [comment]
Thank you very much, @v-thepet. Only one more question: I applied attack surface reduction through Intune, including "[Block credential stealing from the Windows local security authority subsystem](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction-rules-reference?view=o365-worldwide#block-credential-stealing-from-the-windows-local-security-authority-subsystem)". Is ASR is an automated option to implement LSA protection, or is it another feature to mitigate another kind of flaw?
