### ISSUE TITLE
Raspberry Pi 2/3 and IoT Browser crash

### ISSUE THREAD

**Issue by gmpentaxfan** [MicrosoftDocs/windowsserverdocs#722]
In the hopes to use the Raspberry Pi as a thin client for our remote desktop servers.

I have tested Windows IoT 16299 IoTBrowser on a  Raspberry Pi 2B and the app crashes with (0xc0000005) 'access violation'.  

The crash occurs after the second login prompt and before the published app or remote desktop session starts.
I have disabled any device redirection on the RDS server.

Since I am new to C# programming is there any thing I can add to my app that will provide more insight into the error?  The app runs fine using the MinnowBoard Turbot/MAX (x64) image on a virtual machine.
https://www.youtube.com/watch?v=VupSwWKId8g

**Comment by gmpentaxfan** [comment]
'IoTBrowser.exe' (Win32): Loaded 'C:\Windows\System32\MMDevAPI.dll'. Skipped loading symbols. Module is native, and native debugging is currently disabled.
'IoTBrowser.exe' (Win32): Loaded 'C:\Windows\System32\devobj.dll'. Skipped loading symbols. Module is native, and native debugging is currently disabled.
'IoTBrowser.exe' (Win32): Loaded 'C:\Windows\System32\AudioSes.dll'. Skipped loading symbols. Module is native, and native debugging is currently disabled.
'IoTBrowser.exe' (Win32): Loaded 'C:\Windows\System32\avrt.dll'. Skipped loading symbols. Module is native, and native debugging is currently disabled.
'IoTBrowser.exe' (Win32): Loaded 'C:\Windows\System32\wuceffects.dll'. Skipped loading symbols. Module is native, and native debugging is currently disabled.
The thread 0xed8 has exited with code 0 (0x0).
Unhandled exception at 0x6771DAAF (edgehtml.dll) in IoTBrowser.exe: 0xC0000005: Access violation reading location 0x0000001C.

**Comment by gmpentaxfan** [comment]
Update...  on RDS Web Client and Raspbery Pi 2B

Using the Windows IoT Insider edition 17115, and turning off all device redirection has resolved the error.
It technically works, however is extremely slow on the Raspberry 2B. - Like click and have a coffee and click again. CPU sitting at 100%
Using latest Raspian Pi Desktop release and Chromium is faster but still too slow for production.

Hopefully I can get a Raspberry Pi 3B+ with the better/faster CPU to test.

**Comment by lizap** [comment]
Since you were able to resolve the original error, I'm going to close this issue. If you're still having trouble, please let me know and I'll reopen. Thanks!
