### ISSUE TITLE
How do partners get the Windows Admin Center SDK

### ISSUE THREAD

**Issue by mikejochimsen** [MicrosoftDocs/windowsserverdocs#723]
Trying to find the SDK for the newly released Windows Admin Center and cannot find any links to it, only references saying it can be used to manage third party components. Is the SDK, and documentation on how to use it, posted somewhere online? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5d4a9c-11eb-3b85-91dd-cdbb0625db5a
* Version Independent ID: 01dad638-f8fb-61ff-4952-e3b25007a234
* Content: [Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/understand/windows-admin-center)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/understand/windows-admin-center.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/understand/windows-admin-center.md)
* Service: **unspecified**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by lizap** [comment]
Hi - the SDK was released today (May 3, 2018) as a private preview. The [announce](https://cloudblogs.microsoft.com/windowsserver/2018/05/03/building-the-windows-admin-center-ecosystem-with-partners-sdk-preview-release/) has details on how to get the SDK, and you can check out the [SDK documentation](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/extend/extensibility-overview). Thanks!
