### ISSUE TITLE
Multiple values are missing

### ISSUE THREAD

**Issue by OursonBleu** [MicrosoftDocs/windowsserverdocs#7231]
Example: 
For AU option - configure automatic updates:
https://learn.microsoft.com/en-us/windows-server/administration/windows-server-update-services/deploy/4-configure-group-policy-settings-for-automatic-updates#configure-automatic-updates

You're missing option 7: Notify for install and notify for restart ( windows server 2016 and later)
https://learn.microsoft.com/en-us/windows/deployment/update/waas-wu-settings#configuring-automatic-updates-by-editing-the-registry

You should probably revise the document as there probably other option that change other than that.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4d9a7aaf-447d-a2dd-d7f6-828f277a00ea
* Version Independent ID: c3dd7389-454f-870d-5502-46544d6336dc
* Content: [Step 4 - Configure Group Policy Settings for Automatic Updates](https://learn.microsoft.com/en-us/windows-server/administration/windows-server-update-services/deploy/4-configure-group-policy-settings-for-automatic-updates##configure-automatic-updates)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/deploy/4-configure-group-policy-settings-for-automatic-updates.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-server-update-services/deploy/4-configure-group-policy-settings-for-automatic-updates.md)
* Product: **windows-server**
* Technology: **wsus**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by v-thepet** [comment]
Hello @OursonBleu, 

Thanks for contacting Microsoft. We value your feedback.

Documentation changes have been made to address this and other issues and are now live.

Thank you again and have a most pleasant day.
#please-close
