### ISSUE TITLE
Opt out tool has two files with same name

### ISSUE THREAD

**Issue by maweeras-msft** [MicrosoftDocs/windowsserverdocs#7234]
The document links to an opt out tool at https://www.microsoft.com/en-us/download/details.aspx?id=40897 . But it lists two LsaPplConfig.efi files with the same name and different sizes.

How do we pick which file to use?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b04bc4d-9435-cdbc-429f-2433ada7bd37
* Version Independent ID: 5c902397-b2e7-4435-2b37-a57919434c9e
* Content: [Configuring Additional LSA Protection](https://learn.microsoft.com/en-us/windows-server/security/credentials-protection-and-management/configuring-additional-lsa-protection)
* Content Source: [WindowsServerDocs/security/credentials-protection-and-management/configuring-additional-lsa-protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/security/credentials-protection-and-management/configuring-additional-lsa-protection.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by v-thepet** [comment]
Hello @maweeras-msft,

Thank you for contacting Microsoft. We value your feedback.

You are correct that the Download Center has two files with the same name. We determined that the smaller file is for 32-bit systems, and the larger file is for 64-bit systems. We've made a documentation update to clarify this, which will be live after the next business day.

We'll now be closing this issue. Thank you again for your feedback, and have a most pleasant day.

#please-close
