### ISSUE TITLE
Remote Registry should be enabled

### ISSUE THREAD

**Issue by TonitoDux** [MicrosoftDocs/windowsserverdocs#7236]
[Enter feedback here]
Hi,

I would improve the article by inserting in the prerequisite section that the "Remote Registry" service in services.msc has to be enabled. 
Because of this missing information I have spent four hours on troubleshooting today because I got and error that the "The network path was not found". 

BR

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2aa81041-3a2a-961a-05d5-4a845cc74ae2
* Version Independent ID: fadf165a-5c81-0102-e096-7f527483313b
* Content: [Migrate a file server by using Storage Migration Service](https://learn.microsoft.com/en-us/windows-server/storage/storage-migration-service/migrate-data)
* Content Source: [WindowsServerDocs/storage/storage-migration-service/migrate-data.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/storage-migration-service/migrate-data.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey @TonitoDux, 

Thanks again for contacting Microsoft. We value your feedback. 

On this page, if you go to the TOC on the left, we have a "[Known issues](https://learn.microsoft.com/en-us/windows-server/storage/storage-migration-service/known-issues)" category.

Scrolling through this, you'll come across "[Error 53](https://learn.microsoft.com/en-us/windows-server/storage/storage-migration-service/known-issues)" (The network path was not found) which does state to enable the service you have mentioned:

> At this stage, Storage Migration Service orchestrator is attempting remote registry reads to determine source machine configuration, but is being rejected by the source server saying the registry path does not exist. This can be caused by:
>
>- The Remote Registry service isn't running on the source computer.
>- Firewall does not allow remote registry connections to the source server from the Orchestrator.
>- The source migration account does not have remote registry permissions to connect to the source computer.
> - The source migration account does not have read permissions within the registry of the source computer, under "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion" or under "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanmanServer"

Hopefully this addresses your concern. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
