### ISSUE TITLE
New features in 2022

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/windowsserverdocs#7237]
This page includes new features for several versions of Windows Server. Where can I find the new Active Directory features that are ONLY available in Windows Server 2022?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36f4538a-b7ae-fd8d-9337-23dffe93c8f8
* Version Independent ID: 0a0a4ea0-8afe-b021-ed19-26e8e720fe8a
* Content: [What's new in Active Directory Domain Services in Windows Server 2016](https://learn.microsoft.com/en-us/windows-server/identity/whats-new-active-directory-domain-services)
* Content Source: [WindowsServerDocs/identity/whats-new-active-directory-domain-services.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/whats-new-active-directory-domain-services.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
Nothing new in AD DS to address currently. #please-close
