### ISSUE TITLE
Does not mention about file size limit

### ISSUE THREAD

**Issue by lapaz17** [MicrosoftDocs/windowsserverdocs#7256]
[Enter feedback here]

Findstr fails for vmware vmdk files. Please mention file size.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b90f482-f48a-7d60-7ba9-bb5a1e837989
* Version Independent ID: 5a8e1ac5-3f4d-4da9-67c3-15a08d9a1b61
* Content: [findstr](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/findstr)
* Content Source: [WindowsServerDocs/administration/windows-commands/findstr.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/findstr.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey lapaz17,

Thanks again for contacting Microsoft. We value your feedback. 

The `findstr` command searches for patterns of text in files and does not have any inherent limitations on the size of the file it can search. However, it may take longer to search larger files, and there may be practical limitations based on the amount of memory available on the system running the command.

A VMDK file is not a plain-text file.

I'm not completely positive, but you may need to mount the VMDK first if you intend to use findstr against it (if possible). Please utilize our other channels for assistance in this matter:

- Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
- Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
- Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

As this is a non-documentation issue, we’re closing this thread.

Thank you and have a most pleasant day. 
#please-close
