### ISSUE TITLE
diskpart's subpages are appearing as top level pages in the command line reference

### ISSUE THREAD

**Issue by VimalShekar** [MicrosoftDocs/windowsserverdocs#7258]
I'm referring to both :
https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands

as well as the tree view. 

diskpart.exe has several subcommands. Instead of showing these as subcommands, the reference doc shows them as top level commands. These subcommand pages should come under diskpart and not at the top level.
active
add
assign
attach
attributes
automount
break
clean
compact
convert
create
delete
detach
detail
exit
expand
extend
filesystems
format
gpt
help
import
inactive
list
merge
offline
online
recover
that
rem
remove
repair
rescan
retain
san
select
set
shrink
uniqueid

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 223974fe-b7c4-6ff2-73c5-939403da80a8
* Version Independent ID: e9f30af6-812b-b206-1a3c-fe48cb2b58a9
* Content: [active](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/active)
* Content Source: [WindowsServerDocs/administration/windows-commands/active.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/active.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey VimalShekar,

Thanks again for contacting Microsoft. We value your feedback. 

We are aware of this issue and it's a lengthy ongoing process of having it resolved. It is in our action plan with no given estimated data of completion. We are keeping this thread active until fully resolved in restructuring the TOC and associated commands pertaining to their command-line shells.

Thank you for your patience.

**Comment by Xelu86** [comment]
Hey VimalShekar,

We have aligned the Diskpart & Diskshadow parameters to their respective shells and updated the TOC. We will now be closing this thread.

Thank you and have a most pleasant day. 
#please-close
