### ISSUE TITLE
Regular update ?

### ISSUE THREAD

**Issue by PatrikHLT** [MicrosoftDocs/windowsserverdocs#7259]
Page says 
"We regularly update the [Remote Desktop web client]
(https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client)"

Two updated in over a year is not regular.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d692cf46-e5df-6425-8655-0e75a5c1fe83
* Version Independent ID: b6f6934e-a515-83e2-59f8-748ac0b472b9
* Content: [What's new in the web client](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/web-client-whatsnew)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/web-client-whatsnew.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/web-client-whatsnew.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
Hey PatrikHLT,

Thanks again for contacting Microsoft. We value your feedback. 

Looking at this page, updates to the Web Client of RDS starting from 03/28/2018 to 12/19/22. Several features and improvements have been made which often take months to complete. As this is a non-issue, we'll now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
