### ISSUE TITLE
VM Version 8.3 - Windows 10 version 1803

### ISSUE THREAD

**Issue by gabrielluizbh** [MicrosoftDocs/windowsserverdocs#726]
Where do I find news about VM version 1803?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4944168-7e1f-b07d-fcf3-f8310ba9a398
* Version Independent ID: 1603af67-fcc0-58a6-b86d-5b812bfbcdc7
* Content: [Upgrade virtual machine version in Hyper-V on Windows 10 or Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/deploy/upgrade-virtual-machine-version-in-hyper-v-on-windows-or-windows-server)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/deploy/Upgrade-virtual-machine-version-in-Hyper-V-on-Windows-or-Windows-Server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/deploy/Upgrade-virtual-machine-version-in-Hyper-V-on-Windows-or-Windows-Server.md)
* Service: **na**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by Chirishman** [comment]
Yep. This seems to be an ongoing issue, there still isn't documentation of the 8.2 configuration version which launched with 1709 (See #354 ). For the record 1803 defaults to the new, still unexplained 8.3 configuration version.

```PowerShell
PS > Get-VMHostSupportedVersion

Name                                                      Version IsDefault
----                                                      ------- ---------
Microsoft Windows 8.1/Server 2012 R2                      5.0     False
Microsoft Windows 10 1507/Server 2016 Technical Preview 3 6.2     False
Microsoft Windows 10 1511/Server 2016 Technical Preview 4 7.0     False
Microsoft Windows Server 2016 Technical Preview 5         7.1     False
Microsoft Windows 10 Anniversary Update/Server 2016       8.0     False
Microsoft Windows 10 Creators Update                      8.1     False
Microsoft Windows 10 Fall Creators Update/Server 1709     8.2     False
Microsoft Windows 10 Update/Server 1803                   8.3     True
```

Until the differences north of 8.0 are explained and/or if you have any Windows Server 2016 or Hyper-V Server 2016 VM Hosts (Versions above 8.0 are only supported if you have a Server 2016 Software Assurance volume license) I'm going to recommend creating your VMs using the below command:

```powershell
New-Vm -Name "Whatever" -Version 8.0
```

**Comment by lukebarone** [comment]
1803 is working for me under 8.3. I need to disable Secure Boot in the VM during the install, then enable it again after the first reboot.

**Comment by larsiwer** [comment]
This should also be addressed in PR #1805 

@gabrielluizbh @Chirishman @lukebarone 
Sorry that this took so long -- hopefully the updated content adds enough clarity. Please let us know if there is anything missing from your perspective.

**Comment by Chirishman** [comment]
@larsiwer

Still wish that we had a changelog for 8.1 and 8.2 but that's a lot better. Thanks!

I really hope going forward that as a team you can communicate about these changes as the releases happen.

Here's an example of the impact this can have:

> The biggest trouble with this for me involves workflows where a test or prototype VM is spun up on a fully up to date Win10 workstation and when it comes time to promote the VM you're unable to move it to your company's testing or prod Hyper-V cluster if the cluster is licensed for Server 2016/LTSB and thus you're forced to rebuild your VM.
> 
> I ended up with a Gitlab server VM stuck on my company laptop for a month before I snagged a disused win10 desktop to run it on so I could take my laptop home. Six months later we finally got a key for Server SAC and it's only just now running on an actual server.
> 
> I actually made an abortive attempt to go down the road of nested virtualization because of this, running a Win10 1803 VM on the Server 2016 Hyper-V cluster and running the Gitlab VM inside of that. I only gave up on that because I couldn't get the networking to work properly.
>
> "You can't get there from here" is a much more palatable answer when someone can give you an actual reason why.

**Comment by jobecker01** [comment]
So this article was updated lateley but the date is still 2016, so how should I find such important informations about the VM Version in the future?
