### ISSUE TITLE
nslookup camand 

### ISSUE THREAD

**Issue by uniqueone1111** [MicrosoftDocs/windowsserverdocs#7283]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9eba5593-e098-79ad-d314-fde8f49b1aac
* Version Independent ID: 8b7dbf11-907c-85f3-07c2-681de5830324
* Content: [nslookup](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/nslookup)
* Content Source: [WindowsServerDocs/administration/windows-commands/nslookup.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/nslookup.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey uniqueone1111,

We're unable to determine what the intent of your question is. If there are any errors or areas of improvement with said documentation, please let us know so we may better assist. We're now closing this thread.

Thank you and have a most pleasant day.
#please-close
