### ISSUE TITLE
Microsoft Remote Desktop hijacks foreground on MacOS 

### ISSUE THREAD

**Issue by cagrimunyas** [MicrosoftDocs/windowsserverdocs#7284]
on MacOS 13.3.1 Microsoft RD, when having an active RDP connection opens control center from menu bar automatically while working on different apps (other than the connected remote desktop) makes it impossible to work on the local machine once it has active session. Even working on the remote desktop on full screen control center became visible from the menu bar automatically and interaction with the remote desktop gets interupted. 

Repro Steps:
- Open an rdp session on MacOS with full screen.
- Try to work on another app like Safari on Mac for few minutes. 
- After few minutes, The mac switches to rdp screeen automatically, without the user's intent, and opens up the control center. Even trying to switch back is a flickery experience. Thus hijacking.

I love Microsoft remote desktop on MacOS. It's my daily driver, and right know it's impossible to use. Please fix it asap.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0517ea6a-9417-31a8-39a5-f6128387fee5
* Version Independent ID: 7636ec70-e1dd-8c6b-516c-8af324d9f645
* Content: [Get started with the macOS client](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-mac)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-mac.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
Hey cagrimunyas,

Thanks again for contacting Microsoft. We value your feedback.

As we understand it, you're describing an issue with the product compared to an issue with the documentation. GitHub isn't the right location or channel if searching for troubleshooting, technical support, deeper specifics of the product or feature requests as it is completely outside our scope. If there are any issues within the content itself, ie incorrect code, verbiage, etc., please let us know.

As the error/issue you're experiencing is quite specific, we recommend that you engage with the product community or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).

Additional support forums listed below:
- TechNet: https://social.technet.microsoft.com/Forums/en-US/home
- MSDN: https://social.msdn.microsoft.com/Forums/en-US/home
- Microsoft Community: https://answers.microsoft.com/

Hopefully one of the community experts may be able to better assist. We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
