### ISSUE TITLE
The PS module, AZSBTools, for the Get-FileShare function has many unapproved verbs

### ISSUE THREAD

**Issue by smilnebgmedhost** [MicrosoftDocs/windowsserverdocs#7286]
[Enter feedback here]
The page references a command, Get-FileShares, from the AZSBTools module. 
1. That module doesn't have Get-FileShares (it has a Get-FileShareInfo)
2. The module has many unapproved verbs and does not import correctly
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dbc92a8a-7a52-b8cc-006f-279c2aa34d2b
* Version Independent ID: dbc92a8a-7a52-b8cc-006f-279c2aa34d2b
* Content: [Secure SMB Traffic in Windows Server](https://learn.microsoft.com/en-us/windows-server/storage/file-server/smb-secure-traffic#block-outbound-smb-access)
* Content Source: [WindowsServerDocs/storage/file-server/smb-secure-traffic.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/file-server/smb-secure-traffic.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by Xelu86** [comment]
Hey smilnebgmedhost,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting the PS command to `Get-FileShareInfo`. As the creator of the AZSBTools is not affiliated with Microsoft directly, we cannot do anything about the verbs in these commands. You can choose to provide them this feedback in the PowerShell Gallery under "Contact Owners".

![image](https://github.com/MicrosoftDocs/windowsserverdocs/assets/103963494/96fc6cfc-0226-4db1-b3af-7dce8d51235c)

Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close

**Comment by smilnebgmedhost** [comment]
Then why would you reference that module in official Microsoft Documentation?
It's probably a very poor choice to do so!!!

________________________________
From: Xelu86 ***@***.***>
Sent: Monday, June 12, 2023 9:23 AM
To: MicrosoftDocs/windowsserverdocs ***@***.***>
Cc: Scott Milne - BG ***@***.***>; Author ***@***.***>
Subject: [External] - Re: [MicrosoftDocs/windowsserverdocs] The PS module, AZSBTools, for the Get-FileShare function has many unapproved verbs (Issue #7286)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>
WARNING:This email originated outside of the MEDHOST/YourCareUniverse email system.
DO NOT CLICK links or attachments unless you recognize the sender and know the content is safe.


Hey smilnebgmedhost,

Thanks again for contacting Microsoft. We value your feedback.

A documentation change has been made correcting the PS command to Get-FileShareInfo. As the creator of the AZSBTools is not affiliated with Microsoft directly, we cannot do anything about the verbs in these commands. You can choose to provide them this feedback in the PowerShell Gallery under "Contact Owners".

[image]<https://user-images.githubusercontent.com/103963494/245203722-96fc6cfc-0226-4db1-b3af-7dce8d51235c.png>

Changes will be live after the next business day. We will now be closing this thread.

Thank you and have a most pleasant day.
#please-close
