### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by vabello** [MicrosoftDocs/windowsserverdocs#7287]
There is a typo with the word Navigate.

"You can enable ABE in Server Manager. **Navigatie** to File and Storage Services > Shares, right-click the share, select Properties, go to Settings and then select Enable access-based enumeration."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 755656e0-2ec9-754c-9d2a-1c9a8107567b
* Version Independent ID: 24aef27b-d600-9d7a-660c-6ee8788e575a
* Content: [High CPU usage issue on the SMB server](https://learn.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/high-cpu-usage-issue-on-smb-server)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/high-cpu-usage-issue-on-smb-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/file-server/Troubleshoot/high-cpu-usage-issue-on-smb-server.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by Xelu86** [comment]
Hey vabello,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting this typo and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
