### ISSUE TITLE
export-federationconfiguration.ps1 supported for use with current versions of ADFS?

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/windowsserverdocs#7288]
This [article](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/migrate-ad-fs-fed-server-r2) discusses how to move from 2012 R2 to newer versions of ADFS, but I would like to know the export-federationconfiguration.ps1 script can be used against modern ADFS servers. I do not see a more recent version of this topic, and observe the file is still included even on the latest Windows 2022 server media.

I need to move an ADFS server from one forest to another and am wondering if I can use this script.

The ADFS [rapid restore tool](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/operations/ad-fs-rapid-restore-tool) requires that the service account be the same, which would not be true when moving to a new domain, so this export-federationconfiguration.ps1 script may be able to help, if its still supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c9ee880-410e-baa6-c4b3-79796116d2b4
* Version Independent ID: ae800f9c-239b-4d9c-03bb-e8926ee148ec
* Content: [Migrate the AD FS 2.0 federation server to Windows Server 2012 R2](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/migrate-ad-fs-fed-server-r2)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/migrate-ad-fs-fed-server-r2.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/deployment/migrate-ad-fs-fed-server-r2.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by Mike-Crowley** [comment]
I answered my own question when attempting to use it:


    This version of the Federation service is not supported. Exiting...
    At C:\Users\mike.crowley\desktop\export-federationconfiguration\adfs\export-federationconfiguration.ps1:1759 char:13
    +             throw ($_system_translations.ExportStsVersionNotSupported ...
    +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : OperationStopped: (This version of...ted. Exiting...:String) [], RuntimeException
        + FullyQualifiedErrorId : This version of the Federation service is not supported. Exiting...

**Comment by Laith-Hayajneh** [comment]
did you find a solution for this issue

**Comment by Laith-Hayajneh** [comment]
Many thanks for replying.
Let me explain tomyounwhat happened with us 
We have a server running on windows server  2016 and we use on it INfOR OS application so it has configured ADFS and works fine ,now we duplicate this server on another isolated environment for testing something else ,also it works good until we upgrade to windows 2019.the configuration for ADFS lost , we tried a lot of solutions to export and import none of them works .
Appreciate your help

**Comment by Mike-Crowley** [comment]
I haven't looked into the 2016>2019 upgrade process, but with older versions, you need to introduce new servers to the farm and then remove the old server, and then update the farm level. I'm not sure if ADFS supports in-place upgrades.

However, if you've just got one relying party application, it may be easier to just build the farm from scratch and re-configure the trust.

**Comment by Laith-Hayajneh** [comment]
We are looking to export ADFS configuration from the old VM "windows server 2016" which has the configuration for ADFS to the new upgraded vm "windows server 2019" ,we don't use farm ,is there a way to export or copying these configuration
