### ISSUE TITLE
More info?

### ISSUE THREAD

**Issue by Skatterbrainz** [MicrosoftDocs/windowsserverdocs#729]
I'd love to know more about this mysterious command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e27ba45-7e15-1919-0ad3-358a7362e85e
* Version Independent ID: c484b586-876f-550b-ab00-849e0c829a30
* Content: [wlbs](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/wlbs_1)
* Content Source: [WindowsServerDocs/administration/windows-commands/wlbs_1.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/wlbs_1.md)
* Service: **unspecified**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Me too. Thanks for pulling me into this mystery. 😄

**Comment by illfated** [comment]
@Skatterbrainz :

https://en.wikipedia.org/wiki/WLBS_(disambiguation):
> Windows NT Load Balancing Service, an early version of Microsoft's [Network Load Balancing Services](https://en.wikipedia.org/wiki/Network_Load_Balancing_Services)

See also: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/nlbmgr

**Comment by illfated** [comment]
The page has been deleted, so no use in keeping this ticket open.

**Comment by illfated** [comment]
#please-close
