### ISSUE TITLE
Typo in the description of the /e option.

### ISSUE THREAD

**Issue by NudeSpoons** [MicrosoftDocs/windowsserverdocs#730]
In the https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/xcopy#parameters table, on the row for the **`/e`** option, the _Description_ has an extraneous **`/t`** tagged on to the end.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 544925b9-8587-3e0e-9d49-44b77dbd290d
* Version Independent ID: e9969211-1085-ca1f-afb5-b619edbbfab3
* Content: [xcopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/xcopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/xcopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/xcopy.md)
* Service: **unspecified**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by lizap** [comment]
Thanks for raising this issue. Did you know you can edit the file to fix the typo directly? Follow the instructions [here](https://docs.microsoft.com/en-us/windows/whats-new/contribute-to-a-topic). We're working on making the command information more useful - we'll add this typo to our list of fixes. Thanks!
