### ISSUE TITLE
Docs online for format missing /NoTrim flag

### ISSUE THREAD

**Issue by paulfwilliams** [MicrosoftDocs/windowsserverdocs#7304]
Using the format command line, I see there is a flag called /NoTrim with the following help text:

`/NoTrim         Skip sending trim (delete notification) during format.`

I did not see an entry for /NoTrim in the format documentation.

(I am running Windows 11 version 22H2 (OS Build 10.0.22621.1702.)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c9fbdba6-cfee-e68d-e1a9-e97d09f0cfad
* Version Independent ID: 26f12948-5d6d-41c2-21ac-538da6e25f7a
* Content: [format](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/format)
* Content Source: [WindowsServerDocs/administration/windows-commands/format.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/format.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey paulfwilliams,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding the following parameters:

- /NoTrim
- /SHA256Checksums
- /Y

Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
