### ISSUE TITLE
Repo About Description outdated

### ISSUE THREAD

**Issue by crisman** [MicrosoftDocs/windowsserverdocs#7309]
Under the `About` box on the web page for this repo:

https://github.com/MicrosoftDocs/windowsserverdocs

The description text is:

>  Public content repository for Windows Server 2016 content. 

which is a bit out-of-date.

Probably just remove '2016 '

**Comment by Xelu86** [comment]
Hey @crisman,

Thanks again for contacting Microsoft, we value your feedback. 

We have corrected the description for this repo to reflect "Windows Server". 

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
