### ISSUE TITLE
cd X: does not just DISPLAY the current directory of the other drive, it moves you there.

### ISSUE THREAD

**Issue by TheTM1Channel** [MicrosoftDocs/windowsserverdocs#7313]
> If used with only a drive letter (for example, cd C:), cd displays the names of the current directory in the specified drive. 

This is misleading. It does not merely DISPLAY the current directory of the specified drive, it MOVES the command prompt to point to the current directory of the other drive.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 52ed71f1-2459-7f4d-0526-478187c4590d
* Version Independent ID: 9e5a0d9f-36c5-6e6b-bf46-f8a27f0ae363
* Content: [cd](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/cd)
* Content Source: [WindowsServerDocs/administration/windows-commands/cd.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/cd.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by crisman** [comment]
This was probably tested in PowerShell.

The content source in question is for `cmd`'s `cd`:
https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/cd

In the shell you are using type `help cd`, if you get the docs for `Set-Location` you are in powershell and `cd` is an alias to `Set-Location` which does not work like `cmd`'s `cd`.

In PowerShell to view another drive's current directory you want something like:
`Get-Location -PSDrive d`

**Comment by TheTM1Channel** [comment]
> This was probably tested in PowerShell.
> 
> The content source in question is for `cmd`'s `cd`: https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/cd
> 
> In the shell you are using type `help cd`, if you get the docs for `Set-Location` you are in powershell and `cd` is an alias to `Set-Location` which does not work like `cmd`'s `cd`.
> 
> In PowerShell to view another drive's current directory you want something like: `Get-Location -PSDrive d`

What on EARTH are you talking about? First of all, I think I know the difference between PowerShell and CMD.exe. I said NOTHING about PowerShell. You may want to read what I actuallywrote. The documentation for ****CMD.EXE****, NOT Powershell, says, and I repeat, "cd displays the names of the current directory in the specified drive". "Displays". That's the word in the help.

Now open a computer that has more than one drive. Open a CMD.exe window. Type the drive letter of the other drive, just as the help file describes. Now, does it merely "DISPLAY" the current folder of the other path, or does it MOVE you to the other path such that your cmd.exe prompt changes from C:\Wherever to D:\Wherever? It will be the second of these.

**Comment by crisman** [comment]
Shell in use is not mentioned in original post.

Problem does not repeat for me in `cmd.exe`:
```
C:\Users>cd D:\Mangos

C:\Users>cd D:
D:\Mangos

C:\Users>cd D:\Apples

C:\Users>cd D:
D:\Apples

C:\Users>cd /d D:

D:\Apples>
```

I do see the issue reported in `pwsh`:
```
PS C:\Users> cd D:\Mangos
PS D:\Mangos>
PS D:\Mangos> cd C:\Users
PS C:\Users> cd D:
PS D:\Mangos>
PS D:\Mangos> cd C:\Users
PS C:\Users> cd D:\Apples
PS D:\Apples>
```

If possible, please provide the text of a cmd.exe session which uses a `cd d:` ( or other drive letter) command and the output seen.  The three command set of `cd`, `cd d:`, `cd` would also be of interest.

**Comment by craigcaseyMSFT** [comment]
Hello @TheTM1Channel,

Thanks for contacting Microsoft. We value your feedback.

We have tested the problem as described in this issue and either couldn't replicate the stated result or have verified that no documentation change is required.

As a result, we’re closing this thread.

Thank you again and have a most pleasant day.
#please-close
