### ISSUE TITLE
Registry path not correct

### ISSUE THREAD

**Issue by BaconBandito** [MicrosoftDocs/windowsserverdocs#7317]
Hi,
Under the section "Managing ECC curves using GPO" steps 3 and 4 reference the following path

HKEY_LOCAL_MACHINE\CurrentControlSet\Control\Cryptography\ECCParameters

That path is not correct and should be:

HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Cryptography\ECCParameters

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e40eec07-5000-8af5-37f9-c2908bea3c67
* Version Independent ID: 4540c962-9294-e70d-de5b-8094e608768c
* Content: [Manage Transport Layer Security (TLS)](https://learn.microsoft.com/en-us/windows-server/security/tls/manage-tls#configuring-tls-cipher-suite-order)
* Content Source: [WindowsServerDocs/security/tls/manage-tls.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/security/tls/manage-tls.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @Andrei-Popov
* Microsoft Alias: **wscontent**

**Comment by Xelu86** [comment]
Hey BaconBandito,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting the registry paths in the **"Managing ECC curves using GPO"** section and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
