### ISSUE TITLE
"schtasks /create" and "schtasks /query" documentation has no mention of XML features

### ISSUE THREAD

**Issue by ShraiSingh** [MicrosoftDocs/windowsserverdocs#7322]
See title. 
There are no mentions of the XML import and XML export features despite them being included. 
You can find information about it when you type "schtasks /create /?" and "schtasks /query /?" respectively. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0feda591-bda7-75e4-3eee-f38ec06f6f17
* Version Independent ID: f9f5b2ca-d26f-dd8a-70d1-0c07b94a4dd6
* Content: [schtasks create](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/schtasks-create)
* Content Source: [WindowsServerDocs/administration/windows-commands/schtasks-create.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/schtasks-create.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **alalve**

**Comment by Xelu86** [comment]
Hey ShraiSingh,

Thanks again for contacting Microsoft, we value your feedback. 

A documentation change has been made adding the `/xml` parameter to both `schtasks /create` & `schtasks /query` pages. Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
