### ISSUE TITLE
Link is wrong or section is misleading

### ISSUE THREAD

**Issue by STaylor135** [MicrosoftDocs/windowsserverdocs#7343]
[Enter feedback here]
This feed back is not really for this page, but for the index on the left side of this page and the entry "NIC Teaming" 

This link does not take you to a page about NIC Teaming but rather to a different guide on Azure-Stack HCI Concepts requirements. Should this not be a guide in the Windows Server Networking core guide? Just like everything else on that list? Typing in the the URL according to what seems to be the convention of other items will return a 404 error, which makes me think the entry doesn't exist.  Furthermore the destination does not explain Teaming in terms of what it does, how to set it up, requirements and exceptions. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62f953b5-5ea4-4435-37b9-53484f75b316
* Version Independent ID: 6394da95-c5cb-2e17-2ae7-82e203b16c9e
* Content: [Network Load Balancing](https://learn.microsoft.com/en-us/windows-server/networking/technologies/network-load-balancing)
* Content Source: [WindowsServerDocs/networking/technologies/Network-Load-Balancing.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/networking/technologies/Network-Load-Balancing.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by v-thepet** [comment]
Hi @STaylor135,

Thank you for contacting Microsoft. We value your feedback.

A documentation change has been made to address this issue and will be live the next business day. The title of the table of contents entry was changed from "NIC Teaming" to "Switch Embedded Teaming (SET)," which is the current supported form, and it was moved to alphabetical order after the "Software Defined Networking" node, which also contains useful information. Here's a blog post about the different NIC Teaming technologies: https://techcommunity.microsoft.com/t5/networking-blog/teaming-in-azure-stack-hci/ba-p/1070642. 

We'll now be closing this issue. Thanks again for your input, and have a most pleasant day.

#please-close
