### ISSUE TITLE
Incorrect Link and Typo

### ISSUE THREAD

**Issue by Zonouz** [MicrosoftDocs/windowsserverdocs#7348]
There was some mistake happened in context of the page:

> You can create sync shares using Windows PowerShell by using the [New-SyncShare](https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh994572(v=ws.11)) cmdlet. Below is an example of this method:

The "New-SyncShare" link to a wrong page. The correct page may be: "https://learn.microsoft.com/en-us/powershell/module/syncshare/new-syncshare?view=windowsserver2022-ps"

and in this code:

> `New-SyncShare "HR Sync Share" K:\Share-1 –User "HR Sync Share Users"`

> The example above creates a new sync share named Share01 with the path K:\Share-1, and access granted to the group named HR Sync Share Users

The **sync share** named should not be: **"Share01"** So according to the PowerShell code it needs to be replaced by: "HR Sync Share" test.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2ee48ca-ffdd-e0e6-1c52-767b5d14a008
* Version Independent ID: 67235c91-d322-4029-3474-66d4e87a93f7
* Content: [Deploying Work Folders](https://learn.microsoft.com/en-us/windows-server/storage/work-folders/deploy-work-folders)
* Content Source: [WindowsServerDocs/storage/work-folders/deploy-work-folders.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/work-folders/deploy-work-folders.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey Zonouz,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made updating the new link to the `New-SyncShare` cmdlet and correcting the wording from the example. Changes will be live by the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
