### ISSUE TITLE
Incorrect examples description

### ISSUE THREAD

**Issue by kayasax** [MicrosoftDocs/windowsserverdocs#7353]
Regarding the samples provided here: https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/gpresult#examples 

the commands will get RSOP data for "targetusername", not for "maindom\hiropln" so this statement is incorrect or ambiguous: 

"To retrieve RSoP data for only the remote user, maindom\hiropln with the password p@ssW23, who's on the computer srvmain, type:"
`gpresult /s srvmain /u maindom\hiropln /p p@ssW23 /user targetusername /scope user /r`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b095f55a-3e89-09f4-7735-ecb4be8ba6ff
* Version Independent ID: 1fbbe8ab-ca51-8535-d8f6-db058ae79248
* Content: [gpresult](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/gpresult)
* Content Source: [WindowsServerDocs/administration/windows-commands/gpresult.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/gpresult.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey kayasax,

Thanks again for contacting Microsoft, we value your feedback. 

A documentation update was made addressing the example and this issue was not closed. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
