### ISSUE TITLE
how to check if LSA is running correctly?

### ISSUE THREAD

**Issue by magwa101** [MicrosoftDocs/windowsserverdocs#7360]
This page says to search for lsass.exe in EventViewer, but it turns up no results. How can I verify that Local Security Authority is correctly running correctly?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b04bc4d-9435-cdbc-429f-2433ada7bd37
* Version Independent ID: 5c902397-b2e7-4435-2b37-a57919434c9e
* Content: [Configuring Additional LSA Protection](https://learn.microsoft.com/en-us/windows-server/security/credentials-protection-and-management/configuring-additional-lsa-protection#verifying-lsa-protection)
* Content Source: [WindowsServerDocs/security/credentials-protection-and-management/configuring-additional-lsa-protection.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/security/credentials-protection-and-management/configuring-additional-lsa-protection.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by v-thepet** [comment]
Hello @magwa101,

Thank you for contacting Microsoft. We value your feedback.

We've made a documentation update that clarifies how to search Event Viewer for the event that indicates LSASS.exe was started as a protected process. The update will be live after the next business day.

We'll now be closing this thread. Thanks again for your feedback, and have a most pleasant day.

#please-close
