### ISSUE TITLE
AVMA keys on Windows server Standard edition?

### ISSUE THREAD

**Issue by jforstneric** [MicrosoftDocs/windowsserverdocs#7370]
Under "System Requirements" we find the following sentence:

> AVMA requires Windows Server Datacenter edition with the Hyper-V host role installed.

Then below we have a second sentence:

> The table above applies all editions (Datacenter, Standard, or Essentials).

Which of these two is it? Can AVMA keys be used in the Standard edition or not? And, if not, how would one go about activating the 2 VMs which can be activated as part of the host?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7354104e-ed89-252d-4a7b-8eb64f08b100
* Version Independent ID: d33aa125-9586-c70e-0194-d1abdfd862f3
* Content: [Automatic Virtual Machine Activation in Windows Server](https://learn.microsoft.com/en-us/windows-server/get-started/automatic-vm-activation)
* Content Source: [WindowsServerDocs/get-started/automatic-vm-activation.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/get-started/automatic-vm-activation.md)
* Product: **windows-server**
* Technology: **getting-started**
* GitHub Login: @dknappettmsft
* Microsoft Alias: **daknappe**

**Comment by dksimpson** [comment]
Hello @jforstneric,

Thanks for contacting Microsoft; we value your feedback. We've addressed this issue and rewritten the System requirements section to make it clearer.

#please-close
