### ISSUE TITLE
HTML Issue in HTML Probes

### ISSUE THREAD

**Issue by aakash-shah** [MicrosoftDocs/windowsserverdocs#7376]
Under the section [Load Balancer requirements](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-requirements#load-balancer-requirements), the third bullet contains HTML probe URLs that are not displaying as likely intended. it appears these are meant to be the less than and greater than characters, but someone not familiar with HTML encoding may not know this.

I am unable to paste the code since this editor auto corrects it, but it uses "&lt" and "&gt" instead of "<" and ">".

Please help correct this to avoid confusion.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81fc58b9-7063-5107-5f65-c77694b33c7e
* Version Independent ID: a541e745-1505-696d-2adf-c578e1f54b4c
* Content: [AD FS 2016 Requirements](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-requirements)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/ad-fs-requirements.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/overview/ad-fs-requirements.md)
* Product: **windows-server**
* Technology: **ad-fs**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by GURURAJ8** [comment]
where do you want to add the < > tags in the? in the text?

Use the HTTP (not HTTPS) health probe endpoints to perform load balancer health checks for routing traffic. This requirement avoids any issues relating to SNI. The response to these probe endpoints is an HTTP 200 OK and is served locally with no dependence on back-end services. The HTTP probe can be accessed over HTTP using the path '/adfs/probe'

**Comment by craigcaseyMSFT** [comment]
Hello @aakash-shah,

Thanks for contacting Microsoft. We value your feedback.

Documentation changes have been made to clarify and acknowledge this issue. The doc changes will be live after the next business day.

Thank you again and have a most pleasant day.
#please-close

**Comment by aakash-shah** [comment]
I am not seeing any changes or clarification - the URLs still contain "&lt" and "&gt" instead of "<" and ">", which makes this more difficult to read.
