### ISSUE TITLE
More information needed for /e option.

### ISSUE THREAD

**Issue by NudeSpoons** [MicrosoftDocs/windowsserverdocs#738]
In the https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/wscript#parameters section, the description given for the `/e` option provides scant information, which is not very helpful.

Users need to know which values are acceptable in defining the engine used for running the script, and whether and how this option relates to the `/h` option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ab8facb-62fc-07d3-facf-509cc80de78e
* Version Independent ID: 2897b4e0-b2fb-8d91-2519-cb5bac06f46b
* Content: [wscript](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/wscript)
* Content Source: [WindowsServerDocs/administration/windows-commands/wscript.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/wscript.md)
* Service: **unspecified**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by lizap** [comment]
Thanks for the feedback! I've updated the article with the information that @coreyp-at-msft referenced above. Please let us know if that's not enough.
