### ISSUE TITLE
null

### ISSUE THREAD

**Issue by starsalmon** [MicrosoftDocs/windowsserverdocs#7380]
```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c54ec64-15b2-ba84-ea00-27dde4334911
* Version Independent ID: 9c54ec64-15b2-ba84-ea00-27dde4334911
* Content: [Configure conditional access for VPN connectivity using Azure AD](https://learn.microsoft.com/en-us/Windows-server/remote/remote-access/how-to-aovpn-conditional-access)
* Content Source: [WindowsServerDocs/remote/remote-access/how-to-aovpn-conditional-access.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-access/how-to-aovpn-conditional-access.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @anaharris-ms
* Microsoft Alias: **wscontent**

**Comment by starsalmon** [comment]
Only missing in Entra. Old link worked the second time.

**Comment by anaharris-ms** [comment]
Hi @starsalmon,

Can you clarify which links aren't working please? Thank you !

**Comment by starsalmon** [comment]
They all seem to be missing VPN Connectivity the first time the page loads. Sometimes shows up after refreshing the page a few times. Using Edge.

https://entra.microsoft.com/#view/Microsoft_AAD_ConditionalAccess/ConditionalAccessBlade/~/Overview/fromNav/Identity
https://portal.azure.com/#view/Microsoft_AAD_ConditionalAccess/ConditionalAccessBlade/~/Overview
https://aad.portal.azure.com/#blade/Microsoft_AAD_IAM/ConditionalAccessBlade/Vpn

![image](https://github.com/MicrosoftDocs/windowsserverdocs/assets/119138782/448fa5c0-f050-4e8d-9f7e-d5ef8dc912e1)
![image](https://github.com/MicrosoftDocs/windowsserverdocs/assets/119138782/fbd4ff74-a77c-4373-b183-c5fa52e9e81c)

**Comment by anaharris-ms** [comment]
Did you try:

1. Clear your Edge cache.
2. Close all browser windows.
3. Reload the browser and navigate to the page.

**Comment by starsalmon** [comment]
Tried in that order, no change. Chrome behaves the same.

**Comment by anaharris-ms** [comment]
Hi @starsalmon,

This doesn't seem to be a doc issue and is something that can be better addressed by support. Please feel free to raise a support request: [Microsoft Azure Support Ticket | Microsoft Azure](https://azure.microsoft.com/en-gb/support/create-ticket).

**Comment by Xelu86** [comment]
Closing as issue isn't doc related.
#please-close
