### ISSUE TITLE
The `nslookup` cli syntax for non-interactive mode is not really covered here at all with any of the examples/docs.

### ISSUE THREAD

**Issue by daemonhorn** [MicrosoftDocs/windowsserverdocs#7382]
[Enter feedback here]

Need the examples to include the `-<variable>=<value>` part of the syntax when used directly within scripts/cli/powershell.
Example1:  `nslookup -type=MX example.com`  (To retrieve mail server DNS record types)
Example2:  `nslookup -type=AAAA example.com` (To retrieve only IPv6 record types)
Example2:  `nslookup -debug -type=A+AAAA -nosearch -recurse example.com 1.1.1.1` (To enable debug output, retreive both IPv6 and IPv4 addresses, and do not attempt to use the search domain, use recursive lookup, use the 1.1.1.1 dns server for query)
Example4: ` nslookup -debug -type=SOA example.com` (To retrieve the start of authority record for zone example.com)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9eba5593-e098-79ad-d314-fde8f49b1aac
* Version Independent ID: 8b7dbf11-907c-85f3-07c2-681de5830324
* Content: [nslookup](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/nslookup)
* Content Source: [WindowsServerDocs/administration/windows-commands/nslookup.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/nslookup.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by v-thepet** [comment]
Hello @daemonhorn, 

Thanks for contacting Microsoft. We value your feedback.

Documentation changes have been made to add examples for both interactive and noninteractive nslookup modes, and clarifying how and when to use each. The changes will be live after the next business day. We will now be closing this thread.

Thank you and have a most pleasant day.
#please-close
