### ISSUE TITLE
Entra Branding

### ISSUE THREAD

**Issue by Snozzberries** [MicrosoftDocs/windowsserverdocs#7389]
Lots to cover for Entra branding.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d25e426f-b6ed-c9db-1b8f-4c755789e0a6
* Version Independent ID: d25e426f-b6ed-c9db-1b8f-4c755789e0a6
* Content: [Get started with Windows LAPS and Azure Active Directory](https://learn.microsoft.com/en-us/windows-server/identity/laps/laps-scenarios-azure-active-directory)
* Content Source: [WindowsServerDocs/identity/laps/laps-scenarios-azure-active-directory.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/laps/laps-scenarios-azure-active-directory.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @jay98014
* Microsoft Alias: **jsimmons**

**Comment by isrbaral** [comment]
please don't break links, redirect all old links to new names instead of breaking existing infrastructure.

**Comment by craigcaseyMSFT** [comment]
Hello @Snozzberries,

Thanks for contacting Microsoft. We value your feedback.

We have tested the problem as described in this issue and either couldn't replicate the stated result or have verified that no documentation change is required.

As a result, we’re closing this thread.

Thank you again and have a most pleasant day.
#please-close
