### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by des2013** [MicrosoftDocs/windowsserverdocs#7390]
[Enter feedback here]

none of these power shell commands worked.  all i got was a big block of red error messages. i do not need more complexity, I need a working smb server.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 643788d4-ceda-1f1d-a36f-916d207068e7
* Version Independent ID: 9ac5db6c-9619-b699-aabf-1c51faa22c2b
* Content: [Advanced Troubleshooting Server Message Block (SMB)](https://learn.microsoft.com/en-us/windows-server/storage/file-server/troubleshoot/troubleshooting-smb)
* Content Source: [WindowsServerDocs/storage/file-server/Troubleshoot/troubleshooting-smb.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/file-server/Troubleshoot/troubleshooting-smb.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by Xelu86** [comment]
Hey @des2013,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made updating the commands and will be live after the next business day. They should now work as seen below:

![image](https://github.com/MicrosoftDocs/windowsserverdocs/assets/103963494/30114e06-8733-432d-8339-7dcb86c72557)

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
