### ISSUE TITLE
[SFC] What are the return codes

### ISSUE THREAD

**Issue by djibe** [MicrosoftDocs/windowsserverdocs#7391]
Hi,

what are the return codes sent by SFC ?

I need these to set a CMD repair script and select according choice using errorlevel.

I assume a normal sfc sends 0, but what happens when error where found and repaired, and found but not repaired ?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0d979606-3b11-34e5-70db-88d90855cf5c
* Version Independent ID: d2358e0b-7688-ac7f-0f08-fc198b6a57a9
* Content: [sfc](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/sfc)
* Content Source: [WindowsServerDocs/administration/windows-commands/sfc.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/sfc.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **alalve**

**Comment by PC-Bjorn** [comment]
Did you ever figure this out?

**Comment by djibe** [comment]
Hi, not sure to fully understand your answer but no. Didn't find more info.

**Comment by PC-Bjorn** [comment]
Here's a breakdown of the %errorlevel% codes, with some additional details:

0: No integrity violations were found. This is indeed the ideal outcome, indicating all protected system files are healthy.

1: System File Checker found corrupt files and attempted to repair them. This doesn't necessarily guarantee successful repair. SFC checks if it has a cached copy of the healthy file and replaces the corrupt one. However, if the cached copy is also corrupt or unavailable, the repair may not be successful.

2: System File Checker found corrupt files but could not repair them. This usually means the tool lacks a healthy copy of the file or encounters permission issues preventing the replacement. It's crucial to investigate further and find alternative solutions for these unfixable files.

Always check/parse the CBS.log file for the full details of what happened..

**Comment by djibe** [comment]
Very kind.
Thanks
