### ISSUE TITLE
Great Guide for SSH

### ISSUE THREAD

**Issue by Yoyoma22** [MicrosoftDocs/windowsserverdocs#7396]
Tried it as of 2023-07-21 Windows 11 and it works great!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c89b7b3-c05f-b517-6109-04e6a97195c3
* Version Independent ID: 1e4b742e-d999-2c1e-a396-dc149f7ac76b
* Content: [Key-based authentication in OpenSSH for Windows](https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/OpenSSH/OpenSSH_KeyManagement.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @maertendMSFT
* Microsoft Alias: **damaerte**

**Comment by Xelu86** [comment]
Hey Yoyoma22,

Thanks for contacting Microsoft. We value your feedback.

We are happy to hear that you found our OpenSSH Key Management documentation helpful! As this is a non-issue, we'll now be closing this thread.

Thank you and have a most pleasant day. 
#please-close
