### ISSUE TITLE
sc.exe - type= shared (as documented in example) doesn't work

### ISSUE THREAD

**Issue by AndrewKoransky** [MicrosoftDocs/windowsserverdocs#7402]
Where defining `interact` usage, you have a typo. Currently it reads:

_This type must be used in conjunction with type= own or type= shared (for example, type= interact type= own). Using type= interact by itself will generate an error._

But `type= shared` doesn't work. Only `type= share` works. So it should read:

_This type must be used in conjunction with type= own or type= share (for example, type= interact type= own). Using type= interact by itself will generate an error._

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 582a188c-bf96-b9c5-50fc-2dacade5fba0
* Version Independent ID: 2f25595f-9d0e-a533-2dac-7c6495c94511
* Content: [sc.exe create](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/sc-create)
* Content Source: [WindowsServerDocs/administration/windows-commands/sc-create.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/sc-create.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **alalve**

**Comment by v-thepet** [comment]
Hi @AndrewKoransky,

Thank you for contacting Microsoft. We appreciate your feedback. A documentation update has been made to fix the typo and will be live the next business day. 

We'll now be closing this issue. Thanks again for your input and have a most pleasant day.

#please-close
