### ISSUE TITLE
Script name consistency issues

### ISSUE THREAD

**Issue by yamauchikazu** [MicrosoftDocs/windowsserverdocs#7404]
There is a mix of ImportUpdatesInToWSUS.ps1 and ImportUpdateToWSUS.ps1 in the document.

https://learn.microsoft.com/windows-server/administration/windows-server-update-services/manage/wsus-and-the-catalog-site?branch=pr-4097#powershell-script-to-import-updates-into-wsus

These should be unified in ImportUpdateToWSUS.ps1.

**Comment by Xelu86** [comment]
Hey @yamauchikazu,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made for the consistency of the `.ps1` script naming and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
