### ISSUE TITLE
Links to microsoft gallery doesn't work

### ISSUE THREAD

**Issue by dev246** [MicrosoftDocs/windowsserverdocs#7406]
Link [SMB Share Configuration for Hyper-V Workloads](https://gallery.technet.microsoft.com/SMB-Share-Configuration-4a36272a)   doesn't work

**Comment by Xelu86** [comment]
Hey @dev246,

Thanks again for contacting Microsoft. We value your feedback. 

What documentation page are you referencing?

**Comment by Xelu86** [comment]
Due to no response towards this issue, we are now closing this thread. Have a most pleasant day.
#please-close
