### ISSUE TITLE
certutil - view -restrict "certificate template=templateName"

### ISSUE THREAD

**Issue by Tarjei-stavanger** [MicrosoftDocs/windowsserverdocs#7409]
When using
certutil - view -restrict "certificate template=templateName"

I'm using the command on Windows Server 2023 and Windows server 2012R2.

I have found that using names does not work. I only get the schema and nothing else. However using the OID instead of the name works.

It might be useful to provide this information to the users.

The OID can be found with the following PowerShell command

`get-adobject "CN=TemlateName,CN=Certificate Templates,CN=Public Key Services,CN=Services,CN=Configuration,DC=aDomainName,DC=TopDomain" -properties cn,msPKI-Cert-Template-OID`

As can be seen, this is found under "Sites and Services".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d238db2c-10e1-d418-e780-54b421779754
* Version Independent ID: d1313e31-d990-2f0b-3f70-ae0fcdb4ba5c
* Content: [certutil](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/certutil)
* Content Source: [WindowsServerDocs/administration/windows-commands/certutil.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/certutil.md)
* Service: ****
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by v-thepet** [comment]
Hello @Tarjei-stavanger,

Thanks for contacting Microsoft. We value your feedback.

A documentation change has been made to address this issue and will go live the next business day. Note the new Remark under -view -restrict.

Thank you again and have a most pleasant day.
#please-close
