### ISSUE TITLE
Doskey

### ISSUE THREAD

**Issue by Speedmeup007** [MicrosoftDocs/windowsserverdocs#7413]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfca3039-33ac-2038-1ffb-ced81f81cc4d
* Version Independent ID: f5663e9c-6a38-fd0c-2958-e3d21b913689
* Content: [doskey](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/doskey)
* Content Source: [WindowsServerDocs/administration/windows-commands/doskey.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/doskey.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Closing as documentation issue is not described.
#please-close
