### ISSUE TITLE
shutdown.exe: description of the parameter "/g" is incorrect

### ISSUE THREAD

**Issue by datto-cschulze** [MicrosoftDocs/windowsserverdocs#7414]
The description of the parameter "/g" is incorrect.
See attach screenshot.

![image](https://github.com/MicrosoftDocs/windowsserverdocs/assets/92443363/010db22c-cd21-4d60-bcbd-385b8e0f0b38)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2770335e-d15c-6389-36b9-d687b7794b92
* Version Independent ID: 319c885a-1c12-595f-8018-c563945afe93
* Content: [shutdown](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/shutdown)
* Content Source: [WindowsServerDocs/administration/windows-commands/shutdown.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/shutdown.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @Xelu86
* Microsoft Alias: **wscontent**

**Comment by Xelu86** [comment]
Hey datto-cschulze,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made updating the `/g` parameter and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
