### ISSUE TITLE
Capitalization of "VM"

### ISSUE THREAD

**Issue by git-tariqu** [MicrosoftDocs/windowsserverdocs#7416]
"vm" should be capitalized as "VM".

e.g., `3. Add the server or vm to the domain:` should be `3. Add the server or VM to the domain:`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc57542-d28d-f0f5-8baa-bf439c8a1b04
* Version Independent ID: 36a9dd84-5284-5cfd-2366-546c978b1852
* Content: [Scale out your RDS deployment by adding an RD Session Host farm](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-scale-rdsh-farm)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-scale-rdsh-farm.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/rds-scale-rdsh-farm.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by Xelu86** [comment]
Hey @git-tariqu,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made where all instances of "vm" has been changed to "VM" and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
