### ISSUE TITLE
script name inconsistency

### ISSUE THREAD

**Issue by TimoGT** [MicrosoftDocs/windowsserverdocs#7422]
In this page you ask users to save the script as ImportUpdatesIntoWSUS.ps1 but then in your execution examples you refer to the script as ImportUpdateToWSUS.ps1

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d6f6d856-a48e-4926-291d-1f399a28970a
* Version Independent ID: 9504cad8-7801-e461-62e2-c54da2cd7517
* Content: [WSUS and the Microsoft Update Catalog](https://learn.microsoft.com/en-au/windows-server/administration/windows-server-update-services/manage/wsus-and-the-catalog-site?SKU=WSUS&Version=6.3.9600.18838&ServerName=DCUSVSCCM01&PortNumber=8530&Ssl=False&Protocol=1.8&source=docs)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/manage/wsus-and-the-catalog-site.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-server-update-services/manage/wsus-and-the-catalog-site.md)
* Product: **windows-server**
* Technology: **wsus**
* GitHub Login: @JasonGerend
* Microsoft Alias: **wscontent**

**Comment by Xelu86** [comment]
Hey @TimoGT,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made for the consistency of the `.ps1` script naming and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
