### ISSUE TITLE
certutil documentation seems way out of sync with the product.

### ISSUE THREAD

**Issue by hkc94501** [MicrosoftDocs/windowsserverdocs#7426]
The documentation is obviously incomplete.
the command supports the verb -csplist but it is not documented on this page.
It also supports the verb -displayECCcurve but there is no mention of it on this page.
One wonders how many other undocumented features there are in certutil.
The verb -csplist does not give a complete list of all CSPs on the system,  It only shows CryptoAPI providers.
Why does -displayECCcurve work when there are no CNG providers listed?  ECC requires CNG.
If certutil only works for CryptoAPI then that should be documented.
IF there are verbs to display the CNG providers then those need to be documented.
Hard to believe that would be the case because windows definitely does support ECC certificates and ECC requires CNG.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d238db2c-10e1-d418-e780-54b421779754
* Version Independent ID: d1313e31-d990-2f0b-3f70-ae0fcdb4ba5c
* Content: [certutil](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/certutil)
* Content Source: [WindowsServerDocs/administration/windows-commands/certutil.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/certutil.md)
* Service: ****
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by v-thepet** [comment]
Hello @hkc94501,

Thanks for contacting Microsoft. We value your feedback.

Documentation changes have been made to address these issues and will go live the next business day.

Thank you again and have a most pleasant day.
#please-close
