### ISSUE TITLE
minor inaccuracy in winlogon graph

### ISSUE THREAD

**Issue by hamzawinix** [MicrosoftDocs/windowsserverdocs#7427]
[Enter feedback here]
hi, just  small technical edit 
@https://learn.microsoft.com/en-us/windows-server/security/windows-authentication/credentials-processes-in-windows-authentication
@Logon tile enumeration the graph incorrectly says winlogon uses the secure32.dll which should be changed to secur32.dll (minus the extra e)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ebfccb0-3ec2-67f2-5566-68815e97b884
* Version Independent ID: 96e7a317-573e-3d79-f08d-10cf76dcb3de
* Content: [Credentials Processes in Windows Authentication](https://learn.microsoft.com/en-us/windows-server/security/windows-authentication/credentials-processes-in-windows-authentication)
* Content Source: [WindowsServerDocs/security/windows-authentication/credentials-processes-in-windows-authentication.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/security/windows-authentication/credentials-processes-in-windows-authentication.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey hamzawinix,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made where instances in the graphs of "Secure32.dll" being corrected to Secur32.dll and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
