### ISSUE TITLE
Bring back normal fonts

### ISSUE THREAD

**Issue by Dionisas** [MicrosoftDocs/windowsserverdocs#7429]
After upgrade, we see that bigger fonts are used in All Services blade, under categories. This does not look nice ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7a131da0-9b7e-c9e1-3536-9c668317585c
* Version Independent ID: 2e572be9-9f47-999b-4c4e-d9801d900b55
* Content: [Manage Failover Clusters with Windows Admin Center](https://learn.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/manage-failover-clusters)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/use/manage-failover-clusters.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/manage/windows-admin-center/use/manage-failover-clusters.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by Xelu86** [comment]
Hey @Dionisas,

Thanks again for contacting Microsoft. We value your feedback. 

As we understand it, you may be describing an issue with the product/service compared to an issue with the documentation itself.

For the Windows Server Repo in GitHub, here is what we're able to assist with that is in our direct scope:

- Content Issues
   - Broken Links, Grammar, Incorrect Code, Typos, Updates, Verbiage (general documentation issues)

GitHub is _not_ the right location/channel if searching for:

- Support Case or Support Tickets
   - We cannot action such items, nor are we a liaison between support teams.
- [Bug Submittal/Feature Requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
   - If on a Windows OS, click [here](https://aka.ms/WIPFeedbackHub) or perform `Windows Key + F` [Only on Win10 Build 14367+] ( this captures & attaches a screenshot).
   - Feedback can also be provided via our [Feedback Form](https://feedbackportal.microsoft.com/feedback).
- Extended Troubleshooting, Technical/Product Support, Vast specifics/functions of a product
   - Please utilize one or more of the following: 
     - Engage with the product community or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
     - TechNet: https://social.technet.microsoft.com/Forums/en-US/home.
     - MSDN: https://social.msdn.microsoft.com/Forums/en-US/home.
     - Microsoft Community: https://answers.microsoft.com/.

For all non-documentation issues, hopefully one of the community experts may be able to better assist. We will now be closing this thread.

Thank you and have a most pleasant day.
#please-close
