### ISSUE TITLE
Typo in Remarks section

### ISSUE THREAD

**Issue by NudeSpoons** [MicrosoftDocs/windowsserverdocs#743]
In the https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/wscript#remarks section, the final sentence of the 6th bullet point has the following typo:

`This registers wscript.exe or cscript as ...`
should be
`This registers wscript.exe or cscript.exe as ...`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ab8facb-62fc-07d3-facf-509cc80de78e
* Version Independent ID: 2897b4e0-b2fb-8d91-2519-cb5bac06f46b
* Content: [wscript](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/wscript)
* Content Source: [WindowsServerDocs/administration/windows-commands/wscript.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/wscript.md)
* Service: **unspecified**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by lizap** [comment]
Closing as @doctordns fixed it - thanks!
