### ISSUE TITLE
Link to "Azure Virtual Desktop Store app for Windows" gives 404 error

### ISSUE THREAD

**Issue by richard-artes** [MicrosoftDocs/windowsserverdocs#7432]
Link to "Azure Virtual Desktop Store app for Windows" gives 404 error
https://learn.microsoft.com/en-us/azure/virtual-desktop/users/connect-windows-avd-app
Not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: acc42a8f-2623-4352-7cc4-70f0f61e9d89
* Version Independent ID: 97d8b54b-5e7d-098b-4fb7-e8f6e0b30389
* Content: [Get started with the Remote Desktop app for Windows](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windows)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windows.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/windows.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
Hey @richard-artes,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made with the following update:

> [!Important]
>
> We're no longer updating the Remote Desktop app for Windows with new features and support for Azure Virtual Desktop will be removed in the future.
>
> For the best Azure Virtual Desktop experience that includes the latest features and updates, we recommend you download the [Windows Desktop client](https://review.learn.microsoft.com/en-us/azure/virtual-desktop/users/connect-windows) instead.

Changes will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
