### ISSUE TITLE
Possible incorrect default location of Event Log Readers

### ISSUE THREAD

**Issue by thkasaxo** [MicrosoftDocs/windowsserverdocs#7433]
The "Event Log Readers" default container is stated to be "CN=Users, DC=<domain>, DC=".
However, in a fresh install of AD DS it looks like the group is placed in the container "CN=Builtin, DC=<domain>, DC=".
The SID "S-1-5-**32**-573" also points to a Builtin group as the 32-groups cannot be moved.

Is the documentation incorrect?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3489e3cf-5323-1d4d-9250-081af0abb2f7
* Version Independent ID: 3489e3cf-5323-1d4d-9250-081af0abb2f7
* Content: [Active Directory security groups](https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/understand-security-groups#event-log-readers)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/understand-security-groups.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-ds/manage/understand-security-groups.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @Dansimp
* Microsoft Alias: **alalve**

**Comment by thkasaxo** [comment]
Adding to this, as DHCP Administrator and DHCP Users default container is stated to be "CN=Builtin, DC=, DC=".
However, the default container for the two groups are "CN=Users, DC=, DC=".

**Comment by v-thepet** [comment]
Hi @thkasaxo - Thanks again for contacting Microsoft and for your valuable feedback.

A documentation change has been made implementing your corrections and will be live after the next business day. We will now be closing this thread.

Thank you and have a most pleasant day.
#please-close
