### ISSUE TITLE
TIME command

### ISSUE THREAD

**Issue by martago54** [MicrosoftDocs/windowsserverdocs#7434]
In the Microsoft page explaining this command:

https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/time

when mentioning the option "time /t", there are no output examples.

I know the output is as follows - 10:23 (hour and minutes of the current time), however I am in doubt whether below 10 hours the time is indicated as i.e. 09:23 or 9:23.  It makes a difference if you want to use this information programmatically.

**Comment by Xelu86** [comment]
Hey martago54,

Thanks again for contacting Microsoft. We value your feedback. 

Running `time /t` will look different depending on the region the user is from and if they changed the default settings for their clock. Users using 12-hour clocks running the command would show (for example) 05:00 _xM_ if all settings are default.

Users can change the default settings to omit the AM/PM, the "0" for time less than "10", and they can also use a 24-hour system. If a user is using 24-hours, and it is 10pm, it would show as 22:00 when running `time /t`. In the 24-hour system, you can also omit the "0" for time less than "10".

This page is intended for regional default settings only of how the time will display in both the GUI and CLI. If you're programming for time, we can't really assist as that is outside our scope. We do have support forums that you can look into that may be of help:

- [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home)
- [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home)
- [Microsoft Support Community](https://answers.microsoft.com/)

Or any others you so decide to use for your programming needs.

As this isn't a general documentation issue, we are not making updates to this page at this time. We are now closing this thread.

Thank you and have a most pleasant day. 
#please-close
