### ISSUE TITLE
Errorlevel description missing

### ISSUE THREAD

**Issue by GoodMirek** [MicrosoftDocs/windowsserverdocs#744]
Errorlevel description missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31d4d309-5a67-bfc2-8bdf-1149260e1af5
* Version Independent ID: 37cf9db4-8ee3-9ade-e271-46d2111fb087
* Content: [taskkill](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/taskkill)
* Content Source: [WindowsServerDocs/administration/windows-commands/taskkill.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/taskkill.md)
* Service: **unspecified**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by IngridAtMicrosoft** [comment]
Hi @GoodMirek. We do want you to be invested in documentation, and we understand your frustration.  Your feedback has been captured and will be added to our backlog.

**Comment by GoodMirek** [comment]
@IngridAtMicrosoft Where will I be able to follow the progress and resolution of this issue, if this Github issue is closed?
