### ISSUE TITLE
TSS Tools no longer available

### ISSUE THREAD

**Issue by mwilsontx** [MicrosoftDocs/windowsserverdocs#7443]
The TSS Tools mentioned are no longer available on GitHub. It displays the following message:

> Content of https://github.com/CSS-Windows/WindowsDiag was moved to Microsoft Internal location and will be not accessible to external accounts.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70ed7e4c-0e62-887f-e3aa-db50bcb9d2b9
* Version Independent ID: 4d40f939-2773-a34b-ff7b-4f9d8e29878b
* Content: [Troubleshoot problems on the DHCP server](https://learn.microsoft.com/en-us/windows-server/troubleshoot/troubleshoot-problems-on-dhcp-server)
* Content Source: [WindowsServerDocs/troubleshoot/troubleshoot-problems-on-dhcp-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/troubleshoot/troubleshoot-problems-on-dhcp-server.md)
* Product: **windows-server**
* Technology: **troubleshoot**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by v-thepet** [comment]
Hi @mwilsontx and @nyakojiru,

Thanks for contacting Microsoft. We value your feedback.

A documentation change has been made with an updated link and instructions for the TSS tools and will be live after the next business day. We will now be closing this thread.

Thank you and have a most pleasant day.
#please-close
