### ISSUE TITLE
Page is incomplete

### ISSUE THREAD

**Issue by Douglas-G-Walker** [MicrosoftDocs/windowsserverdocs#7444]
At step 2 (https://learn.microsoft.com/en-us/windows-server/storage/storage-migration-service/migrate-data#step-2-create-job-and-inventory-server-data)

It says "Select New job"  ... select it where? 

This is the problem I have with most of your documentation.  It assumes people know more than they do, and it's not explicit about exactly what we should be doing where.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2aa81041-3a2a-961a-05d5-4a845cc74ae2
* Version Independent ID: fadf165a-5c81-0102-e096-7f527483313b
* Content: [Migrate a file server by using Storage Migration Service](https://learn.microsoft.com/en-us/windows-server/storage/storage-migration-service/migrate-data)
* Content Source: [WindowsServerDocs/storage/storage-migration-service/migrate-data.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/storage-migration-service/migrate-data.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by v-thepet** [comment]
Hi @Douglas-G-Walker,

Thank you for contacting Microsoft. We appreciate your feedback.

A documentation update has been made to address this issue and will be live the next business day. We'll now be closing this thread.

Thanks again for your feedback, and have a very pleasant day.

#please-close
