### ISSUE TITLE
Windows Admin Center Install 2306 Broken

### ISSUE THREAD

**Issue by rhinoroo** [MicrosoftDocs/windowsserverdocs#7447]
Windows 11 installation with 2306 Windows Admin Center fails with unable to reserve default port of 6516 or creates unhandled exception using alternate port.
![2023-08-11_16-25-22](https://github.com/MicrosoftDocs/windowsserverdocs/assets/11729238/014d8335-cf5f-4511-a662-a1080ec1e494)

**Comment by Xelu86** [comment]
Hey rhinoroo,

Thanks again for contacting Microsoft. We value your feedback.

As we understand it, you're describing an issue with the product/service compared to an issue with our documentation.

For the Windows Server Repo in GitHub, here is what we're able to assist with that is in our direct scope:

- Content Issues
   - Broken Links, Grammar, Incorrect Code, Typos, Updates, Verbiage (general documentation issues)

GitHub is _not_ the right location/channel if searching for:

- Support Case or Support Tickets
   - We cannot action such items, nor are we a liaison between support teams.
- [Bug Submittal/Feature Requests](https://learn.microsoft.com/microsoft-365/admin/misc/feedback-provide-microsoft?view=o365-worldwide)
   - If on a Windows OS, click [here](https://aka.ms/WIPFeedbackHub) or perform `Windows Key + F` [Starting from Win10 Build 14367+] (this captures & attaches a screenshot).
   - Feedback can also be provided via our [Feedback Form](https://feedbackportal.microsoft.com/feedback).
- Extended Troubleshooting, Technical/Product Support, Vast specifics/functions of a product
   - Please utilize one or more of the following: 
     - Engage with the product community or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
     - TechNet: https://social.technet.microsoft.com/Forums/en-US/home.
     - MSDN: https://social.msdn.microsoft.com/Forums/en-US/home.
     - Microsoft Community: https://answers.microsoft.com/.

For all non-documentation issues, hopefully one of the community experts may be able to better assist. We will now be closing this thread.

Thank you and have a most pleasant day.
#please-close
