### ISSUE TITLE
Link is missing

### ISSUE THREAD

**Issue by it-dcs-sv** [MicrosoftDocs/windowsserverdocs#746]
The Link for the SPA Pack for Tiered Storage Spaces is missing. It just ends at another Microsoft Website.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b0fb4de-8212-0ff6-b9fa-ce87bdf2cd8d
* Version Independent ID: 8a0ba8c4-3b8d-590d-051b-b8547437359e
* Content: [Server Performance Advisor Pack for Tiered Storage Spaces](https://docs.microsoft.com/en-us/windows-server/administration/server-performance-advisor/server-performance-advisor-pack-for-tiered-storage-spaces)
* Content Source: [WindowsServerDocs/administration/server-performance-advisor/server-performance-advisor-pack-for-tiered-storage-spaces.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/server-performance-advisor/server-performance-advisor-pack-for-tiered-storage-spaces.md)
* Service: **unspecified**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by lizap** [comment]
You're right - that link is broken. We're working the problem. Sorry about that!

**Comment by coreyp-at-msft** [comment]
Hi @it-dcs-sv, 
After investigating the cause of this broken link, it appears it never pointed to a viable SPA Pack for download, and was just a placeholder. The **Performance Advisor Pack for Tiered Storage Spaces** was never released, so we will remove the page to prevent further confusion.
Thank you for brining this to our attention!
