### ISSUE TITLE
Switch Confusion (/k pauses, /c exits)

### ISSUE THREAD

**Issue by david-maw** [MicrosoftDocs/windowsserverdocs#7464]
On my windows 11 at least, the behavior of /c and /k switches is the opposite of what's documented here (/k pauses after executing the command, /c does not). documentation says:

<html>
<body>

/c | Carries out the command specified by string and then stops.
-- | --
/k | Carries out the command specified by string and continues.

</body>
</html>

 I think the confusion is just the phrasing, perhaps something like:

<html>
<body>

/c | Carries out the command specified by string and then exits the command processor.
-- | --
/k | Carries out the command specified by string and pauses the command processor.

</body>
</html>

Since it behaves as if EXIT or PAUSE had been used after the command.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0df94452-999b-43a0-be42-722fbabedaf3
* Version Independent ID: 84206d79-507f-b562-9d3f-cc3683b7abe6
* Content: [cmd](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/cmd)
* Content Source: [WindowsServerDocs/administration/windows-commands/cmd.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/cmd.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey david-maw,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made clarifying the `/c` & `/k` parameters and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
