### ISSUE TITLE
Somewhat useless forum link

### ISSUE THREAD

**Issue by DaxDupont** [MicrosoftDocs/windowsserverdocs#7465]
The MS SQL setup just refers to the forums, not a specific post. Ideally this should link to a guide on the learn. pages. 
Another acceptable option would be the link to a specific post. 
Just linking to a forum is not very useful and could lead to posts that might have wrong or insecure configurations as quality of forum posts vary.

It is either best removed entirely or replaced by something more tangible and controllable in quality.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8235ae7a-cdad-fb02-ee42-0cf6597e93db
* Version Independent ID: fe2696b4-e244-8a97-63f7-a21d9c000ba9
* Content: [Step 1 - Install the WSUS Server Role](https://learn.microsoft.com/en-us/windows-server/administration/windows-server-update-services/deploy/1-install-the-wsus-server-role?source=recommendations)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/deploy/1-install-the-wsus-server-role.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-server-update-services/deploy/1-install-the-wsus-server-role.md)
* Product: **windows-server**
* Technology: **wsus**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by dksimpson** [comment]
Hi @DaxDupont,

You are correct, the Windows Server forum link in the article doesn't provide any useful information and we are removing it.
Unfortunately, there currently isn't any learn documentation that provides information on how to install WSUS using SQL Server. However, you might find this TechNet article useful: https://social.technet.microsoft.com/forums/windowsserver/b2b80368-1b13-47fd-b0d0-fcb108b0a6f3/setting-up-wsus-for-remote-sql.

You can also try engaging with these forums:
  - From Windows, use [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**. You can also provide feedback with [Feedback](https://feedbackportal.microsoft.com/feedback).
 - Open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs).
 - Search or engage with [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home).
 - Search or engage with the [Microsoft Support Community](https://answers.microsoft.com/).

**Comment by dksimpson** [comment]
#please-close
