### ISSUE TITLE
Missing step

### ISSUE THREAD

**Issue by Tarjei-stavanger** [MicrosoftDocs/windowsserverdocs#7469]
It looks like you are forgetting to document the use of Set-VpnAuthProtocol for authentication.

It is at least vital if the VPN server is located outsize the AD domain.

I'm not sure that having the VPN in the domain is best practice.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b3227e0-102d-4acd-8480-a5fd8bdbd632
* Version Independent ID: 5b3227e0-102d-4acd-8480-a5fd8bdbd632
* Content: [Tutorial - Set up infrastructure for Always On VPN](https://learn.microsoft.com/en-us/windows-server/remote/remote-access/tutorial-aovpn-deploy-setup)
* Content Source: [WindowsServerDocs/remote/remote-access/tutorial-aovpn-deploy-setup.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-access/tutorial-aovpn-deploy-setup.md)
* Product: **windows-server**
* Technology: **remote**
* GitHub Login: @anaharris-ms
* Microsoft Alias: **anaharris**

**Comment by Xelu86** [comment]
Hey Tarjei-stavanger,

Thanks again for contacting Microsoft, we value your feedback. 

The steps outlined in this document specifically are performed all through the Windows Server Manager. No mention of performing these actions in PowerShell are discussed. At this time, we are not making updates to this document. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
