### ISSUE TITLE
Microsoft Cluster Documentation

### ISSUE THREAD

**Issue by artur-aragao** [MicrosoftDocs/windowsserverdocs#7470]
Microsoft Cluster Documentation

Dear,

About Microsoft Cluster documentation, I am not finding in the base, information about requirements and recommendations for resizing a shared volume on top of a Hyper-V Cluster. Mainly about implementations by versions.

Could you please help in this scenario?

The documentation I found about Clustering is this - "https://learn.microsoft.com/en-us/windows-server/failover-clustering/failover-cluster-csvs".

**Comment by Xelu86** [comment]
Hey @artur-aragao,

> The documentation I found about Clustering is this - "https://learn.microsoft.com/en-us/windows-server/failover-clustering/failover-cluster-csvs".

Are any of these pages helpful & what you're looking for?

- https://learn.microsoft.com/en-us/archive/blogs/chrad/cluster-shared-volumes-csv-extending-a-volume
- https://learn.microsoft.com/en-us/troubleshoot/windows-server/high-availability/extend-partition-cluster-shared-disk
- https://learn.microsoft.com/en-us/troubleshoot/windows-server/backup-and-storage/extending-csv-isnt-blocked
- https://learn.microsoft.com/en-us/system-center/vmm/hyper-v-storage?view=sc-vmm-2022

Please let us know if any of the pages addresses your question.

**Comment by artur-aragao** [comment]
> Hey @artur-aragao,
> 
> > The documentation I found about Clustering is this - "https://learn.microsoft.com/en-us/windows-server/failover-clustering/failover-cluster-csvs".
> 
> Are any of these pages helpful & what you're looking for?
> 
> * https://learn.microsoft.com/en-us/archive/blogs/chrad/cluster-shared-volumes-csv-extending-a-volume
> * https://learn.microsoft.com/en-us/troubleshoot/windows-server/high-availability/extend-partition-cluster-shared-disk
> * https://learn.microsoft.com/en-us/troubleshoot/windows-server/backup-and-storage/extending-csv-isnt-blocked
> * https://learn.microsoft.com/en-us/system-center/vmm/hyper-v-storage?view=sc-vmm-2022
> 
> Please let us know if any of the pages addresses your question.

Thank you very much for your contribution.
Helped me a lot!
