### ISSUE TITLE
Commands are incorrect

### ISSUE THREAD

**Issue by NE137** [MicrosoftDocs/windowsserverdocs#7472]
Commands are incorrect: should be: `manage-bde -tpm -turnon`
instead of `manage-bde tpm -turnon`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c00fc666-2988-82e3-9391-b39dfab356ff
* Version Independent ID: 6f6452e7-9bad-4c4b-3d43-f3964327e60f
* Content: [manage-bde tpm](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/manage-bde-tpm)
* Content Source: [WindowsServerDocs/administration/windows-commands/manage-bde-tpm.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/manage-bde-tpm.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey NE137,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made correcting the parameter in the examples and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
