### ISSUE TITLE
What attributute is set by Set-LapsADComputerSelfPermission?

### ISSUE THREAD

**Issue by smillpch** [MicrosoftDocs/windowsserverdocs#7473]
Could you possibly update this page with how to query an AD space for the attribute which gets created by the Set-LapsADComputerSelfPermission command? I can't find that anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70be2bc5-d5c8-3802-5a11-76885966af5b
* Version Independent ID: 70be2bc5-d5c8-3802-5a11-76885966af5b
* Content: [Windows LAPS overview](https://learn.microsoft.com/en-us/windows-server/identity/laps/laps-overview)
* Content Source: [WindowsServerDocs/identity/laps/laps-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/laps/laps-overview.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @jay98014
* Microsoft Alias: **jsimmons**

**Comment by Xelu86** [comment]
Hey @smillpch,

Thanks again for contacting Microsoft. We value your feedback.

To query, are you referring to this command potentially?

`Get-ADComputer -Identity <computername> -Properties ms-Mcs-AdmPwdExpirationTime`

**Comment by smillpch** [comment]
I was looking for a command I could run against the entire AD structure which would tell me what OUs have the permission set to allow the computers in that OU to update their own LAPS password.

**Comment by Xelu86** [comment]
Closing thread.
#please-close
