### ISSUE TITLE
how to solved

### ISSUE THREAD

**Issue by nurersafa007** [MicrosoftDocs/windowsserverdocs#7491]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51695048-f8f8-c2c1-89ff-dc3614f9d3d8
* Version Independent ID: 372b149c-9a75-7db5-f8fd-4820e7b05b35
* Content: [Plan for Hyper-V scalability in Windows Server](https://learn.microsoft.com/en-us/windows-server/virtualization/hyper-v/plan/plan-hyper-v-scalability-in-windows-server#failover-clusters-and-hyper-v)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/plan/plan-hyper-v-scalability-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/virtualization/hyper-v/plan/plan-hyper-v-scalability-in-windows-server.md)
* Product: **windows-server**
* Technology: **hyper-v**
* GitHub Login: @BenjaminArmstrong
* Microsoft Alias: **benarm**

**Comment by Xelu86** [comment]
Hey nurersafa007,

Thanks again for contacting Microsoft. We value your feedback. 

We're unable to determine what the intent of your question is. If there are any errors or areas of improvement with said documentation, please let us know so we may better assist. We're now closing this thread.

Thank you and have a most pleasant day.
#please-close
