### ISSUE TITLE
"CSV" does not sound very reliable

### ISSUE THREAD

**Issue by SamB** [MicrosoftDocs/windowsserverdocs#7494]
You, uh, might want to let marketting know about CSV's unfortunate connotations, at least with respect to reliability.

To quote the Python Library docs for [`csv`](https://docs.python.org/3/library/csv.html):

>The so-called CSV (Comma Separated Values) format is the most common import and export format for spreadsheets and databases. CSV format was used for many years prior to attempts to describe the format in a standardized way in [RFC 4180](https://datatracker.ietf.org/doc/html/rfc4180.html). The lack of a well-defined standard means that subtle differences often exist in the data produced and consumed by different applications. These differences can make it annoying to process CSV files from multiple sources.

(Mind you, any given variant of Comma Separated Values isn't necessarily unreliable. The problem is that there are so many to choose from, and software attempting to consume CSV essentially has to know in advance which variant to parse it as - or let the user interactively preview the results as they tweak syntax parameters. I suppose nowadays this often boils down to "try to do what Excel would do in a US English locale".)

So, it might be a good idea to figure out some way to avoid the collision in initialisms, given that Cluster Shared Volumes are presumably supposed to make things *more* reliable, not less.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ede5970f-3974-f410-2d00-d99ae6177e9e
* Version Independent ID: 835f76fc-f470-d52e-50e8-880f7986a65c
* Content: [NTFS overview](https://learn.microsoft.com/en-us/windows-server/storage/file-server/ntfs-overview)
* Content Source: [WindowsServerDocs/storage/file-server/ntfs-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/file-server/ntfs-overview.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey SamB,

Thanks for contacting Microsoft. We value your feedback.

Per the feedback you provided, we recommend that you use either of the following:

 - If on a Windows OS, the [Windows Feedback Hub](https://aka.ms/WIPFeedbackHub) or press **Windows + F**.
 - You can also provide feedback with using our [Feedback Portal](https://feedbackportal.microsoft.com/feedback).
 
GitHub issues in the Windows Server repo are monitored for content issues that we can address, such as broken links, grammar or wording, typos, updates, or incorrect code in examples. 

As this isn't a general documentation issue, we’re closing this thread.

Thank you and have a most pleasant day. 
#please-close
