### ISSUE TITLE
Print

### ISSUE THREAD

**Issue by blanglo10** [MicrosoftDocs/windowsserverdocs#7503]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5bdb199f-b5ad-2da1-c497-d98bcf6deb9b
* Version Independent ID: c0238945-29e5-a91f-82cf-308f68e333e8
* Content: [Migrate your Remote Desktop Services Client Access Licenses (RDS CALs)](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/migrate-rds-cals)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/migrate-rds-cals.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/migrate-rds-cals.md)
* Product: **windows-server**
* Technology: **remote-desktop-services**
* GitHub Login: @ChristianMontoya
* Microsoft Alias: **chrimo**

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. 

We're unable to determine what the intent of your question is. If there are any errors or areas of improvement with said documentation, please let us know so we may better assist. We're now closing this thread.

Thank you and have a most pleasant day.
#please-close
