### ISSUE TITLE
Ayuda

### ISSUE THREAD

**Issue by Diegonavaa** [MicrosoftDocs/windowsserverdocs#7504]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: da547401-f0e8-a8ae-f350-a309109895d4
* Version Independent ID: c8521262-0bac-e256-1cd5-1b65e4902967
* Content: [Configure RADIUS Clients](https://learn.microsoft.com/en-us/windows-server/networking/technologies/nps/nps-radius-clients-configure)
* Content Source: [WindowsServerDocs/networking/technologies/nps/nps-radius-clients-configure.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/networking/technologies/nps/nps-radius-clients-configure.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Thanks again for contacting Microsoft. We value your feedback. 

We're unable to determine what the intent of your question is. If there are any errors or areas of improvement with said documentation, please let us know so we may better assist. We're now closing this thread.

Thank you and have a most pleasant day.
#please-close
