### ISSUE TITLE
CAVANDOWS system 2cmd.exe sh  Microsoft Windows [Version

### ISSUE THREAD

**Issue by khovvannak23** [MicrosoftDocs/windowsserverdocs#7514]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 45b9a61b-38a5-151e-376c-ea2786acf8dd
* Version Independent ID: dd7a38cb-2485-0d03-8441-aa4cca2899cd
* Content: [Command-line syntax key](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/command-line-syntax-key)
* Content Source: [WindowsServerDocs/administration/windows-commands/command-line-syntax-key.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/command-line-syntax-key.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **alalve**

**Comment by khovvannak23** [comment]
CAVANDOWS system 2cmd.exe sh

Microsoft Windows [Version

**Comment by Xelu86** [comment]
Closing as this is a non-document issue. #please-close

**Comment by khovvannak23** [comment]
ប្រព័ន្ធ CAVANDOWS 2cmd.exe sh Microsoft Windows [កំណែ
