### ISSUE TITLE
Active Directory Replication Status Tool Link Not Working

### ISSUE THREAD

**Issue by aakash-shah** [MicrosoftDocs/windowsserverdocs#7515]
There is a link to the [Active Directory Replication Status Tool](https://www.microsoft.com/download/details.aspx?id=30005). However this link is not working. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2df81ca8-c5f9-d1f1-cbf1-5b7dbf2beb23
* Version Independent ID: 22d77ad4-f25f-7550-fcfe-07bca8313f1a
* Content: [Troubleshooting Active Directory Replication Problems](https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/troubleshoot/troubleshooting-active-directory-replication-problems)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/troubleshoot/Troubleshooting-Active-Directory-Replication-Problems.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-ds/manage/troubleshoot/Troubleshooting-Active-Directory-Replication-Problems.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @iainfoulds
* Microsoft Alias: **daveba**

**Comment by Xelu86** [comment]
Hey @aakash-shah,

Thanks again for contacting Microsoft, we value your feedback. 

Per this page: https://learn.microsoft.com/en-us/troubleshoot/windows-server/active-directory/get-use-active-directory-replication-status-tool

> As of June 2nd, 2023, the Active Directory Replication Status Tool is no longer available for download.

We have updated this doc and removed the dead link. Changes will be live after the next business day. We will now be closing this thread.

Thank you and have a most pleasant day. 
#please-close
