### ISSUE TITLE
Add shutdown reason codes

### ISSUE THREAD

**Issue by gtimread** [MicrosoftDocs/windowsserverdocs#7516]
This article would be improved by adding a full table of the shutdown reason codes, e.g.

Reason codes
 E = unplannEd 0x10000000
  U = Unexpected 0x00000000
   P = Planned 0x80000000
   C = customer defined 0x40000000 (for these, specify your own Major reason # in the range 64-255)

Type    Major Minor Title
  U      0     0    Other (Unplanned)
 E       0     0    Other (Unplanned) 
 E P     0     0    Other (Planned)
  U      0     5    Other Failure: System Unresponsive
 E       1     1    Hardware: Maintenance (Unplanned)
 E P     1     1    Hardware: Maintenance (Planned)
 E       1     2    Hardware: Installation (Unplanned)
 E P     1     2    Hardware: Installation (Planned)
   P     2     3    Operating System: Upgrade (Planned)
 E       2     4    Operating System: Reconfiguration (Unplanned)
 E P     2     4    Operating System: Reconfiguration (Planned)
   P     2     16   Operating System: Service pack (Planned)
         2     17   Operating System: Hot fix (Unplanned)
   P     2     17   Operating System: Hot fix (Planned)
         2     18   Operating System: Security fix (Unplanned)
   P     2     18   Operating System: Security fix (Planned)
 E       4     1    Application: Maintenance (Unplanned)
 E P     4     1    Application: Maintenance (Planned)
 E P     4     2    Application: Installation (Planned)
 E       4     5    Application: Unresponsive
 E       4     6    Application: Unstable
  U      5     15   System Failure: Stop error
 E       5     19   Security issue
  U      5     19   Security issue
 E P     5     19   Security issue
 E       5     20   Loss of network connectivity (Unplanned)
  U      6     11   Power Failure: Cord Unplugged
  U      6     12   Power Failure: Environment
   P     7     0    Legacy API shutdown

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2770335e-d15c-6389-36b9-d687b7794b92
* Version Independent ID: 319c885a-1c12-595f-8018-c563945afe93
* Content: [shutdown](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/shutdown)
* Content Source: [WindowsServerDocs/administration/windows-commands/shutdown.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/shutdown.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @Xelu86
* Microsoft Alias: **wscontent**

**Comment by Xelu86** [comment]
Hey gtimread,

Thanks again for contacting Microsoft. We value your feedback. 

A documentation change has been made adding the shutdown/restart reasons into a table and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
