### ISSUE TITLE
Update-LapsADSchema "not recognized"

### ISSUE THREAD

**Issue by copenhaus** [MicrosoftDocs/windowsserverdocs#7519]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a984ce3b-9369-d01b-17f1-d93b4fe3dcc6
* Version Independent ID: a984ce3b-9369-d01b-17f1-d93b4fe3dcc6
* Content: [Get started with Windows LAPS and Windows Server Active Directory](https://learn.microsoft.com/en-us/windows-server/identity/laps/laps-scenarios-windows-server-active-directory)
* Content Source: [WindowsServerDocs/identity/laps/laps-scenarios-windows-server-active-directory.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/laps/laps-scenarios-windows-server-active-directory.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @jay98014
* Microsoft Alias: **jsimmons**

**Comment by jay98014** [comment]
@copenhaus - can you please clarify the issue you are seeing?  I can't figure it out based on the minimal details supplied here.

**Comment by copenhaus** [comment]
Update-LapsADSchema command is not recognized.  My DC servers are Win2016 and DFL is 2016, but it doesn't recognize the command.

**Comment by jay98014** [comment]
The LAPS PowerShell module is not available on Windows Server 2016.   It is only available on patched versions of Windows 10 and later, and Windows Server 2019 and later.   You can run the Update-LapsADSchema cmdlet from one of those machines and it will work fine (it updates the schema remotely over LDAP).

Also see:   [Windows LAPS supported platforms and Azure AD LAPS preview status](https://learn.microsoft.com/windows-server/identity/laps/laps-overview#windows-laps-supported-platforms-and-azure-ad-laps-preview-status)

Does that help?

**Comment by jay98014** [comment]
@copenhaus - let me know if you need anything else, otherwise we'll close this issue out.
