### ISSUE TITLE
chcp

### ISSUE THREAD

**Issue by NickSLI** [MicrosoftDocs/windowsserverdocs#7524]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c4b8705-8d38-cad1-a9aa-42e98003624d
* Version Independent ID: ef824a08-3cbb-b96b-b45f-f54cd0994521
* Content: [chcp](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/chcp)
* Content Source: [WindowsServerDocs/administration/windows-commands/chcp.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/chcp.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey NickSLI,

Is there an issue with the `chcp` documentation?

**Comment by Xelu86** [comment]
Due to no response, we’ll now be closing this thread. If a documentation issue is still present, please consider opening a new issue. #please-close
