### ISSUE TITLE
Replace link to VM Compute Resiliency article

### ISSUE THREAD

**Issue by i3laze** [MicrosoftDocs/windowsserverdocs#7528]
URL in the text is broken:
[Virtual Machine Compute Resiliency in Windows Server 2016](https://blogs.msdn.com/b/clustering/archive/2015/06/03/10619308.aspx)

This is the correct URL:
https://techcommunity.microsoft.com/t5/failover-clustering/virtual-machine-compute-resiliency-in-windows-server-2016/ba-p/372027

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4150f10d-0ac3-0a70-8bcb-c7c2fa630f66
* Version Independent ID: 41670466-1fa8-d27c-965d-59e3ac362676
* Content: [What's new in Failover Clustering in Windows Server](https://learn.microsoft.com/en-us/windows-server/failover-clustering/whats-new-in-failover-clustering)
* Content Source: [WindowsServerDocs/failover-clustering/whats-new-in-failover-clustering.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/failover-clustering/whats-new-in-failover-clustering.md)
* Product: **windows-server**
* Technology: **failover-clustering**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey i3laze,

Thanks again for contacting Microsoft, we value your feedback. 

A documentation change has been made updating the link to direct users to the WS2016 VM Compute Resiliency page and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
