### ISSUE TITLE
Typo in api permissions at "Create an Azure Active Directory registered app to retrieve Windows LAPS passwords"

### ISSUE THREAD

**Issue by bmemvandenhoek** [MicrosoftDocs/windowsserverdocs#7532]
At the part Create an Azure Active Directory registered app to retrieve Windows LAPS passwords it says the app requires Device.LocalCredential.Read. The dot between Device and LocalCredential needs to be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d25e426f-b6ed-c9db-1b8f-4c755789e0a6
* Version Independent ID: d25e426f-b6ed-c9db-1b8f-4c755789e0a6
* Content: [Get started with Windows LAPS and Azure Active Directory](https://learn.microsoft.com/en-us/windows-server/identity/laps/laps-scenarios-azure-active-directory)
* Content Source: [WindowsServerDocs/identity/laps/laps-scenarios-azure-active-directory.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/laps/laps-scenarios-azure-active-directory.md)
* Product: **windows-server**
* Technology: **security**
* GitHub Login: @jay98014
* Microsoft Alias: **jsimmons**

**Comment by jay98014** [comment]
Thanks @bmemvandenhoek - I will fix this.

**Comment by jay98014** [comment]
@bmemvandenhoek - the fix is now live, lmk if you see other issues.

**Comment by jay98014** [comment]
#please-close
