### ISSUE TITLE
/iorate:<n>[kmg] usage is unclear

### ISSUE THREAD

**Issue by elliotstaker** [MicrosoftDocs/windowsserverdocs#7547]
I can't figure out how to correctly use `/iorate:<n>[kmg]`.  An example would be great!

I've tried
/iorate:1000k
/iorate:1000:k
/iorate:1000[k]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy#related-links)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @Xelu86
* Microsoft Alias: **wscontent**

**Comment by Xelu86** [comment]
Hey @elliotstaker,

Thanks again for contacting Microsoft, we value your feedback. 

These throttling options accepts values in bytes per second. If not specifying in bytes per second, whole numbers can be used in k, m, or g. Any values less than 524288 bytes gets bumped to this value.

```cmd
robocopy <source> <destination> <options> /iorate:<value>
```
```cmd
robocopy <source> <destination> <options> /iorate:<value>[kmg]
```

A documentation change has been made adding this information, including an example, and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
