### ISSUE TITLE
Step 4, last line is missleading

### ISSUE THREAD

**Issue by floremsft** [MicrosoftDocs/windowsserverdocs#755]
At the end of Step 4, you are asked to either go to Step 8, or 7, which make you skip steps 5 and 6 in any case.
A customer and myself interpreted the instructions the same way. But we soon realized that step 6 was mandatory.
Could it be rephrased?

Also, my customer and I faced the same issue described below, to bring the WSUS server online again:
-WID had to be removed
-WSUSutil.exe command required
https://social.technet.microsoft.com/Forums/ie/en-US/fd38f661-0352-4cee-b6df-4bf4763b3aa4/updateservicesdbxml-missing?forum=winserverwsus

_Step 4:
Verify permissions on the database:
Right-click the SUSDB, select Properties, and then click Permissions. The NT AUTHORITY\NETWORK SERVICE account should be listed. If it is not, you need to add it.
**If both WSUS and SQL Instance are on the same machine skip to step 8. Otherwise proceed to step 7.**_

**Comment by lizap** [comment]
We seem to have lost the associated article - which one were you trying to follow? Thanks!

**Comment by floremsft** [comment]
Here is the link to our documentation : https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/manage/wid-to-sql-migration

**Comment by floremsft** [comment]
Hi Liza,

It looks like my comment did not get attached to the WSUS article, I was not signed in properly…
Sorry, I am a GitHub beginner.

If you can link it to the below article, that would be great, otherwise I could repost my comment again
https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/manage/wid-to-sql-migration

Let me know!

Florent


Florent Mordelet



Premier Field Engineer | System Center/Azure/EMS
Enterprise Services Delivery | Secure Infrastructure
Microsoft Canada | Mississauga Office
[MSFT_logo_Gray DE sized SIG1.png]    [https://www.mcneese.edu/sites/all/themes/mcneese_www/images/linkedin_icon.png] <https://www.linkedin.com/in/florent-mordelet-576b9914/>

Office: (289) 305 9868
Mobile: (+1) 416 985 4233
Florent.mordelet@microsoft.com<mailto:Florent.mordelet@microsoft.com>

**Comment by sml156** [comment]
Ya you are a beginner do you really need your contact info published to the public, Or is this the new way to game Googles SEO tack ticks

**Comment by floremsft** [comment]
Reopened on WSUS docs:https://github.com/MicrosoftDocs/windowsserverdocs/issues/769

**Comment by floremsft** [comment]
Comment added to the proper MSFT Doc
