### ISSUE TITLE
Documentation needs correction  - Start-Service sshd  

### ISSUE THREAD

**Issue by penguinpages** [MicrosoftDocs/windowsserverdocs#7564]
[Enter feedback here]

Powershell command sequence does not work.  Once install is completed the OpenSSH services cannot start (powershell or GUI).

I believe instructions fail to set proper security services and roles for service.

https://github.com/PowerShell/Win32-OpenSSH/issues/907

Overall the document otherwise is well written and looks great.  Just needs some cleanup

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Get started with OpenSSH for Windows](https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse?tabs=powershell)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @robinharwood
* Microsoft Alias: **roharwoo**

**Comment by Xelu86** [comment]
Hey @penguinpages,

Thanks again for contacting Microsoft, we value your feedback.

Going through the steps of installing OpenSSH in our VMs and starting the sshd service via PowerShell and through the Services GUI generated no issues on our end. This was tested in Windows 10, 11, Server 19, and Server 22: 

<img width="1004" alt="image" src="https://github.com/MicrosoftDocs/windowsserverdocs/assets/103963494/6b860080-4492-4698-a074-806672f2f8ba">

As there are no issues within the steps involved in this document, no updates are to be made at this time. 

If you're experiencing issues on your device, please reach out to our community forums as this is outside our scope of work:

- [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home)
- [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home)
- [Microsoft Support Community](https://answers.microsoft.com/)

We will now be closing this thread. Thank you and have a most pleasant day. 
#please-close
