### ISSUE TITLE
OPEN SSH

### ISSUE THREAD

**Issue by Massis1950** [MicrosoftDocs/windowsserverdocs#7578]
Merci pour votre article  qui m'a permis de configurer un accès Sftp vers mon pc w11

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Get started with OpenSSH for Windows](https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse?tabs=gui)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @robinharwood
* Microsoft Alias: **roharwoo**

**Comment by Xelu86** [comment]
Hey @Massis1950,

Thanks again for contacting Microsoft, we value your feedback.

We're glad to hear our documentation assisted you on your Windows device. As this is a non-documentation issue, we’re closing this thread.

Thank you and have a most pleasant day. 
#please-close
