### ISSUE TITLE
client credentials flow

### ISSUE THREAD

**Issue by manishdalal2** [MicrosoftDocs/windowsserverdocs#759]
Not getting custom claims when flow is client credentials. 
Ex- RPT identifier is  https://scale
code is 
await authContext.AcquireTokenAsync("https://scale", clientCredential);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e04047c8-df0d-d752-afc1-0daa314e5d75
* Version Independent ID: 93cac62e-204f-b523-3751-51e420672555
* Content: [Customize claims to be emitted in id_token when using OpenID Connect or OAuth with AD FS 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/custom-id-tokens-in-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/Custom-Id-Tokens-in-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/Custom-Id-Tokens-in-AD-FS.md)
* Service: **unspecified**
* GitHub Login: @anandyadavMSFT
* Microsoft Alias: **billmath**

**Comment by akgoel23** [comment]
Hi manishdalal2,

In client credential flow ID Token is not issued, only Access Token is issued. Please see https://tools.ietf.org/html/rfc6749#section-4.4 for more details. In case you are not getting additional claims in access token, make sure you are passing the resource parameter in the token request. 


Thanks.

**Comment by IngridAtMicrosoft** [comment]
#please-close
