### ISSUE TITLE
Spell out HKLM, HKCU, HKCR, HKU, and HKCC

### ISSUE THREAD

**Issue by karlbo** [MicrosoftDocs/windowsserverdocs#7610]
Change "HKLM" to "HKLM (i.e., HKEY_LOCAL_MACHINE)", "HKCU" to "HKCU (i.e., HKEY_CURRENT_USER)" and so forth. It's a very simple fix that could have a relatively large impact.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd817f1d-e494-af38-4a10-86360d63c195
* Version Independent ID: 11fcbf91-6c28-9ae8-045a-35ea97444dfe
* Content: [reg add](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/reg-add)
* Content Source: [WindowsServerDocs/administration/windows-commands/reg-add.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/reg-add.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @Xelu86
* Microsoft Alias: **wscontent**

**Comment by Xelu86** [comment]
Hey @karlbo,

Thanks again for contacting Microsoft, we value your feedback. 

A documentation change has been made where the registry path keynames have been expanded for more clarity and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
