### ISSUE TITLE
/?

### ISSUE THREAD

**Issue by xtso08** [MicrosoftDocs/windowsserverdocs#7619]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c4e01700-60c9-ae17-6296-963cc80d5438
* Version Independent ID: 8dc84763-6f4b-558b-439b-b35e41ed663f
* Content: [hostname](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/hostname)
* Content Source: [WindowsServerDocs/administration/windows-commands/hostname.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/hostname.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
User feedback is unspecified or unrelated to documentation. Closing thread.
