### ISSUE TITLE
What about on premise designs?

### ISSUE THREAD

**Issue by CVTejas** [MicrosoftDocs/windowsserverdocs#762]
We all realize MSFT is pushing everything to Azure.  That doesn't mean you should over look solutions where a customer may prefer an on premise deployment or a hybrid deployment.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 428e9e07-ca35-27d2-e63a-92930cec0118
* Version Independent ID: 9a452a85-9afa-42d5-f319-bf1c4c50d01d
* Content: [Remote Desktop Services architecture](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/desktop-hosting-logical-architecture)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/Desktop-hosting-logical-architecture.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/Desktop-hosting-logical-architecture.md)
* Service: **unspecified**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by clowg** [comment]
Can you please update these reference architectures to include on-premises iterations.

**Comment by PhrygianMode** [comment]
Yes.  Can you please include on-premises diagrams?

**Comment by sasanmcp** [comment]
almost all the diagrams above can be adapter for an on-premises deployment:
for "Virtual Network", simply put "Corp Network", put "RDWEB and RDGateway" in the DMZ portion of your Corp network, keep the rest of them in the Internal subnet of your Corp network.
make your security team onboard with the design that "RDWEB and RDGATEWAYs are domain-joined servers in the DMZ and there is no alternative".
for SQL, it could be any flavor of SQL such as Azure SQL, on-prem Always On SQL ,Clustered SQL or even a single-instance SQL with no HA.
