### ISSUE TITLE
Text over another text

### ISSUE THREAD

**Issue by mozilla343** [MicrosoftDocs/windowsserverdocs#7628]
See the issue in this [screenshot](https://github.com/MicrosoftDocs/windowsserverdocs/assets/62311944/6ac5060f-cfd0-42b2-980f-2c2b1799b9f3):

![image](https://github.com/MicrosoftDocs/windowsserverdocs/assets/62311944/6ac5060f-cfd0-42b2-980f-2c2b1799b9f3)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f38b3e17-9e4b-958b-5b4c-87f230f43254
* Version Independent ID: f38b3e17-9e4b-958b-5b4c-87f230f43254
* Content: [Security identifiers](https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/understand-security-identifiers)
* Content Source: [WindowsServerDocs/identity/ad-ds/manage/understand-security-identifiers.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-ds/manage/understand-security-identifiers.md)
* Product: **windows-server**
* Technology: **ad-ds**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by Xelu86** [comment]
Hey @mozilla343,

Thanks again for contacting Microsoft, we value your feedback. 

A documentation change has been made correcting the text overflow issue and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
