### ISSUE TITLE
Please fix the DNS records for dns.msftncsi.com for IPv6 address

### ISSUE THREAD

**Issue by saudiqbal** [MicrosoftDocs/windowsserverdocs#7634]
My firewall logs are full of errors because someone at Microsoft decided to use a local IPv6 address for checking Internet connectivity for Windows.

DNS A record: 131.107.255.255

(Correct public IP)

DNS AAAA record: fd3e:4f5a:5b81::1

(Incorrect private IP)

Please use a global public IPv6 address for checking Internet connectivity.

https://learn.microsoft.com/en-us/answers/questions/1412403/please-fix-the-dns-records-for-dns-msftncsi-com-fo

**Comment by Xelu86** [comment]
Hey @saudiqbal,

Thanks again for contacting Microsoft, we value your feedback. 

Is this concerning a specific document?
