### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by 6OClark** [MicrosoftDocs/windowsserverdocs#7635]
Manage from anywhere
Publish your Windows Admin Center gateway server to the public Internet, then you can connect to and manage servers your from anywhere, all in a secure manner.
[Enter feedback here] It needs to read "manage your servers"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5fe3f40d-c04f-55bf-df8d-846ef2411108
* Version Independent ID: 4eb546b9-3821-70bb-3257-8cdd6a26f57a
* Content: [What is Windows Admin Center](https://learn.microsoft.com/en-us/windows-server/manage/windows-admin-center/understand/what-is#manage-from-anywhere)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/understand/what-is.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/manage/windows-admin-center/understand/what-is.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @davannaw-msft
* Microsoft Alias: **dawhite**

**Comment by Xelu86** [comment]
Hey @6OClark,

Thanks again for contacting Microsoft, we value your feedback. 

A documentation change has been made correcting the grammar in the "Manage from anywhere" section and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day.
