### ISSUE TITLE
issue with the article

### ISSUE THREAD

**Issue by Tarjei-stavanger** [MicrosoftDocs/windowsserverdocs#7637]
The article contains only information about the VPN connection. Not general WI-FI.

I'm interested because we have problems with a GPO which works with Windows 11 and not Windows 10. So we consider creating a new WI-FI profile for EAP-TEAP using PowerShell, but it is not easy to find information on doing so. This is no exception since it only deals with VPN.

Incidentally EAP-TEAP works if you do it manually on Windows 10, but not using a GPO. This is annoying.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e818388-3006-88d8-23a8-a22411d6d484
* Version Independent ID: 1e818388-3006-88d8-23a8-a22411d6d484
* Content: [Configure EAP profiles and settings in Windows](https://learn.microsoft.com/en-us/windows-server/networking/technologies/extensible-authentication-protocol/configure-eap-profiles?tabs=netsh-wifi%2Cpowershell-vpn%2Csettings-wifi%2Cgroup-policy-wifi)
* Content Source: [WindowsServerDocs/networking/technologies/extensible-authentication-protocol/configure-eap-profiles.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/networking/technologies/extensible-authentication-protocol/configure-eap-profiles.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @samyun
* Microsoft Alias: **wscontent**

**Comment by samyun** [comment]
I assume you're referring to the `PowerShell` section when you say it only has info about VPN. This is because there is no native PowerShell cmdlet to interact with Wi-Fi (or Ethernet) profiles. I suggest using `netsh` or the other UI, both details on that same page.

**Comment by samyun** [comment]
#please-close
