### ISSUE TITLE
What URLs are accessed by the Azure MFA Adapter?

### ISSUE THREAD

**Issue by peternield** [MicrosoftDocs/windowsserverdocs#764]
If using a web proxy to egress to the public Internet, what URLs need to whitelisted for this to function?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae96cfcf-0a50-7e13-30c8-43e3730e184f
* Version Independent ID: 9d8ed7b7-eec6-1b95-40b8-24a13361f66d
* Content: [Configure AD FS 2016 and Azure MFA](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md)
* Service: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by custorod** [comment]
login.microsoftonline.com and adnotifications.windowsazure.com over port 443.

**Comment by MicrosoftGuyJFlo** [comment]
The server needs to be able to communicate with the following URLs over ports 80 and 443.
•	https://adnotifications.windowsazure.com 
•	https://login.microsoftonline.com

**Comment by MicrosoftGuyJFlo** [comment]
Adding to doc with a PR against our private repo.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
