### ISSUE TITLE
No windows 11 method

### ISSUE THREAD

**Issue by SickProdigy** [MicrosoftDocs/windowsserverdocs#7644]
Would at least like a link to download a good openssh client for windows 10/11. Not just, oh click a few things and IF you see it here, download it here.  There's also no windows 11 version. So can't find anything that's relevant on that page. It's also the first page to come up on goodl when searching openssh windows

After a little bit of searching
It's
System > optional Features

This is where you will see if openssh is installed. Windows 11. 

Doesn't show on installed applications. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Get started with OpenSSH for Windows](https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse?tabs=gui)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @robinharwood
* Microsoft Alias: **roharwoo**

**Comment by Xelu86** [comment]
Hey @SickProdigy

Thanks again for contacting Microsoft, we value your feedback. 

A documentation change was recently made addressing installing OpenSSH on Windows 11 devices and is currently live. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
