### ISSUE TITLE
Do not download Perfomance Tunning IIS

### ISSUE THREAD

**Issue by cuongva1804** [MicrosoftDocs/windowsserverdocs#7650]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6d673198-cf0c-5e77-9416-0f5e5e4d7f0e
* Version Independent ID: a689482c-674d-fcf2-0375-e8066d543973
* Content: [Windows Server 2022 Performance Tuning Guidelines](https://learn.microsoft.com/en-us/windows-server/administration/performance-tuning/)
* Content Source: [WindowsServerDocs/administration/performance-tuning/index.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/performance-tuning/index.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @phstee
* Microsoft Alias: **phstee**

**Comment by Joachim-Otahal** [comment]
Aaaand why?

**Comment by Xelu86** [comment]
User feedback is unspecified/unrelated to documentation. Closing thread.
