### ISSUE TITLE
Failed Foreign Disk Import

### ISSUE THREAD

**Issue by francoluis** [MicrosoftDocs/windowsserverdocs#7652]
[Enter feedback here]
When I imported the foreign disk, it gives me a status of failed for the Raid 1 folder but every other folders are ok:
![image](https://github.com/MicrosoftDocs/windowsserverdocs/assets/7529127/439a6457-7bee-4ea8-8322-568404dbf5d9)

What can I do? The document doesn't give any guidelines for this issue.

Thank you.
Best regards.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d50fc049-8fad-f318-1d3a-f5a50ad2a5ac
* Version Independent ID: 742902d7-d4be-d211-ee78-293101d06f02
* Content: [Move disks to another computer](https://learn.microsoft.com/en-us/windows-server/storage/disk-management/move-disks-to-another-computer)
* Content Source: [WindowsServerDocs/storage/disk-management/move-disks-to-another-computer.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/disk-management/move-disks-to-another-computer.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Xelu86** [comment]
Hey @francoluis,

Thanks again for contacting Microsoft, we value your feedback. 

You have described an issue that is not covered in this documentation when importing foreign drives. It's outside our scope to address issues that aren't document related.


Please search and engage within our community forums:


- [Microsoft TechNet](https://social.technet.microsoft.com/Forums/home)
- [Microsoft Developer Network](https://social.msdn.microsoft.com/Forums/home)
- [Microsoft Support Community](https://answers.microsoft.com/)
- Or open a ticket with [Microsoft Support](https://support.microsoft.com/ContactUs)

Hopefully one of our community members may be better able to assist. We'll now be closing this thread.

Thank you and have a most pleasant day.
