### ISSUE TITLE
Spelling update

### ISSUE THREAD

**Issue by rinseaid** [MicrosoftDocs/windowsserverdocs#7653]
The title of "How this effects extensions" should read "How this affects extensions."

https://learn.microsoft.com/en-us/windows-server/manage/windows-admin-center/understand/modernized-gateway#how-this-effects-extensions

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bf6c9fe6-8e87-5e85-3da3-ac0bc14e78a0
* Version Independent ID: bf6c9fe6-8e87-5e85-3da3-ac0bc14e78a0
* Content: [Windows Admin Center modernized gateway (Preview)](https://learn.microsoft.com/en-us/windows-server/manage/windows-admin-center/understand/modernized-gateway)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/understand/modernized-gateway.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/manage/windows-admin-center/understand/modernized-gateway.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @davannaw-msft
* Microsoft Alias: **dawhite**

**Comment by Xelu86** [comment]
Hey @rinseaid,

Thanks again for contacting Microsoft, we value your feedback. 

A documentation change has been made correcting the 6th header (effects > affects) and will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day.
