### ISSUE TITLE
dy

### ISSUE THREAD

**Issue by dylanzhang200** [MicrosoftDocs/windowsserverdocs#7654]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bf2281d4-1470-0658-ec5a-687fe2cd451c
* Version Independent ID: 2ce2be3e-e3a2-790c-3bff-90efe7318450
* Content: [robocopy](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server**
* Technology: **windows-commands**
* GitHub Login: @Xelu86
* Microsoft Alias: **wscontent**

**Comment by Xelu86** [comment]
User feedback is unspecified/unrelated to documentation. Closing thread.
#please-close
