### ISSUE TITLE
Path needs to be updated.

### ISSUE THREAD

**Issue by ScubadooX** [MicrosoftDocs/windowsserverdocs#7659]
This post needs to be updated. The correct path to enable OpenSSH Server, at least on Windows 11, is Settings ==> System ==> Optional features.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18a5a4e5-2604-23c2-1374-68a6974170bc
* Version Independent ID: f93809cc-eb5e-6b9b-ed58-c8811a8ee21f
* Content: [Get started with OpenSSH for Windows](https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse?tabs=gui)
* Content Source: [WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/OpenSSH/OpenSSH_Install_FirstUse.md)
* Product: **windows-server**
* Technology: **administration**
* GitHub Login: @robinharwood
* Microsoft Alias: **roharwoo**

**Comment by christking246** [comment]
#assign:christking246

**Comment by christking246** [comment]
Thanks again for contacting Microsoft, we value your feedback.
 
A documentation change has been made updating the instructions for installing and uninstalling OpenSSH on your Windows devices and will be live after the next business day. We will now be closing this thread.
 
Thank you and have a most pleasant day.
