### ISSUE TITLE
Wrong way to write <AlwaysOn>True</AlwaysOn>

### ISSUE THREAD

**Issue by JoergWu** [MicrosoftDocs/windowsserverdocs#766]
[Enter feedback here]
When using the PS1 script you will find this line here:
<AlwaysOn>True</AlwaysOn>
But this true written with capital T causes to fail the VPN connection import with wrong values
The result is an Automatic VPN type instead of IKEv2 VPN type!
And this finally results VPN not using computer certificates
This also applies to the XML file created!
So in both you need it written this way:
<AlwaysOn>true</AlwaysOn>
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7453068-95eb-2a42-fd0b-553ae593adb0
* Version Independent ID: b39b2cb7-25b1-2af3-4954-dbcc04c836e9
* Content: [Configure Windows 10 Client Always On VPN Connections](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md)
* Service: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
I talked to the Always On VPN engineer, and he stated that the syntax is lower case 't'.  I will verify with him the correct syntax.

**Comment by shortpatti** [comment]
True but be all lower case: 'true.'
