### ISSUE TITLE
Typo in "Available job-wide settings" section

### ISSUE THREAD

**Issue by DDIT87** [MicrosoftDocs/windowsserverdocs#7666]
When attempting to create a new dedup schedule, I used the command lifted directly from [here](https://learn.microsoft.com/en-us/windows-server/storage/data-deduplication/advanced-settings#modifying-job-schedules:~:text=Create%20a%20nightly%20Optimization%20job%20that%20runs%20at%207%3A00%20PM%20with%20high%20priority%20and%20all%20the%20CPUs%20and%20memory%20available%20on%20the%20system.).

`New-DedupSchedule -Name "NightlyOptimization" -Type Optimization -DurationHours 11 -Memory 100 -Cores 100 -Priority High -Days @(1,2,3,4,5) -Start (Get-Date "2016-08-08 19:00:00")`

This was rejected on Server 2022, with error

`New-DedupSchedule : Cannot process argument transformation on parameter 'Priority'. Cannot convert value "Medium" to
type "Microsoft.PowerShell.Cmdletization.GeneratedTypes.DedupSchedule.Priority". Error: "Unable to match the
identifier name Medium to a valid enumerator name. Specify one of the following enumerator names and try again:
Low, Normal, High"`

So, the correct syntax for 'Priority' is Low, **Normal**, High. Whereas in this document, it shows Low, **Medium**, High. Please correct the typo.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: afbeabe4-15fa-65dd-9fe2-126ceadc96a1
* Version Independent ID: 7a8534d6-56b3-ae36-463c-158ebb5e86bc
* Content: [Advanced Data Deduplication settings](https://learn.microsoft.com/en-us/windows-server/storage/data-deduplication/advanced-settings#modifying-job-schedules)
* Content Source: [WindowsServerDocs/storage/data-deduplication/advanced-settings.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/storage/data-deduplication/advanced-settings.md)
* Product: **windows-server**
* Technology: **storage**
* GitHub Login: @wmgries
* Microsoft Alias: **wgries**

**Comment by christking246** [comment]
#assign:christking246

**Comment by christking246** [comment]
Thanks again for contacting Microsoft, we value your feedback.

A documentation change has been made updating the priority listing for _Dedup_ and will be live after the next business day. We will now be closing this thread.

Thank you and have a most pleasant day.
