### ISSUE TITLE
Needs Powershell option

### ISSUE THREAD

**Issue by timmmayyy** [MicrosoftDocs/windowsserverdocs#7681]
Would be helpful to include a PowerShell example.

**Comment by christking246** [comment]
Thanks for contacting Microsoft, we value your feedback.

Could you please specify what document could potentially benefit from a PowerShell example?

**Comment by Xelu86** [comment]
#assign:christking246

**Comment by christking246** [comment]
User feedback is incomplete and as such we cannot move forward. Closing thread as it has been over a week since it has been open without additional information.
#please-close
