### ISSUE TITLE
high performance networking 

### ISSUE THREAD

**Issue by srey-mey** [MicrosoftDocs/windowsserverdocs#7682]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 801f55b2-1a96-6661-b07e-33fcd3b6d50d
* Version Independent ID: 7d7178c4-d679-eb13-39ea-82fd1fa8a2bd
* Content: [High-performance networking (HPN)](https://learn.microsoft.com/en-us/windows-server/networking/technologies/hpn/hpn-top)
* Content Source: [WindowsServerDocs/networking/technologies/hpn/hpn-top.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/networking/technologies/hpn/hpn-top.md)
* Product: **windows-server**
* Technology: **networking**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by christking246** [comment]
User feedback is incomplete and unspecified/unrelated to documentation. Closing thread.
#please-close

**Comment by christking246** [comment]
#assign:christking246
