### ISSUE TITLE
software developer

### ISSUE THREAD

**Issue by erickool** [MicrosoftDocs/windowsserverdocs#773]
There are 126 ADFS 4 counters (Get-Counter -ListSet "AD FS") but this page only lists 10. Where is the documentation for the other 116? For example, what is "U/P Authentications"? Also, what is the relationship between counters? Are there roll-up counters for more granular counters? What is the relationship between the counters and the ADFS events in the Security log (with Verbose logging)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6e5761a-4593-bc93-a28c-c059121f1acf
* Version Independent ID: 831fe81f-a5bf-48c0-ea6a-0b1a4a3e89a2
* Content: [Configure Performance Monitoring](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/configure-performance-monitoring)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Configure-Performance-Monitoring.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Configure-Performance-Monitoring.md)
* Service: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
Does this ticket provide enough information to help generate any constructive changes to the document?
