### ISSUE TITLE
Remove the references to Server 2016

### ISSUE THREAD

**Issue by eponerine** [MicrosoftDocs/windowsserverdocs#7731]
Probably shouldn't even be a year/build put here. Just leave it as "Hyper-V is the virtualization server role in Windows Server and Azure Stack HCI". 

![image](https://github.com/MicrosoftDocs/windowsserverdocs/assets/503974/9a66b363-0de0-4995-af73-aac70034cfb1)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a028c9f4-3c32-9459-2f5a-fdd535b28e5d
* Version Independent ID: 249e452f-a38c-a604-cc7d-1ae17a31d291
* Content: [Performance Tuning Hyper-V Servers](https://learn.microsoft.com/en-us/windows-server/administration/performance-tuning/role/hyper-v-server/)
* Content Source: [WindowsServerDocs/administration/performance-tuning/role/hyper-v-server/index.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/administration/performance-tuning/role/hyper-v-server/index.md)
* Service: **windows-server**
* Sub-service: **administration**
* GitHub Login: @phstee
* Microsoft Alias: **wscontent**

**Comment by Xelu86** [comment]
Hey @eponerine,

Thanks again for contacting Microsoft, we value your feedback. 

You're correct, good catch. We're updating this document with this change, and it will be live after the next business day. We will now be closing this thread. 

Thank you and have a most pleasant day. 
#please-close
