### ISSUE TITLE
finance

### ISSUE THREAD

**Issue by HasrawatiCS50X** [MicrosoftDocs/windowsserverdocs#7737]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: acc42a8f-2623-4352-7cc4-70f0f61e9d89
* Version Independent ID: 97d8b54b-5e7d-098b-4fb7-e8f6e0b30389
* Content: [Get started with the Remote Desktop app for Windows](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windows#add-a-workspace)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/windows.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/remote/remote-desktop-services/clients/windows.md)
* Service: **windows-server**
* Sub-service: **remote**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by Xelu86** [comment]
Closing as this is a non-documentation issue.
#please-close
