### ISSUE TITLE
Wrong information for forest functional level

### ISSUE THREAD

**Issue by Odd1t135** [MicrosoftDocs/windowsserverdocs#7739]
[Enter feedback here]
On https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/active-directory-functional-levels it says Server 2016 introduced PAM and MIM and links to https://learn.microsoft.com/en-us/windows-server/identity/whats-new-active-directory-domain-services#privileged-access-management which says PAM and MIM can be used with Server 2012 R2.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36f4538a-b7ae-fd8d-9337-23dffe93c8f8
* Version Independent ID: 0a0a4ea0-8afe-b021-ed19-26e8e720fe8a
* Content: [What's new in Active Directory Domain Services in Windows Server 2016](https://learn.microsoft.com/en-us/windows-server/identity/whats-new-active-directory-domain-services#privileged-access-management)
* Content Source: [WindowsServerDocs/identity/whats-new-active-directory-domain-services.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/whats-new-active-directory-domain-services.md)
* Service: **windows-server**
* Sub-service: **security**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
There are parts that were available in 2012R2 that were enhanced with 2016.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
