### ISSUE TITLE
Installation Type 

### ISSUE THREAD

**Issue by mcroob** [MicrosoftDocs/windowsserverdocs#774]
Should the "Installation" field be referring to "Desktop Experience" rather than "Datacenter Edition"? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bf0fae6-d821-8220-87c0-b1e71b48260f
* Version Independent ID: afa6c125-4c14-baf2-ae10-7096d65cda04
* Content: [Security guidelines for system services in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server#feedback)
* Content Source: [WindowsServerDocs/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server.md)
* Service: **windows-server-threshold**
* GitHub Login: @nirb
* Microsoft Alias: **nirb**

**Comment by lizap** [comment]
That's an excellent point - does the Server Core version of the Datacenter edition actually include these? We'll update after sorting the details. Thanks!

**Comment by Justinha** [comment]
@mcroob and @lizap great suggestion. I replaced Server Core with Desktop Experience.
