### ISSUE TITLE
Link to Dealing with Advanced Threats does not work

### ISSUE THREAD

**Issue by myfope** [MicrosoftDocs/windowsserverdocs#776]
The link to http://wincom.blob.core.windows.net/documents/Post_Breach_Dealing_with_Advanced_Threats_Whitepaper.pdf does no longer work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8f38aa8-326d-ac62-3c13-7f31ce6c0edf
* Version Independent ID: 94073c27-65a6-5c21-c8b2-41ca249cdc31
* Content: [Beginning your General Data Protection Regulation (GDPR) journey for Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/security/gdpr/gdpr-winserver-whitepaper)
* Content Source: [WindowsServerDocs/security/gdpr/gdpr-winserver-whitepaper.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/gdpr/gdpr-winserver-whitepaper.md)
* Service: **unspecified**
* GitHub Login: @eross-msft
* Microsoft Alias: **nirb**

**Comment by lizap** [comment]
Thanks for flagging this, we'll get it fixed.

@DaniHalfin - can you take a look?

**Comment by DaniHalfin** [comment]
Fixed. The change should be live sometime later today (soon™).
Thanks for pointing out the issue, @myfope !
