### ISSUE TITLE
"Windows LAPS supported platformss" chapter contains 2 "s" characters

### ISSUE THREAD

**Issue by guldenk** [MicrosoftDocs/windowsserverdocs#7832]
Please change to "Windows LAPS supported platforms"

https://learn.microsoft.com/en-us/windows-server/identity/laps/laps-overview#windows-laps-supported-platformss

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70be2bc5-d5c8-3802-5a11-76885966af5b
* Version Independent ID: 70be2bc5-d5c8-3802-5a11-76885966af5b
* Content: [Windows LAPS overview](https://learn.microsoft.com/en-us/windows-server/identity/laps/laps-overview)
* Content Source: [WindowsServerDocs/identity/laps/laps-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/laps/laps-overview.md)
* Service: **windows-server**
* Sub-service: **security**
* GitHub Login: @jay98014
* Microsoft Alias: **jsimmons**

**Comment by jay98014** [comment]
@guldenk - thanks for filing this feedback item.  I have fixed the issue in this [PR](https://github.com/MicrosoftDocs/windowsserverdocs/issues/7832).  The fix should go live around 10:30am PST tomorrow morning.

**Comment by jay98014** [comment]
#please-close
