### ISSUE TITLE
Refresh tokens no issued as result on refresh_token grant_type

### ISSUE THREAD

**Issue by dstefanMSFT** [MicrosoftDocs/windowsserverdocs#7835]
refresh token grant type section is wrong - using refresh_token grant returns only Access and ID tokens if requested

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5399f381-2744-9012-2575-b2d1dd110040
* Version Independent ID: c816cb8d-b7b5-6fe7-bcca-b5d0da9efefc
* Content: [AD FS OpenID Connect/OAuth flows and Application Scenarios](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-openid-connect-oauth-flows-scenarios)
* Content Source: [WindowsServerDocs/identity/ad-fs/overview/ad-fs-openid-connect-oauth-flows-scenarios.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/identity/ad-fs/overview/ad-fs-openid-connect-oauth-flows-scenarios.md)
* Service: **windows-server**
* Sub-service: **security**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by billmath** [comment]
Thank for submitting this. I have created a work item for it and will reviewing this in the coming weeks. I am not sure what the timeline will be, so I am going to close this for now. But once I have an update I will drop it in here and let you know.

Thank you!

Bill

#please-close
