### ISSUE TITLE
Remote Desktop credentials not authenticating

### ISSUE THREAD

**Issue by arthurzakaryan** [MicrosoftDocs/windowsserverdocs#788]
Hello, I am trying to connecting to a test Windows Server (2019 - Latest Build 17650) via Remote Desktop via Edge and Chrome and I am getting the same error in both. I understand there is currently an issue within Chrome that is documented as a known issue but the same isn't documented for Edge.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1c16ba9-2fc0-4c4e-8e98-71fa6149224c
* Version Independent ID: 95a061bd-a176-1ec3-259d-2a3925ca279e
* Content: [Windows Admin Center Known Issues](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/known-issues#feedback)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/use/known-issues.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/use/known-issues.md)
* Service: **windows-server-threshold**
* GitHub Login: @jwwool
* Microsoft Alias: **jeffrew**

**Comment by jwwool** [comment]
Hi @arthurzakaryan, are you using Windows Admin Center behind any type of proxy? This may be caused by [WebSocket compatibility when using a proxy service](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/known-issues#websockets). Will you also please check to see if the traditional remote desktop clients are able to connect to the machine?

**Comment by lizap** [comment]
Hi, @arthurzakaryan - were you able to check the things @jwwool suggested? Is this still a problem for you?

**Comment by lizap** [comment]
I think your best option might be to check out [Windows Admin Center in the Windows Server forum](https://social.technet.microsoft.com/Search/en-US/windowsserver?query=Windows%20Admin%20Center&refinement=9&beta=0&ac=5#refinementChanges=112&pageNumber=1&showMore=false). You can look at existing posts to see if others have run into the same problem, or start a new thread to ask for specific help with your issue. Thanks!
