### ISSUE TITLE
Hyphens in the body of the article

### ISSUE THREAD

**Issue by sttelv** [MicrosoftDocs/windowsserverdocs#791]
Hi, I've noticed this on many of the child articles for Best Practices for Securing Active Directory:

you'll often see two words smushed together where, I presume, a hyphen should be present. Example here:

When a member server or a workstation is compromised and altered by an attacker, the computer is no longer trustworthy, but neighboring uncompromised servers and workstations arecompromise of one computer does not imply that all computers are compromised.

"workstations arecompromise of one" is likely meant to be "workstations are - compromise of one"

I unfortunately don't have examples for all the other articles (I went through them in order and noticed this in many of them), and couldn't find the dash even in the raw text at https://raw.githubusercontent.com/MicrosoftDocs/windowsserverdocs/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Planning-for-Compromise.md, so I'm not sure how you could check, unless you have access to the actual source files (presumably Word documents).

Hth,
Stefan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ba343b4-6195-ca47-1724-f642dcabe65a
* Version Independent ID: d3ef4dd0-3849-28eb-cae8-f277c689de55
* Content: [Planning for Compromise](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/planning-for-compromise)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Planning-for-Compromise.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Planning-for-Compromise.md)
* Service: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by doctordns** [comment]
Resolved (I think) in PR #791

**Comment by lizap** [comment]
Yep! You fixed it - thanks for that!
