### ISSUE TITLE
CRL check requirements - error in the text?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/windowsserverdocs#794]
Is it an error to say that port 80 between ADFS/WAP and AAD Connect will be used for CRL checking?  My understanding is that what should be said here is that all three - ADFS, WAP, and AAD Connect - require outbound TCP 80 to the internet so they can each do CRL checking.

The screenshot also shows that AAD Connect will use port 80 and port 443 for synchronizing to Azure AD, but makes no mention of CRL checking between ADFS/WAP and AAD Connect.  This also supports my suspicion that the information in the table is in error around port 80's requirements for CRL checking.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a834de4-c696-4599-6ab2-94ae03d31471
* Version Independent ID: 78658bfd-8bcc-0d71-5139-77733f1a795e
* Content: [Best Practices for securing AD FS and Web Application Proxy](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/best-practices-securing-ad-fs#standard-deployment-topology)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Best-Practices-Securing-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Best-Practices-Securing-AD-FS.md)
* Service: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by jordanmills** [comment]
It probably assumes that your AIA and CDP will be exposed through the WAPs.  I suppose that's for the case where the remote federated party checks revocation, but not trusted roots... but practically nobody performs validity checks on the token signing certificates.
