### ISSUE TITLE
Reference to this page

### ISSUE THREAD

**Issue by mfstanton** [MicrosoftDocs/windowsserverdocs#797]
I was on another page talking about resolving boot issues and there was a link get to a "recommended page" which brought me to this one and not to a page with content similar to what I was viewing so now I have to do my search all over again.  When You take a user to a page for a "recommended version" of a document, you should at least populate the search window with the keywords from the prior reference to minimize rework on the part of the user since they probably came in from a page with an arcane set of keywords.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0230423b-be6b-c5b3-7c69-d99b0a0f79aa
* Version Independent ID: 825d1114-1fa8-5e9b-a0d1-478ac15d7626
* Content: [Windows Server](https://docs.microsoft.com/en-us/windows-server/windows-server)
* Content Source: [WindowsServerDocs/Windows-Server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/Windows-Server.md)
* Service: **windows-server-threshold**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by lizap** [comment]
Hi, I'm sorry we got you lost. We'll look into pages that are pointing here, or that end up here through redirection bounces. Thanks for sharing your experience.

**Comment by mfstanton** [comment]
Thank you, ma'am
