### ISSUE TITLE
Command to set static IP address is incorrect

### ISSUE THREAD

**Issue by p1johnson** [MicrosoftDocs/windowsserverdocs#798]
The command shown to set a static IP address:

New-NetIPaddress -InterfaceIndex 12 -IPAddress -192.0.2.2 -PrefixLength 24 -DefaultGateway -192.0.2.1

Incorrectly includes - before the IP address and Default Gateway

Should read:

New-NetIPaddress -InterfaceIndex 12 -IPAddress 192.0.2.2 -PrefixLength 24 -DefaultGateway 192.0.2.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a821622a-23dd-f730-6063-e9e7445876ff
* Version Independent ID: 1b8404ba-31fd-ee15-e10b-b255fc0c53fd
* Content: [Administer Server Core](https://docs.microsoft.com/en-us/windows-server/administration/server-core/server-core-administer)
* Content Source: [WindowsServerDocs/administration/server-core/server-core-administer.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/server-core/server-core-administer.md)
* Service: **windows-server-threshold**
* GitHub Login: @lizap

**Comment by lizap** [comment]
Thanks! We'll get that fixed.
