### ISSUE TITLE
Documentation uses SHA-1 (deprecated)

### ISSUE THREAD

**Issue by visualblind** [MicrosoftDocs/windowsserverdocs#800]
Change your documentation at step 14 to state SHA-2 instead of SHA-1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e75c5bf-aefe-154e-de20-a01ab982adf6
* Version Independent ID: 92189653-36bb-7e01-aa84-20fbad5808c8
* Content: [Install the Certification Authority](https://docs.microsoft.com/en-us/windows-server/networking/core-network-guide/cncg/server-certs/install-the-certification-authority)
* Content Source: [WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Install-the-Certification-Authority.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/core-network-guide/cncg/server-certs/Install-the-Certification-Authority.md)
* Service: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
Hi @visualblind, thanks for catching.  I've updated the document with SHA2.
