### ISSUE TITLE
Nice Documentation 

### ISSUE THREAD

**Issue by actionaer** [MicrosoftDocs/windowsserverdocs#801]
lets ride =)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588d12d1-fdd1-892a-eb5e-9e2d86302368
* Version Independent ID: 5eceac91-1d90-a663-2856-19e13da59351
* Content: [Remote Desktop clients](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-clients)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-clients.md)
* Service: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by lizap** [comment]
Thanks! Let us know if you run into issues.
