### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mpking828** [MicrosoftDocs/windowsserverdocs#805]
Under Target Accuracy: 1 Millisecond: you have the number 1 instead of a quotation mark.  The open quotation mark looks funny as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75bcebc6-6996-2df3-fbbc-148a7943353c
* Version Independent ID: e8374ced-eff5-4fde-2d8b-9229a461bca8
* Content: [Support boundary to configure the Windows Time service for high-accuracy environments](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/support-boundary)
* Content Source: [WindowsServerDocs/networking/windows-time-service/support-boundary.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/networking/windows-time-service/support-boundary.md)
* Service: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **dacuo**

**Comment by shortpatti** [comment]
Thanks for the catch.  I have fixed the error.

**Comment by mpking828** [comment]
When will the change go live?

**Comment by shortpatti** [comment]
It will be pushed mid-morning tomorrow.
