### ISSUE TITLE
Modern Auth for RDWeb Login when Using Webclient

### ISSUE THREAD

**Issue by alanmreagan** [MicrosoftDocs/windowsserverdocs#809]
Will the RDWeb logon page in the future accept modern auth, so that Azure can be used to for MFA/Conditional Access though a gallery app since the web client doesn't support Azure Application Proxy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Service: **windows-server-threshold**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by davidbel** [comment]
Hi Alan, thank you for using the web client.

There is no plan to add modern auth to RDWeb at this point. However, Azure Application Proxy does provide this functionality and is the recommended way to enable the benefits of AAD with RDWeb.

Supporting Azure Application Proxy with the Remote Desktop web client is one of our top priority and we are working closely with the AAD-AP team to enable this as soon as possible.

**Comment by ferronsw** [comment]
Any update on the progress of supporting the AAD Proxy?

**Comment by davidbel** [comment]
@ferronsw Not yet. We know this is resonating strongly with our customers and how important it is. Definitely something we're looking into now that we've reached general availability.

**Comment by craigofnz** [comment]
There is a certain sense of irony, of implementing a different cloud service so that we could pre-authenticate with Azure Active Directory MFA with websockets support. Really love your work, and looking forward to testing AAD Proxy, optimistically with KCD for a full SSO experience between O365 with some hybrid access back to heritage apps through the rdwebclient.

**Comment by robskij** [comment]
Getting the RDS webclient working on Azure App Proxy will make it an awesome service. Slightly puzzled that you let it go GA without having first got this working, especially after citing it as a top priority earlier in the year seems a bit strange. Top priority usually means its a must to deliver !

We find that RDweb / RDS Gateway via Azure App Proxy configured as per the guidelines is a bit flaky, missing icons, random disconnects.

There a number of other web services presented from our organisation via azure app proxy and they all seem to be 100% stable
