### ISSUE TITLE
Link to Best Practices Analyzer is outdated?

### ISSUE THREAD

**Issue by olavt** [MicrosoftDocs/windowsserverdocs#810]
The link to the Best Practices Analyzer links to a page, which is applicable to Windows Server 2008 R2. Is this really the latest?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e8b8354-682b-74f8-324b-205b1ed3629b
* Version Independent ID: c3473722-b5a4-7e20-7c5f-a401b42b2344
* Content: [Best Practices Analyzer for Hyper-V](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/best-practices-analyzer/best-practices-analyzer-for-hyper-v)
* Content Source: [WindowsServerDocs/virtualization/hyper-v/best-practices-analyzer/Best-Practices-Analyzer-for-Hyper-V.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/virtualization/hyper-v/best-practices-analyzer/Best-Practices-Analyzer-for-Hyper-V.md)
* Service: **na**
* GitHub Login: @KBDAzure
* Microsoft Alias: **kathydav**

**Comment by illfated** [comment]
I know this is a very late reply, but there is a 2012 R2 version of the page.

I will make an effort to find the related links and create a pull request to have the links updated.

The best case scenario will be that I can manage to get more than 1 link changed to use the newer version, maybe even get a link to the 2016 PowerShell cmdlet page into the mix.

**Comment by illfated** [comment]
I have been searching through the pages underneath https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/hyper-v-on-windows-server , but could not find any TOC links to pages related to "Best Practices Analyzer for Hyper-V" for modern server versions:

**Hyper-V on Windows Server** (Get started, Plan, Deploy, Manage) :
- https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/get-started/get-started-with-hyper-v-on-windows
- https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/plan/plan-hyper-v-on-windows-server
- https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/deploy/deploy-hyper-v-on-windows-server
- https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/manage/manage-hyper-v-on-windows-server

I suspect that what we are looking for is mainly documented in the PowerShell repository for modern servers.

For now, I can only locate the specific page for "Applies To: Windows Server **2012 R2**, Windows Server **2012**" as an improvement to the 2008 R2 version:
- https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn283329(v=ws.11)

**Comment by illfated** [comment]
PowerShell `BestPractices` Module:
- https://docs.microsoft.com/en-us/powershell/module/bestpractices/?view=win10-ps

**Comment by illfated** [comment]
There you go. PR #4896 is ready for review. I have postponed other link changes as a solution to other potential ticket reports for outdated links.
