### ISSUE TITLE
Windows Update

### ISSUE THREAD

**Issue by micro-help** [MicrosoftDocs/windowsserverdocs#815]
When scheduling a restart after updates, does it go based on the remote server's time or the WAC host's time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99fcece9-57ba-c2cb-a4a4-4d9188490bd5
* Version Independent ID: 63fd5c3b-76c7-a45f-1700-6fdb81706aee
* Content: [Manage Servers with Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/manage-servers#updates)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/use/manage-servers.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/use/manage-servers.md)
* Service: **windows-server-threshold**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by jwwool** [comment]
It is based on the target server that you are managing, not the Windows Admin Center gateway.
