### ISSUE TITLE
Firefox 60.0 on Linux Mint - Secure Connection Failed - after imported the cerfificate

### ISSUE THREAD

**Issue by amsteel** [MicrosoftDocs/windowsserverdocs#816]
Still got the following error when using Firefox 60.0 (Seems chromium works ok):
Secure Connection Failed

The connection to the server was reset while the page was loading.

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
