### ISSUE TITLE
Missing options

### ISSUE THREAD

**Issue by seeingeyegod** [MicrosoftDocs/windowsserverdocs#819]
This doesn't show the wbadmin delete backup options ie (wbadmin delete backup -deletOldest)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aab8cc6-db1c-803d-b8ed-bee01000a0b1
* Version Independent ID: 2ccc2b34-cbfb-616c-930f-91d2bb8f6526
* Content: [wbadmin](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/wbadmin)
* Content Source: [WindowsServerDocs/administration/windows-commands/wbadmin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/wbadmin.md)
* Service: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
You need to go into the page **wbadmin delete systemstatebackup** to see those options.

- https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/wbadmin-delete-systemstatebackup

**Comment by illfated** [comment]
Not a real issue, only a question of using the links, either in the document text or in the Table Of Contents to the left of the page.

#please-close
