### ISSUE TITLE
Printer configuration options

### ISSUE THREAD

**Issue by LarsErikK** [MicrosoftDocs/windowsserverdocs#825]
As far as I can tell, there's no way to configure what options are available for the client. For instance, the only supported paper sizes are Letter and A4 on the client, even though the printer properties on the server have A3 available. Is this solution Letter and A4 only as of now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c4e7221-25fc-1aff-75e4-47ce9ac6c285
* Version Independent ID: 36236322-05f4-8cf8-dfa2-a4943dc5bb58
* Content: [Windows Server Hybrid Cloud Print overview](https://docs.microsoft.com/en-us/windows-server/administration/hybrid-cloud-print/hybrid-cloud-print-overview)
* Content Source: [WindowsServerDocs/administration/hybrid-cloud-print/hybrid-cloud-print-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/hybrid-cloud-print/hybrid-cloud-print-overview.md)
* Service: **w10**
* GitHub Login: @TrudyHa
* Microsoft Alias: **TrudyHa**

**Comment by nilssedlacek** [comment]
Hi LarsErikK,

we are facing the same issue. It seems to be related to the default driver which is distributed to the Client "MicrosoftEnterpriseCloudPrintClassDriver". We also are searching for a solution to provide the printing properties e.g. the right driver for the right printer instead of the "CloudPrint***-Driver".

Did you already get a response from Microsoft?

**Comment by LarsErikK** [comment]
No, not yet. I've got a case open with Microsoft Premier support to get a straight answer to a really simple question; "can you add additional paper sizes so they're available for the client?". But so far they don't seem to know or understand the difference between Hybrid Cloud Print and the regular windows print solutions with a directly connected print server. I'll update you when and if I get an answer.

**Comment by aidancopps** [comment]
Just implemented this as part of a move to Intune and came across this limitation. Seems strange that basic options like paper size and colour/greyscale selection wouldn't be supported from the start.

**Comment by nilssedlacek** [comment]
Hi @ all, we also had contact to Microsoft. We got the information that the cloud print support for printers will be extended with windows server 2019.

Regards,
Nils

**Comment by adrianwells** [comment]
Hello @ all - now that Windows Server 2019 is GA, where might one read about the updates around the cloud print support?

**Comment by coreyp-at-msft** [comment]
Hi @adrianwells ,  for WS2019, Hybrid Cloud Print now offers support for printer preferences. Documentation is not available yet. The team is working on prioritizing it.

Thanks,
Corey

**Comment by adrianwells** [comment]
@coreyp-at-msft, OK.  That is good to know.  Look forward to seeing it soon.
