### ISSUE TITLE
Is it correct to pass id_token to WebAPI?

### ISSUE THREAD

**Issue by dmytrol** [MicrosoftDocs/windowsserverdocs#828]
As far as I understand OpenID Connect, id_token is aimed exclusively at the client (in this case, the single page app), while access_token is used for accessing the protected resource (that is, the Web API). However the diagram in the beginning of the article suggests that the id_token should be used to authorize at the Web API which is possibly against the OIDC standard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 731a5db9-3e53-0379-edcb-4c338dad0240
* Version Independent ID: 683ef16d-2cbd-7d01-a7da-842f4afb1d8f
* Content: [Build a single page web application using OAuth and ADAL.JS with AD FS 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/single-page-application-with-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/Single-Page-Application-with-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/Single-Page-Application-with-AD-FS.md)
* Service: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by davewoodward** [comment]
Would appreciate an answer here.

**Comment by lizap** [comment]
Hi, Dymtro (and hi again, Dave!) - the team's updated the introduction to the graphic to be more clear about what's happening. If you still have questions, please reopen this issue and we'll keep working on it.

**Comment by amouly** [comment]
This still doesn't makes sense. The graphic still uses the ID Token to access the API layer.
