### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by TXbluzmn** [MicrosoftDocs/windowsserverdocs#829]
this link:  "Failover Clustering Hardware Requirements and Storage Options." at the top of this page is broken and returns a 404 error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa6a457c-f213-1d54-9dcb-d42d9ff84bd1
* Version Independent ID: 352fb2e9-2523-4d42-5c80-3199bf4e06ad
* Content: [Create a failover cluster](https://docs.microsoft.com/en-us/windows-server/failover-clustering/create-failover-cluster)
* Content Source: [WindowsServerDocs/failover-clustering/create-failover-cluster.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/failover-clustering/create-failover-cluster.md)
* Service: **windows-server-threshold**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by lizap** [comment]
Thanks for pointing this out - the correct link is https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn265970(v=ws.11). We've updated the article, so you should see a fixed link soon.

**Comment by linal** [comment]
The link goes to the wrong page. Should it go to 

https://docs.microsoft.com/en-gb/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/jj612869(v%3dws.11)

**Comment by JasonGerend** [comment]
Thanks for double-checking, but the following reference:
"For more information about validating a failover cluster, see Validate Hardware for a Failover Cluster."

looks to me like it's properly pointing to the following topic:
Validate Hardware for a Failover Cluster at: https://docs.microsoft.com/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/jj134244%28v%3dws.11%29

Are you seeing something different? Thanks for caring about the content and letting us know when you find something amiss!

**Comment by linal** [comment]
On the line 

"Review the hardware requirements to make sure that your configuration is supported. For more information, see Failover Clustering Hardware Requirements and Storage Options."

Takes me to a page titled "Deploy an Active Directory-Detached Cluster".

(Might have added comment against the wrong thing and should have just opened a new issue.)

Thanks

**Comment by JasonGerend** [comment]
Aha - sorry I missed that! I see it now and will fix it - great catch, and thanks for letting us know! :)
