### ISSUE TITLE
Article on Server cites Windows 10 KBs?

### ISSUE THREAD

**Issue by doctordns** [MicrosoftDocs/windowsserverdocs#834]
Looking at the section titled: Solutions for installing or upgrading Windows Server in : 
windowsserverdocs/WindowsServerDocs/troubleshoot/windows-server-support-solutions.md

The first three articles cited in this section are about Windows 10, not Windows Server. That could be confusing. It's not clear why the top three references in the Section 'Top support solutions for Windows Server 2016' refers to Windows 10 content. There may be a good reason but the page doesn't say so.

Two alternative solutions:
1. Remove those first three article references and keep the rest.

2. Put those three at the bottom along with some text explaining that there is additional guidance in those articles that _could_ help to resolve installation issues with Windows Server e.g. _Since much of the underlying components are identical between Windows 10 and Windows Server 2016 these articles have additional information that may assist you in resolving installation or upgrade issues with Windows Server 2016_. Or something like that.

**Comment by illfated** [comment]
The referenced page has been renamed to windows-server-support-solutions-old.md (**Top support solutions for Windows Server 2016**):
- https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/troubleshoot/windows-server-support-solutions-old.md
- https://docs.microsoft.com/en-us/windows-server/troubleshoot/windows-server-support-solutions-old (not linked in the TOC)

The current page is named **Troubleshooting Windows Server components** (windows-server-troubleshooting.md)
- https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/troubleshoot/windows-server-troubleshooting.md
- https://docs.microsoft.com/en-us/windows-server/troubleshoot/windows-server-troubleshooting

**Comment by illfated** [comment]
#please-close

**Comment by illfated** [comment]
#please-close
