### ISSUE TITLE
Example of using attribute store

### ISSUE THREAD

**Issue by TRegan3** [MicrosoftDocs/windowsserverdocs#842]
This page would be much more helpful if it included an example of using a SQL Server attribute store.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54d73e9d-e08d-9184-e357-65b9f5a19bc1
* Version Independent ID: 8c60d2ba-8fe4-cabf-0dda-72dbf58f1b73
* Content: [Add an Attribute Store](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/add-an-attribute-store)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Add-an-Attribute-Store.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Add-an-Attribute-Store.md)
* Service: **unspecified**
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by TheOtherBillGates** [comment]
Exactly, this article is close to 0 regarding usefulness, nothing in this page helps in any way to add an Attribute Store in AD FS !

**Comment by anwarmahmood1** [comment]
There's an example at
Active Directory Federation Services – SQL Attribute Store | Journey Of The Geek
https://journeyofthegeek.com/2017/05/28/active-directory-federation-services-sql-attribute-store/

**Comment by anwarmahmood1** [comment]
the documentation keeps saying "SQL", without providing any more information.

From what I can tell, it means "OLE DB provider".  Adding this one piece of information would be MASSIVELY helpful!


Also suggest adding an optional (but HIGHLY RECOMMENDED step) test connectivity using the steps at
https://blogs.technet.microsoft.com/michaelgriswold/2014/01/06/the-easy-way-to-test-sql-connectivity/

**Comment by anwarmahmood1** [comment]
not "OLE DB provider", but "OLE DB connection using any OLE DB provider"

**Comment by anwarmahmood1** [comment]
ignore my comments about OLE DB provider.  Add a link to...

Attribute stores that are supported by AD FS
https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/technical-reference/the-role-of-attribute-stores#attribute-stores-that-are-supported-by-ad-fs

https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/technical-reference/the-role-of-attribute-stores

**Comment by anwarmahmood1** [comment]
Why was this closed? My last suggestion would have improved this article. 

Change...

Data from the attribute stores is then projected as claims.

You can use the following procedure to add an attribute store to the Federation Service.

To...
Data from the attribute stores is then projected as claims.

Attribute stores that are supported by AD FS
https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/technical-reference/the-role-of-attribute-stores#attribute-stores-that-are-supported-by-ad-fs

You can use the following procedure to add an attribute store to the Federation Service.
