### ISSUE TITLE
Egregious Error /sL

### ISSUE THREAD

**Issue by ArtlessAptyrex** [MicrosoftDocs/windowsserverdocs#847]
The document says this: "/sl 	Copies the symbolic link instead of the target."
It should say: "/sl 	Follows the symbolic link and copies the target."

Amazingly the programmers actually got the default behaviour right. The "find(1) command on UNIX actually has a "-follow" directive to force it to do the counter-intuitive thing of following symlinks when creating a backup. Pity they can't get the documentation right.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af94ad3b-6603-2b26-1010-073fb2c07c2a
* Version Independent ID: 09fd75d0-8624-5cfd-5122-b40ba50055f9
* Content: [robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Service: **unspecified**
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by lizap** [comment]
Thanks for pointing out this error. We'll get the description updated to match reality.

Should you have a few minutes and feel like fixing one of these issues, you can follow the instructions [here](https://docs.microsoft.com/en-us/windows/whats-new/contribute-to-a-topic).

Again, thanks for raising this issue.

**Comment by lizap** [comment]
Article has been updated per this issue. Thanks!
