### ISSUE TITLE
There is no AD FS Management Console

### ISSUE THREAD

**Issue by DanJ210** [MicrosoftDocs/windowsserverdocs#849]
I can't access how to add applications to our AD FS like shown above. Elsewhere states that AD FS Management Console is no longer included with the remote management software. Perhaps update docs to explain this? Provide an alternate solution? Can't use these docs if can't get past the first step.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 731a5db9-3e53-0379-edcb-4c338dad0240
* Version Independent ID: 683ef16d-2cbd-7d01-a7da-842f4afb1d8f
* Content: [Build a single page web application using OAuth and ADAL.JS with AD FS 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/single-page-application-with-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/Single-Page-Application-with-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/Single-Page-Application-with-AD-FS.md)
* Service: **unspecified**
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
@DanJ210 : Could you please check again to see if the page has been updated during the last 2 years to see if there is more useful information added to the document?

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
