### ISSUE TITLE
A concrete example of a custom claim rule would help here.

### ISSUE THREAD

**Issue by TRegan3** [MicrosoftDocs/windowsserverdocs#850]
Providing a concrete example of a custom claim rule would help here.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 229fc828-d0f7-13d3-94a5-b2de9e6d0fd2
* Version Independent ID: cd6e9117-874a-9b52-4b84-1412fb14f8dd
* Content: [Create a Rule to Send Claims Using a Custom Rule](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/create-a-rule-to-send-claims-using-a-custom-rule)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Create-a-Rule-to-Send-Claims-Using-a-Custom-Rule.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Create-a-Rule-to-Send-Claims-Using-a-Custom-Rule.md)
* Service: **unspecified**
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by styfle** [comment]
Agreed, some examples of `if this, then that` with the proper syntax or at least link to the syntax page if it exists.

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft 
gh issue comment 849 -b #assign:IngridAtMicrosoft

**Comment by IngridAtMicrosoft** [comment]
#assign:IngridAtMicrosoft
