### ISSUE TITLE
Update Example steps

### ISSUE THREAD

**Issue by andypituch** [MicrosoftDocs/windowsserverdocs#853]
It may be worth mentioning that before you can perform step 10, you'll need to remove the 2012 R2 (AD FS 3.0) nodes first.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebfd725f-1b77-751c-1948-f8f88d26a9bc
* Version Independent ID: 7d9c78d9-7736-8f0a-9636-269125a10d6f
* Content: [Upgrading to AD FS in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server.md)
* Service: **unspecified**
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
@andypituch : Could you please check if the document has been improved, with regards to your suggestion, since you first posted this?

**Comment by illfated** [comment]
Closing this issue based on the main PR comment in the linked PR #1384 . Thank you all for contributing. 👍🏻

#please-close
