### ISSUE TITLE
Listing installed Roles and Features

### ISSUE THREAD

**Issue by mfstanton** [MicrosoftDocs/windowsserverdocs#854]
I remember finding by accident a way to list what roles and features were installed so they could be installed on another system. It isn't easy to find with such an unforgiving search engine

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16734c29-49a3-0c7c-0665-c9c9cbed2c7c
* Version Independent ID: ea95e7da-004f-fdce-6e54-a85996c4f31b
* Content: [Install or Uninstall Roles, Role Services, or Features](https://docs.microsoft.com/en-us/windows-server/administration/server-manager/install-or-uninstall-roles-role-services-or-features)
* Content Source: [WindowsServerDocs/administration/server-manager/install-or-uninstall-roles-role-services-or-features.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/server-manager/install-or-uninstall-roles-role-services-or-features.md)
* Service: **unspecified**
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
@mfstanton : Could you please confirm whether you intended to suggest any improvements or changes to the page you commented on?

**Comment by mfstanton** [comment]
I don’t remember what my original comments were. I commented on so many and usually include starting points for improvements. My apologies for the oversight, quite rude

**Comment by illfated** [comment]
@mfstanton : Fair enough, such things tend to happen, more frequent than we think. Thank you for replying.

Would it be OK to close this ticket and wait for a new ticket containing suggestions for improvements?
