### ISSUE TITLE
Application tooltip, wrong encoding in html5 RD client

### ISSUE THREAD

**Issue by gabaruga** [MicrosoftDocs/windowsserverdocs#863]
Tooltip on the application taskbar is not encoded correctly while using localized apps (russian in this case).
The issue is browser-independed, tested Chrome and Edge.
The issue is present in rd-html5 builds 0.8.0 and 0.8.1, deployed on the Windows Server 2016.
![image](https://user-images.githubusercontent.com/3691334/40409868-d53f1906-5e74-11e8-8ad8-adab63b94fe1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38213294-2784-2341-ac3e-77d2b017e2a2
* Version Independent ID: 8d30b4c5-68df-5fa2-d7e9-ede9b406527f
* Content: [Set up the Remote Desktop web client for your users](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/remote-desktop-web-client-admin)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/clients/remote-desktop-web-client-admin.md)
* Service: **unspecified**
* Product: **windows-server-threshold**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by lizap** [comment]
Thanks for taking the time to identify this issue! We want to make sure it gets directly into the hands of the product team - we've got a dedicated channel for that very purpose :) You can let the RD team know about the problem in the [RD User Voice forum](https://remotedesktop.uservoice.com/forums/266795-remote-desktop-services-for-enterprises). We can submit this issue for you, but it might make more sense for you to do so - that way you'll get notifications about the issue and be able to monitor any discussion or progress. If we don't hear back from you in the next few days, we'll move this issue to that forum and add a link here. Thanks!

**Comment by davidbel** [comment]
Thank you @gabaruga. I have filed a bug to track this issue.

**Comment by gabaruga** [comment]
The issue is still present in 1.0.0, any updates?

**Comment by davidbel** [comment]
@gabaruga The fix for this issue should be included in version 1.0.1 which we hope to release in the next couple of weeks. (Bug # 18043307) Keep an eye out on https://aka.ms/rdwebupdates for the release.

**Comment by davidbel** [comment]
Appreciate the confirmation @gabaruga
