### ISSUE TITLE
Questions about Powershell in WAC

### ISSUE THREAD

**Issue by sergiomartinezconde** [MicrosoftDocs/windowsserverdocs#866]
Hi all

After connect to a server trough WAC, Is normal that powershell request user credentials again?

After run first powershell command, is normal that the system displays this message?

Error reading or writing history file '\Microsoft\Windows\PowerShell\PSReadline\ConsoleHost_history.txt': Access to the path 'C:\Microsoft\Windows\PowerShell\PSReadline\ConsoleHost_history.txt' is denied.
This error will not be reported again in this session. Consider using a different path with:
    Set-PSReadlineOption -HistorySavePath <Path>
Or not saving history with:
    Set-PSReadlineOption -HistorySaveStyle SaveNothing

**Comment by sergiomartinezconde** [comment]
No answers
:(

**Comment by jwwool** [comment]
Yes, when Windows Admin Center is deployed as a gateway, you must reenter your credentials for the PowerShell and RDP tools.

The PSReadline error is not expected.

**Comment by sergiomartinezconde** [comment]
How we can avoid that this occur, configuring gateway in a different server?

**Comment by jwwool** [comment]
I cannot reproduce it, so I'm unable to determine the root cause and advise a mitigation. 
It appears to be a permissions/access control issue.
