### ISSUE TITLE
Case for 'true' is important!

### ISSUE THREAD

**Issue by AndyChips** [MicrosoftDocs/windowsserverdocs#867]
I concur with others that it is important to get the case correct when using the XML value 'true'.
For example, in the following tags:

<RememberCredentials>true</RememberCredentials>
<AlwaysOn>true</AlwaysOn>

Any other combination of upper or lower case results in a partial configuration of the VPN profile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7453068-95eb-2a42-fd0b-553ae593adb0
* Version Independent ID: b39b2cb7-25b1-2af3-4954-dbcc04c836e9
* Content: [Configure Windows 10 Client Always On VPN Connections](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections.md)
* Service: **unspecified**
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
Thank you for your feedback, I will add an Important note.

**Comment by AndyChips** [comment]
Your system has removed the two XML tags in my original post.
For completeness, the two examples were:

<RememberCredentials>true</RememberCredentials>
<AlwaysOn>true</AlwaysOn>

(I hope they don't get stripped again)

**Comment by AndyChips** [comment]
Yep, they did.
Let's try again without the chevrons:
(RememberCredentials)true(/RememberCredentials)
(AlwaysOn)true(/AlwaysOn)

**Comment by shortpatti** [comment]
Okay, that actually makes more sense :)  Thank you.  I'll make sure to include the two tags.
