### ISSUE TITLE
Need clarification about proxy endpoints!

### ISSUE THREAD

**Issue by grundencp** [MicrosoftDocs/windowsserverdocs#869]
When I disabled these endpoints, it also prevented authentications for remote PowerShell sessions and IMAP mailbox connectivity:
/adfs/services/trust/2005/usernamemixed Used for Exchange Online with Office clients older than Office 2013 May 2015 update. Later clients use the passive \adfs\ls endpoint. 
/adfs/services/trust/13/usernamemixed Used for Exchange Online with Office clients older than Office 2013 May 2015 update. Later clients use the passive \adfs\ls endpoint. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a834de4-c696-4599-6ab2-94ae03d31471
* Version Independent ID: 78658bfd-8bcc-0d71-5139-77733f1a795e
* Content: [Best Practices for securing AD FS and Web Application Proxy](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/best-practices-securing-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/Best-Practices-Securing-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/Best-Practices-Securing-AD-FS.md)
* Service: **unspecified**
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by dknappettmsft** [comment]
Hi @grundencp, when you say it prevented authentications IMAP mailbox connectivity, do you mean IMAP connectivity to a mailbox hosted in Exchange Online/Office 365 or on-premises Exchange Server?

Please could you also provide more information about the remote PowerShell sessions scenario?

**Comment by dknappettmsft** [comment]
#assign:dknappettmsft

**Comment by grundencp** [comment]
It prevented authentications for IMAP connectivity to a mailbox hosted in Exchange Online.

**Comment by dknappettmsft** [comment]
Thanks. And which version of Microsoft Office? I think in this case it's best if you log this with Microsoft Support as it's not something we're able to support here.  If the outcome with Support is that this document requires updating, they will notify us of the changes required to the article.

**Comment by dknappettmsft** [comment]
#please-close
