### ISSUE TITLE
Issues in step 6 (Install Web Application Proxy

### ISSUE THREAD

**Issue by v-mipra** [MicrosoftDocs/windowsserverdocs#871]
"On your Web Application Proxy open PowerShell and run the follow*o*ing cmdlt: Install-WebApplicationProxy -CertificateThumbprint {SSLCert} -fsname fsname -TrustCred $trustcred"

Should Be

"On your Web Application Proxy open PowerShell and run the following cmdlt: 
$trustcred = Get-Credential

     -Enter Domain Admin Credentials-
Install-WebApplicationProxy -CertificateThumbprint {SSLCert} -FederationServiceName fsname -FederationServiceTrustCredential $trustcred"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebfd725f-1b77-751c-1948-f8f88d26a9bc
* Version Independent ID: 7d9c78d9-7736-8f0a-9636-269125a10d6f
* Content: [Upgrading to AD FS in Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server)
* Content Source: [WindowsServerDocs/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/deployment/upgrading-to-ad-fs-in-windows-server.md)
* Service: **unspecified**
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by MoNadtheGrey** [comment]
Thanks, although, could someone please confirm, is this the thumbprint of "token decrypting" cert already installed on existing primary ADFS server?

**Comment by rotraves** [comment]
No @MoNadtheGrey. Actually is the Service Communication certificate thumbprint.

**Comment by illfated** [comment]
Closing this ticket based on the linked PR #1384 and further updates to the document after that. Thank you all for contributing! 👍🏻 

#please-close
