### ISSUE TITLE
Need better instructions on "including" powershell in nanoserver.

### ISSUE THREAD

**Issue by agr** [MicrosoftDocs/windowsserverdocs#875]
The linked pages does not make it any clearer on how to include powershell in 1803 nanoserver images.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9308a6f-52cd-8594-c1bd-48376bcc8a35
* Version Independent ID: 879f7f6b-d102-e547-7d57-0fddb2327192
* Content: [Changes to Nano Server in Windows Server Semi-Annual Channel](https://docs.microsoft.com/en-us/windows-server/get-started/nano-in-semi-annual-channel#feedback)
* Content Source: [WindowsServerDocs/get-started/nano-in-semi-annual-channel.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/nano-in-semi-annual-channel.md)
* Service: **unspecified**
* Product: **windows server**
* GitHub Login: @jaimeo

**Comment by lizap** [comment]
Thanks for raising this issue - we will look at updating this article for clarity. Because Nano server is only available as a container OS, check out the [container documentation](https://docs.microsoft.com/en-us/virtualization/windowscontainers/about/). You can also reach out to the container team through their GitHub issues: https://github.com/MicrosoftDocs/Virtualization-Documentation/issues

**Comment by kiazhi** [comment]
Will this [dockerfile](https://github.com/kiazhi/Windows-Containers/blob/master/dockerfiles/nanoserver/powershell/1709-6.0.2/Dockerfile) for 1709 be useful for you? @agr.

I havn't started on 1803 yet but will be doing one soon when I able to spin a Windows10 build 1803 with docker on it.

**Comment by agr** [comment]
@kiazhi, nanoserver 1803 has no powershell to begin wih, so, no.

**Comment by kiazhi** [comment]
@agr, 1709 has no powershell to begin with either. You will need to use multi-stages within the dockerfile to build the nano server container image.

You can try pulling those container images from my [nanoserver.powershell](https://hub.docker.com/r/kiazhi/nanoserver.powershell/) repo at DockerHub to check it.

```shell
C:\> docker pull kiazhi/nanoserver.powershell:1803-6.0.2
C:\> docker run --rm -it kiazhi/nanoserver.powershell:1803-6.0.2
```

```powershell
PS C:\> # Check OS Version
PS C:\> [Environment]::OSVersion.Version
PS C:\> $PSVersionTable
```

Have a look at the Dockerfile link below from my [Windows-Containers](https://github.com/kiazhi/Windows-Containers) GitHub repo and view the code. There is a `download` stage using the sac2016 nano server which still has Windows PowerShell to do `Invoke-WebRequest` and `Expand-Archive`. Followed by the `build` stage using the 1803 nano server image, and Dockerfile `COPY` to copy those files across from `download` stage to `build` stage. Finally, use `SETX` to set environment path for PowerShell.

> Freshly baked commits of 1803 with PowerShell Core. Hope it answers your question. :)

| Nano Server | PowerShell | Dockerfile | DockerHub Instructions |
| -- | -- | -- | -- |
| 1803 | 6.0.0 | [Dockerfile](https://github.com/kiazhi/Windows-Containers/tree/master/dockerfiles/nanoserver/powershell/1803-6.0.0/Dockerfile) | `docker pull kiazhi/nanoserver.powershell:1803-6.0.0` |
| 1803 | 6.0.1 | [Dockerfile](https://github.com/kiazhi/Windows-Containers/tree/master/dockerfiles/nanoserver/powershell/1803-6.0.1/Dockerfile) | `docker pull kiazhi/nanoserver.powershell:1803-6.0.1` |
| 1803 | 6.0.2 | [Dockerfile](https://github.com/kiazhi/Windows-Containers/tree/master/dockerfiles/nanoserver/powershell/1803-6.0.2/Dockerfile) | `docker pull kiazhi/nanoserver.powershell:1803-6.0.2` |
