### ISSUE TITLE
No option to initialize disks

### ISSUE THREAD

**Issue by xobs** [MicrosoftDocs/windowsserverdocs#879]
USB disks seem to behave differently.  They have no option to "Initialize Disk", and Disk Management seems completely incapable of doing anything with them for some reason.  This seems like a bug in Disk Management, because diskpart.exe is able to initialize and repartition this same disk.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aed88c8d-c15e-9dad-4cf4-9cc92e625f41
* Version Independent ID: 3ba55b69-bea2-a674-d08f-e93a03de1ffa
* Content: [Initialize new disks](https://docs.microsoft.com/en-us/windows-server/storage/disk-management/initialize-new-disks)
* Content Source: [WindowsServerDocs/storage/disk-management/initialize-new-disks.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/disk-management/initialize-new-disks.md)
* Service: **unspecified**
* Product: **windows-server-threshold**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by xobs** [comment]
In fact, it is possible to leave `Disk Management` open while using `diskpart.exe`, and `Disk Management` will dynamically update its views as partitions are created and deleted, all while being incapable of modifying partitions on its own.

This really does seem like a bug in `Disk Management` that the documentation does not note.

**Comment by lizap** [comment]
@JasonGerend - can you take a look?

**Comment by rwwllms** [comment]
How can I use diskpart.exe to initialize a disk that doesn't have a drive letter.

**Comment by JasonGerend** [comment]
I'm hunting for someone who can answer these questions...

**Comment by JasonGerend** [comment]
I spoke with our tech support, and they indicated that some USB drives don't have the option to be initialized, they just get formatted and a drive letter. Initializing a drive is just an interim step in the process of formatting a drive, so perhaps you don't need to initialize your drive, and can skip straight to formatting the drive or assigning a drive letter? I updated the topic to try to help a little, but I've been told that due to the huge variety of storage hardware Windows supports, we can't address all scenarios, and if this topic doesn't cover something you need, your best bet is probably to contact the device manufacturer or [Microsoft support](https://support.microsoft.com/contactus/). I hope this helps at least a little...

**Comment by xobs** [comment]
A common scenario is that a user has a USB drive with a small FAT32 partition and a large non-Windows filesystem such as ext2.  In such cases, it would be nice to re-initialize the disk.  The documentation seems to indicate that `Disk Management` can be used to initialize all disks, however Windows appears to explicitly disable this feature for USB drives.

As noted in the first comment, it is possible to use `diskpart.exe` to do this, so it does not appear to be an inherent Windows limitation.

The syntax is:

```
DISKPART> list disk
  Disk ###  Status         Size     Free     Dyn  Gpt
  --------  -------------  -------  -------  ---  ---
 [List of disks here -- look for the one that has the correct size -- I'll assume "disk 7" here]

DISKPART> select disk 7

Disk 7 is now the selected disk.

DISKPART> list part

  Partition ###  Type              Size     Offset
  -------------  ----------------  -------  -------
  [[There will be a list of partitions here]]
DISKPART>
```

Then, for every partition listed, delete it:
```
DISKPART> select part 1

Partition 1 is now the selected partition.

DISKPART> delete part
```

After doing this, you can format the disk using `Disk Manager`.  However, as stated previously, because `Disk Manager` appears to treat USB drives as different for some reason, the documentation is incorrect and there is no option to Initialize these types of disks.

**Comment by cyberherman** [comment]
I have the same problem as the original post. I cant format or initialize my new SSD. 

I have typed all the commands in the syntax above, but whenever I get to the "list part" part it says "There are no partitions on this disk to show".

**Comment by RAJU2529** [comment]
boot the windows into  recovery  environment and get in to command prompt

type  diskpart
list disk   ( note the  disk numbers  like 0  ,1  )  say 1 is  for HDD
select disk 1
clean     (  clean commands  will wipe  all datas in disk )
convert gpt
exit exit
boot as normal , then create  new  partitions  using disk management

**Comment by johnerbes** [comment]
This is an added note to the procedure xobs outlined above.

If you are going to initialize an OLD disk (like one that you pulled out of your laptop and put into a USB drive enclosure when you upgraded to an SSD) many of the partitions on the old drive are going to be protected.

If you use diskpart.exe to initialize your repurposed USB drive, you will need to use the command  "del part override" to remove the selected partitions (one at a time) that are protected.
