### ISSUE TITLE
Readability

### ISSUE THREAD

**Issue by IanJDan** [MicrosoftDocs/windowsserverdocs#880]
Image authn_lsa_architecture_client.gif against dark theme is difficult to read.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c25e4bc4-d343-331d-d364-216e1665c439
* Version Independent ID: 6b9327a6-ac27-6360-969d-a93c692f8976
* Content: [Credentials Processes in Windows Authentication](https://docs.microsoft.com/en-us/windows-server/security/windows-authentication/credentials-processes-in-windows-authentication#feedback)
* Content Source: [WindowsServerDocs/security/windows-authentication/credentials-processes-in-windows-authentication.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/security/windows-authentication/credentials-processes-in-windows-authentication.md)
* Service: **unspecified**
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by Saggiehaim** [comment]
![authn_lsa_architecture_client](https://user-images.githubusercontent.com/12769001/54075265-f9d47c00-42a5-11e9-97d9-014b0ef954e2.png)

I added a white background so it will be easier to read with dark theme :) just need to change the image.
