### ISSUE TITLE
Case sensitive

### ISSUE THREAD

**Issue by panos415** [MicrosoftDocs/windowsserverdocs#882]
The keyword is case-sensitive but is incorrect throughout the documents.  The correct sensitivity it PrintUIEntry.  For example:
       rundll32 printui.dll,PrintUIEntry /?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa36b7f2-97e8-83eb-8c24-b7c3c415a7fc
* Version Independent ID: 8333d236-2c07-624b-1628-d35d0a385bf7
* Content: [rundll32 printui.dll,printUIEntry](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/rundll32-printui)
* Content Source: [WindowsServerDocs/administration/windows-commands/rundll32-printui.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/rundll32-printui.md)
* Service: **unspecified**
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by lizap** [comment]
Thanks! I've fixed the casing in the source and will update the published article.
