### ISSUE TITLE
.Net core?

### ISSUE THREAD

**Issue by chrisjau** [MicrosoftDocs/windowsserverdocs#887]
Can we please have a .net core adaptation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 731a5db9-3e53-0379-edcb-4c338dad0240
* Version Independent ID: 683ef16d-2cbd-7d01-a7da-842f4afb1d8f
* Content: [Build a single page web application using OAuth and ADAL.JS with AD FS 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/single-page-application-with-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/Single-Page-Application-with-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/Single-Page-Application-with-AD-FS.md)
* Service: **unspecified**
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by lizap** [comment]
Hi, Chris - you're probably going to find more traction for your request over in the User Voice forum for Windows Server: https://windowsserver.uservoice.com/forums/295047-general-feedback 

Thanks!
