### ISSUE TITLE
Replacement for SCOM S2D Management Pack?

### ISSUE THREAD

**Issue by ThomasRapidis** [MicrosoftDocs/windowsserverdocs#889]
I am operating SCOM and te S2D Management Pack for the sole reason of its ability to provide alert EMAILS when there is an S2D health alert condition. Can WAC accomplish this for me? An email alert? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7be9997d-7c5d-1f44-c243-b232fdbdf8df
* Version Independent ID: 88564bdf-d24a-c298-2d0c-371b0d33288c
* Content: [Manage Hyper-Converged Infrastructure with Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/use/manage-hyper-converged)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/use/manage-hyper-converged.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/use/manage-hyper-converged.md)
* Service: **unspecified**
* Product: **windows-server-threshold**
* GitHub Login: @daniellee-msft
* Microsoft Alias: **jol**

**Comment by jwwool** [comment]
Windows Admin Center does not send email alerts. Feel free to add your vote to the request [here](https://windowsserver.uservoice.com/forums/295071/suggestions/33594202)

**Comment by ThomasRapidis** [comment]
Added the vote. Judging by the angry replies on that user voice thread it will never happen.

Too bad. S2D / HCI is brilliant, but the requirement to operate the deranged system that is SCOM just in order to be able to receive an email, when my storage has a problem is insane.
