### ISSUE TITLE
* ID: bfc1fd4d-4e12-880f-20ab-85bc1436059a

### ISSUE THREAD

**Issue by Diablo86** [MicrosoftDocs/windowsserverdocs#891]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfc1fd4d-4e12-880f-20ab-85bc1436059a
* Version Independent ID: 25d6854b-8a38-eec1-b638-b150b1fbf8fa
* Content: [Windows Server Software-Defined Datacenter](https://docs.microsoft.com/en-us/windows-server/sddc)
* Content Source: [WindowsServerDocs/sddc.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/sddc.md)
* Service: **unspecified**
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by lizap** [comment]
Hi, @Diablo86 - Did you have a comment to share? If so, please reopen this issue and add your issue/comment. Thanks!
