### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by sanfonck** [MicrosoftDocs/windowsserverdocs#892]
there's a typo in Mirosoft.Sme.PowerShell under "Apply role-based access control to a single machine"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6273f49-fe06-5a18-80e3-863bd3a0cf4e
* Version Independent ID: 4ed5bf3d-0c2a-a80e-5bd9-0e858dd8749b
* Content: [Configuring user access control and permissions](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/configure/user-access-control)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/configure/user-access-control.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/configure/user-access-control.md)
* Service: **unspecified**
* Product: **windows-server-threshold**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by jwwool** [comment]
Thanks for opening the issue! This typo will be corrected in the doc updates that are planned for next week.
