### ISSUE TITLE
EMET related content should be removed

### ISSUE THREAD

**Issue by mahanpathak** [MicrosoftDocs/windowsserverdocs#901]
This article still have reference to EMET. Please provide details of implementation with WDEG.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd5878a8-a83e-e75d-ddae-59edc04e7138
* Version Independent ID: 0f0cbbe4-20da-3abe-1a7c-effc608d8cca
* Content: [Privileged Access Workstations](https://docs.microsoft.com/en-us/windows-server/identity/securing-privileged-access/privileged-access-workstations)
* Content Source: [WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md)
* Service: **unspecified**
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Resolved in PR #1087 (commit https://github.com/MicrosoftDocs/windowsserverdocs/commit/33290f4e051bfcc6b8232fc40da680982295d18b).

**Comment by illfated** [comment]
#please-close
