### ISSUE TITLE
Windows Server 2016: Logical processor limit (MAX) discrepancies and errors

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/windowsserverdocs#902]
This issue is created by @lagriz from https://github.com/MicrosoftDocs/feedback/issues/403
🛑 IMPORTANT: You can get your feedback addressed faster if you use the comment section for the article in which you encountered a problem.
Link to article:
https://www.microsoft.com/en-us/cloud-platform/windows-server-comparison
https://docs.microsoft.com/en-us/windows-server/get-started/2016-edition-comparison
Problem:
The Windows Server 2016 processor limits do not match - and do not correspond to the tested values -
-On one site we can find this table :
Feature description | Windows Server 2012/2012 R2 Standard and Datacenter | Windows Server 2016 Standard and Datacenter
Physical (host) logical processor support| Up to 320 LPs | Up to 512 LPs
On another site, we can read
Maximum number of 64-bit sockets | 64 | 64
Maximum number of cores | unlimited | unlimited
Our testing shows that Windows Server 2016 - supports up to 640 logical processors ( this corresponds to Intel cores with Hyper Threading) above this value, logical processors are not reported.
To my knowledge also 2016 is limited to 20 NUMA nodes, that would be 20 sockets, right?
Is there a way to have matching limits?
I need to update our white papers and would like to reference Microsoft pages, but I find it hard for the reader to understand the right number.
Thank you.
Regards.
Laurence Grizaud

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5acee3a-b458-172f-127d-07e0406bd46f
* Version Independent ID: a11c4876-e20a-4307-b1b7-38f414a4532c
* Content: [Windows Server 2016 Products and Editions](https://docs.microsoft.com/en-us/windows-server/get-started/2016-edition-comparison)
* Content Source: [WindowsServerDocs/get-started/2016-Edition-Comparison.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/2016-Edition-Comparison.md)
* Service: **unspecified**
* Product: **windows-server-threshold**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
Thanks for bringing this to our attention. I own the second topic, which as been reviewed by our technical SMEs many times; however, I shall certainly run this by them again. I don't know who owns the first topic, but will find out and get the two topics in phase. As for your testing, of course I will ask our SMEs about this, but keep in mind that what we quote is what is *supported* by license and technical support--so it's possible you could find a limit that is possible but not officially supported.

**Comment by lizap** [comment]
@jaimeo - can you take a look at this? Thanks!

**Comment by lagriz** [comment]
Hi,

Thanks, this is exactly why I am checking, but on the other hand, our engineering is working with your engineering.

Regards.
Laurence
