### ISSUE TITLE
Redirect HTTP requests to HTTPS

### ISSUE THREAD

**Issue by rmilojkovic** [MicrosoftDocs/windowsserverdocs#907]
Is it possible to set redirection of HTTP request to HTTPS, directly in WAC configuration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe84fb4b-3420-bc1e-6a1d-b64ecc56fc5e
* Version Independent ID: f089767e-4613-d595-a0ee-0dab012724a1
* Content: [Install Windows Admin Center](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/deploy/install)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/deploy/install.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/deploy/install.md)
* Service: **unspecified**
* Product: **windows-server-threshold**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by jwwool** [comment]
Not in the web UI.

To update this option post-install, run the MSI and choose the **change** option.
