### ISSUE TITLE
missing powershell commands for managing Windows Admin Center

### ISSUE THREAD

**Issue by CharlPels** [MicrosoftDocs/windowsserverdocs#908]
WAC is a very nice tool to work with.
The only thing I am missing are tools to manage the WAC it self on Windows Core for example.

Changing certificate for a new one using powershell and a command to update the server lists dynamically.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 136cbcd9-a631-587d-3b48-dded76d9e6c9
* Version Independent ID: d1ac1f79-89de-97d8-aec7-1c6a78212910
* Content: [Windows Admin Center Frequently Asked Questions](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/understand/faq)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/understand/faq.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/understand/faq.md)
* Service: **unspecified**
* Product: **windows-server-threshold**
* GitHub Login: @nwashburn-ms
* Microsoft Alias: **niwashbu**

**Comment by IngridAtMicrosoft** [comment]
#please-close
