### ISSUE TITLE
Cor

### ISSUE THREAD

**Issue by araceli-45** [MicrosoftDocs/windowsserverdocs#920]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fc1255a-fc24-26b8-cf22-049b6f3d4988
* Version Independent ID: 3468d97b-4e31-f264-cbe8-3e87805b0eb9
* Content: [Configure a Server Core installation of Windows Server with Sconfig.cmd](https://docs.microsoft.com/en-us/windows-server/get-started/sconfig-on-ws2016)
* Content Source: [WindowsServerDocs/get-started/Sconfig-on-WS2016.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/Sconfig-on-WS2016.md)
* Product: **windows-server-threshold**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
@araceli-45 did you have a particular request or suggestion for this topic?

**Comment by lizap** [comment]
Hi, @araceli-45 - please reopen the issue with more details of your comment. Thanks!
