### ISSUE TITLE
Get Started with Windows Server link broken

### ISSUE THREAD

**Issue by MarcLaf** [MicrosoftDocs/windowsserverdocs#927]
The link in the Note to get started with Windows Server doesn't work. https://docs.microsoft.com/windows-server/get-started/server-basic
The proper link is https://docs.microsoft.com/windows-server/get-started/server-basics (with an s on the end)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9709554a-64bd-51ae-5701-10de1b721284
* Version Independent ID: 9d7dc454-8587-2fd3-4986-e0ff660f7d10
* Content: [Windows Server Semi-Annual Channel overview](https://docs.microsoft.com/en-us/windows-server/get-started/semi-annual-channel-overview)
* Content Source: [WindowsServerDocs/get-started/semi-annual-channel-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/semi-annual-channel-overview.md)
* Product: **windows-server-threshold**
* GitHub Login: @jaimeo

**Comment by lizap** [comment]
Thanks for catching this - we'll get it fixed.
