### ISSUE TITLE
Error running set-PAWOUDelegation.ps1

### ISSUE THREAD

**Issue by armandomedrano** [MicrosoftDocs/windowsserverdocs#937]
Hello, 
Im getting this error running Set-PAWOUDelegation.ps1

Set-ACL : Access is denied
At C:\PAWContent 02052018\Set-PAWOUDelegation.ps1:195 char:1
+ Set-ACL -ACLObject $configContainerACL -Path ("AD:\"+($configCN));
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (CN=Configuration,DC=corp,DC=com:String) [Set-Acl], UnauthorizedAccess
   Exception
    + FullyQualifiedErrorId : ADProvider:SetSecurityDescriptor:AccessDenied,Microsoft.PowerShell.Commands.SetAclComman
   d

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd5878a8-a83e-e75d-ddae-59edc04e7138
* Version Independent ID: 0f0cbbe4-20da-3abe-1a7c-effc608d8cca
* Content: [Privileged Access Workstations](https://docs.microsoft.com/en-us/windows-server/identity/securing-privileged-access/privileged-access-workstations)
* Content Source: [WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/securing-privileged-access/privileged-access-workstations.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by philready** [comment]
Hi, did you resolve this issue? I am having the same trouble
