### ISSUE TITLE
Managing SSL/TLS Protocols and Cipher Suites for AD FS

### ISSUE THREAD

**Issue by kcirtapcapital** [MicrosoftDocs/windowsserverdocs#939]
This is the best guide to eliminating the use of older TLS protocols.
Title should be change to "Managing SSL/TLS Protocols and Cipher Suites" and server as the root of TLS documents. As this applies to a scope of products outside AD FS. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ae56e74-1346-a822-2800-70db6d365376
* Version Independent ID: ccf848e1-5276-1f3f-73e8-036dba9c66a7
* Content: [Managing SSL/TLS Protocols and Cipher Suites for AD FS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/manage-ssl-protocols-in-ad-fs#enabling-or-disabling-additional-cipher-suites)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/Manage-SSL-Protocols-in-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/Manage-SSL-Protocols-in-AD-FS.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by IngridAtMicrosoft** [comment]
#please-close

**Comment by PRMerger6** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: ingridatmicrosoft 
gh issue comment 929 -b ingridatmicrosoft
