### ISSUE TITLE
Link to documentation is incorrect

### ISSUE THREAD

**Issue by karlheinz-hildebrandt** [MicrosoftDocs/windowsserverdocs#945]
The link 
https://go.microsoft.com/fwlink/?LinkId=201803
is incorrect. It leads to
https://www.msn.com/de-de/?ocid=NEFLS000
Please correct it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3203ec37-ee2d-b426-7754-99a4460e4395
* Version Independent ID: a6d39095-89a5-4ab6-cc56-a424bd14806c
* Content: [regini](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/regini)
* Content Source: [WindowsServerDocs/administration/windows-commands/regini.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/regini.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by lizap** [comment]
We'll update the article to link to this KB instead: https://support.microsoft.com/en-us/help/264584/how-to-change-registry-values-or-permissions-from-a-command-line-or-a

Thanks

**Comment by lizap** [comment]
Thanks for the feedback - I've updated the article.
