### ISSUE TITLE
SMB server tuning example

### ISSUE THREAD

**Issue by dmorsephd** [MicrosoftDocs/windowsserverdocs#947]
Are the values given for the parameters listed in the SMB server tuning example expressed in decimal or hexadecimal?  I am assuming decimal, since they are not annotated 0x64.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81b40e8b-6840-30f3-ff6a-e178160f6ef5
* Version Independent ID: 8a9f683d-cc6a-0182-713f-c0a789335f65
* Content: [Performance Tuning for SMB File Servers](https://docs.microsoft.com/en-us/windows-server/administration/performance-tuning/role/file-server/smb-file-server#smb-server-tuning-example)
* Content Source: [WindowsServerDocs/administration/performance-tuning/role/file-server/smb-file-server.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/performance-tuning/role/file-server/smb-file-server.md)
* Product: **windows-server-threshold**
* GitHub Login: @phstee
* Microsoft Alias: **NedPyle; Danlo; DKruse**

**Comment by lizap** [comment]
You're correct - decimal.
