### ISSUE TITLE
Windows 2016 Server Core License conversion

### ISSUE THREAD

**Issue by Jctechbr** [MicrosoftDocs/windowsserverdocs#948]
Is there anyway to convert the "evaluation" datacenter server core to a full "no eval"datacenter server core?

Thank you very much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adf594c8-5d55-8bfe-99b8-e1a1f91081fd
* Version Independent ID: 32ba9200-79f5-671d-bcc5-650540e8e94f
* Content: [Upgrade and Conversion Options for Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/get-started/supported-upgrade-paths)
* Content Source: [WindowsServerDocs/get-started/Supported-Upgrade-Paths.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/get-started/Supported-Upgrade-Paths.md)
* Product: **windows-server-threshold**
* GitHub Login: @jaimeo
* Microsoft Alias: **jaimeo**

**Comment by jaimeo** [comment]
Yes; as described in the topic (https://docs.microsoft.com/en-us/windows-server/get-started/supported-upgrade-paths#converting-a-current-evaluation-version-to-a-current-retail-version), you can convert evaluation versions of Standard to either retail Standard or retail Datacenter and evaluation versions of Datacenter to retail Datacenter. If the starting (eval) installation is a Server Core installation, the resulting retail installation will also be a Server Core installation.

**Comment by mjashraf** [comment]
I already have WinSvrSTDCore licenses, I need to confirm that is it possible to convert them into Data Center? If yes then how many Standard licenses can be converted to or eligible for conversion?

**Comment by robcmc** [comment]
No. You cannot upgrade from Server Core Eval to Servercore. Running Get-TargetEditions states that this edition cannot be upgraded. Even with the last refreshed 2016 Eval ISO the problem persists despite the article linked above.
