### ISSUE TITLE
Missing steps to create certs

### ISSUE THREAD

**Issue by ianc911** [MicrosoftDocs/windowsserverdocs#949]
Under "Deploy certificates and VPN configuration script to the clients", point 1 (Create and publish the VPN certificate, and enable the auto-enrollment Group Policy object (GPO)) ends with:
"For the steps to configure certificates and auto-enrollment, see ."
Please furnish the missing references.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08e5da80-a94a-845d-6c6c-e04c08611a97
* Version Independent ID: 8a807734-2131-5372-161f-9162b2369a0f
* Content: [Migration from DirectAccess to Always On VPN](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/da-always-on-vpn-migration/da-always-on-migration-deploy)
* Content Source: [WindowsServerDocs/remote/remote-access/da-always-on-vpn-migration/da-always-on-migration-deploy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/da-always-on-vpn-migration/da-always-on-migration-deploy.md)
* Product: **windows-server**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@ianc911, Thanks for catching.  I've updated it.
