### ISSUE TITLE
Split brain DNS?

### ISSUE THREAD

**Issue by ianc911** [MicrosoftDocs/windowsserverdocs#952]
"Other DNS designs, such as split-brain DNS ... are also possible, but the configuration for these environments is beyond the scope of this guide."

C'mon, split brain is the most commonly used configuration out there by far. How about adding some value by including it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35733357-c761-adb9-add1-7eca45af8153
* Version Independent ID: 75eba511-c85e-42ea-d6e2-fd88a767132a
* Content: [Remote Access Always On VPN Deployment Overview](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-overview)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-overview.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/always-on-vpn-deploy-overview.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
Thank you for your feedback. The engineering team is reviewing the content to add more information around DNS.

**Comment by msuedfel** [comment]
And do you know when the Engineering Team will leave any comment on this Topic? The last entry for this Topic has been entered three months ago…...

**Comment by shortpatti** [comment]
hi @msuedfel, the content is in progress and being reviewed by the engineering teams.  Please be patient.

**Comment by shortpatti** [comment]
I've added a link to the 'Deploying Split-Brain DNS" topic and it will be published later today.

**Comment by ianc911** [comment]
Thanks Patti!
