### ISSUE TITLE
Incorrect MMC specified in step 17

### ISSUE THREAD

**Issue by ianc911** [MicrosoftDocs/windowsserverdocs#953]
Step 17 specifies the Routing and Remote Access MMC, when this change should be made in the NPS MMC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53ca42af-1e8b-7f41-a3b9-de1cb20d895d
* Version Independent ID: dc054edd-c916-28ba-78d2-ee7b10635201
* Content: [Configure the Remote Access Server for Always On VPN](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-ras)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-ras.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-ras.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by shortpatti** [comment]
@ianc911, Another good catch.  Thank you.    I'll have it corrected soon.
