### ISSUE TITLE
401 Unauthroized

### ISSUE THREAD

**Issue by jnfarmer** [MicrosoftDocs/windowsserverdocs#955]
I'm getting the error below when trying to register the Azure AD gateway

Invoke-WebRequest : The remote server returned an error: (401) Unauthorized.
At C:\users\jfarmer.server\downloads\WindowsAdminCenterAzureConnectScript-1804-4\New-AadApp.ps1:262 char:21
+ ... $response = Invoke-WebRequest -Uri $url -Body $body -Method Put -UseD ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Failed to register the application with the gateway
At C:\users\jfarmer.server\downloads\WindowsAdminCenterAzureConnectScript-1804-4\New-AadApp.ps1:270 char:5
+     throw $err
+     ~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to regis...ith the gateway:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to register the application with the gateway

I've tried the CNAME suggestion in the other article but still had no luck with that either.

**Comment by jnfarmer** [comment]
This was meant to be for Windows Admin Center, don't know why it dumped in to the entire server area. Not sure if it can be moved?

**Comment by lizap** [comment]
I've changed the labeling, which should get the attention of the WAC team.
