### ISSUE TITLE
Excluding wildcard directories?

### ISSUE THREAD

**Issue by yecril71pl** [MicrosoftDocs/windowsserverdocs#956]
The option

    /XD PACKAGES\*SUSE*

gives me 

> ERROR : Invalid Parameter #&zwnj;4 : "PACKAGES\\\*SUSE\*"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af94ad3b-6603-2b26-1010-073fb2c07c2a
* Version Independent ID: 09fd75d0-8624-5cfd-5122-b40ba50055f9
* Content: [robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by yecril71pl** [comment]
It seems that /XD accepts absolute path names only.

**Comment by turgayyoo** [comment]
not true. I had a vaguely similar problem. I wanted to skip all files and directories below e.g. c:\users\username\AppData 
This only works if you do it like this: robocopy \somepath\someorigindir \somepath\sometargetdir /XD "specific_folder_name_no path" /s /mir
So /XD does indeed work without path information 
Alas, I do not know if the wildcards would work. One might try to find out. I won't.
