### ISSUE TITLE
RPT Not Required, Use WebAPI Inside Application Group Instead

### ISSUE THREAD

**Issue by notoriousedd** [MicrosoftDocs/windowsserverdocs#957]
Creating a Relying Party Trust is not required.  You can Create a Web API entry in the same Application Group.  Also, it would help to include instructions on how to add the resource parameter to the OIDC sample app.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e04047c8-df0d-d752-afc1-0daa314e5d75
* Version Independent ID: 93cac62e-204f-b523-3751-51e420672555
* Content: [Customize claims to be emitted in id_token when using OpenID Connect or OAuth with AD FS 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/custom-id-tokens-in-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/Custom-Id-Tokens-in-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/Custom-Id-Tokens-in-AD-FS.md)
* Product: **windows-server-threshold**
* GitHub Login: @anandyadavMSFT
* Microsoft Alias: **billmath**

**Comment by stephanosio** [comment]
When you use ASP.NET OWIN OpenID Connect external login (Microsoft.Owin.Security.OpenIdConnect), you can use "Server application accessing a web API" application group type. Just make sure that the Resource parameter is set to the CallbackPath/RedirectUri when you do app.UseOpenIdConnectAuthentication.
