### ISSUE TITLE
Link to running ADPREP links to old content

### ISSUE THREAD

**Issue by jrjenk** [MicrosoftDocs/windowsserverdocs#960]
In the section Adprep and Domainprep (https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/upgrade-domain-controllers#adprep-and-domainprep)

Your link for information about running ADPREP.EXE links to the old documentation (https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd464018(v=ws.10)), which does not appear to Mention Server 2016

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e32288e6-1a81-01da-51bf-d1564049a28a
* Version Independent ID: 7388c199-ee35-63fa-deda-e3f6399de3ee
* Content: [Upgrade Domain Controllers to Windows Server 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/upgrade-domain-controllers)
* Content Source: [WindowsServerDocs/identity/ad-ds/deploy/upgrade-domain-controllers.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/deploy/upgrade-domain-controllers.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by MicrosoftGuyJFlo** [comment]
Info is still valid.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close

**Comment by jrjenk** [comment]
My point was that if it is valid why does it have a huge disclaimer at the top of the page saying it isn't being updated and having a link to a "recommended version" that then takes you to a content area and not an updated version of the content.

**Comment by MicrosoftGuyJFlo** [comment]
Understood. Unfortunately AD DS content lives intermingled amongst Windows Server content for previous versions. Windows Server content is no longer being updated for old versions but as updates are made to AD DS content we will bring that forward and update it.

**Comment by jrjenk** [comment]
So is there a better place to open a ticket for "Missing Article" then?  One for how to run ADPREP in the current windows server environment?

**Comment by MicrosoftGuyJFlo** [comment]
Runs the same way as the article describes. Schema versions are listed in the doc below. 

https://docs.microsoft.com/windows-server/identity/ad-ds/deploy/domain-wide-updates

**Comment by jrjenk** [comment]
I am pretty sure that the current ADPREP article is missing some of the command line arguments that ADPrep supports when run from the Windows Server 2016 Installation media, but I don't have access to my test environment to verify right now.

From memory I think it was the fact that the article as-is mentions a requirement to run the adprep command from Domain Controllers holding specific FSMO roles, but I thought the Server 2016 version of adprep modified that requirement.

As you also pointed out with your reference to the Schema documentation, the existing article is also missing a link to the changes made by adprep for Windows Server 2016.

**Comment by MicrosoftGuyJFlo** [comment]
I will add it to the backlog to get it updated but there is no timeline I can give you on when that will get completed. Wanted to give you info so that you could move forward.

**Comment by jrjenk** [comment]
Oh I appreciate any and all feedback. I really just wanted to make note of it in case it hadn't been already mentioned, I didn't mean to be such a nag.  Thank you for all the work you do on keeping the documentation vetted and updated.

**Comment by JeoffB** [comment]
Why would you add this comment.. Server 2012 and 2012 R2 were also 64-bit only? 
"Domain controllers that run 64-bit versions of Windows Server 2012 or Windows Server 2012 R2 can be upgraded to Windows Server 2016. Only 64-bit version upgrades are supported because Windows Server 2016 only comes in a 64-bit version."

**Comment by MicrosoftGuyJFlo** [comment]
@JeoffB I don't think that is related to this issue but your feedback is valid. That was part of the original doc before I inherited it. If you would like to propose a change feel free to hit the edit button and propose what you think should be changed. Otherwise I will add it to my backlog and try to get to it as soon as possible.
