### ISSUE TITLE
Web API - Passing ID Token Instead of Access Token

### ISSUE THREAD

**Issue by davewoodward** [MicrosoftDocs/windowsserverdocs#964]
The opening of this article instructs the reader to use the ID_Token that issued to the SPA to a Web API for authorization purposes.  This is contrary to my understanding of how this scenario should play out.  Instead, I would expect the SPA to obtain a separate access token that would be passed to the Web API for authorization purposes.  I would appreciate your feedback on this..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 731a5db9-3e53-0379-edcb-4c338dad0240
* Version Independent ID: 683ef16d-2cbd-7d01-a7da-842f4afb1d8f
* Content: [Build a single page web application using OAuth and ADAL.JS with AD FS 2016](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/single-page-application-with-ad-fs)
* Content Source: [WindowsServerDocs/identity/ad-fs/development/Single-Page-Application-with-AD-FS.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/development/Single-Page-Application-with-AD-FS.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by davewoodward** [comment]
Sorry, I see this is a duplicate of #828 (not answered yet).

**Comment by lizap** [comment]
Thanks, Dave - let me see if I can get some answers for you (and for the opener of #828 too).

**Comment by lizap** [comment]
Hi, Dave - the team's updated the introduction to the graphic to be more clear about what's happening. If you still have questions, please reopen this issue and we'll keep working on it. Thanks!

**Comment by amouly** [comment]
This still doesn't makes sense. The graphic still uses the ID Token to access the API layer.
