### ISSUE TITLE
Azure App Proxy and RDS UDP Traffic

### ISSUE THREAD

**Issue by jasonlevandoski** [MicrosoftDocs/windowsserverdocs#966]
Will Azure App Proxy ever support RDS UDP Traffic?  That is a large disadvantage especially with all of new new GPU/RemoteFX evolutions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 428e9e07-ca35-27d2-e63a-92930cec0118
* Version Independent ID: 9a452a85-9afa-42d5-f319-bf1c4c50d01d
* Content: [Remote Desktop Services architecture](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/desktop-hosting-logical-architecture)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/Desktop-hosting-logical-architecture.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/Desktop-hosting-logical-architecture.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by lizap** [comment]
Let me take your question back to the RD team. I'll be back with what I learn. Thanks!

**Comment by lizap** [comment]
Hi - since this is actually a request for Azure App Proxy, your best option is to submit this ask as feedback for that service. You can do that here: https://feedback.azure.com/forums/169401-azure-active-directory
