### ISSUE TITLE
Clearly written documentation

### ISSUE THREAD

**Issue by SGL3** [MicrosoftDocs/windowsserverdocs#969]
This SSD documentation is clearly written and addresses the main questions we have around fault tolerance and the requirements for the different levels.  Very good job in communicating important information in a compact manner.  Great job.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03523046-9f0e-6f95-0855-54cf664aa38d
* Version Independent ID: c6a6c74d-31e2-dd38-ff48-a04e2ba8f902
* Content: [Fault tolerance and storage efficiency in Storage Spaces Direct](https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/storage-spaces-fault-tolerance#feedback)
* Content Source: [WindowsServerDocs/storage/storage-spaces/Storage-Spaces-Fault-Tolerance.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/storage/storage-spaces/Storage-Spaces-Fault-Tolerance.md)
* Product: **windows-server-threshold**
* GitHub Login: @cosmosdarwin
* Microsoft Alias: **cosmosdarwin**

**Comment by lizap** [comment]
Thanks for sharing this feedback! Flagging @cosmosdarwin to make sure he sees it.
