### ISSUE TITLE
Protocol not specificed

### ISSUE THREAD

**Issue by ianc911** [MicrosoftDocs/windowsserverdocs#971]
Under 'Configure the edge firewall' -&gt; "... you must open your firewall rules to allow ports 500 and 4500"

TCP, UDP? Please specify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbeab4b7-f8d6-59ee-49df-fc4646fcbaea
* Version Independent ID: 1fceb417-3029-7b89-f583-560c05a68ad2
* Content: [Configure DNS and Firewall Settings](https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-dns-firewall)
* Content Source: [WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-dns-firewall.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-dns-firewall.md)
* Product: **windows-server-threshold**
* GitHub Login: @shortpatti
* Microsoft Alias: **pashort**

**Comment by ianc911** [comment]
My bad - upon further inspection, UDP is specified earlier in the section. Please disregard.

**Comment by shortpatti** [comment]
Closing.
