### ISSUE TITLE
Backup-ADFS command does not prompt for credentials when ran as domain admin

### ISSUE THREAD

**Issue by sandfred** [MicrosoftDocs/windowsserverdocs#976]
But if the command is ran with a domain service account/local admin that has ADFS/DKM permissions, the prompt always occurs.  This is problematic when attempting to execute the backup via scheduled task with credentials specified in the task.  The backup cmdlet still prompts for credentials.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a58b49ca-ae39-132e-adbd-6766a8019a89
* Version Independent ID: fdf31266-bc9e-8880-0073-00cf1cad2897
* Content: [AD FS Rapid Restore Tool](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/ad-fs-rapid-restore-tool)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/AD-FS-Rapid-Restore-Tool.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/AD-FS-Rapid-Restore-Tool.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
As discussed in #1831 , there is a suggested script/PS code example in that ticket:

```PowerShell
import-module 'C:\Program Files (x86)\ADFS Rapid Recreation Tool\ADFSRapidRecreationTool.dll'

$Password = "This-is-the-Key-of-your-storage-account-and-can-be-found-in-your-Azure-Storage-Container-under-Access-Keys"
$pass = ConvertTo-SecureString -AsPlainText $Password -Force
$Username = "adfsbackups" #Name of your storage account
$cred = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $Username,$pass

Backup-ADFS -StorageType "Azure" -AzureConnectionCredentials $cred -AzureStorageContainer "adfsbackups" -EncryptionPassword "password" -BackupComment "ADFS Backup"
```
Not sure if it is practical or useful to you, but I thought it would be nice to reference it.
