### ISSUE TITLE
fsutil setCaseSensitiveInfo

### ISSUE THREAD

**Issue by SoftWatchAdmin** [MicrosoftDocs/windowsserverdocs#977]
I tried running this command through powershell as admin: 
fsutil.exe file setCaseSensitiveInfo &lt;path&gt; enable
but I keep getting an error:
The request is not supported.
I am running on an NTFS file system, as administrator.
Is this not supported on Windows 10 as specified in the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94c21d61-d08c-250a-097b-6e5794525107
* Version Independent ID: 121ab330-a917-d5f2-d9f3-e317d95bc584
* Content: [Fsutil](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil)
* Content Source: [WindowsServerDocs/administration/windows-commands/fsutil.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/fsutil.md)
* Product: **windows-server-threshold**
* GitHub Login: @toklima
* Microsoft Alias: **toklima**

**Comment by coreyp-at-msft** [comment]
Hi @SoftWatchAdmin ,

Thanks for bringing this to our attention. We'll update this article ASAP with the following information:

You have to enable **Windows Subsystem for Linux** before this will work. 

Run the following command as Administrator in PowerShell to enable this optional feature: 

`Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`

You'll be prompted to restart your machine once it's installed. After your computer restarts, you'll be able to run Fsutil as Administrator in a command prompt window as you expected, .

Here are a couple articles that explain in more detail:

https://blogs.msdn.microsoft.com/commandline/2018/02/28/per-directory-case-sensitivity-and-wsl/
https://docs.microsoft.com/en-us/windows/wsl/install-win10

Thanks,
Corey

**Comment by lizap** [comment]
Thanks for the feedback. I've updated the article with the info about the Subsystem for Linux requirement that @coreyp-at-msft mentioned above. Please let us know if there's other things we need to update. Thanks!

**Comment by Micheal-Yan** [comment]
【fsutil file setCaseSensitiveInfo】This command can only open the case of the current file, and its sub-files are still case-insensitive. This caused me to fail to pass the case-sensitive check when compiling the Android source code on WSL. How to solve this problem?

**Comment by Micheal-Yan** [comment]
> 【fsutil file setCaseSensitiveInfo】This command can only open the case of the current file, and its sub-files are still case-insensitive. This caused me to fail to pass the case-sensitive check when compiling the Android source code on WSL. How to solve this problem?@coreyp-at-msft

**Comment by theking2** [comment]
Be ware though that enabling Linux Subsystem potentially prevents the Desktop (explorer) from loading. This happened in 1903 (19013.1). Disabling Microsoft-Windows-Subsystem-Linux feature rendered a working desktop.

**Comment by DonFrazier** [comment]
Is there any chance `The request is not supported.` could be modified to provide actionable information?  For example 

The request is not supported.  See http://aka.ms/setCaseSensitiveInfo for details on how to enable this feature for your device.

**Comment by s1291** [comment]
Hello,
This is confusing, At the top of the article, Windows 7 is also mentioned. But this requires WSL which is available on Windows 10 Only.
Thanks.

**Comment by illfated** [comment]
Please post in issue ticket #1880 or open a new ticket if you find that there are issues in need of improvement, but still are left unchanged or unimproved.
