### ISSUE TITLE
/SEC option

### ISSUE THREAD

**Issue by CodaAmok** [MicrosoftDocs/windowsserverdocs#981]
I thought /SEC was the same as /copy:DATS and not just /copy:DAT ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af94ad3b-6603-2b26-1010-073fb2c07c2a
* Version Independent ID: 09fd75d0-8624-5cfd-5122-b40ba50055f9
* Content: [robocopy](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy#BKMK_remarks)
* Content Source: [WindowsServerDocs/administration/windows-commands/robocopy.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-commands/robocopy.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by GarryMartin** [comment]
Agreed - /SEC is equivalent of /copy:DATS

**Comment by lizap** [comment]
Yep, you're correct. We've fixed the source file - you'll see it later on 6/18/18. Thanks!
