### ISSUE TITLE
Additional step if implementing on AD FS Farm with WID

### ISSUE THREAD

**Issue by peternield** [MicrosoftDocs/windowsserverdocs#985]
I believe there is an extra step required when configuring the MFA adaptor in an AD FS farm which uses WID for the AD FS databases.

In this case. an exception will occur when executing the New-AdfsAzureMfaTenantCertificate cmdlet on a secondary AD FS server To get past this, it is necessary to configure the AD FS server as the primary server for the farm (using Set-AdfsSyncProperties), execute the New-AdfsAzureMfaTenantCertificate cmdlet, and then optionally re-configure the AD FS server as secondary server.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae96cfcf-0a50-7e13-30c8-43e3730e184f
* Version Independent ID: 9d8ed7b7-eec6-1b95-40b8-24a13361f66d
* Content: [Configure AD FS 2016 and Azure MFA](https://docs.microsoft.com/en-nz/windows-server/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa#configure-the-ad-fs-servers)
* Content Source: [WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-fs/operations/configure-ad-fs-and-azure-mfa.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by zjorz** [comment]
I have a different experience. I have been able to do what you mention without first making the ADFS server a primary ADFS server
