### ISSUE TITLE
Upstream and downstream version supported configuration doc

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windowsserverdocs#987]
Need a documentation on if higher version WSUS (e.g Winodws 2016) can be a downstream to a lower version WSUS (e.g Windows 2012 R2) or not.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa4be2a-4045-4135-353a-ed882ada9402
* Version Independent ID: c43f3896-9f9b-2754-9b5d-d73f9650592b
* Content: [Plan Your WSUS Deployment](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/plan/plan-your-wsus-deployment#BKMK_1.1)
* Content Source: [WindowsServerDocs/administration/windows-server-update-services/plan/plan-your-wsus-deployment.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/administration/windows-server-update-services/plan/plan-your-wsus-deployment.md)
* Product: **windows-server-threshold**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

**Comment by illfated** [comment]
Notice that the user account no longer exists (@ghost is a replacement for deleted GitHub accounts).

**Comment by illfated** [comment]
#please-close
