### ISSUE TITLE
Download PDF for the documentation branch I am on, not the entire tree?

### ISSUE THREAD

**Issue by jschadow** [MicrosoftDocs/windowsserverdocs#993]
Can one, for example, download a PDF for https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/best-practices-for-securing-active-directory branch and not the entire https://docs.microsoft.com/en-us/windows-server/identity/identity-and-access.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dad9ef73-50b0-04cb-3e0e-bd100579d4ef
* Version Independent ID: 7dec62ab-7d4a-f7fa-8627-9f92c82bf49f
* Content: [Best Practices for Securing Active Directory](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/best-practices-for-securing-active-directory)
* Content Source: [WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Best-Practices-for-Securing-Active-Directory.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/identity/ad-ds/plan/security-best-practices/Best-Practices-for-Securing-Active-Directory.md)
* Product: **windows-server-threshold**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by illfated** [comment]
You probably need to run a curl script on a machine with JS or similar to be able to concatenate the PDF into only those pages you need.

My solution would be to edit the full PDF in Adobe Acrobat Pro and remove all pages I don't need (or extract pages to a new document, if that is faster).

**Comment by illfated** [comment]
BTW, I have seen someone making scripts to do what you ask, but that involves editing a script and running the script on a machine with JS or similar scripting language support.

**Comment by illfated** [comment]
Search the web for parts of the URL, note in particular the directory name `opbuildpdf` and use that in your searches. Maybe reddit has a solution for you, or even here on GitHub.

**Comment by illfated** [comment]
#please-close
