### ISSUE TITLE
we have new deployment for RSA application around 150 user but there are issue in two RDS broker server which run through the powershell script to Maintain the session 

### ISSUE THREAD

**Issue by biren1234** [MicrosoftDocs/windowsserverdocs#997]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3281b55b-4df2-b23e-0119-d5bf39569886
* Version Independent ID: e89bcd00-f480-2a32-e533-29f376369f56
* Content: [Remote Desktop Services - Build anywhere](https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-plan-build-anywhere)
* Content Source: [WindowsServerDocs/remote/remote-desktop-services/rds-plan-build-anywhere.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/remote/remote-desktop-services/rds-plan-build-anywhere.md)
* Product: **windows-server-threshold**
* GitHub Login: @lizap
* Microsoft Alias: **elizapo**

**Comment by lizap** [comment]
Hi - Are you running into problems trying to set up your environment?

**Comment by lizap** [comment]
Sorry to hear that you've run into trouble. Unfortunately we don't have the resources to offer troubleshooting through the docs. Instead, your best option is to start a new thread on the [Remote Desktop forum](https://social.technet.microsoft.com/Forums/windowsserver/en-US/home?forum=winserverTS). Thanks!
