### ISSUE TITLE
Unable to connecto the the remote server error when running New-AADApp.PS1

### ISSUE THREAD

**Issue by poynter2** [MicrosoftDocs/windowsserverdocs#999]
AAD Application already exists for SME-https://localhost. Application not created
AadClientId: xxxxxxx
AadTenantId: xxxxxxx
Invoke-WebRequest : Unable to connect to the remote server
At E:\Downloads\New-AadApp.ps1:262 char:21
+ ... $response = Invoke-WebRequest -Uri $url -Body $body -Method Put -UseD ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : System.Net.WebException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Failed to register the application with the gateway
At E:\Downloads\New-AadApp.ps1:270 char:5
+     throw $err
+     ~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to regis...ith the gateway:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to register the application with the gateway

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae730e6-5e1e-1ae6-5cbd-9eb6d271690b
* Version Independent ID: a79daa4b-e8fb-0ed4-867c-430b3c61ceea
* Content: [Configuring Azure Integration](https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/configure/azure-integration)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/configure/azure-integration.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/master/WindowsServerDocs/manage/windows-admin-center/configure/azure-integration.md)
* Product: **windows-server-threshold**
* GitHub Login: @Haley-Rowland
* Microsoft Alias: **harowl**

**Comment by Haley-Rowland** [comment]
Are you running the script from the gateway server itself? If not, you'll need to specify the gateway endpoint parameter as the fully-qualified domain name of the gateway server.

**Comment by PHITDept** [comment]
What is the gateway server?

**Comment by desmondkung** [comment]
I'm getting "The client and server cannot communicate, because they do not possess a common algorithm" when I try to register my WAC with Azure. Server Core 2016 with TLS 1.0 and 1.1 switched off.

**Comment by jwwool** [comment]
Windows Admin Center now performs the Azure registration in the product, without the need for the external script.
